### ISSUE TITLE
Email Forwarders: Why a password?

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1001]
This issue has existed since a long time ago in VestaCP, very minor, just curious if anyone has looked into it.

When creating a new email account that has a "Forward to" address AND the "Discard all fowarded mail" option checked, why is a password still required?

This new email account will actually be a pure forwarder, so it should not require a password.  It's an overcomplicated UI and process for a simple forwarder.

I am not looking to pile more work on the Hestia team, just asking the question to better understand and maybe start the discussion if no one has talked about it yet.

**Comment by ghost** [comment]
Hi @vestacp-user,

Thanks for pointing this out. We're aware of this annoyance in the UI, and the process of adding forwarders will be re-worked in a future release alongside other improvements that we have in store for the mail stack.

**Comment by ioannidesalex** [comment]
The way it currently works is that a mailbox is created even for forwarding only. Only adding an alias/catchall doesn’t create a mailbox.

Of course there is much room for improvement.

**Comment by ScIT-Raphael** [comment]
Probaly related with the black hole request: #1454

**Comment by jaapmarcus** [comment]
Quick note:
1001 should be simple, just clone the mail account creation screen strip the unused elements and set a random password on the mailbox automatically

**Comment by ScIT-Raphael** [comment]
Fixed
