### ISSUE TITLE
WebUI: No forced logout on inactivity after timeout delay, security risk

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1002]
The legacy VestaCP and HestiaCP WebUI both never had a forced logout on inactivity (or I never found the setting).  This is convinient, but a security risk considering that the control panel is the second most powerfull access point to the server (after ssh root/sudo/su-).  

All visible Hestia browser windows might be closed, but if the admin's browser process stays opened and the admin never forced the logout, anyone with authorized or unauthorized access to the computer can gain full control of the server by opening the HestiaCP url in the currently running browser process.

In general, these types of web-based admin control panels by default have server-side forced logouts on inactivity (default timeouts that are quite short eg. 15mins) and the admins can increase the timeout or deactivate it if they are willing to assume the security risks.

**Comment by jaapmarcus** [comment]
We should also considering optional check to send an email when a new login has been detected / allow less frequent checks for the 2FA code. Nobody wants to enter 9 times a day the 2FA code. 

Maybe in combination with https://fingerprintjs.com/open-source/  to ensure no hacking

**Comment by vestacp-user** [comment]
Generally, a login of 2FA or password has the same risk related to the length of time the session remains opened, because once a session is open, it is full access regardless of 2FA or not.   It's not a questions of the login process, but how log the session lasts.  

On the topic of other ways to secure the account.  Simultaneous logins should not be permitted, but I realized that there is only one user admin and per account.  So maybe an indicator of how many simultaneous sessions are currently open, and eventually a list of the current sessions and past logins/sessions.  Kind of like Gmail bottom right of screen.

**Comment by ghost** [comment]
We've discussed this internally @vestacp-user and the approach of showing the number of logins along with the ability to force sessions to be logged out and configuring a time out value will be implemented but no time frame on delivery. If you're able to submit a PR for this please feel free to do so, it would be much appreciated.

**Comment by jaapmarcus** [comment]
Multiple logins are not allowed. I agree we need to decrease it to xx minutes. 

How ever currently you need to enter every time  when you login a 2fa. We should be able with fingerprintjs + cookies to allow not enter 2fa each time. Same as google does...

**Comment by jaapmarcus** [comment]
My last commit should fix the first issue

We have decided to set the default value to 60 min. How ever this will become changeable via Web UI later on

```
<?php
$_SESSION['INACTIVE_SESSION_TIMEOUT'] * 60 + $_SESSION['LAST_ACTIVITY'] < time();
?>
```

**Comment by vestacp-user** [comment]
I can close, or leave open for upcoming improvements, as the project wishes.  

The bigest risk is covered by having some sort of inactivity timeout, as the worst case scenario was the hidden and perpertual login session of an open browser process.

**Comment by jaapmarcus** [comment]
Just leave it open until it has been merged.

Added a few additional items

1. Log of all successful login events 
2. When user do log out the active session is set to inactive
3. Web ui to view the logs + delete them if needed 

Things still to be done adjustments to server "edit" to increase / descrease session length + If you want to allow skip 2Fa for next login upto 24 hours 

For extra security we use Browser finger print to give with 99,5% unique id to separate the browsers. 

Together with a User token + password_hash I don't see any issues with it.


Maybe in the future Send warning via email when new login is detected. 

Way to stop to have 2 sessions open at same time.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/0fdfc846cd3b538e9a8bae4f360e04f0aab606ba/web/inc/main.php#L77-L90

Pull request has been merged :) Issue can be closed
