### ISSUE TITLE
WebUI: Bread crumbs trail would be usefull in certain cases where the context is lost

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1003]
In some cases, the current navigation context is completely lost and the user cannot determine what is being created or edited.  A bread crumb trail just below the main button banner "WEB DNS MAIL DB CRON BACKUPS" would be usefull

For example:
myuser -> DNS -> mydomain.com -> DNS Records

Let's say the user only Type "A" records with IP addresses and he wants to delete a record, it is impossible to visually confirm on the UI that he is deleting a record from mydomain.com.  So if the user has been clicking around alot and has many domain and different windows opened, there is a high risk of deleting the wrong entries.

A stable bread crumb trail would the user always know current context and avoid being lost and making mistakes.  In some situations, the context is dangerously missing, in others, it would be just "nice to have"

Some other examples that would be nice to have if there was one global coherent bread crumb trail for the application. 
admin -> server -> configure
admin -> user2 -> DNS -> domain2.com -> DNS Records -> Edit -> 12 - mail2.domain2.com
user42 -> Mail -> domain38.com -> Mail Accounts -> Edit -> joe@domain38.com

**Comment by johnnyq** [comment]
@vestacp-user This is a very good design idea. A few users I host with hestiaCP  tell me they get lost in the UI. Bringing breadcrumbs to the table is a great idea!!

**Comment by ScIT-Raphael** [comment]
We currently close this issue - with the existing system we do not want to implement breadcrumbs. This may be integrated, if we find enough time to do a whole rewrite of the interface.
