### ISSUE TITLE
WebUI: User records list wrapping on small screen is offset with header

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1004]
When reducing the screen width, the user list records wrapping is offset with the header.  The header line starts wrapping back under the "Name" header to the (far left).  The record lines start wrapping back under the "Login as" icon (center left).  Thus the records are wrapping offset with the header.

The user list could also benefit from having a tooltip on the circles with numbers in them.  The header icons already have tooltips, so it should be easy to reuse for the records below (eg "Web Domains", "Email Domains", etc...)

Other list wrappings and screens get broken as the width is reduced, but the user screen seems to be the widest one and breaks with a 50% side docking of the window on a 1080p screen, that that is quite a common usage pattern. 

Might be browser specific, this test was in Firefox.

For anyone reading and dealing with this problem, my preferred and fastest workaround is a scroll out in the browser (Ctrl+MouseWheelScrollOut), fast and efficient and easy to adjust back when moving to other screens when the text is unreadable (Ctrl+MouseWheelScrollIn)

**Comment by ScIT-Raphael** [comment]
fixed with: https://github.com/hestiacp/hestiacp/pull/1010
