### ISSUE TITLE
Installer scripts assume openssh-server already installed

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1012]
Name says it all. While installing to a test container I noticed the installer scripts don't install openssh-server and just assumes it is already present which produces errors if this is not the case. It would be best if this was installed alongside the other essential packages.

**Comment by kpapad904** [comment]
Thanks for pointing out openssh-server, I had also noticed the issue with default container images. Btw AppArmor is another package we may consider adding to the installer scripts.

Currently HestiaCP installer just adds a one-line rule for Bind9, if it detects AA. I'm looking forward for HestiaCP to use AppArmor more in the future, starting with PHP-FPM and Exim4.

**Comment by Lupul** [comment]
Which Hestia version and OS are you testing?, current release v1.2.0 already installs ssh on debian 9 and 10 commit:https://github.com/hestiacp/hestiacp/commit/1091b5e685fa512b61102f4cc95f4ee86d7e39b1
On Ubuntu ssh is installed by default on all tested images (iso or lxc containers)

**Comment by vestacp-user** [comment]
This is true, a Debian 10 Buster minimal install does not have the sshd server.  Packages `ssh` (client) and `openssh-server` (server aka `sshd`) are different.  If you want to ensure that the ssh server is installed, apt install openssh-server should be added to the install script.  It doesn't hurt anything, apt will do the required checks, updates, installs automatically.

I can provide a pull if desired.

https://packages.debian.org/buster/ssh
https://packages.debian.org/buster/openssh-server

Here is the output on an up to date Hestia 1.2.0 install, to demonstrate that there is no harm in adding this to the install script, even if the target system already has it installed:
```
apt install openssh-server -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssh-server is already the newest version (1:7.9p1-10+deb10u2).
openssh-server set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by ghost** [comment]
@vestacp-user The following commit should fix this: https://github.com/hestiacp/hestiacp/commit/ed63c3c7ba3fe1393032fb4a971d7d47c0891d3c
