### ISSUE TITLE
WebUI: Quota denominators are not displayed in Main Navigation Ribbon

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1015]
WebUI: The quota denominators are not displayed in Main Navigation Ribbon (WEB DNS MAIL DB CRON BACKUPS), regardless if the quota is infinite or a specified number.  The denominators are always displayed as 0.  Additionally, the Backup does not have a denominator, of course, the count will often be at the max of the quota, but not always, for example, when an new user is created, when the quota is changed or when backups are deleted.  For coherence of the UI, the backup should have the same count/quota display.

**Comment by ghost** [comment]
The information displayed is slightly different from Vesta's. For example, under Web where it states "Domains: 1 / 0", the second value is the number of domains which are suspended and _not_ the package/quota limit.

We may consider changing this behavior in the future when we begin to move away from the legacy front end which the UI is still based upon.

**Comment by vestacp-user** [comment]
I would suggest avoiding using a division (/) symbol and denominator for anything other than a quota (or something similar) as that is the natural meaning of the symbol.  Alternatives for suspended being anything but division (/) symbol.  Additionally, a suspended account usually counts against the quota, that is should naturally be part of the nominator if that display pattern is kept.

Original VestaCP UI did not use the division (/) symbol.

If the choice is no quota display, then it would be preferable NOT to use the division (/) denominator symbol and maybe just parentheses or other symbol (dash, other brackets, etc..)

Eg: Quota=100, Count=4, Suspended=1, Active=3
My preference being the first or second.
4/100 (1)
4 (1)
(3+1)/100
3 - 1
4 - 1

**Comment by ghost** [comment]
The first option (**Count/Quota (Suspended)**) makes the most sense to me. I'll make the necessary changes and we'll ship with the next release.

**Comment by jaapmarcus** [comment]
Fixed and released
