### ISSUE TITLE
WebUI: "Edit Mail Account" is missing inifite symbol UI element in the quota field

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1017]
WebUI: "Edit Mail Account" is missing inifite symbol UI element in the quota field.  Thus it is currently impossible to set a quota to a mail account that was created with an infinite quota or inversely, switch a fixed quota to infinite.

For reference, the infinite UI element works correctly on the "Add Mail Account" screen.

**Comment by jaapmarcus** [comment]
Will fix it during the changes regarding password fields.
