### ISSUE TITLE
WebUI: Cannot delete suspended "Web Domain", "Email Domain", "Mail Account", etc...

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1018]
A suspended domain cannot be deleted, it gives the error "Error: web example.com is suspended"

Since you guys are on fire fixing bugs, here is an old legacy bug that is minor.  It is a normal pattern to suspend an account and then delete it or unsuspended it, so the only permitted actions on a suspended web domain should be unsuspend and delete.

Unsuspending (re-activating) should not be required to delete a record.

The same bug exists for "Email Domain", "Mail Account", etc...  I don't know if this is by design or just a bug in the common functionality.

**Comment by ghost** [comment]
Thanks for the report @vestacp-user. I agree that the legacy behavior doesn't make much sense here, we'll remove the unnecessary step of having to unsuspend an item before allowing its deletion.
