### ISSUE TITLE
WebUI: Host SSL, confusing. v-add-letsencrypt-host Error: Web domain exist / doesn't exist

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1019]
HestiaCP warns the user to create "Web Domains" under regular user, not admin.  If the host "Web Domain" is created under a regular user (not admin as instructed), and then the script v-add-letsencrypt-host is used, the following errors occur:

```
# v-add-letsencrypt-host 
Error: Web domain example.com exist
Error: web domain example.com doesn't exist
```

The error seems to occur because the script is (partially) expecting the host domain to be under the admin user.  This makes sense, but is not exactly clear.  I think it would be better if the v-add-letsencrypt-host would impose using a regular user, thus respecting HestiaCPs request to only have "Web Domains" under regular users.

I then used `v-change-domain-owner example.com admin` to bring the domain under the admin user, but it gave some errors and lost the "Web Domain".   (real IPs replaced by 123...)

```
# v-change-domain-owner example.com admin
Moving example.com from example to admin, please wait...
[*] Moving web domain...
[*] Moving DNS zone and records...
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
[*] Moving mail domain and accounts...
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
# v-change-domain-owner example.com admin
ERROR: example.com is already owned by admin.
```

Fortunately, the `v-rebuild-web-domain` worked, to make it visible under admin, but still gives errors.  The error seems to be coming from:

```
# v-rebuild-dns-domain admin example.com
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
```

This is actually two issues in one issue, please advise if you want them seperated.  I don't need a solution, just documenting the error for the team and other users that might get this.

**Comment by vestacp-user** [comment]
It might have also been because of a loopback nameserver configuration, I am not sure, I haven't retested the complete process again.

**Comment by vestacp-user** [comment]
Also, previously, there was a WebUI box to choose the SSL cert for the host.  I searched and can't find it anymore.  There is Server -> Configure -> SSL, but it only offers Self-Signed or Copy/Paste.  

The host SSL seems to have come by magic from the admin's (first?) "Web Domain" or because I ran `v-add-letsencrypt-host` maybe?  I deleted everything a recreated it following the errors and the admin's "Web Domain" (also the hostname), seems to have been re-setup automatically by magic.  But if the link is the hostname, it should have done it regardless of which account it is under (admin or regular user).  Seems more flaky and magical then before.  Maybe I should RTFM... lol

**Comment by ghost** [comment]
In the future, please create separate issue reports for different bugs/issues so that we can properly track them.

The intended design (and partially inherited from Vesta at the time Hestia was forked) is that the web domain corresponding to the hostname which is created by default under the admin account exists to facilitate the Let's Encrypt implementation for hostname. More work needs to be done in this area to ensure the host web domain always exists and that it should not be deleted except by the system.

The Let's Encrypt SSL checkbox you are referring to under Configure Server has never existed in HestiaCP as we haven't implemented the front end UI for this yet.

**Comment by vestacp-user** [comment]
Sometimes, it is not so simple to have the final desired domain completely available and functionition at the time of the initial system install, particularly when the domain is hosted elsewhere and it will be transitioned at the end of transferring all other domains hosted under it's account on another server.  Additionally, there is no reason why the hostname webdomain would be less risky to have operating under the admin account.  Actually, in some cases, the hostname domain might be the main account under which all of the web coding, ftp access, ssh access, etc (all other risky things). will occur, thus going against the security warning of HestiaCP.

If possible, as the initial Hestia warning, I would suggest having absolutely nothing under the admin account and that even the server would be setup with a temporary hostname (temphostname), the web domain would be setup under a standard user awesome (awesomedomain.com) and then when everything is functioning correctly with dns, ssl, etc. the hostname and reverse dns, domain records, etc. are switched to awesome / awesomedomain.com.  This would also permit changed in the future and be more flexible.  I saw code in the host stuff that was hardcoded for "admin", this will eventually cause some users to get irreversably stuck during the lifecycle of a Hestia server.

**Comment by vestacp-user** [comment]
`v-change-domain-owner` and `v-rebuild-web-domain` errors transferred to the new issue #1024

**Comment by ScIT-Raphael** [comment]
fixed: https://github.com/hestiacp/hestiacp/pull/1037#merged-event
