### ISSUE TITLE
Error 503 on all websites after upgrade to HestiaCP 1.2.1

### ISSUE THREAD

**Issue by Spheerys** [hestiacp/hestiacp#1020]
===

### In a few words, please describe the issue that you're experiencing:
All hosted websites give a Error 503 Site temporarily unavailable

### What steps did you take when the issue occured? 
The error occurs suddenly, but I had notification about HestaiaCP upgarde to 1.2.1

### Expected behavior:
Every sites are online

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.1 just upgraded

**Comment by Spheerys** [comment]
I finaly had to reselect the correct personalized backend default.
I don't know why it was set on the default one for now.
Maybe I have forgoten to chosse the correct one during VestaCP to HestiaCP migration, but it is strange because the websites worked after migration...

**Comment by ScIT-Raphael** [comment]
Just reopen the issue, we will check and fix the issues.

**Comment by jaapmarcus** [comment]
Don't know it is released

https://forum.hestiacp.com/t/sudden-site-errors-corrected-by-rebuild/1392
