### ISSUE TITLE
after upgrade 1.2.0 -> 1.2.1 webui hestiacp stopped working (error 500)

### ISSUE THREAD

**Issue by marco-acorte** [hestiacp/hestiacp#1021]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

![immagine](https://user-images.githubusercontent.com/6375935/88639238-d7224d80-d0bc-11ea-897c-b06b6b2dffe6.png)

===

### In a few words, please describe the issue that you're experiencing:
When i Try to access webui on 8083 the server return erro 500 (see img).

### What steps did you take when the issue occured? 
1. Attempted to open webui control panel and received an Internal Server Error.

### Expected behavior:
the web login should appear.

### Operating system:
Ubuntu 16.04.6 LTS (GNU/Linux 2.6.32-042stab141.3 x86_64)

### Hestia Control Panel version:
1.2.1 

### Additional notes:
v-list-sys-info

```
HOSTNAME          OS      VER    ARCH    HESTIA  RELEASE  UPTIME  LA
--------          --      ---    ----    ------  -------  ------  --
13404.s.t4vps.eu  Ubuntu  16.04  x86_64  1.2.1   release  33      0.00
```
 v-list-sys-hestia-updates

```
PKG           VER      ARCH   UPDT  DATE
---           ---      ----   ----  ----
hestia        1.2.1    amd64  yes   2020-07-28
hestia-php    7.4.6    amd64  yes   2020-06-30
hestia-nginx  1.17.10  amd64  yes   2020-06-29
```

**Comment by jaapmarcus** [comment]
Please run **systemctl status hestia**

After that try to look in /var/log/hestia/nginx-error.log

**Comment by marco-acorte** [comment]
mmmm libzip.so.4 missing
```
● hestia.service - LSB: starts the hestia control panel
   Loaded: loaded (/etc/init.d/hestia; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-07-28 10:58:35 EEST; 49min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 417 ExecStart=/etc/init.d/hestia start (code=exited, status=127)
   CGroup: /system.slice/hestia.service
           ├─536 nginx: master process /usr/local/hestia/nginx/sbin/hestia-ngin
           └─542 nginx: worker process

Jul 28 10:58:35 domain.example hestia[417]:  * Starting hestia-nginx hestia-nginx
Jul 28 10:58:35 domain.example systemd[1]: Starting LSB: starts the hestia control panel...
Jul 28 10:58:35 domain.example hestia[417]:    ...done.
Jul 28 10:58:35 domain.example hestia[417]:  * Starting hestia-php hestia-php
Jul 28 10:58:35 domain.example hestia[417]: /usr/local/hestia/php/sbin/hestia-php: error while loading 
                         shared libraries: libzip.so.4: cannot open shared object file: No such file or directory
Jul 28 10:58:35 domain.example systemd[1]: hestia.service: Control process exited, code=exited status=127
Jul 28 10:58:35 domain.example systemd[1]: Failed to start LSB: starts the hestia control panel.
Jul 28 10:58:35 domain.example systemd[1]: hestia.service: Unit entered failed state.
Jul 28 10:58:35 domain.example systemd[1]: hestia.service: Failed with result 'exit-code'.
```

**Comment by jaapmarcus** [comment]
Yes, don't know why but it was already a requirement for 1.2.0 

Please run 
apt-get-install libzip4

**Comment by marco-acorte** [comment]
installed libzip4 ... and now it'a all OK. very strange issue :| . thanks for collaboration @jaapmarcus

**Comment by jaapmarcus** [comment]
Oke will close the issue than...
