### ISSUE TITLE
[CLI] v-rebuild-user error 

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1022]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Error message when running the command 
v-rebuild-user [user]

root@cp:/usr/local/hestia/data/templates/web/php-fpm# v-rebuild-user [user]
/usr/local/hestia/func/rebuild.sh: line 531: [: too many arguments

### What steps did you take when the issue occured? 
Attempt to rebuild user

### Expected behavior:
No error message 

### Operating system:
20.04 LTS

### Hestia Control Panel version:
1.2.1 Release

### Additional notes:
https://github.com/hestiacp/hestiacp/blob/0727ef9d5c6a7ff61caab8f38b2d86e62c50a631/func/rebuild.sh#L531-L535

**Comment by Lupul** [comment]
Thanks @jaapmarcus , will take a look

**Comment by jaapmarcus** [comment]
Issue in mailhello.conf

**Comment by Lupul** [comment]
Still a bug, v-rebuild-user should handle this case
