### ISSUE TITLE
v-rebuild-dns-domain Error when changing from standard user to admin and possible loopback dns configuration

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1024]
Following the process described in #1019, `v-change-domain-owner` and `v-rebuild-web-domain` give the following errors.  Possibly because the domain is being changed from a regular user to admin user, possibly because of a loopback dns configuration.

Continuing from issue #1019: ...I then used v-change-domain-owner example.com admin to bring the domain under the admin user, but it gave some errors and lost the "Web Domain". (real IPs replaced by 123...)
```
# v-change-domain-owner example.com admin
Moving example.com from example to admin, please wait...
[*] Moving web domain...
[*] Moving DNS zone and records...
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
[*] Moving mail domain and accounts...
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
# v-change-domain-owner example.com admin
ERROR: example.com is already owned by admin.
```
Fortunately, the v-rebuild-web-domain worked, to make it visible under admin, but still gives errors. The error seems to be coming from:
```
# v-rebuild-dns-domain admin example.com
/usr/local/hestia/func/domain.sh: eval: line 463: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 464: syntax error: unexpected end of file
/usr/local/hestia/func/domain.sh: line 463: 123.123.123.123=123.123.123.123: command not found
```

Even though the web domain did re-appear under admin after rebuilding, it was still somewhat broken, some dns parts remained under the standard user account and there were some dns resolving problems.

I ultimately deleted everything and recreated it under admin, corrected the loopback dns entries and it worked correctly.

**Comment by jaapmarcus** [comment]
Just check could this issue be fixed with https://github.com/hestiacp/hestiacp/pull/1037#merged-event ?

**Comment by ScIT-Raphael** [comment]
fixed: https://github.com/hestiacp/hestiacp/pull/1037
