### ISSUE TITLE
Improve version detection in installer

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1025]
WebUI shows two different versions, incoherent:
"Hestia Control Panel: v1.2.0" at /list/server/
"Hestia Control Panel 1.2.1" at /list/updates/

Remains even after an update from WebUI, Restart Server from WebUI and also a "reboot now" from the commant line.

This was a fresh install of v1.2.0 that should have been updated to v1.2.1

**Comment by ghost** [comment]
What does $HESTIA/conf/hestia.conf contain for VERSION?

**Comment by vestacp-user** [comment]
If I am the only one with this, don't worry about it, I don't need it fixed, just making sure it isn't a general install or update problem.

```
# v-update-sys-hestia hestia
# v-update-sys-hestia-all

# apt update
...                                                       
Hit:5 https://apt.hestiacp.com buster InRelease  
...                                                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

# apt install hestia
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hestia is already the newest version (1.2.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# cat /usr/local/hestia/conf/hestia.conf | grep VERSION
VERSION='1.2.0'
```

**Comment by ghost** [comment]
Hmm, and if you run `apt install --reinstall hestia`?

**Comment by vestacp-user** [comment]
Yes, `apt install --reinstall hestia` seems to have clobbered several files, and both the WebUI and the hestia.conf say 1.2.1

However, nothing seems broken, everything works right after that reinstall.

**Comment by kpapad904** [comment]
I can't replicate this issue on 2 different HestiaCP installations (both on Debian 10.4): system1 was updated from 1.2.0 release to 1.2.1 release last Monday, whereas system2 was a "test" setup that was first updated to 1.2.1-beta and then to release with --reinstall.

Both HestiaCP systems display the correct version (1.2.1) everywhere.

**Comment by vestacp-user** [comment]
Ok, no problem, closing, reopen if someone else gets this.

**Comment by vestacp-user** [comment]
@kristankenney When exactly was the 1.2.1 release changed on github and also when was it changed in the repo packages?  What is the release process/sequence? Maybe I was extremely unlucky and installed v1.2.0 during the release process.  I assume that the repos and github are not updated atomically, thus could cause this?

**Comment by vestacp-user** [comment]
Actually, I will re-open, because looking at the code, the release version is written from the install script, but the actual version of hestia comes from the apt.hestiacp.com repo.  So if the repo was updated first but I downloaded the github install with v1.2.0 which installed the v1.2.1 from repo and then github, v1.2.1 would be installed from repo, but the version would be clobbered by the install script.

Install script, this will clobber the version during install during a release change
Line 26
`HESTIA_INSTALL_VER='1.2.1'` 
Line 1124
`echo "VERSION='${HESTIA_INSTALL_VER}'" >> $HESTIA/conf/hestia.conf`

There are no easy general fixes to this since there is code and config duplication, the only real solution is to have one source for everything.  Temporarily, the script could be changed to impose the apt install of a specific version of hestia* from the hestia repo and keep two versions of hestia* in the repo during transition.

**Comment by ghost** [comment]
There is a chance that you may have gotten extremely unlucky during the install process when 1.2.1 was released and the branches/apt repositories aligned. The installer is generally designed to detect a version mismatch at runtime and abort if the installer and apt don't line up. However if you happened to get past the version check _before_ the final apt update that could be it.

Further changes are being done in the installer and how we handle versioning; I'll leave this open until I merge the fix over so we can track.

**Comment by vestacp-user** [comment]
@kristankenney it's not as robust as you think, the version is checked on github, which can be out of sync with the apt.hestiacp.com for longer than you think.

Line 417:
`release_branch_ver=$(curl -s https://raw.githubusercontent.com/hestiacp/hestiacp/release/src/deb/hestia/control`

**Comment by jaapmarcus** [comment]
True but the time between merge and release was about 10 minutes. This was the time we needed to build the 1.2.1 packages and update apt.hestiacp.com

**Comment by ghost** [comment]
@vestacp-user The changes made in commit https://github.com/hestiacp/hestiacp/commit/1d0c4f298d391f7f779baa32edf431886f6e5da1 should correct this behavior.

**Comment by vestacp-user** [comment]
> @vestacp-user The changes made in commit [1d0c4f2](https://github.com/hestiacp/hestiacp/commit/1d0c4f298d391f7f779baa32edf431886f6e5da1) should correct this behavior.

Ok, perfect, that will help reduce some exceptions, including transparent forward caching proxies such as squid, apt-cacher, approx, etc. that automatically cache repo contents.  There might also be apt.hestiacp.com repo mirrors (using debmirror, rsync, etc) that are significantly delayed.  In my case the repo was ahead, but in these cases, the repo would be a version behind

However, even with this change, the current setup is not safe for the long term and much higher adoption rates.  There are certainly others out-of-sync scenarios hiding in the current install design that includes duplicated code and config.  Important to keep in mind for the long-term design of the install procedure.

Examples of thesoftware that provides the above mentioned caching of repos:
https://packages.debian.org/buster/squid
https://packages.debian.org/buster/debmirror
https://packages.debian.org/buster/apt-cacher-ng
https://packages.debian.org/buster/approx
https://packages.debian.org/buster/apt-cacher

**Comment by vestacp-user** [comment]
> I'll leave this open until I merge the fix over so we can track.

Sorry for closing, re-opening so you can close it as per your earlier message @kristankenney
