### ISSUE TITLE
Error on file manager page

### ISSUE THREAD

**Issue by version2** [hestiacp/hestiacp#1026]
Updated from version 1.1.1 to 1.2.1
Try to open file manager but get an error
Deleting the file manager and adding it again didn't help

![изображение](https://user-images.githubusercontent.com/57840254/88726316-c5c55980-d12d-11ea-8a6c-a2d82d813c52.png)

**Comment by Lupul** [comment]
Can you open a sftp session on that account?
`sftp -P 22 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1`

**Comment by version2** [comment]
> 
> 
> Can you open a sftp session on that account?
> `sftp -P 22 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1`

Yes, but not on this port, I use a different port for ssh

**Comment by Lupul** [comment]
In this case do a logout/login on the control panel (webUI), the sftp port is auto-detected on login and saved trough-out the session

**Comment by version2** [comment]
> 
> 
> Can you open a sftp session on that account?
> `sftp -P 22 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1`

Sorry, I made a mistake, on other port I also have an error

ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 13333: Broken pipe
Connection closed



> 
> 
> In this case do a logout/login on the control panel, the sftp is auto-detected on login and saved trough-out the session

I tried logout /login on the control panel and I tried restarting the VPS, it didn't help

**Comment by Lupul** [comment]
If the sftp command doesn't work, the file manger won't work either, you need to figure out that first.

**Comment by version2** [comment]
> 
> 
> If the sftp command doesn't work, the file manger won't work either, you need to figure out that first.

The connection is now working, but I see a warning - No such file or directory
but the file exists

ls /home/admin/.ssh/
authorized_keys  hst-filemanager-key

sftp -P 13333 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1
Warning: Identity file /home/admin/.ssh/hst-filemanager-key not accessible: No such file or directory.
admin@127.0.0.1's password:
Connected to 127.0.0.1.
sftp>

**Comment by jaapmarcus** [comment]
Who is the owner of the hst-filemanager-key it should be admin:admin

Also common issues please read:
https://docs.hestiacp.com/admin_docs/filemanager.html

**Comment by Lupul** [comment]
`.ssh/hst-filemanager-key` gets created when you open the file manager url `:8083/fm/` and automaticaly removed after some time

**Comment by version2** [comment]
> 
> 
> Who is the owner of the hst-filemanager-key it should be admin:admin
> 
> Also common issues please read:
> https://docs.hestiacp.com/admin_docs/filemanager.html


change port to 22

delete file manager

reboot

add file manager

/etc/ssh/sshd_config has a parameter:

//override default of no subsystems
Subsystem sftp internal-sftp

owner of the hst-filemanager-key it admin:admin,  permissions 0600

enter to file manager

![изображение](https://user-images.githubusercontent.com/57840254/88783311-e5409e80-d18e-11ea-8a49-23054242093e.png)



owner of the hst-filemanager-key it admin:admin,  permissions 0600

**Comment by jaapmarcus** [comment]
Try after you visited the filemanager page the sftp command @Lupul posted this should should work

If so there is a issue at our side if not there is some issues with the sftp config

**Comment by version2** [comment]
> 
> 
> Try after you visited the filemanager page the sftp command @Lupul posted this should should work
> 
> If so there is a issue at our side if not there is some issues with the sftp config

do this
connection is established

 sftp -P 12222 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1
admin@127.0.0.1's password:
Connected to 127.0.0.1.
sftp>

**Comment by jaapmarcus** [comment]
Is it still asking for a password ? Shouldn’t be required by default

**Comment by version2** [comment]
> 
> 
> Is it still asking for a password ? Shouldn’t be required by default

yes, it ask

**Comment by Lupul** [comment]
To summarize the troubleshouting steps when filemanager is not working:
- if you are using a non default (22) sftp port: logout and log back into hestia webui
- if that doesn't work, then your ssh config is preventing sftp login you need to troubleshot that on your own.
Test with : `sftp -P 22 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1`
- Note:  `.ssh/hst-filemanager-key` will get deleted automatically after some time, re-create it by opening the filemanager page
(or trough the cli: `v-add-user-sftp-key admin 60`)

**Comment by Lupul** [comment]
@version2  did you made any progress on this?

**Comment by version2** [comment]
> 
> 
> @version2 did you made any progress on this?

no, I made all the recommendations and suggestions to fix it, but the error remained. Port changed to 22, connection via "sftp-P 22 -i /home/admin/. ssh/hst-filemanager-key admin@127.0.0.1" - works, the file". ssh/hst-filemanager-key " is created and automatically deleted, its rights are admin:admin. logout, login, and restarting don't help

**Comment by Lupul** [comment]
Can you create a new user and test there?

**Comment by version2** [comment]
> 
> 
> Can you create a new user and test there?

Yes, I did, for a new user - it works!

**Comment by jaapmarcus** [comment]
@version2 still issues? 

If so please reopen again with some additional information.
