### ISSUE TITLE
WebUI: Do not automatically send credentials via email to user

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1027]
When a new account is created, the WebUI automatically copies the email address ito the "Email login credentials to:" field.  This is certainly convinient for most, but is also a security risk (bad opsec).  The issue here is not that there is an option to email the credentials, the issue is that emailing the credential is **ALWAYS IMPOSED** by the HestiaCP WebUI and the admin must always explictly remove the email address from the "Email login credentials to:" and there is no kill switch for this automatic copying.  

Not only are email insecure and largely communicated as clear text, they also often get picked up into large search databases such as gmail, outlook, office365, yahoo, etc which are then used for targetted marketing, which also means that many many people have working acess to this information.

This is an issue for the password itself, but also for attempts to hide the control panel (different port, different url, ipv6, tor, cloudfare, private lan, etc.) which gets completely compromised by simply one email sent out, sniffed as clear text and/or indexed in gmail/outlook/office365/yahoo, etc. 

I am simply proposing to not automatically copy the email address to the "Email login credentials to:" field, or at least have a global option or kill switch for this.

**Comment by jaapmarcus** [comment]
Fixed with #1034

It will change the default behaviour to not copy unless checkbox is checked then it functions as before.
