### ISSUE TITLE
Crontab: Automatically eliminated the crontab set through the terminal, after the last update.

### ISSUE THREAD

**Issue by drego85** [hestiacp/hestiacp#1028]
Hi Team,
yesterday I updated Hestia to the latest version (1.2.1) and I lost all the crontab that I had set manually from the terminal (via $crontab -e).

I'm currently proceeding with a restore and configure them via the graphical interface, I believe it is correct to notify your users.

===

### Operating system:
Ubuntu 18.04 TLS

### Hestia Control Panel version:
1.2.1

**Comment by jaapmarcus** [comment]
Just checked the code 

https://github.com/hestiacp/hestiacp/blob/f0eaa05a8628097167725af9daf14a93d2bddc38/func/main.sh#L566-L586

It seems that for the user accounts the crontab are reset. 

The crontab was reset for a use account or also the root user. We are discussion if we need to change this behavouir / should improve it.

**Comment by jaapmarcus** [comment]
Changes to be made:

1. Backup all cronjobs in the backup folder (as all other config)
2. Improve system syncing manual crontab (via crontab -e) and via Web UI.

Last point is still open how and what would be the best method.

**Comment by jaapmarcus** [comment]
Step 1 vist the filemanager this will ensure the key is present
step 2 execute the command @Lupul posted yesterday. 

If it works fine then there is a issue on Hestia side if not Something is wrong with your config

**Comment by vestacp-user** [comment]
Does the team want the non-root users to be able to edit their HestiaCP generated crontab on the command line using `crontab -e`?

My best guess would be no.  In that case, Hestia shouldn't touch anything related to user crontabs (`crontab -e`).  Hestia should simply use /etc/cron.d/ with seperate files and the user field for running the jobs.  You can even maintain 1 file per user-job, which makes updating them much simply in code, simply overwrite the file for a specific user-job. Note that both  /etc/cron.d and /var/spool/cron/crontabs are both owned by root so if you are writting to either, the writting hestia process needs elevated priviledges unless you are executing `crontab -e` as the user. 

This approach would let the user run `crontab -e` as they wish with whatever user they want and they would not see any Hestia jobs and would not be affected by hestia changes.

`man cron`
> Support  for  /etc/cron.d  is  included  in  the  cron  daemon  itself,  which handles this location as the system-wide crontab spool.  This directory can contain any file defining tasks following the format used in /etc/crontab, i.e. unlike the user cron spool, these files must provide the username to run the task as in the task definition.
...
>The intended purpose of this feature is to **allow packages that require finer control** of their scheduling than the /etc/cron.{hourly,daily,weekly,monthly} directories to add a crontab file to /etc/cron.d.  Such files should be named after the package that supplies them.

**Comment by ioannidesalex** [comment]
Having all crons in /etc/cron.d/ is kind of tricky since this would be viewed by all users (at least that's how it is now). I don't think it's a major concern for making users add their cron jobs via Hestia UI. It makes it much more consistent in order to add all crons from the same place and keep backups of all of them.

However you are right, we need to inform users about that behaviour.

**Comment by vestacp-user** [comment]
@ioannidesalex There are no requirements that the `/etc/cron.d/` files be readable by all.  The only requirement is that they be owned by root and read/write for root. Actually, security reccommendations are that they only be accessible by `root`.  Thus, Hestia can just create the `/etc/cron.d/` files as read/write root only (`chown root:root ...` `chmod 600 ...`).

`man cron`
> ...Files in this directory have to be owned by root...

Example security reccommendations: https://secscan.acron.pl/centos7/5/1/7
```
chown root:root /etc/cron.d
chmod og-rwx /etc/cron.d
```

**Comment by ScIT-Raphael** [comment]
The current behaviour is as expected, you should not manualy edit hestia users cron file - please use interface only.
