### ISSUE TITLE
open_basedir (Internal Server Error)

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#1029]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

### What steps did you take when the issue occured? 
1. Ex.: Click on the Web tab
2. Ex.: Click on Add Web Domain
3. Ex.: Attempted to add a domain and received an Internal Server Error.

### Expected behavior:
Please enter your answer here (e.g. the web domain should have been added successfully).

### Operating system:
Deb10

### Hestia Control Panel version:
Last

### Additional notes:
I'm using Nginx + PHP-FPM
Added domain to Hestia and got error

```
Internal Server Error

realpath(): open_basedir restriction in effect. File(/usr/lib/php/20180731) is not within the allowed path(s): (/home/sdor/web/pzdc.fun/public_html:/home/sdor/web/pzdc.fun/public_shtml:/home/sdor/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/phppgadmin:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt)
```

**template default /usr/local/hestia/data/templates/web/php-fpm/default.tpl**

```
; origin-src: deb/templates/web/php-fpm/default.tpl

[%backend%]
listen = /run/php/php%backend_version%-fpm-%domain%.sock
listen.owner = %user%
listen.group = www-data
listen.mode = 0660

user = %user%
group = %user%

pm = ondemand
pm.max_children = 8
pm.max_requests = 4000
pm.process_idle_timeout = 10s
pm.status_path = /status

php_admin_value[upload_tmp_dir] = /home/%user%/tmp
php_admin_value[session.save_path] = /home/%user%/tmp
php_admin_value[open_basedir] = /home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/phppgadmin:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt
php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@%domain%

env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /home/%user%/tmp
env[TMPDIR] = /home/%user%/tmp
env[TEMP] = /home/%user%/tmp
```

**Comment by jaapmarcus** [comment]
You need to add the folder that you receive to your open base_dir as this folder false outside the open_base_dir see 

https://docs.hestiacp.com/admin_docs/server_management.html#how-do-web-templates-work

And 

https://docs.hestiacp.com/admin_docs/server_management.html#how-can-i-change-settings-for-a-specific-domain

As this not related to Hestia it self I will close the issue. If you have any questions you can use our forum at forum.hestiacp.com

**Comment by avcvv** [comment]
But user folder already exist (home/%user%/web/%domain%/public_html)

**Comment by jaapmarcus** [comment]
Not /usr/lib/php/20180731

open_base_dir restricts PHP where he can access certain things.

Don't know what this folder contains

**Comment by avcvv** [comment]
I did rebuild user, but still get error

`php_admin_value[open_basedir] = /home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/phppgadmin:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt:/usr/lib/php/20180731`

**Comment by jaapmarcus** [comment]
Again https://forum.hestiacp.com

Technical support is not available at Github...
