### ISSUE TITLE
WebUI: "Add user" requires "Name" field minimum 2 characters.  "Edit user" does not require "Name" field. Incoherence

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1031]
WebUI: "Add user" requires "Name" field minimum 2 characters.  "Edit user" does not require "Name" field. Incoherence between functionalities.

Behavior should be the same for both functionalities. I would prefer the "Name" be never required.  There is no loss of functionality when name is not present and it can be easily seen from the User list if someone wants to check for missing Names.  

As a side note: v1.2.0 had two seperate fields, "First Name" and "Last Name" and now the data for both fields are combined into one.  This is a nice simplification.  Unless a fields is functionally required by Hestia, it should not be required by the UI.

**Comment by jaapmarcus** [comment]
`As a side note: v1.2.0 had two seperate fields, "First Name" and "Last Name" and now the data for both fields are combined into one. This is a nice simplification. Unless a fields is functionally required by Hestia, it should not be required by the UI.
`
The main/only usage is in greetings via email and on the /list/user pages. 

We also had issues with entering "Companies" as you can't use often the last name. 

Still trying to find the length requirements

**Comment by jaapmarcus** [comment]
Fixed with #1034

It should behave the same
