### ISSUE TITLE
WebUI: Password length check different between "Add user" and "Edit user". Incoherence

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1032]
WebUI: Password length check different between "Add user" and "Edit user". Incoherence

"Add user" requires minimum 6 characters, "Edit user" requires only 1 characters.  The two screens should have the same behavior.

**Comment by jaapmarcus** [comment]
In /add/user/ 
The a check of minum length is used. 
https://github.com/hestiacp/hestiacp/blob/0727ef9d5c6a7ff61caab8f38b2d86e62c50a631/web/add/user/index.php#L46-L50

In /edit/user not.
https://github.com/hestiacp/hestiacp/blob/main/web/edit/user/index.php

**Comment by neto737** [comment]
There's a thing that can improve the UI in a general way. First of all, use the "required" attribute in all required inputs, it will prevent form from being submitted if there's an empty required field. Other good way to improve it is using the "minlength" attribute to run a client-side filtering, it will give a feedback to user just before sending a request to the back-end.

It's important to point that when you use "minlength" attribute is needed to use the "required" attribute too.

**Comment by jaapmarcus** [comment]
I agree for the Web UI we need to make the error messages more easy than the current system but that is a new redesign....

Will change the min length change and enforce certain pattern.

**Comment by vestacp-user** [comment]
Honestly, the WebUI is very nice, congrats to the HestiaCP team! :)

The team probably already knows this, but just putting it here in case:
If ever there was a plan to change the WebUI framework, a modern virtual DOM framwork such as VueJS or ReactJS are the way to go (vs the current jQuery).  This code could also be isomorphic (client-side and server-side rendering) to support light clients (no js) and also to do form validation both on the server and client side and avoid code duplication.   The full stack would be harmonized into one language only, just JavaScript, for both the backend (NodeJS) and frontend, thus concentrating coding language skills into one language (js) and avoid code and effort duplication.

Frameworks are eventually going that way, coding once and let the system optimize the rendering decisions (server-side, client-side, mixed) live.  For example, the first js render is server-side for faster first load and then rendering migrates to the client side, keeping form validation both client-side and server-side.

https://github.com/vuejs/vue
https://vuejs.org/v2/guide/ssr.html
https://github.com/nuxt/nuxt.js
https://github.com/quasarframework/quasar

But I am not sure it is worth all the work to move to a new framework (at least for now), the HestiaCP UI both looks and works really nice!

**Comment by jaapmarcus** [comment]
Fixed with #1034

Increased In both cases to 8 chars and enforce certain pattern 

`var regex = new RegExp(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\d)[a-zA-Z\d]{8,}$/); 
`
Also with a nice hint if a password matches
