### ISSUE TITLE
can't add new user

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1036]
### In a few words, please describe the issue that you're experiencing:

![image](https://user-images.githubusercontent.com/39749258/89033319-2930d080-d354-11ea-9ce4-1a88956c7015.png)

can't add the new user

### What steps did you take when the issue occurred? 
then trying to add a new user via panel

### Expected behavior:
should not ask for Field "First Name, Last Name" 

### Operating system:
Ubuntu 20.04 LTS
Ubuntu 18.04 LTS

### Hestia Control Panel version:
1.2.1

### Additional notes:
After upgrading to 1.2.0 to 1.2.1

**Comment by jaapmarcus** [comment]
Enter a name in "Contact" it should work normally

**Comment by alber-khan** [comment]
Yes I tired it and after submitting the form I'm getting that issue. Happening in all 5 servers.

**Comment by jaapmarcus** [comment]
Strange thing is that the "Contact" field is also not translated 

If I check my "main" server

<img width="709" alt="Screenshot 2020-07-31 at 15 06 25" src="https://user-images.githubusercontent.com/9754650/89037835-89694780-d33f-11ea-8b07-b858dbc8bc74.png">

**Comment by jaapmarcus** [comment]
Please run

apt install --reinstall hestia

It will reinstall Hestia

**Comment by alber-khan** [comment]
Creating account via api is working fine. Also I've notice my clients name got merged and when I'm trying to change the name it's reverting back automatically after few minutes.

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/89066312-e0e0d500-d38a-11ea-9fad-3ff6dad7c411.png)

after running apt install --reinstall hestia

it's showing System Administrator

but when i edit the user

![image](https://user-images.githubusercontent.com/39749258/89066376-fa821c80-d38a-11ea-95e2-11ed3f0a7559.png)

it's showing blank

**Comment by alber-khan** [comment]
and when i try to edit it doesn't work

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/89066809-b17e9800-d38b-11ea-9017-5deceffc6e70.png)

**Comment by ScIT-Raphael** [comment]
the hsts information message is not relevant for the issue and has already been fixed for the next release.

**Comment by alber-khan** [comment]
I'm reinstalling the panel on ubuntu 18.04 at the moment as it's all the production servers

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/89067923-db38be80-d38d-11ea-9510-6c960ccc06c7.png)

After 2nd reinstalling it's all gone.

**Comment by jaapmarcus** [comment]
It is very strange as "System Adminstrator" is only set during install and never else used.

Can you check what the value is in $HESTIA/data/users/{username}/user.conf 
And check if there is a line with "NAME=''"
or FNAME and LNAME

During the install rebuild user is called 
https://github.com/hestiacp/hestiacp/blob/0727ef9d5c6a7ff61caab8f38b2d86e62c50a631/func/rebuild.sh#L17-L22

**Comment by alber-khan** [comment]
-bash: /usr/local/hestia/data/users/shopallt/user.conf: Permission denied
-bash: /usr/local/hestia/data/users/admin/user.conf: Permission denied

**Comment by alber-khan** [comment]
i ssh via root

**Comment by jaapmarcus** [comment]
Use cat / nano a config isn't executable

If you use 

root@dev:~# stat /usr/local/hestia/data/users/admin/user.conf 

You should something see like:
  File: /usr/local/hestia/data/users/admin/user.conf
  Size: 1133      	Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d	Inode: 532498      Links: 1
Access: (**0660/-rw-rw----**)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-07-31 14:13:26.387477578 +0200
Modify: 2020-07-31 14:13:26.159474962 +0200
Change: 2020-07-31 14:13:26.159474962 +0200
 Birth: -

**Comment by alber-khan** [comment]
Hello sorry for the delay in the response. as this was a production server so I have to put the names. I will set up a new server tomorrow on DO and hetzner to check out if the same issues occur.

**Comment by jaapmarcus** [comment]
@4183r did you modify something with you package?

See 
https://github.com/hestiacp/hestiacp/commit/fe3ce86ce908fcbf1b92246e5c2f10169ddebf51

**Comment by alber-khan** [comment]
Nope Not made any changes just after it got updated, I've notice all the name were same. Then I tried to change and it wasn't working so I've run the reinstall command and after that it wasn't working, then I've rebooted it and rebuild all the users and then all the names fields got empty and then I was able to change the name manually.

**Comment by jaapmarcus** [comment]
We have rolled out Version 1.2.3 to fix the issue when changeing user packages the name returned to the old status. 

Also no other users have reported any issues. I will close the issue.
