### ISSUE TITLE
Awstats to organize the top frame and button to update not showing

### ISSUE THREAD

**Issue by beird** [hestiacp/hestiacp#1043]
1) When I open AWSTATS on browser the top frame needs adjustment in order to show Hestiacp logo correctly
2) When add AllowToUpdateStatsFromBrowser 1 to /usr/local/hestia/data/templates/web/awstats/awstats.tpl
wont show the button to update.

**Comment by jaapmarcus** [comment]
1. Is a issue we need to check how to change it if possible. (With out modifying the html as this will break the after updating awstats.

2. There is a general setting but it also could cause issue due to the rights issues. (Default user running under nobody except admin/root / what ever user it runs under by default)

```
# When this parameter is set to 1, AWStats adds a button on report page to
# allow to "update" statistics from a web browser. Warning, when "update" is
# made from a browser, AWStats is run as a CGI by the web server user defined
# in your web server (user "nobody" by default with Apache, "IUSR_XXX" with
# IIS), so the "DirData" directory and all already existing history files
# awstatsMMYYYY[.xxx].txt must be writable by this user. Change permissions if
# necessary to "Read/Write" (and "Modify" for Windows NTFS file systems).
# Warning: Update process can be long so you might experience "time out"
# browser errors if you don't launch AWStats frequently enough.
# When set to 0, update is only made when AWStats is run from the command
# line interface (or a task scheduler).
# Possible values: 0 or 1
# Default: 0
#
AllowToUpdateStatsFromBrowser=0
```

**Comment by jaapmarcus** [comment]
Also

Existing subdomain with some traffic just enabled awstats. "domain.com" works fine

Last Update:     No qualified records found in log (0 corrupted, 0 comments, 0 Blank, 0 dropped)

**Comment by jaapmarcus** [comment]
> * When I open AWSTATS on browser the top frame needs adjustment in order to show Hestiacp logo correctly

Fixed limit height logo + increase slightly frame height
https://github.com/hestiacp/hestiacp/pull/1044

> * When add AllowToUpdateStatsFromBrowser 1 to /usr/local/hestia/data/templates/web/awstats/awstats.tpl
>   wont show the button to update.

Unable to fix this issue tried things:

1. Set allow AllowToUpdateStatsFromBrowser to 1 in all config files (/etc/awstats.conf,  /usr/local/hestia/data/templates/web/awstats/awstats.tpl) with out any result
2. Check code of **awstats.pl** (https://github.com/eldy/awstats/blob/58524d86acd77903b2ffbb985c9274ccdd531cde/wwwroot/cgi-bin/awstats.pl#L9959-L9977) to find if `$AllowToUpdateStatsFromBrowser` was set that was.
3. Checked if `$StaticLinks` so some unknown reason when I echo it it returned `td>`. 
4. Modified **awstats.pl** to exclude `$StaticLinks` link to update is showing fine how even when I click it it shows a 404 error.

What does need to change to make it working 

1. Make awstats.pl available via web. 
2. Setup CGI-BIN propperly
3. Unknown configuration changes. 

I don't know if the time worth it to change it. For me personally my answer is **no**. Feel free to contribute on it via Pull Request.

**Comment by ScIT-Raphael** [comment]
Fixed with: https://github.com/hestiacp/hestiacp/pull/1044

And according to https://forum.hestiacp.com/t/awstats-implement-new-options/1339/7 we're not able to resolve the manual update problematic. Please feel free to submit a PR, if you're able to solve the issue.
