### ISSUE TITLE
"Add Database": Database and Name Identifier lengths, maximum characters, label incoherent

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1045]
Various closely related issues with the "Add Database" Identifier lengths.

1) The sub-label "(maximum 16 characters in length (including prefix))" on Username is not representative of the actual check.  The current check is for 30 characters.  This is incorerent for the user.
1a) The username length check is 30 characters and gives the error: "Error: mysql username can be up to 30 characters long"  

2) The maximum length for the Database name is not verified, it currently lets an unlimited length.  The database then returns an error such as: "Error: invalid database format :: ..."  The error currently occurs with Database names longer than 64 characters, which is the MySQL limitation and not the MariaDB limitation.

3) Different databases have different limitations.  There are three possible solutions, but it should be coherent and harmonized for all databases ( I think 3b is the simplest and covers most standard use-cases).  
3a) Each databases limitations is be programmed into the UI
3b) The most common denominator is imposed. 
3c) Let the database return the error as a validation

4) This might also need to be harmonized with the relevant v-*scripts

5) The connector limitations need to be checked, but the connectors should respect the database limitations, if not, it would be a bug that the connector would have to fix.  For the moment, on v1.2.1, the WebUI is blocking at 30 characters, but the Database is failing at 64 characters, even though the underlying database is MariaDB which should be 80 characters.  Thus, maybe the connector is legacy and causing the error?

Limitations:
MariaDB: DB:80 User:80
MySQL: DB:64 User:32 (Obselete?)
PostgeSQL: DB:63 User:63

As a reference, here are the limitations.  I added MySQL just in case it is sometimes used, but I think references to mysql are just legacy or for the connector.

MariaDB:
https://mariadb.com/kb/en/identifier-names/
Databases, tables, columns, indexes, constraints, stored routines, triggers, events, views, tablespaces, servers and log file groups have a maximum length of 64 characters. 
>Users have a maximum length of 80 characters.

MySQL (Obselete?):
https://dev.mysql.com/doc/refman/8.0/en/user-names.html
https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html
>Database 	64

https://dev.mysql.com/doc/refman/8.0/en/grant-tables.html#grant-tables-scope-column-properties
>Table 6.8 Grant Table Scope Column Lengths
>...
>User, Proxied_user 	32

https://dev.mysql.com/doc/refman/8.0/en/user-names.html
>6.2.1 Account User Names and Passwords
>...
>MySQL user names are up to 32 characters long. Operating system user names may have a different maximum length. 

PostgreSQL:
https://www.postgresql.org/docs/current/infoschema-datatypes.html
https://www.postgresql.org/docs/current/infoschema-user-mappings.html
https://www.postgresql.org/docs/12/sql-syntax-lexical.html
>4.1.1. Identifiers and Key Words
>...
>By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes.

**Comment by vestacp-user** [comment]
Forgot to mention that on an Database or UserName errors, the password is erased on the form, which is a slightly annoying WebUI bug.

**Comment by jaapmarcus** [comment]
Limitations:
MariaDB: DB:80 User:80
MySQL: DB:64 User:32 (Obselete?)
PostgeSQL: DB:63 User:63

As Hestia is based on Vesta and Vesta default database was always "mysql" it will no surprise me that the default values are used when creating this page.

**Comment by ioannidesalex** [comment]
Information provided is very helpful! Thanks for pointing this out.

**Comment by jaapmarcus** [comment]
Just did some checking:

Even if MariaDB is installed in all the configs Hestia thinks it is Mysql. And as MariaDB is still drop in replacement for Mysql  I think it is the safest method to keep the limit for the lowest / worst setting
63 chars for PostgreSql and 32 for Mysql should be the limits then. 

https://github.com/hestiacp/hestiacp/blob/798cf3691aa12eff366b7b17a80e3e7157d3fe63/func/main.sh#L706-L711
and 
https://github.com/hestiacp/hestiacp/blob/798cf3691aa12eff366b7b17a80e3e7157d3fe63/func/main.sh#L721-L730

Limit for all databases is 64 chars and 30 (?) for Database usernames.

It should be flexible to create a unique name and still within the limits of all the different software...
