### ISSUE TITLE
API enabled yet not connecting

### ISSUE THREAD

**Issue by inputuserhere** [hestiacp/hestiacp#1048]
### In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

### What steps did you take when the issue occured? 

Installed Hestia on slave vps to act as a DNS cluster. Installed nginx and bind only.

### Expected behavior:

API enabled on slave but still not connecting to master.

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.1

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/i-only-have-one-nameserver-ns1/1438/11

**Comment by jaapmarcus** [comment]
Is this still an issue? Unable to replicate it...
