### ISSUE TITLE
Can not delete cyrillic DNS domain --> Error: dns domain ***** doesn't exist

### ISSUE THREAD

**Issue by idevappspro** [hestiacp/hestiacp#1052]
I have an unnecessary Cyrillic DNS domain/zone "xn--e1aaujjcdi.xn--p1ai". When I try to delete it, an error message appears (Error: DNS domain "семестро.рф" doesn't exist).

1. Go to DNS section
2. Select DNS domain "xn--e1aaujjcdi.xn--p1ai" and click trash can button

![Screenshot at Aug 07 16-03-08](https://user-images.githubusercontent.com/23634140/89648344-c1d0ce80-d8c7-11ea-806a-7d4257874657.png)
![Screenshot at Aug 07 16-04-38](https://user-images.githubusercontent.com/23634140/89648353-c4cbbf00-d8c7-11ea-9b9d-5eed58bd93af.png)

### Expected behavior:
The DNS domain "xn--e1aaujjcdi.xn--p1ai" should have been deleted successfully.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.1 (amd64)

**Comment by jaapmarcus** [comment]
Can confirm it is a bug. 

Bug is related to the v-delete-dns-domain command and not the "Web" interface

**Comment by jaapmarcus** [comment]
Found mulitple other script that using 
`domain=$(idn -t --quiet -u "$domain" )`

to find the domain even we save it as the format used in the location.

Those changes should fix it.

**Comment by ScIT-Raphael** [comment]
Merged the pull request, thanks @jaapmarcus.

@idevappspro, could you please test the new branch on a NON productiv system and let us know, if all works as expected? For upgrading to main branch please have a look here (Beta Testing): https://github.com/hestiacp/hestiacp/blob/release/CONTRIBUTING.md#ways-to-contribute, replace beta branch with main.

**Comment by Lupul** [comment]
How did you end up with the domain 'xn--e1aaujjcdi.xn--p1ai'? Adding the normal unicode domain 'семестро.рф' works fine in my limited tests

**Comment by jaapmarcus** [comment]
Just did some limitted tests and was able to add both formats to v-add-web-domain and v-add-dns-domain

If we would like to limit the adding of "xn--e1aaujjcdi.xn--p1ai" we should disable the possibiltity to add the possiblity every where. (Web allow them at the same time/DNS not)

Also with this fix the deleting of семестро.рф worked still fine.

**Comment by idevappspro** [comment]
> Merged the pull request, thanks @jaapmarcus.
> 
> @idevappspro, could you please test the new branch on a NON-productiv system and let us know if all works as expected? For upgrading to the main branch please have a look here (Beta Testing): https://github.com/hestiacp/hestiacp/blob/release/CONTRIBUTING.md#ways-to-contribute, replace beta branch with main.

Hi @ScIT-Raphael , sorry for the delay. Unfortunately, I couldn't do that, but I applied changes from #1053 manually and it solved my issue, I was finally able to delete stale DNS record and affected zone at all. 

So I appreciate everyone from this thread for your help! Hoooray!

**Comment by ScIT-Raphael** [comment]
Hi @idevappspro 

Glad that it worked for you,  infact we've merged the changes already to main, we will release them with the next feature update (1.3.0) in around a week. I'll going to close this issue now.
