### ISSUE TITLE
How to add iptables rule according parameters inside CP

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#1055]
Is it possible to add specific blocking rule in iptables without cmd, only in HestiaCP? 

I see many access log for my websites with scraping bots like Semrush and ahrefs, i found way how to block them fully according them UA, but this possible only in cmd shell

```
iptables -I INPUT 1 -m string --algo kmp --string "SemrushBot" --to 65535 -j DROP
iptables -I INPUT 1 -m string --algo kmp --string "AhrefsBot" --to 65535 -j DROP
```

Then we can see how many traffic we saved `iptables -vnL --line-numbers`

**Comment by ghost** [comment]
The Web UI only supports adding allow/block rules for TCP/UDP/ICMP connections at this time, for advanced modifications to iptables beyond that you must use the command line.
