### ISSUE TITLE
Feature Request: Hardware Key Auth (FIDO2/WebAuthn) Example: Yubikey

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1058]
I just got a Yubikey and set one up with Nextcloud 19.01 and its absolutely great for a passwordless solution, this would be an awesome feature for the HestiaCP webpanel and possibly expand to mail and ssh at a later time.

here is some docs I found explaing the new webAuth FIOD2 Implementation

https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/WebAuthn_Readiness_Checklist.html

**Comment by ghost** [comment]
Hi @johnnyq,

After discussing this internally we've decided not to approach this at this time, as we already have two-factor authentication with OTP codes which can be used with YubiKey's and other devices. While this is obviously not a full passwordless solution it provides adequate protection for user accounts.

With that said, if there is enough interest from the community in supporting this we may reconsider as development time allows or if anyone wishes to submit a PR with the necessary changes we can review then.
