### ISSUE TITLE
File Manager installation failed after upgrade to 1.2.2

### ISSUE THREAD

**Issue by pakdhetimin** [hestiacp/hestiacp#1059]
### In a few words, please describe the issue that you're experiencing:
After upgrading from 1.2.1 to 1.2.2, an error message appeared stating that File Manager installation failed.

### What steps did you take when the issue occured? 
1. Upgrading from 1.2.1 to 1.2.2
2. After succesfully upgraded, and Login as admin 
3. Attempted to Save configuration in server configuration, when choose in Plugin File tab i choose from No to Yes.

### Expected behavior:
File Manager should have been installed successfully, because before when in version 1.2.1 File Manager was installed successfully and has been used normally.

### Operating system:
Ubuntu 16.04 LTS

### Hestia Control Panel version:
1.2.2 

### Additional notes:
I have tried reinstall File manager with this command in terminal:
`v-add-sys-filemanager`

But error code happen like this:

[ErrorException]
  is_file(): open_basedir restriction in effect. File(./composer.json) is not
   within the allowed path(s): (/home/)

ERROR: File Manager installation failed!
Please report this to our development team:
https://github.com/hestiacp/hestiacp/issues
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

**Comment by jaapmarcus** [comment]
Did you modify anything in the open_basedir settings?

open_basedir restriction in effect. File(./composer.json) is not
within the allowed path(s): (/home/)

**Comment by pakdhetimin** [comment]
Apparently not. I didnt change or modify anything. Just normal upgrade with SSH:
`apt-get update && apt-get upgrade`
and then File Manager got error, and i tried to fix by reinstalling hestia with this command:
`apt-get install --reinstall hestia`
but error still happen with this note: **ERROR: File Manager installation failed!**

**Comment by jaapmarcus** [comment]
Running apt-get update && apt-get upgrade and running apt-get install --reinstall hestia again won't help as the error is a different location. Your error message you posted clear states there is a the openbase_dir of your php config.

Did you modify or somebody else changed anything in the open_basedir of the admin account? 

**open_basedir restriction in effect. File(./composer.json) is not
within the allowed path(s): (/home/)**

Default config file should look like
https://github.com/hestiacp/hestiacp/blob/main/install/deb/php-fpm/www.conf
or 
https://github.com/hestiacp/hestiacp/blob/main/install/deb/php-fpm/multiphp.tpl

Make sure you are using the correct and orignal php-fpm config....
