### ISSUE TITLE
repository mariadb does not have a Release file

### ISSUE THREAD

**Issue by mindaugasdi** [hestiacp/hestiacp#1061]
### In a few words, please describe the issue that you're experiencing:

Installing hestiacp displays errors, but installation completes successfully.

```
Updating currently installed packages, please wait... E: The repository 'https://mirror.mva-n.net/mariadb/repo/10.4/ubuntu focal Release' does not have a Release file.
[...]
No apport report written because the error message indicates its a followup error from a previous failure.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### What steps did you take when the issue occured? 
Installing HestiaCP

### Expected behavior:
No errors

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.2

**Comment by ScIT-Raphael** [comment]
Please have a look here https://forum.hestiacp.com/t/error-updating-to-1-2-2/1483/2 and try to install the package. Please let me know if this works: `apt install ca-certificates`

**Comment by mindaugasdi** [comment]
As I mentioned, installation completed successfully despite errors. Different than described in the forums.
Writing this, it says "ca-certificates is already the newest version"

**Comment by ScIT-Raphael** [comment]
what happens if you run now an `apt-get update`?

**Comment by mindaugasdi** [comment]
Shows
```
Hit:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal InRelease
Hit:2 http://archive.canonical.com/ubuntu focal InRelease                                           
Hit:3 https://nginx.org/packages/mainline/ubuntu focal InRelease                                    
Hit:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease                                    
Hit:5 https://apt.hestiacp.com focal InRelease                                                      
Hit:6 https://mirror.mva-n.net/mariadb/repo/10.4/ubuntu focal InRelease 
[...etc]
Reading package lists... Done
```

**Comment by jaapmarcus** [comment]
Replace   https://mirror.mva-n.net/mariadb/repo/10.4/ubuntu focal InRelease  with 
```
eris@cp:~$ cd /etc/apt/sources.list.d/
eris@cp:/etc/apt/sources.list.d$ cat mariadb.list
deb [arch=amd64] https://mirror.mva-n.net/mariadb/repo/10.4/ubuntu focal main
```

**Comment by ScIT-Raphael** [comment]
It should already be main: https://github.com/hestiacp/hestiacp/blob/e1068a53fcc39a3061ec106e276b273344838d92/install/hst-install-ubuntu.sh#L570

**Comment by mindaugasdi** [comment]
I am not sure what problem I am solving, because Hestia seems to work at the moment, but it displayed those errors on installation.
mariadb.list file contained before
`deb [arch=amd64] https://mirror.mva-n.net/mariadb/repo/10.4/ubuntu focal main`

Now I changed it to
`deb [arch=amd64] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu focal main`

Writing
```
sudo apt update
sudo apt upgrade
```
It says
```
The following packages have been kept back:
  mariadb-client mariadb-server
```

**Comment by ScIT-Raphael** [comment]
no need to change it back, please lave it on https://mirror.mva-n.net/mariadb/repo/10.4/ubuntu, the reference above was from an older version of the installer, we changed the mariadb repository.

**Comment by mindaugasdi** [comment]
Changed it back. Is it normal, that 'sudo apt upgrade' always shows the message as this package is something special.
```
The following packages have been kept back:
  mariadb-client mariadb-server
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

**Comment by jaapmarcus** [comment]
apt-get dist-upgrade will solve the issue

**Comment by ScIT-Raphael** [comment]
you could do a apt dist-upgrade and check if they will be installed, maybe not shipped with the normal system upgrades.

**Comment by mindaugasdi** [comment]
I wrote this and that message dissapeared, it also updated mariadb even though this is totally new server. So I guess this is related to installation error.

```
The following packages will be REMOVED:
  mariadb-client-10.3 mariadb-client-core-10.3 mariadb-server mariadb-server-10.3
  mariadb-server-core-10.3
The following NEW packages will be installed:
  libmariadb3 mariadb-client-10.4 mariadb-client-core-10.4
The following packages will be upgraded:
  mariadb-client
```

**Comment by ScIT-Raphael** [comment]
sounds like he want to do an upgrade to mariadb v10.4, your decission if you want to do it :). There is also an upgrade script for this step: $HESTIA/install/upgrade/manual/upgrade_mariadb.sh

**Comment by mindaugasdi** [comment]
Who wants to upgrade? As for me, I don't want anything :) Just to install hestia with default settings.

**Comment by mindaugasdi** [comment]
So I said yes to `sudo apt-get dist-upgrade` and it updated package to 10.4, is everything ok? I can start using Hestia? Or should reinstall / wait or something? Is that error message on installation normal or not?

**Comment by jaapmarcus** [comment]
You are save to upgrade to 10.4

**Comment by mindaugasdi** [comment]
Mysql no longer start. Also `/list/server/` no longer lists 'mariadb' as before, now it lists 'mysql'... I understand very little, possibly I should reinstall the server, at least it was functioning before...

**Comment by jaapmarcus** [comment]
`systemctl status mysql` or `systemctl status mariadb`

to see if mysql is running

**Comment by mindaugasdi** [comment]
Both printed `Unit .....service could not be found.`
Running `bash $HESTIA/install/upgrade/manual/upgrade_mariadb.sh` fixed the database.

**Comment by jaapmarcus** [comment]
So everything is working again?

**Comment by mindaugasdi** [comment]
I am yet to test how actual website is working, will write

**Comment by mindaugasdi** [comment]
Website is working, thank you for support and awesome control panel.

**Comment by mindaugasdi** [comment]
Since you closed the issue, I will guess that error reported will be fixed in some other context.
