### ISSUE TITLE
Password requirement does not allow non-alphanumeric characters like "*, !, ?"

### ISSUE THREAD

**Issue by vicalop** [hestiacp/hestiacp#1062]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When creating a new user, the it fails as the password does not meet all requirements. This happens even if the noted requirements are met, but a "!" is included in the password.

### What steps did you take when the issue occured? 
1. Add new user
2. Try to create user with new password that includes a "!" character

### Expected behavior:
Successful user creation.

### Operating system:
UBUNTU 18.04

### Hestia Control Panel version:
1.2.2

**Comment by jaapmarcus** [comment]
You have a point 
https://github.com/hestiacp/hestiacp/blob/798cf3691aa12eff366b7b17a80e3e7157d3fe63/web/add/user/index.php#L48

**Comment by neto737** [comment]
> You have a point
> https://github.com/hestiacp/hestiacp/blob/798cf3691aa12eff366b7b17a80e3e7157d3fe63/web/add/user/index.php#L48

You can use the filter_var function. I think it's enough to verify passwords, isn't it?

**Comment by jaapmarcus** [comment]
We should still validate the user input if it matches the basic requirements min 1 small, 1 caps + 1 number

Create a new function
https://github.com/hestiacp/hestiacp/blob/d9158901ad22849344e3b451551866e8156511dc/web/inc/main.php#L393-L395

Should handle it well as it is used on multiple locations created a function for it...

**Comment by jaapmarcus** [comment]
Due to this issue we decided to release 1.2.3 please install it and it should be fixed
