### ISSUE TITLE
HTTP-to-HTTPS redirection automatically re-enabled

### ISSUE THREAD

**Issue by neto737** [hestiacp/hestiacp#1063]
### In a few words, please describe the issue that you're experiencing:
When the SSL certificate is renewed the HTTP-to-HTTPS redirection option is being re-enabled.

### What steps did you take when the issue occured? 
1. Enabled "Use Lets Encrypt to obtain SSL certificate" option and saved.
2. Edit the same Web Domain and unchecked the "Enable automatic HTTP-to-HTTPS redirection" option, then saved.
3. After weeks, when the cron runs the SSL certificate renewal the "Enable automatic HTTP-to-HTTPS redirection" was automatically re-enabled.

### Expected behavior:
Renew the SSL certificate without re-enabling the "Enable automatic HTTP-to-HTTPS redirection" option.

### Operating system:
Debian 9 and Debian 10

### Hestia Control Panel version:
HestiaCP v1.2.2 (in both Debian 9 and 10)

**Comment by jaapmarcus** [comment]
Think the renewal is related to a bug in the upgrade script see

https://forum.hestiacp.com/t/updating-to-1-2-2-error-ssl-not-enabled/1484/5

We need to investigate on it.

**Comment by neto737** [comment]
It has happened before (in v1.2.1 or 1.2.0, I'm not sure). I know that happened before because one of my sites use an rewrite rule to redirect an specific page to HTTP, and when this option is enabled this page always shows the TOO_MANY_REDIRECTS error.

**Comment by ghost** [comment]
Off the top of my head this is probably caused by `v-add-web-domain-ssl` as it automatically enables HTTP-to-HTTPS redirection or somewhere else within rebuild code, will need to take a further look.

**Comment by jaapmarcus** [comment]
You got a point

https://github.com/hestiacp/hestiacp/blob/2e05ab4f56d66f94e26cec430c6adccecd35e780/bin/v-add-web-domain-ssl#L123-L124
and 


https://github.com/hestiacp/hestiacp/blob/0387031c2ddb403c2c66f2d37fee3cf04d3e5b29/bin/v-add-letsencrypt-host#L78-L80

**Comment by ScIT-Raphael** [comment]
@neto737 could you maybe implement the following change on your system and let me know, if it worked as it should? https://github.com/hestiacp/hestiacp/commit/3e69ca497f30d8d59a5647acd41f0bd84dc9d50f

**Comment by neto737** [comment]
@ScIT-Raphael of course. Is there any way to force the automatic renewal to a domain? So we can test it right now. Also if you want to discuss it faster on Discord I can talk to you and we can do some tests.

**Comment by ScIT-Raphael** [comment]
I just discussed with @jaapmarcus, the change I did will work, but basicly will disable the function completly. I'll need to find another way to solve the issue, please keep on the line, I'll push here as soon as I was able to send a new patch. Of course we can do the further discussions on discord :).

**Comment by snakehill** [comment]
It's also just upon adding a domain and enabling SSL (whether LE or another) with HTTP-to-HTTPS unchecked. Once the domain is saved, HTTP-to-HTTPS is enabled.

So I suppose it happens whenever there is a new certificate obtained (whether by checking SSL with or without LE, or by LE autorenewal).

**Comment by jaapmarcus** [comment]
Fixed: https://github.com/hestiacp/hestiacp/commit/ed0965bff846471cae79e86eddc896ee1e5c4802#diff-8b8710da6b59f8f7c06f193903f00d2e215c7eda347ae794bf078c3c95e2e5ee
