### ISSUE TITLE
Unable to update from prerelease / beta to release

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1065]
### In a few words, please describe the issue that you're experiencing:
With the use of Systematic Version and the new version string (v1.2.3-beta for example). You are not able to use `apt-get update && apt-get upgrade` any more as 1.2.3-beta is see as a downgrade to 1.2.3 
Also `apt update && apt install --reinstall hestia` as 1.2.3-beta is an unknown version

### What steps did you take when the issue occured? 
`v-update-sys-hestia-git hestiacp main install`

And then `apt-get update && apt-get upgrade`

### Expected behavior:
Upgrade from beta to "release" when available (Same version)

### Operating system:
All OS have this issue

### Hestia Control Panel version:
Since 1.2.1 we follow this format 

### Additional notes:
It would we nice if we are able to find a solution mainly for "beta testers" / users who are less familiar with Hestia / Beta testing that the get updated to the last version instead staying  on the beta version until next release

**Comment by jaapmarcus** [comment]
For users with this issue in the future:
`v-update-sys-hestia-git hestiacp release  install`

**Comment by ghost** [comment]
This will be fixed with the new upgrade script later this week.
