### ISSUE TITLE
Postgre backup fails

### ISSUE THREAD

**Issue by gatsukito** [hestiacp/hestiacp#1068]
### In a few words, please describe the issue that you're experiencing:
From 1.2.2 version, some postgresql database fail when nightly backup is running. In backup log I see **Error: Connection to localhost failed**, but this database is working from all my sites.

### What steps did you take when the issue occured? 
1. Execute backup process.
1. When backup try postgre, some databases fail this process.

### Expected behavior:
The backup process should have worked correctly.

### Operating system:
Debian 9.13

### Hestia Control Panel version:
1.2.3

### Additional notes:
![image](https://user-images.githubusercontent.com/49730910/90117789-a2b6be80-dd57-11ea-8148-48b8be25845d.png)

**Comment by gatsukito** [comment]
I have tried to remove this database and restore from the last backup, but this error stills appearing

**Comment by jaapmarcus** [comment]
Are you able to connect with root / "root password" to the database.

These can be found in /usr/local/hestia/conf/pgsql.conf

**Comment by gatsukito** [comment]
I can to connect and I can select "select version()"

![image](https://user-images.githubusercontent.com/49730910/90122704-fe844600-dd5d-11ea-972d-0013682ad2e6.png)

**Comment by jaapmarcus** [comment]
Maybe try via SSH/shell
`pg_dump -h localhost -U $USER -c --inserts -O -x -f temp.sql database_name`

https://github.com/hestiacp/hestiacp/blob/15405d64cab494dbda1872fd8a5e3ed067493b89/func/db.sh#L382-L393

**Comment by gatsukito** [comment]
Thanks you jaapmarcus, I have tried this and I have seen a problem with user permissions. I delete and create same database and I restore content database and this problem is solved, but, main problem persist. I think that this error appears on hestiacp/func/db.sh:

`psql -h $HOST -U $USER -p $PORT -c "SELECT VERSION()" > /dev/null 2>/tmp/e.psql`

Because error on backup log is the same

**Comment by gatsukito** [comment]
I think that I have seen the problem and how to resolve. When hestia executes **psql -h $HOST -U $USER -p $PORT -c "SELECT VERSION()" > /dev/null 2>/tmp/e.psql**, it is not passing "-d" parameter and psql thinks that user and database are the same, but in my case it is not (and I think that many people also).

Executing sentence like hestiacp/func/db.sh:

```
root@eclipseestheticspa:~# psql -h localhost -U eclipse_ecdeysol -p 5432 -c "SELECT VERSION()"
Password for user eclipse_ecdeysol:
psql: error: could not connect to server: FATAL:  database "eclipse_ecdeysol" does not exist
```

Executing with -d parameter

```
root@eclipseestheticspa:~# psql -h localhost -U eclipse_ecdeysol -d eclipse_gestion -p 5432 -c "SELECT VERSION()"
Password for user eclipse_ecdeysol:
                                                             version
----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.3 (Debian 12.3-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)
```
Reference: https://www.postgresql.org/docs/12/app-psql.html

Please, test this answer and create new commit with the fix.

**Comment by jaapmarcus** [comment]
Strange the 

With PostgreSQL 11.9 I have no issue
```
root@dev:~# psql -h localhost -U postgres -p 5432 -c "SELECT VERSION()"
Password for user postgres: 
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.9 (Debian 11.9-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)
```
**Edit**

Did a upgrade 
```
root@dev:~# psql -h localhost -U postgres -p 5432 -c "SELECT VERSION()"
Password for user postgres: 
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)
```

**Comment by gatsukito** [comment]
Of course, postgres user has permissions with postgres database, and everything match, but when hestia try to generate a backup, it uses user about database for backup, and the problem appears.

Your example also works with my VPS.

```
root@eclipseestheticspa:/home/admin# psql -h localhost -U postgres -p 5432 -c "SELECT VERSION()"
Password for user postgres:
                                                             version
----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.3 (Debian 12.3-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)
```

**Comment by jaapmarcus** [comment]
Did some testing:
Modified
https://github.com/hestiacp/hestiacp/blob/15405d64cab494dbda1872fd8a5e3ed067493b89/func/db.sh#L382-L393


To echo the username, host and database name
```
    echo "$USER"
    echo "$HOST"
    echo "$1 $2"
```

It will show:
```
2020-08-14 10:22:13 test_12344 (pgsql)
postgres
localhost
/home/backup/tmp.x0pAKpdeFd/db/test_12344/test_12344.pgsql.sql test_12344
2020-08-14 10:22:13 *** 1 database ***
```
Also where the error happens it fetches the data from `$HESTIA/conf/pgsql.conf` that contains the postgres user with it password. 
https://github.com/hestiacp/hestiacp/blob/95b492d80edbce3f1070afd13c0f1c6828ec44e5/func/db.sh#L102-L123

**Comment by gatsukito** [comment]
You are right, I tried to echo user and pass from psql_connect() and I see data about postgres into pgsql.conf. I don't know because with one postgre database it works and another postgre database it does not work

**Comment by jaapmarcus** [comment]
Put the echo thing in pgsql_dump function and then execute 

`v-backup-user eclipse`  in command line and see what happens

**Comment by gatsukito** [comment]
It is launched, i am waiting.

On the other hand, I see that only works postgre backup in account with only postgre database, if an account have mysql and postgre, mysql works but postgre fails.

```
-- DB --
2020-08-14 06:07:47 deysol_default (mysql)
2020-08-14 06:07:47 deysol_deysolwp (mysql)
2020-08-14 06:07:49 deysol_gcp (mysql)
2020-08-14 06:07:50 deysol_hosting (mysql)
2020-08-14 06:07:51 deysol_inmobi (mysql)
2020-08-14 06:07:53 deysol_pre (mysql)
2020-08-14 06:07:55 deysol_prestashop (mysql)
2020-08-14 06:07:56 deysol_qdpm (mysql)
2020-08-14 06:07:57 deysol_remoto (mysql)
2020-08-14 06:07:57 deysol_users_deysol (mysql)
2020-08-14 06:07:57 deysol_website_review (mysql)
2020-08-14 06:07:57 deysol_owncloud (pgsql)
Error: Connection to localhost failed
```

```
-- DB --
2020-08-14 07:00:15 unnidesdro_pre (pgsql)
2020-08-14 07:00:17 unnidesdro_admin (pgsql)
2020-08-14 07:00:19 *** 2 databases ***
```

```
-- DB --
2020-08-14 07:14:49 eclipse_cosmetica (mysql)
2020-08-14 07:14:57 eclipse_dom2 (mysql)
2020-08-14 07:14:58 eclipse_eclipse (mysql)
2020-08-14 07:15:01 eclipse_gestion (pgsql)
Error: Connection to localhost failed
```

**Comment by jaapmarcus** [comment]
Strange... Have created multiple databases..  No issues... Can't wait for the logs when your backup is complete...

```
-- DB --
2020-08-14 13:17:56 test_fkaewij (pgsql)
2020-08-14 13:17:56 test_faewfaefaewfae (mysql)
2020-08-14 13:17:56 test_feaefaewfaweaewafawe (mysql)
2020-08-14 13:17:56 test_awfeawefaewfaew (pgsql)
2020-08-14 13:17:56 *** 5 databases **
```

**Comment by gatsukito** [comment]
Log about host, dump, database and dbuser

```
-- DB --
2020-08-14 13:31:11 eclipse_cosmetica (mysql)
2020-08-14 13:31:19 eclipse_dom2 (mysql)
2020-08-14 13:31:19 eclipse_eclipse (mysql)
2020-08-14 13:31:22 eclipse_gestion (pgsql)
HOST: localhost, dump: /backup/tmp.jkP0vFSFfr/db/eclipse_gestion/eclipse_gestion.pgsql.sql, database: eclipse_gestion, dbuser: eclipse_ecdeysol
Error: Connection to localhost failed
root@eclipseestheticspa:/home/admin#
```

**Comment by jaapmarcus** [comment]
Maybe a stupid questions but currently I have no idea what is going wrong. Cosidering installing Debian 9 to try it my self...

1. For **eclipse_gestion** the database user is **eclipse_eclipse** or something else?
2. What happens if you create new user with 1 mysql database and 1 pgsql database and no additional content happens it again and run the command `v-backup-user newuser`. Happens it again?

**Comment by gatsukito** [comment]
New user with new and empty databases, created first mysql and last postgre. It fails

![Screenshot_20200815_111652](https://user-images.githubusercontent.com/49730910/90309452-13d9ab80-dee9-11ea-89d5-05e4b2ab7f78.jpg)

Edit

This time, user and database are the same as mysql as postgre

**Comment by jaapmarcus** [comment]
Tried it on a different server but had no issues. Are you able to replicate this is on a different server?

**Comment by gatsukito** [comment]
I'm sorry jaapmarcus, but I don't have another server for testing, I can to create a local virtual machine, but it is not a good acceptance criteria.

I see that /tmp/e.psql don't erase when backup fails. The content is: 

`psql: error: could not connect to server: received invalid response to SSL negotiation: u`

**Comment by gatsukito** [comment]
Ok, I can see the error. It seems that, when you run a mysql database, you use $PORT variable with 3306 value, but if later you create a postgre backup, system don't modify $PORT and it tries to connect to postgre with 3306 port

![image](https://user-images.githubusercontent.com/49730910/90346175-2954ef80-e027-11ea-9613-da54a44cebbe.png)  
![image](https://user-images.githubusercontent.com/49730910/90346184-3f62b000-e027-11ea-9d08-70df3a8bbcef.png)

**Comment by gatsukito** [comment]
Ok, if I force port for postgre, it works

![image](https://user-images.githubusercontent.com/49730910/90346261-d62f6c80-e027-11ea-9ce6-97447ed5593b.png)

![image](https://user-images.githubusercontent.com/49730910/90346246-be57e880-e027-11ea-9a7c-9714b1d0c6d5.png)

It is a bad hotfix, I understand that, in some where about the flow there is a problem

**Comment by jaapmarcus** [comment]
This would also explain why it does work on newer installs as we have added support for multiple ports (External server / second version beside default one and maybe more reasons... 

Past the contents of /usr/local/hestia/pgsql.conf (And change/remove the password?)

Adding `unset PORT` before host_str should solve the issue...

**Comment by jaapmarcus** [comment]
Thanks for your time investments finding this bug.. 

I have created a bug fix see https://github.com/hestiacp/hestiacp/commit/7b222c34029795c6b5c373ed6861a76a8241208b

Best way to fix this issue is 
wget https://raw.githubusercontent.com/hestiacp/hestiacp/7b222c34029795c6b5c373ed6861a76a8241208b/func/db.sh 
and replace /usr/local/hestia/func/db.sh

**Comment by gatsukito** [comment]
Perfect, this commit works correctly.

Thanks you so much for your dedication and fast communication
