### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#107]
### Operating System (OS/VERSION):

Debain 8 and Ubuntu 16.04 (probaly also 14.04)

### HestiaCP Version:

0.9.8-25

### Installed Software (what you got with the installer):

Apache2 + Nginx

### Steps to Reproduce:

service hestia start
/usr/local/hestia/php/bin/php -v

### Other Notes:

Error Message:
root@web03:/usr/local/hestia/php/bin# ./php -v
./php: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or dire

Seems to be a problem with older OS Versions, the deb packages are running properly on Ubuntu 18.04 and Debian 9.

**Comment by ScIT-Raphael** [comment]
A recompile under the Ubuntu 16.04 worked, php is working properly now - pushed new debs also for debian 8 but this needs still testing. For that case I leave the issue open.

**Comment by HueyGeek** [comment]
When I was investigating the VESTA to make the version for ARMv8 (VESTA-ARM), I concluded that the packages are compiled separately with a flavor installation and corresponding version of Linux, and that is just one of the libraries that has changed its version through the Ubuntu (and Debian) releases is libssl (openssl).

I recommend removing from the [hst_autocompile.sh](https://github.com/hestiacp/hestiacp/blob/master/src/hst_autocompile.sh) the direct use of the sources of the _openssl_ library, also of _pcre_ and _zlib_.

In particular I'm working on that in my project, and I think the most convenient thing is to use Docker images to access from a single installation (and script) all the flavors and versions that you want to support.

**Comment by ScIT-Raphael** [comment]
Based on @HueyGeek suggestion I removed the zlib and openssl part for php-fpm: https://github.com/hestiacp/hestiacp/commit/a73841646c3b28cc96f6eafc53e8ac8d236a8143
