### ISSUE TITLE
New features that can be coming

### ISSUE THREAD

**Issue by saptrishi17** [hestiacp/hestiacp#1070]
Please add some feature on application installer to delete WordPress installation or migrate to other domain as like Softaculous Becouse we can not delete WordPress and reinstalling  
### Operating system:
Ubuntu 18.04 LTS 
### Hestia Control Panel version:
 1.2.3

**Comment by ScIT-Raphael** [comment]
Hi @saptrishi17 

We just discussed your feature request internaly and come to the consense, that we do not want to implement such a migration feature. Basicly you can remove the files and database, then you'll also be able to install it again.
