### ISSUE TITLE
Install fails when trying to start apache.

### ISSUE THREAD

**Issue by madeofstown** [hestiacp/hestiacp#1072]
### Operating system:
Ubuntu 20.04 LTS, Debian 10.5

### Hestia Control Panel version:
1.2.3

### Additional notes:
Systemctl status tells me it has something to do with a wildcard (*.conf) configuration file.

**Comment by ScIT-Raphael** [comment]
Can you please provide the error output and used installation string? I anyway would suggest to use fpm when you install hestia, it will use fpm and mod_event by default.

**Comment by madeofstown** [comment]
It happens any time `-w no` and `-o no` are used in the same install script.
Console:
`[ * ] Configuring Apache Web Server...
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
Error: apache2 start failed`

From journalctl -xe:
`Aug 15 07:05:56 webdeb.rndmm.us apachectl[39501]: The Apache error log may have more information.
Aug 15 07:05:56 webdeb.rndmm.us systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE`

From systemctl status apache2.service:
```
Aug 15 07:05:56 webdeb.rndmm.us systemd[1]: Starting The Apache HTTP Server...
Aug 15 07:05:56 webdeb.rndmm.us apachectl[39501]: apache2: Syntax error on line 83 of /etc/apache2/apache2.conf: Include/IncludeO
Aug 15 07:05:56 webdeb.rndmm.us apachectl[39501]: Action 'start' failed.
Aug 15 07:05:56 webdeb.rndmm.us apachectl[39501]: The Apache error log may have more information.
Aug 15 07:05:56 webdeb.rndmm.us systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
Aug 15 07:05:56 webdeb.rndmm.us systemd[1]: apache2.service: Failed with result 'exit-code'.
Aug 15 07:05:56 webdeb.rndmm.us systemd[1]: Failed to start The Apache HTTP Server.
 ESCOC


 vendor preset: enabled)
:56 PDT; 3min 29s ago

d, status=1/FAILURE)

HTTP Server...
x error on line 83 of /etc/apache2/apache2.conf: Include/IncludeOptional: No matches for the wildcard '*.conf' in '/etc/apache2/c
 failed.
or log may have more information.
trol process exited, code=exited, status=1/FAILURE
led with result 'exit-code'.
```


[hst_install-150820200701.log](https://github.com/hestiacp/hestiacp/files/5078784/hst_install-150820200701.log)

**Comment by ScIT-Raphael** [comment]
Thanks for the detailed records, I'll try to reproduce them. Is there any reason you want to stick on using mod_php instead switch over to fpm, as also the apache2 foundation suggests?

**Comment by madeofstown** [comment]
My client prefers it because he is used to configuring it.

**Comment by jaapmarcus** [comment]
Can config the issue. 

```
Aug 16 22:25:38 test.nl apachectl[47985]: apache2: Syntax error on line 83 of /etc/apache2/apache2.conf: Include/IncludeOptional: No matches for the wildcard '*.conf' in '/etc/apache2/conf.d', failing
Aug 16 22:25:38 test.nl apachectl[47982]: Action 'start' failed.
```

Fix seems to be to add a dummy file to both folders or wait with reload after phpmyadmin/domains have been created

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/2e05ab4f56d66f94e26cec430c6adccecd35e780/install/hst-install-ubuntu.sh#L1219-L1220

Replace with:
```
    mkdir -p /etc/apache2/conf.d
    touch /etc/apache2/conf.d/dummy.conf
    mkdir -p /etc/apache2/conf.d/domains
    touch /etc/apache2/conf.d/domains/dummy.conf
```

**Comment by jaapmarcus** [comment]
#1125 will fix the issue it was due to a error in /etc/apache2/apache2.conf

Thanks for reporting
