### ISSUE TITLE
Install on Ubuntu 20.04 fails with "apt-get install failed"

### ISSUE THREAD

**Issue by daniel-eder** [hestiacp/hestiacp#1073]
### In a few words, please describe the issue that you're experiencing:
When installing the latest version (1.2.3) of hestiacp on a fresh install of ubuntu 20.04 the installation fails with "Error: apt-get install failed"

### What steps did you take when the issue occured? 
1. Log in as root and run `apt-get update && apt-get upgrade`
1. Download install script: `wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh`
2. Execute installation `bash hst-install.sh`
3. Enter installation details (admin email, FQDN)
4. Script runs until `NOTE: This process may take 10 to 15 minutes to complete, please wait...` and shows a spinner, then after a few seconds the error `Error: apt-get install failed` is printed and the script exits.

### Expected behavior:
The install script should finish successfully, or print more information about the error. 

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.3

### Additional notes:
 /var/log/apt/term.log and  /var/log/apt/history.log contain no log entries for the time frame of the installation.

**Comment by ScIT-Raphael** [comment]
Hi @daniel-eder 

Just spinned up a test machine on Hetzner Cloud (Ubuntu 20.04) and wasnt able to reproduce your issue.

For further debugging, could you please directly download the installer script for ubuntu and remove the log output prevent from apt-get install?

wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install-ubuntu.sh
nano hst-install-ubuntu.sh

on line 837, remove the " > /dev/null 2>&1 &", basicly you could remove the lines 838 to and with 851: https://github.com/hestiacp/hestiacp/blob/2e05ab4f56d66f94e26cec430c6adccecd35e780/install/hst-install-ubuntu.sh#L837

Then directly run the script using bash hst-install-ubuntu.sh, please let us know the output :).

**Comment by daniel-eder** [comment]
Thank you @ScIT-Raphael, with the apt-get log enabled tracking the issue down was easy.
The repository for php 7.3 was missing, after adding it as per [AskUbuntu.com](https://askubuntu.com/questions/1231381/unable-to-install-php-7-3-on-ubuntu-20-04) the installation worked.

**Comment by ScIT-Raphael** [comment]
That's a bit special, the installer should integrate the sury repository which itself ships the php7.3 package. A manual add of the repository should not be needed: https://github.com/hestiacp/hestiacp/blob/2e05ab4f56d66f94e26cec430c6adccecd35e780/install/hst-install-ubuntu.sh#L571-L573

If you would do some further debugs, that would be awesome - maybe we got here a unfixed issue :). If Hestia works now properly, I wish you fun when you explore the features and please let us know, if something doesnt work.

**Comment by daniel-eder** [comment]
@ScIT-Raphael I set up a fresh VPS with the same provider (Contabo.co) to debug this further.
It seems the issue is that `software-properties-common` is missing. As the output of add-apt-repository is voided no error shows, even if the command cannot be executed. Simply ensuring that the package is installed should prevent this on this and potentially other images.

**Comment by ScIT-Raphael** [comment]
@daniel-eder well found, software-properties-common was missed when we rewrote the dependencies installation process: https://github.com/hestiacp/hestiacp/commit/a8c7be0c933cc31eb44dcc254b0709ced19db140

I reopened the issue so we can add the package back to the list.

**Comment by ScIT-Raphael** [comment]
Hi @daniel-eder, once again thanks for the direct fix - I've merged it to the current staging branch and cherry picked it to the release branch. The issue has been resolved.
