### ISSUE TITLE
Quick Install Wordpress Description says Wordpresss

### ISSUE THREAD

**Issue by lifis** [hestiacp/hestiacp#1074]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

### What steps did you take when the issue occured? 
1. Click on the Web tab
2. Edit Web Domain
3. Click Quick Install App
4. Click Wordpress (Setup)
5. Description field has an extra S for wordpress, "Another wordpresss site"

### Expected behavior:
Description should be Another wordpress site

### Operating system:
N/A

### Hestia Control Panel version:
1.2.3

**Comment by jaapmarcus** [comment]
Fixed with next release
