### ISSUE TITLE
phpMyAdmin UI button leads to wrong URL when PostgreSQL is installed as well

### ISSUE THREAD

**Issue by ifaist0s** [hestiacp/hestiacp#1078]
### In a few words, please describe the issue that you're experiencing:
In Hestia UI, when I go to the tab **DB** and click on the **phpMyAdmin** button, the wrong URL opens https://server.example.com/php**pg**admin instead for the correct one https://server.example.com/php**my**admin

This is only happening to a server that has PostgreSQL installed along with MySQL. Other Hestia servers without PostgreSQL are not affected by this.

### What steps did you take when the issue occured? 
1. Login to Hestia Web UI with admin
2. Click on a user to login that user
3. Click on the **DB** tab
4. Click on the phpMyAdmin button

Please note that a MySQL database had already been created for that user at an earlier stage.

### Expected behavior:
Clicking the phpMyAdmin button should open the correct URL https://server.example.com/php**my**admin

### Operating system:
OS:	Ubuntu 20.04

### Hestia Control Panel version:
v1.2.3

### Installation string:
bash hst-install.sh --nginx yes --apache yes --phpfpm no --multiphp yes --named yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav yes --mysql yes --postgresql yes --interactive yes --hostname $(hostname -f) --email xxx@yyy.zz --port 12110 --api yes

### Additional notes:
Contabo VPS SSD
12/07/2020	Hestia installed on VPS (might have been v1.2.0 but I can't remember exactly)
28/07/2020	Upgraded to 1.2.1
11/08/2020	Upgraded to 1.2.2
12/08/2020	Upgraded to 1.2.3

### Other troubleshooting steps:
_Please treat the following information as info that **might** be related and not as the actual issue at hand._

At first I thought that the problem might have been introduced by some update. So I decided to spin a new VPS (Hetzner this time) and install from scratch Hestia v.1.2.3 with the same installation string. But the installation had issues with postgresql. Below is the installation result (on the troubleshooting VPS, not on the actual one):
```

                _   _           _   _        ____ ____
               | | | | ___  ___| |_(_) __ _ / ___|  _ \
               | |_| |/ _ \/ __| __| |/ _` | |   | |_) |
               |  _  |  __/\__ \ |_| | (_| | |___|  __/
               |_| |_|\___||___/\__|_|\__,_|\____|_|

                          Hestia Control Panel
                                  1.2.3
                            www.hestiacp.com

========================================================================

Thank you for downloading Hestia Control Panel! In a few moments,
we will begin installing the following components on your server:

   - NGINX Web / Proxy Server
   - Apache Web Server (as backend)
   - Multi-PHP Environment
   - Bind DNS Server
   - Exim Mail Server + ClamAV + SpamAssassin
   - Dovecot POP3/IMAP Server
   - MariaDB Database Server
   - PostgreSQL Database Server
   - Vsftpd FTP Server
   - Firewall (Iptables) + Fail2Ban Access Monitor

========================================================================


Would you like to continue with the installation? [Y/N]: y
Installation backup directory: /root/hst_install_backups/160820201610
Installation log file: /root/hst_install_backups/hst_install-160820201610.log

Adding required repositories to proceed with installation:

[ * ] NGINX
[ * ] PHP
[ * ] Apache2
[ * ] MariaDB
[ * ] Hestia Control Panel
[ * ] PostgreSQL

Updating currently installed packages, please wait...|
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait...                                                                                                                                                                    /

========================================================================

[ * ] Configuring system settings...
[ * ] Configuring Hestia Control Panel...
[ * ] Generating default self-signed SSL certificate...
[ * ] Adding SSL certificate to Hestia Control Panel...
[ * ] Configuring NGINX...
[ * ] Configuring Apache Web Server...
[ * ] Install PHP version 5.6...
[ * ] Install PHP version 7.0...
[ * ] Install PHP version 7.1...
[ * ] Install PHP version 7.2...
[ * ] Install PHP version 7.3...
[ * ] Install PHP version 7.4...
[ * ] Configuring PHP-FPM...
[ * ] Configuring PHP...
[ * ] Configuring Vsftpd server...
[ * ] Configuring MariaDB database server...
[ * ] Installing phpMyAdmin version v5.0.2...
[ * ] Configuring PostgreSQL database server...
cp: cannot create regular file '/etc/postgresql/*/main/': No such file or directory
[ * ] Configuring Bind DNS server...
[ * ] Configuring Exim mail server...
[ * ] Configuring Dovecot POP/IMAP mail server...
[ * ] Installing ClamAV anti-virus definitions.../
[ * ] Configuring SpamAssassin...
[ * ] Configuring Roundcube webmail client...
[ * ] Configuring fail2ban access monitor...
Error: PostgreSQL connection to localhost failed
/dev/sda1 [/]: group quotas turned on
/dev/sda1 [/]: user quotas turned on
[ * ] Installing remaining software updates...
[ * ] Configuring File Manager...


====================================================================
```

Please note the errors:
`cp: cannot create regular file '/etc/postgresql/*/main/': No such file or directory`
`Error: PostgreSQL connection to localhost failed`

**Comment by jaapmarcus** [comment]
Think it is related to a minor bug

https://github.com/hestiacp/hestiacp/blob/2e05ab4f56d66f94e26cec430c6adccecd35e780/install/hst-install-ubuntu.sh#L1452-L1453

**Confirmed**

**Comment by jaapmarcus** [comment]
For the error during installing this is the line
How ever have no issue with Ubuntu 20.04


https://github.com/hestiacp/hestiacp/blob/2e05ab4f56d66f94e26cec430c6adccecd35e780/install/hst-install-ubuntu.sh#L1442-L1443

I used the following string (Disabled ClamAV/spamassing and disabled Multiphp)

bash hst-install.sh --nginx yes --apache yes --phpfpm yes --multiphp no --named yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin no --clamav no --mysql yes --postgresql yes --interactive yes --hostname $(hostname -f) --email me@email.com --api yes -f

Can you check if /etc/postgresql/12/main/ is availble?

**Comment by ScIT-Raphael** [comment]
Fixed with: https://github.com/hestiacp/hestiacp/pull/1080#merged-event
