### ISSUE TITLE
Freeze on install of 1.2.1 update

### ISSUE THREAD

**Issue by Fyroeo** [hestiacp/hestiacp#1079]
### In a few words, please describe the issue that you're experiencing:

When dpkg (dpkg --configure -a) try to setup Hestia 1.2.1, it keeps freezing on the "Updating default writable folders for all users..." step.

### What steps did you take when the issue occured? 

1. Tried to install an apt packet but was informed that dpkg was interrupted and needed to do the "dpkg --configure -a" command
2. When the command is launched, dpkg tries to setup Hestia 1.2.1 but it keep freezing on the "Updating default writable folders for all users..." step

### Expected behavior:

The update should be complete.

### Operating system:

Debian 10.4

### Hestia Control Panel version:

1.2.0

**Comment by ScIT-Raphael** [comment]
Could you share more informations? Like how high is the load during upgrade? How long did you waited? What fo you have for system resources? Also the current release is 1.2.3, it should show this versions and should do all version steps from 1.2.0 to 1.2.3.

Also it sounds a bit weird that you should run dpkg --configure -a, usualy this happens when a package installation fails. What happens if you trigger apt install --reinstall hestia?

**Comment by Fyroeo** [comment]
The load during "upgrade" isn't higher than 10 or 5 % on every cores and the RAM memory is around half used. (Load average at 0.07)
I waited nearly 24 hours with dpkg running.
My server is made of 3 x86 64bits cores at 2096.062 MHz, 4 GB Memory and 40GB NVMe SSD.

"apt install --reinstall hestia" is (at least since your message) at 60% progress on the "Updating default writable folders for all users..." step

**Comment by ScIT-Raphael** [comment]
Is the upgrade still inprogress?

**Comment by Fyroeo** [comment]
Yeah :/
Still at the same progress and step.

![image](https://user-images.githubusercontent.com/20495032/90343252-01599200-e00f-11ea-8068-0fc0b77a0a68.png)

**Comment by ScIT-Raphael** [comment]
Could you stop the process and send us the login credentials to your server? If possible, send it to info@hestiacp.com. Will have a look tomorrow morning.

**Comment by Fyroeo** [comment]
I sent an email with all the credentials.

**Comment by ScIT-Raphael** [comment]
I was able to manualy run the upgrade steps so hestia was patched on v1.2.3, then rerunned dpkg --configure -a which went trough properly. I strongly recommend to NOT run anything (expect the hostname domain for lets encrypt ssl) under the admin user, please create a new user for the hosting itself.

I wasnt able to find any source of the problem, so maybe it depends on a local issue only, gonna close it now.
