### ISSUE TITLE
Minor bugs in v-change-domain-owner

### ISSUE THREAD

**Issue by brackenhill-mob** [hestiacp/hestiacp#1082]
HestiaCP v1.2.3
Ubuntu 20.04LTS Server

v-change-domain-owner leaves behind a trail of breadcrumbs...

I just moved all domains from the admin user to another. 2 bugs:

1. For each one the folder /home/admin/conf/web/DOMAIN is not deleted once it has been copied to the new owner
2. If the SSL certificate is issued by Let's Encrypt the symlink for nginx in /home/admin/conf/web/DOMAIN is not copied across which cause all renewals to fail

Also I get a number of Error[3] lines on screen which I think, looking at the code, is to do with DNS copying. I use Cloudflare for DNS so maybe this part of the code needs to check if DNS is active for the domain and ignore copying DNS entries if it not active (assuming that this error is to do with DNS!)

**Comment by ghost** [comment]
Can you please run `wget -O $HESTIA/bin/v-change-domain-owner https://raw.githubusercontent.com/hestiacp/hestiacp/fix/1082_v-change-domain-owner/bin/v-change-domain-owner && chmod +x $HESTIA/bin/v-change-domain-owner`, then move a few domains and let me know how it works for you please?

**Comment by ScIT-Raphael** [comment]
fixed with the branch above: fix/1082_v-change-domain-owner
