### ISSUE TITLE
Delete backup does not work if backup is only remote

### ISSUE THREAD

**Issue by gatsukito** [hestiacp/hestiacp#1083]
### In a few words, please describe the issue that you're experiencing:
When an user delete a backup, if server is configured to storage backups only on remote and not in local, the backup is not removed from remote server but hestia delete backup from its own database

### What steps did you take when the issue occured? 
1. You configure your server for allow remote backups and disable local backup.
1. Generate a new backup from some user. This backup is correctly sent into backup server.
1. Delete backup from hestiacp UI.
1. Hestia says that backup is deleted, but this backup still stored into backup server.

### Expected behavior:
If I delete a backup, I understand that hestia remove backup from local and remote server, and I say it because when daily backups are running, hestia rotates backups into backup server.

### Operating system:
Debian 9.13

### Hestia Control Panel version:
1.2.3, but this error appears from the beginning of hestia.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/2e05ab4f56d66f94e26cec430c6adccecd35e780/bin/v-delete-user-backup#L40-L42

Just checked and confirm... We should implement a system similar to the backup / restore function

**Comment by jaapmarcus** [comment]
Problem should be fixed with the following commit .

**Comment by jaapmarcus** [comment]
Will be in next release
