### ISSUE TITLE
User or database with upper case does not work with postgreSQL

### ISSUE THREAD

**Issue by gatsukito** [hestiacp/hestiacp#1084]
### In a few words, please describe the issue that you're experiencing:
Hestia allows to create an user with upper case name, and also allows for database name. If you have one postgre database or user with upper case, when backup executes, there is an error with postgre because don't support database and user with upper case

### What steps did you take when the issue occured? 
1. Generate a new user.
1. Generate a new postgre database. This database has an upper case character.
1. Generate a new backup. Crash.

![image](https://user-images.githubusercontent.com/49730910/90402686-192d2680-e0a0-11ea-8443-e010d03aea2a.png)

### Expected behavior:
From UI, user shouldn't to create a database or user for postgre that this contains an upper case character.

### Operating system:
Debian 9.13

### Hestia Control Panel version:
1.2.3

**Comment by jaapmarcus** [comment]
Can confirm the issue. 

The "Yellow" Error is due to the fact that the directory you are currently using doen't exists. Can't do any thing about that. Also need to confirm that PGSql doesn't allow Uppercase characters. Or something is on our side...

**Comment by gatsukito** [comment]
[2020-08-17 17-02-00.zip](https://github.com/hestiacp/hestiacp/files/5085049/2020-08-17.17-02-00.zip)

I attach a screen recording showing the error. By default, postgre does not like upper case into database and user name.

**Comment by jaapmarcus** [comment]
"Related" issue https://github.com/hestiacp/hestiacp/issues/1045
