### ISSUE TITLE
DNSBL URIBL_BLOCKED ADMINISTRATOR NOTICE: The query to URIBL was blocked.

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#1086]
Spamassassin includes the following message about DNSBL lookups in incoming emails it has scanned:

```
  0.0 URIBL_BLOCKED          ADMINISTRATOR NOTICE: The query to URIBL was
                             blocked.  See
                             http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
                              for more information.
```

In the context of HestiaCP, which is assumed to be installed on a clean system, this probably means that the Cloud Provider, ISP, etc. has configured nameservers that does not include 127.0.0.1 as the first choice.

For small installations with a low volume of incoming mail, the following solution seems to work:
```
echo "
prepend domain-name-servers 127.0.0.1;
" >> /etc/dhcp/dhclient.conf 
systemctl restart networking
```

Context:
Before making the above change, the user can check ```nano /etc/resolv.conf``` first to see if it is missing a localhost entry (eg. 127.0.0.1), after adding the prepend command to dhclient.conf and restarting the network, the localhost entry should now be included in resolv.conf.

References: 
https://wiki.debian.org/resolv.conf
https://cwiki.apache.org/confluence/display/spamassassin/DnsBlocklists#dnsbl-block
Section: "Q: My queries to a DNS-blocklist were blocked. What does this mean?"

Another option would be to include a DNSBL mirror with HestiaCP, this would cover servers that have a larger volume of incoming mail.

Has the Hestia team done any work on this yet? either to fix the resolve.conf or to have a DNSBL mirror?  If nothing is planned, I could propose some pulls, the first one being the resolve.conf / dhclient.conf fix.  Ideally using Augeas http://augeas.net/docs/references/lenses/files/dhcpd-aug.html

**Comment by kpapad904** [comment]
IIRC, there will be problems with getting a proper response from DNSRBL if you're forwarding all your DNS queries to Google (8.8.8.8) or Cloudflare (1.1.1.1) or your big ISP.

The solution is to ask DNSBL queries directly from your server's IP (and forward the other DNS queries to Google/CF/ISP etc).

**Comment by vestacp-user** [comment]
> The solution is to ask DNSBL queries directly from your server's IP (and forward the other DNS queries to Google/CF/ISP etc).

Yes, that is exactly what I have detailed in my post.  However, I am waiting back for news from the project team on the various questions in my initial post.

**Comment by jaapmarcus** [comment]
@vestacp-user feel free to create a pull request. Also if you want you can join Discord see the link in readme.md

**Comment by kpapad904** [comment]
Here is a Blacklist Performance Monitor, tracking more than 40 blacklists: 
https://www.intra2net.com/en/support/antispam/

I got uribl (http://uribl.com/refused.shtml) to work by selectively defining a null forwarder in bind9, thus circumventing the default forwarders (Google, Cloudflare, Hetzner etc) for that specific domain.

PS: Just checked exim4 config and I think we should also include .img/.iso to the list of blacklisted file extensions (L210 of /etc/exim4/exim4.conf.template), since about 25% of the viruses my servers receive are of that type.

**Comment by ScIT-Raphael** [comment]
As requested, we would need a pull request for it. After a discussion in dev chat, we decided to close this issue report / feature request for now.
