### ISSUE TITLE
Add option to import domain ssl to mail ssl

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#1090]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
domain wildcards can be used for domain mail certificates

### What steps did you take when the issue occured? 
This is not an error, but a feature request

### Expected behavior:
`/usr/local/hestia/bin/v-add-mail-domain-ssl USER DOMAIN SSL_DIR [RESTART]`

`if domain has wildcard cert, import, without issuing new certificate`

### Operating system:
ANY / Ubuntu 16.04.7

### Hestia Control Panel version:
LATEST

### Additional notes:
See expected behavior
web settings issuing new certificate, for mail, without need when domain has a wildcard certificate

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/1091#issuecomment-687571906
