### ISSUE TITLE
[Bug] Import from Vesta has the incorrect owner to mail folders

### ISSUE THREAD

**Issue by bubblecatcher** [hestiacp/hestiacp#1095]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

###
After moving domains from Admin account to a new non admin account i noticed that the email accounts for those domain had wrong group, it was set to 'admin'

### What steps did you take when the issue occured? 
1. Ex.: v-change-domain-owner domain.com newuser
2. Ex.: ls -la /home/newuser/mail/domain.com/
drwxrwx---  3 newuser mail    18 May  3 19:01 .
drwxr-x--x  4 root      root    47 May 18 19:20 ..
drwx------ 12 newuser admin 4096 Jul 31 11:54 email

### Expected behavior:
I have been informed the group for each email domain and or each email account should be 'mail'

### Operating system:
Debian 10.5

### Hestia Control Panel version:
1.2.3

### Additional notes:
Originally accounts imported from vestacp backup

**Comment by jaapmarcus** [comment]
v-change-domain-owner assumes that after the restore the owner of the files  is {user}:mail and not  {user}:{user}. 

{user}:mail is the default permission when you create a mail account. 

https://github.com/hestiacp/hestiacp/pull/1114 will fix the issue
