### ISSUE TITLE
Access to a website without a ssl certificate on https shows the content of the first, valid ssl website.

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#1103]
### In a few words, please describe the issue that you're experiencing:
Access to a website without a ssl certificate on https shows the content of the first, valid ssl website.

### What steps did you take when the issue occured? 
1. Add a web domain with a valid ssl certificate
2. Add a second web domain without any ssl certificate
3. Connect to the first web domain with https

### Expected behavior:
Show nothing, a success or error message after the invalid ssl error message.

### Operating system:
Ubuntu 18.04 LTS

### Hestia Control Panel version:
1.2.3

**Comment by ScIT-Raphael** [comment]
Can confirm that it always loads the first config file in /etc/apache2/conf.d/domains/, a probaly solution would be to generate a dummy config file there.

**Comment by ioannidesalex** [comment]
If I am not mistaken we have fixed that for Nginx only?

**Comment by ScIT-Raphael** [comment]
fixed
