### ISSUE TITLE
[Bug] Check Disk space before starting backup

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#1115]
I recently came across a fresh new server where a client uploaded a big 15GB TAR which got copied over 3 times in backup and space got full... so subsequent backups failed (logs were formed)

I have a suggestion if the devs can look into it. I use a small script on a few servers so I'll share that as a starting point as well.

#A	Logic to check if Backup can be completed
```
du -shc /home | awk '{ print $1 }'| cut -d'%' -f1
```

#B	Now you have a rough idea of how much Hestia Needs to backup, then use 
```
df -H | grep -vE '^Filesystem|tmpfs|cdrom|udev' | awk '{ print $5 }'| cut -d'%' -f1
```
and compare 
1. if B < A  =  Disk space is OK = proceed with backup
2. if B > A  = Disk space is low = Do not start backup, make log or empty file saying "%datetime% could not start backup as available space is less" and shoot an email to admin as well.

Infact this check should be in other cron schedules as well... which run daily or multiple times daily
I think if disk space is low, we should show a warning on login page in RED ... that would be a good UI and good indicator of problems beforehand for Server admins.

## Attached is a small script that I used a few years ago... can  be a good starting point.
[Disk space get.txt](https://github.com/hestiacp/hestiacp/files/5138985/Disk.space.get.txt)

Thanks

**Comment by jaapmarcus** [comment]
I think it should happen on default see if I am not wrong... 

https://github.com/hestiacp/hestiacp/blob/89e62ae8380737413f6c9143ce366e4b2e77198f/func/backup.sh#L22-L30

**Comment by jaapmarcus** [comment]
Just checked the check is only made after completion of the backup and before saving...

**Comment by mehargags** [comment]
I'm not sure... But if the 'check' is done after the backup is attempted, it kind of defeats the purpose as by that time your backup has already failed to complete and moreover the half backup whatever happened might have filled the last few gb of space left on drive.

We will need a check before the backup is attempted with some logic as I mentioned. I'm sure we can have some more logical checks too...open to more ideas from members here.
Thx

**Comment by myvesta** [comment]
@jaapmarcus 
That check (that you linked) will not check account size, but only if less than 95% disk space is used.
https://github.com/hestiacp/hestiacp/blob/main/func/main.sh#L6

**Comment by ScIT-Raphael** [comment]
I would say a simple check against the user.conf (U_DISK which stores the value in MB) against the diskspace should be enough and could be done fast. I'll have a look on it as soon as I get some free time.

**Comment by myvesta** [comment]
Exactly @ScIT-Raphael

**Comment by myvesta** [comment]
And should be multiple with 2, because while making backup, we first make tar files, and after that we gzip all tars... so double space of account is used.

**Comment by jaapmarcus** [comment]
We should also extend it to the remote backup locations

**Comment by mehargags** [comment]
> We should also extend it to the remote backup locations

How would you do that? Assessing remote storage capacity will be a tedious job and not possible many a times.

**Comment by ScIT-Raphael** [comment]
@mehargags it depends on the remote storage, for cifs, smb and sftp it should be possible. The only thing which seems not to support a "easy" disk space check, is ftp.
