### ISSUE TITLE
Feature Request] add file permissions system on file manager

### ISSUE THREAD

**Issue by saptrishi17** [hestiacp/hestiacp#1116]
There are not options on file Manager to file permissions so in custom script not working 
### Operating system:
Ubuntu 18.4 lts

### Hestia Control Panel version:
 1.2.3

### Additional notes:
Please add this feature to install custom script via file manager

**Comment by jaapmarcus** [comment]
See https://github.com/filegator/filegator/issues/112

It is not possible due to underlaying software limitations.

With https://github.com/hestiacp/hestiacp/pull/1102 the permissions are set as it should be. 

Unless a complete rewrite is made we can't do anything about it...

**Comment by Digital-Media-Group** [comment]
It helps. On Hetznert's hosting service, they apparently use Filegator and if you have the permissions option. Just in case it helps.

![Screenshot_12](https://github.com/hestiacp/hestiacp/assets/119053220/e58b48e8-cfd4-4f93-8c7c-ac1f2e6b68a1)

**Comment by tlcd96** [comment]
see: https://github.com/filegator/filegator/issues/112#ref-pullrequest-1729743800

**Comment by jaapmarcus** [comment]
See:
https://github.com/filegator/filegator/pull/399

We probably need to build our own version...

**Comment by ww7** [comment]
Released new version with chmod 
https://github.com/filegator/filegator/releases/tag/v7.10.0

**Comment by jaapmarcus** [comment]
It has been allready merged with main branch
