### ISSUE TITLE
Thunderbird or any similar Email not able to login email which hosted in Hestiacp server

### ISSUE THREAD

**Issue by KashifHK123** [hestiacp/hestiacp#1120]
### In a few words, please describe the issue that you're experiencing:
I have multiple email accounts in my hestiacp server, i can use them through roundcube without any problem but when i use same email in Email Clinet for example Thunderbird it not work, i try serverhostname, mail.example.com,
I try SSL/TLS and STARTTLS with Normal Password authentican for both SMTP and IMAP but not success, 

### Operating system:
Ubuntu 18.04.4 LTS

### Hestia Control Panel version:
v1.2.3

**Comment by jaapmarcus** [comment]
Check if you are able to connect with to the ports  with telnet it could be a issue with firewalls (Hestia or Provider)

**Comment by ErnestoNCarrea** [comment]
This might be a Thunderbird 78 issue. Try this: install Thunderbird 68, configure your mail account and then let Thunderbird auto-update to version 78. Worked for me. I didn't have time to investigate any further.

**Comment by Pleskan** [comment]
@jaapmarcus My guess that TS should add `smtp_enforce_sync = false` in **exim.conf**, then restart **exim4** service in order to install connection using Thunderbird.
Are you able to reproduce the issue?

**Comment by samanthasdad** [comment]
I have the same issue. I have tried using Apple Mail and Thunderbird. Same issues in both. Could not connect to server errors.

**Comment by jaapmarcus** [comment]
My guess that TS should add smtp_enforce_sync = false in exim.conf, then restart exim4 service in order to install connection using Thunderbird.

Please try

**Comment by ScIT-Raphael** [comment]
@KashifHK123 @samanthasdad do you've enabled let's encrypt for the related mail domain? If yes, which settings do you use exactly in thunderbird? If no, please enable it and try again.

**Comment by samanthasdad** [comment]
@ScIT-Raphael yes. enabled let's encrypt for the related mail domain Use SSL settings.

**Comment by ScIT-Raphael** [comment]
As written, please define "ssl settings" - port? ssl/tls? Have you noticed @EquisTango post? https://github.com/hestiacp/hestiacp/issues/1120#issuecomment-683326018

**Comment by samanthasdad** [comment]
Saw @EquisTango post.  Configured in 68 and then auto updated. Still same problem. Also same problem in Apple Mail. Not in front of CPU right now, will post settings shortly. But I tried STARTTLS and SSL at both ports 443 and 587 at mail.(domainname).com

**Comment by samanthasdad** [comment]
Normal password for both.

**Comment by ScIT-Raphael** [comment]
port 443 isnt a valid mail port, please have a look at the suggested settings when you add a mail account - ports are either 25 (non ssl), 465, 587 for smtp or 143 (non ssl), 993 for imap.

**Comment by samanthasdad** [comment]
Sorry. Here are settings. 993 for incoming and 587 for outgoing.

![Screen Shot 2020-08-30 at 3 15 48 PM](https://user-images.githubusercontent.com/70485065/91667585-da519480-ead3-11ea-9f78-f81f86a89c06.png)
![Screen Shot 2020-08-30 at 3 15 43 PM](https://user-images.githubusercontent.com/70485065/91667587-da519480-ead3-11ea-93ce-b446da01c403.png)

**Comment by ScIT-Raphael** [comment]
Authentification none for smtp? Can't work...

**Comment by KashifHK123** [comment]
@jaapmarcus all ports enabled and i verified them from online open port checking tool also
@jaapmarcus @Pleskan if write this in exim4.conf.template "smtp_enforce_sync = false" exim won't start.

**Comment by KashifHK123** [comment]
> @KashifHK123 @samanthasdad do you've enabled let's encrypt for the related mail domain? If yes, which settings do you use exactly in thunderbird? If no, please enable it and try again.

yes Let's Encrypt activated, i try mail.domain and hostname.domain with IMAP port 143, 993 with SMTP Port 465, 587 i tried both ports but not sucess

**Comment by ScIT-Raphael** [comment]
@KashifHK123 have you followed @EquisTango's advice aswell?

**Comment by KashifHK123** [comment]
@ScIT-Raphael  me and @samanthasdad we trying to solve this togather but no success

**Comment by Pleskan** [comment]
> smtp_enforce_sync = false

Just put mentioned line in in the config file without the quotes at the beginning of **exim4.conf.template** (at line 15 for example), but to be honest I think that is not the case of your problem, "roots" of the  your issue should be more obvious.

**Comment by ScIT-Raphael** [comment]
I'm not able to reporduce the issue: Just configure a customer domain with the "USE SSL / TLS" settings from hestia (when you edit/add a mail account), mail.domain.tld with SSL/TLS flag and 993 for imap, the same with port 465 for smtp - incoming and outgoing communication works properly. Please review your settings and let me know if thunderbird works properly.

**Comment by KashifHK123** [comment]
> > smtp_enforce_sync = false
> 
> Just put mentioned line in in the config file without the quotes at the beginning of **exim4.conf.template** (at line 15 for example), but to be honest I think that is not the case of your problem, "roots" of the your issue should be more obvious.

@Pleskan  line # 15 is blank in my exim confing


/etc/exim4/exim4.conf.template
--
######################################################################
#                                                                    #
#          Exim configuration file for Hestia Control Panel          #
#                                                                    #
######################################################################

#SPAMASSASSIN = yes
#SPAM_SCORE = 50
#CLAMD = yes

smtp_banner = $smtp_active_hostname
add_environment = <; PATH=/bin:/usr/bin
keep_environment =
disable_ipv6 = true

domainlist local_domains = dsearch;/etc/exim4/domains/
domainlist relay_to_domains = dsearch;/etc/exim4/domains/
hostlist relay_from_hosts = 127.0.0.1
hostlist whitelist = net-iplsearch;/etc/exim4/white-blocks.conf
hostlist spammers = net-iplsearch;/etc/exim4/spam-blocks.conf
no_local_from_check
untrusted_set_sender = *
acl_smtp_connect = acl_check_spammers
acl_smtp_mail = acl_check_mail
acl_smtp_rcpt = acl_check_rcpt
acl_smtp_data = acl_check_data
acl_smtp_mime = acl_check_mime

**Comment by Pleskan** [comment]
@KashifHK123, So just write there line needed, restart exim and test the connection.
Just for the sake of completeness of the testing process.

**Comment by ScIT-Raphael** [comment]
Just to write again: Was able to setup the mail account without any modifications to exim.conf on ubuntu 18.04 - https://github.com/hestiacp/hestiacp/issues/1120#issuecomment-683461374

**Comment by ghost** [comment]
Also not able to reproduce here with Thunderbird 78 on Windows -- using port 993 for IMAP and 465 for SMTP with both set to SSL/TLS connects successfully.

![image](https://user-images.githubusercontent.com/40798553/91672259-c45bc800-eb03-11ea-88b9-4b9bd283fceb.png)

**Comment by ScIT-Raphael** [comment]
I gonna close this ticket currently, due to the fact that we are not able to reproduce it. Please feel free to reopen the issue or create a new one if you find anything else!
