### ISSUE TITLE
Typo in 1.3.0 upgrade script

### ISSUE THREAD

**Issue by wojsmol** [hestiacp/hestiacp#1129]
Hi
IMHO https://github.com/hestiacp/hestiacp/blob/8ad50fc672871c0fe74a2c8632b516c43c50bfd8/install/upgrade/versions/1.3.0.sh#L37-L39
should be changed to
```bash
if [ -e  /etc/proftpd/tls.conf ]; then 
     rm /etc/proftpd/tls.conf 
fi 
```
one `s` instead of two in if statement.

**Comment by jaapmarcus** [comment]
Changed
