### ISSUE TITLE
[Bug] Putting "/" (slash) on Proxy Extensions breaks creating the configuration file from the template

### ISSUE THREAD

**Issue by arinc9** [hestiacp/hestiacp#1133]
### In a few words, please describe the issue that you're experiencing:
I've made a template to do 301 redirects.
I've also put an empty template, no-apache, to not initialize apache on that domain.

`301-redirect.tpl`
```
server {
    listen %ip%:%proxy_port%;
    server_name %domain% %alias_idn%;
    return 301 https://$host$request_uri;
}
```
`301-redirect.stpl`
```
server {
    listen %ip%:%proxy_ssl_port% ssl;
    server_name %domain% %alias_idn%;
    ssl_certificate      %ssl_pem%;
    ssl_certificate_key  %ssl_key%;
    return 301 https://%proxy_extentions%;
}
```
I put the URL I want to redirect to under Proxy Extensions section on the panel.
Putting domain.com works but if I put domain.com/example, nginx config won't be created from the template.
Checking nginx.ssl.conf with domain.com
```
server {
    listen <ip>:443 ssl;
    server_name test.com www.test.com;
    ssl_certificate      /home/admin/conf/web/test.com/ssl/test.com.pem;
    ssl_certificate_key  /home/admin/conf/web/test.com.com/ssl/test.com.key;
    return 301 https://domain.com;
}
```
checking nginx.conf with domain.com
```
server {
    listen <ip>:80;
    server_name test.com www.test.com;
    return 301 https://$host$request_uri;
}
```
Checking nginx.ssl.conf with domain.com/example, file is empty.
Checking nginx.conf with domain.com/example, file is empty.

I believe putting "/" on Proxy Extensions break creating the nginx configuration file.

### What steps did you take when the issue occured? 
![2020-09-02 (4)](https://user-images.githubusercontent.com/29339981/91987189-67942380-ed36-11ea-868f-0ed500af18bd.png)

### Expected behavior:
The configuration to be generated properly.

### Operating system:
Debian 10.3 (x86_64)

### Hestia Control Panel version:
1.2.3

**Comment by jaapmarcus** [comment]
If your check you $HESTIA/data/users/{user}/web.conf 

You will see 

`PROXY_EXT='jpeg,jpg,png,gif,bmp,ico,svg,tif,tiff,css,js,htm,html,ttf,otf,webp,woff,txt,csv,rtf,doc,docx,xls,xlsx,ppt,pptx,odf,odp,ods,odt,pdf,psd,ai,eot,eps,ps,zip,tar,tgz,gz,rar,bz2,7z,aac,m4a,mp3,mp4,ogg,wav,wma,3gp,avi,flv,m4v,mkv,mov,mpeg,mpg,wmv,exe,iso,dmg,swf'`

Please check how the templates work on a different template..

**Comment by arinc9** [comment]
I know I am using proxy extensions section in a hacky way, as if it's just a text to be carried over by the variable on the template. I couldn't figure out a better way to do redirects without creating a template for every URL to redirect to.

**Comment by jaapmarcus** [comment]
`        location ~* ^.+\.(%proxy_extentions%)$ {
              return 301 https://$host$request_uri;
        }`

**Comment by arinc9** [comment]
I'm not sure what this does and where do I need put this on the template. Can you explain a bit?

**Comment by jaapmarcus** [comment]
Check other templates...
caching.(s)tpl

Should be explaining it self
