### ISSUE TITLE
Lost two new translation strings

### ISSUE THREAD

**Issue by Wibol** [hestiacp/hestiacp#1134]
The new strings "Next" and "Login" for the login screen do not appear in the language files, at least in "en.php" and "es.php".

**Comment by jaapmarcus** [comment]
We will scrap the translations strings with next version.  How ever we could use some help with the translations.

We are currently busy with converting to the new system.  

See
https://translate.hestiacp.com/glotpress/projects/hestiacp/

If you are willing to help please join Discord (https://discord.gg/nXRUZch)

**Comment by Wibol** [comment]
I have registered with Discord and after doing so they ask for my phone number which I do not want to give them. Please, is there another way to get an account at https://translate.hestiacp.com/glotpress/projects/hestiacp/ to help with the Spanish translation?

**Comment by jaapmarcus** [comment]
Send you the link via pm.

https://translate.hestiacp.com/wp-login.php?action=register and the key is hestiacp

**Comment by Wibol** [comment]
Got it. Thanks.

**Comment by jaapmarcus** [comment]
Thank you for your changes / improvements
