### ISSUE TITLE
Changing IP Address leaves files behind causing Nginx failing to start.

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1139]
Related issue: https://forum.hestiacp.com/t/how-to-change-ip-address-in-vestacp/1642/10

Changing IP Adress leave certain files behind causing the server to fail 

```
systemctl status nginx.service ● nginx.service - nginx - high performance web server Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Thu 2020-09-03 03:37:29 +0430; 9min ago Docs: http://nginx.org/en/docs/ Process: 10746 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE) Sep 03 03:37:29 mypanel systemd[1]: Starting nginx - high performance web server… Sep 03 03:37:29 mypanel nginx[1…
```

**Comment by layanto** [comment]
This happened to me too. Looks like v-update-sys-ip left behind a few old IP around causing nginx to fail to start.
With
```
grep -I -R "w\.x\.y\.z" /etc
```
(where w.x.y.z is the old IP address), I found a few nginx configurations which still have old IPs. After fixing them, nginx can start without error. I didn't need to modify /etc/sysctl.conf.

Not sure if relevant but I restored backup from vestaCP.

**Comment by jaapmarcus** [comment]
Thank you we will investigate it

**Comment by ozgurerdogan** [comment]
I had this twice too.

**Comment by fuzhyperblue** [comment]
this happened to me too. I formatted my vps, reinstalled hestia, restored backups, a total 2hrs downtime. it was a sad day :)

**Comment by tlcd96** [comment]
I've never had that bug, and cannot replicate it. It's this bug still active?

**Comment by hazrpg** [comment]
This bug happens to me too. The easiest, and cheapest, way to replicate it is:

- Create a small lightsail ubuntu 20.04 instance
- Give it a free static IP address
- Install HestiaCP as per normal for whichever instance you can get for free
- Set up any domain for a website - real or not - in HestiaCP
- Then take a snapshot
- Once the snapshot finishes, spin a new instance from that snapshot for the same whichever instance you can get for free. You'll then notice that nginx is down and a bunch of config files still have the old Private IP address assigned (even though it automatically picks up the new IP address and tries to change everything to it).

None of the commands fixes the issue, you have to just go through and update the config files.

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/2212
