### ISSUE TITLE
[Bug] Docker - Auto-Instaler's have small bugs

### ISSUE THREAD

**Issue by Freebase394** [hestiacp/hestiacp#1140]
**Soo...**

On the SCRIPT **hst-install.sh** 
NOTE--> When i execute a command "bash hst-install.sh" 70%-98% of all system operatives of all users, dont have installed yet the "lsb_release" package... And everytime will print:
apt-get update && apt-get install lsb_release 
And in some cases in like me for example, executing the comand apt-get update && apt-get install lsb_release will generate this
![image](https://user-images.githubusercontent.com/19652056/92298501-4e12f780-ef41-11ea-9130-348c44bb167e.png)
And to fix that, this is what we need --> "apt-get update && apt-get install -y lsb-release && apt-get clean all" but even so, we never know what the user is doing on the machine, or what packages he has been installing, in which none of the previous commands will work, the most extreme case will be to install the package: "apt install lsb-core" 
It will be better to edit the script to do these checks, avoiding wasted time and streamlining procedures, since the script can do just that!

On the SCRIPT **hst-install-ubuntu.sh**
![image](https://user-images.githubusercontent.com/19652056/92298488-3a679100-ef41-11ea-95a1-72bc32f6ec62.png)
**apt-utils** is not installed
### WARNING: this shows only on Ubuntu

![image](https://user-images.githubusercontent.com/19652056/92297253-4cdbcd80-ef35-11ea-8ae7-464b94ae4ce4.png)
**apt-utils** still not installed,
### WARNING: this shows only on Ubuntu

![image](https://user-images.githubusercontent.com/19652056/92297138-fcb03b80-ef33-11ea-84ef-fb66362a3d51.png)
Apears on 06/09/2020 ->23:28 ---
![image](https://user-images.githubusercontent.com/19652056/92336447-b6282180-f098-11ea-8a8e-8dba3078d235.png)

===

My System Info:
![image](https://user-images.githubusercontent.com/19652056/92298844-07bf9780-ef45-11ea-98b2-c617e09a523e.png)

===

**Comment by Freebase394** [comment]
Welcome to the Hestia Control Panel installer!

	Please wait, the installer is now checking for missing dependencies...

	[ * ] Installing dependencies...
	debconf: delaying package configuration, since apt-utils is not installed

**Comment by Freebase394** [comment]
Aparently this installer have diferent ERRORS if SO is installed on hypervisor hyper-V microsoft or installed on qemu opensuse!  
![](https://www.memesmonkey.com/images/memesmonkey/41/411df63662a39d31d0c53791947c3096.jpeg)
 
Its a work in progress..

**Comment by ghost** [comment]
Closed, please see my comment on issue #1101 as these two are linked.
