### ISSUE TITLE
Backup create many tmp.XXX folder

### ISSUE THREAD

**Issue by Vladzimir** [hestiacp/hestiacp#1154]
-- DB --
2020-09-07 12:26:30 alpha_db (mysql)
Error: Connection to localhost failed

password in root/.my.cnf and in /usr/local/hestia/conf/mysql.conf and in /usr/local/hestia/conf/.mysql.localhost identical!

**Comment by jaapmarcus** [comment]
tmp.xxx is due the fact the backup can't be completed.

Can you login into the mysql server with the password / username provided?

**Comment by Vladzimir** [comment]
No. 
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
`
 But password not chenged. Only install.

**Comment by jaapmarcus** [comment]
Try setting up a new password 

https://www.techrepublic.com/article/how-to-set-change-and-recover-a-mysql-root-password

**Comment by Vladzimir** [comment]
Helping only "Recover your MySQL password"
