### ISSUE TITLE
[Feature request] Deploy from git repository

### ISSUE THREAD

**Issue by sergix44** [hestiacp/hestiacp#1157]
Some other control panels allow us to deploy applications directly from a git repository, this is especially useful for PHP applications. For example, Plesk allows this function: https://docs.plesk.com/en-US/onyx/customer-guide/git-support/using-remote-git-hosting.75848/

As far as I know, not many other free open source panels have this feature, it can be a really "nice to have".

**Comment by jaapmarcus** [comment]
I can remember that we have a similar request via forum few months ago see https://forum.hestiacp.com/t/sync-scripts-and-file-using-git/1343

CPanel has a similar function https://docs.cpanel.net/knowledge-base/web-services/guide-to-git-host-git-repositories-on-a-cpanel-account/

It could be a nice feature how ever limited resources (time) is currently one of the biggest issues.

Feel free to contribute with a pull request if you want / can.

**Comment by ScIT-Raphael** [comment]
As @jaapmarcus already wrote, we currently don't have enough resources to fullfill that request. Please feel free to provide any implementation steps over a PR, we would love to review, discuss and implement your code!
