### ISSUE TITLE
Blank pages after upgrading Hestia to 1.3.0 on Ubuntu 20.04

### ISSUE THREAD

**Issue by jeret15** [hestiacp/hestiacp#1158]
After upgrading Hestia to 1.3.0 RC on my Ubuntu 20.04 server I lost the ability to manage all Hestia related services from the server list page.
![image](https://user-images.githubusercontent.com/1844509/92506097-37042c00-f205-11ea-8ed1-e63060752e3e.png)

**Comment by jaapmarcus** [comment]
Also /list/dns/ is affected

**Comment by Freebase394** [comment]
Verry nice! I apritiate allot
Yesterday i have updated do RC version, and i saw someting wird like a page refreshing loop.. I don't know maybe are my resources! 
Nice progress ...
