### ISSUE TITLE
DNS Cluster - problem with API

### ISSUE THREAD

**Issue by spilo** [hestiacp/hestiacp#1167]
Dear all, 

today I installed a new installation of the HestiaCP, version 1.2.3 on Debian 10. 
I am having problem with the DNS-cluster, using the DOC:
https://docs.hestiacp.com/admin_docs/server_management.html#how-to-setup-a-dns-cluster 

user dns-cluster, was created in the HestiaCP, User configuration. 

When I enter the command, I get the following, something with API ? 

Error: api connection to <slave> failed
No Firewall in between the 2 servers, they are on the same subnet

Thank in advance

Kind Regards Peter

===

### Expected behavior:
DNS-cluster should be working

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.3
![HestiaCP_api](https://user-images.githubusercontent.com/10963716/92614284-2cf13480-f2bc-11ea-8ecf-03ee3ff5a725.jpg)

**Comment by jaapmarcus** [comment]
Are you sure the api is enabled? When the page is accessed over a get request the page shows empty

Maybe try the following script if the api is working as it should be... Just upload the file and access it via the browser 
https://gist.github.com/jaapmarcus/86c0e588a8ba69a6f521e3ea370708a4

**Comment by Freebase394** [comment]
Some news @spilo ?

**Comment by ScIT-Raphael** [comment]
I gonna close this issue, it seems to be a connection issue and not a bug which we could fix.

**Comment by spilo** [comment]
Hello,
no not yet, nothing has changed 
For the API part, by default it is disabled ? 

Kind Regards Peter

**Comment by ScIT-Raphael** [comment]
No, api isnt disabled by default. You could check if you can connect to the other server using curl https://host.domain.tld:8083, if this works, you could proceed with additional tests.

**Comment by spilo** [comment]
Hello ScIT-Raphael, 

Ok I have tested the curl as you suggested, but the result is blank, please see bellow:

![apitest](https://user-images.githubusercontent.com/10963716/93052143-e0b04680-f665-11ea-8974-7d9747fce0b7.jpg)

**Comment by ScIT-Raphael** [comment]
Seems the connection is open, maybe you want to test your api with the script @jaapmarcus provided above:

> Are you sure the api is enabled? When the page is accessed over a get request the page shows empty
> 
> Maybe try the following script if the api is working as it should be... Just upload the file and access it via the browser
> https://gist.github.com/jaapmarcus/86c0e588a8ba69a6f521e3ea370708a4

**Comment by spilo** [comment]
ok, once done I will inform you of the results

**Comment by spilo** [comment]
Dear all, 

sorry for the late response, please see the attached screenshot
![php-test](https://user-images.githubusercontent.com/10963716/93336992-cc687700-f828-11ea-9f02-4cd65434eb8f.jpg)

**Comment by jaapmarcus** [comment]
API is working fine..

**Comment by spilo** [comment]
hmmm, I am now doing a tcpdump/wireshark session, what the packets are telling ... 
it may look like that there is a problem with the Certificate ? the default HestiaCP is using TLS 1.3, but when I do the command, _v-add-remote-dns-host_ , i see in the wireshark a request to change the Cipher, could it be related ?

![capture](https://user-images.githubusercontent.com/10963716/93344679-3f2a2000-f832-11ea-8e0c-172a82f2be6d.jpg)

**Comment by jaapmarcus** [comment]
It could be try via command line from the server with issue

**Comment by iamra** [comment]
I am having this issue as well.
Please keep in mind that I am coming from original Vesta, so I am still learning in what ways Hestia is different.

My issue is as follows:
Stock Hestia install on Debian 10 (in container enviornment)
2 VPS instances of Hestia running the same versions, fresh installs. Default installation script.
Following Hestia docs on how to add DNS Cluster, I follow directions.

Password authentication works perfectly.
I want to test API connection, I generate api key on slave, and replace password in the command.

```
root@host:~# v-add-remote-dns-host host.domain.tld 8083 admin api_key
/usr/local/hestia/func/remote.sh: line 42: return: Error:: numeric argument required
Error: api connection to host01.sacred.network failed
```

```
https://host.domain.tld:8083/api_test.php/
string(309) "HTTP/1.1 200 OK
Server: nginx
Date: Thu, 21 Jan 2021 07:39:47 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

Error: authentication failed"
```

api_test.php works if I use the admin password, fails if I use api key.

I did not find any additional steps needed to enable api in Hestia.
I assume the default install script installed api functions as expected.

Please advice for any further testing.

**Comment by jaapmarcus** [comment]
When use the api key password should be empty and admin username is the api key 


In the test file there is currently no support for it. See docs for an working example

**Comment by ScIT-Raphael** [comment]
Is also visible in the scrip example: https://github.com/hestiacp/hestiacp/blob/657a6e49d156846af905d7d3c3f22fb4b9fe6e31/bin/v-add-remote-dns-host#L8

**Comment by iamra** [comment]
wow, no wonder, I read that section, but overlooked to remove the admin username from the command.
I corrected and confirm all is working as expected.

Thank you for your help, apologies for the false assumption.
