### ISSUE TITLE
Lets encrypt renew fails with HTTP-to-HTTPS enabled

### ISSUE THREAD

**Issue by xtrime-ru** [hestiacp/hestiacp#1168]
### In a few words, please describe the issue that you're experiencing:
When  HTTP-to-HTTPS redirect is enabled cron command `sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl` generates this in error.log:
`Error: Let's Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending [Error 2]`
 
Redirect makes http://proxy.i-c-a.su/.well-known/acme-challenge/xxx path unreacheable (301 redirect). Letsencrypt can`t validate domain and renew of ssl fails.

### What steps did you take when the issue occured? 
1. Enable https 
2. Enable HTTP-to-HTTPS redirect
3. `curl  -v http://proxy.i-c-a.su/.well-known/acme-challenge/xxx`
4. Got 301 error/redirect.

### Expected behavior:
 HTTP-to-HTTPS redirect must be disabled for `http://domain.com/.well-known/acme-challenge/xxx`.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.3

### Additional notes:
nginx -T:
```
# configuration file /etc/nginx/conf.d/domains/proxy.i-c-a.su.conf:
server {
    listen      80;
    listen      [::]:80;
    server_name proxy.i-c-a.su ;

    include /home/admin/conf/web/proxy.i-c-a.su/nginx.forcessl.conf*;

    types {
            text/html   html htm shtml php php5;
    }

    location / {
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
            expires     max;
            fastcgi_hide_header "Set-Cookie";
        }
    }

    include     /home/admin/conf/web/proxy.i-c-a.su/nginx.conf_*;

}

# configuration file /home/admin/conf/web/proxy.i-c-a.su/nginx.forcessl.conf:
return 301 https://$host$request_uri;

# configuration file /home/admin/conf/web/proxy.i-c-a.su/nginx.ssl.conf_letsencrypt:
location ~ "^/\.well-known/acme-challenge/(.*)$" {
    default_type text/plain;
    return 200 "$1.6S1MneElgpHLF8QHb9LcFV3gznbZTNJ_08_FTiUT_PU";
}
```

**Comment by ScIT-Raphael** [comment]
Hi @xtrime-ru 

Are you sure, that it is related to the http to https rewrite? I use the redirect on nearly all my let's encrypt enabled domains and do not have any issues on renew. The request will be forwarded from http to https with a 301, the validation should still work.

**Comment by xtrime-ru** [comment]
After i disabled redirect and HTHS and manually started v-update-letsencrypt-ssl one of domains with outdated certificate was fixed.

Another domain still has outdated certificate. Im 90% sure its because nginx redirect for .well-known. 

Currently v-update-letsencrypt-ssl does not work. Probably my ip was banned for 24 hours because of too many errors. I will try with another domain tomorrow.

Can you curl .well-known path in your domains via http? I can give you access for my vps if you need.

**Comment by ScIT-Raphael** [comment]
The curl on .well-known path redirects to https, which then shows the correct validation key.

```
root@webxxx:~# curl -L http://xxx.xx/.well-known/acme-challenge/
.JIiTz40j-KThloXcKV6syR-cJbEiKql-kTybGhBRhH8
```

As I'm not able to reproduce and do not have the issues on my systems, either another dev or community member has the same problem, I don't think your issue is related to the http-https redirect.

Please wait the renewal ban and rerun v-update-letsencrypt, probaly disabling the cron for now would be a good idea - then try a day later. Let me know if it worked or not.

**Comment by xtrime-ru** [comment]
> As I'm not able to reproduce and do not have the issues on my systems, either another dev or community member has the same problem, I don't think your issue is related to the http-https redirect.

I found few exact issues:

https://forum.vestacp.com/viewtopic.php?f=11&t=18597&sid=adbe321dbe4fefa7fba143e7c9e1b9fa&start=50#p83045
<img width="971" alt="image" src="https://user-images.githubusercontent.com/34161928/92751274-7f038a00-f390-11ea-829a-370010bf57bf.png">

https://community.letsencrypt.org/t/letsencrypt-renewal-issue/62480/17
<img width="778" alt="image" src="https://user-images.githubusercontent.com/34161928/92751214-7448f500-f390-11ea-8822-5c4034aa9f71.png">

I think if we put redirect in simple location with regex to avoid well-known will fix this issue. I can do pull request. 

PS. Why letsencrypt renew works for your domains ?🤔

**Comment by ScIT-Raphael** [comment]
As written: The redirect function has been implemented more than a year ago (https://github.com/hestiacp/hestiacp/commits/7184b7e3ef420d9ad13ac2fcaf5494a811a78080/bin/v-add-web-domain-ssl-force), aswell it is in use by a lot of devs and community members. This still leads me to the fact, that this could not be the source of the renewal issue.

Also, since 6 months, the http to https redirect will enabled by default, as soon as you activate ssl for the domain: https://github.com/hestiacp/hestiacp/blob/e47594433463aa6ace4d0400c70d24cda50c3505/bin/v-add-web-domain-ssl#L124

Maybe you could trace down the issue on your system and monitor a renewal with active redirect? As written, it should work without any troubles.

**Comment by jaapmarcus** [comment]
Maybe also some information about server set up would be nice.

Hosting your own DNS, Third party and so on, Apache2, Nginx + Apache2 or Nginx Standalone?

I just checked a few domains renewed with in the last week with out any issues...

**Comment by xtrime-ru** [comment]
> Maybe also some information about server set up would be nice.
> 
> Hosting your own DNS, Third party and so on, Apache2, Nginx + Apache2 or Nginx Standalone?
> 
> I just checked a few domains renewed with in the last week with out any issues...

Nginx only. Also i have named dns installed (default option) in hestia. But im not using it, because i managing DNS records in another hosting/registrator, where i buy domains.

**Comment by xtrime-ru** [comment]
> Maybe you could trace down the issue on your system and monitor a renewal with active redirect?

Yes. I want to do this. I still got one domain for renewal. How can i get full logs from v-update-letsencrypt-ssl ?

**Comment by xtrime-ru** [comment]
Also it would be nice if v-update-letsencrypt-ssl put all errors to stdout, because i was not knowing i got this cron not working :(

Searching for logs and found this in nginx.error: 

```
2020/09/10 11:45:10 [error] 538#538: OCSP response not successful (6: unauthorized) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: 195.138.255.24:80, certificate: "/home/admin/conf/web/proxy.i-c-a.su/ssl/proxy.i-c-a.su.pem"
2020/09/10 17:50:35 [error] 85588#85588: OCSP response not successful (6: unauthorized) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: 2.16.186.27:80, certificate: "/home/admin/conf/web/proxy.i-c-a.su/ssl/proxy.i-c-a.su.pem"
```

Maybe my https config causes troubles? But it looks like default...

Also found this in syslog:
`Sep 10 01:51:07 static systemd-resolved[392]: message repeated 3 times: [ Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.]`

**Comment by ScIT-Raphael** [comment]
You can adjust the v-update-letsencrypt-ssl script, to not supress the output. Basicly it triggers v-add-letsencrypt-domain again: https://github.com/hestiacp/hestiacp/blob/789a2b09b647f722e593a3bd0f3fe95bde864b65/bin/v-update-letsencrypt-ssl#L82

**Comment by ScIT-Raphael** [comment]
For the records, let's encrypt acme challenge is following 301 rewrites: https://community.letsencrypt.org/t/301-caching-on-acme-challenge/78364

**Comment by xtrime-ru** [comment]
> You can adjust the v-update-letsencrypt-ssl script

Thanks for tip! I commented continue on max fails and added echo.

```
#HSTS and HTTP-to-HTTPS on
root@static:/home/admin/web/tg.i-c-a.su/TelegramApiServer# sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl
proxy.i-c-a.su failcount: 31
Error: Let's Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending

#HSTS off and HTTP-to-HTTPS on
root@static:/home/admin/web/tg.i-c-a.su/TelegramApiServer# sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl
proxy.i-c-a.su failcount: 32
Error: Let's Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending
```

If i disable HTTP-to-HTTPS now - renewal will work (99% sure). 

But maybe i can hire (and pay) some one from your team so you can check my nginx configs and find out what causes troubles?

**Comment by ScIT-Raphael** [comment]
Is the certificate outdated on renewal? If yes, that would explains why the validation fails.

**Comment by xtrime-ru** [comment]
Currently its outdated, yes.

But It was valid `NOT_AFTER: | Sep 8 21:26:35 2020 GMT` and still renewal failed entire month before that...
Here is part of /var/log/hestia/error.log

```
2020-09-06 01:53:01 v-list-dns-records  'admin' 'proxy.i-c-a.su' [Error 3]
2020-09-06 01:53:42 v-list-dns-records  'admin' 'proxy.i-c-a.su' [Error 3]
2020-09-06 01:53:42 v-add-letsencrypt-domain  'admin' 'proxy.i-c-a.su' [Error 15]
2020-09-06 01:53:42 v-update-letsencrypt-ssl proxy.i-c-a.su Error: Let's Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending [Error 2]
```

**Comment by ScIT-Raphael** [comment]
Just posted your request for paid support into our dev chat, currently we do not offer paid support from hestia itself. If someone has interrests to check it out, I'll write you.

**Comment by xtrime-ru** [comment]
If i made pull request with echo on fail in v-update-letsencrypt-ssl and with regex location for return 301 for HTTP-to-HTTPS will you approve/merge it?
 
I know it's a hack, but i have no other ideas how to solve this properly.

**Comment by Pleskan** [comment]
Hello @xtrime-ru !
If you still would like to get a paid support for your issue, you can contact me directly via pleskan87[at]gmail[dot]com.
And we can discuss paid support moment in Russian using mail communication.

**Comment by ScIT-Raphael** [comment]
> If i made pull request with echo on fail in v-update-letsencrypt-ssl and with regex location for return 301 for HTTP-to-HTTPS will you approve/merge it?

If we can find out, if it is the source if your issue and would be a proper fix, then yes. But maybe check with @Pleskan first, so we can gain more informations :).

**Comment by xtrime-ru** [comment]
> And we can discuss paid support moment in Russian using mail communication.

Thanks for reply. Sent email to you.

**Comment by xtrime-ru** [comment]
> > If i made pull request with echo on fail in v-update-letsencrypt-ssl and with regex location for return 301 for HTTP-to-HTTPS will you approve/merge it?
> 
> If we can find out, if it is the source if your issue and would be a proper fix, then yes. But maybe check with @Pleskan first, so we can gain more informations :).

Ipv6 AAAA address was incorrect. We replaced 2a01:4f8:c0c:71d1:: -> 2a01:4f8:c0c:71d1::1 
Also https://letsdebug.net was very helpfull. 

Many thanks to @Pleskan and @ScIT-Raphael for fast replies and support. I will send another donate to support hestia.

Im closing this issue, but i will make pull request to enable echo errors from letsencrypt :)
