### ISSUE TITLE
Add public key ssh

### ISSUE THREAD

**Issue by reina3596** [hestiacp/hestiacp#1169]
Hi, 

I use AWS CLOUD9. I have created a normal user "aws". I have added a key from Cloud9 but I can't connect. The key have been added to "admin" user but with my user "aws" I can not connect :(

What can I do, to connect with my normal user "aws" with key from cloud9???? 

Thanks

**Comment by jaapmarcus** [comment]
Copy paste the key manually into "~/.ssh/authorized_keys" will be fixed during next release.

https://github.com/hestiacp/hestiacp/pull/1161

**Comment by jaapmarcus** [comment]
Also make sure to use the public key and allow "bash" if you want to connect over ssh. 

It is nothing more as short interface to ~/.ssh/autorized_keys
