### ISSUE TITLE
default Apache2 Mail template

### ISSUE THREAD

**Issue by sirlensen** [hestiacp/hestiacp#1175]
I think the template install/deb/templates/mail/apache2/default.stpl is incorrect. Because the line 
**IncludeOptional %home%/%user%/conf/mail/%root_domain%/apache2.forcessl.conf**
results in a endless loop if the option _Enable automatic HTTP-to-HTTPS redirection_ is set

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.3

**Comment by ScIT-Raphael** [comment]
fixed with https://github.com/hestiacp/hestiacp/pull/1206
