### ISSUE TITLE
Configuration tab not showing components configuration

### ISSUE THREAD

**Issue by gerikobcn** [hestiacp/hestiacp#1179]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When click on configuration button, configurations doesn't appear, like apache2,nginxs...
### What steps did you take when the issue occured? 
1. Ex.: Click on the configuration button

### Expected behavior:
Show configurations for server components

### Operating system:
Debian 10.5

### Hestia Control Panel version:
Hestiacp 1.3 Alpha

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1159/commits/296d2432e7f6b585f33bee9a7bdef4ed1978d0c5

Know issue should be fixed. With next prerelease / final release 

To test it you can manually patch those files.

**Comment by gerikobcn** [comment]
> [296d243](https://github.com/hestiacp/hestiacp/commit/296d2432e7f6b585f33bee9a7bdef4ed1978d0c5)
> 
> Know issue should be fixed. With next prerelease / final release
> 
> To test it you can manually patch those files.

Sorry, I tried to find it before ticket opening... :)

**Comment by jaapmarcus** [comment]
Better 2 min work to close a extra issue than a never reporting and when we release it got discovered...
