### ISSUE TITLE
Save button not working on any form through mobile webbrowser

### ISSUE THREAD

**Issue by gerikobcn** [hestiacp/hestiacp#1180]
# In a few words, please describe the issue that you're experiencing:
Save button not working on any form through mobile Android chrome webbrowser
### What steps did you take when the issue occured? 
1. Ex.: Click on save button 

### Expected behavior:
Save changes

### Operating system:
Debian 10.5

### Hestia Control Panel version:
Hestiacp 1.3 Alpha

### Additional notes:
I didn't try it on computer browser yet.

**Comment by jaapmarcus** [comment]
I am unable to test it on an Android Device but I have no issues with iOS.

Please try if it work on 1.2.3.

**Comment by ScIT-Raphael** [comment]
Checked on 1.2.3 on a galaxy s10+, current patchlevel using google chrome: I'm not able to reproduce it there. I'll try it out on 1.3.0~alpha, as soon as I got time to spin up a new test system.

**Comment by ScIT-Raphael** [comment]
Now tested aswell on 1.3.0: Edited user, pressed save + added a new domain -> Save button works properly, not able to reproduce here.
