### ISSUE TITLE
Web UI: Consolidate top right items into one user drop down menu

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1181]
![image](https://user-images.githubusercontent.com/1812594/93004391-82278300-f514-11ea-8cb2-f1dcd2745fad.png)

attached is the items in question. Would it make sense to consolidate all these item in a user drop down menu. It will keep the top bar less cluttered and keep a cleaner feel, but maybe keep notifications bell icon separate from the user drop down menu.

**Comment by johnnyq** [comment]
Maybe look something like this but maybe not in this order.

- Username
  - Disk / Transfer Stats
  - Preferences
  - Server Config (If Admin)
  - Help
  - Submit Issue
  - Logout

**Comment by jaapmarcus** [comment]
Notification Bell, Edit user and Server settings are the most important icons  and it is nice to see in one view the current "Stats/Usage" with out clicking. 

There are I think better ways to improve the layout...

**Comment by ScIT-Raphael** [comment]
I'm cleary not a fan of hiding the logout button in a drop down menu, aswell as I personaly think, that the menu doesnt look to overloaded which would need a modification. But design taste is different for everyone :).

Maybe you want to create a pull request, maybe as a new template if possible, so we can discuss the implementation of your code to default or another template?

I allow myself to close your request for now, but please let me know if you could provide a pr for it - would love to see your idea :).
