### ISSUE TITLE
Mysql external access

### ISSUE THREAD

**Issue by reina3596** [hestiacp/hestiacp#1194]
Hi, 

How I can configure external access form my bbdds??? 

I use Sequel for bbdds. 

Thanks

**Comment by Lupul** [comment]
Use the firewall to a  'Allow' incoming connections from your ip address on the mysql port, and double check mysql is listening on the right interface and not only on localhost (127.0.0.1)

**Comment by ScIT-Raphael** [comment]
Closing because answered :).
