### ISSUE TITLE
Problem with AWS Cloud9

### ISSUE THREAD

**Issue by reina3596** [hestiacp/hestiacp#1197]
Hello,

I have problem installing Cloud9.

Install script intent create a folder /home/user/.c9 but doesnt have permissions.

Can I change owner without problem???

Thanks

**Comment by jaapmarcus** [comment]
See https://forum.hestiacp.com/t/permission-denied-when-creating-files-through-terminal-console/1734/7

Answer is also applicable here...

**Comment by reina3596** [comment]
This solution is not correct.

I do login with root.

I have created /home/user/.c9 folder

I have change permisions to chown user:user /home/user/.c9

With this, I can install AWS Cloud9

**Comment by jaapmarcus** [comment]
Exactly what I told...

mkdir /home/$1/.wp-cli
chown $1:$1 /home/$1/.wp-cli

Except .c9 instead of .wp-cli

**Comment by ScIT-Raphael** [comment]
The solution is correct, but it probaly wasnt written understandable for all - @jaapmarcus has already adjusted the post. Thanks for letting us know and aswell for posting the solution!
