### ISSUE TITLE
Installation Error on Ubuntu 16.04 - Error: nginx start failed

### ISSUE THREAD

**Issue by muratcesmecioglu** [hestiacp/hestiacp#1204]
### In a few words, please describe the issue that you're experiencing:
When i install hestia and it's configuring nginx, it fails. I'm using hestiacp since v1.0.6. It worked flawless until i messed up my VPS yesterday. This time i can't install easily.

My OS is Ubuntu 16.04 x86_64. When i first try, some GPG problems has been appear. I solved them. But configuraton stage, nginx fails.

### What steps did you take when the issue occured? 
1.  Download Hestia
```wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh```

2.  Add some gpg keys
```
curl -O https://nginx.org/keys/nginx_signing.key && apt-key add ./nginx_signing.key
wget -qO - https://gpg.hestiacp.com/deb_signing.key | sudo apt-key add -
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
```

3.  Start install
```bash hst-install.sh -x no```

### Expected behavior:
Complete install without error.

### Operating system:
Ubuntu 16.04

### Hestia Control Panel version:
1.2.3

### Additional notes:

```bash
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait...                                                                                               \

========================================================================

[ * ] Configuring system settings...
[ * ] Configuring Hestia Control Panel...
[ * ] Generating default self-signed SSL certificate...
[ * ] Adding SSL certificate to Hestia Control Panel...
[ * ] Configuring NGINX...
Job for nginx.service failed because a timeout was exceeded. See "systemctl status nginx.service" and "journalctl -xe" for details.
Error: nginx start failed
root@Bobi:~# systemctl status nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Sat 2020-09-19 23:06:20 EDT; 2h 47min ago
     Docs: http://nginx.org/en/docs/
  Process: 2471 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)

Sep 19 23:04:50 Bobi systemd[1]: Starting nginx - high performance web server...
Sep 19 23:04:50 Bobi systemd[1]: nginx.service: Can't open PID file /var/run/nginx.pid (yet?) after start: Too many levels of symbolic links
Sep 19 23:06:20 Bobi systemd[1]: nginx.service: Start operation timed out. Terminating.
Sep 19 23:06:20 Bobi systemd[1]: Failed to start nginx - high performance web server.
Sep 19 23:06:20 Bobi systemd[1]: nginx.service: Unit entered failed state.
Sep 19 23:06:20 Bobi systemd[1]: nginx.service: Failed with result 'timeout'.

```

**Comment by jaapmarcus** [comment]
Is this setup a new clean install?

Maybe check https://linuxx.info/can-t-open-pid-file-var-run-nginx-pid-yet-after-start-too-many-levels-of-symbolic-links/

**Comment by muratcesmecioglu** [comment]
> Is this setup a new clean install?
> 
> Maybe check https://linuxx.info/can-t-open-pid-file-var-run-nginx-pid-yet-after-start-too-many-levels-of-symbolic-links/


Yes, i always format the vps before install. And attempt no.1923...
I will check the link. Thank you.

---
I checked that link and solution #2 will fix nginx service problem BUT i can't make that changes during hestia installation. I will try solution #1.

**Comment by muratcesmecioglu** [comment]
I edited ubuntu install script and add following codes before nginx service start command. It passed. BUT this time fail2ban fails :/

```
sed -i 's/pid                     \/var\/run\/nginx.pid/pid                     \/run\/nginx.pid/' /etc/nginx/nginx.conf
cat /etc/nginx/nginx.conf
read -p "Press any key to resume ..."

sed -i 's/PIDFile\=\/var\/run\/nginx.pid/PIDFile\=\/run\/nginx.pid/' /lib/systemd/system/nginx.service
cat /lib/systemd/system/nginx.service
read -p "Press any key to resume ..."

systemctl daemon-reload
```

**Comment by muratcesmecioglu** [comment]
I couldn't figure out. I installed older version (v1.1) and then update to v1.2.3. 
Maybe because of my VPS setup, i don't know.

**Comment by muratcesmecioglu** [comment]
Fixes that works for me:

Do NOT re-create /var/run symlink, just edit the necessary lines from /var/run to /run

**For nginx:**
edit "/lib/systemd/system/nginx.service" file
find "PIDfile" line 
change from "/var/run/nginx.pid" to "/run/nginx.pid"

edit "/etc/nginx/nginx.conf" file
find "PID" line 
change from "/var/run/nginx.pid;" to "/run/nginx.pid;"

**For ssh:**
edit "/usr/lib/tmpfiles.d/sshd.conf" file
change from    "d /var/run/sshd 0755 root root"
to      "d /run/sshd 0755 root root"

**For fail2ban:**
edit "/lib/systemd/system/fail2ban.service" file
add "ExecStartPre=/bin/mkdir -p /run/fail2ban" before ExecStart= parameter
