### ISSUE TITLE
Upgrade: Replace MariaDB 10.4 with MariaDB 10.5

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#1211]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
MariaDB latest stable is 10.5, thus we should upgrade our current version (10.4)

### Operating system:
All

### Hestia Control Panel version:
1.2.4

**Comment by jaapmarcus** [comment]
https://mariadb.com/kb/en/upgrading-from-mariadb-104-to-mariadb-105/

**Comment by jaapmarcus** [comment]
Will be released with 1.3.0
