### ISSUE TITLE
Change: ssh package dependency

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#1213]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Package ssh is not needed, it's just a metapackage. I suggest to be removed.

### Operating system:
All

### Hestia Control Panel version:
1.2.4

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1214

👍🏻
