### ISSUE TITLE
After HestiaCP v1.2.4 upgrade all websites gives Error 500.

### ISSUE THREAD

**Issue by lautiromero** [hestiacp/hestiacp#1223]
===

### In a few words, please describe the issue that you're experiencing:
After HestiaCP v1.2.4 upgrade all websites gives Error 500.

### What steps did you take when the issue occured? 
1. The error occurs suddenly, but I had notification about HestaiaCP upgarde to 1.2.4.

### Expected behavior:
Normal.

### Operating system:
Ubuntu 18.04.

### Hestia Control Panel version:
1.2.4

### Additional notes:
Apache and nginx services goes down after restart server. I am trying to use the solution of  #1020  , but it doesn't work for me.

**Comment by jaapmarcus** [comment]
We rolled out an update today due to a bug in the renewal of Let's encrypt

What was the old version of Hestia? 1.2.3 

Did you change any of the default templates?

**Comment by lautiromero** [comment]
Hi, when i checking the logs I found an error in line 83 of /etc/apache2/apache2.conf  , instead of `Include conf.d/*.conf` it said `Include conf.d/` , for that reason apache did not start. 

I hope it helps if anyone has the same problem
