### ISSUE TITLE
Hestia CP login keeps looping back to password

### ISSUE THREAD

**Issue by cptmedic** [hestiacp/hestiacp#1224]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When trying to login to admin panel with password provided after install, login page continue to loop back to where you enter password.

### What steps did you take when the issue occured? 
1. Install HestiaCP fresh
2. Reboot Server
3. Go to server_ip:8083
4. Type in admin in username box, click next
5. Paste password in password field, click login
6. Loops back to password box

### Expected behavior:
Would expect it to take me to admin account in Hestia CP

### Operating system:
Ubuntu 18.04 LTS

### Hestia Control Panel version:
1.2.4 release from today

### Additional notes:
Interestingly enough, when I go and install an older version of HestiaCP and then upgrade it to the latest the admin panel works. I feel like part of the issue may relate to the password or not properly creating the admin account. Passwords generated recently have included letters with special characters over them, and i'm not sure if this is causing an issue (e.g. Ô, ß; have been in passwords.

**Comment by cptmedic** [comment]
As an update I checked auth.log for hestia and found that I can use the login command via terminal and it says it logins fine, however, using same user and pass on the panel fails.
`2020-09-21 22:44:33 admin 127.0.0.1 successfully logged in
2020-09-21 22:45:36 admin <myip> failed to login`

**Comment by ScIT-Raphael** [comment]
Hi @cptmedic 

Thanks for the detailed report, the issue has already been fixed for hestia 1.3.0 which is currently in beta state. You'll find all informations in the following issue report: https://github.com/hestiacp/hestiacp/issues/1184

Please let us know, if you'll find out anything else, that doesnt work as expected.

**Comment by emekaorjiani** [comment]
Am still having this issue in Version 1.3.2
I can't login it keeps looping the login screen

**Comment by jaapmarcus** [comment]
Using root / password?

Please use admin / admin_password
