### ISSUE TITLE
Feature Request - Allow SFTP user to ssh

### ISSUE THREAD

**Issue by darkworks** [hestiacp/hestiacp#1233]
**Describe the problem:**
i wonder how can we allow sftp user to ssh into his web directory in case he want to checkout from his git repo.

**Steps to Reproduce:**

- click on web
- click on web domain
- add sftp user
- login to ssh via root ,
- nano /etc/passwd
- find our sftp user we added above
- change its shell from /usr/sbin/nologin to /bin/rbash
- now login to sftp user via ssh , it will login and will auto exit.
- so how to allow sftp users to ssh

**Debian version:**
Debian 10

**Comment by ScIT-Raphael** [comment]
Will be possible as soon as we've inolemented rush: https://github.com/hestiacp/hestiacp/issues/894

Infact the feature request is a duplicate, I'll close it for now.
