### ISSUE TITLE
From API CLI v-add-domain and v-add-domain return 500 error

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1236]
===

### In a few words, please describe the issue that you're experiencing:
From API CLI v-add-web-domain and v-add-domain return 500 error.
Error in v-restart-web-backend.

if commented this lines in v-restart-web-backend file -  all fine (all created)
```
$BIN/v-restart-service "$v_phpfpm" >> $tmpfile 2>&1
    if [ $? -ne 0 ]; then
        send_email_report
       check_result $E_RESTART "$v_phpfpm restart failed"
   fi
```
### What steps did you take when the issue occured? 
1. use API CLI command from php file

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.4

**Comment by jaapmarcus** [comment]
This also applies to 1.3.0~beta

Did some investigating:
```
            $postvars = array(
                'user' => $_POST['admin'],
                'password' => $_POST['password'],
                'returncode' => 'no',
                'cmd' => 'v-restart-service',
                'arg1' => 'php7.3-fpm.service'
            );
```

Is given me the same error.

(Error log where I send the api call from)
[Tue Sep 29 11:18:10.702656 2020] [proxy_fcgi:error] [pid 12487:tid 140657167402752] [client XX.XX.XX.184:0] AH01067: Failed to read FastCGI header, referer: https://dev.domain.nu/
[Tue Sep 29 11:18:10.702720 2020] [proxy_fcgi:error] [pid 12487:tid 140657167402752] (104)Connection reset by peer: [client 84.82.33.184:0] AH01075: Error dispatching request to : , referer: https://dev.domain.nu/

Hestia Domain
First call creates the domain with restart "no"
2nd list and the third executes v-restart-service
127.0.0.1 - - [29/Sep/2020:11:18:10 +0200] POST /api/ HTTP/1.1 "200" 11 "-" "-" "-"
127.0.0.1 - - [29/Sep/2020:11:18:10 +0200] POST /api/ HTTP/1.1 "200" 11 "-" "-" "-"
127.0.0.1 - - [29/Sep/2020:11:18:10 +0200] POST /api/ HTTP/1.1 "**499**" 0 "-" "-" "-"

**Comment by jaapmarcus** [comment]
I think with v-restart-service the thread of the current php thread is stopped an there for an 500 error is shown.

The "easy" fix would be calling the api from an different server. And it would be no issue. 

Don't know if there is a fix for it.

**Comment by ghost** [comment]
> I think with v-restart-service the thread of the current php thread is stopped an there for an 500 error is shown.
> 
> The "easy" fix would be calling the api from an different server. And it would be no issue.
> 
> Don't know if there is a fix for it.

yep, not so good (
Are how this worked in VestaCP? In vesta work fine...

**Comment by jaapmarcus** [comment]
Incase of Apache2 it runs as modphp and there fore not affected the restart

**Comment by alber-khan** [comment]
the patch is already given in 1.3.0 you can also check the PR #1094

**Comment by jaapmarcus** [comment]
The patch giving will prevent restarting Apache / Nginx / PHP from restarting but it you need the restart. It will not happen.

The issue is still there unless you execute the restart command from a different server.

**Comment by alber-khan** [comment]
i think we can reload instead of a restart?

**Comment by jaapmarcus** [comment]
I think this is already done..

https://github.com/hestiacp/hestiacp/blob/f862aaa7d081ce79bfb9807454a3a2442db95cb6/bin/v-restart-service#L42-L67

Just tested replacing "reload-or-restart" with reload doesn't help

**Comment by wojsmol** [comment]
@jaapmarcus I resolved this issue on Hestiacp 1.3.5 by running `v-restart-service` from php script on the same server like this

```php
// Prepare POST query

$postvars = array(
    'hash' => $hst_hash,
    'returncode' => $hst_returncode,
    'cmd' => $hst_command,
    'arg1' => 'php7.4-fpm'
);
```

**Comment by jaapmarcus** [comment]
Version that the website was running was on was also php7.4?

**Comment by wojsmol** [comment]
> Version that the website was running was on was also php7.4?

yes
