### ISSUE TITLE
How to delete a certificate from server.example.com

### ISSUE THREAD

**Issue by pawel06281990** [hestiacp/hestiacp#1237]
Hello,

How can I add a certificate and valid data to a new domain because I get the message "Warning: potential security risk" because the certificate points to a page other than mine.

Please help

### Operating system:
I put the server on Ubuntu 20.04 LTS

### Hestia Control Panel version:
My version of the panel 1.2.4.

**Comment by ScIT-Raphael** [comment]
Tick the add lets encrypt checkbox? But probaly I missunderstood your issue, can you please explain it in detail?

**Comment by pawel06281990** [comment]
My point is that I have the message Warning: potential security risk and if I set a certificate for the domain, the domain will not load at all because I cannot use the API

**Comment by ScIT-Raphael** [comment]
Still a lot of ??? in my head. What for an API you talking about? Are you sure it isnt a caching issue? I just dont know how we should help you here, it dosnt sound like a hestia issue. Maybe you want to visit our discord server? It could probaly be a faster way to understand your issue.

**Comment by pawel06281990** [comment]
Can I write on Discord okay? and describe the problem

**Comment by ScIT-Raphael** [comment]
Thats exactly why discord is here :).
