### ISSUE TITLE
Can't open PHPMYADMIN

### ISSUE THREAD

**Issue by t3rr0rz0n3** [hestiacp/hestiacp#1238]
### In a few words, please describe the issue that you're experiencing:
The URL of the button to access PHPMyAdmin does not work. Load the URL with https://ip.server/phpmyadmin (only works with http)

### What steps did you take when the issue occured? 
In DB tab, clic on PHPMYADMIN button.

### Expected behavior:
You should load phpmyadmin (https://ip_server/phpmyadmin)

### Operating system:
Ubuntu 20.04 (x86_64)

### Hestia Control Panel version:
v1.2.4

**Comment by jaapmarcus** [comment]
Use http://hostname.com/phpmyadmin/

**Comment by t3rr0rz0n3** [comment]
So what's the button for? If the button is useless, it is better to remove it because it misleads the user.

**Comment by CLDNMarcos** [comment]
First of all it is not possible what you say jaapmarcus 
https://docs.hestiacp.com/admin_docs/server_management.html#why-i-can-t-use-http-my-ip-adress-phpmyadmin

As you can see in the manual it is not possible to access with http://hostname.com/phpmyadmin/

The problem is not whether you use hostname or not. The problem is that HestiaCP's PHPMYADMIN button opens https and phpmyadmin works with http

**Comment by ScIT-Raphael** [comment]
Probaly there are some missunderstandings, I'll try to clear a bit up:

Usualy you use v-add-letsencrypt-host directly after installation, then access Hestia over https://hostname.domain.tld:8083 -> https://docs.hestiacp.com/admin_docs/ssl_certificates.html. The docs is probaly missleading in that part, you should always use pma with SSL, you dont want to send your sql passwords over an unencrypted connection, I'll fix it and write "https://host.domain.tld/phpmyadmin".

And the button: As soon as you use the way above, it will automatically use the right way to connect, as already explained https://host.domain.tld/phpmyadmin.

Hope I was able to clear the missunderstandings a bit.

**Comment by CLDNMarcos** [comment]
Ok, we are an IaaS offering servers with HestiaCP. We do an unattended installation with a local hostname so no SSL is generated for HestiaCP. Thanks for the clarifications we will see if we can improve the installation to work with a real random hostname.
