### ISSUE TITLE
Blank dns domain page (/list/dns)

### ISSUE THREAD

**Issue by YVbakker** [hestiacp/hestiacp#1245]
### In a few words, please describe the issue that you're experiencing:
When I try to list dns domains the page is blank

### What steps did you take when the issue occured? 
1. add user account 'test'
2. add domain 'test.local' -> ticked both dns & mail boxes
3. Attempt to load dns domain page /list/dns/ but it stays blank

### Expected behavior:
The /list/dns/ page should list the dns domain I just created (it shows 1 in the menu)

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.0 development snapshot (latest from forum https://forum.hestiacp.com/t/1-3-0-rc-we-need-you/1673)

### Additional notes:
I added another domain with dns box ticked: test.nl, still a blank dns

![Screenshot from 2020-10-02 15-48-19](https://user-images.githubusercontent.com/6083799/94930521-d2b44f80-04c6-11eb-8d85-ebb68a16513a.png)

**Comment by jaapmarcus** [comment]
Please run 

`v-update-sys-hestia-git hestiacp main install`

It will install the last version.

**Comment by YVbakker** [comment]
I see, please excuse me for the inconvenience

**Comment by jaapmarcus** [comment]
It was a bug in the past how ever the test version posted hasn't been build yet. But if you find any bug please go ahead or report it via Discord...

**Comment by ScIT-Raphael** [comment]
Or aswell on github, nothing to excuse here!
