### ISSUE TITLE
Error 403 access denied for styles.css Wordpress 

### ISSUE THREAD

**Issue by mylesgoose** [hestiacp/hestiacp#1255]
When we install a Wordpress site on this server running Hestiacp we are unable to have the webpages load correctly because the style.css file is not loading.

If we try to manually load the file in browser we get this error. "Access Denied You do not have permission to view this page. Please check your credentials and try again. Error Code: 403"

We have followed the procedure on this page to set the permissions and all are correct.
https://www.cyberciti.biz/faq/apache-403-forbidden-error-and-solution/

We have been unable to find the apache web error logs in the last instruction. 

The server is running on ubuntu 20. 

update. to test if it was a fault with my server i setup this system on google cloud platform and it does the same thing does not load CSS information. here is an example of a wordpress site loaded on the google platform. 

I ran this command sudo chmod -r public_html because originally the page would not load and now it loads but still does not load the CSS style sheet.

**Comment by mylesgoose** [comment]
update command "sudo chmod -R 755 public_html "made it work

**Comment by jaapmarcus** [comment]
Don't use file manager to install software currently there is a know bug with the permissions

Replace 
`/usr/local/hestia/web/fm/configuration.php`
 with `https://raw.githubusercontent.com/hestiacp/hestiacp/main/install/deb/filemanager/filegator/configuration.php`
