### ISSUE TITLE
Proxmox connector

### ISSUE THREAD

**Issue by krakazyabra** [hestiacp/hestiacp#1256]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Hi! It'll be perfect to see realization of VPS ordering. Can you add proxmox connector to be able create LXC and CT under hypervisor for customers?

### Additional notes:
This is feature reauest

**Comment by ScIT-Raphael** [comment]
Hestia runs perfectly on lxc/lxd containers, ofcourse also in kvm. Creating a template for proxmox should not be that hard, you can do this with a few steps according their wiki:

KVM/VM: https://pve.proxmox.com/wiki/VM_Templates_and_Clones#Create_VM_Template
LXC/LXD: https://forum.proxmox.com/threads/customize-a-lxc-template.23461/

If you want to have it for your customers, then you'll probaly want to create them on your own - so you can adjust them to your needs.

**Comment by krakazyabra** [comment]
I'm talking not about running panel inside lxc. The idea is to add function of managing lxc/lxd inside panel. If customer wants to order his own VPS instead of web-site hosting. For this purposes will be great add support of pve (f.e.). 
Customer chooses amount of resources he wants (cpu, ram, hdd), panel makes lxc with such parameters for him.

**Comment by ScIT-Raphael** [comment]
I think this feature belongs more to the billing software itself than to hestia, for example whmcs - has already a proxmox connector.
