### ISSUE TITLE
[phppgadmin] Version of PostgreSQL not supported. Please upgrade to version or later.

### ISSUE THREAD

**Issue by KashifHK123** [hestiacp/hestiacp#1258]
### Operating system:
Ubuntu 20.04

### Hestia Control Panel version:
v1.2.4 

### Additional notes:
Version of PostgreSQL not supported. Please upgrade to version or later. I'm not able to access phppgadmin because it not supported, Today Install fresh server with Hestiacp but problem still same.

**Comment by jaapmarcus** [comment]
Suppose it is thePHPgaAdmin that is causing the error?

What is the current version you are using for PHPgaAdmin and PostgeSql version.

Probally we need to switch over a system that doesn't depends on APT

**Comment by jaapmarcus** [comment]
Double: 
https://github.com/hestiacp/hestiacp/issues/728
