### ISSUE TITLE
Cannot set password with some PAM options

### ISSUE THREAD

**Issue by Red3Tango** [hestiacp/hestiacp#1259]
### In a few words, please describe the issue that you're experiencing:
With some installations there are certain checks for passwords through PAM. HestiaCP does not validate and will try to change/set passwords even if unable to.

### What steps did you take when the issue occured? 
1. Install HestiaCP with `-p something`
2. or Change password of any user inside of CP

### Expected behavior:
Should give error if password is not validated through PAM.

### Operating system:
Debian 10 (Buster)

### Hestia Control Panel version:
1.3.0 and 1.2.4

### Additional notes:
On my testing server, the Debian 10 image contained some optional features to "help" with security. Such as in `/etc/pam.d/common-password` there are some directives that were set that will deny any password that includes "dictionary" words. The first line enforces this for all unix accounts, or any other system that uses PAM.

`password	requisite			pam_cracklib.so retry=3 minlen=8 enforce_for_root difok=3 dictpath=/usr/share/dict/common enforce_for_root
password	[success=1 default=ignore]	pam_unix.so obscure use_authtok try_first_pass sha512`

With installing with -p, this does not set a password for the unix usernames. It prevents you from being able to login to the CP. When you enter password, it will loop back to the password page.

**Comment by jaapmarcus** [comment]
You have a point.

root@dev:/etc/pam.d# v-change-user-password admin 123454321
BAD PASSWORD: it is too simplistic/systematic
BAD PASSWORD: is a palindrome
/usr/share/dict/common.pwd: No such file or directory
BAD PASSWORD: error loading dictionary
chpasswd: (user admin) pam_chauthtok() failed, error:
Have exhausted maximum number of retries for service
chpasswd: (line 1, user admin) password not changed

**Comment by jaapmarcus** [comment]
This should fix the issue 

https://github.com/hestiacp/hestiacp/pull/1261

Please not when preforming the install it will fail same way was no "email" is giving...

**Comment by jaapmarcus** [comment]
Merged with staging/fixes
