### ISSUE TITLE
[Feature] Dynamically create DNS records/aliases for Mail services

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1274]
### In a few words, please describe the issue that you're experiencing:

For "Mail" part the default aliases mail and webmail are created by default it would be nice users can select "SMTP". "IMAP", "POP3" as additional aliases where an certificate needs to be generated. 

Also add the option for resolving the domains to make sure the system works fine.

**Comment by ScIT-Raphael** [comment]
as discussed in team chat.
