### ISSUE TITLE
Sorting issue in case of capital letters

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1276]
### In a few words, please describe the issue that you're experiencing:
Sorting is broken when capital letters are in the names

### What steps did you take when the issue occured? 
1. Add users, databases or the like with CaPiTaL LeTtErS (e.g. Test1, test2 and TeSt3)
2. Sort By: 'Username' or 'Database'
3. The order now is incorrect: TeSt3 - Test1 - test2

### Expected behavior:
The order to be correct: Test1 - test2 - TeSt3

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

### Additional notes:
A simple way to go about it is by setting the sort-name tags (as seen in the HTML) to lowercase.

**Comment by jaapmarcus** [comment]
Don't know if it is to to fix as I think it an an limitation of of the "Sort" function of javascript

See 
```
let eris = ["test1","Tast2","1Test","aEst","test","TEST"];
eris.sort();

console.log(eris);
```

["1Test" ,"TEST" ,"Tast2" ,"aEst" ,"test" ,"test1"]

**Comment by snakehill** [comment]
> Don't know if it is to to fix as I think it an an limitation of of the "Sort" function of javascript

Simply convert and render the HTML tags into lowercase, then there is no need to rewrite any JavaScript and it will sort correctly.

Like this:
![likethis](https://user-images.githubusercontent.com/20109369/96430986-2e8b1200-1203-11eb-8d1e-ea7519e6ee13.png)
`v_unit_id="Test1"` `sort-name="test1"`
`v_unit_id="test2"` `sort-name="test2"`
`v_unit_id="TeSt3"` `sort-name="test3"`

**Comment by jaapmarcus** [comment]
Fixed
