### ISSUE TITLE
[Feature Request] Enhanced/Friendlier Sorting

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1277]
### In a few words, please describe the issue that you're experiencing:
If users prefer a certain kind of sorting (e.g. by name), they need to choose it time and time again when navigating the control panel.

### What steps did you take when the issue occured? 
1. Sort anything (e.g. sort Users by Username)
2. Go to any other page (e.g. Web or anywhere else on the internet)
3. Go back to Users
4. Sorting is back to by Date

### Expected behavior:
Remember the sorting by user and list, so that one doesn't need to choose it over and over again.

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

### Additional notes:
Also really nice would be having the same events added to the "table" headers to whatever is sortable, so that we can simply click it (once for ascending, again for descending), like this:
![clickable](https://user-images.githubusercontent.com/20109369/96429192-f551a280-1200-11eb-9d85-ac0a9326c37b.png)

**Comment by ScIT-Raphael** [comment]
We currently close this issue - with the existing system we do not want to implement breadcrumbs. This may be integrated, if we find enough time to do a whole rewrite of the interface.
