### ISSUE TITLE
Add Spamassassin after install

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1279]
I haven't seen any instructions on how to add Spamassassin after the actual install. I was going to try Rspamd but it didn't do anything for me.

**Comment by jaapmarcus** [comment]
Hello Roxy,

Currently we don’t support that it has been planned for a future released to allow adding certain modules in the feature.

However you could try to look at the correct version the installer and follow the instructions made by the installer line for line.

The other option would be doing an reinstall

**Comment by ghost** [comment]
Can I reinstall on an existing install or do I need to reload the whole system? I do believe I have it running but I can’t bring up the config to edit through the control panel.

**Comment by ScIT-Raphael** [comment]
Usualy, a reinstall of the system is the better idea, if you want to run it in productive.
