### ISSUE TITLE
Unusable/unclickable search results

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1280]
### In a few words, please describe the issue that you're experiencing:
When searching and finding results, there is no way to click it to access/edit it.

### What steps did you take when the issue occured? 
1. Search for any domain, DNS, etc in the user's account using the built-in search feature
2. Try to click or access the domain, DNS, etc from there

### Expected behavior:
Being able to click the result and access/edit it from the search.

Hestia (also upon mouseover):
![noclick](https://user-images.githubusercontent.com/20109369/96541536-862b8b00-12a0-11eb-8861-e91fcf25e63a.png)

Vesta (upon mouseover):
![vesta](https://user-images.githubusercontent.com/20109369/96541534-84fa5e00-12a0-11eb-8fea-7da482dc2f87.png)

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

**Comment by jaapmarcus** [comment]
Noticed the last when I went over all scripts

**Comment by ghost** [comment]
The search experience has been updated for v1.4 which will be released soon.
