### ISSUE TITLE
[Feature] Modularize webmail system and improve Web UI controls

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1281]
1. Add the ability to enable/disable webmail on a per-domain basis, exposing existing CLI functionality.
2. To provide more choice, allow the domain administrator to configure which webmail client to deploy for a domain:
    - **Roundcube** - default option and will respect existing installations.
    - **Rainloop** - available as an alternative.

To facilitate this functionality, additional install/upgrade/uninstall commands for upstream versions of Roundcube and Rainloop will need to be added to the backend CLI and then exposed through the Control Panel web interface. As a bonus, this allows us to finally upgrade the default webmail client to RC 1.4.

**Comment by johnnyq** [comment]
Just a big Awesome!!!

**Comment by jaapmarcus** [comment]
> 1. Add the ability to enable/disable webmail on a per-domain basis, exposing existing CLI functionality.
> 2. To provide more choice, allow the domain administrator to configure which webmail client to deploy for a domain:
>    
>    * **Roundcube** - default option and will respect existing installations.
>    * **Rainloop** - available as an alternative.

https://github.com/hestiacp/hestiacp/pull/1548  (Adds support for rainloop )
+
https://github.com/hestiacp/hestiacp/pull/1537 (Adds support for upstream version Roundcube + 1.4.10 (Last version)) 

> 
> To facilitate this functionality, additional install/upgrade/uninstall commands for upstream versions of Roundcube and Rainloop will need to be added to the backend CLI and then exposed through the Control Panel web interface. As a bonus, this allows us to finally upgrade the default webmail client to RC 1.4.

Only thing left if  disable we might add an disabled "Option"?

<img width="507" alt="Screenshot 2021-01-10 at 14 14 33" src="https://user-images.githubusercontent.com/9754650/104148537-e844e980-53d2-11eb-8cea-b7c99007fd06.png">

Also added support for future other webmail clients proposed by the community.

**Comment by jaapmarcus** [comment]
Issue can be closed all features has been implemented. Didn't update the issue yet.
