### ISSUE TITLE
Missing changes saved indicator for Web

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1285]
### In a few words, please describe the issue that you're experiencing:
When saving web domain edits, no indicator shows. This is upon a successful save:
![web](https://user-images.githubusercontent.com/20109369/96769780-dd844500-13df-11eb-8139-07506a345e40.png)

### What steps did you take when the issue occured? 
1. Click any domain under Web
2. Make any or even no change
3. Click 'Save'
4. In case of a successful save, the page merely refreshes with the edits in place, but no successful 'Changes have been saved' message shows.

### Expected behavior:
Like under Mail Domains and DNS Zones, it should show a 'Changes have been saved' message, so that the user knows it has actually saved:

![mail](https://user-images.githubusercontent.com/20109369/96769979-30f69300-13e0-11eb-9fd1-d1896ea13624.png)

![dns](https://user-images.githubusercontent.com/20109369/96769989-33f18380-13e0-11eb-8692-ce813b7e1396.png)

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

**Comment by jaapmarcus** [comment]
You have a point. Don't know why the decision has been been made but we should be able to change it. Will wait until 1.3.0 has been released.

**Comment by ghost** [comment]
This is certainly a bug as the necessary code to render the element exists in the templates (edit_web.html), however no status is being piped back to trigger message from my limited testing so far.

**Comment by jaapmarcus** [comment]
Fixed

**Comment by Lupul** [comment]
just a heads-up: https://github.com/hestiacp/hestiacp/commit/65e8b73dd356e9748681d30836e1cf19ac195dd2#diff-046fe8083de2316bf7b17cf104eff84a9bf6f3dc3b5cb8c4b3ef59fc0b67e6b8
