### ISSUE TITLE
Incorrect database name/username preview

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1286]
### In a few words, please describe the issue that you're experiencing:
The previews showing upon Database creation are incorrect if they include the prefix.

### What steps did you take when the issue occured? 
1. Create a database with **username_** in the database name or username as prefix
2. The preview behind the field shows it without prefix
3. Click Save
4. The database has been created with prefix, opposed to the preview

Hereby the preview without the literal **username_** prefix in the input:
![test1](https://user-images.githubusercontent.com/20109369/96932618-6f16b400-14bf-11eb-8fe7-6254268974c3.png)

However, as soon as it contains the literal **username_** prefix in the input, the preview shows as such:
![test2](https://user-images.githubusercontent.com/20109369/96932648-7dfd6680-14bf-11eb-8e70-0c83199d58f9.png)

But upon creation, it saves it like this:
![test3](https://user-images.githubusercontent.com/20109369/96932703-966d8100-14bf-11eb-96d9-39108dd30481.png)

![test4](https://user-images.githubusercontent.com/20109369/96932728-9ff6e900-14bf-11eb-8ced-f840eef0c4da.png)

### Expected behavior:
Either the preview should be correct (**username_username_name**), or the database should be saved with the name and username that showed in the preview (**username_name**).

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

**Comment by jaapmarcus** [comment]
Just checked still exists in 1.3.0~beta

Need to investigate how to solve it it is probally something wrong with the code.

**Comment by ghost** [comment]
Fix has been included for 1.3.1 with #1294
