### ISSUE TITLE
Imported/restored mail folders: 'An error occured'

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1287]
### In a few words, please describe the issue that you're experiencing:
Upon importing/restoring mail domains from a backup (in my case from Vesta), some folders in Roundcube show a "Server Error: STATUS: Internal error occured. Refer to server log for more information." error.

![error](https://user-images.githubusercontent.com/20109369/97001103-1afbe600-1538-11eb-99a4-d3c93d8177d3.png)

The server logs show nothing about it nor anything remotely related at all.

### What steps did you take when the issue occured? 
1. Restore a Vesta backup with mail domains
2. Login to the webmail/Roundcube
3. Navigate to a folder. In my case it's 4 out of 5 times the 'Archive' folder showing the error.

### Expected behavior:
No error, with the e-mails loading properly.

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

### Additional notes / a fix:
It seems to do with the user rights of the mail domain folders. I fixed it by doing this:

`cd /home/[user]/mail/[domain]`
`chown -hR [user]:mail [mailbox]/`

For example for `box@test.com` under user `admin`:
`cd /home/admin/mail/test.com`
`chown -hR admin:mail box/`

It'd be prefered if the rights are checked and set automatically upon v-restore-user.

**Comment by jaapmarcus** [comment]
I think it is already fixed for 1.3.0. 

https://github.com/hestiacp/hestiacp/commit/05f41259acef142e44ba8f0b2c725c1539bf5927#diff-d7fe3f4f254cc99e8ae74d30a038d3eb8c9fb831fb278e8582aadc2db5a5228a

To lazy to search for PR... But I am going to close it :)

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/issues/1095
