### ISSUE TITLE
Infinite loop of daily backup results in full disk space

### ISSUE THREAD

**Issue by LiMoon** [hestiacp/hestiacp#1288]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:

My system has a database installed, but the database was removed later.
But now the daily backup situation is
1. WEB backup completed
2. DB (because mariadb is removed, but the backup cannot be read)

after removing mariadb, do I need to delete the data in the DB to back up successfully?
and `sudo apt-get purge mariadb-server`?

Because 2. DB backup cannot be read, now the backup will loop back and back up from the beginning

### What steps did you take when the issue occured? 
1. Ex.: Click on the Web tab
2. Ex.: Click on Add Web Domain
3. Ex.: Attempted to add a domain and received an Internal Server Error.

### Expected behavior:
Please enter your answer here (e.g. the web domain should have been added successfully).

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.4

**Comment by jaapmarcus** [comment]
When you open
/usr/local/hestia/conf/hestia.conf 

And replace DB_SYSTEM='mysql' with DB_SYSTEM=''

What happens then?

**Comment by LiMoon** [comment]
Sorry, the English is not good, I used Google to translate it

> When you open
> /usr/local/hestia/conf/hestia.conf
> 
> And replace DB_SYSTEM='mysql' with DB_SYSTEM=''
> 
> What happens then?

Haven't tried it yet, the current host is not a test host, and will be tested next time.

**Comment by LiMoon** [comment]
Solution:
1. The mariadb database is installed back
2. After deleting the data in the database, remove the mariadb database
3. v-backup-user is working

---
Perhaps the script of the backup mechanism may need to be added...
If the database service is not start, should skip the database backup.

**Comment by jaapmarcus** [comment]
We are planning to create a modular system where you can "remove" certain functions. It will be not in the next release but probably in 1.4.0

**Comment by ScIT-Raphael** [comment]
Infact removing the database service manualy, I'll close this issue now because it isnt directly related to hestia. As @jaapmarcus already wrote, disabling mysql/mariadb in DB_SYSTEM would have skipped the db backup function.
