### ISSUE TITLE
Restart not working for some services

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1289]
### In a few words, please describe the issue that you're experiencing:
When clicking the restart icon on some services in /list/server/, they simply don't restart. Stop and start still works, restart refreshes the page but without the service restarting.

I can't restart any of the following:
- php-fpm
- nginx
- dovecot
- vsftpd
- fail2ban

![restart](https://user-images.githubusercontent.com/20109369/97033150-2a445900-1563-11eb-8d09-b30897f5f302.png)

### What steps did you take when the issue occured? 
1. On [ip]:8083/list/server/, click the restart icon on any of these services
2. The page refreshes but the service has not restarted

### Expected behavior:
The service restarting.

If the service cannot (or should not be able to) be restarted, the arrow should either not show or be unclickable/greyed out. However, as one can stop and start the service (using the pause/play icon), it leads me to believe they should be able to be restarted also.

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

### Additional notes / possible a bigger issue:
It seems that upon making a change to any Additional FTP user under a Web domain, vsftpd sometimes doesn't restart and thus the changes don't reflect with the FTP completely breaking (timing out).

That is when I figured the restart issue, as I wanted to restart vsftpd but it didn't do anything. Stopping and starting the service did work.

**Comment by Lupul** [comment]
Any errors when restarting from cli with `v-restart-service nginx` ?

**Comment by snakehill** [comment]
> Any errors when restarting from cli with `v-restart-service nginx` ?

No errors, but it doesn't restart nginx either (not the timer displayed in the CP, nor the service which shows it is still running). Opposed to `systemctl restart nginx`.

However, maybe it's a graceful restart (reload) as I just found out these don't reset the service or timer either.

No such luck with vsftpd though. `v-restart-service vsftpd` doesn't do anything, while `systemctl restart vsftpd` does work. Actually, it seems exactly like the nginx restart, which leads me to believe that is not a graceful reload either.

**Comment by jaapmarcus** [comment]
By default it executes an reload...

https://github.com/hestiacp/hestiacp/blob/main/bin/v-restart-service#L63

**Comment by snakehill** [comment]
> By default it executes an reload...
> 
> https://github.com/hestiacp/hestiacp/blob/main/bin/v-restart-service#L63

So it actually is graceful then. But for vsftpd that apparently doesn't do anything. I think something is wrong with that too (perhaps worth its own issue instead). Each time I make a change to an Additional FTP user (directory change or such), I manually need to restart (or stop/start in case of within the panel) the service.

**Comment by snakehill** [comment]
As for the restarts, maybe there should be a success message saying the service has in fact restarted (or reloaded/restarted gracefully). Given the timer doesn't reset for those services, it's impossible to tell something actually happened.

**Comment by ghost** [comment]
Can you please run `wget -O $HESTIA/bin/v-restart-service https://raw.githubusercontent.com/hestiacp/hestiacp/fix/1289_v-restart-service/bin/v-restart-service && chmod +x $HESTIA/bin/v-restart-service`, then restart vsftpd from the Control Panel UI to see if it corrects the issue you're experiencing?

**Comment by snakehill** [comment]
At least the following still don't visibly restart when clicking said button. No timer reset (and no success message obviously). It could be more but it's hard to tell as of course some services are tied and restarting together:

- php-fpm
- nginx
- dovecot
- ssh
- iptables
- fail2ban

vsftpd now restarts fine via /list/server/ now, but not when adding an additional FTP user still.

**Comment by ghost** [comment]
Issue has been resolved in v1.4.
