### ISSUE TITLE
IPTables changes in Ubuntu 20.04 causing issues

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1293]
### In a few words, please describe the issue that you're experiencing:
Changes has been made regarding saving location see https://forum.hestiacp.com/t/iptable-showing-but-not-activated/1890/6

### Expected behavior:
IPtables should be loaded that currently isn't 

### Operating system:
20.04 LTS

### Hestia Control Panel version:
1.2.4 > 

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by pihentagy** [comment]
Maybe changing the path of iptables from `/sbin/` to `/usr/sbin/` caused the problem.

**Comment by jaapmarcus** [comment]
Fixed @cmstew  for fixing ❤️
