### ISSUE TITLE
Unexisting domain shows SSL certificate from another domain

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1295]
### In a few words, please describe the issue that you're experiencing:
When going to an unexisting subdomain for one domain, it exposes the SSL Certificated for a completely different domain.

### What steps did you take when the issue occured? 
1. Set up any domain with SSL (e.g. `test.com` and `try.com` with just `www` aliases)
Go to any unexisting subdomain (e.g. `https://nothing.test.com` or `https://nothing.try.com`)
2. It displays an invalid certificate warning. The subject of this certificate is another domain, possibly even one set up on a entirely different IP address within the server.

"This server could not prove that it is **nothing.test.com**; its security certificate is from **try.com**."

### Expected behavior:
Preferably there should be no certificate showing at all. At the very most (an invalid) one of the domain itself, but not a certificate with information of another domain.

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

**Comment by snakehill** [comment]
Apparently this was a mistake in my nginx configuration (nginx.conf). The default configuration actually already seems to prevent this.

**Comment by snakehill** [comment]
Apologies for the closing/reopening. I thought I had made a mistake myself, but no, the case stands as is.

**Comment by jaapmarcus** [comment]
I know we have changed this behaviour in 1.3.0 

See https://github.com/hestiacp/hestiacp/issues/1103

**Comment by snakehill** [comment]
> I know we have changed this behaviour in 1.3.0
> 
> See #1103

I can't believe I either didn't find or overlooked that particular issue while searching for pretty much anything with SSL. Thanks!!
