### ISSUE TITLE
SMTP Banner sending main IP hostname

### ISSUE THREAD

**Issue by cmstew** [hestiacp/hestiacp#1299]
Steps to Reproduce:

1. Setup second ip for mail
2. Configure rdns
3. Configure DNS
4. Run `telnet hostname 25` from outside the server ( where hostname is the rdns value of second ip)
5. Receive response with the hostname of main ip

I've already found the problem, but the solution needs more thought. The problem is that the exim config file has this line in it:
`smtp_banner = $smtp_active_hostname`.

It needs to be adjusted to return the hostname of the ip that the connection is made to similar to what we did with the mailhelo.conf file.

**Comment by snakehill** [comment]
How simple and great would it be if we would have an SMTP banner field when setting up and editing the IP address? 

Then just set those values into mailhelo.conf, used by exim accordingly.

Mock-up:
![smtpbanner](https://user-images.githubusercontent.com/20109369/97257318-d2814880-1815-11eb-83cb-43a3a48e9fa0.png)
