### ISSUE TITLE
[fix for error]  server certificate does not include an id which matches the server name

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1300]
change server name in the IP.conf generated for apache with localhost instead of the IP as shown below stops the error logs from having "server certificate does not include an id which matches the server name" 1000 times a day. This don't change much as the error is not a big deal. but it fills the logs and can hide a real error in that log file.

Listen 192.168.1.45:8443
Listen 192.168.1.45:8080
<VirtualHost 192.168.1.45:8080>
    ServerName localhost
    DocumentRoot /var/www/html/
    Alias /error/ /var/www/document_errors/

</VirtualHost>

<VirtualHost 192.168.1.45:8443>
    ServerName localhost
    DocumentRoot /var/www/html/
    Alias /error/ /var/www/document_errors/

    SSLEngine on
    SSLVerifyClient none
    SSLCertificateFile         /usr/local/hestia/ssl/certificate.crt
    SSLCertificateKeyFile      /usr/local/hestia/ssl/certificate.key
    
</VirtualHost>

**Comment by erikdemarco** [comment]
@vontainment  I also got the same error on fresh install hestiacp. How do you fix this?

**Comment by ghost** [comment]
I got it fixed a few different times a few different ways but then eventually just start doing it again. Nothing I have any effect on anything except for it's writing to a log for no reason all day... When I found online I think it's as a quark of Apache
