### ISSUE TITLE
v-change-domain-owner typo'd errors despite working

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1308]
### In a few words, please describe the issue that you're experiencing:
When doing v-change-domain-owner on domains that I imported from a Vesta backup, I keep getting the following:
![errors](https://user-images.githubusercontent.com/20109369/97321208-ea38eb00-186e-11eb-93be-a1f20f22f2b2.png)

Despite the 10+ (usually 11-13) errors, it still works just fine, without ever saying it did succeed.

Besides, the error itself is either incorrect or very convoluted with the double negative: **"no doesn't"** so that would need a fix also.

### What steps did you take when the issue occured? 
1. Successfully restored a Vesta backup
2. Created a user in Hestia
3. v-change-domain-owner [domain.com] [newuser]

### Expected behavior:
No errors, or at least after any error ending with a success message if it worked anyways.

### Operating system:
Debian 10

### Hestia Control Panel version:
Please enter your answer here (e.g. 1.3.0). 1.3.0

**Comment by ghost** [comment]
Fixed in #1312
