### ISSUE TITLE
IP is in use / SYS_USERS error

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1309]
### What steps did you take when the issue occured? 
1. v-change-domain-owner multiple domains to another user (in my case 4 domains)
2. Check $HESTIA/data/ips/[ip.address]
3. It keeps adding users and doesn't take away the previous domain owner

![multip](https://user-images.githubusercontent.com/20109369/97323557-371dc100-1871-11eb-81c5-ef964222419a.png)

This also means that when you remove the IP from all domains, it's said to be in use still (in this case by user 'host', which in case of the above screenshot would be user 'admin', not having anything with the IP connected anymore):
![unknown](https://user-images.githubusercontent.com/20109369/97323718-62081500-1871-11eb-97d0-411e6717fa75.png)

### Expected behavior:
Removing the previous owner if these doesn't have any domains left with the IP, and probably adding users to U_SYS_USERS just once.

### Operating system:
Debian 10

### Hestia Control Panel version:
1.3.0

**Comment by jaapmarcus** [comment]
Bug fix has been merged and released in 1.3.1 Closing the issue
