### ISSUE TITLE
New update 1.3 Asking to remove admin user - Closed update instructions not included in readme

### ISSUE THREAD

**Issue by liamgibbins** [hestiacp/hestiacp#1310]
Hi,
Following the steps to update to 1.3.0 on the installation "bash hst-install.sh" it comes back with an error to remove admin before installing.

Admin is not logged in so I ran it with the -f flag.
hope this is right?

It just flat failed and now no websites are working.

I knowtest it in the readme file is says needs a new clean OS so its time to reinstall the server I am guessing...

going to take weeks to get all the backups and stuff back onto the server again.

**Comment by snakehill** [comment]
Did you want to update or install? Updating should be done with apt update && apt upgrade

**Comment by ScIT-Raphael** [comment]
NEVER run the installer twice, expect you know what you're doing! Update will be triggered over apt update && apt upgrade as @snakehill has proberly written above. No issue -> closed.

**Comment by liamgibbins** [comment]
> Did you want to update or install? Updating should be done with apt update && apt upgrade

Ahhh maybe update the readme with a section on to update do this... would be more clear for me and others new to this CP, not only that it gives full instructions for upgrade and fresh install and would in return avoid cluttering the forum and issue tracker with these sort of issues.

Anyways it stuffed up my websites etc so having to fresh install now anyway.

anyhow thankyou for your replies.
