### ISSUE TITLE
Please put upgrade instructions in readme. thanx

### ISSUE THREAD

**Issue by liamgibbins** [hestiacp/hestiacp#1311]
the readme should list 2 lines:
To update:
Do a system update and upgrade.

This would avoid unessacery mistakes and would make for a more complete changelog.
also stop people making the same mistake as me (never make the assumption people know what there doing or know as much as you or others do where not all system administrators and coding kings) lol...

Just a thought.

**Comment by YVbakker** [comment]
Hi Liam,

Isn't doing a system update the same as doing an update? It would be the same as saying: to walk, use your legs to walk.

Also as far as I know Hestia updates automatically, and this can also be controlled through the panel and command line.
On top of that:
> never make the assumption people know what there doing or know as much as you or others do where not all system administrators and coding kings

Yeah the Hestia team kind of does make that assumption, and they clearly state that for example [here](https://forum.hestiacp.com/t/please-read-this-before-you-start/383)

Aside from that I do think the panel is currently quite user friendly, even for those without much sysadmin experience. It's usually the people that are trying to learn more, or think they already know, that break stuff or get unintended results.

But that's also just a thought

**Comment by liamgibbins** [comment]
Wooh no need to get like that, it was only a suggestion to make a better and new user friendly update to a template for the read me file.

Wow leaving constructive criticism is fine but without attitude always helps development of software, trust me I have contacts in many development projects.. 

Anyway that's enough from me, just thought I would charm in with a way to help new users as there is many different ways to update or auto update software. With such a simple and often overlooked way.

**Comment by YVbakker** [comment]
Hi Liam, all I was doing was indeed leaving constructive feedback. Nothing personal in there as far as my intentions go. Also reading back your original message I still think my response was entirely valid. Based off of the formatting of your issue title and choice of words within I can understand you might've interpreted it like you describe, and I'm sorry you feel that way.

I do agree with proper documentation, and the fact that it is often easy to produce and often overlooked (skipped).
Anyway, I am not part of the Hestia team, as stated before just sharing my thoughts as well.

**Comment by liamgibbins** [comment]
I do agree hestiacp is awesome, new user friendly and is surprisingly active.

Compaired to others like Vesta, sentora etc that where great in there day, activity dropped off and they never seemed to recover from that..

This is where Hestia fits in, active, user friendly and has an extremely bright future with such an active Dev group and community that reports bugs and suggests features that are actively viewed and viewed for inclusion where appropriate.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/commit/03aa2c803dcd9b832c393823ef02fbb84c43fe9b

Done
