### ISSUE TITLE
Failed install on ubuntu 20.04.1 - Errors were encountered while processing:  hestia-php

### ISSUE THREAD

**Issue by special2k5** [hestiacp/hestiacp#1312]
the first log
Reading package lists...
Building dependency tree...
Reading state information...
dirmngr is already the newest version (2.2.19-3ubuntu2).
dirmngr set to manually installed.
gnupg is already the newest version (2.2.19-3ubuntu2).
gnupg set to manually installed.
wget is already the newest version (1.20.3-1ubuntu1).
wget set to manually installed.
ca-certificates is already the newest version (20190110ubuntu1.1).
ca-certificates set to manually installed.
curl is already the newest version (7.68.0-1ubuntu2.2).
curl set to manually installed.
software-properties-common is already the newest version (0.98.9.2).
software-properties-common set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1708 B of archives.
After this operation, 160 kB of additional disk space will be used.
Get:1 http://de.archive.ubuntu.com/ubuntu focal-updates/universe amd64 apt-transport-https all 2.0.2ubuntu0.1 [1708 B]
Fetched 1708 B in 0s (25.5 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%>
Preparing to unpack .../apt-transport-https_2.0.2ubuntu0.1_all.deb ...
Unpacking apt-transport-https (2.0.2ubuntu0.1) ...
Setting up apt-transport-https (2.0.2ubuntu0.1) ...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  libargon2-1 libidn2-0 libpcre2-8-0 libpcre3 libssl1.1 libxml2 openssl
7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3607 kB of archives.
After this operation, 92.2 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 libpcre3 amd64 2:8.44-2+ubuntu20.04.1+deb.sury.org+1 [240 kB]
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 libidn2-0 amd64 2.3.0-1+ubuntu20.04.1+deb.sury.org+2 [68.7 kB]
Get:3 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 libpcre2-8-0 amd64 10.35-5+ubuntu20.04.1+deb.sury.org+1 [201 kB]
Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 libargon2-1 amd64 0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1 [19.5 kB]
Get:5 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal/main amd64 libssl1.1 amd64 1.1.1g-1+ubuntu20.04.1+deb.sury.org+1 [1534 kB]
Get:6 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 libxml2 amd64 2.9.10+dfsg-5+ubuntu20.04.1+deb.sury.org+3 [710 kB]
Get:7 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal/main amd64 openssl amd64 1.1.1g-1+ubuntu20.04.1+deb.sury.org+1 [833 kB]
Preconfiguring packages ...
Fetched 3607 kB in 1s (4436 kB/s)
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%>
Preparing to unpack .../libpcre3_2%3a8.44-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libpcre3:amd64 (2:8.44-2+ubuntu20.04.1+deb.sury.org+1) over (2:8.39-12build1) ...
Setting up libpcre3:amd64 (2:8.44-2+ubuntu20.04.1+deb.sury.org+1) ...
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%>
Preparing to unpack .../libidn2-0_2.3.0-1+ubuntu20.04.1+deb.sury.org+2_amd64.deb ...
Unpacking libidn2-0:amd64 (2.3.0-1+ubuntu20.04.1+deb.sury.org+2) over (2.2.0-2) ...
Setting up libidn2-0:amd64 (2.3.0-1+ubuntu20.04.1+deb.sury.org+2) ...
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%>
Preparing to unpack .../libpcre2-8-0_10.35-5+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libpcre2-8-0:amd64 (10.35-5+ubuntu20.04.1+deb.sury.org+1) over (10.34-7) ...
Setting up libpcre2-8-0:amd64 (10.35-5+ubuntu20.04.1+deb.sury.org+1) ...
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%>
Preparing to unpack .../libargon2-1_0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libargon2-1:amd64 (0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1) over (0~20171227-0.2) ...
Preparing to unpack .../libssl1.1_1.1.1g-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1g-1+ubuntu20.04.1+deb.sury.org+1) over (1.1.1f-1ubuntu2) ...
Preparing to unpack .../libxml2_2.9.10+dfsg-5+ubuntu20.04.1+deb.sury.org+3_amd64.deb ...
Unpacking libxml2:amd64 (2.9.10+dfsg-5+ubuntu20.04.1+deb.sury.org+3) over (2.9.10+dfsg-5) ...
Preparing to unpack .../openssl_1.1.1g-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb ...
Unpacking openssl (1.1.1g-1+ubuntu20.04.1+deb.sury.org+1) over (1.1.1f-1ubuntu2) ...
Setting up libssl1.1:amd64 (1.1.1g-1+ubuntu20.04.1+deb.sury.org+1) ...
Setting up libargon2-1:amd64 (0~20190702-0.1+ubuntu20.04.1+deb.sury.org+1) ...
Setting up openssl (1.1.1g-1+ubuntu20.04.1+deb.sury.org+1) ...
Setting up libxml2:amd64 (2.9.10+dfsg-5+ubuntu20.04.1+deb.sury.org+3) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...

and runinng the script again 

Reading package lists...
Building dependency tree...
Reading state information...
dirmngr is already the newest version (2.2.19-3ubuntu2).
gnupg is already the newest version (2.2.19-3ubuntu2).
wget is already the newest version (1.20.3-1ubuntu1).
ca-certificates is already the newest version (20190110ubuntu1.1).
curl is already the newest version (7.68.0-1ubuntu2.2).
software-properties-common is already the newest version (0.98.9.2).
apt-transport-https is already the newest version (2.0.2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up hestia-php (7.4.11) ...
dpkg: error processing package hestia-php (--configure):
 installed hestia-php package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-php

and after apt update 
Setting up hestia-php (7.4.11) ...
dpkg: error processing package hestia-php (--configure):
 installed hestia-php package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-php
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@srv1:~#

it seems always to stop on hestia-php package

===

### What steps did you take when the issue occured? 
run the bash script to install 1.3.0 on a clean ubuntu 20,04 install

### Expected behavior:
Please enter your answer here (e.g. the web domain should have been added successfully).

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
try to install 1.3.0

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by ScIT-Raphael** [comment]
Thanks for the report, we're already working on a fix.

**Comment by special2k5** [comment]
Thank you very much for your effort

**Comment by liamgibbins** [comment]
As I put in an issue Report

It also fails on all supported Ubuntu versions and debain 9 and 10

**Comment by liamgibbins** [comment]
Thank you for your time.. :)

**Comment by ScIT-Raphael** [comment]
It is a known issue due to the rework of hestia-php today, we're just preparing a new version of that package right now.

**Comment by ScIT-Raphael** [comment]
The issue has been fixed, our test installation with ubuntu and debian (current versions) went trough properly. I'll close the issue, but please @liamgibbins and @special2k5 spin up a new installation aswell - just to be sure :).
