### ISSUE TITLE
File Manager logo missing

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1317]
The logo (shown as illustrated below in the top left corner of the File Manager) is now missing (incorrectly rendered) after upgrading from 1.2.4 to 1.3.0.

![image](https://user-images.githubusercontent.com/40798553/97392456-90f9a780-18c0-11eb-9def-7c6b51b6f930.png)

**Comment by lunargrizzly** [comment]
I can fix it if you want)

**Comment by ghost** [comment]
@robothemes if you can submit a PR that would be fantastic.

**Comment by lunargrizzly** [comment]
I don't know how to link pull request for this issue.

**Comment by jaapmarcus** [comment]
Thanks fixed for 1.3.1
