### ISSUE TITLE
Restore backup error user exists on new installation

### ISSUE THREAD

**Issue by liamgibbins** [hestiacp/hestiacp#1321]
On a fresh install when you restore a a user from command line it generates a error "user exists".
no users in the users list in the cp apart from admin

logfile shows: 
Logfile: 
2020-10-28 12:48:29 v-restore-user  'RhiannonG' 'RhiannonG.2020-10-27_05-20-31.tar' [Error 3]
2020-10-28 12:48:30 v-restore-user  'RhiannonG' 'RhiannonG.2020-10-27_05-20-31.tar' [Error 4]

===

### In a few words, please describe the issue that you're experiencing:
Can not restore any users as it comes up with user exists even when restoring on a clean install

### What steps did you take when the issue occured? 
1. log into server with root
2. upload backup into backup folder and make sure permissions are correct
3. use command v-restore-user user filename

### Expected behavior:
Restore user from previous version backup

### Operating system:
debain 10

### Hestia Control Panel version:
1.3.0

**Comment by ScIT-Raphael** [comment]
This has been already discussed in dev chat and is a known and fixed bug: https://github.com/hestiacp/hestiacp/pull/1319/files

We will ship a patch shortly.
