### ISSUE TITLE
PHP Default backend template error after update

### ISSUE THREAD

**Issue by julianarmando** [hestiacp/hestiacp#1322]
I'm using Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-52-generic x86_64)

Hestia Control Panel 1.3.0 (amd64)
Hestia PHP 7.4.11 (amd64)
Hestia Nginx 1.19.3 (amd64)

After update last night, sites using the default back-end template no work anymore, I see this error in the log 

`AH01144: No protocol handler was valid for the URL /index.php (scheme '|fcgi'). If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.`

I solve it changing from backend template php-fpm **Default** to **PHP-7_4**

The web statistics option is disabled

Thanks :)

**Comment by ScIT-Raphael** [comment]
Could you provide us the output of v-list-sys-php?

**Comment by julianarmando** [comment]
> v-list-sys-php

VERSION
--------
5.6
7.0
7.1
7.2
7.3
7.4

**Comment by ScIT-Raphael** [comment]
Hmm, still feels like the "webalizer-bug" - do you still have a domain which you could test the issue? Basicly change the stats to awstats or even just hit save on the domain - without changing the fpm template.

**Comment by ScIT-Raphael** [comment]
Also please post the upgrade log from /root/hst_backup_xxx, maybe we have more log informations there.

**Comment by brackenhill-mob** [comment]
I had exactly the same error. My solution was to set this to PHP_7.3 (only one in v-list-sys-php) and then set it back to default. Something screwy in the update

Here's my log - hope it's useful

==============================================================================
Hestia Control Panel Software Update Log
==============================================================================

OPERATING SYSTEM:      Ubuntu (20.04)
CURRENT VERSION:       1.2.4
NEW VERSION:           1.3.0
RELEASE BRANCH:        release
BUILD TYPE:            Production release

INSTALLER OPTIONS:
=============================================================================
Send email notification on upgrade complete:      
Send installed log output to admin email:         

=============================================================================
[ ! ] Performing system health check before proceeding with installation...  
[ ! ] Adding missing variable to hestia.conf: DISK_QUOTA ('no')
[ ! ] Adding missing variable to hestia.conf: UPGRADE_SEND_EMAIL ('true')
[ ! ] Adding missing variable to hestia.conf: UPGRADE_SEND_EMAIL_LOG ('false')
[ * ] Health check complete. Starting upgrade from 1.2.4 to 1.3.0...
=============================================================================
[ * ] Backing up existing templates and configuration files...

[ - ] Now applying any necessary patches from version v1.3.0...
[ * ] Updating default writable folders for all users...
[ * ] Updating nginx configuration...
[ * ] Updating exim4 configuration...
[ * ] Restricting access to /proc fs...
[ * ] Setting zstd backup compression type as default...
[ * ] Updating configuration file: hestia.conf...
[ * ] Updating File Manager configuration...
[ ! ] Updating default web domain templates...
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
[ ! ] Updating default mail domain templates...
[ ! ] Updating default DNS zone templates...
[ * ] Upgrading phpMyAdmin to version v5.0.4...
=============================================================================
Installation tasks complete, performing clean-up...                          
=============================================================================
[ * ] Rebuilding user accounts and domains, this may take a few minutes...
      - admin...
      - sc...
[ * ] Restarting services...

=============================================================================
UPGRADE COMPLETE.                                                            
Please report any issues on GitHub:                                          
https://github.com/hestiacp/hestiacp/issues                                  
=============================================================================

**Comment by julianarmando** [comment]
> Some body able to do
> 
> cd /usr/local/hestia/data/templates/web/php-fpm
> ls -lah
> 
> -rw-r--r-- 1 root root 943 Oct 27 09:56 default.tpl
> -rw-r--r-- 1 root root 927 Oct 27 09:56 no-php.tpl
> -rw-r--r-- 1 root root 903 Oct 27 09:56 PHP-7_3.tpl
> -rw-r--r-- 1 root root 903 Oct 27 09:56 PHP-7_4.tpl
> -rw-r--r-- 1 root root 922 Oct 27 09:56 socket.tpl

total 44K
drwxr-xr-x 2 root root 4.0K Sep 21 18:32 .
drwxr-xr-x 9 root root 4.0K Oct 28 03:20 ..
-rw-r--r-- 1 root root  903 Oct 28 03:20 PHP-5_6.tpl
-rw-r--r-- 1 root root  903 Oct 28 03:20 PHP-7_0.tpl
-rw-r--r-- 1 root root  903 Oct 28 03:20 PHP-7_1.tpl
-rw-r--r-- 1 root root  903 Oct 28 03:20 PHP-7_2.tpl
-rw-r--r-- 1 root root  903 Oct 28 03:20 PHP-7_3.tpl
-rw-r--r-- 1 root root  903 Oct 28 03:20 PHP-7_4.tpl
-rw-r--r-- 1 root root  943 Oct 28 03:20 default.tpl
-rw-r--r-- 1 root root  927 Oct 28 03:20 no-php.tpl
-rw-r--r-- 1 root root  922 Oct 28 03:20 socket.tpl

**Comment by julianarmando** [comment]
> Hmm, still feels like the "webalizer-bug" - do you still have a domain which you could test the issue? Basicly change the stats to awstats or even just hit save on the domain - without changing the fpm template.

I think the problem is solved, I just hit on save bottom in the domain.

Now if I change again the domains to default in backend template, the problem not appears, I have no way to test the problem now, I have update all my domains :/

**Comment by julianarmando** [comment]
> Also please post the upgrade log from /root/hst_backup_xxx, maybe we have more log informations there.

In /root/hst_backups/281020200320 I found this...

=============================================================================
[ * ] Backing up existing templates and configuration files...

[ - ] Now applying any necessary patches from version v1.3.0...
[ * ] Updating default writable folders for all users...
[ * ] Updating nginx configuration...
[ * ] Updating exim4 configuration...
[ * ] Restricting access to /proc fs...
[ * ] Setting zstd backup compression type as default...
[ * ] Updating configuration file: hestia.conf...
[ * ] Updating File Manager configuration...
[ ! ] Updating default web domain templates...
**Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist
Error: no backend template doesn't exist**
[ ! ] Updating default mail domain templates...
[ ! ] Updating default DNS zone templates...
[ * ] Upgrading phpMyAdmin to version v5.0.4...

**Comment by ScIT-Raphael** [comment]
@julianarmando could you send me the output of v-list-web-domain user domain.tld json of a non working domain, in special the “STATS” part would be interresting.

**Comment by julianarmando** [comment]
> @julianarmando could you send me the output of v-list-web-domain user domain.tld json of a non working domain, in special the “STATS” part would be interresting.

All my sites are solved and working now, so, I think is not very informative, but, here is the report of one of my domains, but, again, the site is working now.

{
    "######.com": {
        "IP": "######",
        "IP6": "",
        "DOCUMENT_ROOT": "/home/#####/web/######/public_html/",
        "U_DISK": "102",
        "U_BANDWIDTH": "41",
        "TPL": "default",
        "ALIAS": "www.#######.com",
        "STATS": "",
        "STATS_USER": "",
        "SSL": "yes",
        "SSL_FORCE": "yes",
        "SSL_HSTS": "",
        "SSL_HOME": "same",
        "LETSENCRYPT": "yes",
        "FTP_USER": "",
        "FTP_PATH": "",
        "AUTH_USER": "",
        "BACKEND": "PHP-7_4",
        "PROXY": "default",
        "PROXY_EXT": "jpeg,jpg,png,gif,bmp,ico,svg,tif,tiff,css,js,htm,html,ttf,otf,webp,woff,txt,csv,rtf,doc,docx,xls,xlsx,ppt,pptx,odf,odp,ods,odt,pdf,psd,ai,eot,eps,ps,zip,tar,tgz,gz,rar,bz2,7z,aac,m4a,mp3,mp4,ogg,wav,wma,3gp,avi,flv,m4v,mkv,mov,mpeg,mpg,wmv,exe,iso,dmg,swf",
        "CUSTOM_DOCROOT": "",
        "SUSPENDED": "no",
        "TIME": "11:14:32",
        "DATE": "2020-10-13"
    }
}

**Comment by ScIT-Raphael** [comment]
@julianarmando thanks but unlucky, you're right - we would need one of a page which doesnt work.

**Comment by jaapmarcus** [comment]
I was able to replicate the issue after deleting the backend template from the web.conf and created the fix 

https://github.com/hestiacp/hestiacp/commit/624270b04ba65609fa51df6098ac14df2aff5e6b

Will be released I the next few days
