### ISSUE TITLE
Permission denied errors when running v-update-web-templates

### ISSUE THREAD

**Issue by sltmunky69** [hestiacp/hestiacp#1325]
### In a few words, please describe the issue that you're experiencing:
When I try to update the apache web templates by issuing the v-update-web-templates command, I get permission denied errors for all domains that have web stats enabled. There are four of the first messages followed by one of the second message.
`tee: /home/[USER]/web/[FQDN]/stats/.htaccess: Permission denied`
`tee: /home/[USER]/web/[FQDN]/stats/.htpasswd: Permission denied`

Identical error message to #793 
Possibly also connected to issue #1322 

### What steps did you take when the issue occured? 
1. Created some apache web templates .tpl + .stpl
2. Ran v-update-web-templates
3. Received error messages and the new web templates are not listed in the domain drop down upon refresh

### Expected behavior:
The new web templates should show up as an available option

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
hestia
core package
1.3.0 (amd64)
hestia-php
php interpreter
7.4.11 (amd64)
hestia-nginx
internal web server
1.19.3 (amd64)

### Additional notes:
Could be a separate issue, but it also says there is an update for hestia-php, but nothing happens when you click update.

**Comment by jaapmarcus** [comment]
For the second issue see https://github.com/hestiacp/hestiacp/issues/1318

Will be fixed in next release

Other option 
v-update-web-templates is used to "update" /usr/local/hestia/data/templates/web/ folder  containing templates and sync them with GitHub. 

Please check:
https://docs.hestiacp.com/admin_docs/server_management.html#how-do-web-templates-work

How to work with templates this. When done correctly you won't need to run the command
After this the template should become available in the web interface.

**Comment by sltmunky69** [comment]
Ok, well you closed my ticket and per the documentation, after running "v-rebuild-user admin" command, I still have no apache templates listed. Could you kindly please reopen it?

**Comment by jaapmarcus** [comment]
As I told you the command "v-update-web-templates" issn't the correct command to be ran. This command will update all the "default" templates with "Hestia" package and not move / create the template. So you should not / never need to run the command. 

1. With out the exact server config we can't know what is wrong. But if you used the default "install" string. Save locations for templates will be  /usr/local/hestia/data/templates/web/apache2/php-fpm/

2. If you need an "custom" template I create 2 new files ( test.tpl and test.stpl) in  /usr/local/hestia/data/templates/web/apache2/php-fpm/

<img width="532" alt="Screenshot 2020-11-03 at 02 24 44" src="https://user-images.githubusercontent.com/9754650/97936444-cd734a80-1d7b-11eb-9746-f37d6cf67030.png">

And then go to Edit domain. 
<img width="506" alt="Screenshot 2020-11-03 at 02 26 10" src="https://user-images.githubusercontent.com/9754650/97936512-fa276200-1d7b-11eb-8c64-0001a02063b5.png">

It should work straight out of the box.

**Comment by sltmunky69** [comment]
My apologies, I'm certainly not trying to be difficult here, I'm just trying to do an initial port over from Vesta to Hestia and still getting a crash course on how to navigate the differences in systems. 

My install string was `bash hst-install.sh -a yes -n yes -w yes -o yes -v no -j yes -k yes -m yes -g no -x yes -z yes -c yes -t yes -i yes -b yes -q yes -d yes -s server.fqdn -e aaa@bbb.com -p asdfasdf`.

So, simple oversight. I was trying to use apache2 templates since that's what my old system had, but on the new system it has php-fpm. I will try and update that set of templates instead. Thank you for your assistance.

**Comment by jaapmarcus** [comment]
If PHP-FPM is used the correct folder should be /usr/local/hestia/data/templates/web/apache2/php-fpm/  If you placed them first in /usr/local/hestia/data/templates/web/apache2 they will not work.

Probaly you will need to rework your templates as some changes has been made to support PHP-FPM correctly
