### ISSUE TITLE
Tried to change admin user to hestauser but get errrors in the install script. User admin is already taken.

### ISSUE THREAD

**Issue by pedroponte** [hestiacp/hestiacp#1328]
===

### In a few words, please describe the issue that you're experiencing:
Tried to change admin user to hestauser but get errors in the install script. User admin is already taken.

### What steps did you take when the issue occurred? 
Was trying to install and as result, installation aborted

### Operating system:
Ubuntu 20.04 LTS)

### Hestia Control Panel version:
1.3.0 

### Additional notes:
cp: cannot stat '/usr/local/hestia/install/deb/sudo/hestiaadmin': No such file or directory
chmod: cannot access '/etc/sudoers.d/hestiaadmin': No such file or directory
[ * ] Generating default self-signed SSL certificate...
[ * ] Adding SSL certificate to Hestia Control Panel...
[ * ] Configuring NGINX...
[ * ] Configuring Apache Web Server...
[ * ] Configuring PHP-FPM...
[ * ] Configuring PHP...
[ * ] Configuring Vsftpd server...
[ * ] Configuring MariaDB database server...
[ * ] Installing phpMyAdmin version v5.0.4...
[ * ] Configuring Bind DNS server...
[ * ] Configuring Exim mail server...
[ * ] Configuring Dovecot POP/IMAP mail server...
[ * ] Configuring Roundcube webmail client...
[ * ] Configuring fail2ban access monitor...
grep: /usr/local/hestia/data/users/admin/user.conf: No such file or directory
sed: can't read /usr/local/hestia/data/users/admin/user.conf: No such file or directory
grep: /usr/local/hestia/data/ips/*: No such file or directory
grep: /usr/local/hestia/data/ips/*: No such file or directory

**Comment by ScIT-Raphael** [comment]
What exactly do you want to do? Renaming admin user isnt supported, if the installer tell you, that there is a admin user, you probaly want to delete that to proceed the installation on a CLEAN system.
