### ISSUE TITLE
Hestia does not use the Let's Encrypt cert automatically managed for the same web domain

### ISSUE THREAD

**Issue by DailenG** [hestiacp/hestiacp#1334]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When I use Let's Encrypt to add a domain for the domain I'm using, Hestia does not use that certificate when accessing the Control Panel. As a result, I get the browser error regarding the security issue. This isn't normally a big deal but if using a domain that automatically enforces HSTS like a .DEV domain, then Hestia is inaccessible except directly via IP address.

### What steps did you take when the issue occured? 
1. Access hestia control panel from any browser
2. Add Let's Encrypt cert using web domain
3. Access the same domain used for hestia directly 

### Expected behavior:
It would be nice if Certs were centrally "managed", so the cert for Hestia matches the web domain and the mail domain certs automatically

### Operating system:
Ubuntu 18.04 LTS

### Hestia Control Panel version:
1.3.0

**Comment by ScIT-Raphael** [comment]
Hi @DailenG 

Thanks for your issue report, all parts has been already resolved, lets take it apart.

Hestia Backend (and other services like ftps and mail) are handled over v-add-letsencrypt-host, it's a command you just trigger once for your server and you're good to go - more you'll find here: https://docs.hestiacp.com/admin_docs/ssl_certificates.html

For mail ssl, hestia provides already the functionality for ssl certs per domain - just click edit on the mail domain and add tick the ssl checkbox.

Infact your request, as far as I see, has been already implemented, I'm going to close the issue. Please let us know if you have any (additional) question.

**Comment by DailenG** [comment]
Wow that is really impressive, I apologize for underestimating the intricate depth of Hestia 😳
