### ISSUE TITLE
v1.3 Excessive resource usage / v-backup-users / CSF-LFD notification every 40 minutes

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#1338]
Ubuntu Linux 18.04.4
Hestia : Automatically upgraded from 1.2.4 to 1.3.0
CSF-LFD notification every 40 minutes

Issue : Excessive resource usage: admin
/bin/sh -c sudo /usr/local/hestia/bin/v-backup-users
time took longer - 118254 > 1800 (seconds)

This issue on since the latest upgrade hestia v1.3..

**Comment by jaapmarcus** [comment]
We are using ZSTD since as compression method. How ever as 118254 is almost 1,5 day please check why it run so fast. 

Maybe check the backup log. 

My experience was that it took less time.  

Switching over to the old "Gzip" can be done via admin of via v-change-sys-config-value  BACKUP_MODE gzip

**Comment by ScIT-Raphael** [comment]
You can also set back to gzip in the backup settings, please give it a try and let us know, if it solved your issue.

PS: As always, issue template isnt decoration...

**Comment by vvcares** [comment]
I changed the 

> You can also set back to gzip in the backup settings, please give it a try and let us know, if it solved your issue.
> 
> PS: As always, issue template isnt decoration...

I changed it to GZIP. Let me monitor for few hours.

**Comment by vvcares** [comment]
Yes. I changed the backup type to GZIP. Seems it works. I have not recvd any notifications in the past 2.5 hrs. normally it will be every 40 minutes

**Comment by ScIT-Raphael** [comment]
That's weird, in our tests zstd was always the better and faster option. Infact it works now for you, I'll close the issue. If we get furhter, negativ feedback about zstd, we will do further checks.

**Comment by vvcares** [comment]
Nope. The same notifications started since this morning. Even i restarted the whole server on yesterday, upon changed to GZIP.

**Comment by jaapmarcus** [comment]
Please check if then process is still running or not. If the progress is still running kill it manually and run it then. And check where it hangs. As this is the first issue with the backup I find it strange.

**Comment by vvcares** [comment]
Settled. Thank you.
The issue was with my Digital ocean do-agent service v3.7.1 consuming lot of CPU (120~160%)
Upgraded do-agent v3.8.0 - then tried hestia backup. it runs well. Let me monitoring for next 12 hours for hestia's auto backup task to run.

**Comment by vvcares** [comment]
Seems it works. No issues on hestia itself. The issue was with do-agent consumed my CPU erroniously & hestia bkp tasks has not enough CPU resource to run.
