### ISSUE TITLE
ARM/ARM64 support

### ISSUE THREAD

**Issue by sHAsHiLx** [hestiacp/hestiacp#1342]
Tried to install it on raspbian but get error
apt-get install failed

then just tried to apt update and see this

N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://apt.hestiacp.com buster InRelease' doesn't support architecture 'armhf'
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.hestiacp.com buster InRelease' doesn't support architecture 'arm64'

so as I understand - there is no arm/arm64 versions of panel. Can you add it?

**Comment by ScIT-Raphael** [comment]
Currently, we do not have any plans to support arm. If you would like to test and contribute it, our build script for the relevant packages is public: https://github.com/hestiacp/hestiacp/blob/main/src/hst_autocompile.sh

You're free to provide a pull request with the necessary changes, we will discuss and probaly implement as always.

**Comment by sHAsHiLx** [comment]
Just to understanding - to compile for aarch64 I just need to change string

BUILD_ARCH='amd64'

to

BUILD_ARCH='aarch64'

?

**Comment by jaapmarcus** [comment]
See https://forum.hestiacp.com/t/arm-systems-support/894/4

**Comment by jaapmarcus** [comment]
Support to APT has been added from now on please use the default install steps!
