### ISSUE TITLE
File Manager loading the whole directory of server 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1344]
### In a few words, please describe the issue that you're experiencing:
File Manager loading the whole directory of server when set the ssh access to SH or Bash.
![image](https://user-images.githubusercontent.com/39749258/98228741-016a8d80-1f7f-11eb-9e7a-6812c4bcbc70.png)

### What steps did you take when the issue occured? 
domain:8083/edit/user/?user=admin (or any other user)
change the SSH Access to sh or bash
![image](https://user-images.githubusercontent.com/39749258/98228599-c9fbe100-1f7e-11eb-8a2f-8aa3a1865b7b.png)

now go to domain:8083/fm/#/ (file manager)

### Expected behavior:
Should only show the user directory 

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.0 (Prod)

**Comment by ScIT-Raphael** [comment]
This isnt a bug, because the filemanager use sftp for connection. If you give a user ssh permission, he can also login to the server and see the same directories.

This could be resolved with enabling a jailed/chrooted ssh, which could be resolved with rush - there is already a open feature request ticket for this.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/894

**Comment by rzafiamy** [comment]
Indeed, this a ssh configuration... You can avoid this by changing sshd_config like below : 

Subsystem sftp internal-sftp
      Match Group hestia-users
      ChrootDirectory %h

You have to add user manually  into  group hestia-users if you don't want them accessing the whole root... 
By default, newly created user will be added into group "hestia-users" except the "admin".
