### ISSUE TITLE
DKIM record doesn't appear in the DNS zone

### ISSUE THREAD

**Issue by cringeops** [hestiacp/hestiacp#1345]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When I first create an email domain with DKIM enabled, and after that, add a DNS zone, the DKIM record is not there. However, when I disable and then enable the DKIM checkbox again, it appears in the zone. It's not a critical issue but it's a bit annoying.

### What steps did you take when the issue occured? 
1. Add Mail Domain
2. Make sure DKIM is enabled
3. Add DNS zone
4. Have a look at the list of DNS records: DKIM record is not there.
5. Disable DKIM in the mail domain settings, re-enable it.
6. Now the DKIM record is present in the DNS zone.

### Expected behavior:
I expect the record to be added upon DNS zone creation.

### Operating system:
Ubuntu 18.04. I'm confident enough the bug will be present on 20 as well.

### Hestia Control Panel version:
1.3.0

**Comment by jaapmarcus** [comment]
It won’t surprise me the issue.

Normally you would activate the DNS and then Mail. Don’t know if there is an easy fix for it

**Comment by snakehill** [comment]
You can also activate just DKIM (instead of the entire mail domain) after having enabled the DNS.

Only if there is no DNS set up at all at the time of enabling DKIM, will there not be a DKIM record in the DNS records. Would be nice of course. But for the time being, make sure to set up DNS before either setting up the Mail or just before enabling DKIM on it.

**Comment by ScIT-Raphael** [comment]
We just discussed this in our dev chat: As snakehill and jaap already pointed out, dns should be prior to mail. We currently do not see this as critical issue which needs to be fixed.
