### ISSUE TITLE
Logging out again and again

### ISSUE THREAD

**Issue by rpeshnegi** [hestiacp/hestiacp#1346]
Why I'm logging out again and again.
Can I set to not log out

**Comment by jaapmarcus** [comment]
Please give us more information?

**Comment by rpeshnegi** [comment]
@jaapmarcus is there any security reason , that logging out me again and again even I changing pages, web then other page

**Comment by jaapmarcus** [comment]
Yes, We have multiple security checks these can be found 
https://github.com/hestiacp/hestiacp/blob/main/web/inc/main.php

https://github.com/hestiacp/hestiacp/blob/e6c29ad590a5f4dc7aefb905a113bc1c494e3cdb/web/inc/main.php#L39-L46

For example or https://github.com/hestiacp/hestiacp/blob/e6c29ad590a5f4dc7aefb905a113bc1c494e3cdb/web/inc/main.php#L66-L72

How ever with out any information we don't know what is going wrong...

**Comment by ScIT-Raphael** [comment]
Please switchover to our discord chat (https://discord.gg/nXRUZch), so we can discuss this further or provide us additional, understandable informations :). As always, issue report template isnt decoration...
