### ISSUE TITLE
hestia-php - error on fresh install

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#1348]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

### What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Add Web Domain".
3. Ex.: Attempted to add a domain and received an Internal Server Error.

### Expected behavior:
In a /list/updates/  i see notification concerning hestia-php with red label, i tried update but nothing happened, screen attached
<img width="1035" alt="Снимок экрана 2020-11-08 в 02 45 31" src="https://user-images.githubusercontent.com/39009179/98453678-fd03c780-216c-11eb-94d2-80eb9181c17d.png">

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.0

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/issues/1318,

It will be fixed during next release
