### ISSUE TITLE
Changing document root via user interface

### ISSUE THREAD

**Issue by nirbhasa** [hestiacp/hestiacp#1349]
In 'edit web domain' , when I check the 'custom document root' checkbox and edit either (or both) of the 'point to' or 'directory' fields, the changes do take effect, but the new changes dont show up on the 'edit web domain' screen

### What steps did you take when the issue occured? 
1. Edit a domain
2. Check the 'custom document root' checkbox and edit either (or both) of the 'point to' or 'directory' fields, and save
3. The changes appear to take effect, and show up in the logs
4. The changes dont show in the 'edit web domain screen'. The 'custom document root' checkbox is unchecked, and the domain is still shown as pointing to its original folder

### Expected behavior:
The changes should show up on the screen

### Operating system:
Debian 10

### Hestia Control Panel version:
1.30

The same also happens when I change doc root using the CLI command - it takes effect and shows in the logs, but not in the 'edit web domain' screen

**Comment by jaapmarcus** [comment]
Yes, This issues has been reported their is a minor issue In the regex code

We will release a fix shortly

**Comment by jaapmarcus** [comment]
Fix will be in next release
