### ISSUE TITLE
Lets Encrypt cert doesnt update when new alias is added via user interface

### ISSUE THREAD

**Issue by nirbhasa** [hestiacp/hestiacp#1350]
When I add an alias and save, the lets encrypt cert is unchanged

### What steps did you take when the issue occured? 
1. Point the web domain and all the aliases to the hestia server
2. Add web domain and some aliases, and select 'use letsencrypt to obtain ssl certificate'. The certificate is generated successfully with domains and aliases
3. Add some more domains, and save
4. The lets encrypt cert is unchanged

### Expected behavior:
The domains would automatically be added to the letsencrypt cert

### Operating system:
Debian 10

### Hestia Control Panel version:
1.3.0

Right now, I am adding via CLI as workaround. For documentation, it might be good to add that v-add-letsencrypt-domain command doesnt add aliases - you need to specify all the aliases in comma separated form, even the ones that are already there.

**Comment by ScIT-Raphael** [comment]
fixed: https://github.com/hestiacp/hestiacp/pull/1353
