### ISSUE TITLE
Not working MultiPHP

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#1351]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:

I installed multiphp and tried set for one my domain php 7.3, but it doesn't work, when i check phpinfo i see there 7.4

I checked /home/admin/conf/web/domain.com and nginx.conf switched for 7.3 correctly
nginx.conf

`  fastcgi_pass    unix:/run/php/php7.3-fpm-pzdc.fun.sock;
        fastcgi_index   index.php;
        include         /etc/nginx/fastcgi_params;
		fastcgi_read_timeout 300;
		fastcgi_send_timeout 300;
`

### What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Add Web Domain".
3. Ex.: Attempted to add a domain and received an Internal Server Error.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
Last version hestiacp
<img width="484" alt="Снимок экрана 2020-11-08 в 16 41 51" src="https://user-images.githubusercontent.com/39009179/98466562-573e7000-21e1-11eb-8424-3b1857601b92.png">

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
What happens if you run 

`v-add-web-php 7.3` ?

**Comment by avcvv** [comment]
v-add-web-php 7.3
Version already installed...

**Comment by avcvv** [comment]
php output https://pzdc.fun/cc.php in a panel settings for this domain set php7.3

**Comment by jaapmarcus** [comment]
Issue has been solved via Discord
