### ISSUE TITLE
Services not starting on a fresh install following a reboot

### ISSUE THREAD

**Issue by liamgibbins** [hestiacp/hestiacp#1354]
after rebooting some services are not restarting.
This is on a fresh install of the latest version.

![Hestiacp_reboot_services](https://user-images.githubusercontent.com/16313132/98482764-7649fb80-21fb-11eb-85a1-73098db9fb4b.png)

===

### In a few words, please describe the issue that you're experiencing:
Services not automatically starting on a fresh install following a reboot

### What steps did you take when the issue occured? 
reboot server.
login to panel and services page

### Expected behavior:
when rebooted the server then services should automatically start, like they did in previous versions

### Operating system:
Debain 10.6

### Hestia Control Panel version:
1.3.0

**Comment by ScIT-Raphael** [comment]
What's the output of each service status?

**Comment by liamgibbins** [comment]
there basically not started, you can start them via command line or panel.
going to reinstall and see if its a once off.

**Comment by jaapmarcus** [comment]
systemctl status MariaDB
systemctl status clamav-deamon
systemctl status php7.4-fpm
and 
so on...

**Comment by liamgibbins** [comment]
root@panel:~# systemctl status MariaDB
Unit MariaDB.service could not be found.
root@panel:~# systemctl status clamav-deamon
Unit clamav-deamon.service could not be found.
root@panel:~# service named status
Unit named.service could not be found.
root@panel:~# sudo systemctl is-active mariadb.service
active

**Comment by jaapmarcus** [comment]
It is systemctl status bind9

For all the other options please check https://github.com/hestiacp/hestiacp/blob/main/bin/v-list-sys-services for the correct service names. 
 
I am running multiple Debian servers in production and for testing and we are not able to replicate your issues.

**Comment by jlguerrerosanz** [comment]
I experienced this issue today.

- Bind
- ClamAV
- Exim

Didn´t start. This is the first restart after 38 days of a fresh install.

**Comment by ScIT-Raphael** [comment]
@jlguerrerosanz please check the service output as written above - nearly sure this isnt the same issue as this user have had. Probaly a forum thread would be the better position to handle that issue.

**Comment by ScIT-Raphael** [comment]
@jlguerrerosanz Please check out https://forum.hestiacp.com/t/how-to-contribute-with-translations/1664, any help would be awesome!
