### ISSUE TITLE
v-delete-domain showing wrong error message

### ISSUE THREAD

**Issue by jeazyee** [hestiacp/hestiacp#1364]
### In a few words, please describe the issue that you're experiencing:
When I try to delete a domain via command and the domain does not exist the error of too many arguments occur

### What steps did you take when the issue occured? 
1. Use the command: v-delete-domain username domainwithtypo.com
getting error: /usr/local/hestia/func/main.sh: line 125: [: too many arguments

### Expected behavior:
error message should tell domain does not exist

### Operating system:
Debian 10 buster

### Hestia Control Panel version:
1.3.0

**Comment by Lupul** [comment]
Confirmed, will be fixed soon
