### ISSUE TITLE
phpMyAdmin TempDir is not accessible

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1377]
### In a few words, please describe the issue that you're experiencing:
On phpMyAdmin 5.0.4: ![error](https://user-images.githubusercontent.com/20109369/99158850-9f74fb00-26d7-11eb-9d76-3405a2b7fc02.png)

It's something that apparently appeared in 1.1.0 also and was fixed in 1.2.0 before: #754 

### Operating system:
Debian 10

### Hestia Control Panel version:
1.3.0

### Additional notes:
The folder (/var/lib/phpmyadmin/tmp/) exists. However, changing the rights to this folder doesn't seem to do anything.

**Comment by jaapmarcus** [comment]
Know issues the issue is fixed by giving the php 777 access to the folder only really don't want it. 

Other option would be running phpmyadmin under an specific user (Or Hestia-php)

**Comment by jaapmarcus** [comment]
We have rewrote phpmyadmin to disconnect atp Should be working now
