### ISSUE TITLE
User restore problem

### ISSUE THREAD

**Issue by lonelyhearth** [hestiacp/hestiacp#1379]
### In a few words, please describe the issue that you're experiencing:
i'm trying to migrate a user from a debian 10 server to another debian10 server. Both are updated hestiacp panels. 
I make the backup in the old server, and move the .tar to the new instance. 
When i try to restore the user into the new instance, using v-restore-user, appears "user already exists" message. 
The user is not listed in /etc/passwd
The script "v-delete-user elusuario" shows the message "user elusuario doesn't exist"  
### What steps did you take when the issue occured? 

Into old server

1.  `# /usr/local/hestia/bin/v-backup-user elusuario `
2. `# cp /backup/elusuario.xxxx-xx-xx_xx-xx-xx.tar /home/elusuario/web/undominio.com/public_html/elusuario.xxxx-xx-xx_xx-xx-xx.tar && chown elusuario:elusuario /home/elusuario/web/undominio.com/public_html/elusuario.xxxx-xx-xx_xx-xx-xx.tar && chmod 777 /home/elusuario/web/undominio.com/public_html/elusuario.xxxx-xx-xx_xx-xx-xx.tar`

Into new server
1.- `# cd /backup`
2.- `# wget https://undominio.com/elusuario.xxxx-xx-xx_xx-xx-xx.tar`
3.- `# /usr/local/hestia/bin/v-restore-user elusuario elusuario.xxxx-xx-xx_xx-xx-xx.tar`
        Result: Error: User already exists
4.- `# /usr/local/hestia/bin/v-delete-user`
       Error: user elusuario doesn't exist

### Expected behavior:
Obviusly: restore user data into new server instance

### Operating system:
Both servers:
Debian GNU/Linux 10 (buster)

### Hestia Control Panel version:
Both: Hestia 1.3.0

**Comment by lonelyhearth** [comment]
Please apologize my pre-kinder level english.  I will be at your orders if you need some clarification or help.

**Comment by jaapmarcus** [comment]
See #1321

Solution is v-add-user elusuario password email package

Will be fixed in next release. Or use the 1.3.1 RC candidate

**Comment by ScIT-Raphael** [comment]
The 1.3.1 RC, you'll find it here: https://forum.hestiacp.com/t/hestiacp-1-3-1-rc/2072

**Comment by lonelyhearth** [comment]
Well, that's very fast, and it's sunday! Many thanks. Problem solved.  I will try hestiacp RC in my test server too... 
I wish you a very good rest-of-end-of-week. 
Thanks again!
