### ISSUE TITLE
Hestia 1.3.1 -v-add-letsencrypt-host

### ISSUE THREAD

**Issue by dariusuk69** [hestiacp/hestiacp#1391]
v-add-letsencrypt-host for Apache2 not create certs for aliasses like www.domain.ltd. only for domail.ltd

**Comment by jaapmarcus** [comment]
This is the correct working for v-add-letsencrypt host see

As you can see here: https://github.com/hestiacp/hestiacp/blob/2dd167fed8d6f042aea6790f012eafaacb2564a2/bin/v-add-letsencrypt-host#L16-L17

And here 
https://github.com/hestiacp/hestiacp/blob/2dd167fed8d6f042aea6790f012eafaacb2564a2/bin/v-add-letsencrypt-host#L71-L76

Use  v-add-letsencrypt-domain instead: see https://docs.hestiacp.com/cli_commands/commands.html#v-add-letsencrypt-domain

For how to use it.
