### ISSUE TITLE
[Bug] Letsencrypt renewal

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1393]
## In a few words, please describe the issue that you're experiencing:
Run the command v-add-letsencrypt-domain user domain.com www.domain.com causing the following error:

```
2020-11-17 12:59:57 v-add-letsencrypt-domain  'xxxx' 'xxxx.video' 'www.xxxx.video' [Error 15]
2020-11-17 13:01:25 v-list-dns-records  'xxxx' 'xxxx.video' [Error 3]
2020-11-17 13:01:58 v-list-dns-records  'xxxx' 'viraal.video' [Error 3]
2020-11-17 13:01:58 v-add-letsencrypt-domain  'xxxx' 'xxxx.video' 'www.xxxx.video' [Error 15]
2020-11-17 13:06:33 v-list-dns-records  'xxxx' 'viraal.video' [Error 3]
2020-11-17 13:07:07 v-add-letsencrypt-domain  'xxxx' 'xxxx.video' 'www.xxxx.video' [Error 15]
```

Please note that xxxx.video is an valid domain (Also issues with "normal" domains as xxx.nu)

### What steps did you take when the issue occured? 
1. v-add-letsencrypt-domain  'xxxx' 'xxxx.video' 'www.xxxx.video'
Also issues renewal with cronjob

### Expected behavior:
To be working 

### Operating system:
Ubuntu 20.04 

### Hestia Control Panel version:
1.3.1 / 1.3.0 

### Additional notes:
After suggestion from dev chat added the following line on line 203

echo "$user - $domain - $answer" >> "/var/log/hestia/letsencrypt-debug.log"

Ran the command "v-add-letsencrypt-domain  'xxxx' 'xxxx.video' 'www.xxxx.video'" again

Result:
```
viraalvideo - xxx.video - HTTP/2 201 
server: nginx
date: Tue, 17 Nov 2020 11:59:05 GMT
content-type: application/json
content-length: 479
boulder-requester: 80339873
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
location: https://acme-v02.api.letsencrypt.org/acme/order/80339873/6259673422
replay-nonce: 0103vxFTbpm4p6vXuob_eSxYcHRKtnlbMSMHrqLIENNHgb0
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-24T11:59:05.821983001Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "xxx.video"
    },
    {
      "type": "dns",
      "value": "www.xxx.video"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8470540316",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8667388920"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/80339873/6259673422"
}
viraalvideo - xxx.video - HTTP/2 201 
server: nginx
date: Tue, 17 Nov 2020 12:01:37 GMT
content-type: application/json
content-length: 467
boulder-requester: 80339873
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
location: https://acme-v02.api.letsencrypt.org/acme/order/80339873/6259673422
replay-nonce: 0104F0St8J920XBOk0RZ4WgCAYpxRwaZatUnT8oMCoCRbk4
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "status": "ready",
  "expires": "2020-11-24T11:59:05Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "xxx.video"
    },
    {
      "type": "dns",
      "value": "www.xxx.video"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8470540316",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8667388920"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/80339873/6259673422"
}
viraalvideo - xxx.video - HTTP/2 201 
server: nginx
date: Tue, 17 Nov 2020 12:06:45 GMT
content-type: application/json
content-length: 467
boulder-requester: 80339873
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
location: https://acme-v02.api.letsencrypt.org/acme/order/80339873/6259673422
replay-nonce: 0103cDnZ-OCHwqYcvr17woyqwn3p8IJmclHcT4uwMJV6Uas
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "status": "ready",
  "expires": "2020-11-24T11:59:05Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "xxx.video"
    },
    {
      "type": "dns",
      "value": "www.xxx.video"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8470540316",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8667388920"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/80339873/6259673422"
}
```

Full logs with domain names are available in dev chat.

**Comment by jaapmarcus** [comment]
Did some debugging added an aditinal echo to log between:
https://github.com/hestiacp/hestiacp/blob/03aa2c803dcd9b832c393823ef02fbb84c43fe9b/bin/v-add-letsencrypt-domain#L214-L215

xxxxx - xxxxx.video - https://acme-v02.api.letsencrypt.org/acme/authz-v3/8470540316
xxxxx - xxxxx.video - HTTP/2 200 
server: nginx
date: Tue, 17 Nov 2020 13:57:35 GMT
content-type: application/json
content-length: 706
boulder-requester: 80339873
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0104OUckDWSk-V23Unk4kT8plrTuC5XBUZbcPebX5hppmHs
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "xxxxx.video"
  },
  "status": "valid",
  "expires": "2020-12-09T05:12:06Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "valid",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxxx",
      "token": "oxL0Kqz8ecq970cqqLDZEqzIvVnZtcsDpC9dnEesjXQ",
      "validationRecord": [
        {
          "url": "http://xxxxx.video/.well-known/acme-challenge/oxL0Kqz8ecq970cqqLDZEqzIvVnZtcsDpC9dnEesjXQ",
          "hostname": "xxxxx.video",
          "port": "80",
          "addressesResolved": [
            "x.x.x.x"
          ],
          "addressUsed": "x.x.x.x"
        }
      ]
    }
  ]
}
xxxxx - xxxxx.video - https://acme-v02.api.letsencrypt.org/acme/authz-v3/8667388920
xxxxx - xxxxx.video - HTTP/2 200 
server: nginx
date: Tue, 17 Nov 2020 13:57:35 GMT
content-type: application/json
content-length: 718
boulder-requester: 80339873
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0003A-6bv9vToBZISnKI0haHLmiZW2J-pAmH995QNtT1GVg
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "www.xxxxx.video"
  },
  "status": "valid",
  "expires": "2020-12-17T11:59:34Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "valid",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxxx",
      "token": "UVpMjonm3hw26YtKJ66ar4m6hYRhdJrNM6LMjaZPIec",
      "validationRecord": [
        {
          "url": "http://www.xxxxx.video/.well-known/acme-challenge/UVpMjonm3hw26YtKJ66ar4m6hYRhdJrNM6LMjaZPIec",
          "hostname": "www.xxxxx.video",
          "port": "80",
          "addressesResolved": [
            "x.x.x.x"
          ],
          "addressUsed": "x.x.x.x"
        }
      ]
    }
  ]
}

**Comment by linuskom** [comment]
Similar letsencrypt renewal issue
=================================

v-add-letsencrypt-domain admin healthsmartnutra.com www.healthsmartnutra.com

Error: Let's Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending

---------------------------------------------------------------------------------

Then checked /var/log/hestia/letsencrypt-debug.log
see below
---------------------------------------------------------------------------------

admin - healthsmartnutra.com - HTTP/2 201
server: nginx
date: Wed, 18 Nov 2020 12:39:15 GMT
content-type: application/json
content-length: 485
boulder-requester: 96380350
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
location: https://acme-v02.api.letsencrypt.org/acme/order/96380350/6277711927
replay-nonce: 0103ZNGNMYhczEJfm7BrcUaDbs3ZKlDDOIbGqtdzzrMbiGs
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-25T03:01:06Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "healthsmartnutra.com"
    },
    {
      "type": "dns",
      "value": "www.healthsmartnutra.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8681936823",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8691132150"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/96380350/6277711927"

**Comment by linuskom** [comment]
1. Disabled the checkbox “Automatic HTTPS Redirection” then SAVE
2. Run command;
> v-add-letsencrypt-domain admin healthsmartnutra.com www.healthsmartnutra.com
No error message generated.
3. Verified LE-SSL renewed successfully.
4. Re-Enabled “Automatic HTTPS Redirection” then SAVE

**Comment by plutocrat** [comment]
"Disabled the checkbox “Automatic HTTPS Redirection” then SAVE" 
This also fixed it for me. I believe the issue is with the nginx config, which will force SSL before doing the Letsencrypt magic. And of course, LE can't verify over a connection other than port 80. 
If you were to make sure the LE stanza matches first, I believe it would allow the verification. 

I'm guessing that we're only just noticing this now, as the first wave of certs is being re-issued after a change from approx 60 days ago?

**Comment by jaapmarcus** [comment]
About 60 / 70 days ago we released an emergency fix that contained an bug
```
=============================
WEB_SYSTEM: apache2
PROXY_SYSTEM: nginx
user: xxxxx
domain: xxxxx.nl


- aliases: xxxxx.nl
- proto: http-01
- wildcard: 


==[Step 1]==
- status: 200
- nonce: 0004rcg4PLqi0d0H2ersvsEzbGClXH1JW-2DDEuSWpFEtEY
- answer: HTTP/2 200 
server: nginx
date: Mon, 23 Nov 2020 02:50:13 GMT
content-type: application/json
content-length: 658
cache-control: public, max-age=0, no-cache
replay-nonce: 0004rcg4PLqi0d0H2ersvsEzbGClXH1JW-2DDEuSWpFEtEY
x-frame-options: DENY
strict-transport-security: max-age=604800



==[Step 2]==
- status: 201
- nonce: 0103LwN3OKXA4XPPNEBLlO54d0cszpGttVor3AFNr_tanTg
- authz: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8728505246
https://acme-v02.api.letsencrypt.org/acme/authz-v3/8728505295
- finalize: https://acme-v02.api.letsencrypt.org/acme/finalize/80302793/6305735020
- payload: {"identifiers":[{"type":"dns","value":"handigeweetjes.nl"},{"type":"dns","value":"www.handigeweetjes.nl"}]}
- answer: HTTP/2 201 
server: nginx
date: Mon, 23 Nov 2020 02:50:13 GMT
content-type: application/json
content-length: 479
boulder-requester: 80302793
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
location: https://acme-v02.api.letsencrypt.org/acme/order/80302793/6305735020
replay-nonce: 0103LwN3OKXA4XPPNEBLlO54d0cszpGttVor3AFNr_tanTg
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-27T02:50:04Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "xxxxx.nl"
    },
    {
      "type": "dns",
      "value": "xxxxx.nl"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8728505246",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8728505295"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/80302793/6305735020"
}


==[Step 3]==
- status: 200
- nonce: 0103uos5uf9u-MMX_7Kc20rwXcVyGSCJcSz0qB4WOlVqS-w
- url: https://acme-v02.api.letsencrypt.org/acme/chall-v3/8728505246/wAhZyA
- token: lYw4Kg2KXASrv7-UTt0AqGTkF8oIHX28BS-M90OHDME
- answer: HTTP/2 200 
server: nginx
date: Mon, 23 Nov 2020 02:50:14 GMT
content-type: application/json
content-length: 1430
boulder-requester: 80302793
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0103uos5uf9u-MMX_7Kc20rwXcVyGSCJcSz0qB4WOlVqS-w
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "xxxxx.nl"
  },
  "status": "valid",
  "expires": "2020-12-22T02:50:35Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "valid",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8728505246/wAhZyA",
      "token": "lYw4Kg2KXASrv7-UTt0AqGTkF8oIHX28BS-M90OHDME",
      "validationRecord": [
        {
          "url": "http://xxxxx.nl/.well-known/acme-challenge/lYw4Kg2KXASrv7-UTt0AqGTkF8oIHX28BS-M90OHDME",
          "hostname": "xxxxx.nl",
          "port": "80",
          "addressesResolved": [
            "xxxxxx.a",
            "xxxxxx.b",
            "xxxxxx.c",
            "xxxxxx.ip6.a",
            "xxxxxx.ip6b",
            "xxxxxx.ip6c"
          ],
          "addressUsed": "xxxxxx.ip6.c"
        },
        {
          "url": "https://xxxx.nl/.well-known/acme-challenge/lYw4Kg2KXASrv7-UTt0AqGTkF8oIHX28BS-M90OHDME",
          "hostname": "xxxx.nl",
          "port": "443",
          "addressesResolved": [
            "xxxxxx.a",
            "xxxxxx.b",
            "xxxxxx.c",
            "xxxxxx.ip6.a",
            "xxxxxx.ip6b",
            "xxxxxx.ip6c"
          ],
          "addressUsed": "xxxxxx.ip6.c"
        }
      ]
    }
  ]
}


==[Step 3]==
- status: 
- nonce: 
- url: 
- token: 
- answer: 
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1425

With this pull request the issue should be solved.
