### ISSUE TITLE
[Feature Request] Add section for whitelisting hosts from Firewall in the web backend

### ISSUE THREAD

**Issue by beli42** [hestiacp/hestiacp#1395]
To prevent locking yourself out from a system by changing firewall entries via the web interface, i recommend to put a section above the firewall-gui where you can enter ip/network for whitelisting source hosts. These hosts should be configured in the firewall so that they are in no cases denied.

**Comment by jlguerrerosanz** [comment]
I would rather see the fail2ban implementation but the whitelisting from Firewall may work for me too.

My web servers running wordpress try to connect to the smtp server. If the password / protocol is misconfigured, the whole server gets banned and no one can send emails.

I had to put the ignoreip in the jail.local file.

**Comment by jaapmarcus** [comment]
Fail2ban blocks ips in Iptables.  "Whitelisting" in iptables will probally be fine...

**Comment by jlguerrerosanz** [comment]
No it won't if fail2ban can ban a whitelisted ip

**Comment by ScIT-Raphael** [comment]
You can already whitelist your hosts from the current iptables firewall implementation - just add a rule, allow and your IP.
