### ISSUE TITLE
[Feature Request] Include Port Knocking Service

### ISSUE THREAD

**Issue by beli42** [hestiacp/hestiacp#1396]
Include a port knocking service to the service portfolio to open/close access to ssh, ftp etc. only after successfull knocking.
I have a working knockd configuration and can provide it to you if you want.

**Comment by ioannidesalex** [comment]
Very interesting indeed! Greatly enhances security.

**Comment by ScIT-Raphael** [comment]
It would be a good enhancement, but currently we do not have enough time to implement it. If you want to take it over @beli42 please reach out in our discord chat.
