### ISSUE TITLE
[Feature Request] Cron Job notifications on/off for individual jobs

### ISSUE THREAD

**Issue by Johnzapf** [hestiacp/hestiacp#1397]
I would like to be able to get cron job notification on individual jobs, and or the option to only get an email if a job fails.

**Comment by ScIT-Raphael** [comment]
You can disable cronjob output per cronjob using `>/dev/null 2>&1` -> https://www.google.com/search?q=disable%20crontab%20output

If you want to completly disable the cronjob notifications, there is a disable notification function in the crontab overview.
