### ISSUE TITLE
hestiacp, it fails when I want to install it on Ubuntu / Debian

### ISSUE THREAD

**Issue by raulrr1986** [hestiacp/hestiacp#1400]
### In a few words, please describe the issue that you're experiencing:
hestiacp, it fails me when I try to install it, following the basic installation steps, it tells me that it does not locate the repository

### What steps did you take when the issue occured? 
Step 1: Log in as the system user (root):
Yes, I do it natively.

Step 2: Download the installer:
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

Step 3: Run the installer and follow the prompts:
bash hst-install.sh

### Expected behavior:
it should have been installed, correctly, but it doesn't.

### Operating system:
Ubuntu 18.04 or Debian 10 Buster

### Hestia Control Panel version:
anyone.

**Comment by jaapmarcus** [comment]
Please give is the error message

**Comment by ScIT-Raphael** [comment]
Probaly:
https://github.com/hestiacp/hestiacp/blob/03aa2c803dcd9b832c393823ef02fbb84c43fe9b/install/hst-install-ubuntu.sh#L293-L295

But the repo is up and running. Please run the command manualy and check if you can reach our website or/and repository - maybe you got blocked out from cloudflare.

**Comment by raulrr1986** [comment]
> Probaly:
> https://github.com/hestiacp/hestiacp/blob/03aa2c803dcd9b832c393823ef02fbb84c43fe9b/install/hst-install-ubuntu.sh#L293-L295
> 
> But the repo is up and running. Please run the command manualy and check if you can reach our website or/and repository - maybe you got blocked out from cloudflare.

I am installing from Cuba, and in my configuration I exit from a squid proxy, a proxy that I have already declared for wget, curl and apt. But the following fails me

Updating currently installed packages, please wait... W: GPG error: http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C
E: The repository 'http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic InRelease' is not signed.
W: GPG error: https://nginx.org/packages/mainline/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
E: The repository 'https://nginx.org/packages/mainline/ubuntu bionic InRelease' is not signed.
W: GPG error: https://apt.hestiacp.com bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5
E: The repository 'https://apt.hestiacp.com bionic InRelease' is not signed.
W: GPG error: https://mirror.mva-n.net/mariadb/repo/10.5/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F1656F24C74CD1D8
E: The repository 'https://mirror.mva-n.net/mariadb/repo/10.5/ubuntu bionic InRelease' is not signed.
\
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait... 
|
Error: apt-get install failed

**Comment by imjustafox** [comment]
looks like you don't have the repository signing keys.  One fix is to install these via:
https://askubuntu.com/questions/939479/import-the-repository-signing-key

the other fix, which is insecure and extremely not recommended is to modify your sources.list by prepending 
```[trusted=yes] ```
to your links

**Comment by jaapmarcus** [comment]
Haven't seen any more issues with it probally it was an issue only on your side. Will close the issue as there can't be a lot changed.
