### ISSUE TITLE
'webmail' dns entry removed when changing webmail alias

### ISSUE THREAD

**Issue by YVbakker** [hestiacp/hestiacp#1403]
### In a few words, please describe the issue that you're experiencing:
When changing the webmail alias, the dns record for 'webmail' is removed without a warning.

### What steps did you take when the issue occured? 
1. Go into settings as an admin
2. Change webmail alias under 'mail'

### Expected behavior:
Either a warning, and/or an option to keep the original 'webmail' record either by default or optionally.

### Operating system:
Ubuntu 20.04LTS

### Hestia Control Panel version:
1.3.1

### Additional notes:
I understand why, but in case one has their own webmail service running on the 'webmail' subdomain, suddenly having this removed is not useful. (it doesn't take much time to re-enter it, but imagine not noticing and then finding out after 4 hours (default TTL)

**Comment by ghost** [comment]
We'll improve this behavior alongside the changes we are making to the webmail implementation for the next major release.

**Comment by jaapmarcus** [comment]
I think the current default behaviour is fine. We are working currently on an system where sysadmins then add their own webmail client to it. 

By default rainloop and roundcube (up to date with the last version) is supported.

Additional clients can added with minor changes...

**Comment by jaapmarcus** [comment]
We have added an option to disable the webmail via mail domain. It will keep the DNS records + LE intact.  I think it is save to close the issue.
