### ISSUE TITLE
wrong certificate served after update (using webmail as custom subdomain)

### ISSUE THREAD

**Issue by YVbakker** [hestiacp/hestiacp#1404]
### In a few words, please describe the issue that you're experiencing:
After updating the control panel (both to 1.3.0 and 1.3.1) my 'webmail.domain.com' serves the server certificate instead of the correct certificate issued for that subdomain. Please note that in this case the 'webmail' subdomain is added as an actual domain under a user account in order to provide alternative webmail software. The system webmail alias (to roundcube) was left in its default setting.
The correct certificate is served after SSL is disabled and then re-enabled on the domain.

### What steps did you take when the issue occured? 
1. go to domain 'webmail.domain.com'
2. copy over SSL details & disable SSL
3. enable SSL and re-enter SSL details

### Expected behavior:
Everything should keep working after an (auto) update

### Operating system:
Ubuntu 20.04LTS

### Hestia Control Panel version:
1.3.1 (1.3.0)

### Additional notes:
I have set the system webmail alias to another value thinking this might prevent it in the future. I'll have to see with a future update.

**Comment by cmstew** [comment]
As far as I know, if the system webmail alias is set to "webmail", nginx will prioritize that domain over the one you've added. Personally what I've done to get around this is to set the system webmail alias to "roundcube" so it doesn't conflict with my custom webmail (rainloop).

I think the real problem has something to do with the nginx config files loading two server blocks. One from the system and one from the domain you added. Which in turn conflict and perhaps the order that they load is dependent on the order that they are added.

Still worth discussing options though.

**Comment by ghost** [comment]
This is caused by a conflict between the alias being used for Roundcube (which is by default "webmail") and the custom webmail.domain.tld subdomains you have created.

As @cmstew has mentioned, simply change the system default to "roundcube" or another value and then you can proceed to use another webmail client.
