### ISSUE TITLE
Let's encrypt 'new auth status 400' after restoring domain from backup

### ISSUE THREAD

**Issue by YVbakker** [hestiacp/hestiacp#1405]
# NOTE
I did not test this with a backup from the latest version of Hestia (1.3.1) to an instance with the latest version. This may or may not have been fixed with the latest release since I saw another issue with backups just now. If you believe this has already been fixed, please close this issue and pretend I didn't write it :-) 

### In a few words, please describe the issue that you're experiencing:
I recently moved some domains from one Hestia instance to another, but I'm not able to enable let's encrypt auto-renewal for this specific domain on the new instance. I was able, however, to copy over the certificate details manually, but this will expire in the future. I figured it might take some time (dns propagation) but it turned out the same issue is still there two weeks later. I am seeing a possible workaround here where I temporarily move the web directory elsewhere, delete the domain from Hestia and re-add it, but this doesn't address the issue.

### What steps did you take when the issue occured? 
1. Create a backup of a Hestia user account
2. Restore this backup on another machine
3. Re-check the let's encrypt checkbox
4. Manually copy over the certificate details, leaving the let's encrypt checkbox unchecked

### Expected behavior:
Everything continues to work as expected

### Operating system:
Ubuntu 20.04LTS

### Hestia Control Panel version:
1.3.1 (1.3.0)

### Additional notes:
It is like let's encrypt cannot reach the domain for some reason. (at least that's roughly the connotation of the error according to let's encrypt docs)

**Comment by jaapmarcus** [comment]
Please disable the "force" ssl checkbox and try again.
https://forum.hestiacp.com/t/hestiacp-log-deleted-dns-record-25-added-caa-dns-record/2116/13

We should still fix the issue with moving certificates

**Comment by alber-khan** [comment]
Another issue is when the database size is large it does not restore the database properly 

/backup/tmp.S4oyFc8m1v/db/database/database.mysql.sql.zst: 154456067 bytes

![image](https://user-images.githubusercontent.com/39749258/99721170-cadf5780-2ad4-11eb-9a6d-61a23d6119e5.png)

**Comment by jaapmarcus** [comment]
Please create a new issue.

Also what is not / what is imported

**Comment by ScIT-Raphael** [comment]
We've rewrote the LE API and expanded aswell the log functions. Please inform us, if they are still issues on renew - but "should be fixed".
