### ISSUE TITLE
[Feature request] Option to manage email separately

### ISSUE THREAD

**Issue by martinkoutecky** [hestiacp/hestiacp#1407]
I prefer to only use HestiaCP to manage my websites (apache/nginx/php/mariadb/vsftpd) and manage email separately (in my case with mailcow, but that's irrelevant). So I have disabled the dovecot and exim4 services. However, during a hestia update, they get reenabled and this leads to undesireable port conflicts etc.

An ideal solution would be to have a "Manage email separately" checkbox in hestia settings which would simply make hestia completely disregard the state of dovecot and exim4 and leave this to the user, both during normal operation and during an update.

(I also don't need DNS, so it would be nice to have an option to disable bind9, but this is a much lower priority for me since I manage DNS separately on a different server, so I don't mind running bind9 even though it doesn't do anything.)

**Comment by ScIT-Raphael** [comment]
Have a look at custom installation, you can disable each not needed service there on installation: https://github.com/hestiacp/hestiacp#custom-installation

Currently we work on a modular setup, where you can add or remove each module like mail, ftp, dns - but currently we're not ready yet :).

You could basicly remove the services (exim, bind) and revert the steps which our installer did for the requested part, also remove the services from $HESTIA/conf/hestia.conf.

Infact we already support it due to the custom installer, I'll close your feature request.

**Comment by martinkoutecky** [comment]
@ScIT-Raphael Hi, this is somewhat helpful info, but I want to ask a few more questions, if I may.

Since I have already installed hestia and it's in production, I can't use the advice with custom installation. When you say "revert the steps which our installer did" I don't know what those steps are and how to find out. Finally, how do I remove the services from the $HESTIA/conf/hestia.conf file? Just comment them out (with a hash symbol)? replace with an empty string? or?

If you can help me figure this out then I agree that's a fairly satisfactory long-term solution, and the new modular setup sounds great, obviously.

**Comment by jaapmarcus** [comment]
Replace:

DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'

With 
DNS_SYSTEM=''
MAIL_SYSTEM=''
ANTIVIRUS_SYSTEM=''
ANTISPAM_SYSTEM=''
IMAP_SYSTEM=''

And then remove the respected software. 

"Modular" setup is planned for 2.0 together with CentOS support.  Only unknown it when it happens

**Comment by martinkoutecky** [comment]
@jaapmarcus Perfect, thanks! I guess I can add this to the docs here: https://github.com/hestiacp/hestiacp-docs -- make a PR? Would that be the appropriate place to have this? (Since I couldn't find how to do this, maybe there are others.)

**Comment by ScIT-Raphael** [comment]
Of course, feel free to make a PR!
