### ISSUE TITLE
SSL not displayed in HestiaCP

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#141]
### Operating System (OS/VERSION):

Ubuntu 18.04

### HestiaCP Version:

Alpha Test

### Installed Software (what you got with the installer):

Nginx, PHP-FPM 7.3

### Steps to Reproduce:

When you add an SSL for a website, it is saved but not displayed from the panel. This issue exists for non LetsEncrypt SSLs.

**Comment by ScIT-Raphael** [comment]
Wasnt able to reproduce this issue.

**Comment by ioannidesalex** [comment]
@ScIT-Raphael Issue exists. Tried this in several servers, all running Ubuntu 18.04 with Nginx + PHP-FPM.

**Comment by ScIT-Raphael** [comment]
Please share your system credentials that we can have a short check.

**Comment by ScIT-Raphael** [comment]
Checked on system, seems to be a issue with cloud flare ca. Looks like not hestia related, so I close the ticket for now.
