### ISSUE TITLE
Some CLI commands are not returning JSON format data

### ISSUE THREAD

**Issue by Hipshares** [hestiacp/hestiacp#1410]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

OS : Debian 10.6
Hestia : 1.3.0
Multi php, Apache + Nginx, Mysql and PG

I check the commands code on /usr/local/hestia/bin and it's missing the JSON function. I didn't check all the 200+ commands

### In a few words, please describe the issue that you're experiencing:
Some commands like v-list-sys-dns-status , v-list-sys-db-status and others are not returning JSON format data. This is an issue for APIs connection as well.

### What steps did you take when the issue occured? 

From shell, as root, launch the commands with parameter JSON and is returning plain or what is configured (sometime is html)

### Expected behavior:
Option to get JSON format answer for all the CLI commands

### Operating system:
Debian 10.6

### Hestia Control Panel version:
Hestia 1.3.0

### Additional notes:
Some CLI commands are just doing a CAT from temp files, so is also hard to fix it by adding the JSON function directly on the CLI code

**Comment by ScIT-Raphael** [comment]
Not all scripts are planed to throw out a json content, some scripts are also sending out plain html as you already noticed. This isnt a bug, more a "by design"-part.
