### ISSUE TITLE
database is not importing on new server 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1412]
### In a few words, please describe the issue that you're experiencing:

trying to export and import the user to new server with v1.3.1

the database size is 261.5 MiB

and restoing it via "v-restore-user"

### What steps did you take when the issue occured? 
Another issue is when the database size is large it does not restore the database properly
/backup/tmp.S4oyFc8m1v/db/database/database.mysql.sql.zst: 154456067 bytes

![image](https://user-images.githubusercontent.com/39749258/99721864-d0896d00-2ad5-11eb-97ed-4c74f0acc634.png)

### Expected behavior:
shoud import the user without any issue

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
 1.3.1 (Fresh Install)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/99722587-dc296380-2ad6-11eb-821e-c353ed7a5d2e.png)

here's another user

**Comment by 4183r** [comment]
/usr/local/hestia/bin/v-restore-user: line 837: /usr/local/hestia/web/inc/mail-wrapper.php: Permission denied

i'm also getting this issue and i've fix it by using
`chmod -R 777 /usr/local/hestia/web/inc/mail-wrapper.php`

**Comment by alber-khan** [comment]
```
SET GLOBAL innodb_default_row_format='dynamic';
SET SESSION innodb_strict_mode=OFF;
SET GLOBAL innodb_strict_mode=OFF;
```

it works when I disable "innodb_strict_mode"

**Comment by 4183r** [comment]
![image](https://user-images.githubusercontent.com/39749258/99732828-3251d300-2ae6-11eb-85fa-38d0df594567.png)

here's another issue when I'm creating a backup on a new server (Running fresh v1.3.1) in zstd mode and restoring it to another server it's skipping "WEB" Files

and when i take backup in GZIP mode it's working fine.
![image](https://user-images.githubusercontent.com/39749258/99732952-675e2580-2ae6-11eb-895f-45a82982a99f.png)

**Comment by jaapmarcus** [comment]
The issue
ERROR 1118 (42000) at line 1093: Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.

Issue should be solved now...
