### ISSUE TITLE
v-generate-ssl-cert command returns errors

### ISSUE THREAD

**Issue by nirbhasa** [hestiacp/hestiacp#1414]
## What steps did you take when the issue occured? 
1. Run script as suggested in docs: `v-generate-ssl-cert example.com mail@yahoo.com USA California Monterey ACME.COM IT`
2. Received this message:

```
problems making Certificate Request
140024005616832:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:../crypto/asn1/a_mbstr.c:107:maxsize=2

```
The private key was generated and placed in tmp folder

### Operating system:
Debian 10

### Hestia Control Panel version:
1.3.1

**Comment by wojsmol** [comment]
Please use `US` instead of `USA` as a country code.

**Comment by jaapmarcus** [comment]
Yes it works 

Issue can be closed
