### ISSUE TITLE
Xubuntu 20.04 Install error 1.3.1

### ISSUE THREAD

**Issue by Phill77** [hestiacp/hestiacp#1416]
Hello,
I decide to try a HestiaCP 1.3.1 but without success of the installation.
OS: Xubuntu 20.04

Previously there was Vesta ср on Hubuntu 18.04, updated to 20.04
When installing, your panel. suggests deleting other data when running the script, I agree…

sudo bash hst-install.sh -n yes -a yes -w no -k yes -v yes -j no -i no -b no -q no -x no -t no -z no -c no -m no -o no -g no

==========

Please wait, the installer is now checking for missing dependencies...

[ * ] Installing dependencies...
!!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!!

WARNING: The following packages are already installed
nginx*

It is highly recommended that you remove them before proceeding.

!!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!!

Would you like to remove the conflicting packages? [y/n] **Y**

-----

Adding required repositories to proceed with installation:

[ * ] NGINX
[ * ] PHP
[ * ] Apache2
[ * ] Hestia Control Panel

Updating currently installed packages, please wait…-
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait…
**Error: apt-get install failed**

### Expected behavior:
Hestiacp 1.3.1 work

### Operating system:
Xbuntu 20.04 LTS

### Hestia Control Panel version:
1.3.1 
===
Log File
===
The latest version of apt-transport-https package (2.0.2ubuntu0.1) is already installed.
The latest version of ca-certificates (20201027ubuntu0.20.04.1) is already installed.
The latest curl package (7.68.0-1ubuntu2.2) is already installed.
The dirmngr package of the newest version (2.2.19-3ubuntu2) is already installed.
The most recent version of gnupg (2.2.19-3ubuntu2) is already installed.
The newest version software-properties-common package (0.98.9.3) is already installed.
The latest wget package (1.20.3-1ubuntu1) is already installed.
Updated 0 packages, 0 new packages installed, 0 packages marked for removal, and 0 packages not updated.
Reading package lists ...
Building a dependency tree ...
Reading status information ...
Calculation of updates ...
Updated 0 packages, 0 new packages installed, 0 packages marked for removal, and 0 packages not updated.

**Comment by ScIT-Raphael** [comment]
As written on the forum: xbuntu != ubuntu, please stick to the supportes operating systems: https://github.com/hestiacp/hestiacp#supported-operating-systems

Closed due to unsupported version, please use ubuntu server 20.04 lts.

**Comment by Phill77** [comment]
you yourself wrote that xubuntu = ubuntu. Anything that works for Ubuntu also works for Xubuntu.
Are you not interested in solving questions?

**Comment by ScIT-Raphael** [comment]
Where I wrote that? Currently we develop and test for ubuntu server and debian systems, according to our supported systems part in our readme. We do not have any interrests to also support (and test) every devirat of a system. I would suggest to use ubuntu server, if you get issues there aswell, please proceed with a bug report containing the installation log.

**Comment by Phill77** [comment]
Thanks. I added 1 post. if it helps you.
I fixed all the problems. and the remains of the Vestacp installation. I just don't understand what's stopping you from installing your panel.

**Comment by ScIT-Raphael** [comment]
Just because you write about remains of vestacp installation: Hestia needs a clean system for installation, as written in the readme, docs and website. If you used xubuntu on a system that already runs vesta, it can't work.

**Comment by Phill77** [comment]
Yes, that's exactly what happened. Well, what do you want to reinstall the server because of your panel? Are you kidding me?)
there are ways to clean the system)

I added a log file at the end of the start post.

It's easier to install another panel. But it's a shame I would like yours.

**Comment by ioannidesalex** [comment]
We don’t want you to do anything, eg reinstall. HestiaCP is what it is, free for everyone to use and it has certain requirements. Using it or not is entirely your own choice.

Demands can be made by users when they are paying for a product. Which is not the case with HestiaCP. Team members use their personal time, free of charge to develop the product. At least show some respect to this.

**Comment by ScIT-Raphael** [comment]
We require a clean system, you try to install it on a not clean system, so please dont expect any support for this. So it would be a better idea to install any other panel than hestia.

If you still would like to use it, proceed with a clean and supported system.
