### ISSUE TITLE
Mail Infobox information presentation enhancement. And add POP details. 

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1417]
### In a few words, please describe the issue that you're experiencing:
When adding or editing a mail account, relevant connection settings are displayed in a box to one side. However the layout of the information is confusing, repeats details unnecessarily, and misses out POP completely. 

### Current layout. 
This is what is displayed currently the user is required to click on one of the four headings to display information, most of which is repeated. 

**USE DOMAIN NAME**
Username: user1@example.com
Password: 
IMAP Hostname: example.com
IMAP Port: 143
IMAP Security: No encryption
IMAP Authentication Method: Normal Password
SMTP Hostname: example.com
SMTP Port: 25
SMTP Security: No encryption
SMTP Authentication Method: Normal Password
Webmail Alias: http://webmail.example.com 

**USE STARTTLS:**
Username: user1@example.com
Password: 
IMAP Hostname: example.com
IMAP Port: 143
IMAP Security: STARTTLS
IMAP Authentication Method: Normal Password
SMTP Hostname: example.com
SMTP Port: 587
SMTP Security: STARTTLS
SMTP Authentication Method: Normal Password

**USE SSL/TLS:**
Username: user1@example.com
Password: 
IMAP Hostname: example.com
IMAP Port: 993
IMAP Security: SSL / TLS
IMAP Authentication Method: Normal Password
SMTP Hostname: example.com
SMTP Port: 465
SMTP Security: SSL / TLS
SMTP Authentication Method: Normal Password
Webmail Alias: http://webmail.example.com 

**NO ENCRYPTION:**
Username: user1@example.com
Password: 
IMAP Hostname: example.com
IMAP Port: 143
IMAP Security: No encryption
IMAP Authentication Method: Normal Password
SMTP Hostname: example.com
SMTP Port: 25
SMTP Security: No encryption
SMTP Authentication Method: Normal Password
Webmail Alias: http://webmail.example.com 

### Suggested improvement:
Have all the information displayed as one single block, suitable for copying and pasting into an email. The information could be condensed into the following. 

**COMMON ACCOUNT SETTINGS**
Username: user1@example.com
Password: xxxxxxx
Webmail Alias: https://webmail.example.com 
Hostname(s): mail.example.com example.com

**IMAP SETTINGS:**
Authentication: Normal Password
Port 993: SSL / TLS
Port 143: STARTTLS
Port 143: No encryption

**POP3 SETTINGS:**
Authentication: Normal Password
Port 995: SSL / TLS
Port 110: STARTTLS
Port 110: No encryption

**SMTP SETTINGS:**
Authentication: Normal Password
Port 465: SSL / TLS
Port 587: STARTTLS
Port 25: No encryption

(options above are presented in decreasing order of security)

**Comment by jlguerrerosanz** [comment]
And maybe a link to a hestia docs section with detailed instructions on how to configure the server for the most important clients:
- Outlook 
- Thunderbird
- Android
- iOS
- ...

I can make those step by step guides if you want to put them.
