### ISSUE TITLE
lets encrypt validation error spelling  - v-add-letsencrypt-domain - 

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#142]
There is a spelling differed..
v-add-letsencrypt-domain
Line#193 - Let's Encrypt vvalidation status

**Comment by ScIT-Raphael** [comment]
Thanks for your report, is fixed in the following commit: https://github.com/hestiacp/hestiacp/commit/6fb09dcd6a26c9d98db2ec40b35af220a991323c
