### ISSUE TITLE
Odd username preview for Additional FTP

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#1424]
### In a few words, please describe the issue that you're experiencing:
There is a preview with double prefix for usernames of any already set, unchangeable Additional FTP Account(s). It doesn't do much harm but since the name cannot be changed, it's simply unneccesary and looks odd. People may think that upon saving the domain again, that is what the name will become (which I believe did actually happen in Vesta):

![odd](https://user-images.githubusercontent.com/20109369/100273803-aa445100-2f5d-11eb-8134-dc279551de00.png)

### What steps did you take when the issue occured? 
1. Add any Additional FTP Account(s)
2. Save the domain
3. Look at the Additional FTP Account(s)

### Expected behavior:
No preview to be shown, instead of an incorrect preview showing.

### Operating system:
Debian 10

### Hestia Control Panel version:
1.3.1

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/1411

:)
