### ISSUE TITLE
File Manager shows HTML code instead of some files content

### ISSUE THREAD

**Issue by EAnsy** [hestiacp/hestiacp#1427]
### In a few words, please describe the issue that you're experiencing:
File Manager shows HTML code instead of some files content

### What steps did you take when the issue occured? 
1. Trying to view users' _/home/USER/logs/DOMAIN.*.log_ (click on filename or **...** then **View**)
2. See the window with HTML code of _https://DOMAIN:8083/list/user/_ %(
3. **...** then **Download** opens new page with _https://DOMAIN:8083/list/user/_ instead of downloading the log file.

### Expected behavior:
I expect to see the content of log files. Or dialog for downloading it.

### Operating system:
**Debian 10** container temlpate in **ProxmoxVE 6.x**

### Hestia Control Panel version:
**1.3.1**

### Additional notes:
All files looks good when viewing in SSH or some other ways.

![Screenshot_20201130_134205](https://user-images.githubusercontent.com/18551027/100588060-31554880-3313-11eb-8eff-5a74b980e341.png)

**Comment by jaapmarcus** [comment]
As log files are saved in /etc/{web system}/domains/ I think falls outside the permission that the ssh user has

As the root has read access to this folder it executes the command fine

Use the binocular to view the log files
<img width="139" alt="Screenshot 2020-11-30 at 10 11 41" src="https://user-images.githubusercontent.com/9754650/100590467-bd0bac80-32f4-11eb-9a62-3f4efc2d0b77.png">

**Comment by EAnsy** [comment]
> As log files are saved in /etc/{web system}/domains/ I think falls outside the permission that the ssh user has
> As the root has read access to this folder it executes the command fine
> Use the binocular to view the log files

I see, but:

1. Binocular is not in the File Manager.
2. File Manager still has to show correct data (or an error) even on the files without enough permissions.

**Comment by jaapmarcus** [comment]
1. Binocular is not in the File Manager. 
 True it in the /list/web folder
2. This is a limitation of the current file manager. We can't change that sadly enough with out changes right to certain folders and files. And I don't think we want that. 

If you have a good solution please create a pull request for it.  But the issue can be closed
