### ISSUE TITLE
Error: Error: target dir outside of target domain dir

### ISSUE THREAD

**Issue by DmitrySkibitsky** [hestiacp/hestiacp#1428]
When creating a domain that was previously deleted

```
Error: Error: target dir outside of target domain dir
```

**Comment by DmitrySkibitsky** [comment]
![2020-11-30_23-07](https://user-images.githubusercontent.com/20288556/100664918-ccc0da80-3360-11eb-987a-13674bba26e9.png)

**Comment by ScIT-Raphael** [comment]
The target folder needs to exist when you point to it, otherwise you'll get that error message.

**Comment by DmitrySkibitsky** [comment]
@ScIT-Raphael 
Help me understand this situation.
Here I created a php file for the test.
![2020-11-30_23-12](https://user-images.githubusercontent.com/20288556/100666494-c3843d80-3361-11eb-8a37-07e9ff130f6a.png)
And here is the Apache config
![2020-11-30_23-14](https://user-images.githubusercontent.com/20288556/100666608-f0385500-3361-11eb-92d1-58c00a580b55.png)
But going to the IP address, I see this message all the time.
```log
Success!
Your new web server is ready to use.
```
I understand that it does not see virtual hosts and displays default pages.

**Comment by ScIT-Raphael** [comment]
That's the default behaviour and is correct, on IP you'll see always the default message: https://forum.hestiacp.com/t/dedicated-user-ip-how-does-it-work/2171/2?u=scit

**Comment by DmitrySkibitsky** [comment]
There are no visit logs and no errors.
![2020-11-30_23-18](https://user-images.githubusercontent.com/20288556/100666897-7bb1e600-3362-11eb-820f-745b5cf4ad81.png)

**Comment by DmitrySkibitsky** [comment]
> That's the default behaviour and is correct, on IP you'll see always the default message: https://forum.hestiacp.com/t/dedicated-user-ip-how-does-it-work/2171/2?u=scit

It doesn't suit me at the moment. Sadness. Will have to ask to clear the vps.
Thanks for the timely responses.

**Comment by Lupul** [comment]
There is no point in serving a app directly on the IP addr without a hostname as it's imposible to get a LE ssl certificate and you can't add  addtional php apps on the same ip.
