### ISSUE TITLE
dovecot ssl config update for version 2.3+

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1432]
Dovecot ssl config is outdated for servers running Dovecot 2.3 and above. This throws a warning in Dovecot, although not an error.
doveconf: Warning: Obsolete setting in /etc/dovecot/conf.d/10-ssl.conf:2: ssl_protocols has been replaced by ssl_min_protocol
doveconf: Warning: Obsolete setting in /etc/dovecot/conf.d/10-ssl.conf:10: ssl_dh_parameters_length is no longer needed 

## Current (2.2) config 
```
ssl = yes
ssl_cert = </usr/local/hestia/ssl/certificate.crt
ssl_key = </usr/local/hestia/ssl/certificate.key

# Orig
ssl_protocols = !SSLv3 !TLSv1
ssl_prefer_server_ciphers = yes
ssl_cipher_list = ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SH>

# From and up to version 2.2
ssl_dh_parameters_length = 4096
# From version 2.3
# ssl_dh = </etc/ssl/dhparam.pem
```

## Suggested config for 2.3+
```
ssl = yes

ssl_cert = </usr/local/hestia/ssl/certificate.crt
ssl_key = </usr/local/hestia/ssl/certificate.key

# Intermediate config from here https://ssl-config.mozilla.org/
ssl_min_protocol = TLSv1.2
ssl_cipher_list = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1>
ssl_prefer_server_ciphers = yes

# From version 2.3. 
ssl_dh = </etc/ssl/dhparam.pem

```
On Ubuntu Xenial and Bionic, 2.2 is the default package. On Focal onwards its 2.3
https://packages.ubuntu.com/search?keywords=dovecot

The /etc/ssl/dhparam.pem file is already generated on a fresh server install. 
If its not present, generate with 
openssl dhparam -dsaparam -out /etc/ssl/dhparam.pem 4096
(the -dsaparam parameter, **massively** speeds up the process, by minutes, if not hours)

**Comment by ScIT-Raphael** [comment]
@plutocrat thanks for the issue report, you're right - we will check how we can resolve it due to different dovecot versions on different os versions :).

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2015

We have decide to drop TLS1.1 fully for mail April 2022 we will alter it then
