### ISSUE TITLE
Escape chars in cron tasks don't work

### ISSUE THREAD

**Issue by cristiancosano** [hestiacp/hestiacp#1433]
### In a few words, please describe the issue that you're experiencing:
When I try adding cron task (`find /home/user/images -type f -name "*.jpg" -exec jpegoptim --strip-all --max=60 {} ';'` or `find /home/user/images -type f -name "*.jpg" -exec jpegoptim --strip-all --max=60 {} \;`) the escaped char (`\` or `''`) for semicolon `;` is deleted and `-exec` option causes error.

### What steps did you take when the issue occured? 
Add new cron task from any user on Hestia Panel with escaped char.

### Expected behavior:
The cron task should have been added successfully with the escaped char.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
Hestia 1.3.0 

### Additional notes:
If I add manually cron task with `crontab -e` and go to edit this from HestiaCP input value is empty. I don't know if this is a bug or a known security measure. I warn you in case it is a failure.

**Comment by ScIT-Raphael** [comment]
In some way escaped yes, but that amount of code should be placed in a bash file inside of the user directory, then triggered from cron. This is more a user handling issue than a hestia problem :).
