### ISSUE TITLE
[Feature Request] Cloudflare DNS Zones syncronization

### ISSUE THREAD

**Issue by gabriel-curtino** [hestiacp/hestiacp#1436]
I've seen this feature in another panel and I think it could be really useful for a lot of us that make an extensive use of Cloudflare as DNS service.

### Expected behavior:
You provide your Cloudflare's `API Key` or `API Token` and HestiaCP synchronize the DNS Zones automatically with Cloudflare.

### Additional notes:
I think a global setting will be enough, but it will be even better if each user can specify his owns tokens globally or by domain.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/607

https://github.com/jaapmarcus/hestiacp/tree/feature/cloudflare_support

Need to spend / waste some time on it. How ever going to close the issue for now as it is duplicate
