### ISSUE TITLE
MariaDB service is running while from GUI is showing stopped after edit my.conf

### ISSUE THREAD

**Issue by Hipshares** [hestiacp/hestiacp#1437]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:

After editing my.conf, Mariadb is correctly running but from GUI it shows STOPPED.

### What steps did you take when the issue occured? 

1 - visit /list/server/
2 - click /edit/server/mariadb/
3 - add any option on my.conf such as _join_buffer_size = 1M_
4 - be sure "restart" on save is flagged
5 - Save
6 - MariaDB is showing stopped from GUI while is correctly running

If i re-edit my.conf to stock, GUI is showing Mariadb correctly running.

### Expected behavior:
GUI should shows the correct service status even with my.conf modifications

### Operating system:
DEBIAN 10.7

### Hestia Control Panel version:
1.3.1

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by ioannidesalex** [comment]
Can you please tell us if the issue persists in Hestie v1.3.2?

**Comment by Hipshares** [comment]
> Can you please tell us if the issue persists in Hestie v1.3.2?

yes, still the same behaviour

**Comment by jaapmarcus** [comment]
<img width="1062" alt="Screenshot 2021-01-18 at 09 36 59" src="https://user-images.githubusercontent.com/9754650/104891070-bdc5d400-5970-11eb-9ecb-18309700caef.png">

On Debian 10.7  I am not able to replicate the issue

I see that the is uptime is set to zero but that is expected

**Comment by jaapmarcus** [comment]
Please run:
/usr/local/hestia/bin/v-list-sys-services 

NAME           STATE    CPU  MEM   UPTIME
----           -----    ---  ---   ------
apache2        running  0    448   384
php-fpm        running  0    7     2434
nginx          running  0    21    2434
bind9          running  0    51    1362
exim4          running  0    1     2433
dovecot        running  0    0     2433
clamav-daemon  running  0    1187  2434
spamassassin   running  0    228   2433
postgresql     running  0    12    2433
mariadb        running  0.2  671   2
vsftpd         running  0    0     2433
cron           running  0    0     2433
ssh            running  0.2  2     2433
iptables       running  0    0     0
fail2ban       running  0.4  120   2434
root@dev:~#

**Comment by Hipshares** [comment]
yes, uptime or service running is not the issue ideed. Mariadb is working well after editi the my.conf from GUI, but (still from GUI) i see the service stopped even if is running

STEP 1
![image](https://user-images.githubusercontent.com/74708897/104892266-42fdb880-5972-11eb-80f1-30b8e0dd47c7.png)

After save, service is running but from GUI is marked as not running
STEP 2
![image](https://user-images.githubusercontent.com/74708897/104892431-76404780-5972-11eb-89f4-79c9d31c62f8.png)

STEP3
Mariadb is working (i can access correctly to phpmyadmin, web apps, etc ) but hestia says  is not
![image](https://user-images.githubusercontent.com/74708897/104892753-d931de80-5972-11eb-9667-fac7f9c68f0c.png)

**Comment by jaapmarcus** [comment]
The issue is caused by the error unknown variable 'join_buffer_size=1M' instead of the expected mysql version.

What is your installed mysql version?

**Comment by Hipshares** [comment]
![image](https://user-images.githubusercontent.com/74708897/104898005-61b37d80-5979-11eb-9dab-3aba3305cb1b.png)

**Comment by jaapmarcus** [comment]
Please try:
Editing line 235 from 

``` mariadb_v=`mysqladmin --version | awk 'NR==1{print $5}' | head -c 4 ` ```

 to 

``` 
mariadb_v=`mysql -V | awk 'NR==1{print $5}' | head -c 4`
```
