### ISSUE TITLE
HELO name IP address check giving false positives

### ISSUE THREAD

**Issue by jrohde** [hestiacp/hestiacp#1438]
It looks like the following HELO IP address check in /etc/exim4/exim4.conf.template gives some false positives:  

```
drop    message       = Helo name contains an IP address (HELO was $sender_helo_name) and not is valid
          condition     = ${if match{$sender_helo_name}{\N((\d{1,3}[.-]\d{1,3}[.-]\d{1,3}[.-]\d{1,3})|([0-9a-f]{8})|([0-9A-F]{8}))\N}{yes}{no}}
          condition     = ${if match {${lookup dnsdb{>: defer_never,ptr=$sender_host_address}}\}{$sender_helo_name}{no}{yes}}
          delay         = 45s
```

The first condition is matching strings like: "some-d1245f1a.random-hosting.name" which **is not** a valid string to match a PTR record with i think (as in the second condition).

I think it should match only IP addresses with digits separated by dot '.' (no dashes) and reversed IP with the addition of a 'in-addr.arpa' or 'ip6.arpa' string (e.g. 123.456.789.101 or 101.789.456.123-in-addr.arpa) * 

regex is not my expertise, but maybe something like this fixes it:

```(^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$)|(^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(-in-addr\.arpa|-ip6\.arpa)$))```

So the full condition becones:

```condition     = ${if match{$sender_helo_name}{\N(^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$)|(^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(-in-addr\.arpa|-ip6\.arpa)$))\N}{yes}{no}}```

I'm not really sure about the "\N' in the regex, but without them the regex fails with: "regular expression error in "(^(d{1,3": missing ) at offset 8". I hope someone with more knowledge of exim and/or PCRE might be able to explain ;-) 

\* see: [exim dnsdb lookup](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-file_and_database_lookups.html#SECTdnsdb) & [Arpa Reverse DNS](https://en.wikipedia.org/wiki/Reverse_DNS_lookup)

Last edit: just realized IPv6 isn't matched at all with the above regex. So to make this future proof i guess a new separate ipv6 condition or a better overal regex should be created.

**Comment by ScIT-Raphael** [comment]
The mail helo function has been reworked, could you please verify if the issue still exists? Until you're feedback I'll close your issue.

**Comment by jaapmarcus** [comment]
2021-11-05 19:33:00 H=serv78908167.xxxxxx-node.xxx [yyy.yyy.yyy.yyy] X=TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128 CV=no rejected MAIL <info@xxxx-xxxxx.xx>: Helo name contains a ip address (HELO was serv78908167.xxxxxx-node.xxx) and not is valid

Bug is still present

**Comment by jaapmarcus** [comment]
Did some testing and it seems and the check is also used in:
https://github.com/Exim/exim/wiki/AclHeloTricks#helo-contain-a-ip-part

How ever the line below contains an error it has an extra \ inside


${if match {${lookup dnsdb{>: defer_never,ptr=$sender_host_address}}\}{$sender_helo_name}{no}{yes}}

vs

${if match {${lookup dnsdb{>: defer_never,ptr=$sender_host_address}}}{$sender_helo_name}{no}{yes}}

@jrohde are you able to verify it the fix works?

**Comment by jrohde** [comment]
Sorry for the late reply.
I don't seem to be having any issues anymore regarding the HELO, so i'd say it's fixed indeed. 
Muchas gracias!

**Comment by jaapmarcus** [comment]
We have reverted the fix as it caused issues with users that use mail clients and where not able to connect properly...

**Comment by ronald-at** [comment]
Today I've had a server which was matched by this rule. Therefore, the problem still persists.
2025-03-30 21:39:58 H=serv50361260-xxxx.secure-xxxx.xxxx [yyy.yyyy.yyy.yyy] X=TLS1.3:ECDHE_SECP256R1__RSA_PSS_RSAE_SHA256__AES_128_GCM:128 CV=no rejected MAIL <no-reply@xyz.xyz>: Helo name contains an IP address (HELO was serv50361260-xxxx.secure-xxxx.xxxx) and not is valid
