### ISSUE TITLE
No template selection (Webserver, PHP) when create new domain

### ISSUE THREAD

**Issue by ManuelReschke** [hestiacp/hestiacp#1439]
### In a few words, please describe the issue that you're experiencing:
If i click on the button Create New Domain, there is no field to set the correct PHP and NGINX template. Why is that missing here?

Discord Image: [Screen](https://media.discordapp.net/attachments/738055379614826578/785840792248778792/unknown.png?width=909&height=676)

### What steps did you take when the issue occured? 
Just click on the create new domain button.

### Expected behavior:
The field for PHP and NGINX is visible.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.31

**Comment by jaapmarcus** [comment]
We should include: PHP-FPM template / Proxy Template and Web template in this case....
