### ISSUE TITLE
Slight issue with password on install

### ISSUE THREAD

**Issue by youradds** [hestiacp/hestiacp#1440]
Using the installer in a custom build script:

```
`echo "Please enter the admin login password [ENTER]";
read admin_password

echo "Please type your admin URL - i.e admin.foobar.com and press [ENTER]";
read admin_host

echo "Please enter your admin email address [ENTER]";
read email

echo 'Acquire::ForceIPv4 true;' > /etc/apt/apt.conf.d/99force-ipv4
#curl -O http://vestacp.com/pub/vst-install.sh
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh


bash hst-install.sh -n yes \
-w yes \
-t no \
-c no \
-x yes \
-z yes \
-b yes \
-i yes \
-m yes \
-l de \
-s $admin_host \
-e $email \
-p "$admin_password" \
--apache no \
-k no \
--port 9183 \
-o yes \
-t yes \
-d no`
```

If I pass in the password as "$12ZGz9cDjiAPXY$1", it gives me this password at the end of the install:

 -n2ZGz9cDjiAPXY-n

Is this a Hestia issue, or my end where the shell script is converting `$1` in my password to `-n` ?

**Comment by ScIT-Raphael** [comment]
it's e issue on your end, because you load the admin password with "$admin_password" which loads the var $1 (usualy argument). Probaly it would be an option to not escape the password, not sure - at least not hestia related :).

**Comment by youradds** [comment]
Ah ok. Well not a super biggie. Just happened to notice it. Its a build script I wrote for VestaCP, but I'm just porting it over to use hestia as it supports Ubuntu 20 :)

**Comment by ScIT-Raphael** [comment]
And will give you a lot of new features, checkout the changelog :).

**Comment by youradds** [comment]
Lookijng forward to it! Vesta seems to have stagnated so nice to see someone picking up the baton
