### ISSUE TITLE
Feature Request : myVesta secret URL feature

### ISSUE THREAD

**Issue by darkworks** [hestiacp/hestiacp#1442]
HI am wondering can we have [myVesta ](https://github.com/myvesta/vesta)  Secret URL feature in hestia cp it will be helpful in protecting hestiacp sites from crawlers who hunt for panels that its cpanel/vesta/hestia etc when they have flaw they hit thousands of sites like in past happen with vesta . so this secret url feature of myVesta will block crawlers from fetching default login page of hestia

thanks

**Comment by jaapmarcus** [comment]
Please check 

https://github.com/hestiacp/hestiacp/blob/main/web/inc/secure_login.php

**Comment by darkworks** [comment]
@jaapmarcus  can u tell how to enable secure login option in hestia kinda new to it
