### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dimys** [hestiacp/hestiacp#1445]
After updating the panel from version 1.2.x to the current version 1.3.1, I received a 500 error.

The update was launched via the web interface. 

### Operating system:
Debian 10

### Hestia Control Panel version:
Before update 1.2.3

### Additional notes:
/usr/local/hestia/log/nginx-error.log
`
2020/12/09 18:30:43 [error] 5291#0: *30 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function bindtextdomain() in /usr/local/hestia/web/inc/i18n.php:10
Stack trace:
#0 /usr/local/hestia/web/inc/main.php(82): require_once()
#1 /usr/local/hestia/web/login/index.php(6): include('/usr/local/hest...')
#2 {main}
  thrown in /usr/local/hestia/web/inc/i18n.php on line 10" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "xx.xx.xx.xx:8083"
2020/12/09 18:32:45 [error] 5291#0: *34 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function bindtextdomain() in /usr/local/hestia/web/inc/i18n.php:10
Stack trace:
#0 /usr/local/hestia/web/inc/main.php(82): require_once()
#1 /usr/local/hestia/web/login/index.php(6): include('/usr/local/hest...')
`

**Comment by ScIT-Raphael** [comment]
please update hestia-php aswell, apt update && apt upgrade is the way to go :).
