### ISSUE TITLE
Debian 10 + php 8.0 + exim-4.94

### ISSUE THREAD

**Issue by Piercerer** [hestiacp/hestiacp#1449]
### In a few words
1. Cannot find issue how to update exim 4.92 to 4.94
2. Cannot find how to set php 8.0 in Hestia
![exim](https://user-images.githubusercontent.com/35381793/101777939-392b9e80-3b04-11eb-950a-4f701dd03ff6.png)
CP

### What steps did you take when the issue occured? 
1. apt update & apt upgrade || root@server :~# exim --version || Exim version 4.92 #3 built 13-May-2020 16:01:31
2. root@server:~# php -v || PHP 8.0.0 (cli) (built: Dec  6 2020 06:56:45) ( NTS )

### Expected behavior:
1. exim 4.94
2. php 8.0 in HestiaCP web server settings

### Operating system:
 Debian 10 php 8.0 

### Hestia Control Panel version:
Hestia 1.3.1

**Comment by jaapmarcus** [comment]
Package for Debian 10 (Stable) is still 4.9.2.x 
See https://packages.debian.org/search?keywords=exim4

buster (stable) (mail): metapackage to ease Exim MTA (v4) installation 
4.92-8+deb10u4: all

PHP 8  is currently not support will be added in next release.
See https://github.com/hestiacp/hestiacp/pull/1441
