### ISSUE TITLE
Feature Request: Incremental Backups

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#145]
**The problem**

Vesta CP provides by default a backup system, this backup system creates a tar for each user every day (by default 10 copies are saved), But this way of making backups has some disadvantages when you have a lot of users:

Server overload. Earch time the backup is run, a complete copy of user files are saved.
Disk space consumption. Each backup copy contains a full backup of the user files. So its very easy to run out of disk space.

**The solution**

An incremental backup is one in which successive copies of the data contain only the portion that has changed since the preceding backup copy was made. This way you can store lot of backups points, without making a full backup each time.

Borg Backup does an excellent job making incremental backups. And provide very interesting features such as compression, encryption and good performance. You can get more info at https://www.borgbackup.org/

https://github.com/ramirojoaquin/vestacp-borg-incremental-backups

**Comment by ScIT-Raphael** [comment]
Good idea, will get it checked.

**Comment by beli42** [comment]
Also splitting backup into configuration and data backups would be a nice feature.

**Comment by ioannidesalex** [comment]
The tricky part is to maintain support of restoring Vesta backups. At least for now.

**Comment by ScIT-Raphael** [comment]
On the VestaCP Github page, this was also discussed already: https://github.com/serghey-rodin/vesta/issues/1823

I'm not sure if we can solve that as requested, also infact @ioannidesalex wrote it properly, that we need to stay compatible to vesta backup - at least for now :)

**Comment by JOduMonT** [comment]
As best practice, a backup should be **pull from** a server and _never push to_ another one
simply because if you push your backup is means if your server is compromise the "hacker" could also compromise the backup and gain access to the machine where the backup are.

#### With this in mind

if you have a home a old PC or a raspberry and you configure correctly rsnapshot or urbackup and you don't expose them to Internet (open any port) you should have a relatively secure and incremental backup. This kind of box is easily realizable with [OpenMediaVault and his extra tools](http://omv-extras.org/joomla/index.php/omv-plugins-4)

**Comment by JOduMonT** [comment]
### What I could propose and is possible right now

it's to use a service like https://www.hetzner.com/storage/storage-box
which is compatible with **sftp** (already supported by vesta/hestia)
but also compatible with **borg** (desire/mightbe future solution)

**Comment by FalzoMAD** [comment]
I suggest to keep it simple (and compatible) by continue using tar, but look into it's inbuilt incremental function: https://www.gnu.org/software/tar/manual/html_node/Incremental-Dumps.html

we already do seperate archives for files and mails which get bundled together with mysql and the conf data again in the end. 

it should be easy to do the first level of archives with the incremental switch and even include the metafile in the overall tar, helping also with a proper restore later on.

btw: borg does not do increments but deduplication. while it works really good, it might be more difficult to extract a few single files compared to tar archives.

**Comment by loxK** [comment]
Just use duplicaty alone or through backupninja

**Comment by JOduMonT** [comment]
@FalzoMAD KISS principle is always the best for users and developers :)
why not to simply add an option to active a rsync and a destination for it ?

**Comment by FalzoMAD** [comment]
@JOduMonT 

> why not to simply add an option to active a rsync and a destination for it ?

yes that might be an interesting option as well, though it won't do any increments, just updates. also not compressing and still need a proper mysqldump beforehand.

so I'd rather consider that as an additional option (I am usually using rsync exactly for that in addition to local backups anyway) ;-)

**Comment by tlcd96** [comment]
also it could have an git option instead of rsync

**Comment by ramirojoaquin** [comment]
I am the creator of https://github.com/ramirojoaquin/vestacp-borg-incremental-backups repo, if you want i can help implement this in hestia.
I am using the incremental backup scripts on my productions servers with hestia and they are working very well. The only thing left is to create the apropiate ui buttons for restore, etc. Right now i run the scripts by console.

**Comment by ghost** [comment]
Hi @ramirojoaquin, if you'd be willing to help us implement incremental backups using the scripts you've created please feel free to send us a pull request for review and we'll go from there. :)

**Comment by ScIT-Raphael** [comment]
We currently do not have enough resources to fullfill all feature requests, I'm going to close this issue now.
