### ISSUE TITLE
When setting a new password for an email account, password complexity rules does not work all the time.

### ISSUE THREAD

**Issue by ozgurerdogan** [hestiacp/hestiacp#1450]
When setting a new password for an email account, password complexity rules does not work all the time - this happens rarely.

But I was even able to save account with an empty password field - this can be reproduced all the times.

**Comment by jaapmarcus** [comment]
Please check the console.log / error  when it happens if this issue is happening.

So far I didn't encounter any issue  yet...

Editing email address with out changing password should be allowed as it will allow you to update the setting and not the password.  (Quota , forwarder, auto reply)

**Comment by ozgurerdogan** [comment]
Sorry my mistake. I forgot that. I will try to find something in console log but it does does not happen all the time. Maybe my chrome is doing something with its plugins. U have some password related plugins.

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/change-password-complexity/2261

**Comment by jaapmarcus** [comment]
Fixed the bug in the linked Pull request thanks for reporting :)

**Comment by jaapmarcus** [comment]
Fixed will be released with next release
