### ISSUE TITLE
[Feature request] Allow forward email to :blackhole:

### ISSUE THREAD

**Issue by gabriel-curtino** [hestiacp/hestiacp#1454]
It will be nice that Hestia allow to forward email to `:blackhole:` by its front-end.

### What steps did you take when the issue occurred? 
1. Setup a new email account
2. Add `:blackhole:` to the _Forward to_ list

`Error: invalid email format :: :blackhole:`

### Expected behavior:
No error, allowing to forward to the `:blackhole:` exim system alias.

### Additional notes:
Allow `:blackhole:` but not `/dev/null`. If exim is not properly setup to deliver to `/dev/null` the transport may fails. `:blackhole:` instead should work out of the box.

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/mail-fowrard-to/2262/5

Probally we need to add an exception for ":blackhole:"  when updating / adding the forwarder

**Comment by jaapmarcus** [comment]
<img width="490" alt="Screenshot 2020-12-24 at 00 26 29" src="https://user-images.githubusercontent.com/9754650/103044201-fc3dbe00-457f-11eb-8d10-fe26b0ab0b40.png">

I think this is fine or not?

**Comment by jaapmarcus** [comment]
We have merged the pull requests with the changes above.
