### ISSUE TITLE
Roundcube + custom port, password driver plugin, etc

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#146]
Hi, 
The issue : ROUNDCUBE configs modifications..
1. If we use custom hestia port, the same have to update inside roundcube configs.
2. For Roundcube password change plugin, need to manually hardcode the hostname & port number again.

Is it possible to replace your installation files, with dynamic variables as %HOSTNAME%, %Hestiaport% etc..?
for Eg:
https://github.com/hestiacp/hestiacp/blob/7815c274aa3a88c5afc7e8e80bb3b64cb574b22f/install/ubuntu/16.04/roundcube/hestia.php#L23
https://github.com/hestiacp/hestiacp/blob/7815c274aa3a88c5afc7e8e80bb3b64cb574b22f/install/ubuntu/16.04/roundcube/hestia.php#L17

**Comment by ScIT-Raphael** [comment]
The host not, but for the port there already exists a change port script:

v-change-sys-port PORT
v-change-sys-webmail whateveryouwant (default: webmail)
v-change-sys-pma whateveryouwant (default: phpmyadmin)

**Comment by vvcares** [comment]
Ooh yeah. Got it. Thanx.. :-)
