### ISSUE TITLE
[Feature request] - Scan PHP files with ClamAV

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1466]
If a website gets comprimised, maybe a malware scan in cron could help.

I can think of two possible scenarios:
- Run daily scans to new files or changed files.
- Use incron to trigger clamAV as the file is closed by the operating system.

We would have to import the virus signatures too.

**Comment by johnnyq** [comment]
Yes I like this too =] +1

**Comment by Piercerer** [comment]
sudo nice -n 19 clamscan /home -r --include=php -o -i -l /log/clamav/daily.log

 Making it very "nice -n 19" means it'll let other processes do their work before its own. This means if there are lots of other busy processes, yes, it'll take a long time to do its own work but if there's nothing on there, it'll just chunk through its workload.

**Comment by jlguerrerosanz** [comment]
I would suggest this:

Scan new files or recently edited files

---
#!/bin/bash
for folder in /home/\*/web/\*/public_html
do
find $folder -type f -newerct '2 days ago' | grep ".php" | tee -a /tmp/filelist.txt
find $folder -type f -newerct '2 days ago' -name ".*" | grep ".php" | tee -a /tmp/filelist.txt
done
date
clamscan -i -f /tmp/filelist.txt --move=/quarantine
rm /tmp/filelist.txt
---

We would also have to download the signatures:
https://community.spiceworks.com/topic/2269879-clamav-custom-signatures
https://forum.opnsense.org/index.php?topic=14024.0
DatabaseCustomURL http://www.rfxn.com/downloads/rfxn.ndb
DatabaseCustomURL http://www.rfxn.com/downloads/rfxn.hdb
DatabaseCustomURL http://www.rfxn.com/downloads/rfxn.yara

**Comment by Piercerer** [comment]
I noticed ClamAV is eating CPU & memory. Hope this will help - add:
vi /etc/systemd/system/clamav-daemon.service.d/extend.conf
[Service]
IOSchedulingPriority = 7
CPUSchedulingPolicy = 5
MemoryLimit=256M
CPUQuota=30%
Nice = 19

**Comment by ScIT-Raphael** [comment]
We just discussed it in our dev chat: We will not implement any auto scan by default, this would be to resource intensive and should be a decission of every admin. We will expand our docs with "how to set a cronjob to trigger the scans" as written above.

**Comment by ScIT-Raphael** [comment]
I'll close the issue, moved it to hestiacp-docs.

**Comment by jlguerrerosanz** [comment]
> We just discussed it in our dev chat: We will not implement any auto scan by default, this would be to resource intensive and should be a decission of every admin. We will expand our docs with "how to set a cronjob to trigger the scans" as written above.

Can we just include the feature as an option in the hst-install.sh?

You may decide wether you want postgresql or have clamav scan php files.

**Comment by jaapmarcus** [comment]
No, Clamv AV can be setup via Cronjob / manually. Feel free to update the Hestia Docs
