### ISSUE TITLE
[Feature Request] Email migration tool from GUI

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1467]
I think that it would be interesting to have IMAPSYNC installed with a GUI.

You can provide Hestia with a csv file with:

mail.server.com;account@domain.com;p4ssw0rd;
mail.server2.com;account2@domain2.com;p4ssw0rd;

And then feed that to **imapsync**.

Hestia could then **create the accounts** with the **same passwords**, assign the **username = domain.com** and a **default plan**.

And then migrate all the mails in the mailboxes.

**Comment by johnnyq** [comment]
Oh this would be very nice indeed!! +1
