### ISSUE TITLE
Add web domain button displaying where it shouldn't

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1469]
### In a few words, please describe the issue that you're experiencing:
When I log in as an user in a plan whithout web hosting
- Only DNS
- DNS and Email only

after login, the user visits: https://server1.mydomain.com:8083/list/web/

It should go directly to the dns url: https://server1.mydomain.com:8083/list/dns/

Therefore you see an empty list and the button.

### Operating system:
Debian 10

### Hestia Control Panel version:
Hestia 1.3.1

**Comment by jaapmarcus** [comment]
This is easy solve able. Issue is only what priority to be used:

Web -> Email -> DNS -> DB
Or Web -> DNS - Email -> DB

**Comment by johnnyq** [comment]
This sounds logical +1

**Comment by jlguerrerosanz** [comment]
I would use the **natural panel's interface order**.

Web -> DNS - Email -> DB -> Cron > Backups

**Comment by ghost** [comment]
This has been fixed for v1.5 which is currently in early development.
