### ISSUE TITLE
Suggestion: Change the default Web/Proxy templates to more secured by default

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#147]
As ref # https://vestacp.com/docs/#template-description
Why not HestiaCP set the default templates as secured instead of end user changing that..?

WEB TEMPLATE >>  basedir - to fight against phpshells using openbasedir directive
PROXY TEMPLATE>> hosting - disable_symlinks directive to protect from symlink attacks

This may make the HestiaCP moving ahead with secured env by default..

**Comment by ScIT-Raphael** [comment]
The web templates are already using openbasedir as default. But I will check if disable symlink would be a option to set as default.

**Comment by ScIT-Raphael** [comment]
Hestia does already support the named templates, you're free to select them on your own. I will close the issue for now, please reopen it if you've any questions.
