### ISSUE TITLE
[Feature Request] Check if the DNS server is actually configured as the DNS server in the Registrar

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1470]
Sometimes my people forget to check if the DNS server is the correct one and change the records with no effect at all.

Display a warning to the user.

**Comment by johnnyq** [comment]
nice suggestion @jlguerrerosanz +1

**Comment by danielalexis** [comment]
For people who use the built-in DNS server from hestia this would be a nice addition but for people who use other servers, like cloudflare, this wouldnt work

**Comment by jlguerrerosanz** [comment]
Of course. It is only a warning so you know, **Maybe you can configure the warning not to be shown again.**

**Comment by ghost** [comment]
We'll need to discuss further internally before committing to anything, but perhaps we could look at surfacing a small warning under the associated DNS domain when viewing the list records screen (similar to how we currently warn not to add web domains under the admin account) in the event that nslookup returns different nameservers than what would be expected at the Hestia server level.

For example: 

> **Warning:** The nameservers for this domain are currently set to **ns1.domain.tld, ns2.domain.tld.** Please log into your DNS provider to change or update DNS records.

**Comment by aaronsql2019** [comment]
i'm sorry to be a nuisance, but I have a couple of servers with a broken DNS config, and I cannot for the LIFE of me figure out how to fix this. I really through I had done it correctly by changing the RDNS on the Linode, but that didn't do what I want. Is there an article on how to test for proper DNS config? Either way, I'd UPVOTE this request, if Github was as sophisticated as reddit.com was. :)

**Comment by ScIT-Raphael** [comment]
We currently close this issue - with the existing system we do not want to implement breadcrumbs. This may be integrated, if we find enough time to do a whole rewrite of the interface.
