### ISSUE TITLE
Do not allow removal of active used php versions.

### ISSUE THREAD

**Issue by ronald-at** [hestiacp/hestiacp#1477]
### In a few words, please describe the issue that you're experiencing:
After the update of hestia to 1.3.2 I changed all the PHP-versions from 7.4 to 8.0. Afterwards I wanted to remove php-7.4 in the "Configure server" page. The task didn't finish and I ran into an Internal Server error.

### What steps did you take when the issue occured? 
1. Click on the "Server" button.
2. Click on the "Configure" button.
3. Cllick on "Web Server".
4. Deselect check box "php-7.4".
5. Click on the "Save" button.
6. After a few minutes I received an "Internal Server Error".

### Expected behavior:
php-7.4 should be removed without any error.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.2

### Additional notes:
When I had a look on the running processes, I found out that phpmyadmin was removed with many other packages. During the phpmyadmin removal, there was a question with whiptail, if  the database of phpmyadmin should be removed or not. At that point the removal was stuck.

These are the processes, which were participating during the removal. I forgot to copy the whiptail process, so it is missing in the list:
sh -c /usr/bin/sudo /usr/local/hestia/bin/v-delete-web-php '7.4'
/usr/bin/sudo /usr/local/hestia/bin/v-delete-web-php 7.4
/bin/bash /usr/local/hestia/bin/v-delete-web-php 7.4
apt-get -y purge php7.4-mbstring php7.4-bcmath php7.4-cli php7.4-curl php7.4-fpm php7.4-gd php7.4
/usr/bin/dpkg --status-fd 61 --no-triggers --force-depends --abort-after=1 --remove phpmyadmin:al
sh -c (test -x /usr/lib/needrestart/dpkg-status && /usr/lib/needrestart/dpkg-status || cat > /dev
sh -c (test -x /usr/lib/needrestart/dpkg-status && /usr/lib/needrestart/dpkg-status || cat > /dev
/bin/sh /usr/lib/needrestart/dpkg-status
/usr/bin/perl -w /usr/share/debconf/frontend /var/lib/dpkg/info/phpmyadmin.prerm remove
/bin/sh /var/lib/dpkg/info/phpmyadmin.prerm remove

**Comment by jaapmarcus** [comment]
There are still multiple systems still depending on 7.4 (phpmyadmin, roundcube ) 

How ever phpmyadmin should not have been deleted

**Comment by ScIT-Raphael** [comment]
We will prevent the removal of an active used php version in a feature release, also combine it with the suggested rewrite of the detection routine: https://github.com/hestiacp/hestiacp/issues/1480

**Comment by jaapmarcus** [comment]
This should also include the Roundcube  PHP-FPM  / www.conf!

**Comment by jaapmarcus** [comment]
Issue should be solved 1.4 >
