### ISSUE TITLE
some errors during clean install

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#1478]
### In a few words, please describe the issue that you're experiencing:
Some errors during install

### What steps did you take when the issue occured? 
Basic install
[ * ] Configuring NGINX...
cp: cannot stat '/etc/php/5.6/': No such file or directory
[ * ] Install PHP version 5.6...
[ * ] Install PHP version 7.0...
[ * ] Install PHP version 7.1...
[ * ] Install PHP version 7.2...
[ * ] Install PHP version 7.3...
[ * ] Install PHP version 7.4...
cp: cannot stat '/etc/php/8.0/': No such file or directory
[ * ] Install PHP version 8.0...

### Expected behavior:
no error messages

### Operating system:
Debian 10

### Hestia Control Panel version:
1.3.1/1.3.2

### Additional notes:
This apparently doesnt harms nothing .. I believe... but ... its sounds good to fix.

**Comment by ScIT-Raphael** [comment]
Thanks for the issue report, it has been already fixed and will be released with the next version.

**Comment by jaapmarcus** [comment]
The error has "no" issues on the system. It is used in the backup of the old (non existing) config files
