### ISSUE TITLE
Small bug and improve Domain using php detection 

### ISSUE THREAD

**Issue by mysterydata** [hestiacp/hestiacp#1480]
I’ve a site which doesn’t uses any php and using no php template but its still listed in the list of php 7.4 list (multi php) which is misleading. The detection should be improved.

possible solution  : 

`grep -lr --include=*.conf "unix:/run/php" /home/*/conf/web/* | cut -d"/" -f6 | sort -uk1`

it will list the domain name who are using php

eg : 

```
root@server:~# grep -lr --include=*.conf "unix:/run/php" /home/*/conf/web/* | cut -d"/" -f6 | sort -uk1
domain.com
server.domain.com
```

**Comment by mysterydata** [comment]
hope it will be added soon :) @ScIT-Raphael

**Comment by ScIT-Raphael** [comment]
If you directly implement it into a PR, I can promise it will be with the next version ;).

**Comment by jaapmarcus** [comment]
Template "no-php" is still created in the pool (7.4) but commented out... We should not depend on a check if an .php file is active. / located in the user dir. But probably find an other way to fix the issue. Also the default php version is stil used for webmail.

**Comment by mysterydata** [comment]
> 
> 
> Template "no-php" is still created in the pool (7.4) but commented out... We should not depend on a check if an .php file is active. / located in the user dir. But probably find an other way to fix the issue. Also the default php version is stil used for webmail.

it will look into this dir (wildcard username) : 
`/home/*/conf/web/*`

**Comment by jaapmarcus** [comment]
What is "PHP-7.3" template is active  and leaves the website for while as it currently is.  

"You" as admin check decides to remove php-7.3 as no body uses it 

User decides to install wordpress and what now? Wordpress will not work as 7.3 is missing. 

Probally the best way to fix it is creating an "extra" pool.conf folder where no-php templates are saved and this doesn't depend on the current php version

**Comment by mysterydata** [comment]
> 
> 
> What is "PHP-7.3" template is active and leaves the website for while as it currently is.
> 
> "You" as admin check decides to remove php-7.3 as no body uses it
> 
> User decides to install wordpress and what now? Wordpress will not work as 7.3 is missing.
> 
> Probally the best way to fix it is creating an "extra" pool.conf folder where no-php templates are saved and this doesn't depend on the current php version

we can filter out like this : 
for php 7.4
`grep -lr --include=*.conf "unix:/run/php/php7.4" /home/*/conf/web/* | cut -d"/" -f6 | sort -uk1`

for php 7.3
`grep -lr --include=*.conf "unix:/run/php/php7.3" /home/*/conf/web/* | cut -d"/" -f6 | sort -uk1`

**Comment by mysterydata** [comment]
and this is only detection of sites which are using specific php versions, there is nothing to do with template delete or create.

**Comment by ScIT-Raphael** [comment]
We will proceed this request together with #1477
