### ISSUE TITLE
Off server proxy configurations

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#1482]
Its great to be able to map ports 80 and 443 directly to a HestiaCP server and handle all the setup from its UI.

However when you need to use the same IP for other web applications that aren't hosted on the Hestia server, you usually end up having to set up a second downstream reverse proxy.

It would be great if HestiaCP had an option just to map a domain name (with all the SSL features) but let it point to an 'Off Server' resource.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/1453

Double. If we are going to implement an "proxy" system we "should" allow  all the option. To condense the related issues... See #1453
