### ISSUE TITLE
[Feature request] - Ipset Whitelist add from text field

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1484]
### In a few words, please describe the issue that you're experiencing:
Ipsets have to be added from a file or http location.

It would be very convenient to have a text field in the backend to paste some IPs in order to create **at least two local ipsets**. One for blacklisting and another for whitelisting.

**Comment by jaapmarcus** [comment]
Currently IPset implementation will not work with less then 10 ip's 

For both fail2ban as iptables we accept ip ranges when cird format is used. 

Related issue: https://github.com/hestiacp/hestiacp/issues/1395

**Comment by Lupul** [comment]
IPset lists can be used for white-listing too, actually that's the way i'm using it currently.
If the ip list is too short (<10) then there is no point in using ipset, iptables should be used in that case
