### ISSUE TITLE
[Feature request] - v-add-web-app

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1485]
### In a few words, please describe the issue that you're experiencing:
I can't create a WordPress Install from the CLI

I would love to have my bash script

- Create User
- Create DNS Zones
- Create EMAIL accounts
- Create Web Domain
- **Install Wordpress**
- Copy wp-content from repository
- ...

It is very complicated from bash to install WordPress but **the functionality is already in Hestia**.

### Additional notes:
v-add-web-app
add app from the app installer

Label: web

Options: USER DOMAIN APP

Examples:

v-add-web-app myuser mydomain.com wordpress
v-add-web-app myuser mydomain.com drupal

**Comment by shaneshuford** [comment]
I would also love to see this feature.

**Comment by jaapmarcus** [comment]
The current "Quick Install" app is currently written in PHP and not in Bash...  So if we are going to do it would be a lot of work... 

Also issues to solve how we are going to handle "optional" settings like default user / default password / database creation ect......

**Comment by jlguerrerosanz** [comment]
And how about call php from bash?

**Comment by ScIT-Raphael** [comment]
You cant call this parts from bash, there isnt an api for the web installer - otherwise @jaapmarcus would have wrote about this possibility.

**Comment by jaapmarcus** [comment]
The current api calls only the bash commands. In that point of view at least the api is limited... 

For Wordpress WP-CLI might be worth a try. For composer based systems try v-add-user-composer and run the composer commands via CLI...

**Comment by Lupul** [comment]
installing wp from cli should be pretty straigh fwd using wp-cli
https://blog.sucuri.net/2015/08/wp-cli-guide-installing-wordpress.html

**Comment by wojsmol** [comment]
I have bash script for installing WordPress - using WP-CLI and vestacp API calls - with randomly generated database details and database table prefix.

**Comment by jaapmarcus** [comment]
Put it on GitHub and share it.... There is no need to become a part of Hestia for it...

**Comment by wojsmol** [comment]
@jaapmarcus https://github.com/hestiacp/hestiacp/issues/1236 is blocking conversion of this script to Hestia when running API calls from the same server. I don't wont share version dependent on insecure Vestacp API :smile:

**Comment by shaneshuford** [comment]
wp-cli will work for my needs, but it would still be a good idea in my opinion to at some point create a hestia cli/api endpoint for installation of web applications, this seems to me as an obvious addition to an already amazingly useful panel.

**Comment by jlguerrerosanz** [comment]
I was thinking about expanding the concept a bit.

How about:

- export wp
- import wp
- clone wp
- move to staging
- deploy staging to production

**Comment by shaneshuford** [comment]
@jlguerrerosanz 
I think that might be overkill. "Quick Install App" CLI/API is enough. WordPress, Drupal, Symfony etc.

**Comment by jaapmarcus** [comment]
As is currently stands It will still require extended rewrite of the system.  

And it will have a currently low priority.  There are other issues with  way higher priorities than this one. 

This is more an issue for my "this is nice to have one list" then the "I need this feature list"

**Comment by ScIT-Raphael** [comment]
As explained from @jaapmarcus, I'm going to close this feature request.

**Comment by jlguerrerosanz** [comment]
> I have bash script for installing WordPress - using WP-CLI and vestacp API calls - with randomly generated database details and database table prefix.

@wojsmol please can you somehow share it with me? I will need some inspiration to make my own.

**Comment by wojsmol** [comment]
@jaapmarcus @jlguerrerosanz I published simple version of my script [here](https://github.com/webmetric-agency/vinstallwp). I plan to add readme shortly.

**Comment by jlguerrerosanz** [comment]
Thank you very much! I have read through the source code. I think I will be able to make my scripts work. Thank you again!

**Comment by wojsmol** [comment]
In case on any issue create issue in linked repo :)
