### ISSUE TITLE
Roundcube - An error occurred! Could not save new password.

### ISSUE THREAD

**Issue by paoloabdullah** [hestiacp/hestiacp#1486]
### In a few words, please describe the issue that you're experiencing:

When I try to change the email password at roundcube, I get this error: An error occurred! Could not save new password.

### What steps did you take when the issue occured? 
1. Login to webmail
2. Go to Settings
3. Password (at this exact link: webmail.domain.com/?_task=settings&_action=plugin.password-save)
4. Changed the password 

### Expected behavior:
It should be successful.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
v1.3.2

### Additional notes:

Exact link of the roundcube password change: https://webmail.domain.com/?_task=settings&_action=plugin.password-save
Installed version: 1.3.1 (The system updated and current version is v1.3.2)
web server: Nginx + PHP-FPM
PHP VERSIONS INSTALLED: 7.4 and 7.3

**Comment by jaapmarcus** [comment]
I am not able to replicate the issue. The only issue it could if the detection of the ip adress:

https://github.com/hestiacp/hestiacp/blob/4b4edd540ffde7f17a364aa3911c11b71b477eab/web/reset/mail/index.php#L11-L26

Don't know I you run Hestia behind a firewall / nat / Cloudflare?

**Comment by jaapmarcus** [comment]
Please check /tmp/roundcube.log

**Comment by jaapmarcus** [comment]
Please provide us with aditional

**Comment by paoloabdullah** [comment]
Hi Jaap. Sorry was on vacay. Yes, it is behind cloudflare. Should I turn off the mail and the webmail cloudflare?

**Comment by jaapmarcus** [comment]
It uses https://localhost/ so it should not be affected

try again and check /tmp/round cube.log and see what is  in there

**Comment by paoloabdullah** [comment]
root@mail:~# cat /tmp/roundcube.log
test ok
root@mail:~#

No log after I tried changing the password.

**Comment by jaapmarcus** [comment]
Just tested the issue is that:
`v-change-sys-hostname host.domain.com`
does not update /etc/roundcube/plugins/password/config.inc.php

https://github.com/hestiacp/hestiacp/blob/4b4edd540ffde7f17a364aa3911c11b71b477eab/bin/v-change-sys-hostname#L40-L52

Thanks for reporting.

**Comment by Machiel92** [comment]
It doesn't update the hostname nor the port.
I've changed the Hestia port. Changed it from 8083 to something different like 9999
It still keeps it on > $rcmail_config['password_hestia_port'] = '8083';

**Comment by ghost** [comment]
Issue has been resolved in v1.4 which will be released soon. :)

**Comment by poolerMF** [comment]
I had same problem
in ./roundcube/logs/errors I found error

FUNCTION roundcubedb.update_passwd does not exist (SQL Query: SELECT update_passwd('$1$eXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'XXXXX@XXXXXXXX.com')) in ./roundcube/program/lib/Roundcube/rcube_db.php on line 543

Webmail 1.3.8 (password | 4.2)
10.3.12-MariaDB-1:10.3.12+maria~bionic

I solved it by logging into DB and manually changing password I get from errors log
