### ISSUE TITLE
Can't activate SSL on mail for a NDD that use dedicated IP

### ISSUE THREAD

**Issue by user67x** [hestiacp/hestiacp#1491]
Hello,

For a client, on a dedicated IP for a domain :

Click on the "MAIL" tab.
Click on a mail domaine et than "Edit the domain mail"
Check "Activate SSL for this domain" and "Use Lets Encrypt for obtain SSL certificat"

Attempted to add a SSL domain and received an Error (see the screencaps). The two entries exist on DNS (mail and webmail).

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.2

https://nsa40.casimages.com/img/2020/12/21/201221123154869930.png

EDIT: maybe the DNS change hasn't propagated yet, so put my report on hold. Thank you.

**Comment by ScIT-Raphael** [comment]
You get the error due to a basic check with nslookup, sonas you already commented, probaly the dns isnt in sync yet. I'll close the issue, if there should be any other problem, please feel free to write again or create a new report.
