### ISSUE TITLE
disk size not being calculated correctly on admin and user panel

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1497]
### In a few words, please describe the issue that you're experiencing:
disk size not being calculated correctly on admin panel and user panel (on top header)

### What steps did you take when the issue occured? 
On the Admin Panel, it's showing the wrong disk size
![image](https://user-images.githubusercontent.com/39749258/102982469-92e28e80-4530-11eb-91b6-9e5d50b69ccf.png)

but if you check the disk size from user panel it's around   154GB 
![image](https://user-images.githubusercontent.com/39749258/102982704-f967ac80-4530-11eb-9939-5654aa88e819.png)

also on the top, it's showing the wrong size (User Panel)
![image](https://user-images.githubusercontent.com/39749258/102982914-4c416400-4531-11eb-83b3-5ba52db5ec95.png)

### Expected behavior:
should show the correct size 

### Operating system:
Ubuntu 20.04 (x86_64)

### Hestia Control Panel version:
v1.3.2

**Comment by jaapmarcus** [comment]
Any other issues with users.

It seems to only calculated the user disk excluding domains / database

What happens when you run v-update-user-disk?

**Comment by 4183r** [comment]
![image](https://user-images.githubusercontent.com/39749258/102992898-2f615c80-4542-11eb-9fab-d64e7b1a5157.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/102992921-3c7e4b80-4542-11eb-9e3e-13a7b4d65f87.png)

**Comment by jaapmarcus** [comment]
There is something wrong with reading in the user config.

Can you post the contents of user.conf? 

https://github.com/hestiacp/hestiacp/blob/2a0c04566a31f9aa7057555f623b358fa65367bf/func/main.sh#L550-L553

**Comment by alber-khan** [comment]
yes after rebuilding everything is working fine now!

**Comment by jaapmarcus** [comment]
Is it working or not?

**Comment by alber-khan** [comment]
```
NAME='Alber'
PACKAGE='10D-160G'
WEB_TEMPLATE='default'
BACKEND_TEMPLATE='PHP-7_4'
PROXY_TEMPLATE='caching'
DNS_TEMPLATE='default'
WEB_DOMAINS='10'
WEB_ALIASES='unlimited'
DNS_DOMAINS='10'
DNS_RECORDS='unlimited'
MAIL_DOMAINS='10'
MAIL_ACCOUNTS='unlimited'
DATABASES='10'
CRON_JOBS='10'
DISK_QUOTA='unlimited'
BANDWIDTH='unlimited'
NS='ns1.example.ltd,ns2.example.ltd'
SHELL='bash'
BACKUPS='3'
CONTACT='xxxxx@xxxx.com'
CRON_REPORTS='yes'
MD5='$6$EM1Np4ANM140B/tm$Qqnyr/onAWg/AiL/supqpVtsroGvCj79P8L6wfWglzfDKw72yZEL6h7PZx0A/'
RKEY='sLCsZt30Nd'
TWOFA=''
QRCODE=''
PHPCLI='7.4'
ROLE='user'
SUSPENDED='no'
SUSPENDED_USERS='0'
SUSPENDED_WEB='0'
SUSPENDED_DNS='0'
SUSPENDED_MAIL='0'
SUSPENDED_DB='0'
SUSPENDED_CRON='0'
IP_AVAIL='1'
IP_OWNED='0'
U_USERS='0'
U_DISK='170881'
U_DISK_DIRS='1'
U_DISK_DIRS='1'
U_DISK_WEB='177384'
U_DISK_MAIL='0'
U_DISK_DB='1'
U_BANDWIDTH='11245072'
U_WEB_DOMAINS='4'
U_WEB_SSL='2'
U_WEB_ALIASES='1'
U_DNS_DOMAINS='1'
U_DNS_RECORDS='15'
U_MAIL_DOMAINS='1'
U_MAIL_DKIM='1'
U_MAIL_ACCOUNTS='0'
U_DATABASES='1'
U_CRON_JOBS='0'
U_BACKUPS='1'
LANGUAGE='en'
NOTIFICATIONS='yes'
TIME='13:39:39'
DATE='2020-09-28'

```

**Comment by jaapmarcus** [comment]
I just removed you email form the contact address would be useful to have the user.conf before the error happend. As it is working. Will close the issue for now as we can't reproduce the issue. If it happens again please provide us with user.conf before updating

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/102998501-435e8b80-454d-11eb-85bb-06cb9b640f52.png)

i'm still having the same issue

**Comment by jaapmarcus** [comment]
Check the contents of db.conf / mail.conf  If you see something wrong inside?

I have really no clue.. And can't repoduce the error probably over here...
