### ISSUE TITLE
Bug in email autoresponder

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1498]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When setting an autoresponder, the interface shows errors because of html illegal characters.
Maybe you could HTML transform all data in that field

The text provided:

> Sehr geehrte Damen und Herren, liebe KollegInnen
> Leider erreichen Sie mich außerhalb meiner Arbeitszeiten. Diese lauten über Weihnachten/Neujahr wie folgt:
> Vom 24.-26.12.2020 und 31.12.2020-01.01.2021 sowie am 06.01.2021 > NICHT verfügbar.
> Vom 28.-30.12.2020 und ab dem 04.01.2021 bin ich zu folgenden Arbeitszeiten für Sie da:
> Montag bis Donnerstag: 10-18 Uhr | Freitag: 10-16 Uhr
> Ich wünsche eine besinnliche Adventszeit und einen guten Start ins neue Jahr!

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/8faf69d966a4a3557bb662a68bbfeea486dade18/func/main.sh#L677-L682

The issue is in the |  sign as it is an char used in the sed command

**Comment by jaapmarcus** [comment]
```
root@dev:/usr/local/hestia/bin# v-add-mail-account-autoreply  'jaap' 'jaap.xxx' 'jaap' 'Sehr geehrte Damen und Herren, liebe KollegInnen
Leider erreichen Sie mich außerhalb meiner Arbeitszeiten. Diese lauten über Weihnachten/Neujahr wie folgt:
Vom 24.-26.12.2020 und 31.12.2020-01.01.2021 sowie am 06.01.2021 > NICHT verfügbar.
Vom 28.-30.12.2020 und ab dem 04.01.2021 bin ich zu folgenden Arbeitszeiten für Sie da:
Montag bis Donnerstag: 10-18 Uhr  Freitag: 10-16 Uhr
Ich wünsche eine besinnliche Adventszeit und einen guten Start ins neue Jahr!' 
```
Works fine the issue that there are certain characters are filtered out. The only solution is probably is a rewrite of the auto reply part as there also have been issues with ä ü ö. 

Don't know if there is an "easy" fix for it...

**Comment by jlguerrerosanz** [comment]
Maybe a warning of the illegal characters until you find the time to fix it.

Cannot you just html_encode the text in the front end? and transform the complicated symbols ñ -> `&ntilde;`

**Comment by jaapmarcus** [comment]
Haven't tested it yet fully. Was busy with an few other email related bugs ...

**Comment by jaapmarcus** [comment]
We might need to debug slightly more 

Edit the check on line 679 and it should work fine

`if  [ 10240 -le ${#1} ]; then `

And it should work fine
