### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by hopfrogsalerno** [hestiacp/hestiacp#1499]
Where are the errors related to the SITE? I found this directory but it is not readable and I don’t know what it refers to

domain
logs
domain.error.log

Sorry, I recently use Hestiacp and I did not find the necessary instructions to solve the problem. 
Thanks

**Comment by ScIT-Raphael** [comment]
Logs are in /home/user/web/domain.tld/logs, there are only accessible over ssh or backend. Would suggest to checkout our forum (https://forum.hestiacp.com) or our discord server (check the readme.md), github issues will be used more for reproduceable issues than questions :).

**Comment by jaapmarcus** [comment]
Please check: https://github.com/hestiacp/hestiacp/issues/937

As logs are saved /etc/{websystem}/domain.com they are not readable by the user

**Comment by hopfrogsalerno** [comment]
OK, thanks
