### ISSUE TITLE
Feature request - Option to skip creation of web folder for domains with custom document roots

### ISSUE THREAD

**Issue by nirbhasa** [hestiacp/hestiacp#1500]
This is a very small housekeeping issue. This is my use case:

- A user account with many (100+) domains, each pointing to the same document root
- My /home/{user}/web directory is filled with many domain folders that I don't need, and makes it hard to spot the one folder that I do need :) I did try manually removing the other folders, but they are recreated if the domain is edited, or if Hestia is upgraded.
- So it would be nice if in the 'custom document root' section, there was a checkbox to skip creation of the web folder

This is clearly not an end-of-the-world issue, but maybe it is easy to do...

**Comment by ScIT-Raphael** [comment]
I don't think this would make much sense to add this button. If all domains point to the same docroot, probaly using alias instead separated domains would be a better way to go.

**Comment by nirbhasa** [comment]
True - the only caveat is that for 100+ domains, LetsEncrypt wont let you put them all on the same domain cert, so you need more domains for that case.
