### ISSUE TITLE
[Feature Request] How to permanently ban ip block on all ports from Hestia CP

### ISSUE THREAD

**Issue by SCelik** [hestiacp/hestiacp#1502]
I want to ban known attackers permanently.

For example there are lots of login attempts for all services from 45.150.x.x

![image](https://user-images.githubusercontent.com/2869849/103068374-0dadb700-45ce-11eb-8d4f-f44782267ae1.png)

So I want to use Add IP to Ban List function from panel. But even if i can use CIDR format like 45.150.0.0/16, panel forces me to select a service (in other words, panel restricts me for some ports).

![image](https://user-images.githubusercontent.com/2869849/103068287-e1923600-45cd-11eb-95ed-08a19ecbcee7.png)

**Comment by jaapmarcus** [comment]
<img width="472" alt="Screenshot 2020-12-24 at 10 14 18" src="https://user-images.githubusercontent.com/9754650/103077825-da205c00-45d0-11eb-9bb8-3e10686c751b.png">

In Add Firewall rull 

IP port you want to block
Port: 0 (Will block all ips)

For support questions please use our forum.
