### ISSUE TITLE
Custom document root not restoring

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1505]
### In a few words, please describe the issue that you're experiencing:
when creating a backup and restoring it on new server it doesn't restore "Custom document root"

### What steps did you take when the issue occured? 
backup the user via Panel

then restoring it via command line "v-restore-user"

after restoring I manually need to change the "Custom document root"
![image](https://user-images.githubusercontent.com/39749258/103100723-f73d4500-4639-11eb-93e3-b2a407d64b8d.png)

### Expected behavior:
it should restore "Custom document root"

### Operating system:
Ubuntu 20.04 (x86_64)

### Hestia Control Panel version:
v1.3.2

**Comment by jaapmarcus** [comment]
Just tested and can confirm the bug

**Comment by jaapmarcus** [comment]
Pushed an fix that solves the issue
