### ISSUE TITLE
Can't enable LE SSL for any websites on Ubuntu 16.04

### ISSUE THREAD

**Issue by molny** [hestiacp/hestiacp#1509]
### In a few words, please describe the issue that you're experiencing:
Trying to enable a Let's Encrypt SSL certificate for the site, I keep getting the error "Error code: 15". Using the `v-add-letsencrypt-domain` command also fails.

### What steps did you take when the issue occured? 
1. Logging in to Hestia
2. Open the configuration of any site without SSL certificate
3. Press "Use Lets Encrypt to obtain SSL certificate" and then "Save".
4. I get the error `Error code: 15`

### Expected behavior:
SSL certificated should have been configured successfully

### Operating system:
Ubuntu 16.04.7 LTS

### Hestia Control Panel version:
1.3.2

### Additional notes:
Actually, I was able to find the cause of this error on my own and fix it. I need help from someone who knows more about bash-scripting than I do, to help me write a fix.

### The situation is as follows:

When using the `v-add-letsencrypt-domain` script, we may see a message like `curl: option --retry-connrefused: is unknown`.
![image](https://user-images.githubusercontent.com/1726455/103181856-9ff3da80-48ae-11eb-8c4a-a99a23b1d833.png)

This is because curl version **7.47.0** is in the Ubuntu 16.04.7 repositories, but the `--retry-connrefused` option was added in version **7.52.0**
![image](https://user-images.githubusercontent.com/1726455/103181928-4fc94800-48af-11eb-9f61-0b95621b9db4.png)

If you remove the `--retry-connrefused` parameter on the next line, everything works fine!
https://github.com/hestiacp/hestiacp/blob/4b4edd540ffde7f17a364aa3911c11b71b477eab/bin/v-add-letsencrypt-domain#L58

**⚠️ I think you just need to add a check on the Ubuntu version (or curl version) and add this parameter if necessary.**

**Comment by ScIT-Raphael** [comment]
Hi @molny 

First of all: Thanks for this awesome debug work, a lot of users would just have written "doesnt work".

We will discuss a current fix for it, but the easiest way for you would probaly be a os upgrade (take a snapshot/backup first!) to 18.04 or even 20.04. Ubuntu 16.04 will be EOL in april 21, we will follow it and drop the support then aswell for hestia.

Once again, amazing work!

**Comment by ScIT-Raphael** [comment]
We just discussed in dev chat: Infact we will drop the support of Ubuntu 16.04 due to their EOL date, we will not fix this issue. A other solution would also be to update curl manualy, following the guide provided from another user in our forum: https://forum.hestiacp.com/t/curl-option-retry-connrefused-is-unknown/2498/3

**Comment by molny** [comment]
@ScIT-Raphael Houston, we have a problem! Support for Ubuntu 16.04 extended until April 2026 :)
https://ubuntu.com/blog/ubuntu-14-04-and-16-04-lifecycle-extended-to-ten-years

**Comment by ScIT-Raphael** [comment]
Thanks for the information, end of life wasnt the right term in that case, more end of standard support which is april 2021: https://wiki.ubuntu.com/Releases

There will be no change to the decission, support has already been dropped and a upgrade to 18.04/20.04 isnt that difficult.

**Comment by jaapmarcus** [comment]
Also we are not able to keep support available for only a 60 out of the 13+ k users...
