### ISSUE TITLE
[Feature Request] - Add button to Whitelist a banned IP in the banned IPs list

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1511]
https://myserver.com:8083/list/firewall/banlist/
Next to the "+ add IP" button place a "Whitelist IP" button
Maybe an icon to whitelist next to the garbage can.

**Comment by johnnyq** [comment]
Good Idea

**Comment by jlguerrerosanz** [comment]
The actions associated with the IP could be:
*set ignoreip in fail2ban
*iptables allow all ports

**Comment by ScIT-Raphael** [comment]
We currently close this issue - with the existing system we do not want to implement this request. This may be integrated, if we find enough time to do a whole rewrite of the interface.
