### ISSUE TITLE
error v-list-sys-services

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1512]
The script throws this error. **Don't know if it is a bug. It seems to work**
`/usr/local/hestia/bin/v-list-sys-services
**/usr/local/hestia/bin/v-list-sys-services: line 298: lsb_release: command not found**
NAME           STATE    CPU  MEM   UPTIME
----           -----    ---  ---   ------
apache2        running  0    471   736
php-fpm        running  0    7     20346
nginx          running  0    61    736
bind9          running  0    67    736
exim4          running  4    9     736
dovecot        running  0    0     736
clamav-daemon  running  0.1  1679  81840
spamassassin   running  0.7  289   81840
mariadb        running  0    611   20346
vsftpd         running  0    0     81840
cron           running  0    0     17281
ssh            running  0    3     751
iptables       running  0    0     751
fail2ban       running  0.8  245   17073
`
Hestia version: 1.3.2
OS: Debian 10

**Comment by jaapmarcus** [comment]
For Debain the lsb-release is not always installed

**Comment by jaapmarcus** [comment]
Fix pushed when accepted it will be release in the next release
