### ISSUE TITLE
Issue with excluding certain web folders

### ISSUE THREAD

**Issue by youradds** [hestiacp/hestiacp#1516]
Latest stable release of Hestia

I'm trying to globally exclude a directory from being backed up. In particular the public_html for ALL domains. please see post:

https://forum.hestiacp.com/t/exclude-certain-directories-from-backup-from-all-domains/2423/5

### What steps did you take when the issue occurred? 

1) For a user, go into "Backups" and set "Exclusions". Try setting:

`foo.net:public_html`

This works. However, none of these seem to:

```
*:public_html/
*:public_html
*.:public_html/
```

It seems to not take into account the * wildcard. If I do:

`*`

It works as expected (but stops backing up the whole web folder for that domain

### Expected behavior:

I should be able to block domains with a wildcard in the exclusions list. A cool feature would also be a global list of exclusions (rather than having to do it for every single user account / domain)

### Operating system:

Ubuntu 18.04 LTS

### Hestia Control Panel version:

1.3.2 (amd64)

**Comment by jaapmarcus** [comment]
Checked today it is not OS depended. 

Also the translations are something wrong

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1790

Something like this would probally work for the domains need to check it ..

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/commit/7e8f09d6924968979d8645dff405351f67b9871f
