### ISSUE TITLE
Language defaults to Arabic in consecutive user creation view

### ISSUE THREAD

**Issue by YVbakker** [hestiacp/hestiacp#1517]
### In a few words, please describe the issue that you're experiencing:
When adding one user after another, or when entering incomplete (=error message) information when creating a user: upon reloading the user creation page the default language is set to arabic.

### What steps did you take when the issue occured? 
1. attempt to create a new user
2. (optional) enter incomplete information or create user successfully
3. create another user

### Expected behavior:
Language is initially set to English (or Hestia system language), in every consecutive user creation screen I'd expect the language to default to this as well.

### Operating system:
Ubuntu 20.04 LTS (most likely not distribution specific)

### Hestia Control Panel version:
1.3.2. 

### Additional notes:
Did not try with other system languages (mine is English) but I assume it defaults to Arabic since it sorts alphabetically.

**Comment by jaapmarcus** [comment]
Noticed simelar issue will check it out

**Comment by jaapmarcus** [comment]
Fixed see pull request
