### ISSUE TITLE
! character in installation script (in password in my case) caused event not found error

### ISSUE THREAD

**Issue by the-wazir** [hestiacp/hestiacp#1519]
I was installing using the script on Ubuntu 20.04 and when I specified a password on the command line which included an exclamation mark, it caused the script to fail instantly with a bash "Error !0 event not found" message... the password happened to have !0 in the character sequence.  I tried encapsulating in quotes but this didn't help.

**Comment by jaapmarcus** [comment]
What was your command?

--password '!eafefwae'  or 
--password 'eAD!12afefwae'  

Seems to work fine. 

With " double quotes it fails directly

**Comment by jaapmarcus** [comment]
Will close the issue with "Special chars" use --password 'Adae!344'

**Comment by Lupul** [comment]
To clarify whats happening here:

When passing random chars args to cli command **always** use single quotes, this not something Hestia can do anything about as it is processed before by bash (globbing, substituion, expansion etc). 
```bash
echo "abc$def"
```
> abc

```bash
echo "abc!def"
```
> bash: !def: event not found

Reference: https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html
