### ISSUE TITLE
Hestiacp HTTP ERROR 503

### ISSUE THREAD

**Issue by darkworks** [hestiacp/hestiacp#1524]
i have website :   it was ok today i visit and start getting error 503 . am not sure why am getting it , i checked apache logs and nothing in it , no error that could cause it . am totally blind 503 seems to be difficult to fix compare to error 500 which leave some trace in log . so any idea what could be cause of it . i visit the website from my another server through vnc and from there i can visit it however from my system am getting 503 i tried in different browsers and also tried private window too 

also how can i optimize hestiacp for heavy traffic , not sure what default limit of hestia cp that how much user it can handle. 

### Operating system:
Debian 10

### Hestia Control Panel version:
Latest 1.3.2

**Comment by ScIT-Raphael** [comment]
I don't see any issue from here, your site is up and running. There is no usual guide how to optimize your system, it depends on what your website needs, buffers, timeouts and so on. Please consider to use https://forum.hestiacp.com for support requests, I'll close this issue report for now.
