### ISSUE TITLE
Could not remove or edit additional ftp users

### ISSUE THREAD

**Issue by rix-lv** [hestiacp/hestiacp#1526]
Impossible to delete or edit additional ftp users because of extra username prefix adding.
For exmaple aditional ftp user is FTPUSER and Hestia username is USERNAME, then username for additional ftp is USERNAME_FTPUSER. When I try to delete or edit it then I`v got this error:
Error: account USERNAME_USERNAME_FTPUSER doesn't exist.
So, there is one extra USERNAME_

Ubuntu 20.04
Hestia Control Panel v1.3.2

**Comment by jaapmarcus** [comment]
The issue has been fixed in the "dev" version. 

This pull requests will fix this behavour:
https://github.com/hestiacp/hestiacp/pull/1411
