### ISSUE TITLE
Editing default user admin shows Role "User"

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#1529]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Editing default user admin shows Role "User"

### What steps did you take when the issue occured? 
Edit User Admin

### Expected behavior:
Should show Role "Admin"

### Operating system:
Ubuntu 20.04

### Hestia Control Panel version:
1.3.2

**Comment by jaapmarcus** [comment]
The admin  user is hard coded as "Admin". Will fix it for clarity
