### ISSUE TITLE
Web/Proxy templates choose permission to Non-Admin users..

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#153]
https://github.com/hestiacp/hestiacp/commit/01c1b54b4df7d46ecce55599f5dffef82a0cf9d9#commitcomment-32225303

I feel this is really a security flaw.
The normal USER should not able to change the WEB/PROXY templates.

**Comment by ScIT-Raphael** [comment]
Due to existing discussion, i will close this issue now. We will implement a new way with the new backend.
