### ISSUE TITLE
Hestia backup log file not rotating properly

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#1530]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Hestia backup log file not rotating properly

### What steps did you take when the issue occured? 
cat /var/log/hestia/backup.log

### Expected behavior:
They should be rotated according to logrotate - /etc/logrotate.d/hestia

### Operating system:
Ubuntu 20.04

### Hestia Control Panel version:
Have noticed it on version > 1.3.0. However it could happen in earlier versions as well. Not happening in < 1.2.0

### Additional notes:
@jaapmarcus had similar issue in the past. Don't know if that's still the case.

**Comment by jaapmarcus** [comment]
Still the case see:
https://github.com/hestiacp/hestiacp/issues/1296

**Comment by ioannidesalex** [comment]
Oops sorry, didn't notice that.

**Comment by ScIT-Raphael** [comment]
duplicate
