### ISSUE TITLE
[Bug] After changing Hostname, it doesn't update in helo_data

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1531]
### In a few words, please describe the issue that you're experiencing:
helo_data doesn't use new hostname after changing hostname via dashbord 

### What steps did you take when the issue occured? 
I've changed the hostname via panel and confirm the changes by doing 'nano /etc/hostname'
and then rebooted the server

after rebooting I've rebuilt all the users
![image](https://user-images.githubusercontent.com/39749258/103519591-cbbd2480-4e9b-11eb-9c59-26ccdd041344.png)

but when i checked the Helo_data (nano /etc/exim4/mailhelo.conf)
it's still showing the old hostname and also even adding a new domain  it uses old hostname
![image](https://user-images.githubusercontent.com/39749258/103520088-a250c880-4e9c-11eb-99e6-1cc03b5b41fc.png)
old hostname - fsn-s1.b2btech.in
new hostname - de-s1.b2btech.in

### Expected behavior:
it should update all the domain hostname while rebuilding or adding new on in (/etc/exim4/mailhelo.conf)

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.2

**Comment by jaapmarcus** [comment]
Can you check the data in /etc/hosts and /etc/hostname?

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/103521103-3a9b7d00-4e9e-11eb-879d-75eec0061f07.png)
Yes it's using old hostname in (/etc/hosts)

**Comment by alber-khan** [comment]
in  /etc/hostname
it's showing a new hostname

![image](https://user-images.githubusercontent.com/39749258/103521161-51da6a80-4e9e-11eb-8459-517bb9b2444b.png)

**Comment by jaapmarcus** [comment]
Change in /etc/hosts the old hostname to the new one.

**Comment by alber-khan** [comment]
Awesome! it works after updating I've rebuilt the users.
so I think we need to put the extra validation on "Configure Server" page 
when we change the Hostname it should also update '/etc/hosts'
