### ISSUE TITLE
How to disable http2 in hestia panel

### ISSUE THREAD

**Issue by raulrr1986** [hestiacp/hestiacp#1532]
it turns out that I'm using hestia panel, and combining it with NodeJS and Angular, but I can't find where to  disable the nginx http2 option, which produces an annoying:

  Invalid Host header.

Grateful, and waiting for the answer.

PS: I have already disabled from the nginx configuration file, this feature, manually, but somehow it has remained persistent.

**Comment by theotherpeople** [comment]
Nginx templates are here;

/usr/local/hestia/data/templates/web/nginx

**Comment by jaapmarcus** [comment]
This is not a bug report. Please use our forum (https://forum.hestiacp.com) in the future. 

For your current issue check /usr/local/hestia/data/templates/web/nginx(/php-fpm) to alter / create a new template that removes the http2 form the command line. Please note that templates updates get updated when it is an default template!

https://github.com/hestiacp/hestiacp/search?q=http2

**Comment by raulrr1986** [comment]
Sorry, thanks
