### ISSUE TITLE
GPG error

### ISSUE THREAD

**Issue by Tazer89** [hestiacp/hestiacp#1540]
Updating currently installed packages, please wait... W: GPG error: https://apt.hestiacp.com focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5
E: The repository 'https://apt.hestiacp.com focal InRelease' is not signed.

**Comment by jaapmarcus** [comment]
Please try this:

https://forum.hestiacp.com/t/hestia-1-1-0-released/526

**Comment by Tazer89** [comment]
> Please try this:
> 
> https://forum.hestiacp.com/t/hestia-1-1-0-released/526

That did work! Thanks.
