### ISSUE TITLE
Can´t change between PHP versions

### ISSUE THREAD

**Issue by titodevera** [hestiacp/hestiacp#1541]
I can´t change between PHP templates for any web domain on a PHP-FPM installation, after click on the save button the default option is set again. Other options works as spected. No errors thrown.

### What steps did you take when the issue occured? 
1. Edit a web domain
2. Change the PHP template
3. Click on "Save" button

### Expected behavior:
The PHP version should have been changed succesfully

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
v1.3.2

### Additional notes:
![muestra](https://user-images.githubusercontent.com/11556124/104001357-d0d1ea80-519f-11eb-85d4-bbd033f1f863.gif)

Thanks! :)

**Comment by jaapmarcus** [comment]
Logged in as "User"?

If so it will be addressed in the next release
https://github.com/hestiacp/hestiacp/pull/1522

**Comment by titodevera** [comment]
Yes, it seems that works logged in as admin.

I´ll wait to the next release, thanks so much!
