### ISSUE TITLE
[Feature request] - echo "path/to/logfile.log" when a CLI command returns an error.

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1542]
Executing for example the following command returns:

```
/usr/local/hestia/bin/v-update-letsencrypt-ssl
Error: Let’s Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending
```
If the return also told me that the logfile is: /var/log/hestia/LE-admin-c02.mydomain.com-date-time.log it would help me debug on my own and I would have not needed the assistance in the forum.

For example, the **output** would be like this:
**Error: Let’s Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending
Please read  /var/log/hestia/LE-admin-c02.mydomain.com-20210108-175802.log for more details.**

**Comment by jlguerrerosanz** [comment]
Thank you very much ScIT.

What I was suggesting is to do that for **all scripts in the CLI**, but maybe it is too much to ask. Maybe with time you can update them if you set as standard to help debug a bit better with the outputs.

**Comment by ScIT-Raphael** [comment]
Define "all scripts". v-update-letsencrypt just triggers v-add-letsencrypt-domain so this should be enough.

**Comment by jlguerrerosanz** [comment]
Well, I was suggesting to **take a careful look at the CLI as a whole** and **how Hestia handles errors**.

Sometimes errors are incomplete, or maybe the error message can also point you to where is the logfile where the output is written... so you do not have to check the documentation (where it can or not be documented) or ask in the forum, and therefore everyone saves time.

**Comment by ScIT-Raphael** [comment]
We see hestia as a solution for sysadmin, personaly i dont see any need for a rework of the error messages. Your point was valid due to the fact, that a cron mail sent from v-update-letsencrypt would not contain the domain name, this is fixed now and will be includef in the next release.

**Comment by jlguerrerosanz** [comment]
Thank you very much for your time again.
