### ISSUE TITLE
Fix autoupdate Lets Encrypt certificate

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1543]
### In a few words, please describe the issue that you're experiencing:
When autoupdating Lets Encrypt certificate, the script fails.

- Let's say my machine is called "srv.domain.com"
- admin owns website srv.domain.com
- other user owns domain.com with dns and email

It's time to renew the let's encrypt certificate and cron runs:
/usr/local/hestia/bin/v-add-letsencrypt-domain admin srv.domain.com

Internally, that script tries this:
/usr/local/hestia/bin/v-list-dns-domains admin | grep srv.domain.com | cut...

But the output of /usr/local/hestia/bin/v-list-dns-domains admin | grep srv.domain.com is empty because the DNS zone does not belong to the user admin.

And therefore, the variable $dns_domain is empty

From then, on. I suppose that the rest of the commands will still fail.

running the command with bash -x

`+ echo -e '\n==[Step 5]==\n- status: 400\n- nonce: 0104hu_OuKU0fL9d-JgyVh4pUPZWrSVr5wYto0aAC02XQ3Y\n- validation: \n- details: Unable to update challenge :: authorization must be pending\n- answer: HTTP/2 400
server: nginx
date: Fri, 08 Jan 2021 10:50:31 GMT
content-type: application/problem+json
content-length: 144
boulder-requester: 101121629
cache-control: public, max-age=0, no-cache
link: [<https://acme-v02.api.letsencrypt.org/directory>](https://acme-v02.api.letsencrypt.org/directory);rel="index"
replay-nonce: 0104hu_OuKU0fL9d-JgyVh4pUPZWrSVr5wYto0aAC02XQ3Y

{
"type": "urn:ietf:params:acme:error:malformed",
"detail": "Unable to update challenge :: authorization must be pending",
"status": 400
}\n'
+ [[ 400 -ne 200 ]]
+ '[' '!' -z bind9 ']'
++ **/** **usr/local/hestia/bin/v-list-dns-domains admin**
++ grep **srv.domain.com**
++ cut '-d ' -f1
+ **dns_domain=**
++ **/usr/local/hestia/bin/v-list-dns-records admin srv.domain.com**
++ grep -i letsencrypt
++ cut '-d ' -f1
+ caa_record=
+ '[' '' = srv.domain.com ']'
+ debug_log 'Abort Step 5' '=> Wrong status'
+ echo -e '\n==[Abort Step 5]==\n=> Wrong status\n'
+ check_result 15 'Let'\''s Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending'
+ '[' 15 -ne 0 ']'
+ echo 'Error: Let'\''s Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending'
Error: Let's Encrypt validation status 400. Details: Unable to update challenge :: authorization must be pending
+ '[' '!' -z '' ']'
+ log_event 15 ' '\''admin'\'' '\''srv.mydomain.com'\'''
+ '[' -z '' ']'
++ date '+%F %T'
++ basename /usr/local/hestia/bin/v-add-letsencrypt-domain
+ LOG_TIME='2021-01-08 11:50:32 v-add-letsencrypt-domain'
+ '[' 15 -eq 0 ']'
+ echo '2021-01-08 11:50:32 v-add-letsencrypt-domain '\''admin'\'' '\''srv.domain.com'\'' [Error 15]'
+ exit 15`

### Expected behavior:
- Warn admin user that all DNS zones of domain.com have to be owned by user "admin"
- Handle this exception differently

### Operating system:
Debian 10.6

### Hestia Control Panel version:
1.3.2

**Comment by ScIT-Raphael** [comment]
```
Internally, that script tries this:
/usr/local/hestia/bin/v-list-dns-domains admin | grep srv.domain.com | cut...
```

Can you please point to the related part in the script? It would be much easier to understand, if you would use the github permalink function to related codeparts: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet

**Comment by jlguerrerosanz** [comment]
It's the first time I try this. I think it is this part:
https://github.com/hestiacp/hestiacp/blob/aeb07fed7c93c893d6d65ab8be8eab3b23a8f045/bin/v-add-letsencrypt-domain#L347-L361

**Comment by ScIT-Raphael** [comment]
This is just the dns caa part and isnt relevant. I don't think you get any error output, isnt it?

**Comment by jlguerrerosanz** [comment]
Now I don't get an error since I managed to get it to work by disabling SSL completely and enabling it again.

https://forum.hestiacp.com/t/lets-encrypt-cron-error/2483

**Comment by ScIT-Raphael** [comment]
As written, LE error 400 could be all, but it isnt related to the referenced codepart.

**Comment by jlguerrerosanz** [comment]
https://github.com/hestiacp/hestiacp/blob/aeb07fed7c93c893d6d65ab8be8eab3b23a8f045/bin/v-add-letsencrypt-domain#L75-L79

dns_domain=$($BIN/v-list-dns-domains $user | grep $domain | cut -d' ' -f1)
caa_record=$($BIN/v-list-dns-records $user $domain | grep -i "CAA" | cut -d' ' -f1)

The thing is that if:
- admin owns website srv.domain.com
- but admin doesn't own domain.com

_$dns_domain_ is empty because _v-list-dns-domains $user_ doesn't return a value for $user, but the domain exists

**Comment by jaapmarcus** [comment]
See:

https://github.com/hestiacp/hestiacp/blob/aeb07fed7c93c893d6d65ab8be8eab3b23a8f045/bin/v-add-letsencrypt-domain#L178-L190

It will only be used for Wildcard DNS records as it a requirement for Lets encrypt. 

400 error could point of 4 often used things:

1. Use of Cloudflare with SSL/TLS mode and proxy mode
2. Issues with Nginx/Apache2 config (Depending on setup) 
3. Issues Force SSL mode enabled  (Some cases causing issues so working fine)

And maybe a few more. Currently we are not always detect the "issues" Lets encrypt throws out an 400 with out any "usefull data"  It is currently almost impossible to verify 

We know the current setup is confusing mainly for new users how the never ending "to do" list is still growing.  Unless somebody is willing to start fixing the issue it will never get solved.

**Comment by jlguerrerosanz** [comment]
Ok thank you.
