### ISSUE TITLE
Issue with Additional FTP Accounts when restoring (problem 1)

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#1545]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When restoring a backup to a new user (not existing), and the user has Additional FTP Accounts that their path is a subdirectory of public_html, the FTP Account is not created with an error message "absolute path not found". It seems that the issue is caused because the system tries to restore the Additional FTP Account prior to creating the folders (WEB).

### What steps did you take when the issue occured? 
./v-restore-user username backupfile.tar

### Expected behavior:
The folders should be created prior to restoring Additional FTP Accounts, or find another workaround.

### Operating system:
Ubuntu 20.04

### Hestia Control Panel version:
1.3.2

**Comment by jaapmarcus** [comment]
I don't have any issue with restoring part how ever after restoring I am able to login.
When I try to upload certain files I am not able to list them via file manager / sftp (main account)
Tested against the main branch...

**Comment by jaapmarcus** [comment]
Fixed with 1.4
