### ISSUE TITLE
[Bug] - When adding firewall rules, check if port field is empty

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1549]
For ipsets it is unclear if you have to put a 0 for all ports or just nothing.

Since a void value for port is not allowed, don't let the panel set any rule with an empty port field.

**Comment by jaapmarcus** [comment]
Confirmed as a bug!

**Comment by jlguerrerosanz** [comment]
This also happens with the Address field.

**Comment by jaapmarcus** [comment]
Please explain:

<img width="480" alt="Screenshot 2021-01-12 at 10 42 38" src="https://user-images.githubusercontent.com/9754650/104297258-f114e880-54c2-11eb-8bc5-52a0118077e4.png">

**Comment by jaapmarcus** [comment]
It does apply on editing the rule

**Comment by jlguerrerosanz** [comment]
![image](https://user-images.githubusercontent.com/8811720/104299132-1d316900-54c5-11eb-9c61-4ec6080589cb.png)
Just edited the rule

**Comment by jaapmarcus** [comment]
I noticed the issue when editing.
