### ISSUE TITLE
[Feature Request] - Merge ipsets

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1550]
For now, I can only select one ipset, name it and use it.

For example:
- I would like to create a Europe + USA + GB ipset
- I would also like to create a China + Russia + India ipset

**Comment by ScIT-Raphael** [comment]
Currently, a merge function of ipsets isnt planed. You could also provide the lists over a custom script (script:/path/to/local/script.sh), check https://github.com/hestiacp/hestiacp/pull/819 for more details.

**Comment by jlguerrerosanz** [comment]
Thank you. It would be so awesome to be able to use a well curated set of lists.

In fact, if no operation with lists can be done but create them, why aren't all the default lists already created and ready to use? Since I cannot combine them it is only an useless extra step to have to create them to then be able to use them.

**Comment by ScIT-Raphael** [comment]
As written, there is the option to combine different lists and tasks over the script function.

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/blob/main/install/deb/firewall/ipset/blacklist.sh

For example.

It will need DIY but it should be possible.

**Comment by jlguerrerosanz** [comment]
Thank you very much.
