### ISSUE TITLE
Lets Encrypt broken if their token contains the characters "url"

### ISSUE THREAD

**Issue by lucaslcode** [hestiacp/hestiacp#1553]
### In a few words, please describe the issue that you're experiencing:
LetsEncrypt SSL is failing for one particular domain

### What steps did you take when the issue occured? 
1. Run `v-add-letsencrypt-domain user my-domain.com www.my-domain.com`
2. Get output: `Error: Let's Encrypt validation status . Details:` (Not a typo, it doesn't say anything).

### Expected behavior:
LE should be activated on the domain.

### Operating system:
Ubuntu 20.04.1 LTS  (GNU/Linux 5.4.0-52-generic x86_64)

### Hestia Control Panel version:
1.3.2

### Additional notes:
Looking through the LE logs, it fails on step 5 with exit code 3, which apparently means malformed URL? I had a look at the source for `v-add-letsencrypt-domain` ~~but couldn't see anything obvious~~. See below for a possibility?

Here is the log for step 3 and 5 (no step 4 is expected since there's no wildcard, looking at the source):

```
==[API call]==
exit status: 0


==[Step 3]==
- status: 200
- nonce: 0104fVJ9xZwEutoPVARryRzOi05u7xEc4CwnHeCDSmwgGyk
- url: https://acme-v02.api.letsencrypt.org/acme/chall-v3/XXXX/YYYY
ZZZZZ?
- token: XXXXX
- answer: HTTP/2 200
server: nginx
date: Mon, 11 Jan 2021 22:25:06 GMT
content-type: application/json
content-length: 796
boulder-requester: 101628503
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: XXXXXXXXXX
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "www.my-domain.com"
  },
  "status": "pending",
  "expires": "2021-01-18T00:20:05Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/XXXX/YYYY",
      "token": "XXXXX"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/XXXX/YYYY",
      "token": "XXX"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/XXXXX/YYYY",
      "token": "XXX"
    }
  ]
}


==[API call]==
exit status: 3


==[Step 5]==
- status:
- nonce:
- validation:
- details:
- answer:


==[Abort Step 5]==
=> Wrong status

```

Actually, after pasting this in, it looks like there is a newline in the URL? Is that possibly the cause? Changing the tokens, it looks like this:
```
==[Step 3]==
- status: 200
- nonce: 024u128947184f31a481a
- url: https://acme-v02.api.letsencrypt.org/acme/chall-v3/1234567890/abcdef
a12B3Cdb31b314AB341BDA
- token: ...
```

**Comment by lucaslcode** [comment]
Ok, the problem is the token has the characters "url" in it. So:

```
cat x.tmp |grep -A3 http-01 |grep url
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/XXXXX/YYYY",
      "token": "XXXXXXXXXXXXXXXXurlXXXX"
```
Not sure the best way around that. Over to you, devs :D

**Comment by lucaslcode** [comment]
I changed `grep url` in that line in the source to `grep -m1 url` as a workaround, which worked, but I'm getting a 400 error on step 5 now. Not sure if related.

**Comment by ScIT-Raphael** [comment]
Hmm, LE 400 could now be all (missing dns, firewall/connection issue and so on). Good catch with the url. We should make it a bit more strict, to grab exactly the "wanted" part.

**Comment by jaapmarcus** [comment]
The bug mentioned should be fix
