### ISSUE TITLE
[Feature Request] - Feedback button / link in footer

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1558]
Place a link in the footer to give feedback about current hestia panel's URL that link would open a form for:
- Suggestions
- Improvements
- Bugs

Then you can read people's opinion and then you may think about what to develop next.

**Comment by Lupul** [comment]
Don't we already have one in the header? :smile: 
![image](https://user-images.githubusercontent.com/3596864/104392781-7f34b180-554b-11eb-97ef-fb06a5f94ef9.png)

**Comment by jaapmarcus** [comment]
I think we supply more than enough methods to connect with HestiaCP team.

There is no need to  add another method of causing headaches and we are already considering to "stop" all methods of "free" support as we can't find  enough time and resources to keep up with the demand.  Don't forget we don't get paid for our effort. And offer only "paid" support.
