### ISSUE TITLE
Suggestion: Add Microsoft, Zoho DNS templates

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#156]
If possible, better to add more DNS templates mainly for EMail MX records..

https://raw.githubusercontent.com/vvcares/hestia/master/microsoftoutlook.tpl
https://raw.githubusercontent.com/vvcares/hestia/master/zoho.tpl

**Comment by ScIT-Raphael** [comment]
Thanks for your suggestion, I'm not sure if it would really be useful: Someone who runs a Hestia server should also be able to add two MX records :-). Especially with Microsoft / O365 the entry has to be changed anyway.

Or would you, except for the MX records, change other positions?

**Comment by ScIT-Raphael** [comment]
*Closed by mistake :)

**Comment by vvcares** [comment]
Hi Raphael,
Suggested just to make some easier automations for end user level & hopefully Hestia may get more ++ if someone comparing features. :-)

as long as Hestia already has GSuite DNS, we could provide the best alternatives too.
GSuite - Getting damn expensive, (April 2019 onwards)
Microsoft - Even still costly, but officials still rely on that & buying more,
Zoho - Best/cheapest alternative for both above giants.
Localhost - Of-course, as a server admin, I prefer not to run my mail server as primary. :-)

"...Or would you, except for the MX records, change other positions?..." >> Just we provide the fields, so they will aware of it as, they still need to find something from microsoft.

**Comment by ScIT-Raphael** [comment]
Implemented: https://github.com/hestiacp/hestiacp/commit/6556f5bc4a3c5bf3243348c802aa1fedc2abe995

Will close the request now.
