### ISSUE TITLE
Editing PHP-FPM in panel updates all php.ini files [5.6/7.0/7.1/7.2/7.3/7.4]

### ISSUE THREAD

**Issue by iT0mT0m** [hestiacp/hestiacp#1560]
### In a few words, please describe the issue that you're experiencing:
When I change settings for one php version the changes are updating in all php versions. Currently I installed ioncube module for all php versions and I add config link for zend_extension. When I click Save changed all settings to the ioncube libraries under php version 7.4.

### What steps did you take when the issue occured? 
1. Click Server
2. Edit PHP-FPM
3. Advanced settings
4. Change options
5. Save
6. All php.ini files are updated

### Expected behavior:
Could you add drop-down list with select php version which php.ini file will to update?

### Operating system:
Debian 10.7 (x86_64) 

### Hestia Control Panel version:
v1.3.2 

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
It is an known issue see https://github.com/hestiacp/hestiacp/issues/1268 also restarting should be possible per version
