### ISSUE TITLE
Bug - v-change-user-password

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1562]
The script prompts for password when the password contains certain characters when it shouldn't as desccribed in the docs:
https://docs.hestiacp.com/cli_commands/commands.html#v-change-user-password

![image](https://user-images.githubusercontent.com/8811720/104510574-a642c000-55eb-11eb-91a8-2f25d332679d.png)

Either edit the docs to say that it doesn't accept all characters or fix.

**Comment by jaapmarcus** [comment]
So chars causes issues with bash..

Use single quotes and it should fine. 

v-change-user-password demo '#1233456Abds()'

**Comment by jaapmarcus** [comment]
The main issue is that with use of the rest api the single quotes are not required and even causing issues. For command line use it is sometimes. As we have build with the api use in mind it causes conflicting issues. 

Probally there is no easy fix for it...
