### ISSUE TITLE
No access to website while opening hestiacp. Previously file manager was not working.

### ISSUE THREAD

**Issue by pgoncharuk** [hestiacp/hestiacp#1565]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
While providing my IP+port hestia doesnt opens. I have an error like it is no access to website. My ip and port are: http://173.212.225.247:8083/

### Expected behavior:
Hestia CP opens and i file manager opens 

### Operating system:
Ubuntu 18.04

### Hestia Control Panel version:
dont remember

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by tudorr89** [comment]
Your port is closed. Make sure your firewall allows traffic through 8083. Also make sure hestia is running `service hestia status`. Surely not an issue.
![Screenshot 2021-01-15 at 09 48 29](https://user-images.githubusercontent.com/3405514/104696432-ef436300-5716-11eb-9806-4dd30befc1d4.png)

**Comment by ScIT-Raphael** [comment]
This is not a real issue which we could fix, please stick for community support to our fourm (https://forum.hestiacp.com) or discord channel. Please be sure you read https://forum.hestiacp.com/t/please-read-this-before-you-start/383 before you create a support request.
