### ISSUE TITLE
Bug - v-change-domain-owner

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1566]
### The command worked fine but threw an error
**/usr/local/hestia/bin/v-change-domain-owner: line 135: v-sync-dns-cluster: command not found**

# $HESTIA/bin/v-change-domain-owner mindfulness.com mindfulness
Moving mindfulness.com from miindfulness to mindfulness, please wait...
[*] Moving DNS zone and records...
/usr/local/hestia/bin/v-change-domain-owner: line 135: v-sync-dns-cluster: command not found
[*] Moving mail domain and accounts...

===

Hestia 1.3.2
Debian 10.6

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/722149b316b6f9101070948f97edf1ce0e364e7a/bin/v-change-domain-owner#L133-L136

Confirmed will patch  it
