### ISSUE TITLE
Bug - v-change-user-name

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1567]
```
 # $HESTIA/bin/v-change-user-name miindfulness mindfulness.com
Error: invalid name format :: mindfulness.com
```

I have always been able to set a domain as a username in hestia.

The real name I introduced in the CLI prompt is exactly 32 characters long (I counted it twice). Since linux allows 32 characters long. It should not be an issue.

### Expected behaviour
1) change error message to: "Error: name is too long. max 32 characters :: mindfulness.com"
2) trigger error on 33 characters not on 32

**Comment by jaapmarcus** [comment]
```
root@dev:~# v-change-user-name jaap nu.nl
root@dev:~# v-list-user jaap json
```
Will result in: 
 "NAME": "nu.nl",

```
root@dev:~# v-change-user-name jaap mindfulness.com
root@dev:~# 
```

https://github.com/hestiacp/hestiacp/blob/722149b316b6f9101070948f97edf1ce0e364e7a/func/main.sh#L879-L884

According this line it should an Letter or Number Then Letter, number, - or " " or  . or   _  (Max 28) and then an another letter

```
root@dev:~# v-change-user-name jaap 12345678901234567890123456789012
Error: invalid name format :: 12345678901234567890123456789012
root@dev:~# v-change-user-name jaap 1234567890123456789012345678901
Error: invalid name format :: 1234567890123456789012345678901
root@dev:~# v-change-user-name jaap 123456789012345678901234567890
```

So indeed max 30 chars.  

We only save the "name" variable in our files and not in /etc/password so Linux issn't the issue.  

On the level for error reporting I can agree there is might need an level for improvement. For the UI we are considering switching to a better system. 

The question is this valid enough to fix / alter or we say 30 chars is long enough

**Comment by jlguerrerosanz** [comment]
I think it is long enough for me. I can make one exception amoung 140 clients.

**Comment by jaapmarcus** [comment]
The biggest issue is lack of error "reporting" and not the check it self. Will close the issue
