### ISSUE TITLE
Feature Request: Integration of 2FA

### ISSUE THREAD

**Issue by beli42** [hestiacp/hestiacp#157]
Integration of 2FA (2 Factor Authentication) would be nice to have for
- Web Authentication
- SSH Connections (possibly via PAM Modules like libpam-google-authenticator)

**Comment by beli42** [comment]
- For SSH the following setup works well: https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04

- For Web i would recommend the use of a php framework extension or generic using https://github.com/RobThree/TwoFactorAuth (composer based)

**Comment by ioannidesalex** [comment]
Thanks @beli42 for the feedback.

**Comment by johnnyq** [comment]
Excellent Idea!

**Comment by ScIT-Raphael** [comment]
First steps done: https://github.com/hestiacp/hestiacp/commit/965fe567ef8e0bae2fe376f8b9127c9aeacaf5f9 and https://github.com/hestiacp/hestiacp/commit/3b02f964409381dbd3b0925058e36a60a7b68aef

Pending is the reset 2fa function and the integration for enabling 2fa directly in backend.

**Comment by ScIT-Raphael** [comment]
Last steps with the commits https://github.com/hestiacp/hestiacp/commit/9445295259db021137ba39e9436ee800f4d69ac7 and https://github.com/hestiacp/hestiacp/commit/15a11a9ce5fe0869562fa973523a3e4e142d25fe done.

We will push new deb packages soon.
