### ISSUE TITLE
nginx cache template: create url exceptions

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1572]
### In a few words, please describe the issue that you're experiencing:
When I enable the nginx caching template, I am getting some pages cached that is not good. For example the shopping cart of woocommerce.

### What steps did you take when the issue occured? 
1. Enable nginx caching template.
2. Try to create my shopping cart using my woocommerce solution.

### Expected behavior:
Shopping cart updated with my goods.

### Operating system:
Ubuntu 20.04

### Hestia Control Panel version:
Last version updated today.

### Additional notes:
1. What nginx caching effectively do? I mean, which files are affected? I am trying to get this from git to manually create exceptions.
2. Will be good to source some directory that implement exceptions for this template. The nginx caching template is amazing and some times get better results than openlitespeed+lscache solution, however we need to fix this (probably the same is happening with others php ecommerces solutions).

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/server_management.html#how-do-web-templates-work

It can be done via modifying / duplicating the template. With the different 1000 use cases we can't provide everyone the best template. 

For support questions please use:
https://forum.hestiacp.com

**Comment by franciscopaniskaseker** [comment]
@jaapmarcus I understood that. I only want to get more details that I not found in the docs or git. Thank you.

ps: I thought this is a appropriate question to do in the github and create a document reference. People will find this thread through google, that have more relevance than the forum.

**Comment by ScIT-Raphael** [comment]
We just try to split support and bug reporting to have a better overview. The forum is also good indexed, so there should not be a problem.

We will adjust the github issue template soon, so we can point to the difference for community support and bug reports.

**Comment by franciscopaniskaseker** [comment]
Thank you.

**Comment by jaapmarcus** [comment]
I have added to the todo list for the docs.
