### ISSUE TITLE
[Feature Request] Copy website to staging

### ISSUE THREAD

**Issue by syndicate515** [hestiacp/hestiacp#1574]
# In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

It would be good to add some sort of feature that allows a user to copy a website to another domain for the purposes of staging. 

### What steps did you take when the issue occured? 
1. Wanted to create a staging website to do some Wordpress updates for a client
2. Had to make a domain, copy the files and database manually.
3. Search and replace the database to include the staging domain.

### Expected behavior:
1. Add 'Clone Site'
2. User selects staging domain which is already pre-made under domains.
3. Server copies entire site and any associated databases.
4. Bonus is if for the likes of Wordpress websites, a find and replace is initiated within the database to match the new domain.
5. Push staging to live feature, where a user can replace their entire main website with the staged version. Backup taken of the old website to ensure it is reversable.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.3.2

### Additional notes:
Should improve user experience for developers and provide a new convenient feature which most hosting platforms seem to provide as standard recently.

**Comment by jaapmarcus** [comment]
It is an great idea how ever the current work load it will probally not likely it will be implemented soon / never

Questions to solve:
1. How do we find the config file with database username/password 
2. Database are not linked to domain but to the user. 

For Wordpress the easy answer is wp-cli it is way quicker... But you will need SSH  / CLI access

**Comment by ioannidesalex** [comment]
It’s a great idea, however certain things should be taken into consideration.

One example: WordPress “hardcodes” the URLs in the database. Thus (among others) we will need to replace all production urls from the database to the staging ones.

**Comment by jlguerrerosanz** [comment]
Its better to have the tool with SSH / CLI than not having the tool at all.

> One example: WordPress “hardcodes” the URLs in the database. Thus (among others) we will need to replace all production 
urls from the database to the staging ones.

wp search-replace 'foo' 'bar'

> * How do we find the config file with database username/password

Let's only support 3 or 4 technologies.
Have a config file with all that.
Or store it upon creation. So we only have to read it.

> * Database are not linked to domain but to the user

supply the correct database in CLI or

@wojsmol did a great job with his script
https://github.com/webmetric-agency/vinstallwp/blob/5be1f964e29dc64773ac03bd22cf6ee328e1bfb2/vinstallwp.sh#L3

This is almost the same issue as deploying a wordpress template or copying from another panel. We need a wordpress management tool.

**Comment by jaapmarcus** [comment]
There are more systems than Wordpress alone.  There is already an ideal tool for staging / modifing Wordpress and it is called wp-cli

We discussed this issue in our team chat and every body agrees this a great tool how ever there is currently not enough man power. Don't forget this **open source** and so far I know I am getting **paid** for my services to my clients and not by any user(s) from HestiaCP of by HestiaCP it self. I really don't care about this.  But this will mean that we might be a need set priorities and this will mean that certain issues have an higher priority than this one.  

And for me:
https://github.com/hestiacp/hestiacp/issues/1268
https://github.com/hestiacp/hestiacp/issues/429
https://github.com/hestiacp/hestiacp/issues/919

And I think I can name certain issue more if I really need. 

Everybody want to have certain features but with only 4 to 5 active developers who have their "main" jobs that are required to support my self / family / company. We can't work 24/7 for free unless we are making it a paid project. Other paid control panels adding it as an additional paid "License" for their current licenses as they can't make enough money out of it. 

https://forum.directadmin.com/threads/pro-pack.62943/

But for your question

https://wp-cli.org we might need to  add an 

Create a new package wordpress --> wordpress.sh 
```
#!/bin/bash
mkdir /home/$1/.wp
chown $1:$1  /home/$1/.wp
v-change-user-php-cli "$1" "7.4"
```
(Or 8.0)

For any good pull request https://github.com/hestiacp/hestiacp/pulls

If somebody think it is worth to pay please contact us on info@hestiacp.com  we might consider it depending on time/other projects  but it will be

**Comment by ioannidesalex** [comment]
I completely agree with @jaapmarcus . There are only two options for massive features:

- Pay to get it done
- Submit a pull request to include it in the project

**Comment by ScIT-Raphael** [comment]
Infact @jaapmarcus made a good write up to the current state, I'm going to close this request now.

**Comment by jaapmarcus** [comment]
To add to the comment of @ioannidesalex:
Or accept that an feature request get ignored and put on the waiting list and then get forgotten.

Added a small feature so an admin can add wp-cli to the user packages with 1 simple command. 
https://github.com/hestiacp/hestiacp/pull/1575

**Comment by jlguerrerosanz** [comment]
I am sorry if my previous intervention got misunderstood. I meant no offense by all means.

> Or accept that an feature request get ignored and put on the waiting list and then get forgotten.

Of course. I undestand you very well. It's just that if more people keep posting maybe it will raise in your priority scale.

> Added a small feature so an admin can add wp-cli to the user packages with 1 simple command.
> #1575

Great news. Thank you.

I am going to work this week in my own bash scripts. I will share them if I think they can be valuable to anyone.
