### ISSUE TITLE
[FEATURE] GoAccess for HTML Statistics

### ISSUE THREAD

**Issue by iamra** [hestiacp/hestiacp#1577]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
awstats is better than weblizer, but goaccess is better than both.

**Describe alternatives you've considered**
What is it GoAccess?
GoAccess is an open source real-time web log analyzer and interactive viewer that runs in a terminal in *nix systems or through your browser.
It provides fast and valuable HTTP statistics for system administrators that require a visual server report on the fly.

**Additional context**
GoAccess can generate html statistics in a more modern looking form. Matching the direction Hestia CP has taken in refining its features.

Please visit [https://goaccess.io/](https://goaccess.io/) and have a look!

I have a very crude implementation at the moment.
I am creating this ticket and will add more detail as I get it working better.

**Comment by jlguerrerosanz** [comment]
I have been looking the goaccess.io platform. 

I hate awstats and webalizer with all my guts and don't use them.
I do not hate GoAcces but if I had to choose I would implement matomo.

**Comment by iamra** [comment]
GoAccess is somewhat different from Matomo. I used to use Piwik before it became Matomo, and it seems to be a great analytics tool, but not quite the use case I am recommending here. since its more of a web application than a command line tool.

GoAccess works off the Apache logs themselves on the server. So its more of an aggregate/web page generator for that existing data. It also seems to be very light weight, and already is available in the debian repos.

I think GoAccess can be used to generate statistics page rather than awstat for a more modern, mobile, and generally better looking solution.

**Comment by jaapmarcus** [comment]
Both systems has their usage and still can exists next to each other... 

For GoAccess if we are able to get the same "level" as integrations as Awstats (Able to enable it per domain ) it would be an option to aggregate logs files and output static html files it would be great.

Feel free to create a pull request. 

Matomo is no alternative for Awstats as it way to heavy and requires too much resources.

**Comment by webeditors** [comment]
I'd be interested in GoAccess integration with Hestia. Apart from Awstats having an ancient front end, its features are limited and I can't get the detail drill-downs to work on the standard Hestia install to work anyway.

GoAccess's realtime tools would be really useful.

**Comment by djshades2004** [comment]
This seems like a great idea as well.
I did have a look a the goaccess page and to perform a live html view the command is:
goaccess access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html

**Comment by jaapmarcus** [comment]
Unless somebody is able to implement it please submit a pull request. We don't have the time for it.

**Comment by franciscopaniskaseker** [comment]
I created a script that will read all hestiacp access_log from active accounts and create the goaccess report.

Easy to install and use: https://github.com/franciscopaniskaseker/goaccess-hestiacp

I have no idea how hestiacp can import a report.html from somewhere into the panel. But if is easy to do, the report is about one command to be created. And using just opensource tools.

Goaccess does not provide a domain view. Maybe, in this case, we have to generate multiple reports for each domain. Is something to the future.

**Comment by weasam** [comment]
The benefits using Goaccess instead of Matomo(Piwik) or Awstat
-  Adblcker could not block Goaccess instead Matomo is using JavaScript that would block by user, we need some fundamental 
-    data to analyze our website data
- Goaccess is more modern look then Awstat
I had install GoAccess by command line, but isn't convenient by add goaccess every domains

**Comment by weasam** [comment]
The benefits using Goaccess instead of Matomo(Piwik) or Awstat
-  Adblcker could not block Goaccess instead Matomo is using JavaScript that would block by user, we need some info to anlyse our website data
I had install GoAccess by command line, but isn't convenient by add goaccess every domains
