### ISSUE TITLE
[BUG] After last update filemanager not loading, Some internal server errors are there

### ISSUE THREAD

**Issue by robiul-shagor** [hestiacp/hestiacp#1581]
When going at file manager it's not loading,

**Screenshots**
    Ex - https://prnt.sc/xhbyjz
    and - https://prnt.sc/xhbzb7

**Operating system:**
Debian 9

**Hestia Control Panel version:**
v1.2.4.

**Comment by ScIT-Raphael** [comment]
Current version of hestia is 1.3.2, please consider to update. If you still get issues, please use our forum or discord for community support.
