### ISSUE TITLE
[BUG] /list/server/?mail shows a blank page.

### ISSUE THREAD

**Issue by shaneshuford** [hestiacp/hestiacp#1582]
Log in > settings > Task Monitor > View Advanced Details > Mail
This page as of this morning is showing a blank page other than the header/menu.

This page should show mail details.

Ubuntu 20.04 (x86_64) / Hestia Control Panel v1.3.2

**Comment by shaneshuford** [comment]
It appears to be working again, maybe it shows a blank page when there is nothing to show?
Thanks.

**Comment by ScIT-Raphael** [comment]
That's possible, can you check the web log file in $HESTIA/log? It should show why you got a white page. PS: Issue template isnt decoration, please use it next time :).

**Comment by shaneshuford** [comment]
The error log does not show anything since 2020-11-08.

Sorry, i thought i did follow the template, i just removed the headers:

**Describe the bug**
**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

Log in > settings > Task Monitor > View Advanced Details > Mail
This page as of this morning is showing a blank page other than the header/menu.

**To Reproduce**
What steps did you take when the issue occured? 

Log in > settings > Task Monitor > View Advanced Details > Mail

**Expected behavior**
A clear and concise description of what you expected to happen.
This page as of this morning is showing a blank page other than the header/menu.

This page should show mail details.

**Operating system:**
**Hestia Control Panel version:**
Ubuntu 20.04 (x86_64) / Hestia Control Panel v1.3.2

**Comment by jaapmarcus** [comment]
Any information regarding setup? Exim installed?

https://github.com/hestiacp/hestiacp/blob/a30037919556539c4c285fd6456b20bd745c7540/web/list/server/index.php#L91-L103

There can't go a lot of things wrong in the code

**Comment by jaapmarcus** [comment]
It return nothing 

<img width="1073" alt="Screenshot 2021-01-24 at 15 34 08" src="https://user-images.githubusercontent.com/9754650/105633572-9fbd0f80-5e59-11eb-9fa8-d8930e9e1c33.png">

**Comment by shaneshuford** [comment]
That must have been what had happen then. A blank page makes it look like something has broken to me.
I believe it should show a response of some kind so the end user is aware of why no stats can be shown.

**Comment by jaapmarcus** [comment]
issue will be fixed with the next release see Pull request

https://github.com/hestiacp/hestiacp/pull/1583
