### ISSUE TITLE
[BUG] - Copy hosting plan forces name of plan.

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1584]
**Describe the bug**
When you visit https://my.domain.com:8083/list/package/ and hit the "copy" button, a copy of the plan is created BUT you can't edit the plan's name

The main goal of making a copy of a plan is to start modifying it without having to configure and test.

I can't have both:
- A descriptive name of the variation
- A clone of the original to start to work with.

**Expected behaviour**
- Either let me change the name after creation of the copy
- Or ask for the new name before the ceation of the copy

**Operating system:**
Debian 10.6

**Hestia Control Panel version:**
Hestia 1.3.2

**Comment by jaapmarcus** [comment]
We might need to add a check if a plan is in current use to allow renaming the current active plan / or "move" move the user to new package...

**Comment by jaapmarcus** [comment]
It seems to be hardcoded in /copy/package/

https://github.com/hestiacp/hestiacp/blob/060746275715557997348314ae7a398fa7b3f19c/web/copy/package/index.php#L26-L38

**Comment by jlguerrerosanz** [comment]
If we could rename an empty plan at least it would be enough I think.

**Comment by jaapmarcus** [comment]
I have addd an function to rename a existing package via edit package...

**Comment by jlguerrerosanz** [comment]
Thank you @jaapmarcus 

I love you
