### ISSUE TITLE
[BUG] phpmyadmin not found [Ubuntu 20.04 | -a no]

### ISSUE THREAD

**Issue by devilstars** [hestiacp/hestiacp#1587]
**Describe the bug**
Can't open phpmyadmin - shows 404 page

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Clean install Hestia
2. Login
3. Open phpmyadmin via control panel (or directly - http://your_ip/phpmyadmin/

**Expected behavior**
It should work

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
1.3.2 (latest)

**Additional context**
hestia was installed in phpfpm only mode (no apache).

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/server_management.html#why-i-can-t-use-http-my-ip-adress-phpmyadmin

No Bug or issue should work fine with:

https://domain.com/phpmyadmin/

**Comment by devilstars** [comment]
@jaapmarcus what if "for security reason" I decided not to attach any domains to server? I want it to be accessed via IP only.

**Comment by devilstars** [comment]
Well, It must be an option, not a restriction.

**Comment by jaapmarcus** [comment]
The idea behind this is that it would allow the use for SSL on PHPmyadmin. If you used https://mycontrol.domain.com/ the link will be https://mycontrol.domain.com/phpmyadmin/ and it will work fine

**Comment by devilstars** [comment]
What if domain of the server is https://nothing-to-see.here ?

**Comment by ScIT-Raphael** [comment]
It isnt a problem, phpmyadmin is configured as alias, so it will be available on every domain you setup. If you don't want this behaviour, you can remove or also rename that alias. As @jaapmarcus already wrote, the limitation is to force the use of a valid ssl certificate which improves the server security.

I usualy use web001.domain.tld as hostname, do an A record for it and then run v-add-letsencrypt-host (https://docs.hestiacp.com/admin_docs/ssl_certificates.html#how-to-setup-let-s-encrypt-for-the-control-panel). After that, you'll have a valid ssl cert for hestia, exim, vsftpd and a few more services, you can aswell reach phpmyadmin from https://web001.domain.tld/phpmyadmin.

**Comment by devilstars** [comment]
sounds good, but in case I have no real domain on the server, it should be accessed via IP.

nvm, I've used Navicat to access my db.

**Comment by ScIT-Raphael** [comment]
In that case you could still add a entry to your hosts file. I strongly suggests to use a valid hostname, also for a valid mail configuration and communication. There is no reason for us to change the current behaviour.

**Comment by devilstars** [comment]
local hosts file sometimes can't be changed if user is not an admin

**Comment by ScIT-Raphael** [comment]
That's right, but using a server without a valid hostname also isnt a valid configuration. Basicly a valid hostname is a win/win in every case, so I suggest to use it :).
