### ISSUE TITLE
[BUG] - CLI error: lsb_release: comand not found - Debian

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1595]
After executing
**./v-list-sys-services**
I get:
./v-list-sys-services: line 298: lsb_release: command not found

**./v-list-sys-info**
I get
./v-list-sys-info: line 77: lsb_release: command not found

**I suppose this will happen with some more commands.**

**Comment by jaapmarcus** [comment]
For v-list-sys-services:
https://github.com/hestiacp/hestiacp/issues/1512

For v-lis-sys-info
https://github.com/hestiacp/hestiacp/blob/eff8c3c5ff79a90a02067c84c3c2d2ad691f7efb/bin/v-list-sys-info#L77-L89

We need to fix it ..

**Comment by ioannidesalex** [comment]
Operating System / version you are using?

**Comment by jlguerrerosanz** [comment]
debian 10.7 (sorry for not providing it)

`root@c02:/usr/local/hestia/bin# ./v-list-sys-info
./v-list-sys-info: line 77: lsb_release: command not found
HOSTNAME                  OS      VER   ARCH    HESTIA  RELEASE  UPTIME  LA
--------                  --      ---   ----    ------  -------  ------  --
c02.xxx.com  Debian  10.7  x86_64  1.3.2   release  32196   0.19
`

**Comment by ioannidesalex** [comment]
It seems that we didn't notice that package lsb is no longer a default with Debian. Thanks for pointing this.

**Comment by jlguerrerosanz** [comment]
How about we apt install it?

**Comment by jaapmarcus** [comment]
Could be an option and add it to the dependencies for hestia package

**Comment by ioannidesalex** [comment]
I don't think it's needed just for this. It shouldn't be hard to find a way to figure out the operating system. However, I don't have Debian at hand to test it. /etc/debian_version exists right? Can you please paste its content? Also if you (or anyone else reading this) can also provide us with information regarding Debian 9 - eg if lsb package is installed and the content of /etc/debian_version

**Comment by jlguerrerosanz** [comment]
root@c02:/etc# cat debian_version
10.7

xxx@w02:/etc$ cat debian_version
8.11

I don't have debian 9 installed but I suppose it will have the same behaviour.

**Comment by jaapmarcus** [comment]
it depends on the image used. Some Debian images still installs it and some mainly minimal images doesn't.

In v-list-sys-services we created an "exception" for it 
https://github.com/hestiacp/hestiacp/commit/aeb07fed7c93c893d6d65ab8be8eab3b23a8f045

Probally it is just easier to include in on the atp install list / dependency

**Comment by jlguerrerosanz** [comment]
@jaapmarcus that would fix all the not-discovered-yet errors.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/search?q=lsb_release&type=code 

It isn't used that often but it will save any issues in the future...

**Comment by ioannidesalex** [comment]
@jaapmarcus appeoach is better than mine. Adding this as dependency. Small package and we make sure no other issues show up.

**Comment by manuelserol** [comment]
I am using a VPS with 10.7 which includes:

lsb-base/stable,now 10.2019051400 all [installed]
lsb-release/stable,now 10.2019051400 all [installed]

I do not know the installation parameters/packages because is a VPS and they use their own installation copy when deploying it

**Comment by jaapmarcus** [comment]
It depends on the image used.

**Comment by jaapmarcus** [comment]
Fix will be released in combination with 1.4.0
