### ISSUE TITLE
[BUG] Backup not getting deleted from Disk

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1597]
**Describe the bug**
After creating a backup and deleting it from panel, it doesn't remove it from /backup location

**To Reproduce**
1st go to backup section via dashboard and create a backup
then delete the backup
![image](https://user-images.githubusercontent.com/39749258/105992038-9b4b5d80-60ca-11eb-87d1-30939e55327d.png)

**Expected behavior**
after deleting the backup via dashboard it should delete it from the disk too

**Operating system:**
Ubuntu 20.04 (x86_64)

**Hestia Control Panel version:**
v1.3.2

**Comment by alber-khan** [comment]
`root@ca-s1:~# v-delete-user-backup admin admin .2021-01-27_18-24-24.tar`

`Error: backup backup admin.2021-01-27_18-24-24.tar doesn't exist` 

when i run 
v-delete-user-backup admin admin.2021-01-27_18-24-24.tar

**Comment by alber-khan** [comment]
https://docs.hestiacp.com/cli_commands/commands.html#v-delete-user-backup
if i follow this i'm getting this error 

`
root@ca-s1:~# v-delete-user-backup admin.2021-01-27_18-24-24.tar
`
`
Usage: v-delete-user-backup USER BACKUP
`

**Comment by jaapmarcus** [comment]
Command is v-delete-user-backup admin admin.2021-01-27_18-24-24.tar

We should update the example and check what is going wrong..

**Comment by jaapmarcus** [comment]
See:
https://github.com/hestiacp/hestiacp/pull/1421

Issue is already fixed in master branch

**Comment by jaapmarcus** [comment]
Just checked the issue exists in 1.3.2 and not in the main branch.

**Comment by alber-khan** [comment]
this is still not working in 1.3.3

**Comment by jaapmarcus** [comment]
We only released a security fix.
