### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by raulrr1986** [hestiacp/hestiacp#1605]
**Describe the bug**
Creando un usuario ftp, ha tomado un formato no valido

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1-En un dominio web ya creado, añadí un usuario ftp.
2-Entiendo que el genera un prefijo, por tanto coloqué como usuario ftpuser, para que quedara. prefijo_usuarioftp

**Expected behavior**
deberia haberlo hecho de manera, normal, esto genero lo siguiente:
Error: invalid ftp_user format :: mercareview-app_mercareviewapp_ftpuser

**Screenshots**
![image](https://user-images.githubusercontent.com/63142142/106390300-b1e90180-63b5-11eb-9016-ee588f82ddab.png)

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
  v1.3.2

**Additional context**
Ahora no me deja borrar, el usuario, malformado, da error, como se resuelve manual ?

**Comment by ScIT-Raphael** [comment]
Please open issue requests in english only. The described bug has already been fixed in the main branch and will be released with 1.4.0.

**Comment by raulrr1986** [comment]
> a

Ok, Sorry, for That, in Englis will be !!
