### ISSUE TITLE
[FEATURE] Make HESTIA panel's email templates customizable / translatable

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1606]
**When you create a client or a domain...**

The emails from the panel are sent in english and the text can't be edited.

**Comment by jaapmarcus** [comment]
1. Emails are translated to the users locale how ever there is an bug in the system if you as use the admin account to create "account" / send email  it is send as the "admin" account. Need to fix it

2. Template for the email need to be translatable.

**Comment by jaapmarcus** [comment]
This enough:
```
<subject>Reset password {{data}} {{user}}</subject>
Hello {{name}},
To reset your {{appname}} password, please follow this link:
https://{{hostname}}/reset/?action=confirm&user={{user}}&code={{resetcode}}

Alternatively, you may go to https://{{hostname}}/reset/?action=code&user={{user}} and enter the following reset code:
{{resetcode}}

If you did not request password reset, please ignore this message and accept our apologies.

Best regards,
{{appname}}
```

If a "template" exists in /nl/reset_password.html then it will take the "nl" locale if dutch us selected... 

If `<subject>Text</subject>` is missing is will use the default value (defined in code / translatable fully)

And of the file both /lang/reset_password.html and reset_password.html are missing it will also default the default

Feel free to share any feed back...

**Comment by jlguerrerosanz** [comment]
I would do as other programs. Have a global version of the file that is updated and maintained by the HCP team and have a local version of the file that can be cloned and edited and if present it will take precedence.

email_x_default.global
email_x_default.local
email_x_default_nl.local

**Comment by jaapmarcus** [comment]
> I would do as other programs. Have a global version of the file that is updated and maintained by the HCP team and have a local version of the file that can be cloned and edited and if present it will take precedence.
> 
> email_x_default.global email_x_default.local email_x_default_nl.local

We use gettext for translations already and now we can already offer each email in any localisation as possible it was only not friendly as *** and therefor a lot of time not properly  translated ...
