### ISSUE TITLE
[FEATURE] Translate EXIM error messages

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1607]
**When exim bounces an email it sends an email in English**
Be able to send errors in other languages or multi-language. Or have the template messages already translated so the messages are sent in the defined user's language

**Comment by ScIT-Raphael** [comment]
This is something which should be brought by exim and not hestia. This is impossible to implement from our side.

**Comment by jlguerrerosanz** [comment]
Well. Not really. I have read the documentation and messages can be customized and stored in separate files.

The thing is that It needs a lot of testing.

If I find the time to have this done, I'll come back to you with my customization. And a proposal on how to translate to different languages out of the box.

**Comment by ghost** [comment]
Please feel free to submit a pull request with the necessary code changes and it will be considered.
