### ISSUE TITLE
[FEATURE] - Cron Jobs to be displayed full under CRON tab

### ISSUE THREAD

**Issue by mariospavlou** [hestiacp/hestiacp#1611]
**Is your feature request related to a problem? Please describe.**
Cron jobs are not regognized under the CRON tab. You have to click on each cron in order to view the full request. That cause issues in the cases where we have lot of of crons under the same domain and we would like to edit or remove a specific one. 

**Describe the solution you'd like**
A quick solution is to add the actual cron request under the a href title (of edit cron link), so in that way we will be able to view the full request by hovering our mouse.

**Describe alternatives you've considered**
Alternatively you can just display the full cron as it was in previous versions. 

**Additional context**

**Comment by ioannidesalex** [comment]
Nice idea. Indeed its a pain when you have many and “large” crons

**Comment by jibon57** [comment]
Yes, I'm facing similar problem. At least simple CSS `overflow: auto;` will give better result. 

https://github.com/hestiacp/hestiacp/blob/6f9034ebec2ceb1dfbae8ab95007b8cdce646ef2/web/templates/user/list_cron.html#L91



<img width="1063" alt="with_overflow" src="https://user-images.githubusercontent.com/6080277/107158690-0859cf80-69b6-11eb-8901-dec53c723f6a.png">

**Comment by jaapmarcus** [comment]
Sadly it doesn't look great in Dark theme. How ever don't know a easy method to fix the scroll bars 

<img width="1078" alt="Screenshot 2021-02-08 at 11 27 10" src="https://user-images.githubusercontent.com/9754650/107207453-9b1f5c00-6a00-11eb-9897-b00e32565481.png">

**Comment by mariospavlou** [comment]
you can style the scroll bars using the following css classes

/* width */
::-webkit-scrollbar {width: 10px;}
/* Track */
::-webkit-scrollbar-track {box-shadow: inset 0 0 5px grey; border-radius: 5px;}
/* Handle */
::-webkit-scrollbar-thumb {background: #ed1c24;  border-radius: 5px;}
/* Handle on hover */
::-webkit-scrollbar-thumb:hover { background: #000000; }

**Comment by ghost** [comment]
This has been resolved in the next major release.
