### ISSUE TITLE
Backups don’t work

### ISSUE THREAD

**Issue by fabiodeoliveiraesilva** [hestiacp/hestiacp#1612]
I’ve been using HestaCP for some time, but I was never able to make backups, either through the web panel or via ssh.
My VPS Server: 12-core CPU, 4GB RAM and 25GB storage (17GB free).

I tried to backup a small user with only one website (19MB), I used the command:

`v-backup-user bryan`

It is running an infinite loop and never finishes the backup.

2021-02-05 00:02:13 Load Average 10
2021-02-05 00:03:13 Load Average 13
2021-02-05 00:04:13 Load Average 11
2021-02-05 00:05:13 Load Average 8
2021-02-05 00:06:13 Load Average 9
2021-02-05 00:07:13 Load Average 11
2021-02-05 00:08:13 Load Average 9
2021-02-05 00:09:13 Load Average 12
2021-02-05 00:10:13 Load Average 8
2021-02-05 00:11:13 Load Average 8
2021-02-05 00:12:13 Load Average 9
2021-02-05 00:13:13 Load Average 11
…

What can it be?

**Comment by fabiodeoliveiraesilva** [comment]
After searching a lot, I found a solution:

Edit the file:
**/usr/local/hestia/func/main.sh**

I switched this line:
**BACKUP_LA_LIMIT=`cat /proc/cpuinfo | grep processor | wc -l`**

For this
**BACKUP_LA_LIMIT=30**

Using the command v-backup-user _username_, the backup (zstd) was created in 0.5s.

Whoever has this problem, here is the solution.

**Comment by jaapmarcus** [comment]
Your load is to big....

**Comment by ScIT-Raphael** [comment]
beside the high load, your change will also been overwritten on a next update. I strongly suggest to check why you get such a high load.

**Comment by ioannidesalex** [comment]
I would be more worried about the high load. Hestia la_limit is there for a reason.

**Comment by dfag86** [comment]
I have a similar problem on one server. A backup never ends, it just happens over and over again. Cleanup: rm /usr/local/hestia/data/queue/backup.pipe
  touch /usr/local/hestia/data/queue/backup.pipe

does not help, no error in the /backup/ file
where to look for a solution?
