### ISSUE TITLE
service monitor [FEATURE]

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1617]
I think an important feature would be to have to a service monitor that restarts the main components:
 apache2
 php-fpm
 nginx
 exim4
 dovecot
 spamassassin
 mariadb
 vsftpd
 cron
 ssh
 iptables
 fail2ban

and upon failed emails the admin

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/6f9034ebec2ceb1dfbae8ab95007b8cdce646ef2/bin/v-restart-ftp#L53-L57

There is already a notification when a certain function restart fails.

**Comment by ScIT-Raphael** [comment]
I run a lot of hestia servers, either for my own infra or for customers. I never had the case that a service stopped and needed to be started again.

Personaly, for stable working servers, I don't think this feature would be usefull. For not stable one you probaly better check why they are instable and fix the source of the issue.

**Comment by ghost** [comment]
It happened 2twice out of almost 200 current installs. 1 was a ram being overused not a big deal to fix. but had one time could not figure out what crashed mariadb.. but I went a while before I know it was down. Though tit could be helpful thing at times.

**Comment by ScIT-Raphael** [comment]
If you got 200 installs, I would suggest to monitor them using icinga2 or similar services. As far as I remember, @jaapmarcus has a own hestia plugin to monitor the related services.

**Comment by jaapmarcus** [comment]
https://github.com/jaapmarcus/hestiacp-icinga2-tools/blob/main/tools/check_hestia

An plugin for Nagios / Icinga2. Haven't tested it yet with a custom port.

**Comment by ScIT-Raphael** [comment]
We just discussed your wish in our dev chat and we came to the conclusion, that we will not implement your request. As explained above, the server should be monitored which itself should not be a feature of hestia.
