### ISSUE TITLE
[FEATURE] hst-install.sh --reboot yes

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1619]
After installing hestia a reboot is needed.

In case you don't care to see the last page because you used the command line parameters to set passwords and hostnames or in case you are going to set your passwords via CLI later after reboot. It is an unnecesary step.

Accept --reboot parameter in command line to execute right after completion without issues:
shutdown -r now

**Comment by sickcodes** [comment]
You can add `&& reboot` to the end of the first command.

**Comment by jaapmarcus** [comment]
> You can add `&& reboot` to the end of the first command.

👍🏻
