### ISSUE TITLE
Unzip in file menu

### ISSUE THREAD

**Issue by mikey0000** [hestiacp/hestiacp#1620]
Happy to add it but would need a bit of direction since I'm unfamiliar with this project (Dev by trade though) as uploading file by file would be painful.

**Comment by jaapmarcus** [comment]
You are allready able to upload files via the filemanager and unzip:
<img width="479" alt="Screenshot 2021-02-14 at 05 57 24" src="https://user-images.githubusercontent.com/9754650/107868981-9ee03200-6e89-11eb-8b6d-2039f691400e.png">

Or do I miss something?

**Comment by mikey0000** [comment]
Ah I see, I uploaded a .gz and the option was only zip. Should have clarified.

14/02/2021 5:58:51 pm Jaap Marcus <notifications@github.com>:

**Comment by ScIT-Raphael** [comment]
We use the filegator filemanager, the gunzip request must be placed in their github project (https://filegator.io/).

**Comment by mikey0000** [comment]
Thanks for the direction.

25/02/2021 8:32:45 pm Raphael Schneeberger <notifications@github.com>:
