### ISSUE TITLE
Cannot change PHP version in existing domain

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1621]
**Describe the bug**
After installing aditional PHP version 8.0 I tried to assign it to existing domains but was not able to do it

**To Reproduce**
- Installed PHP 8.0 throught **Configure Server => Web Server** by ticking the 8 version and saved
- Created a **new package** with PHP 8.0 selected
- Assigend the **new package** to the existing domains and saved
- Edited the domains and changed the **Back End Template** to PHP 8.0 and saved
- After refresh the domain editing tab, the **Back End Template** was back to Default
- After checking at **Configure Server => Web Server** the domains are still assigend to PHP 7.4

P.S. Also tried without creating a new package, just by editing the current package and without editing the current package

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.3.2

**Comment by jaapmarcus** [comment]
Check if there are any configs left behind in /etc/php/x.x/fpm/pool.d/

**Comment by manuelserol** [comment]
At /etc/php/7.4/fpm/pool.d/ I have the .conf files for the existing domains I tried to "move" to 8.0 + the HCP subdomain config file + dummy.conf + www.conf

At /etc/php/8.0/fpm/pool.d/ I have the .conf file for a new domain I created and assigned to the new PHP 8 package + dummy.conf

**Comment by manuelserol** [comment]
The same happen when downgrading from 8.0 to 7.4

It seems the save button is not saving the changes but I get the saved message

![image](https://user-images.githubusercontent.com/23358751/108048545-12777000-703f-11eb-90a5-83fd2a770469.png)

**Comment by jaapmarcus** [comment]
Are you loggin in as user? Or admin -> Login as ?

**Comment by manuelserol** [comment]
I was doing it as user but because you asked I tried admin -> Login as and now I was able to save it

So my understanding is that there is an issue on save button when logged in directly as user not by admin first

**Comment by manuelserol** [comment]
Other detail is that this time by doing admin -> Login as I just got one green line saying "Changes have been saved" instead of two in the previous picture

![image](https://user-images.githubusercontent.com/23358751/108050809-04771e80-7042-11eb-9abb-227ab6857f58.png)

**Comment by jaapmarcus** [comment]
1. Non admin Users can't currently change php version. It will be adjusted in 1.4.0
2. The double save messages has been patched in 1.4.0 also 

It should be fixed in the next version.. 1.3.3 was only an security patch...

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/1522
