### ISSUE TITLE
[BUG] No check for inputs in v-change-user-php-cli ? 

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1623]
**Describe the bug**

Running without parameters, 
v-change-user-php-cli 

Produces
/usr/local/hestia/bin/v-change-user-php-cli: line 31: /usr/local/hestia/data/users//user.conf: No such file or directory
Error: user  doesn't exist

In v-change-user-php-cli, line 31 is 
\# Reading user values
source $USER_DATA/user.conf

I'd expect to see a Usage message if the command is issued without USER and PHPVERSION

**Comment by jaapmarcus** [comment]
Will change it
