### ISSUE TITLE
FileManager not worked [BUG]

### ISSUE THREAD

**Issue by mnffy** [hestiacp/hestiacp#1626]
**Describe the bug**
after updating to 1.3.3 the file manager does not work

**To Reproduce**
What steps did you take when the issue occured? 
1. Click on the "FIles"
2. Loading and writing an unknown error

**Screenshots**
[Screenshot](https://downloader.disk.yandex.ru/preview/704d1a766b219278ec1a41313ee664f260ed37d4bafb4cac8057115f9f8ad419/602c8f58/zfc4uGMAfBQkjltsD5BG2CJNPNSho8Trx9BzM8KCUnQHbWwkKWgNqiEgkWPEYmuitPIs8ru_C-MorVzS5LTL_g%3D%3D?uid=0&filename=2021-02-17_02-32-20.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048)

**Operating system:**
Ubuntu 20.04 (x86_64)

**Hestia Control Panel version:**
v1.3.3

**Comment by jlguerrerosanz** [comment]
I can't reproduce

Debian 10.8
Hestia 1.3.3

**Comment by jaapmarcus** [comment]
Please check first older issues it contains any solutions. On both Debain and Ubuntu I can't replicate the issue...

https://github.com/hestiacp/hestiacp/issues?q=is%3Aissue+filemanager+is%3Aclosed
https://forum.hestiacp.com/search?q=file%20manager

Check if the ssh key in /home/{user}/.ssh is working
