### ISSUE TITLE
[FEATURE] add cli command v-import-mysql-dump

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1627]
I just had to import a wiki. The dump.sql.zip was about 65MB and the uncompressed dump.sql was 300MB.
To tweak the php.ini and the mysql config file in order to import is not the way to use phpmyadmin is not the way.

**Solution: have a CLI command that helps with the import**

v-import-mysql-dump user database_name dump.sql

Additionally we could **detect if the file is compressed** and unzip it

Solution2: if we had time **maybe in the far future** make a frontend importer or integrate the importer into the file manager so you can **upload, right click and import**.

**Comment by jaapmarcus** [comment]
For CLI what is wrong with:

mysql -u username -p database < database.sql 

It has the advantage that is can be called by any user instead only root/admin user as long they have ssh access...

Changes to file manager will not happen unless we develop our own...  How ever I don't see it coming anytime soon...

**Comment by jlguerrerosanz** [comment]
There is nothing wrong with that but for the fact that you have to know your mysql password

The thing is to save time.

v-import-mysql-dump user database_name dump.sql


database=$3
#Retrieve mysql root pass
cat /usr/local/hestia/conf/mysql.conf | cut -d' ' -f3 | cut -c10-50 | sed 's/.//;s/.$//'

if (file $database | grep -q compressed ) ; then
     unzip $database
fi

mysql -u root -p database < $database

**Comment by ScIT-Raphael** [comment]
If you are logged in with root, you just need to run mysql db-name < sqldump due to the fact the creds are also saved in root user. So there is no advantage in any case. Works also for mysqldump.

**Comment by jlguerrerosanz** [comment]
I can't reproduce that.

**Comment by jaapmarcus** [comment]
ls -lah /root/ will show .mysql.cnf containing the root password

**Comment by jlguerrerosanz** [comment]
In debian 10 I have my /root/.my.cnf with the root mysql password.

root@w04:~# cat /root/.my.cnf
[client]
password='xxXXXxxxXXXXxxX'

But when I use mysqldump I am prompted with the password. Not a big deal since I now know where to find it but, makes scripting complicated.

**Comment by jaapmarcus** [comment]
Did you change the mysql root password....

**Comment by jlguerrerosanz** [comment]
No. I didn't.
In fact, if I type the password the command gets executed. It's not a big deal. If you want to explore if it is a debian issue to make a PR to correct something I will help you.

If it is for me... don't bother. It's not a big deal.

**Comment by ScIT-Raphael** [comment]
How do you mysqldump?

**Comment by jlguerrerosanz** [comment]
cd /home/myclient/web/wiki.myclient.com/public_html/
cat $HESTIA/conf/mysql.conf | cut -d' ' -f3 | cut -c10-50 | sed 's/.//;s/.$//'
mysql -p -u root myclient_wiki < wiki.myclient_mediawiki_6_2021-02-16_23-17-13.sql

**Comment by ScIT-Raphael** [comment]
Please have a look about the -p param, it will explain why it asks for a password.

**Comment by jlguerrerosanz** [comment]
Okay. Then it's me. Thank you very much for your time.
