### ISSUE TITLE
[FEATURE] assign database to domains

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1628]
In order to:
- Install web apps
- Take snapshots / backups
- Change a domain's owner
- Know what database belongs to which subdomain (in case you host 5 wordpress under different subdomains and the same user)

If there are databases 99% of the times they will belong to a web app so the backups, change domain names, etc. will always be incomplete.

Just configure a field to associate / link a database to a domain

![image](https://user-images.githubusercontent.com/8811720/108141612-5cef0000-70c4-11eb-9d1b-eb5bac039083.png)

With time, we could improve how we deal with:
- backups
- deployment of web apps (staging, cloning)
- change domain's owner the right way

**Comment by jlguerrerosanz** [comment]
Alternatively, we may assign a database to a web domain.

**Comment by ioannidesalex** [comment]
So mostly like an optional "note" without any practical effect?

**Comment by jlguerrerosanz** [comment]
Yes. **Without any effect for now**.

You can know what database belongs to which subdomain (in case you host 5 wordpress under different subdomains and the same user)

With time, we could enhance the deployment of web apps to staging, cloning...

**Comment by Lupul** [comment]
- A database can be used from multiple web domains from the same user or different user
- web domains can use multiple databases too

So it looks like not even a many-to-many relationship would be enough to cover all the use cases in a reliable manner

**Comment by jlguerrerosanz** [comment]
How about the other way around?

In the website domain config we assign the database or databases.


It is true that there will be more complex cases but 95% of the use cases will be 1 to 1.

The database option is available in Plesk like this: you assign databases to domains.

I think that it makes more sense to assign the database in the web interface.

**Comment by aaronsql2019** [comment]
I'd like to push back on this, I would NEVER let 5 sites be published on the  same user. Sorry.

**Comment by aaronsql2019** [comment]
but at the same time I *WOULD* like to be able to custom override (the default) and SOMETIMES allow one database to have multiple Web users, things like that.

**Comment by jaapmarcus** [comment]
Would require a lot of changes
