### ISSUE TITLE
1.3.3 no_symlink_chmod command not found

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#1629]
Debian 10

After update to 1.3.3
/usr/local/hestia/func/rebuild.sh: line 407: no_symlink_chmod: command not found

**Comment by Lupul** [comment]
that function should be in /usr/local/hestia/func/main.sh , can you confirm it's present in your server too?
https://github.com/hestiacp/hestiacp/blob/2f91cc881ea368b377ba5cc49569816186faca7b/func/main.sh#L1170

**Comment by arielesp** [comment]
Solved. I downloaded file main.sh again and fixed it.

thanks

**Comment by Lupul** [comment]
Any idea why main.sh wasn't updated to v1.3.3? Is this a customized setup?
