### ISSUE TITLE
DNS issues caused by incorrect AppArmor profile

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#163]
### Operating System (OS/VERSION):
Ubuntu 18.04 LTS

### HestiaCP Version:
0.9.8-25 (latest available public version)

### Installed Software (what you got with the installer):
Defaults - Apache, Nginx, MariaDB, Iptables/Fail2ban, Dovecot/Exim

### Steps to Reproduce:
1. Install HestiaCP
2. Configure custom name servers to point to your HestiaCP installation

### Behavior:
All DNS resolution for hosted domains fails even though named/bind9 is running.

### Fix for existing installations:
`echo "/home/** rwm," >> /etc/apparmor.d/local/usr.sbin.named`

### Other Notes:
This appears to be caused by AppArmor not allowing BIND to read the DNS databases located under /home/ because the install script isn't writing the necessary data correctly.

I've fixed this during installation in my fork with this commit: https://github.com/kristankenney/hestiacp/commit/e8694b010b2430739c920ac24db37468480717c3

**Comment by ScIT-Raphael** [comment]
Thanks for your report, that directly includes a solution <3! I've fixed the reported bug with the following commit: https://github.com/hestiacp/hestiacp/commit/fc3a1c581db4ad82a794f2739e273b5db4635e6a

I see that you do already a lot of changes in your fork, are you interrested to talk a bit? We are searching always devs to work together. You can add me in skype (ScIT-Raphael) or just send a mail to info@hestiacp.com. Would like to hear from you!
