### ISSUE TITLE
[BUG] Wildcard domain overwrites webmail.domain.com or any other subdomain

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1631]
**Describe the bug**
When you add *.domain.com as alias for an website. webmail.domain.com is ignored

**To Reproduce**
What steps did you take when the issue occured? 
Run the following commands

Durring bats testing
v-add-web-domain user domain
v-add-web-domain-alias user domain *.domain.com
Then 
v-add-mail-domain user domain.com

**Expected behavior**
Webmail client to be visisble instead "Empty" page

**Screenshots**

**Operating system:**
Please enter your answer here (e.g. Ubuntu 20.04 LTS)

**Hestia Control Panel version:**
Please enter your answer here (e.g. 1.3.3). 

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
With commit: 
https://github.com/hestiacp/hestiacp/commit/763c4aab297e103c0c2a7b7cace1dc27c5dcc126

Bats testing failed on the "validate_webmail_domain()" test:

To confirm:

v-add-web-domain jaap xxxx.xyz 
v-add-web-domain-alias jaap xxxx.xyz  *.xxxx.xyz 
v-add-mail-domain-alias jaap xxxx.xyz 

Vissit webmail.xxxx.xyz
<img width="916" alt="Screenshot 2021-02-22 at 20 32 45" src="https://user-images.githubusercontent.com/9754650/108760320-c8feb780-754d-11eb-83cd-a91c15775944.png">

Then: v-delete-web-domain-alias jaap xxxx.xyz *.xxxx.xyz

<img width="909" alt="Screenshot 2021-02-22 at 20 33 26" src="https://user-images.githubusercontent.com/9754650/108760417-e764b300-754d-11eb-8837-13ed7ade6797.png">

Also calling v-delete-web-alias after v-add-web-alias ensured the check went with out any issues

**Comment by jaapmarcus** [comment]
Issue is only present in Apache + Nginx (as proxy)

**Comment by Scan4u** [comment]
> So far I know it has to do with the order in how apache2 the file reads

Which file do U mean?

The mentioned domain was added through the Hestia panel in same way like other domains - nothing was changed in templates. But to some happy reason, it working nice with LE Wildcard - webmail is accesible. Let me know, if I can help with ssh access for trialing of this situation.

**Comment by jaapmarcus** [comment]
The config files in /etc/apache2/conf.d/domain/

If you have:
domain.com.conf
webmail.domain.conf
webmail.wiskey.com.conf
whiskey.com.conf

And both domains have wildcard attached:
Ony webmail.domain.conf will not work

**Comment by Scan4u** [comment]
Yes, U are right. U described exactly my situation. 
Now I understand, why my domain with name wi****.** is working fine with WLE. No magic :)

**Comment by ErikSRoth** [comment]
Any updates on this? I am having the same issue with a fresh install of Hestia. Everything works fine if I add individual aliases for subdomains, however everything breaks when I add a wildcard instead of subdomain names.

**Comment by jaapmarcus** [comment]
> Any updates on this? I am having the same issue with a fresh install of Hestia. Everything works fine if I add individual aliases for subdomains, however everything breaks when I add a wildcard instead of subdomain names.

Issue is still open nothing has changed:

It is related to: https://serverfault.com/questions/332730/exclude-specific-domains-from-apache2-serveralias-while-using-a-catch-all-wild 

So the solution would be to prepend zzzz- for any wildcard defined domain

**Comment by AlexPyth** [comment]
Hi everybody. I solved this problem like this (crutch). 

In the file /etc/apache2/apache2.conf to change the lines (Remove the space before *): 
IncludeOptional conf.d/ *.conf 
IncludeOptional conf.d/domains/ *.conf 

On: 
IncludeOptional conf.d/ *.conf 
IncludeOptional conf.d/domains/webmail. *.conf 
IncludeOptional conf.d/domains/ *.conf 

That is, to determine the webmail configuration files earlier than the main domains.

**Comment by Scan4u** [comment]
@AlexPyth - U are Genius! :) 👍 
It works like a swiss watch! :) 
@jaapmarcus - can we include this fix to your next release?
