### ISSUE TITLE
[BUG] Misspellings in CLI commands

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1633]
$HESTIA/bin/v-add-web-domain $username $domain
Error: Web domain xyz.com exist -> Should be: **exists**

$HESTIA/bin/v-add-database $username $db_name $db_user $db_pass
Error: DB=xyz_wp **is** already exists -> Should be: **xyz_wp already exists**

$HESTIA/bin/v-add-web-domain-ssl $username $domain $path
Error: SSL=yes **is** already exists -> Should be: Error: SSL=yes. The certificate for $domain already exists.

**Comment by jaapmarcus** [comment]
1. Will be fixed
2. We check if an object exits via the following code: See link 51 for v-add-database
https://github.com/hestiacp/hestiacp/blob/090608ae1039ba52d323db12a9ce5f50e6e388e1/func/main.sh#L232-L244
Don't know if the is an easy way to fix it without creating an extra check
3. Same only https://github.com/hestiacp/hestiacp/blob/eff8c3c5ff79a90a02067c84c3c2d2ad691f7efb/func/main.sh#L343-L351 as check

**Comment by jaapmarcus** [comment]
Don't know a way how we can solve the issue without rewriting the current code... But then the checks need to be created on a different way

**Comment by jlguerrerosanz** [comment]
2) check_result $E_EXISTS "$2=$3 is already exists"
Change "_is_ already exists" for "already exists"
3) check_result $E_EXISTS "${4//$}=$value is already exists" 
Change "_is_ already exists" for "already exists"

**Comment by jaapmarcus** [comment]
Oke changed
