### ISSUE TITLE
[SUPPORT] Errors php during clean install Debian 10

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1634]
**Install path:**
bash hst-install.sh -f -y no --nginx yes --apache yes --phpfpm yes **--multiphp yes** \
--vsftpd yes --proftpd no --exim yes --dovecot no --clamav no --spamassassin no \
--mysql yes --quota yes --named no --lang es --hostname $hostname -e $email -p $password

**Output**
...
[ * ] Configuring NGINX...
[ * ] Configuring Apache Web Server...
cp: cannot stat '/etc/php/5.6/': No such file or directory
[ * ] Install PHP version 5.6...
cp: cannot stat '/etc/php/7.0/': No such file or directory
[ * ] Install PHP version 7.0...
cp: cannot stat '/etc/php/7.1/': No such file or directory
[ * ] Install PHP version 7.1...
cp: cannot stat '/etc/php/7.2/': No such file or directory
[ * ] Install PHP version 7.2...
cp: cannot stat '/etc/php/7.3/': No such file or directory
[ * ] Install PHP version 7.3...
[ * ] Install PHP version 7.4...
[ * ] Install PHP version 8.0...
[ * ] Configuring PHP-FPM...
[ * ] Configuring PHP...
...
I don't know if there are any practical consequences to this but just to be safe I ask.

**Comment by ScIT-Raphael** [comment]
already fixed in main branch.
