### ISSUE TITLE
[SUPPORT] Debian 10 clean install v-add-web-domain

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1635]
On a clean install after successfully creating myuser from CLI.

$HESTIA/bin/v-add-web-domain myuser mydomain.com
cat: /usr/local/hestia/data/templates/web/apache2/.tpl: No such file or directory
cat: /usr/local/hestia/data/templates/web/nginx/.tpl: No such file or directory

**Comment by jlguerrerosanz** [comment]
Nginx is disabled and let's encrypt doesn't resolve -> Error 400

After that, via panel: enable nginx enable let's encrypt and everything works fine.

**Comment by jaapmarcus** [comment]
Install string?

**Comment by jlguerrerosanz** [comment]
bash hst-install.sh -f -y no --nginx yes --apache yes --phpfpm yes --multiphp yes \
--vsftpd yes --proftpd no --exim yes --dovecot no --clamav no --spamassassin no \
--mysql yes --quota yes --named no --lang es --hostname $hostname -e $email -p $password

**Comment by jaapmarcus** [comment]
Nginx is running on port 80. And Apache2 on port 8080 so unless you modified the ports disabling nginx will indeed cause the website not resolving .

If Nginx "proxy" is disabled and software falls back on the default behaviour
```
server {
    listen       ip:80 default;
    server_name  _;
    #access_log  /var/log/nginx/ip.log main;
    location / {
        proxy_pass  http://ip:8080;
   }
}

```

There is will discover the apache2 config
Don't see any reason why you should want to disable the proxy settings

When we release 1.3.3 I did a clean install of 1.3.3 and ran the test.bats script for automated testing

**Comment by jlguerrerosanz** [comment]
Thank you @jaapmarcus for your time.

I don't disable Nginx (at least consciously). It's just that it is not enabled after the script is run so I have to enable it manually.

Is there a CLI command to enable Nginx for a domain? Or to set it as enabled by default?

The commands I run are:

- **v-add-user** $username $hst_password $hst_email $hst_plan
- **v-add-web-domain** $username $domain
- sudo -u $username **wp core download** --locale=$wp_locale
- **v-add-database** $username $db_name $db_user $db_pass
- sudo -u $username **wp config create** --dbname=$db_name --dbuser=$db_user --dbpass=$db_pass --locale=$wp_locale --force
- sudo -u $username **wp core install** --url=$domain --title="$wp_title" --admin_user=$wp_user --admin_password=$wp_pass --admin_email=$wp_email
- **rm $path/index.html**
- **v-add-web-domain-ssl** $username $domain $path
- **v-add-web-domain-ssl-force** $username $domain
- **v-add-letsencrypt-domain** $username $domain www.$domain

The result is that nginx is deactivated when I visit the domain via panel. Which I think it shouldn't. (And it hasn't happened in a different server with the same scripts)

Maybe it is the install string that forces apache + FPM and Nginx disabled?

**Comment by wojsmol** [comment]
@jlguerrerosanz Please see issue referenced in my comment https://github.com/hestiacp/hestiacp/issues/1485#issuecomment-747794480.

**Comment by jlguerrerosanz** [comment]
> @jlguerrerosanz Please see issue referenced in my comment [#1485 (comment)](https://github.com/hestiacp/hestiacp/issues/1485#issuecomment-747794480).

I had a look at the comment and the references thread and I don't understand if it has something to do with my case or if it doesn't and how to solve the problem.

The fact is that this didn't happen on a different server (without php-fpm)

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/090608ae1039ba52d323db12a9ce5f50e6e388e1/bin/v-add-web-domain#L147-L156

It should work out of the box

**Comment by jlguerrerosanz** [comment]
Thank you @jaapmarcus 
But it doesn't work out of the box. Do you want to have a look at my server or can you reproduce the error?

**Comment by jaapmarcus** [comment]
Just done an test install from "new" server and no issue...

**Comment by ScIT-Raphael** [comment]
As usual I would suggest to test on a hetzner cloud vps, if you're able to replicate the issue there, we will have a look for sure.

**Comment by jlguerrerosanz** [comment]
Okay. I'll try again and let you know. Thank you for your time.

**Comment by jaapmarcus** [comment]
Also so far no other issues reported If we can't replicate the issue  we can't fix it ...
