### ISSUE TITLE
[FEATURE] Domain redirects (301/302) as a setting

### ISSUE THREAD

**Issue by jaredearle** [hestiacp/hestiacp#1638]
When setting up a domain, sometimes, we need another domain to redirect to it. What would be ideal is if, alongside the custom domain root, we could have a **301** or **302** redirect as an option. This would allow us to keep the domains hosted on Hestia, with the SSL settings (LetsEncrypt/HSTS/Redirects/etc) maintained.

**Comment by jlguerrerosanz** [comment]
Doesn't an alias perform a 301 redirect? If it doesn't then it should

**Comment by jaapmarcus** [comment]
No an alias is something different. And it should behave not as an redirect..

**Comment by jlguerrerosanz** [comment]
Then @jaredearle has a point.

It's common to buy an expired domain to 301 redirect it to the domain you want to rank in Google.

**Comment by jaapmarcus** [comment]
There is already an "issue/feature" report for force www -> non www / non www -> www redirects.

This can be appended with out any problem:
https://github.com/hestiacp/hestiacp/issues/427

**Comment by jaredearle** [comment]
A www to non-www redirect is not a domain redirect.

**Comment by jaapmarcus** [comment]
I know but changes to be made are for 99% the same. There should no issue to put them under the same issue. Just keep the list work able...
