### ISSUE TITLE
Debian 10 Installation - PHP Fails on MultiPHP

### ISSUE THREAD

**Issue by dvgui** [hestiacp/hestiacp#1639]
I used the following options
./hst-install.sh -a no -o yes -k no -z no -c no -t no

seems like only 7.3 was able to install, the rest are failing

[ * ] Configuring NGINX...
cp: cannot stat '/etc/php/5.6/': No such file or directory
[ * ] Install PHP version 5.6...
cp: cannot stat '/etc/php/7.0/': No such file or directory
[ * ] Install PHP version 7.0...
cp: cannot stat '/etc/php/7.1/': No such file or directory
[ * ] Install PHP version 7.1...
cp: cannot stat '/etc/php/7.2/': No such file or directory
[ * ] Install PHP version 7.2...
cp: cannot stat '/etc/php/7.3/': No such file or directory
[ * ] Install PHP version 7.3...
[ * ] Install PHP version 7.4...
cp: cannot stat '/etc/php/8.0/': No such file or directory
[ * ] Install PHP version 8.0...
[ * ] Configuring PHP-FPM...
[ * ] Configuring PHP...

**Comment by ScIT-Raphael** [comment]
Already fixed in 1.4.0 (main branch), please consider to do a short search before you open a new issue: https://github.com/hestiacp/hestiacp/search?q=cannot+stat+%27%2Fetc%2Fphp%2F8.0%2F%27&type=issues
