### ISSUE TITLE
[BUG] We need to disable sso before updating phpmyadmin

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1649]
**Describe the bug**
https://www.loom.com/share/885d3ad3fa5a42f896f81068cb42b1b2

**To Reproduce**
1st Open SSH 
run $HESTIA/install/upgrade/manual/migrate_phpmyadmin.sh
v-add-sys-pma-sso
v-delete-sys-pma-sso

https://www.loom.com/share/ab4d66297ab842d99ccd868ccc5cccde

**Expected behavior**
SSO Should work after we migrate phpmyadmin

**Screenshots**

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
 v1.4.0~alpha

**Comment by ScIT-Raphael** [comment]
It's not a bug -> connect to hostname instead ip address, phpmyadmin will not be served on ip address.

**Comment by alber-khan** [comment]
Solution By @jaapmarcus

remove line:
PHPMYADMIN_KEY='mLgp0b9KD0V7P7U5'
In /usr/local/hestia/conf/hestia.conf

Then v-delete-sys-pma-sso

**Comment by jaapmarcus** [comment]
Nope it is a bug

**Comment by ScIT-Raphael** [comment]
ok :)
