### ISSUE TITLE
[BUG] Backup not restoring with changed default backup folder

### ISSUE THREAD

**Issue by GodMorduk** [hestiacp/hestiacp#1655]
**Describe the bug**

Then you change default backup folder name, backup restoring is not working. One of the archives inside the main archive became corrupted or "unrestorable".

Example from the log (mine and Jaap Marcus who helped me):

```
Error: invalid source path /storage/hestia-backup/tmp.fz3tSsbVh2/user_dir/file.file.tar.gz
Error: Can't unpack file.file user dir container
```

```
-- USER FILES --
2021-03-06 11:51:05 file.file
Error: invalid source path /storage/tmp.WMBWLe53jU/user_dir/file.file.tar.gz
Error: Can't unpack file.file user dir container
root@dev:/backup#
```

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Change backup folder. In my case I changed it to "/storage/hestia-backup/", Jaap Marcus changed it to "/storage" and got the same problem. 
2. Create a backup by any way possible. The more separated archives would it have, the bigger chance of one of them being corrupt. 
3. Try to restore this backup.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.3

**Comment by jaapmarcus** [comment]
For debugging also happens on mail accounts:

-- MAIL --
2021-03-06 21:45:23 xxx.test
Error: invalid source path /storage/tmp.qN51xCVDBW/mail/xxxx.test/accounts.tar.zst
Error: Can't unpack xxx.test mail account container

**Comment by jaapmarcus** [comment]
Can you check out 
https://forum.hestiacp.com/t/backup-dir-location/769/16

**Comment by jaapmarcus** [comment]
Solutions seems to be
Change backup folder to /backup/
Then delete backup folder 
mkdir backup

Then:
mount --bind /mnt/large-partition/optional-subfolder /backup

For permanent fix:

/etc/fstab:
/mnt/large-partition/optional-subfolder /backup none defaults,bind 0 0

**Comment by GodMorduk** [comment]
Can confirm, solution is working.

**Comment by jaapmarcus** [comment]
For future reference please check:

https://docs.hestiacp.com/admin_docs/backups.html#how-to-change-default-backup-folder

**Comment by franciscopaniskaseker** [comment]
I did not change the backup folder and I am getting same problem to import backups:
```bash
-- WEB --
2021-04-19 15:25:24 xxx.yy
tar (child): /backup/tmp.vrNT9SIzj8/web/xxx.yy/domain_data.tar.zst: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
zstd: /*stdin*\: unexpected end of file 
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Can't unpack xxx.yy data tarball
```

**Comment by franciscopaniskaseker** [comment]
ps: same account was installed in vestacp and I did not had this problem there. I imported to hestiacp without problem. Then I tried to delete the user and restore using hestiacp and I got that.

**Comment by jaapmarcus** [comment]
Probably the issue is not releated. Please create a new issue + an  backup without any private information or send a link to support@hestiacp.com so we can debug. 

Also make sure the permissions to the root dir are 755  root / root

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/backups.html

Mount the drive and it will work fine
