### ISSUE TITLE
[BUG] Install hestiacp on Debian 10

### ISSUE THREAD

**Issue by maxpayne20012** [hestiacp/hestiacp#1657]
I using Proxmox VM with Debian Buster 10.8.
I wanted to install hestiacp. I using your bash script to install.
But your installscript will break soon with the error message:

Updating currently installed packages, please wait...-
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait...                                                                                                                                                                - Error: apt-get install failed

I have been trying to install Hestia Control Panel 1.3.3.

Please tell me, what I can to do fix it?

**Comment by jaapmarcus** [comment]
Please check the error logs why it is failing.

**Comment by maxpayne20012** [comment]
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
apt-transport-https ist schon die neueste Version (1.8.2.2).
ca-certificates ist schon die neueste Version (20200601~deb10u2).
curl ist schon die neueste Version (7.64.0-4+deb10u1).
dirmngr ist schon die neueste Version (2.2.12-1+deb10u1).
gnupg ist schon die neueste Version (2.2.12-1+deb10u1).
wget ist schon die neueste Version (1.20.1-1.1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
Paketaktualisierung (Upgrade) wird berechnet...
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

This is the log file.

**Comment by maxpayne20012** [comment]
I will reinstall my BBS with english language. I will install HestiaCP again. If an error comes you can read the error in english.

**Comment by maxpayne20012** [comment]
Now I have a successfully installed HestiaCP. Important: Before you install HestiaCP you must install a blank debian 10 system.
Did you install any software before installing for HestiaCP the installation script will maybe interrupting.

**Comment by jaapmarcus** [comment]
NOTE: Hestia Control Panel must be installed on top of a fresh operating system installation to ensure proper functionality.
