### ISSUE TITLE
php-fpm not installed by default (by design or an overlook? )

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#166]
### Operating System (OS/VERSION):

Ubuntu 18.04.2

### HestiaCP Version:

0.9.8 Release 26

### Installed Software (what you got with the installer):

Dwfault

### Steps to Reproduce:

Install Hestiacp Default install

### Other Notes:

I noticed php-fpm in not installed by default, is this by design or an overlook. I noticed vestacp does install php-fpm by default.

**Comment by ScIT-Raphael** [comment]
Vesta does also install apache2+nginx by default, that's the same for hestia. If you want to install php-fpm, you can run the installer using "hst-install.sh --phpfpm yes --apache no". You can also checkout the additional installation commands using hst-install.sh -h.

A short list what's new in hestia:
- MultiPHP switch (add --multiphp yes to your install script). This will install you the versions set here: https://github.com/hestiacp/hestiacp/blob/3e8e3b68124954517e755e7123f5f219f75c32fe/install/hst-install-ubuntu.sh#L26
- PHP FPM Version can be adjusted one line below: https://github.com/hestiacp/hestiacp/blob/3e8e3b68124954517e755e7123f5f219f75c32fe/install/hst-install-ubuntu.sh#L27
- v-change-sys-port or add --port 8083 to your install script, to change the default system port to whatever you want.
- v-change-sys-pma PMA to change the default phpmyadmin path (/phpmyadmin) to whatever you want
- v-change-sys-webmail same as pma for /webmail.

I will close your issue for now, please feel free to reopen it if you have any questions.
