### ISSUE TITLE
[FEATURE] Debian 11 Bullseye support

### ISSUE THREAD

**Issue by Neustradamus** [hestiacp/hestiacp#1661]
Can you add the Debian 11 Bullseye support?

EDIT: Debian 11 "Bullseye" Full Freeze starts:
- https://lists.debian.org/debian-devel-announce/2021/06/msg00000.html

**Comment by ScIT-Raphael** [comment]
Debian 11 is already on the list, currently it is in freezing state since 12th january. According to what I read, the release will be around this summer. So there is still plenty of time to wait for a release candidate for checking the hestia's compatibility and expand if needed. For now, I'll close the issue, due to we already monitor it internaly.

**Comment by Neustradamus** [comment]
On https://wiki.debian.org/DebianBullseye:
- 2021-01-12: Transition and (build-)essentials Freeze
- 2021-02-12: Soft Freeze
- 2021-03-12: Hard Freeze - for key packages and packages without autopkgtests (scheduled) 

The official build will be this summer but the compatibility can be operational before to test.

**Comment by jaapmarcus** [comment]
It took us last time 2 days to add some support for Ubuntu  20.04  and currently strapped for time with other commitments for Hestia and our "paid" jobs .  If you want to help feel free to do so

Install Debian Bullseye, 
Run apt-get install git

Then fork HestiaCP and clone it

And follow the instructions: https://docs.hestiacp.com/development/panel.html#install-hestia-from-packages
You might need to modify the installer on some parts

**Comment by Neustradamus** [comment]
@ScIT-Raphael: Can you reopen this ticket?
It is not solved.

**Comment by ScIT-Raphael** [comment]
As written: We already monitor it internally and working on the support.

**Comment by Neustradamus** [comment]
@ScIT-Raphael: Can you update "Supported platforms and operating systems" section in:
- https://github.com/hestiacp/hestiacp/blob/main/README.md

**Comment by ScIT-Raphael** [comment]
Why? I've clearly wrote "working on the support".

**Comment by Neustradamus** [comment]
@ScIT-Raphael: So, it is not working, when it is not working, a ticket must not be closed.

**Comment by ScIT-Raphael** [comment]
> Debian 11 is already on the list, currently it is in freezing state since 12th january. According to what I read, the release will be around this summer. So there is still plenty of time to wait for a release candidate for checking the hestia's compatibility and expand if needed. For now, I'll close the issue, due to we already monitor it internaly.

I clearly stated that the support will implemented and the tracking will be internal. Please don't tell us how we have to handle our development or issue/feature tracking...

**Comment by ScIT-Raphael** [comment]
Just for the records, hestia will support debian 11, as soon as our external repos for mariadb and nginx also provide support for it: https://github.com/hestiacp/hestiacp/tree/feature/debian_11_support

**Comment by Neustradamus** [comment]
@ScIT-Raphael: Nice to know but it is not logic to close a current unsolved ticket.

**Comment by ScIT-Raphael** [comment]
@Neustradamus honestly, I've wrote you that we monitor that specific request another way. I suggest to accept that, otherwise-> fork it and create your own project. Thanks!
