### ISSUE TITLE
[BUG] Error when creating a user.

### ISSUE THREAD

**Issue by rigin** [hestiacp/hestiacp#1662]
**Describe the bug**

Error when creating a user.

When creating a new user, in case of incorrect password filling (non-compliance with security requirements), the user is created in the database, but it is not visible in the list of users.

When you correct the password and try to create a user again, you get the error message: Error: user *** exists

**Comment by jaapmarcus** [comment]
Please explain or do I see it wrong?

<img width="708" alt="Screenshot 2021-03-08 at 00 16 07" src="https://user-images.githubusercontent.com/9754650/110258577-9029fe00-7fa3-11eb-810a-e40411c8f0ad.png">

<img width="562" alt="Screenshot 2021-03-08 at 00 16 18" src="https://user-images.githubusercontent.com/9754650/110258574-8ef8d100-7fa3-11eb-9396-1bbf6aa893a1.png">

**Comment by rigin** [comment]
Not right.

When I go under the user admin and create a user in the list of users, I need to fulfill the condition that the password has at least 8 characters, 1 letter, 1 Large letter and 1 digit. If you make a mistake here, then a message pops up that such a password is invalid, and after the correction, an error message appears that such a user already exists.
But it is not in the list of users .

**Comment by rigin** [comment]
[](url)

**Comment by rigin** [comment]
Not right.

When I go under the user admin and create a user in the list of users, I need to fulfill the condition that the password has at least 8 characters, 1 letter, 1 Large letter and 1 digit. If you make a mistake here, then a message pops up that such a password is invalid, and after the correction, an error message appears that such a user already exists.
But it is not in the list of users .

![Без имени-1](https://user-images.githubusercontent.com/904365/110365301-ee171e00-8055-11eb-81d7-faa68264ed17.jpg)
