### ISSUE TITLE
[Feature] SSL Self Signed Domain

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1663]
**Is your feature request related to a problem? Please describe.**
Sometimes we use some proxy like Cloudflare with SSL set to full (then all comunication will occur under https). If you do that, then the lets encrypt will fail. If we have self signed option, everything will works.

**Describe the solution you'd like**
SSL self signed option, like lets encrypt option.

**Describe alternatives you've considered**
I like the alternative implemented by cyberpanel: if the lets encrypt ssl issue fail, then a self signed will be created. But to be honest I prefer to choose the option that I want.

**Additional context**
I think just one panel do that (cyberpanel). This will solve a lot of work for people that do not know how to use Cloudflare.

**Comment by jaapmarcus** [comment]
<img width="576" alt="Screenshot 2021-03-08 at 06 55 17" src="https://user-images.githubusercontent.com/9754650/110280534-43fab000-7fdb-11eb-9803-6d3a173eb49a.png">

Disable Lets Encrypt and then click:Generate Self signed ssl  https://xxxx:8083/generate/ssl/?domain=xxx.xyz

I don't like the option that it creates it by default as when an user fails to move transfer the domain to the correct ip adress it will generate an ssl certificate and the user could understand it wrong..

I personally suggest use the root certificate from Cloudflare:
https://docs.hestiacp.com/admin_docs/ssl_certificates.html

**Comment by franciscopaniskaseker** [comment]
Great.
