### ISSUE TITLE
[BUG] Error when creating a user.

### ISSUE THREAD

**Issue by rigin** [hestiacp/hestiacp#1668]
**Describe the bug**

When creating a new user, in case of incorrect password filling (non-compliance with security requirements), the user is created in the database, but it is not visible in the list of users.

![Без имени-1](https://user-images.githubusercontent.com/904365/110623594-19148580-81ae-11eb-8809-cab14bcd3dd9.jpg)

When I go under the user admin and create a user in the list of users, I need to fulfill the condition that the password has at least 8 characters, 1 letter, 1 Large letter and 1 digit. If you make a mistake here, then a message pops up that such a password is invalid, and after the correction, an error message appears that such a user already exists.
But it is not in the list of users .

p/s: I accidentally closed the previous Issue, so I'll duplicate it. Sorry.

**Comment by jaapmarcus** [comment]
What happens when you run`/usr/local/hestia/bin/v-list-users` in command line

**Comment by rigin** [comment]
I understood what was the matter.
My name of the user being created was the same as the name of an existing linux user.
I installed the panel on an already deployed operating system.

Perhaps, when creating a user in the panel, it is worth adding a prefix to the username in the system.
Otherwise, such coincidences are quite possible.

**Comment by jaapmarcus** [comment]
We always suggest to install on a clean server:

NOTE: Hestia Control Panel must be installed on top of a fresh operating system installation to ensure proper functionality.

We also do a check if the user already exsists to prevent new user over write current system users

**Comment by jaapmarcus** [comment]
Changing user name by adding an a prefix should never be done by the system the current behaviour is correct.
