### ISSUE TITLE
Feature Request: Implement v-add-letsencrypt-host in Hestia backend.

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#167]
I know this can be done via the command line but it would be nice to have it on the web interface as well, similar to the way LE is implemented with sites.

**Comment by ScIT-Raphael** [comment]
Just follow the tutorial from @dpeca: https://forum.vestacp.com/viewtopic.php?t=17353

This is still the same for hestia. We work at a "one click" solution, also that you can enable it over the backend.

I close the issue, please feel free to reopen it if you have any additional question or feedback.

**Comment by Wibol** [comment]
As well as in "HestiaCP/Server/$HOSTNAME/Configure/SSL" there is a "Generate Self-Signed SSL Certificate" link, can you add a "Generate LetsEncrypt SSL Certificate" link for launching "v-add-letsencrypt-host" from GUI?

**Comment by ScIT-Raphael** [comment]
Infact v-add-letsencrypt-host is a onetime command, there is no need to implement it to the interface. Also we will work on a direct run of it on hestia's installation process, if this fails, you still can run it on cli.
