### ISSUE TITLE
[BUG] FTP username duplicate...

### ISSUE THREAD

**Issue by vegtelenmt2** [hestiacp/hestiacp#1674]
Hello! Ftp username duplicate :/ 

**To Reproduce**
What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Edit web".

**Operating system:**
Debian 9.13 64bit

**Hestia Control Panel version:**
v1.3.3

I've solved it once, but it always changes back with an update.

**Comment by ScIT-Raphael** [comment]
Thanks for the report, this has already been fixed in main branch and will be shipped with 1.4.0.

**Comment by vegtelenmt2** [comment]
Thanks! :)
