### ISSUE TITLE
[BUG]  v-rebuild-web-domains not correctly rebuilding one domain out of six. 

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1677]
Not sure if this is related to the 1.3.4 update, or whether it has been around for a while and I've never used a full  v-rebuild-web-domains for a while with this configuration. 
For one user on one of my Hestia installations, the 1.3.4 upgrade triggered a  v-rebuild-web-domains and only four out of six were correctly rebuilt.
 
One domain was rebuilt with the DocumentRoot in both nginx and apache2 config files, pointing to the WRONG document root. It was incorrectly set as the domain which was processed immediately before this one. Perhaps a variable not getting re-set? 

One further domain lost its path (an additional /html/ after /public_html/). This is a minor point, and as it was processed after the problem domain, it might be related to the earlier breakage, so lets ignore this for now. 

Building the domains with v-rebuild-domain USER DOMAIN fixes the issues. So it seems to be an issue with the multiple rebuild. 

**To Reproduce**
- Ran v-rebuild-web-domain USER DOMAIN to fix
- Ran  v-rebuild-web-domains USER -> breaks again. 
- Ran v-rebuild-web-domain USER DOMAIN to fix

**Operating system:**
Ubuntu 20.4

I feel that the answer might be contained in the domain names themselves. The problem one is a subdomain containing a number which makes it different to the other 5. I don't want to post these publicly, but can make the 'bash -x v-rebuild-web-domains USER' output available to you privately. Please advise how to do this.

**Comment by jaapmarcus** [comment]
Please send an email to info@hestiacp.com

**Comment by jaapmarcus** [comment]
I am trying to look trough the log files but I can't find the error. If possible try to replicate the issue with an second user and some random domains and when successful please create an backup of the "test" user.

**Comment by plutocrat** [comment]
It is a long logfile! OK, so I was having another look yesterday and I noticed that the domain before the problem one (txxxxxxx.domain.com), had a custom path. So my current theory is that somehow the "custom_path" path is inherited from the previous domain in the processing queue. 
I checked this by editing the /usr/local/hestia/data/users/username/web.conf file. 
I added 
CUSTOM_DOCROOT='/home/username/web/nxxxx.domain.com/public_html/
in the file to the problem domain, and ran v-rebuild-web-domains username
This time the domains were all built correctly. 

I had a look in the v-rebuild-web-domains code to see if I could spot where this was happening, but couldn't immediately. 
One fix would be to make sure every domain has a CUSTOM_DOCROOT='' set to null if there is no _actual_ custom docroot. But it would obviously be far better to find the missing logic in the script and fix that. I'll take a look again.

**Comment by plutocrat** [comment]
My best guess would be the logic in these lines needs to be adjusted. 

https://github.com/hestiacp/hestiacp/blob/0678bde2c832da2d015c1df17922e0ac8f743bb0/func/domain.sh#L186

**Comment by jaapmarcus** [comment]
You have a point:

Issue is caused in:
https://github.com/hestiacp/hestiacp/blob/0e43d28b68abffd9b652824927ad28cb1be87580/func/domain.sh#L866-L869

In 1.2 and after that few new vars has been "Added"  but the older / imported files have never been updated and there for are missing. As the function is "stupid" enough to do not care about the new config vars and even not clean them. 

Time for a health check on rebuild

**Comment by jaapmarcus** [comment]
Easiest method for now is:
Edit web -> Update custom docroot and then disable it it will leave the CUSTOM_DOCROOT

Will try to create an "Health" check system for older domains

**Comment by jaapmarcus** [comment]
Thanks found the issue this commit will solve it
:)
https://github.com/hestiacp/hestiacp/pull/1683/commits/b5b3f252fed9dde80781ec994c126f15b1045137
