### ISSUE TITLE
[BUG] after user restore, "Files" tab displays "unkown error"

### ISSUE THREAD

**Issue by fuzhyperblue** [hestiacp/hestiacp#1678]
**Describe the bug**
after user restore, "Files" tab displays unkown error

**To Reproduce**
What steps did you take when the issue occured? 
1. restore user backup via ssh terminal v-restore-user
2. Click on "Files" under user account on GUI
3. Popup Unkown Error, files dont list

**Expected behavior**
"Files" should be working

**Screenshots**
https://prnt.sc/10pscxp

**Operating system:**
Ubuntu 18.04 LTS

**Hestia Control Panel version:**
1.3.4

**Comment by jaapmarcus** [comment]
Delete any existing ssh keys in /home/user/.ssh/ folder

**Comment by fuzhyperblue** [comment]
> Delete any existing ssh keys in /home/user/.ssh/ folder

thanks, now working.
