### ISSUE TITLE
Feature Request: LE certs for each mail.domain.ext added via web interface

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#168]
When you add a web domain via web interface it by default creates a mail subhost for that domain. It would be nice to have a checkbox to enable letsencrypt for that sub domain for imap and exim. This will eliminate the Cert Verify notice on mail clients when they use as thunderbird, outook etc

**Comment by ScIT-Raphael** [comment]
There was already a team internal discussion about this feature, i will leave your issue open. Additional informations "how to solve" this feature request can maybe be found here: https://github.com/serghey-rodin/vesta/issues/1572

**Comment by johnnyq** [comment]
Gotchya sorry I must of missed this. I hope this can be resolved at some point thanks for the quick responses

**Comment by ScIT-Raphael** [comment]
No need for sorry! You can't know the issue from vesta - also I just found it out today after we've discussed this as a potential feature :).

**Comment by ScIT-Raphael** [comment]
Additional informations: https://help.atmail.com/hc/en-us/articles/115009208748-Multiple-SSL-certs-with-Dovecot-Exim

Should be possible, we will work on a integration.

**Comment by ghost** [comment]
@johnnyq, 

I wanted to provide you with a quick update on your feature request for per-domain SSL/Let's Encrypt support for mail domains; we're actively developing this now as part of our planned changes to the mail stack and will have more information to share soon. Thanks again and stay tuned. :)

**Comment by johnnyq** [comment]
That's Excellent! @kristankenney  I can't wait I have been wanting this feature for about a year and half now

**Comment by ScIT-Raphael** [comment]
Implemented in develop branch, will follow in a new version soon. Will close the issue for now.
