### ISSUE TITLE
[BUG] 1.3.4 Update removed SSH login setting for users -- reset to nologin.

### ISSUE THREAD

**Issue by buxjr311** [hestiacp/hestiacp#1680]
HestiaCP was automatically updated successfully.  Upon rebuild of user accounts, SSH setting was reverted back to "nologin", from "bash", effectively disabling remote SSH access, without logging in via HestiaCP to re-set this user account option.

Not the end of the world, but an unexpected (and unwelcome) bump in the road.

Just figured I'd report it, just so y'all can review and potentially add a fix to the next update.

Thanks.

**Comment by jaapmarcus** [comment]
Did you use v-change-user-shell username bash or just modified the /etc/passwd

**Comment by buxjr311** [comment]
I had originally set the user account to allow SSH login via 'bash', using the "edit user" capability within HestiaCP interface.  It had been set and was working correctly, until after the 1.3.4 update was installed/applied.  The update effectively overwrote this previously configured option, back to the default of "nologin".  Again, it just took logging in through HestiaCP, and simply re-setting it back to "bash" (and clicking SAVE), to restore this functionality.  Just a minor annoyance, but an annoyance just the same.

**Comment by jaapmarcus** [comment]
The only reasons I can find:

https://github.com/hestiacp/hestiacp/blob/66f19e1afa006374ec5d1d2d0039a572a8931490/func/rebuild.sh#L61-L67

But the v-change-user-shell / WebUI should set the shell value in the user.conf

**Comment by buxjr311** [comment]
So...are you saying that the "rebuild" code DOES effectively set this configuration option, back to NULL?  That would explain why it defaulted back to "nologin" (which is the default, read: NULL) value.  Am I missing something here?  Can the rebuild code be altered to simply keep whatever value is already there, when applying the update?

**Comment by buxjr311** [comment]
Hmmm, I see.  Yes, we agree then, why indeed, did it get set back to "nologin".

This happened on two separate machines/installations of Hestia, so it was observed twice, which made me believe it was a bug and not a random fluke/glitch.

I never used the Hestia cli commands.  I configured this setting via the "SSH Access" drop down list, on the "Edit User" page, via the Hestia GUI (User > admin > Edit User > SSH Access).  

As previously mentioned, it was set a while back and was working fine.  I have a shortcut to the SSH (using keys, no password) on my desktop.  Previously, clicking that shortcut, dropped me directly into my admin SSH shell/commandline.  After the 1.3.4 update, this shortcut resulted in error, stating, "This server allows sftp connections only." and closed the connection.

So, after review of the User Account within the Hestia GUI, I discovered that the "SSH Access" option had reverted back to "nologin".  So, I set it back to "bash" and my shortcut resumed working correctly.

Please let me know if there is anything I can do to help you sort this out.  I am happy to help.

**Comment by buxjr311** [comment]
UPDATE:  I just manually pushed updates 1.3.4 -> 1.3.5 on both servers and this time the "bash" setting was retained!  So perhaps this is put to bed?

**Comment by ghost** [comment]
1.3.5 doesn't do a rebuild on user configuration which might explain why it didn't trigger for this update, can you test running `v-rebuild-user <user>` from the shell to see if the value is reset?

**Comment by buxjr311** [comment]
Ah, that makes sense...

I logged into the shell as root and performed "v-rebuild-user admin" -- no errors.  Upon review, "SSH Access" setting was retained.

HTH
