### ISSUE TITLE
Webmal not working

### ISSUE THREAD

**Issue by rfnxinger** [hestiacp/hestiacp#1682]
the Link icon for webmail is leading to a non present website.

![grafik](https://user-images.githubusercontent.com/31359191/111921279-14947a80-8a94-11eb-952d-e3b171e64912.png)

**Comment by rfnxinger** [comment]
Do I have to install further addons or packages?

**Comment by jaapmarcus** [comment]
Make sure the domain is resolving

jaapmarcus@Jaaps-MacBook-Pro ~ % ping webmail.gotnet.io
ping: cannot resolve webmail.gotnet.io: Unknown host

**Comment by rfnxinger** [comment]
what kind of record do I have to use?
I have a CNAME record for mail.rfnx.eu & webmail.rfnx.eu and bothe are not resolvabalke by ping coomand:
ping: mail.gotnet.io: Name or service not known
ping: webmail.gotnet.io: Name or service not known

**Comment by jaapmarcus** [comment]
Please use our support forum (https://forum.hestiacp.com) for support questions. Normally an A record is needed or an cname but it  need to point to an other dns record that is working.
