### ISSUE TITLE
[BUG] iptables rules fail to restore if multiple network adapters present

### ISSUE THREAD

**Issue by Pryx** [hestiacp/hestiacp#1689]
**Describe the bug**
I've been tracking a problem with firewall rules not applying on boot for some specific VPS machines and finally found the cause. Some of the machines we use have two ethernet adapters assigned to them by the VPS provider. This causes Hestia to create the `/usr/lib/networkd-dispatcher/routable.d/50-ifup-hooks` file with a wrong if condition. The condition looks like this:
```
if [ "$IFACE" == "eth0
eth1" ]; then ...
```

It should probably look something like this:

```
if [ "$IFACE" == "eth0"] || [ "$IFACE" == "eth1" ]; then ...
```

Right now I manually fixed the condition (only one of the eth adapters is really used, so I just deleted the second one), but it would be nice if Hestia would handle this automatically.

**To Reproduce**
1. Install Hestia on Ubuntu 20.04 machine that has multiple network adapters
2. Disable some predefined rules (e.g. SSH)
3. Reboot and see SSH working regardless = rules not applied (running v-update-firewall fixes that until the next reboot)

**Expected behavior**
iptables rules should be successfully applied on boot 

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.5

**Comment by Lupul** [comment]
I can confirm the issue, and thx for an excelent bug report :+1: 

Relevant code(bug) is here:
https://github.com/hestiacp/hestiacp/blob/b543ea2238cc35f2a24715937700e297a2394cf4/bin/v-update-firewall#L191-L194
