### ISSUE TITLE
Add Database User (maximum 16 characters length, including prefix) <- is this still relevant

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#170]
is this limitation still relevant with the latest version of mariaDB? if so we can remove this limitation when adding a database

**Comment by ScIT-Raphael** [comment]
This limitation was already removed: https://github.com/hestiacp/hestiacp/commit/f1f4023c15a36f10ec726f6a0f0658dfcc193bee

**Comment by johnnyq** [comment]
Oh that's a good thing. It looks like just the label helper text needs updated then when you go to add the database currently it states maximum 16 characters length, including prefix. Update to maximum 30 characters length, including prefix
