### ISSUE TITLE
[BUG] Nginx access/error log files not removed when domain is deleted

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#1705]
**Describe the bug**
Nginx access/error log files not removed when domain is deleted (/var/log/nginx/domains)

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Add Web Domain".
3. Ex.: Attempted to add a domain and received an Internal Server Error.

**Expected behavior**

**Screenshots**

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
1.3.5

**Additional context**
They should be deleted when the domain is removed.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/8eb5219bed6f3e18f815d7aa1a59a31f38b48a3b/bin/v-delete-web-domain#L105-L108

Still need to test it...
