### ISSUE TITLE
[SUPPORT]can't start iptables and fail2ban within ubuntu 20.04 by oraclecloud

### ISSUE THREAD

**Issue by doublog** [hestiacp/hestiacp#1706]
root@frankfurt-serv01:~# v-start-service iptables
bash: v-start-service: command not found
root@frankfurt-serv01:~# /usr/local/hestia/bin/v-start-service iptables
root@frankfurt-serv01:~# /usr/local/hestia/bin/v-start-service fail2ban
root@frankfurt-serv01:~# sudo apt install fail2ban
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fail2ban is already the newest version (0.11.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@frankfurt-serv01:~# sudo systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-03-30 09:02:02 UTC; 5min ago
       Docs: man:fail2ban(1)
    Process: 4852 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
    Process: 4853 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 4853 (code=exited, status=255/EXCEPTION)

Mar 30 09:02:01 frankfurt-serv01 systemd[1]: Starting Fail2Ban Service...
Mar 30 09:02:01 frankfurt-serv01 systemd[1]: Started Fail2Ban Service.
Mar 30 09:02:02 frankfurt-serv01 fail2ban-server[4853]: 2021-03-30 09:02:02,156 fail2ban      >
Mar 30 09:02:02 frankfurt-serv01 fail2ban-server[4853]: 2021-03-30 09:02:02,158 fail2ban      >
Mar 30 09:02:02 frankfurt-serv01 systemd[1]: fail2ban.service: Main process exited, code=exite>
Mar 30 09:02:02 frankfurt-serv01 systemd[1]: fail2ban.service: Failed with result 'exit-code'.

i was install hestiacp by oraclecloud with frankfurt localtion wrong with it. The Japan Vps is ok. So,i don't know why.

**Comment by jaapmarcus** [comment]
Please use for support our forum located at https://forum.hestiacp.com 

**Please do NOT use our GitHub Project for support requests, you can find community support and help here:**
**Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
**Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
**Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)

**Comment by doublog** [comment]
ok,thanks.
