### ISSUE TITLE
[BUG] v-generate-api-key generates key that v-add-remote-dns-host cannot use

### ISSUE THREAD

**Issue by lastguru-net** [hestiacp/hestiacp#1708]
When setting up a DNS cluster, an alternative to providing an admin password is to generate an API key with v-generate-api-key, as advised in v-add-remote-dns-host comments. However, the key generated as advised may contain the '-' character that v-add-remote-dns-host does not accept:
```
# ./v-add-remote-dns-host xx.example.com 8083 some_key-with_some-minuses ''
Error: invalid hash format :: some_key-with_some-minuses
```

If I manually change the API key to not contain '-', everything goes as it should.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.5

**Comment by jaapmarcus** [comment]
Will be fixed for 1.4.0
