### ISSUE TITLE
BUG: 1.3.4/1.3.5 upgrade reset custom control panel port to 8083

### ISSUE THREAD

**Issue by animeai** [hestiacp/hestiacp#1710]
I'm unsure which of these two updates caused this bug (my other was ssh access for all users being reset, but this appears to have been fixed). I use port 2053 for the hestia control panel as this is compatible with cloudflare's free tier proxy service and keeps the real server IP hidden from potential attackers. (This is an excellent work around and should probably be documented somewhere!) However during one of the last two updates (I cannot be sure which as they happened close together and I did not log into 1.3.4 before 1.3.5 was pushed) the custom port was reset to 8083. I'm unsure why this happened and do not have time to delve into the code. "v-change-sys-port 2053" followed by a manual "systemctl restart hestia" fixed this.

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/server_management.html#can-i-use-hestiacp-behind-cloudflare-cdn

It is already documented in our documentation. 

v-change-sys-port should write the correct new port number in the config and update the values in the config and It doesn't 

We should check it to make sure

**Comment by ghost** [comment]
@animeai, 

Can you review the most two or three recent `/root/hst_backups/[date]/conf/hestia/hestia.conf` files, check the value for `BACKEND_PORT` to see if it differs from 2053? Also review `hst-upgrade-[date].log` in `/root/hst_backups/[date]/` for any messages referring to the port being reset by the system health check and kindly let us know your findings.

Thank you.

**Comment by animeai** [comment]
@kristankenney 
All hestia.conf checkd. Neither of the two available backups from /root/ had "BACKEND_PORT", but my current config has BACKEND_PORT='2053' at the bottom. The upgrade log for 1.3..3 to 1.3.4 had "[ ! ] Adding missing variable to hestia.conf: BACKEND_PORT ('8083')".

I cannot remember if I set the custom backend port on installation of HestiaCP or using v-change-sys-port following installation. This was a fresh server install in February following an OS reinstall (upgrade) from Ubuntu 18.04 to 20.04 on this particular server. I don't have a custom port on the other server I use HestiaCP on as I use a subdomain that points to the right IP for that server.  

Let me know if you want any of the logs, I should still have things like the install log if required.

**Comment by jaapmarcus** [comment]
The part where it sets into the config is part of an "system health" check 

https://github.com/hestiacp/hestiacp/blob/27556a9a43aeaf308b33be224c2e70f2011574e6/func/syshealth.sh#L237-L241

If set normally via during install we also use:

https://github.com/hestiacp/hestiacp/blob/00c6a96b8ae28a8568dd3b71d70fd285b953e0d5/install/hst-install-ubuntu.sh#L1176-L1177

The issue left why it hasn't ben set

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/27556a9a43aeaf308b33be224c2e70f2011574e6/bin/v-change-sys-port#L62-L70

We should probably convert it to v-change-sys-config-value

**Comment by jaapmarcus** [comment]
We have added an "auto detection" script that get the port number from the /usr/local/hestia/nginx/nginx.conf should fix the issue for 1.4.0

https://github.com/hestiacp/hestiacp/pull/1712/commits/326f4e65de384242e0b0ce1dac60e86db2c7c238
