### ISSUE TITLE
BUG: NGINX and Apache fail to start on reboot if ZeroTier local IPs are used on the server 

### ISSUE THREAD

**Issue by animeai** [hestiacp/hestiacp#1711]
I use ZeroTier to secure my installation and prevent any access to ports other than http, https, and the hestiacp panel (no public ssh is accessible and only an authorised user connected to the correct ZeroTier global area network can access - it works in a similar way to a VPN without the fuss) and run two ZeroTier networks on my server - one in the 10.x.x.x and one in the 192.x.x.x private IP range. I believe NGINX and Apache are trying to start before the ZeroTier IP is established as I get a failure. An example from the syslog is "Mar 31 04:16:51 server nginx[715]: nginx: [emerg] bind() to 10.X.X.X:80 failed (99: Cannot assign requested address)".

Following access to ssh, NGINX and Apache can both be started normally with "systemctl start nginx/apache2". I'm unsure if this is a HestiaCP bug or an upstream bug caused by ZeroTier not being ready to allow anything to bind to its IP(s).

**Comment by jaapmarcus** [comment]
If Zerotier doesn't allow to bind to that address or ZeroTier is loaded after Apache2 / Nginx  we can't do a lot about it .

**Comment by ScIT-Raphael** [comment]
I'll going to close it, not related to hestia. I would suggest to use the implemented firewall and limit ssh to static ips (could also be a central vpn server or similar).
