### ISSUE TITLE
Feature Request: White label branding

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#172]
Ability to change the branding (logo, text) for hestiaCP Web panel and roundcube webmail using the web interface.

**Comment by ScIT-Raphael** [comment]
We plan a rewrite of the backend using Laravel as full stack php framework. There is also a idea to implement a template engine, where you can manage them without much work. The rewrite will take a lot of work, we do not have any ETA yet.

For webmail we can't provide any engine, it's based on the default repo package.

I will close the issue for now, please feel free to reopen it if you have any question!

**Comment by johnnyq** [comment]
neat! I look forward to it!

**Comment by xeruf** [comment]
hey, is there any update on this? This shouldn't be closed if it isn't solved

**Comment by ScIT-Raphael** [comment]
Rewrite is still a wish, but needs massive ressources. If you want to have a white label function, there is still an option to sponsor it - but we do not have any prio here.

**Comment by xeruf** [comment]
Maybe simply replace all mentions of "Hestia Control Panel" (tab title, login, etc) by an environment variable with the current text as default?

**Comment by ScIT-Raphael** [comment]
Please have a review of the existing code, it isnt "that" easy. Also we do not have any real advantages when we provide a "white label branding", if you want to have it - fork it and do the changes on your own.

**Comment by xeruf** [comment]
Found a good workaround :)

https://stackoverflow.com/questions/1583219/how-can-i-do-a-recursive-find-replace-of-a-string-with-awk-or-sed/22385837#22385837  

    grep -rl 'Hestia Control Panel' /usr/local/hestia/web | xargs sed -i 's/Hestia Control Panel/Iridion/g'


https://docs.hestiacp.com/customize_hestia.html#can-i-run-certain-command-before-and-after-update  

    mkdir /etc/hestiacp/hooks
    echo '#!/bin/sh'"
    grep -rl 'Hestia Control Panel' /usr/local/hestia/web | xargs sed -i 's/Hestia Control Panel/Iridion/g'" | tee /etc/hestiacp/hooks/pre_install.sh
    chmod +x /etc/hestiacp/hooks/pre_install.sh
