### ISSUE TITLE
 videos and messed up content from the sites automatically

### ISSUE THREAD

**Issue by euphoriatek** [hestiacp/hestiacp#1721]
Hello Support Team Members,

 Before 2-3 day's I have Installed LiveSmart successfully On My client Hestia Control
 Server  https://patrio.tv:8083  but after installation LiveSmart by ubuntu Terminal command on
 https://patrio.tv:8083 server so after some time automatically https://patrio.tv is not
 showing any videos and seems messed up content from the site front page. Do you
 know the issue. please let me know if you have any solution to restore old backup or old data on the same server.

 thanks & regards
 Nidhi Barve

**Comment by ScIT-Raphael** [comment]
Please do not use github for support requests, you should have been informed while opening a support based issue:

**Please do NOT use our GitHub Project for support requests, you can find community support and help here:**

**Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
**Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
**Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)

Also, the issue template isnt decoration and should be filled out and not deleted...

**Comment by euphoriatek** [comment]
ok thank you so much !
