### ISSUE TITLE
[BUG] Statistics username changed after backup restore

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1723]
**Describe the bug**
After restoring a backup to a new username all the domain statistics usernames been changed with a prefix added like newusername_oldusername where it should keep only oldusername

**To Reproduce**
Restore a backup to a different username

**Expected behavior**
Keep the same statistics usernames

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.3.5

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1741
