### ISSUE TITLE
[BUG] mail missing some dns records

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#1726]
**Describe the bug**
Missing dns records for imap.{domain.tld}, smtp.{domain.tld} and pop.{domain.tld}, for microsoft outllook app and others possibly

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. create a email domain
2. create a email account
3. try to connect using android microsoft outlook
4. check the settings of the connection, there will be an imap.{domain.tld} and a smtp.{domain.tld}

**Expected behavior**
connecting to webmail without problems in certificate, and with the right dns records for outlook and other clients on android, possibly on IOS and windows mail too

**Operating system:**
Ubuntu 18.04 LTS

**Hestia Control Panel version:**
1.3.5

**Additional context**
nothing further

**Comment by jaapmarcus** [comment]
Currently the default to be used is mail.domain.com. I think any other app should allow the use of mail.domain.com.

There is already a current outstanding issue for adding smtp / imap / pop3 as additional subdomains for mail

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/1274

So this issue can be closed
