### ISSUE TITLE
[BUG] hestia autobackup filed notifications not working

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#1729]
**Describe the bug**
hestia daily auto-backup ( i think its 05:30am)..
Last week i checked my websites backup, it was not working on after 13-march-20201 (for about past 10 days). The issue was due to my server disk space. But expecting the bkp failed notification. If i have not check the backup tasks, i cant even think my client's complaints :-)

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. increased disk server space. So the next day the auto-bkp task works as usual.
2. Put a 20GB file inside /home/#USERNAME/web/#WEBSITE.com (This try is to let the bkp task try to consume the over space. So will fail & expecting the failed notification)
3. I did the above step #2, as expected, the auto bkp failed on next day but no email notifications.
4. But the log file shows clearly. /usr/local/hestia/log >> Error: not enough diskspace available to perform the backup.
5. If i trigger the hestia bkp manually, it tried, failed & i recvd the expected notification
6. https ://3MYSERVER .com:443/list/backup/ >> create backup

**Expected behavior**
Hestia auto bkp tasks, need bkp failed email notifications. Or am i missing some settings over here to enable it.?

**Operating system:**
Ubuntu Linux 20.04.2

**Hestia Control Panel version:**
hestia 1.3.5

**Comment by ioannidesalex** [comment]
I agree.

**Comment by jaapmarcus** [comment]
Fix with https://github.com/hestiacp/hestiacp/pull/1741
