### ISSUE TITLE
Feature Request: Enable chroot ssh to users home

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#173]
For security purposes FTP is a dead protocol, could this be removed completely and just use ssh and scp when needed and also chroot the user to their own home folder

**Comment by ScIT-Raphael** [comment]
Due to compatibility, FTP is still a need - also vsftp is configured to provide ftps by default. There is also some idea to implement chroot as default, similar to the vesta sftp chroot module. I will leave this request open and change your title.

**Comment by JOduMonT** [comment]
@johnnyq 
I think what you want is `rssh`
at least in debian, probably ubuntu to, you could try

````
apt install -y rssh
````
#### than define your user
````
yourUser=

sudo chsh $yourUser -s rssh
````

**Comment by ScIT-Raphael** [comment]
Chroot is now enabled by default in develop branch, we will close the issue. Please feel free to open it again or create a new one.
