### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bludelego** [hestiacp/hestiacp#1733]
After disabling softaculous continue to recieve mail notification Software Updates The following software were updated during Automatic Cron Updates:
and the list of 
**Describe the bug**
A clear and concise description of what the bug is. Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Add Web Domain".
3. Ex.: Attempted to add a domain and received an Internal Server Error.

**Expected behavior**

**Screenshots**

**Operating system:**
Please enter your answer here (e.g. Ubuntu 20.04 LTS)

**Hestia Control Panel version:**
Please enter your answer here (e.g. 1.3.2). 

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
We don't support Softaculous
