### ISSUE TITLE
[SUPPORT] Auto update SSL stop working after update

### ISSUE THREAD

**Issue by rAmfu** [hestiacp/hestiacp#1736]
After hestiacp update cron job with SSL update stop working.

**Debian 10 
Update to latest version**

**Hestiacp log:**
=============================
WEB_SYSTEM: apache2
PROXY_SYSTEM: nginx
user: Svor
domain: svor.wroclaw.pl

- aliases: www.svor.wroclaw.pl
- proto: http-01
- wildcard: 

==[Step 1]==
- status: 200
- nonce: 0004QZ61jPEHAdqOFDiL6PsfZ_-vXprR2zQV88StRzrQSw4
- answer: HTTP/2 200 
server: nginx
date: Sun, 11 Apr 2021 03:34:02 GMT
content-type: application/json
content-length: 658
cache-control: public, max-age=0, no-cache
replay-nonce: 0004QZ61jPEHAdqOFDiL6PsfZ_-vXprR2zQV88StRzrQSw4
x-frame-options: DENY
strict-transport-security: max-age=604800

==[API call]==
exit status: 0

==[Step 2]==
- status: 201
- nonce: 0103xTzbYpVAM4-p6Yvlr6gTqbQFMHGTRJc0Bh6xBQqy83A
- authz: https://acme-v02.api.letsencrypt.org/acme/authz-v3/12219897344
https://acme-v02.api.letsencrypt.org/acme/authz-v3/12244750052
- finalize: https://acme-v02.api.letsencrypt.org/acme/finalize/111215740/8992682706
- payload: {"identifiers":[{"type":"dns","value":"svor.wroclaw.pl"},{"type":"dns","value":"www.svor.wroclaw.pl"}]}
- answer: HTTP/2 201 
server: nginx
date: Sun, 11 Apr 2021 03:34:03 GMT
content-type: application/json
content-length: 478
boulder-requester: 111215740
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
location: https://acme-v02.api.letsencrypt.org/acme/order/111215740/8992682706
replay-nonce: 0103xTzbYpVAM4-p6Yvlr6gTqbQFMHGTRJc0Bh6xBQqy83A
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "status": "pending",
  "expires": "2021-04-17T03:34:03Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "svor.wroclaw.pl"
    },
    {
      "type": "dns",
      "value": "www.svor.wroclaw.pl"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12219897344",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12244750052"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/111215740/8992682706"
}

==[API call]==
exit status: 0

==[Step 3]==
- status: 200
- nonce: 010304lxUfpifA1EgCi6O6ll-1q9ijlbrY78Lh-swtpDRDU
- url: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw
- token: ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI
- answer: HTTP/2 200 
server: nginx
date: Sun, 11 Apr 2021 03:34:04 GMT
content-type: application/json
content-length: 800
boulder-requester: 111215740
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 010304lxUfpifA1EgCi6O6ll-1q9ijlbrY78Lh-swtpDRDU
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "www.svor.wroclaw.pl"
  },
  "status": "pending",
  "expires": "2021-04-17T03:34:03Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw",
      "token": "ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/fvT1Wg",
      "token": "ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/p5Q5oQ",
      "token": "ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI"
    }
  ]
}

==[API call]==
exit status: 0

==[Step 5]==
- status: 200
- nonce: 0003C_cjZ6kRzz0rPgi0-VDzk-UeK1hdgSkXFPU3P_zi5hk
- validation: pending
- details: 
- answer: HTTP/2 200 
server: nginx
date: Sun, 11 Apr 2021 03:34:10 GMT
content-type: application/json
content-length: 186
boulder-requester: 111215740
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/12219897344>;rel="up"
location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw
replay-nonce: 0003C_cjZ6kRzz0rPgi0-VDzk-UeK1hdgSkXFPU3P_zi5hk
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw",
  "token": "ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI"
}

==[API call]==
exit status: 0

==[Step 5]==
- status: 200
- nonce: 0004D3iY8ikDEgSavq4z3jFqx7btbVHKiSS9vY1U3FlqKf4
- validation: pending
- details: 
- answer: HTTP/2 200 
server: nginx
date: Sun, 11 Apr 2021 03:34:15 GMT
content-type: application/json
content-length: 186
boulder-requester: 111215740
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/12219897344>;rel="up"
location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw
replay-nonce: 0004D3iY8ikDEgSavq4z3jFqx7btbVHKiSS9vY1U3FlqKf4
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw",
  "token": "ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI"
}

==[API call]==
exit status: 0

==[Step 5]==
- status: 200
- nonce: 0004RAKTwDm2DrO9ENsbh1Zy7Yu492pk_ZsEvm3XAZjtLqg
- validation: pending
- details: 
- answer: HTTP/2 200 
server: nginx
date: Sun, 11 Apr 2021 03:34:21 GMT
content-type: application/json
content-length: 186
boulder-requester: 111215740
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/12219897344>;rel="up"
location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw
replay-nonce: 0004RAKTwDm2DrO9ENsbh1Zy7Yu492pk_ZsEvm3XAZjtLqg
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw",
  "token": "ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI"
}

==[API call]==
exit status: 0

==[Step 5]==
- status: 200
- nonce: 0103S5B045cCPTeWms0I86IblQaPyYUyh9q0q8buG2N8pp8
- validation: pending
- details: 
- answer: HTTP/2 200 
server: nginx
date: Sun, 11 Apr 2021 03:34:30 GMT
content-type: application/json
content-length: 186
boulder-requester: 111215740
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/12219897344>;rel="up"
location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw
replay-nonce: 0103S5B045cCPTeWms0I86IblQaPyYUyh9q0q8buG2N8pp8
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12219897344/kXf_Nw",
  "token": "ktLsnk1EX1IIOJdd6N63Vs9zWP0DZ7nQUYEn3bAeaeI"
}

==[API call]==
exit status: 0

==[Step 5]==
- status: 400
- nonce: 0104VSPBbxEBXooK47WgY75FVGFKo-41_8Xoxj-SK7XpWME
- validation: 
- details: Unable to update challenge :: authorization must be pending
- answer: HTTP/2 400 
server: nginx
date: Sun, 11 Apr 2021 03:34:41 GMT
content-type: application/problem+json
content-length: 144
boulder-requester: 111215740
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0104VSPBbxEBXooK47WgY75FVGFKo-41_8Xoxj-SK7XpWME

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Unable to update challenge :: authorization must be pending",
  "status": 400
}

==[Abort Step 5]==
=> Wrong status

=======================================

To solve this problem I must delete SSL and create new one for domain.
Before update everything working very well.

**Comment by jaapmarcus** [comment]
Disable ipv6 and it should be working 

Also 

**Please do NOT use our GitHub Project for support requests, you can find community support and help here:**

**Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
**Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
**Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)

Also you might be able to disable ssl forward
