### ISSUE TITLE
[BUG] If "Local backup" is "No", then v-backup-user will also fail

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1737]
**Describe the bug**
If "Local backup" setting is "No", then v-backup-user will also fail. 

**To Reproduce**
1. Configure "Local backup" setting with "No"
2. Try to use v-backup-user or v-backup-users

**Expected behavior**
If I set "Local backup" to "No", I am just saying that I do not want hestiacp doing my backups. I have a custom backup script that use v-backup-user to create and send to my s3 service.

For me this setting must just remove the cronjob task.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.5

**Comment by franciscopaniskaseker** [comment]
As a workaround I tried to enable local backup setting and set zero in the website package.

Then the error is (when I try to use v-backup-user):
```bash
Error: user backup is disabled
```

**Comment by ghost** [comment]
Thanks for your report, we will improve the user interface and documentation regarding how the "local backup" switch and relevant cron job(s) work.
