### ISSUE TITLE
[BUG] Issue with restoring users additional FTP (problem 2)

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#1739]
**Describe the bug**
When restoring a user from one server to another, keeping the same username, the "Additional FTP" is restored with a double prefix. This is caused by having in the newly restored web.conf the whole ftp username (including the prefix).

The Path is also reset to public_html instead of the Path that was previously defined.

**To Reproduce**
What steps did you take when the issue occured? 
Check Web Section of impacted domain.

**Expected behavior**
No double prefix, Path should be correct.

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
1.3.5

**Comment by jaapmarcus** [comment]
Related problem:
https://github.com/hestiacp/hestiacp/issues/1723

**Comment by jaapmarcus** [comment]
Fix
