### ISSUE TITLE
[BUG] Enabled PHP versions - 500 error

### ISSUE THREAD

**Issue by Barmunksu** [hestiacp/hestiacp#1740]
**Describe the bug**
fresh install, use multi-php

**To Reproduce**
Server → Configure → Web server, go to Enabled PHP versions и and uncheck all php versions,
except 7.4, after ~5 min i have got a 500 error, after refresh (f5) again 500 error.

`2021/04/12 08:11:32 [error] 1104#0: *75 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxxxx, server: _, request: "POST /edit/server/ HTTP/1.1", upstream: "fastcgi://unix:/var>`

**Operating system:**
core i3
ram 8gb
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.2

**Comment by Barmunksu** [comment]
> 2021/04/12 08:11:32 [error] 1104#0: *75 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxxxx, server: _, request: "POST /edit/server/ HTTP/1.1", upstream: "fastcgi://unix:/var>

**Comment by jaapmarcus** [comment]
We don't speak Russiian . Please use English

**Comment by Barmunksu** [comment]
> We don't speak Russiian . Please use English

done

**Comment by jaapmarcus** [comment]
Thanks, 

It is a know issue that it is slow and it won't suprise me on older systems the time taken to delete an all the php versions takes longer then 5 min 
https://github.com/hestiacp/hestiacp/blob/bb76f91b1dd62d32959e2afdd63a4a2b5af786ec/src/deb/nginx/nginx.conf#L41-L43

Only solution is rewrite the currenty "system" and convert it to an Ajax based system. And fire of each "task" async after each other.. 

Please try disabling on 1 version each time. If that doesn't work /usr/local/hestia/bin/v-delete-web-php x.x

Where x.x is the version. 

Also the last version should be Hestia 1.3.5

**Comment by Barmunksu** [comment]
> Only solution is rewrite the currenty "system" and convert it to an Ajax based system. And fire of each "task" async after each other..

a good alternative would be to use < select >, instead of < checkbox >?

**Comment by jaapmarcus** [comment]
We allow the use of multiple php versions at the same time. The issue is probally caused due to the older "age" server then a real issue.

Please try to run how long it takes to do 
v-delete-web-php 7.3 for example
