### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Winwarin** [hestiacp/hestiacp#1746]
**Describe the bug**
Hestia deletes file php-fpm pool www.conf when a user creates domain called "www" and then removes it.

**To Reproduce**
1. Create website domain called "www"
2. Delete it
3. Then file /etc/php/%default-version%/fpm/pool.d/www.conf also gets deleted by Hestia

**Expected behavior**
File www.conf should have never been deleted by Hestia by any chances.

**Operating system:**
Debian 10

**Hestia Control Panel version:**
Hestia 1.3.2

**Comment by jaapmarcus** [comment]
Fixed will get released with 1.4
