### ISSUE TITLE
Hestia keeps loggin me off

### ISSUE THREAD

**Issue by dudulima0312** [hestiacp/hestiacp#1749]
hi guys, i'm new here!

I have installed Hestia on a fresh Ubuntu 20.04 and I'm having a problem to keep logged to the CP.

sometimes it logout when I try to go to any other section, sometimes when I try to save any configuration, and sometimes after 2 or 3 minutes.

anyone have any idea about it?

thank you so much!

**Comment by jaapmarcus** [comment]
Please provide us with more information. 

We use Cookies for authentication / sessions.
