### ISSUE TITLE
[BUG] Import backup is failing due "permission denied" in domain data tar file

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1751]
**Describe the bug**
Trying to import a hestiacp backup and the process fail because the homedir can not be extracted due permission denied.

**To Reproduce**
What steps did you take when the issue occured? 
1. Create a backup (as root user)
```bash
v-backup-user testingbug
```
2. Import the backup (as root user)
```bash
cd /backup
root@mail:/backup# v-restore-user testingbug testingbug.2021-04-19_19-39-13.tar 

-- WEB --
2021-04-19 19:42:08 testing.com
tar (child): /backup/tmp.BPh1ylK7nZ/web/testing.com/domain_data.tar.zst: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
zstd: /*stdin*\: unexpected end of file 
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Can't unpack testing.com data tarball
```

I attached a simple backup that I created one user, added one testing domain and created the backup. It was zipped because github does not allow .tar.
[testingbug.2021-04-19_19-39-13.zip](https://github.com/hestiacp/hestiacp/files/6338032/testingbug.2021-04-19_19-39-13.zip)

The problem happen even if you delete the user before the restore procedure.

**Expected behavior**
Account being restored.

**Operating system:**
Updated Ubuntu 20.04.

**Hestia Control Panel version:**
1.3.5

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
What is the permission of /backup/ ?

**Comment by franciscopaniskaseker** [comment]
@jaapmarcus 700

**Comment by jaapmarcus** [comment]
chmod 755 should do the trick please confirm

**Comment by jaapmarcus** [comment]
```
root@dev:/# chmod 700 backup/

root@dev:/backup# v-delete-user test 
root@dev:/backup# v-restore-user test testingbug.2021-04-19_19-39-13.tar 
-- USER --
2021-04-19 22:31:15 test

-- WEB --
2021-04-19 22:31:16 testing.com
tar (child): /backup/tmp.XYys9DihDS/web/testing.com/domain_data.tar.zst: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
zstd: /*stdin*\: unexpected end of file 
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Can't unpack testing.com data tarball
root@dev:/backup# v-delete-user test
root@dev:/backup# v-restore-user test testingbug.2021-04-19_19-39-13.tar 
-- USER --
2021-04-19 22:32:18 test

-- WEB --
2021-04-19 22:32:18 testing.com
tar (child): /backup/tmp.yFCH1k7SuG/web/testing.com/domain_data.tar.zst: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
zstd: /*stdin*\: unexpected end of file 
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Can't unpack testing.com data tarball
root@dev:/backup# v-delete-user test 
root@dev:/backup# chmod 755 ../backup/ 
root@dev:/backup# v-restore-user test testingbug.2021-04-19_19-39-13.tar 
-- USER --
2021-04-19 22:32:43 test

-- WEB --
2021-04-19 22:32:43 testing.com

-- DNS --

-- MAIL --

-- DB --

-- CRON --
2021-04-19 22:32:45 0 cron jobs

-- USER FILES --
.....
root@dev:/backup# 
```

**Comment by franciscopaniskaseker** [comment]
755 fixed. 750 did not work. 

I do not think is a good idea to offer execute and read to others. I understand that backups does not has read permission for others, however is usual to the sysadmins extract backups there to recover something. Then it can be read by any user.

**Comment by jaapmarcus** [comment]
Files are extracted under the users permissions

https://github.com/hestiacp/hestiacp/blob/8d82541fdaf40b4f65b56ea2e5c963916eaa870b/bin/v-restore-user#L339-L342

**Comment by franciscopaniskaseker** [comment]
@jaapmarcus 

excellent. probably the /backup was created manually because the hestiacp setup did not create. I think just when some backup happen it will be checked and created if needed.
