### ISSUE TITLE
[FEATURE] Custom hooks after upgrade  of packages

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1757]
**Is your feature request related to a problem? Please describe.**
Any custom changes to the control panel files are lost after an update

**Describe the solution you'd like**
A post-install/update hook to run a custom script

**Comment by jaapmarcus** [comment]
Will get added in 1.4.6

**Comment by manuelserol** [comment]
That's great news!

**Comment by jaapmarcus** [comment]
https://github.com/jaapmarcus/hestia-hooks

For an example to Disable and then enable Demo mode... (demo.hestiacp.com)
