### ISSUE TITLE
[BUG] Gmail "send as" feature failing due wrong SSL under hestiacp domain

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1758]
**Describe the bug**
When I try to do a TLS authentication in Gmail tool, I get:
```
TLS Negotiation failed, the certificate doesn't match the host
```

The domain is installed with valid SSL les encrypt, but under Cloudflare with Full (not strict) proxy. However the mail. subdomain is not under proxy, so nothing to worry about Cloudflare.

**To Reproduce**
What steps did you take when the issue occured? 
1. Try to add on Gmail a new "send as" domain
2. Try to enter hestiacp e-mail credential details
3. Get the error

**Expected behavior**
The TLS auth happen without problem. I remember this problem already happened under vestacp sometimes. But I did not find in their forum and git the answer. This is the first time that I am seeing under hestiacp.

**Operating system:**
Updated Ubuntu 20.04

**Hestia Control Panel version:**
1.3.5

**Comment by franciscopaniskaseker** [comment]
I checked the file /usr/local/hestia/ssl/certificate.crt and the right subdomain was configured there. And the permissions are root:mail as expected. The domain is not expired, however it is a self-sgined domain.

**Comment by franciscopaniskaseker** [comment]
I tried to copy the lets encrypt ssl keys (valid) from 
```
/usr/local/hestia/data/users/[user]/ssl/
```

to

```
/usr/local/hestia/ssl
```

and after that I fixed the permissions and restarted hestia service. Did not work too.

**Comment by jaapmarcus** [comment]
> I checked the file /usr/local/hestia/ssl/certificate.crt and the right subdomain was configured there. And the permissions are root:mail as expected. The domain is not expired, however it is a self-sgined domain.

Request an LE domain.  Also make sure the hostname is correct

**Comment by jaapmarcus** [comment]
Just run v-add-letsencrypt-host

**Comment by jaapmarcus** [comment]
<img width="616" alt="Screenshot 2021-04-22 at 00 41 08" src="https://user-images.githubusercontent.com/9754650/115629919-7fd7a380-a303-11eb-83be-974f751d09d6.png">

Works fine. Make sure you have a valid SSL certificate for mail.domain.com and webmail.domain.com then follow the steps

**Comment by franciscopaniskaseker** [comment]
@jaapmarcus Executed your command to mail subdomain and now it is working.

We already had requested lets encrypt SSL to the domain (and I manually checked that is there, not expired and is signed by LE).

So why that happened?

**Comment by jaapmarcus** [comment]
I used the following settings:
<img width="522" alt="Screenshot 2021-04-22 at 00 45 55" src="https://user-images.githubusercontent.com/9754650/115630372-3471c500-a304-11eb-9b9e-df1d2f2c5396.png">

Please make sure proxy is disabled for mail.domain.com

**Comment by franciscopaniskaseker** [comment]
webmail. domain is not configured under DNS. I created the DNS record.  I am getting "ERR_TOO_MANY_REDIRECTS" when I try to access.

But besides that, I am trying to understand why hestiacp did not asked to the mail. subdomain the ssl from LE. It was done correctly for main domain.

I will test more. Thank you.

**Comment by jaapmarcus** [comment]
Hestia threats mail domain and web domain as 2 separate domains allowing installing a mail only server. 

2 many redirect try disable the proxy for webmail also.... 

For support please use 
https://forum.hestiacp.com

**Comment by franciscopaniskaseker** [comment]
Ok. I thought this is was a bug because vestacp does not has a event to fix the mail server cert.

thank you.
