### ISSUE TITLE
ports.conf file

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#176]
### Operating System (OS/VERSION):

Ubuntu 18.04

### HestiaCP Version:

Latest

### Installed Software (what you got with the installer):

Nginx, PHP-FPM

### Steps to Reproduce:

NA

### Related Issues/Forum Threads:

NA

### Other Notes:

What's the purpose of configuration file ports.conf? It seems that it has many ports, some of them irrelevant.  I wasn't able to find an actual usage of this file.

**Comment by ScIT-Raphael** [comment]
Well, to be honest: It looks like it will not be used anymore. It was loaded in v-update-firewall to a variable but never used. I removed the file form installer folders and also the variable load from v-update-firewall in the following commit: https://github.com/hestiacp/hestiacp/commit/c134835f12b00305e24431e767deb49f1ad3903e
