### ISSUE TITLE
[BUG] Users can still add FTP users, when FTP subsystem is not installed. 

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1761]
**Describe the bug**
I choose not to install the FTP subsystem for a number of reasons. I'll sometimes field a comment from a user who is complaining that "They added an FTP user but the password is not working" 

**Expected behavior**
I think the "Add FTP user" section of the domain control page should be disabled if the FTP subsystem is not defined in hestia/conf/hestia.conf

Alternatively it should produce some sort of error if you try to add a user, telling the user that they're wasting their time. 

Maybe this is a FEATURE rather than a bug

**Comment by jaapmarcus** [comment]
We discovered yesterday the same issue.
 

We will fix it

**Comment by ghost** [comment]
Fixed in v1.4.

**Comment by fedekrum** [comment]
Is it fixed only at the interface or will v-add-web-domain-ftp give an error in case there is no FTP service installed?

**Comment by jaapmarcus** [comment]
It is only a change on UI level.
