### ISSUE TITLE
[BUG] Double dot TLD domain NGINX config file deleted after adding identical single dot TLD domain

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1763]
**Describe the bug**
When having a domain with TLD .com.au like domain.com.au if I add a new domain with the exact same name but with TLD .com like domain.com the folder /home/user/conf/web/domain.com.au/ disapears and when visiting the website it goes to the default success welcome page of the web server. The same happen when suspending or re-enabling the domain.com

**To Reproduce**
root@srv:/# /sbin/service nginx configtest
nginx: [emerg] open() "/etc/nginx/conf.d/domains/domain.com.au.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:149
nginx: configuration file /etc/nginx/nginx.conf test failed
I have a symlink in /etc/nginx/conf.d/domains/domain.com.au.conf pointing to /home/user/conf/web/domain.com.au/nginx.conf
however I do not have the folder /home/user/conf/web/domain.com.au/
just have the folder /home/user/conf/web/domain.com/
after suspending the domain.com.au
and then re-enable it
I get the folder /home/user/conf/web/domain.com.au/ with its nginx.conf file
and the website goes back to normal
after I suspend the domain.com
and re-enable it
the folder /home/user/conf/web/domain.com.au/
disappears again
and I get the default welcome page again
then I suspend the domain.com.au and re-enable it and comes back to normal
I did this a few times
and I can tell the issue is on suspend not on re-enable
because as soon as I suspend the domain.com the .com.au folder is wiped
and as soon as I suspend the com.au the folder comes back again
also if I suspend the .com the folder for .com.au disapears
then I suspend the .com.au and the folder appears
with both suspended
If I enable the .com
the folder for .com.au disappears again
so anything I do with .com will wipe the .com.au folder

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.3.5

**Comment by jaapmarcus** [comment]
Please try to use a better title that explains the issue bette.

**Comment by manuelserol** [comment]
Sorry, I forgot to fill that. Fixed!

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/96817a9eb7fb74e1a38645ee90c0108611c9d538/func/domain.sh#L291-L292

change rm -rf to rm -f 
Fixed for 1.4
