### ISSUE TITLE
[BUG] User access to domain listing without permissions in package

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1764]
**Describe the bug**
If I setup a package with zero domains and zero aliases when the user with that package logins it goes straight to the domains listing page and can click on button add web domain but is not possible to add because then gets the message saying the limit was reached

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.3.5
![bug](https://user-images.githubusercontent.com/23358751/116227267-dbfb5700-a74b-11eb-9b37-0212414bd0ab.png)

**Comment by jaapmarcus** [comment]
Issue will be fixed with the new release.  I a dev version this behavoir is all ready changed

**Comment by manuelserol** [comment]
The add web domain button is not visible when loggin in directly with user account. It just shows up when loging in from admin account

**Comment by jaapmarcus** [comment]
We have rewritten al lot of the web GUI in the last weeks. 

v-update-sys-hestia-git hestiacp main install on a test server (With Hestia installed)
