### ISSUE TITLE
[BUG] Web alias limit not working

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1767]
**Describe the bug**
When setting a limit for web aliases in a package the user using that package can still add more aliases than the limit.

Also when setting an alias limit in a package that limit is multiplied by the number of web domains limit of the same package.

Example: A package with limit of 2 web domains and 2 web aliases will show to the user a limit of two web domains and 4 web aliases

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.3.5

**Comment by jaapmarcus** [comment]
The Aliases are per domain so it 1 domain can add max 2 aliases

**Comment by manuelserol** [comment]
If that is a feature so there are two limits not being limited. The total aliases limit and the aliases limit per domain

**Comment by jaapmarcus** [comment]
<img width="480" alt="Screenshot 2021-04-28 at 19 10 03" src="https://user-images.githubusercontent.com/9754650/116444780-611e6300-a855-11eb-8d8c-e2db15f0a7f9.png">

Even then it works not as it should be

**Comment by manuelserol** [comment]
I did not have problems saving and did not get any error message as you shown. 
![Capture](https://user-images.githubusercontent.com/23358751/116445103-65468280-a84d-11eb-9677-d014835f303f.PNG)

**Comment by jaapmarcus** [comment]
Fixed issue https://github.com/hestiacp/hestiacp/pull/1768
