### ISSUE TITLE
CentOS 7

### ISSUE THREAD

**Issue by cdnmall** [hestiacp/hestiacp#177]
Any plans to support CentOS 7?

**Comment by ScIT-Raphael** [comment]
Until now, there is no CentOS support planed. Maybe you could checkout Debian or Ubuntu? From a personal view I would say both are faster than CentOS.

**Comment by iNilo** [comment]
> From a personal view I would say both are faster than CentOS.

I'm interested in this claim, do you have any resources on this?

**Comment by ScIT-Raphael** [comment]
I think it's written in my thread: Personal view is the source :).

**Comment by iNilo** [comment]
Oh I see! nvm,
I was looking for a possible performance comparison.

Thanks a bunch!
