### ISSUE TITLE
[BUG] Email account list disk space sorting broken

### ISSUE THREAD

**Issue by ffgriever-pl** [hestiacp/hestiacp#1771]
**Describe the bug**
Sorting by disk space on email account list doesn't work properly.
- Choosing to sort in ascending order doesn't work at all (no change on the list).
- Choosing to sort in descending order (default) simply reverses current sorting method (so if the list is currently sorted in descending order by account name, it will be sorted in ascending order by account name, etc.).

**To Reproduce**
1. Go to mail tab.
2. Choose mail accounts.
3. Try changing the sorting method to "disk".

**Expected behavior**
Actual sorting by disk space used by the account.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.5

**Additional info**
The same behavior on two servers, both Ubuntu 20.04 LTS, though.

**Comment by ScIT-Raphael** [comment]
The sort function has already been reworked in 1.4 (main branch). Could you spin up a test machine (v1.3.5) and upgrade to the current main branch -> https://docs.hestiacp.com/cli_commands/commands.html#v-update-sys-hestia-git

Then please check if the issue is persistent and report back :).

**Comment by ffgriever-pl** [comment]
Yes. In case of head of main it works. There is a tiny issue though. For disk usage and quota, the ascending and descending is reversed (when choosing ascending, it starts with the highest usage/quota accounts instead of the lowest). But that's another issue. I'm closing this one ;)
