### ISSUE TITLE
[Feature Request] Allow Additional FTP accounts over SFTP

### ISSUE THREAD

**Issue by archergod** [hestiacp/hestiacp#1774]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
My Client do not prefer to have FTP software on their server. But they often need FTP access for other team members. So we do not install FTP while installing, but when we use Additioanl FTP feature, those FTP do not work for obvious reason. So, if not FTP is detected, that feature is either disable or alterantaive give option to create SFTP (SSH) login. 

**Describe alternatives you've considered**
We currently manually create SSH login and jail them etc to be used as sFTP for alternative. it is not a security concern as we use this for closed group. 

**Additional context**
N/A

**Comment by jaapmarcus** [comment]
We have discussed this feature in the past and I agree it will become soon a "requirement" to allow sftp login on "Additional FTP accounts" It should be possible to create a similar security as the FTP login.

**Comment by archergod** [comment]
I am not sure if making it requirement is good option, considering that lot of small companies still do not fully understand the SFTP. Though I agree it is more secure for server and one less "server" software to free up more RAM on server. 

But I am happy either way,

**Comment by jaapmarcus** [comment]
The "Requirement" as an way to stay "Hestia" competitive with other CP that currently support it maybe. Not in the sense that FTP will get removed for any reason. To many users still depend on it.. 

FTP will always remain an option off course.. 

SFTP is almost never used due to users are scared that open port 22 / or any other port as they are afraid getting hacked..

**Comment by jlguerrerosanz** [comment]
I personally only give sftp credentials to my clients. I say:

- server: w01.mydomain.com
- port: 22200
- protocol: SFTP
- user: your-user
- pass: your-pass!
I have no problem at all

**Comment by jaapmarcus** [comment]
I do agree but sometime you don't want to give somebody full access to the system but only to the uploads folder that is only possible with "Additional FTP accounts"

**Comment by archergod** [comment]
> I personally only give sftp credentials to my clients. I say:
> 
> * server: w01.mydomain.com
> * port: 22200
> * protocol: SFTP
> * user: your-user
> * pass: your-pass!
>   I have no problem at all

To give that information you currently have to create SSH account from command line. Yes we can give main user login, but we have 10+ website on single account and we don't want to give access to all to new member, we want him to get access for single domain only. Additional FTP is for that purpose. 

It is also a Good Extension to make Additional FTP (current or future SFTP) to able to access more than one Domain at least from same user.

**Comment by jaapmarcus** [comment]
Feature has been implemented
