### ISSUE TITLE
[FEATURE] check nginx before requesting for a letsencrypt certificate

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1779]
Sometimes we get the 400 error upon requesting a LE certificate. 

Frequently it is because a problem with the nginx configuration.

We could run nginx -t to check if it will work before we try with LE.

**Comment by jaapmarcus** [comment]
We should probably extend it to all restarts of nginx...

**Comment by jlguerrerosanz** [comment]
We could keep it simple for now, I think this should be an easy fix.

I have also another two suggestions regarding the LE process debug.

- in case of error, tell the user where is the error log or even output the error in the panel
- or have a script parse the error log and extract the critical information including the acme link (https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxxxxx/UniqueID) and display it or even parse it and return the final answer.

**Comment by jlguerrerosanz** [comment]
Any thoughts on this?

**Comment by jaapmarcus** [comment]
Check just before $BIN/v-restart-service $PROXY_SYSTEM  / WEB_SYSTEM is easier as it only 2 locations that need to be changed and it will cause all other reasons why an nginx / apache2 reload will fail. 

https://github.com/hestiacp/hestiacp/pull/1795

Haven't changed the behaviour of LE check script yet as that is an different issue that need improved

**Comment by jlguerrerosanz** [comment]
Great news! Thank you for your efforts.

**Comment by jaapmarcus** [comment]
Implemented please create a new issue for improving the error message
