### ISSUE TITLE
Proxmox LXC Ubuntu 18.04 Container DNS lookups Fail (Fixed by disabling iptables)

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#178]
In 4 instances of spinning up ubuntu 18.04 LXC containers in proxmox, after the install hestiacp default options. I am not able to resolve names to IP (DNS) Although disabling iptables corrects the issue. I was able to replicate the issue 4 times not sure whats causing this. Ill try with debian 9 LXC tmrw. Im sure KVM VM will not be affected but I will try that as well.

**Comment by johnnyq** [comment]
I may have found the fix. I spun up another Ubuntu 18.04 LXC Container. When you click new LXC container uncheck Unpriviledged container. I'm not sure why this fixes the problem with iptables but ill investigate further in the afternoon.

**Comment by johnnyq** [comment]
Proxmox 5.3 recently switched to Unpriviledged containers as a default option when LXCs are created. This has happened recently with an update from proxmox. Fresh install of proxmox 5.3 doesn't give that option and by default uses priviledged containers. I believe the problem is with proxmox. but it wouldn't hurt to have known issues and quick fixes added to the hestiaCP readme. Especially for people using proxmox and its LXC containers.

**Comment by ioannidesalex** [comment]
Can you confirm thst with a priviledged container the issue does not exist?

**Comment by johnnyq** [comment]
Yes with priviledged containers the problem does not exist

**Comment by ScIT-Raphael** [comment]
Just checked up this issue and can confirm it also: As soon as "Unprivileged Container" is set, the dns communication stops. After disable iptables, the dns communication will work again:
```
iptables-save > /root/firewall.txt
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
```
We will search the issue and work on a fix.

**Comment by ScIT-Raphael** [comment]
Small update: I checked it now double and can't confirm, that the checkbox "Unprivileged Container" does change anything - as soon as the installation is done, dns stops working on proxmox systems.

**Comment by ScIT-Raphael** [comment]
Bug is now fixed on beta branch: https://github.com/hestiacp/hestiacp/commit/21a310bbd63cbb800c195f4981cfe844478361aa

Source: https://bitbucket.org/lowendguide/scripts/src/06cc2250855ebfe7798790ab4a70898e41bfa816/VestaCP%20firewall%20custom%20script/custom.sh?at=master&fileviewer=file-view-default

If you want to recover the communication before a new release, place the file above under /usr/local/hestia/data/firewall/custom.sh and reboot the server.

Please feel free to reopen the issue, if there is anything that not work properly.

**Comment by ScIT-Raphael** [comment]
found the source issue and fixed it with the following commit: https://github.com/hestiacp/hestiacp/commit/ad75b429d8274f064e0b4f2263598453be0b36e9

If you want to fix a running system, you need to download the actual beta v-update-firewall and run it once.
