### ISSUE TITLE
[BUG] SSH key is not getting deleted.

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1784]
**To Reproduce**
go to Edit User
then 'Manage SSH keys'
then when i try to delete the keys it's not working.

**Expected behavior**
should delete the SSH Key from the user profile

**Screenshots**
![image](https://user-images.githubusercontent.com/39749258/116923208-f9f91800-ac73-11eb-9022-6e6da4a9a9f7.png)

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
v1.3.5

**Comment by jaapmarcus** [comment]
This issue should have been fixed with 
https://github.com/hestiacp/hestiacp/pull/1773
