### ISSUE TITLE
[BUG] Not able to SSH into Server

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1785]
**To Reproduce**
go to Edit User
then 'Manage SSH keys'
then add a new SSH Key 
![image](https://user-images.githubusercontent.com/39749258/116923689-8efc1100-ac74-11eb-954c-aec126cd275b.png)

when you try to SSH into Server then you'll get this error 
![image](https://user-images.githubusercontent.com/39749258/116923751-a1764a80-ac74-11eb-8f33-e9e499ac1fdd.png)

**Expected behavior**
should be able to SSH into User Account. 

**Screenshots**

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.5

**Additional context** 

SSH Access is set to Bash
![image](https://user-images.githubusercontent.com/39749258/116923869-ca96db00-ac74-11eb-9a7f-c9d2f893996e.png)

**Comment by jaapmarcus** [comment]
Please check your log files...

With out any informations we can't really do any thing

**Comment by jaapmarcus** [comment]
https://www.edureka.co/community/82632/remote-side-unexpectedly-closed-network-connection

Doesn't look like an issue with SSH keys. Try to login with username / password

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/116934578-c671ba00-ac82-11eb-993e-48f494547f79.png)

i use to log in via `username@hostname` with the ppk file and it use to work fine, since i've updated to v1.3.5 i'm facing this issue.

**Comment by jaapmarcus** [comment]
Please check your log files... We haven't change anything related ssh / login via ssh keys..  We are not able to solve the issues on your server via remote access. I can't debug your servers and there are 10k servers running without any issues.

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/116936070-e86c3c00-ac84-11eb-9bcc-6d53d14a1f97.png)

`grep 'sshd' /var/log/auth.log`

fatal: bad ownership or modes for chroot directory

**Comment by jaapmarcus** [comment]
When bash is enabled chroot should be disabled. 

chown /home/hyperzod folder to root:root or run the command:

https://docs.hestiacp.com/cli_commands/commands.html#v-delete-user-sftp-jail

**Comment by alber-khan** [comment]
`v-delete-user-sftp-jail` works!
