### ISSUE TITLE
[FEATURE] Exclude backup email accounts via wildcard

### ISSUE THREAD

**Issue by asessa** [hestiacp/hestiacp#1788]
**Is your feature request related to a problem? Please describe.**
User backup files can include a huge amount of emails, this means doubling the space used locally to backup the emails and time to complete a remote backup.
Considering the email system is file based (mbox) and hestiacp needs only the configuration files to restore a mail backup, the email account data can be backed up via other methods (rsync/rclone) and manually restored if/when needed.

**Describe the solution you'd like**
The backup system supports an exclude list, the exclusion is current possible per domain (\* for all domains) or per account (domain:account1:account2).
The proposed solution is to support wildcards also for accounts (domain:\*) or partials (domain:account\*), and manage in other ways the backup/restore of user account data.

**Comment by jaapmarcus** [comment]
The "system" isn't really flexible to allow wildcards in between domain:* or domain:accout* Don't know how easy it is improved.


And backup function that only back ups the config files is useful..

See https://forum.hestiacp.com/t/email-migration-strategy/3423/12

**Comment by asessa** [comment]
Yes, i've just forked and checked the code, `domain:*` should be possible by extending the grep on https://github.com/hestiacp/hestiacp/blob/main/bin/v-backup-user#L393 to

```
exclusion=$(echo "$exclusion" |tr ':' '\n' |grep -E "^$account|\*")
```
Tested directly on shell:
```
grep MAIL backup-excludes.conf | tr ',' '\n' | grep 'domain.ext:' | tr ':' '\n' | grep -E "^info$|\*"
```

I'm available to submit a PR with this change

**Comment by jaapmarcus** [comment]
Please go ahead

**Comment by asessa** [comment]
just a quick update on this, I've been testing it during the last 2 weeks, I did the same change on production servers (both on vesta and hestia) with around 150 clients, did also a server migration, everything works fine

**Comment by jaapmarcus** [comment]
Merged
