### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by sancu89** [hestiacp/hestiacp#1789]
quiero saber porque al ingresar el ip con puerto no puedo ingresar a la pagina?? y como restauro mi key y src??

**Please do NOT use our GitHub Project for support requests, you can find community support and help here:**

**Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
**Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
**Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)

**Comment by jaapmarcus** [comment]
Please use the follow support methods:
Documentation: docs.hestiacp.com
Forums: forum.hestiacp.com
Discord: Join the discussion
