### ISSUE TITLE
Option to remove packages before install

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#179]
I noticed when trying to install hestiacp, if i have postfix or ufw installled. Hestia wants you to remove the packages before continuing, It would be nice to have a switch to remove unnecessary packages before install. If the switch is not used then ask in order to continue these packages must be removed Would you like to remove them Y/n Maybe something to that nature

**Comment by ioannidesalex** [comment]
Thanks for the suggestion. The team will discuss it internally and let you know.

**Comment by ScIT-Raphael** [comment]
Is now implemented for both installer with the following commit: https://github.com/hestiacp/hestiacp/commit/86ac9525fa70067f966fcb2b9529674e4c10daf9

Again thanks for your feedback, we hope you will like it :)!
