### ISSUE TITLE
[BUG] Overflow issues in WebUI 

### ISSUE THREAD

**Issue by EmrahKayihan** [hestiacp/hestiacp#1791]
**Describe the bug**
WebUI has an overflow issue as shown in the screenshot. (Turkish language is used in WebUI.)

**Screenshot**
![tempsnip](https://user-images.githubusercontent.com/30529651/117210187-07dba400-ae00-11eb-84bd-a34ecbdff8e6.png)

**Operating system:**
Ubuntu 20.04.2 LTS

**Hestia Control Panel version:**
 v1.4.0~beta

**Comment by jaapmarcus** [comment]
We  have removed the sort function changed the with of the "Select" box so the update could be added again. In the future we might need work an better layout...

**Comment by EmrahKayihan** [comment]
It would be logical to pass on a design built on bootstrap in the future.

**Comment by jaapmarcus** [comment]
We agree
