### ISSUE TITLE
[BUG]Email Addresses Deleted with Forward enabled - Do not Delete

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1796]
**Describe the bug**
Today I deleted an email that had a forward to set to another email with the discard all forwarded email ticked. When I deleted that email I sent a test to see if I got a bounce back, I did not.

I did an ls in /home/user/mail/domain.ext/ and didnt see the user in there

Then I checked /home/user/conf/mail/domain.ext/
I seen a file called fwd_only

I spotted the user still in there

The permissions (see below) to the file seem correct, not sure why it didn't delete the user from there, but maybe its something in the delete mail user script.

`-rw-rw----  1 Debian-exim mail     6 Mar 19 01:08 fwd_only`

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Click Mail
2. Click Add mail Account
3. Fill in the email and password under forward_to put an email in there choose discard all forwarded mail
4. Delete the email
5. Send an email to the deleted email

**Expected behavior**
Email is fully deleted

**Operating system:**
Ubuntu 20.04.2

**Hestia Control Panel version:**
1.3.5

**Comment by jaapmarcus** [comment]
Can confirm the issue:

```
2021-05-12 11:27:21 1lgl9F-0007Gj-9o <= jaap@xxxxxxx H=mail-ej1-f44.xxxx [xxxxx] P=esmtps X=TLS1.3:ECDHE_RSA_AES_128_GCM_SHA256:128 CV=no SNI="xxxxx" K S=2509 id=CAKCf741pY2K+52JMi50eHbQxSRhPFkNH=u1a3tZyOqQz4tqBfgxxxxxxx
2021-05-12 11:27:21 1lgl9F-0007Gj-9o => info <info@xxxxx> R=localuser_fwd_only T=devnull
```

**Comment by johnnyq** [comment]
@jaapmarcus Excellent! that should do it.
