### ISSUE TITLE
v-add-database-host

### ISSUE THREAD

**Issue by ntkonsultant** [hestiacp/hestiacp#1797]
Hello,

Server Debian 10 / Hestiacp latest stable.

Sorry for my bad english

But this append on all my server (4) all debian 10 and Hestiacp latest.

**Describe the bug**
When using : 
v-add-database-host 

v-add-database-host mysql 10.0.0.XX XXXXX XXXXXXXXXXXX

The password is not completely filled in 
vim /usr/local/hestia/conf/mysql.conf
Just the 5 ou 6 first characters are filled.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**

**Expected behavior**
Filling the pwd in conf file.

**Screenshots**

**Operating system:**
Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Hestia Control Panel version:**
1.3.5

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
Use "password" when it contains special chars or escape them when it contains \
