### ISSUE TITLE
[BUG] Unable to change backend template when username = domain

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1799]
**Describe the bug**
When a user has the same name as the domain name  you are not able to change the change the template
**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Add user jaap.nl
2. Create web domain jaap.nl
3. Change backend to PHP-8_0 for example

**Expected behavior**
Change the reflected config file as set via template...

**Screenshots**

**Operating system:**
Debian 10 / Ubuntu 20.04

**Hestia Control Panel version:**
1.3.5 and 1.4

**Additional context**
root@dev:~# v-change-web-domain-backend-tpl jaap.nl jaap.nl PHP-8_0
/usr/local/hestia/bin/v-change-web-domain-backend-tpl: line 97: shell_list: command not found

Issue is in:

https://github.com/hestiacp/hestiacp/blob/3d60e15dd8381a2d3d708d4f93faa3de07adb979/bin/v-change-web-domain-backend-tpl#L86-L127

**Comment by sdelfi** [comment]
The same problem.

I added the following code to  /usr/local/hestia/bin/v-change-web-domain-backend-tpl as a quick fix:
```
# Shell listing function
shell_list() {
    if [ -z "$nohead" ] ; then
        echo "${fields//$/}"
        for a in $fields; do
            echo -e "------ \c"
        done
        echo
    fi
    while read line ; do
        eval $line
        for field in $fields; do
            eval value=$field
            if [ -z "$value" ]; then
                value='NULL'
            fi
            echo -n "$value "
        done
        echo
    done < $conf
}
```

It works for me, but I'm not sure that is correct function code

**Comment by jaapmarcus** [comment]
There is a check for https://github.com/hestiacp/hestiacp/blob/cb0f85da5a129aafc02ea6a37ab055c785417f9b/func/domain.sh#L106-L116 for an backend pool.  Probably an old Vesta Feature that is not used a lot... 

A extra check should be enough I think

`if [ "$backend_type" = "$user" && $WEB_BACKEND_POOL = 'user' ]; then`

**Comment by jaapmarcus** [comment]
And works
