### ISSUE TITLE
Feature Request: Hide unavailable services in the Web control Panel

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#180]
For example if DNS and mail are not chosen for install in the beginning. Then hide their web control panel counterparts,  or if you wanted to use hestiacp just for DNS Only, then only show the DNS portion in web panel.

**Comment by ghost** [comment]
This is a great suggestion @johnnyq. I know that there is a re-write of the interface planned but no ETA as of yet; that said I will look at possibly implementing this with the current user interface for the time being.

**Comment by ghost** [comment]
@johnnyq,

I wanted to get your feedback on a feature that is related to this -- what are your thoughts on the ability to add or remove the individual server roles after installation? For example say on a scale of 1 to 5, with 1 being "not important at all" and 5 being "it would be very useful" where would you place the importance of such a feature?

Thanks again :)

**Comment by johnnyq** [comment]
Absolutely 5 @kristankenney! that sounds like a terrific idea!! Thanks to you and all the developers of Hestia, its been a pleasant developing/bug reporting/ feature request experience!

**Comment by ghost** [comment]
![Good news](https://user-images.githubusercontent.com/40798553/54889074-5e383380-4e81-11e9-9654-1e9529cbe7a8.jpg)

**Comment by johnnyq** [comment]
A great feature accompanied by a nice meme I love it Thanks @kristankenney
