### ISSUE TITLE
[BUG]unable to create backup

### ISSUE THREAD

**Issue by maxshop** [hestiacp/hestiacp#1802]
**Describe the bug**
i wanted to make a backup 3 days ago but until now not finished, i want again triing to create but show this daialog "An existing backup is already running. Please wait for that backup to finish." 

**To Reproduce**
What steps did you take when the issue occured? 
1. Ex.: Click on the "backups" tab.
2. Ex.: Click on "create backup".

**Operating system:**
Ubuntu 20.04 (x86_64)

**Hestia Control Panel version:**
v1.3.5

**Comment by ScIT-Raphael** [comment]
This sounds more like a support case, please switch over to our forum or discord channel.
