### ISSUE TITLE
[FEATURE] Improve error message Lets Encrypt 

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1804]
**Is your feature request related to a problem? Please describe.**
Current error message in Hestia is worth less. Users are required to check log files an if it is not an sys admin. They don't have the correct access rights to see them

**Describe the solution you'd like**
Current message is something like:
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Unable to update challenge :: authorization must be pending",
  "status": 400

How ever if you follow in "step" for 
{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12520447717/scDRXA",
  "token": "9yriok5bpLtV__m-rZ8f2tQmrfeQli0tCxSj4iNkv2Y"
}

You would normally see an error message where an Ip is unable to resolve and so on. This error has more meaning then the first one. 

**Describe alternatives you've considered**

**Additional context**
There are no alternatives except give every user the knowlegde to how to debug.

**Comment by jlguerrerosanz** [comment]
What we could do:

1) parse the output of: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12520447717/scDRXA" and show it to the user
2) Tell the user to visit: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12520447717/scDRXA", for more info
3) show the content of the LE-XXXX-XXXX.log logfile
4) show the path to the LE-XXXX-XXXX.log logfile

**Comment by jaapmarcus** [comment]
4 is no option as non admin users don’t have access 
3. Have seen to many users unable to read the logs so it will still have the issues
2. If we go trough the issue finding this link 1 should be more use full alternative we can show the link if the detection fails
