### ISSUE TITLE
[BUG] bulk deleting the domains from WEB doesn't remove .sock

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1809]
**Describe the bug**
when you delete multiple domains from "WEB" it doesn't delete .sock files from '/run/php' directory 

**To Reproduce**
What steps did you take when the issue occured? 
1. Click on the "Web" tab.
2.  Select all Domain.
3. Bulk Delete

**Expected behavior**
should delete .sock files from '/run/php' directory 

**Screenshots**
![image](https://user-images.githubusercontent.com/39749258/118454835-70872280-b716-11eb-8ed4-1322a998202d.png)
![image](https://user-images.githubusercontent.com/39749258/118455131-9f04fd80-b716-11eb-8782-7c64d50b01e8.png)

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.3.5

**Comment by jaapmarcus** [comment]
Issue is caused due to the fact v-restart-web-backend has't been called
