### ISSUE TITLE
[FEATURE] Why hestiacp still use the old mpm prefork?

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#1812]
This request has been asked multiple times and neglected everytime since 2015 in vestacp forum. And since last year in hestiacp repo here #839.

But still in the most recent version of hestiacp (1.3.5 ). The PHP handler is still using mpm prefork. You can check it after installing latest hestia using:
apachectl -V

Is there any reason vestacp and now hestiacp still insist using this very old php handler?

**Comment by jaapmarcus** [comment]
We use mpm event by default unless you install mod php

**Comment by ScIT-Raphael** [comment]
I'll close this issue, because @jaapmarcus already pointed out, that we are using event by default since a longer time. The only way you could still stick to mod_php is to disable php-fpm during installation - set it to no in install string.

**Comment by jaapmarcus** [comment]
Manual upgrade form modphp to php-fpm 
https://github.com/hestiacp/hestiacp/blob/main/install/upgrade/manual/migrate_apache.sh

And then  to convert mpm_prefork to mpm_event
https://github.com/hestiacp/hestiacp/blob/main/install/upgrade/manual/migrate_mpm_event.sh
