### ISSUE TITLE
[FEATURE] Please add option to exclude filemanager in installation script

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#1814]
Hi is it possible to add an option in installation script to exclude filemanager. Like shown in this docs:
https://docs.hestiacp.com/getting_started.html#all-available-options-of-install-script

Some developer may want as lean system as possible to minimize the bug and security issue because of too many features.

**Comment by jaapmarcus** [comment]
You can remove Filemanger in the settings or with the command 
v-delete-sys-filemanager 

It will remove the filemanger fully. 

In the future we will consider it to add the option in the future...

**Comment by jaapmarcus** [comment]
As told it can be done via command line after installations
