### ISSUE TITLE
Multi PHP on new debain 10 install[BUG]

### ISSUE THREAD

**Issue by liamgibbins** [hestiacp/hestiacp#1815]
**Describe the bug**
I did my yearly reinstall and did the usual standard install with multi-php, During installation this message comes up

[ * ] Configuring system settings...
[ * ] Configuring Hestia Control Panel...
[ * ] Generating default self-signed SSL certificate...
[ * ] Adding SSL certificate to Hestia Control Panel...
[ * ] Configuring NGINX...
[ * ] Configuring Apache Web Server...
cp: cannot stat '/etc/php/5.6/': No such file or directory
[ * ] Install PHP version 5.6...
cp: cannot stat '/etc/php/7.0/': No such file or directory
[ * ] Install PHP version 7.0...
cp: cannot stat '/etc/php/7.1/': No such file or directory
[ * ] Install PHP version 7.1...
cp: cannot stat '/etc/php/7.2/': No such file or directory
[ * ] Install PHP version 7.2...
cp: cannot stat '/etc/php/7.3/': No such file or directory
[ * ] Install PHP version 7.3...
[ * ] Install PHP version 7.4...
cp: cannot stat '/etc/php/8.0/': No such file or directory
[ * ] Install PHP version 8.0...
[ * ] Configuring PHP-FPM...
[ * ] Configuring PHP...

**To Reproduce**
install on debain 10 with the following command bash hst-install.sh -f -y no  -o yes -e email@domain.tld -p p4ssw0rd -s hostname.domain.tld
and it does the same every time.

**Expected behavior**
A clean install no errors

**Operating system:**
Debain 10 

**Hestia Control Panel version:**
v1.3.5 when following the instructions in the documentation page

**Additional context**
not really except that after install when you reboot you have to manually start services but thats an old issue when installing on debain 10.

**Comment by jaapmarcus** [comment]
Known issue it will be fixed in the next  release it is caused that the backup of /etc/php/x.x is created but the folder doesn't exists yet.

**Comment by jaapmarcus** [comment]
Manully starting services after an reboot should never happen. I have never seen an issue before with Debian 10

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/3d60e15dd8381a2d3d708d4f93faa3de07adb979/install/hst-install-debian.sh#L1242-L1249

Bug is still there should be easy to fix

**Comment by jaapmarcus** [comment]
Never mind it has been fixed in the release branch 

https://github.com/hestiacp/hestiacp/blob/47cf4a076776c225d686b08c7aab94234d76c535/install/hst-install-debian.sh#L1325-L1331

**Comment by liamgibbins** [comment]
> Manully starting services after an reboot should never happen. I have never seen an issue before with Debian 10

it doesnt happen all the time, just now and then.
I have reported it before several times.

**Comment by jaapmarcus** [comment]
You mean: https://github.com/hestiacp/hestiacp/issues/1354
For support question please use our support forum. Github is only used to track bugs and so on.
