### ISSUE TITLE
[BUG] when restoring from backup file, file manager doesnt work

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#1816]
when restoring from backup file, file manager doesnt work. showing 'Unknown error'

I try every single steps mentioned here, still doesnt work:
https://docs.hestiacp.com/admin_docs/filemanager.html
https://forum.hestiacp.com/t/file-manager-unknown-error-error-500/1221

Then after spent hours, I finally found the cause:
Its because when restoring the user_dir, especially '.ssh' folder. 
The '.ssh' folder permission changed to '700'. It should be '755'

**Comment by jaapmarcus** [comment]
Did an backup and then a restore. The permission of the folder is still 755 as it should be. How ever hst-filemanager-key has user:user permission and it should be admin:admin

-rw-r--r--   1 jaap  jaap   297 May 18 23:59 authorized_keys
-rw-------   1 jaap jaap 1.1K  May 18 23:59 hst-filemanager-key

-rw-r--r--   1 jaap  jaap   297 May 18 23:59 authorized_keys
-rw-------   1 admin admin 1.1K May 18 23:59 hst-filemanager-key

**Comment by jaapmarcus** [comment]
Issue should be fixed in 1.4.2
