### ISSUE TITLE
[FEATURE] - Interface to provide multiple URLs as sources for a single ipset

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1821]
The actual web interface only allows one source for an Ipset

I would like to have a textarea field to add several url's (one per line) and them feed ipset with that.

**Comment by jaapmarcus** [comment]
Discused in the past https://github.com/hestiacp/hestiacp/issues/1550

See https://forum.hestiacp.com/t/create-ipset-from-multiple-files/3518/2 for an working example

**Comment by jlguerrerosanz** [comment]
Lol I forgot that!
