### ISSUE TITLE
[Bug] Include extra config in backups

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1834]
**Is your feature request related to a problem? Please describe.**
Kind of. Sometimes we need to add extra nginx configurations, but if we manually change the files, hestia can overwrite on some moment. Then we have to create a specific nginx template to some domain. One example of extra configuration: CORS policy.

**Describe the solution you'd like**
Like the option to have a custom root folder, a textarea form to add new nginx rules. Then we can add extra nginx rules without lose the configuration. I understand that it can make users broke the nginx server syntax. But this can be fixed doing a nginx test before save the rules. If the return is zero, then it will be saved.

I recommend to create an extra file to add the customization instead of customize the main file. It will make more organized and in the same time will allow the backup system copy the conf file to the backup.

**Describe alternatives you've considered**
The alternative today is create a specific template for a specific domain and ask the user to use that template in just that domain.  And if the template is not supporting all site features, the user need to ask the sysadmin to change the nginx template again.

**Additional context**
One good example about extra configs are proxies (cloudflare, quic cloud etc). Usually they copy the CORS headers from origin site and it works as expecred. But there are some proxy servers, like gtranslate service, that rewrite the domain in a new domain to offer a new language to the site. For example: from mydomain.com will be created a proxy to mydomain.it and the site will be automatically translated to italian. The problem with this is the new domain .it will receive the .com CORS headers. Then I need to modify my http server to allow this cross origin source. In the case of hestiacp, the nginx config file.

Some cache plugins of wordpress also need to add extra rules in nginx to have all features enabled. This another good reason to have this kind of feature.

**Comment by jaapmarcus** [comment]
It will add more complexity. Also I am not an fan for allowing every user to change Nginx config files. 

We are currently using template files for it these can be modified for example https://github.com/hestiacp/hestiacp/tree/main/install/deb/templates/web/nginx/php-fpm
 as long you create an copy of it.
 
 See https://docs.hestiacp.com/admin_docs/server_management.html 

We will discuss it...

**Comment by franciscopaniskaseker** [comment]
I do not like either users adding nginx rules, but it can be an advanced tab with "I agree that I can take down the server" and of course do a nginx syntax test before save.

This is not an essential feature for the hestiacp and I agree of the consequences. But as I saw the "root folder config" was added, I saw that we actually are very close of this feature.

thank you.

**Comment by jaapmarcus** [comment]
You are allready able to load custom config via:

https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/web/nginx/php-fpm/default.tpl#L53

Just create an file with the name nginx.conf_name  and nginx.ssl.conf_name   and place it %home%/%user%/conf/web/%domain%/ so even custom templates are even not needed.

**Comment by franciscopaniskaseker** [comment]
Great. THose files are copied from backup system? Seems not. So maybe I can open a new issue about add extra nginx conf files to the backup. What do you think?

**Comment by jaapmarcus** [comment]
Extra config is currently also backed up and restored

**Comment by franciscopaniskaseker** [comment]
Excellent!
