### ISSUE TITLE
[BUG] Version icon not updated after upgrade to v1.4

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1835]
**Describe the bug**
Red test tube icon still shows instead of the white box icon of stable releases

**To Reproduce**
Debian 10.9
Was 1.4 Beta upgraded to 1.4 with apt update && apt upgrade

![image](https://user-images.githubusercontent.com/23358751/119720219-9cff1500-be61-11eb-9048-f3fb7231bc03.png)

**Comment by jaapmarcus** [comment]
As it is only visual: 

nano /usr/local/hestia/conf/hestia.conf 
Change RELEASE_BRANCH="xxx" to RELEASE_BRANCH="release"

We will sort it for a later release.

**Comment by manuelserol** [comment]
It currently shows `RELEASE_BRANCH='main'`

I changed from `main` to `release` and is with the white icon now
