### ISSUE TITLE
[BUG] Modx template (s)tpl

### ISSUE THREAD

**Issue by speak82** [hestiacp/hestiacp#1838]
Nginx default config template lost one "}".
ngingx start falied.

**Comment by speak82** [comment]
location / {
        try_files $uri $uri/ @rewrite;
        location ~* ^.+\.(ogg|ogv|svg|svgz|swf|eot|otf|woff|woff2|mov|mp3|mp4|webm|flv|ttf|rss|atom|jpg|jpeg|gif|png|ico|bmp|mid|midi|wav|rtf|css|js|jar)$ {
            expires 30d;
            fastcgi_hide_header "Set-Cookie";
        }

**Comment by speak82** [comment]
modx.tpl modx.stpl

**Comment by ScIT-Raphael** [comment]
So a custom template and not default.tpl/stpl? Could you link the related template, will be easier to debug for us: https://github.com/hestiacp/hestiacp/tree/main/install/deb/templates/web

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/web/nginx/php-fpm/modx.tpl and https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/web/nginx/php-fpm/modx.stpl

**Comment by ioannidesalex** [comment]
Well I guess you made it faster than me :)

Only a } was missing.

**Comment by ioannidesalex** [comment]
Will be fixed at the next version. Thanks for reporting.
