### ISSUE TITLE
[BUG] Clamd filled all the server memory usage

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1840]
**Describe the bug**
Suddenly zabbix start send to me warnings about high memory usage in my server. I entered in the server and checked the journalctl. OOM killer killed the clamd process. This is probably something related with clamd and low memory servers (my vps has 2GB with usually 1.3Gb free). I already saw this happening a lot of times in vestacp and now, for the first time, in hestiacp.

```
[ 8954.267734] Tasks state (memory values in pages):
[ 8954.267734] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 8954.267798] [    553]   115   553   312668   271974  2310144        0             0 clamd
[ 8954.267755] [    462]   115   462    15136      456   110592        0             0 freshclam
[ 8954.267881] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/clamav-daemon.service,task=clamd,pid=553,uid=115
[ 8954.267907] Out of memory: Killed process 553 (clamd) total-vm:1250672kB, anon-rss:1087896kB, file-rss:0kB, shmem-rss:0kB, UID:115 pgtables:2256kB oom_score_adj:0
[ 8954.346509] oom_reaper: reaped process 553 (clamd), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

```

**To Reproduce**
What steps did you take when the issue occured? 
1. Install ubuntu 20.04
2. Install hestiacp 1.4.1
3. Setup a wordpress installation
4. Configure this wordpress with one smtp account
5. wait some time

**Expected behavior**
clamd not eat all the memory. 

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.1 (fresh install did today)

**Comment by jaapmarcus** [comment]
The issue is caused by the fact clamav/clamd takes over 1 GB of memory when active.

 clamav-daemon email antivirus 49 minutes 0 1115 MB

**Comment by franciscopaniskaseker** [comment]
Everytime that I restart the server (that have 2GB of memory) clamd start eating the memory and in sometime it trigger OOM and then the clamd daemon is killed.

**Comment by jaapmarcus** [comment]
Feel free to find a way to limit the ram usage of ClamAV/Clamd 

Set up a swap disk and maybe use ulimit -m amountofram.

https://unix.stackexchange.com/questions/114709/how-to-reduce-clamav-memory-usage

The only thing we can do is increase the memory requirements for ClamD

**Comment by jaapmarcus** [comment]
The point to complain is by the developers of ClamAV. But probably assign more swap / memory is a better idea... 

https://github.com/Cisco-Talos/clamav

**Comment by franciscopaniskaseker** [comment]
I clearly understand that the problem come from them. My point is: do you want the new hestiacp users having memory issues because a third service? clamd is a CPU and a memory eater. I do not think it is a good idea to set it enable by default.

If you look in the google by the clamd problems under vestacp and cpanel, you will find a lot of years of cpu and memory problems. Hestiacp will be blamed by a third service that does not bring too much benefits to the server.

If the user do not use swap, the clamd will be killed and probably systemd will try to restart. If the user has swap, the kernel will start swapping and the server performance will fastly decrease.

I know how to fix the problem in the servers that I manage, however now I have to create a quirk to execute after new hestiacp setups to avoid clamd problems. 

I will not recommend add swap to fix this problem. My recommendation to the users with low quantity of memory (less than 4gb) is just to remove the service. And if you do not need clamav checking your emails or even do not use hestiacp mail server, just remove. Clamav has more benefits checking the system files and not emails, but in hestiacp the service just scan the email. If you want some protection with your emails without to use too much resources as clamd needs, a spamassassin well configured can do the job very well.

ps: I understand that they are different softwares.

**Comment by ScIT-Raphael** [comment]
We already discussed within the team to increase the clamd minimal memory limit.
