### ISSUE TITLE
[BUG] File Manager installation failed!

### ISSUE THREAD

**Issue by fuzhyperblue** [hestiacp/hestiacp#1842]
after automatic update to 1.4.1 I got a notification in the panel "File Manager installation failed! Please report this to our development team on  GitHub."

now files button at the top is missing in gui interface

I have not done anything, automated update process resulted this error.
log attached

[hst-upgrade-270520210525.log](https://github.com/hestiacp/hestiacp/files/6552031/hst-upgrade-270520210525.log)

Ubuntu 18.04.5 LTS
Hestia Control Panel version 1.4.1

**Comment by tudorr89** [comment]
just do `v-add-sys-filemanager` in the terminal and it will be reinstalled

**Comment by fuzhyperblue** [comment]
> just do `v-add-sys-filemanager` in the terminal and it will be reinstalled

its back, thanks!

**Comment by webeditors** [comment]
Had the same issue, but had this error

		~# v-add-sys-filemanager
		[/usr/local/hestia/web/fm/filegator_v7.5.1.zip]
		  End-of-central-directory signature not found.  Either this file is not
		  a zipfile, or it constitutes one disk of a multi-part archive.  In the
		  latter case the central directory and zipfile comment will be found on
		  the last disk(s) of this archive.
		unzip:  cannot find zipfile directory in one of /usr/local/hestia/web/fm/filegator_v7.5.1.zip or
				/usr/local/hestia/web/fm/filegator_v7.5.1.zip.zip, and cannot find /usr/local/hestia/web/fm/filegator_v7.5.1.zip.ZIP, period.
		mv: cannot stat '/usr/local/hestia/web/fm/filegator/*': No such file or directory

Quite possibly related, but on the same server I got a Cron with the following:

		W: Failed to fetch https://apt.hestiacp.com/dists/bionic/InRelease  Temporary failure resolving 'apt.hestiacp.com'
		W: Some index files failed to download. They have been ignored, or old ones used instead.
		W: Failed to fetch https://apt.hestiacp.com/dists/bionic/InRelease  Temporary failure resolving 'apt.hestiacp.com'
		W: Some index files failed to download. They have been ignored, or old ones used instead.

... even though the server says it's running 1.4.1. Possibly a failed upgrade?

**Comment by jaapmarcus** [comment]
Try running atp update && apt upgrade

**Comment by webeditors** [comment]
Well this isn't looking good... seems to be having problems resolving domain names since the update

	apt update
	Err:1 https://mirror.mva-n.net/mariadb/repo/10.5/ubuntu bionic InRelease       
	  Temporary failure resolving 'mirror.mva-n.net'
	Err:2 https://nginx.org/packages/mainline/ubuntu bionic InRelease              
	  Temporary failure resolving 'nginx.org'
	Err:3 http://archive.ubuntu.com/ubuntu bionic InRelease                        
	  Temporary failure resolving 'archive.ubuntu.com'
	Err:4 https://apt.hestiacp.com bionic InRelease                                
	  Temporary failure resolving 'apt.hestiacp.com'
	Err:5 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic InRelease          
	  Temporary failure resolving 'ppa.launchpad.net'
	Err:6 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease      
	  Temporary failure resolving 'ppa.launchpad.net'
	Err:7 http://archive.ubuntu.com/ubuntu bionic-security InRelease       
	  Temporary failure resolving 'archive.ubuntu.com'
	Err:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
	  Temporary failure resolving 'archive.ubuntu.com'
	Reading package lists... Done        
	Building dependency tree       
	Reading state information... Done
	132 packages can be upgraded. Run 'apt list --upgradable' to see them.
	W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
	W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'
	W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
	W: Failed to fetch http://ppa.launchpad.net/ondrej/apache2/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'ppa.launchpad.net'
	W: Failed to fetch https://apt.hestiacp.com/dists/bionic/InRelease  Temporary failure resolving 'apt.hestiacp.com'
	W: Failed to fetch https://mirror.mva-n.net/mariadb/repo/10.5/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'mirror.mva-n.net'
	W: Failed to fetch https://nginx.org/packages/mainline/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'nginx.org'
	W: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'ppa.launchpad.net'
	W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jaapmarcus** [comment]
Try disabling iptables and then try again.

**Comment by webeditors** [comment]
> Try disabling iptables and then try again.

That fixed it, and I v-add-sys-filemanager also worked... but iptables is a necessary, right?

**Comment by jaapmarcus** [comment]
Yes it is. Digital ocean by accident?

**Comment by webeditors** [comment]
> Yes it is. Digital ocean by accident?

Nope, not Digital Ocean - I've got three dedicated boxes with Easyspace and this is happening on two of them, even though all three are the same config (Ubuntu 18.04 (x86_64), Intel Xeon E3-1230, 32GB, 2TB). 

Something funky has happened since the overnight update and it would be good to get to the bottom of it. Any pointers as to which log files I should be looking at would be appreciated.

**Comment by jaapmarcus** [comment]
Try rebooting the server. On one server it solved the issue

**Comment by jaapmarcus** [comment]
Try https://forum.hestiacp.com/t/hestiacp-very-slow-dns-errors-ssl-errors-hetzner/2585/21

The last post
