### ISSUE TITLE
[BUG] File Manager installation failed

### ISSUE THREAD

**Issue by webeditors** [hestiacp/hestiacp#1846]
I have three dedicated servers, all the same setup with matching hardware, OS and Hestia installs. Overnight they all updated to 1.4.1, but on two of them I had the notification "File Manager installation failed! - Please report this to our development team on  GitHub.", the third server didn't have the same issue.

Not sure what logs would be useful here, but tell me where to find them and I'll post them :-)

**Operating system:**
Ubuntu 18.04 (x86_64)

**Hestia Control Panel version:**
Automatic Upgrade 1.3.5 > 1.4.1

**Comment by tudorr89** [comment]
make sure to search before opening a new issue. See #1842
