### ISSUE TITLE
[FEATURE] Download full webserver logs (access.log and error.log) from the Web UI of HestiaCP

### ISSUE THREAD

**Issue by Pleskan** [hestiacp/hestiacp#1847]
It's worth to implement possibility of downloading full webserver and/or  backend upstream logs from the HestiaCP web interface at the **Web Domains**  screen.

**Comment by jaapmarcus** [comment]
<img width="347" alt="Screenshot 2021-06-03 at 18 09 08" src="https://user-images.githubusercontent.com/9754650/120676923-d4d80f00-c496-11eb-8f74-52b805811d9d.png">

Both "Download" icons are links to download the log files
(only the last one)
