### ISSUE TITLE
I need your urgent support

### ISSUE THREAD

**Issue by Mertsahin-Demircioglu** [hestiacp/hestiacp#1850]
1.4.1 Updated
* Hestia panel does not open.
* We looked at many files, could not solve
* My site does not work and refuses to link.

![image](https://user-images.githubusercontent.com/84936149/119887833-4ebf4400-bf3d-11eb-8db3-34072421e5f3.png)

**### can i completely restore the system**

I tried changing the disk letter.  ( mount -o remount,..)

Didn't happen

**Comment by ScIT-Raphael** [comment]
Please provide the whole output, not a bad cut screenshot :).

**Comment by MertsahinD** [comment]
Which ones have I tried
* I looked at the system logs and could not find much, it was not resolved.
* I restarted the whole server in the system not resolved.
* I updated the system again with the apt -get commands, it still does not work.
I tried the ways that came to my mind, followed the forms and problems, but still could not find it.

![image](https://user-images.githubusercontent.com/84936149/119889451-3b14dd00-bf3f-11eb-951e-e847c1655d43.png)

**Comment by jaapmarcus** [comment]
Nothing resolves try:
https://github.com/hestiacp/hestiacp/issues/1849

**Comment by ScIT-Raphael** [comment]
Can you run apt install --reinstall hestia-nginx?

**Comment by MertsahinD** [comment]
* i am working

![image](https://user-images.githubusercontent.com/84936149/119890748-e1151700-bf40-11eb-84a6-011527cfb750.png)

**But my problem is still i'm trying**

![image](https://user-images.githubusercontent.com/84936149/119891632-e32ba580-bf41-11eb-8bdf-e92d0efd800b.png)

I'm sorry I'm replying late. I received 425 messages from members on my site, and I had to reply to them.

**Comment by Mertsahin-Demircioglu** [comment]
If possible I can restore the system to its old version. Is there such an opportunity? I am getting excessive messages. We need to tackle the problem as soon as possible.

**Comment by ScIT-Raphael** [comment]
So is hestia itself now up and running? Probaly validate if you've aswell connection issues, related to the issue report: https://github.com/hestiacp/hestiacp/issues/1849

A downgrade isnt possible, it sounds like two issues - a old issue after a hestia-nginx update which showed up now due to the restart routine and the issue report linked above.

**Comment by Mertsahin-Demircioglu** [comment]
I was looking at these too
* tried all of them but it didn't work

![image](https://user-images.githubusercontent.com/84936149/119893109-a8c30800-bf43-11eb-8988-2512aa640cd7.png)


 https: // server: 8086 / list / firewall / banlist /  = I tried this too, it didn't work for myself.

**Comment by Mertsahin-Demircioglu** [comment]
It must be something else
* I haven't even been to the hestia panel in a long time
* This update has arrived and is broken.

**Comment by ScIT-Raphael** [comment]
Run the commands using full path, add /usr/local/hestia/bin/ in front of the v commands, but probaly running `iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT` is enough.

**Comment by Mertsahin-Demircioglu** [comment]
I guess the problem is
1. I was able to login to the hesta panel
2. I checked the services one by one
Problem = I saw that Nginx config files are not opening.

- IPtables is also OK, I guess it does not block my IP address anyway.

![image](https://user-images.githubusercontent.com/84936149/119895333-533c2a80-bf46-11eb-81a0-c250a5deada4.png)

![image](https://user-images.githubusercontent.com/84936149/119894737-a497ea00-bf45-11eb-810a-d6d49a04f3ee.png)

/edit/server/nginx/

![image](https://user-images.githubusercontent.com/84936149/119894833-c42f1280-bf45-11eb-8bdf-52d251c9c663.png)

I think it's a **nginx** problem
* config files are not visible
* Can I solve this easily?
* Or should I reinstall the sidewalk completely.

**Comment by jaapmarcus** [comment]
:port_number/edit/server/nginx/
Should work fine:
<img width="1107" alt="Screenshot 2021-05-27 at 23 05 15" src="https://user-images.githubusercontent.com/9754650/119896933-081f1900-bf40-11eb-914d-72b036a9521a.png">


Any issues with Nginx on the main site?

**Comment by Mertsahin-Demircioglu** [comment]
![image](https://user-images.githubusercontent.com/84936149/119896874-50dad000-bf48-11eb-856f-690c2d46eb30.png)

Nginx config file exists
* Cannot find the file in the hestia panel.
I don't know what to do because of the rush

**Comment by Mertsahin-Demircioglu** [comment]
just can't see it in hesta panel

**Comment by jaapmarcus** [comment]
This hestia-nginx 

Check /etc/nginx/nginx.conf

**Comment by Mertsahin-Demircioglu** [comment]
yes there is there it seems not on the url in the hesta panel 

![image](https://user-images.githubusercontent.com/84936149/119897819-a794d980-bf49-11eb-8c78-c668188549d9.png)

**Comment by Mertsahin-Demircioglu** [comment]
Here at midnight I am confused. When the people I worked with could not reach the site, their stress became great. I think I'm doing something wrong.

**Comment by jaapmarcus** [comment]
If you want join Discord and send me a DM. I can have a look via SSH if you want...

**Comment by jaapmarcus** [comment]
Please provide some more information or use our Discord / Forum.  As I allready told it is probally smart to backup the users and wipe the server / start up a new VM
