### ISSUE TITLE
[BUG] Antispam system impacted by latest upgrade to 1.4.x

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1852]
**Describe the bug**
After upgrading, I noticed that my mail was not being scanned for spam. I knew that the exim configs had been altered, so I spent a long time looking through them, rolling back to previous versions, cursing, etc. 

Finally I figured out: spam detection is triggered by the presence of the file /etc/exim4/domains/domain.com/antispam 
This sets a variable in the acl which triggers the scan. The file was missing post upgrade, so no spam scanning was taking place. I use rspamd, but this probably also applies to spamassassin, which uses the same method to trigger the acl. 

So now the cause: 
The option to select Antispam has been removed from that control panel Mail Domain Edit page. I believe this is how it was removed from my domain. I used that page to switch mail client from roundcube to rainloop, and during that operation, as there was no Antispam option on that page, it deleted the settings. 

Commandline v-add-mail-domain-antispam works OK, and domain then appears as having antispam in web interface. 

**To Reproduce**
touch antispam file back into existence. Spam scanning starts again. 
remove file. spam scanning stops. 

Change something on Mail domain Edit page and Save. Antispam is removed from mail domain. 
Run v-add-mail-domain-antispam, spam protection returns.

**Comment by plutocrat** [comment]
OK, so you're saying that I should put "something" in ANTISPAM_SYSTEM for that domain, when I switch from spamassassin to rspamd?

**Comment by jaapmarcus** [comment]
It is in the /usr/local/hestia/conf/hestia.conf

By default is ANTISPAM_SYSTEM='spamassassin'
I don't know what happens when you replace it with rspamd. You might need to test it on a test server first. I think ANTISPAM_SYSTEM variable is only used.

**Comment by plutocrat** [comment]
Yes, so I can confirm that as long as the ANTISPAM_SYSTEM variable has something in it, then everything works as expected, and changing webmail system from the Mail Domain Edit page doesn't break spam filtering. 
On the server where I experienced problems, the ANTISPAM_SYSTEM variable was completely absent. I thought there was a function in syshealth.sh which would have detected this and replaced it, at least with an empty value, but it didn't seem to work on this server. Other servers which I upgraded to rspamd are OK. Strange one.

**Comment by ScIT-Raphael** [comment]
Thanks for the testing @plutocrat. Infact we currently only support spamassassin and your issue report is in combination with rspamd, I'm going to close this report. Maybe we will have a day some time to build rspamd support or you've the interrest to provide it with a PR - we are always open for such things!

**Comment by plutocrat** [comment]
Sure. I realize I voided the warranty by installing rspamd, but I wondered if it might be part of another problem, for instance with the syshealth config checker, or the new Mail Domain Edit page, so I reported it here. 
I've learnt to check for the presence of that variable in hestia.conf, when converting to rspamd, so that's also a good thing!
