### ISSUE TITLE
[BUG] File Manager installation failed!

### ISSUE THREAD

**Issue by SCelik** [hestiacp/hestiacp#1853]
==============================================================================
Hestia Control Panel Software Update Log
==============================================================================

OPERATING SYSTEM:      Ubuntu (20.04)
CURRENT VERSION:       1.3.5
NEW VERSION:           1.4.1
RELEASE BRANCH:        release
BUILD TYPE:            Production release

INSTALLER OPTIONS:
=============================================================================
Send email notification on upgrade complete:      true
Send installed log output to admin email:         true

=============================================================================
[ ! ] Performing system health check before proceeding with installation...
[ ! ] Adding missing variable to hestia.conf: WEBMAIL_SYSTEM ('roundcube')
[ ! ] Adding missing variable to hestia.conf: INACTIVE_SESSION_TIMEOUT ('60')
[ ! ] Adding missing variable to hestia.conf: ENFORCE_SUBDOMAIN_OWNERSHIP ('no')
[ ! ] Adding missing variable to hestia.conf: API_ALLOWED_IP ('allow-all')
[ ! ] Adding missing variable to hestia.conf: ENFORCE_SUBDOMAIN_OWNERSHIP ('yes')
[ ! ] Adding missing variable to hestia.conf: DEBUG_MODE ('false')
[ ! ] Adding missing variable to hestia.conf: PLUGIN_APP_INSTALLER ('true')
[ ! ] Adding missing variable to hestia.conf: POLICY_SYSTEM_ENABLE_BACON ('false')
[ ! ] Adding missing variable to hestia.conf: POLICY_SYSTEM_HIDE_SERVICES ('no')
[ ! ] Adding missing variable to hestia.conf: POLICY_SYSTEM_PASSWORD_RESET ('no')
[ ! ] Adding missing variable to hestia.conf: POLICY_SYSTEM_PROTECTED_ADMIN ('no')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_CHANGE_THEME ('yes')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_DELETE_LOGS ('yes')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_EDIT_DETAILS ('yes')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_EDIT_DNS_TEMPLATES ('yes')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_EDIT_WEB_TEMPLATES ('yes')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_VIEW_LOGS ('yes')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_VIEW_SUSPENDED ('no')
[ ! ] Adding missing variable to hestia.conf: PHPMYADMIN_KEY ('')
[ * ] Health check complete. Starting upgrade from 1.3.5 to 1.4.1...
=============================================================================
[ * ] Backing up existing templates and configuration files...

[ - ] Now applying any necessary patches from version v1.4.0...
[ * ] Enabling nginx FastCGI cache support...
[ * ] Updating nginx configuration with changes to Cloudflare IP addresses
[ * ] Populating HELO/SMTP Banner value for existing IP addresses...
[ * ] Updating exim4 configuration...
[ * ] Enabling SMTP relay support...
[ * ] Creating known good configuration data for system recovery...
[ * ] Fix potenial issue with multiple network adapters and netplan...
[ * ] Removing outdated nginx templates...
[ * ] Migrating legacy default package for all users...
[ * ] Replacing default package...

[ - ] Now applying any necessary patches from version v1.4.1...
**[ * ] Updating File Manager...
ERROR: File Manager installation failed!
Please report this to our development team:
https://github.com/hestiacp/hestiacp/issues**
[ ! ] Updating default web domain templates...
[ ! ] Updating default mail domain templates...
[ ! ] Updating default DNS zone templates...
[ ! ] Verifying phpMyAdmin v5.1.0 installation...
=============================================================================
Installation tasks complete, performing clean-up...
=============================================================================
[ * ] Rebuilding user accounts and domains, this may take a few minutes...
      - admin...
      - usr01...
      - usr02...
      - usr03...
      - usr04...
      - usr05...
      - usr06...
      - usr07...
      - usr08...
      - usr09...
      - usr10...
      - usr11...
      - usr12...
      - usr13...
      - usr14...
[ * ] Restarting services...

=============================================================================
UPGRADE COMPLETE.
Please report any issues on GitHub:
https://github.com/hestiacp/hestiacp/issues
=============================================================================

**Comment by arielesp** [comment]
[Symfony\Component\Process\Exception\RuntimeException]
  The Process class relies on proc_open, which is not available on your PHP installation.


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

ERROR: File Manager installation failed!
Please report this to our development team:
https://github.com/hestiacp/hestiacp/issues
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

**Comment by ScIT-Raphael** [comment]
enable proc_open, already stated in your error message: The Process class relies on proc_open, which is not available on your PHP installation.

**Comment by arielesp** [comment]
the php.ini doesnt contains proc_open disabled

**Comment by jaapmarcus** [comment]
Currently hestia-php has all the required modules loaded make sure you are using the last version and you are done...

**Comment by arielesp** [comment]
I already tried run apt reinstal hestia

**Comment by ScIT-Raphael** [comment]
reinstall hestia needed, better run an apt update && apt upgrade and validate your hestia, hestia-nginx and hestia-php version.

**Comment by jaapmarcus** [comment]
And if you are using ARM follow the instructions in changelog!

**Comment by arielesp** [comment]
hestia-php php interpreter7.4.26 (amd64)
hestia-nginx internal web server1.21.4 (amd64)

**Comment by arielesp** [comment]
not using arm

**Comment by ScIT-Raphael** [comment]
Then I have no idea, please consider to use our forum or discord, it's the better place for support cases (non reproducible issue).

**Comment by jaapmarcus** [comment]
```
/usr/local/hestia/php/bin/php -m | grep openssl
```
Will check if hestia-php has the openssl module installed. If it returns openssl then continue with the next step. This should be your case... 

```
/usr/local/hestia/bin/v-add-sys-filemanager
```
Does install the file manager without installing hestia again.

If the first step does provide an empty answer then modify /etc/php/x.x/cli/php.ini and look for disable_functions=

Check if proc_open is there or not. If it is there remove it and restart php...

And then run 

```
/usr/local/hestia/bin/v-add-sys-filemanager
```

We are not able to login into your server. And if we have to our standard rates do apply...

**Comment by arielesp** [comment]
I run a apt reinstall hestia-php
and aparently worked ...

but we have a error yet... "unknow error" in every hestiacp file manager ... how to fix this?

**Comment by ScIT-Raphael** [comment]
https://forum.hestiacp.com/t/1-5-0-update-filemanager-unknown-error/5009
