### ISSUE TITLE
[BUG] The --nginx no option does not work debian/ubuntu

### ISSUE THREAD

**Issue by thanur** [hestiacp/hestiacp#1857]
The latest HestiaCP cannot be installed with the option
--nginx no
(same apche)
debian and ubuntu.

The only option I see is uninstalling nginx, or manually editing the file: https://github.com/hestiacp/hestiacp/blob/main/install/hst-install-debian.sh

**Comment by thanur** [comment]
Why? :(
What about existing installations?

Can I remove it manually according to this manual? https://vestacp.com/docs/#how-to-remove-nginx-debian-ubuntu

**Comment by ScIT-Raphael** [comment]
Because there is no reason to let it run as apache2 only, also it gives trouble while generating lets encrypt certs.

Ofc you can try, but we can't provide any support for it.
