### ISSUE TITLE
[FEATURE] modsecurity or other waf

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1859]
I'm curious to know why mod security or an nginx specific web application firewall isn't compiled by default into nginx. Is there a specific reason this feature has been left out?  Especially now that the standalone Apache is not an option. I think this would be a valuable feature. Even if it's not activated or put into the configurations just having it available would be great.

I'm bit concerned about attempting to recompile nginx with Hestia, would it have any possible effects with future updates having a modified nginx compiled with other flags?

I think in general this is just a valuable option. Either having an option in the setup for including her not including a waf impossible multiple options on which one. Understand that could be complex if you were to include changes to configuration files with the inclusion of the flags. But the configuration files wouldn't be necessary, as people could add that themselves if they want to use it.

**Comment by jaapmarcus** [comment]
>I'm curious to know why mod security or a nginx specific web application firewall isn't compiled by default into nginx. 

Time!

**Comment by jlguerrerosanz** [comment]
To find time is always a matter of priorities. 

Interesting feature though.

**Comment by jaapmarcus** [comment]
> To find time is always a matter of priorities.
Even then we don't have the time for it.... 

We are not interested in supplying custom build version supplied with Hestia.
 
If some body is willing to invest the time to create a new project on the same basis as it happens with the custom php-packages that are build for Ubuntu / Debian it might be worth for a consideration.  

But it takes time and/or money to set it up and both are currently / in the near feature not available...

**Comment by ghost** [comment]
I was not referring to a custom build (the option to select a waf or not would be great) but I was more thinking that mod security should be compiled into nginx with hestia. then people who want to use it could just add the code to the conf or just not use it. that would avoid ppl having to compile a new nginx  that may break updates.

**Comment by ghost** [comment]
apache is nice as you just drop in things, but nginx has few dropins, your build has most of what ppl would use it wouldld be nice to have a way to select additional flags at installation and have it carry though updates, but I know that is a time issue. but modsec or a nginx specific waf compiled by default  would be great so we could just put the conf code in ourself.  I don't believe compiling them itself into nginx without setting them up would cause issues or such. it wouIld just be available to who wants to use it.  modsec should not increase ram usage noticeably at least as long as its code is not in nginx.conf as its config call in most of the parts that would consume ram.

**Comment by jaapmarcus** [comment]
> I was not referring to a custom build (the option to select a waf or not would be great) but I was more thinking that mod security should be compiled into nginx with hestia. 

As told we don't think it is a great idea to build Nginx packages on the server of the users.  I have seen issues with building custom hestia-php / hestia-nginx for ARM that we "unofficially" support with some DIY as building the custom packages with a Raspberry Pi doesn't work. And few users are not able to do it. 

"hestia-nginx" is used for the backend as it requires some special config and by making it this way it is extremely light weight as the are no unused packages installed for it allowing it to be fast and light weight... I see a lot of issues when we apply "hestia-nginx" for the websites. 

For the websites we use currently Nginx mainline from the Nginx website (free version). If we want the "build" Nginx with Mod rewrite we have to spend at least 2000 / 3000  euro  a month keeping it up to date / and test all the situations. We don't want to invest  money (Or the time into it). 

There are lot of feature requests and wishes we have for Hestia but are postponed until the feature as we don't have time for it.  And with this feature it will happen the same it will end up on the never done list. 

As HestiaCP is an Open source project so pick of one of the four options below:

1. Make it your self 
2. Higher a developer who is able to do it for you 
3. Accept it that it will not be added
4. Or move to an other project / program that you like. 

I know the advantages of Apache2 and how it works but it doesn't make sense for use to spend the time developing features that we don't use and as a large of the installs are with Nginx + Apache or only Nginx.  

VestaCP decided to keep supporting everything to the max creating major headaces for compability and maintaining it. And we all know what happened..
