### ISSUE TITLE
[BUG] v-restore-user does not restore Enable automatic HTTPS redirection web domain configuration

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1862]
**Describe the bug**
When Restoring a User that had websites with the option Enable automatic HTTPS redirection checked. It does not restore that configuration which means you have to manually check them after restore
This a backup from 1.4.1 to restore to another 1.4.1 install

**To Reproduce**
What steps did you take when the issue occured? 
1. Create a site make sure Enable automatic HTTPS redirection is checked
2. backup user
3. restore user to a different instance

**Expected behavior**
should hold configuration from backup

**Operating system:**
Ubuntu 20.04 LTS

1.4.1

**Comment by jaapmarcus** [comment]
Can confirm also for HSTS settings will fix it in next release.
