### ISSUE TITLE
[BUG] Leftover files on / when v-change-database-owner

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1863]
**Describe the bug**
I Moved some Domains and Databases over from admin to a new user and noticed there were files left over on /
here are the few files it left over when I moved a database called admin_surfacetech  
**admin_surfacetech.mysql.sql** 
**admin_surfacetech.mysql.admin_surfacetech**
 

**To Reproduce**
What steps did you take when the issue occured? 
1. Create DB on admin
2. Create another user
3. move DB over to new user using v-change-database-owner
4. ls -l /
5. You will notice db files there

**Expected behavior**
These files should be deleted once ported to new user

**Operating system:**
ubuntu 20.04

**Hestia Control Panel version:**
1.4.1

**Additional context**
I have tested this on two instances.

**Comment by jaapmarcus** [comment]
Issue was caused by mktmp dir was not saved in the variable propperly
