### ISSUE TITLE
[BUG] v-change-domain-owner - Did not carry over custom document root - directory value

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1864]
**Describe the bug**
I moved a site from admin to another user I had the option Custom document ticked with the directory value being public
The moved over except the directory value was empty

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. create web domain on admin user
2. edit web domain
3. choose advanced
4. check Custom document root
5. Put in public for Directory field
6. Save
7. move site over to another user using v-change-domain-owner
8. Site moves over but Directory setting does not follow

**Expected behavior**
It should carry all configuration options when moving a web domain to a new user

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
1.4.1

**Additional context**
I did get these errors when moving the site

```
[*] Moving web domain...
[*] Moving DNS zone and records...
/usr/local/hestia/func/domain.sh: eval: line 483: unexpected EOF while looking for matching `''
/usr/local/hestia/func/domain.sh: eval: line 484: syntax error: unexpected end of file
```

**Comment by jaapmarcus** [comment]
We also need to check for the new features added in 1.4

**Comment by jaapmarcus** [comment]
Issue is caused by the fact the full path is stored:
/home/owner/web/domain.com/public_html/random_root/ 

When the custom doc root falls within the same domain.com it might be an option to "change" the username from "owner" to the new user

When it links to domain2.com we should thrown an error and or reset the custom docroot to ""

**Comment by johnnyq** [comment]
@jaapmarcus I agree with both just changing the user value when moving domain to new user and if its a different domain NULL it out.
