### ISSUE TITLE
[BUG] File manager wrong directory

### ISSUE THREAD

**Issue by Regerta** [hestiacp/hestiacp#1865]
**Describe the bug**
When I'am login as user from admin account and accesing file manager it goes to admin directory, not the user's directory

**To Reproduce**
What steps did you take when the issue occured? 
1. Login to HestiaCP with admin account
1. Go to a user and login as user
2. Go to file manager

**Expected behavior**
Admin should have access to current user's directory on file manager when logged in as user.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.1

**Comment by jaapmarcus** [comment]
Noticed same issue once need to investigate it...

**Comment by samaya-smg** [comment]
same issue

**Comment by yaelahan** [comment]
same issue

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1867

Should do the trick

**Comment by Regerta** [comment]
Problem solved, thank you!
