### ISSUE TITLE
[BUG] " Allowed IP addresses for API" field with strange behaviour

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1866]
**Describe the bug**
When filling this field, the `textarea` is prefilled with tabulations, what makes dificult to set the cursor on the first line and first character space to strat writing.

Also after inserting an IP and saving. Then the IP appears in the `textarea` on a random position, depending on the browser used it might show on different locations. This happen with one or multiple IPs and then to edit the `textarea` is again recessary to reposition the cursor and remove tabulations.

**Operating system:**
Debian 10.9

**Hestia Control Panel version:**
1.4.1

**Comment by jaapmarcus** [comment]
Fixed
