### ISSUE TITLE
[BUG] Adding public ssh keys for other users as admin reverts back to edit admin user

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1870]
**Describe the bug**
When I login in as admin and click edit another user and add ssh key, it adds the key to the admin and not to the specified user.

**To Reproduce**
What steps did you take when the issue occured? 
1. Add User
2. Click Edit user
3. click Manage SSH Keys
4. Add SSH Key
5. It will redirect back to edit admin under manage ssh keys section and not add the key for the specified user

**Expected behavior**
To Add the key for the intended user

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
1.4.1

**Comment by jaapmarcus** [comment]
Will get fixed with 1.4.2 release
