### ISSUE TITLE
[BUG] DNS - Cannot add root domain value (example.com) record as MX Record

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1874]
**Describe the bug**
I have been trying a self hosted app called Yunohost which requires the root domain to be the mx record value. I discovered this is not allowed in the hestia DNS Configuration.

here is the record the app wants me to add
`
@ 3600 IN MX 10 domain.com.`

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Create a Domain under DNS
2. Choose default-nomail template (so it doesn't create mx records for you)
3. Click Domain to manage Records
4. Click Add Record
5.  Leave Record with @ 
6. Choose MX for type
7. type in domain.com for value or try domain.com.
8. type 10 for Priority
9. Click Save
10. Rececive the error MX Record example.com should be a fully qualified domain name (FQDN)

**Expected behavior**
It should take the entry as its not an illegal DNS Entry

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
1.4.1

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/20b0fd922148206abea5accfc2bf1178a6dadb24/func/domain.sh#L564-L584

Probably changing 3 to 2 should solve the issue

**Comment by johnnyq** [comment]
@jaapmarcus I can confirm the change from 3 to 2 does fix the issue.
I'm curious will these changes get overridden during an update
Thank you!! =]

**Comment by jaapmarcus** [comment]
I will fix it for next release tomorrow.  It is in deed an bug in Vesta / Hestia

```
    fqdn_type=$(echo $t | grep "NS\|CNAME\|MX\|PTR\|SRV")
    tree_length=3
    if [[ $t = 'CNAME' || $t = 'MX' ]]; then
        tree_length=2
    fi
```
