### ISSUE TITLE
[BUG] Saved confirmation message missing

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1879]
**Describe the bug**
When saving server settings the message "Changes have been saved." does not appear anymore

**Operating system:**
Devbian 10.9

**Hestia Control Panel version:**
1.4.1

**Comment by jaapmarcus** [comment]
I am not able to replicate the issue:
<img width="722" alt="Screenshot 2021-06-04 at 08 05 36" src="https://user-images.githubusercontent.com/9754650/120753590-afd1b380-c50b-11eb-8c28-4d362c65f7d0.png">

**Comment by manuelserol** [comment]
It seems that is not happening on all the field changes.

When saving a change on "Set as selected theme for all users" it occurs but I recall to see it happening in other options too

**Comment by jaapmarcus** [comment]
Found the issue it was caused by a header location only for templates. Will get fixed
