### ISSUE TITLE
[FEATURE] utf8mb4 as default charset

### ISSUE THREAD

**Issue by amadex13** [hestiacp/hestiacp#1882]
**Is your feature request related to a problem? Please describe.**
Add utfm8mb4 as default server charset, sometimes on default install the charset goes to Latin1. Who uses Latin1? No emojis.

**Describe the solution you'd like**
my.cnf

```
[client]
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
collation-server = utf8mb4_unicode_520_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

**Comment by david-spring-h** [comment]
I strongly support this suggestion. This charset is required on Moodle websites and would be helpful on many other websites. It would help me and many other Moodle teachers out greatly if this were the default Hestia charset setting.

**Comment by imjuniper** [comment]
Done as of #3337
