### ISSUE TITLE
[BUG] Installation aborted

### ISSUE THREAD

**Issue by BrightestTV** [hestiacp/hestiacp#1883]
I've used hestiacp before, but since I want to install it on a new machine.
Today I installed it with Ubuntu 18.04 LTS operating system as I had installed and followed the website's instructions, but I encountered a problem with the installation aborted like this; what should I do?

[ * ] Installing dependencies...

Installation aborted
====================================================================
ERROR: Install script version does not match package version!
Please download the installer from the release branch in order to continue:

https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

To test pre-release versions, build the .deb packages and re-run the installer:
  ./hst_autocompile.sh --hestia branchname no
  ./hst-install.sh .. --with-debs /tmp/hestiacp-src/debs

Error: Installation aborted

**Comment by wojsmol** [comment]
As suggested in the error message please download fresh installer from https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh.

**Comment by mrassol** [comment]
I also have this problem with this file (I always use this URL with wget anyway) on debian10

**Comment by jaapmarcus** [comment]
I didn't update the version in the installers. Please remove hst-install-ubuntu.sh and try again.
