### ISSUE TITLE
[BUG] problem with suspended mail domain after upgrade

### ISSUE THREAD

**Issue by endrepavel** [hestiacp/hestiacp#1886]
**Describe the bug**
After update all suspended mail domain switched to unsuspended.

**To Reproduce**
Next update

**Expected behavior**
workaround: ln -s /etc/exim4/ /etc/exim

file: /usr/local/hestia/func/rebuild.sh
function:  rebuild_mail_domain_conf()
:
        # Removing configuration files if domain is suspended
        if [ "$SUSPENDED" = 'yes' ]; then
---       rm -f /etc/exim/domains/$domain_idn
+++     rm -f /etc/$MAIL_SYSTEM/domains/$domain_idn
            rm -f /etc/dovecot/conf.d/domains/$domain_idn.conf
        fi

**Operating system:**
Debian GNU/Linux 10

**Hestia Control Panel version:**
1.4.2

**Comment by jaapmarcus** [comment]
Created a pull request for the suggested changes will be released in 1.4.3
