### ISSUE TITLE
[BUG] nginx.hsts.conf being overwritten with each patch

### ISSUE THREAD

**Issue by themew** [hestiacp/hestiacp#1888]
**Describe the bug**
A clear and concise description of what the bug is. Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. HestiaCP upgrades patch itself
2. curl domain header
3. nginx add_header Strict-Transport-Security has reset itself ignoring the nginx.hsts.conf file

**Expected behavior**
Settings in nginx.hsts.conf should remain intact after a patched update

**Operating system:**
Debian 10.9

**Hestia Control Panel version:**
Occurred when auto-updating to 1.4.1 and 1.4.2  (Happened with the 1.4.0 update as well, but I expected it in a major release update)

**Comment by jaapmarcus** [comment]
I don't see a reason why it should reset:

https://github.com/hestiacp/hestiacp/blob/2b1ba7f9bdf6f182bd55a7d73c32bdc43b3743ee/func/rebuild.sh#L306-L309

Are you using a custom template?

**Comment by themew** [comment]
Nope, standard template with Magento template running.  Just noticed with each update the nginx.hsts.conf file got reset.

**Comment by jaapmarcus** [comment]
On each update we loop trough all the websites and reset every thing on default. Unless htst is disabled in the settings the file should been recreated on update. Default behaviour... 

Unless you have changed the value... There should be no reason that is have been changed...

**Comment by themew** [comment]
I recall during the 1.3.x updates the hsts file wasn't recreated each time and held the edit, but the stock hsts settings fail hsts inclusion, so we are required to recreate them.
Is there another hsts file I'm missing to edit.  The file we edit is `/home/user/conf/web/domain.com` on each update.

Not a big deal to fix it, but without `add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;` the site is removed from the hsts registry in all browsers.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/f85104215d628613306bc90e29de45116f00b649/func/rebuild.sh#L280-L289
It was already there in 1.3.x 

Probally due to the "lack" of updates it was not noticed...

**Comment by jaapmarcus** [comment]
We should find a fix for it ... We want to increase the number of updates anyway

**Comment by themew** [comment]
Thanks for re-opening this.  Editing this file after each update or risk losing the hsts inclusion can take months to be added back to the 3 major browsers that use the hsts file. Happened once to us when we didn't notice and before the nginx.hsts.conf file existed.

**Comment by ScIT-Raphael** [comment]
May I suggest to disable the hestia hsts and create a custom config? If you name it to nginx.hsts.conf.custom it get included by the template: https://github.com/hestiacp/hestiacp/blob/1215cf97ef82400bd06b2f65d9c961450fa57e47/install/deb/templates/web/nginx/default.stpl#L15

**Comment by themew** [comment]
> May I suggest to disable the hestia hsts and create a custom config? If you name it to nginx.hsts.conf.custom it get included by the template:
> 
> https://github.com/hestiacp/hestiacp/blob/1215cf97ef82400bd06b2f65d9c961450fa57e47/install/deb/templates/web/nginx/default.stpl#L15

If I create the file ` nginx.hsts.conf.custom` to replace ` nginx.hsts.conf` it won't get over written when HesitaCP updates?

**Comment by jaapmarcus** [comment]
Yes

**Comment by jaapmarcus** [comment]
I will close the issue

**Comment by themew** [comment]
Hi @jaapmarcus  - The server updated itself to  1.4.9 and while my file `nginx.hsts.conf.custom` is still there, the update recreated the file `nginx.hsts.conf` so now my header looks like this:

`strict-transport-security: max-age=15768000;`
`strict-transport-security: max-age=63072000; includeSubDomains; preload`

What do I need to do to prevent hestiacp from reading both the conf and conf.custom files to prevent the incorrect header and hsts setting?

**Comment by ScIT-Raphael** [comment]
@themew disable hsts function in hestia and place every hsts part in your custom config file.

**Comment by themew** [comment]
Thanks @ScIT-Raphael for the reply.  Since the current hsts line in Hestiacp breaks hsts approval and will force a site to get delisted from inclusion in hsts, should the current hsts config be removed or edited?  It hurts rather than helps a site with hsts enabled.  Plus as a result of the update, unless a site owner checks their hsts status, they'll never know they've been removed from all the browsers hsts config.

Not a complaint, just an observation.  Really appreciate the quick response and the amazing work on hestiacp.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/main/bin/v-delete-web-domain-ssl-hsts

Or uncheck the htst  option in the Hestia
