### ISSUE TITLE
[BUG] Web sub-domains can't be used across users

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#1889]
Previously, a sub-domain of a domain belonging to one user could be used with another user.

This now raises an error

This was very useful if the owner of the hestia server was also a web developer, developing sites clients where the domain is not yet purchased.

E.g. Developer could use a sub-domain (of the developer's domain) in the alias, with the final domain as the actual domain. The client could look at the temporary subdomain, until the final domain was purchased. Once the site was live, you could remove the alias.

Please at least make an option to enable or disable this functionality

Thanks
Jamie

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/settings.html#what-does-the-policy-enforce-subdomain-ownership-mean

See settings ...

**Comment by jaiume** [comment]
You guys are the best!
