### ISSUE TITLE
Frontend URLs for phpMyAdmin and Roundcube have been reverted to default after update

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#189]
Frontend URLs for phpMyAdmin and Roundcube have been reverted to the default (/phpmyadmin & /webmail) after update to the latest version.

**Comment by ScIT-Raphael** [comment]
Webmail and pma values are hardcoded, will find a way to detect and show them properly in backend.

**Comment by vvcares** [comment]
seems the custom port also overwritten to default 8083

**Comment by ScIT-Raphael** [comment]
@vvcares This was already fixed here: https://github.com/hestiacp/hestiacp/blob/b7982ea43d1b43e53f69a270635b7506b4b6722d/install/upgrade/0.9.8-28.sh#L56

**Comment by vvcares** [comment]
Today suddenly my hestiaCP cant login. 
Realized the port was 8083. 
Meantime realized the hestia web ui got colorful. 
So considered the update was overwritten

**Comment by ScIT-Raphael** [comment]
Thanks for your input, I found out that the HESTIA.conf wasnt loaded properly during the upgrade script. So the $BACKEND_PORT variable was empty and the "reset backend port" part wasnt executed. I fixed this with the following commit: https://github.com/hestiacp/hestiacp/commit/d6cab2f3c640e26427dee10d856d650971548261

**Comment by ghost** [comment]
Hi @vvcares,

We're currently working on an overhaul of the mail system and some other related components, and I wanted to know, what values/URL format do you use to access webmail and phpMyAdmin? Are you using a different alias, a subdomain, or disabling them entirely? 

Also, if you have a moment I'd like to know your thoughts on the colors and font used throughout the new interface. We're continuing to work on refreshing the interface to improve overall efficiency.

Thanks for your feedback and have a great day! :)

**Comment by vvcares** [comment]
Hi Kristan,
Webmail URL - Using default link.
PhpMyAdmin - Replaced with https://server/adminer.php

Web UI,
What you did :
- The top bar is too dark blue color. Not feel like professional panel interface.
- The fonts are 'Exo 2'. This is not a basic font for all browsers (even though you have substituted with Arial,Helvetica etc..)
- Usability : (For eg:/list/user/) >> Only 2 user accounts viewable in a single window.

I have commented the same on vestacp also (https://forum.vestacp.com/viewtopic.php?p=76521#p73560).

all what a professional team need is :
- No need of fancy images, navigations, fonts etc.
- Simple interface with most controls. Single windows should able to see more details (Deeper details upon click)
- The basic idea is.. Something like this is better than the current interface even.. (https://forum.vestacp.com/viewtopic.php?t=12819)

**Comment by ghost** [comment]
Hi @vvcares,

Thanks for your feedback -- the user interface is currently undergoing a full redesign, and these points will be taken into consideration for when we make this available in an upcoming release.

We are aiming to develop Hestia as a lightweight, but fully functional and modern control panel to power the modern web:

- Updated fonts, icons, and color schemes will remain however these elements will be adjusted over time. The current shipping theme will be replaced in an upcoming release, as we intend to introduce proper support for custom themes (which are simply a style sheet substitution) and a dark mode as many users have said they prefer this type of scheme.

- We agree that there is far too much wasted space in the current design, and work on this has already taken place to help remedy this issue for the next release with a full redesign also underway. This redesign will see much of the user interface streamlined to provide an overview of your domains, DNS zones, mail services, and system settings with improved navigation, drilling down into the details from there. 

I am closing this issue as development around an improved mail system will take care of this for an upcoming release as well.
