### ISSUE TITLE
[BUG] Cannot add domains to users

### ISSUE THREAD

**Issue by andreas-glaser** [hestiacp/hestiacp#1893]
**Describe the bug**
Cannot add domain to users right after fresh and successful installation of 1.4.2. I'm receiving an error that the "domain exists" already but it definitely does not.

**To Reproduce**
1. Install fresh 1.4.2 panel
2. Add User
3. Add domain (sub domain of domain associated to admin main domain)

**Expected behavior**
Add domain

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.4.2

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/1889
