### ISSUE TITLE
[BUG] Change of password from RC / RL not working 

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1895]
**Describe the bug**

Anyone else having problems with this? I’ve tried it in both Roundcube and Rainloop, and I get errors in both. Not very helpful errors. I’m on latest version 1.4.2

I remember experiencing this a couple of years ago and it was due to the roundcube config not being updated with the correct HESTIA port, where it had been changed from the default. Seems the correct port is set in rainloop plugin ini file and in roundcube plugins/password/config file

I’ve tried different passwords from simple to very complex, so that’s not it either.
Roundcube logfiles in /ver/log/nginx/domains/ don’t show anything, other than the password module is being accessed. No errors.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
Change password via RC or Rainloop

**Expected behavior**
To be working 

**Operating system:**
N/A
**Hestia Control Panel version:**
1.4.2

**Additional context**
07:20:02.480][ab9ded35] AJAX[NOTE]: Action: DoChangePassword
[07:20:02.480][ab9ded35] POST[DATA]: {“PrevPassword”:"*******",“NewPassword”:“P",“Action”:“ChangePassword”,“XToken”:“606cc8737a52a95df43ebdb5b2d49e79”}
[07:20:02.484][ab9ded35] INFO[DATA]: Hestia: Try to change password for test@domain.com
[07:20:02.484][ab9ded35] INFO[DATA]: Hestia[Api Request]:https://hestia.server.com:9090/reset/mail/
[07:20:02.484][ab9ded35] INFO[DATA]: cURL: Send post request: https://hestia.server.com:9090/reset/mail/
[07:20:02.503][ab9ded35] INFO[DATA]: cURL: Post request result: (Status: 401, ContentType: )
[07:20:02.503][ab9ded35] INFO[WARNING]: cURL: Error: The requested URL returned error: 401 Unauthorized
[07:20:02.503][ab9ded35] INFO[DATA]: Hestia[Error]: Empty Response: Code:401
[07:20:03.504][ab9ded35] INFO[NOTICE]: Error: Can’t change password for test@domain.com account.
[07:20:03.504][ab9ded35] INFO[NOTICE]: RainLoop\Exceptions\ClientException: CouldNotSaveNewPassword[130] in /var/lib/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Providers/ChangePassword.php:79
Stack trace:
#0 /var/lib/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(5144): RainLoop\Providers\ChangePassword->ChangePassword(Object(RainLoop\Model\Account), '’, ‘*******P’)
#1 /var/lib/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoChangePassword()
#2 /var/lib/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(151): RainLoop\ServiceActions->ServiceAjax(’’)
#3 /var/lib/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#4 /var/lib/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#5 /var/lib/rainloop/rainloop/v/1.16.0/app/handle.php(94): RainLoop\Service::Handle()
#6 /var/lib/rainloop/rainloop/v/1.16.0/include.php(243): include(’/var/lib/rainlo…’)
#7 /var/lib/rainloop/index.php(13): include(’/var/lib/rainlo…’)
#8 {main}
[07:20:03.504][ab9ded35] AJAX[DATA]: {“Action”:“ChangePassword”,“Result”:false,“ErrorCode”:130,“ErrorMessage”:”",“ErrorMessageAdditional”:"",“Time”:1054}
[07:20:03.510][ab9ded35] INFO[MEMORY]: Memory peak usage: 4MB
[07:20:03.510][ab9ded35] INFO[TIME]: Time delta: 1.0595219135284

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/email-password-change-via-webmail-not-working/3684/3

**Comment by johnnyq** [comment]
Hi @jaapmarcus I have two Hestia instances I tested on. A new install and an old install both instances i'm able to change passwords via roundcube but not rainloop. Actually I was getting ready to open a ticket on this one but you beat me to it ;-)

**Comment by plutocrat** [comment]
Additional information in case its relevant: the roundcube version on the server is the one after running the manual upgrade script at ./install/upgrade/manual/migrate_roundcube.sh i.e not the apt version. 

head /var/lib/roundcube/CHANGELOG
CHANGELOG Roundcube Webmail
RELEASE 1.4.11

**Comment by jaapmarcus** [comment]
Closed, Will be fixed with 1.4.3

**Comment by jult** [comment]
This is not truly solved yet! I noticed that some hestia script probably retrieves its hostname from /etc/hostname, but in properly configured debian servers that hostname is actually the subdomain name only. So, if your servername is
my.server.org
the file /etc/rainloop/data/_data_/_default_/configs/plugin-hestia-change-password.ini
will have
`hestia_host = "my"`
and that should actually be
`hestia_host = "my.server.org"`

Just so you know.
My roundcube config has the proper full domain name, so it's probably just how rainloop installer does it..

**Comment by jaapmarcus** [comment]
> This is not truly solved yet! I noticed that some hestia script probably retrieves its hostname from /etc/hostname, but in properly configured debian servers that hostname is actually the subdomain name only. So, if your servername is my.server.org the file /etc/rainloop/data/_data_/_default_/configs/plugin-hestia-change-password.ini will have `hestia_host = "my"` and that should actually be `hestia_host = "my.server.org"`
> 
> Just so you know. My roundcube config has the proper full domain name, so it's probably just how rainloop installer does it..

With the installers we use hostname -f instead of hostname 

```
eris@web01:~$ hostname -f
web01.xxx
eris@web01:~$ hostname
web01
```

Maybe it is only an issue if you install it afterwards
