### ISSUE TITLE
[FEATURE] user+emailfolder@domain.tld - Support

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1896]
**Is your feature request related to a problem? Please describe.**

For example, emails sent to johndoe+booking@the.domain.tld will automatically land in the booking dir (lowercase) of John Doe's mailbox or in John Doe's inbox if booking directory doesn't exist . 

It is a practical technique for example to provide an e-mail address to a website, then easily sort (via automatic filters) the mail coming from this website.

Mailinabox and Yunohost are few I know that implement this functionality

**Describe alternatives you've considered**
manually sorting email or creating aliases, although doable can be time consuming.

**Comment by ScIT-Raphael** [comment]
Hi @johnnyq 

Thanks for your feature request. We just had a discussion in our team chat and came to the conclusion, that we do not want to implement the feature from our side. If you or someone else would like to contribute it, we will review the PR for sure and if all works properly, we would love to merge into the hestia project.
