### ISSUE TITLE
[BUG] iptables doesn't get up after server restart 

### ISSUE THREAD

**Issue by thanur** [hestiacp/hestiacp#1898]
Hi,
I checked on two servers, after rebooting iptables is red and you have to turn it on manually.

**Comment by jaapmarcus** [comment]
What is your version?

**Comment by jaapmarcus** [comment]
```
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
apt update && apt upgrade
```

Should probally do the trick. We released in 1.4.0 a version with a bug v-stop-firewall and v-update-firewall code

**Comment by thanur** [comment]
v1.4.2

**Comment by thanur** [comment]
It didn't do anything
