### ISSUE TITLE
Install mysql 

### ISSUE THREAD

**Issue by onfire-d** [hestiacp/hestiacp#190]
Hi,

Is there a way to install MYSQL instead of MariaDB and install a certain version? I have an old backup of a site and the script is not compatible with mysql/mariadb newest version so I would like to install old version and then upgrade the script to latest version which would be compatible with MariaDB newest version and then upgrade MariaDB again. 

Is ther a way to do so? Maybe by uninstalling MariaDB and then change the repo to my desired version? and run installer?

**Comment by ioannidesalex** [comment]
What version of MySQL or MariaDB would you like to install?

**Comment by ScIT-Raphael** [comment]
closed due to inactivity.
