### ISSUE TITLE
[BUG] TABS AND NEWLINE CHARS IN API IP WITELIST FIELD

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1902]
**Describe the bug**
A newly updated HESTIA install.

![image](https://user-images.githubusercontent.com/8811720/121055938-ffd7a100-c7bd-11eb-91c9-2ec426a7ae74.png)

The field is populated with TAB and NEWLINE

(It appears not to be a very important issue but who knows...)

After adding an IP, the TAB and NEWLINE chars appear again.

**Comment by jaapmarcus** [comment]
Know issue will be fixed in next release

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/1866

**Comment by jlguerrerosanz** [comment]
Thank you!
