### ISSUE TITLE
[FEATURE] Add option to whitelist domain in the API

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1903]
**I can add an IP but not a domain / subdomain**

**Comment by jaapmarcus** [comment]
It would mean we have to resolve it every time an api request is done. As we use the ip adress and not the hostname / domain / what every. 
https://github.com/hestiacp/hestiacp/blob/0abfedd8ee9d37b4c224bcf76298cd4dedefec38/web/api/index.php#L48-L55

**Comment by jlguerrerosanz** [comment]
Yes. I agree with you.

Is it too crazy? The OS should cache the resolution right?

**Comment by jaapmarcus** [comment]
Don't see a advantage in it...  What if there are issues with DNS / resolutions ...

**Comment by jlguerrerosanz** [comment]
If I have a non-static IP address I could link it to a dyndns subdomain

**Comment by jaapmarcus** [comment]
Don't think a lot of users with a dynamic ip uses the api. Even then the can also use "allow-all" without quotes...
