### ISSUE TITLE
[FEATURE] v-add-sys-whitelist-api-ip

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1904]
**There is no command line to whitelist an IP for the API**
And I don't know where  to find that list file therefore I can't automate the process in bash.

**Comment by jaapmarcus** [comment]
It is an setting so v-change-sys-config-value key value 

https://github.com/hestiacp/hestiacp/blob/0abfedd8ee9d37b4c224bcf76298cd4dedefec38/web/edit/server/index.php#L870

**Comment by jlguerrerosanz** [comment]
So it would basically run this command: v-change-sys-config-value API_ALLOWED_IP 1.2.3.4

If you enhance the documentation it is not necessary to implement this function. Since it's very easy.

**Comment by jaapmarcus** [comment]
Doesn't work for multiple ips of course. Might add an function for removing / adding ips via cli...

**Comment by jlguerrerosanz** [comment]
I love you guys.
