### ISSUE TITLE
[FEATURE] redirect template for panel from install

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#1907]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A creation of a nginx template that redirects the user directly into the hestiacp panel.

**Describe alternatives you've considered**
I've created one, it's simple but that feature, if applied will create the first domain (that's on admin user) as a redirect to hestiacp

**Additional context**
Nope, I think I've explained concisely enough to be understood...

**Comment by jaapmarcus** [comment]
With the changes in 1.4.0 you can add an simple redirect in the admin as you need. Don't like the idea of enabling for users by default. May cause security issues
