### ISSUE TITLE
[FEATURE] webmail as choosing between two programs as cpanel. 

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#1908]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A little dashboard to choose the preferred client, instead of choosing it on the hestiacp panel. Like on cpanel webmail client.

**Describe alternatives you've considered**
Creating a specific domain with both installs

**Additional context**
No further details are required in my understanding to know what I pretend as a feature.

**Comment by jaapmarcus** [comment]
I don't think it is really need we offer a lot off flexibility for the users to pick what they want...
