### ISSUE TITLE
[FEATURE] Support diacritics account name

### ISSUE THREAD

**Issue by Efkovole** [hestiacp/hestiacp#1909]
Please add support diacritics on account name. 

ěščřžýáíé not support.

**Comment by jaapmarcus** [comment]
Please explain:

<img width="219" alt="Screenshot 2021-06-09 at 14 17 44" src="https://user-images.githubusercontent.com/9754650/121352805-82cb3980-c92d-11eb-8961-8de0bd21dc80.png">

For the "name" / contact of an user it should be no issue. For usernames this is en issue on OS level where we can't do anything about

**Comment by Efkovole** [comment]
![obrazek](https://user-images.githubusercontent.com/23062975/121405689-a1e1bf80-c95d-11eb-81df-3d16388ad1fd.png)

Here is screeenshot

**Comment by jaapmarcus** [comment]
Where is exactly the error: v-add-user should work fine

https://github.com/hestiacp/hestiacp/blob/0abfedd8ee9d37b4c224bcf76298cd4dedefec38/func/main.sh#L901-L906

https://github.com/hestiacp/hestiacp/blob/0abfedd8ee9d37b4c224bcf76298cd4dedefec38/bin/v-add-user#L42-L46

Don't understand why it should work fine

**Comment by wojsmol** [comment]
@jaapmarcus This is coursed by `[:alnum:]` in the validator - see https://stackoverflow.com/a/57280495.

**Comment by Efkovole** [comment]
> Where is exactly the error: v-add-user should work fine

The error is when adding a user via the web and using the API.

**Comment by Efkovole** [comment]
In the user format validator I have the following. 

![obrazek](https://user-images.githubusercontent.com/23062975/121469999-c9687480-c9bd-11eb-8e7a-ec13a9b32ee0.png)

Shall I rewrite to:

`

# Name validator
      
      
        is_name_format_valid() {
      
      
            if ! [[ "$1" =~ ^[[:alnum:]][-|\ |\.|_[:alnum:]]{0,28}[[:alnum:]]$ ]]; then
      
      
                check_result $E_INVALID "invalid $2 format :: $1"
      
      
            fi
      
      
        }

`

**Comment by jaapmarcus** [comment]
SoSo v-add-user "Deč čečr" password email package 
or 
So v-add-user "user" password email package "Deč čečr"

The first one is not supported as spaces are not allowed in usernames

**Comment by wojsmol** [comment]
@jaapmarcus I'm referring to `v-add-user "user" password email package "Deč čečr"` so name not username.

**Comment by jaapmarcus** [comment]
@Efkovole  please provide with more what locale are you using and so one. I know we had a lot of issues with different locales  and password generation with mainly Russian locales...

**Comment by Efkovole** [comment]
> 
> 
> @Efkovole please provide with more what locale are you using and so one. I know we had a lot of issues with different locales and password generation with mainly Russian locales...

I use Czech locale Ubuntu 20.04.

**Comment by jaapmarcus** [comment]
If I change my locale to to Czech I have also the issue. So it uses UTF8 as encoding instead of the "default" one.

**Comment by Efkovole** [comment]
Where did you set the encoding to UTF8? In linux or in HestiaCP? Thank you for your help.

**Comment by jaapmarcus** [comment]
https://wiki.debian.org/Locale

**Comment by Efkovole** [comment]
I set to 
![obrazek](https://user-images.githubusercontent.com/23062975/123043764-11918900-d3f9-11eb-86ee-3bc5170adbca.png)

And the problem continues to boil over

**Comment by jaapmarcus** [comment]
I use: 
root@dev:~# echo $LANG
en_US.UTF-8 

And have no issue ...

**Comment by Efkovole** [comment]
> 
> 
> I use:
> root@dev:~# echo $LANG
> en_US.UTF-8
> 
> And have no issue ...

So I managed to solve the system I left set to: cs_CZ.UTF-8 
And I added an extra: en_US.UTF-8. Using the command dpkg-reconfigure locales and locale-gen

![obrazek](https://user-images.githubusercontent.com/23062975/123045149-d728eb80-d3fa-11eb-96fe-d17de968302a.png)

![obrazek](https://user-images.githubusercontent.com/23062975/123045288-02abd600-d3fb-11eb-879e-e53303ae468d.png)

Thank you for your help
