### ISSUE TITLE
During Install: cp: cannot stat '/usr/local/hestia/install/ubuntu/18.04/templates/web/unassigned/*': No such file or directory

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#191]
Im getting a new error during install

cp: cannot stat '/usr/local/hestia/install/ubuntu/18.04/templates/web/unassigned/*': No such file or directory

**Comment by ioannidesalex** [comment]
Will be fixed shortly.

**Comment by johnnyq** [comment]
Excellent!

**Comment by ghost** [comment]
I've patched out the section in the installer until we have new packages released and this will be fixed in the next complete release, so I'll go ahead and close this issue for now. Thanks for bringing this to our attention @johnnyq! :)
