### ISSUE TITLE
iptables doesn't get up after server restart

### ISSUE THREAD

**Issue by thanur** [hestiacp/hestiacp#1910]
```
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
apt update && apt upgrade
```

Should probally do the trick. We released in 1.4.0 a version with a bug v-stop-firewall and v-update-firewall code

_Originally posted by @jaapmarcus in https://github.com/hestiacp/hestiacp/issues/1898#issuecomment-855379643_

It does nothing, still iptables doesn't get up after "reboot" 
v1.4.2

**Comment by jaapmarcus** [comment]
There is no need to create a new issue. For support please use our forum...

**Comment by ScIT-Raphael** [comment]
The issue has already been fixed, otherwise you would not be able to upgrade to 1.4.2. So it sounds more like a support case, as @jaapmarcus wrote, please use our forum for it: https://forum.hestiacp.com

Github itself is only for issue tracking and not for support. Thanks for your understanding!
