### ISSUE TITLE
[BUG] Not possible to request LE Certificate for mail and webmail when using Rainloop

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1913]
**Describe the bug**
When requesting the LE Certificate for mail and webmail with Rainloop the following error pops up:

Error: Let's Encrypt validation status 400 (mail.domain.tld). Details: Unable to update challenge :: authorization must be pending

After investigating the logs I determined that the problem is the following wrong response to the ACME GET request:

`"Invalid response from http://mail.domain.tld/.well-known/acme-challenge/GK7gdF0_nYTnFaAcvzkk3IIarrKH2O-cwnbVe8DLbD0 [XXX.XXX.XXX.XXX]: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=""`

This is caused because the `.well-kown` is not being created to the rainloop webmail

**Operating system:**
Debian 10.9

**Hestia Control Panel version:**
1.4.2

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/a5acdb95527433c05f5c4cd631f676a702f36677/bin/v-add-letsencrypt-domain#L318-L322

**Comment by jlguerrerosanz** [comment]
Just thinking ... Would a hard link work? That way the same certificate would be installed regardless of the web mail choice.

**Comment by jaapmarcus** [comment]
No unless we detect what webmail client is running... 

Have fixed the issue in a local branch allready but didn't had the time to do some other small checks / bug fixes

**Comment by sirlensen** [comment]
Hi,
unfortunately, the correction broke the updatescript for me. In the script the followinng is called
get_object_value mail DOMAIN mail.volume6.de WEBMAIL 
` get_object_value 'mail' 'DOMAIN' "$domain" "WEBMAIL"`

but in the mail.conf the DOMAIN mail.volume6.de is not present. I think the call 
`
get_object_value 'mail' 'DOMAIN' "$root_domain" WEBMAIL`

would be correct.

Sorry for the bad english :(

**Comment by jaapmarcus** [comment]
Known issue will be fixed in next release
