### ISSUE TITLE
[BUG] Roundcube .htaccess file not present after manual upgrade.

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1917]
**Describe the bug**
In the roundcube zip file downloaded by v-add-sys-roundcube there is an .htaccess file with a few suggested values and a few more commented out. This file is not transferred correctly to /var/lib/roundcube
I believe the problem is this command in v-add-sys-roundcube (appears twice)
`    cp -rf $RC_EXTRACT/* $RC_INSTALL_DIR`
This cp command won't copy dot files 
Alternatives which might work include  
* cp -rT $RC_EXTRACT $RC_INSTALL_DIR
* Or maybe using rsync. 
* Or maybe just extracting the tar file direct into the $RC_INSTALL_DIR

Depending on what you want to achieve. 

There is also the possibility that you might wish to copy .htaccess into /etc/roundcube/ and symlink to it. I'm not sure if that's more in keeping with the Hestia house style? 

**Hestia Control Panel version:**
Latest

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/0d49ebc3438fb7ff34d329bd72c7467f7b878c57/bin/v-add-sys-roundcube#L91-L92

https://github.com/hestiacp/hestiacp/blob/0d49ebc3438fb7ff34d329bd72c7467f7b878c57/bin/v-add-sys-roundcube#L173-L174

One is for new install and the second one is for upgrades we should probally include them on install/upgrade

**Comment by jaapmarcus** [comment]
Most sense makes to use cp -rT in install and 

   $RC_INSTALL_DIR/$RC_EXTRACT/bin/installto.sh $RC_INSTALL_DIR  

How ever you have to press Y to continue it will fail during auto updates. If you have any ideas feel free to share them...

**Comment by plutocrat** [comment]
I like the fact installto.sh will leave the existing .htaccess intact, and add the new one with a .htaccess.new extension. 

```
$target_dir = unslashify(end($_SERVER['argv']));
$accept = in_array('-y', $_SERVER['argv']) ? 'y' : null;

if (empty($target_dir) || !is_dir(realpath($target_dir)))
    rcube::raise_error("Invalid target: not a directory\nUsage: installto.sh [-y] <TARGET>", false, true);
```
This would seem to indicate that you can run installto.sh with -y to approve it automatically
