### ISSUE TITLE
[BUG] Problems after upgrading to 1.4.3

### ISSUE THREAD

**Issue by EmrahKayihan** [hestiacp/hestiacp#1922]
**Describe the bug**
The following problems appeared after upgrading to 1.4.3.
-Phpmyadmin SSO option doesn't appear in the configure server options.
-When I click on the logs page then blank screen is coming.
-Spelling issue in the uptime. Example: he is writing "52 minute1" 

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.3

Upgrade logs:
```
                  _   _           _   _        ____ ____                      
                 | | | | ___  ___| |_(_) __ _ / ___|  _ \                     
                 | |_| |/ _ \/ __| __| |/ _` | |   | |_) |                    
                 |  _  |  __/\__ \ |_| | (_| | |___|  __/                     
                 |_| |_|\___||___/\__|_|\__,_|\____|_|                        
                                                                              
                    Hestia Control Panel Software Update                      
                               Version: 1.4.3                         

==============================================================================

[ ! ] IMPORTANT INFORMATION:                                                  

Default configuration files and templates may be modified or replaced         
during the upgrade process. You may restore these files from:                 

Backup directory: /root/hst_backups/150620212317/                                             
Installation log: /root/hst_backups/150620212317/hst-upgrade-150620212317.log                                                        
=============================================================================
[ ! ] Performing system health check before proceeding with installation...  
[ ! ] Adding missing variable to hestia.conf: WEBMAIL_SYSTEM ('')
[ ! ] Adding missing variable to hestia.conf: POLICY_USER_VIEW_SUSPENDED ('no')
[ ! ] Adding missing variable to hestia.conf: PHPMYADMIN_KEY ('')
[ * ] Health check complete. Starting upgrade from 1.4.2 to 1.4.3...
=============================================================================
[ * ] Backing up existing templates and configuration files...

[ - ] Now applying any necessary patches from version v1.4.3...
[ * ] Fix the issue of generate firewall rules...
[ * ] Updating File Manager...
[ ! ] Updating default web domain templates...
[ ! ] Updating default mail domain templates...
[ ! ] Updating default DNS zone templates...
[ * ] Upgrading phpMyAdmin to version v5.1.1...
=============================================================================
Installation tasks complete, performing clean-up...                          
=============================================================================
[ * ] Rebuilding user accounts and domains, this may take a few minutes...
      - admin...
      - emrah...
[ * ] Restarting services...
=============================================================================

Upgrade complete! If you encounter any issues or find a bug,                 
please take a moment to report it to us on GitHub at the URL below:          
https://github.com/hestiacp/hestiacp/issues                                  

We hope that you enjoy using this version of Hestia Control Panel,           
have a wonderful day!                                                        

Sincerely,                                                                   
The Hestia Control Panel development team                                    

Web:      https://www.hestiacp.com/                                          
Forum:    https://forum.hestiacp.com/                                        
Discord:  https://discord.gg/nXRUZch                                         
GitHub:   https://github.com/hestiacp/hestiacp/                              

Help support the Hestia Control Panel project by donating via PayPal:        
https://www.hestiacp.com/donate                                              

Made with love & pride by the open-source community around the world.        

=============================================================================

Setting up libmagickcore-6.q16-6:amd64 (8:6.9.10.23+dfsg-2.1ubuntu11.4) ...
Setting up libmagickwand-6.q16-6:amd64 (8:6.9.10.23+dfsg-2.1ubuntu11.4) ...
Setting up imagemagick-6.q16 (8:6.9.10.23+dfsg-2.1ubuntu11.4) ...
Setting up imagemagick (8:6.9.10.23+dfsg-2.1ubuntu11.4) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Log ended: 2021-06-15  23:17:45
    ```

**Comment by alber-khan** [comment]
Facing the same issues. 

![image](https://user-images.githubusercontent.com/39749258/122131481-d91d0880-ce56-11eb-9432-228257a37dd9.png)


```
allow-all is removed from API Section 
```

![image](https://user-images.githubusercontent.com/39749258/122131651-1d100d80-ce57-11eb-9bc8-b2320fb16297.png)

`
Current Number of Databases - is calculating wrong. 
`

![image](https://user-images.githubusercontent.com/39749258/122131856-6f512e80-ce57-11eb-939b-0b1b2b9431dd.png)
but when I check via PHPmyadmin i have around 9 database.
![image](https://user-images.githubusercontent.com/39749258/122132173-fdc5b000-ce57-11eb-93c4-0e170b131dcf.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/122133076-b04a4280-ce59-11eb-850b-efae9ec00426.png)

after removing php-8.0 it doesn't remove from service page
![image](https://user-images.githubusercontent.com/39749258/122133150-ceb03e00-ce59-11eb-8f26-08204638f908.png)

**Comment by alber-khan** [comment]
when running commands via CLI 

![image](https://user-images.githubusercontent.com/39749258/122133376-35355c00-ce5a-11eb-83c9-0fca33ae4a66.png)

**Comment by jaapmarcus** [comment]
> -Phpmyadmin SSO option doesn't appear in the configure server options.
Server -> Settings ->  Updates -> Enable Features  -> Save 

Then:

Server -> Settings ->  database and enable PHPmyadmin SSO feature

> -When I click on the logs page then blank screen is coming.
Indeed a bug 

> -Spelling issue in the uptime. Example: he is writing "52 minute1"
Indeed a bug 

Last 2 things I will fix

**Comment by jaapmarcus** [comment]
> 
> ```
> allow-all is removed from API Section 
> ```
> ![image](https://user-images.githubusercontent.com/39749258/122131651-1d100d80-ce57-11eb-9bc8-b2320fb16297.png)
Just tested an under 1.4.3 should work fine. I just tested on a 1.4.2 and when I said the settings they got removed ... 

> 
> `Current Number of Databases - is calculating wrong. `
> 
> ![image](https://user-images.githubusercontent.com/39749258/122131856-6f512e80-ce57-11eb-939b-0b1b2b9431dd.png)
> but when I check via PHPmyadmin i have around 9 database.
> ![image](https://user-images.githubusercontent.com/39749258/122132173-fdc5b000-ce57-11eb-93c4-0e170b131dcf.png)

Is still / and was before an issue mainly on my test server with xx databases created and then deleted and then restored... And so on I think there is currently no "command" active that sync them every day

**Comment by jaapmarcus** [comment]
> when running commands via CLI
> 
> ![image](https://user-images.githubusercontent.com/39749258/122133376-35355c00-ce5a-11eb-83c9-0fca33ae4a66.png)

Have seen the issue before what happens when you execute this command?

**Comment by alber-khan** [comment]
it removes all the php8.0 with a few other stuff like PHPMyAdmin but i was able to install PMA via migrate_phpmyadmin.sh again.

**Comment by jaapmarcus** [comment]
In older versions it phpmyadmin depend on it. Have seen the issue before it will be hard to solve. On newer systems it should not happen as we don't install phpmyadmin anymore...

**Comment by alber-khan** [comment]
> Is still / and was before an issue mainly on my test server with xx databases created and then deleted and then restored... And so on I think there is currently no "command" active that sync them every day

we can create a new script by using a `v-list-users` and after getting the json we can loop the users and get database count via `v-list-databases`?

**Comment by jaapmarcus** [comment]
Have submitted a pull request with several changes...

https://github.com/hestiacp/hestiacp/pull/1931
