### ISSUE TITLE
[Feature] pigeonhole implimentation 

### ISSUE THREAD

**Issue by steenekenm** [hestiacp/hestiacp#1924]
I have successfully added dovecot-sieve & dovecot-managesieved to hestiacp, maybe this could be part of the standard installation, it's works really well?

I am happy to share my config files if there is any interest.

Regards

**Comment by jaapmarcus** [comment]
Please create a pull request https://github.com/hestiacp/hestiacp/pulls with the required changes...

**Comment by johnnyq** [comment]
Hello @steenekenm That fantastic! Please do create a PR as @jaapmarcus suggests I have been looking for this feature and it would be a very nice addition to HestiaCP.

**Comment by steenekenm** [comment]
Hello Johnny, although I have installed and configured sieve on a couple of Hestia servers, I am not sure if I could incorporate these changes into HestiaCP.

I have not done a Pull Request before, I am happy to work with someone to include Sieve into Hestia but would require help with the Pull Request process.

Regards
Marcus

**Comment by jaapmarcus** [comment]
Please go ahead an post the changes to be made and I will see what can be done. 

Here can  some information be found on how to build a test version: https://docs.hestiacp.com/development/panel.html

**Comment by jlguerrerosanz** [comment]
@steenekenm please try at least to add the feature. It is a hell of a feature that would increase the attractive of HestiaCP as a solid solution.

**Comment by liamgibbins** [comment]
Hi did you get chance to do the pull request?.
I am interested in this aswell, I had a look at it yesterday on a test server but wasn't successful.

If you didn't manage to do a push maybe post them on the forum and they will be picked up there.. https://forum.hestiacp.com/

Thank you very much in advance

**Comment by jaapmarcus** [comment]
Added

**Comment by jlguerrerosanz** [comment]
Thank you very much @jaapmarcus

**Comment by johnnyq** [comment]
Thank you @jaapmarcus !

**Comment by liamgibbins** [comment]
Thank you for doing this, been waiting for it forever, I have tried to add it with various tutorials that have messed the mail system up ..

Thank you once again
