### ISSUE TITLE
[BUG] Cron notifications are still being sent even after they are disabled either via the web GUI or CLI.

### ISSUE THREAD

**Issue by cringeops** [hestiacp/hestiacp#1925]
**Describe the bug**
Cron notifications are still being sent even after they are disabled either via the web GUI or CLI.

**To Reproduce**
1. Disable cron notifications.
2. Wait for it...
3. Get tons of emails with execution status.

**Expected behavior**
Disabled notifications should be disabled.

**Operating system:**
20.04 LTS (GNU/Linux 5.4.0-29-generic x86_64)

**Hestia Control Panel version:**
 v1.4.3

**Comment by jaapmarcus** [comment]
Can you check /usr/local/data/users/{user}/user.conf

and crontab -u {user} -e

When the cronjobs are disabled it should be:

CRON_REPORTS='no' should be set to no and in the crontab -u {user} -e only the cronjobs should be visible

**Comment by jaapmarcus** [comment]
Please check what kind of message is send. When mysql  is down it will always send a notification via email

**Comment by cringeops** [comment]
Thank you for your reply. I have checked the directory you've provided, and it doesn't exist, but I think you meant `/usr/local/hestia/data/users/`.

`CRON_REPORTS='no'` is right there, yes.

`crontab -u admin -e` yields a default list of cronjobs.
```
*/2 * * * * sudo /usr/local/hestia/bin/v-update-sys-queue restart
10 00 * * * sudo /usr/local/hestia/bin/v-update-sys-queue daily
15 02 * * * sudo /usr/local/hestia/bin/v-update-sys-queue disk
10 00 * * * sudo /usr/local/hestia/bin/v-update-sys-queue traffic
30 03 * * * sudo /usr/local/hestia/bin/v-update-sys-queue webstats
*/5 * * * * sudo /usr/local/hestia/bin/v-update-sys-queue backup
10 05 * * * sudo /usr/local/hestia/bin/v-backup-users
20 00 * * * sudo /usr/local/hestia/bin/v-update-user-stats
*/5 * * * * sudo /usr/local/hestia/bin/v-update-sys-rrd
12 5 * * * sudo /usr/local/hestia/bin/v-update-sys-hestia-all
34 5 * * * sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl
```
When MySQL is down, Hestia spams every 5 minutes even if notifications are disabled. Therefore, I believe these notifications should honor the reports var as well.

**Comment by jaapmarcus** [comment]
Users are complaining when they don't receive a notification when a backup fails and now they are complaining when mysql is down.

The issue us caused due to the fact notifications about mysql down are send trough:
https://github.com/hestiacp/hestiacp/blob/c4151489e6054c67496c9d2b705fbb1ef8855358/func/db.sh#L62-L67

Instead of the "cron" notifications that just send all the output to the email address  will not trigger but the check ignores that setting.  I am fine with disabling notications during v-update-sys-rrd on default
