### ISSUE TITLE
[BUG] Admin login loop after auto-upgrade to 1.4.3

### ISSUE THREAD

**Issue by themew** [hestiacp/hestiacp#1927]
**Describe the bug**
A clear and concise description of what the bug is. Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
Login to Admin panel from admin login screen
Password if incorrect knows it's incorrect with an error
Using correct password reloads the Username prompt

**Expected behavior**
Admin login to panel

**Operating system:**
Debian 10.9

**Hestia Control Panel version:**
1.4.3

**Additional context**
Login with CLI and checked /var/log/hestia/auth.log and each login attempt shows 'successful'.  The incorrect login attempt that was done purposely shows 'failed to logon' so the panel is aware of the current correct admin password.

**Comment by jaapmarcus** [comment]
Only real thing that has changed is:

https://github.com/hestiacp/hestiacp/blob/2dc80972cfbb0510fbd6499cfc8bfb66ef722d8d/web/login/index.php#L222-L223

Please note we save session id inside cookies. Maybe try changing: line 223 to  false

**Comment by themew** [comment]
You're right -- looks like a cookie issue.  I deleted all cookies in the browser and same issue occurs. However, going to the admin login from a private window takes me right into the panel.

Haven't tried changing the file you mentioned @jaapmarcus to test the index.php file.

**Comment by johnnyq** [comment]
I get this same thing on every upgrade and its random on difference hestiacp hosts. 
My solution was to login as root on the shell and run passwd admin to change the password. 
I should have reported this much sooner.
My browser clears all data when closed so I don't run into cookie problems.
Its strange no one else reported this so I thought maybe my password is not escaping right during an upgrade, im not sure.

**Comment by themew** [comment]
Only mentioned it as I had never experienced this until the 1.4.3 update.  Never occurred in the 1.3.x series or 1.4.x until 1.4.3.  Going to private mode has been the easiest way to work around this until it (hopefully) is fixed in 1.4.4 :)

**Comment by jaapmarcus** [comment]
It would not explain why in private mode it works and not in "normal" mode.

**Comment by themew** [comment]
Killing all cookies from history in the browser for the domain and subdomains as well as resetting cache and cookie permissions in the browser now permits login from normal mode without the need for private mode.  Whatever was set that prevented login and looped back out but logged a successful login can be solved by a browser deep cookie cleanse.

**Comment by themew** [comment]
@jaapmarcus  And 24 hours later the bug has reared it's ugly head again, preventing login due to cookies.

**Comment by johnnyq** [comment]
Hi @themew the login issue you are experiencing appears to be isolated. The issue points back to your web browser.  More than likely it is a browser plugin or setting. Try reinstalling your browser Firefox and Chrome are supported but Hestia should work on other browsers too. Keep the defaults and don't install plugins, please report back with any findings as this could help someone else with a similar issue

**Comment by themew** [comment]
Hi @johnnyq .  Using Brave and Chromium without any plugins installed and same issue on both once the login cookies are more than 24 hours old.  The panel logs still believe I was successfully logged in even though I was kicked back to the login page.  Not at a machine where I can try Firefox at the moment to see if it's a Chrome only issue.  Also, switching to a new user account also works, but again, within 24 hours it seems the cookie prevents logging in.   Interesting that I'm the only one experiencing it.  Machines are using Arch with XFCE.

**Comment by jaapmarcus** [comment]
Replace: 
https://github.com/hestiacp/hestiacp/blob/2dc80972cfbb0510fbd6499cfc8bfb66ef722d8d/web/login/index.php#L222-L223

with session_regenerate_id();
