### ISSUE TITLE
[FEATURE] Have an option not to overwrite default.tpl

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1928]
I don't need it, but I see lots of support requests because people can't read the message asking not to touch the file. The development team might benefit of some extra time not having to deal with people who don't know what they're doing and don't mind to edit a file that will be overwritten.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/web/nginx/default.stpl#L1-L4

But this is not the real issue users "manually" edit the config files directly.
