### ISSUE TITLE
[BUG]admin → backup failed

### ISSUE THREAD

**Issue by ohmichael** [hestiacp/hestiacp#1935]
**Describe the bug**
I keep getting e-mails from myself through the domain - what is weird I have not even set up an email client - but through hestiacp I have been getting flooded with e-mails saying "not enough diskspace available to perform the backup." what that means I have no idea because I just got my server and I have 30gb of disk space from what I remember so I know I am not over the limit.
**To Reproduce**
What steps did you take when the issue occured? 
no steps I have no clue what to do
**Expected behavior**
I expected it to backup my panel and be through with it but I keep getting emailed saying I have not enough storage every 5 minutes.
**Screenshots**
I can't screenshot - screenshot would contain sensitive information.
**Operating system:**
Please enter your answer here (e.g. Ubuntu 20.04 LTS)
Debian 10
**Hestia Control Panel version:**
Please enter your answer here (e.g. 1.3.2). 
1.4.3
**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.
I would like to know how I can shut off these e-mails through my domain and to turn off backups since they do not work. My website is running fine it's just backups is flooding me with constant emails.

**Comment by jaapmarcus** [comment]
There was a bug where a message was never created when a backup failed for any unknown reason. We have patched this issue ... 

```
nano /usr/local/hestia/data/queue/backup.pipe and remove the line that creates the backup.
```

This will stop the email message.

For backups: It is required to have at least 2x the total backup available on the server it self.

1. Check what your current free disk space is  and what the amount of disk usage it. It might be an idea to split them up in multiple accounts

**Comment by ohmichael** [comment]
the line says 
/usr/local/hestia/bin/v-backup-user admin yes >> /usr/local/hestia/log/backup.log 2>&1  
do i remove this and save it

**Comment by jaapmarcus** [comment]
Yes

**Comment by ScIT-Raphael** [comment]
Going to close the issue, because it's a support request and has already been answered. For the future, please use our forum or discord channel - we try to split github for issues and features only.
