### ISSUE TITLE
[BUG] Can not auth /login

### ISSUE THREAD

**Issue by inpakeo** [hestiacp/hestiacp#1937]
**Describe the bug**
After last update can not auth to hestia cp 

**To Reproduce**
What steps did you take when the issue occured? 
1. Go to /login/
2. Type login, type password
3. No error in console or other things 

**Expected behavior**
Want access to admin

**Screenshots**
No screen

**Operating system:**
Debian 9

**Hestia Control Panel version:**
1.4.3

**Additional context**
Before update all be ok

My auth config
LOGIN_STYLE='default'
THEME='dark'

**Comment by theotherpeople** [comment]
Try to remove cookies.

https://github.com/hestiacp/hestiacp/issues/1927

**Comment by jlguerrerosanz** [comment]
Try to enable cookies

**Comment by inpakeo** [comment]
yeap thanks!
