### ISSUE TITLE
[BUG] Leftover /etc/nginx/conf.d/domains/domain.conf link when deleting subdomain

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1938]
**Describe the bug**
The user makes a mistake in a subdomain, and deletes the subdomain but the /etc/nginx/conf.d/domains/subdomain.conf link remains and breaks when the subdomain is deleted.

Nginx doesn't restart and whole server is down.

**To reproduce**
create user: domain.com
create subdomain with an error: subdomain (instead of subdomain.domain.com)
delete subdomain

nginx: [emerg] open() "/etc/nginx/conf.d/domains/subdomain.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:160
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by jaapmarcus** [comment]
root@test:/etc/nginx/conf.d/domains# v-add-user jaap.xxx 1234 me@jaap.xxx
root@test:/etc/nginx/conf.d/domains# v-add-web-domain jaap.xxx test 
root@test:/etc/nginx/conf.d/domains# v-list-web-domains  jaap.xxx
DOMAIN   IP   TPL   SSL   DISK   BW   SPND   DATE

test x.x.x.x default no 0 0 no 2021-06-22
root@test:/etc/nginx/conf.d/domains# v-delete-web-domain jaap.xxx test
root@test:/etc/nginx/conf.d/domains# nginx -t

**Comment by jlguerrerosanz** [comment]
Could you reproduce it?

**Comment by jaapmarcus** [comment]
Yes if 

        "PROXY_TEMPLATE": "",

is missing from the user config like this I can replicate the issue but that should normally not need to happen.

**Comment by jlguerrerosanz** [comment]
> but that should normally not need to happen.

So we have a hidden bug causing this issue.

I can share my server deployment scripts with you. Everything I do is pretty standard (I think).

Can we bullet-proof the deletion script? So that it doesn't work we could still delete the domain and start over again?

**Comment by jaapmarcus** [comment]
If no "PROXY_TEMPLATE" has been set in user.conf and proxy_system is active the file is still created. Assiged an default PROXY_TEMPLATE is var is "missing"

Also when $PROXY is not set we will try to delete the file any way
