### ISSUE TITLE
[BUG] v-add-web-domain cant find template files

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1939]
**Describe the bug**
When I execute v-add-web-domain
$HESTIA/bin/v-add-web-domain username domain.es

I get the following error.
cat: /usr/local/hestia/data/templates/web/apache2/.tpl: No such file or directory
cat: /usr/local/hestia/data/templates/web/nginx/.tpl: No such file or directory

Debian 10
Hestia - 1.4.3

**Comment by jaapmarcus** [comment]
v-list-user user json should list 

```
        "WEB_TEMPLATE": "default",
        "BACKEND_TEMPLATE": "default",
        "PROXY_TEMPLATE": "default",
```

If it is not set it might be the reason why. I have no issue on a test server from mine (Clean server)

**Comment by jlguerrerosanz** [comment]
"WEB_TEMPLATE": "",
        "BACKEND_TEMPLATE": "default",
        "PROXY_TEMPLATE": "",

Okay. it is not set. 

I corrected the second issue with:
v-add-web-domain-proxy user example.com default

**Comment by jaapmarcus** [comment]
Set the correct settings in the user.conf and it should be fixed then. Don't know why those values are empty

**Comment by jlguerrerosanz** [comment]
I never touched user.conf

Where is that file located?

**Comment by jaapmarcus** [comment]
/usr/local/hestia/data/users/user/user.conf

**Comment by jlguerrerosanz** [comment]
Is there a default user.conf template or is it the plan template?

This is my web.pkg file. The one that I use

WEB_TEMPLATE='default'
BACKEND_TEMPLATE='default'
PROXY_TEMPLATE='default'
DNS_TEMPLATE='default'
WEB_DOMAINS='5'
WEB_ALIASES='unlimited'
DNS_DOMAINS='0'
DNS_RECORDS='unlimited'
MAIL_DOMAINS='0'
MAIL_ACCOUNTS='unlimited'
DATABASES='5'
CRON_JOBS='unlimited'
DISK_QUOTA='unlimited'
BANDWIDTH='unlimited'
NS=','
SHELL='nologin'
BACKUPS='1'
TIME='09:20:12'
DATE='2021-06-22'

**Comment by jaapmarcus** [comment]
packagename.pkg is used

**Comment by jlguerrerosanz** [comment]
So why is my web.pkg not copying all the configuration upon user creation.

hst_plan=web
$HESTIA/bin/v-add-user $username $hst_password $hst_email $hst_plan

My install script only uses this command. Is there a second command missing?

**Comment by jaapmarcus** [comment]
root@test:/etc/nginx/conf.d/domains# v-add-user test test me@jaap.xxxxx web  
root@test:/etc/nginx/conf.d/domains# v-list-user test json
{
    "test": {
        "NAME": "",
        "PACKAGE": "web",
        "WEB_TEMPLATE": "default",
        "BACKEND_TEMPLATE": "PHP-7_4",
        "PROXY_TEMPLATE": "hosting",
        "DNS_TEMPLATE": "default",
       ........  ......
      }
}

Seems to work fine

**Comment by jaapmarcus** [comment]
See #1938 or #1940 

Why v-add-user has issues I have no idea...
