### ISSUE TITLE
[BUG] MariaDB service fails to start

### ISSUE THREAD

**Issue by ayoubamine** [hestiacp/hestiacp#1942]
**Describe the bug**
MariaDB service fails to start/restart from the GUI.

Cron job `sudo /usr/local/hestia/bin/v-update-sys-rrd` email notification content:

```
Can't connect to MySQL localhost
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)
```

`sudo systemctl status mariadb`

```
● mariadb.service - LSB: Start and stop the mysql database server daemon
     Loaded: loaded (/etc/init.d/mariadb; generated)
    Drop-In: /etc/systemd/system/mariadb.service.d
             └─migrated-from-my.cnf-settings.conf
     Active: active (exited) since Wed 2021-06-23 09:52:23 UTC; 42min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 23170 ExecStart=/etc/init.d/mariadb start (code=exited, status=0/SUCCESS)

Jun 23 09:52:23 **** systemd[1]: Starting LSB: Start and stop the mysql database server daemon...
Jun 23 09:52:23 **** systemd[1]: Started LSB: Start and stop the mysql database server daemon.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/30782991/123080719-22e88e80-d415-11eb-8079-1df68ad5e886.png)

**Operating system:**
Ubuntu 20.04 (x86_64)

**Hestia Control Panel version:**
v1.4.3

**Additional context**
The "Turn on/off notifications" button does not take any effect to stop receiving email notifications every 5min, I suspended temporarily the `sudo /usr/local/hestia/bin/v-update-sys-rrd` cron job to stop sending emails.

**Comment by ScIT-Raphael** [comment]
Please do not use github for support requests, we only use it for issue reports. The reason in your case is that mysql is not up and running, that's why v-update-sys-rrd fails and you get mails every 5 minutes. You need to find out why mysql hangs and fix it.
