### ISSUE TITLE
[BUG] The time active for the services list displays a number "1" after.

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1944]
![image](https://user-images.githubusercontent.com/8811720/123261999-b8f4e580-d4f7-11eb-85b9-70fdd7bc8ab9.png)

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1931/commits/fb7c67557951b85c8a331c266ff113ca32161dbb

Will fix it.  Will be released with 1.4.4

**Comment by jaapmarcus** [comment]
If you have time please update:

https://translate.hestiacp.com/projects/hestiacp/es/default/

**Comment by jlguerrerosanz** [comment]
Done!
