### ISSUE TITLE
[BUG] domain belongs to a different user

### ISSUE THREAD

**Issue by saaiful** [hestiacp/hestiacp#1946]
![image](https://user-images.githubusercontent.com/4525049/123460927-33ae2580-d60a-11eb-8102-b2c96224a0ea.png)

Getting this error while creating a new video domain (I'm using a subdomain that belongs to another user). I used another subdomain before and it worked before. After the latest update is stopped working.

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/settings.html#what-does-the-policy-enforce-subdomain-ownership-mean
