### ISSUE TITLE
ADMIN login name & display disk usage on server level

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#1950]
Hi team,
1. In this awesome control panel, may add more enhanced security matters like ability to change/custom the admin login name. Because this name is globally general.
2. Hestia page : /list/server/ : Add simple disk usage info - server level. This will help us to keep the disk usage for hestia-bkp tasks.

**Comment by jaapmarcus** [comment]
You can create a new user and assign him administrator permissions. Then go to the admin login and disable login for this user.

**Comment by vvcares** [comment]
Wow. Ok, thank you

**Comment by jaapmarcus** [comment]
/list/server/?disk

For the disk usage...  I will close the issue

**Comment by vvcares** [comment]
Hi. superb.. 
Im mentioning something like below link..
[https://ibb.co/KrGbmJr]   https://ibb.co/KrGbmJr
