### ISSUE TITLE
Unable to add FTP as remote backup if username ends with @domainname.tld

### ISSUE THREAD

**Issue by avinashpudota** [hestiacp/hestiacp#1954]
I am trying to add an FTP location as remote backup.
The username is given as ftpuser@domainname.com. If i enter the username in this way it says “Error: invalid user format ::” if i remove the @domainname.com it says “Error: can’t login to ftp”

I am able to login via filezilla using username ftpuser@domainname.com

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/unable-to-add-ftp-as-remote-backup/3894/2

**Comment by vanengers** [comment]
I have the same issue. Is there a fix ready? Or how do i fix this?

**Comment by jaapmarcus** [comment]
I have made some changes is somebody has test account available where I can upload an back up please contact me on discord...

**Comment by jaapmarcus** [comment]
Issue should be solved.
