### ISSUE TITLE
[BUG] Self-Signed SSL Generator Fail

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#1955]
Installing fresh hestiacp. And try to use ssl generator. But only SSL key is generated. The other two textarea is empty ( SSL Certificate & SSL Certificate Request )

**Comment by jaapmarcus** [comment]
If you use  Ubuntu 18.04 also enter an email adress for some stupid reason email is then not optional...

**Comment by erikdemarco** [comment]
Yes its working now. Maybe we should make it required. So it same across platform. And user will not think its a bug.

**Comment by jaapmarcus** [comment]
It was before an requirement but all the other OS doesn't require it except for some strange reason Ubuntu 18.04. Probally just add an check for Ubuntu 18..
