### ISSUE TITLE
[BUG]After Update - Webmail setting reverted from Rainloop back to Roundcube

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1956]
**Describe the bug**
When we performed the update from 1.4.3 to 1.4.4 we noticed the webmail for domains that we switched to Rainloop reverted back to Roundcube. Its an easy fix as we just switched it back for the domains. 

**To Reproduce**
What steps did you take when the issue occured? 
1. Install Rainloop on a 1.4.3 instance
2. Change webmail for a domain to rainloop
3. Update Hestia to 1.4.4

**Expected behavior**
On update the webmail setting should carry on after upgrade

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
1.4.3 to 1.4.4

**Comment by ScIT-Raphael** [comment]
Fixed in 1.4.5 which just has been released now.
