### ISSUE TITLE
[FEATURE] Prevent PHP 7.4 from uninstalling if file manager is active

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1957]
I have seen some people deal with this in the forum. 

Is it possible to show a warning somehow?

**Comment by jaapmarcus** [comment]
"We" might need to check if hestia-php can be used but we are considering it also upgrading to 8.x soon.

**Comment by jaapmarcus** [comment]
The solution is probably switch to composer 2 for FM updates. Might be an older install or not ... Hard to know

**Comment by jaapmarcus** [comment]
We have addd In Hestia-php 7.4.22 openssl with the next release we are going to use Hestia-php instead
