### ISSUE TITLE
[BUG]  phpmyadmin SSO isn't working

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1958]
**Describe the bug**
![image](https://user-images.githubusercontent.com/39749258/124127963-f0383900-da99-11eb-8e9f-1b92bb506edf.png)

**To Reproduce**
OPEN SSH
and run `v-add-sys-pma-sso`

go to the DB tab and select the database you want to open.

![image](https://user-images.githubusercontent.com/39749258/124128234-32617a80-da9a-11eb-8d6d-fb5a19f7fd8b.png)

**Expected behavior**
should be able to log in to PMA without any issues.
**Operating system:**
Ubuntu 20.04 LTS
**Hestia Control Panel version:**
1.4.5

**Comment by alber-khan** [comment]
actually PHPMyAdmin isn't working after updating to 1.4.5

**Comment by jaapmarcus** [comment]
What setup are you using?

In case mod-php + apache2 you have to use see:
Added new template for mod php users to access phpmyadmin

**Comment by neto737** [comment]
Hi,

I was facing the same problem.

It was solved after upgrading my phpMyAdmin manually (I'm using Debian, so I ran  /usr/local/hestia/install/upgrade/manual/migrate_phpmyadmin.sh)

It's important to point that my server is running the same Hestia installation since version 1.3.0, I don't know if you're using a new installation or an old one

**Comment by jaapmarcus** [comment]
We have changed a lot the permissions on where phpmyadmin is running under. Before 1.4.3 you could access the phpmyadmin config files as user and it is considered as a bad idea.  This should be fixed but I think I missed the fact we need to refresh apache2 config... 

Incase of Nginx + Apache2 + FPM (Default since 1.2.0) : 

Solution: v-change-sys-db-alias pma phpmyadmin

https://docs.hestiacp.com/cli_commands/commands.html#v-change-sys-db-alias

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/124136619-90925b80-daa2-11eb-8cca-9a6e0685cf78.png)
Server MPM: event

**Comment by jaapmarcus** [comment]
@4183r  v-change-sys-db-alias pma phpmyadmin should be enough. 

Still checking why Nginx + PHP-FPM has issues

**Comment by alber-khan** [comment]
@jaapmarcus i'm using Nginx + Apache2 + PHP-FPM

**Comment by johnnyq** [comment]
Im not able to access the one click db function either. I just enabled it in this release 1.4.5. I click edit database and it just takes me to login page for phpmyadmin. I tried deleting pma and re-adding it. and tried the command v-change-sys-db-alias pma phpmyadmin with no luck.

My installation is Nginx Apache php-fpm

**Comment by promoweb** [comment]
Same problem with Roundcube, after updating HestiaCP a white screen appears.

Operating system:
Debian 10
Hestia Control Panel version:
1.4.5

**Comment by ScIT-Raphael** [comment]
@promoweb with or without apache2?

**Comment by ScIT-Raphael** [comment]
@johnnyq have you noticed and tried https://github.com/hestiacp/hestiacp/issues/1958#issuecomment-872272062

**Comment by promoweb** [comment]
> @promoweb with or without apache2?

 With Nginx + Apache2 + PHP-FPM

**Comment by ScIT-Raphael** [comment]
This sounds like a different issue. I suggest to check the web logs for any related things, then either open a forum thread or a new issue report.

**Comment by promoweb** [comment]
> This sounds like a different issue. I suggest to check the web logs for any related things, then either open a forum thread or a new issue report.

Ok, but I think it's caused by the change in file permissions. This is the error that causes the white screen.

`Unsupported database driver:  in /usr/share/roundcube/program/lib/Roundcube/rcube.php on line 1364`

**Comment by johnnyq** [comment]
@ScIT-Raphael I just tried /usr/local/hestia/install/upgrade/manual/migrate_phpmyadmin.sh and still getting the phpMyadmin login screen I also tryed adding sso and then deleting it then adding it again and still no go.

**Comment by neto737** [comment]
@ScIT-Raphael I'm not sure about that, but I ran some tests on my server.

My results:

If I remove all allowed IPs for API (even allow-all) the SSO doesn't work properly.

If I allow 127.0.0.1 it still doesn't work.

If I allow my server IP or "allow-all" it works.

I'm not sure if it's the correct behaviour to the SSO system, but it's whats happening on my side

**Comment by jaapmarcus** [comment]
127.0.0.1 is by default enabled. Need to check how requests are send on a nginx + apache2  setup... 

 We have changed the permissions of the files due to a security issue and this may all cause it... Need to investigate what is going wrong. But it will not happen before Monday / Tuesday.

**Comment by alber-khan** [comment]
> @ScIT-Raphael I'm not sure about that, but I ran some tests on my server.
> 
> My results:
> 
> If I remove all allowed IPs for API (even allow-all) the SSO doesn't work properly.
> 
> If I allow 127.0.0.1 it still doesn't work.
> 
> If I allow my server IP or "allow-all" it works.
> 
> I'm not sure if it's the correct behaviour to the SSO system, but it's whats happening on my side

Thank you @neto737  I was having the same issue with another server. putting `allow-all` fix the SSO issue.

![image](https://user-images.githubusercontent.com/39749258/124262185-57fc8b80-db4f-11eb-80da-967c46833a38.png)

**Comment by jaapmarcus** [comment]
Changed a few things with the permissions and it works now 100% of the time.  I haven't tested it with Apache2 in standalone mode but officially it is not supported any more
