### ISSUE TITLE
[BUG] %proxy_extensions% not returning any value

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#1959]
When you see this ' hestiacp/install/deb/templates/web/nginx/default.tpl ':

`location ~* ^.+\.(%proxy_extensions%)$ {`

it using '%proxy_extensions%' instead of '%proxy_extentions%'
When you use '%proxy_extensions%' you will get blank value.

Just see all the conf files for domain in '/etc/nginx/conf.d/domains'
You will see that part will be like :
`location ~* ^.+\.()$ {`

But if you use:
`location ~* ^.+\.(%proxy_extentions%)$ {`

All that part will be:
`location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|tif|tiff|css|js|htm|html|ttf|otf|webp|woff|txt|csv|rtf|doc|docx|xls|xlsx|ppt|pptx|odf|odp|ods|odt|pdf|psd|ai|eot|eps|ps|zip|tar|tgz|gz|rar|bz2|7z|aac|m4a|mp3|mp4|ogg|wav|wma|3gp|avi|flv|m4v|mkv|mov|mpeg|mpg|wmv|exe|iso|dmg|swf)$ {`

**Comment by erikdemarco** [comment]
Fixed.

**Comment by jaapmarcus** [comment]
It has been befixed in 1.4.2 

            -e "s/%proxy_extentions%/${PROXY_EXT//,/|}/g" \
            -e "s/%proxy_extensions%/${PROXY_EXT//,/|}/g" \
