### ISSUE TITLE
[BUG] After updating to 1.4.5 on Roundcube webmail client a white page appears

### ISSUE THREAD

**Issue by promoweb** [hestiacp/hestiacp#1960]
After updating to HestiaCP 1.4.5 on Roundcube webmail client a blank page appears whith the notice:

No input file specified.

Operating system:
Debian 10 with Nginx + Apache2 + PHP-FPM

Hestia Control Panel version: 
1.4.5

Apache Log Error:
AH01071: Got error 'PHP message: PHP Warning:  Unknown: open_basedir restriction in effect. File(/var/lib/roundcube/index.php) is not within the allowed path(s).

**Comment by jaapmarcus** [comment]
Can you please check what is inside  /etc/php/7.4/fpm/pool.d/www.conf 

By default this template should be used. Or are you using https://domain.com/webmail/

**Comment by promoweb** [comment]
Until the last update I had been using https://domain.com/webmail/ without problems for over a year.

Content of /etc/php/7.4/fpm/pool.d/www.conf:     

; origin-src: deb/php-fpm/www.conf

[www]
listen = 127.0.0.1:9000
listen.allowed_clients = 127.0.0.1

user = www-data
group = www-data

pm = ondemand
pm.max_children = 4
pm.max_requests = 4000
pm.process_idle_timeout = 10s

**Comment by jaapmarcus** [comment]
Add  

https://github.com/hestiacp/hestiacp/blob/b688e7b7213cb9b4aa8198cbb382f9faa436a8bd/install/deb/pma/apache.conf#L20-L25

To the alias config for webmail. Depending on your setup I assume it will be /etc/apache2/conf.d/webmail.conf?

We have strengthen the security for  and removed all the not needed open base_dir out the php exclusions

**Comment by jaapmarcus** [comment]
Other option would be creating an fpm template and assign open base dir to roundcube...

**Comment by promoweb** [comment]
> Add
> 
> https://github.com/hestiacp/hestiacp/blob/b688e7b7213cb9b4aa8198cbb382f9faa436a8bd/install/deb/pma/apache.conf#L20-L25
> 
> To the alias config for webmail. Depending on your setup I assume it will be /etc/apache2/conf.d/webmail.conf?
> 
> We have strengthen the security for and removed all the not needed open base_dir out the php exclusions

I added the code to the Roundcube configuration file for Apache which in Debian 10 is /etc/apache2/conf.d/apache.conf

Now it works again, thanks.
