### ISSUE TITLE
[BUG] Let's encrypt mail/webmail certificate renew bug. Error: Let's Encrypt validation status 400...

### ISSUE THREAD

**Issue by endrepavel** [hestiacp/hestiacp#1961]
**Describe the bug**
Let's encrypt mail/webmail certificate renew bug.

v-add-letsencrypt-domain user foo.bar ' ' mail
Error: Let's Encrypt validation status 400 (mail.foo.bar). Details: Unable to update challenge :: authorization must be pending

Use $domain instead of $root_domain.

**To Reproduce**
v-add-letsencrypt-domain user foo.bar ' ' mail

Expected behavior
file:/usr/local/hestia/bin/v-add-letsencrypt-domain

```
--- /usr/local/hestia/bin/v-add-letsencrypt-domain	2021-07-02 10:54:49.155579430 +0200
+++ v-add-letsencrypt-domain.new	2021-07-02 14:29:32.057930974 +0200
@@ -331,7 +331,7 @@
                     check_result $? "Proxy restart failed" > /dev/null
                 fi
             else
-                get_object_value 'mail' 'DOMAIN' "$domain" "WEBMAIL"
+                get_object_value 'mail' 'DOMAIN' "$root_domain" 'WEBMAIL'
                 if [ ! -z "$WEBMAIL" ]; then
                     well_known="/var/lib/$WEBMAIL/.well-known"
                     acme_challenge="$well_known/acme-challenge"
```

**Operating system:**
Debian GNU/Linux 10

**Hestia Control Panel version:**
1.4.5

**Comment by jaapmarcus** [comment]
I am assuming you are using Apache2 + PHP-FPM?

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/1972

We will release 1.4.6 soon
