### ISSUE TITLE
[BUG?] Can't edit and change count of backups in default package

### ISSUE THREAD

**Issue by iT0mT0m** [hestiacp/hestiacp#1970]
**Describe the bug**
In earlier version of HestiaCP I could edit default package and set count of backup. Actually default package is not edited.

What steps did you take when the issue occured? 
1. Log in to Panel
2. Click Package in Users Tab
3. Click default and website is refreshed

**Expected behavior**
Will it be restored or do I need to create own modified versions of packages?

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.4.5

**Comment by tlcd96** [comment]
https://github.com/hestiacp/hestiacp/blob/main/web/edit/package/index.php#L22~L26

It was disabled on this update, the default package it's not supposed to be used as a normal package, you have to create a new package or  duplicate the default one. This behavior was added in hestiacp version 1.4.0
