### ISSUE TITLE
[SUPPORT] Why Hestia doesnt use internal dns as its dns resolver?

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#1971]
Hi,

I install hestia with bind/named included.

When I add a fake domain to hestia for example like xyzxyzxyz.com (hestia will add dns record for this domain)

So logically If I access this domain via php using gethostbyname('xyzxyzxyz.com'), it should resolve to our ip. But its not. Instead it ask external dns to resolve this domain (it fail because thi domain is not exist on internet)

Why hestia not making internal dns as its dns resolver? And making external resolver as a backup.

It will be good because: Resolving domain which has been added to hestia will be much much more faster. We dont need to ask external dns resolver for our domain. So we will access the server faster.

For example If we behind the cloudflare. And want to communicate with any of our internal website via rest api. This request will go to CF server first, before routed to our server. which took so long route

This is how i successfully make hestia use internal dns as first priority:
-) I add 'nameserver 127.0.0.1' before other nameserver (but this file will be reseted everytime i do a reboot)

NOTES:
-) editing '/etc/hosts' will fail. Because php/curl ignore this file
-) editing '/etc/dhcp/dhclient.conf' or '/etc/network/interfaces' will fail because hestiacp doenst use 'dhclient' nor 'ifup'
-) editing '/etc/systemd/resolved.conf' with ReadEtcHosts=yes also fail

**Comment by jaapmarcus** [comment]
Please use 
https://forum.hestiacp.com

We want to keep support and bugs seperated
