### ISSUE TITLE
[BUG] failed to make connection to backend

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#1976]
**Describe the bug**
[Wed Jul 07 23:01:02.931045 2021] [proxy_fcgi:error] [pid 1685931:tid 140146647234304] [client 103.145.227.81:0] AH01079: failed to make connection to backend: httpd-UDS
 
after adding the domain via api.

**To Reproduce**
https://docs.hestiacp.com/admin_docs/api/rest_api.html#add-web-dns-mail-domain
Using this method to create the user.

when opening the domain I'm getting error
![image](https://user-images.githubusercontent.com/39749258/124804188-a35fd100-df77-11eb-95f7-9ea586c44bc3.png)

when checking the error log 
`[Wed Jul 07 23:01:02.931045 2021] [proxy_fcgi:error] [pid 1685931:tid 140146647234304] [client 103.145.227.81:0] AH01079: failed to make connection to backend: httpd-UDS`

**Expected behavior**
Domain should work fine.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
v1.4.5

**Comment by alber-khan** [comment]
`
[Wed Jul 07 23:05:38.921347 2021] [proxy:error] [pid 1685931:tid 140146502518528] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm-student.domain.test.sock (*) failed
[Wed Jul 07 23:05:38.921371 2021] [proxy_fcgi:error] [pid 1685931:tid 140146502518528] [client 103.211.19.168:0] AH01079: failed to make connection to backend: httpd-UDS
`

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/1236

Known issue issue is solve able to set restart to no 

And then run v-restart-service apache2 no 

It will reload the config instead of restarting

**Comment by jaapmarcus** [comment]
And also use the search function...
