### ISSUE TITLE
[FEATURE] Auto generate self signed certificate when add domain

### ISSUE THREAD

**Issue by aktolu** [hestiacp/hestiacp#1977]
I think would be awesome, when add domain auto checked **SSL support** option and auto generate **Self Signed Certificate**.

**Comment by jaapmarcus** [comment]
I don't think an self generated ssl is useful at all as it doesn't work in any browser.. 

As there was a delay of 5 minutes before generating and if then no notification was send if it was succeeded. The 5 minutes delay was there to sync DNS records in the case if there was DNS cluster...  If creating a domain fails you still needed to go to the edit domain page.

**Comment by aktolu** [comment]
> I don't think an self generated ssl is useful at all as it doesn't work in any browser..

That is correct. For use on Cloudflare with SSL we don't need Let's Encrypt but we need activate SSL. When nameservers directed to Cloudflare, we can't activate Let's Encrypt, so we have only one option, it's self signed certificate.

**Comment by ScIT-Raphael** [comment]
Not directly, this is the way to go: https://docs.hestiacp.com/admin_docs/web/ssl_certificates.html#can-i-use-a-cloudflare-origin-ssl-certificate-with-cloudflare
