### ISSUE TITLE
[BUG] All mysql conf gone after installation finished.

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#1979]
I  you see this line in source code:
https://github.com/hestiacp/hestiacp/blob/6eaf813be53f0d5a24d1a32dfc6964b0bc849a29/install/hst-install-ubuntu.sh#L1445

You know hestiacp automatically copy configuration files based on system performance to '/etc/mysql/my.cnf'. The configuration can be any of these:
https://github.com/hestiacp/hestiacp/tree/main/install/deb/mysql

So lets install hestiacp using regular installation process:
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
bash hst-install.sh

After installation finished, lets check the configuration using:
sudo nano /etc/mysql/my.cnf

All gone! It gets resetted to mysql default

But if during installation we exclude some of the package for example using this comand instead:
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
bash hst-install.sh -v no -x no -z no -c no -t no

Then when you check 'sudo nano /etc/mysql/my.cnf'. The configuration is correct. Not get resetted to mysql default

**Comment by jaapmarcus** [comment]
I have tested it on Debian 11 an it works with out any issues

**Comment by jaapmarcus** [comment]
It seems to be Ubuntu issue

**Comment by jaapmarcus** [comment]
We have made some changes to the installer script. It is a strange issues as both installers should delete the file first before overwriting it with the new version
