### ISSUE TITLE
[BUG] phppgadmin throwing configuration error

### ISSUE THREAD

**Issue by mach0** [hestiacp/hestiacp#1984]
This is basically a copy of issue #872

### In a few words, please describe the issue that you're experiencing:
error accessing phppgadmin.
updated hestiacp to version 1.4.6

Accessing https://domainname/phppgadmin gives:
Configuration error: Copy conf/config.inc.php-dist to conf/config.inc.php and edit appropriately.
 
### What steps did you take when the issue occured? 
1. Ex.: Log into the Hestia Control Panel using Firefox or Chrome
2. Ex.: go to an existing domain on the server and try to access the phppgadmin panel

### Expected behavior:
Access to phppgadmin allowed and functional

### Does this issue always occur, or is it intermittent?
always

### Operating system distribution and release:
debian 10 buster

### Which version of Hestia Control Panel is currently installed?
1.4.6

### Which branch are you using?
stable (automated update)

### When did this issue occur? After a clean installation, or after an upgrade?
after upgrade to 1.4.6 though I think I did not use phppgadmin in version 1.4.5

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP
- PHP-FPM + Multi-PHP

If someone tries to explain where this is configured and how it could be kept updated I am willing to update phppgadmin and take care that it works.

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/issues/872

We have added some security improvements regarding permissions as you where able to access certain folders and files as user... 

The changes suggested in #872 should work. I will install a new test server and try it quickly.. 

Anyway needs some love ❤️

**Comment by mach0** [comment]
thanks for the quick answer - the fix works!! 

needs some love is also true - phppgadmin is at version 7.13 - hestia uses 5.1
I already tried to work on a script updating phppgadmin to the new version but as already said, I think I do not completely understand the connections yet..
If there is anything I can do to help here just drop me a note.

**Comment by jaapmarcus** [comment]
Feel free to submit a PR request with the fix if not possible I will do it later...
