### ISSUE TITLE
Error: Let's Encrypt validation status 400

### ISSUE THREAD

**Issue by VPS21** [hestiacp/hestiacp#1985]
After updating to hestiacp v1.4.6, the following issue arose during SSL activation.

`Error: Let's Encrypt validation status 400 (domain.info). Details: Unable to update challenge :: authorization must be pending`

This problem also occurs when enabling SSL to the hostname of the new VPS.

Vestacp does not have this problem. I also installed and tested it.

Does not use cloudflare or firewall

**Comment by jaapmarcus** [comment]
See: https://docs.hestiacp.com/admin_docs/web/ssl_certificates.html#error-let-s-encrypt-validation-status-400

**Comment by jaapmarcus** [comment]
Can confirm it is a bug with in Hestia

**Comment by AlexBO222** [comment]
Same thing, 1.4.6 does not get LE certificates. 10 VPS on 1.4.5 - receives LE certificates normally.

And bug (1.4.5 also):
When adding a third-level domain, the www. alias is not automatically added.
But the DNS record www. is added.

**Comment by ScIT-Raphael** [comment]
Already confirmed as bug and fixed on main, preparing the release of 1.4.7.

**Comment by jaapmarcus** [comment]
> When adding a third-level domain, the [www](http://www). alias is not automatically added.
> But the DNS record [www](http://www). is added.

We need to rewrite parts of the code to solve this. Know issues

**Comment by youradds** [comment]
Good to know it wasn't just me then :) (although, I just spent 2 hours trying to debug haha)

**Comment by VPS21** [comment]
> Already confirmed as bug and fixed on main, preparing the release of 1.4.7.

Thank you very much. I was tired for about 6 hours not being able to fix this problem

**Comment by VPS21** [comment]
> Good to know it wasn't just me then :) (although, I just spent 2 hours trying to debug haha)

so did I

**Comment by VPS21** [comment]
> Can confirm it is a bug with in Hestia

Yes, thank you very much

**Comment by jaapmarcus** [comment]
Please update the systems we have released 1.4.7
