### ISSUE TITLE
[BUG] Double TLD mail domain conf folder deleted after any update

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1986]
**Describe the bug**
When having a mail domain example.com and an example.com.au , everytime I perform an HestiaCP update the `/home/username/conf/mail/example.com.au` folder is removed. It seems to happen during the `[ * ] Rebuilding user accounts and domains, this may take a few minutes...` ending up with nginx service down.

To fix this I have to `v-rebuild-mail-domain username example.com.au` then `systemctl start nginx` and then on GUI:

- Edit the mail domain and save (the SSL option is not selected as soon as I edit it)
- Then select SSL + LE and save (to get the certificate to work again)

P.S. If I edit the mail domain and select the SSL and save, it shows the saved message but the SSL is not restored so I have to save it first without SSL selected and then select it to save again

**To Reproduce**
Just do an update OR do `v-rebuild-mail-domain username example.com`

**Expected behavior**
HestiaCP to be able to distinguish example.com from example.com.au when rebuilding the mail domain

**Operating system:**
Debian 10.10 (x86_64)

**Hestia Control Panel version:**
1.4.7 (happening since 1.3.5 at least)

**Additional context**
This also happened once without any update or mail domain rebuild triggered. The server was running on its own for about two weeks without any changes or even logging into it, then suddenly from "nothing" the conf folder disapeared, what leads me to think that somehow a `v-rebuild-mail-domain username example.com` was automatically performed

**Comment by jaapmarcus** [comment]
Probally the same issue as we had with v-rebuild-domains in the past  will need to search what the issue is

**Comment by manuelserol** [comment]
Yes, I am almost sure is the equivalent to that issue already fixed

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/issues/1763

**Comment by manuelserol** [comment]
I guess this is the problem
https://github.com/hestiacp/hestiacp/blob/96817a9eb7fb74e1a38645ee90c0108611c9d538/func/domain.sh#L804-L806

**Comment by jaapmarcus** [comment]
I think so. It was more a reference for my self to know where to look for ... 

Replacing -rf with -f should work probally. Willl write a test to verify it for both Web / Mail part

**Comment by Lupul** [comment]
Deleting the result of this could work: (replace `stat` with `rm` )
- this will return only files that match the pattern/wildcard any subfolder will be skipped
- pattern "$domain.*" will continue to match double TLP but since the original code is supposed to remove obsolete config files it doesn't matter if it matches those too, no config files are expected to be there anymore.

``` 
find $HOMEDIR/$user/conf/mail/ -maxdepth 1 -type f \( -name "$domain.*' -o -name "ssl.$domain.*" -o "*nginx.$domain.*" \) -exec stat {} \;
```

There is another problematic cleanup on line 818  https://github.com/hestiacp/hestiacp/blob/c192eaa9024cac455ebd08bf0cb6ff3a375203b2/func/domain.sh#L818

**Comment by jaapmarcus** [comment]
I noticed it all ready. Have changed that one as well. Seems to work fine 

https://github.com/hestiacp/hestiacp/pull/1994
