### ISSUE TITLE
[BUG] missing libicuio60 ubuntu 18.04 after upgrade to latest version

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#1989]
**Describe the bug**
Found out that my server upgraded and hestiacp was not working, because it missed the libicu60.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
i don't know how many people have bee  affected by this, i'm reporting just now because i only saw it now.

**Expected behavior**
hestiacp working normally

**Screenshots**
![image](https://user-images.githubusercontent.com/7103685/126015105-a2a6048a-2e52-4d5b-b74e-6f061bb7a75a.png)

**Operating system:**
Ubuntu 18.04lts

**Hestia Control Panel version:**
1.4.7

**Additional context**
`apt install libicu60` solves the problem.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/1962

Known issue see
