### ISSUE TITLE
When I redirect domain to a differant URL I get an error once the SSL needs to update. Error: Let's Encrypt validation status 400 (xxxxxxxxxxx.com). Details: Unable to update challenge :: authorization must be pending

### ISSUE THREAD

**Issue by Johnzapf** [hestiacp/hestiacp#1992]
**Describe the bug**
A clear and concise description of what the bug is. Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Add Web Domain".
3. Ex.: Attempted to add a domain and received an Internal Server Error.

**Expected behavior**

**Screenshots**

**Operating system:**
Please enter your answer here (e.g. Ubuntu 20.04 LTS)

**Hestia Control Panel version:**
Please enter your answer here (e.g. 1.3.2). 

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by ScIT-Raphael** [comment]
Please fill out the whole issue report. There was an issue in hestia 1.4.6, be sure you are on 1.4.7. Also check https://docs.hestiacp.com/admin_docs/web/ssl_certificates.html#error-let-s-encrypt-validation-status-400

This is more a support issue than a real bug, olease switch over to forum or discord.

**Comment by ScIT-Raphael** [comment]
Sorry, missed the discord conversation. But please fill out a new bug report and include all the relevant informations for os, version and so on.
