### ISSUE TITLE
Postfix should not conflict when no mailservice is selected 

### ISSUE THREAD

**Issue by m4rcu5** [hestiacp/hestiacp#1995]
Hi,

The installer marks the `postfix` package as a conflicting package and refuses to install. This does not make sense when there are no mail services selected in the HestiaCP installer.

https://github.com/hestiacp/hestiacp/blob/c192eaa9024cac455ebd08bf0cb6ff3a375203b2/install/hst-install-debian.sh#L346-L350

For example, when you want to install a web-only server, you might want a minimal postfix install to relay/send email, and provide the installer with the `sendmail` command, it requires at the end.

https://github.com/hestiacp/hestiacp/blob/c192eaa9024cac455ebd08bf0cb6ff3a375203b2/install/hst-install-debian.sh#L1936-L1937

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2010
