### ISSUE TITLE
[FEATURE] Add a form to edit Proxy Templates

### ISSUE THREAD

**Issue by Adruabi** [hestiacp/hestiacp#1997]
When you have Hestia CP installed and there are some services running, listening to different ports (i.e. EMQX, Containers, GITEA...) it would be awesome to have a button to changes the two "proxy_pass" lines in new .stpl and .tpl files in /usr/local/hestia/data/templates/web/nginx/ 

**Describe the solution you'd like**
It would be nice to have some fields like "host" and "port" to fill these lines, somewhere in the web domain edition page, where the proxy template is choosen. Also, a field where you can name that template. (Not in image example, as I realized it after posting the issue)

![imagen](https://user-images.githubusercontent.com/47302006/126435441-ed3b2e72-6b80-4c8d-bc8d-da0e066cb6fc.png)

**Comment by jaapmarcus** [comment]
Duplicate: https://github.com/hestiacp/hestiacp/issues/1453
