### ISSUE TITLE
[BUG] Can't create an subdomain despite the user being the owner of the top-domain

### ISSUE THREAD

**Issue by Fyroeo** [hestiacp/hestiacp#2003]
**Describe the bug**
It is currently impossible to create a subdomain for a specified user, despite he is the owner of the top domain.
(ex: can't create test.domain.tld, despite the user already have domain.tld)

**To Reproduce**
1. Use the `v-search-domain-owner domain.tld` to search which user own domain.tld.
2. Try to move the domain.tld to the user returned in Step 1 using `v-change-domain-owner domain.tld user`: You should get "ERROR: domain.tld is already owned by user." (Step to prove that the user is still considered as the owner)
3. Try to create a subdomain using `v-add-web-domain user subdomain.domain.tld ip yes www.subdomain.domain.tld`: You will get "Error: domain.tld belongs to a different user"

**Expected behavior**
The subdomain should be created since the user is the owner of domain.tld.

**Operating system:**
Debian 10.9

**Hestia Control Panel version:**
1.4.7

**Comment by jaapmarcus** [comment]
I am not able to replicate the bug with out automated testing setup and on my own test server...

See:
https://github.com/hestiacp/hestiacp/blob/955f0fdb25060c696ec7bb7f18d48704977e022c/test/test.bats#L1002-L1107

And mainly 

https://github.com/hestiacp/hestiacp/blob/955f0fdb25060c696ec7bb7f18d48704977e022c/test/test.bats#L1094-L1107
See https://drone.hestiacp.com/hestiacp/hestiacp
For the build tests

**Comment by ScIT-Raphael** [comment]
Not able to replicate aswell, please provide more informations if possible.
