### ISSUE TITLE
[BUG] Suggested DNS records on mail domains are incorrect

### ISSUE THREAD

**Issue by imjuniper** [hestiacp/hestiacp#2005]
**Describe the bug**
The suggested DNS records on mail domains are incorrect. To be precise, the `MX` and `mail._domainkey` records are wrong. When testing the records on [MxToolbox](https://mxtoolbox.com) and sending test emails to [mail-tester.com](https://mail-tester.com), multiple errors are shown.

**To Reproduce**
1. Click on the "Mail" tab.
2. Click on "Add Mail Domain".
3. Add a domain and enable DKIM.
4. Go back to the "Mail" tab.
5. Check the DNS Records
6. (Optional) Test the records using [MxToolbox](https://mxtoolbox.com) or [mail-tester.com](https://mail-tester.com)

**Expected behavior**
The `MX` should be reversed with `mail.example.com` being the value and `example.com` being the record. The `mail._domainkey` record should be prefixed with `v=DKIM1; k=rsa; p=`

**Screenshots**
The records
![Screenshot](https://i.imgur.com/X21Uel6.png)

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.7

**Comment by jlguerrerosanz** [comment]
Maybe we could reach an agreement on which DNS records should be made by default so that most of use don't need to change the template.

Since I only use one of my servers as primary DNS, I have already tuned my template but some of us would maybe benefit of some tweaks.

**Comment by jaapmarcus** [comment]
When you go to Mail -> And then hover over the DNS records you will see this data.
 
<img width="1099" alt="Screenshot 2021-07-25 at 13 29 38" src="https://user-images.githubusercontent.com/9754650/126897522-c3cf20e1-fb46-40b6-aae4-585ab7130054.png">

But I agree both change should be applied.. 

The default template for DNS records are fine. At least if you host email, dns and web on the same server. Maybe a point to change are the dmarc records to make them more strict or less strict but it is hard to say  what is best.

**Comment by imjuniper** [comment]
I personally don't use the DNS function of Hestia (as I run Pi-hole on it), I either manage it with Google Domains or with Cloudflare, so I can't seem to access the page you show. Unless I am misunderstanding

**Comment by jaapmarcus** [comment]
If bind is not installed this page will not be available..

**Comment by jaapmarcus** [comment]
Change by @cmstew  will merge it
