### ISSUE TITLE
[BUG] Nginx template no-php causes reponse content-type: application/octet-stream

### ISSUE THREAD

**Issue by m4rcu5** [hestiacp/hestiacp#2007]
**Describe the bug**
If you switch the "Web tempalate" to `no-php`, css files will get the response header `content-type: application/octet-stream` instead of `content-type: text/css`. This will cause browsers to fail to load the stylesheet.

**To Reproduce**
What steps did you take when the issue occured? 
1. Upload a website with static content, including a CSS file.
2. Verify the site is working with the `default` template. (check response headers)
3. Switch the "Web template" to `no-php`
4. Verify the site does now not load the stylesheet. (and the response headers are incorrect)

**Expected behavior**
The server to serve any non php content with correct mime-types applied.

**Operating system:**
Debian 10.10, amd64

**Hestia Control Panel version:**
1.4.7

**Additional context**
Looking at the template `nginx/php-fpm/no-php.tpl`, there is a stanza to define what files should be served as `text/html`.
```
    types {
            text/html   html htm shtml php php5;
    }
```

This however causes the globally included `/etc/nginx/mime.types` to be disregarded, most likely causing this issue.
Related serverfault posting: https://serverfault.com/questions/678673/nginx-how-to-override-add-single-mime-type

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2009
