### ISSUE TITLE
[FEATURE] Disable TLS 1.0 / 1.1 for mail | April 2022

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2012]
Currently TLS 1.1 / 1.0 is still active for mail only 

**TLS 1.0 & 1.1 support ended at March 31, 2020. Maybe we can give a two year window and implement it in April 2022**

**Comment by jlguerrerosanz** [comment]
Does this take any effort to maintain? If it doesn't, maybe we should leave it as is so we don't have to contact all clients and tell them to use an alternative way if they are connecting via TLS.

Is there a way to know who is using TLS?

**Comment by ScIT-Raphael** [comment]
TLS is used, yes. You'll find more informations about TLS and SSL here: https://kinsta.com/knowledgebase/tls-vs-ssl/

**Comment by jaapmarcus** [comment]
TLS 1.0 and 1.1 went EOL on 31 March 2020. It should already not been used any more by any  mail server.  It is used fors secured connections between servers and clients...  Giving it a 2 year window behind that. As it is for security we think it is important to implement it. If you don't like that revert the changes made when we release this version it will be not more then 2 min work. 

TLS 1.1 and below are already disabled for Web, Vsftpd and Proftpd. 


SSL 1.0 – never publicly released due to security issues.
SSL 2.0 – released in 1995. Deprecated in 2011. Has known security issues.
SSL 3.0 – released in 1996. Deprecated in 2015. Has known security issues.
TLS 1.0 – released in 1999 as an upgrade to SSL 3.0. Planned deprecation in 2020.
TLS 1.1 – released in 2006. Planned deprecation in 2020.
TLS 1.2 – released in 2008.
TLS 1.3 – released in 2018.

**Comment by jlguerrerosanz** [comment]
To see if this change affects you, just:

cat /var/log/exim4/mainlog | grep TLS1.0
cat /var/log/exim4/mainlog | grep TLS1.1

I can't see more than 3 entries so there is no problem for me.

**Comment by jaapmarcus** [comment]
TLS1.0 is already disabled at least for dovecot. It is more a reminder for to not forget ...

**Comment by ohuet** [comment]
TLS 1.0 is still used by old software sending mails through SMTP servers and old printer&scanner.
So we cannot upgrade HestiaCP to 1.6 for now if it disable TLS 1.0 in Exim (we cannot replace all this software and scanners)
I think there should be an option in HestiaCP to keep TLS 1.0 enabled for Exim, with a warning.

**Comment by jaapmarcus** [comment]
Update to 1.6 and revert back the changes made in here. 

https://github.com/hestiacp/hestiacp/commit/83a18e0ee532abb74964a378885c268e7079563d

for "new" users they can still modify the config files manually.

Does it make sense to add a feature for 1% of the users that need it and can't edit their files them self..
