### ISSUE TITLE
[BUG] Problem with fresh install 1.4.8

### ISSUE THREAD

**Issue by btechn01** [hestiacp/hestiacp#2017]
**Describe the bug**
Install latest version in ubuntu 20.04
Dovecot  won't start
Fail2Ban won't start

**To Reproduce**
Just follow installation

**Expected behavior**
Fix bug

**Screenshots**
<img width="1022" alt="Screen Shot 2021-07-28 at 1 31 18 AM" src="https://user-images.githubusercontent.com/6770866/127226866-9c48a581-d60b-48c2-b192-4c127d2d5d2a.png">

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.8

**Additional context**

**Comment by jaapmarcus** [comment]
Please provide the install string?

**Comment by ScIT-Raphael** [comment]
Also some more informations like the output of systemctl status dovecot

**Comment by btechn01** [comment]
Just used `bash hst-install.sh` 




root@server:~# systemctl status dovecot
● dovecot.service - Dovecot IMAP/POP3 email server
     Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-07-27 22:59:59 CEST; 2min 33s ago
       Docs: man:dovecot(1)
             http://wiki2.dovecot.org/
    Process: 464 ExecStart=/usr/sbin/dovecot -F (code=exited, status=89)
   Main PID: 464 (code=exited, status=89)

Jul 27 22:59:58 xxx systemd[1]: Started Dovecot IMAP/POP3 email server.
Jul 27 22:59:58 xxx dovecot[464]: doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 3: Unknown setting: ssl_min_protocols
Jul 27 22:59:59 xxx systemd[1]: dovecot.service: Main process exited, code=exited, status=89/n/a
Jul 27 22:59:59 xxx systemd[1]: dovecot.service: Failed with result 'exit-code'.

root@server:~# systemctl status fail2ban.service 
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-07-27 22:59:59 CEST; 4min 59s ago
       Docs: man:fail2ban(1)
    Process: 471 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
    Process: 523 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 523 (code=exited, status=255/EXCEPTION)

Jul 27 22:59:58 xxx systemd[1]: Starting Fail2Ban Service...
Jul 27 22:59:59 xxx systemd[1]: Started Fail2Ban Service.
Jul 27 22:59:59 xxx fail2ban-server[523]: 2021-07-27 22:59:59,846 fail2ban                [523]: ERROR   Failed during configuration: Have not found any log file for dovecot-iptables jail
Jul 27 22:59:59 xxx fail2ban-server[523]: 2021-07-27 22:59:59,858 fail2ban                [523]: ERROR  Async configuration of server failed
Jul 27 22:59:59 xxx systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Jul 27 22:59:59 xxx systemd[1]: fail2ban.service: Failed with result 'exit-code'.

**Comment by btechn01** [comment]
Also there is a little bug in Dialog

<img width="1021" alt="Screen Shot 2021-07-28 at 1 37 26 AM" src="https://user-images.githubusercontent.com/6770866/127227602-98dbadfb-7407-41c8-8e0d-feb7ed66af8f.png">

**Comment by jaapmarcus** [comment]
For the UI bug please create a new one:

For the install:
replace ssl_min_protocols with ssl_min_protocol in /etc/dovecot/conf.d/10-ssl.conf

And then restart both services

**Comment by jaapmarcus** [comment]
Both issues should be solved right now for the server you might need to manually update the config!
