### ISSUE TITLE
[BUG] Interface does not show/hide block to add additional FTP accounts on websites

### ISSUE THREAD

**Issue by jcerdan** [hestiacp/hestiacp#2021]
**Describe the bug**
When clicking checkbox "Additional FTP Accounts" the box below is not shown.

**To Reproduce**
What steps did you take when the issue occured? 
1. try to add an additional FTP account

**Expected behavior**
Box should below should be opened

**Operating system:**
Ubuntu 20.04 LTS, but the problem is in Javascript interface

**Hestia Control Panel version:**
1.4.9

**Additional context**
The solution is to to the same as in "Document root"

`<label><input type="checkbox" size="20" class="vst-checkbox" name="v_ftp" onclick="javascript:elementHideShow('v_add_domain_ftp');">Additional FTP account(s)</label>`

and below

`<table id="v_add_domain_ftp" class="ftptable ftptable-nrm" ... >`

**onClick** function should be modified and id should be added to **table** tag

**Comment by jaapmarcus** [comment]
Replace line 180 in /web/js/pages/edit_web.js with 
.attr('checked') with prop('checked')

The bug is probably caused by the replacement of the newer jQuery library and jQuery-UI library
