### ISSUE TITLE
Bug: Can not add mail domain if web domain exists under condition

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#2024]
**Current Setup:** Hestiacp 1.4.9 - Ubuntu 20.04.2 - Default Install

Yesterday I created a Web Domain and clicked create DNS Zone

Today I wanted to add mail functionality to the domain so I click Mail Domains Clicked Add and typed the domain name and click save and got the following error **Error: Web alias domain.tld exists**

**Comment by johnnyq** [comment]
Okay upon further investigation it appears to only happen with 1 domain I was able to add mail to other domains, im not sure what is different. I'll investigate further and report back

**Comment by johnnyq** [comment]
I can create mail domains for all my other domains just not this one for some odd reason they are all configured the same. The error itself is weird and doesn't even relate to mail im at a loss. Ill take another stab at it tommorow

**Comment by johnnyq** [comment]
okay I found out whats going on. 

I have 2 domains domain.net and domain.com each has their own web domain
I set domain.net enable domain redirection > Redirect visitors to a custom domain or web address > Set it to domain.com and chose 301 Redirect

By unchecking that option I was able to add the mail domain example.com

This would be a rare bug to trigger but I found a way to trigger it

**Comment by jaapmarcus** [comment]
DNS Domain A, DNS Domain B
WEB Domain A and Domain B 

Domain A -> 301 Redirect to Domain B

Now add Domain B as Mail domain -> Error?

**Comment by jaapmarcus** [comment]
Can confirm the issue

**Comment by jaapmarcus** [comment]
Issue should be fixed with the changes made 10 days ago. Improved the alias detection
