### ISSUE TITLE
[FEATURE] Stable release repository

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2025]
**Is your feature request related to a problem? Please describe.**
In some occasions when an update is pushed and there are no relevant security fixes we find new bugs in the system.

For those who have clients and can't afford to risk their uptimes for their services it would be nice to **automatically update Hestia from a repository in which we know that new critical bugs have not appeared in X days.**

I would even consider putting it behind a paywall.

**Comment by jaapmarcus** [comment]
Idea behind the number of updates is keeping the changes relative small. We have implemented automated testing to speed up the testing path and improve the quality of the issues found. 
How ever not everything can be automated yet.  (JS, PHP code for example) 

It makes no sense to set it up for 10 users / servers. How ever if there are more users interested it might be an idea. 

So far I know from 1.4.7 to finally 1.4.9 there is no downtime. Only notifications/mail didn't work. Issues with FM and PHPmailer not installing is always caused some restrictions some user set in php cli. Solution would be to use "Hestia-php" for it instead how ever it requires to be using OpenSSL with it.

**Comment by jaapmarcus** [comment]
I don't see any other interest in a stable repository. 

We should focus on the fact to get the "releases" it self more stable...
