### ISSUE TITLE
File Manager installation failed!

### ISSUE THREAD

**Issue by mail47002** [hestiacp/hestiacp#2026]
**Describe the bug**
After updated, file manager not work

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Ex.: select file manager - yes
2. Ex.: Save

**Expected behavior**

**Screenshots**
https://i.imgur.com/EnXk2f4.png

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.9 (amd64)

**Additional context**
ERROR: File Manager installation failed!<br>Please report this to our development team:<br>https://github.com/hestiacp/hestiacp/issues

**Comment by jaapmarcus** [comment]
v-add-sys-filemanager via cli any output then.

**Comment by mail47002** [comment]
I did not understand, you can detail

**Comment by mail47002** [comment]
previously worked without problems

**Comment by ScIT-Raphael** [comment]
open your command line aka ssh aka bash and run the command which @jaapmarcus suggested - then provide us with the error output.

**Comment by mail47002** [comment]
https://i.imgur.com/TcZS9rT.png

**Comment by jaapmarcus** [comment]
Did you modify php.ini recently?
pcntl_singnal_get_handler has been disabled. 

Check /etc/php/x.x/cli/php.ini

**Comment by mail47002** [comment]
Thank you!!!! It`s works (jaapmarcus)
have a new problem))) 
https://i.imgur.com/6koeKzo.png
not opened window new FTP user

**Comment by ScIT-Raphael** [comment]
Known bug, will be fixed in next release. Please use for support cases next time our forum or discord - github is for bug handling only.
