### ISSUE TITLE
[FEATURE] Editable open_basedir

### ISSUE THREAD

**Issue by xelnaga64** [hestiacp/hestiacp#2027]
My PHP application requires to read a special directory. Let's say: /var/log/apache2/domains
I can edit php_admin_value[open_basedir] by editing this file: /usr/local/hestia/data/templates/web/php-fpm/PHP-7_4.tpl

However, every HestiaCP update removes my special directory from PHP-7_4.tpl. I have to edit PHP-7_4.tpl file again and again.

Is there any way to permanently keep my special directory inside php_admin_value[open_basedir]?
Or
Is it possible to keep additional open_basedir directories in future HestiaCP versions? Ability to keep it for other PHP versions (such as PHP-8_0.tpl) would be a plus.

**Comment by jaapmarcus** [comment]
cp PHP-7_4.tpl openbase-PHP-7.4.tpl and make your changes there. 

https://docs.hestiacp.com/admin_docs/web.html#how-can-i-change-settings-for-a-specific-domain
