### ISSUE TITLE
[BUG] Port missing from nginx default domain config after installation

### ISSUE THREAD

**Issue by sandroshu** [hestiacp/hestiacp#2028]
**Describe the bug**
Installing the 1.4.9 version with the following parameters result in a bad nginx configuration (missing port).
bash hst-install.sh -a no -w no -o no -v no -j no -k yes -m no -g no -x yes -z yes -c no -t no -i yes -b yes -q no
/etc/nginx/conf.d/domains/example.hu.conf (listen x.x.x.x:;)
After fixing the configuration file manually and running the above command again with -f result in missing configuration.

**Expected behavior**
Successful installation.

**Operating system:**
Debian 10 64bit x86

**Hestia Control Panel version:**
1.4.9

**Comment by jaapmarcus** [comment]
-w is currently required for Nginx only it might be the cause. We should probably add it as a "dependency"

**Comment by jaapmarcus** [comment]
Unless we want to add a "feature" where we would not allow the install of Nginx with out php-fpm the changes submitted above will solve the issue from never happing again
