### ISSUE TITLE
Feature Request: Enable toggle in admin panel to SSL sign host (v-update-host-certificate)

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#203]
It is currently possible to sign the host's services (control panel, exim/dovecot, etc) with v-update-host-certificate through the command line. This functionality should be extended to the web UI/admin panel as well for easier access.

**Comment by johnnyq** [comment]
Absolutely excellent Idea! @kristankenney

**Comment by killer30001000** [comment]
@kristankenney Would it be possible to create a symbolic link of the .crt and .key files? If those two are renewed you need to copy these files again, but if you link them, you never have to copy them again. I'm doing this right now on my installation and it works fine, it would be great if this could be implemented in the command (v-update-host-certificate).

**Comment by ScIT-Raphael** [comment]
@cr1s3c There is already a function, that works without symlink (v-update-host-certificate). Symlinks will produce permission failures with exim and dovecot.

**Comment by ScIT-Raphael** [comment]
Added with the command v-add-letsencrypt-host.

**Comment by ghost** [comment]
Will ship in v1.0.2.
