### ISSUE TITLE
[FEATURE] v-delete-firewall-ban 1.2.3.4 ALL

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2031]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to grant someone access to hestia but you don't know which rule banned the user:
- Ssh
- Mail
- Hestia
- Recidive
So this command is useless until you know which jail banned you.

**Describe the solution you'd like**
Add a "ALL" option to the chain so that you get unbanned regardless of the Jail or Chain your ban belongs to.

**Describe alternatives you've considered**
Alternatively if the jail is empty it will unban form all by default.

This one might be more insecure.

**Comment by jaapmarcus** [comment]
Makes sense..

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2040

**Comment by jaapmarcus** [comment]
Please also included a few tests to make sure everything remains working !
