### ISSUE TITLE
[BUG] http://xx.xx.xx.xx/phpmyadmin 404 Page Not Found

### ISSUE THREAD

**Issue by viratsoft** [hestiacp/hestiacp#2034]
Hello!
Fresh install hestiacp 1.4.9 in debian 10. when open phpmyadmin using http://xx.xx.xx.xx/phpmyadmin get error 404 Page Not Found.
already try https://forum.hestiacp.com/t/phpmyadmin-error-404/271 but not work.
why this in fresh install?

**Comment by ScIT-Raphael** [comment]
https://docs.hestiacp.com/admin_docs/database.html#why-i-can-t-use-http-ip-phpmyadmin

**Comment by vihatsoft** [comment]
"For security reason we have decided to disable this option."
How can i enable http://xx.xx.xx.xx/phpmyadmin?

**Comment by viratsoft** [comment]
> https://docs.hestiacp.com/admin_docs/database.html#why-i-can-t-use-http-ip-phpmyadmin

"For security reason we have decided to disable this option."
How can i enable http://xx.xx.xx.xx/phpmyadmin?

**Comment by ScIT-Raphael** [comment]
Please use https://hostname.domain.tld/phpmyadmin instead, access over ip isnt supported anymore.

**Comment by viratsoft** [comment]
> Please use https://hostname.domain.tld/phpmyadmin instead, access over ip isnt supported anymore.

okay brother thank you,
