### ISSUE TITLE
[FEATURE] Add way to customize SPF for SMTP relays

### ISSUE THREAD

**Issue by liamdemafelix** [hestiacp/hestiacp#2038]
**Is your feature request related to a problem? Please describe.**
The new SMTP Relay settings are great. One problem with this approach, however, is that it requires manual changes to the DNS records created for the SPF record to include the SPF records of the relay. For instance, in mail.baby's usage, `include:relay.mailbaby.net` must be added to the SPF record.

Customizing the DNS template wouldn't work as far as I know, since these get overwritten during updates.

**Describe the solution you'd like**
An additional field in the Global Relay settings section in the control panel where admins can place custom SPF record formats would be ideal, OR introduce a way for DNS templates (and possibly all other templates) to be customizable without getting overwritten during updates.

**Describe alternatives you've considered**
For now, I manually change the SPF records of the domains added to the system, which is ideal for a small amount of domains but gets impractical as you scale.

**Additional context**
N/A

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/web.html#how-do-web-templates-work also work the same for DNS templates except they are saved in /usr/local/hestia/data/templates/dns

cp default.tpl mailbabynet.tpl and make your changes. 

In combination with https://github.com/hestiacp/hestiacp/issues/1521 it should be enough.
