### ISSUE TITLE
[FEATURE] Make update Let's encrypt certificate less cumbersome

### ISSUE THREAD

**Issue by amaneshi** [hestiacp/hestiacp#2041]
Maybe I missed something but I found that current Let's Encrypt SSL update not really usable.
Recently my certs reach "update" stage, but every automatic retry was unsuccessfull. I waited few days in hope that automatic update will make it, but got reports that "error 400 authorization pending..." in log.

Some time ago I created certificate with admin panel for domain and www.* subdomain and it was issued. But now when it try to update automatic or manual (tried from admin panel and from console) got error.

I spent some time discovering couse of problem - detailed digging in log told that "connection to my host was refused for certbots". Enabled log for incoming requests (even from certbot) and found out that requests reach my domain, but got redirected somewhere (no more info from NGINX logs).

Then I returned to domain/site settings and disabled redirection from www.* to main domain - I conducted that it redirect letsencrypt HTTP challenge for www.* domain and challenge failed - and this helped - partly.

Look like same reason was with force HTTPS redirection - I disabled it next in admin panel (and HSTS for any case, not sure if it have similar effect) and certificates updated!

Then I discovered NGINX domain templates - as I can get from its - this above described redirects located in config higher so before Certbot can reach request to check webroot data/token and validate it - request get redirected and http challenge failed!!!

Not sure how better to solve this case (or I miss something?) , but guess need to move webroot access request higher, maybe in main NGINX config file before any redirects.

Sorry if my story become long, but wanted to describe my (and I believe not only mine) problem in details.

**Comment by Pleskan** [comment]
Why are you using certbot in HestiaCP?!
We've implemented own scripts to get LE certificates long ago.

**Comment by ScIT-Raphael** [comment]
@Pleskan He probaly thinks we using certbot :).

@amaneshi thanks for the debug work and your story. Could you share with us which template(s) ypu've used?

**Comment by amaneshi** [comment]
@Pleskan @ScIT-Raphael  Thanks for reply!
I dont think HestiaCP use certbot. I mentioned it as a Let's Encrypt bot that make HTTP challenges to my host.
I use default templates, any manual changes from my side. Do I really need to show it here in this case? If so - then template of domain (generated or template, not sure where templates located) or include general?

**Comment by jrohde** [comment]
Looks like i got the same issue. For a complete new domain - with all default templates - i can no longer issue LE certs.
When i disable the forcessl include on line 10 in the domains nginx.conf ```/home/someuser/conf/web/example.com/nginx.conf```
So: 

```#include /home/someuser/conf/web/example.com/nginx.forcessl.conf*;```

...I can issue a cert without any problem.

I can't find any recent changes that fast which might have caused this.
Maybe the default flag of 'forcessl' is now on by default (so even before there's a cert in place, it's still generated in the 'virgin' default nginx.conf)?
When i have some more time i can dive into it, but maybe/hopefully one of the main dev's already have a clue by now ;-)


Update: After reading the OP's issue again it seems he has also troubles with LE updates (AFAIK i don't have that). So this might not be exactly the same issue, but at least regarding the forcessl include being present there's some common ground. Shout if you rather have a complete new issue.

**Comment by amaneshi** [comment]
I mentioned same issue with "force HTTPS redirection" - so you have same problem. I tested this case and got same result - can't renew certificates with this option active.
Additionally I had problem with "www.domain.com" redirection to "domain.com" with same reason and result.

**Comment by jrohde** [comment]
I just completely removed the domain (Site, DNS, Mail, DB). waited 5 min and recreated the domain. Now when i went to issue a new cert. I first disabled the Force SSL option (it was active by default) and the cert issued without any problems. The only prob i then had was that nginx needed a restart. www. redirection is also fine.

My thoughts: I think the problems arise if the first cert issue attempt fails. Then forcessl is already present in the nginx.conf and all later attempts won't work because it tries to redirect to https. Also a nginx restart is needed after a successful cert issue.

**Comment by jaapmarcus** [comment]
Made some changes to improve the renewal of LE certificates

**Comment by MenschLink** [comment]
I would actually be interested in rfc2136 compliance for dns alterations so I can use certbot from other machines to create dns-checked certificates based on zones in hestia cp...
