### ISSUE TITLE
[BUG] v-change-sys-ip-helo

### ISSUE THREAD

**Issue by kenng** [hestiacp/hestiacp#2044]
**Describe the bug**
command `$HESTIA/bin/v-change-sys-ip-helo $local_ip $servername` is causing an issue when there's more than one IPs

Example this command returns two IPs
```sh
/sbin/ip addr |grep 'inet ' |grep global |awk '{print $2}' |cut -f1 -d/
172.17.0.1
172.20.141.122
```

```sh
update_ip_value_new() {
    key="$1"
    value="$2"
    conf="$HESTIA/data/ips/$ip"  
    # now, the value of conf="$HESTIA/data/ips/172.17.0.1 172.20.141.122 "
    // ... 

    // sed will throw error
    // sed: can't read 172.20.141.122: No such file or directory
    sed -i "s|^$key=.*|$key='$value'|g" $conf
```
**Output**
```
[ * ] Configuring Dovecot POP/IMAP mail server...                                                                                                        
[ * ] Downgrade dovecot config to sync with 2.2 settings
[ * ] Configuring fail2ban access monitor...
[ * ] Install Roundcube...
[ * ] Configure System IP...
sed: can't read 172.20.141.122: No such file or directory
Error: php7.3-fpm restart failed
```

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.9

**Comment by jaapmarcus** [comment]
I have made a test with Digital ocean + 3 ip addr defined... 

We get the main ip in:

https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/install/hst-install-ubuntu.sh#L1782-L1784

and then 

https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/install/hst-install-ubuntu.sh#L1814-L1817

In v-change-sys-ip-helo
https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/bin/v-change-sys-ip-helo#L47-L55

The only issue that might cause the issue is 

https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/func/ip.sh#L52-L56


```
[ * ] Install Roundcube...
[ * ] Configure System IP...
[ * ] Installing remaining software updates...
[ * ] Configuring File Manager...
[ * ] Finish up install...
[ * ] Configuring PHPMailer...

```

**Comment by kenng** [comment]
> I have made a test with Digital ocean + 3 ip addr defined...
> 
> We get the main ip in:
> 
> https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/install/hst-install-ubuntu.sh#L1782-L1784
> 
> and then
> 
> https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/install/hst-install-ubuntu.sh#L1814-L1817
> 
> In v-change-sys-ip-helo
> https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/bin/v-change-sys-ip-helo#L47-L55
> 
> The only issue that might cause the issue is
> 
> https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/func/ip.sh#L52-L56
> 
> ```
> [ * ] Install Roundcube...
> [ * ] Configure System IP...
> [ * ] Installing remaining software updates...
> [ * ] Configuring File Manager...
> [ * ] Finish up install...
> [ * ] Configuring PHPMailer...
> ```

@jaapmarcus yap, that's the line that causing the issue

**Comment by kenng** [comment]
@jaapmarcus yap, this is the line that's causing the issue

https://github.com/hestiacp/hestiacp/blob/2304b935db47ea303c8e0caa8931712c4e2764e0/func/ip.sh#L52-L56
