### ISSUE TITLE
[BUG] Installation as root on Ubuntu 20.04, ending with access error

### ISSUE THREAD

**Issue by davidmarquesfg** [hestiacp/hestiacp#2045]
The installation process in a fresh ubuntu 20.04 server, ends, but with errors and server does not work.
Informations: The server is running in a godaddy VPS.
I've runned the setup script with root user.
The installation process printed messages is in Additional Information
After server reboot, when access  https://mydomain.com:8083 a error 500 screen is printed.
in /var/log/hestia/nginx-error.log i've found some errors:
 screen is printed.

in /var/log/hestia/nginx-error.log i've found some errors:
___
2021/08/03 20:29:54 [error] 157418#0: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/hestia/web/inc/main.php on line 7PHP message: PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (includepath='.:') in /usr/local/hestia/web/inc/main.php on line 7" while reading response header from upstream, client: MYIP, server: , request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "my.fqdnserver.com:8083"
2021/08/03 20:32:45 [error] 849#0: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/hestia/web/inc/main.php on line 7PHP message: PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (includepath='.:') in /usr/local/hestia/web/inc/main.php on line 7" while reading response header from upstream, client: MYIP, server: , request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "my.fqdnserver.com:8083"
___

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.9

**Additional information**

---------------------

                _   _           _   _        ____ ____
               | | | | ___  ___| |_(_) __ _ / ___|  _ \
               | |_| |/ _ \/ __| __| |/ _` | |   | |_) |
               |  _  |  __/\__ \ |_| | (_| | |___|  __/
               |_| |_|\___||___/\__|_|\__,_|\____|_|

                _   _           _   _        ____ ____
               | | | | ___  ___| |_(_) __ _ / ___|  _ \
               | |_| |/ _ \/ __| __| |/ _` | |   | |_) |
               |  _  |  __/\__ \ |_| | (_| | |___|  __/
               |_| |_|\___||___/\__|_|\__,_|\____|_|

                          Hestia Control Panel
                                  1.4.9
                            www.hestiacp.com

========================================================================

Thank you for downloading Hestia Control Panel! In a few moments,
we will begin installing the following components on your server:

   - NGINX Web / Proxy Server
   - Apache Web Server (as backend)
   - PHP-FPM Application Server
   - Bind DNS Server
   - Exim Mail Server + ClamAV + SpamAssassin
   - Dovecot POP3/IMAP Server
   - MariaDB Database Server
   - Vsftpd FTP Server
   - Firewall (Iptables) + Fail2Ban Access Monitor

========================================================================

Would you like to continue with the installation? [Y/N]: Y
Please enter admin email address: myemail.com
Please enter FQDN hostname [serverfqdn.com]: mydomain.com
Installation backup directory: /root/hst_install_backups/040820211515
Installation log file: /root/hst_install_backups/hst_install-040820211515.log

Adding required repositories to proceed with installation:

[ * ] NGINX
[ * ] PHP
[ * ] Apache2
[ * ] MariaDB
[ * ] Hestia Control Panel

Updating currently installed packages, please wait...-
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait...
\

========================================================================

[ * ] Configuring system settings...
[ * ] Configuring Hestia Control Panel...
[ * ] Generating default self-signed SSL certificate...
[ * ] Adding SSL certificate to Hestia Control Panel...
[ * ] Enable SFTP jail...
[ * ] Create admin account...
[ * ] Configuring NGINX...
[ * ] Configuring Apache Web Server...
[ * ] Configuring PHP-FPM...
[ * ] Configuring PHP...
[ * ] Configuring Vsftpd server...
[ * ] Configuring MariaDB database server...
[ * ] Installing phpMyAdmin version v5.1.1...
[ * ] Configuring Bind DNS server...
[ * ] Configuring Exim mail server...
[ * ] Configuring Dovecot POP/IMAP mail server...
[ * ] Installing ClamAV anti-virus definitions...-WARNING: Ignoring deprecated option SafeBrowsing at /etc/clamav/freshclam.conf:22
|
[ * ] Configuring SpamAssassin...
[ * ] Configuring fail2ban access monitor...
[ * ] Install Roundcube...
[ * ] Configure System IP...
**chmod: cannot access '/home/admin/web/mydomain.com/public_*html/*': No such file or directory**
[ * ] Installing remaining software updates...
[ * ] Configuring File Manager...
[ * ] Finish up install...
[ * ] Configuring PHPMailer...

====================================================================

**2021-08-04 15:19:02 failed to expand "${if exists {/etc/exim4/mailhelo.conf}{${lookup{$interface_address}lsearch{/etc/exim4/mailhelo.conf}{$value}{$primary_hostname}}}{$primary_hostname}}" (smtp_active_hostname): failed to open /etc/exim4/mailhelo.conf for linear search: Permission denied (euid=117 egid=124)**

Congratulations!

You have successfully installed Hestia Control Panel on your server.

Ready to get started? Log in using the following credentials:

    Admin URL:  https://mydomain.com:8083
    Username:   admin
    Password:   password

Thank you for choosing Hestia Control Panel to power your full stack web server,
we hope that you enjoy using it as much as we do!

Please feel free to contact us at any time if you have any questions,
or if you encounter any bugs or problems:

Web:     https://www.hestiacp.com/
Forum:   https://forum.hestiacp.com/
Discord: https://discord.gg/nXRUZch
GitHub:  https://www.github.com/hestiacp/hestiacp

Note: Automatic updates are enabled by default. If you would like to disable them,
please log in and navigate to Server > Updates to turn them off.

Help support the Hestia Control Panel project by donating via PayPal:
https://www.hestiacp.com/donate
--
Sincerely yours,
The Hestia Control Panel development team

Made with love & pride by the open-source community around the world.

[ ! ] IMPORTANT: System will reboot
----------------------

**Comment by jaapmarcus** [comment]
As told I have no issues with it. It might be an issue with your provider...

**Comment by jaapmarcus** [comment]
There seems some issues with the Ubuntu template used. It will be impossible to debug unless we create hundreds of VPS by diffrentent providers

**Comment by caos30** [comment]
I suffered the same error 500 trying to access on browser to mydomain.com:8083, and i had HestiaCP running since almost a year without problems. It seems that the problem arised in the update to 1.4.9. 

I explain how i solved it in the official HestiaCP forum: https://forum.hestiacp.com/t/panel-error-after-1-4-8-update/4166/8

In my case, it seems that the PHP CLI setting open_basedir was not including certain needed paths:
```
/tmp
/usr/local/hestia
/home/admin/.config
/home/admin/.composer
```
I don't know if has happened a miss-configuration of my PHP settings or was the HestiaCP update who introduced changes in this sense. I'm not really an expert on HestiaCP development issues. But i think that it more people could have this problem in a near future. So... i hope you find something of sense in my words.
If you need more information, please ask me.

Tecnichally talking: i've running HestiaCP on my own VM with this unique domain name. Ubuntu 20.04.
