### ISSUE TITLE
[BUG] Can't create FTP via GUI

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2046]
**Describe the bug**
https://www.loom.com/share/3d05080c68394f71b077f6cc5822ebac

**To Reproduce**
![image](https://user-images.githubusercontent.com/39749258/128411027-fe01d923-b123-4461-8125-dcd2578efb55.png)

**Expected behavior**
should be able to create FTP via Panel.

**Screenshots**

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
v1.4.9

**Comment by ScIT-Raphael** [comment]
Please use the search function before you create new reports, already known and fixed on main branch: https://github.com/hestiacp/hestiacp/issues/2021
