### ISSUE TITLE
[BUG]Cannot Delete Multiple Mail Accounts

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#2047]
**Describe the bug**
When you select multiple mail account under a mail domain and choose delete and click the apply arrow at the top it does not delete the accounts and kicks you back to the mail domain section.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Click Mail Tab
2. Click a mail Domain that has accounts in it
3. Select the ones you want to delete
4. Choose Delete in the select box above 
5. Click the Apply Arrow next to the select box

**Expected behavior**
It should delete the selected mail accounts

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
Hestia 1.4.9

**Comment by johnnyq** [comment]
It also looks like the suspend option doesn't work either ill keep on testing and report back

**Comment by johnnyq** [comment]
After some more testing on two instances of HestiaCP I was able to replicate it in the mail accounts section. This doesn't seem to affect any other section such as web dns or SQL

**Comment by jaapmarcus** [comment]
Found the issue will submit a pull request
