### ISSUE TITLE
[BUG] French language hestiacp email charset issue

### ISSUE THREAD

**Issue by Faymir** [hestiacp/hestiacp#2050]
**Describe the bug**
Emails sent by the hestia control panel have weird characters instead of é à etc (french language selected).
I suspect wrong charset, because in the received email header, the charset is iso-8859-1 instead of utf-8.

**To Reproduce**
What steps did you take when the issue occurred? 
1. Change the hestiacp default language to french
2. Set one user account language to french
3. If the user has no email domain add one
4. create or change email credential (test@example.com) for this user and then enter an email address to receive the new credentials.
5. The received email has characters encoding issue. For example, you have **_MÃ©thode dâauthentification IMAP:_** instead of **_Méthode d'authentification IMAP:_**

**Expected behavior**
A clear and readable hestiacp credentials email.

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.4.9

**Additional context**
I corrected the issue by adding at **line 321** of the **web/inc/main.php** this:
```php
$mail->CharSet = "utf-8";
```

Because default charset is set to iso-8859-1 in PHPMailer.

Also here is the email subject header before my change:
`=?iso-8859-1?Q?Envoyer_les_informations_d'identification_=C3?=  =?iso-8859-1?Q?=A0?=`
And here is the header after the suggested change
`?utf-8?Q?Envoyer_les_informations_d'identification_=C3=A0?=`

**Comment by jaapmarcus** [comment]
Thanks got notified via Discord already. Please submit a pull request with the made changes

**Comment by Faymir** [comment]
okay, i'll submit the PR then
