### ISSUE TITLE
[BUG]Deleting an IP makes nginx fail to restart

### ISSUE THREAD

**Issue by elerion64** [hestiacp/hestiacp#2053]
After deleting the x.x.x.x IP address, nginx fails to restart.
The file /etc/nginx/conf.d/x.x.x.x.conf remained, and nginx fails on listen to this IP with error:
nginx: [emerg] bind() to x.x.x.x:80 failed (99: Cannot assign requested address)

To Reproduce:
add a new IP x.x.x.x
(check if /etc/nginx/conf.d/x.x.x.x.conf is created)
delete IP

Expected behavior:
nginx IP config should be removed from /etc/nginx/conf.d/ also

Operating system: Ubuntu 20.04 LTS
Hestia Control Panel version:. 1.4.10

**Comment by jaapmarcus** [comment]
Did you run v-delete-sys-ip ?

https://github.com/hestiacp/hestiacp/blob/0ac3db88627e988ebf30e53f354c3ef3c365ee08/bin/v-delete-sys-ip#L94-L101

Please explain how you deleted the ip address?

**Comment by elerion64** [comment]
Just clicked delete under IP in the interface: (server - configure - network)

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/0ac3db88627e988ebf30e53f354c3ef3c365ee08/web/delete/ip/index.php#L15-L20

It does the same as above. So far I haven't notice any issue yet 

We run regular tests including v-delete-sys-ip with out issues.

**Comment by elerion64** [comment]
It happened on a server that is over 2 years old. (Maybe I've done something....) 
I'll try to recreate the bug on a new install over the weekend.

**Comment by jaapmarcus** [comment]
I am not able to replicate the issue on a new system.  We also run multiple test builds with the same test on our "test" cluster...
