### ISSUE TITLE
Folders for domains/subdomains

### ISSUE THREAD

**Issue by CaraTortu** [hestiacp/hestiacp#2057]
When you have lots of domains in hestiacp it is not comfortable to the eye to see all of the domains not classified. If you could be able to organise domains in folders it would be so much easier to look at!

**Comment by ScIT-Raphael** [comment]
We had this request already somewhere in our issue reports. The last time we discussed it within our team, we didnt saw a big practical need, also infact you should split up the domains to multiple users to get the best security. Also with the current panel code, it would be really hard to implement such a function.

Infact that we still plan to rewrite the whole backend, I'll close your request for now - it's just not possible to fullfill it with the available dev hours. If you want to provide it with a pull request, feel free to do so, we would love to review it.
