### ISSUE TITLE
[FEATURE] Metrics export to Prometheus

### ISSUE THREAD

**Issue by ostiwe** [hestiacp/hestiacp#2058]
**Is your feature request related to a problem? Please describe.**
I would like to be able to view server statistics via Prometheus. For example, the number of http requests, http errors, how much traffic was used, logs, and etc.

**Describe the solution you'd like**
Add the ability to export statistics to Prometheus (like {host}/hestia/metrics)

**Comment by ScIT-Raphael** [comment]
This is a to specific request which we can't fullfill with our limited available dev time. Please feel free to provide a pull request with the needed changes, we would review it for sure.
