### ISSUE TITLE
[FEATURE]I want to see the disk capacity of the server itself.

### ISSUE THREAD

**Issue by 810drawing** [hestiacp/hestiacp#2059]
**I want a function to display the disk capacity of the server including Hestia itself.**
This is because the current function does not know what percentage of the disk space is being used.

**Comment by ScIT-Raphael** [comment]
This is something where server monitoring like icinga2, nagios or zabbix steps in. I'll discuss with the team, if we gonna implement such a function. But probaly a proper monitoring system makes more sense.

**Comment by jaapmarcus** [comment]
https://xxxx.nu:8083/list/server/?disk

<img width="599" alt="Screenshot 2021-08-15 at 18 07 00" src="https://user-images.githubusercontent.com/9754650/129484903-81e886de-de61-464c-b81b-d42948387ab2.png">
<img width="707" alt="Screenshot 2021-08-15 at 18 06 56" src="https://user-images.githubusercontent.com/9754650/129484904-8001ad52-9cad-4fcd-a51d-66a2c6df6826.png">

Is more then enough?

**Comment by 810drawing** [comment]
If possible, I would like to see the usage status of each performance of the server in a graph. Is it possible?

**Comment by ScIT-Raphael** [comment]
Currently not no, also it isnt planed.
