### ISSUE TITLE
[BUG] Dovecot user auth is case-sensitive

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#2060]
**Describe the bug**
Not entirely sure if this is a bug or not, but thought I'd put it on your radar. 
I just migrated a client from an old Vesta install to a freshly installed Hestia. Everything was pretty smooth, but after a few days I got a message saying that they couldn't login with one of their email accounts which they called from a script. They tracked it down to the fact that their script was configured to connect to ServerAdmin@domain.com, which failed, but when they changed it to serveradmin@domain.com, it worked fine. 
I checked the two server configs in /etc/dovecot/conf.d/10-auth on the old server, there is no auth_username_format setting, but doveconf reports the value as "auth_username_format = %Lu "
On the new Hestia server, the value of auth_username_format is specified in 10-auth.conf, as auth_username_format = %u
Changing it to %Lu activates the case-insensitive login, which I did for this client, as it matches their previous configuration. 

Not sure if this is a bug. At the very least it might be filed under "Useful Information". The %u setting works fine on other servers that I'm handling.

**Comment by jaapmarcus** [comment]
From https://doc.dovecot.org/settings/core/

> auth_username_format
> Default: %u
> Values: String
> Formattting applied to username before querying the auth database.

If I search in  https://github.com/serghey-rodin/vesta/search?q=auth_username_format I can't find any config file except RHEL 5...  

Also Hestia != Vesta .

**Comment by jaapmarcus** [comment]
Also https://github.com/serghey-rodin/vesta/issues/1499 
They want it the other way around...

**Comment by plutocrat** [comment]
Yes, I wasn't suggesting you change it from the default %u. But I was flagging it as a possible migration issue Vesta > Hestia, and also a possible consequence of having authorisation via the file system which is case sensitive. 
Side note: I always believed that email addresses were case insensitive and that PERSON@DoMaIn.coM would get to the correct place. Which means it's slightly strange that dovecot would have case-insensitive as a default. Anyway, it was intended as more of an informational post.

**Comment by jaapmarcus** [comment]
It doesn't make sense to keep issues open that can't be fixed and the search engine will still be able to find them anyway.
