### ISSUE TITLE
[BUG] Pause button on the task monitor page

### ISSUE THREAD

**Issue by EmrahKayihan** [hestiacp/hestiacp#2065]
**Describe the bug**
Pause button on the task monitor page is not user-friendly when the dark theme is selected. 

**Expected behavior**
Needs to be a light colored button.

**Operating system:**
Ubuntu 20.04.2 LTS

**Hestia Control Panel version:**
v1.4.10

**Comment by jaapmarcus** [comment]
Should consider it migrating to Font Awsome instead.

**Comment by EmrahKayihan** [comment]
It is not a very important issue, just wanted to report. 

Edit: I have seen the pull request late :) Thanks...

**Comment by jaapmarcus** [comment]
Bug has been fixed update is scheduled for next week

**Comment by EmrahKayihan** [comment]
@jaapmarcus a new bug has appeared, it's only on firefox browser. Screenshot: https://i.ibb.co/0CdsmDT/Ekran-Al-nt-s.png

**Comment by jaapmarcus** [comment]
It sounds like Firefox doesn't like spinning icons :(
