### ISSUE TITLE
[BUG] Unable to load dynamic library 'pdo_mysql.so' after php reinstalling

### ISSUE THREAD

**Issue by ezy-code** [hestiacp/hestiacp#2069]
**Describe the bug**
I got this error after re-enabling php-fpm in multiphp installation.

PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql.so' (tried: /usr/lib/php/20170718/pdo_mysql.so (/usr/lib/php/20170718/pdo_mysql.so: undefined symbol: pdo_parse_params), /usr/lib/php/20170718/pdo_mysql.so.so (/usr/lib/php/20170718/pdo_mysql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**You can easy reproduce it on clean install:**
1. Nginx PHP-FPM without apache with multiphp flag
2. Disable all php versions except 7.4 through panel settings
3. Enable back any php version, for example 7.2
4. Then you got this error on 7.2 and after reboot on 7.4 too.

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
v1.4.10

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2070

Please check after installing this and rerun of v-delete-web-php 7.2 and v-add-web-php 7.2 if php7.2 still has issues.
