### ISSUE TITLE
phpmyadmin installed on raw IP - could be security issue

### ISSUE THREAD

**Issue by Lolabird** [hestiacp/hestiacp#2072]
https://github.com/hestiacp/hestiacp/blob/a92f143e03962ba8d6d47087d14ee049d5b124f4/install/deb/apache2/apache2.conf#L83

phpmyadmin installed on insecure IP which could be a security issue. Jaap Marcus in the discord suggested that it could be configured the way nginx does it and that there should be some way to prevent putting the phpmyadmin on the IP.

**Comment by sickcodes** [comment]
Yes I noticed too it doesn't have SSL and there's not way to add it (in the panel)

**Comment by jaapmarcus** [comment]
Easiest solution would be renaming phpmyadmin.conf to phpmyadmin.inc and include them on each site config

Putting it on port "8083" / Hestia port it would mean we need build the packages with Mysql (And later PostgreSQL support)  of course it will be possible...

**Comment by sickcodes** [comment]
Thanks, it was default on vesta, Ill figure it out on my end and try do  a PR

**Comment by jaapmarcus** [comment]
#2227 

And changes have been made
