### ISSUE TITLE
[BUG] I can't add multiple CAA records in the panel

### ISSUE THREAD

**Issue by slaapkopamy** [hestiacp/hestiacp#2073]
**Describe the bug**
The bug it's very simple to describe, If you try to add multiple CAA records with letsencrypt enabled for the domain the other CAA records won't be seen via CAA checkers. 

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Go to DNS tab
2. Add a new DNS record for the domain
3. Values of the DNS record: @ CAA 0 issue "digicert.com"
4. Do a check for the CAA records.

**Expected behavior**
Expected behavior should be that if you do a check for the CAA record with a checker that you have 2 records or more instead only one. 

**Screenshots**
https://imgur.com/72VsvBQ

**Operating system:**
Ubuntu 20.04.3 LTS

**Hestia Control Panel version:**
v1.4.10

**Additional context**
I tried first to google my issue but couldn't find anything related to it only then that you can add multiple CAA records.. 
I'm trying to add a custom sub domain to gitbook.io but I need for that a CAA record at the root domain with the values of digicert.. but meanwhile keeping my root domain on a letsencrypt certificate.

In the Discord server I asked about what I'm doing wrong but meanwhile its a bug in hestia itself...
message link: https://discord.com/channels/737721354937303161/738055454285889597/878267942847008788

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/0bdfb3ed84703ae6f2f7bf0343ecd5925b5df846/bin/v-add-letsencrypt-domain#L188-L193

We should add an detection of the CAA link is for LE or not

**Comment by jaapmarcus** [comment]
See pull request
