### ISSUE TITLE
[BUG] Debian 11 + Quota error 

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2080]
**Describe the bug**
When Installing Hestia with quotas enabled you will get this error:

`quotaon: Your kernel probably supports ext4 quota feature but you are using external quota files. Please switch your filesystem to use ext4 quota feature as external quota files on ext4 are deprecated.
`

**To Reproduce**
What steps did you take when the issue occured? 
 hst-install-debian.sh --with-debs /tmp/hestiacp-src/deb/ --quota yes 

**Expected behavior**
No error and to be working 

**Screenshots**

**Operating system:**
Debian 11

**Hestia Control Panel version:**
1.4.11

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
Quota seems to be working fine:

root@test:~# repquota -a
*** Report for user quotas on device /dev/sda1
Block grace time: 7days; Inode grace time: 7days
                        Block limits                File limits
User            used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
root      -- 2404032       0       0          64226     0     0       
daemon    --      72       0       0              4     0     0       
man       --    1520       0       0            160     0     0       
www-data  --      48       0       0             12     0     0       
_apt      --      12       0       0              3     0     0       
systemd-timesync --       4       0       0              2     0     0       
mysql     --  133024       0       0            286     0     0       
nginx     --       0       0       0              2     0     0       
Debian-exim --      68       0       0             15     0     0       
bind      --      16       0       0              4     0     0       
debian-spamd --      24       0       0              6     0     0       
admin     --    3132       0       0             64     0     0       
jaap      --      92    5120    5120             26     0     0

**Comment by jaapmarcus** [comment]
The issues seems to be harder to solve as it require a modifications during install or in recovery mode.

**Comment by cipitaua** [comment]
confirmed on debian sid, installed without quotas and enabled afterwards by adding usrquota,grpquota in /etc/fstab and then by
```
sudo mount -o remount /home
sudo quotacheck -ugm /home
sudo quotaon -v /home

quotaon: Your kernel probably supports ext4 quota feature but you are using external quota files. Please switch your filesystem to use ext4 quota feature as external quota files on ext4 are deprecated.
/dev/md0 [/home]: group quotas turned on
/dev/md0 [/home]: user quotas turned on
```

how do I "switch" to ext4 quota feature?

**Comment by jaapmarcus** [comment]
Need to be done in safe mode probally the easiest method is google it ...

**Comment by cipitaua** [comment]
I've already looked for solutions, without finding any. Could you please recommend a link?

**Comment by jaapmarcus** [comment]
https://unix.stackexchange.com/questions/578349/project-quota-on-a-live-root-ext4-filesystem-without-live-cd

Goodluck....

**Comment by cipitaua** [comment]
thank you. Since I'm not using quotas in root but in /home, it should be easier
