### ISSUE TITLE
Add much needed features

### ISSUE THREAD

**Issue by aljailane** [hestiacp/hestiacp#2084]
I have features that are very much needed in society, and I hope that they will be considered

- Please add the ability to fix all files linux permissions automatically in the file manager
- Possibility to change the header for e-mail
- 
![Screenshot_٢٠٢١٠٨٢٥_١٢٢٦٢٤](https://user-images.githubusercontent.com/14370075/130765757-3681c59a-aa1a-461c-a706-759c8d4e3ac4.jpg)

**Comment by divinity76** [comment]
fwiw i too am interested in adding chmod capabilities to the file manager

**Comment by jaapmarcus** [comment]
I asked the same question to the dev of the filemanager:

https://github.com/filegator/filegator/issues/112

So unless we change filemanger or or implement our own system it will not happen
