### ISSUE TITLE
[FEATURE] map instead of if in cache template

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#2085]
I noticed the cache template for nginx now use if statements for nocache. My understanding it can be a hit to performance and there's that whole thing I see constantly about "if is evil" I have a template I made for my own usage where I use the map function. I'm not you get familiar with submitting things to projects on here. If the developers are interested or anyone else is interested in the code to maybe submit it I'm happy to post it.

**Comment by jaapmarcus** [comment]
Please fork our project, Create a branch, Make any changes and commit them to your branch  and submit a pull request  via  "Compare & Pull request" or the new Pull request button.

**Comment by ghost** [comment]
ok, you actually just summed that up so easy lol TY. Reading up on it its just windbags blogging lol made it seem harder

**Comment by ghost** [comment]
> Please fork our project, Create a branch, Make any changes and commit them to your branch and submit a pull request via "Compare & Pull request" or the new Pull request button.

I think I just did it LOL Let me know if I did anything of the GIt part badly. The code is totally good though.

**Comment by jaapmarcus** [comment]
👍🏼  Start looks fine

**Comment by ghost** [comment]
> 👍🏼 Start looks fine
If the powers that be are good with moving to map instead of If, and want to use it, I'll change everything over.
