### ISSUE TITLE
[FEATURE] custom admin "modules"

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#2086]
Currently the admin section is completely uncustomizable except for the themes. Since the file changes would be reverted on any update it's not really convenient to do anything with it.

 I think either something similar to wordpress child themes. You have a folder and any file to put in it or use instead of the files in the main directory would be a great addition as it allow us to make edits conversation fee and then you would not be overridden but during an update the new phone to be in place and then we just have to update any changes.

It's really nice because we could include changes that allowed us to install things like a Redis GUI and have a quick accessible from admin

**Comment by jaapmarcus** [comment]
Yes it is a know issue. How ever changing this behaviour would mean a partial rewrite of our code base. 

At some point the investment need to add such feature it is probably smarter to convert the control panel to a framework to allow for modularity, php testing and a better templating system.

**Comment by ghost** [comment]
The easiest way may be to just add a protected directory and a protected file that can be used to add custom code to the admin footer. By default folder is empty and so is the include file. On updates just put a few lines to not overwrite them... Wouldn't that be the easiest?

**Comment by jaapmarcus** [comment]
It will work for adding link to the footer but nut for adding a link in the main menu. And how will it handle sessions and so on..  

If we are going to integrate it I would like some thing like:
https://github.com/hestiacp/hestiacp/blob/662f2f2df478f8e051fd3144a16512d52c8d7530/web/add/webapp/index.php#L90-L103

Where you drop in a certain php file in a folder (Plugins for example) with "basic" infomation and it the just works (Or enable /disable it via settings) We can add certain functions to generate menus based on the basic information and so on and maybe add certain to certain files so they will also remain in place on restoring the certain user... But that is future music...  

How ever it will be not out priority currently and as our development team is small we don't have time for this kind of things...

**Comment by xeruf** [comment]
maybe you can get some inspiration for modularity from https://github.com/solidusio/solidus, a superbly customizable webshop I am just now setting up next to Hestia ;)

**Comment by ghost** [comment]
Just a folder in the admin section that isn't overwrite that can serve from nginx. And aconf file for nginx included that is located where it won't be overwritten.then we can put ps there and use the nginx conf to set them up. Security and sessions can be handled by the admin as this would just be opening up the availability as an advanced custom option

**Comment by ghost** [comment]
One way that may be easy to set up a way to customise the admin may be a cron job that checks for a folder that is in the admin part but made presistant and if it exists it would make a change to nginx so it fist check for any files in that directory and if they exist uses thrm. if not defaults to the standard.

**Comment by Steveorevo** [comment]
Sounds like we need more "action" and "filter" hooks (not unlike how WordPress does it via a plugins directory). We already have pre and post install hooks to run routines after every upgrade. I use them to re-apply my modifications (in edition to my own /etc/hestiacp/local.conf) but it would be better if these two simple mods were in core:

1) Override $BIN in /usr/local/hestia/func/main.sh
2) Override HESTIA_CMD in web/api/index.php & web/inc/main.php

These values currently resolve to "/usr/local/hestia/bin/". 

Instead, I'd propose that they invoke any "filter hooks" found in a /usr/local/hesta/plugins folder, passing along the bin/v-* script name and it's parameters as filterable/hooked PHP functions [see how WordPress does it](https://developer.wordpress.org/plugins/hooks/filters/#example).

After invoking the hook, the mod would simply carry on its way invoking the original script in /usr/local/hestia/bin, along with any modified parameters the plugin has modified. 

Lastly, a "post" action could be introduced to do anything a plugin would like to accomplish after an API command has been executed.

**Comment by jaapmarcus** [comment]
> Sounds like we need more "action" and "filter" hooks (not unlike how WordPress does it via a plugins directory). We already have pre and post install hooks to run routines after every upgrade. I use them to re-apply my modifications (in edition to my own /etc/hestiacp/local.conf) but it would be better if these two simple mods were in core:
> 
> 1. Override $BIN in /usr/local/hestia/func/main.sh
> 2. Override HESTIA_CMD in web/api/index.php & web/inc/main.php
> 
> These values currently resolve to "/usr/local/hestia/bin/".
> 
> Instead, I'd propose that they invoke any "filter hooks" found in a /usr/local/hesta/plugins folder, passing along the bin/v-* script name and it's parameters as filterable/hooked PHP functions [see how WordPress does it](https://developer.wordpress.org/plugins/hooks/filters/#example).
> 
> After invoking the hook, the mod would simply carry on its way invoking the original script in /usr/local/hestia/bin, along with any modified parameters the plugin has modified.
> 
> Lastly, a "post" action could be introduced to do anything a plugin would like to accomplish after an API command has been executed.

The current existing hooks where a by pass to disable / enable demo mode that blocks running the update scripts and enabling / disabling where things that often forgotten..

If we want to implement such hooks we also need to invest time into a rewrite of the whole code base. It is just such a trash that is not worth to implement in the current version...

**Comment by Steveorevo** [comment]
They are just a two changes; but there is some code cleanup that needs to take place to ensure full extendability. I've submitted a pull request.

**Comment by Steveorevo** [comment]
I've created a side project to allow WordPress-like plugins to HestiaCP. It basically patches a few files to allow for third-party code hooks one can author and place into a /usr/local/hestia/plugins folder. It's a work in progress (though it would be great if HestiaCP would make the post_install.sh patches apart of core); it may provide a path for my customizations to not get thrown out after Hestia updates; if not just make my customizations more orderly and maintainable.

https://github.com/Steveorevo/hestiacp-pluginable

**Comment by jaapmarcus** [comment]
Personally modules maybe it is nice to have has no priority if you compare it with ipv6 support. And I think a lot of modules could become  part of the core.  For example Redis / Memcached support but are hard to execute due to security as you don't want a 2 sites of different users share the same database. 

Ideally a plugin support should be added but I don't want to do it in the current code as it is already reaching a point of  unable to maintain it in an efficient way... 

But we don't have enough time to develop everything. Instead overloading us with new features that are I think questionable instead of that we should focus on a lot of there things like IPV6 supports. If you think you can implement some new features   that you would like to add  to the core we are always open for PR and so on. But with only 1 active developer that is working on the backend there is a limit I reach very soon on what I can do.... 

And Hestia still doesn't pay me any dollar..

**Comment by Steveorevo** [comment]
A plugin architecture can alleviate some pressure as it allows you to isolate features. In the WordPress community, we have the idea of "canonical plugins"; this allows us to propose and implement major features that will eventually be rolled into core or at least allow the community to evaluate it. But one has to start out with a versatile enough plugin architecture. My project does hook most of the API and at very least allows code injection into web pages at various key-points. That may or may not be enough. 

But I understand that HestiaCP's user base is considerably smaller than WordPress and isn't funded; or at least not enough to address big goals at lightening speed. I hope to use HestiaCP for some of my SaaS ideas and naturally if it works out; I would be happy to contribute more coding and monetarily for sure. :)

I originally started out with ISPConfig, and while I'm a fan of their cluster mode; I found HestiaCP's out-of-the-box simplicity and support for imagemagick, multi-php stacks and nginx + apache much easier.

Hopefully 2023 will be more successful for all and in turn, allows HestiaCP to continue moving forward.
