### ISSUE TITLE
[BUG] Special Characters not escaped and json_decode returns empty value.

### ISSUE THREAD

**Issue by victor-vanherpt** [hestiacp/hestiacp#2090]
**Describe the bug**
Some special characters are not being escaped properly. For instance, when a value field with a tabulator is introduced, the json_decode function in the listing page returns an empty result. 

**To Reproduce**
Enter a new DNS record with a tabulator in the value.

**Expected behavior**
When accessing the list records page, records should be displayed.

**Screenshots**
![Captura de pantalla 2021-08-26 102157](https://user-images.githubusercontent.com/531901/130936759-99029c0a-d1ac-4d64-9892-b1774764b428.jpg)
![Captura de pantalla 2021-08-26 105916](https://user-images.githubusercontent.com/531901/130936763-b3d4475f-7436-495e-8e59-4410950945be.jpg)

**Operating system:**
Debian 10.10, php 7.4

**Hestia Control Panel version:**
v1.4.11

**Comment by victor-vanherpt** [comment]
I created a pull request that fixes this in this specific list (v-list-dns-records), but maybe a more global solution should be made.
I don't have time to suggest a better fix now, but in a few weeks i hope to have some more time :)

https://github.com/hestiacp/hestiacp/pull/2089

**Comment by jaapmarcus** [comment]
We will review and test the changes

**Comment by victor-vanherpt** [comment]
Yes, it seems it was copied from somewhere else. The records were being copied from a plesk panel, but I see the tabulation there as well, so it's been around for a while, from the website that requested the record as a verification (I have some cleanup to do in this domain, lol)
