### ISSUE TITLE
[SUPPORT] add hidepid gid feature

### ISSUE THREAD

**Issue by anvme** [hestiacp/hestiacp#2092]
**Please do NOT use our GitHub Project for support requests, you can find community support and help here:**

**Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
**Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
**Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)

Hello start was here  https://forum.hestiacp.com/t/proposal-hestiacp-zabbix-agent-process-monitoring-proc-num-0/4246  . I create feature allow to add gid to hestia conf. But how to add bash script which use sed to add/change value in crontab file? Commit https://github.com/anvme/hestiacp/commit/32d632b9c57f520854e39aafc235511344e8b0df

**Comment by jaapmarcus** [comment]
Easiest method is rm and then create a new one as done as done here:

https://github.com/hestiacp/hestiacp/blob/8c3e36693dc51d81efb10cf948c6c1d7fd6fd24d/install/hst-install-ubuntu.sh#L1027-L1032

If we would require a reboot it might make sense to not add it and just include in the docs how to solve this issue.  I don't like the idea of rebooting the system via executing a command without explaining..

**Comment by anvme** [comment]
> Easiest method is rm and then create a new one as done as done here:
> 
> https://github.com/hestiacp/hestiacp/blob/8c3e36693dc51d81efb10cf948c6c1d7fd6fd24d/install/hst-install-ubuntu.sh#L1027-L1032
> 
> If we would require a reboot it might make sense to not add it and just include in the docs how to solve this issue. I don't like the idea of rebooting the system via executing a command without explaining..

But we don't need to reboot. I just want to execute the bash script from hestiacp. And change value in crontab file

**Comment by jaapmarcus** [comment]
Running this code in v-add-sys-proc-gid  should work fine. No need to sed the value to the new value. Add some checks if it possible to use (Proxmox and maybe some systems more) and you should be done ...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp-docs/commit/2e60614f6ccc0a1377f8dfd77981b3e3d7669d04

I have added the required formation to solve this issue in the docs.
