### ISSUE TITLE
[FEATURE] redirect to a donation url on first run

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2095]
When installing for instance Mozilla Thunderbird in the first execution the user is redirected to a donation landing page where the user can choose not to donate or one-time donations or periodical donations.

I thought that it could be interesting to have that donation so that new features can be developed.

** Expected behavior **
The first time you visit https://my.server.tld:8080 a 301 redirect takes you to a donation landing page.

**Comment by jaapmarcus** [comment]
No!

**Comment by ScIT-Raphael** [comment]
We clearly don't want to beg for donations, which this is in my point of view. We already placed the dono link in the installer output.

**Comment by jlguerrerosanz** [comment]
Okay. Understood.

Buy bear in mind that the correct way for asking for donations is not maybe with a link in ssh.

Change the link and track the traffic. I guess it will be zero.

I only wanted to help sorry if I offended you in any way.

**Comment by ScIT-Raphael** [comment]
Opening a dono page is just spamming, at least in my point of view. If we want to generate more donations, we still can include the link on more positions, in the interface, maybe in the upgrade notifications and so on.

**Comment by ScIT-Raphael** [comment]
In addition: We do not have any interrests to track the traffic at all.

**Comment by ScIT-Raphael** [comment]
> I only wanted to help sorry if I offended you in any way.

Please don't feel attacked in any way just you got a "no" or a direct answer. It isnt meant that way and we've discussed this already a lot of times in our fourm (and here on github).

**Comment by jaapmarcus** [comment]
For Thunderbird, Filezilla and so on I makes sense to add an page where you can download the software and "do" with it...  We download the install script with in 1 second with wget...  So it would not help... 

We should be able to modify the "Install notification" 

https://github.com/hestiacp/hestiacp/blob/d34931a67cb5e2f4bc6118404e5662d2cb5d2b18/install/hst-install-ubuntu.sh#L2006-L2007

And in the email you receive when installing a update (and also update text in console)

**Comment by jlguerrerosanz** [comment]
That could work.

I would also suggest a small link below the Login box.
