### ISSUE TITLE
[BUG?] After update to 1.4.12, certificate set by v-add-letsencrypt-host gets overwritten by the server's hostname mail SSL cert

### ISSUE THREAD

**Issue by LucentW** [hestiacp/hestiacp#2096]
**Describe the bug**
As per title, after the upgrade to Hestia 1.4.12 (presumably from pull request #2061) the default certificate for Dovecot, which previously matched the server's hostname, has been overwritten by the one set on the control panel for the mail domain whose domain matches the server's hostname.
Needless to say, the mail domain SSL flag creates a certificate only for `mail.*` and `webmail.*` and not for the server's hostname itself.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Have a LE cert for the host with v-add-letsencrypt-host
2. Enable SSL on the host mail domain to have a valid SSL certificate for the webmail frontend 
3. Update to Hestia 1.4.12

**Expected behavior**
Avoid overwriting the server's certificate or use SNI to avoid serving the certificate for `mail.*`/`webmail.*` when the server's hostname is contacted, avoiding common name mismatches when people connect to the actual server's hostname.

**Screenshots**
n.a.

**Operating system:**
Debian 10.10

**Hestia Control Panel version:**
1.4.12

**Additional context**
n.d.

**Comment by LucentW** [comment]
Adding further info -- the code on the pull request sets the certificate for `mail.*` and `webmail.*` for both `$domain` and `mail.$domain`: https://github.com/hestiacp/hestiacp/pull/2061/files#diff-62c18a1929f0fac52499c934ab3e545cc654c35fccc2ee8cae29820cfa2899a2R700-R704

**Comment by jaapmarcus** [comment]
@LucentW  Your hostname is domain.com. You have added domain.com for mail and it overwrite it I presume?

**Comment by LucentW** [comment]
My hostname is `name.domain.com`, by default `admin` has `name.domain.com` as web+DNS+mail, to which I enabled the mail certificate so that customers can go to `webmail.name.domain.com` -- the issue being that with that commit, the certificate set by `v-add-letsencrypt-host` which had `name.domain.com` as common name gets overwritten by the one that covers only `mail.name.domain.com` and `webmail.name.domain.com`, effectively breaking all configurations that are pointing to `name.domain.com` and relying on the CN being correct.

Just removing lines from 700 to 704 referenced on the previous comment is sufficient to avoid this from happening, so that actual requests to `mail.name.domain.com` get the correct certificate, but won't get served one with non-matching CN+alternate DNS names when contacting `name.domain.com`.

**Comment by jaapmarcus** [comment]
I have added few extra checks to prevent this use case...

**Comment by LucentW** [comment]
Considering the mail certificate CN/alternate DNS fields aren't *"control panel controllable"* (defaults to `mail.domain.tld,webmail.domain.tld`), that code won't be hit except by manual fiddling with the configuration to add the main domain.

**Comment by jaapmarcus** [comment]
You can add your own certificate..

See #2061 

> Currently, the TLS support of IMAP/SMTP hard-coded the "mail." subdomain prefix.
> 
> If add a custom subdomain as mail domain and use custom TLS certificate, the TLS handshake will not be completed.
> 
> So improve it now.

**Comment by UnKnoWn-Consortium** [comment]
It also seems to have created a side effect of retarding secured SMTP connections from establishing via ```domain.ltd``` (now connections are only accepted via ```mail.domain.ltd```) which has been working since the very early versions.

**Comment by myrevery** [comment]
This issue should only occurs when the email domain is equal the hostname.

Marcus's PR https://github.com/hestiacp/hestiacp/pull/2097 is good.

@UnKnoWn-Consortium Now default certificate (SNI mismatch) of IMAP/SMTP will always fallback to "/usr/local/hestia/ssl/certificate.crt" that matches hostname.

**Comment by jaapmarcus** [comment]
> This issue should only occurs when the email domain is equal the hostname.

Yes that is correct. It will also prevent Dovecot serving an invalid certificate for domain.com. We should maybe consider expanding the script a bit and allow via general settings the addition for smtp.domain.com, imap.domain.com and pop3.domain.com

At the same time we should improve LE certificate creating and error reporting...

**Comment by myrevery** [comment]
About the "smtp." "imap." "pop3." subdomains, maybe we should investigate whether enough people need it.

Use "mail." subdomain in modern mail clients will not be an obstacle.

Add too many alias will make the TLS certificate large.

And Dovecot doesn't seem to support wildcard domain? Then the configuration will become more complicated.

**Comment by plutocrat** [comment]
Experiencing this too. Up until yesterday, this was the setup. 
hestia domain name = domain.com
client domain. = domain2.net
client mx record for domain2.net points to domain.com
Clients have outlook configured to connect to domain.com. It serves the right certificate. Outlook is happy. Email worked for several months. 

Starting yesterday, I assume after the 1.4.12 update, this happens:
Clients outlook connects to domain.com. Gets offered certificate for mail.domain.com. Complains, and won't connect until dialog box is OKed. Client panics. 
(Also freaking them out, the certificate is from R3, instead of Letsencrypt, but I checked, and that is a legit Letsencrypt cert name)

**Comment by jaapmarcus** [comment]
All users are affected if the use domain.com as hostname and mail.domain.com for email. We will release we are probably releasing the a new version beginning of next week 

> (Also freaking them out, the certificate is from R3, instead of Letsencrypt, but I checked, and that is a legit Letsencrypt cert name)

See https://letsencrypt.org/certificates/ it is correct...

**Comment by jaapmarcus** [comment]
Changes have been merged. Release with bug fix is scheduled mid next week
