### ISSUE TITLE
How to set ssl for the hostname

### ISSUE THREAD

**Issue by Amitxyz** [hestiacp/hestiacp#210]
Hi,

How to enable ssl for the hostname?

**Comment by ScIT-Raphael** [comment]
Same way like on vesta: https://forum.vestacp.com/viewtopic.php?f=10&t=17353

**Comment by Amitxyz** [comment]
I am trying to install ssl on debian 9 for the hostname,but i get this error:

root@vx:~# v-add-letsencrypt-domain 'admin' $HOSTNAME '' 'yes'
-bash: v-add-letsencrypt-domain: command not found

**Comment by ghost** [comment]
Have you logged out and logged back in or restarted the system since installing? There's an issue currently where the PATH variable isn't reloaded immediately after install which causes Hestia's commands to fail when executing them via BASH

**Comment by Amitxyz** [comment]
Great,it worked :)

**Comment by Pleskan** [comment]
@amitx11, You also may use full path like **/usr/local/hestia/bin/v-add-letsencrypt-domain**  I guess it is 100% working method.

**Comment by Amitxyz** [comment]
> Have you logged out and logged back in or restarted the system since installing? There's an issue currently where the PATH variable isn't reloaded immediately after install which causes Hestia's commands to fail when executing them via BASH

How to restart this,to make it work? I am trying on vps now and waiting almost 30 minutes now but still  getting - bash error

**Comment by ScIT-Raphael** [comment]
Restart the server or login and logout.

**Comment by Amitxyz** [comment]
I did, but still. I just installed the ssl from the panel to the hostname domain, but the next command still not working:
root@cx:~# v-update-host-certificate admin $HOSTNAME
bash: v-update-host-certificate: command not found

**Comment by ScIT-Raphael** [comment]
Did you also used the full path, as @Pleskan suggested in the post above? or switch to the directory /usr/local/hestia/bin, then run the commands.

**Comment by Amitxyz** [comment]
No,After waiting so long,rebooted the server several times , logged in and logged out..nothing helped,i installed from hestia panel the ssl,so cx.mydomain.com is working but to make it work for hestia, Exim and dovecot daemons the commands are not working:

root@cx:/usr/local/hestia/bin# v-update-host-certificate admin $HOSTNAME
bash: v-update-host-certificate: command not found

**Comment by Amitxyz** [comment]
Got it:
These has to be run first:
source /etc/profile
PATH=$PATH:/usr/local/hestia/bin && export PATH
