### ISSUE TITLE
[BUG] Nginx Caching for Wordpress causing redirect loop

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#2110]
**Describe the bug**
If your wordpress address is set without www, but you type in the browser using www. it will cause infinite loop.

Maybe this bug is related to this:
https://github.com/serghey-rodin/vesta/issues/1233

@anton-reutov  I provide steps on how to reproduce below

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occured? 
1. Install hestiacp with default settings here https://www.hestiacp.com/
2. add domain in hestia cp with this settings:
-) yourdomain.com with alias www.yourdomain.com
-) set nginx template to 'caching'
3. install wordpress by typing the address without 'www' during installation
4. in 'general settings' make sure 'WordPress Address' & 'Site Address' is without 'www'
5. Clean cache for this domain via hestiacp panel
6. On your browser type 'www.yourdomain.com' it will be infinite loop. or you wont get redirected to non-www.

**Expected behavior**
the www will be redirected automatically to non-www (tested with 'default' nginx template)

**Screenshots**

**Operating system:**
Ubuntu 20.04

**Hestia Control Panel version:**
Please enter your answer here (e.g. 1.3.2). 

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by jaapmarcus** [comment]
I am not able to replicate the issue.

Did you enable SSL for the domain?

No issues with No SSL as well if you have checked the issue you would see that we already use https://

**Comment by erikdemarco** [comment]
Hi @jaapmarcus Did you get redirected to non-www (yourdomain.com)? Do not look in browser's address bar. Sometimes its not right. Look from the developer tools (network tab).

So the error either you get redirected infinetly or you wont get redirected to non-www

**Comment by jaapmarcus** [comment]
Yes I got redirected from www.domain.com to domain.com

**Comment by erikdemarco** [comment]
@jaapmarcus The problem is in nginx.conf:
https://github.com/hestiacp/hestiacp/blob/39509be29beafdde0e226973514e77681406f287/install/deb/nginx/nginx.conf

Because currently proxy_cache_key is set to use "$host" only, so it cant differentiate between www and without www, between http and https. So both url will use the same cache
proxy_cache_key "$host$request_uri $cookie_user"

We should also use $scheme & $request_method to more differentiate the request url

NOTE: this is unrelated, but $cookie_user is useless parameter, dont have any use. we should get rid of it

**Comment by jaapmarcus** [comment]
So replace :

https://github.com/hestiacp/hestiacp/blob/fd42196718a6fa7fe17b37fab0933d3cbcb3db0d/install/deb/nginx/nginx.conf#L131

With 
https://github.com/hestiacp/hestiacp/blob/fd42196718a6fa7fe17b37fab0933d3cbcb3db0d/install/deb/nginx/nginx.conf#L139

Only proxy_cache instead

**Comment by jaapmarcus** [comment]
Fixed
