### ISSUE TITLE
[BUG] Outdated SSL certificate served even after renewing LE certificate

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2114]
**Some of the domains hosted under one of my machines show NET::ERR_CERT_DATE_INVALID error**

![image](https://user-images.githubusercontent.com/8811720/132266117-31c0163a-5064-4797-a299-29a714a6b090.png)

Although the domain configuration shows an updated LE certificate, the server is using an old one.

This is happening with several (maybe all) of the domains under the same machine.

**Comment by jaapmarcus** [comment]
Have seen the issue a few times before...

Have no idea why it is caused...

**Comment by ioannidesalex** [comment]
Same for me but couldn’t find either the source or replicate.

**Comment by jlguerrerosanz** [comment]
Do you need ssh access? How can I help you reproduce it?

**Comment by jlguerrerosanz** [comment]
It's a bug. But I still need to solve the issue. Can you please help me?

**Comment by jaapmarcus** [comment]
systemctl restart nginx should solve the issue but will not solve the root issue...

**Comment by jlguerrerosanz** [comment]
Yes. The restart of nginx took quite some time and it solved the issue.

If nginx restarted after each successful LE renovation would it be acceptable? Would that reasonably patch the problem?

**Comment by ScIT-Raphael** [comment]
We'll rework the v-update-letsencrypt script a bit, it should not hurt restarting the service once it runned trough.

**Comment by jaapmarcus** [comment]
v-add-letsencrypt-domain does not use a restart flag after updating ssl. Set default to yes when restart flag is empty

https://github.com/hestiacp/hestiacp/pull/2117

**Comment by myrevery** [comment]
https://github.com/hestiacp/hestiacp/pull/2117 may cause more issue.

This issue with Nginx has been existed for a long time.

I created special scripts to manage certificates, because I need additional ECC certificates, but it‘s difficult to merge them all into Hestia.

It actually completely took over renew certificates and handle Nginx service, and it has been working normally for several years since using Vesta.

I will share some useful fixes to Hestia later.

**Comment by jaapmarcus** [comment]
Why would a extra restart of Nginx cause more issues...  It already done during reload of the acme test any way ... 

How ever I think any changes are met that bad idea.. Please submit these :)

**Comment by myrevery** [comment]
I'm working on it...

Need to modify and test a lot, it takes some time.

**Comment by myrevery** [comment]
All done, see https://github.com/hestiacp/hestiacp/pull/2118 for details.

**Comment by ScIT-Raphael** [comment]
Fixed in #2118
