### ISSUE TITLE
[FEATURE] Support Reverse proxy, Hesitacp as backend web server multi domains

### ISSUE THREAD

**Issue by blackyzero** [hestiacp/hestiacp#2119]
**Is your feature request related to a problem? Please describe.**

Yes, i am using backend nginx multi domains on same server which are listening on different ports. They are behind reverse proxy/ssl termination 

Ex: abc.com: 1122
xyz.net: 1133
domain.org:1144

**Describe the solution you'd like**
Add custom port option for nginx web domain without manually creating custom nginx web template.

**Describe alternatives you've considered**
Workaround using separated nginx web template for each domain using different port setting, which is complicated to maintain.

**Additional context**

Thank you very much.

**Comment by ScIT-Raphael** [comment]
As already written in our forum, the feature request already exists: https://github.com/hestiacp/hestiacp/issues/1453

**Comment by liamgibbins** [comment]
This would be an owesome option to have, I have my cctv, nextcloud and my solarpv monitoring server all on different ports, this would make it so much easier for people wanting to use this already awesome panel either private like me or commercial like others do.
