### ISSUE TITLE
Feature request: Integration of sslh

### ISSUE THREAD

**Issue by hrvylein** [hestiacp/hestiacp#212]
Maybe giving the user the opportunity to install sslh during installation of hestiacp? Additionally every nginx (or apache) template has to be edited to listen on 127.0.0.1 instead of %ip%.

sslh is essential if one needs to setup openvpn, a webserver and/or ssh to listen on tcp port 443.

**Comment by ScIT-Raphael** [comment]
Thanks for your suggestion, I don't see any need in integrate sslh into hestia. Of course you're free to do this on your own system or fork!
