### ISSUE TITLE
[BUG] Debian 11 + 2 IPv4 = Always loads the page from /etc/nginx/conf.d/IP1.conf

### ISSUE THREAD

**Issue by tomclancys** [hestiacp/hestiacp#2121]
**Describe the bug**
After a clean install of Hestiacp on Debian11, everything works fine. But after I add the second IP address through Hestiacp, instead of my domain site.ru, the index.html page from /etc/nginx/conf.d/IP1.conf is always loaded
Then if I clear or delete the /etc/nginx/conf.d/IP2.conf file everything works fine again.

The structure of the files /etc/nginx/conf.d/IP1.conf and /etc/nginx/conf.d/IP2.conf is exactly the same, the only difference is in the IP address. 

**Operating system:**
Debian 11

**Hestia Control Panel version:**
1.4.12

**Comment by jaapmarcus** [comment]
Any errors in systemctl status nginx

**Comment by tomclancys** [comment]
At the moment, I did so. All lines in the /etc/nginx/conf.d/IP1.conf file were commented out. In /etc/nginx/conf.d/IP2.conf replaced address with *. And now it works fine. Apparently, when adding a second address through the panel, a conflict is created. Now everything works so great: 
server {
    listen *:80 default;
    server_name _;
    location / {
        access_log /dev/null;
        error_log /dev/null;
        root /var/www/html;

        location /phpmyadmin/ {
            alias /var/www/document_errors/;
            return 404;
        }

        location /phppgadmin/ {
            alias /var/www/document_errors/;
            return 404;
        }

        location /webmail {
            alias /var/www/document_errors/;
            return 404;
        }
        
        location /webmail/ {
            alias /var/www/document_errors/;
            return 404;
        }

        location /error/ {
            alias /var/www/document_errors/;
        }
    }
}

server {
    listen *:443 ssl http2 default;
    server_name _;
    ssl_certificate      /usr/local/hestia/ssl/certificate.crt;
    ssl_certificate_key  /usr/local/hestia/ssl/certificate.key;

    return 301 http://$host$request_uri;

    location / {
        root /var/www/document_errors/;
    }

    location /error/ {
        alias /var/www/document_errors/;
    }
}

**Comment by jaapmarcus** [comment]
I am not able to replicate the issue it would be usefull to see the error before you modified the config...
