### ISSUE TITLE
[BUG] hestia php will not be started

### ISSUE THREAD

**Issue by aehm2k5** [hestiacp/hestiacp#2126]
After upgrading ubuntu from 20.04 to 21.04 hestia cant be used anymore

errors:
Internal Server Error 500
/usr/local/hestia/php/sbin# ./hestia-php
./hestia-php: error while loading shared libraries: libzip.so.5:

2021/09/16 13:00:05 [crit] 6314#0: *10 connect() to unix:/var/run/hestia-php.sock failed (2: No such file or directory) while connecting to upstream, client: 10.7.0.2, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "xxxxx.xxxxxxxx.net:8083"

**To Reproduce**
update ubuntu from 20.04 to 21.04

**Expected behavior**
i should have access to hestia cp

**Screenshots**

**Operating system:**
ubuntu 21.04

**Hestia Control Panel version:**
latest version

**Additional context**

**Comment by aehm2k5** [comment]
update: if i create a symlink libzip.so.5 -> libzip.so.4.0 in /usr/lib/x86_64-linux-gnu
it works

**Comment by jaapmarcus** [comment]
Operating system:
ubuntu 21.04

Is not supported so you will never recive any updates any more...
