### ISSUE TITLE
[BUG] exim mail

### ISSUE THREAD

**Issue by aehm2k5** [hestiacp/hestiacp#2127]
**Describe the bug**
cant receive or send mails

**error log exim**
Tainted filename for search: '/etc/exim4/domains/xxxx-xxxx.de/aliases' 
H=mail.xXxXx-xxxx.de [xx.x.x.x] X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=no F=<xxxx@xXxXx-xxxx.de> temporarily rejected RCPT <x.x@xxxx-xxxx.de>: failed to expand "${extract{1}{:}{${lookup{$local_part@$domain}lsearch{/etc/exim4/domains/$domain/aliases}}}}": NULL
sender verify defer for <x.x@xxxx-xxxx.de>: failed to expand "${extract{1}{:}{${lookup{$local_part@$domain}lsearch{/etc/exim4/domains/$domain/aliases}}}}": NULL

**Expected behavior**
receiving and sending emails

**Hestia Control Panel version:**
latest

**exim version**
4.94

**Comment by ScIT-Raphael** [comment]
os?

**Comment by aehm2k5** [comment]
ubuntu

**Comment by jaapmarcus** [comment]
Ubuntu 21.04 is not supported please switch to 20.04.

**Comment by ScIT-Raphael** [comment]
As @jaapmarcus wrote, please stop opening issue report with an unsupported os.

**Comment by aehm2k5** [comment]
https://github.com/hestiacp/hestiacp/pull/2151
this one works, under ubuntu 21.04 just as info ;-)

**Comment by gOOvER** [comment]
> #2151 this one works, under ubuntu 21.04 just as info ;-)

Ubuntu 21.04 is no LTS Release, so i think you are on your own.

**Comment by aehm2k5** [comment]
i know i just would inform thats its working with that patch ;-) regarding to the problem i had
