### ISSUE TITLE
[BUG] ssl problem mail server ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by aehm2k5** [hestiacp/hestiacp#2128]
**Describe the bug**
2021-09-16 17:46:32 TLS error on connection from xxxxx(abc) [x.x.x.x] (cert/key setup: cert=/usr/local/hestia/ssl/certificate.crt key=/usr/local/hestia/ssl/certificate.key): Error while reading file.    
2021-09-16 17:46:56 TLS error on connection from xxxxxx(abc) [x.x.x.x] (cert/key setup: cert=/usr/local/hestia/ssl/certificate.crt key=/usr/local/hestia/ssl/certificate.key): Error while reading file.

**To Reproduce**
after install of the latest update

**Expected behavior**
should connect ether to port 465/587

**Screenshots**

**Operating system:**
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
root@vmd63245:/var/log/exim4#

**Hestia Control Panel version:**
latest 

**Additional context**
its since the update, until yesterday it worked there is NO OS updated

ls -la /usr/local/hestia/ssl/
total 20
drwxr-xr-x  3 root root 4096 Mar 18 14:07 .
drwxr-xr-x 12 root root 4096 Dec  2  2020 ..
lrwxrwxrwx  1 root root   82 Mar 18 12:12 certificate.crt -> /home/admin/conf/web/xxx-server.net/ssl/xxx-server.net.pem
lrwxrwxrwx  1 root root   82 Mar 18 14:07 certificate.key -> /home/admin/conf/web/xxx-server.net/ssl/xxx-server.net.key
drwxr-xr-x  2 root root 4096 Sep 16 05:32 mail

ls -la /home/admin/conf/web/xxx-server.net/ssl/
total 28
drwxr-xr-x 2 root root 4096 Jul 28 01:22 .
drwxr-xr-x 3 root root 4096 Jul 28 01:22 ..
-rw-r----- 1 root root 3750 Sep 16 05:32 xxx-server.net.ca
-rw-r----- 1 root root 2224 Sep 16 05:32 xxx-server.net.crt
-rw-r----- 1 root root 3243 Sep 16 05:32 xxx-server.net.key
-rw-r----- 1 root root 5975 Sep 16 05:32 xxx-server.net.pem

**Comment by jaapmarcus** [comment]
lrwxrwxrwx 1 root root 82 Mar 18 12:12 certificate.crt -> /home/admin/conf/web/xxx-server.net/ssl/xxx-server.net.pem
lrwxrwxrwx 1 root root 82 Mar 18 14:07 certificate.key -> /home/admin/conf/web/xxx-server.net/ssl/xxx-server.net.key

Files are not readable by exim

Dit you use v-add-letencrypt-host to enable ssl?

**Comment by aehm2k5** [comment]
no i used the cp

**Comment by ScIT-Raphael** [comment]
please use v-add-letsencrypt-host to install a propper ssl certificate according to our docs: https://docs.hestiacp.com/admin_docs/web/ssl_certificates.html#how-to-setup-let-s-encrypt-for-the-control-panel

**Comment by aehm2k5** [comment]
after changing the rights its working

**Comment by ScIT-Raphael** [comment]
I strongly suggest to use the susposed way over v-add-letsencrypt-host, it's the only official supported one and honestly quiet easy - so take it ;).
