### ISSUE TITLE
system messages getting marked as spam

### ISSUE THREAD

**Issue by xXKynarethXx** [hestiacp/hestiacp#213]
Whenever I setup a server with hestia, all messages from the system are getting marked as spam by the recipient.
Mostly this occurs with gmail users, my server's ip is not on a mx blacklist or sth.
You don't send system mails via php, do you?
Do you have any ideas how to fix this? Don't want my people have to look in the spam folders.

Thanks!

**Comment by ScIT-Raphael** [comment]
Can be bad IP reputation, not properly conifgured reverse dns record, and a lot of other things. We can't provide any free help here, but we plan to offer a payed support for such issues, that are not really related to hestia itself.
