### ISSUE TITLE
[BUG] Error description

### ISSUE THREAD

**Issue by matveyvelesov** [hestiacp/hestiacp#2136]
![1](https://user-images.githubusercontent.com/45035708/133943028-893c43b9-2b2c-473a-beaf-3431bf6f6ef1.png)

**Comment by jaapmarcus** [comment]
Changed on translations site...
https://translate.hestiacp.com/projects/hestiacp/en/default/?filters%5Bterm%5D=database&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
