### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by nagesh7588** [hestiacp/hestiacp#2138]
**Please do NOT use our GitHub Project for support requests, you can find community support and help here:**

**Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
**Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
**Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)
Hi!

I have a problem!

Server is pointing to other location needs VPS Configuration

I have installed a hestia cpanel and it was working fine.

Until last week the whole site started to point somewhere else and it now says server is ready to use.

There are 4 websites already running but none are opening and saying "server ready to use"

Warm Regards,

John
9911674402

**Comment by ScIT-Raphael** [comment]
Dear John, did you rread the text while opening the issue report...?

> **Please do NOT use our GitHub Project for support requests, you can find community support and help here:**
> 
> **Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
> **Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
> **Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)

**Comment by nagesh7588** [comment]
Hi!

So kind of you to reply so quickly.

Request: What do you mean by "did you rread the text while opening the
issue report...?"

Can you please provide a sample snap-shot.

Warm Regards,

John

**Comment by jaapmarcus** [comment]
<img width="1140" alt="Screenshot 2021-09-20 at 16 47 39" src="https://user-images.githubusercontent.com/9754650/134022930-c11ed827-180e-4d18-b686-22406acf7ec2.png">

This message but  https://forum.hestiacp.com/t/do-not-load-website-from-public-html/4487/24 will solve the issue
