### ISSUE TITLE
[BUG] v-add-web-domain-httpauth not showing auth

### ISSUE THREAD

**Issue by Fill84** [hestiacp/hestiacp#2139]
Hi, i tried to add a password to protect a domain via the following cli command "v-add-web-domain-httpauth"

i added all the options needed for the command "v-add-web-domain-httpauth user domain authuser authpassword" as the command is running i get the following messages: 
 ln: failed to create symbolic link *path */htaccess
 ln: failed to create symbolic link *path */htpasswd

after that nothing is happening. when i run the command again i get Error auth user already exists but the auth never shows up when i go to the domain.

I dont know if i'm doing something wrong or that there is something else not correct here,

many thanks in advance for fixing or helping

**Comment by Fill84** [comment]
i correct the symlink to apache2.conf_htaccess and apache2.ssl.conf_htaccess after i restarted apache it worked, so i think there went something wrong while creating the symlinks in the v-add-web-domain-httpauth script

**Comment by jaapmarcus** [comment]
Feel free to submit a pull request with the required changes.

**Comment by jaapmarcus** [comment]
See #2218 issue should be solved
