### ISSUE TITLE
[FEATURE] Is it possible to bulk create hostnames, Bulk self SSL generation ?

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2140]
Hi respected team.
Is it possible to bulk create hostnames, Bulk self SSL generation ? 

May be via CLI

**Comment by ScIT-Raphael** [comment]
I don't understand your request, but with the API you can bulk create web domains and also add self signed certificate. It just needs a few lines of bash scripting. I suggest to switch over to the forum with your request.
