### ISSUE TITLE
[BUG] Small interface bug in WEB-FTP section

### ISSUE THREAD

**Issue by AntsHere** [hestiacp/hestiacp#2145]
On page /add/web/ (or /edit/web/) in section “Additional FTP account(s)” when deleting all FTP it is impossible to add new FTP (button “Add FTP account” stops working).

To make it work it’s necessary to reload the page.

This behavior is due to the fact that the JS function “add_ftp_user_form” tries to do “$(’#templates’).find(’.ftptable’).clone(true)”, but all blocks with the ftptable class are removed.

![1](https://user-images.githubusercontent.com/73195325/134825033-6c74ed88-3f98-494d-b5e6-8bd6506579ae.png)
![2](https://user-images.githubusercontent.com/73195325/134825034-e39279a6-feea-4a71-a7e7-3ee243162339.png)

**Comment by jaapmarcus** [comment]
See attached pull request
