### ISSUE TITLE
Web templates missing when using multiphp

### ISSUE THREAD

**Issue by Lupul** [hestiacp/hestiacp#215]
First of all **thank you** for starting this fork of vestacp, I have just began testing HestiaCP and everything seems to work so much better out of the box.

### Brief issue description:
Usual web templates (wordpress, laravel, opencart etc) are supposed to be available when using multiphp install? I can only see phpversions as templates (php56,php70,php71 etc)

### Operating system distribution and release:
Ubuntu 18.04 LTS

### HestiaCP Version:
latest git commit: 014c203942eea9bae674221b87ec1b49cf0e5836 (tag: 0.9.8-28)

### What software is installed?
Nginx, PHP-FPM, Dovecot/Exim, MariaDB
install cmd: install/hst-install-ubuntu.sh -p XXXX --apache no --nginx yes --multiphp yes --hostname domain.tld --email mail@mail.tld

**Comment by ScIT-Raphael** [comment]
We work on a better implementation of multiphp on nginx/phpfpm systems. Until now, you've to copy the wanted php version template (for example php7.0) and adjust the template.
