### ISSUE TITLE
Feature Request: Additional UI controls for Mail administration (per domain/user)

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#216]
It would be kool if we had common mail settings integrated into the GUI without modifying conf files. We can break it down into 2 types of mail options Global and domain based. Some of the options could be auto delete spam and or trash every x amount of days, max attachment size, input a smart host, limit max # of emails sent per (day, hour, min, sec) Append message to outgoing email (useful for company policies such as non disclosure of email messages) blacklist, whitelist, spam filter level, etc.

**Comment by ghost** [comment]
Once we have the supporting back-end components in place, the mail admin UI for both users and server administrators will be undergoing an overhaul to implement many of these features.

**Comment by ScIT-Raphael** [comment]
Infact we moved this feature request around since nearly two years, we decided to close it: We currently do not have enough time to implement such a function, also it isnt on our highest priority. Please feel free to provide a PR for it, we would love to implement it.

**Comment by jaapmarcus** [comment]
Also some features has been added in the past
