### ISSUE TITLE
[BUG] search isn't working

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2166]
**Describe the bug**
the search option isn't working 

**To Reproduce**
What steps did you take when the issue occured? 
Click on the "Web" tab.
try to search anything
![image](https://user-images.githubusercontent.com/39749258/135729542-a044f1e9-e901-4c10-a575-fe9aa9e5a38e.png)

**Expected behavior**
search should work fine

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
v1.4.17 (tested on my own sevrer)

https://www.loom.com/share/7244620742854f4cbf0f88958fcefc4c

**Comment by alber-khan** [comment]
Hi, why the issue has been closed?

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2170

This pull request should fix the bug...

**Comment by alber-khan** [comment]
same issue when you download access and error log (v1.5.0)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/143457251-17d0ad6d-f981-4122-82d5-a6fd15080fdd.png)

**Comment by alber-khan** [comment]
@jaapmarcus

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/new?assignees=&labels=bug&template=BUG-REPORT.yml&title=%5BBug%5D+
