### ISSUE TITLE
[FEATURE] Add Remote URL upload & tar.gz compress and extract to file manager

### ISSUE THREAD

**Issue by viratsoft** [hestiacp/hestiacp#2169]
Hi, 
  please add this to file manger:
1.  Remote URL upload 
2.  tar.gz compress and extract 

thank you,

**Comment by ScIT-Raphael** [comment]
We don't use a own filemanager. If you want to like to have such additional features, please checkout the main project: https://github.com/filegator/filegator

**Comment by viratsoft** [comment]
okay, thank you
