### ISSUE TITLE
[SUPPORT] fork: retry: Resource temporarily unavailable

### ISSUE THREAD

**Issue by viratsoft** [hestiacp/hestiacp#2172]
![Screenshot_20211006-072439_Gmail](https://user-images.githubusercontent.com/49095830/136128642-c4b08324-61a2-49e9-b872-50e2f14e1e27.jpg)

continues receive mail with subject 
Cron <admin@****> sudo /usr/local/hestia/bin/v-update-sys-queue restart

 fork: retry: Resource temporarily unavailable

i have dedicated server with 32GB ram.
bellow is my ulimit -a output

real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 127855
max locked memory           (kbytes, -l) 4096097
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 127855
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited

please give me solution.. thank you

**Comment by viratsoft** [comment]
also get same error email with bellow subject with sudo: unable to fork: Resource temporarily unavailable
sudo /usr/local/hestia/bin/v-update-sys-queue backup
sudo /usr/local/hestia/bin/v-update-sys-rrd

**Comment by ScIT-Raphael** [comment]
First of all, please do not ignore the standard text when you open a issue report:

**Please do NOT use our GitHub Project for support requests, you can find community support and help here:**

**Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
**Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
**Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)

So still placing yours here is just wrong. Also for itself u should probaly increase the open file limit - spin up a google search with the error message and you'll get a few entries how to try to fix that problem.

**Comment by viratsoft** [comment]
sorry for wrong post.. thank you brother..
