### ISSUE TITLE
[BUG] /var/log/roundcube incorrect permissions

### ISSUE THREAD

**Issue by krg3** [hestiacp/hestiacp#2173]
On a default install permissions for /var/log/roundcube/ are owned by admin. The directory needs to be owned by www-data so that roundcube can write its logs. 

I had this problem on my production server. Spun a new Debian 10 VM to confirm the issue. Hestia 1.4.17.

**Comment by gejobj** [comment]
I have right permissions in my Ubuntu 20.04.3 LTS:
![screenshot](https://user-images.githubusercontent.com/9005888/136356268-f84a3929-1039-42b6-b301-84de863da540.png)
Maybe this bug is only for debian version?
Best regards.

**Comment by krg3** [comment]
Did some more testing. Issue is present on Debian 10 and 11. Permissions are correct on Ubuntu 18 and 20 LTS. Perhaps a slight modification to hst-install-debian.sh would resolve the problem.

**Comment by jlguerrerosanz** [comment]
I don't know if there is a place where all permissions are documented or if there is a script that could set all permissions to hestia defaults.

**Comment by johnnyq** [comment]
@jlguerrerosanz I agree a script to set all permissions correctly and then output the results start with the 

- The file that got updated
- the before permissions
- the after permissions

I have some files and directories that don't match the permissions on all my other instances of HestiaCP.

The script could be run on every upgrade to insure proper permissions.

**Comment by jlguerrerosanz** [comment]
Or just create a report of the discrepancies so the sysadmin can make decisions.

**Comment by jaapmarcus** [comment]
If it is still an older "Pre" 1.4.0" it might have other permission due to changes that have been made will add it to the update list for next version to chown the folder to the correct permissions
