### ISSUE TITLE
HestiaCP admin panel access with any hostname

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2174]
Im using HestiaCP with latest version (with automatic updates).
Once i created any domain, all DOMAIN:8083 are listening with admin panel's Backend port. This is security issue as hackers may try any open ports on any domain names,  by fate, they will know the new DOMAIN:8083 is listening for some admin interface.

How to protect the HESTIACP:8083 only to listen with server's hostname (or our main domain only ?

note: I already using with diff custom port, but the scenario wont change. :-)

**Comment by jaapmarcus** [comment]
Set POLICY_CSRF_STRICTNESS to 1 (Hostname and IP) or 2 (Hostname) only

**Comment by vvcares** [comment]
Hi @jaapmarcus , 
Thank you for your quick responses as usual :-)
Hopes you could set this as default setting on upcoming updates.

My point of view is, the admin panel should be allowed only by server's main domain instead of all domains.
Or may be i'm wrong, you might have some strong reasons for that.

**Comment by jaapmarcus** [comment]
It has been enabled for new installs and can be enabled by via the settings.

We decided it against enabling for "update" due to issues that might raise after enabling it...  If you go to /edit/web/?domain.com it will give you a error directly...
