### ISSUE TITLE
[BUG] BackBlaze Remote Backups: Unable to retrieve backup file from remote server

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#2178]
**Describe the bug**

https://forum.hestiacp.com/t/backblaze-backups-unable-to-retrieve-backup-file-from-remote-server/4695

I have a problem witht the remote backups and I don’t know where to look,

I have set the remote backups with BackBlaze, the backups are stored correctly, but I can’t download them from the panel.

I get this error:

![image](https://user-images.githubusercontent.com/88941527/136666251-ed11211c-2875-4b2b-bbfa-3dda69c4f9cc.png)

This how it’s set to use BackBlaze:

![image](https://user-images.githubusercontent.com/88941527/136666256-53626942-8c8d-41e3-b4cd-253400f0bb6c.png)

And you can see the backup it’s done

![image](https://user-images.githubusercontent.com/88941527/136666264-607ae809-53aa-47da-869d-a26c523105ec.png)

**To Reproduce**
What steps did you take when the issue occurred? 

Added the backblaze remote option and tried to download from the panel itself.

**Expected behavior**
Be able to restore & download from the panel.

**Screenshots**
already added.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
v1.4.17

**Comment by jaapmarcus** [comment]
Currently only backup has been implemented we need to add the download part….

**Comment by ghost** [comment]
> Currently only backup has been implemented we need to add the download part….

The restore it's implemented or just the backup?

**Comment by ScIT-Raphael** [comment]
just the backup, for restore you'll need to download the file from your bucked manualy to /backup and restore it over cli (v-restore-user).

**Comment by ScIT-Raphael** [comment]
Sorry, closed by mistake.

**Comment by ghost** [comment]
Okay, and another issue I have now, sorry.
It's stuck and I can't generate another backup (local) or restore (local)

The process it's pending since I tried to restore/download with a BackBlaze one, how can I stop it?

Already did [THIS ](https://forum.vestacp.com/viewtopic.php?t=16357) but seems to not work.
(changed vesta to hestia, the commands worked)

Thanks again!

**Comment by jaapmarcus** [comment]
Issue has been fixed for next release
