### ISSUE TITLE
[BUG] .user.ini accessible from web. 

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#2179]
**Describe the bug**
After the change to apache event + fcgi, if users want to add PHP values, they no longer went into .htaccess, but moved to .user.ini in the website root directory. 
Although there are rules blocking access to files starting .ht .git etc, there is no rule blocking .user.ini in nginx config, so the file is accessible from the web. While the info in .user.ini is typically not terribly sensitive, setting memory limits etc, I feel it should probably be blocked in the same way as .ht* files.  

**To Reproduce**
After creating a .user.ini file in the web root, load it in a web browser eg https://mydomain.com/.user.ini

**Comment by jaapmarcus** [comment]
I assume it is Nginx + Apache2? 

I will add 

`    location ~ /\.(?!well-known\/) { 
       deny all; 
       return 404;
    }`

To all Nginx Proxy templates like we did for Nginx + FPM

**Comment by plutocrat** [comment]
Yes this was detected on an nginx+apache system. I don't have any other type to try it out on.

**Comment by jaapmarcus** [comment]
In Nginx + FPM it was allready patched have applied the same rules also for Nginx + Apache2 installs
