### ISSUE TITLE
Feature Request: Thoughts on switching from BIND to unbound DNS

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#218]
Unbound is much much lighter, more secure, compliant, modern and faster DNS server any thoughts on possibly switching. It has compatibility with BIND Zone files.

**Comment by johnnyq** [comment]
Actually I was mistaken unbound is not an authoritative DNS Server, its only meant for caching, caching forward. Maybe switching to NSD as its an authoritative DNS Server only

**Comment by ScIT-Raphael** [comment]
We don't see any reason to switch the DNS server, bind9 is still state of the art, stable and works well.
