### ISSUE TITLE
[BUG] Old session files with custom name not being deleted

### ISSUE THREAD

**Issue by neto737** [hestiacp/hestiacp#2180]
**Describe the bug**
The old session files are not being deleted if they have a custom name. If the session file doesn't start with "sess_" these files will remain in the /tmp folder forever, or until you run out of storage and figure it out.

I've been running a website using CodeIgniter 4.1.4, and I was using a custom session file name, after few months I was running out of storage. As I already had this problem when using VestaCP a long time ago I know what to look, and found this issue.

**To Reproduce**
What steps did you take when the issue occured? 
1. Use a script that don't save session files with the dafault name, starting with "sess_"
2. Wait until it run out of storage
3. That's it.

**Expected behavior**
Session files being deleted after a determinate time, no mattering what is its names.

**Operating system:**
Debian 10.11

**Hestia Control Panel version:**
1.4.17

**Comment by jaapmarcus** [comment]
It is caused by the session cleanup script in php..

See https://salsa.debian.org/php-team/php-defaults/-/blob/main/sessionclean

**Comment by jaapmarcus** [comment]
See:
https://www.getpagespeed.com/server-setup/php/cleanup-php-sessions-like-a-pro

You have 3 option: Modify CI so they handle garbage collection
2: use the default session name
3 Write a script that checks every tmp folder for each user that deletes files older as xx hours of days...
