### ISSUE TITLE
[FEATURE] SSL Key should be emailed

### ISSUE THREAD

**Issue by PlayBoxTech** [hestiacp/hestiacp#2181]
**Is your feature request related to a problem? Please describe.**
When creating a new CSR, the key should be emailed to user creating it

**Describe the solution you'd like**
Email address on form should be made mandatory, and the created Key should be sent to that email address. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jaapmarcus** [comment]
Email address is not mandatory unless you are on 18.04 and has been removed for privacy reason as it ends  up in the certificate. 

We should probably add a download function for both CSR / Key.

**Comment by jlguerrerosanz** [comment]
Yes, the download function is essential.
