### ISSUE TITLE
[BUG] Domain change owner success but the permissions not changed to new owner

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2182]
**Describe the bug**
[BUG] Domain change owner success but the permissions not changed to new owner

**To Reproduce**
What steps did you take when the issue occurred? 
1. Existing domain, changed to diff owner (v-change-domain-owner USER DOMAIN)
2. The command is success & site is working well

**Expected behavior**
3. But when we do FTP using new owner, it denies to amend the files inside '/web/DOMAIN/public_html/FOLDERS '
4. Realized the owner permissions to folders are set to '0' instead of owners id '100x'
5. Then we did CHOWN OWNER:OWNER to get it resolved.

**Operating system:**
Ubuntu 20.04 LTS

HESTIA - Latest version

**Comment by johnnyq** [comment]
Anybody else able to confirm this? I do not have a domain that needs the owner changed but ill try on my test platform to see if I can replicate.

**Comment by vvcares** [comment]
@johnnyq , Actually you no need any real/live domain. Just create a dummy domain and try the same as i had issues. You can check . Thank you

**Comment by jaapmarcus** [comment]
I have no issues with permissions how ever I can't login any more with ftp...

Chmodding should be done on default:
https://github.com/hestiacp/hestiacp/blob/035eb154cfbc116162f73abb3c08441c1f14ae80/bin/v-change-domain-owner#L97-L99

Please check if https://github.com/hestiacp/hestiacp/pull/2210
fixes the issue

**Comment by jaapmarcus** [comment]
@vvcares  Please check if the bug has been solved

**Comment by vvcares** [comment]
Hi. Sorry for the delay. I will chk soon. Thank you

**Comment by vvcares** [comment]
> @vvcares Please check if the bug has been solved

Hi @jaapmarcus 
Today, i checked it, ok now.
I just created a new DUMMY.COM and moved to another user via CLI & i compared the permissions for public_html, it shows as new USER. So no issues today.
