### ISSUE TITLE
[BUG] - DIR vendor

### ISSUE THREAD

**Issue by avta77** [hestiacp/hestiacp#2186]
В файле /usr/local/hestia/web/inc/main.php есть трока  require 'vendor/autoload.php';   данной директории (vendor) и файла (autoload.php - данный файл пустой) не было, мы их создали и панель заработала, можете об этом написать разработчикам hestia

**Comment by ScIT-Raphael** [comment]
Please open your ticket in english, we can't provide support for any other language.
