### ISSUE TITLE
[SUPPORT/BUG?] Freeze VM at 6:15 everyday after run cron

### ISSUE THREAD

**Issue by iT0mT0m** [hestiacp/hestiacp#2189]
VM specification:
VM: 1vCPU/3GB RAM/24GB SSD
OS: Debian 11
HestiaCP: 1.4.17

Problem description:
Everyday at 6:15 o'clock I have a freeze machine after run cron. I reinstalled Debian and installed again clean HestiaCP but problem still occurs. I host 3 websites with 3 mail accounts. I stopped clamav and used my-small.cnf config for mysql because I think I have too small ram memory for all services. Anybody have this problem too?
[https://imgur.com/Ji0Rm9S]

**Comment by ScIT-Raphael** [comment]
As already stated in the issue text while you open a support related ticket, please do not use our github tracker for support requests.

Place your request in our forum (https://forum.hestiacp.com) or on our discord.
