### ISSUE TITLE
Error while installation on Debian 9

### ISSUE THREAD

**Issue by xXKynarethXx** [hestiacp/hestiacp#219]
### Brief issue description:
When I try to install vestiacp on my Debian 9 KVM Server, the installation fails.
I tried it multiple times, and it's the same error every time, does someone know a solution?
Thanks anyone who can help me with that!

### Steps to Reproduce:
I used these commands:
- apt update & upgrade
- mkdir vestiacp --> cd vestiacp
- bash hst-install.sh --> y 

### Expected behavior:
Installtion should be successful

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
latest

### What software is installed?
normal installation --> bash hst-install.sh

### Installation & it's errors

  _   _           _   _        ____ ____  
 | | | | ___  ___| |_(_) __ _ / ___|  _ \ 
 | |_| |/ _ \/ __| __| |/ _` | |   | |_) |
 |  _  |  __/\__ \ |_| | (_| | |___|  __/ 
 |_| |_|\___||___/\__|_|\__,_|\____|_|    

                      Hestia Control Panel

The following software will be installed on your system:
   - Nginx Web Server
   - Apache Web Server (as backend)
   - Bind DNS Server
   - Exim Mail Server + ClamAVSpamAssassin
   - Dovecot POP3/IMAP Server
   - MariaDB Database Server
   - Vsftpd FTP Server
   - Iptables Firewall + Fail2Ban

Would you like to continue? [y/n]: y
Please enter admin email address:
Please enter FQDN hostname

Installation backup directory: /root/hst_install_backups/160320191559
Installation log file: /root/hst_install_backups/hst_install-160320191559.log

Updating currently installed packages, please wait...\
Installing required repository keys... 
(*) NGINX
(*) PHP
(*) MariaDB
(*) Hestia Control Panel
Installing Hestia Control Panel and required dependencies...
NOTE: This process may take 10 to 15 minutes to complete, please wait...-
hst-install-debian.sh: Zeile 846: ntpdate: Kommando nicht gefunden.
sed: /etc/rssh.conf kann nicht gelesen werden: Datei oder Verzeichnis nicht gefunden
sed: /etc/rssh.conf kann nicht gelesen werden: Datei oder Verzeichnis nicht gefunden
sed: /etc/rssh.conf kann nicht gelesen werden: Datei oder Verzeichnis nicht gefunden
chmod: Zugriff auf '/usr/bin/rssh' nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/sudo/admin' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
chmod: Zugriff auf '/etc/sudoers.d/admin' nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/logrotate/hestia' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/packages' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/templates' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/firewall' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
hst-install-debian.sh: Zeile 1004: /usr/local/hestia/bin/v-generate-ssl-cert: Datei oder Verzeichnis nicht gefunden
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes »,«
sed: -e Ausdruck #1, Zeichen 1: Unbekannter Befehl: »,«
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/nginx/nginx.conf' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/nginx/status.conf' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/nginx/phpmyadmin.inc' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/nginx/phppgadmin.inc' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/nginx/webmail.inc' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/usr/local/hestia/install/debian/9/logrotate/nginx' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
hst-install-debian.sh: Zeile 1033: /etc/nginx/conf.d/hestia.conf: Datei oder Verzeichnis nicht gefunden
Failed to start nginx.service: Unit nginx.service not found.
Error: nginx start failed

**Comment by ghost** [comment]
This is caused by a missing package on our development branch, I'll have this patched shortly -- sorry for any inconvenience.

**Comment by ScIT-Raphael** [comment]
@kristankenney already patched :-).

We had made a little mistake during the switch to our beta / master branches, it took the installer from beta instead master branch. This was fixed with the following commit: https://github.com/hestiacp/hestiacp/commit/28ac03ac67032067bdac68511d01055a50c16953

Please try the installation again and let us know if all works as expected!

**Comment by kristankenney** [comment]
For future reference, https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install.sh is the correct URL for installation going forward. :)

**Comment by xXKynarethXx** [comment]
Just tried it, works like a charm!
Tranks so much for your blazing fast answers!!
\\can be closed

**Comment by ScIT-Raphael** [comment]
@xXKynarethXx Thanks for your fast feedback - sorry for the troubles! Let me know if you will find anything else. Btw: We will push Release 28 in a few seconds, including some backend refresh and also 2 factor authentication.
