### ISSUE TITLE
[BUG] Webmail not accessible when using secondary ip

### ISSUE THREAD

**Issue by cmstew** [hestiacp/hestiacp#2191]
1. Add a second IP to server
2. Edit web domain and change IP
3. Try to access webmail
4. Get default success page

**Comment by jaapmarcus** [comment]
I think that we don't rebuild webmail config after we update the ip of the web domain

**Comment by cmstew** [comment]
I just confirmed that these nginx configs do get updated:

`/etc/nginx/conf.d/domains/sub.domain.com.conf` and `/etc/nginx/conf.d/domains/sub.domain.com.ssl.conf`

Will need further investigation.

**Comment by jaapmarcus** [comment]
Just checked on my local server: 

v-add-web-domain jaap jaap.xx
v-add-mail-domain jaap jaap.xx
v-change-web-domain-ip jaap jaap.xx ip2.x.x.x

cat webmail.jaap.xx
listen      192.168.2.10:80;

So it doesn't update as it should be.

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/2212

**Comment by ANTONIOPSD** [comment]
I have this problem on 1.6.14
