### ISSUE TITLE
[Question] Not able to use main domain

### ISSUE THREAD

**Issue by ultra-pool** [hestiacp/hestiacp#2196]
For the past 2 months or so. Iv have not been able to use a main domain like `https://thisIsit.com` like I used too. Now its only supporting something. `https://subthis.thisIsit.com` I have not tried just using `https://www.thisIsiit.com` but normally I haven't been using www just without it. Has something changed within Hestia code to make this happen where you have to use a sub domain of some type or a www?

**Comment by jaapmarcus** [comment]
Please use https://forum.hestiacp.com
