### ISSUE TITLE
Problems with SFTP Backup

### ISSUE THREAD

**Issue by killer30001000** [hestiacp/hestiacp#220]
### Brief issue description:
Whenever I try to setup Backups via SFTP, I get the error code 1.
I tried it with two different sftp Servers and nothing worked. I can connect to them via SFTP-Clients without any issues.

### Steps to Reproduce:
Add SFTP as Backup location

### Expected behavior:
SFTP Backup location added

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
Newest

### What software is installed?
apache, nginx, vsftpd, mysql, exim, dovecot, clamav, spamassassin, iptables, fail2ban

**Comment by ghost** [comment]
Hi @cr1s3c,

Thanks for your bug report. We're investigating this and will follow up when we have more information.

**Comment by xXKynarethXx** [comment]
Fyi: Also being discussed at vesta Forum, Link: https://forum.vestacp.com/viewtopic.php?t=17923

**Comment by ghost** [comment]
Thanks for the info @xXKynarethXx. I'm able to replicate the issue, @cr1s3c if you have a moment can you follow the instructions in the link that was provided to configure your SFTP backup and then also check the control panel settings to see if they match what was entered in the configuration? Replace any instances of **vesta** with **hestia**.

**Comment by cr1s3c** [comment]
I tried the instructions in the link and it worked perfectly, the informations are showing inside of the control panel settings as well. It works as well after deleting the known_hosts file. After that I tried to set the sftp informations in the control panel settings by myself and I got the error code 1 again.

**Comment by ScIT-Raphael** [comment]
@cr1s3c thanks for your informations! I'm sure we can get this fixed, it looks like a "wrong" check routine - we will update you soon.

**Comment by ScIT-Raphael** [comment]
Was able to fix this with the following commit: https://github.com/hestiacp/hestiacp/commit/12d92feae38c94133cb8c7855b082bdff494a7d8

The commit is in beta branch, can you please manually download the file into your /usr/local/hestia/bin and check again if all works as expected?

```
wget https://raw.githubusercontent.com/hestiacp/hestiacp/beta/bin/v-add-backup-host -O /usr/local/hestia/bin/v-add-backup-host
chmod +x /usr/local/hestia/bin/v-add-backup-host
```

**Comment by cr1s3c** [comment]
@ScIT-Raphael I tested it using the WebUI and CLI and both worked perfectly fine. Thank you very much!

**Comment by ScIT-Raphael** [comment]
Perfect, thanks for your feedback, will close this bugreport. Please feel free to reopen it or create a new one if you find any additional issue.
