### ISSUE TITLE
[SUPPORT] How to restrict phpmyadmin to localhost only?

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#2213]
Using hestia v1.3 I can do it by adding this line to '/etc/phpmyadmin/apache.conf':
<RequireAll>
    Require local
</RequireAll>

But in newest version. I got 500 error. 'requireall is not allowed here'

How to do it right in new version of hestiacp?

**Comment by ScIT-Raphael** [comment]
We do not provide any support over github, this has been stated in the text you removed while opening it. Please use our forum or discord, be sure you updated to the latest hestia version before you send out a request.
