### ISSUE TITLE
[BUG] Could not reliably determine the server's fully qualified domain name

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#2215]
Fresh install of hestiacp without bind9.
after installation finished. test apache2 config using 'apache2ctl configtest'
it will show warning 'Could not reliably determine the server's fully qualified domain name'

To fix this, during installation. hestiacp must automatically add this line into /etc/apache2/apache2.conf:
ServerName {User_Inputed_FQDN}

**Comment by jaapmarcus** [comment]
Solution is to set a proper FQDN in /etc/hosts file that should be setup before installing Hestia.

127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
# --- BEGIN PVE ---
x.x.x.x test.xxx test
# --- END PVE ---

Nov 04 21:46:20 test systemd[1]: Starting The Apache HTTP Server...
Nov 04 21:46:20 test systemd[1]: Started The Apache HTTP Server.
root@test:~# 

When you remove the x.x.x.x test.xxx test 

Nov 04 21:45:43 test systemd[1]: Starting The Apache HTTP Server...
Nov 04 21:45:43 test apachectl[1577]: AH00557: apache2: apr_sockaddr_info_get() failed for test
Nov 04 21:45:43 test apachectl[1577]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the >
Nov 04 21:45:43 test systemd[1]: Started The Apache HTTP Server.


Solution would be adding grep -I "Hostname" and if missing add them to the hostname

**Comment by erikdemarco** [comment]
Maybe setting the servername to localhost will be better choice than set it to FQDN?.

This is official solution from ubuntu:
=> https://help.ubuntu.com/community/ApacheMySQLPHP#Troubleshooting_Apache

**Comment by ScIT-Raphael** [comment]
Probaly not, configure hosts the right way with a propper fqdn is a must and often already done from several vps providers or lxc templates.

**Comment by jaapmarcus** [comment]
> Maybe setting the servername to localhost will be better choice than set it to FQDN?.
> 
> This is official solution from ubuntu: => https://help.ubuntu.com/community/ApacheMySQLPHP#Troubleshooting_Apache

help.ubuntu.com/comunity is nothing more than a forum. So it is not the official solution...

**Comment by erikdemarco** [comment]
> Probaly not, configure hosts the right way with a propper fqdn is a must and often already done from several vps providers or lxc templates.

@ScIT-Raphael Hi, any example how to put it using fqdn correctly, if for example our fqdn is cp.hestiacp.com?
I tested fresh installation of vanilla hestia on both digitalocean and ovh. It still show the same error

**Comment by jaapmarcus** [comment]
I have added a check if hostname is present in /etc/hosts and if not it will add it to it ...

https://github.com/hestiacp/hestiacp/pull/2216

**Comment by 3ruce** [comment]
I ran into trouble with the valid hostname stuff, even though I changed it a bunch of times...

I just edited line 178 of hst-install-debian.s to `return 1` instead of `return 0`

Kind of weird as I used other hostnames running hestia on them and that also didn't work...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/0b1fa128a5f8da5cf6f5506e23a6069f40c0be57/install/hst-install-debian.sh#L172-L181

Check if fine how ever domain.com is  according https://www.rfc-editor.org/info/rfc1178 should not been used...

**Comment by 3ruce** [comment]
Thank you...
