### ISSUE TITLE
[BUG] Backup restore from FTP does not transfer tar file

### ISSUE THREAD

**Issue by gatsukito** [hestiacp/hestiacp#2217]
**Describe the bug**
I have hestiacp with backup system with only ftp remote. I connect with FTP, no SFTP. Generate backup works fine, but restore backup hestia returns error because there is not a file in /backup. I am trying to get backup file with function script, and my console is waiting and does not connect.

**To Reproduce**
What steps did you take when the issue occured? 
1. Configure server with local backup NO and remote backup FTP
2. Generate a new backup
3. Restore this new backup
4. See the restore.log, there is an error

```
tar: /backup/viv_miq.2021-11-06_00-15-10.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Error: Can't unpack PAM container
```

**Expected behavior**
It should be worked fine

**Operating system:**
Debian 11.1

**Hestia Control Panel version:**
1.4.17

**Comment by jaapmarcus** [comment]
Please try if the bug is still present in the main / alpha version. We have made some changes to it since 1.4.17 release...

https://github.com/hestiacp/hestiacp/pull/2199/commits/37fda6e3cf36f161497cbda380976b2578706858

**Comment by gatsukito** [comment]
Solved, I have rebooted my servers and all systems work.
