### ISSUE TITLE
[BUG] Basic httpauth issue

### ISSUE THREAD

**Issue by pacomedina** [hestiacp/hestiacp#2218]
Hello,

Activating access control with with the official command will not work properly.
Using the command : 

```
# v-add-web-domain-httpauth admin test.com test password
ln: failed to create symbolic link '/home/admin/conf/web/test.com/htpasswd': File exists
ln: failed to create symbolic link '/home/admin/conf/web/test.com/htaccess': File exists
```
While it was the first time I did this command on this new vhost for testing, and a fresh install of Hestia.

Then if you configure it manually via .htaccess/.htpasswd or into Apache configuration + restart, you can call for a known page/file :

1.
User access control will only work if you call for the folder and default index.html/php.
If you call explicitly for this index.html/php in your URL you can access without authentication.

2.
If then you send any request to get some content with the exact URL (ex: http://test.com/test/test.htm) you have access.

In my case (migrating a website) I could gain access just clicking on the "Cancel" button when it was asking me for authentication.

I can reproduce those issues on a fresh install :

v1.4.17
Ubuntu 20.04 (x86_64)

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/2139
