### ISSUE TITLE
[BUG] Basic httpauth not working properly

### ISSUE THREAD

**Issue by pacomedina** [hestiacp/hestiacp#2219]
Configuring basic httpauth like this : https://forum.hestiacp.com/t/file-path-for-htaccess-to-password-protect-directory/1739/7

User access control will only work if you call for the folder and default index.html/php.
If you call explicitly for this index.html/php in your URL you can access without authentication.

If then you send any request to get some content with the exact URL (ex: http://test.com/test/test.htm) : you have access without authentication.

In my case (migrating a website) I could gain access just clicking on the "Cancel" button when it was asking me for authentication.

I can reproduce thise issues on a fresh install :

v1.4.17
Ubuntu 20.04 (x86_64)

**Comment by jaapmarcus** [comment]
See #2118 please keep simallar issues under same issue It makes debugging way easier

**Comment by jaapmarcus** [comment]
Also for questions use the forum

**Comment by pacomedina** [comment]
Hello,

Thank you but I don't really find the link between the issue #2219 and the #2118.

**Comment by jaapmarcus** [comment]
Wrong issue id:
https://github.com/hestiacp/hestiacp/issues/2218#event-5577688860

**Comment by pacomedina** [comment]
Thank you for you answer, but you closed the #2218 because of using the script : v-add-web-domain-httpauth

But what I found is another issue, it is different and not related to this script.
In this case I'm just using a regular .htaccess et .htpasswd file.

I send a request on the forum, but I suggest you should try to reproduce the problem.
Because there is an issue using basic http auth on a fresh installed Hestia.

Here is what I found : 

/test/ = OK it’s asking for auth, and if I cancel I get a 401 error.
/test/index.html : KO (it’s not asking for auth and I gain access)
/test/test.html : KO (it’s not asking for auth and I gain access)
/test/test.avi : KO (it’s not asking for auth and I access)
/test/test.test : OK it’s asking for auth, and if I cancel I get a 401 error.

Using a basic .htaccess in the folder /test/ : 

```
AuthName "Restricted Area"
AuthType Basic
AuthUserFile /home/admin/web/test.com/.htpasswd 
require valid-user
```

**Comment by pacomedina** [comment]
It's seems that I'm not the only one : https://forum.hestiacp.com/t/file-path-for-htaccess-to-password-protect-directory/1739/9

Can you open back and take this issue ?

**Comment by jaapmarcus** [comment]
It is not a bug:

All files with extension in the "proxy" list are handled by nginx and by pass .htaccess file that is only Apache2 only...

By default are:
`jpg, jpeg, gif, png, ico, svg, css, zip, tgz, gz, rar, bz2, doc, xls, exe, pdf, ppt, txt, odt, ods, odp, odf, tar, wav, bmp, rtf, js, mp3, avi, mpeg, flv, html, htm`

Create a template that doesn't use 

https://github.com/hestiacp/hestiacp/blob/d5f0028293c307148cbb3589da9b9409c8699ab8/install/deb/templates/web/nginx/default.stpl#L17-L26

But only 

    location / {
        proxy_pass      https://%ip%:%web_ssl_port%;
    }
    
 It can be solved on Nginx level by creating a custom template or in case of sub folder 

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

In /$HOMEDIR/$user/conf/web/$domain/nginx.conf_htaccess
