### ISSUE TITLE
"Connection to storage server failed." dovecot error 

### ISSUE THREAD

**Issue by Pleskan** [hestiacp/hestiacp#222]
### Brief issue description:
This error appears while trying to login to Roundcube WebGUI due to incorrect dovecot configuration inherited from VestaCP — https://prnt.sc/mz45wi

### Steps to Reproduce:
1. Install Hestia from master branch
2. Create new mail account and try login to it
3. View error mentioned above

### Expected behavior:
Working dovecot mailbox and Rouncube webinterface without quirks.
### Operating system distribution and release:
Ubuntu 16.04.5

### HestiaCP Version:
0.9.8-28

### What software is installed?
Nginx, PHP-FPM, Dovecot/Exim, MariaDB, fail2ban

### Related issues or forum threads:
Issue [#1716](https://github.com/serghey-rodin/vesta/issues/1716) VestaCP
### Additional notes:
Excerpt of [dovecot](https://pastebin.com/NV6UbHrd) log  with error

**Comment by Pleskan** [comment]
@kristankenney, I would like to send you VPS credentials if you are still interesting in eliminating subject issue

**Comment by ghost** [comment]
Thanks for the information @Pleskan and sorry for the inconvenience that this is causing you, we'll take a look into this further. 

Please note that we are planning to overhaul the installation and upgrade processes, hopefully for the next release if all goes well. This will eliminate much of the duplicate code that currently exists within Hestia and ensure consistency, and we are also working on the underlying mail system to make it more robust. 

Again, pleae accept my apologies for the inconvenience, I'll post an update here once a fix is in place

**Comment by Pleskan** [comment]
@kristankenney, ok thanks for quick response, I understand that you and team have no time to test my pull request due to working on completely new Hestia user experience, **Hestia Remastered** :-)  for short. There is no problem at all. Don't hesitate to contact me for testing environment to see subject bug by yourself in the  future.
Regards!

**Comment by ghost** [comment]
@Pleskan, have you had a chance to test this on your end against Ubuntu 18.04 LTS yourself or just 16.04.5?

**Comment by Pleskan** [comment]
@kristankenney original [issue](https://github.com/serghey-rodin/vesta/issues/1716) and my fix at VestaCP repo.
OK, I'll test it on Ubuntu 18.04.2 in a few days and keep you posted.

**Comment by ghost** [comment]
@Pleskan, can you try the following for me please:

1. Replace the contents of /etc/dovecot/conf.d/10-mail.conf with the following:


```mail_privileged_group = mail
mail_access_groups = mail
mail_location = maildir:%h/mail/%d/%n
pop3_uidl_format = %08Xu%08Xv

namespace Inbox {
  type = private
  separator = /
  inbox = yes
  list = yes
}
```

2. Create a new file named **15-mailboxes.conf** under **/etc/dovecot/conf.d/** with the following contents:

```# NOTE: The below assumes that the Inbox namespace has been defined in 10-mail.conf

namespace Inbox {
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }

  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }

  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }

  mailbox "Sent Messages" {
    special_use = \Sent
  }
}
```

3. Restart dovecot: **systemctl restart dovecot**

Let me know at your convenience if this has any effect on the issue.

**Comment by Pleskan** [comment]
@kristankenney, ok I've created 2 files and restart dovecot daemon but bug is still here.
By the way, I tried many fixing receipts from community, but only one (with prefix **mail/** and **list = no** written to main config file) done the job well.

P.S. Error log doesn't change 

`Mar 17 21:24:44 master: Warning: Killed with signal 15 (by pid=6582 uid=0 code=kill)
Mar 17 21:24:45 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Mar 17 21:25:43 imap-login: Info: Login: user=<tester@mautik.tk>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=6795, secured, session=</OPtPE+E2M9/AAAB>
Mar 17 21:25:43 imap(tester@mautik.tk): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Mar 17 21:25:43 imap: Error: Invalid user settings. Refer to server log for more information.`

**Comment by xXKynarethXx** [comment]
> Thanks for the information @Pleskan and sorry for the inconvenience that this is causing you, we'll take a look into this further.
> 
> Please note that we are planning to overhaul the installation and upgrade processes, hopefully for the next release if all goes well. This will eliminate much of the duplicate code that currently exists within Hestia and ensure consistency, and we are also working on the underlying mail system to make it more robust.
> 
> Again, pleae accept my apologies for the inconvenience, I'll post an update here once a fix is in place

If you need people to test this - just ask ;)

**Comment by ghost** [comment]
@xXKynarethXx, if you happen to have time and an installation of Ubuntu 16.04 to test against it would be greatly appreciated to see if the same thing presents itself. 

So far we haven't been able to reproduce this on installations of Ubuntu 16.04 and 18.04, modifying the prefix causes issues with the mailbox layout on working installations.

**Comment by xXKynarethXx** [comment]
I am setting up a server with Ubuntu 16.04 at the moment.
If you need testers for your new installer, I can help too :)

**Comment by xXKynarethXx** [comment]
> @Pleskan, can you try the following for me please:
> 
> 1. Replace the contents of /etc/dovecot/conf.d/10-mail.conf with the following:
> 
> ```
> mail_access_groups = mail
> mail_location = maildir:%h/mail/%d/%n
> pop3_uidl_format = %08Xu%08Xv
> 
> namespace Inbox {
>   type = private
>   separator = /
>   inbox = yes
>   list = yes
> }
> ```
> 1. Create a new file named **15-mailboxes.conf** under **/etc/dovecot/conf.d/** with the following contents:
> 
> ```
> 
> namespace Inbox {
>   mailbox Archive {
>     auto = subscribe
>     special_use = \Archive
>   }
> 
>   mailbox Drafts {
>     auto = subscribe
>     special_use = \Drafts
>   }
> 
>   mailbox Junk {
>     auto = subscribe
>     special_use = \Junk
>   }
> 
>   mailbox Trash {
>     auto = subscribe
>     special_use = \Trash
>   }
> 
>   mailbox Sent {
>     auto = subscribe
>     special_use = \Sent
>   }
> 
>   mailbox "Sent Messages" {
>     special_use = \Sent
>   }
> }
> ```
> 1. Restart dovecot: **systemctl restart dovecot**
> 
> Let me know at your convenience if this has any effect on the issue.

Didn't work for me as well :/
If you have another fix tell me and I'll set up a new maschine :)

**Comment by ghost** [comment]
Just an update, I've managed to reproduce this and am working on a proper fix now.

**Comment by ghost** [comment]
Can you both please remove **/etc/dovecot/conf.d/15-mailboxes.conf** and replace the contents of **/etc/dovecot/dovecot.conf** with the following, then restart the dovecot service and try logging into Roundcube? This configuration is working so far on this end.

``` 
protocols = imap pop3
listen = *, ::
base_dir = /var/run/dovecot/
login_greeting = Mail Delivery Agent
!include conf.d/*.conf

namespace {
    type = private
    separator = /
    inbox = yes
    list = yes

    mailbox Sent {
        auto = subscribe
        special_use = \Sent
    }
    mailbox Drafts {
        auto = subscribe
        special_use = \Drafts
    }
    mailbox Trash {
        auto = subscribe
        special_use = \Trash
    }
}
```

**Comment by Pleskan** [comment]
@kristankenney no effect, no luck on my side, nothing change

**Comment by Pleskan** [comment]
@kristankenney I confirm: bug doesn't affect Ubuntu 18.04.2.
I've test it just now.

**Comment by Pleskan** [comment]
@kristankenney Yep! Your latter fix works after I restored default **10-mail.conf** content from repo.

**Comment by ghost** [comment]
@Pleskan, that's great to hear! I was a bit perplexed as to why it wasn't working but forgot to mention to revert 10-mail.conf that we had changed earlier. 

@xXKynarethXx, are you able to confirm the same results? (revert 10-mail.conf, delete 15-mailboxes.conf, and update dovecot.conf to the configuration mentioned in my last post)

Thanks for the help so far everyone! :)

**Comment by xXKynarethXx** [comment]
> Can you both please remove **/etc/dovecot/conf.d/15-mailboxes.conf** and replace the contents of **/etc/dovecot/dovecot.conf** with the following, then restart the dovecot service and try logging into Roundcube? This configuration is working so far on this end.
> 
> ```
> protocols = imap pop3
> listen = *, ::
> base_dir = /var/run/dovecot/
> login_greeting = Mail Delivery Agent
> !include conf.d/*.conf
> 
> namespace {
>     type = private
>     separator = /
>     inbox = yes
>     list = yes
> 
>     mailbox Sent {
>         auto = subscribe
>         special_use = \Sent
>     }
>     mailbox Drafts {
>         auto = subscribe
>         special_use = \Drafts
>     }
>     mailbox Trash {
>         auto = subscribe
>         special_use = \Trash
>     }
> }
> ```

Tested with fresh install and your fix worked!

**Comment by Pleskan** [comment]
@kristankenney, great news! Thanks for collaboration in bugfixing process. I think you can create pull request after receiving confirmation from @xXKynarethXx 
Good luck!

**Comment by Pleskan** [comment]
@kristankenney I think it's worth to know is Debian 8, 9 affected by this bug, isn't it?

**Comment by ghost** [comment]
@Pleskan I'll check on Debian 8 and 9 to confirm, but I want to say that it is safe to assume that at least 8 would be affected given that Ubuntu 16.04 is based upon it (unless this is an Ubuntu-specific bug with Dovecot).

**Comment by xXKynarethXx** [comment]
My installation on Debian 9 worked yesterday, I am trying, too.

**Comment by Pleskan** [comment]
@kristankenney @xXKynarethXx thanks for your time and efforts making Hestia better :smile:

**Comment by xXKynarethXx** [comment]
Works on Debian 9 :)
No problem, it's nice to see such an active project!

**Comment by ghost** [comment]
This issue should now be fixed across-the-board with commit https://github.com/hestiacp/hestiacp/commit/fc37bdc44dcb319f79a72726a6223e43430de80b.

Thanks again for all of your help, it's much appreciated by myself and the rest of the team. :)
