### ISSUE TITLE
[BUG] Restored user will not Chrooted?

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#2222]
I chroot all users in other server of hestiacp.

But when I restore all this users from backupo to other hestiacp server. All of this users are not chrooted (means all user can browse root file via sftp)

Is it a bug of hestiacp?

**Comment by jaapmarcus** [comment]
If the user is set to nologin it should be Chrooted by default

**Comment by erikdemarco** [comment]
@jaapmarcus. Yeah you are right.

So to prevent other user to browse other user directory, it seems only possible with 'nologin'. But with 'nologin' user cant have access to shell.

Is there any way to allow shell but restrict access to other user's directory?

**Comment by ScIT-Raphael** [comment]
This would be possible over an jailed ssh access - but this feature hasnt currently built in. For jailed ssh there is already another feature request, so I'm going to close this issue.

**Comment by erikdemarco** [comment]
Thanks @ScIT-Raphael 
Just to make sure. Is #894 the correct issue?

**Comment by jaapmarcus** [comment]
Yes
