### ISSUE TITLE
[FEATURE] Backblaze backup versioning

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#2226]
Currently hestiacp backup file tobackblaze using unique name each upload. With this method it will bypass file versioning feature of backblaze here:

=> https://www.backblaze.com/b2/docs/file_versions.html

The correct way is to upload the file using the same name each time. for example instead of 'admin.2021-11-14_05-10-09.tar' we should upload 'admin.tar'. With this we can browse many version using the lowest storage possible because of incremental backup.

**Comment by jaapmarcus** [comment]
Feel free to submit to submit a pull request where you keep support of downloading older backups via the WebUI. 

We don't have plan to alter this function currently

**Comment by jaapmarcus** [comment]
Unless we want to rewrite how them in hestia it self it does not make sense to change it for only B2...
