### ISSUE TITLE
PHP 8.0 cli makes default domain(s) disappear [BUG]

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#2229]
**Describe the bug**
When changing the PHP CLI default from 7.x to 8.0, domain(s) with PHP backend: Default disappear from /edit/server/.

**To Reproduce**
1. Create domains with different PHP versions (e.g. eight with default, one with 5.6 and one with 8.0 like in  the screenshots below)
2. Change the CLI to another version (e.g. from 7.3 to 8.0)
3. Aaaaah! All the default domains have disappeared under Configure: Web Server (/edit/server/)
4. Change the CLI back to 7.x (e.g. from 8.0 to 7.4)
5. Whew! All the default domains have reappeared under Configure: Web Server

**Expected behavior**
The domains all showing properly under Configure: Web Server (/edit/server/)

**Screenshots**
`update-alternatives --set php /usr/bin/php7.3`
![php7 3](https://user-images.githubusercontent.com/20109369/142185935-b09253d6-eed9-45d8-9ca4-35e373a0c208.png)

`update-alternatives --set php /usr/bin/php8.0`
![php8](https://user-images.githubusercontent.com/20109369/142187710-50717936-5c67-4970-a3d3-3b5a1e669819.png)

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.4.17

**Comment by jaapmarcus** [comment]
Strange but can confirm the issue

**Comment by jaapmarcus** [comment]
```
exec('php -r "echo (float)phpversion();"')
```
return 8 instead of 8.0 due to the float
