### ISSUE TITLE
Invalid DKIM pubkey with newline chars

### ISSUE THREAD

**Issue by Pleskan** [hestiacp/hestiacp#223]
### Brief issue description:
Invalid DKIM public key because of newline ('\n') char in it

### Steps to Reproduce:
1. Install Hestia from master branch
2. Create mail domain and DKIM signature
3. Add that pubkey to DNS TXT-record

### Expected behavior:
Correct DKIM public key

### Operating system distribution and release:
Ubuntu 16.04.5, 18.04.2

### HestiaCP Version:
0.9.8-28

### What software is installed?
Nginx, PHP-FPM, Dovecot/Exim, MariaDB, Fail2ban
### Related issues or forum threads:
[Comments](https://github.com/serghey-rodin/vesta/issues/320#issuecomment-397879733) at issue[ #320](https://github.com/serghey-rodin/vesta/issues/320) at VestaCP repo
### Additional notes:
None

**Comment by ScIT-Raphael** [comment]
Do you know if this commit will solve the issue? -> https://github.com/serghey-rodin/vesta/pull/1645/commits/d24a57224b4f622d15fec72333337196a6b6d523

**Comment by Pleskan** [comment]
@ScIT-Raphael, Yes I know about it. Nevertheless, when I copy-paste domain pubkey from .pub-file  (even on local PC using Notepad++) there are "rubbish" newline chars. May be is my misunderstanding of treating DKIM-pubkey, but anyway additional testing would be useful. 
@xXKynarethXx, can you test DKIM pubkey correctness on your servers?

**Comment by xXKynarethXx** [comment]
I have the same problem  with „\n“ :/
Cloudflare isnt accepting my pubkey because of that.

**Comment by Pleskan** [comment]
@xXKynarethXx, thanks for feedback.
You copy-paste the pubkey from file **directly** or use **v-list-mail-domain-dkim-dns** script for getting the public key?
Anyway fix wanted because fixing newline by hand it is rather tiresome task.

**Comment by xXKynarethXx** [comment]
I used the Vesta/hestia script (Debian 9 & Ubuntu 16.04)

**Comment by Pleskan** [comment]
@xXKynarethXx ok, then [this](https://github.com/hestiacp/hestiacp/issues/223#issuecomment-473808890) fix may help you. Would you like to try directly copy-paste from file method? 
Have you got any problems with newlines using that method?
Thanks in advance for your assistance :smiley:

**Comment by xXKynarethXx** [comment]
@Pleskan I will try, might take some time :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ScIT-Raphael** [comment]
If you will find it out, please create a pull request to the beta branch - we will implement asap.

**Comment by Pleskan** [comment]
@ScIT-Raphael , @xXKynarethXx  fix for bash script works as expected.
Listed DKIM-pubkey is valid. I've just test it.

**Comment by ScIT-Raphael** [comment]
Thanks for your checks! It is implemented to the beta branch with the following commit: https://github.com/hestiacp/hestiacp/commit/6f8fd03dbb844294e83dbc9fdd1ba1107ba5c273

@Pleskan can you contact me at info@hestiacp.com? Thanks!

**Comment by Pleskan** [comment]
@ScIT-Raphael, ok I'll mail you in a few days
Regards!

**Comment by xXKynarethXx** [comment]
>If you will find it out, please create a pull request to the beta branch - we will implement asap.

@ScIT-Raphael @Pleskan  fix works for me as well, tested on Debian 8,9 & Ubuntu 16.04 :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Pleskan** [comment]
@xXKynarethXx I'm looking forward for your feedback about the second case of DKIM pubkey processing.
You also can mail to Twissell@fex.net (it is my e-mail for public needs, I don't afraid of spammers :smile:)

**Comment by ScIT-Raphael** [comment]
Again thanks to @Pleskan and @xXKynarethXx for your great work!

**Comment by Pleskan** [comment]
@ScIT-Raphael Not at all. I just want to use quality and lightweight OpenSource Sofware. :1st_place_medal:

**Comment by xXKynarethXx** [comment]
Fully agree to @Pleskan, I love your work and how blazing fast you resolve issues/bugs, that's why I changed from vesta. Didn't even get a response by now (issue is open since two weeks). Keep up your amazing work and if you need testers for the remastered panel/backend/installer, just text me, I can provide an email adress as well :)

**Comment by ScIT-Raphael** [comment]
@xXKynarethXx Sorry for the delay, can you send a email to info@hestiacp.com? We still search team members - would be great to have some additional testers in our team <3!
