### ISSUE TITLE
Hestia breaks when uninstalling its PHP version [BUG]

### ISSUE THREAD

**Issue by snakehill** [hestiacp/hestiacp#2231]
**Describe the bug**
When uninstalling the PHP version used by Hestia from Configure Server: Web Server, Hestia will get in a limbo state loading forever. It then needs to be restarted manually for it to work again.

**To Reproduce**
1. Go to Configure Server: Web Server;
2. Uninstall the PHP version used by Hestia;
3. Witness Hestia loading forever and not working anymore.

**Expected behavior**
Hestia should continue working. Now it's essentially self-destructing. When uninstalling the version that it's running on (or possibly just any version just to be sure), the Hestia service should restart by itself.

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.4.17

**Comment by jaapmarcus** [comment]
Do you have any logs or more information?

It is a a slow process and it takes for sure 1 / 2 min depending how many version you want to disable

**Comment by jaapmarcus** [comment]
Also it works fine here...

**Comment by snakehill** [comment]
I uninstalled PHP 7.4 for having moved all sites to 8.0, and afterwards Hestia simply wouldn't load anymore (or rather it kept on loading forever, also upon refresh). I manually restarted service hestia, which instantly made it work again.

I then repeated that on my other server running PHP 7.3, installing 7.4 and removing 7.3 afterwards (just as a test). Again up to unchecking the box it worked, but then upon pressing 'Save' the same exact thing happened with Hestia not responding anymore and requiring a reboot/restart.

All websites and the like kept on working, so I assume it was just the Control Panel not being able to reach and resolve its PHP version.

**Comment by snakehill** [comment]
I think the first time I let it load about 10 minutes. The second time 3, maybe 4. It was definitely slower than any other save ever (including installing and uninstalling any other PHP version not in use).

**Comment by jaapmarcus** [comment]
3 to 4 minutes looks like me  to be quite normal if you want to install 1 php version and remove 1. As it depends on APT what is know not fastest method. It also depends if the last apt went without any issues as if it wait on a user input it just hangs..

I don't think there is a reasonable method to solve the issue except disable the feature from WebUI....

**Comment by snakehill** [comment]
Just to be clear, it was only the removing that took so long (10 and 3 or 4 minutes respectively), not installing any at the same time. When removing any version not in use by the Control Panel, that takes 10-30 seconds for me. But I guess it's alright then. In both instances, however, restarting hestia made it work instantly with the PHP versions removed completely and everything working as should.
