### ISSUE TITLE
[FEATURE] Installation without domain

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#2232]
Currently its required to install hestiacp with domain name.

If you install it with domain name. hacker can easily find your website's ip even if you hide behind cloudflare. 

For example one of my site is using hestiacp here
pinkbatteries.com (its hiding via cloudflare)

But if you use censys search to find what ssl certificate contain the word 'pinkbatteries.com', here's the result:
https://search.censys.io/hosts/139.99.200.255

As you can see there. 139.99.200.255 is the real ip of the website. and panel.pinkbatteries.com is the url of hestiacp. After knowing this info hacker/competitor can just deploy ddos attack to real server directly.

If we can install hestia without domain, it will be more hard to find our real ip via certificate search. Because on old version of hestia domain is not required for installation. On new hestia its required as pointed by @ScIT-Raphael

**Comment by ScIT-Raphael** [comment]
Hestia needs a fqdn for setup, but you can create anyone, it doesnt need to exist. Basicly doesnt.exist.com would work - you can still change it later to a real one (v-change-sys-hostname), which you can protect with cloudflare - you even can use a custom port, 2083 or similar, which is supported by cloudflare and you can set as hestiacp's port. Mail communication itself cant be protected with cloudflare and their free plans, so there is no way to obscure your server ip if you want to use it.

So it doesnt really depend on hestia or if a hostname is used during installation, more to what you setup in your dns zone (and what you share with the internet). Probaly best way is to use a fake domain name, then protect it by cloudflare and use v-add-letsencrypt-host or a self signed one with the cloudflare ca.

**Comment by jaapmarcus** [comment]
It is an requirement for when using email and so on.. If you really care about security ip table / firewall to block access to port 8083...  If you don't care about sending email use i.dont.care as hostname or create a non existing one...  It doesn't matter 

https://github.com/hestiacp/hestiacp/blob/e143c493638c905d5f3dae6a20c553713d530913/install/hst-install-debian.sh#L174-L180

It happened to many times users where entering the ip as hostname and it is a bad idea...
