### ISSUE TITLE
[Feature] Add support for yescrypt

### ISSUE THREAD

**Issue by ww7** [hestiacp/hestiacp#2235]
Fresh installation doesn't allow login to panel. 
Unsupported hashing method for password.

> Invalid username or password.

Newest Debian 11 used `yescrypt` instead supported by HestiaCP `sha512`

Issue can be fixed with changing default hashing method in `/etc/pam.d/common-password` with replacing
`password [success=1 default=ignore] pam_unix.so obscure yescrypt`
to
`password [success=1 default=ignore] pam_unix.so obscure sha512`
and then resetting password with `v-check-user-password`

Please update HestiaCP to support `yescrypt` method.

Referral: [Bullseye release-notes: 5.1.4. Password hashing uses yescrypt by default](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information)

**Operating system:**
Debian 11

**Hestia Control Panel version:**
Version 1.4.17

**Comment by jaapmarcus** [comment]
Hestia does not support yescrypt and it is addressed in the installer 

https://github.com/hestiacp/hestiacp/blob/e2d7eb9da2af4372d8f11b07ad3a56cf3da970bb/install/hst-install-debian.sh#L1293-L1296

**Comment by jaapmarcus** [comment]
There is currently no yescrypt support in PHP....  And with https://github.com/hestiacp/hestiacp/blob/main/bin/v-generate-password-hash we generate the password hash..

**Comment by ww7** [comment]
Then installer should change default hashing function for Debian 11 to sha512 
(at `/etc/pam.d/common-password`)

**Comment by ScIT-Raphael** [comment]
Which the installer does:



> Hestia does not support yescrypt and it is addressed in the installer
> 
> https://github.com/hestiacp/hestiacp/blob/e2d7eb9da2af4372d8f11b07ad3a56cf3da970bb/install/hst-install-debian.sh#L1293-L1296

**Comment by ww7** [comment]
Oh, great, for some reason it didn't applied on a fresh installation

**Comment by jaapmarcus** [comment]
I will reopen the issue it is still required future for in the past

**Comment by jaapmarcus** [comment]
Closed by accident

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2499

**Comment by jaapmarcus** [comment]
Support has been added for next release
