### ISSUE TITLE
[BUG] Error in Debian installation script

### ISSUE THREAD

**Issue by malbrock** [hestiacp/hestiacp#2239]
**Describe the bug**
Definition of the installation directory in hst-install-debian.sh has a space at the end, which prevents the installer to work.

**Comment by malbrock** [comment]
Line 22 of the file

**Comment by ScIT-Raphael** [comment]
Confirmed, will be fixed in a few minutes: https://github.com/hestiacp/hestiacp/blob/0d715874236b3824a88398bbeee16c19301def89/install/hst-install-debian.sh#L22

**Comment by jaapmarcus** [comment]
To slow :)

Allready done in release
