### ISSUE TITLE
Your OS is currently not supported.

### ISSUE THREAD

**Issue by Amitxyz** [hestiacp/hestiacp#224]
On Kimsufi with debian 9 i cant install?

/etc/issue
 Debian GNU/Linux 9 (stretch)
 Linux myhost.domain.com 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x8$

  Server        : 279297
  IPv4          : 11111
  IPv6          : 111111
  Hostname      : servername

/etc/os-release

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by ghost** [comment]
Hi @amitx11, sorry to hear you're having troubles installing Hestia. Try using the Debian install script directly and let us know what happens please:

`wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install-debian.sh`
`bash hst-install-debian.sh`

**Comment by Amitxyz** [comment]
Thanks, it installed succesfully :)

When you push a new update for the panel,how should i update it( force update)

**Comment by ghost** [comment]
Perfect, I'm glad to hear you got things installed! I'll take a look into the stub installer to see where it's getting confused later on today and patch this for our next release. You can upgrade your Hestia installation just as easily as you would any other package by running apt update && apt upgrade. :)

**Comment by Amitxyz** [comment]
Ok :) And please make the option during installation what the user want to install like vesta cp advanced install settings.

**Comment by ghost** [comment]
Do you mean options like adding Multi PHP, or turning off mail or DNS during install for example? If so, the functionality is there and just needs to be set with the correct flags when you run the installer, e.g. hst-install.sh --multiphp yes.

**Comment by Amitxyz** [comment]
Like i dont want spamassin and clamav.

**Comment by ghost** [comment]
No problem, just specify --clamav no --spamassassin no during installation to exclude them.

We will take a look at improving the installation process as well as our documentation to make these options more discoverable overall. :)

**Comment by ghost** [comment]
@amitx11, what output do you receive when you run the following command?

`head -n1 /etc/issue | cut -f 1 -d ' '`

**Comment by ghost** [comment]
Hi @amitx11,

We've been unable to reproduce the issue in our test environments with the latest release of Debian 9.8.0. If you continue to have issues, please reach out and we can reopen this.

Thanks for your feedback and have a great day. :)
