### ISSUE TITLE
[BUG] phpmyadmin page is not found (error 404)

### ISSUE THREAD

**Issue by samodraland** [hestiacp/hestiacp#2240]
After got notification "Your server has been updated to Hestia Control Panel v1.5.0." at 02:23:40 2021-11-26, my phpmyadmin page is not found (error 404 Page Not Found). A day before upgrade I was able to open phpmyadmin page

**Comment by wojsmol** [comment]
@samodraland Please see [first point](https://github.com/hestiacp/hestiacp/blob/main/CHANGELOG.md#breaking-changes).

**Comment by samodraland** [comment]
Hi @wojsmol thank you for pointing out the documentation. How to do that while I'm not familiar with Linux environment?

**Comment by wojsmol** [comment]
Simply access  phpmyadmin by domain and not IP address - this shold work without any configuration changes.

**Comment by samodraland** [comment]
@wojsmol nice! it works. Thank you!

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/database.html
