### ISSUE TITLE
Filemanager stoped working after update

### ISSUE THREAD

**Issue by reznik1988** [hestiacp/hestiacp#2242]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

:8083/fm/?r=/getdir:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

what do you think i should do ?

**Comment by ScIT-Raphael** [comment]
First of all, do not remove the issue template and fill it please out - it isnt decoration :).

Then check your weblog to find out, what exactly throws out the 500 error.

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/nginx-error.log 

We haven't update this version the file manager also try using domain.com:8083/fm/

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2245
