### ISSUE TITLE
[BUG]Phpmyadmin error 404

### ISSUE THREAD

**Issue by k1ngozavr** [hestiacp/hestiacp#2243]
After update i cant use phpmyadmin, error 404 
Page Not Found
Oops! We couldn't find the page that you're looking for.

Please check the address and try again.

Error Code: 404

**Comment by ScIT-Raphael** [comment]
Please read the changelog...: https://github.com/hestiacp/hestiacp/blob/main/CHANGELOG.md

We do not suggest to revert it, due to security.

**Comment by akhzarjaved** [comment]
So is there any other way to access the phpmyadmin ? 
I mean like making ssh tunnel ETC ?

**Comment by jaapmarcus** [comment]
Follow the instructions here https://docs.hestiacp.com/admin_docs/database.html#how-can-i-enable-access-to-http-ip-phpmyadmin

For other options we can't provide support for

**Comment by canthis** [comment]
@jaapmarcus 
Followed documentation exactly.
Hitting `http://{myip}/phpmyadmin/` produces 403 Forbidden status code and shows Page Not Found page.

Fresh Debian 11, Hestia 1.5.1 installation with nginx, multiple php and no apache.

**EDIT**
Solved it by adding `index index.php index.html;` to the `server {}` block of `/etc/nginx/conf.d/ip.conf`

**Comment by farkhod89** [comment]
Hi.
```
https://host.domain.tld/phpmyadmin/
```
Not working, please check

**Comment by akhzarjaved** [comment]
@farkhod89 
Try the domain which is your default one given on hestiacp 
I just tried mine and its working

![image](https://user-images.githubusercontent.com/50201631/146729642-8afc8216-1952-4796-94e7-049429d42d9d.png)

![image](https://user-images.githubusercontent.com/50201631/146729828-6fffa111-0dcd-4abe-ba4c-bc6bc80f43c7.png)

**Comment by farkhod89** [comment]
@akhzarjaved 
Thank you, I initially deleted this domain. That's why it didn't work for me. Everything is working now.

**Comment by jaapmarcus** [comment]
The domain is also used for LE on the host panel

**Comment by ssheduardo** [comment]
Hi,
I have a fresh install hestiacp last version with ubuntu 20.04.
I installed apache with nginx, Follow the instructions here https://docs.hestiacp.com/admin_docs/database.html#how-can-i-enable-access-to-http-ip-phpmyadmin

```
For Apache2

nano /etc/apache2/conf.d/ip.conf

# And add the code before both </VirtualHost>
IncludeOptional /etc/apache2/conf.d/*.inc

# Restart apache2
systemctl restart apache2

# Or add in /etc/apache2.conf
IncludeOptional /etc/apache2/conf.d/*.inc
```

But when access to phpmyadmin:
(I changed the IP is not real )


![image](https://user-images.githubusercontent.com/1160138/148690396-cf401cb7-8486-4def-a8bd-5c3b96fab826.png)


Some solutions for this error?

**Comment by jaapmarcus** [comment]
Just checked my test server this should work fine


```
Listen w.x.y.z:8443
Listen w.x.y.z:8080
<VirtualHost w.x.y.z:8080>
    ServerName w.x.y.z
    DocumentRoot /var/www/html/
    Alias /error/ /var/www/document_errors/
    IncludeOptional /etc/apache2/conf.d/*.inc
</VirtualHost>

<VirtualHost w.x.y.z:8443>
    ServerName w.x.y.z
    DocumentRoot /var/www/html/
    Alias /error/ /var/www/document_errors/

    SSLEngine on
    SSLVerifyClient none
    SSLCertificateFile         /usr/local/hestia/ssl/certificate.crt
    SSLCertificateKeyFile      /usr/local/hestia/ssl/certificate.key
    IncludeOptional /etc/apache2/conf.d/*.inc
</VirtualHost>
```

**Comment by ssheduardo** [comment]
> Just checked my test server this should work fine

Yes is same, see my image

![image](https://user-images.githubusercontent.com/1160138/148696811-59aff1c1-aa26-4efe-af3e-c918a438b6b9.png)


After restart service apache, but result is same:
```
Access Denied
You do not have permission to view this page.

Please check your credentials and try again.

Error Code: 403
```

Why don't I have permissions?

**Comment by jaapmarcus** [comment]
Does the phpmyadmin.inc exists on your server?

**Comment by ssheduardo** [comment]
> Does the phpmyadmin.inc exists on your server?

Yes,
![image](https://user-images.githubusercontent.com/1160138/148698238-7a1481fd-b122-4d0b-925d-b26713f71baf.png)

**Comment by jaapmarcus** [comment]
I don't know but If I remove the IncludeOptional /etc/apache2/conf.d/*.inc I get an 404

What happens when you visits http://ip/

**Comment by ssheduardo** [comment]
> I don't know but If I remove the IncludeOptional /etc/apache2/conf.d/*.inc I get an 404
> 
> What happens when you visits http://ip/

Yes, if remove the includeOptional I get an 404.
When visits http://ip/ return

![image](https://user-images.githubusercontent.com/1160138/148704563-c0c66966-5a1b-4d24-8489-a8bb3fac2fad.png)

**Comment by ScIT-Raphael** [comment]
@ssheduardo you need to use a web domain which is added to hestia, not only point to the server!

Edit: After reviewing it I'm wrong on that one :). I still strongly suggest to use a valid domain and access it over a hostname with ssl certificate - this can't be added for an ip address itself.

**Comment by jaapmarcus** [comment]
> > I don't know but If I remove the IncludeOptional /etc/apache2/conf.d/*.inc I get an 404
> > What happens when you visits http://ip/
> 
> Yes, if remove the includeOptional I get an 404. When visits http://ip/ return
> 
> ![image](https://user-images.githubusercontent.com/1160138/148704563-c0c66966-5a1b-4d24-8489-a8bb3fac2fad.png)

According Apache2 documentation it should work

https://httpd.apache.org/docs/2.4/mod/core.html#includeoptional

**Comment by ssheduardo** [comment]
> > > I don't know but If I remove the IncludeOptional /etc/apache2/conf.d/*.inc I get an 404
> > > What happens when you visits http://ip/
> > 
> > 
> > Yes, if remove the includeOptional I get an 404. When visits http://ip/ return
> > ![image](https://user-images.githubusercontent.com/1160138/148704563-c0c66966-5a1b-4d24-8489-a8bb3fac2fad.png)
> 
> According Apache2 documentation it should work
> 
> https://httpd.apache.org/docs/2.4/mod/core.html#includeoptional

The truth is that this permissions error is very strange, I have followed all the steps and it still doesn't work.

**Comment by jaapmarcus** [comment]
Use https://domain.com/phpmyadmin/ and it should work

**Comment by ssheduardo** [comment]
> @ssheduardo you need to use a web domain which is added to hestia, not only point to the server!
> 
> Edit: After reviewing it I'm wrong on that one :). I still strongly suggest to use a valid domain and access it over a hostname with ssl certificate - this can't be added for an ip address itself.

Hi, I just point the domain to the server (I use cloudflare dns) and I try to open phpmyadmin with the domain with SSL and I still get the 403 error, I don't understand.

![image](https://user-images.githubusercontent.com/1160138/149039105-e00da87d-2ccc-49bc-a75c-1ed5f6d1d97c.png)

![image](https://user-images.githubusercontent.com/1160138/149039532-2762b1e7-560c-4ace-85c8-4f4e489e19ee.png)

In hestiaCP
![image](https://user-images.githubusercontent.com/1160138/149042471-afa38c95-9e8d-4cf0-9449-419018eebe2e.png)

![image](https://user-images.githubusercontent.com/1160138/149042842-e25bd469-dde8-4e68-9f46-499c89e5a243.png)


![image](https://user-images.githubusercontent.com/1160138/149042535-89acf71b-5a63-43af-b555-4316ea57dd55.png)

**Comment by jaapmarcus** [comment]
Check the logs off Apache2. (/var/log/apache2/domains/domain.com.error.log)

**Comment by ssheduardo** [comment]
> Check the logs off Apache2. (/var/log/apache2/domains/domain.com.error.log)

I'm not understand, today is working.


![image](https://user-images.githubusercontent.com/1160138/149093085-8b16038c-0fd7-455a-abb9-8a7a9e2e9f8d.png)

Thanks.

**Comment by darkworks** [comment]
> Use https://domain.com/phpmyadmin/ and it should work

mine not working maybe because my url redirect to : https://www.domain.com/phpmyadmin/

**Comment by darkworks** [comment]
> > Use https://domain.com/phpmyadmin/ and it should work
> 
> mine not working maybe because my url redirect to : https://www.domain.com/phpmyadmin/
also i not understand why you guys have disable ip/phpmyadmin ?? how it was security issue.  if by default you guys would have just change alias from phpmyadmin to something else like http://ip/gdfgdfgdfg/  
then it would be safe .

**Comment by ScIT-Raphael** [comment]
> mine not working maybe because my url redirect to : https://www.domain.com/phpmyadmin/
> also i not understand why you guys have disable ip/phpmyadmin ?? how it was security issue.  if by default you guys would have just change alias from phpmyadmin to something else like http://ip/gdfgdfgdfg/
> then it would be safe .

A redirect should not make an issue, pma should also be available on https://www.domain.com/phpmyadmin/ - it's added by  /etc/nginx/conf.d/phpmyadmin.inc respectively /etc/apache2/conf.d/phpmyadmin.inc as alias.

Security is easy answered: You can't add a valid ssl certificate to a ip address, if you want to have it back on ip, just have a look at the docs, we've stated it there how to do so.

(PS: No need to write under multiple issues ;))

**Comment by darkworks** [comment]
ok guys its fixed , make sure you manually download phpmyadmin from : https://www.phpmyadmin.net/downloads/ and place under your  http://domain.com/secreturl_phpadmin/ in public_html/secreturl_phpadmin

then you can visit and connect via : http://domain.com/secreturl_phpadmin/

**Comment by ScIT-Raphael** [comment]
Should not be a need to do so, also you could use the pma alias field to change it to whatever you like:

![image](https://user-images.githubusercontent.com/13765400/203250624-d2c06be2-8242-4cb6-90f3-3c0d5e720a52.png)

But glad it worked for you that way.
