### ISSUE TITLE
[Bug] log isn't being downloaded 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2248]
### Describe the bug

![image](https://user-images.githubusercontent.com/39749258/143679242-763bbc21-a55e-4b71-8d18-467ee87ebacb.png)

can't download the log

### Tell us how to replicate the bug

Select the domain and try to download the log
![image](https://user-images.githubusercontent.com/39749258/143679248-a4ffdac9-0c87-45b1-bff2-f063f733cc90.png)

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.0

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2256
