### ISSUE TITLE
User cannot edit css/ js/ webfonts folders in public_(s)html

### ISSUE THREAD

**Issue by killer30001000** [hestiacp/hestiacp#225]
### Brief issue description:
A user cannot open/ edit it's css/ js/ webfonts folders in public_(s)html
If you change the permissions from 644 to 751 in this file (or delete this line) it works.
[https://github.com/hestiacp/hestiacp/blob/b7982ea43d1b43e53f69a270635b7506b4b6722d/bin/v-add-web-domain#L94](url)

### Steps to Reproduce:
1. Create new user
2. Add domain to user
3. Connect via ftp
4. Try to open/ edit these folders in public_(s)html

### Expected behavior:
Can open/ edit folders

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
newest

**Comment by ScIT-Raphael** [comment]
Thanks for your issue report, this has been already fixed on beta branch with the following commit: https://github.com/hestiacp/hestiacp/commit/652720f3306ceddd347e644e211a24328200c3bc
