### ISSUE TITLE
[Feature] PMA: Auto Login - open PMA in new tab 

### ISSUE THREAD

**Issue by Heart1010** [hestiacp/hestiacp#2250]
### Describe the feature or change in detail

Enabled preview features + API access (with allowed IP from the server) plus the new PMA auto login feature - it's working perfect 👍 

PMA (auto login) is opened with a click on 'edit database' icon but now PMA opens directly in the current tab/window (where hestia is used) - it would be better to open PMA as new tab I think.

![image](https://user-images.githubusercontent.com/1481680/143687653-f9ac1adf-32a3-4e9b-bbf8-71c54856b0e1.png)

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
Done: https://github.com/hestiacp/hestiacp/pull/2252
