### ISSUE TITLE
Filemananger dont work after update [Bug] 

### ISSUE THREAD

**Issue by funsurfer2008** [hestiacp/hestiacp#2255]
### Describe the bug

Filemanager shows Unknown error for all users.
in Browser Debug i get:
POST https://web01.a-square.at:8083/fm/?r=/getdir 500 (Internal Server Error) xhr.js:177 

Also the hints in the forum dont work:
I deleted the keyfiles -> dont work.
I rebooted the server -> downt work.
I updated my server -> dont work.

### Tell us how to replicate the bug

1. log into webpanel
2. click on Files

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.0

### Operating system

Debian 10.5

**Comment by ScIT-Raphael** [comment]
Please have a look at https://forum.hestiacp.com/t/1-5-0-update-filemanager-unknown-error/5009

Should already been fixed and will follow in a new release, probaly next week.
