### ISSUE TITLE
[Bug]  php8.1-fpm edit page not found

### ISSUE THREAD

**Issue by fawwazid** [hestiacp/hestiacp#2261]
### Describe the bug

When click edit php8.1-fpm, page not found.

https://user-images.githubusercontent.com/38886966/144119920-719e8f26-ce9b-478f-b4a9-da60c0f0008d.mp4

### Tell us how to replicate the bug

1. Click server setting
2. Enable  php8.1-fpm
3. Click  php8.1-fpm edit

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

v1.5.0

### Operating system

Debian 11.1 (x86_64)

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/3bcbc4cd8c031228c2940c30d7cbb89e952260a8/web/templates/pages/list_services.html#L122-L125

Some hardcode php version where found in the template 

Changed that...

**Comment by fawwazid** [comment]
Thank you, it's work with #2262.
