### ISSUE TITLE
[Feature] 7G nginx firewall support

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2263]
### Describe the feature or change in detail

7G Nginx firewall will enhance the server security and decrease the cpu time spent handling malicious requests and bad bots.

It can be installed in four steps described here: https://forum.hestiacp.com/t/7g-firewall-for-nginx/4190/12?u=jlguerrero

I have successfully installed it in my servers very easily.

I would love to have a toggle button to switch the firewall on and off although I can also comment and uncomment the line in nginx.conf.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
As already written in https://github.com/hestiacp/hestiacp/issues/1644#issuecomment-787449482, we still tend to not integrate this feature. As you already noticed, its easy to integrate with a few lines to run. If you like, you can expand our docs to include the steps "how to add 7g firewall": https://github.com/hestiacp/hestiacp-docs

**Comment by jlguerrerosanz** [comment]
Thank you for your comment.

I thought that since now **_the ruleset is for NGINX and not for Apache_** you might reconsider it since the other thread was before 7G firewall was ported to NGINX

Thank you again for your work and excuse me for having wasted your time.
