### ISSUE TITLE
[Bug] .user.ini file is not loading/working

### ISSUE THREAD

**Issue by zedpr0** [hestiacp/hestiacp#2267]
### Describe the bug

.user.ini file is not loading/working when place in /var/lib/roundcube or /var/lib/rainloop and php values are not reflected locally.

.user.ini file does work flawlessly when places in /home/user/web/domain/public_html and any php values are reflected locally.

This behaviour is strange, php values can be changed and reflected when php.ini is changed in /etc/php/7.4/fpm/php.ini

I have tried using different user and group ownerships and giving it full permissions but it doesn't seem to affect anything.

Please advise. Thanks in advance.

### Tell us how to replicate the bug

1. SSH into server.
2. cd /var/lib/roundcube or /var/lib/rainloop
3. sudo nano .user.ini
4. add php directive upload_max_filesize = 50M
5. save file
6. restart php and Nginx server
7. check php values using phpinfo()

### Which components are affected by this bug?

Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.5.1

### Operating system

Ubuntu 20.04

**Comment by fra81** [comment]
Did you try to restart phpfpm?

**Comment by jaapmarcus** [comment]
I assume you are https://forum.hestiacp.com/t/increase-roundcube-upload-size/5004 ?

**Comment by zedpr0** [comment]
yes that's me.

**Comment by jaapmarcus** [comment]
I haven't tested on Nginx + PHP-FPM but on Nginx + Apache2 + PHP-FPM this works fine:

```
root@dev:/var/lib/roundcube# ls -lah 
total 612K
drwxr-xr-x 11 root www-data 4.0K Dec  1 19:59 .
drwxr-xr-x 38 root root     4.0K Nov 25 11:24 ..
drwxr-xr-x  2 root www-data 4.0K Nov 29 14:15 bin
-rw-r--r--  1 root www-data 183K Sep  3 09:25 CHANGELOG
-rw-r--r--  1 root www-data 194K Nov 22 22:12 CHANGELOG.md
-rw-r--r--  1 root www-data  989 Nov 30 07:37 composer.json
-rw-r--r--  1 root www-data 1003 Nov 22 22:12 composer.json-dist
-rw-r--r--  1 root www-data  87K Sep  3 09:25 composer.lock
lrwxrwxrwx  1 root www-data   15 Sep  3 09:25 config -> /etc/roundcube/
-rw-r--r--  1 root www-data 2.6K Sep  3 09:25 .htaccess
-rw-r--r--  1 root www-data 2.5K Nov 29 14:15 .htaccess.new
-rw-r--r--  1 root www-data  12K Nov 22 22:12 index.php
-rw-r--r--  1 root www-data  13K Nov 22 22:12 INSTALL
-rw-r--r--  1 root www-data  35K Nov 22 22:12 LICENSE
drwxr-xr-x  2 root www-data 4.0K Sep  3 09:25 logs
drwxr-xr-x 36 root www-data 4.0K Nov 29 14:15 plugins
drwxr-xr-x  8 root www-data 4.0K Nov 29 14:15 program
drwxr-xr-x  3 root www-data 4.0K Sep  3 09:25 public_html
-rw-r--r--  1 root www-data 3.8K Nov 22 22:12 README.md
-rw-r--r--  1 root www-data   26 Sep  3 09:25 robots.txt
drwxr-xr-x  5 root www-data 4.0K Nov 29 14:15 skins
drwxr-xr-x  7 root www-data 4.0K Nov 22 22:12 SQL
drwxr-xr-x  2 root www-data 4.0K Sep  3 09:25 temp
-rw-r--r--  1 root www-data 4.6K Nov 22 22:12 UPGRADING
-rw-r--r--  1 root root       48 Dec  1 19:59 .user.ini
drwxr-xr-x  9 root www-data 4.0K Sep  3 09:25 vendor
```

For .user.ini

```
root@dev:/var/lib/roundcube# cat .user.ini 
upload_max_filesize = 100M
post_max_size = 100M
```

**Comment by jaapmarcus** [comment]
<img width="225" alt="Screenshot 2021-12-01 at 20 07 49" src="https://user-images.githubusercontent.com/9754650/144297868-f71365f1-86cd-4cb2-9f5c-6e407ec2052a.png">

**Comment by zedpr0** [comment]
thank you for the update. do you have any idea why it may not be working for my Nginx + PHP-FPM server but it works for Nginx + Apache2 + PHP-FPM  server on your system?

**Comment by jaapmarcus** [comment]
No I have no idea will have to start up a test server ...

**Comment by zedpr0** [comment]
Thank you for your help. So I spun up a new vm and installed a fresh instance of HestiaCP Nginx + PHP-FPM and I can confirm that the problem can be replicated.

<img width="529" alt="Screenshot 2021-12-02 at 3 31 18 PM" src="https://user-images.githubusercontent.com/44780859/144377482-a8a84b63-61af-494d-9f49-a7e7865027f2.png">

<img width="1915" alt="Screenshot 2021-12-02 at 3 31 13 PM" src="https://user-images.githubusercontent.com/44780859/144377495-188297a7-47c9-4aef-b298-d5514efc2887.png">

**Comment by jaapmarcus** [comment]
For you test server please run 

`v-update-sys-hestia-git jaapmarcus fix/2267-fix-webmail-templates-nginx `

And verify it is working as it should be.

After that you can decide if you if want to do the same for your production server or patch the files manualy in /usr/local/hestia/data/templates/mail/nginx/

After that make sure you rebuild the mail domains

**Comment by zedpr0** [comment]
I have manually patched the files and it works great. Thank you so much, have a great day @jaapmarcus.
