### ISSUE TITLE
Missing GPG public key when --multiphp yes

### ISSUE THREAD

**Issue by ifaist0s** [hestiacp/hestiacp#227]
Thank you all for this fork. I think a faster moving alternative CP compatible with VESTA was needed 🥇 So, here goes my first contribution...

### Brief issue description:
Installation can not be completed when using `--multiphp yes` Kindly check the notes below for the exact error message.

### Steps to Reproduce:
Try to install on a clean Ubuntu 16.04 system using the command line switch `--multiphp yes`

### Expected behavior:
HESTIA installer should be able to complete the installation.

### Operating system distribution and release:
Ubuntu 16.04 LTS

### HestiaCP Version:
0.9.8-28. Installer commit [27ad300](https://github.com/hestiacp/hestiacp/commit/27ad300c33a80db7ec0394cc34a7129c90b3aaa5)

### What software is installed?
None yet. The OpenVZ VPS I tried to install HESTIA on, had just been re-imaged.

### Related issues or forum threads:
I didn't find any

### Additional notes:
The installer is throwing the following error:
`GPG error: http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease: The following signatures couldnt be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C`

The full command used to perform the installation was:
`bash hst-install-ubuntu.sh --nginx yes --apache yes --phpfpm no --multiphp yes --named yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav no --mysql yes --postgresql no --interactive yes --hostname HOSTNAME --email EMAIL --password PASSWORD --port 18083 --api yes`

### Possible Resolution
I overcame the problem by issuing the following command **before** running HESTIA installer
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C`

**Comment by ScIT-Raphael** [comment]
Well that's weird - the sury repository will be added using add-apt-repository, so basicly it should install the needed key automatically. I will check it on our test systems.

Can you maybe check the installation process on a Ubuntu 18.04? Also what happens if you add the repository manual using add-apt-repository?https://github.com/hestiacp/hestiacp/blob/b7982ea43d1b43e53f69a270635b7506b4b6722d/install/hst-install-ubuntu.sh#L542

**Comment by ifaist0s** [comment]
This is an old OpenVZ VPS, which unfortunately does not support Ubuntu 18.04 :( So, at this time, I can only debug/test on Ubuntu 16.04 LTS.

I just reimaged the VPS and before starting the installer of Hestia, i run:
`add-apt-repository -y ppa:ondrej/php`
 and here is the result:
`-bash: add-apt-repository: command not found`

### Possible solution
`apt-get install software-properties-common`

After installing the above, here is the new output of: `add-apt-repository -y ppa:ondrej/php`

`gpg: keyring '/tmp/tmpar88lms5/secring.gpg' created
gpg: keyring '/tmp/tmpar88lms5/pubring.gpg' created
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpar88lms5/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur▒" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)
`

**Comment by ScIT-Raphael** [comment]
software-properties-common will be installed from script if not exist. Can you run the following command: `LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php`

**Comment by ifaist0s** [comment]
Here is the output (not including the intro text)

`# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php`
`More info: https://launchpad.net/~ondrej/+archive/ubuntu/php`
`Press [ENTER] to continue or ctrl-c to cancel adding it`
`gpg: keyring '/tmp/tmp4on8d430/secring.gpg' created`
`gpg: keyring '/tmp/tmp4on8d430/pubring.gpg' created`
`gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com`
`gpg: /tmp/tmp4on8d430/trustdb.gpg: trustdb created`
`gpg: key E5267A6C: public key "Launchpad PPA for Ondřej Surý" imported`
`gpg: Total number processed: 1`
`gpg:               imported: 1  (RSA: 1)`
`OK`

Could it be a locale issue? Before starting the installer I did:
`sed -i 's/# el_GR.UTF-8 UTF-8/el_GR.UTF-8 UTF-8/g' /etc/locale.gen`
`sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen`
`locale-gen`
`update-locale`
`echo 'export LC_CTYPE="el_GR.UTF-8"' >> ~/.bash_profile`
to get the locales I wanted.

**Comment by ScIT-Raphael** [comment]
this is a known issue in the sury repository. I've implemented it i the following commit: https://github.com/hestiacp/hestiacp/commit/132540e4301391e58bf9e7ed8d018beaf1369145

So we should be save for future installations :). I will close this issue, please feel free to reopen it or post a new one.
