### ISSUE TITLE
[Feature] Listing Domain Alias' in Web Tab

### ISSUE THREAD

**Issue by LandyLane** [hestiacp/hestiacp#2278]
### Describe the feature or change in detail

Currently, the web tab just shows the main domain listed. It would be very helpful to have alias' listed as well on the page to make finding where it is located. I know there isn't much room, but perhaps having it listed in a smaller font below the listed domain would work?

Thanks for the great panel!

### Would you like to sponsor this feature to have it implemented?

Yes - I can pay with crypto!

**Comment by jlguerrerosanz** [comment]
You mean that when you are looking for a domain and you don't know that it is an alias you won't find it unless you go through all the domains one by one looking into the aliases.

Does the search function find aliases?

**Comment by LandyLane** [comment]
> 

It does work but it would be nice to have them listed regardless.

**Comment by jaapmarcus** [comment]
I know it has been requested many times...

**Comment by jaapmarcus** [comment]
<img width="1085" alt="Screenshot 2021-12-13 at 14 27 33" src="https://user-images.githubusercontent.com/9754650/145822951-6f8248c0-3cfc-492f-b6a5-71cd90813d84.png">
<img width="1072" alt="Screenshot 2021-12-13 at 12 44 00" src="https://user-images.githubusercontent.com/9754650/145822954-e02a6308-ff01-4614-bd73-91ee1d429fd6.png">


What about this?

**Comment by jlguerrerosanz** [comment]
That should do the trick. I would add a br at the end of the line so that we can see all aliases and I would also remove the www domains since they will most likely not add any important information.

**Comment by jaapmarcus** [comment]
Have removed the www alias. 

I am not a a fan of adding a br to show the full line it is almost impossible to estimate how long the line will be and so on ... 

@LandyLane  See readme.md for one of the supported crypto currencies

**Comment by jlguerrerosanz** [comment]
Thank you eris

**Comment by LandyLane** [comment]
Sent some btc! Thanks!
