### ISSUE TITLE
Installation fails because fail2ban can't start - Ubuntu 16.04

### ISSUE THREAD

**Issue by ifaist0s** [hestiacp/hestiacp#228]
### Brief issue description:
Installation can not be completed because of an error with fail2ban. Kindly check the notes below for the exact error message.

### Steps to Reproduce:
Try to install on a clean Ubuntu 16.04 system

### Expected behavior:
HESTIA installer should be able to complete the installation.

### Operating system distribution and release:
Ubuntu 16.04 LTS

### HestiaCP Version:
0.9.8-28

### What software is installed?
None yet. The OpenVZ VPS I tried to install HESTIA on, had just been re-imaged.

### Related issues or forum threads:
I didn't find any

### Additional notes:
Here is the output from `journalctl -xe` :
`fail2ban-client[17889]: ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.`

If I run `mkdir /var/run/fail2ban` **before** starting Hestia installation, then the installer is able to complete the installation.

Below you can see exactly where the installer quits:
`Updating currently installed packages, please wait...-`
`Installing required repository keys...`
`(*) NGINX`
`(*) PHP`
`(*) MariaDB`
`(*) Hestia Control Panel`
`Installing Hestia Control Panel and required dependencies...`
`NOTE: This process may take 10 to 15 minutes to complete, please wait...|`
`Upgrade phpMyAdmin to v4.8.5...`
`Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.`
`Error: fail2ban start failed`

### Exact installer command
`bash hst-install-ubuntu.sh --nginx yes --apache yes --phpfpm no --multiphp yes --named yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin yes --clamav no --mysql yes --postgresql no --interactive yes --hostname HOSTNAME --email EMAIL --password PASSWORD --port 18083 --api yes`

**Comment by ScIT-Raphael** [comment]
As already written in your log, please check the output of:
`Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.`

And post it also here, so we can have a closer lock into the issue. Just finished the test installation in ubuntu 16.04 without any issue (expect the already known language bug from last issue):
`Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial`

**Comment by ifaist0s** [comment]
I'm sorry for the delay...

OK, I started fresh again, and did a reinstall of Hestia. Same installation command as before.

### Installer output
````
Updating currently installed packages, please wait...\
Installing required repository keys...
(*) NGINX
(*) PHP
(*) MariaDB
(*) Hestia Control Panel
Installing Hestia Control Panel and required dependencies...
NOTE: This process may take 10 to 15 minutes to complete, please wait.../
Upgrade phpMyAdmin to v4.8.5...
Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.
Error: fail2ban start failed
````
### journalctl -xe output
````
--
-- Unit fail2ban.service has begun starting up.
Mar 22 17:30:01 calchas fail2ban-client[17857]: ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Mar 22 17:30:01 calchas systemd[1]: Failed to start Fail2Ban Service.
-- Subject: Unit fail2ban.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has failed.
--
-- The result is failed.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Unit entered failed state.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Mar 22 17:30:01 calchas systemd[1]: Stopped Fail2Ban Service.
-- Subject: Unit fail2ban.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has finished shutting down.
Mar 22 17:30:01 calchas systemd[1]: Starting Fail2Ban Service...
-- Subject: Unit fail2ban.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has begun starting up.
Mar 22 17:30:01 calchas fail2ban-client[17859]: ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Mar 22 17:30:01 calchas systemd[1]: Failed to start Fail2Ban Service.
-- Subject: Unit fail2ban.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has failed.
--
-- The result is failed.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Unit entered failed state.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Mar 22 17:30:01 calchas systemd[1]: Stopped Fail2Ban Service.
-- Subject: Unit fail2ban.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has finished shutting down.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Start request repeated too quickly.
Mar 22 17:30:01 calchas systemd[1]: Failed to start Fail2Ban Service.
-- Subject: Unit fail2ban.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has failed.
--
-- The result is failed.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Unit entered failed state.
Mar 22 17:30:01 calchas systemd[1]: fail2ban.service: Failed with result 'start-limit-hit'.
Mar 22 17:30:44 calchas sshd[17860]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=58.242.83.39  user=root
````

In the installer file, instead of redirecting to `> /dev/null 2>&1` I could search and replace that, to redirect to a file. Do you think that would help in the debugging process?

**Comment by ScIT-Raphael** [comment]
Can you check the fail2ban log?
`cat /var/log/fail2ban.log`

Just checked again, the installation routine works on our test systems (hetzner vps and proxmox lxc).

**Comment by ScIT-Raphael** [comment]
Closed due to inactivity.
