### ISSUE TITLE
[Bug] hetzner vswitch + pfsense + hestiacp showing wrong IP

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2281]
### Describe the bug

We have a proxmox cluster and a pfsense that control the output of the servers. The input come from hetzner vswitch IP that I will call x.y.z.w. The IP that goes through pfsense I will call a.b.c.d.

I put hetzner vswitch as an example, but it will happen in any other situation with same environment specs.

Well, when we install hestiacp in a VM, hestiacp reconize a.b.c.d as a IP and make it available to the user use. However inside of config files it uses the NAT IP (192.168.*.*). All works good, by the way. However it seems to me that the IP that needs to be showed (in the web gui) is the NAT IP. The external IP does not matter. it can change and actually will never be used by who access my server (in this case). That IP is just used to connections made by the server to the internet (when the connection start from the server).

So besides everything works good (conf files are listening the LAN), the IP in the web gui does not make sense.

### Tell us how to replicate the bug

1. Install a server/vm that incoming connections come thorugh LAN (not valid ip) and the output connections, started from the server, use another ipv4 valid IP.
2. Install hestiacp.
3. The IP that will be showed is the ipv4 valid IP used to connections that started from the server/vm.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.1

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
We do a look up of the external ip in:
https://github.com/hestiacp/hestiacp/blob/7e2159883b612063cf2c3555e25022e199364dec/install/hst-install-debian.sh#L1892-L1898

This is currently mainly used for DNS and mail (Sending)

You can disable this behaviour by editing /usr/local/hestia/data/ips/192.168.x.x

And replace NAT='a.b.c.d' with NAT='' and rebuild al templates.

It will then always show the internal ips for it users. 

If you use DNS from Hestia make to validate them and probally you need to adjust them...

**Comment by franciscopaniskaseker** [comment]
thank you.

i thought it was that. thank you to show the details about how to fix. is not important in our case.

**Comment by jaapmarcus** [comment]
As it fixes other issues where the nat behaviours is wanted it will almost be possible to fix in this use case...
