### ISSUE TITLE
[Bug] Delete button is not working from Edit User section

### ISSUE THREAD

**Issue by hahagu** [hestiacp/hestiacp#2282]
### Describe the bug

![image](https://user-images.githubusercontent.com/3746349/145099727-cafe8f94-c58d-4048-ab5e-772123c7c1c9.png)

Expected behavior:
```
When I click on [Delete] button from the 'Edit User' section, the user is deleted.
```

Actual behavior:
```
The user is not deleted, and no error dialogs or error console messages are logged.
```

### Tell us how to replicate the bug

1. Click on the User tab
2. Click the pencil icon (edit button) next to a user
3. Attempt to delete the user
4. Deletion does not work

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.1

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
JS event doesn't fire properly

**Comment by jaapmarcus** [comment]
Thanks for reporting
