### ISSUE TITLE
[Bug] v-backup-user: invalid parameters for check_result

### ISSUE THREAD

**Issue by magicua** [hestiacp/hestiacp#2283]
### Describe the bug

when there is not enough disk space for backup, I receive a letter about it, but the panel's logs write an error: 
/usr/local/hestia/func/main.sh: line 140: [: too many arguments
-- SYSTEM --

### Tell us how to replicate the bug

1. make a small partition for backup
2. run backup 

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.5.1

### Operating system

Ubuntu 20.04

### Log capture

```shell
/usr/local/hestia/func/main.sh: line 140: [: too many arguments
-- SYSTEM --
```

**Comment by magicua** [comment]
--- v-backup-user.orig  2021-12-09 11:10:05.568227392 +0200
+++ v-backup-user       2021-12-09 11:14:14.166547500 +0200
@@ -183,7 +183,7 @@
 if [ "$u_disk" -gt "$v_disk" ]; then
     # Always notify on failure
     echo "not enough diskspace available to perform the backup." | $SENDMAIL -s "$subj" "$email" "yes"
-    check_result "$E_LIMIT ""not enough diskspace available to perform the backup."
+    check_result "$E_LIMIT" "not enough diskspace available to perform the backup."
 fi

 if [ -z "$BACKUP_TEMP" ]; then

**Comment by magicua** [comment]
`--- v-backup-user.orig  2021-12-09 11:10:05.568227392 +0200
+++ v-backup-user       2021-12-09 11:14:14.166547500 +0200
@@ -183,7 +183,7 @@
 if [ "$u_disk" -gt "$v_disk" ]; then
     # Always notify on failure
     echo "not enough diskspace available to perform the backup." | $SENDMAIL -s "$subj" "$email" "yes"
-    check_result "$E_LIMIT ""not enough diskspace available to perform the backup."
+    check_result "$E_LIMIT" "not enough diskspace available to perform the backup."
 fi

 if [ -z "$BACKUP_TEMP" ]; then`

**Comment by magicua** [comment]
```bash
--- v-backup-user.orig  2021-12-09 11:10:05.568227392 +0200
+++ v-backup-user       2021-12-09 11:14:14.166547500 +0200
@@ -183,7 +183,7 @@
 if [ "$u_disk" -gt "$v_disk" ]; then
     # Always notify on failure
     echo "not enough diskspace available to perform the backup." | $SENDMAIL -s "$subj" "$email" "yes"
-    check_result "$E_LIMIT ""not enough diskspace available to perform the backup."
+    check_result "$E_LIMIT" "not enough diskspace available to perform the backup."
 fi

 if [ -z "$BACKUP_TEMP" ]; then
```

**Comment by jaapmarcus** [comment]
Please submit a pull request the fix is correct...

**Comment by ScIT-Raphael** [comment]
Fixed with https://github.com/hestiacp/hestiacp/pull/2284
