### ISSUE TITLE
[Bug] Can't login to suspended users

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2286]
### Describe the bug

when you suspended the user and try to autologin via Panel it logout the user.

### Tell us how to replicate the bug

Suspend the user via Panel
![image](https://user-images.githubusercontent.com/39749258/145711595-ca7dbf3a-f6d4-4f6c-b184-6cc69ffc7339.png)

then try to autologin login

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.1

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Can confirm the bug

**Comment by jaapmarcus** [comment]
Issue has been fixed in main branch
