### ISSUE TITLE
Add Default website option 

### ISSUE THREAD

**Issue by viratsoft** [hestiacp/hestiacp#2287]
### Describe the feature or change in detail

hi,
  please add option for set as default domain for website. so, access website with server ip address like http://xx.xx.xx.xx for testing purpose. and after test complete one click to switch back to default index "Success! Your new web server is ready to use." for ip.

thank you,

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
What are the advantages via direct ip access above pointing an sub domain:

1. SSL is still able to work 
2.  Multiple test sites can be active..

Don't see any reason why we need to implement such feature ....

**Comment by viratsoft** [comment]
i want to access added domain using ip address before change dns, so i can check site work without error or not.

**Comment by ScIT-Raphael** [comment]
Use a hosts entry to verify the functionality, common way to do it.

**Comment by jaapmarcus** [comment]
@ScIT-Raphael  is right it the preferred method to use...
