### ISSUE TITLE
[Bug]  phpmyadmin sso doesn't work

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2288]
### Describe the bug

phpmyadmin sso doesn't work on fresh install 

### Tell us how to replicate the bug

Install a fresh nginx+multi-phpfpm 

run v-add-sys-pma-sso
then go to panel and db tab
![image](https://user-images.githubusercontent.com/39749258/145907197-6fb9da1a-58bb-48de-bf62-c10e7676dc38.png)

doesn't login 

![image](https://user-images.githubusercontent.com/39749258/145907216-05e17c4a-81f8-4443-b06e-5b0d9eccf39e.png)it 

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Web Interface

### Hestia Control Panel Version

1.5.1

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
Make sure that the api is enabled and the ip of the server has been added to the allowed list. SSO has been tested a few days/weeks ago and is working as expected. Please have a search in the forum for related threads: https://forum.hestiacp.com/t/pma-sso-user-mistake-or-bug/3782

**Comment by alber-khan** [comment]
i already tried that. i've also enabled api and "allow-all" in allow IP

![image](https://user-images.githubusercontent.com/39749258/145960764-14efba0c-60a3-41f6-95b1-2433da3bd724.png)

**Comment by jaapmarcus** [comment]
Check /var/log/nginx/domain/hostname.com.error.log

**Comment by alber-khan** [comment]
2021/12/14 14:02:41 [error] 42909#42909: *12013 FastCGI sent in stderr: "PHP message: PHP Warning:  Unable to connect over API please check api connection in /usr/share/phpmyadmin/hestia-sso.php on line 55" while reading response header from upstream, client: 110.235.228.173, server: s1.something.com, request: "GET /phpmyadmin//hestia-sso.php?database=something_wp&user=something&exp=1639470757&hestia_token=$2y$10$yjLAI9KYGUVFELURaPpjiu6.t7/3Ol607hnW4w35irUmZU67R1hn6 HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "s1.something.com", referrer: "https://s1.something.com:8083/"

**Comment by jaapmarcus** [comment]
```
Unable to connect over API please check api connection in /usr/share/phpmyadmin/hestia-sso.php on line 55"
```

Check why the api is not working

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/145962994-5b3a7464-905c-4fc4-9886-02bc1b6aa5e1.png)

looks like this function isn't working

**Comment by alber-khan** [comment]
i can confirm that it's working as I can create a new User, DNS, and Mail via API.

**Comment by ScIT-Raphael** [comment]
Run the command manualy with the arguments and check the output

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/145965735-b60d7b75-d757-484b-8763-a39c8ab83ac2.png)

**Comment by alber-khan** [comment]
when i enter these details I'm able to login

**Comment by jaapmarcus** [comment]
What happens when you var_dump json_last_error()

**Comment by alber-khan** [comment]
Nothing, it's empty i can confirm the issue is there in nginx + php-fpm.
I just install fresh nginx + apache2 + php-fpm and when I run v-add-sys-pma-sso and tried to login via Panel it works fine,

**Comment by jaapmarcus** [comment]
I will run a few test today and check if I can see the error

**Comment by jaapmarcus** [comment]
Maybe a stupid question? 

But by accident hostname.com doesn't point to 127.0.1.1  as with some vps providers ?

**Comment by jaapmarcus** [comment]
` cat /usr/share/phpmyadmin/hestia-sso.php `

First few lines look like this:
```
/* Following keys will get replaced when calling v-add-sys-pma-sso */
define('PHPMYADMIN_KEY', 'xxxxx');
define('API_HOST_NAME', 'xxxxxxx');
define('API_HESTIA_PORT', '');
define('API_KEY', 'xxxxxxx');

```

If API_HESTIA_PORT is empty add you system port

**Comment by alber-khan** [comment]
> But by accident hostname.com doesn't point to 127.0.1.1 as with some vps providers ?
it was  actually lol and i have to delete the line from `/etc/hosts`

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/145992236-3513e5b3-66c8-4154-95a4-465faa5f28a1.png)

but in that file it's pointing to domain.tld

**Comment by jaapmarcus** [comment]
I assume it connect by default to a non existing ip 


We create a config file:
https://github.com/hestiacp/hestiacp/blob/47fd38209ceca718f88b8b96337e22de6ddf1656/install/hst-install-ubuntu.sh#L125-L131

And then delete it:
https://github.com/hestiacp/hestiacp/blob/47fd38209ceca718f88b8b96337e22de6ddf1656/install/hst-install-ubuntu.sh#L1118-L1121

I will submit a pull request to address this issue

echo "BACKEND_PORT='8083'" >> $HESTIA/conf/hestia.conf

And then v-delete-sys-pma-sso and then v-add-sys-pma-sso will address the issue

**Comment by 4183r** [comment]
BACKEND_PORT is already there.

![image](https://user-images.githubusercontent.com/39749258/146033499-e34c7162-f486-435e-9677-2f16703fda95.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/146033961-c6187a7a-5e6e-41a1-a58b-e445f8331c62.png)
`2021/12/14 21:30:30 [error] 205101#205101: *54 FastCGI sent in stderr: "PHP message: PHP Warning:  Unable to connect over API please check api connection in /usr/share/phpmyadmin/hestia-sso.php on line 55" while reading response header from upstream, client: 110.235.228.173, server: something.com, request: "GET /phpmyadmin//hestia-sso.php?database=getnames_tadeebulquran&user=getnames&exp=1639497627&hestia_token=$2y$10$uPRP8wQUiraAEqn5KHm8Vew0PW1A18kp7ycZ2YLtKLUlQFOkg.mvO HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "something.com", referrer: "https://something.com:8083/"`

Still getting the same issue.

**Comment by jaapmarcus** [comment]
hostname.com points to the server? 

What happens when you run curl -Is hostname.com:8083

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/146043435-f23d395d-692a-4a77-85a1-93de30b3d184.png)

**Comment by ScIT-Raphael** [comment]
do the command again with https:// in front...

**Comment by alber-khan** [comment]
Sorry for some reason Allowed IP went blank.
i've var_dump and get `ostring(44) "Error: IP is not allowed to connect with API"`
![image](https://user-images.githubusercontent.com/39749258/146043844-bbd7ce39-6540-4eeb-b3c1-6f458cce394f.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/146044115-cbda4ca6-7834-4a98-b2e3-282a24892e46.png)

it's fixed!
