### ISSUE TITLE
FPM PHP user permission

### ISSUE THREAD

**Issue by ang3lx** [hestiacp/hestiacp#229]
Hello
Could be very interesting to have that each domain (on the same user account) run under his user

Ex. User Pippo has 2 domains : abc.com cde.org
At this moment these domains run under Pippo account, so if WordPress on abc.com were hacked, cde.org can be compromised too because user sharing

Is possibile to run each domain with his php-fpm instance and his user?

Plesk do aleready this

**Comment by ScIT-Raphael** [comment]
Running multiphp, it will create for each domain a own pool configuration - but with the same user. I would suggest to split the domain to two users if you want to keep them separated.
