### ISSUE TITLE
FR/Q: Show user DKIM key/DNS record

### ISSUE THREAD

**Issue by xXKynarethXx** [hestiacp/hestiacp#230]
The user should see how he has to set up his dns records.
That information could be displayed at the "edit mail account" page, where all the other information that he needs to set up his email client e.g., is visible.
At the moment I can't find any possibility where a user (without SSH access) can look this up, if there is one, I would be pleased if you can tell me where :)

**Comment by ghost** [comment]
Thanks for the feedback @xXKynarethXx, I've added this to the list of items to investigate and improve upon for the mail stack overhaul that's currently in progress. 

Based on this, I think that the control panel interface should recognize and act as follows:

1. If the Hestia server is hosting Web & DNS for this domain, then add the DNS records as per usual and allow the user to view the configuration info under setup information as an option.
2. If the Hestia server is **only** hosting mail for this domain and no DNS zone or web domain exists, then display a configuration warning to alert the user that further setup is needed and display the information by default.

What do you think of this flow?

**Comment by xXKynarethXx** [comment]
Hello, @kristankenney, part 1 works already out of the box in my installation (afaik). If I register a new mail domain (with dns enabled on that node), then activate dkim, the records are already set by default :)
Part 2 would be perfect and a great enhancement!

**Comment by ghost** [comment]
@xXKynarethXx perfect, thanks! 

Somewhat related in terms of DNS/DKIM, if you have a moment to test this I'd greatly appreciate it: if you change your DNS zone's template from default to child-ns, do you subsequently lose the DKIM records but the mail domain settings still show DKIM as being enabled?

**Comment by xXKynarethXx** [comment]
I'll set up a server, could take a few minutes, I don't use DNS with hestia ^^
Do you have a OS I should test in detail? Setting up Debian 9 atm :)

**Comment by ghost** [comment]
No worries, whenever you have time :) The OS shouldn't matter, for what its worth I'm on Ubuntu 18.04.

**Comment by xXKynarethXx** [comment]
I think I found another bug, that I will write before I will test your problem (otherwise I forget how I got the bug :D ).
When I add a mail domain, then add the dns domain, then the dkim token won't be generated and added to dns (12 records total).
When I add the dns domain, then add the mail domain, I get the "mail._domain" & "_domainkey". (14 records total).
All with dns template default.
Had to triple check this, as I said I am using Debian 9 in this installation, maybe you know why it's behaving like that :D

**Comment by xXKynarethXx** [comment]
>do you subsequently lose the DKIM records but the mail domain settings still show DKIM as being enabled?

No, all records are untouched. But if I delete the mail domain, and add it again afterwards, I get 16! records. Tried to delete and add again, but turned to 14 at deletion and went up to 16 after adding the mail domain again.

Hope I could help a bit and didn't confuse even more :D

**Comment by ghost** [comment]
Hmm, I have seen the number of records fall out of sync in the header when this happens so it may be related but try this flow to see what happens in further detail:

On a Hestia server that supports Web/DNS/Mail roles:

1. Create a new web domain with both DNS and mail enabled
2. Navigate to DNS > yourdomain.tld and verify that mail._domain and _domainkey records exist:
2a. If the records exist, skip to step 3.
2b. If the records do not exist, navigate to Mail > yourdomain.tld, and turn DKIM off/on to create the records and verify that they exist.
3. Navigate to DNS > yourdomain.tld and change the template from default to child-ns
4. Navigate to DNS, list all of the records for yourdomain.tld and verify if mail._domain and _domainkey records for DKIM still exist or if they have been removed

**Comment by JOduMonT** [comment]
one project who I love how they present they DNS configuration is mailcow which they present it like this

![43882866-8caaeaba-9bb1-11e8-8875-f07f1cbaff29](https://user-images.githubusercontent.com/5204724/56168559-d6ef6300-5fdb-11e9-8f0d-1cffbd790dbf.png)

which, I think, is build with [this page](https://github.com/mailcow/mailcow-dockerized/blob/58d0f51242139d4f5407d68464479434644ac5b9/data/web/inc/ajax/dns_diagnostics.php)

**Comment by FalzoMAD** [comment]
somehow related... I never use dns on the hestia server itself. would be nice to copy the dkim record for a mail domain with the click of a button in the control-panel itself, maybe here:

![image](https://user-images.githubusercontent.com/25381635/62005546-18dc8900-b135-11e9-94dc-6ada11ec2032.png)

**Comment by TheDanielMoli** [comment]
Sorry, how do I manually get the DKIM public key? Couldn't find it out on my own.

**Comment by FalzoMAD** [comment]
v-list-mail-domain-dkim is the command you are looking for...

**Comment by Pleskan** [comment]
As well as **v-list-mail-domain-dkim-dns**

**Comment by ScIT-Raphael** [comment]
solved with https://github.com/hestiacp/hestiacp/pull/1570

**Comment by cantalupo555** [comment]
> As well as **v-list-mail-domain-dkim-dns**

Thank you.
I found the public key and added it to Cloudflare.

```
cd /usr/local/hestia/bin/
sudo -s ./v-list-mail-domain-dkim-dns user example.com
```
