### ISSUE TITLE
[Feature] individual users can backup to their own storage account. 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2301]
### Describe the feature or change in detail

currently, we can only export backup by admin under (Configure Server Settings)

![image](https://user-images.githubusercontent.com/39749258/146641881-d4a58944-96c0-4596-b519-4c2c37b85d06.png)
 and we have an option where individual users can put their own FTP, sFTP, Backblaze and Google Drive to back up their site data.

we can have it's settings under backup Tab 
![image](https://user-images.githubusercontent.com/39749258/146642038-fce4191b-2a50-46af-a486-dcb42165711f.png)

### Would you like to sponsor this feature to have it implemented?

No

**Comment by alber-khan** [comment]
the idea is inspired by Aapanel where they have an option to export the customer data to any Cloud Storage.

![image](https://user-images.githubusercontent.com/39749258/146642109-de78d224-0d4e-4516-9582-ac1b2be7228c.png)

**Comment by jlguerrerosanz** [comment]
Although It may seem like a good idea, since I sell the space for backups to my clients it may be counterproductive in my case
BUT it makes a lot of sense if you offer free hosting or your clients don't want to pay for backups and you don't want to assume any responsibility for the data.

**Comment by alber-khan** [comment]
@jlguerrerosanz we can also have an option to disable it from the backend. 
for example (Show/Hide Button)

**Comment by jaapmarcus** [comment]
With the number of available developers I don't think this feature will be ever implemented.

1. Additional intelengence need to be added so we are able to restore images. Because what if server has a 5 days backup and the client has a 10 days backup.
2. Backup rotation need to be adjusted. For example users want to have backups for 1 month.  And the admin only supports 7 days...

**Comment by jaapmarcus** [comment]
As our available time is limited. We are not able to implementent this feature...

If you want to implement it on your own, please feel free to provide a PR which we will review and merge, if it fits to our requirements.
