### ISSUE TITLE
[Bug] Database password with some characters does not allow adding more databases in the future

### ISSUE THREAD

**Issue by aalbarca** [hestiacp/hestiacp#2303]
### Describe the bug

When a new database is created and the password contents some special characters the file `/usr/local/hestia/conf/mysql.conf` is broken and we'll not be able to add more databases in the future.

The form input should be validate valid string passwords before to add.

### Tell us how to replicate the bug

1. Go to `https://myhost.tld/add/db/` and add a new database with some password like `(\"S(?.'\$B7y\bDPD'`
2. Now try to add a new database. The form will throw a error "Field host cannot be empty"
3. Command `v-list-database-hosts` throw a error: Error:  Invalid  object  format:
4. If you modify the password in the file `/usr/local/hestia/conf/mysql.conf` removing some characters the issue is fixed

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.1

### Operating system

Ubuntu 20.04

**Comment by aalbarca** [comment]
The issue is caused by another reason. I am investigating.

**Comment by jaapmarcus** [comment]
The issue is caused by the fact that ' is used as separator in the conf file 

As it is not escaped it *** up the config reading. Don't use any other special character is safe
