### ISSUE TITLE
[Feature] Provide sysadmin contact info when an error says to contact a sys admin

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2311]
### Describe the feature or change in detail

Sometimes like for instance when an user is suspended when they try to login this error appears suggesting the user to contact a system administrator.

Maybe a contact details field in the backend could be enough and if the sysadmin has put his details, hestia will provide them.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/2310

I don't see the need for 2 different issues

**Comment by jlguerrerosanz** [comment]
The error of a suspended account is not the only reason why that error could be triggered

**Comment by jlguerrerosanz** [comment]
The Success page is also a candidate for this.

**Comment by jaapmarcus** [comment]
I am not a fan of putting contact information on a public page. The effort most users try to hide everything for anything counteract the fact you put  the contact info on a public page.

**Comment by jlguerrerosanz** [comment]
Yes. But we could provide a custom link where the sysadmin can put a form or the contact page of his website

**Comment by ScIT-Raphael** [comment]
> Yes. But we could provide a custom link where the sysadmin can put a form or the contact page of his website

This doesnt make really sense, @jaapmarcus has already written the potential optimization of the template files in the other thread - there are no other changes planed.

**Comment by jlguerrerosanz** [comment]
Great. Thank you.
