### ISSUE TITLE
[Bug] suspended object gets excluded from disk usage calculation

### ISSUE THREAD

**Issue by Winwarin** [hestiacp/hestiacp#2312]
### Describe the bug

If a user has some email accounts or web domains which get suspended, those objects are excluded from disk usage calculation in Web UI.

Some scripts in BIN directory that do disk usage calculation uses:

`$(search_objects ..... 'SUSPENDED' "no" .....)`

So only objects that are not suspended get calculated.

### Tell us how to replicate the bug

1. Create web domain or mail account.
2. Suspend them
3. Copy 500MB+ file into the web domain or mail account directory
4. Run /usr/local/hestia/bin/v-update-sys-queue disk
5. Web UI ignore to report disk usage changes

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

Latest

### Operating system

Debian

**Comment by jaapmarcus** [comment]
See: https://forum.hestiacp.com/t/disk-quota-vs-panel-disk-usage/4808/4 for related issue

**Comment by jaapmarcus** [comment]
Both mail domains, web domains and databases where not taken into account
