### ISSUE TITLE
[Bug] Not possible to change user language when 2FA is enabled

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#2314]
### Describe the bug

If try to change the user language when editing the user profile and 2FA is enabled, get the message "Error: 2FA already enabled"

Have to disable 2FA in order to change user language

### Tell us how to replicate the bug

Go to Edit User
Select another language
Click save

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.2

### Operating system

Debian 10

**Comment by jaapmarcus** [comment]
Can confirm the issue
