### ISSUE TITLE
[Bug] String "Enable two-factor authentication" not being translated

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#2315]
### Describe the bug

String "Enable two-factor authentication" on edit user page not being translated

### Tell us how to replicate the bug

1 - Go to edit user
2 - Make sure you are not using English language (tested with Portuguese)
3 - read the string in english

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.2

### Operating system

Debian 10

**Comment by jaapmarcus** [comment]
See https://translate.hestiacp.com/projects/hestiacp/pt/default/?filters%5Bterm%5D=Enable+2FA&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc 

Please :)
