### ISSUE TITLE
[Feature] FPM process_control_timeout setting

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2318]
### Describe the feature or change in detail

[Feature] FPM
process_control_timeout setting
Currently is disabled as per PHP-FPM's default settings.
This causing WordPress websites keep utilizing high CPU if it runs 5 minutes or more (due to some bad plugin scripts etc.,).
Can you set the php-fpm config file for this setting as our hestia's default..?

Method : Just add this line on top of the 'php-fpm.conf' file, as our hestia's default settings (I set just 180)
**process_control_timeout = 300**

If people want to change, they can do it manually. So the default HestiaCP with FPM become more reliable..

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by ioannidesalex** [comment]
Hmm very strange. I was almost sure that we shipped a custom php-fpm.conf with Hestia and not the default. Let me check and will get back to you. There are several optimizations that could br done on that file, including what you propose.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/fe68ebe0b66962470a529393ad913069fbfe53a1/bin/v-add-web-php#L116-L125

It looks like we don't

**Comment by ioannidesalex** [comment]
https://github.com/hestiacp/hestiacp/blob/main/src/deb/php/php-fpm.conf

We do for Hestia’s own PHP processes. This is what I remember.

 I will arrange this.

**Comment by vvcares** [comment]
@ioannidesalex  Hi, Is this commit included in the latest v1.5.3..?
If is included, Is this amended the required FPM CONF files inside my existing Hestia server  (OR) need to install as fresh Hestia ?

**Comment by ScIT-Raphael** [comment]
@vvcares This is not a commit, only a feature request which is still open - so there is currently nothing to include in 1.5.3.

**Comment by vvcares** [comment]
Hi @ScIT-Raphael  Thank you.
