### ISSUE TITLE
mysql-server : Depends: default-mysql-server E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by Amitxyz** [hestiacp/hestiacp#232]
### Brief issue description:
 mysql-server : Depends: default-mysql-server
E: Unable to correct problems, you have held broken packages.

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
Type here (e.g. 0.9.8-28)
09.8.28

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-server : Depends: default-mysql-server
E: Unable to correct problems, you have held broken packages.

**Comment by Amitxyz** [comment]
How to fix this?

**Comment by ghost** [comment]
Hi @amitx11, sorry to hear you're having trouble with the installation process. I'll spin up a Debian 9 virtual machine this evening to see if I can reproduce this issue and report back as soon as I have more information for you.

**Comment by ScIT-Raphael** [comment]
@amitx11 Where does this happen? On running the installer? Just checked on a clean Debian 9 system - all is working as expected.

**Comment by Pleskan** [comment]
@amitx11 I think you should check [this](https://unix.stackexchange.com/questions/470903/error-installing-mysql-server-on-debian-9-stretch-dependency-problems/470920) at first.

**Comment by ghost** [comment]
@amitx11, 

I have also been unable to reproduce this issue on a clean installation of Debian 9.8.0. If this issue still persists please let us know so that we may continue to troubleshoot.
