### ISSUE TITLE
[Bug] Disabling preview features keeps them enabled

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#2322]
### Describe the bug

When enabling preview features and then enable "PHPMyAdmin Single SignOn" if then I disable preview features the PMASS keeps on. Did not test with "Policy: Allow suspended users to log in with read-only access" but might occur the same.

### Tell us how to replicate the bug

1 - Enable preview features
2 - Enable PHPMyAdmin Single SignOn
3 - Disable preview features
4 - Go to DB List and click on PMASS icon

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.2

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Bug is correct won't fix it for PHPMyAdmin option as it should be stable enough the allow users to select it on default and just moved it out of final testing phase
