### ISSUE TITLE
[Bug] Exim4 Tainted file aliases

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#2326]
### Describe the bug

Immediately after an upgrade to Debian 11 (thus exim 4.94) exim tainted errors started occurring.  I tried rebuilding the user both from the web interface and command line and rebooting the server, but no success.  

I saw that there were other resolved issues on this topic and the code seems already committed and released, so I am guessing that this is either a separate issue or that there is no self-healing code in the rebuild yet and that I will have to make some manual corrections.

Inbound emails are also not coming in because of a different (but similar) tainted error.  I will log a separate issue.

### Tell us how to replicate the bug

Previously working HestiaCP install on Debian 10 with domain aliases, email aliases, etc.  Upgrade to Debian 11.

Versions on server are as follows:

`exim4/stable,now 4.94.2-7 all [installed]`
```
v-list-sys-info 
HOSTNAME         OS      VER   ARCH    HESTIA  RELEASE  UPTIME  LA
--------         --      ---   ----    ------  -------  ------  --
[...]            Debian  11.2  x86_64  1.5.2   release  46      0.00
```

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.5.2

### Operating system

Debian 11

### Log capture

```shell
Tainted filename for search '/etc/exim4/domains/[...]/aliases'
[...] sender verify defer for <[...]>: failed to expand "${extract{1}{:}{${lookup{$local_part@$domain}lsearch{/etc/exim4/domains/$domain/aliases}}}}": NULL
[...] X=TLS1.3:ECDHE_SECP256R1__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=no SNI=[...] F=<[...]> A=dovecot_plain:[...] temporarily rejected RCPT <[...]>: Could not complete sender verify
```
```

**Comment by jaapmarcus** [comment]
See: https://forum.hestiacp.com/t/install-hestiacp-debian-11/4313/5

**Comment by jaapmarcus** [comment]
There are some config changes in Exim versions what we can't control so it will not heal...

**Comment by vestacp-user** [comment]
@jaapmarcus Thank you for your quick response.  The manual exim4 correction worked.  Also applied the pam.d correction with no issues. 

Just for extra safety for those who are less familiar with these systems, I would suggest moving/copying the files to be changed and not force the copy.

```
cp /etc/pam.d/common-password /root/
sed -i "s/obscure yescrypt/obscure sha512/g" /etc/pam.d/common-password
```

```
mv /etc/exim4/exim4.conf.template /root/
cp /usr/local/hestia/install/deb/exim/exim4.conf.4.94.template /etc/exim4/exim4.conf.template
```
