### ISSUE TITLE
[Feature] IPv6 Only

### ISSUE THREAD

**Issue by rlacr0ix** [hestiacp/hestiacp#2329]
### Describe the feature or change in detail

Support installation/working on 100% Ipv6 Host/Network

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
I think step one is working on the fact  to get ipv6 working at al. 

https://github.com/hestiacp/hestiacp/issues/429

Also a problem to solve is that Launchpad is still ipv4 only...

After that we need to decide if it is worth to add support for ipv6 only...
