### ISSUE TITLE
[Bug] Cannot Download Local Backup

### ISSUE THREAD

**Issue by themew** [hestiacp/hestiacp#2335]
### Describe the bug

 Domain Local backup displays as 'local backup'. Backups are automatically created locally every day at 5:10am. Remote backup is not set and has never been set up.

Click the download link and server reports
![image](https://user-images.githubusercontent.com/7772702/148398442-3bd2abc6-5578-435f-b16f-2fb207fe89c1.png)

A minute later, the golden bell lights up and informs me that **"Backup file user.2022-01-06_05-12-00.tar was retrieved from the remote server and will be available to download for 12 hours."**

I do see the backup in the backup folder using CLI so it is on the server, just can't be accessed from the panel.
Also noticed that the username in the backup directory for the backup and log file changed on 12-26 from user.2020-12-26_05-10-58.tar to USER.2020-01-06_05-12-00.tar.  I have an uppercase backup from 12-26 and uppercase.log file as well as a lower case backup and .log file.

Only 1 backup is set to store on the sever and the username has never been changed in 3+ years.

Just trying to help file the answer to this...

### Tell us how to replicate the bug

1. In panel go from admin to domain (log in as user button)
2. Click BACKUPS
3. Choose to download backup
4. Server informs user that 'download of remote backup has been scheduled'

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.3

### Operating system

Debian 10.11

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/i-can-not-download-backups/5309/4

**Comment by jaapmarcus** [comment]
We have to rebuild the packages for hestia-php

**Comment by jaapmarcus** [comment]
Issue has been patched with:
https://github.com/hestiacp/hestiacp/commit/661ec27b0c0bc241c1b8840bbe94897ed97f202b

We still need to release the new package probally happen next week

To fix the issue see forum topic

**Comment by themew** [comment]
@jaapmarcus  Thanks for the response and posting the fix.  Really appreciate the amazing effort that goes into HestiaCP.

**Comment by jaapmarcus** [comment]
Fixed with https://github.com/hestiacp/hestiacp/commit/661ec27b0c0bc241c1b8840bbe94897ed97f202b
