### ISSUE TITLE
[Bug] create user through dashboard vs through commad line

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2337]
### Describe the bug

When I create a user through web dashboard, I can see in the User list something like: test (test)
When i create the user through commad line, I see: test()

Example:
![Captura de Tela 2022-01-06 às 17 25 07](https://user-images.githubusercontent.com/8779476/148447303-9d8384e1-e4bd-4642-9739-d5b59164a6ba.png)

Id I try to change some user config, like force redirect to www. version, I get a "parse error".
<img width="685" alt="Captura de Tela 2022-01-06 às 17 27 37" src="https://user-images.githubusercontent.com/8779476/148447438-bca5f250-a300-4f32-a21e-f60759192364.png">

If I try to do the same thing with the user created thorugh web dashboard, the error does not happen.

### Tell us how to replicate the bug

I do not think all the steps are necessary, but I will write all commands that i execute.

1. Create one user 
```bash
/usr/local/hestia/bin/v-add-user $get_user $get_password $get_email
```

2. Add the domain
```bash
/usr/local/hestia/bin/v-add-domain $get_user $get_domain
``` 

3. Change the doc root
```bash
/usr/local/hestia/bin/v-change-web-domain-docroot $get_user $get_domain $get_domain source/public/
``` 
4. Create database
```bash
/usr/local/hestia/bin/v-add-database $get_user $panel_database_name $panel_database_name $panel_database_pass
```
5. Change php version
```bash
/usr/local/hestia/bin/v-change-user-php-cli $get_user $panel_site_cli_php_version
/usr/local/hestia/bin/v-change-web-domain-backend-tpl $get_user $get_domain $panel_site_php_version
```
6. Add cronjob
```bash
/usr/local/hestia/bin/v-add-cron-job $get_user '*' '*' '*' '*' '*'  "cd /home/${get_user}/web/${get_domain}/public_html/source && /usr/bin/php7.4 artisan schedule:run >> /home/${get_user}/web/${get_domain}/logs/cron.log 2>&1"
```
7. Add www alias
```bash
 /usr/local/hestia/bin/v-add-web-domain-alias $get_user $get_domain www.${get_domain} yes
``` 

Note:
When i just execute the first command (to create the user), i saw the same behavior in User list: test2 (), instead of test2 (test2). If I manually add a domain there, I can edit without get "Parser error".

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.5.3

### Operating system

Ubuntu 20.04.3

### Log capture

```shell
2022-01-06 20:30:40 v-add-web-domain  'test' 'abc.com' '192.168.1.175' 'yes' 'www.abc.com' 'jpeg,jpg,png,gif,bmp,ico,svg,tif,tiff,css,js,htm,html,ttf,otf,webp,woff,txt,csv,rtf,doc,docx,xls,xlsx,ppt,pptx,odf,odp,ods,odt,pdf,psd,ai,eot,eps,ps,zip,tar,tgz,gz,rar,bz2,7z,aac,m4a,mp3,mp4,ogg,wav,wma,3gp,avi,flv,m4v,mkv,mov,mpeg,mpg,wmv,exe,iso,dmg,swf' [Error 2]
 

```bash
2022-01-05 23:57:50 v-add-web-domain-alias  'hestiacpuserxyz' 'domain.com' 'www.domain.com' 'yes' [Error 4]
2022-01-06 14:33:31 v-change-web-domain-ip  'hestiacpuserxyz' 'domain.com' '192.168.1.175' 'no' [Error 12]
```

```bash
2022-01-06 20:30:40 v-list-web-domain  'test' 'abc.com' 'plain' [Error 3]
2022-01-06 20:30:40 v-list-web-domain  'test' 'abc.com' 'plain' [Error 3]
```
```

**Comment by franciscopaniskaseker** [comment]
About the empty name, according to the documentation they are optional ( https://docs.hestiacp.com/cli_commands/commands.html#v-add-user ), so that behavior is ok.

I am not sure yet why I am getting parse error.

**Comment by jaapmarcus** [comment]
The behaviour for v-add-user is correct if you want also the name filled use:
v-add-user user password email package name

2022-01-05 23:57:50 v-add-web-domain-alias  'hestiacpuserxyz' 'domain.com' 'www.domain.com' 'yes' [Error 4]
www.domain.com does already exists...


2022-01-06 14:33:31 v-change-web-domain-ip  'hestiacpuserxyz' 'domain.com' '192.168.1.175' 'no' [Error 12]

https://github.com/hestiacp/hestiacp/blob/984af65017c3b85dd817c5f6e857b2db7a185afc/func/main.sh#L43


It looks the error is here:

https://github.com/hestiacp/hestiacp/blob/fe68ebe0b66962470a529393ad913069fbfe53a1/func/ip.sh#L90-L113

Please check the configs for /usr/local/hestia/data/ips/xxxx.conf

**Comment by franciscopaniskaseker** [comment]
I just found this file (no .conf there):
```bash
/usr/local/hestia/data/ips/192.168.1.175
``` 

I removed the NAT config (as we talked here https://github.com/hestiacp/hestiacp/issues/2281 ), but when I try to rebuild the template, I got this:
```bash
root@panel:~# /usr/local/hestia/bin/v-rebuild-web-domains username
Error: IP x.y.z.w doesn't exist
``` 

And the problem is here:
```bash
+ '[' '!' -e /usr/local/hestia/data/ips/x.y.z.w ']'
++ grep -H '^NAT='\''x.y.z.w'\''' /usr/local/hestia/data/ips/x.y.z.w
+ nat=
```

The "x.y.z.w" ip come from this file:
```bash
  /usr/local/hestia/data/users/LOGIN/web.conf
``` 

I changed to local IP and it fixed the problem.

Maybe there is some other command before do
```bash
/usr/local/hestia/bin/v-rebuild-web-domains username
```

but I did not find.

**Comment by jaapmarcus** [comment]
Please use links to the source code so it makes debugging on our side a lot easier.. The code used is:
https://github.com/hestiacp/hestiacp/blob/fe68ebe0b66962470a529393ad913069fbfe53a1/func/ip.sh#L257-L265

As it doesn't make sense for us to support such use cases I will close this issue... 

config in web does require the localconfig but usually the external ip is show as this the default value what the user needs to see.. 

As told in #2282 it doesn't make sense to change it for one user...
