### ISSUE TITLE
[Bug] HTTP 500 Error occurs when Wordpress is installed by Quick Install App

### ISSUE THREAD

**Issue by Nadun21** [hestiacp/hestiacp#2342]
### Describe the bug

I installed Wordpress using the Quick Install App

It comes with HTTP ERROR 500

The website did not work

I had to install Manual Wordpress.

I reinstalled Hestiacp and tried but the problem persists

This problem has been around for about two months

### Hestia Control Panel Version

1.5.3

### Operating system

Debian 10, Debian 11

**Comment by ScIT-Raphael** [comment]
This is a current bug in 1.5.3, it has been fixed in 1.5.4 which will be released today or tomorrow.

**Comment by Nadun21** [comment]
> This is a current bug in 1.5.3, it has been fixed in 1.5.4 which will be released today or tomorrow.

ok thank you
