### ISSUE TITLE
[Bug] sshd_config

### ISSUE THREAD

**Issue by Mertsahin-Demircioglu** [hestiacp/hestiacp#2347]
### Describe the bug

sshd_config,v stuck at version 1.103.
1) It has not been updated in the latest version 1.5.4 Have any changes been made to this package?
2) If it is done, will I encounter any problems if I update it? At the moment, I have not encountered any problems other than the main domain ssl.
* I'm looking at others

### Tell us how to replicate the bug

sshd_config,v stuck at version 1.103.

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.4

### Operating system

Ubuntu

**Comment by ioannidesalex** [comment]
Being "stuck" at a version has nothing to do with HestiaCP, since we are not touching OpenSSH (apart from some small configuration changes).

It's your call to make if you want to update it / compile from source.

**Comment by Mertsahin-Demircioglu** [comment]
I don't think there will be any corruption in version 1.5.4 I still wanted to ask. Thank you.
