### ISSUE TITLE
[Bug] Backblaze backup fail to run with /tmp noexec

### ISSUE THREAD

**Issue by ptrinh** [hestiacp/hestiacp#2348]
### Describe the bug

For security concern, we should make /tmp noexec.
However, the B2 backup requires +x on /tmp.

### Tell us how to replicate the bug

1. Install hestiacp as a docker container (https://hub.docker.com/r/smied/hestia-cp)
2. Try running: v-backup-user admin

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.4.5

### Operating system

Ubuntu 20

### Log capture

```shell
b2: error while loading shared libraries: libz.so.1: failed to map segment from shared object
2022-01-14 10:18:22 Size: 2 MB
2022-01-14 10:18:22 Runtime: 1 minute
```

**Comment by jaapmarcus** [comment]
We don't provide the Docker images I think in this case I suggest contact the developer who made the Docker image

**Comment by jaapmarcus** [comment]
Also we don't control the permissions required for B2 as we download the official package from Blackblaze

We can't do anything about it.
