### ISSUE TITLE
Feature Request: Dynamic DNS

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#235]
This would be awesome to have maybe a simple GET request along with a session key.

**Comment by ghost** [comment]
Hey @johnnyq, this is a great idea, I'll be sure to raise this with the team during our next meeting.

**Comment by ScIT-Raphael** [comment]
There is already a implementation for vestacp, that can be also used for hestia: https://github.com/ryanbrownell/DDNS-for-Vesta-CP

We will discuss this and decide of a direct implementation.

**Comment by johnnyq** [comment]
Oh this is fantastic news!! I have so many sites with Dynamic IPs =]

**Comment by JOduMonT** [comment]
would be interesting to make it as option like postgresql

oh and please if you implement this

don't forget the patch for CloudFlare and cie

here a simple example of how I install it in a [lxc container](https://github.com/jodumont/ScRIPtS/blob/master/Debian/ddclient-install.sh)

**Comment by ScIT-Raphael** [comment]
Infact we moved this feature request around since nearly two years, we decided to close it: We currently do not have enough time to implement such a function, also it isnt on our highest priority. Please feel free to provide a PR for it, we would love to implement it.
