### ISSUE TITLE
[Bug] Remaining files and folders

### ISSUE THREAD

**Issue by dyrer** [hestiacp/hestiacp#2351]
### Describe the bug

Hello
I saw some no needed  files in accounts directories live visual studio code server
can you check
![hestia](https://user-images.githubusercontent.com/379094/149616825-96f59db5-d105-4038-8f49-2cd3645274a0.png)

### Tell us how to replicate the bug

CLI in server

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.5.4

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
This is by design, users can't create folders in /home/user, so we create a bunch of default folders: https://github.com/hestiacp/hestiacp/blob/fe68ebe0b66962470a529393ad913069fbfe53a1/bin/v-add-user#L116-L132
