### ISSUE TITLE
[Bug] PMA SSO Issues

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#2359]
### Describe the bug

I am reporting two issues

1 - Is not possible to enable PMA SSO if API is disabled

2 - PMA SSO is not doing its job

### Tell us how to replicate the bug

Issue 1
1 - Disable API
2 - Enable PMA SSO
3 - Get error message "error: API is not enabled"
![Screenshot from 2022-01-19 14-57-54](https://user-images.githubusercontent.com/23358751/150157246-a9f0e465-e0b9-44fa-b5f1-7228b72d08eb.png)

Issue 2
1 - Enable PMA SSO
2 - Use UI icon on Databases list to PMA SSO
3 - PMA opens but asks for authentication

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.4

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
PMA SSO connects over API....

**Comment by manuelserol** [comment]
> 

I believe you mean SSO, not SSH. This is happening on a clean and standard installation, not upgrade

**Comment by jaapmarcus** [comment]
I accidentally submitted the form...

PMA SSO connects over the API so it is required to enable it ....

For the last error check the error logs of the domain it should provide more information regarding why it is not able to connect..

If you have use Cloudflare for the domain it might be an issue as it changes your ip address..

**Comment by manuelserol** [comment]
If PMA SSO uses the API that is not explicit anywhere. In this case I suggest to add it to the UI like "PhpMyAdmin Single Sign On (requires API enabled)" or change the error message to a more explicit one in regad to PMA SSO activation or at least to the docs.

I disabled Cloudflare proxy, enabled Cloudflare development mode, purged Clouflare cache, cleared the browser cache/cookies and still does not go through. I have other servers and domains under Cloudflare proxy where PMA SSO is working fine

**Comment by jaapmarcus** [comment]
Check the error logs

**Comment by manuelserol** [comment]
I am doing it

**Comment by johnnyq** [comment]
I have never been able to get PhpMyAdmin SSO working either. Although I haven't tried it on a fresh install. I will follow this thread to see what the conclusion is. I have Enabled API Access to Yes as well as phpmyadmin SSO.Enabled

**Comment by jaapmarcus** [comment]
Check /var/log/{webserver}/domain/hostname.error.log

So far issues I am aware of:
1.  Hostname goes over public ip instead of local ip. Add you public ip to the allowed ips
2. Cloudflare Proxy enabled. It messes things up with the ip addresses.. Disable it

If have added errors in it:
https://github.com/hestiacp/hestiacp/blob/7b6e4b7541a469d48bc7dc4b1867e40ed7288a3e/install/deb/phpmyadmin/hestia-sso.php#L55-L56

So check them out...

**Comment by johnnyq** [comment]
@jaapmarcus I juasst added my public IP to the API allow list and that fixed the issue! Thank you!!
Although shouldnt the API always accept from the IP anyway if enabled and then anything else added would be extra.

**Comment by ob-tk** [comment]
If the client IP (browser) matches the server IP, I get the following error: "Access denied: There is a security token mismatch" in the error.log

In this case аdding the public server IP to the allowed ips is  not work for me.

**Comment by jaapmarcus** [comment]
In that case it didn't even connect to the api... 

HestiaCP calculates a token based on $database.$user.$ip.$time.PHPMYADMIN_KEY and verify against the provided token.

https://github.com/hestiacp/hestiacp/blob/7b6e4b7541a469d48bc7dc4b1867e40ed7288a3e/install/deb/phpmyadmin/hestia-sso.php#L153-L156

I have no idea why it might be a difference between the client ip in HestiaCP UI and when accessing PHPmyadmin..

Enable Debug mode in HestiaCP settings and add an var_dump($ip); exit(); after https://github.com/hestiacp/hestiacp/blob/7b6e4b7541a469d48bc7dc4b1867e40ed7288a3e/install/deb/phpmyadmin/hestia-sso.php#L154

As I am not able to replicate the setup. I am not able to test it... And as it is not an Critical feature I won't invest in setting it up....

**Comment by ob-tk** [comment]
If the client (browser) and server have the same external IP: string(0) ""

Here's why:
https://github.com/hestiacp/hestiacp/blob/7b6e4b7541a469d48bc7dc4b1867e40ed7288a3e/install/deb/phpmyadmin/hestia-sso.php#L85-L87

**Comment by jaapmarcus** [comment]
Hestia isn't designed on to be ran on the same computer. Use the password authentication... If I remove this line the the users who are using Nginx + Apache2 will complain because the the are not able to use it due to the proxy infront of it...
