### ISSUE TITLE
[Feature] Security: Email login credentials to: create a secure encrypted temp link for the password

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#2361]
### Describe the feature or change in detail

The option **Email login credentials to:** which appears if you add a new mail, db, hestia user.

The password should not be sent over email but instead a temp self destructing link should be provided in place of the password and then when clicked on it will reveal the password and then self destruct. This link can expire within 4 Hours by default or can be set in the admin panel settings as well.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
Sometimes it is handy to just email credentials. Maybe this could be an option just as send credentials.

Imagine someone has multiple devices and you are going to help set up the clients. In this case, if the user changes the password, the workflow is more complicated.

Or if a client changes his password and only configures one device. Then, again he will have to share the info via insecure channels so his nephew can help him set the iphone.

**Comment by ScIT-Raphael** [comment]
Currently, providing an own ots function for hestia is out of our planed range and will not be implemented from our side. If you want to implement it on your own, please feel free to provide a PR which we will review and merge, if it fits to our requirements.

**Comment by jaapmarcus** [comment]
Also for "Hestia" Users ask the user to create a new password via Lost password.
