### ISSUE TITLE
User Packages Default no edit [Bug] 

### ISSUE THREAD

**Issue by speak82** [hestiacp/hestiacp#2362]
### Describe the bug

User Packages Default no edit

### Tell us how to replicate the bug

User
Packages 
click Default

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.4

### Operating system

Debian 10

**Comment by ScIT-Raphael** [comment]
https://forum.hestiacp.com/t/user-default-package-not-editable/4184
https://github.com/hestiacp/hestiacp/issues/1970
and more entries, just use the search function next time :).

**Comment by jaapmarcus** [comment]
Will get changed soon!
