### ISSUE TITLE
[Bug] Renewal LE CP does not renew (+ Mail)

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2363]
### Describe the bug

This has only happened so far on one of many Hestia servers I’m looking after, but I thought I’d mention it here in case it was a wider problem. And SSL certs go in 2 or 3 month cycles, so it could be the first server in a wave of them … anyway.

panel.domain.com is the domain name assigned as the system host. It is assigned to a webserver (http/https), hestia install (port 8083), and mail server (dovecot and exim).

The certificate was expiring on Jan 10th, so Letsencrypt renewed it as expected for the web domain around Dec 10th. However it didn’t update the certificate for Hestia, or the mail subsysems, so those expired this week and clients started complaining about their mail not working.

It wasn’t hard to fix. I ran:
v-change-sys-hostname panel.domain.com (not sure if this one was necessary)
v-add-letsencrypt-host
and all was good again. But it shouldn’t really have happened. Any ideas what was the cause? Is this just a weird one-off? Or is it a bug? I guess my questions will be answered if others start to experience it. But I just thought I’d post here to warn of a potential problem.

I run a script to check various SSL certs for webservers, so that reported no problems, and I didn’t pick it up until too late. I might now look at including some checks for mail server SSL certs too.

https://forum.hestiacp.com/t/ssl-certs-did-not-update-correctly-for-cp-and-mail/5355

### Tell us how to replicate the bug

Add LE to hostname and wait until it expires

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.5.4

### Operating system

N/A

**Comment by ioannidesalex** [comment]
What happened to me in the past is certificates not to renew without any errors and they just expired. I removed the certificate and recreated it and everything was ok. Don’t know if its related though.

**Comment by jaapmarcus** [comment]
Yes.. 

For example: 
SSL renewed on 11 Jan  
How ever Hestia was still expire on  9 February 

Hestia should be able to manage it self...

**Comment by caos30** [comment]
@jaapmarcus i've the same problem on one of my three HestiaCP servers. The SSL certificate for the domain web has been updated correctly as expected. And the certificates for mail it seem to work fine too. But the certificate being loaded when visiting the domain name hosted on the server with port 8083 to access HestiaCP returns THE OUTDATED SSL certificate.

I would say that i reported this issue several months ago. Some developers of the core project told me that the proble could be that i use the domain name as "hostname" of the machine. But sincerely, i do the same with the other 3 virtual servers and they have not this problem.

So... you've me here finding an answer/solution.

**Comment by caos30** [comment]
Ok, i've run the suggeste command `v-add-letsencrypt-host` and it worked immediately. All the certificates has been successfully re-generated.

So, i will be monitoring if this issue happen again 2 months later ;-)
Thanks anyway for be there guys.

**Comment by jaapmarcus** [comment]
Bug only has been introduced around 21 December 2021.

**Comment by rooteto** [comment]
Hi,

I ran v-add-letsencrypt-host but it **didn't fix it**.

root@server:/# v-add-letsencrypt-host
Error: Let's Encrypt validation status 400 (servername.com). Details: Unable to update challenge :: authorization must be pending
Error: Let's Encrypt SSL creation failed

**Comment by caos30** [comment]
> authorization must be pending

Be sure that the DNS for that domain name or subdomain hast been propagated, if you changed it recently. Let's Encrypt need to check if the domain name resolve to the same IP you say you use the certificate.

**Comment by rooteto** [comment]
all dns are correct. no error appears.

**Comment by rooteto** [comment]
https://acme-v02.api.letsencrypt.org/acme/finalize/252958940/58249305090

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Method not allowed",
  "status": 405
}

**Comment by ScIT-Raphael** [comment]
As @jaapmarcus wrote here, plase use our forum:
https://github.com/hestiacp/hestiacp/issues/2376#issuecomment-1020486084

Also it doesnt make sense to write in another, resolved issue.
