### ISSUE TITLE
[Bug] HestiaCP - Phpmyadmin Access Denied Error

### ISSUE THREAD

**Issue by rooteto** [hestiacp/hestiacp#2364]
### Describe the bug

I installed Hestiacp. I created a user.

I added database to user. I pressed the phpmyadmin button, the error I got was "Access Denied"

![image](https://user-images.githubusercontent.com/3899331/150475381-7fe5d6ff-be8a-40b4-afa8-7b4bb02a392a.png)

![image](https://user-images.githubusercontent.com/3899331/150475317-2446a4dc-af34-438e-a375-2cc41ed7036b.png)

### Tell us how to replicate the bug

Access Denied

You do not have permission to view this page.
Please check your credentials and try again.
Error Code: 403

### Which components are affected by this bug?

Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

v1.5.4

### Operating system

Ubuntu 18.04 (x86_64)

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/2243

Also what is your setup in the case of modphp + apache2 make sure www-data

Also please check the logs

**Comment by rooteto** [comment]
I just installed the server.

"Also what is your setup in the case of modphp + apache2 make sure www-data" - **I did not get it.**

"Also please check the logs" - which logs? (file,directory)

**Comment by rooteto** [comment]
[Thu Jan 20 20:55:19.218781 2022] [autoindex:error] [pid 28446:tid 140490829641472] [client 192.168.1.105:0] AH01276: Cannot serve directory /usr/share/phpmyadmin/: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: https://server.com:8083/

I saw such an error.

/var/log/apache2/domains/server.com.error.log

**Comment by jaapmarcus** [comment]
What is your install command?

What is the contents of /usr/share/phpmyadmin/

**Comment by rooteto** [comment]
"What is your install command?"
sudo apt-get update && apt-get upgrade
sudo wget -qO - https://gpg.hestiacp.com/deb_signing.key | sudo apt-key add -
sudo apt-get install ca-certificates
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
sudo bash hst-install.sh

"What is the contents of /usr/share/phpmyadmin/"
![resim](https://user-images.githubusercontent.com/3899331/150531669-2e288f8f-7f78-43fe-9ad4-3940bc00a1a4.png)

**Comment by jaapmarcus** [comment]
Run /usr/local/hestia/install/upgrade/manual/migrate_phpmyadmin.sh  and it should install phpmyadmin

**Comment by rooteto** [comment]
i got error.

`To remove phpMyAdmin you will need use the root password. Password can be found in /usr/local/hestia/conf/mysql.conf
Would you like to continue? [y/n]y

PMA Hestia-SSO plugin has been succesfully removed/disabled
[ * ] Backing up old configuration files...
[ * ] Marking phpmyadmin as held in apt...
phpmyadmin set on hold.
[ * ] Removing old folders...
[ * ] Creating new folders...
rm: cannot remove '/etc/apache2/conf.d/phpmyadmin.conf': No such file or directory
[ * ] Installing phpMyAdmin version v5.1.1...
tar (child): phpMyAdmin-5.1.1-all-languages.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
cp: cannot stat 'phpMyAdmin-5.1.1-all-languages/*': No such file or directory
sed: can't read /usr/share/phpmyadmin/libraries/vendor_config.php: No such file or directory
sed: can't read /usr/share/phpmyadmin/libraries/vendor_config.php: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
[ * ] Creating localhost configuration...
[ * ] Dropping database (could throw an error if successful)...
[ * ] Creating new user...
[ * ] Creating new database...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
PMA Hestia-SSO plugin has been succesfully installed
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
`

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/7b6e4b7541a469d48bc7dc4b1867e40ed7288a3e/install/upgrade/manual/migrate_phpmyadmin.sh#L71-L75

It seems that fails to download phpmyadmin for some reasons

Are you able to download it via wget --quiet https://files.phpmyadmin.net/phpMyAdmin/5.1.1/phpMyAdmin-5.1.1-all-languages.tar.gz

**Comment by rooteto** [comment]
I downloaded it manually and extracted it to the folder. what should i do now

**Comment by rooteto** [comment]
Thank you. 

![resim](https://user-images.githubusercontent.com/3899331/150548822-c4020ece-2db8-4902-914d-0d0639fd4d1e.png)
