### ISSUE TITLE
[Bug] v-update-letsencrypt-ssl does not update host cert

### ISSUE THREAD

**Issue by nirbhasa** [hestiacp/hestiacp#2367]
### Describe the bug

This may be a bug, or just a documentation issue, depending on the intention behind `v-update-letsencrypt-ssl`

In attempting to fix the issue, I was also a little confused by the documentation at https://docs.hestiacp.com/cli_commands and the differences between the various letsencrypt commands. 
I ran `v-add-cron-letsencrypt-job` which generates the cron command `v-update-sys-queue letsencrypt`. It is unclear how this latter command differs from `v-update-letsencrypt-ssl`, whether one deprecates the other, and if the latter command would update the hostname cert.

If the intention is for `v-update-letsencrypt-ssl` not to update the hostname cert, is it advisable to add a cron job for `v-add-letsencrypt-host`?

### Tell us how to replicate the bug

Despite `v-update-letsencrypt-ssl` set to run daily via cron, my hostname cert expired. (I updated it successfully by running `v-add-letsencrypt-host`)

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.5.4

### Operating system

Debian 10

**Comment by kpapad904** [comment]
Check https://github.com/hestiacp/hestiacp/pull/2366

**Comment by ScIT-Raphael** [comment]
Thanks @kpapad904, already fixed.
