### ISSUE TITLE
[Feature] Show server time in Cron page

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2368]
### Describe the feature or change in detail

Server time could be different than the admins and that could lead to mistakes such as to think that Cron system is inoperative or that my new script doesn't work.

To know server's time in the Cron page would prevent this from happening.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by mehargags** [comment]
+1
this timezone setup can be 
1) A question for install wizard
2) custom install parameter
so that timezone setup is 'prompted' at install time

And the WebUI/v-xx/h scripts can be used to set timzone
