### ISSUE TITLE
[Feature] Derive additional DNS templates from default.tpl

### ISSUE THREAD

**Issue by tamas36** [hestiacp/hestiacp#2369]
### Describe the feature or change in detail

It looks like gmail, office365 and zoho DNS templates are currenty based on child-ns.tpl, because NS records are fixed in them, just like in child-ns.tpl. (If this is not the case, apologize for my assumption.)

**Suggestion:** Derive additional DNS templates from default.tpl, because this template has the support of every core functions of Hestia, like custom NS entries per package/customer, which is not the case of child-ns.tpl.

**Problem description**: .hu domains must have two nameservers in two different locations by .hu Registry's restrictions. So, let's assume one of my Hestia customer wants to handle his DNS in Hestia. I assign him a package, that has custom presetted nameservers, for example ns1.{hestia_machine}.hu, ns2.{hestia_machine}.hu (this two are the default Hestia NS) and ns.whatever.com (this is a backup NS from other company). If he using the default.tpl template, everything is fine, .hu Registry accepts it by technical, because it has a backup NS in a different location. But, if he using Google Workspace or Office365 for emailing and he changes the template to gmail.tpl or office365.tpl, .hu Registry refuses the domain, because these templates has burned-in nameservers and custom NS records are not included by default, so it must be fixed manually by adding external backup NS to the records. (I know, it also could be solved by writing custom templates for this cases, but the customers still can select the "wrong" templates in this case, so this kind of workaround is not that practical).

The problem can be solved, if we change these two lines in additional DNS templates...:

```
ID='1' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns1%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='2' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns2%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
```

...to this (copy-pasted from default.tpl):

```
ID='1' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns1%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='2' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns2%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='3' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns3%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='4' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns4%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='5' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns5%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='6' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns6%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='7' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns7%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='8' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns8%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
```

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
I like your idea.
I did my custom template and then I had no problems.

What I would suggest is to divide the templates so they affect web, ns and mail independently.

So you can choose from a DNS template your ns rules and the A rules relevant to DNS

From Mail template the Gmail config or the hestia default config

From a web template...

**Comment by jaapmarcus** [comment]
child-ns  has as name servers:

```ID='1' RECORD='@' TYPE='NS' PRIORITY='' VALUE='ns1.%domain%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='2' RECORD='@' TYPE='NS' PRIORITY='' VALUE='ns2.%domain%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
```

As the old mail templates has 

```
ID='1' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns1%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
ID='2' RECORD='@' TYPE='NS' PRIORITY='' VALUE='%ns2%.' SUSPENDED='no' TIME='%time%' DATE='%date%'
```

It is smart to bring the behaviour for non ns-clild template in lien with default. So I will change it..

I am not a fan for full rewrite of the DNS template system

As the only thing that is changes is by default the mail server it doesn't make sense to overwrite to some thing different
