### ISSUE TITLE
From email address on PHP form submission

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2372]
Hi team, Im using hestiacp for past ~5 years. Everything work great.

- Latest Hestia v.1.5.4
- Ubuntu 20x
- Just installed fresh hestiacp

I just installed a new server with fresh hestia installation. Seems the latest PHPMAILER function (OR) may EXIM configs not like previous versions.

If i send PHP form submission with from email headers defined, the recieved email shows always from web hosting account's admin email. Not followint the defined from email inside my php send file. This is the same file im using on the old server, it follows the defined FROM address but not this new server.

How to replicate:
- Use any php form submission with below 
- $header .= "From: online@domain.com";  // I auto forwarded this mail to my personal GMAIL
- Check your GMail - it shows the from address as
'admin@domain.com' instead ' online@domain.com' defined in this php form headers.

- The same domain with same form works as expected but not this new server

Am I missing missing something plz..?

**Comment by ScIT-Raphael** [comment]
Please use our forum or discord for support requests.
https://forum.hestiacp.com/
