### ISSUE TITLE
[Bug] Error: Let's Encrypt validation status 400 . Details: Unable to update challenge :: authorization must be pending

### ISSUE THREAD

**Issue by rooteto** [hestiacp/hestiacp#2376]
### Describe the bug

I installed hestiacp.
I installed all the sites on the server and activated the ssl certificates.
there is no problem.
Nginx was installed on the server. The next day I uninstalled nginx.

SSL certificate expired 3 months and did not auto-renew.
+ I deleted the certificate, tried to install it again, it gave an error.
+ I tried to re-install over SSH, it gave an error.

I couldn't solve the problem.

![image](https://user-images.githubusercontent.com/3899331/150838699-c4526149-fc2e-400a-a375-f1c0538d87ef.png)
![image](https://user-images.githubusercontent.com/3899331/150838795-7b6500bb-cafe-4663-9123-abf19c61036c.png)

### Tell us how to replicate the bug

Error: Let's Encrypt validation status 400 (servername.com). Details: Unable to update challenge :: authorization must be pending

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

  v1.5.4	

### Operating system

18.04 (x86_64)

### Log capture

```shell
cat /var/log/hestia/LE-servername.com.log

==[API call]==
exit status: 0


==[Step 5]==
- status: 400
- nonce: 0101K1dzHD3mPzxfsqQgy6g6PYBUIPgmloqkeZ_R6irH5uE
- validation:
- details: Unable to update challenge :: authorization must be pending
- answer: HTTP/2 400
server: nginx
date: Mon, 24 Jan 2022 17:58:10 GMT
content-type: application/problem+json
content-length: 144
boulder-requester: 248223580
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0101K1dzHD3mPzxfsqQgy6g6PYBUIPgmloqkeZ_R6irH5uE

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Unable to update challenge :: authorization must be pending",
  "status": 400
}


==[Abort Step 5]==
=> Wrong status
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/2363

**Comment by jaapmarcus** [comment]
1. Please use the search function Error code 400 has been handled 100x

https://docs.hestiacp.com/admin_docs/web/ssl_certificates.html#error-let-s-encrypt-validation-status-400
https://forum.hestiacp.com/search?q=400
https://github.com/hestiacp/hestiacp/issues?q=is%3Aissue+400+is%3Aclosed

2.  For support questions please use our forum. Github is only to be used for bugs that are caused by the software and not probably in this case by user error.
