### ISSUE TITLE
FR: Cloudflare Implementation

### ISSUE THREAD

**Issue by xXKynarethXx** [hestiacp/hestiacp#238]
Hi,
I am using CF to manage the DNS stuff for my domains.
It would be really cool if there was the option to handle DNS stuff via CF, the API is very well documented and it would be a cool thing for the future, when CF is going to be the cheapest domain registrar (they are going to sell domains at self cost).
I know this is a golden faucet feature, but there are a lot of CF users out there!

Have a nice one ;)

**Comment by ghost** [comment]
Hi @xXKynarethXx,
Thanks for your feedback - I'll discuss this further with the team and provide an update as soon as I have more information for you. :)

**Comment by ghost** [comment]
Hi again @xXKynarethXx,
After an internal discussion, we've decided not to support Cloudflare DNS at this time, however this may be reconsidered for a future release if there's enough demand for it.

Thanks again for your feedback and have a great day.
