### ISSUE TITLE
[Bug] error during install 1.5.5

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#2381]
### Describe the bug

During the process:

[ * ] Configuring system settings...
Created symlink /etc/systemd/system/dbus-org.freedesktop.timesync1.service → /lib/systemd/system/systemd-timesyncd.service.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service → /lib/systemd/system/systemd-timesyncd.service.
[ * ] Configuring Hestia Control Panel...
[ * ] Generating default self-signed SSL certificate...
[ * ] Adding SSL certificate to Hestia Control Panel...
[ * ] Enable SFTP jail...
[ * ] Configuring NGINX...
[ * ] Install PHP 5.6...
[ * ] Install PHP 7.0...
[ * ] Install PHP 7.1...
[ * ] Install PHP 7.2...
[ * ] Install PHP 7.3...
[ * ] Install PHP 7.4...
[ * ] Install PHP 8.0...
[ * ] Install PHP 8.1...
[ * ] Configuring PHP 8.0...
[ * ] Configuring PHP...
[ * ] Configuring Vsftpd server...
[ * ] Configuring MariaDB database server...
[ * ] Installing phpMyAdmin version v5.1.2...
[ * ] Configuring Exim mail server...
[ * ] Installing ClamAV anti-virus definitions...|
[ * ] Configuring fail2ban access monitor...
[ * ] Install Roundcube...
[ * ] Configuring System IP...
Error: WEB_ALIASES limit is reached :: upgrade user package
Error: can't create domain.domain.com domain

And install stop totally... I am not able to proceed

### Tell us how to replicate the bug

bash hst-install.sh --apache no --phpfpm yes --multiphp yes \
--vsftpd yes --proftpd no --named no \
--mysql yes --postgresql no \
--exim yes --dovecot no \
--clamav yes --spamassassin no \
--iptables yes --fail2ban yes \
--quota no --port 6660 \
--email myemail@gmail.com --force yes

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.5.5

### Operating system

Debian 10

**Comment by arielesp** [comment]
How to install older version!? I need setup my server =(

**Comment by jaapmarcus** [comment]
We are working on 1.5.6 and release a patch shortly

**Comment by jaapmarcus** [comment]
Issue has been resolved. Please  try again!
