### ISSUE TITLE
Issues during upgrades

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2382]
With the release of 1.5.5 we introduced 1 major bug causing to break auto updates for affected servers!

If you have updated from 1.5.4 or before directly to 1.5.7 you should **not** be affected!

If you have installed 1.5.5 or 1.5.6 follow the follow in steps you are not able to run apt update anymore with out an error!

Run the following command to solve it:

```
rm /usr/share/keyrings/hestia-keyring.gpg
mkdir /root/.gnupg/
gpg --no-default-keyring --keyring /usr/share/keyrings/hestia-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A189E93654F0B0E5

# run apt update
apt update && apt upgrade
```

**Comment by gejobj** [comment]
Hi jaapmarcus, thanks for advice ^_^

I upgraded from 1.5.3 to 1.5.7 with no errors but I found this warning:
`gpg: WARNING: Insecure permissions on homedir '/root/.gnupg'`
I thought '/root/.gnupg' should have 700 permissions instead of 755.

Thanks!

--- LOG ---
```
[ - ] Now applying patches and updates for version v1.5.5...
[ * ] Updating apt keyring configuration...
   [ * ] NGINX
gpg: WARNING: unsafe permissions on homedir '/root/.gnupg'
   [ * ] MariaDB
gpg: WARNING: unsafe permissions on homedir '/root/.gnupg'
   [ * ] Hestia
[ * ] Install default system package.
```

**Comment by jaapmarcus** [comment]
> Hi jaapmarcus, thanks for advice ^_^
> 
> I upgraded from 1.5.3 to 1.5.7 with no errors but I found this warning: `gpg: WARNING: Insecure permissions on homedir '/root/.gnupg'` I thought '/root/.gnupg' should have 700 permissions instead of 755.
> 
> Thanks!
> 
> --- LOG ---
> 
> ```
> [ - ] Now applying patches and updates for version v1.5.5...
> [ * ] Updating apt keyring configuration...
>    [ * ] NGINX
> gpg: WARNING: unsafe permissions on homedir '/root/.gnupg'
>    [ * ] MariaDB
> gpg: WARNING: unsafe permissions on homedir '/root/.gnupg'
>    [ * ] Hestia
> [ * ] Install default system package.
> ```

Yeah that is the issue. How ever we will resolve it for next release. How ever it should be working...

We will fix the issue next release..  3 releases on 1 day is to much allready :)

**Comment by EmsTatay** [comment]
1.5.5 no further upgrades possible due to missing KEY in keyring...
Well, 
seems I got impacted by this too... MY version of the above solution includes a quick fix for the permissions... in case you like to cut and paste... ;-)

rm /usr/share/keyrings/hestia-keyring.gpg
mkdir /root/.gnupg/
chmod -R 600 /root/.gnupg/
gpg --no-default-keyring --keyring /usr/share/keyrings/hestia-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A189E93654F0B0E5

**Comment by jaapmarcus** [comment]
During the few hours 700 servers where updated

**Comment by EmsTatay** [comment]
SORRY @jaapmarcus, I should have opened my comment with THANK YOU for a prompt FIX!!!
You had it posted here before I got my error eMails... so it took me only a few ssh sessions to correct and some servers had not yet updated (so they jumped to 1.5.7 nicely!)
MY comment was more intended to offer the additional "fix" for @gejobj  - directory being too permissive...

THANKS also for this fork! Much more active than the original (shame as the intention was good!)...

**Comment by gejobj** [comment]
Hi @EmsTatay,

I thought 600 permissions for all files and folders inside '.gnupg' it's wrong (chmod -R 600 /root/.gnupg/).
Files inside '.gnupg' should be 600 and folders should be 700.
I have searched several web pages and they all agree that the permissions of the '.gnupg' should be 700:
- https://askubuntu.com/questions/330755/unsafe-permissions-on-configuration-file-home-david-gnupg-gpg-conf-what-doe
- https://gist.github.com/oseme-techguy/bae2e309c084d93b75a9b25f49718f85
- https://superuser.com/questions/954509/what-are-the-correct-permissions-for-the-gnupg-enclosing-folder-gpg-warning

The last link has the best explanation about this issue.

Best regards.

**Comment by ifaist0s** [comment]
Hi @jaapmarcus 
I followed your instructions on a server and I get the following:

`rm /usr/share/keyrings/hestia-keyring.gpg` = OK
`mkdir /root/.gnupg/` = mkdir: cannot create directory ‘/root/.gnupg/’: File exists
`gpg --no-default-keyring --keyring /usr/share/keyrings/hestia-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A189E93654F0B0E5` = 
gpg: keybox '/usr/share/keyrings/hestia-keyring.gpg' created
gpg: keyserver receive failed: No such file or directory

Directory `/root/.gnupg` and subdirectories have 0700 permissions.
Directory `/root/.gnupg` contains:
1. Directory `crls.d` with one file `DIR.txt`
2. Directory `private-keys-v1.d` which is empty

The command `apt update` still produces the error: `W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.hestiacp.com bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5`

**Comment by jaapmarcus** [comment]
rm /root/.gnupg and then try again?

**Comment by ifaist0s** [comment]
Note: Problem resolution at section **EDIT v2** below.

Well yes, that's obvious :) Though I have no idea what problems I could cause by deleting a NON-empty directory tree. Anyway, I renamed it, started from scratch and here is the result of the last command:
```
gpg: WARNING: unsafe permissions on homedir '/root/.gnupg'
gpg: keybox '/usr/share/keyrings/hestia-keyring.gpg' created
gpg: keyserver receive failed: No such file or directory

```
By the way: DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS" Hetzner Cloud

EDIT: Some more debug info.
```
gpg -vvv --debug-all --no-default-keyring --keyring /usr/share/keyrings/hestia-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A189E93654F0B0E5
gpg: Note: no default option file '/root/.gnupg/gpg.conf'
gpg: using character set 'utf-8'
gpg: enabled debug flags: packet mpi crypto filter iobuf memory cache memstat trust hashing ipc clock lookup extprog
gpg: DBG: [not enabled in the source] start
gpg: DBG: chan_3 <- # Home: /root/.gnupg
gpg: DBG: chan_3 <- # Config: [none]
gpg: DBG: chan_3 <- OK Dirmngr 2.2.4 at your service
gpg: DBG: connection to the dirmngr established
gpg: DBG: chan_3 -> GETINFO version
gpg: DBG: chan_3 <- D 2.2.4
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KEYSERVER --clear hkp://keyserver.ubuntu.com:80
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KS_GET -- 0xA189E93654F0B0E5
gpg: DBG: chan_3 <- ERR 167805009 No such file or directory <Dirmngr>
gpg: keyserver receive failed: No such file or directory
gpg: DBG: chan_3 -> BYE
gpg: DBG: [not enabled in the source] stop
gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=0 cached=0 good=0 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/65536 bytes in 0 blocks

```
**EDIT v2**: The discussion at https://bbs.archlinux.org/viewtopic.php?id=252494 was helpful. It seems I had an issue with `/etc/resolv.conf`. After fixing it, and running the gpg command again, it succeded 👍

**Comment by wungad** [comment]
I suggest either to put add  the correct procedure to [documentation site](https://docs.hestiacp.com/release_notes/1.5.7.html) or create a a link pointing to into linking the solution to the [first post in this issue](https://github.com/hestiacp/hestiacp/issues/2382#issue-1116271251)
Currently it looks like someone's been cut off just when it was about time to show the commands:

> Follow the following instructions
  After that run apt update && apt upgrade

I would do this myself but it seems that docs are not present in this repository.

**Comment by jaapmarcus** [comment]
Only a "limited" number of users are affected (About +/-700 installs) out of 15k installs and probably most should have seen the issue by now.

The number of issues reported via Discord and Forum are quite small..

**Comment by grajales666** [comment]
Thanks, work for my 1.5.7 version.
