### ISSUE TITLE
[Bug] Unable to install hestia 

### ISSUE THREAD

**Issue by capripio** [hestiacp/hestiacp#2385]
### Describe the bug

When I tried to install I get following error message:

[ * ] NGINX
[ * ] PHP
[ * ] Apache2
[ * ] MariaDB
[ * ] Hestia Control Panel
[ * ] PostgreSQL

Updating currently installed packages, please wait... 
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait...
-
**Error: apt-get install failed**

When I tried to run apt-get update I get following error:

root@ji:~# apt-get update
Hit:1 http://ppa.launchpad.net/ondrej/apache2/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 https://nginx.org/packages/mainline/ubuntu focal InRelease
Hit:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
Hit:5 https://mirror.mva-n.net/mariadb/repo/10.6/ubuntu focal InRelease
Get:6 https://apt.hestiacp.com focal InRelease [3,599 B]
Hit:7 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:8 https://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease
Hit:9 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:10 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Err:6 https://apt.hestiacp.com focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5
Reading package lists... Done
W: GPG error: https://apt.hestiacp.com focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5
E: The repository 'https://apt.hestiacp.com focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Tell us how to replicate the bug

1. Install Hestia.

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.5.5

### Operating system

Ubuntu 20.04

### Log capture

```shell
Package setpriv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  util-linux:i386 util-linux

E: Package 'apache2.2-common' has no installation candidate
E: Package 'php-opcache' has no installation candidate
E: Unable to locate package rssh
E: Unable to locate package hestia
E: Unable to locate package hestia-nginx
E: Unable to locate package hestia-php
E: Package 'setpriv' has no installation candidate
```

**Comment by gejobj** [comment]
Please, read this: https://github.com/hestiacp/hestiacp/issues/2382
It seems that it is your case.
Best regards.

**Comment by jaapmarcus** [comment]
mkdir /root/.gnupg/
chmod 700 /root/.gnupg/

And then try to install it...

**Comment by jaapmarcus** [comment]
Issue should be fixed we have addd the .gnupg folder to the root folder
