### ISSUE TITLE
[Feature] Add CakePHP to Nginx templates

### ISSUE THREAD

**Issue by miftygusein** [hestiacp/hestiacp#2389]
### Describe the feature or change in detail

Hi everyone,

The [Nginx Template](https://github.com/hestiacp/hestiacp/tree/master/install/deb/templates/web/nginx) dropdown at HestiaCP → Users → Packages → Add → Web → Web Template NGINX is missing CakePHP. 

Here's an example of the config CakePHP is expecting: https://book.cakephp.org/4/en/installation.html#nginx

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Feel free to submit a pull request with the working template

https://docs.hestiacp.com/admin_docs/web.html#how-do-web-templates-work
