### ISSUE TITLE
[Bug] Domain suspend not working with proxy_pass

### ISSUE THREAD

**Issue by Hexaris** [hestiacp/hestiacp#2405]
### Describe the bug

If I use a template where proxy_pass + location / is used, suspend for domains stops working. I assume that this is not a HCP bug, but nginx seems to work like this and the suspend content in root is ignored. 

### Tell us how to replicate the bug

Create own template with proxy_pass or use gitea template (example).

### Which components are affected by this bug?

Backend Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.5.7

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
> 21:54] Jaap Marcus: You mean when you suspend web domain?
>[21:55] Hexaris: yes
>[21:57] Jaap Marcus: It changes the doc root to  root        /usr/local/hestia/data/templates/web/suspend;
>[21:58] Jaap Marcus: So no wonder it will not work for  proxy_pass
>[21:59] Jaap Marcus: To fix the issue we would probally update the template to suspended.tpl or something like that
>[21:59] Jaap Marcus: If we want to solve it ...
>[21:59] Jaap Marcus: Please create an bug report ...

**Comment by jaapmarcus** [comment]
Fixed
