### ISSUE TITLE
[Bug] Broken mirror of MariaDB repository specified 

### ISSUE THREAD

**Issue by click0** [hestiacp/hestiacp#2414]
### Describe the bug

In the logs I get errors with apt-update: :
```
Err:9 https://mirror.mva-n.net/mariadb/repo/10.6/debian bullseye Release
  404  Not Found [IP: 195.65.111.42 443]
Reading package lists... Done
E: The repository 'https://mirror.mva-n.net/mariadb/repo/10.6/debian bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

https://github.com/hestiacp/hestiacp/blob/04a6c5c5aff3da8531018fbb438ea064f0fe3e2c/install/hst-install-debian.sh#L721

### Tell us how to replicate the bug

1. Run the panel installation in the console.
2. Run `apt-get update` command 

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.5.7

### Operating system

Debian 11.2

**Comment by ScIT-Raphael** [comment]
Known issue, we currently wait for a fix on repo side, this is out of hestias range. see https://forum.hestiacp.com/t/e-the-repository-https-mirror-mva-n-net-mariadb-repo-10-4-ubuntu-focal-release-no-longer-has-a-release-file/5550

**Comment by ScIT-Raphael** [comment]
The issue has been resolved, all is working properly here.

**Comment by ScIT-Raphael** [comment]
UPDATE: 10.3 and 10.4 are working properly, 10.5 and 10.6 are still buggy. We’re monitoring the situation.

**Comment by jaapmarcus** [comment]
Issue should be solved if you have still issues change /etc/apt/sources.list.d/mariadb.list to 

`deb [arch=$ARCH signed-by=/usr/share/keyrings/mariadb-keyring.gpg] https://dlm.mariadb.com/repo/mariadb-server/$mariadb_v/repo/$VERSION $codename main`

$arch, $version, $codename an mariadb_v can be taken from the old file name

**Comment by click0** [comment]
Almost all mirrors of MariaDB repositories return 404 over IPv6... 
```
Err:9 https://ftp.nluug.nl/repo/mariadb-server/10.6/repo/debian bullseye Release
  404  Not Found [IP: 2001:67c:6ec:221:145:220:21:40 443]
Reading package lists... Done
E: The repository 'https://ftp.nluug.nl/repo/mariadb-server/10.6/repo/debian bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
