### ISSUE TITLE
[Bug] SSL cannot be updated automatically

### ISSUE THREAD

**Issue by 810drawing** [hestiacp/hestiacp#2417]
### Describe the bug

I have set Encrypt SSL, but I cannot update automatically.
Would you please allow it to be updated automatically?

### Tell us how to replicate the bug

I tried it.
https://chee-s.net/ubuntu%E3%81%A7lets-encrypt%E3%81%AE%E7%84%A1%E6%96%99ssl-tls%E3%82%B5%E3%83%BC%E3%83%90%E8%A8%BC%E6%98%8E%E6%9B%B8%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.5.7

### Operating system

Debian11

**Comment by jaapmarcus** [comment]
Use v-add-letsencrypt-domain user domain

To update run v-update-letsencrypt-ssl

It should do it as a daily update . There is no need to use Certbot....
