### ISSUE TITLE
[Bug] Error calling domain

### ISSUE THREAD

**Issue by AZI47249** [hestiacp/hestiacp#2425]
### Describe the bug

I have freshly installed your panel and all port releases are given.
I added my domain and all dns entries are also available and functional.
If I call up the domain locally on the server via my browser, it shows me the standard generated design and is accessible.
When I access the site from the internet, it gives me the error code:
DNS_PROBE_FINISHED_NXDOMAIN

why is that?

I hope you can help me

### Tell us how to replicate the bug

I added my domain and all dns entries are also available and functional.
If I call up the domain locally on the server via my browser, it shows me the standard generated design and is accessible.
When I access the site from the internet, it gives me the error code:
DNS_PROBE_FINISHED_NXDOMAIN

### Which components are affected by this bug?

Backend Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.5.8

### Operating system

Ubuntu 20.04 (x86_64)

**Comment by ScIT-Raphael** [comment]
That's a dns lookup issue you got there which isnt a hestia bug. Make sure your dns is working properly, for support, please use our forum or discord.
