### ISSUE TITLE
[Feature]: Install Percona Server for MySQL (5.7) instead of MariaDB 

### ISSUE THREAD

**Issue by click0** [hestiacp/hestiacp#2428]
### Describe the feature or change in detail

I don't like using either MariaDB or vanilla Mysql.
Is it necessary to write pull requests to install Percona Server for MySQL (5.7)?
Or is there a need to choose two versions of Percona Server for MySQL 5.7 and 8.0?
I have developments (scripts) for Debian 9, 10, 11, but do I need to support Ubuntu? 
Which version of Ubuntu should be supported? 

P.S. I read a similar [issue](https://github.com/hestiacp/hestiacp/issues/821). 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We don't have plans to add support for a 3rd database engine currently and in the future. 

We are currently enough time to keep supporting everything in the future.

Off course you can create a fork of Hestia and make the changes that are required or just write the custom installers for it.

**Comment by mehargags** [comment]
Percona is drop-in replacement for MySQL/MariaDB... I have not tried myself on HestiaCP but I did install Percona on VestaCP/Debian 8 long time ago, worked like a charm, atleast if you don't have webmail dependent on your MySQL, it should work.
