### ISSUE TITLE
[Feature] Discuss raising LimitNOFILE for Nginx

### ISSUE THREAD

**Issue by kpapad904** [hestiacp/hestiacp#2431]
### Describe the feature or change in detail

Summarizing the solution provided by u/jtraulle about getting 400 errors when attempting to issue Let’s Encrypt certificates, on a server with Debian 10 and HestiaCP 1.5.7 hosting 222 web domains (190 ssl):

> Installed nginx-dbg, added the debug directive to the error_log and started it after having stopped nginx. And I figured it out ! nginx issued an emerg notice that I havent noticed before :
> 
> `2022/02/21 15:04:38 [emerg] 51772#51772: open() "/var/log/apache2/domains/<redactedforprivacy>.error.log" failed (24: Too many open files)`
>
> After digging around, find out how to increase it :
> 
> systemctl edit --full nginx.service
>
> and add the following line to the [Service] section:
> 
> LimitNOFILE=65536
>
> And now reloading is working as expected, no more need to restart nginx!
>
> Src: https://forum.hestiacp.com/t/problem-with-reloading-nginx-config-lets-encrypt/5478/7

There are three files where LimitNOFILE can be defined:
1. /etc/security/limits.conf
2. /etc/systemd/system.conf (1024:524288)
3. nginx.service

Note: File /etc/security/limits.conf sets the resource limits for the users logged in via PAM. It does not affect resource limits of the system services. If a program starts via systemctl then edit /etc/systemd/system.conf or its service file (nginx.service).

### Would you like to sponsor this feature to have it implemented?

No

**Comment by kpapad904** [comment]
For reference, more info about the same issue:

> For nginx simply editing nginx.conf and setting worker_rlimit_nofile should change the limitation
> 
> `worker_rlimit_nofile 4096;`
> 
> on ubuntu 20.04, if worker_rlimit_nofile > LimitNOFILE, the max openfile is equal to worker_rlimit_nofile value

> Create file `/etc/systemd/system/nginx.service.d/override.conf` with the following contents:
> ```
> [Service]
> LimitNOFILE=65536
> ```
> Reload systemd daemon with:
> `systemctl daemon-reload`
> 
> Add this to Nginx config file:
> `worker_rlimit_nofile 16384; (has to be smaller or equal to LimitNOFILE set above)`
> 
> And finally restart Nginx:
> `systemctl restart nginx`
> 
> You can verify that it works with `cat /proc/<nginx-pid>/limits`.
> 
> https://stackoverflow.com/questions/27849331/how-to-set-nginx-max-open-files/36423859#36423859

**Comment by ScIT-Raphael** [comment]
Personaly, I don't think we should raise that limit on every system by default - more than 200 different webdomains is basicly "a lot". I tend to adjust either the docs, or maybe only higher the limit, if there is a need for it - probaly set a counter for 200 domains or similar. What do you think about it?

**Comment by jaapmarcus** [comment]
I have added a comment regarding this issue to our docs.
