### ISSUE TITLE
IMAP problem?

### ISSUE THREAD

**Issue by hqin2013** [hestiacp/hestiacp#2438]
Hi,

I used hestica as email server, for IMAP connection, get the error: SSL routines:ssl3_get_record:wrong version number

https://prnt.sc/YqmO8DgJVf-3

Debian 11 x 64
anything suggestion? thx

**Comment by ScIT-Raphael** [comment]
Please use our forum or discord for support requests, github is for reproducable issue and bug reports only.

**Comment by ScIT-Raphael** [comment]
Also, port 143 isnt a valid asl port, you want to probaly check that.
