### ISSUE TITLE
[Bug] install issue

### ISSUE THREAD

**Issue by mr-buffy** [hestiacp/hestiacp#2439]
### Describe the bug

Trying to install on a Debian 11.2 VM and it seems to be stalled, see below

E: The repository 'cdrom://[Debian GNU/Linux 11.2.0 _Bullseye_ - Official amd64 DVD Binary-1 20211218-11:13] bullseye Release' does not have a Release file.
[ * ] Installing dependencies...

Been like this for an hour

### Tell us how to replicate the bug

running the installer: bash hst-install.sh

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.5.8

### Operating system

Debian  11

**Comment by ScIT-Raphael** [comment]
This is not a hestia related issue, your sources.list still contains your cdrom. Please adjust your list file, remove that line and check if you need to add public repos for your os. Infact this is a support request, please consider to use forum or discord for future requests, github is for reproducable issues and bugs only.
