### ISSUE TITLE
[Bug] "Error" Adding database 

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2444]
### Describe the bug

When adding a new "App" via Quick installer and the DB limit is set 0 or DB count = limit adding a new database results in:

![image](https://user-images.githubusercontent.com/9754650/156262500-1d43693e-28e6-44ce-b6a1-db49fe13b4bb.png)

### Tell us how to replicate the bug

- Add new package with 0 DB or use "system" package
- Add web domain 
- Use Quick installer 

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.9

### Operating system

N/A

### Log capture

```shell
See screenshot
```

**Comment by fishermanG** [comment]
Same here. Any solutions to this yet?

**Comment by jaapmarcus** [comment]
Don't use admin user!

And create a new user....

**Comment by jaapmarcus** [comment]
Issue has been resolved
