### ISSUE TITLE
Manual Backup Error[Bug] 

### ISSUE THREAD

**Issue by medsaif95** [hestiacp/hestiacp#2448]
### Describe the bug

When i make backup manually , get this error 
Error: invalid user format :: 'admin'
Error: invalid user format :: 'med'

on both of my servers 

### Tell us how to replicate the bug

backups ->create backup
Error: invalid user format :: 'admin'

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.9

### Operating system

ubntu 20

**Comment by jaapmarcus** [comment]
See 
https://github.com/hestiacp/hestiacp/pull/2449
