### ISSUE TITLE
[Bug] v-add-database-host error: pgsql type is invalid

### ISSUE THREAD

**Issue by fishnux** [hestiacp/hestiacp#2450]
### Describe the bug

Can't add PostgreSQL server to existing MariaDB-based HestiaCP installation
Attempted to install PostgreSQL by manually following what Hestia's install script does

### Tell us how to replicate the bug

```
v-add-database-host pgsql 8.8.8.8 abc abc
```

### Which components are affected by this bug?

Control Panel Command Line Interface, Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.5.9

### Operating system

Ubuntu 20.04

### Log capture

```shell
Error: pgsql type is invalid
```

**Comment by jaapmarcus** [comment]
We run write_config_value "DB_SYSTEM" "$db"  during the installer phase... 

https://github.com/hestiacp/hestiacp/blob/0e0ccd4f311cef96885023ad24ea8caf78e0f4d3/install/hst-install-ubuntu.sh#L1179-L1186

To solve the issue 

Adjust /usr/local/hestia/conf/hestia.conf and adjust DB_SYSTEM from

DB_SYSTEM='mysql' to 

DB_SYSTEM='mysql,pgsql'
