### ISSUE TITLE
[Bug] Database creation interface typos (wrong quotes and underscore)

### ISSUE THREAD

**Issue by ww7** [hestiacp/hestiacp#2454]
### Describe the bug

![](https://i.imgur.com/crTA8Rq.png)
![](https://i.imgur.com/ojiV9UV.png)

### Tell us how to replicate the bug

Create database

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.9

### Operating system

Ubuntu 20.4

**Comment by ScIT-Raphael** [comment]
Please upgrade to our staging version of 1.5.10, you can download and install the package entering the following command:

`v-update-sys-hestia-git hestiacp staging/1.5.10`

Let us know, if this fixed your issue.

**Comment by jaapmarcus** [comment]
Noticed should been fixed today :)

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/2453/commits/640f822d306ffb3eddf8ce2f46de75d7344283c1

**Comment by ww7** [comment]
Thanks

**Comment by jaapmarcus** [comment]
Thanks anyway:

https://camo.githubusercontent.com/dc0b89d7541d66064b093023c2d6230b5c25cdef7a586ba09a25c0ae573edbf8/68747470733a2f2f692e696d6775722e636f6d2f6f6a69563955562e706e67

Missed this one ...
