### ISSUE TITLE
Hello i am not able to instal msql via PUTTY in my vpn server

### ISSUE THREAD

**Issue by raolkashyap** [hestiacp/hestiacp#2456]
### Describe the bug

Hello i am not able to instal msql via PUTTY in my vpn server can you help

### Tell us how to replicate the bug

Hello i am not able to instal msql via PUTTY in my vpn server can you help

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Installation or Upgrade

### Hestia Control Panel Version

18.04

### Operating system

Ubuntu 18.04 with HestiaCP

**Comment by ScIT-Raphael** [comment]
We expect to install hestia on a clean server without any existing software on it. Also github is for issue tracking only, so I'll close your issue. Usualy I would tell here to switch over to forum or discord, but your case doesnt seems to be really related to hestia.
