### ISSUE TITLE
Google drive [Feature] 

### ISSUE THREAD

**Issue by mariojgt** [hestiacp/hestiacp#2457]
### Describe the feature or change in detail

Is possible to have integration with google drive for backups ?

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
As far as I can see the projects of connectors with Google drive over ftp and SCP are abandoned so it will be difficult to push files to drive.

Is there a way to have Google Drive pull the files from hestiacp?

The API way seems complicated

https://developers.google.com/drive/api/v3/manage-uploads#resumable

**Comment by mariojgt** [comment]
i use https://rclone.org/ on my server with hestia cp does have a lot of connector using S3 protocol looks good and easy to integrate maybe is a s good this to have some king of bash script to automate this process.

**Comment by mehargags** [comment]
rclone is way more powerful and I don't know what exactly you are missing with it. I use it to sync to GDRIVE, ONEDRIVE and ofcourse S3 since lst 5 years. I takes less than 2 mins to script and setup on every server

**Comment by mariojgt** [comment]
i see i have set up to on my server is really easy to use i was just a idea to have like a section the the web panel to help with a automated process using bash script.

**Comment by jaapmarcus** [comment]
It is open source. Feel free to submit a PR 

We don't have currently enough time...

**Comment by mariojgt** [comment]
No problem i will check if i can understand properly how to create a integration.

**Comment by kpapad904** [comment]
I just wanted to say that any HestiaCP support of cloud drives should be via Rclone (aka "rsync for cloud storage").

Probably the best combination for HestiaCP backups would be BorgBackup and then copying the repo(s) to cloud (GoogleDrive, OneDrive, Amazon S3, Backblaze B2 etc) via Rsync.

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/issues/158
