### ISSUE TITLE
[Bug] PHPMailer is still using v6.5.3 instead of v6.6.0

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2458]
### Describe the bug

![image](https://user-images.githubusercontent.com/39749258/156832447-cc8d9b21-4743-467d-900f-cd0c58675620.png)

### Tell us how to replicate the bug

take a backup or create a new ftp/db and send those details to email

### Which components are affected by this bug?

Control Panel Backend, Mail (Exim, Dovecot), Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.5.10

### Operating system

Ubuntu 20.04

### Log capture

```shell
Screenshot
```

**Comment by jaapmarcus** [comment]
See #2459
