### ISSUE TITLE
[Bug]  Backup zstd not working 

### ISSUE THREAD

**Issue by baxterdmutt** [hestiacp/hestiacp#2461]
### Describe the bug

The backup compression is set to zstd but the created backup file is a tarball file. If tried changing and even increased compression past 10 and still a tar glue is created. 

### Tell us how to replicate the bug

Creating cron backups 

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.10

### Operating system

Debian 10.11

**Comment by jaapmarcus** [comment]
Tge final output file is still an tar how ever if you open the tar file you see that domain, database and mail accounts are compressed using zest

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/046a8f9e47807c747b04542bf57938f8a9698034/bin/v-backup-user#L387-L392

**Comment by baxterdmutt** [comment]
Ok I’m still confused because the code says if the mode is zstd, so then the file will be whatever.tar.zst but my files are whatever.tar Why is my file  not tar.zst if that what the code says.  And where is the compression level set. Doesn’t there need to be a CLEVEL=9 or whatever switch set.

**Comment by jaapmarcus** [comment]
Open the first tar file...

If you extract the tar files:
<img width="352" alt="Screenshot 2022-03-06 at 06 36 17" src="https://user-images.githubusercontent.com/9754650/156910716-3367905a-05c5-42a7-bd06-49594d3eea71.png">
<img width="302" alt="Screenshot 2022-03-06 at 06 36 02" src="https://user-images.githubusercontent.com/9754650/156910717-6d7eab13-f24c-4526-884c-d64dc708a79b.png">
 You will see the folders + compressed files 

Final "tar" file compressed saves about 1%  as only the config files are left...

**Comment by baxterdmutt** [comment]
Oh. Ok now I understand. It’s compressed into a ZST and then combined into a tar. Thanks. Sorry for my confusion.
