### ISSUE TITLE
[BUG] PrestaShop Install Script   Error: "install" directory is missing

### ISSUE THREAD

**Issue by petrus9** [hestiacp/hestiacp#2467]
### Describe the bug

Also see: https://forum.hestiacp.com/t/prestashop-quick-install-app-error-install-directory-is-missing/5765?u=petrushka

setup domain  with SSL

Install PrestaShop Quick install

see the following message:  (Even though the directory is empty)

> 'Data loss warning!
> Your web domain already has files uploaded, the installer will overwrite your files and/or the installation might fail.
> 
> Please use the installer only for empty web domains'

When I go to my to my URL I see the following:

`Error: "install" directory is missing`

### Tell us how to replicate the bug

1. Click on  Quick install App on any domain panel 
2.  click on setup for the PrestaShop App

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.5.10

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Haven't been able to "Find" the  issue:

We delete the install dir in code so the error doesn't surprise me...

https://github.com/hestiacp/hestiacp/blob/20912d7de7e94680018e533cdb8de791fdd1686e/web/src/app/WebApp/Installers/Prestashop/PrestashopSetup.php#L55-L71

How ever there should be a reason why the code before the deletion fails. 

When an install fails the system should be able to return with an error instead of "Nothing" ...

**Comment by jaapmarcus** [comment]
What is the php version do you have? So far I can remember Prestashop has issues with certain php versions...

**Comment by jaapmarcus** [comment]
@petrus9  Please run preferable on a test server:

v-update-sys-hestia-git jaapmarcus fix/quick-installers 

And try again

**Comment by jaapmarcus** [comment]
Your server is running PHP 8.0.16, but PrestaShop requires PHP 7.4 or lower. To install PrestaShop 1.7.8.4 you need to downgrade your server's PHP version.
....

**Comment by petrus9** [comment]
> @petrus9 Please run preferable on a test server:
> 
> v-update-sys-hestia-git jaapmarcus fix/quick-installers
> 
> And try again

Is this a fix for all the installers or just for PrestaShop?

**Comment by jaapmarcus** [comment]
- Opencart 
- Drual 
- Docuwiki

Currently fixed

Prestashop has still some issues but at least I know how to solve them... 

MediaWiki not yet tested ...

**Comment by petrus9** [comment]
for   `v-update-sys-hestia-git jaapmarcus fix/quick-installers`

It looks like this updates HestiaCP to an Alpha version?  Or does it just update the quick installer code? I don't have a test server at the moment, but may be able to spin one up.

**Comment by jaapmarcus** [comment]
Yes it updates Hestia to the Alpha version + the changes for Quick installer

**Comment by petrus9** [comment]
@jaapmarcus I am just getting to testing this now,  Is ` v-update-sys-hestia-git jaapmarcus fix/quick-installers`  still valid or should I go with the latest build?

**Comment by jaapmarcus** [comment]
jaapmarcus fix/quick-installers  contains the above listed patches. 


It still need some rewrites to have some more options...

**Comment by petrus9** [comment]
@jaapmarcus Is there anything in particular you want me to test right now?

**Comment by jaapmarcus** [comment]
All the installers should work fine... 

Have a few more ideas to add some version detection when you select the app you want to install.. (For example 7.4 or lower missing for Prestashop)

**Comment by petrus9** [comment]
Yes, I noticed this kind of message. Thanks! Perhaps even have a message like that show up under the quick install logo of each app or pop up when you click on it.

**Comment by jaapmarcus** [comment]
I think we should "grey" out non supported apps

**Comment by petrus9** [comment]
agreed, with some messaging about what is needed to support them.

Or something more elegant way like this:  You click on the installer if the
required PHP version is not installed or set, you are asked if you want to
install and then the installer installs the required PHP version for you
and then installs the app.   I am not a coder and this may be more work
than its worth.
