### ISSUE TITLE
[BUG] Opencart Quick Install No Formatting (Not loading CSS)

### ISSUE THREAD

**Issue by petrus9** [hestiacp/hestiacp#2468]
### Describe the bug

see: https://forum.hestiacp.com/t/opencart-quick-install-no-formatting-not-loading-css/5762/10?u=petrushka

For the solution, 

### Tell us how to replicate the bug

1. enable SSL on a domain
2.  install OpenCart
3. navigate to URL 

### Which components are affected by this bug?

Backend Web Server (Nginx, Apache2)

### Hestia Control Panel Version

v1.5.10

### Operating system

Ubuntu 20.04

**Comment by jlguerrerosanz** [comment]
Will opencart work fine with ssl disabled if you define https in config.php?

**Comment by jaapmarcus** [comment]
No 

But we can add an check...

```
        $this->appcontext->run('v-list-web-domain', [$this -> appcontext->user(),$this -> domain,'json'], $status);
        if ($status->code !== 0) {
            throw new \Exception("Cannot list domain");
        }
        if ($status -> json[$this -> domain]['SSL'] == 'no') {
            $protocol = 'http://';
        } else {
            $protocol = 'https://';
        }
```
