### ISSUE TITLE
Let’s encrypt new auth status 429

### ISSUE THREAD

**Issue by raolkashyap** [hestiacp/hestiacp#2469]
### Describe the bug

i got this error in my one of the sub domain

https://svmmoh71.sarvhitkari.org/

can anyone tell me how to solve this i am tired from 3 days its not working 

### Tell us how to replicate the bug

i got this error in my one of the sub domain

https://svmmoh71.sarvhitkari.org/

can anyone tell me how to solve this i am tired from 3 days its not working 

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

18.04

### Operating system

Ubuntu 18.04 with HestiaCP

**Comment by ScIT-Raphael** [comment]
Please use the search function in https://forum.hestiacp.com

**Comment by raolkashyap** [comment]
i cant find anything there thats why i came here

**Comment by ScIT-Raphael** [comment]
There are plenty threads, basicly you run into the max request limit probaly due to prior LE400 errors: https://forum.hestiacp.com/search?q=429

Also the issue tracker here in discord is for bugs and issues only, please refrain for support to discord or forum.
