### ISSUE TITLE
[Bug] DokuWiki Quick Install  rendering with no formatting (CSS is being blocked) 

### ISSUE THREAD

**Issue by petrus9** [hestiacp/hestiacp#2470]
### Describe the bug

Install DokuWiki with Quick Install script.  
SSL not enabled (did not test with SSL enabled) 
DokuWiki renders without formatting. 

Expected:  Quick install script choses the right PHP version. 

### Tell us how to replicate the bug

1. Install DokuWiki via Quick Install Script
2.  DokuWiki renders without formatting.
3. **Solution:** change PHP version from default to 7.4.x (see https://www.dokuwiki.org/requirements)

Expected:  Install script choses the right PHP version for the Installed DokuWiki version

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.5.10

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
We need to add support to change / check if the php used version is supported...
