### ISSUE TITLE
i cant go on the admin data base of mySQL using xamp because of PHP admin[Bug] 

### ISSUE THREAD

**Issue by 00GreyHat00** [hestiacp/hestiacp#2476]
### Describe the bug

i cant login PHPmyAdmin because of this weird error
![image](https://user-images.githubusercontent.com/91491985/157940816-b4ff1b7e-c8e9-4647-9d68-718945b564cc.png)

### Tell us how to replicate the bug

i just oppened the xampp control pannel and launched the admin of SQL and it failed i dont know why or how i didn't change nothing of the config

### Which components are affected by this bug?

Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

3.3.0

### Operating system

Windows 11

### Log capture

```shell
mysqli::real_connect(): (HY000/1045): Access denied for user 'pma'@'localhost' (using password: NO)
```

**Comment by jlguerrerosanz** [comment]
Xamp has nothing to do with hestiacp.
Also hestiacp doesn't run on windows 11.
Current hestia version is not 3.3.0 it is 1.5.10

Vous avez bu combien?

**Comment by 00GreyHat00** [comment]
thanks @jlguerrerosanz for your help but i solved it
also if u wanna help by just being toxic just don't help

**Comment by jlguerrerosanz** [comment]
@00GreyHat00 I am sorry.

I thought that you were laughing at us. Sorry.

I am happy to read that you solved your non-hestiacp-related issue.

**Comment by 00GreyHat00** [comment]
yeah im kinda dumb because i had xampp and wampp installed so wampp was using the port that xamp needed i just desinstalled wampp
