### ISSUE TITLE
[Bug] MediaWiki Quick Install Script  Fails

### ISSUE THREAD

**Issue by petrus9** [hestiacp/hestiacp#2477]
### Describe the bug

click on Media Wiki installer
Click on install
nothing happens.  no files are installed.   With or without SSL enabled. 

### Tell us how to replicate the bug

click on Media Wiki installer
Click on install
nothing happens.  no files are installed.   With or without SSL enabled. 

Let me know which logs you want me to post. 

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.5.10

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
There is currently no "Error" reporting present after at all. If an install fails it will with any luck an "false" returned an you are returned to the installer.. 

First step is to implement it
