### ISSUE TITLE
error processing package hestia-php (--configure)

### ISSUE THREAD

**Issue by jannathretail** [hestiacp/hestiacp#2478]
### Describe the bug

Hi Team,

I have used two commands 
1. apt-get update 
2. apt-get upgrade

After running the second command I got the below error at the last
**NOTICE: You are seeing this message because you have apache2 package installed.
Processing triggers for php8.0-fpm (8.0.16-1+ubuntu18.04.1+deb.sury.org+1) ...
NOTICE: Not enabling PHP 8.0 FPM by default.
NOTICE: To enable PHP 8.0 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php8.0-fpm
NOTICE: You are seeing this message because you have apache2 package installed.
Errors were encountered while processing:
 hestia-php
E: Sub-process /usr/bin/dpkg returned an error code (1)**

I have ran the same two commands again
first command doesn't gave any errors but the second command gave the below error
**Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up hestia-php (7.4.27-1) ...
dpkg: error processing package hestia-php (--configure):
 installed hestia-php package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-php
E: Sub-process /usr/bin/dpkg returned an error code (1)**

Please help me out

### Tell us how to replicate the bug

1. apt-get update
2. apt-get upgrade

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.5.10

### Operating system

Ubuntu 18.04

### Log capture

```shell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up hestia-php (7.4.27-1) ...
dpkg: error processing package hestia-php (--configure):
 installed hestia-php package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-php
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by jaapmarcus** [comment]
There is no special check is  the post install script..

https://github.com/hestiacp/hestiacp/blob/main/src/deb/php/postinst

Does the admin user exists?

**Comment by jannathretail** [comment]
yes, two users
1. admin
2. jannath

**Comment by jaapmarcus** [comment]
What happens with systemctl restart hestia
?

**Comment by jannathretail** [comment]
Job for hestia.service failed because the control process exited with error code.
See "systemctl status hestia.service" and "journalctl -xe" for details.

**Comment by jannathretail** [comment]
when I run the command systemctl status hestia.service, it gave me below log
● hestia.service - LSB: starts the hestia control panel
   Loaded: loaded (/etc/init.d/hestia; generated)
   Active: failed (Result: exit-code) since Sat 2022-03-12 18:24:11 IST; 1min 30s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 14067 ExecStart=/etc/init.d/hestia start (code=exited, status=70)
    Tasks: 3 (limit: 614)
   CGroup: /system.slice/hestia.service
           ├─6805 php-fpm: master process (/usr/local/hestia/php/etc/php-fpm.conf)
           ├─7277 nginx: master process /usr/local/hestia/nginx/sbin/hestia-nginx
           └─7279 nginx: worker process

Mar 12 18:24:11 thechickencode.com systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Mar 12 18:24:11 thechickencode.com systemd[1]: Starting LSB: starts the hestia control panel...
Mar 12 18:24:11 thechickencode.com hestia[14067]:  * Starting hestia-nginx hestia-nginx
Mar 12 18:24:11 thechickencode.com hestia[14067]:    ...done.
Mar 12 18:24:11 thechickencode.com hestia[14067]:  * Starting hestia-php hestia-php
Mar 12 18:24:11 thechickencode.com hestia[14067]: [12-Mar-2022 18:24:11] ERROR: Another FPM instance seems to already listen on /var/run/hestia-php.sock
Mar 12 18:24:11 thechickencode.com hestia[14067]: [12-Mar-2022 18:24:11] ERROR: FPM initialization failed
Mar 12 18:24:11 thechickencode.com systemd[1]: hestia.service: Control process exited, code=exited status=70
Mar 12 18:24:11 thechickencode.com systemd[1]: hestia.service: Failed with result 'exit-code'.
Mar 12 18:24:11 thechickencode.com systemd[1]: Failed to start LSB: starts the hestia control panel.








And when i run command journalctl -xe

root@thechickencode:/home# journalctl -xe
Mar 12 18:24:11 thechickencode.com systemd[1]: hestia.service: Found left-over process 7277 (hestia-nginx) in control group while starting unit. Ignoring.
Mar 12 18:24:11 thechickencode.com systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Mar 12 18:24:11 thechickencode.com systemd[1]: hestia.service: Found left-over process 7279 (hestia-nginx) in control group while starting unit. Ignoring.
Mar 12 18:24:11 thechickencode.com systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Mar 12 18:24:11 thechickencode.com systemd[1]: Starting LSB: starts the hestia control panel...
-- Subject: Unit hestia.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit hestia.service has begun starting up.
Mar 12 18:24:11 thechickencode.com hestia[14067]:  * Starting hestia-nginx hestia-nginx
Mar 12 18:24:11 thechickencode.com hestia[14067]:    ...done.
Mar 12 18:24:11 thechickencode.com hestia[14067]:  * Starting hestia-php hestia-php
Mar 12 18:24:11 thechickencode.com hestia[14067]: [12-Mar-2022 18:24:11] ERROR: Another FPM instance seems to already listen on /var/run/hestia-php.sock
Mar 12 18:24:11 thechickencode.com hestia[14067]: [12-Mar-2022 18:24:11] ERROR: FPM initialization failed
Mar 12 18:24:11 thechickencode.com systemd[1]: hestia.service: Control process exited, code=exited status=70
Mar 12 18:24:11 thechickencode.com systemd[1]: hestia.service: Failed with result 'exit-code'.
Mar 12 18:24:11 thechickencode.com systemd[1]: Failed to start LSB: starts the hestia control panel.
-- Subject: Unit hestia.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit hestia.service has failed.
--
-- The result is RESULT.
Mar 12 18:24:15 thechickencode.com sshd[14074]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=117.223.136.107  user=root
Mar 12 18:24:17 thechickencode.com sshd[14074]: Failed password for root from 117.223.136.107 port 40376 ssh2
Mar 12 18:24:17 thechickencode.com sshd[14074]: Received disconnect from 117.223.136.107 port 40376:11: Bye Bye [preauth]
Mar 12 18:24:17 thechickencode.com sshd[14074]: Disconnected from authenticating user root 117.223.136.107 port 40376 [preauth]
Mar 12 18:25:01 thechickencode.com CRON[14079]: pam_unix(cron:session): session opened for user admin by (uid=0)
Mar 12 18:25:01 thechickencode.com CRON[14078]: pam_unix(cron:session): session opened for user admin by (uid=0)
Mar 12 18:25:01 thechickencode.com CRON[14077]: pam_unix(cron:session): session opened for user root by (uid=0)
Mar 12 18:25:01 thechickencode.com CRON[14080]: (admin) CMD (sudo /usr/local/hestia/bin/v-update-sys-queue backup)
Mar 12 18:25:01 thechickencode.com CRON[14081]: (admin) CMD (sudo /usr/local/hestia/bin/v-update-sys-rrd)
Mar 12 18:25:01 thechickencode.com CRON[14082]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Mar 12 18:25:01 thechickencode.com CRON[14077]: pam_unix(cron:session): session closed for user root
Mar 12 18:25:01 thechickencode.com sudo[14084]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 12 18:25:01 thechickencode.com sudo[14083]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 12 18:25:02 thechickencode.com sudo[14084]: pam_unix(sudo:session): session closed for user root
Mar 12 18:25:02 thechickencode.com CRON[14079]: pam_unix(cron:session): session closed for user admin
Mar 12 18:25:02 thechickencode.com sudo[14083]: pam_unix(sudo:session): session closed for user root
Mar 12 18:25:02 thechickencode.com CRON[14078]: pam_unix(cron:session): session closed for user admin
Mar 12 18:26:01 thechickencode.com CRON[14354]: pam_unix(cron:session): session opened for user admin by (uid=0)
Mar 12 18:26:01 thechickencode.com CRON[14355]: (admin) CMD (sudo /usr/local/hestia/bin/v-update-sys-queue restart)
Mar 12 18:26:02 thechickencode.com sudo[14356]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 12 18:26:02 thechickencode.com sudo[14356]: pam_unix(sudo:session): session closed for user root
Mar 12 18:26:02 thechickencode.com CRON[14354]: pam_unix(cron:session): session closed for user admin
Mar 12 18:26:18 thechickencode.com sshd[14383]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=117.223.136.107  user=root
Mar 12 18:26:20 thechickencode.com sshd[14383]: Failed password for root from 117.223.136.107 port 36782 ssh2
Mar 12 18:26:21 thechickencode.com sshd[14383]: Received disconnect from 117.223.136.107 port 36782:11: Bye Bye [preauth]
Mar 12 18:26:21 thechickencode.com sshd[14383]: Disconnected from authenticating user root 117.223.136.107 port 36782 [preauth]
lines 1207-1257/1257 (END)

**Comment by jannathretail** [comment]
I am doing all these commands as root user,

do I have to use commands using admin user?

**Comment by jaapmarcus** [comment]
Reboot the server and try again

**Comment by jannathretail** [comment]
Hey Marcus, thanks man

After reebooting, no error 
Hit:1 http://archive.canonical.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:5 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic InRelease
Hit:6 https://apt.hestiacp.com bionic InRelease
Hit:7 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:8 https://nginx.org/packages/mainline/ubuntu bionic InRelease
Hit:9 https://mirror.mva-n.net/mariadb/repo/10.6/ubuntu bionic InRelease
Fetched 177 kB in 3s (65.8 kB/s)
Reading package lists... Done
root@thechickencode:~# sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up hestia-php (7.4.27-1) ...
W: APT had planned for dpkg to do more than it reported back (0 vs 4).
   Affected packages: hestia-php:amd64
root@thechickencode:~# apt-get update
Hit:1 https://apt.hestiacp.com bionic InRelease
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease
Hit:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 https://mirror.mva-n.net/mariadb/repo/10.6/ubuntu bionic InRelease
Hit:8 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:9 https://nginx.org/packages/mainline/ubuntu bionic InRelease
Reading package lists... Done
root@thechickencode:~# sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
