### ISSUE TITLE
[Bug] not able to suspend user from web panel

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2479]
### Describe the bug

When you try to suspend user from web panel it doesn't work.

### Tell us how to replicate the bug

login with admin user
select the user which you are trying to suspend.

![image](https://user-images.githubusercontent.com/39749258/158040144-cf74a997-14cd-43f1-a371-08451d0597de.png)

after you click ok, the page reloads but the user doesn't get suspended.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

v1.5.10

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Has allready been patched in Main branch will be released this week
