### ISSUE TITLE
[Bug] Hestia installer misleading error output

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2480]
### Describe the bug

I copied an old install string to the installer and got this error:

" hst-install-debian.sh: illegal option -- -"

The illegal option was --nginx yes

Since nginx is compulsory and there is no apache-only option, I understand that you removed that option but: the error should say: "illegal option --nginx" 

Altenatively for backwards compatibility the install script could maybe continue with --nginx yes or even ignore that parameter.

### Tell us how to replicate the bug

Try this install string:
bash hst-install.sh -f -y no --nginx yes --apache yes --phpfpm yes --multiphp yes \
--vsftpd yes --proftpd no --exim yes --dovecot no --sieve no --clamav no -- spamassassin no \
--mysql yes --quota yes --named no --lang es --hostname $hostname -e $email -p $password

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

Latest

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Nginx flag has been "Removed" in 1.4.0.  We almost reach 1.6... And 1.4 has been released almost 1 year ago (April 2021) Currently the flag -n or --nginx has been not used any more so they only thing users have to do is update their own install script...

**Comment by jlguerrerosanz** [comment]
I agree with that we have to update our scripts. I already did.

But. Is that the error message we should show when the installer reads an unknown option?

**Comment by jlguerrerosanz** [comment]
We should at least say which option was illegal
