### ISSUE TITLE
[Feature] Submit HestiaCP to Umbrel app store

### ISSUE THREAD

**Issue by ptrinh** [hestiacp/hestiacp#2485]
### Describe the feature or change in detail

Umbrel is an easy personal server platform that everyone can host.

We could submit HestiaCP as an app inside the Umbrel App Store, so that everyone can easily host their personal websites just with a click.

Umbrel app submission process is just submitting a dockerfile with a few screenshots.

https://github.com/getumbrel/umbrel/blob/master/apps/README.md

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
We do not plan to officially support such external plattforms, mainly due to missing time to maintain it. There is already a docker project from another user: https://hub.docker.com/r/smied/hestia-cp

Please feel free to add it to this platform on your own if you want to :).

**Comment by jaapmarcus** [comment]
https://hub.docker.com/r/artsemkniazeu/hestiacp

This one looks more promising :)
