### ISSUE TITLE
Is Ubuntu 22.04 LTS support planned? 

### ISSUE THREAD

**Issue by fossxplorer** [hestiacp/hestiacp#2489]
### Describe the feature or change in detail

When it's released 21.04.2022? :)

**Comment by jaapmarcus** [comment]
Yes,

It is for 80% working allready still waiting for upstream packages  and there is still a bug in F2B

**Comment by fossxplorer** [comment]
Thanks! Planning a migration from the old VestaCP and i'll wait until 22.04 support is in place

**Comment by jaapmarcus** [comment]
F2B updated their package. One issue less

**Comment by jaapmarcus** [comment]
#2537
