### ISSUE TITLE
Installation on Debian 8 is not possible

### ISSUE THREAD

**Issue by DJIronic** [hestiacp/hestiacp#249]
Hello,

I just tried to install HestiaCP on freshly installed Debian 8 64-bit.

As ft.debian removed backports for Debian 8, the installation will not proceed. I replaced it with the archive repository and disabled the validity check. I was able to proceed after apt-get update, but it will give out errors:

```
W: Selhalo stažení http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found

E: Některé indexové soubory se nepodařilo stáhnout. Jsou ignorovány, nebo jsou použity starší verze.
Installing Hestia Control Panel and required dependencies...
NOTE: This process may take 10 to 15 minutes to complete, please wait...-
Upgrade phpMyAdmin to v4.8.5...
mkdir: adresář „/usr/share/phpmyadmin/tmp“ nelze vytvořit: Soubor již existuje
ERROR: Config file remoteip.conf not properly enabled: /etc/apache2/mods-enabled/remoteip.conf is a real file, not touching it

Congratulations!

You have successfully installed Hestia Control Panel on your server.

```

I don't to upgrade to D9 just now as I am not fully ready to use it's network settings.

+ I have two questions:
1) How can I change the port of admin panel? I want it on 2096 to make it work with Cloudflare.
2) how can I use VestaCP backups to get my sites on HestiaCP. IPs are the same and assigned to the server.

**Comment by ScIT-Raphael** [comment]
Hi, to answer your questions:

1: v-change-sys-port 2096
2: Just restore them, the backup engine will also works with vesta backups.
