### ISSUE TITLE
I'd like to add a systemctl restart command to users domain list view [Feature] 

### ISSUE THREAD

**Issue by osnippet** [hestiacp/hestiacp#2490]
### Describe the feature or change in detail

I'd like to add a systemctl restart command through a click of a button to users domain list row possibly next to suspend button for python applications such as Django or Flask.

The command I use to restart the gunincorn socket looks something like this: `sudo systemctl restart mydomain.test-gunicorn.socket` the domain rebuild function does the job without having to log into terminal to issue that command, however, only admin user has access to rebuild functionality. It would be ideal to have a button for ordinary users to be able to restart the gunincorn socket with a click.

If you guys can provide me with some code samples and/or files to edit would be awesome.

Thank you in advance.
 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
I don't see an easy solution that work in this specific use case. 

I don't think users should be allowed to to restart randomly any services.  Easiest way is creating a custom v-restart-xxx script in /usr/local/hestia/bin/ and run that via UI / changes. Or create a custom "Quick install" (https://github.com/hestiacp/hestia-quick-install)  app that allows it. 

How ever we don't have time to implement such feature.
