### ISSUE TITLE
[Feature] how to delete or reinstall Hestia panel

### ISSUE THREAD

**Issue by ighalo87** [hestiacp/hestiacp#2492]
### Describe the feature or change in detail

I made some mistakes with the panel and the IP address is taking too long to open.

How can I uninstall the panel and install it back 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Wipe your OS..

Uninstall is not supported

**Comment by ighalo87** [comment]
How can I wipe the OS....what line of code should I use.

**Comment by ScIT-Raphael** [comment]
@ighalo87 ... wipe OS means you need to reinstall it.
