### ISSUE TITLE
Add White label options to Hestia CP

### ISSUE THREAD

**Issue by anondev-sudo** [hestiacp/hestiacp#2493]
### Describe the feature or change in detail

Add setting to dashboard where you can edit APP_NAME (now it is "Hestia Control Panel"), that is used as email from, in titles, email signature, etc.

I think that there could be also way to edit favicon and logo.

### Would you like to sponsor this feature to have it implemented?

Yes

https://app.bountysource.com/issues/118691101-add-white-label-options-to-hestia-cp

**Comment by jlguerrerosanz** [comment]
You want to white-label the whole panel or only that?

If you want the whole panel, we should think about a new UI page with all the related settings.

Maybe you also want to include the templates of the emails sent by the system.

**Comment by jaapmarcus** [comment]
The "Issue" that was talking about  in the Discord chat was about customising email send to the user  for that there was allready issue for it. (#1606)

For white labelling options:
Custom logo, 
"Appliction name", 
Themes (disable / enable feature) will be needed...  
Fav icons ( Low / high res)

**Comment by ghost** [comment]
Actually be nice if we've been white label the login. Like way to set the text and logo on the login page and css. Everything else can remain the hestia branding. Reason for this is so people finally poking around don't know what the server is necessarily running right off the bat. The ones logged in I mean it should remain hestio branding since it's free and open source

**Comment by xeruf** [comment]
CHeckout https://github.com/hestiacp/hestiacp/issues/172#issuecomment-1397676166 for a workaround

**Comment by xeruf** [comment]
Maybe we can commission basic white-label options together, it should not be too much effort I think:
logo & favicon (for us the latter should just be automatically downscaled from the former) and application name - in tab title, login welcome, emails and the like.
What price range would we be talking about here?

**Comment by jaapmarcus** [comment]
- Remove all references to Hestia on user facing pages (https://translate.hestiacp.com/projects/hestiacp/en/default/?filters%5Bterm%5D=hestia&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
- Allow Admins to upload and change "Application name" 
  - Logo login / password reset / 2fa reset 
  - Header logo 
  - Icon logo 
 - Allow users to create their own email templates

Depending on the last option if it will get implemented: 
300 to 700 euro + VAT

**Comment by dfag86** [comment]
maybe a few people are doing a collection for this functionality? :)

**Comment by jaapmarcus** [comment]
> maybe a few people are doing a collection for this functionality? :)

Feel free to send an email to info@hestiacp.com

**Comment by xeruf** [comment]
Maybe we can leverage https://bountysource.com to accumulate something together?

**Comment by jaapmarcus** [comment]
https://app.bountysource.com/issues/118691101-add-white-label-options-to-hestia-cp

**Comment by jaapmarcus** [comment]
> Maybe we can commission basic white-label options together, it should not be too much effort I think:
> logo & favicon (for us the latter should just be automatically downscaled from the former) and application name - in tab title, login welcome, emails and the like.
> What price range would we be talking about here?

Feel free to pitch in:
https://app.bountysource.com/issues/118691101-add-white-label-options-to-hestia-cp

**Comment by xeruf** [comment]
One little invaluable addition: A Textfield to add custom CSS to all pages, like some nextcloud themes offer.
This allows very quick but also in-depth adjustments.

**Comment by jaapmarcus** [comment]
> One little invaluable addition: A Textfield to add custom CSS to all pages, like some nextcloud themes offer.
> This allows very quick but also in-depth adjustments.

We can't store plain css / html in hestia.conf and I really don't want to facilitate. It adds complexity and users can drop a css file in a folder. That alleady currently exists.  This is still not a full theme editor or what so on... 

It is slightly more work then a textrea but lot more secure...

**Comment by jaapmarcus** [comment]
![Screenshot 2023-04-09 at 12 09 39](https://user-images.githubusercontent.com/9754650/230766861-0c7a4fe4-306b-4c21-9336-bafa35cd97dd.png)

![Screenshot 2023-04-09 at 12 10 44](https://user-images.githubusercontent.com/9754650/230766905-a2465b8b-bbff-436a-8a95-a40546bf80d8.png)

**Comment by xeruf** [comment]
Nice! The change of color is also part of this I assume?
Btw it's logos not `logo's` ;)

Maybe a hint in this settings menu where custom CSS can be dropped?
That would be totally sufficient!

**Comment by jaapmarcus** [comment]
> Btw it's logos not `logo's` ;)

Changed

Maybe a hint in this settings menu where custom CSS can be dropped?

 /css/themes/custom/

**Comment by jaapmarcus** [comment]
Change of colours can be done with a custom css. It is currently the same issue as with custom css

See: https://github.com/hestiacp/hestiacp/blob/main/web/css/src/themes/default.css for example

```
:root {
	--animate-duration: 300ms;
	--font-family: "Exo", system-ui;
	--font-family-monospace: "Inconsolata", "Lucida Console", "Monaco", monospace;
	--color-text: #7c7c7c;
	--color-text-link: #326b9b;
	--color-text-link-hover: #c36;
	--color-background: #fff;
	--border-radius-base: 4px;

	/* Alerts */
	--alert-border-color: #fff;
	--alert-box-shadow: 0 2px 4px rgb(0 0 0 / 20%);
	--alert-text-shadow: 0 1px rgb(0 0 0 / 45%);
	--alert-info-color: #618ecc;
	--alert-danger-color: #ec6c6c;
	--alert-success-color: #5ea64c;

	/* Icons */
	--icon-color-teal: #3cc;
	--icon-color-purple: #8e2fca;
	--icon-color-maroon: #c36;
	--icon-color-red: #f33;
	--icon-color-green: #53ba55;
	--icon-color-orange: #ffc043;
	--icon-color-blue: #326b9b;
	--icon-color-lightblue: #6eb6f0;
}
```

**Comment by xeruf** [comment]
If everything uses these theme variables, that is ideal :)

**Comment by jaapmarcus** [comment]
Not yet currently

**Comment by jaapmarcus** [comment]
White label support has been added it is only lacking support for custom logo's

**Comment by ghost** [comment]
We can create themes to change the CSS that has always been an option for a while now. It's really just the Logo and Login text. I wouldn't think much of it except we all have a default "admin" account and it kinda just as is signals the software running. Hiding the login branding at least obfujicates  it a bit for security.

**Comment by jaapmarcus** [comment]
Yes, Title login has been already changed. Only the logo is left. How ever PR became a merge disaster due all the changes we via other PR. 

Logo's is next on the to do list.  How ever also wanting to finish up the translation work first ...

**Comment by jaapmarcus** [comment]
Admin user is on the to do list:
https://github.com/hestiacp/hestiacp/pull/2835

**Comment by jaapmarcus** [comment]
Anyone a usefull idea how we can provide the users a way to change the logo?

Option 1: Create values in config and overwrite html
Option 2: Force users to create the logo's in /usr/local/hestia/web/images/custom/
And overwrite it each update / change
Option 3: ???

If somebody has useful input pleas go ahead 😄

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3572

**Comment by xeruf** [comment]
Thanks, works splendidly!
One thing to consider would be allowing to upload separate logos for light and dark mode, like zulip allows it as well - our main logo does not work well in dark mode so we would like to add an inverted variant.
Maybe you can also get inspiration from their implementation to refine yours.
