### ISSUE TITLE
Custom head

### ISSUE THREAD

**Issue by anondev-sudo** [hestiacp/hestiacp#2494]
### Describe the feature or change in detail

Add setting to add custom html tags to the head (of every page on control panel).
This way you could add for example HTML meta tags and others.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jlguerrerosanz** [comment]
I don't know if there are any hooks in header and footer.

**Comment by jaapmarcus** [comment]
There are currently no extra headers for footers. 

You can create hooks that run after install and modify the html files if needed...

https://github.com/jaapmarcus/hestia-hooks

I don't see a need for such feature at the future a more "White" labelling is needed but due the lack of time. This has no need. 

https://github.com/hestiacp/hestiacp/issues/2494

**Comment by anondev-sudo** [comment]
Can you send me hook to do it (to append something to head)

**Comment by ScIT-Raphael** [comment]
The source code of the project is here (https://github.com/hestiacp/hestiacp), the hook which @jaapmarcus means, can place code changes back in place after an upgrade. You need to find out on your own, how to place specific custom html tags, we currently do not plan to support that request and also cant help you out with it.

**Comment by anondev-sudo** [comment]
Add that you can make head.txt footer.txt files where you can place custom code for it. Some php software have that

For example https://www.hesk.com/knowledgebase/?article=33

**Comment by jaapmarcus** [comment]
We don't see a need for it. You can always fork the project and change how you want and make any changes you like.
