### ISSUE TITLE
[Feature] Rename user

### ISSUE THREAD

**Issue by anondev-sudo** [hestiacp/hestiacp#2495]
### Describe the feature or change in detail

Add way to change username directly on the dashboard, it should be changed just by admins (not by users itself)

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Linux does not support renaming users. 

Create a new user  -> 
- https://github.com/hestiacp/hestiacp/blob/main/bin/v-change-domain-owner
- https://github.com/hestiacp/hestiacp/blob/main/bin/v-change-database-owner
- Move all cronjobs
Delete old users

Do we want to invest about 5 hours for a feature that is almost never used.  My answer is no!

**Comment by jaapmarcus** [comment]
Also please do not create issues for non issues.  It is not worth our limited time...

**Comment by anondev-sudo** [comment]
Is there way to backup all mysql, domains, ..., export it, create new account and import backup?

**Comment by jaapmarcus** [comment]
No not by default... Any manual changes still require edditing database config anyway.

**Comment by ScIT-Raphael** [comment]
Basicly: v-backup-user olduser, v-restore-backup newuser olduserbackupfile
