### ISSUE TITLE
[Bug] Add missing cronjob LE renewal after import / new install

### ISSUE THREAD

**Issue by NickCoolii** [hestiacp/hestiacp#2496]
### Describe the bug

Fresh installation.
I had migrated non admin user with its things from another host with same version of HestiaCP.
That user has websites with let’s encrypt domains.
Before and after restore of that user, admin user had only 10 cron jobs and no one related to let’s encrypt.
I disabled and enabled again “Use Lets Encrypt to obtain SSL certificate” option for one web domain.
Only after that admin user get 11th cron job:
30 7 * * * sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl

Simplest way I found just use this part of code
https://github.com/hestiacp/hestiacp/blob/8e1a8d2000abbd5663cae06ad85daf4007ef4f36/bin/v-add-letsencrypt-domain#L528-L534
at `$HESTIA/bin/v-restore-user` after all domains restoration
https://github.com/hestiacp/hestiacp/blob/8e1a8d2000abbd5663cae06ad85daf4007ef4f36/bin/v-restore-user#L377
 if there was at least one domain with enabled let's encrypt.

### Tell us how to replicate the bug

1. Make backup of user which one has web site with enabled let's encrypt
2. Remove cron job `sudo $BIN/v-update-letsencrypt-ssl` of admin user
3. Restore user

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Let's Encrypt SSL

### Hestia Control Panel Version

1.5.11

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
Hmm, could be indeed a bug - we should consider to add the le cronjob part also by backup restore or create it by default.

**Comment by jaapmarcus** [comment]
> Hmm, could be indeed a bug - we should consider to add the le cronjob part also by backup restore or create it by default.

We should add it on default.... For new installs

**Comment by NickCoolii** [comment]
I think it will be fixed with 1.6.0.

**Comment by jaapmarcus** [comment]
It will be shipped with 1.6.0 unless there is something not according to plan
