### ISSUE TITLE
Automatic System backup to external ftp server.

### ISSUE THREAD

**Issue by easylyfe** [hestiacp/hestiacp#2502]
Good day,

We have just reviewed the Hestiacp and we commend you guys, but we came up with a suggestion that it will be better if the function to automatically upload system backup files to an external FTP server, just to keep the entire system backup files safe should there be a case of VPS server damage.
![hestia backup](https://user-images.githubusercontent.com/20471304/160576949-7f24a1e0-3559-44b3-bd91-78c78e56b4c3.PNG)

**Comment by ScIT-Raphael** [comment]
Check server settings -> backup, just add an ftp/sftp/b2 server there.

**Comment by ScIT-Raphael** [comment]
PS: no need to send your recommondation everywhere ;)
