### ISSUE TITLE
I am writing to you with a request to correct the Office365 DNS template

### ISSUE THREAD

**Issue by MrDeik** [hestiacp/hestiacp#2506]
Hello!

I just want to thank you for your work! I recently started using the panel and I can safely say that Hestia is the best among all existing ones!

I am writing to you with a request to correct the Office365 DNS template.
You only need to replace one value on one line and add another line.

It was:
ID='7' RECORD='@' TYPE='TXT' PRIORITY='' VALUE='**"v=spf1 a mx ip4:%ip% include:spf.protection.outlook.com -all"**' SUSPENDED='no' TIME='%time%' DATE='%date%'

Necessary:
ID='7' RECORD='@' TYPE='TXT' PRIORITY='' VALUE='**v=spf1 include:spf.protection.outlook.com -all**' SUSPENDED='no' TIME='%time%' DATE='%date%'

Add:
ID='18' RECORD='@' TYPE='MX' PRIORITY='0' VALUE='%domain%.mail.protection.outlook.com.' SUSPENDED='no' TIME='%time%' DATE='%date%'

Thank you in advance!

P.S. I write with the help of a translator, please do not pay attention to errors))

**Comment by jaapmarcus** [comment]
ip4:%ip%  is used to allow the server send email over php. So it should not be removed.

**Comment by jaapmarcus** [comment]
Just verifiied

`v=spf1 a mx ip4:x.x.x.x include:spf.protection.outlook.com -all`

What is the reason for adding the second MX record?

**Comment by MrDeik** [comment]
> ip4:%ip%используется, чтобы можно было отправить серверу электронную почту через php. Поэтому его не следует удалять.

Microsoft does not accept a record in this form. If you have an Office 365 account, you can try to add a domain with such a record, but you will get an error. I have 15 domains that I tried to link.

**Comment by MrDeik** [comment]
> Только что проверено
> 
> `v=spf1 a mx ip4:x.x.x.x include:spf.protection.outlook.com -all`
> 
> В чем причина добавления второй записи MX?

This is not the second MX record, look carefully at the standard file and the new one I propose.
[Template Office365 DNS.zip](https://github.com/hestiacp/hestiacp/files/8384051/Template.Office365.DNS.zip)

**Comment by MrDeik** [comment]
Sorry, but what I suggested is also wrong...
I give an example of how it should be if the domain is o365.org.ua:
o365-org-ua.mail.protection.outlook.com

What I suggested outputs the entry in this format:
o365.org.ua.mail.protection.outlook.com

That is, instead of dots, they should be But I don’t know how to write it correctly ..
![Screenshot_1](https://user-images.githubusercontent.com/52964785/160932245-d75d0fd0-1197-4183-9671-e9a06441cb3a.jpg)

**Comment by jaapmarcus** [comment]
I don't use Office365 my self.. How ever @ScIT-Raphael  is using it.

**Comment by MrDeik** [comment]
I really apologize! .. I figured out what the problem was. Still, the template is correct!) But I have additional services connected Office 365, and because of this there was a conflict of records)
Just for some domains, you need to tweak the setting a little)
Once again, I'm sorry, and thank you very much)
