### ISSUE TITLE
[Feature]  Rocky Linux Support?

### ISSUE THREAD

**Issue by eminkadioglu** [hestiacp/hestiacp#2508]
### Describe the feature or change in detail

Hi there;
When will support for Rocky Linux arrive?
Thanks

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
We dont have any plans to support rocky linux.

**Comment by jlguerrerosanz** [comment]
Why would you want rocky Linux. Install Ubuntu, install the panel and everything works.

**Comment by jaapmarcus** [comment]
Because Rocky Linux is based on CentOS and some users prefer it over Debian / Ubuntu..

**Comment by jlguerrerosanz** [comment]
I get that.

I have come to the conclusion that since the panel and the scripts are going to take care of 99% of the tasks if not 100%.

I don't care if it is debian or Ubuntu or CentOS. The panel will take care of it. The only thing I need is to know where are the config files located and the log files.

**Comment by eminkadioglu** [comment]
Hestia should have been on Rocky Linux. It has too many users. Stability is preferred. Still waiting for support

Thanks

**Comment by jaapmarcus** [comment]
Currently we don't have the time / development power to add support for Rocky Linux / CentOS based OS. 

Support will not be added unless somebody is willing to invest xxx hours to add support for it or willing to pay at least 10 000  euro for it..

**Comment by istiak101** [comment]
I think I can contribute to bring support for RHEL and 1:1 forks AlmaLinux, Rocky Linux, EuroLinux but not Fedora and other RPM based distro as in 1:1 forks all packages are mostly identical except their branding. I forked the project and hopefully will not lose motivation to complete this in mid way as there is no incentives in it for me except running this myself on my RHEL machines. I will contribute back to upstream if finished.

**Comment by jaapmarcus** [comment]
Build script for the packages should still work :tm: with some small changes 

https://github.com/hestiacp/hestiacp/blob/main/src/hst_autocompile.sh

Feel free to join our Discord channel if you need any help

**Comment by TomasHurtz** [comment]
hello just to jump in here, I would love to see a rocky linux support I prefer it over ubuntu or debian, otherwise, just another set of commands to learn ;-0

**Comment by rjd22** [comment]
> hello just to jump in here, I would love to see a rocky linux support I prefer it over ubuntu or debian, otherwise, just another set of commands to learn ;-0

This is most likely not going to happen. Supporting multiple distributions is quite a chore and we don't have enough maintainers to do so.

So you're better off learning the other set of commands. The differences are not that big.
