### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Stage4000** [hestiacp/hestiacp#2509]
### Describe the bug

PHP error on line 401 of /usr/local/hestia/web/tampltes/pages/add_web.html

```<?php foreach ($v_ftp_users as $i => $ftp_user): ?>```

[error] 776#0: *79 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/hestia/web/templates/pages/add_web.html on line 401" while reading response header from upstream.

This is causing sites to return a 500 error.

### Tell us how to replicate the bug

Unsure, this is a fresh install on a clean Ubuntu 20.04 OVH install.

### Which components are affected by this bug?

Sites hosted on Hestia.

### Hestia Control Panel Version

Latest (installed today)

### Operating system

Ubuntu 20.04 via OVH.

### Log capture

```shell
[error] 776#0: *79 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/hestia/web/templates/pages/add_web.html on line 401" while reading response header from upstream.
```

**Comment by Stage4000** [comment]
Update: Not sure what is going on here, I removed the htaccess file (that im 99% sure came with hestia since it was in the /home/user/web directory) and now everything appears to be fine...

**Comment by jaapmarcus** [comment]
/home/user should not have any "invluence" on Hestia GUI it self

**Comment by Stage4000** [comment]
> /home/user should not have any "invluence" on Hestia GUI it self

There isnt really an option for 'im getting a 500 nginx error that isn't my fault'. Sorry for not making that clearer. I edited it manually to accurately reflect the affected component.

**Comment by jaapmarcus** [comment]
For sites hosted check /var/log/apache2/domains/{your.domain.com}.error.log

```
<?php foreach ($v_ftp_users as $i => $ftp_user){
} ?>
```

As $v_ftp_users is probably empty that is why the error is created. Should not be a major issue. 

As it was an issue with the .htaccess file we can't do anything about. We don't create any .htaccess files on default unless you have used the Quick installer APP (Some use .htaccess files)

But in that case we need more information.  But as it is not an issue with Hestia "UI" it self I can close the issue

**Comment by Stage4000** [comment]
Now I remember why I don't use Hestia, its broken as hell and the staff are too dense to deal with it. Its sad when the current state of Vesta is better at addressing bugs than you. add_web.html is still broken, I don't know how to get that into your dumb ass head and am not going to keep trying to help you find bugs when you guys are clearly more interested in not fixing them than anything else in the world. With all of the open source hacks going around, I'm not interested in having a open source project managing my web server when they're clearly not interested in maintaining their product. If your security practices are anything like the foolish bug closing practices I've just experienced then I have no desire to have your broken software anywhere on my server. Ill go use Vesta in its broken state before I try Hestia again.

**Comment by jaapmarcus** [comment]
As told the error is most likely in .htacess file in /home/user/web/domain/public.html 

Check your log files as instructed and most likely you will see an error. We test on a daily basis our setups via automated testing and a new web domain should always work as intended. 

Everybody blames issue on Hestia while it is 80% user error... 

Feel free on how to provide more information or steps to reproduce the error but. "Removing .htaccess" solves the error is not reproduceable as we don't recreate .htaccess file.

**Comment by ScIT-Raphael** [comment]
Honestly, you got a detailed answer of @jaapmarcus, I don't see any need to rage here around - its on your side to provide the requested informations, but as he already wrote, Hestia UI doesnt have any direct connection to the sites itself, its a different service.

Please feel free to use vestacp, its not our intention to hold you back at all.

**Comment by Stage4000** [comment]
> Check your log files as instructed and most likely you will see an error. We test on a daily basis our setups via automated testing and a new web domain should always work as intended.

This is what im talking about, dense af, my log is included and add_web.html is CLEARLY broken.

**Comment by Stage4000** [comment]
> Honestly, you got a detailed answer of @jaapmarcus, I don't see any need to rage here around - its on your side to provide the requested informations, but as he already wrote, Hestia UI doesnt have any direct connection to the sites itself, its a different service.
> 
> Please feel free to use vestacp, its not our intention to hold you back at all.

I dont see the need for you to be here sucking on dick.

**Comment by ScIT-Raphael** [comment]
Goodbye then :).
