### ISSUE TITLE
Let's encrypt generation break down the webserver

### ISSUE THREAD

**Issue by DJIronic** [hestiacp/hestiacp#251]
### Brief issue description:
Every domain I select to generated SSL certificate from Let's encrypt will crash the webserver (domains ending on gateway timeout). Reboot will fix it until another cert will be generated. The same issue happens when running a command to regenerate all LE certs expired. (as I imported backups from Vesta that has problem with new LE generation)

### Steps to Reproduce:
1. Open HestiaCP
2. Select a domain, enable/disable SSL or ask to generated cert from LE
3. You need to restart the whole debian server to get website back up

### Expected behavior:
Certificates should get generated and up and running.

### Operating system distribution and release:
Debian 8 64.bit

### HestiaCP Version:
0.9.8-28

### What software is installed?
Type here (e.g. Apache, Nginx, PHP-FPM, Dovecot/Exim, MariaDB, etc.)
Apache, NGINX, MultiPHP, Maria DB (everything except dovecot, exim, clamav, spamassasin nad name - not using mails and DNS there)

### Additional notes:
It's a freshly installed VM and I just imported all the domains and users from backup as I moved from VestaCP - I need LE certs generated automatically.

**Comment by ScIT-Raphael** [comment]
Can you add the certificate using the cli -> v-add-letsencrypt-domain user domain

Also we would need to know what's going offline, please check for this the logs (apache2 or nginx).

**Comment by DJIronic** [comment]
Hi @ScIT-Raphael,

No one of them is reported as down in the "server" tab, but getting "gateway timeout" by cloudflare.

Yes, I can, but it will do the same thing.

When running `/usr/local/hestia/bin/v-update-letsencrypt-ssl` it will just run for infinite time and it will do the same effect.

**Comment by ScIT-Raphael** [comment]
Usualy a gateway timeout comes from nginx proxy, i would suggest to remove cloudflare for further testing.

Did you restored also the admin user? If yes, you would need to remove cronjobs, also we do suggest to not run any website under admin.

**Comment by DJIronic** [comment]
Yes, we had like 10 sites under admin created by the guy before me. Should I transfer them to another account?

Ok, I will remove Cloudflare from one domain for testing. But yes, I agree it can be the NGINX proxy with the gateway.

**Comment by r3sist** [comment]
Possible solution: I've got gateway timeout for LE operations when *Force SSL* nginx template is active ([cutom template](https://vestacp.com/docs/#how-to-force-https) for Vesta). You should disable it first.

**Comment by ScIT-Raphael** [comment]
If they are sites for different customers, split them to own accounts - if the sites are for one customer, move them to non admin.

Also a good idea is, if you have "affective" sites like wordpress, to split them anyway to a different account.

@r3sist Thanks for the input! We implement for that case a "force ssl" function, you can easy activate it under the web ssl part. Also I would to suggest default template for nginx.

**Comment by r3sist** [comment]
(I forgot to mention that I was speaking about Vesta, I'm not familiar with your software - yet)

**Comment by DJIronic** [comment]
UPDATE:

I just created a new account and SSL certificate of a domain on it., It generated the cert just fine, but after that getting the timeout again. After reboot site works with the LE cert.

**Comment by ScIT-Raphael** [comment]
There isnt any known bug with let's encrypt generation, also I'm not able to reproduce this issue. You will need to check out why you get a timeout (as already wrote, normaly this happens because nginx is stopped).

**Comment by DJIronic** [comment]
OK, I will splice the websites to separate accounts. Can I do it without changing database logins and etc?

**Comment by ScIT-Raphael** [comment]
you can use some prebuilt scripts: v-change-*-owner (* for database, domain, whatever)

**Comment by DJIronic** [comment]
Ok, got it. :) IF you want, I can let you to my server and you can test what is going on ot find the issue.

**Comment by ScIT-Raphael** [comment]
Any update on your case? If you still have the issue, please contact us with your server credentials on info@hestiacp.com

**Comment by DJIronic** [comment]
OK, reporting it to the email. Still crashing even after used the SSG command `v-add-letsencrypt-domain`

**Comment by DJIronic** [comment]
OK, @ScIT-Raphael. I sent you the email with all the info from simon (at) cechacek.email :)

**Comment by ScIT-Raphael** [comment]
@DJIronic, got your mail, forwarded it to @KristanKenney because of missing time until firday. If the issue couldnt resolve until firday, i will come back to it.

**Comment by DJIronic** [comment]
No problem. I am just monitoring the server and restarting it (manully) if it goes down. We can wait under friday without a problem.

**Comment by ScIT-Raphael** [comment]
You could, temproary, disable the v-update-letsencrypt-domain cronjob until the issue is fixed.

**Comment by ghost** [comment]
Hi @DJIronic, thanks for your feedback and please accept my apologies for the delay in getting back to you. I'll test this issue against the latest development code to verify shortly but I want to say that we've resolved this; I believe the issue is caused by an issue with how nginx is loading the SSL configuration alongside Let's Encrypt and the underlying file path/include structure.

**Comment by ghost** [comment]
I've tested Let's Encrypt support against our latest development code and found no issues in generation of web domain certificates, SSL enforcement or the renewal trigger via cron job.

**Comment by DJIronic** [comment]
Hi there.

I am sorry for a delayed answer. I just noticed all the sites went down probably after the LE regen script.  Reboot put all the sites back up - the same behaviour as it was. What can I do to fix this issue on our server now?

(I am away from my PC for last few days so that's why I was unable to answer sooner, sorry).

**Comment by ScIT-Raphael** [comment]
As @kristankenney already wrote, we think that this is not a hestia bug. I just wanted to login on your server to check step by step what the v-update-letsencrypt-ssl script will trigger, that takes down our service. But I wasnt able to connect with the provided login informations. Can you recheck them? Due to it is not a hestia bug, I will close this issue. Please proceed over the ticketing system with updates and communication.

**Comment by hanzicode** [comment]
I checked my recent install of HestiaCP (installed yesterday), and found this typo in v-add-letsencrypt-domain has not been fixed yet: https://forum.vestacp.com/viewtopic.php?f=11&t=18593&p=77111&hilit=lets+encrypt#p77111 Make sure to get that fixed in the next release.

**Comment by ScIT-Raphael** [comment]
@hanzicode is already fixed in develop branch, will be pushed with a new version.
