### ISSUE TITLE
How update CURL version ?!

### ISSUE THREAD

**Issue by johnguery** [hestiacp/hestiacp#2516]
I can't find the way to upgrade properly php curl version (currently hestia is up to date, but curl version is 7.64)
I would like to use the latest curl version 7.82

Is anyone can help me ?

Thanks

**Comment by jaapmarcus** [comment]
CURL it self is managed by curl package in Ubuntu/Debian 

PHP package is maintained by deb.sury.org  and we can't control it.

Depending on your setup you need to update build the packages your self or install them from a different source. 

As Hestia has noting to do with the packages you need to look for other options

**Comment by jaapmarcus** [comment]
if you use Debian Buster upgrade to Bullseye back ports ... 

https://packages.debian.org/search?keywords=curl

**Comment by johnguery** [comment]
Ok, got it, that's what I thought.

Thanks for the quick reply
