### ISSUE TITLE
Different PHP config values for each site

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#2517]
### Describe the feature or change in detail

I want to change PHP config for a particular site or user, is it possible? 

Currently, the PHP config values are applied to the whole server, correct me if I am wrong. 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Use templates for php-fpm 

https://docs.hestiacp.com/admin_docs/web.html#how-can-i-change-settings-for-a-specific-domain

**Comment by jaapmarcus** [comment]
For example:

```
; origin-src: deb/php-fpm/multiphp.tpl

[%domain%]
listen = /run/php/php%backend_version%-fpm-%domain%.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

user = %user%
group = %user%

pm = ondemand
pm.max_children = 8
pm.max_requests = 4000
pm.process_idle_timeout = 10s
pm.status_path = /status

php_admin_value[upload_tmp_dir] = /home/%user%/tmp
php_admin_value[session.save_path] = /home/%user%/tmp
php_admin_value[open_basedir] = /
php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@%domain%

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /home/%user%/tmp
env[TMPDIR] = /home/%user%/tmp
env[TEMP] = /home/%user%/tmp
```

Disables openbase dir for the domain assigned to this template. It also works for different settings

**Comment by jaapmarcus** [comment]
Or use .user.ini in /home/user/web/domain.com/public_html/

**Comment by vikasprogrammer** [comment]
Is there a CLI command to do this out of the box?

**Comment by jaapmarcus** [comment]
v-change-web-domain-backend-tpl user domain template will edit the settings how ever any admin need to create the templates first. 

.user.ini can be created via SFPT, FTP or just nano / text editor
