### ISSUE TITLE
Can we stop building web domains after update from git

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#2519]
### Describe the feature or change in detail

When I run the git update command , it automatically re-builds all web domains, is there a way to not do that?

```
=============================================================================
Installation tasks complete, performing clean-up...                          
=============================================================================
[ * ] Rebuilding user accounts and domains, this may take a few minutes...
```

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
The config rebuild is not always, only if it is needed due to a code change - it is not planed to change this behaviour, just dont edit configs directly and use templates.

**Comment by jaapmarcus** [comment]
Updates from git should never been pulled as it not stable yet ...

**Comment by vikasprogrammer** [comment]
A little background on my question: I wanted to extend hestia with my own commands and for that I didn't find any documentation. So, I had copy my commands to /usr/local/hestia/bin manually. I thought the best way to maintain this is to create a git repo and pull it from there. 

- If git is unstable I don't want to use it
- What is the best way to extend hestia in a maintainable way.

**Comment by jaapmarcus** [comment]
Hestia is designed to "rebuild" every time if you rebuild from the main branch. As this allows to test the software in the worst case situations so we know every works fine

In https://github.com/hestiacp/hestiacp/blob/3ee1175e5aa9f35a8c1e4687568f0b84d9a837d7/install/upgrade/versions/1.6.0.sh#L18-L22

We can disable rebuilding the packages  how ever it might cause issues as updates in 1.6.0 requires changes to both web.conf and mail.conf and other user config files and rebuilding. 

How ever If a code changes requires a rebuild won't execute properly... And might cause the system to break...

**Comment by jaapmarcus** [comment]
Also use the release branch if you want the most stable version...

https://github.com/hestiacp/hestiacp/blob/3ee1175e5aa9f35a8c1e4687568f0b84d9a837d7/install/upgrade/versions/1.5.11.sh

Doesn't require a rebuild for example...

**Comment by jlguerrerosanz** [comment]
If you only want to place your scripts with hestiacp ones why don't you use an independent repository? A repo that has no files in common with hestiacp.

**Comment by vikasprogrammer** [comment]
so use an independent repo and pull all the commands into the bin folder?

**Comment by jlguerrerosanz** [comment]
Yes. That is exactly what I am about to do with my scripts.
