### ISSUE TITLE
Please support IPv6

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#252]
_has it was suppose to be in the current VestaCP release_
### and [most of ControlPanel](https://en.wikipedia.org/wiki/Comparison_of_web_hosting_control_panels) support it.

**Comment by ScIT-Raphael** [comment]
IPv6 is already on the roadmap, until now we do not have any delivery date for it.

**Comment by JOduMonT** [comment]
@ScIT-Raphael I'm glad to ear this but where is the roadmap ;)

**Comment by ScIT-Raphael** [comment]
we just run it internally on projects.hestiacp.com, we will work on a public version soon, same for changelog.

**Comment by JOduMonT** [comment]
is IPv6 still on the map ?

**Comment by justwebu** [comment]
Here is a tutorial to enable ipv6 on HestiaCP
[https://justwebu.com/how-to-enable-ipv6-on-vestacp-manually.html](url)

**Comment by ScIT-Raphael** [comment]
> https://justwebu.com/how-to-enable-ipv6-on-vestacp-manually.html
I strongly recommend to NOT touch the configuration files, they will be overwritten during a rebuild or hestia upgrade (because of the triggered rebuild). We will need to adjust hestia templates and system itself to support IPv6 and need to find enough time for this plan.

**Comment by espressoelf** [comment]
Is there any news about this? While I don't have IPv6 myself, I'd prefer visitors being able to use it instead of carrier-grade NAT or DS lite etc.

**Comment by archergod** [comment]
Just want to put my Request to Support IPv6.

**Comment by archergod** [comment]
We can to it partially, like just support for Web Server or just for Database server Configuration upgrade .. not all services. WEb SErver one is enough for now.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/429

It is planned for 1.5  We need it also ....
