### ISSUE TITLE
[Bug] HSTS does not work with Apache2+php-fpm

### ISSUE THREAD

**Issue by espressoelf** [hestiacp/hestiacp#2521]
### Describe the bug

I'm running Hestia with Apache2+php-fpm, without nginx. In this setup, the HSTS switch in the control panel (`/edit/web/` -> _Enable HTTP Strict Transport Security (HSTS)_) doesn't work as intended. There are two reasons for that:
1. The generated file doesn't get included (Add `IncludeOptional %home%/%user%/conf/web/%domain%/apache2.hsts.conf*` to `templates/web/apache2/php-fpm/default.stpl`)
2. The configuration syntax is always nginx specific, see [v-add-web-domain-ssl-hsts line 59](/hestiacp/hestiacp/blob/main/bin/v-add-web-domain-ssl-hsts#L59). The correct syntax for Apache httpd2 would be `Header always set Strict-Transport-Security "max-age=15768000; preload"`.

I hope this helps someone more familiar with the project, bash and the variables available in v-add-web-domain-ssl-hsts, to add a fix.

### Tell us how to replicate the bug

1. Install with Apache Httpd2 + php-fpm
2. Add a domain
3. Enable ssl + hsts
4. Open the domain and notice the missing hsts headers

### Which components are affected by this bug?

Backend Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.5.11

### Operating system

Debian 10.12

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/blob/main/CHANGELOG.md#140---major-release-feature--quality-update

Since 1.4.0 we have dropped support for Apache2 "Only" due to low usage. 

Will check how much work it is to fix the issue

**Comment by ScIT-Raphael** [comment]
Sorry, havent noticed that you want to resolve the issue for apache2 only :)

**Comment by espressoelf** [comment]
Thanks for looking into it. I've looked into it again and it should be done in three minor edits:

1. Add `IncludeOptional %home%/%user%/conf/web/%domain%/apache2.hsts.conf*` as last include in https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/web/apache2/php-fpm/default.stpl and https://github.com/hestiacp/hestiacp/blob/main/install/rhel/templates/web/httpd/php-fpm/default.stpl
2. Use `Header always set Strict-Transport-Security "max-age=15768000; preload"` in https://github.com/hestiacp/hestiacp/blob/main/bin/v-add-web-domain-ssl-hsts when `$PROXY_SYSTEM` is unset and `$WEB_SYSTEM` equals `apache2` or `httpd2` (for rhel I guess? else just apache2).

That'd help a lot as I could keep an unmodified version running without creating a second template with hsts enabled.

**Comment by ScIT-Raphael** [comment]
May I ask what the reason for an apache2 only install is?

**Comment by espressoelf** [comment]
It is what I'm most familiar with. I migrated from doing configuration manually and chose HestiaCP because I could disable everything I didn't need (DNS, Mail, ...) but still easily manage a LAMP stack. The apps running are similar to Nextcloud, i.e. php-fpm dependent but not really benefiting from nginx' faster static file delivery, while also relying on some htaccess rules that I would have to migrate.

I could use nginx for ssl-termination and dumb reverse-proxy for apache2+php-fpm, but the only future benefit I currently see would be that the setup is officially supported.

**Comment by ScIT-Raphael** [comment]
there is no big change if you use nginx+apache2, you'll just get a faster cache infront of it. I'll allow myself to close this issue, it isnt worth to start any debugging for it. Give apache2+nginx a try, its worth it!

**Comment by espressoelf** [comment]
No problem, thanks for giving it a thought. I still think my solution is ready for implementation, though. 

While there probably isn't much benefit nginx offers with almost dynamic-only content, it probably isn't going to hurt either. How would I switch to using nginx in front of apache2? Run the installer again?
