### ISSUE TITLE
[Question] Is there an easy way to migrate from apache2+php-fpm to nginx+apache2+php-fpm?

### ISSUE THREAD

**Issue by espressoelf** [hestiacp/hestiacp#2522]
I wanted t ofollow the suggestion I got in #2521 but didn't find an "official" way and wanted to make sure I didn't miss anything before playing around manually.

According to https://forum.hestiacp.com/t/how-to-install-nginx-on-apache-php-running-hestia-cp/1310 it was planned, but since the setup I want to migrate from wasn't that popular to begin with, it would be totally understandable if devs focused on more important stuff.

Thanks for your time - again.

**Comment by jaapmarcus** [comment]
Install nginx repo
https://github.com/hestiacp/hestiacp/blob/f2d9bd86c3517cfba3e21ab8f8c1ea387709b8a5/install/hst-install-ubuntu.sh#L680-L684


apt install nginx 

Modify / add the following options:
WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'

And follow the following steps:

https://github.com/hestiacp/hestiacp/blob/f2d9bd86c3517cfba3e21ab8f8c1ea387709b8a5/install/hst-install-ubuntu.sh#L1354-L1384

**Comment by jaapmarcus** [comment]
I will close the issue as we don't plan to add a script for it in the future.
