### ISSUE TITLE
[Bug] nginx cache template, the purge cache buttom does not appear

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2526]
### Describe the bug

Exactly as describe the official doc, I copied the caching* template files (.tpl, .stpl and .sh) with another name to have my own nginx cache config. 

But when I apply this new template, the hestiacp dashboard does not show the buttom "purge nginx cache" as the "caching" proxy template shows.

### Tell us how to replicate the bug

1. copy nginx caching template files with another name
2. apply the new template
3. you will not see the buttom in the dashboard to purge the cache

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.11

### Operating system

Ubuntu 20.04.4

### Log capture

```shell
No log.
```

**Comment by jaapmarcus** [comment]
For Nginx + Apache2 it tied to the caching template  it is working as intendend.. Currently it is not possible to change it...

**Comment by jaapmarcus** [comment]
The only thing we can do early is match against xxxx-caching.tpl / .stpl / .sh. As we do the same with php templates

**Comment by franciscopaniskaseker** [comment]
Excellent, will work. Is not a critical feature, but is cool to have this workaround.

**Comment by jlguerrerosanz** [comment]
It is essential to have this feature.

**Comment by jaapmarcus** [comment]
> It is essential to have this feature.

Offcourse it is not . Vesta CP has been using this template for over ages and nobody asked for a purge function.

**Comment by jaapmarcus** [comment]
> It is essential to have this feature.

Offcourse it is not . Vesta CP has been using this template for over ages and nobody asked for a purge function.

**Comment by jlguerrerosanz** [comment]
Well, I want a cache policy that doesn't expire every 10 minutes or even that doesn't ever expire unless the page's content has changed so if Google visits my place the cache is active and I get an excellent speed score.

So I need a custom cache template that works without issues.

I also need the home and the category pages to expire hourly so that the content is updated regularly.

I don't want a 3.000 page wordpress install to be generating it's cache 24/7 so that the content is always cached.

With eris's plugin and the new API limits feature I can get a very approximate solution.

Otherwise I can't use Hestia's cache. 

Or maybe I'm wrong and I am missing something.

**Comment by franciscopaniskaseker** [comment]
The purpose of this issue is just document that will not work as expected, but is not critical.

The proxy parameters can be changed in the .tpl, .stpl and .sh files, so the button is not that important. In the .sh file you can also config the inactive parameter to purge the cache that was not used for X time.

Actually for me this is more important because maybe this missing button also can means other stuffs were missing (I did not explore all hestiacp stuffs).

**Comment by jaapmarcus** [comment]
> Well, I want a cache policy that doesn't expire every 10 minutes or even that doesn't ever expire unless the page's content has changed so if Google visits my place the cache is active and I get an excellent speed score.
> 
> So I need a custom cache template that works without issues.
> 
> I also need the home and the category pages to expire hourly so that the content is updated regularly.
> 
> I don't want a 3.000 page wordpress install to be generating it's cache 24/7 so that the content is always cached.
> 
> With eris's plugin and the new API limits feature I can get a very approximate solution.
> 
> Otherwise I can't use Hestia's cache.
> 
> Or maybe I'm wrong and I am missing something.

There are other methods to do the same thing how these as this how ever a pain to setup... 

If you have 3000 pages in cache you don't want clear them all as it would hit the server extra hard.. And 99% out 100% times you only need to update 10 / 20 pages..  And mainly on each update in Wordpress... 

For example "Front-page" / Some archives / categories and the changed page. 

I run a few large sites with over low xxxx pages and so far I haven't used the purge functionality maybe a few times to make sure a few times to reload few times to reload a "side" width plugin that was mandatory to load properly...

As v-purge- already works without caching template enabled as it just removes the cached dir (/. So it is the WEBUI exactly 1 line code change required.

Also wit "Custom" configs the v-purge-nginx-cache isn't ideal as it only deletes it on 1 location ( rm -rf /var/cache/nginx/$domain ) and not the config used in your variables... 

https://github.com/hestiacp/hestiacp/blob/d2ef8f99838eaa253a0242bc23f0dc83f18111a6/bin/v-purge-nginx-cache#L55-L57
