### ISSUE TITLE
[Bug] nginx reload sometimes double the memory used and never release

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2527]
### Describe the bug

I am using a custom nginx cache template. The ONLY difference between the original "caching" template is: instead of 10m, I set 1d to proxy_cache_valid. just that.

When I execute 

```bash
systemctl reload nginx
```
(**note:** instead of manually reload nginx, I can edit any website config in hestiacp dashboard that will execute reload. the problem will happen in the same way)

I can see the nginx restarting gracefully the childs, however I also can see that the memory allocated to nginx is increasing the memory usage and sometimes it almost double the use. And the nginx never release this memory.

I did the same test using "caching" nginx proxy template, and this problem does not happens.
I tried to replicate this in other nginx environment, but I can not get same result. So maybe is not a nginx problem.

**Note:** maybe is related in some way with https://github.com/hestiacp/hestiacp/issues/2526

### Tell us how to replicate the bug

1. As documentation explain, copy the 3 nginx "caching" template files with another name
2. apply this nginx template in any website
3. check nginx memory usage
4. apply again in the same site (without change anything, just apply)
5. check nginx memory usage

You can also manually execute nginx reload in the command line to check the problem.
If you remove that template and just use the "caching" one, the problem will not happen.

### Which components are affected by this bug?

Backend Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.5.11

### Operating system

Ubuntu 20.04.4

### Log capture

```shell
root@panel:/usr/local/hestia/data/templates/web/nginx# systemctl restart nginx

   Main PID: 1537520 (nginx)
      Tasks: 28 (limit: 108523)
     Memory: 884.8M

--> applied a copy of "caching" template and saved

   Main PID: 1537520 (nginx)
      Tasks: 27 (limit: 108523)
     Memory: 1.7G

--> applied again the same template (without change anything) and saved:

   Main PID: 1537520 (nginx)
      Tasks: 27 (limit: 108523)
     Memory: 1.7G

--> manually reload the nginx in command line

root@panel:/usr/local/hestia/data/templates/web/nginx# systemctl reload nginx

   Main PID: 1537520 (nginx)
      Tasks: 27 (limit: 108523)
     Memory: 1.8G

--> applied the same custom template to the same domain:

   Main PID: 1537520 (nginx)
      Tasks: 27 (limit: 108523)
     Memory: 1.8G

--> Now applied to a second domain the same custom template:

   Main PID: 1537520 (nginx)
      Tasks: 27 (limit: 108523)
     Memory: 1.8G

(weird, some times I see it being doubled, but was not now)

--> restarted the nginx not gracefully
root@panel:/usr/local/hestia/data/templates/web/nginx# systemctl restart nginx
   Main PID: 1644478 (nginx)
      Tasks: 28 (limit: 108523)
     Memory: 906.6M

--> now just saved any website config in the dashboard, without any changes
   Main PID: 1644478 (nginx)
      Tasks: 27 (limit: 108523)
     Memory: 1.7G


--> comment: I just did few tests to paste here. In the server we applied the template a lot of times yesterday doing tests and eventually nginx filled all the memory and OOM started to working. Then I started to investigate and I found this weird behavior
```

**Comment by franciscopaniskaseker** [comment]
I executed a new test:

After nginx not graceful restart (systemctl restart nginx), I applied the custom caching template to all domains (175) with the command "v-change-web-domain-proxy-tpl". I have one domain per account. It means that "systemctl reload nginx" was executed 176 times.

After nginx restart, ~1gb qas being used of memory. After 175 nginx reload:
```bash
   Main PID: 1644478 (nginx)
      Tasks: 27 (limit: 108523)
     Memory: 4.8G

root@panel:/home/vinnie# cat /etc/nginx/conf.d/01_caching_pool.conf | wc -l
175

```

then, if I restart not gracefully:
```bash
root@panel:# systemctl restart nginx
   Main PID: 3897323 (nginx)
      Tasks: 28 (limit: 108523)
     Memory: 1.2G
````

and just do one more reload:

```bash
   Main PID: 3897323 (nginx)
      Tasks: 28 (limit: 108523)
     Memory: 2.5G
```

and then restart:

```bash
root@panel:# systemctl restart nginx
   Main PID: 3916392 (nginx)
      Tasks: 28 (limit: 108523)
     Memory: 1.2G
```


Very weird.

I will comment another very weird behavior, but maybe is due nginx implementation (I am not sure yet), so that is why I did not comment here before.
After execute "systemctl reload nginx", if check nginx consume every second (through systemctl status command), I can see the processes opening and closing. And is interesting that before the old process receive shutdown signal, I see some huge peaks of memory usage, like 20GB+ being used and then released, then another random peaks of 4GB+, 8GB+ etc and then they are released. What I showed here in this topic is the final number, after the nginx reload procedure finished.

**Comment by jaapmarcus** [comment]
I will close the issue.

If you need to update a lot of websites via CLI use the "RESTART" flag set to no it should not reload each time. And there fore speed up the issue. 

If it is an issue with Nginx it make more sense to ask for more information at Nginx support forum
