### ISSUE TITLE
[Bug] phpMyAdmin fails to export databases since recent updates

### ISSUE THREAD

**Issue by hazrpg** [hestiacp/hestiacp#2529]
### Describe the bug

The problem occurs when you try to export anything from phpMyAdmin - the error the browser gives is "Could not be saved, because the source file could not be read." (on Firefox, Chrome, Edge) - which implies that the file the server has generated does not exist. Using a standalone version of phpMyAdmin works fine, so something is happening on the hestiacp configuration somehow.

### Tell us how to replicate the bug

1. Start a free lightsail instance of Ubuntu 20.04
2. Start a terminal to the new instance.
3. Run `sudo apt update && sudo apt upgrade` from the terminal to make sure everything is up-to-date first.
4. Setup hestiacp as per normal, which grabs the latest version.
5. Make sure to run `sudo apt update && sudo apt upgrade` again to pull any new changes.
6. Login to hestiacp and check that the latest version is installed.
7. Go to phpmyadmin and create or import a database.
8. Go to export to try and export said database with default settings.
9. You'll get the error that it can't export it.

### Which components are affected by this bug?

Control Panel Web Interface, Backend Web Server (Nginx, Apache2), Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.5.11

### Operating system

Ubuntu 20.04

### Log capture

```shell
Access Log /home/admin/web/domain.tld/logs/domain.tld.log:

9x.x.x.x - - [13/Apr/2022:13:41:48 +0100] "POST /phpmyadmin/index.php?route=/export HTTP/1.0" 200 87498 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"

Error Log (empty) /home/admin/web/domain.tld/logs/domain.tld.error.log.
```

**Comment by hazrpg** [comment]
Interesting, the one last thing I hadn't checked was the version of phpmyadmin details, I grabbed those as reported by phpmyadmin and they are:

* Apache/2.4.53 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
* Database client version: libmysql - mysqlnd 8.0.17
* PHP extension: mysqli, curl, mbstring
* PHP version: 8.0.17

I think I have found a quick workaround, but ideally this should be resolved because PHP 7.4 will be EOL soon. If I change the system's PHP version to 7.4 it works perfectly.

Changing this:

![image](https://user-images.githubusercontent.com/115112/163185501-30ec9ae2-e447-4b2a-916b-b4a29cf373e9.png)

To this:

![image](https://user-images.githubusercontent.com/115112/163185945-5fcf47b6-230f-4541-b729-75125d89d02c.png)

And that temporarily fixes this issue (temporary - because its not an ideal solution long term).

**Comment by jaapmarcus** [comment]
Strange PHPmyadmin should support PHP 8.0 according their website

**Comment by jaapmarcus** [comment]
https://github.com/phpmyadmin/phpmyadmin/issues/17445

It seems to be a bug in PHPmyadmin

**Comment by jaapmarcus** [comment]
Patch provided in the linked issue will solve the issue. For  now it is waiting on release from upstream source

**Comment by williamdes** [comment]
> Strange PHPmyadmin should support PHP 8.0 according their website

We support up to PHP 8.1 :)
This is a FF only issue that seems to be quite new 🤔

**Comment by jaapmarcus** [comment]
> > Strange PHPmyadmin should support PHP 8.0 according their website
> 
> We support up to PHP 8.1 :) This is a FF only issue that seems to be quite new 🤔

Safari 15.4 has the same issue. Upgrading to the last  snapshot solved the issue  2 days ago from me...

**Comment by chiareu** [comment]
phpMyAdmin fails to export databases on Chrome too
Failed - Network error

Hestia Control Panel: v1.5.13 | Operating System: Ubuntu 20.04 (x86_64)
nginx/1.21.6
Database client version: libmysql - mysqlnd 8.0.18
PHP extension: mysqli curl mbstring
PHP version: 8.0.18

**Comment by williamdes** [comment]
> phpMyAdmin fails to export databases on Chrome too Failed - Network error
> 
> Hestia Control Panel: v1.5.13 | Operating System: Ubuntu 20.04 (x86_64) nginx/1.21.6 Database client version: libmysql - mysqlnd 8.0.18 PHP extension: mysqli curl mbstring PHP version: 8.0.18

I would suggest you to try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)

**Comment by jaapmarcus** [comment]
> phpMyAdmin fails to export databases on Chrome too Failed - Network error
> 
> Hestia Control Panel: v1.5.13 | Operating System: Ubuntu 20.04 (x86_64) nginx/1.21.6 Database client version: libmysql - mysqlnd 8.0.18 PHP extension: mysqli curl mbstring PHP version: 8.0.18

Nothing to do with Hestia. Hopefully phpmyadmin comes soon with an new release

**Comment by jaapmarcus** [comment]
https://github.com/phpmyadmin/phpmyadmin/releases/tag/RELEASE_5_2_0

**Comment by williamdes** [comment]
> https://github.com/phpmyadmin/phpmyadmin/releases/tag/RELEASE_5_2_0

5.1.4 too: https://github.com/phpmyadmin/phpmyadmin/releases/tag/RELEASE_5_1_4

**Comment by jaapmarcus** [comment]
I noticed ;)

Will test it tomorrow and push out a release...

**Comment by jaapmarcus** [comment]
Systems are upgraded to 5.1.14 Issue should be resloved
