### ISSUE TITLE
[Bug] Configuring System IP... PHP Notice:  Unable able to load required libaries

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2531]
### Describe the bug

I was doing 3 hestiacp setups at the same time. Completely fresh and updated ubuntu 20.04.4. All the setups failed with:
```bash
PHP Notice:  Unable able to load required libaries. Please run v-add-sys-phpmailer in command line in /usr/local/hestia/web/inc/main.php on line 9
```

### Tell us how to replicate the bug

1. setup ubuntu 20.04.4 server
2. apt update && apt upgrade
3. setup hestiacp with the command:
```bash
bash hst-install.sh --interactive no --email email --password password --hostname my.domain.com  -f
```

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.5.11

### Operating system

Ubuntu 20.04.4

### Log capture

```shell
Updating currently installed packages, please wait...\
The installer is now downloading and installing all required packages.
NOTE: This process may take 10 to 15 minutes to complete, please wait...
-

========================================================================

[ * ] Configuring system settings...
[ * ] Configuring Hestia Control Panel...
[ * ] Generating default self-signed SSL certificate...
[ * ] Adding SSL certificate to Hestia Control Panel...
[ * ] Enable SFTP jail...
[ * ] Create admin account...
[ * ] Configuring NGINX...
[ * ] Configuring Apache Web Server...
[ * ] Install  PHP 8.0...
[ * ] Configuring PHP-FPM 8.0...
[ * ] Configuring PHP...
[ * ] Configuring Vsftpd server...
[ * ] Configuring MariaDB database server...
[ * ] Installing phpMyAdmin version v5.1.3...
[ * ] Configuring Bind DNS server...
[ * ] Configuring Exim mail server...
[ * ] Configuring Dovecot POP/IMAP mail server...
[ * ] Installing ClamAV anti-virus definitions.../
[ * ] Configuring SpamAssassin...
[ * ] Configuring fail2ban access monitor...
[ * ] Install Roundcube...
[ * ] Configuring System IP...
PHP Notice:  Unable able to load required libaries. Please run v-add-sys-phpmailer in command line in /usr/local/hestia/web/inc/main.php on line 9
Unable able to load required libaries. Please run v-add-sys-phpmailer in command lineError: apache2 restart failed
Error: can't create my.domain.com .example.com domain
```

**Comment by franciscopaniskaseker** [comment]
By the way, do you think I need reinstall the server or is possible to restart the setup?

There are no messages after that.

**Comment by jaapmarcus** [comment]
What was the hostname that you entered?


Error: can't create my.domain.com .example.com domain

Can't be right

It looks like something is wrong with the hostname detection as v-add-web-domain seems to fail

**Comment by jaapmarcus** [comment]
Validation of hostname / email for Interactive is skipped on default

https://github.com/hestiacp/hestiacp/blob/d2ef8f99838eaa253a0242bc23f0dc83f18111a6/install/hst-install-ubuntu.sh#L571-L614

We should probally validate the email / hostname against the same requirements.

With the command used above I am no able to replicate the issue. As It is an automated install I except the issue is caused by some thing that fetches the hostname on a automated method. 

Please try with -y yes / Interactive

**Comment by franciscopaniskaseker** [comment]
I replaced the domain used with my.domain.com to not publish the real one.

The real one was not published yet, but I do not think it will be a problem. I will try with interactive=yes.

**Comment by franciscopaniskaseker** [comment]
Now I used:
```bash
bash hst-install.sh --interactive yes --email emal --password password --hostname my.domain.com
```

and worked.

- without -f
- interactive yes

**Comment by jaapmarcus** [comment]
-f shouldn't been needed unless Ubuntu doesn't use Netplan 

I have submitted a PR with changes so it will also "validate" hostname and email address

**Comment by franciscopaniskaseker** [comment]
I am glad to help and participate in this community. thank you.
