### ISSUE TITLE
[Bug] mem usage graph doesn't update when using other locale

### ISSUE THREAD

**Issue by Heart1010** [hestiacp/hestiacp#2540]
### Describe the bug

My mem usage graph stopped working.
```bash
~# v-update-sys-rrd-mem
ERROR: /usr/local/hestia/web/rrd/mem/mem.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert '' to float
```
The update script needs english locale otherwise the grep commands doesn't work anymore https://github.com/hestiacp/hestiacp/blob/8107573b4f18348b5d49c2a4f879ca487d5dc98d/bin/v-update-sys-rrd-mem#L66-L78

So as a workaround I switched back to en_US.UTF8 and it worked again
```bash
~# cat /etc/environment
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
#LC_ALL=de_DE.UTF-8
#LANG=de_DE.UTF-8
~# v-update-sys-rrd-mem
~#
```

### Tell us how to replicate the bug

see description above

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.5.11

### Operating system

Debian 11.3 (x86_64)

**Comment by jaapmarcus** [comment]
https://github.com/serghey-rodin/vesta/commit/fb7f6254fa0291c46749d235a8433c95a777fa9d

This should work

**Comment by jaapmarcus** [comment]
@Heart1010  Can you try: 

`LC_ALL=C free -m`

It should force the use of the English local

**Comment by Heart1010** [comment]
> @Heart1010 Can you try:
> 
> `LC_ALL=C free -m`
> 
> It should force the use of the English local

Sorry @jaapmarcus was on vacation.... but yes I can confirm it works:
```bash
root@cp:~# free -m
              gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
Speicher:       1982         646         122          68        1213        1088
Swap:            509         385         124
root@cp:~# LC_ALL=C free -m
               total        used        free      shared  buff/cache   available
Mem:            1982         646         122          68        1213        1088
Swap:            509         385         124
root@cp:~#
```

**Comment by jaapmarcus** [comment]
Already tested on my test server. It will be updated for 1.6 release
