### ISSUE TITLE
[Hestia 1.6 BETA] Error 500 when editing/adding DNS record

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#2546]
When editing DNS record after 1.6 update server sends ERROR 500 
Logs: 
`2022/04/23 23:18:16 [error] 184103#0: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "selected" in /usr/local/hestia/web/templates/pages/edit_dns_rec.html:83
Stack trace:
#0 /usr/local/hestia/web/inc/main.php(181): include()
#1 /usr/local/hestia/web/edit/dns/index.php(214): render_page()
#2 {main}
  thrown in /usr/local/hestia/web/templates/pages/edit_dns_rec.html on line 83" while reading response header from upstream, client: 10.0.0.12, server: _, request: "GET /edit/dns/?domain=<REDACTED>&record_id=1&token=<REDACTED> HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "10.0.1.1:8083", referrer: "https://10.0.1.1:8083/list/dns/?domain=<REDACTED>&token=<REDACTED>"
`

**Comment by ghost** [comment]
Fixed

**Comment by ghost** [comment]
Fixed also creating new DNS records

**Comment by jaapmarcus** [comment]
Merged 👍🏼
