### ISSUE TITLE
[Bug] 1.6 Beta Letsencrypt SSL certificate can't be generated without Roundcube

### ISSUE THREAD

**Issue by martynaskre** [hestiacp/hestiacp#2549]
### Describe the bug

Letsencrypt SSL sertificate can't be obtained if mail template is not roundcube.

Roundcube Nginx configuration has this line https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/mail/nginx/default.tpl#L39 which adds Letsencrypt authorizations. While configuration without webmail doesn't have this line https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/mail/nginx/default_disabled.stpl

### Tell us how to replicate the bug

1. Edit mail domain
2. Disable Roundcube
3. Try to obtain SSL sertificate from letsencrypt

### Which components are affected by this bug?

Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.5.11

### Operating system

Ubuntu 20.04

**Comment by gOOvER** [comment]
can confirm this. With Webmailclient enabled (Rainloop/Roundcube) you can create a cert. When Webmail is disablked, it ends in an error
