### ISSUE TITLE
[Bug] Permissions for the $HOMEDIR/$user/web/$domain folder

### ISSUE THREAD

**Issue by ob-tk** [hestiacp/hestiacp#2552]
### Describe the bug

When creating a webdomain, permissions **751** are set for the *$HOMEDIR/$user/web/$domain* folder.

*bin/v-add-web-domain*:
```
# Changing file owner & permission
chown -R $user:$user $HOMEDIR/$user/web/$domain
chown root:$user /var/log/$WEB_SYSTEM/domains/$domain.* $conf
chmod 640 /var/log/$WEB_SYSTEM/domains/$domain.*
user_exec chmod 751 $HOMEDIR/$user/web/$domain $HOMEDIR/$user/web/$domain/*
user_exec chmod 551 $HOMEDIR/$user/web/$domain/stats $HOMEDIR/$user/web/$domain/logs
user_exec chmod 644 $HOMEDIR/$user/web/$domain/public_*html/*
chown --no-dereference $user:www-data $HOMEDIR/$user/web/$domain/public_*html
```

After the v-rebuild-web-domains (or after backup restore) the permissions changed to **551**.

*func/rebuild.sh*:
```
# Set folder permissions
no_symlink_chmod 551   $HOMEDIR/$user/web/$domain \
            $HOMEDIR/$user/web/$domain/stats \
            $HOMEDIR/$user/web/$domain/logs
```

**So which permissions are true, and in which case is it a bug????**

### Tell us how to replicate the bug

1. Create webdomain
2. Rebuild webdomain 

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.11

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Issue has been solved for 1.6.0
