### ISSUE TITLE
[Feature] Deduplication components

### ISSUE THREAD

**Issue by ItzYanick** [hestiacp/hestiacp#2553]
### Describe the feature or change in detail

De duplicating components like the `mail-infoblock` container into own template files (maybe even in a own folder). This way code is more scalable and reusing components means less going through code to check if you missed something.

This change would also help with customizing a bit more one day, as some would like to change information in the `mail-infoblock` container for example. Maybe having a override system that can override components (but this is a topic for another issue).

If this feature is wanted by others, I can help / code it my own. It isn't much of a code change. I am also accepting suggestions for other components that could be de duplicated.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Web Ui needs full rewrite first….  Then we can rebuild every thing to .twig or any other template engine …

**Comment by ItzYanick** [comment]
Didn't know there is a UI rewrite planned. I am currently investigating hosting either Hestia or MyVesta and I saw that MyVesta has a select option more for seeing a config with the system domain name instead of the email domain name. But doing a post-install hook would be pretty hard as selecting DOMs via shell would take me ages to setup. Just though this might be a good solution.

**Comment by jaapmarcus** [comment]
It is set via:

https://github.com/hestiacp/hestiacp/blob/e243d341c2411583e3340120a4537de6d192d891/web/templates/pages/edit_mail_acc.html#L177

Just add 

<option v_type="host" domain="<?=$hostname;?>"><?=_('Use hostname');?></option>

And submit a PR.

**Comment by ItzYanick** [comment]
I know **how** to add it (you also need to add it to `add_email_acc.html`). But that is not what I wanted.

**Comment by jaapmarcus** [comment]
I don't see the advantages of Deduplication of the only the mailbox info box as is currently used in 2 location. 
As long we still keep the current UI I don't think we will add / make radical changes. 

On the sort term there are not a lot 

As told you can submit a pull request with the required changes and we add it to Hestia it self. 

For the long term planning we should consider adding support for it with a better method so it can also be reused for FTP,  Database and web stats. But this will probally  during the same period when we rewrite parts to the UI...
