### ISSUE TITLE
Ability to test SMTP config by sending email [Feature] 

### ISSUE THREAD

**Issue by r-kjha** [hestiacp/hestiacp#2554]
### Describe the feature or change in detail

It would be really great if we had the option to test mail settings (SMTP), like this one:

![image](https://user-images.githubusercontent.com/87710356/165316412-6475aa93-a16a-4c7c-91db-da35bc042de3.png)

![image](https://user-images.githubusercontent.com/87710356/165316447-ffbdcf4e-e047-4ee9-b123-6769393b7bc5.png)

### Would you like to sponsor this feature to have it implemented?

No

**Comment by gOOvER** [comment]
This is in my eye's not really needed. This should be a part of the used script. The Mailserver works on Hestia :)

**Comment by jaapmarcus** [comment]
> This is in my eye'Äs not really needed. This should be a part of the used script. The Mailserver works on Hestia :)

It is to test the mail settings if you setup an mail domain in Hestia and use the email relay settings

**Comment by gOOvER** [comment]
> > This is in my eye'Äs not really needed. This should be a part of the used script. The Mailserver works on Hestia :)
> 
> It is to test the mail settings if you setup an mail domain in Hestia and use the email relay settings

He don't talk about relay settings :)

**Comment by jaapmarcus** [comment]
This issue and https://github.com/hestiacp/hestiacp/issues/2934 are duplicate as #2934 is better explained I will close this one
