### ISSUE TITLE
Phpmyadmin no access

### ISSUE THREAD

**Issue by nakhodka** [hestiacp/hestiacp#256]
### Brief issue description:
why can't i log into phpmyadmin

I see next:
mysqli_real_connect(): (HY000/1045): Access denied for user 'pma'@'localhost' (using password: YES)
mysqli_real_connect(): (HY000/1045): Access denied for user 'admin'@'localhost' (using password: YES)

### Operating system distribution and release:
Ubuntu 18.04 LTS)

### HestiaCP Version:
 0.9.8-28)

### What software is installed?
 Apache, Nginx, PHP-FPM, Dovecot/Exim, MariaDB, etc.)

**Comment by Pleskan** [comment]
@nakhodka Are you using HestiaCP from stable or development branch?
I guess you should use correct credentials for phpmyadmin.
Can't reproduce the issue on my test server.

**Comment by ScIT-Raphael** [comment]
@nakhodka as @Pleskan already wrote, we're unable to preproduce this issue on our test servers. Can you share your login informations to info@hestiacp.com so we can have a short look?

**Comment by nakhodka** [comment]
I sent information to the specified address

**Comment by nakhodka** [comment]
and the problem with webmail, no access to DB

**Comment by ScIT-Raphael** [comment]
Issue will be checked through our ticketing system, github issue will be closed.
