### ISSUE TITLE
Bind9 does not work on OpenVZ 7 VPS [Bug] 

### ISSUE THREAD

**Issue by Nadun21** [hestiacp/hestiacp#2560]
### Describe the bug

I am using OpenVZ 7 VPS, I have several VPS obtained from several companies.

Bind9 does not work when Hestiacp is installed on those VPS. Press the start button next to the bind but it does not work

I encountered this error in Ubuntu 20.04 and Debain 11.
Debain 10 does not have this bug and works fine. This has been a problem for months

See screenshots

Thank you

https://i.ibb.co/cyMFzNF/1.png
https://i.ibb.co/7bHx8gQ/2.png

### Tell us how to replicate the bug

No action

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.13

### Operating system

Debian 11 , Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
Please use https://forum.hestiacp.com for support request, also keep in mind to manualy check the bind9 service status (systemctl status bind) before you open your thread, this will contain important informations.

**Comment by Nadun21** [comment]
> Please use https://forum.hestiacp.com for support request, also keep in mind to manualy check the bind9 service status (systemctl status bind) before you open your thread, this will contain important informations.

I reported this as an error

**Comment by jaapmarcus** [comment]
Please provide then more info:

What do you see when you run systemctl status bind9 or try to start it via 

systemctl start bind9 and so on. Doesn't work is for us unable to debug.

**Comment by Nadun21** [comment]
> Please provide then more info:
> 
> What do you see when you run systemctl status bind9 or try to start it via
> 
> systemctl start bind9 and so on. Doesn't work is for us unable to debug.

I can give you a free OpenVZ 7 vps to try this out.

The screenshot shows what I found when running systemctl status bind9

See this at https://i.ibb.co/bsmK5G6/3.png

I just posted about this in the forum now

Thank you

**Comment by jaapmarcus** [comment]
In Debian:
https://github.com/hestiacp/hestiacp/blob/f7c1cc5cc6fcc1e489112dea1a95c07d40d58083/install/hst-install-debian.sh#L1621-L1624

**Comment by Nadun21** [comment]
> In Debian:
> 
> https://github.com/hestiacp/hestiacp/blob/f7c1cc5cc6fcc1e489112dea1a95c07d40d58083/install/hst-install-debian.sh#L1621-L1624

What do you mean by these?

Debain 10, Ubuntu 18.04 does not Auto Update when Hestiacp is installed on OpenVZ. sudo apt-get update && sudo apt upgrade -y You have to update by typing this command. If there is no update, strange problems will appear on the login side of the panel.

**Comment by jaapmarcus** [comment]
This is the code that should enable bind9 when installed on openVZ. 

Probably a good starting point to debug...

**Comment by jaapmarcus** [comment]
Just created an OpenVZ based VPS and can config the issue:

```
Jun 30 10:04:55 xxxxxx systemd[1]: Starting LSB: Start and stop bind9...
Jun 30 10:04:55 xxxxxx systemd[1]: Started LSB: Start and stop bind9.
root@openvz:~# 
```
Where xxx is my hostname. For some reason it doesn't really want to start completely

**Comment by jaapmarcus** [comment]
Even with only installing bind without Hestia I am having the same issue. I suggest switching to different based system as KVM or LXC 

Please open an issue at Bind9

**Comment by Nadun21** [comment]
> Even with only installing bind without Hestia I am having the same issue. I suggest switching to different based system as KVM or LXC
> 
> Please open an issue at Bind9

I will try to switch to KVM.

Hestiacp's Debain 10 and Ubuntu 18.04 do not have this bug. Why does Debain 11 get that bug?

The only solution to this problem is to use Cloudflare. Then Domain works fine

thank you

**Comment by jaapmarcus** [comment]
Ubuntu 20.04 also has issues .. 

You can maybe create an issue with Bind 
https://gitlab.isc.org/isc-projects/bind9/

Or  with OpenVZ 
https://bugs.openvz.org/secure/Dashboard.jspa

If somebody is willing to patch the issue feel free to do so. But currently I don't know where to start...

**Comment by Nadun21** [comment]
> Ubuntu 20.04 also has issues ..
> 
> You can maybe create an issue with Bind https://gitlab.isc.org/isc-projects/bind9/
> 
> Or with OpenVZ https://bugs.openvz.org/secure/Dashboard.jspa
> 
> If somebody is willing to patch the issue feel free to do so. But currently I don't know where to start...

Thank you very much. I'll give it a try
