### ISSUE TITLE
[Bug] Add MX records to DNS not working after [1.5.13] - Service release

### ISSUE THREAD

**Issue by chiareu** [hestiacp/hestiacp#2561]
### Describe the bug

I just observed that is not possible to add MX records to DNS.
Error: invalid value :: aspmx.l.google.com.

As a workaround, we can modify the original MX record created with NEW DNS ZONE, or we can add a normal TXT/A record, and then modify it to MX.

I only have one HP server, so I can't test on another server. 

### Tell us how to replicate the bug

1. add a new MX record on any DNS zone

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.13

### Operating system

Ubuntu 20.04 (x86_64)

**Comment by jaapmarcus** [comment]
Remove the following line:

https://github.com/hestiacp/hestiacp/blob/f7c1cc5cc6fcc1e489112dea1a95c07d40d58083/func/main.sh#L955

Working on a permanent fix for it...

**Comment by Scan4u** [comment]
Same is for CNAME records :) Hope to get fix asap :)

**Comment by jaapmarcus** [comment]
It does with all the values with a . On the end

**Comment by chiareu** [comment]
I just tried with the . added at the end and not worked on my server.

**Comment by jaapmarcus** [comment]
v-add-dns-record adds by default a .  at the end of the value.

**Comment by Scan4u** [comment]
As was told by [jaapmarcus](https://github.com/hestiacp/hestiacp/issues/2561#issuecomment-1113130571) - SSH and edit /usr/local/hestia/func/main.sh - line 941 and comment this string "**is_no_new_line_format "$1";**"

```
# DNS record validator
is_dns_record_format_valid() {
    if [ "$rtype" = 'A' ]; then
        is_ip_format_valid "$1"
    fi
    if [ "$rtype" = 'NS' ]; then
        is_domain_format_valid "${1::-1}" 'ns_record'
    fi
    if [ "$rtype" = 'MX' ]; then
        is_domain_format_valid "${1::-1}" 'mx_record'
        is_int_format_valid "$priority" 'priority_record'
    fi
## comment this string ->>>>    is_no_new_line_format "$1";
```
Now all is working well with CNAME

**Comment by Scan4u** [comment]
CNAME record was added after this fix, but unfortunatelly is not visible in NS records… So, will wait for the fix!

**Comment by jaapmarcus** [comment]
cat /home/user/conf/dns/domain.com.db should contain the .db bind9 uses

**Comment by Scan4u** [comment]
yes, the record is here
`status<>14400<->IN<---->CNAME<-><------>statuspage.betteruptime.com.`
But the bind do not reply it to the https://dnslookup.online/cname.html more than 30 min :(
All other records are ok (A,NS,MX). The problem is only with CNAME

**Comment by Scan4u** [comment]
Sorry, after reboot or just waiting the CNAME is start to work! So, the fix is working! :) I'm bit paranoid! :)

**Comment by jaapmarcus** [comment]
Issue has been sorted

Will release new version this week
