### ISSUE TITLE
dist-upgrade fails for all PHP-FPM versions

### ISSUE THREAD

**Issue by hrvylein** [hestiacp/hestiacp#257]
### Brief issue description:
Every installed php-fpm version fails to upgrade because of

```
Apr 16 09:24:38 srv php-fpm7.1[22677]: [16-Apr-2019 09:24:38] WARNING: Nothing matches the include pattern '/etc/php/7.1/fpm/pool.d/*.conf' from /etc/php/7.1/fpm/php-fpm.conf at line 125.
Apr 16 09:24:38 srv php-fpm7.1[22677]: [16-Apr-2019 09:24:38] ERROR: No pool defined. at least one pool section must be specified in config file
Apr 16 09:24:38 srv php-fpm7.1[22677]: [16-Apr-2019 09:24:38] ERROR: failed to post process the configuration
Apr 16 09:24:38 srv php-fpm7.1[22677]: [16-Apr-2019 09:24:38] ERROR: FPM initialization failed
```
Is this related to configuration files set by hestia?

### Steps to Reproduce:
sudo apt-get update && sudo apt-get dist-upgrade

### Expected behavior:
Upgrade should run with no issues

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
current

**Comment by Pleskan** [comment]
@hrvylein Is there any pool configuration files in  *etc/php/7.1/fpm/pool.d/* after upgrade?
Do you use standard system repo for php or custom one (e.g. deb.sury.org)?

**Comment by hrvylein** [comment]
No, there aren't any configuration files. PHP packages seem to be coming from sury.org and I think hestia installed that repository.

**Comment by Pleskan** [comment]
@hrvylein First of all current multi php implementation, which installed when using *-o* key is not recommended for production usage.
I advice you to use ** -w, --phpfpm ** instead then you can manage php-fpm pool config files by hand, but without any kind of such problems. There is one tested workaround for now.
Good luck!

**Comment by ScIT-Raphael** [comment]
@hrvylein this is a known bug and will be resolved in the next release. Will share with you a temporary solution soon, so that you don't have to wait until the release.

**Comment by ScIT-Raphael** [comment]
Issue is fixed with the following commit for dev branch: https://github.com/hestiacp/hestiacp/commit/c64c0e175476203c00789ebd6e6b59fb36965406

can you please run the following command in a script to resovle the issue on your system?
```
for v in $(ls /etc/php/); do
    wget https://raw.githubusercontent.com/hestiacp/hestiacp/develop/install/deb/php-fpm/dummy.conf -O /etc/php/$v/fpm/pool.d/dummy.conf
    v1=$(echo "$v" | sed -e 's/[.]//')
    sed -i "s/9999/9999$v1/g" /etc/php/$v/fpm/pool.d/dummy.conf
done
```

**Comment by hrvylein** [comment]
Worked, thanks!
