### ISSUE TITLE
[Bug] Letsencrypt Wildcard SSL - Error code: 2

### ISSUE THREAD

**Issue by Scan4u** [hestiacp/hestiacp#2573]
### Describe the bug

Hello!

I have two running Hestia machines ( v1.5.14, Ubuntu 20.04) with own DNS (bind cluster).
All seems to be fine, - NS records are correct on the primary and slave hosts.

I want to get the Wildcard Letsencrypt SSL for my domain www.test.com.ua
But when I added this domain to Hestia: test.com.ua + alias *.test.com.ua - I got “Error code: 2”.

What i’m doing wrong??? How to get the Letsencrypt Wildcard SSL in this case?
Please advise!

### Tell us how to replicate the bug

-

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.5.14

### Operating system

Ubuntu 20.04

### Log capture

```shell
-
```

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/error.log
and /var/log/hestia/system.log

 ✓ is_alias_format_valid success *.hestiacp.com 
 ✓ is_alias_format_valid success www.hestiacp.com,*.hestiacp.com

**Comment by jaapmarcus** [comment]
```
 ✗ DNS: Add domain record *.domain.com
   (from function `assert_success' in file test_helper/bats-assert/src/assert_success.bash, line 42,
    in test file test.bats, line 1180)
     `assert_success' failed with status 2
   
   -- command failed --
   status : 2
   output : Error: invalid value :: *
   --
```

**Comment by jaapmarcus** [comment]
See PR

**Comment by Scan4u** [comment]
Sorry for the stupid question, just for my understanding - is there an issue with creating Letsencrypt Wildcerts? :)
I tried both variants with aliases: a) just the *.hestiacp.com b) www.hestiacp.com, *.hestiacp.com - both sent me an error 2. But, if after I had closed error window in Hestia panel and click again the "Save" button - I got "ok" and the generated SSL certificates looks like on this screen:
![изображение](https://user-images.githubusercontent.com/16424225/166662461-e1ca4503-45c7-4c6f-ab6f-9e97532b5c41.png)

**Comment by Scan4u** [comment]
Also, in the Web Domains list I got the (*.hestia.com) record near the hestia.com domain - and have no idea what it means:
![изображение](https://user-images.githubusercontent.com/16424225/166665331-b7b35375-0d5e-4ea2-8d51-bf69cecaa1d1.png)

**Comment by jaapmarcus** [comment]
The issue was that DNS records created during this step are not created. And this caused the error it self

**Comment by Scan4u** [comment]
Thank U, jaapmarcus! Now I understand. Any chance to get a fast patch for this bug? :)

**Comment by jaapmarcus** [comment]
See
https://github.com/hestiacp/hestiacp/pull/2574/commits/6ccf8e7c6bc194ad42b2375b250af2873529b4f4#diff-7164a9da040b25fa258d1edb59b78a3189779fd1739133a89ed016be988115e1

For main.sh  to patch the issue. Currently testing on my server for more issues related this issue

**Comment by Scan4u** [comment]
I'll better wait for your official fix! :) Do not want to break anything else.
Once again - thank U for your fast corrections and great product!!! Have a nice day!

**Comment by Scan4u** [comment]
> Currently testing on my server for more issues related this issue

Hello, **jaapmarcus**! Do U had any issue at your local server after the mentionad Wildcard fix? :) Can't wait more, want to try this on my working machine. Is there any chance to get the official patch in short period? Or it is better to do this manually?

**Comment by jaapmarcus** [comment]
Yes the patched worked fine

**Comment by Scan4u** [comment]
Good to know! Do U know when U will apply this patch to the update release?

**Comment by jaapmarcus** [comment]
Yes it will be released in the next release

**Comment by Scan4u** [comment]
Just fix the main.sh here
![изображение](https://user-images.githubusercontent.com/16424225/167028385-b4c6bd28-35dd-49b7-92a2-02bd10537bc4.png)
and got the wildcert for the domain hestia.com,*.hestia.com.
But after got another issue - the webmail was stop working: the RoundCube don't want to start, got this page for webmail.hestia.com instead:
![изображение](https://user-images.githubusercontent.com/16424225/167027633-366f0a0c-48d2-4d2d-b080-843726dce683.png)
When I replaced the wildcard alias *.hestia.com to www.hestia.com and recreate the Letsencrypt cert - webmail back to work:
![изображение](https://user-images.githubusercontent.com/16424225/167028170-74093f37-dd62-48b6-ad5e-f0fc5b25da51.png)
So i think there still is a bug with wildcert.

**Comment by Scan4u** [comment]
Found the same situation [here](https://forum.hestiacp.com/t/website-with-wildcard-alias-is-displayed-instead-of-webmail/5907) and your answer [here](https://github.com/hestiacp/hestiacp/issues/1631) 
Is there any chance to get working this pair: webmail + wildcard certificate ?

**Comment by Scan4u** [comment]
Hi, **jaapmarcus**! Do U already have a fix for the webmail + wildcard issue? Please advise. :)

**Comment by jaapmarcus** [comment]
Nginx loads fie order by filename:

So if domain.com (With alias) *.domain.com loads first then webmail.domain.com (A-W) then the default page will show...

Apache2 is even stanger then domain.com goes always infront of webmail.domain.com

**Comment by Scan4u** [comment]
So we can't use the wildcard cert with the webmail page anyhow? Or there is still a chance to fix it i n Hestia?

**Comment by SnAFKe** [comment]
Maybe is not relation with this issue but similar.

https://forum.hestiacp.com/t/problems-with-ssl-wildcard/5542

I've same issue when wildcard is renew, is renew as normal certification  domain,com www.domain.com as mention here

https://github.com/hestiacp/hestiacp/issues/2573#issuecomment-1117140102
