### ISSUE TITLE
[Feature] Improved way of updating Cloudflare addreseses

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#2575]
### Describe the feature or change in detail

Noticed your method of keeping Cloudflare addreses is hard coded into the upgrade script. 
Perhaps consider this method
https://github.com/ergin/nginx-cloudflare-real-ip
This is a bash script that gets the IPs live and puts them into a file. 
Then all you'd need to do is 'include' the file into nginx.conf. 

You could run the bash command either on upgrade, or with a cron job, say monthly. 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
It makes sense to do it such way it shouldn't take a lot of time to implement it

**Comment by ghost** [comment]
Create a official repo. Move ups to its own file and set it to regularly update

**Comment by imjuniper** [comment]
Will be closed by #3338.
