### ISSUE TITLE
[Bug]  Wildcard domain overwrites webmail.domain.com

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2581]
### Describe the bug

When a user adds hestiacp.com and *.hestiacp.com webmail.hestiacp.com will not work any more

See https://github.com/hestiacp/hestiacp/issues/2573#issuecomment-1119060815

### Tell us how to replicate the bug

See above

### Which components are affected by this bug?

Backend Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.5.x

### Operating system

N/A

**Comment by Scan4u** [comment]
Hello, **jaapmarcus**! Do U have any ideas how to fix the mentioned bug when Wildcard domain overwrites webmail.domain.com?

**Comment by jaapmarcus** [comment]
If I knew an fix it would be patched all ready..

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/1631

**Comment by Scan4u** [comment]
l> If I knew an fix it would be patched all ready..

Hi, **jaapmarcus**! Yesterday I suddenly realized, that one of my home Hestia domains, wich got a LetsEncrypt wildcertificate, is working nice with webmail subdomain, - so the roundcube webmail is accessible. If U want, I can give U the access to my local Ubuntu ssh to investigate this case :) Maybe it will help to understand this issue and find a solution.

**Comment by jaapmarcus** [comment]
So far I know it has to do with the order in how apache2 the file reads

But we should continue in:
https://github.com/hestiacp/hestiacp/issues/1631

As was duplicate of #1631
