### ISSUE TITLE
[Feature] Add ability to allow, deny, or delay in robots.txt

### ISSUE THREAD

**Issue by ipkpjersi** [hestiacp/hestiacp#2582]
### Describe the feature or change in detail

Hi,

I think it would be nice to be able to have the ability to choose to use robots.txt to allow, deny, or delay instead of just automatically delaying, since it is automatically-generated by hestia:
![](https://i.imgur.com/IsnBoIb.png)

For example, I have a couple domains that I would like to completely deny (that way all of the main search engines won't index it) whereas I have a domain that I would like to compeltely allow. It would be nice to have some sort of way of doing this in the Edit Web Domain menu. I would also want this feature to be able to used for sites with different index.php locations, like for example the laravel web template has `index.php` in `document root/public/index.php` instead of `document root/index.php`, I hope this makes sense: 
![](https://i.imgur.com/ZbN6I0K.png) 

I am willing to monetarily sponsor this feature.

Cheers.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jlguerrerosanz** [comment]
Excuse my ignorance but isn't it the webmaster the one to change this setting when the web hosting is ready?

I mean, if I set up a new domain and I install wordpress on top of it? That robots.txt gets overwritten.

And if you are about to copy a new website via FTP, the robots.txt should be already in the designer's local folder so it would be overwritten.

I think though that it would be interesting to force some robots.txt depending on the web template or the user plan.

But is it worth to complicate the interface for that?

**Comment by ipkpjersi** [comment]
Typically I would do exactly that - I'd just overwrite the robots.txt file and call it a day.

However, the fact that it says that hestia has automatically generated the robots.txt file tells me literally what it says - hestia automatically generates the robots.txt file. The fact that it automatically generates the robots.txt file doesn't tell me *when* it generates it, but just that it does. It's entirely possible that automatically generating the robots.txt file overwrites it, either periodically, or after hestia version upgrades, etc meaning that manually overwriting the robots.txt file is essentially worthless unfortunately.

If I can safely overwrite the robots.txt file manually and no harm will ever come from that, then I will do just that and be on my way and close this issue. However, I'm not so sure that is the case, which is why I created this issue - to be able to have some control over the supposed automatic generation of robots.txt if said control is needed.

If anyone is familiar with how this works, I'd love to hear about it.

**Comment by jaapmarcus** [comment]
Robots.txt are only created on new domain creation and can be overwritten by the user without any issues.

See 
https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/web/skel/public_html/robots.txt

https://github.com/hestiacp/hestiacp/blob/fad2195deae5360d8363795cbed60a8898fbed0c/bin/v-add-web-domain#L115-L119

**Comment by jaapmarcus** [comment]
And on rebuild:
https://github.com/hestiacp/hestiacp/blob/fad2195deae5360d8363795cbed60a8898fbed0c/func/rebuild.sh#L270-L273

Only the document error are taken over... 

Feel free to send always a donation to:
https://hestiacp.com/donate/

But will close the issue for now
