### ISSUE TITLE
[Bug] No Web Template options

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#2586]
### Describe the bug

All advanced template options correspond to files in `/usr/local/hestia/data/templates/web`, except for the web templates, which should seemingly stem from the apache2 folder - despite multiple options in the folder I can only choose "Default":
<img width="1743" alt="image" src="https://user-images.githubusercontent.com/13354331/167506280-a9c9faef-0e00-4956-84b4-5f21fe78a1d3.png">

### Tell us how to replicate the bug

1. Edit a Web Domain
2. Advanced Options
3. Try to change the web template

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

just installed the latest, you are really missing a display of that somewhere in the panel

### Operating system

Deb11

**Comment by jaapmarcus** [comment]
It is working as intended

/usr/local/hestia/data/templates/web/nginx = Nginx in proxy mode
/usr/local/hestia/data/templates/web/nginx/php-fpm = Nginx in php-fpm mode
/usr/local/hestia/data/templates/web/apache2/ = Apache2 with modphp
/usr/local/hestia/data/templates/web/apache2/php-fpm = Apache2 with php-fpm

As templates for Apache2 with modphp  with php-fpm and and the other way around will break apache2 it doesn't make sense to use them.

**Comment by xeruf** [comment]
But in which situation would I be able to select any other Web Template than "Default"?
And when is the `proxy_ip.tpl` used?

**Comment by jaapmarcus** [comment]
When you install Hestia is installed with php-fpm  set to no and apache2 is selected

proxy_ip.tpl should not been used it is used for 

/etc/nginx/conf.d/xx.xx.xx.xx.conf
