### ISSUE TITLE
[Feature] Is building modules possible for hestia?

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#2589]
### Describe the feature or change in detail

Is there a way to add functionality or override functionality in hestia by building custom module/addons on top hestia? If no, whats the best way to extend hestia at this point.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/issues/2086

It is not supported and currently there is no plan to add support for it
