### ISSUE TITLE
No "ä,ö,ü" allowed in user name

### ISSUE THREAD

**Issue by xXKynarethXx** [hestiacp/hestiacp#259]
### Brief issue description:
Creating a new user containing letters with "ä", "ö" & "ü" in first and last name is not allowed.

### Steps to Reproduce:
1. create a new user
2. if the user has a first- or lastname containing one of the above mentioned letters the user won't be created

### Expected behavior:
The user should be created even if the first or lastname contains unicode letters.
Usernames shouldn't contain such letters because of incompability in the os or other systems.

### Operating system distribution and release:
All OS could be affected, tested with Debian 9 & Ubuntu 18.04

### HestiaCP Version:
latest

### What software is installed?
full install of hestia script on a clean server

**Comment by ghost** [comment]
Hey @xXKynarethXx, thanks for the bug report. We'll take a look further into this and follow up.

**Comment by ScIT-Raphael** [comment]
I can confirm, that it removes any "umlauts" on user, first and lastname field. For user this would be good, but on first and last name we should allow the usage of "umlauts".

**Comment by Lupul** [comment]
Cannot reproduce on branch "**lab06_n**" HEAD at https://github.com/hestiacp/hestiacp/commits/2c3d9b004fc75f6bdb4f675df51269aed312b670
Lang: en
OS: Ubuntu 18.04
Tested multiple times, add user, edit user


![image](https://user-images.githubusercontent.com/3596864/56679405-abe8cb80-66cd-11e9-928b-7f56545a1c3e.png)

**Comment by ghost** [comment]
Also unable to reproduce on **lab06_n** branch builds on Ubuntu 18.04 at this time.

**Comment by ScIT-Raphael** [comment]
looks like we've fixed it already on new branch, wasnt able anymore to reproduce it on lab branch. Will close the issue for now.
