### ISSUE TITLE
[Bug] Beta 1.6.0, Fail2Ban down after restart

### ISSUE THREAD

**Issue by GodMorduk** [hestiacp/hestiacp#2594]
### Describe the bug

For some reason after frest install of 1.6.0-beta3 fail2ban is not enabled in systemctl and is down, same after reboot.

Systemctl enable fail2ban helps this issue (or simple service fail2ban start)

### Tell us how to replicate the bug

1. Fresh install 
2. service fail2ban status <- down
3. reboot
4. service fail2ban status <- down

### Which components are affected by this bug?

Firewall (Iptables, Fail2ban)

### Hestia Control Panel Version

1.6.0beta3

### Operating system

22.04

**Comment by jaapmarcus** [comment]
Run in command line

```
    update-rc.d fail2ban enable
```

Will patch it for new installs don't care enough about beta testers
