### ISSUE TITLE
[Bug] can not connect to Mariadb in Hestiacp admin panel after upgrade

### ISSUE THREAD

**Issue by mohsenMJ** [hestiacp/hestiacp#2595]
### Describe the bug

after upgrading my ubuntu server 20.04 using 

`sudo apt update && sudo apt upgrade`

updated mariadb to version 10.7.3 , my database works fine but the problem is that I can't configure database from hestiacp panel anymore plus I can't open webmail because of database error

### Tell us how to replicate the bug

upgrade mariadb to 10.7.* and you'll see the problem

### Which components are affected by this bug?

Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.15.5

### Operating system

Ubuntu 20.04

![image](https://user-images.githubusercontent.com/5730211/168932461-ca889213-86c2-4e65-98b1-52c89b20f05a.png)

please help me to solve this problem

thanks in advance

**Comment by gOOvER** [comment]
mariadb 10.7 works fine for me with hestiacp on Debian 11

**Comment by jaapmarcus** [comment]
Detection of mysql 10.7 is running / not is broken in 1.5.x branch it will be fixed in the 1.6.0 release. 

What happens If you run systemctl status mariadb

**Comment by jaapmarcus** [comment]
Did you change mysql root password during the update?
