### ISSUE TITLE
[Bug] Users can't download backups

### ISSUE THREAD

**Issue by hmv47** [hestiacp/hestiacp#2600]
### Describe the bug

When logging in as a regular user, backups can't be downloaded - white screen is presented.

### Tell us how to replicate the bug

1. Log in as a regular user
2. Try downloading a backup

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.15

### Operating system

Ubuntu 20.04

**Comment by gOOvER** [comment]
cant confirm; works as it should. i can download ever backup as regular user

**Comment by hmv47** [comment]
Interesting, I know there was an issue with this https://github.com/hestiacp/hestiacp/issues/2524 but a fix was merged. I will debug some more and post logs.

**Comment by jaapmarcus** [comment]
It might be only merged in beta version and not in release

**Comment by hmv47** [comment]
I can't find any errors in any of the Hestia's error files nor nginx-error.log, nginx-access.log shows that response is 200 
```
xx.xx.xx.xx - - [19/May/2022:15:49:36 +0000] GET /download/backup/?backup=user.2022-05-19_05-11-28.tar&token=978bac1ccee996a3e392b50b72f24797 HTTP/1.1 "200" 31 "https://srv.hostname.com:8083/list/backup/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0" "-"
```
I tried replacing web/download/backup/index.php and web/inc/main.php from https://github.com/hestiacp/hestiacp/pull/2525/files and it then does work, but breaks admin UI, probably due to some unrelated changes

**Comment by jaapmarcus** [comment]
Bug is present in 1.5.x / release branch but fixed in the new beta / release candidate version. 

As 1.6 is around the corner. 

Don't think it is needed to patch the issue with a new release
