### ISSUE TITLE
[Bug] Update / Upgrade corrupt the system in ubuntu and debian

### ISSUE THREAD

**Issue by gtavargas** [hestiacp/hestiacp#2604]
### Describe the bug

Greetings, I have updated several ubuntu and debian servers with: apt update and apt upgrade, but on many occasions the operating system is corrupted and after this process it remains with failures such as: phpmyadmin remains at: page not found. and the other pages or domains as well.

Choose to skip update files when asking to overwrite old ones with new ones in: apache, mariadb, nginx.

Who has or knows some good practices that should be followed for this process of apt update and apt upgrade. Thank you.

### Tell us how to replicate the bug

apt update and apt upgrade

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.5.15

### Operating system

Ubuntu 20.04 and Debian 11

### Log capture

```shell
Configuration file '/etc/nginx/conf.d/default.conf'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** default.conf (Y/I/N/O/D/Z) [default=N] ? N
Installing new version of config file /etc/nginx/mime.types ...

Configuration file '/etc/nginx/nginx.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** nginx.conf (Y/I/N/O/D/Z) [default=N] ? N

Configuration file '/etc/logrotate.d/apache2'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** apache2 (Y/I/N/O/D/Z) [default=N] ? N
Setting up dbconfig-mysql (2.0.13) ...
Setting up mariadb-server-10.5 (1:10.5.16+maria~focal) ...
Installing new version of config file /etc/logrotate.d/mysql-server ...
Installing new version of config file /etc/mysql/debian-start ...

Configuration file '/etc/mysql/mariadb.conf.d/50-server.cnf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** 50-server.cnf (Y/I/N/O/D/Z) [default=N] ? N
```

**Comment by jaapmarcus** [comment]
It is always default answer "No"

Not all config files are custom but you need to pay attention

For Apache2 just replace the config from /usr/local/hestia/install/deb/apache2 en  /usr/local/hestia/install/deb/nginx

It is impossible to check for accidental updates by the user so it not possible to fix. It is the user responsibility to not just press Y every time and check what's need to be done.

**Comment by gtavargas** [comment]
Greetings, The question would be: Is it recommended to run apt update and apt upgrade using HestiaCP frequently as a security method to keep up to date with updates?

**Comment by gOOvER** [comment]
> Greetings, The question would be: Is it recommended to run apt update and apt upgrade using HestiaCP frequently as a security method to keep up to date with updates?

there is no other way, to update the system; so yes, it is.

**Comment by jaapmarcus** [comment]
> Greetings, The question would be: Is it recommended to run apt update and apt upgrade using HestiaCP frequently as a security method to keep up to date with updates?

Yes updates are always smart.
