### ISSUE TITLE
[Conf file amendment]

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2605]
### Describe the bug

Ubuntu 20x
Hestia v1.5.15

in file : /usr/local/hestia/conf
the policy attribute is duplicated..

POLICY_SYSTEM_PROTECTED_ADMIN='no'
POLICY_SYSTEM_PROTECTED_ADMIN='yes'

### Tell us how to replicate the bug

in file : /usr/local/hestia/conf
the policy attribute is duplicated..

POLICY_SYSTEM_PROTECTED_ADMIN='no'
POLICY_SYSTEM_PROTECTED_ADMIN='yes'

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.15

### Operating system

Ubuntu20x

### Log capture

```shell
none
```

**Comment by jaapmarcus** [comment]
Haven't been able to replicate the bug on my current install. If it was an older server it might been allready fixed.

Have checked 5 servers where I have access to... 

It is save to remove the duplicated line

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/apache-starts-but-nginx-doesnt/6386/5

Also has the issue (Not the main source of his problem)

We should delete the duplicated entry
