### ISSUE TITLE
[Bug] System failure - Error Send Mail - INFO: task jbd2

### ISSUE THREAD

**Issue by gtavargas** [hestiacp/hestiacp#2614]
### Describe the bug

Greetings, I have this error on a server and when it appears it stops sending and receiving emails, to solve it you must restart.

Does anyone know how I can solve it?

### Tell us how to replicate the bug

![Screenshot_20220523_173445](https://user-images.githubusercontent.com/78830344/170105177-1810fc8f-8ded-46a2-8be0-f0624c91f4a7.png)

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.5.15

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
https://forum.proxmox.com/threads/kernel-panic-since-update-to-proxmox-7-1.101164/

Looks like nothing to do with Hestia

**Comment by gtavargas** [comment]
My proxmox is: Virtual Environment 4.4-1/eb2d6f1e, no 7.1

**Comment by jaapmarcus** [comment]
If you google the exact  error message in Google:

https://helpful.knobs-dials.com/index.php/INFO:_task_blocked_for_more_than_120_seconds.
https://serverfault.com/questions/405210/can-high-load-cause-server-hang-and-error-blocked-for-more-than-120-seconds
https://access.redhat.com/solutions/408833
https://www.blackmoreops.com/2014/09/22/linux-kernel-panic-issue-fix-hung_task_timeout_secs-blocked-120-seconds-problem/

It looks like you have issues with the host .

Start there with debugged. Hestia doesn't update anything with the host.

**Comment by gtavargas** [comment]
We agree, I will review the case in detail with your suggestion and I will be giving feedback
