### ISSUE TITLE
[Bug] DNS Records Issue

### ISSUE THREAD

**Issue by entropyideas** [hestiacp/hestiacp#2615]
### Describe the bug

When adding three CNAME records required by Amazon Web Services to my DNS records caused my records from not displaying and showing 0 DNS records when I click on the domain that is having an issue. It is still showing the proper amount under the DNS tab but just clicking through to the domain displays 0 records.

### Tell us how to replicate the bug

1) Click on DNS tab
2) Click on domain which you are editing the DNS zone
3) Continue to add these three CNAME records that are listed below.

2g7lwbnjvakbg2zciskzyp7al52ng6ez._domainkey.somedomain.com
2g7lwbnjvakbg2zciskzyp7al52ng6ez.dkim.amazonses.com

jov7devhgqqnteg2qnap4zay6ol2atrp._domainkey.somedomain.com
jov7devhgqqnteg2qnap4zay6ol2atrp.dkim.amazonses.com

x5jjiu6qvlbvaqtnh3aikczvn5juoa4h._domainkey.somedomain.com
x5jjiu6qvlbvaqtnh3aikczvn5juoa4h.dkim.amazonses.com

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.15

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
What happens when you run 

v-list-dns-records user domain.com in command line?

**Comment by jaapmarcus** [comment]
<img width="999" alt="Screenshot 2022-05-25 at 00 20 25" src="https://user-images.githubusercontent.com/9754650/170141572-590bbd11-5cc1-40b9-836e-f08cc4dc504a.png">

I don't have any issues

**Comment by entropyideas** [comment]
When I ran the command it displayed all the records properly. I know that the records were still there since the site was still operational. Just for some reason, it is not displaying in the web interface and it occurred after adding those records. It is displaying the proper amount of records before you click the domain, its when you click the domain it shows 0 records.

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/nginx-error.log to see if it provides more info...

**Comment by entropyideas** [comment]
Looks like something is going on.

2022/05/24 22:35:37 [error] 2477790#0: *1770 FastCGI sent in stderr: "PHP message: PHP Warning:  ksort() expects parameter 1 to be array, null given in /usr/local/hestia/web/list/dns/index.php on line 23" while reading response header from upstream, client: 1.1.1.1, server: _, request: "GET /list/dns/?domain=somedomain.com&token=f93e97387bbc484be203790233a7d9e6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "somedomain.com:8083", referrer: "https://somedomain.com:8083/list/dns/"
2022/05/24 22:35:37 [error] 2477790#0: *1770 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/hestia/web/templates/pages/list_dns_rec.html on line 80" while reading upstream, client: 1.1.1.1, server: _, request: "GET /list/dns/?domain=somedomain.com&token=f93e97387bbc484be203790233a7d9e6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "somedomain.com:8083", referrer: "https://somedomain.com:8083/list/dns/"
2022/05/24 22:38:04 [error] 2477790#0: *1785 FastCGI sent in stderr: "PHP message: PHP Warning:  ksort() expects parameter 1 to be array, null given in /usr/local/hestia/web/list/dns/index.php on line 23" while reading response header from upstream, client: 1.1.1.1, server: _, request: "GET /list/dns/?domain=somedomain.com&token=f93e97387bbc484be203790233a7d9e6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "somedomain.com:8083", referrer: "https://somedomain.com:8083/list/dns/"
2022/05/24 22:38:04 [error] 2477790#0: *1785 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/hestia/web/templates/pages/list_dns_rec.html on line 80" while reading upstream, client: 1.1.1.1, server: _, request: "GET /list/dns/?domain=somedomain.com&token=f93e97387bbc484be203790233a7d9e6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "somedomain.com:8083", referrer: "https://somedomain.com:8083/list/dns/"
2022/05/25 15:38:00 [error] 2477790#0: *1817 FastCGI sent in stderr: "PHP message: PHP Warning:  ksort() expects parameter 1 to be array, null given in /usr/local/hestia/web/list/dns/index.php on line 23" while reading response header from upstream, client: 1.1.1.1, server: _, request: "GET /list/dns/?domain=somedomain.com&token=47da5817e7c056a432b4f8388a0182dd HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "somedomain.com:8083", referrer: "https://somedomain.com:8083/list/dns/"
2022/05/25 15:38:00 [error] 2477790#0: *1817 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/hestia/web/templates/pages/list_dns_rec.html on line 80" while reading upstream, client: 1.1.1.1, server: _, request: "GET /list/dns/?domain=somedomain.com&token=47da5817e7c056a432b4f8388a0182dd HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "somedomain.com:8083", referrer: "https://somedomain.com:8083/list/dns/"

**Comment by jaapmarcus** [comment]
Add behind:

https://github.com/hestiacp/hestiacp/blob/df1853531552469721806ea59bbe546487f3fa6e/web/list/dns/index.php#L22-L26
var_dump($data);

Load the page and tell what you see?

**Comment by jaapmarcus** [comment]
Also could you send met the contents of /usr/local/hestia/data/users/{username}/dns/{domain.conf} to  support@hestia.com or contact me at Discord  (https://discord.gg/nXRUZch)

**Comment by entropyideas** [comment]
Here is the output I was getting when dumping the data on the DNS page.

> array(6) { ["$some_domain1"]=> array(11) { ["IP"]=> string(14) "$main_ip" ["TPL"]=> string(7) "default" ["TTL"]=> string(4) "3600" ["EXP"]=> string(10) "2023-01-23" ["SOA"]=> string(19) "ns1.$nsdomain" ["SERIAL"]=> string(10) "2022052304" ["SRC"]=> string(0) "" ["RECORDS"]=> string(2) "19" ["SUSPENDED"]=> string(2) "no" ["TIME"]=> string(8) "01:06:58" ["DATE"]=> string(10) "2022-01-23" } ["glowingseo.co"]=> array(11) { ["IP"]=> string(14) "$main_ip" ["TPL"]=> string(7) "default" ["TTL"]=> string(4) "3600" ["EXP"]=> string(10) "2023-04-21" ["SOA"]=> string(19) "ns1.$nsdomain" ["SERIAL"]=> string(10) "2022042104" ["SRC"]=> string(0) "" ["RECORDS"]=> string(2) "15" ["SUSPENDED"]=> string(2) "no" ["TIME"]=> string(8) "20:16:10" ["DATE"]=> string(10) "2022-04-21" } ["glowingseo.com"]=> array(11) { ["IP"]=> string(14) "$main_ip" ["TPL"]=> string(7) "default" ["TTL"]=> string(4) "3600" ["EXP"]=> string(10) "2023-04-18" ["SOA"]=> string(19) "ns1.$nsdomain" ["SERIAL"]=> string(10) "2022042001" ["SRC"]=> string(0) "" ["RECORDS"]=> string(2) "16" ["SUSPENDED"]=> string(2) "no" ["TIME"]=> string(8) "20:08:33" ["DATE"]=> string(10) "2022-04-18" } ["$some_domain2"]=> array(11) { ["IP"]=> string(14) "$main_ip" ["TPL"]=> string(7) "default" ["TTL"]=> string(4) "3600" ["EXP"]=> string(10) "2023-04-20" ["SOA"]=> string(19) "ns1.$nsdomain" ["SERIAL"]=> string(10) "2022042201" ["SRC"]=> string(0) "" ["RECORDS"]=> string(2) "16" ["SUSPENDED"]=> string(2) "no" ["TIME"]=> string(8) "03:56:45" ["DATE"]=> string(10) "2022-04-20" } ["$some_domain3"]=> array(11) { ["IP"]=> string(14) "$main_ip" ["TPL"]=> string(7) "default" ["TTL"]=> string(4) "3600" ["EXP"]=> string(10) "2023-04-21" ["SOA"]=> string(19) "ns1.$nsdomain" ["SERIAL"]=> string(10) "2022042201" ["SRC"]=> string(0) "" ["RECORDS"]=> string(2) "16" ["SUSPENDED"]=> string(2) "no" ["TIME"]=> string(8) "23:49:15" ["DATE"]=> string(10) "2022-04-21" } ["$ns_domain"]=> array(11) { ["IP"]=> string(14) "$main_ip" ["TPL"]=> string(7) "default" ["TTL"]=> string(4) "3600" ["EXP"]=> string(10) "2023-01-23" ["SOA"]=> string(19) "ns1.$nsdomain" ["SERIAL"]=> string(10) "2022042204" ["SRC"]=> string(0) "" ["RECORDS"]=> string(2) "18" ["SUSPENDED"]=> string(2) "no" ["TIME"]=> string(8) "01:29:13" ["DATE"]=> string(10) "2022-01-23" } }

I went and emailed you the requested file along with what I did to fix the issue. Somehow a tab space was added to one of the CNAME records and caused the domain's DNS records to not display . I had to manually edit /usr/local/hestia/data/users/{username}/dns/{domain.conf} and delete the tab space and everything displayed correctly then.

**Comment by jaapmarcus** [comment]
I think there was an issue with input validation in the past. I know we added multiple checks for it so it should never happen. 

I will close the issue and need to monitor in the future...
