### ISSUE TITLE
[Bug] Domain left suspended after v-change-domain-owner

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#2617]
### Describe the bug

I just used v-change-domain-owner to switch a domain from one user to another. It successfully moved the web and mail domains, and their config, but it left the domain as suspended. i.e when you try to visit the domain you get the Suspended page, but inside HestiaCP, it is reported as normal.
The fix was to log into Hestia and Suspend it, then Unsuspend it. But I think that’s probably not the intended way of doing things …

Thread here. 
https://forum.hestiacp.com/t/v-change-domain-owner-leaves-domain-suspended/6419

### Tell us how to replicate the bug

v-change-domain-owner USER DOMAIN

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

Current

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Found the issue

**Comment by jaapmarcus** [comment]
Adding web_data=$(echo "$web_data" | sed "s/SUSPENDED='no'/SUSPENDED='yes'/")

just after

    if [ -n "$ip" ]; then
        web_data=$(echo "$web_data" | sed "s/IP='$IP'/IP='$ip'/")
    fi

Will solve your issue. How ever found more problems with dedicated ips. Working on a solution for that
