### ISSUE TITLE
[Feature] [Bug] Replace Rainloop Webmail with Rainloop fork Snappymail

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#2620]
### Describe the feature or change in detail

according to the thread link below on the Hestia forum. Rainloop doesn't look like its actively being maintained and there is an unpatched XSS flaw running around since October last year, there is currently a fork called Snappymail which is actively being developed and has many more modern features. It looks to be a drop in replacement

Forum Link
https://forum.hestiacp.com/t/remove-rainloop/6424/3

Comparison
[https://snappymail.eu/comparison.html](https://snappymail.eu/comparison.html)

Github
[https://github.com/the-djmaze/snappymail](https://github.com/the-djmaze/snappymail)

### Would you like to sponsor this feature to have it implemented?

No

**Comment by the-djmaze** [comment]
Added draft code for you ;)

https://github.com/the-djmaze/snappymail/tree/master/integrations/hestiacp

**Comment by hloza** [comment]
Hello, @the-djmaze im going to use your script to replace rainloop with snappy, any special thoughts before i proceed? i will use the official script to unninstall current rainloop and then execute this.

**Comment by the-djmaze** [comment]
> any special thoughts before i proceed

No, just try. I have no idea if it works.

**Comment by the-djmaze** [comment]
Jaapmarcus has fixed/improved my attempt.
It is ready for v1.8 #3590

**Comment by jaapmarcus** [comment]
Forgot to close this one
