### ISSUE TITLE
[Bug] Mysql 8 | Unable to store encoded password in mysql.conf

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2622]
### Describe the bug

When storing password generated via mysql8 (external server) sometimes.

It was also for me the last "issue" to get mysql8 support working for Hesita.

If we install the server our self we can enable legacy passwords how ever it doesn't help you if you have to use a server that you don't control... 

### Tell us how to replicate the bug

Add mysql8 server to the database options  and create a database in some rare cases it will break

### Which components are affected by this bug?

Control Panel Command Line Interface, Control Panel Web Interface, Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.5.x

### Operating system

N/A

**Comment by ManuelReschke** [comment]
You mean when the mysql8 server is installed on a seperate server? Or what exactly is the problem.

**Comment by jaapmarcus** [comment]
Install Mysql 8 on  the same server or on remote / separate server. It still doesn't matter the new "password" hash they return break Hestia it self

**Comment by jaapmarcus** [comment]
Issue has been fixed :)
