### ISSUE TITLE
[Bug] Wildcard SSL failed with Hestia DNS cluster

### ISSUE THREAD

**Issue by Scan4u** [hestiacp/hestiacp#2623]
### Describe the bug

Hello! I use with my pleasure your Hestia panel on my home Ubuntu server + few additional Hestia dns-cluster secondary NS VM servers in Oracle Cloud.

Yesterday i tried to create the Wildcard SSL for 'hestia.tld' domain on my local home server - and was failed with this (repited many tries/time's) error:
![snap397](https://user-images.githubusercontent.com/16424225/170667599-661f5b2e-1430-418e-81bf-9f4ea0839bb0.jpg)
So I check all possible issues from [this post](https://docs.hestiacp.com/admin_docs/web/ssl_certificates.html#error-let-s-encrypt-validation-status-400) - switched the HSTS, HTTPS redirection, IPv6 - no result.

Than I checked the  /var/log/hestia/LE-user-hestia.tld.log and found this issue:
![snap396](https://user-images.githubusercontent.com/16424225/170667620-4e475fd5-836f-4f44-b010-2e595806bf83.jpg)

Seems that during the secondary Acme validation LE got the old acme.txt NS record from one of my secondary Hestia cluster-dns servers, which are much faster than home server (ping, and ssd vs hdd). So, at the moment of Acme validation the correct txt is present only on main home server, but not updated at the remote dns-cluster machines in cloud - and we get a 400 error!

The solution was very "elegant" - I temporary switched off all remote cloud dns-cluster machines - and got the Wildcard SSL cert from the first try! :)

Is it possible to add the preliminary DNS sync/check for the mentioned validation Acme txt record to the remote dns-cluster machines before the starting of the Wildcard LetsEncrypt validation?

### Tell us how to replicate the bug

-

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.5.15

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
After line:
https://github.com/hestiacp/hestiacp/blob/8936df60dbd189a33c44712c5c06cfe1e817517d/bin/v-add-letsencrypt-domain#L294-L295

Add:

```
if [ -n "$DNS_CLUSTER" ]; then
    $BIN/v-sync-dns-cluster 
fi
```

And then try.

**Comment by Scan4u** [comment]
Thank U for the fast reply and working solution! :)

Made all changes:

![зображення](https://user-images.githubusercontent.com/16424225/170674942-fdd88ff3-42ef-44e2-bbd4-86b85e5254f7.png)

And got the Wildcard from the first try! :) 👍 

![зображення](https://user-images.githubusercontent.com/16424225/170675020-ce7d126c-f081-4571-a89f-780251fa3b90.png)

Waiting of SSL certificate was much more longer than usual (~3-4 min). I even thought that system hanged...
Maybe the reason is in more than 300 NS records - so the sync/update to mentioned 3 cloud servers take some time.

Is it possible to sync only single acme txt challenge record instead of the whole dns?

**Comment by jaapmarcus** [comment]
Yes it should be but at least it confirms the "fix" what I had..

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2624

Should fix it please test it out.

**Comment by Scan4u** [comment]
Working perfect! 👍 

![зображення](https://user-images.githubusercontent.com/16424225/170705586-e4921939-122f-491a-8317-a29bab499858.png)
