### ISSUE TITLE
[Feature] Show Owner & Permissions Data (File Manager)

### ISSUE THREAD

**Issue by alexgarciab** [hestiacp/hestiacp#2625]
### Describe the feature or change in detail

It would be great if the owner of files / folders and the permissions associated to files / folders is shown in the File Manager as as column. Right now there are 3 columns: Name, Size & Time.

Also, it would be nice if we can modify the owner & permissions within the File Manager.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We use Filegator (https://github.com/filegator/filegator). See https://github.com/filegator/filegator/issues/112 that  created over 2 years ago

Also https://github.com/hestiacp/hestiacp/issues/1604
