### ISSUE TITLE
[Bug] LetsEncrypt update fails for wildcard subdomain

### ISSUE THREAD

**Issue by shizualand** [hestiacp/hestiacp#2626]
### Describe the bug

Validation if the alias still exists in web.conf for wildcard subdomain `*.domain.com` fails in `v-update-letsencrypt-ssl:85`:
```
            # Loop through all crt aliases
            for alias in ${aliases//,/ } ; do
                # Validate if the alias still exists in web.conf
                if [[ "$ALIAS" =~ $alias ]]; then
                    f_aliases+="$alias,"
                fi
            done
```

Reason: 
`if [[ "*.domain.tld" =~ *.domain.tld ]]` returns  2 exit code due to regexp nature of the right part after `=~` by bash logics.

Can be easily fixed by supporting `$alias` with doublequotes:
`if [[ "*.domain.tld" =~ "*.domain.tld" ]]` returns 0 exit code

As from my understanding, should be fine for other aliases as well, for instance:
`[[ "aaa.domain.tld,bbb.domain.tld" =~ "aaa.domain.tld" ]]` will still return 0 exit code

As it comes from current github code -- issue applies to  `beta/1.6.0` as well

### Tell us how to replicate the bug

1. Add domain with a wildcard alias and Let's encrypt support
2. Let's encrypt will be generated for `"DNS:*.domain.tld, DNS:domain.tld"` and works fine
3. Wait until the certificate is expired
4. When `v-update-letsencrypt-ssl` launches to update certificate it will not validate `*.domain.tld` as such in web.conf, therefore is not included for renewal.
5. New certificate will be issued just for `"DNS:domain.tld"`

### Which components are affected by this bug?

Control Panel Backend, Let's Encrypt SSL

### Hestia Control Panel Version

1.5.15

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Can confirm the issue

**Comment by jaapmarcus** [comment]
> Reason: `if [[ "*.domain.tld" =~ *.domain.tld ]]` returns 2 exit code due to regexp nature of the right part after `=~` by bash logics.
> 

"*.domain.com" will not work as it will get match literally instead as an regex.  See screenshot from shell check

<img width="594" alt="Screenshot 2022-05-27 at 21 43 48" src="https://user-images.githubusercontent.com/9754650/170779644-98277bfd-dc2b-4f63-a22c-f8c2e71f0796.png">

We need to find a better solution

**Comment by jaapmarcus** [comment]
See attached PR for working fix but your fixed worked fine:

Existing Letsnecrypt test went fine:

 ✓ [ User ] Create new user 
 ✓ [ DNS ]Create DNS domain 
 ✓ [ Web ] Create web domain 
 ✓ [ Web ] Request new certificate for web domain 
 ✓ [ Mail ] Create mail domain 
 ✓ [ Mail ] Request new Certificate for Mail Domain 
 ✓ [ All ] Run renewal script for LE 
 ✓ [ Web ] Delete web ssl 
 ✓ [ Mail ] Delete mail ssl 
 ✓ [ Web ] Delete web  domain 
 ✓ [ Redirect ] Create web domain 
 ✓ [ Redirect ] Add Domain redirect to other website 
 ✓ [ Redirect ] Request new certificate for web 
 ✓ [ Redirect ] Run renewal script for LE Redirected domain 
 ✓ Delete user

**Comment by shizualand** [comment]
Have to admit I'm neither a bash guru, nor fully understanding hestiacp internals. 
So just hope someone will join to rule it out.

As from my understanding - this line should check whether 
`$ALIAS` (aliases, separated by comma, that were found from `web.conf`) 
contains
`$alias` (each single alias pulled by `DNS=` from `domain.crt` file)

And I doubt that  =~ and `$alias` as a regexp should be used here in the firstplace.
At least it should be surrounded by ^ $ for exact match, as within current realization it makes a couple of false-matches as well:
```
if [[ "foobar.domain.tld" =~ bar.domain.tld ]] ; then echo "match!"; fi
match!
```

Suppose, that something like forming an array and checking if it contains exact value would be better:
https://stackoverflow.com/questions/3685970/check-if-a-bash-array-contains-a-value

May be I'm mistaken on the way of how `$ALIAS` works, 'cause it seems to be determined somewhere in `main.sh` or in other included\sourced scripts. I'll try to find out myself, but if someone can tell - it would be helpful.

**Comment by jaapmarcus** [comment]
In case of Wildcard: 
ALIAS will contain: "*.demo.com"  and "alias" fetched from the certificate should also contain 

When the user doesn't use an wildcard but specifies all subdomains:

"user1.demo.com,user2.demo.com,website2.com,website3.com,demo4.demo.com" and so on alias form the certificate should also contain the same values. 

If a user removes "website3.com" from the alias list as it not wanted it will fail. This check made sure that  the alias still existed and if not good removed form the certificate genaration query.

As the string "alias" needed to beexact in in the string and no regex was used it really didn't matter to use "$ALIAS" =~ "$alias" and you but report was fine. 

I just need a few minutes to test if it  wouldn't break the other cases... Otherwise we would introduce a new bug for all our users..

**Comment by shizualand** [comment]
I'm afraid that quoted `"$alias"` is still vulnerable to false-matches as already described:
```
# $alias without quotes
if [[ "foobar.domain.tld" =~ bar.domain.tld ]] ; then echo "match!";fi
match!
# "$alias" with quotes
if [[ "foobar.domain.tld" =~ "bar.domain.tld" ]] ; then echo "match!";fi
match!
```
by that means, if user created both `foobar.domain.tld` and `bar.domain.tld`
and then deleted `bar` from web.conf - it will still match into `foobar` and thus will be renewed.

So it is more related to the validation method in global, rather than just to wildcards: opening it as a separate issue may make some sense.

**Comment by jaapmarcus** [comment]
```
 ✗ [ All ] Remove alias and update ssl
   (from function `refute_output' in file test_helper/bats-assert/src/refute_output.bash, line 173,
    in test file letsencrypt.bats, line 72)
     `refute_output' failed
   
   -- output non-empty, but expected no output --
   output : Error: domain alias bar.domain.org doesn't exist
   --
   
```

**Comment by jaapmarcus** [comment]
As ALIAS is an comma separated list:

```
if [[ ",$ALIAS," =~ ",$alias," ]]; then
```

root@dev:/usr/local/hestia/test# bats letsencrypt.bats 
 ✓ [ User ] Create new user 
 ✓ [ DNS ]Create DNS domain 
 ✓ [ Web ] Create web domain 
 ✓ [ Web ] Request new certificate for web domain 
 ✓ [ Mail ] Create mail domain 
 ✓ [ Mail ] Request new Certificate for Mail Domain 
 ✓ [ All ] Run renewal script for LE 
 ✓ [ All ] Remove alias and update ssl 
 ✓ [ Web ] Delete web ssl 
 ✓ [ Mail ] Delete mail ssl 
 ✓ [ Web ] Delete web  domain 
 ✓ [ Redirect ] Create web domain 
 ✓ [ Redirect ] Add Domain redirect to other website 
 ✓ [ Redirect ] Request new certificate for web 
 ✓ [ Redirect ] Run renewal script for LE Redirected domain 
 ✓ Delete user 

Haven't tested it yet with wildcard

**Comment by shizualand** [comment]
```if [[ ",$ALIAS," =~ ",$alias," ]]; then```
seems fine: should work well for wildcards and doesn't lead to false matches as per tests I've made.
