### ISSUE TITLE
[Bug] Create website with www prefix

### ISSUE THREAD

**Issue by bessone** [hestiacp/hestiacp#2632]
### Describe the bug

I need to have two separate websites for example.com and www.example.com.

Hestia doesn't let me do that, when I create a website with www.example.com to save www. is removed and the website is saved as example.com

Doing a search in the code I saw that it is the **fomat_domain** function that removes the www prefix.
https://github.com/hestiacp/hestiacp/blob/d5ff1d0d40e465ef60bffb54b48ae0b43f408acf/func/main.sh#L1353

Is there an alternative to be able to create a website with the prefix www (not as an alias)?
Or could you remove this forcing by making the choice of whether or not to remove the www prefix optional?

Thanks!

### Tell us how to replicate the bug

1. Click on Web tab.
2. Click on Add Web Domain
3. Use **www.example.com** as Domain
4. Click Save
5. The saved domain domain is **example.com** and not **www.example.com**

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.5.15

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
For the 1 in less than 1000 use cases do we need to make an exception?

Use the following trick:

```
v-add-web-domain jaap testkees.nl
v-change-web-domain-name jaap testkees.nl www.testkees.nl
# Adds by default testkees.nl as alias for www.testkees.nl
v-delete-web-domain-alias jaap www.testkees.nl testkees.nl
v-add-web-domain jaap testkees.nl
```

```
www.testkees.nl xxxx default no 0 0 no 2022-05-30
testkees.nl xxxx default no 0 0 no 2022-05-30
```

Works fine

**Comment by bessone** [comment]
Commenting the function piece is what I tried as a first test, it works, but I have to replicate in the web version as well, where I saw that the replace is done in PHP.

But I have a problem with Let's Encrypt certificates, this happens to me:
```
v-add-letsencrypt-domain 'test' 'www.test.example.com'
**Error: web domain test.example.com doesn't exist**
```

but I have not found a trace of the format_domain, any clue?

**Comment by bessone** [comment]
> 
Without modifying the main.sh it works, but only on the first creation.

If then (from the web) I try to modify the website I get the message:
**Error: web domain testkees.nl doesn't exist**

**Comment by jaapmarcus** [comment]
Edit, delete and so also does the same check as above. 

If we want to remove this behaviour we need to make some changes..

https://github.com/jaapmarcus/hestiacp/tree/fix/2632-allow-www

**Comment by jaapmarcus** [comment]
I am sure one of the other functions use the same behaviour as v-add-web-domain to remove the www check

**Comment by bessone** [comment]
I found why the SSL certificate is not generated, there is a www replace here too:
https://github.com/hestiacp/hestiacp/blob/d5ff1d0d40e465ef60bffb54b48ae0b43f408acf/bin/v-add-web-domain-ssl#L29

**Comment by jaapmarcus** [comment]
Question to be asked do we need to change this behaviour:

Web browsers are already removing the www. by default for example: Safari: www.youtube.com becomes youtube.com 

I don't know how many users want to have a different behaviour. But you are the first person to asks this with over 25K server installs.

**Comment by bessone** [comment]
> Web browsers are already removing the [www](http://www/). by default for example: Safari: [www.youtube.com](http://www.youtube.com/) becomes youtube.com

Perhaps for this reason a hard-coded reference to the www could be removed, leaving users free to manage the hostname without limitations.

But I understand that for many users it is transparent and they do not even realize they have to manage the www, as many sys admins always forget the automatic redirect between www and non www. 
I have expressed my need, I understand that it is a limited case.

**Comment by ManuelReschke** [comment]
If all is discussed please close this issue @bessone @jaapmarcus

**Comment by asika32764** [comment]
+1 

I think this is important, many clients did not noticed that www and non-www should be same domain, they may use them on different usages. 

Describe of argue to them about how www works is unhelpful, no one wants to be educated about the basic internet theory, they just wants us to solve their problem.

If HestiaCP can allow managers to configure it, it will be very helpful.
