### ISSUE TITLE
[Feature] Mark or change email subject with: ***SPAM***

### ISSUE THREAD

**Issue by gtavargas** [hestiacp/hestiacp#2642]
### Describe the feature or change in detail

Greetings, I don't see where it is configured in the exim so that it marks or changes the subject of the mail with: *** SPAM *** when it is detected as spam.

//I do it like that:
-Create the file called spam-subject.filter located /etc/exim/ and add:
nano /etc/exim/spam-subject.filter

`if $header_X-Spam-Score matches "^[^-0][0-9\.]+" and ${sg{$header_X-Spam-Score:}{\\.}{}} is above 65`
`#if $h_X-Spam-Flag: contains "YES"`
`#if $h_X-Spam-Status: contains "spam"`
`#if $header_X-Spam-Score matches "^[^-0][0-9\.]+"`
`then`
`     headers add "Old-Subject: $h_subject"`
`     headers remove "Subject"`
`     headers add "Subject: [*** SPAM ***] $h_old-subject"`
`     headers remove "Old-Subject"`
`endif`

-Edit the file: exim.conf or exim4.conf.template located /etc/exim/
- Search:
`acl_smtp_mime = acl_check_mime`
- add:
`#CHANGE SUBJECT OF EMAIL MARKED AS SPAM`
`system_filter = /etc/exim/spam-subject.filter`
`#CHANGE SUBJECT OF EMAIL MARKED AS SPAM`

- stays like this
`acl_smtp_mime = acl_check_mime`
`#CHANGE SUBJECT OF EMAIL MARKED AS SPAM`
`system_filter = /etc/exim/spam-subject.filter`
`#CHANGE SUBJECT OF EMAIL MARKED AS SPAM`

If it is not implemented, could it be included? or is it currently?

Thanks.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Will get added in 1.6

https://github.com/hestiacp/hestiacp/blob/main/install/deb/exim/system.filter

**Comment by gtavargas** [comment]
OK, got it.
