### ISSUE TITLE
Support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by devsdocs** [hestiacp/hestiacp#2648]
### Describe the feature or change in detail

great CP, host my few site on it. 
any information when hestiacp can be installed on Ubuntu 22.04 LTS? thank you.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/beta-hestia-1-6-0-help-wanted/6163/79

**Comment by jaapmarcus** [comment]
22.04 is ready we will publish the last rc version today the beta server if no error are found  with in the next 1 or 2 week release...
