### ISSUE TITLE
[Bug] Generate HestiaCP server template

### ISSUE THREAD

**Issue by gtavargas** [hestiacp/hestiacp#2650]
### Describe the bug

Hello,

I would like to generate a template of a hestiaCP server so as not to have to implement VPS servers for each client and save some time, but when I change the name and domain of the server and put the final data of the client, the load of the web administration of the HestiaCP server starts to take a long time to go from menu to menu and it's already too long, on average 15 to 30 seconds or more.

Example
Old Domain:
olddomain.com

New Domain:
mydomains.com

Old Server Name:
template.olddomain.com

New server name:
vps-client.mydomains.com

I have tried several things but nothing improves this symptom:
https://help.clouding.io/hc/en/articles/4406606413202-Reconfigure-the-IP%C3%B3n-address-in-HestiaCP

Nothing beats the slowness of HestiaCP web administration

Thanks.

### Tell us how to replicate the bug

Commands Examples:
v-update-sys-ip 90.60.44.11
v-change-sys-hostname vps-client.mydomains.com

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.5.15

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
I'm not able to reproduce the issue, as you've already created a forum post aswell, I would suggest to leave the discussion there.

**Comment by gtavargas** [comment]
Thanks.
