### ISSUE TITLE
[Feature] Remove plain text password from welcome email

### ISSUE THREAD

**Issue by AlecRust** [hestiacp/hestiacp#2651]
### Describe the feature or change in detail

When I set up a new HestiaCP I get this email:

```
Congratulations!

You have successfully installed Hestia Control Panel on your server.

Ready to get started? Log in using the following credentials:

Admin URL: https://111.222.333.15:8083
Username: admin
Password: PLAIN TEXT PASSWORD VISIBLE HERE
```

Sending passwords in emails is bad practice, and feels unnecessary here, as I set this password when installing HestiaCP.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ManuelReschke** [comment]
And why do you think is it bad to see the correct password again? I think the password is not stored in plain text in the db.

**Comment by AlecRust** [comment]
https://plaintextoffenders.com/

**Comment by ScIT-Raphael** [comment]
Hestia does NOT store any password in plain text (expect for pws in /usr/local/hestia/conf), it will be encrypted. What he probaly means, is that as soon as the user adds the password to the installer string, it should not be transmitted anymore - this could be implemented.

**Comment by jaapmarcus** [comment]
User did enter the password it self so there should be no reason to repeat it . If it is an generated password we inform the user to "change" the password after first login. Maybe we are able to enforce this rule somehow

**Comment by ifaist0s** [comment]
> Hestia does NOT store any password in plain text (expect for pws in /usr/local/hestia/conf), it will be encrypted. What he probaly means, is that as soon as the user adds the password to the installer string, it should not be transmitted anymore - this could be implemented.

Totally agree on this. If the user is savvy enough to put the pass on the command line installation string, then there is no need to send it over via email. Email systems and MTAs are not always configured to handle email securely :(

**Comment by jaapmarcus** [comment]
I hope this works?

```
    Admin URL:  https://test.xxxx.xxx:8083
    Username:   admin
    Password:   The password you chose during installation.
 ```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2706
