### ISSUE TITLE
[Bug] hst login not secure

### ISSUE THREAD

**Issue by Philius** [hestiacp/hestiacp#2652]
### Describe the bug

I believe I followed the install process correctly.
I added/changed my domains DNS records, including a CNAME for hst.<domain> that points to <domain>
My web site works with https correctly., even redirecting from www.<domain> to <domain>
But when I log in to
  hst.<domain>:8083/login/
Google Chrome states that the certificate is invalid, even though it was for <domain> issued by letsencrypt.

### Tell us how to replicate the bug

I also noticed the same problem with the domain alias www.<domain>
I removed the alias www.<domain> for the web site, saved and added it again.
Now www.<domain> works and is redirected to <domain>.

I tried v-add-letsencrypt-host but no change.

The message:
`This server could not prove that it is hst.<domain>; its security certificate is from <domain>. This may be caused by a misconfiguration or an attacker intercepting your connection.
`
Adding a CNAME record for hst.<domain> didn't seem to make a difference.

Also, I can't find the version of hestia installed, not even on the control panel, maybe I missed something.
I downloaded / installed it on June 7th 2022, so v1.5.15.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.5.15

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
Have a look at https://docs.hestiacp.com/admin_docs/web/ssl_certificates.html#how-to-setup-let-s-encrypt-for-the-control-panel

**Comment by Philius** [comment]
I just tried hst.<domain>:8083 with Firefox.
The message:
`Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for hst.\<domain\>:8083. The certificate is only valid for the following names: \<domain\>, www.<domain\>
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN`

I tried adding hst.<domain> to the web server aliases but got:
`Error: WEB_ALIASES limit is reached :: upgrade user package`

**Comment by ScIT-Raphael** [comment]
We dont provide support over github, please switch over to forum or discord.

**Comment by Philius** [comment]
It's on the forum [here](https://forum.hestiacp.com/t/adding-hst-domain-to-letsencrypt/6575).
