### ISSUE TITLE
[Feature] add debian testing configuration

### ISSUE THREAD

**Issue by Potterli20** [hestiacp/hestiacp#2655]
### Describe the feature or change in detail

add debian testing configuration
This is my problem.
`Welcome to the Hestia Control Panel installer!

Please wait, the installer is now checking for missing dependencies...

[ * ] Installing dependencies...

Installation aborted
====================================================================
ERROR: Install script version does not match package version!
Please download the installer from the release branch in order to continue:

https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

To test pre-release versions, build the .deb packages and re-run the installer:
  ./hst_autocompile.sh --hestia branchname no
  ./hst-install.sh .. --with-debs /tmp/hestiacp-src/debs`

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/development/panel.html#

or https://forum.hestiacp.com/t/beta-hestia-1-6-0-help-wanted/6163

We can add link to the information but the include information should be enough

**Comment by Potterli20** [comment]
Ok, ok, but my machine is Debian Test, and some nginx don't officially have tests, so I had to reinstall the system and go back to Debian 11



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Jaap ***@***.***> |
| Date | 06/14/2022 14:42 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [hestiacp/hestiacp] [Feature] add debian testing configuration (Issue #2655) |

https://docs.hestiacp.com/development/panel.html#

or https://forum.hestiacp.com/t/beta-hestia-1-6-0-help-wanted/6163

We can add link to the information but the include information should be enough
