### ISSUE TITLE
[Bug]  When I update a DNS entry it does not propagate until I restart bind9

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2657]
### Describe the bug

When I update a DNS entry it does not propagate until I restart bind9

### Tell us how to replicate the bug

Login to a random user.
Create a DNS record under that user.

Check with a propagation tool such as: [dnschecker.com](https://dnschecker.org)

It doesn't propagate.

It still doesn't...

log in via ssh

service bind9 restart

Check with a propagation tool such as: [dnschecker.com](https://dnschecker.org) -> Yay! it instantly propagated!

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.5.15

### Operating system

Debian 10.9

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/a8e5e29397b27abf5971b5c2197e88edaaab9ee0/web/add/dns/index.php#L171-L175

**Comment by jaapmarcus** [comment]
no should be changed to yes

**Comment by jaapmarcus** [comment]
Issue has been patched.

**Comment by jlguerrerosanz** [comment]
Always fast!
