### ISSUE TITLE
[SMTP error: [451] Temporary local problem] 

### ISSUE THREAD

**Issue by abradabra** [hestiacp/hestiacp#2662]
### Describe the bug

in EXIM LOG:
failed to expand ACL string "${eval:$acl_c_msg_limit / 2} / 1h / strict / $authenticated_id": error in expression evaluation: expecting number or opening parenthesis (after processing " ")

Еemporary solution:
comment 2 lines in /etc/exim4/exim4.conf.template

"#"  warn    ratelimit     = ${eval:$acl_c_msg_limit / 2} / 1h / strict / $authenticated_id
"#"  log_message           = Sender rate [limitlog]: log / email / $authenticated_id / $sender_rate / $sender_rate_period

and restart exim service

user$: cat  /usr/local/hestia/data/users/example/mail/example.domain.conf 

ACCOUNT='office' ALIAS='' AUTOREPLY='no' FWD='' FWD_ONLY='' MD5='{MD5}$1$Ri5E0scsEXAMPLE.' QUOTA='unlimited' U_DISK='52796' SUSPENDED='no' TIME='11:08:02' DATE='2022-03-05'
ACCOUNT='pr' ALIAS='' AUTOREPLY='no' FWD='' FWD_ONLY='' MD5='{MD5}$1$G13jEXAMPLE' QUOTA='unlimited' U_DISK='3' SUSPENDED='no' TIME='11:08:42' DATE='2022-03-05'

user$: cat /etc/exim4/domains/example.domain/limits 

office@example.domain:200
pr@example.domain:200

### Tell us how to replicate the bug

Just try to send any mail via roundcube interface after upgrade to 1.6.0 hestia version

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.0

### Operating system

Ubuntu 20.04

### Log capture

```shell
2022-06-17 10:11:13 H=localhost.localdomain (webmail.EXAMPLEDOMAIN) [127.0.0.1] F=<office@EXAMPLEDOMAIN> A=dovecot_login:office@EXAMPLEDOMAIN temporarily rejected RCPT <received@EXAMPLEDOMAIN>: failed to expand ACL string "${eval:$acl_c_msg_limit / 2} / 1h / strict / $authenticated_id": error in expression evaluation: expecting number or opening parenthesis (after processing " ")
```

**Comment by jaapmarcus** [comment]
I have no issues with 20.04 and an upgraded version. 

Can you please provide more information? 

Can you check /usr/local/hesita/data/users/{user}/mail/{domain.conf} 

And past the line with the user account?

**Comment by jaapmarcus** [comment]
And /etc/exim4/domains/{domain}/limits.conf

**Comment by abradabra** [comment]
> And /etc/exim4/domains/{domain}/limits.conf
added to description.

I think this may be due to the fact that I used to manually set limits for php-scripts and for SMTP by edit config file
/etc/exim4/exim4.conf.template

and most likely after upgrade to 1.6.0 my config broke.

So, if I replace all my config from repo:
https://github.com/hestiacp/hestiacp/blob/main/install/deb/exim/exim4.conf.template

think this will solve the problem.

But I have a question about the new config:
We have customizable ratelimit for SMTP
https://github.com/hestiacp/hestiacp/blob/d671204f0383e9fd8d2785f572ea87191a1983a7/install/deb/exim/exim4.conf.template#L142

but why we have hardcore ratelimit for PHP scripts?
https://github.com/hestiacp/hestiacp/blob/d671204f0383e9fd8d2785f572ea87191a1983a7/install/deb/exim/exim4.conf.template#L101

**Comment by abradabra** [comment]
This replace didn't work for me, because I changed it before:
https://github.com/hestiacp/hestiacp/blob/d671204f0383e9fd8d2785f572ea87191a1983a7/install/upgrade/versions/1.6.0.sh#L30

I will add it manually and now everything is fine.

But still a question:
Why not do the same customizable ratelimit for PHP-scripts, not only for SMTP?

**Comment by der-peer** [comment]
I can confirm, that "set acl_c_msg_limit" fails. The value is always empty (at least in my case), that's why division by 2 raises an error. I'm using Debian 10.

I'm not familiar with exim4-syntax, but I might see two possible problems, though I'm unable to come up with a solution:
- seems to me, "{1}" in the extract-statement should be "{2}" (the colon-separated values start counting with 1)
- the condition checks for existence of the "limits"-file, not for a valid value for the sender address inside it. So the fallback only drops in, if the limits-file can't be read/found, not in case when the extract-statement does not succeed.

**Comment by jaapmarcus** [comment]
See:
https://github.com/hestiacp/hestiacp/issues/2666

In this case custom changes where made and the replacement didn't work properly as it is no solved we keep tracking the issue in the other issue.
