### ISSUE TITLE
[Bug] All PHP sessions stopped working after Hestia upgrade 1.6.0. No errors, but unable to login anywhere.

### ISSUE THREAD

**Issue by rkkoszewski** [hestiacp/hestiacp#2663]
### Describe the bug

Seems like tonight my server got upgraded to Hestia 1.6.0 and right after that most of my hosted websites stopped working properly. I'm unable to login to most of the websites I'm hosting. The issue seems to be with PHP sessions, but I was unable to find any errors anywhere. 

Whenever I login in any of the websites, it just throws me back to the login screen again. I can see that a session cookie is created, but to me it looks like the session is empty or never properly created. (Nextcloud, and other scripts are affected, it does not seem to be a bug with the PHP script itself, as it was working perfectly fine yesterday and completely different scripts have the same issue, and no updates have been performed on these eider during the past month). 

I tried switching PHP versions 7.* and 8.*.. all had the same issue. It does seems that scripts like "Firefly III" are unaffected, but perhaps they use their own session implementation, not the default one from PHP.

I am able to login to the Hestia Control Panel though without any issues.

Could somebody suggest where I should start debugging this? I see no error in the *.error.log files. everything seems pretty normal. No changes have been performed on the server other than Hestia automatic upgrades and whatever cron jobs Hestia has running.

### Tell us how to replicate the bug

Upgrade to Hestia 1.6.0 and use PHP Sessions.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.0

### Operating system

Debian 11.3 (x86_64)

**Comment by ScIT-Raphael** [comment]
1.6.0 didnt contain any changes of the php session handling, this will be still done over the php process. I also just checked on a few of my servers and I'm not able to reproduce your issue, php sessions are working properly.

Also I'm able to login on a freshly installed nextcloud instance without any hassle. Can you maybe provide more informations? I'm not sure if the issue is related to the hestia update.

**Comment by jaapmarcus** [comment]
Check if /home/user/tmp/ is the owner?

**Comment by rkkoszewski** [comment]
> Check if /home/user/tmp/ is the owner?

I confirm that the "tmp" folder is owned by the respective user. I removed all existing sessions from that folder, and no matter what I do, no new sessions appears in that folder again. (I tried logging into the Nextcloud instance, even from an incognito tab, and no sessions are ever written to the "tmp" folder.). I get a new SESSION ID from what I could inspect in the cookies, but it never gets created in the "tmp" folder.

**Comment by jaapmarcus** [comment]
It is strange as we haven't modified anything related to php or the sessions. 


What happens when you run: `<?php exec('whoami',$output);  var_dump($output); ?>`

**Comment by rkkoszewski** [comment]
The php process is running under the correct user. But I think I just found the root cause...
Something has changed inside "/usr/local/hestia/data/templates/web/php-fpm". There is a new "php-fpm.bak" folder there.
I did customize some parameters here allowing access to the "/storage" folder in openbasedir in the past. This got copied all over the place for some reason during the update..

Before:
```
root@web:/usr/local/hestia/data/templates/web/php-fpm.bak# cat App-PHP-7_4.tpl
[%domain%]
listen = /run/php/php%backend_version%-fpm-%domain%.sock
listen.owner = %user%
listen.group = www-data
listen.mode = 0660

user = %user%
group = %user%

pm = ondemand
pm.max_children = 8
pm.max_requests = 4000
pm.process_idle_timeout = 10s
pm.status_path = /status

php_admin_value[upload_tmp_dir] = /home/%user%/tmp
php_admin_value[session.save_path] = /home/%user%/tmp
php_admin_value[open_basedir] = /home/%user%/web/%domain%/app:/home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt
php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@%domain%

php_admin_value[upload_max_filesize] = 80M
php_admin_value[max_execution_time] = 20
php_admin_value[post_max_size] = 80M
php_admin_value[memory_limit] = 256M

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /home/%user%/tmp
env[TMPDIR] = /home/%user%/tmp
env[TEMP] = /home/%user%/tmp
```

After:
```
root@web:/usr/local/hestia/data/templates/web/php-fpm# cat App-PHP-7_4.tpl
[%domain%]
listen = /run/php/php%backend_version%-fpm-%domain%.sock
listen.owner = %user%
listen.group = www-data
listen.mode = 0660

user = %user%
group = %user%

pm = ondemand
pm.max_children = 8
pm.max_requests = 4000
pm.process_idle_timeout = 10s
pm.status_path = /status

php_admin_value[upload_tmp_dir] = /storage/%user%:/home/%user%/tmp
php_admin_value[session.save_path] = /storage/%user%:/home/%user%/tmp
php_admin_value[open_basedir] = /home/%user%/web/%domain%/app:/home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/storage/%user%:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt
php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@%domain%

php_admin_value[upload_max_filesize] = 80M
php_admin_value[max_execution_time] = 20
php_admin_value[post_max_size] = 80M
php_admin_value[memory_limit] = 256M

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /storage/%user%:/home/%user%/tmp
env[TMPDIR] = /storage/%user%:/home/%user%/tmp
env[TEMP] = /storage/%user%:/home/%user%/tmp

```

See the "storage" folder is all over the place.. including the session temp folder.  That must be it.. what regex was used during upgrade here?? @ScIT-Raphael 


EDIT:
I just noticed that the storage folder is not even present in this config (before), pointing that this regex copied stuff from another of my custom configs into this one...

**Comment by jaapmarcus** [comment]
Only templates with the name:  PHP-x.x are suppost to get overwritten:

https://github.com/hestiacp/hestiacp/blob/2439db3cfd27db85ece9d3cd6f5cdbbc20d571ee/bin/v-update-web-templates#L49-L53

Also got a custom template and it was never changed:

```
eris@monitor:/usr/local/hestia/data/templates/web/php-fpm$ cat icingaPHP-7_4.tpl 
; origin-src: deb/php-fpm/multiphp.tpl

[%domain%]
listen = /run/php/php%backend_version%-fpm-%domain%.sock
listen.owner = %user%
listen.group = icingaweb2
listen.mode = 0660

user = www-data
group = icingaweb2

pm = ondemand
pm.max_children = 8
pm.max_requests = 4000
pm.process_idle_timeout = 10s
pm.status_path = /status

php_admin_value[upload_tmp_dir] = /tmp
php_admin_value[session.save_path] = /tmp
php_admin_value[open_basedir] = /home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/phppgadmin:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt:/etc
php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@%domain%

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
```

**Comment by jaapmarcus** [comment]
It looks like a "user" error. Please verify by creating new server and run v-update-sys-hestia-git hestiacp release it will . It should run the same commands during the update. Check if the custom template get overwritten...
