### ISSUE TITLE
[Bug] File Manager under Development Mode

### ISSUE THREAD

**Issue by xwtk** [hestiacp/hestiacp#2664]
### Describe the bug

**When opening the File Manager from the Control Panel, the title of the File Manager is showing as "_Development mode_"**
![image](https://user-images.githubusercontent.com/37484454/174310646-71489326-6780-4074-83c7-5348aaba40ca.png)

### Tell us how to replicate the bug

1. Login to an account (does not matter if it is an administrator or a standard user account)
2. Click Files
3. Check the title of the webpage

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.0

### Operating system

Ubuntu 20.04

**Comment by wojsmol** [comment]
This looks like a fm document_root is set incorrectly to the fm main folder instead of the `dist` sub-folder - see https://github.com/filegator/filegator/blob/master/docs/development.md#deployment

**Comment by xwtk** [comment]
Side note, the previous 1.5.15 version didn't have this issue.

**Comment by wojsmol** [comment]
@xwtk Hestia 1.6 is fisrt relase that uses version of filegator with that warning implemented.

**Comment by xwtk** [comment]
Got it

**Comment by jaapmarcus** [comment]
Strange:

```
        location /fm/ {
            alias /usr/local/hestia/web/fm/dist/;
            index index.php;
        }
```

**Comment by xwtk** [comment]
Nothing much I can say except that its happening :)
Maybe another setting?

**Comment by wojsmol** [comment]
Looking herder into this https://github.com/filegator/filegator/commit/3d008e4e7f8c89520c4cc87ec0e4a66174d54864 and `APP_ENV` is set to development by default https://github.com/filegator/filegator/blob/3f03a4096d9d895b1fba3b731e19028286a8853f/index.php#L12 so we need `sed` to update this line.

**Comment by xwtk** [comment]
Aha that could be the issue

**Comment by jaapmarcus** [comment]
For some reasons alias /usr/local/hestia/web/fm/dist/ is not working 

So it might something caused by the new nginx  version have no idea why

**Comment by vvcares** [comment]
I had the same issue upon auto updated to 1.6.0
Somehow, the update, messed with **/usr/local/hestia/web/fm/** (Contents of inside this folder was missing a lot of files)

Run this cmd:  v-add-sys-filemanager
But the page title still says (Development mode)
Ref: https://forum.hestiacp.com/t/1-6-where-did-the-file-manager-go/6599/2

**Comment by jaapmarcus** [comment]
We did update PCRE https://www.pcre.org

To the last version it looks like it is caused the issue but have no idea how to change it yet

**Comment by jaapmarcus** [comment]
It looks like it was never working as intended but only due to the addition of the new "Development" in title it was never discovered. 

See: https://serverfault.com/questions/694449/php-in-nginx-directory-alias-not-working

Adding:

```
        location /fm/ {
            alias /usr/local/hestia/web/fm/dist/;
        index index.php;

        location ~ /([^/]+\.php)$ {
           try_files /$1 =404;
           fastcgi_pass    unix:/var/run/hestia-php.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/local/hestia/web/fm/dist/index.php;
    }
    }
```

Will solve the issue. We need to consider if we want to release hestia-nginx_1.22.0-1 version or wait until Nginx releases 1.23.0 or 1.23.1

**Comment by jaapmarcus** [comment]
Issue has been solved and after rebuild of packages and republish them it will get sorted
