### ISSUE TITLE
[Bug] PHPMyAdmin SSO doesn't work after upgrade to 1.6.0

### ISSUE THREAD

**Issue by hmv47** [hestiacp/hestiacp#2665]
### Describe the bug

After upgrade, PHPMyAdmin SSO doesn't work, drops to PHPMyAdmin login page. Tried disabling/enabling it again. 
API config:
![img](https://user-images.githubusercontent.com/35002227/174354538-dffa545e-bc95-44bc-a4c8-1bcae0c7c5a6.png)

### Tell us how to replicate the bug

1. Try using PHPMyAdmin SSO

### Which components are affected by this bug?

Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.6.0

### Operating system

Ubuntu 20.04

### Log capture

```shell
[Fri Jun 17 09:03:28.535981 2022] [proxy_fcgi:error] [pid 142391:tid 140598013380352] [client 123.123.123.123:39828] AH01071: Got error 'PHP message: PHP Warning:  Unable to connect over API please check api connection in /usr/share/phpmyadmin/hestia-sso.php on line 55', referer: https://srv.domain.com:8083/
[Fri Jun 17 09:03:28.652030 2022] [proxy_fcgi:error] [pid 142391:tid 140598013380352] [client 123.123.123.123:39828] AH01071: Got error 'PHP message: phpmyadmin: Failed to load /var/lib/phpmyadmin/config.inc.php Check group www-data has read access and open_basedir restrictions.', referer: https://srv.domain.com:8083/
```

**Comment by hmv47** [comment]
Interestingly, all PHPMyAdmin files are in `/usr/share/phpmyadmin`, `/var/lib/phpmyadmin/` contains only `blowfish_secret.inc.php` and `tmp`. I am not sure if this is how it was before the upgrade but I didn't make any configuration changes after the upgrade.

**Comment by jaapmarcus** [comment]
Enable API access the PMA SSO uses the new api system

**Comment by hmv47** [comment]
Should it be enabled for admin only or for all users? Also, can legacy API be then disabled?

**Comment by jaapmarcus** [comment]
Only admin and yes

**Comment by hmv47** [comment]
This solved the problem. Maybe there should be a check in `v-add-sys-pma-sso` for this

**Comment by jaapmarcus** [comment]
There is allready a check for it in:

```
if [ "API_SYSTEM" = "0" ]; then 
    echo "Error: API is not enabled"
    exit 2
fi

```

Maybe it was an issue with the upgrade script it self
