### ISSUE TITLE
[Bug] Email account is sending too many emails - rate overlimit

### ISSUE THREAD

**Issue by mmoo9154** [hestiacp/hestiacp#2666]
### Describe the bug

The **Exim add custom ratelimits by user (#2225)** feature fails if the From email address doesn't match the Reply-To address (and the Reply-To address isn't a bona fide account).

For instance, if a client MTA tries to send an email through the smtpout@example.com account but with a noreply@example.com Reply-To value then the ratelimit condition will be tested with an illegal (blank) max message count value.  (See [exim ratelimit ACL syntax](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-access_control_lists.html#SECTratelimiting).)

You will see something similar to this message in `/var/log/exim4/rejectlog` if you are experiencing this issue:

`2022-06-17 17:28:38 H=(server-mta) [203.0.113.69] X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=no F=<noreply@example.com> A=dovecot_login:smtpout@example.com rejected RCPT <trobinson@example.com>: Email account smtpout@example.com is sending too many emails - rate overlimit = 83.6 / 1h`

As an interesting distraction, you will be able to successfully send the exact same email from the HestiaCP web email interface (e.g. https://webmail.example.com)).  It turns out that HestiaCP configures exim to accept all smtp rcpt commands if they come from the local host, so the bad ratelimit test is never hit when sending through the web email page.

### Tell us how to replicate the bug

1. Create an email account (e.g. smtpout@example.com).
   - Usually through the Hestia MAIL page (e.g. https://hestiacp.example.com/list/mail/?domain=example.com)
2. Ensure some other account doesn't exist (e.g. noreply@example.com) to use as the Reply-To address.
3. Use your favorite client MTA to send an email to anyone you wish (e.g. myself@example.com).
   - I was able to reproduce the failure with [SMTPer](https://www.smtper.net/) online SMTP tester.
4. Observe failure.

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.0

### Operating system

Ubuntu 20.04.4 LTS (x86_64)

### Log capture

```shell
2022-06-17 17:28:38 H=(server-mta) [203.0.113.69] X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=no F=<noreply@example.com> A=dovecot_login:smtpout@example.com rejected RCPT <trobinson@example.com>: Email account smtpout@example.com is sending too many emails - rate overlimit = 83.6 / 1h
```

**Comment by jaapmarcus** [comment]
@mmoo9154  if you have a fix as you said please submit a PR with the required changes

**Comment by luzik** [comment]
Yeah after upgrade to 1.6.0 I got same issue here

`Email account logs@domain.com is sending too many emails - rate overlimit = 1.0 / 1h`

I did not change any configuration. Just some emails stopped working. Please provide some workaround for this issue

**Comment by luzik** [comment]
Maybe it is related in my case that emails are send from alias email address?

**Comment by jaapmarcus** [comment]
Please check:

https://forum.hestiacp.com/t/weird-issue-since-last-automatic-update-of-hestia-email-email-aliases/6630/5

> Add in /etc/exim4/domains/{domain}/limits:
> 
> email@domain.com:200 and it will work. There is currently in the relay script When you have a different from adress then the actual account login in…

**Comment by jaapmarcus** [comment]
Please note this solution is no "great" and we still need a better solution. Ideally without updating limits file for each sending email address

**Comment by jaapmarcus** [comment]
Test where it doesn't work 

```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';

//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP();                                            //Send using SMTP
    $mail->Host       = 'xxxxx';                     //Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = 'info@xxxxx';                     //SMTP username
    $mail->Password   = 'xxxxx';                               //SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
    $mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    $mail->setFrom('info@xxxxx', 'Mailer');
    $mail->addAddress('me@xxxxx', 'Joe User');     //Add a recipient


    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
```

**Comment by jaapmarcus** [comment]
@mmoo9154  It seems that replacing:

`set acl_c_msg_limit = ${if exists{/etc/exim4/domains/${lookup{$sender_address_domain}dsearch{/etc/exim4/domains/}}/limits} {${extract{1}{:}{${lookup{**$sender_address_local_part@$sender_address_domain**}lsearch{/etc/exim4/domains/${lookup{$sender_address_domain}dsearch{/etc/exim4/domains/}}/limits}}}}} {${readfile{/etc/exim4/limit.conf}}} }`

with $authenticated_id seems to solve the issue

Only now I get now:

SMTP ERROR: RCPT TO command failed: 550-Verification failed for <noreply@xxxxx>
                   	                  550-Unrouteable address


Did some test with Hestia server and there I had no issues at all...

**Comment by mmoo9154** [comment]
I'm not sure why this bug was closed.  If it was closed as duplicate, it would be nice to see a reference to the controlling/duplicate bug.  If this is closed as fixed, it would be kinda nice to have the original author (me) have at least a notice and a chance to confirm the fix before closing.

**Comment by jaapmarcus** [comment]
Bug reports linked to a PR get closed on default after changes have been merged.

**Comment by jaapmarcus** [comment]
```
  deny    message       = Email account $authenticated_id is sending too many emails - rate overlimit = $sender_rate / $sender_rate_period
          set acl_c_msg_limit  = ${lookup {$authenticated_id} lsearch{/etc/exim4/domains/${lookup{${domain:$authenticated_id}}dsearch{/etc/exim4/domains/}}/limits}{$value}{DEFAULT_RATELIMIT}} 
          ratelimit     = $acl_c_msg_limit / 1h / strict/ $authenticated_id
   ```
 
 Works fine for outgoing mail

```
2022-06-23 12:20:28 1o4Jwq-002PFN-Bp <= info@viraal.org H=localhost (xxxxx) [127.0.0.1] P=esmtpa A=dovecot_login:info@xxxx S=586 id=22d2840d0c3bed1dbabc61184390f0d8@xxxx
2022-06-23 12:20:29 1o4Jwq-002PFN-Bp => me@sssss R=dnslookup T=remote_smtp H=aspmx.l.google.com [66.102.1.26] X=TLS1.3:ECDHE_X25519__ECDSA_SECP256R1_SHA256__AES_256_GCM:256 CV=yes K C="250 2.0.0 OK t19-20020a05600c199300b003974c0295a4si2663751wmq.8 - gsmtp"
```
How ever when I send a email from an external server (Gmail) 


```
2022-06-23 12:25:12 H=mail-qk1-f182.google.com [209.85.222.182] X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_128_GCM:128 CV=no SNI=mail.viraal.org F=<jaap@xxxxxx> temporarily rejected RCPT <info@xxxxx>: failed to expand ACL string "${lookup {$authenticated_id} lsearch{/etc/exim4/domains/${lookup{${domain:$authenticated_id}}dsearch{/etc/exim4/domains/}}/limits}{$value}{DEFAULT_RATELIMIT}}": failed to open /etc/exim4/domains//limits for linear search: No such file or directory
```

Offcourse my email.com does not exists on this server. That was my if statement was there

**Comment by jaapmarcus** [comment]
Issue is that incoming mail does not set $authenticated_id

```
  deny    message       = Email account $authenticated_id is sending too many emails - rate overlimit = $sender_rate / $sender_rate_period
          set acl_c_msg_limit  = ${if exists{/etc/exim4/domains/${lookup{${domain:$authenticated_id}}dsearch{/etc/exim4/domains/}}/limits}{${lookup {$authenticated_id} lsearch{/etc/exim4/domains/${lookup{${domain:$authenticated_id}}dsearch{/etc/exim4/domains/}}/limits}{$value}{${readfile{/etc/exim4/limit.conf}}}}}{${readfile{/etc/exim4/limit.conf}}} } 
          ratelimit     = $acl_c_msg_limit / 1h / strict/ $authenticated_id
```

Resolves the issue for most part...

**Comment by jaapmarcus** [comment]
https://github.com/jaapmarcus/hestiacp/commit/fbb2e69000b14cd3b9d70d34d10e792041c23931

Makes it easier to see the differences:

1. If statement make sure the domain exists in the system or if $authenticated_id is empty
2. Check if there is an value in /etc/exim4/domain/{domain}/limits  and if not fall back to default

Both have the same command:
${domain:$authenticated_id}}dsearch{/etc/exim4/domains/}}

But sadly it doesn't work without them on Debian 11 or Ubuntu 22.04
