### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HetviMP** [hestiacp/hestiacp#2667]
### Describe the bug

**https://ivps.webidea.co.in:9037/login/** This is my existing account but When I am going to this link it is showing 500 error and says "Internal Server Error".

Is it is my side BUG or your side ?
Please reply it is very important to us.

### Tell us how to replicate the bug

Please Review my BUG

### Which components are affected by this bug?

Control Panel Backend, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

Actually don't know

### Operating system

Actually don't know

**Comment by ScIT-Raphael** [comment]
Check the hestia service status, also check the related nginx hestia log in /var/log/hestia. Also please use our forum or discord channel for support requests, github is for reproducable bug reports only.
