### ISSUE TITLE
[Bug] Installer sieve

### ISSUE THREAD

**Issue by gtavargas** [hestiacp/hestiacp#2668]
### Describe the bug

Hello, I am installing a hestiacp today and it throws this error when I run the installer:

[ * ] Install Roundcube...
[ * ] Install Sieve...
ln: invalid option -- 'R'
Try 'ln --help' for more information.
[ * ] Configuring File Manager...

How serious could it be?

### Tell us how to replicate the bug

bash hst-install.sh --apache yes --phpfpm yes --multiphp no --vsftpd yes --proftpd no --named yes --mysql yes --postgresql no --exim yes --dovecot yes --sieve yes --clamav yes --spamassassin yes --iptables yes --fail2ban yes --quota yes --api yes --interactive yes --with-debs no  --port 8083 --hostname HESTIACP-CLI.DOMINIOCLIENTE.COM --email admin@HESTIACP-CLI.DOMINIOCLIENTE.COM --password 7***********g --lang en

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.6.0

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
https://github.com/hestiacp/hestiacp/pull/2675 Should fix the issue, report will be closed as soon as we have merged the PR.
