### ISSUE TITLE
Getting an error while trying to install Wordpress on Hestia Control Panel

### ISSUE THREAD

**Issue by mynewopportunities** [hestiacp/hestiacp#2673]
Getting an Database limit reached error.

Can someone please help me in this regard, I am trying to install Wordpress on my Hestia Control Panel.

![Database Error](https://user-images.githubusercontent.com/107834804/174540951-d900764b-2341-446e-8e44-8583a6ae4bfe.png)

My email is coresapservices@gmail.com

**Comment by jaapmarcus** [comment]
Admin users has no databases assigned to the user create a new user. It is for your own security!

**Comment by mynewopportunities** [comment]
Ok.
Thanks jaapmarcus for replying to my thread.

Actually I tried creating a new user, and tried to install Wordpress there also, but it gave me the same Database limit reached error.

Please kindly advise.

**Comment by jaapmarcus** [comment]
Make sure the package includes at least 1 mysql database

**Comment by mynewopportunities** [comment]
I think it doesn't have any database installed.

I see if I can install one.

Please stay in touch.

Thanks for your cooperation.

**Comment by mynewopportunities** [comment]
Same error. After selecting Php 8 from the dropdown menu.
![Database Error 2](https://user-images.githubusercontent.com/107834804/174545194-9dacbd13-4e18-4362-8240-0a4cd3670dd4.png)
![Database Error 3](https://user-images.githubusercontent.com/107834804/174545395-0eaabea5-8c8f-417a-a4d9-74b58d1da8e6.png)

**Comment by jaapmarcus** [comment]
You have still no databases assigned to the package. What package are you using?

**Comment by mynewopportunities** [comment]
Package?

**Comment by mynewopportunities** [comment]
![Database Error 4](https://user-images.githubusercontent.com/107834804/174545872-0636c417-a306-46b7-b2e9-f9f9d28297a3.png)

**Comment by mynewopportunities** [comment]
No package added.
![Database Error 5](https://user-images.githubusercontent.com/107834804/174546234-9b188179-f8b1-40ff-8491-454d5ab46e52.png)

**Comment by mynewopportunities** [comment]
Do we have a link to fill in all these details on own?
![Database Error 6](https://user-images.githubusercontent.com/107834804/174546695-8f5004f1-95ae-41cc-b6ab-0e0ac64837bb.png)

**Comment by jaapmarcus** [comment]
Assign the default package to any non admin user and it should work as it should. If it not working check If MariaDB is installed,

**Comment by mynewopportunities** [comment]
I have created an admin user.
How to check whether MariaDB is installed or not?

**Comment by mynewopportunities** [comment]
Created non admin user and installed php.

Now?
![Database Error 7](https://user-images.githubusercontent.com/107834804/174548436-8806bd63-361a-476b-96c0-18795ec2c1c3.png)

**Comment by jaapmarcus** [comment]
You should be able to install Wordpress via this user

**Comment by mynewopportunities** [comment]
Ok, I'll try now.

**Comment by mynewopportunities** [comment]
SWEET!!!
![Success](https://user-images.githubusercontent.com/107834804/174551221-392d673f-35dd-4b87-b4d0-319c11155bd6.png)

**Comment by mynewopportunities** [comment]
I want Nextcloud installation also.

Can I proceed in this same way for other non admin user?

**Comment by mynewopportunities** [comment]
I got the Welcome Email but the WPadmin page doesn't appear.
![Database Error 8](https://user-images.githubusercontent.com/107834804/174552238-640026d6-8a55-4504-87fe-bbb2551bc1bd.png)

**Comment by jaapmarcus** [comment]
Not an Hestia issue it self...

```
Nameserver: cruz.ns.cloudflare.com
Nameserver: roan.ns.cloudflare.com
DNSSEC: Unsigned

```

Disable proxy setup ssl and enable it again.

**Comment by ScIT-Raphael** [comment]
Please use our forum (https://forum.hestiacp.com) or discord channel for support requests, we try to handle only bug reports and feature requests over github.
