### ISSUE TITLE
[Bug] apache2 failed to restart mail every morning

### ISSUE THREAD

**Issue by sergix44** [hestiacp/hestiacp#2677]
### Describe the bug

Since the 1.6.0 update, I'm receiving an email with a strange content that apache2 failed to restart
![image](https://user-images.githubusercontent.com/4172890/174667517-f3b0edf9-6f24-411c-bdc7-e96d6e738a21.png)

### Tell us how to replicate the bug

Receive an email every morning to the admin email

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.0

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
I assume it slightly after the renewal of Lets encrypt?

https://github.com/hestiacp/hestiacp/commit/a5af334e91a7b0771d722adcae97de3e9849de93

Would be the issue then.

**Comment by jaapmarcus** [comment]
Also:
https://forum.hestiacp.com/t/daily-mail-apache2-restart-failed-containing-syntax-ok-since-hestia-1-6/6688/16

**Comment by jaapmarcus** [comment]
Please enable "DEBUG_MODE" in /usr/local/hestia/conf/hestia.conf by changing it to yes wait for the cronjob and check /var/log/hestia/debug.log after you have received the email

**Comment by ob-tk** [comment]
Same problem but with nginx.  I receive emails with a subject: nginx failed to restart.
In the body:
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

```

/var/log/hestia/debug.log :

```
[  2022-07-04 01:35:04 | nginx | WEB ]
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

```

Cronjob:
35 01 * * * sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl

**Comment by positivitie** [comment]
I have these emails also since the day after the 1.60 update.

**Comment by vvcares** [comment]
I have these emails also since the day after the 1.60 update.
