### ISSUE TITLE
[Bug] Create new LE cert fails on new dns records

### ISSUE THREAD

**Issue by justanthonylee** [hestiacp/hestiacp#2678]
### Describe the bug

I hope this is in the correct section. I created a new CNAME record on a domain to create a new certificate and got error 3 from the API, turns out the system due to a webpage script that does a DNS check made it get cached on that server so when the cert is made the checks inside of v-add-letsencrypt-domain make it fail on nslookup. I am using Cloudflare so update was really fast, from that point even the web UI failed every time until I looked into why it was failing.

This is all a result the nslookup fail inside v-add-letsencrypt-domain.

Would it be a good to maybe clear the DNS cache `sudo systemd-resolve --flush-caches` before doing a nslookup? Once I run this everything works as expected.

Line that does the lookup.

```
if ! nslookup "${identifier}" > /dev/null 2>&1 ; then
      check_result "$E_NOTEXIST" "DNS record for $identifier doesn't exist"
fi
```

I can totally do this via a script on run but I think having this done inside the panel would result in less failures and faster certificates.

### Tell us how to replicate the bug

Takes a few specific things, but for my replication it's make the domain, and check the certificate status on page load once the domain resolves and loads, and at that point creating a cert via v-add-letsencrypt-domain returns error 3.

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

v1.6.0

### Operating system

Ubuntu 20.04

**Comment by justanthonylee** [comment]
I was looking into a bit more and even local routers can be a problem, so a solution might be to use a faster updating dns provider for lookups like 1.1.1.1. So you can set `nslookup "${identifier}"` as `nslookup "${identifier}" 1.1.1.1` to do a CF lookup or even say use 8.8.8.8 (google) as a backup lookup.

**Comment by jaapmarcus** [comment]
root@dev:~# sudo systemd-resolve --flush-caches
Failed to flush caches: Unit dbus-org.freedesktop.resolve1.service not found.

Or 

root@test:/tmp/hestiacp-src/deb# systemd-resolve --flush-caches
systemd-resolve: command not found

It seems no installed by default...

```
nslookup "${identifier}" 1.1.1.1
```

Will  work fine but keep it as an alternative if the first check fails

**Comment by justanthonylee** [comment]
It appears to be installed by default on Ubuntu but yes not all systems will have the same system.

I think if first check fails using the 1.1.1.1 check would be a good alt.
