### ISSUE TITLE
[Bug] Type error if no aliases

### ISSUE THREAD

**Issue by illuminati0n** [hestiacp/hestiacp#2679]
### Describe the bug

Unsupported operand types: string * string in hestia/web/templates/includes/panel.html:128
![image](https://user-images.githubusercontent.com/5390485/174719540-5f4226fe-5e3f-40ec-8a10-6ecc22538fa8.png)
intval fix issue

### Tell us how to replicate the bug

1. Add one or more domains
2. Romove autogenerated aliases
3. Refresh page - Hestia return 500

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.0

### Operating system

Ubuntu 20.04.4

### Log capture

```shell
Unsupported operand types: string * string in hestia/web/templates/includes/panel.html:128
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/2671

Exactly the same issue only slightly different location
