### ISSUE TITLE
[Bug] Add Rebuild / restart after v-change-sys-php 

### ISSUE THREAD

**Issue by mortalys** [hestiacp/hestiacp#2681]
### Describe the bug

When php version, keeps connecting to previous version, after system reboot works

After discord community adding  *add rebuild web-domains + restart nginx / apache2 on the end* to **bin/v-change-sys-php** can fix the issue

### Tell us how to replicate the bug

1. Change/Add PHP version

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.0

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
See #2680
