### ISSUE TITLE
[Bug] v-change-sys-hostname does not fix /etc/hosts

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2683]
### Describe the bug

When I execute

```bash
/usr/local/hestia/bin/v-change-sys-hostname newhostname
```

to change the hostname name, the /etc/hosts file needs to be manually fixed.

If the new domain can not be solved by the dns, some systems can fail. And if the user is some sudoer user to login into the server, he will fail to login. 

### Tell us how to replicate the bug

1. setup fresh hetiacp under ubuntu 20.04 with hostname x
2. try to change the hostname with v-change-sys-hostname
3. check the /etc/hosts

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.6.0

### Operating system

ubuntu 20.04

### Log capture

```shell
Nothing.
```

**Comment by ScIT-Raphael** [comment]
fixed: https://github.com/hestiacp/hestiacp/commit/da9be94b007dbd1c14eebc2d8d9b9509ce7e91be
