### ISSUE TITLE
[Bug] Suspended website still serves urls with parameters.

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2695]
### Describe the bug

If you suspend a web domain, some urls are stil visible in wordpress.

Several wordpresses have been hacked and I am getting traffic from semrush with queries such as:

cat /var/log/apache2/domains/mydomain.com.log
185.191.171.2 - - [23/Jun/2022:02:49:25 +0200] "GET /?bestialized1364296_html HTTP/1.0" 200 12699 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"

I need to stop the hacker by suspending the website.

### Tell us how to replicate the bug

Login Hestia > Impersonate user > Web > Suspend domain.

visit: https://mydomain.com -> Error - Website is suspended
visit: https://mydomain.com/?sometexthere -> Shows https://mydomain.com

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6

### Operating system

Debian 11

### Log capture

```shell
185.191.171.15 - - [23/Jun/2022:02:49:04 +0200] "GET /?brumbie8883666_html HTTP/1.0" 200 12699 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
185.191.171.12 - - [23/Jun/2022:02:49:08 +0200] "GET /?deafanddumb7142349.html HTTP/1.0" 301 477 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
185.191.171.11 - - [23/Jun/2022:02:49:11 +0200] "GET /?deafanddumb7142349_html HTTP/1.0" 200 12699 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
185.191.171.2 - - [23/Jun/2022:02:49:15 +0200] "GET /?perturbedly41685646.html HTTP/1.0" 301 478 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
185.191.171.4 - - [23/Jun/2022:02:49:19 +0200] "GET /?perturbedly41685646_html HTTP/1.0" 200 12699 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
185.191.171.6 - - [23/Jun/2022:02:49:22 +0200] "GET /?bestialized1364296.html HTTP/1.0" 301 477 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
```

**Comment by jaapmarcus** [comment]
I assume you use both default templates

It might be an browser cache as If I try it to access it but it should not result in request to the webserver. 

Ideally we need to create new template and "force" them to the user to select him to make sure the website doesn't work any more. (As it is currently with  proxy template anyway)

**Comment by jlguerrerosanz** [comment]
So for now I have to suspend the user.

**Comment by jlguerrerosanz** [comment]
> I assume you use both default templates
> 
> It might be an browser cache as If I try it to access it but it should not result in request to the webserver.
> 
> Ideally we need to create new template and "force" them to the user to select him to make sure the website doesn't work any more. (As it is currently with proxy template anyway)

Yes! I need to trust that a suspended website doesn't work:
- Does not answer queries or only returns http error
- cannot execute php or interact with the database in any way
- all processes related to the web are stopped 
So I would apply that template and kill all the user's processes. My command of choice is "slay". Unfortunately you have to apt install it first.

**Comment by jaapmarcus** [comment]
Fixed
