### ISSUE TITLE
[Bug] Error: WEB_DOMAINS limit is reached :: upgrade user package

### ISSUE THREAD

**Issue by abeykp** [hestiacp/hestiacp#2698]
### Describe the bug

When trying to create a 2nd domain from the panel I receive this error
Error: WEB_DOMAINS limit is reached :: upgrade user package
I am using Debian 11.
![error](https://user-images.githubusercontent.com/16350275/175773754-0b61ca9d-74a6-4639-8897-c01e3af5c1f5.PNG)

### Tell us how to replicate the bug

1. Click on Web Tab
2. Add Web Domain
3. Error when trying to save domain

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.0

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
do NOT use admin user to host any website, create a new user which will have then the right package to host your sites. This isnt a bug, this is by design.
