### ISSUE TITLE
[Bug] After updating to v1.6.2 Configure Server page deselect the installed php version 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#2705]
### Describe the bug

After updating to v1.6.2 Configure Server `8083/edit/server/` page deselect the installed PHP version and only select single php version (8.0)

![image](https://user-images.githubusercontent.com/39749258/176500760-33baad12-7ef1-4955-bb20-abe06fe4653e.png)

and everytime you hit save it's rebuild all the users.

### Tell us how to replicate the bug

Go to Configure Server page `8083/edit/server/` 
After Updating to 1.6.2

and click on Web Server and see only php8 is selected.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.6.2

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
I'm not able to reproduce your bug, also we had from 1.6.1 to 1.6.2 no changes in edit server section as you can see here: https://github.com/hestiacp/hestiacp/compare/1.6.1...1.6.2

Even the last change was more than 2 months ago: https://github.com/hestiacp/hestiacp/tree/main/web/edit/server

From where to where have you made your update?

**Comment by jaapmarcus** [comment]
I think it was allready present before.. Only added in 1.6.1 v-change-sys-php the rebuild made it worse...

**Comment by alber-khan** [comment]
`From where to where have you made your update?` 

i pushed the update from v1.5.11 to 1.6.2
