### ISSUE TITLE
The Hestiacp panel could not be logged in. An internal server error appears [Bug] 

### ISSUE THREAD

**Issue by Nadun21** [hestiacp/hestiacp#2709]
### Describe the bug

When a new version of Hestia arrives, the panel will not be able to log in. When going to the address :8083, a message appears as Internal Server Error. See screenshot below.

https://i.ibb.co/85wY8jX/screenshot-cp-melchicreator-com-8083-2022-06-30-16-58-44.png

The problem can be solved by using the following command and then rebooting the VPS

sudo apt-get update && sudo apt upgrade -y

This error comes only on OpenVZ VPS

This is a bug so I posted this to report

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.6.2

### Operating system

Ubuntu / Debian

**Comment by jaapmarcus** [comment]
If apt-update && apt-upgrade solves the issue I have no idea what could be wrong but it seems to be solved allready.

Please remember that we released last 2 days 2 releases that also patches multiple bugs

**Comment by Nadun21** [comment]
> If apt-update && apt-upgrade solves the issue I have no idea what could be wrong but it seems to be solved allready.
> 
> Please remember that we released last 2 days 2 releases that also patches multiple bugs

This problem has been going on for a year. We have a hosting company. Many of our VPS are getting this error.

**Comment by jaapmarcus** [comment]
Then check /var/log/hestia/nginx-error.log instead and check what the cause is.

We never test on OpenVZ special.
