### ISSUE TITLE
[Bug] wordpress install "error connecting database"

### ISSUE THREAD

**Issue by macsim26** [hestiacp/hestiacp#2711]
### Describe the bug

Hello i have just installed Hestia on a new server and when i try to install Wordpress everything seem good but impossible to connect to the wordpress site. The messa ge is "error connecting database.
The database is well here.
What must i do?
Thanks

### Tell us how to replicate the bug

install wordpress

### Which components are affected by this bug?

Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.6.2

### Operating system

Ununtu 22.04

**Comment by jaapmarcus** [comment]
How did you install "Wordpress" ?

**Comment by macsim26** [comment]
Just clicking "install app" in the domain tab...?

Le ven. 1 juil. 2022 à 13:19, Jaap Marcus ***@***.***> a
écrit :

**Comment by jaapmarcus** [comment]
Change the password for the database and change the settings in wp-config and it should work. 

As we install  wordpress with an database enabled I have no idea why it should fail:
```
        exec("/usr/bin/curl --location --post301 --insecure --resolve ".$this->domain.":$webPort:".$this->appcontext->getWebDomainIp($this->domain)." "
            . escapeshellarg($webDomain.$options['install_directory']."/wp-admin/install.php?step=2")
            . " -d " . escapeshellarg(
                "weblog_title=" . rawurlencode($options['site_name'])
            . "&user_name="      . rawurlencode($options['wordpress_account_username'])
            . "&admin_password=" . rawurlencode($options['wordpress_account_password'])
            . "&admin_password2=". rawurlencode($options['wordpress_account_password'])
            . "&admin_email="    . rawurlencode($options['wordpress_account_email'])
            ), $output, $return_var);


        if ($return_var > 0) {
            throw new \Exception(implode(PHP_EOL, $output));
        }
```


Also not able to reproduce

**Comment by macsim26** [comment]
Ok i have installed Wordpress manualy with a manualy created database and
it's ok...
With Ubuntu 22.04 and Hestia 1.6.2  "the quick install app" for Wordpress
don't update the file wp-config.php with database parameters.
Thanks.
Miguel

Le ven. 1 juil. 2022 à 22:00, Jaap Marcus ***@***.***> a
écrit :

**Comment by jaapmarcus** [comment]
> Ok i have installed Wordpress manualy with a manualy created database and it's ok... With Ubuntu 22.04 and Hestia 1.6.2 "the quick install app" for Wordpress don't update the file wp-config.php with database parameters. Thanks. Miguel Le ven. 1 juil. 2022 à 22:00, Jaap Marcus ***@***.***> a écrit :
> […](#)

I am not able to replicate the issue 

Did you uncheck the "Create" database option?

**Comment by jaapmarcus** [comment]
The curl command will continue if database setup did fail ...

Will add an check to test it ... 
```
        if ( strpos(implode(PHP_EOL,$output),'Error establishing a database connection' !== false)){
           throw new \Exception('Error establishing a database connection'); 
        }

```
