### ISSUE TITLE
[Feature] Add Tags to Domains

### ISSUE THREAD

**Issue by alexgarciab** [hestiacp/hestiacp#2718]
### Describe the feature or change in detail

I would like to have the ability to add tags to domains. Plus being able to sort domains by tags. That way I can categorize domains and clearly see what is the tag associated to the domain.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
Tags could help know the type of contract or level of service or if there is a specific version of wp...

Very interesting

**Comment by jaapmarcus** [comment]
Current system isn't working well with listing / search / sorting with tags.  Unless you are allowing max 1 tag per domain. So for me it is a clear no. Maybe in the future if we have a better system but this feature has 0 priority

**Comment by alexgarciab** [comment]
Any updates on this? Maybe "folders" would be another way to categorize domains, if the tags implementation is challenging.

**Comment by jaapmarcus** [comment]
Issue has been closed also storing method has not been changed

**Comment by jaapmarcus** [comment]
Also if you want to create folders create seperate users...

**Comment by alexgarciab** [comment]
> Also if you want to create folders create seperate users...

This worked for me - However, I still miss a "favorite" or "star" feature to feature domains in the same user. This is something Cloudflare has implemented recently in their dashboard and Hestia could implement too.
