### ISSUE TITLE
[Feature] Add "nginx proxy manager" support

### ISSUE THREAD

**Issue by animeai** [hestiacp/hestiacp#2723]
### Describe the feature or change in detail

Nginx proxy manager https://nginxproxymanager.com allows for simple control of FQDN routing to a docker app or other app running on a specific port. This is currently achievable manually by writing your own nginx template for HestiaCP to use.

Required additions to the system:
- docker
- docker-compose (for simplicity)
- new nginx template to forward http/https to nginx proxy manager

Possible issues:
- Letsencrypt baked into HestiaCP might fail on these domain names, testing would be required. It would be best to disable https on nginx proxy manager and use HestiaCP's own https transport and certificates. 
- Nginx proxy manager has its own panel, running on its own port. This could be made to appear in the HestiaCP control panel or remain separate. 
- Nginx proxy manager has built in user control, it may not be completely simple to integrate this with pam (how HestiaCP currently controls users). A workaround would be to run a copy of nginx proxy manager for each user who requires it giving them their own admin account. 

Advantages:
- Expansion of existing control panel to allow docker apps to be routed to a subdomain without the user needing to write  a custom template.
- Docker app support would now be baked into HestiaCP allowing for a multitude of new features to be easily and simply added. A future feature enhancement could allow for docker-compose.yml files to be added directly via HestiaCP and not require setting up manually. 
- Default admin credentials.
- Docker would add support for other database types (MongoDB, redis, elastic search, etc) without the user needing to perform an intricate or manual setup. Lets face it, we use a control panel to avoid complex CLI and config file setups! Typical apps could be shipped and published with a simple docker-compose.yml file in the HestiaCP repo.

Depending on cost, I may be willing to sponsor this feature (through an escrow service for security of all parties). I would appreciate an estimate from the HestiaCP dev team for this. 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by divinity76** [comment]
would this also require a CPU with Intel VT-x / AMD-V support? 

fwiw some hosting providers disable these CPU features, for example Contabo.com disable VT-x/AMD-V on most of their VPS offerings (with the notable exception of their "VDS" offerings, which are much more expensive than their normal VPS offerings, and have dedicated CPU cores)

**Comment by tlcd96** [comment]
FIY: you can run docker inside an VM 
(just tested on Ubuntu 18.04) - virtual machine
- installed docker (apt install docker.io)
- ran example docker ( docker run hello-world)
success
```
root@vm03:~# docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:13e367d31ae85359f42d637adf6da428f76d75dc9afeb3c21faea0d976f5c651
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

```

**Comment by animeai** [comment]
> would this also require a CPU with Intel VT-x / AMD-V support?
> 
> fwiw some hosting providers disable these CPU features, for example Contabo.com disable VT-x/AMD-V on most of their VPS offerings (with the notable exception of their "VDS" offerings, which are much more expensive than their normal VPS offerings, and have dedicated CPU cores)

Shouldn't do. Docker on linux doesn't require virtualisation extensions unless you want to split your VPS into more VMs which is a very niche use case. 

I've used docker on bare metal servers (AMD64, x86, ARMv6, ARMv7, and ARM64), and on VPS hosted with hostworld and ionos. I can't speak for other providers, but any standard VPS should be absolutely fine, resources permitting (free RAM, CPU and IO).

**Comment by jaapmarcus** [comment]
We currently don't have enough time to implement this feature it makes sense to add a "template" where a user can edit the port number easier makes a lot more sense then implement a docker image for it. 

Also how are you going to prevent users running Minecraft in a docker..
