### ISSUE TITLE
imap.domain.com + smtp.domain.com should get the same SSL treatment as mail.domain.com (or not exist at all)

### ISSUE THREAD

**Issue by divinity76** [hestiacp/hestiacp#2724]
Currently when creating email for domain.com , <strike>3</strike> 4 subdomains will be created: mail.domain.com and imap.domain.com and smtp.domain.com and pop.domain.com

When enabling LetsEncrypt SSL for email, mail.domain.com will get proper SSL certificates, but imap.domain.com and smtp.domain.com will *not* , they just get some invalid certificate. (?)

When using Thunderbird autodetect, it will detect-and-select imap.domain.com and smtp.domain.com by default, then it will complain that the server is using invalid certificates. Either the former 2 domains should not be created at all (because <strike>iirc</strike> Thunderbird will try mail.domain.com if the former are missing), -or- all 3 subdomains should get proper ssl certificates: 

![image](https://user-images.githubusercontent.com/1874996/177463314-f8c288c2-ed31-4c9b-8e2b-46111a8d8c96.png)
![image](https://user-images.githubusercontent.com/1874996/177462677-364f1853-9bc2-475d-8e0a-1af81625ac45.png)
![image](https://user-images.githubusercontent.com/1874996/177462709-c9b654e4-ea88-469a-a2ed-9bafa1f58d2c.png)

**Comment by divinity76** [comment]
fwiw just deleting the smtp.domain.com and imap.domain.com makes Thunderbird autodetect function correctly -but- idk what that will do with other client autodetects? or what else it might break? 

![image](https://user-images.githubusercontent.com/1874996/177464526-ed935022-ff73-4327-9f91-1a592cc2cd8a.png)

**Comment by divinity76** [comment]
fwiw just deleting the imap.domain.com and smtp.domain.com A records makes Thunderbird autodetect work correctly :) 
not sure if deleting those breaks *something else* tho..
![image](https://user-images.githubusercontent.com/1874996/177465899-2cd859c2-3828-479f-969a-95663db0a15b.png)

**Comment by jaapmarcus** [comment]
the imap / smtp records are some old *** from VestaCP we should just consider deleting on default

**Comment by divinity76** [comment]
@jaapmarcus sounds good to me. you wanna do?  (i'm busy atm with another PR i'm preparing)

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/2725
👍🏼
