### ISSUE TITLE
[Bug] Letsencrypt and + 50 domains  not working

### ISSUE THREAD

**Issue by artemkopytko** [hestiacp/hestiacp#2727]
### Describe the bug

Hi! I'm facing a problem with issuing Letsencrypt SSL. I've got 4 different VPS with Hestia installed, and problem is met everywhere. The number of domains is 100+ on each VPS. For the first 50-70 domains everything was okay, but then SSL stopped issuing. I've got an error "Details: Unable to update challenge :: authorization must be pending"
Domain DNS are okay. When adding those domains to other CPs - SSL issues well

### Tell us how to replicate the bug

1. Add 50-70 domains to Hestia
2. Try to issue SSL

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.6.2

### Operating system

Ubuntu 20.04 (x86_64)

### Log capture

```shell
18.196.3.1 - - [06/Jul/2022:08:15:55 +0000] "GET /.well-known/acme-challenge/AoHsywUprdU4vUCpno7_n_iWGTqXZ11mW548XwXWp1E HTTP/1.0" 404 3589 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"

66.133.109.36 - - [06/Jul/2022:08:15:55 +0000] "GET /.well-known/acme-challenge/AoHsywUprdU4vUCpno7_n_iWGTqXZ11mW548XwXWp1E HTTP/1.0" 404 3589 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"

54.189.52.134 - - [06/Jul/2022:08:15:56 +0000] "GET /.well-known/acme-challenge/AoHsywUprdU4vUCpno7_n_iWGTqXZ11mW548XwXWp1E HTTP/1.0" 404 3589 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"

3.19.234.145 - - [06/Jul/2022:08:15:56 +0000] "GET /.well-known/acme-challenge/AoHsywUprdU4vUCpno7_n_iWGTqXZ11mW548XwXWp1E HTTP/1.0" 404 3589 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/LE-xxxx

**Comment by artemkopytko** [comment]
> Check /var/log/hestia/LE-xxxx
[hestialog.txt](https://github.com/hestiacp/hestiacp/files/9053123/hestialog.txt)

*Changed real domain name to domain.com (can't show because of client)

**Comment by jaapmarcus** [comment]
http://xxxx.co.uk/.well-known/acme-challenge/AoHsywUprdU4vUCpno7_n_iWGTqXZ11mW548XwXWp1E

Returns 404. Is nginx restarting properly?

**Comment by artemkopytko** [comment]
`systemctl status nginx`
says

Jul 04 04:26:17 hostname.domain.ttttt systemd[1]: Reloading nginx - high performance web server.
Jul 04 04:26:17 hostname.domain.ttttt systemd[1]: Reloaded nginx - high performance web server.
Jul 04 04:26:50 hostname.domain.ttttt systemd[1]: Reloading nginx - high performance web server.
Jul 04 04:26:50 hostname.domain.ttttt systemd[1]: Reloaded nginx - high performance web server.
Jul 05 04:12:15 hostname.domain.ttttt systemd[1]: Reloading nginx - high performance web server.
Jul 05 04:12:15 hostname.domain.ttttt systemd[1]: Reloaded nginx - high performance web server.
Jul 06 04:12:18 hostname.domain.ttttt systemd[1]: Reloading nginx - high performance web server.
Jul 06 04:12:18 hostname.domain.ttttt systemd[1]: Reloaded nginx - high performance web server.
Jul 06 08:15:49 hostname.domain.ttttt systemd[1]: Reloading nginx - high performance web server.
Jul 06 08:15:49 hostname.domain.ttttt systemd[1]: Reloaded nginx - high performance web server.

**Comment by jaapmarcus** [comment]
What template do you use?

It is still returning 404

**Comment by artemkopytko** [comment]
Everything is set as default

> What template do you use?
> 
> It is still returning 404
<img width="450" alt="Screenshot 2022-07-06 at 12 04 24" src="https://user-images.githubusercontent.com/13777605/177513534-cdc1ec46-fa6e-4e12-9d1d-832fb0dddc26.png">

**Comment by artemkopytko** [comment]
And as I mentioned before - for the first 50/70 domains everything was good. And is repeated on 4 different VPS

**Comment by jaapmarcus** [comment]
The only thing that might going wrong is an issue with max open files in nginx

**Comment by artemkopytko** [comment]
> The only thing that might going wrong is an issue with max open files in nginx

Deleted some old domains and all seems okay. SSL issued well. But can we find any solution so CP can support any number of domains/files?

**Comment by divinity76** [comment]
Edit: i still think its a rate limit issue, but not exactly as described below, more like max 50 certs per TLD; 

Edit: ok the message below makes sense now, i think:

Pretty sure this is because of LetsEncrypt rate limiting: https://letsencrypt.org/docs/rate-limits/

max 50 certs per TLD per week. HestiaCP probably fetch a separate cert for each subdomain, which would hit this limit around 50 subdomains..

However LetsEncrypt supports up to 100 domains per cert, if we change HestiaCP to share LetsEncrypt certificates for 100 subdomains at a time, we would reach this problem when exceeding 5000 subdomains instead of 50 subdomains 🤔

**Comment by divinity76** [comment]
@artemkopytko when you say `Add 50-70 domains to Hestia`  do you mean 50 Top-Level-Domains or 50 subdomains?

**Comment by divinity76** [comment]
@artemkopytko fwiw if it *is* subdomains, a quickfix for your client would be to buy a wildcard ssl certificate (but they're not free and LetsEncrypt does not provide them; a quick google search suggest they cost $40++/year) ; a wildcard certificate supports unlimited subdomains.

**Comment by artemkopytko** [comment]
@divinity76 Hi! No, I'm using only Top-Level-Domains: .com, .net, .org without subdomains, even without www alias

UPD: problems started with 200+ web domains on Hestia

**Comment by jaapmarcus** [comment]
Lets encrypt should have an error 429  if the rate limit  has been reached and not an 400 error.

The only thing that might happen is there an limit reach with the max open file But it that case  I have no possibility to test with as I don't own 200 domains / or  have access to +  200 domains

**Comment by divinity76** [comment]
what do you get with
```
sudo tail -f /var/log/nginx/error.log /var/log/hestia/nginx-error.log /var/log/hestia/system.log
```
when it fails? 
edit: added more errorlogs to tail command.\

**Comment by jaapmarcus** [comment]
Please provide us with more information it might the rate limit...
