### ISSUE TITLE
[Feature] Fail2ban

### ISSUE THREAD

**Issue by dfag86** [hestiacp/hestiacp#2728]
### Describe the feature or change in detail

Adding to Fail2ban the ability to ban by country code, not just IP.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Use ipset instead works fine

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/settings/firewall.html

**Comment by dfag86** [comment]
thank you i will check it tonight :)
