### ISSUE TITLE
[Bug] IPset Create a repo that can be used instead downloading directly from source

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2733]
### Describe the bug

When in blacklist.sh a service is down for any reason the update will file. We should be able to download all files during a cronjob and maintain a repo for it

And download this list via the cronjob in the panel.

### Tell us how to replicate the bug

Run currently the tests

#   Unavailable (503): https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1

### Which components are affected by this bug?

Firewall (Iptables, Fail2ban)

### Hestia Control Panel Version

1.6.3

### Operating system

N/A

**Comment by wojsmol** [comment]
Link posted above works from my location right now - using Firefox browser.

**Comment by jaapmarcus** [comment]
It works again but during tests last evening all failed:

https://drone.hestiacp.com/hestiacp/hestiacp/1707

Also have seen other services listed in the list failing in the past for a for period

**Comment by jlguerrerosanz** [comment]
I have all countries classified by continent and gross per-capita produce and their corresponding ipset.

**Comment by jlguerrerosanz** [comment]
Can we also include the official googlebot and bing IP list in an IPset?
https://www.gstatic.com/ipranges/goog.json
https://www.bing.com/toolbox/bingbot.json
That way I could block every single conection except from my country and google and bing

**Comment by jlguerrerosanz** [comment]
Like this:
```
#!/bin/bash
bingurl='https://www.bing.com/toolbox/bingbot.json'
googleurl='https://www.gstatic.com/ipranges/goog.json'
#Google
wget -q --output-document - $googleurl | grep "ipv4Prefix" | cut -d'"' -f4 > ipset-googlebot-ip4.txt
wget -q --output-document - $googleurl | grep "ipv6Prefix" | cut -d'"' -f4 > ipset-googlebot-ip6.txt
#Bing
wget -q --output-document - $bingurl | grep "ipv4Prefix" | cut -d'"' -f4 > ipset-bingbot-ip4.txt
#Bing doesn't use ip6 yet to crawl
#wget -q --output-document - $bingurl | grep "ipv6Prefix" | cut -d'"' -f4 > ipset-bingbot-ip6.txt
```

**Comment by ScIT-Raphael** [comment]
Issue has been already resolved due to prior connection loss.

You can add custom lists like you already have written above to ipset on your own, I don't see a need to add them by default.
