### ISSUE TITLE
[Bug] filemanager .zip archive - all files and folders 777

### ISSUE THREAD

**Issue by chiareu** [hestiacp/hestiacp#2734]
### Describe the bug

Hi, I found the following issues on my server. Please check
I created archive.zip of the content of /public_html with Filemanager

Problem no1
The archive has a strange folder nesting inside, including /web/devdomain/public_html/

That's completely wrong if we need to move from dev to live or load a backup; we got that: /home/user/web/livedomain.tld/public_html/web/devdomain.tld/public_html/all_files

It's manageable as we always can create a clean archive on a local computer.

Problem no2
In the originally created archive.zip all files and folders were 777.

### Tell us how to replicate the bug

1. create and download archive.zip of a public_html
2. check the content
3. upload archive in other sub/domain
4. check again

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.2

### Operating system

Ubuntu 20.04 (x86_64)

**Comment by jaapmarcus** [comment]
Compressing is currently done by "Filegator" and not with Hestia it self. If it is an bug it should be reported to Filegator

**Comment by chiareu** [comment]
Thanks Marcus, I reported to "Filegator" and I'll keep an eye on it.

**Comment by ScIT-Raphael** [comment]
Close due to not related to hestia.
