### ISSUE TITLE
[Bug] Apache access log bug

### ISSUE THREAD

**Issue by schneiderbruno** [hestiacp/hestiacp#2736]
### Describe the bug

Hi,

I try download access log, but same times generate 500 error
https://domain.com:8083/download/web-log/?domain=domain.com&type=access&&token=xxx

### Tell us how to replicate the bug

1. Access web
2. In list of sites, click in binoculours icon
3. In access log click in icon "download" from donwload access history
4. Error 500 is sho
![access log](https://user-images.githubusercontent.com/8595383/177830562-51535d75-4a53-41b1-9fba-caaedf8e6bc3.png)
w

### Which components are affected by this bug?

Control Panel Backend, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.2

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
Can you please check the hestia-nginx log in /var/log/hestia and send us the related error output?

**Comment by schneiderbruno** [comment]
In /var/log/hestiacp, list of files

auth.log
auth.log.1
backup.log
backup.log.1
error.log
error.log.1
logout.save
logout.save.1
nginx-access.log
nginx-access.log.1
nginx-error.log
nginx-error.log.1
system.log
system.log.1


"error.log"
2022-07-06 15:02:39 v-list-user  '' 'json' [Error 3]
2022-07-06 17:52:46 v-list-user  '' 'json' [Error 3]
2022-07-06 21:38:32 v-list-user  '' 'json' [Error 3]


"nginx-error.log"
2022/07/06 15:02:39 [error] 1197611#0: *684 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /usr/local/hestia/web/login/index.php on line 64PHP message: PHP Warning:  Trying to access array offset on value of type null in /usr/local/hestia/web/login/index.p>
2022/07/06 15:26:45 [error] 1197611#0: *838 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_proxy in /usr/local/hestia/web/templates/pages/add_web.html on line 189PHP message: PHP Warning:  Undefined variable $v_proxy in /usr/local/hestia/web/templates/pages/add_web.html on line 218" while>
2022/07/06 15:26:51 [error] 1197611#0: *841 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_proxy in /usr/local/hestia/web/templates/pages/add_web.html on line 189PHP message: PHP Warning:  Undefined variable $v_proxy in /usr/local/hestia/web/templates/pages/add_web.html on line 218" while>
2022/07/06 17:52:46 [error] 1197611#0: *933 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /usr/local/hestia/web/login/index.php on line 64PHP message: PHP Warning:  Trying to access array offset on value of type null in /usr/local/hestia/web/login/index.p>
2022/07/06 21:38:32 [error] 1197611#0: *1290 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /usr/local/hestia/web/login/index.php on line 64PHP message: PHP Warning:  Trying to access array offset on value of type null in /usr/local/hestia/web/login/index.>
2022/07/07 12:05:45 [error] 1197611#0: *1822 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/hestia/web/download/web-log/index.php on line 31" while reading response header from upstream, client: 179.124.183.51, s>
2022/07/07 12:06:11 [error] 1197611#0: *1828 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/hestia/web/download/web-log/index.php on line 31" while reading response header from upstream, client: 179.124.183.51, s>
2022/07/07 13:41:20 [error] 1197611#0: *1883 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/hestia/web/download/web-log/index.php on line 31" while reading response header from upstream, client: 179.124.183.51, s>

**Comment by ScIT-Raphael** [comment]
Thats the important part, thanks, we will check that:

[2022/07/07 13:41:20 ](calendar:T7:2022/07/07 13:41:20)[error] 1197611#0: *1883 FastCGI sent in stderr: "PHP message: PHP Fatal error: Allowed memory size of [268435456](tel:268435456) bytes exhausted (tried to allocate 20480 bytes) in /usr/local/hestia/web/download/web-log/index.php on line 31" while reading response header from upstream, client: [179.124.183.51](http://179.124.183.51/), s>

**Comment by schneiderbruno** [comment]
Yes, need more memory

thanx

**Comment by jaapmarcus** [comment]
No the logs files are 256mb large increasing memory isn't a real solution

**Comment by schneiderbruno** [comment]
> HP Fatal error: Allowed memory size of 268435456 bytes exhausted

https://stackoverflow.com/questions/21680244/fatal-error-allowed-memory-size-of-268435456-bytes-exhausted-tried-to-allocate

**Comment by divinity76** [comment]
in /usr/local/hestia/web/download/web-log/index.php line 31 maybe try replacing
```php
exec(HESTIA_CMD."v-list-web-domain-".$type."log $user ".$v_domain." 5000", $output, $return_var);
if ($return_var == 0) {
    foreach ($output as $file) {
        echo $file . "\n";
    }
}
```
with
```php
$oom_test = 1;
if ($oom_test) {
    passthru(HESTIA_CMD . "v-list-web-domain-" . $type . "log $user " . $v_domain . " 5000", $return_var);
    if ($return_var !== 0) {
        echo "Internal error! return_var non-zero: {$return_var}";
    }
} else {
    exec(HESTIA_CMD . "v-list-web-domain-" . $type . "log $user " . $v_domain . " 5000", $output, $return_var);
    if ($return_var == 0) {
        foreach ($output as $file) {
            echo $file . "\n";
        }
    }
}
```

**Comment by divinity76** [comment]
proposed fix in #2741

**Comment by divinity76** [comment]
this is fixed in https://github.com/hestiacp/hestiacp/commit/fc10af5c95b68dccf8d6e63e5ebe61762ae1f506 
,  @schneiderbruno you can apply the patch manually, or wait for the next release and update,
either way, i'm pretty sure this issue can be closed now :)

**Comment by jaapmarcus** [comment]
Manually patching doesn't work as it requires rebuild of hestia-php
