### ISSUE TITLE
[Bug] hestia update failed

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2738]
### Describe the bug

Ubuntu 20.04
Hestia 1.6.2

Today my CSF LFD alert emails
lfd on PANEL.COM : Excessive resource usage: admin .....
------------------------

I tried REBOOT & CMD:
root@USER:~# sudo /usr/local/hestia/bin/v-update-sys-hestia-all
Error: hestia update failed
Error: hestia-nginx update failed
Error: hestia-php update failed

### Tell us how to replicate the bug

CMD:
sudo /usr/local/hestia/bin/v-update-sys-hestia-all

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.6.2

### Operating system

Ubuntu 20.04

### Log capture

```shell
root@USER:~# sudo /usr/local/hestia/bin/v-update-sys-hestia-all
Error: hestia update failed
Error: hestia-nginx update failed
Error: hestia-php update failed
```

**Comment by jaapmarcus** [comment]
If CSF / LFD decides the resources are to intensive and there for decides to cancel the software. Disable auto updates and run it manually. 

What happens when you run apt update && apt upgrade -y

**Comment by ScIT-Raphael** [comment]
> ## Today my CSF LFD alert emails
> lfd on PANEL.COM : Excessive resource usage: admin .....

Explains the issue, not related to hestia.

**Comment by vvcares** [comment]
@ScIT-Raphael, the matter is not about Resource usage. Its an alert related to hestia-update resource usage.

System alert while hestia's cron job
Command Line: /bin/sh -c sudo /usr/local/hestia/bin/v-update-sys-hestia-all

While I run it manually,
sudo /usr/local/hestia/bin/v-update-sys-hestia-all
Got the error as below..

Error: hestia update failed
Error: hestia-nginx update failed
Error: hestia-php update failed
----------------
As you advised, i ran below command & success.
apt update && apt upgrade -y

Now
sudo /usr/local/hestia/bin/v-update-sys-hestia-all
has no errors. SUCCESS.. Thank you

**Comment by jaapmarcus** [comment]
Mostlikely the upgrade process is killed during the update and then restarting it again with the same command it probally still will fail. 

If you use some recourse monitoring with CSF I suggest disabling for the admin user.
