### ISSUE TITLE
I need to import large files to the file manager via URL

### ISSUE THREAD

**Issue by allcdn** [hestiacp/hestiacp#2743]
### Describe the feature or change in detail

Due to network upload bandwidth limitations, I need to import files to the file manager via URL, a feature I'm sure many of you will need.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We don't develop the filemanger

https://github.com/filegator/filegator

You can use ssh in combination with wget / curl
