### ISSUE TITLE
[Feature] store MariaDB database in home directory

### ISSUE THREAD

**Issue by divinity76** [hestiacp/hestiacp#2756]
### Describe the feature or change in detail

currently databases are stored in /var/lib/mysql/{databasename}, this creates some logistics problems when one want to see how much diskspace a hestiacp user is actually utilizing, or want to enforce disk quotas. would be cool if there was an option to put database in `/home/username/databases/mysql/{databasename}` - much like websites are in `/home/username/web/{websitename}`  

Not sure if this is technically doable/feasible/easy/hard though, from a quick investigation, looks like MariaDB doesn't have native support for custom data folders per database 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
The "disk" usage in the Hestia allready includes disk usage in the account info. 

For disk quotas (hard) they are not included

**Comment by istiak101** [comment]
Quota enforcement is `not possible/tricky` but it is possible to calculate disk usage for each database. There was many discussions for this in other popular control panels. And people suggested interesting things like removing INSERT/UPDATE privileges for the database user.

**Comment by divinity76** [comment]
After some digging, this seems to be way more trouble implementing than it's worth. closing
