### ISSUE TITLE
[Bug]  Update 1.6.3 - Wordpress install error

### ISSUE THREAD

**Issue by dfag86** [hestiacp/hestiacp#2760]
### Describe the bug

I updated HestiaCP to the latest version. I have Debian 11 and everything was working perfectly. After the automatic update, I can't install wordpress. I used PHP 8.0 which is standard.

### Tell us how to replicate the bug

1. Edit web domain
2. install Wordpress

### Which components are affected by this bug?

Control Panel Installation or Upgrade, Control Panel Web Interface

### Hestia Control Panel Version

1.6.3

### Operating system

Debian 11

### Log capture

```shell
2022-07-13 12:27:12 v-update-sys-rrd-mysql  'daily' [Error 15]
2022-07-13 12:32:11 v-update-sys-rrd-mysql  'daily' [Error 15]
2022-07-13 12:37:12 v-update-sys-rrd-mysql  'daily' [Error 15]
2022-07-13 12:42:11 v-update-sys-rrd-mysql  'daily' [Error 15]
2022-07-13 12:47:12 v-update-sys-rrd-mysql  'daily' [Error 15]
2022-07-13 12:52:11 v-update-sys-rrd-mysql  'daily' [Error 15]
2022-07-13 12:53:32 v-list-web-domain  [Error 1]
2022-07-13 12:57:12 v-update-sys-rrd-mysql  'daily' [Error 15]
```

**Comment by dfag86** [comment]
The problem does not only concern Wordpress, because NextCloud does not install either, so it is rather a technical problem with listing domains, etc., making it impossible to move on.

**Comment by ScIT-Raphael** [comment]
Its a function issue which affects the whole imstallation manager, we'll get that fixed.

For reference: https://discord.com/channels/737721354937303161/738055454285889597/996721868520308756

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/cbb49fb766eb3ec1e41d3e313b7ab3b7a4262ee8/web/src/app/System/HestiaApp.php#L20-L24

**Comment by jaapmarcus** [comment]
Fixed

**Comment by divinity76** [comment]
for a quickfix you can try running as sudo
```
wget 'https://raw.githubusercontent.com/divinity76/hestiacp/f4eb5fc1063739cf2b07aed91ba3c5f58cd371d4/web/api/index.php' -O /usr/local/hestia/web/api/index.php;
 
wget 'https://raw.githubusercontent.com/divinity76/hestiacp/f4eb5fc1063739cf2b07aed91ba3c5f58cd371d4/web/inc/main.php' -O /usr/local/hestia/web/inc/main.php; 

wget 'https://raw.githubusercontent.com/divinity76/hestiacp/f4eb5fc1063739cf2b07aed91ba3c5f58cd371d4/web/src/app/System/HestiaApp.php' -O /usr/local/hestia/web/src/app/System/HestiaApp.php;
```
- no guarantees, and a proper fix will be included in the next release ^^

**Comment by jaapmarcus** [comment]
```
v-update-sys-hestia-git hestiacp main
```

Will work for sure 
No major changes have been made anyway

**Comment by dfag86** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING - Development builds should not be installed on
systems with live production data without understanding
the potential risks that are involved!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Do you wish to proceed with the installation? [y/n]

**Comment by dfag86** [comment]
**Everything works fine :) Thank you!**
