### ISSUE TITLE
Cannot install any web apps getting message "v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/"

### ISSUE THREAD

**Issue by bobbythomas** [hestiacp/hestiacp#2763]
### Describe the bug

When trying to perform a quick install of any web app I keep getting the error message "v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/" in GUI. Upon checking the log file (/var/log/hestia/nginx-error.log) I see below error messages.

This is a new setup and I started seeing this after adding the Web Domains and then tried installing Web apps. Below are some logs from the log file for reference. I also tried switching Php fpm from 5.6 till 8.1 but the result is same. Don't know if this is something with Nginx or PHP.

`2022/07/14 00:56:53 [error] 1074#0: *6 FastCGI sent in stderr: "PHP message: PHP Notice:  v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/ in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 22" while reading response header from upstream, client: <My web client IP>, server: _, request: "GET /add/webapp/?app=Nextcloud&domain=<myhost.mydomain.com> HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?domain=myhost2.mydomain.com"`

![image](https://user-images.githubusercontent.com/35666904/178886989-22fc7106-9156-4125-81fa-a93d1a9b0d52.png)

root@hostname:~# cat /var/run/hestia-php.sock
cat: /var/run/hestia-php.sock: No such device or address

### Tell us how to replicate the bug

I don't know how this can be replicated, this started happening after I tried installing web apps after initial setup and after Web Domain configuration. I also faced errors when I tried to setup using hestia unattended script as it failed at "--hostname: Command not found" message and so I interactively installed it on a Ubuntu 20.04 box.

### Which components are affected by this bug?

Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.3

### Operating system

Ubuntu 20.04

### Log capture

```shell
2022/07/14 00:56:53 [error] 1074#0: *6 FastCGI sent in stderr: "PHP message: PHP Notice:  v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/ in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 22" while reading response header from upstream, client: <My web client IP>, server: _, request: "GET /add/webapp/?app=Nextcloud&domain=<myhost.mydomain.com> HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?domain=myhost2.mydomain.com"


2022/07/14 01:06:06 [error] 1074#0: *60 FastCGI sent in stderr: "PHP message: PHP Notice:  v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/ in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 22" while reading response header from upstream, client: <My web client IP>, server: _, request: "GET /add/webapp/?app=Nextcloud&domain=myhost.mydomain.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?domain=myhost.mydomain.com"


2022/07/14 01:06:10 [error] 1074#0: *60 FastCGI sent in stderr: "PHP message: PHP Notice:  v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/ in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 22" while reading response header from upstream, client: <My web client IP>, server: _, request: "GET /add/webapp/?app=Opencart&domain=myhost.mydomain.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?domain=myhost.mydomain.com"


2022/07/14 01:06:13 [error] 1074#0: *60 FastCGI sent in stderr: "PHP message: PHP Notice:  v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/ in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 22" while reading response header from upstream, client: <My web client IP>, server: _, request: "GET /add/webapp/?app=Grav&domain=myhost.mydomain.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?domain=myhost.mydomain.com"


2022/07/14 01:06:15 [error] 1074#0: *60 FastCGI sent in stderr: "PHP message: PHP Notice:  v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/ in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 22" while reading response header from upstream, client: <My web client IP>, server: _, request: "GET /add/webapp/?app=Drupal&domain=myhost.mydomain.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?domain=myhost.mydomain.com"


2022/07/14 01:06:19 [error] 1074#0: *60 FastCGI sent in stderr: "PHP message: PHP Notice:  v-list-web-domain is trying to traverse outside of /usr/bin/sudo /usr/local/hestia/bin/ in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 22" while reading response header from upstream, client: <My web client IP>, server: _, request: "GET /add/webapp/?app=Symfony&domain=myhost.mydomain.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?domain=myhost.mydomain.com"
```

**Comment by jaapmarcus** [comment]
See here 
https://github.com/hestiacp/hestiacp/issues/2760

**Comment by bobbythomas** [comment]
I followed this https://github.com/hestiacp/hestiacp/issues/2760 and was able to go past that error it but there is another issue with Web app deployment, I will open another one.
