### ISSUE TITLE
[Bug] Web App (Nextcloud/Wordpress) installation failing with message "Error: Cli command does not exist /usr/bin/phpArray"

### ISSUE THREAD

**Issue by bobbythomas** [hestiacp/hestiacp#2764]
### Describe the bug

After encountering the issue #2763, I followed #2760 to fix the issue. When that issue seems like fixed another issue popped up.
Getting this error message in the GUI:
![image](https://user-images.githubusercontent.com/35666904/178901765-32ebb1ba-8c71-4cdd-adf2-4c2a2c257fd3.png)

Also the public_html folder is getting filled up and I had to clear that out. Not sure if this is something related to the database.

### Tell us how to replicate the bug

After the bug #2763 I started facing this new issue with Web app (Nextcloud/Wordpress) deployment.

### Which components are affected by this bug?

Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2), Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.6.3

### Operating system

Ubuntu 20.04

### Log capture

$cli_arguments in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 29PHP message: PHP Warning:  Undefined variable $cli_arguments in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 29PHP message: PHP Warning:  Undefined variable $cli_arguments in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 29PHP message: PHP Warning:  Undefined variable $cli_arguments in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 29PHP message: PHP Warning:  Undefined variable $cli_arguments in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 29PHP message: PHP Warning:  Array to string conversion in /usr/local/hestia/web/src/app/WebApp/Installers/Nextcloud/NextcloudSetup.php on line 45PHP message: PHP Warning:  Undefined variable $cli_arguments in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 29PHP message: PHP Notice:  Error: Cli command does not exist /usr/bin/phpArray in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 45" while reading response header from upstream, client: <My client IP>, server: _, request: "POST /add/webapp/?app=Nextcloud&domain=myhost.mydomain.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "myhost.mydomain.com:8083", referrer: "https://myhost.mydomain.com:8083/add/webapp/?app=Nextcloud&domain=myhost.mydomain.com"

**Comment by jaapmarcus** [comment]
Fixed:

https://github.com/hestiacp/hestiacp/commit/9304fa35fccbf5cdbd967bae4e9276f6f626229a
