### ISSUE TITLE
[Bug] Admin settings for users

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#2765]
### Describe the bug

Admin settings for users isnt acessible, The gear in upper is not shown when set another user as administrator.
The option in main settings at panel is checked to allow this for other users.

### Tell us how to replicate the bug

Set another user to Administrator permission.
The gear is not available in top menu.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.4

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Login with the "admin" user and go to settings -> Configure settings -> Security -> System policy 
<img width="521" alt="Screenshot 2022-08-17 at 13 27 16" src="https://user-images.githubusercontent.com/9754650/185107345-08f65b60-c513-43d9-b2c3-d726f0e6b056.png">

Set to no and it should work

**Comment by nirbhasa** [comment]
Hi - even with the above setting set to 'no' this does not work. Other users with Administrator role do not see the Server gear icon in the top right
