### ISSUE TITLE
PiHole Web GUI not Working due to Openbase dir

### ISSUE THREAD

**Issue by afzl-wtu** [hestiacp/hestiacp#2767]
I installed Pihole and it is running very good. But I can not view its Web GUI. It has placed its web GUI files in /var/www/html/. But HestiaCP does not follow this directory. So I copied /var/www/html/admin and /var/www/html/pihole folders and pasted them to /home/username/web/domain/public_html/ . I also changed Document root to pihole.
![image](https://user-images.githubusercontent.com/64379149/179073547-45aca0fb-8b36-4669-af20-167a7d30e11b.png)

Now whenever I open its web gui in browser it says: [ERROR] File not found: /etc/pihole/setupVars.conf
![image](https://user-images.githubusercontent.com/64379149/179074589-7dc23259-edc9-4c73-b09c-aa4b2544f883.png)

But I can confirm file is present in the mentioned directory. I also changed its permission to 777 and ownership to www-data. But no matter what it says the same error.

I also have apache2 [configuration](https://gist.github.com/GAS85/62b8e4851923e5ecec29cbc9b374ab18#internet-access) but I do not know in hestia how can I make it work.

**Comment by jaapmarcus** [comment]
Probally due to openbase dir. 

We can't provide support on 3rd party software

**Comment by afzl-wtu** [comment]
> Probally due to openbase dir.
> 
> We can't provide support on 3rd party software

The question is not about third party software its about how to run web ui (in /var/www/html/)of such applications in HestiaCP?

**Comment by ScIT-Raphael** [comment]
Hestia isnt susposed to run beside or with PiHole, ypu can't get that working - also we dont have any plans to integrate pihole in hestia.

**Comment by afzl-wtu** [comment]
> Hestia isnt susposed to run beside or with PiHole, ypu can't get that working - also we dont have any plans to integrate pihole in hestia.

Sir please forget pihole. There are many softwares with web GUI and they place web GUI in /var/www/html/ directory. Nextcloud is also one of them but thanks to hestiaCP it is now just one click install but what about other same softwares?

**Comment by ScIT-Raphael** [comment]
You're using the wrong path, you need to place your software in /home/user/web/domain.tld/public_html

**Comment by afzl-wtu** [comment]
> You're using the wrong oath, you need to place your software in /home/user/web/domain.tld/public_html

and what about chown and permissions? So that I move files from /var/www/html/ to /home/user/web/domain.tld/public_html?

**Comment by ScIT-Raphael** [comment]
user:www-data for the public_html directory itself, for all the content below user:user. Also please use our forum or discord for support requests, github is for bug hunting and feature requests only.

**Comment by afzl-wtu** [comment]
> Probally due to openbase dir.
> 
> We can't provide support on 3rd party software

You were right after wasting my whole day on this issue I find that php settings of hestiacp allow access to only  home/user/ directory. So now I would add another php config by following https://github.com/hestiacp/hestiacp/issues/2027
