### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aannkur** [hestiacp/hestiacp#2768]
### Describe the bug

emails not working with new setup version 1.6.4 all emails frozen and going to spam

### Tell us how to replicate the bug

emails frozen and in mailq facing issue with only sending

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.4

### Operating system

ubuntu 20.04lts

### Log capture

```shell
emails not working with new setup version 1.6.4 all emails frozen and going to spam
```

**Comment by jaapmarcus** [comment]
No changes have been made in 1.6.3 / 1.6.4 with the email stack. Please provide more information

**Comment by aannkur** [comment]
all emails going to mailq
 and when i am adding domain for email then server not generating records for smtp pop and imap
Please check

**Comment by jaapmarcus** [comment]
smtp.domain.com, pop3.domain.com and imap.domain.com had no use mail as we use by default mail.domain.com

If you need them add them manually 

See:
https://github.com/hestiacp/hestiacp/issues/2724

As we are not able to debug your server over the internet. It is something you need to do it your self... 

Open source doesn't mean I need support I get it it is about free en open software... 

If mail is not working check out you you /var/log/exim4/mainlog and other log files. 

Use our forum for support: https://forum.hestia.com/

If you need more support with debugging send an email to info@hestiacp.com how ever support will cost you 100 euro / hour.

**Comment by aannkur** [comment]
2022-07-15 10:47:41 1oCGx0-0000WG-R0 H=gmail-smtp-in.l.google.com [142.250.102.26] Connection timed out
2022-07-15 10:48:00 1oCGoV-000MmS-A9 H=alt1.gmail-smtp-in.l.google.com [142.251.9.26] Connection timed out
2022-07-15 10:49:12 1oCGyU-0000Zc-9E H=mx1.hostinger.com [34.149.19.242]: SMTP timeout after initial connection: Connection timed out

**Comment by ScIT-Raphael** [comment]
As @jaapmarcus already wrote, please use the forum for support.
