### ISSUE TITLE
[Feature] Possibility to have a row on   ... /templates/includes/panel.html

### ISSUE THREAD

**Issue by tgd1973** [hestiacp/hestiacp#2769]
I wish there was a string in the
/usr/local/hestia/web/templates/includes/panel.html
for those who have installed the CSF firewall so as not to have to edit this file (panel.html) after each update. This is very annoying because lately there is a new update every week.

I refer to this string to be added to line 29:

`<div class="l-menu__item <?php if($TAB == 'CSF' ) echo 'l-menu__item--active' ?>"><a href="/list/csf/"><?=_('CSF')?></a></div>`

Obviously you have to add a check box
also in the  >Settings > >Configure > menu Pluggins ... line so that it can be deselected for those who don't have this CSF  firewall.

Thanks!

**Comment by bet0x** [comment]
Do a chattr on the file so it won't get updated, i would not like to have CSF nor i consider it safe.

**Comment by tgd1973** [comment]
The issue of immutability of the file with chattr +i is not new, and I also know that it works, I was thinking of a definitive resolution for others too ...
Regarding the firewall, these are matters of taste, but also practical: the standard Hestiacp firewall filters / blocks only incoming, but does not filter what is outgoing from your server.

A greeting!.

**Comment by jaapmarcus** [comment]
https://github.com/jaapmarcus/hestia-hooks

Create a file in /etc/hestia/hooks/post_install.sh give it +x permissions and add the sed command to alter the panel.html

I think of now it is the easiest method.  In the future we need to add an more "flexible" method

**Comment by tgd1973** [comment]
I think there is a problem with your - [jaapmarcus] - suggestion ... Now there is also confirmation that by entering read only of the panel.html you can no longer upgrade the version of Hestia:

```
Unpacking hestia (1.6.10) over (1.6.5) ...
dpkg: error processing archive /var/cache/apt/archives/hestia_1.6.10_amd64.deb (--unpack):
 unable to make backup link of './usr/local/hestia/web/templates/includes/panel.html' before installing new version: Operation not permitted
```

**Comment by ScIT-Raphael** [comment]
please take the suggested way here and use a sed:



> https://github.com/jaapmarcus/hestia-hooks
> 
> Create a file in /etc/hestia/hooks/post_install.sh give it +x permissions and add the sed command to alter the panel.html
> 
> I think of now it is the easiest method. In the future we need to add an more "flexible" method

We're aware of the "overwriting" issue and would like to implement a modular way. But currently there is no main focus, probaly it will be done during the interface redesign.
