### ISSUE TITLE
[Bug] Correct message to show if subdomains are disabled across multiple Users

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#2771]
### Describe the bug

I was just trying to host subdomain under another hestia user and kept getting error 'domain.com' exists. This is NOT an intuitive message and leads someone to believe some kind of BUG because we are trying to add sub.domain.com and not domain.com

Can we fix this message to a more elaborative phrase:
`Hosting Subdomains across multiple users is NOT ENABLED, please contact Hestia Admin to enable it.`

Many thanks

### Tell us how to replicate the bug

It is easily reproducable

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.4

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
> Can we fix this message to a more elaborative phrase:
> Hosting Subdomains across multiple users is NOT ENABLED, please contact Hestia Admin to enable it.

It also applies on mail domains and DNS domains. It makes sense to add a rule like:

<img width="368" alt="Screenshot 2022-08-17 at 14 09 02" src="https://user-images.githubusercontent.com/9754650/185114921-9c60ace2-5326-4068-adbb-c50e645db26a.png">

**Comment by jaapmarcus** [comment]
Or even beter

> Error: Unable to add test.hestiacp.nl. hestiacp.nl belongs to a different user
