### ISSUE TITLE
[Bug]  emails sent to aliases are sent to catch-all email as well

### ISSUE THREAD

**Issue by mbassiouny33** [hestiacp/hestiacp#2776]
### Describe the bug

I set up an alias for an email address.  when I send a message to that alias (from an external mailing server) the message is sent both to the aliased inbox and to the catch-all email inbox... 

I would expect a behavior where message should get to aliased inbox only, and to catch-all as a last resort if not even an alias exists) ? 

### Tell us how to replicate the bug

- create an email account.
- add an alias to that account
- Set up catch-all
- Send an email (from any mail provider) to that alias. 
- Email is now received  on both catch-all inbox and aliased inbox.

### Which components are affected by this bug?

Control Panel Backend, Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.4

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
See attached logs:

```
2022-07-16 08:59:03 1oCdde-0007tm-Vg <= jaap@xxxx.nl H=mail-qt1-f172.google.com [209.85.160.172] P=esmtps X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_128_GCM:128 CV=no SNI=mail.xxxx.org K S=3903 id=CAKCf7414ooF9BgYrq2tL03i3BZQi4Rb3ZK8-K-BF58Dgd2XXDA@mail.gmail.com
2022-07-16 08:59:04 1oCdde-0007tm-Vg => catch <test@xxx.org> R=localuser T=dovecot_virtual_delivery
2022-07-16 08:59:04 1oCdde-0007tm-Vg => info <test@xxxx.org> R=localuser T=dovecot_virtual_delivery
```

**Comment by divinity76** [comment]
@jaapmarcus that log suggest the alias was BOTH the catch-all AND the alias.. is that the case?

**Comment by mbassiouny33** [comment]
@divinity76 it is irrelevant.  

In my case they were not the same. And in his case, even if both are the same, you will see the error by receiving the message on that "test@..." mailbox twice.

**Comment by jaapmarcus** [comment]
@divinity76  In the settings catch was set as catch all and test as alias.

**Comment by mdlaat** [comment]
Same here, with hestia 1.6.14.
I solved it by adding an condition to the catchall router in /etc/exim4/exim4.conf.template. In one line:
`condition = ${lookup{$local_part@$domain}lsearch{/etc/exim4/domains/${lookup{$domain}dsearch{/etc/exim4/domains/}}/aliases}{false}{true}}`

This disables the catchall when the recipient of the message is listed in the aliases file for that domain.

I wonder however if this modification to exim4.conf.template will stay in place when a new version of hestia will be installed?

**Comment by jaapmarcus** [comment]
Yes, But please submit a PR so it will be added to Hestia :)

**Comment by xeruf** [comment]
We are on v1.7.8, and still experience this issue.

**Comment by jaapmarcus** [comment]
Can you check the contents of exim4.template.conf?

**Comment by xeruf** [comment]
```
$ sudo grep -n -2 aliases /etc/exim4/exim4.conf.template
332-  unseen
333-
334:aliases:
335-  driver = redirect
336-  headers_add = X-redirected: yes
337:  data = ${extract{1}{:}{${lookup{$local_part@$domain}lsearch{/etc/exim4/domains/${lookup{$domain}dsearch{/etc/exim4/domains/}}/aliases}}}}
338:  require_files = /etc/exim4/domains/$domain/aliases
339-  redirect_router = dnslookup
340-  pipe_transport = address_pipe
--
359-  driver = redirect
360-  headers_add = X-redirected: yes
361:  require_files = /etc/exim4/domains/$domain/aliases
362:  data = ${extract{1}{:}{${lookup{*@$domain}lsearch{/etc/exim4/domains/${lookup{$domain}dsearch{/etc/exim4/domains/}}/aliases}}}}
363-  file_transport = local_delivery
364-  redirect_router = dnslookup
365:  condition = ${lookup{@$domain}lsearch{/etc/exim4/domains/${lookup{$domain}dsearch{/etc/exim4/domains/}}/aliases}{false}{true}}
366-
367-terminate_alias:
368-  driver = accept
369-  transport = devnull
370:  condition = ${lookup{$local_part@$domain}lsearch{/etc/exim4/domains/${lookup{$domain}dsearch{/etc/exim4/domains/}}/aliases}{true}{false}}
371-
372-
```

**Comment by jaapmarcus** [comment]
Make sure it looks like:

https://github.com/hestiacp/hestiacp/blob/e060aa0ad985a09c5e4d629e73b69b1eba47fdfd/install/deb/exim/exim4.conf.4.94.template#L351-L363

This will resolve the issue

**Comment by xeruf** [comment]
So everyone has to adjust their conf manually when they upgrade or keep on having this issue?

**Comment by jaapmarcus** [comment]
Yes ... I don't know how many users are affected and how each config looks like.

Exim config updates is already a disaster...

**Comment by mdlaat** [comment]
Would it be easier for the maintenance if we switch to split configuration for exim4?
