### ISSUE TITLE
Only one web domain allowed and default port changing issue

### ISSUE THREAD

**Issue by dpushkar24** [hestiacp/hestiacp#2781]
### Describe the bug

Hi Team,

I am new to this HestiaCP platform and have recently started exploring and personally I just love it's interface.
But below are some issues I am facing with it;

1. Whenever I change it's default port to any other one (example: I made it from 8083 to 2083, the hestia webpage becomes completely inaccessible. I used command "v-change-sys-port 2083". I have also allowed these ports in oracle cloud and HestiaCP firewall with ip 0.0.0.0/0 but no luck.

2. My web domain, mail accounts, backups are only limited to 1. I am attaching screenshot for your reference.

Is it some other version which I got installed? We have any paid version?
Please help me with these 2 query.

Thanks and Regards,
Pushkar Deshpande

### Tell us how to replicate the bug

1. For port issue, we are getting as web page not found.
2. When I triend to add one more web domain, I am getting an "Error: WEB_DOMAINS limit is reached :: upgrade user package" 

### Which components are affected by this bug?

Control Panel Web Interface, Mail (Exim, Dovecot), Firewall (Iptables, Fail2ban)

### Hestia Control Panel Version

1.6.4

### Operating system

Ubuntu 22.04

### Log capture

```shell
Nothing found in log.
```

**Comment by jaapmarcus** [comment]
You need top open port 2083 as well in the firewall setting of Hestia

for When I triend to add one more web domain, I am getting an "Error: WEB_DOMAINS limit is reached :: upgrade user package"

Create a new user with the default package. Admin user should never been used for hosting websites

**Comment by dpushkar24** [comment]
Hello Jaap Marcus,

Thank you so much for reply.
I am able to add more than one web domain in my HestiaCP....:)

But my port issue still exist.
I already tried to add the firewall rule in HestiaCP firewall and as well as in my Oracle Cloud.
Let me share screenshot for the same, which will help you to to understand the entry's I made.

Also I am not able to access HestiaCP using my maintenance link which I configured as "hcp.dpushkar24.tk:<Post number>". It shows me that page is under construction. This domain I wish to dedicatedly use for HestiaCP access.


Once again, I really thank you for your reply and congratulate HestiaCP team for developing such a wonderful platform....:)

Thanks and Regards,
Pushkar Deshpande.

**Comment by jaapmarcus** [comment]
By default it will be:
hcp.dpushkar24.tk:8083 or if you have changed it to 2083 use: hcp.dpushkar24.tk:2083

**Comment by dpushkar24** [comment]
And just a last help needed.
HestiaCP is not accessible via any other port other than 8083.

Can you please suggest something on this?
I already tried to add the firewall rule in HestiaCP firewall and as well as in my Oracle Cloud but still no luck.
I used command "v-change-sys-port 2083".

**Comment by jaapmarcus** [comment]
It is mostly an Oracle cloud issue. 

See https://www.youtube.com/watch?v=BK7qyPa-VmI&t=2s 

for more information.
