### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Roshini0307** [hestiacp/hestiacp#2782]
### Describe the bug

Agent installation operation was not successful

Failed to install kit. Exit code: 1
Standard Output: Sudo path: /etc/opt/microsoft/scx/conf/sudodir/
Standard Error:
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
  #1) Respect the privacy of others.

    #2) Think before you type.

    #3) With great power comes great responsibility.
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
Exception Message:

### Tell us how to replicate the bug

We tried to Onboard redhat 7.9 server in SCOM 2022. while discovering we are getting the above mentioned error

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

blank

### Operating system

red hat 7.9 and 8.2 and 8.4

**Comment by ScIT-Raphael** [comment]
redhat isnt supported...

**Comment by divinity76** [comment]
Not yet anyway, but RHEL support is in active development, ref https://github.com/hestiacp/hestiacp/pull/2749
