### ISSUE TITLE
[Bug] curl to access the url containing "&" must add "\" in front of "&", otherwise it will not be able to read the parameters after "&", unfortunately adding "\" in front of "&" through hestiacp web interface is not valid.

### ISSUE THREAD

**Issue by allcdn** [hestiacp/hestiacp#2783]
### Describe the bug

`curl to access the url containing "&" must add "\" in front of "&", otherwise it will not be able to read the parameters after "&", unfortunately adding "\" in front of "&" through hestiacp web interface is not valid.`

### Tell us how to replicate the bug

`curl to access the url containing "&" must add "\" in front of "&", otherwise it will not be able to read the parameters after "&", unfortunately adding "\" in front of "&" through hestiacp web interface is not valid.`

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.4

### Operating system

debian11

**Comment by jaapmarcus** [comment]
Please explain where the issue is found?

**Comment by allcdn** [comment]
> 

In the timed task using curl can not get the parameters after the URL &, you need to add \ in front of &

**Comment by allcdn** [comment]
v-add-cron-job luren * * * * * sudo curl https://xxxxxxx.com/cron/wztask.php?sys=1&key=673007
I can't add \ in front of the & in the above URL, and the same problem is with the timed tasks in the web interface

**Comment by jaapmarcus** [comment]
use

"https://xxxxxxx.com/cron/wztask.php?sys=1&key=673007"
