### ISSUE TITLE
[Bug] Quick install Wordpress other languages then EN

### ISSUE THREAD

**Issue by funsurfer2008** [hestiacp/hestiacp#2788]
### Describe the bug

If you install Wordpress in English everything is fine.
If you change it to Germal for example the Wizzard running wrong, bcause the wp-config file is localized.
Can you fix it please?

brgds

### Tell us how to replicate the bug

go to quick install
select wordpress
change language to german

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.x

### Operating system

Debain

**Comment by jaapmarcus** [comment]
It doesn't work due to:

define( 'DB_NAME', 'datenbankname_hier_einfuegen' );
..

**Comment by jaapmarcus** [comment]
So locales translate the wp-config.php file

Great ...

**Comment by funsurfer2008** [comment]
Yes. Very Great. 😂

**Comment by jaapmarcus** [comment]
Even better is I did test it in Dutch and it worked fine...  But it uses the English wp-config file

**Comment by funsurfer2008** [comment]
Hmmm… why not overwrite wp-config with english content and then replace the lines.

**Comment by jaapmarcus** [comment]
https://github.com/WordPress/WordPress/blob/a0944f075a27f7d37f67315d98eda857280a7090/wp-admin/setup-config.php#L355-L391

Seems to be a working solution that aways works

**Comment by funsurfer2008** [comment]
Dont work at all for German
