### ISSUE TITLE
[Bug] v-change-user-package changing /home/user permissions to root:root

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2794]
### Describe the bug

When I execute the v-change-user-package to change the package (the package exists!), the /home/user change from user:user to root:root.

I can not replicate this with other hestiacp that I have.

The unique customization (that the other server also have exactly the same thing) is an extra nginx template (that copies the caching.tpl template to a new one with more time with cache).

### Tell us how to replicate the bug

```bash
drwxr-xr-x+ 12 tulsajobsite           tulsajobsite           4.0K Jul 25 20:03 zazajobsite
root@greenpanel:/home# /usr/local/hestia/bin/v-change-user-package zazajobsite unlimited
drwxr-xr-x+ 12 root                   root                   4.0K Jul 25 20:03 zazajobsite
```

I tried in another server with exact same config and nginx customization, but this same thing does not happen.

The same thing happen with default package:
```bash
/usr/local/hestia/bin/v-change-user-package zazajobsite default
drwxr-xr-x+ 12 root                   root                   4.0K Jul 25 20:03 zazajobsite
```

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.4

### Operating system

20.04.4

### Log capture

```shell
No relevants logs. I am trying to investigate v-change-user-package script (with -x) to identify how the /home/user permissions can be affected.
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/a1e592c530b5b39a9bd3af25d99b01eea18fc573/bin/v-add-user-sftp-jail#L71-L74

SFTP jail

**Comment by franciscopaniskaseker** [comment]
@jaapmarcus you are fast! I also found the package difference. of course something must be different in the config.

thank you.

**Comment by jaapmarcus** [comment]
Default has ssh access disabled (no login) probally you package allowed ssh login
