### ISSUE TITLE
File Editor [Feature] 

### ISSUE THREAD

**Issue by WafikAlmasry** [hestiacp/hestiacp#2795]
### Describe the feature or change in detail

if you can guys add file editor in cp
also if you let file tap open in new tap like others panel its will be good

Regards..

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
File editor using filegator is already in place, just click on "Files" in top header menu.

**Comment by WafikAlmasry** [comment]
There is not file Editor And This is Screen shot 

https://snipboard.io/cQybzV.jpg

**Comment by WafikAlmasry** [comment]
you cant edit the code online like other Panels

**Comment by jaapmarcus** [comment]
For filemanger we use Filegator and we have no intentions to replace it with something else or add support for a full editor to it. If you want you can check with the developer(s) of Filegator if they want to add it but for us it has no priority.

Also it allows to edit certain file types include .html / php and a few more.
