### ISSUE TITLE
[Bug] v-restore-user is not restore custom web templates

### ISSUE THREAD

**Issue by mbv** [hestiacp/hestiacp#2797]
### Describe the bug

As I see v-backup-user backup custom web templates in web/$domain/template directory. But v-restore-user is not restore it and just change template to default one.

### Tell us how to replicate the bug

1. Create user and web domain with custom web template
2. run v-backup-user on this user
3. in another cp (or just remove custom templates from templates directory), run v-restore-user for this user

Note that restored web domain uses the default template instead of the custom one.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.6.4

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
It was done like this intentionally. So at least in the worst case a server crash the backups always contains a backup the the template used is present. 

But restoring a template that is not tested on the new server can break things. Don't know enabling on default is ideal...
