### ISSUE TITLE
[Feature] Remove jQuery

### ISSUE THREAD

**Issue by imjuniper** [hestiacp/hestiacp#2798]
### Describe the feature or change in detail

While looking around the repo, I noticed that most JavaScript files use relatively outdated ways of doing things, such as using `var` instead of `const` or `let`, using some plain old objects instead of classes, lots of jQuery, etc.

It would be great to use modern JavaScript, since it would make the code more maintainable and future-proof. Also, dropping jQuery would remove a vulnerability surface to look for.

To do this change, a list of supported browsers would be necessary, to see which modern JavaScript features to use. I'd suggest using the [defaults from browserslist](https://browserslist.dev/?q=ZGVmYXVsdHM%3D) (`> 0.5%, last 2 versions, Firefox ESR, not dead`).

N.B. While I can't sponsor this change, I could do it myself. I have a bit more free time lately, and contributing to Hestia would be fun!

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Ideally it should be combined with a rewrite of CSS / PHP code...

**Comment by divinity76** [comment]
broadly, there are more important things to do, than re-writing old code that works fine :) PR's are welcome though

>most JavaScript files use relatively outdated ways of doing things

yup, much of it was written several years ago with IE6-compatibility in mind! the horror

>dropping jQuery would remove a vulnerability surface to look for.

at least jQuery 3 has an excellent security record!
2022-07: 0 vulnerabilities. 
2021: 0 vulnerabilities.
2020: 2 vulnerabilities 
2019: 1 vulnerability.
2018: 0 vulnerabilities.
2017: 0 vulnerabilities.
2016: 0 vulnerabilities. (2 honorable mentions, pre-release versions had 2 vulnerabilities discovered, both fixed prior to 3.0.0-RC2)

>N.B. While I can't sponsor this change, I could do it myself. I have a bit more free time lately, and contributing to Hestia would be fun!

feel free!

**Comment by divinity76** [comment]
>To do this change, a list of supported browsers would be necessary, to see which modern JavaScript features to use. I'd suggest using the [defaults from browserslist](https://browserslist.dev/?q=ZGVmYXVsdHM%3D) (> 0.5%, last 2 versions, Firefox ESR, not dead).

i think it would be cool if someone could integrate TypeScript, then we can use the newest javascript (and TypeScript) features, and let the transpiler deal with old crappy browsers! guess it would be a non-trivial amount of work though

**Comment by imjuniper** [comment]
Oh I know that there are more important things to do, but I am not super familiar with the codebase yet, and I'd like to start there.

> Ideally it should be combined with a rewrite of CSS / PHP code...

Agreed, though I am unsure of how you guys want the UI to look. I am great at executing designs, not the best at creating them. I could look into doing this at the same time honestly.

Unrelated to this, I am also thinking about updating the docs with something like [KitDocs](https://kit-docs.svelteness.dev/) or [VitePress](https://vitepress.vuejs.org). I have a little prototype up and running locally. It could actually replace both hestiacp.com and the docs.

Edit: Here is the (very basic) [demo](https://astonishing-cocada-67437a.netlify.app/). The homepage wouldn't have a "On this page section" and would actually look correct. It just needs some CSS adjustments. Also, if we deploy on Vercel, they might be able to provide us with an OSS sponsored account for hosting the website.

**Comment by imjuniper** [comment]
@divinity76 Regarding TypeScript, it would indeed be quite a lot of work hahaha. However, I feel like if Hestia wants to go in the direction of using modern tools (such as, my favorite, SvelteKit), it might be better to split the front-end and the back-end. Keep a PHP backend that we communicate with using a frontend built with a tool like SvelteKit.

If we're going to redo everything using TypeScript, might as well use a tool that integrates it directly in my opinion.

**Comment by jaapmarcus** [comment]
> > To do this change, a list of supported browsers would be necessary, to see which modern JavaScript features to use. I'd suggest using the [defaults from browserslist](https://browserslist.dev/?q=ZGVmYXVsdHM%3D) (> 0.5%, last 2 versions, Firefox ESR, not dead).
> 
> i think it would be cool if someone could integrate TypeScript, then we can use the newest javascript (and TypeScript) features, and let the transpiler deal with old crappy browsers! guess it would be a non-trivial amount of work though

Old browsers as in "IE" and so on should die it is not worth the time.

**Comment by theChaosCoder** [comment]
IE is officially not supported anymore. I think even the old Edge browser is unsupported since 2021.

**Comment by AlecRust** [comment]
Seems to me a good first chip at this would be a basic lint and build process for the existing JS. Perhaps Babel/webpack/ESLint, the CSS could also be built through this via PostCSS.

This would involve `node_modules`, `package.json`, `yarn.lock` etc. in the `web` directory. Are there any objections to such a build process? Is some other PHP-based solution preferred? This will need to integrate with whatever existing build/release process there is.

**Comment by jaapmarcus** [comment]
No Using npm is fine.

For prebuild packages it should be no issue and we can do in on default. Only for self building the packages / update via v-update-sys-hestia-git we need to find a solutions

**Comment by imjuniper** [comment]
Definitely agree over linting and PostCSS. It will also make a future TypeScript migration possible and easier. I'm unsure Babel is really necessary however, and I'd personally go with Vite rather than Webpack. It comes with TypeScript support by default and it's quite a bit faster to build too. If we prefer a build only option, Vite uses Rollup and esbuild under the hood. Honestly I'm unsure we even need a bundler for now. Just having Eslint and prettier would do the job no? I have a set of eslint rules I use for work and personal projects I'd be happy to provide. We could also just use SvelteKit's defaults which are pretty good tbh

**Comment by AlecRust** [comment]
> I'm unsure Babel is really necessary however, and I'd personally go with Vite rather than Webpack.

I don't have a strong preference here 👍 

> Just having Eslint and prettier would do the job no?

Totally agree, having JS/CSS linting enforced in CI (Actions?) seems the first step before worrying about bundlers.

As for formatting with Prettier, I agree but perhaps that PR should be after basic linting? Prettier would involve a full re-format of existing code, should probably include a pre-commit hook, and there are considerations like including all the `.html` files (which Prettier supports).

> I have a set of eslint rules

Sure, though having had a very brief look at this I imagine just making the codebase comply with the base rules e.g. `eslint:recommended`/`stylelint-config-standard` will be a large enough task for a first pass.

**Comment by imjuniper** [comment]
I'm starting to work on replacing jQuery as much as possible, and was thinking maybe [Alpine.js](https://alpinejs.dev/) might be interesting to use. I'll start with just replacing jQuery, but if we all think Alpine is interesting, I might start to implement it. It's better than using `javascript:` links.

**Comment by AlecRust** [comment]
jQuery usage has now been replaced with vanilla JS.

The JS is now comprised of the modules in [/web/js/src](https://github.com/hestiacp/hestiacp/tree/main/web/js/src) which are built into one bundle.

The JS should generally be easier to work with now and we're in a better place to refactor it further and implement things like TypeScript if desired. PRs welcome!
