### ISSUE TITLE
[Bug] file manager will not install

### ISSUE THREAD

**Issue by sandsjh** [hestiacp/hestiacp#2800]
### Describe the bug

File manager will not install

### Tell us how to replicate the bug

Settings
Configure
Plugins
File Manager -> Yes
Save

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.65

### Operating system

Debian 11

### Log capture

```shell
<br>Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/admin/.composer/composer/vendor/symfony/console/Helper/HelperSet.php on line 112<br><br>Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php:84<br>Stack trace:<br>#0 [internal function]: array_merge()<br>#1 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()<br>#2 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()<br>#3 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()<br>#4 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()<br>#5 phar:///home/admin/.composer/composer/src/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()<br>#6 phar:///home/admin/.composer/composer/src/Composer/Installer.php(232): Composer\Installer->doInstall()<br>#7 phar:///home/admin/.composer/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()<br>#8 phar:///home/admin/.composer/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()<br>#9 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()<br>#10 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()<br>#11 phar:///home/admin/.composer/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()<br>#12 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()<br>#13 phar:///home/admin/.composer/composer/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()<br>#14 phar:///home/admin/.composer/composer/bin/composer(61): Composer\Console\Application->run()<br>#15 /home/admin/.composer/composer(24): require('phar:///home/ad...')<br>#16 {main}<br> thrown in phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 84<br>ERROR: File Manager installation failed!<br>Please report this to our development team:<br>https://github.com/hestiacp/hestia
```

**Comment by jaapmarcus** [comment]
What happens when you run:

v-add-sys-filemanager

**Comment by sandsjh** [comment]
root@pp:/backup# v-add-sys-filemanager
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/admin/.composer/composer/vendor/symfony/console/Helper/HelperSet.php on line 112

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/admin/.composer/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()
#4 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 phar:///home/admin/.composer/composer/src/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()
#6 phar:///home/admin/.composer/composer/src/Composer/Installer.php(232): Composer\Installer->doInstall()
#7 phar:///home/admin/.composer/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 phar:///home/admin/.composer/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#9 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#10 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#11 phar:///home/admin/.composer/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#12 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#13 phar:///home/admin/.composer/composer/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#14 phar:///home/admin/.composer/composer/bin/composer(61): Composer\Console\Application->run()
#15 /home/admin/.composer/composer(24): require('phar:///home/ad...')
#16 {main}
  thrown in phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()
#4 phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 phar:///home/admin/.composer/composer/src/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()
#6 phar:///home/admin/.composer/composer/src/Composer/Installer.php(232): Composer\Installer->doInstall()
#7 phar:///home/admin/.composer/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 phar:///home/admin/.composer/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#9 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#10 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#11 phar:///home/admin/.composer/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#12 phar:///home/admin/.composer/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#13 phar:///home/admin/.composer/composer/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#14 phar:///home/admin/.composer/composer/bin/composer(61): Composer\Console\Application->run()
#15 /home/admin/.composer/composer(24): require('phar:///home/ad...')
#16 {main}
  thrown in phar:///home/admin/.composer/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 84
ERROR: File Manager installation failed!
Please report this to our development team:
https://github.com/hestiacp/hestiacp/issues
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

**Comment by jaapmarcus** [comment]
rm -fr /home/admin/.composer 

And then run it again

Is it a new install?

**Comment by sandsjh** [comment]
This fixed the issue. A new install <1 week.

> rm -fr /home/admin/.composer
> 
> And then run it again
> 
> Is it a new install?

**Comment by jaapmarcus** [comment]
Strange it looks like composer v1 is installed instead have no idea why it happened

**Comment by sandsjh** [comment]
> Strange it looks like composer v1 is installed instead have no idea why it happened

Thought about it after this reply... I restored the admin account from a 1.63 server.

**Comment by jaapmarcus** [comment]
It might be possible that the admin users still had composer v1 running. 

Might add an option to force update to v2 first
