### ISSUE TITLE
[Bug] v-delete-web-domain-backend Error: php-fpm pool doesn't exist

### ISSUE THREAD

**Issue by adion-gorani** [hestiacp/hestiacp#2803]
### Describe the bug

When calling:
 v-delete-web-domain-backend user domain name  
to a domain that has been changed with v-change-web-domain-name
it shows  Error: php-fpm pool doesn't exist
even when the  sub.domainame.com.conf file is present in /etc/php/7.4/fpm/pool.d causing PHP to crash when the user is deleted.

find -L /etc/php/ -name "sub.domainame.com.conf" -exec dirname {} \;
/etc/php/7.4/fpm/pool.d
/etc/php/8.0/fpm/pool.d

### Tell us how to replicate the bug

1) create a user and add a domain to the user
2) change the domain name using the command v-change-web-domain-name 
3) run  v-delete-web-domain-backend user domain name  

error:
Error: php-fpm pool doesn't exist

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.6.5

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
I can't replicate the error:

```
root@dev:~# v-add-web-domain test test.nl
root@dev:~# v-add-web-domain test sub.test.nl
root@dev:~# v-change-web-domain-backend-tpl test test.nl PHP-8_1
root@dev:~# v-delete-web-domain-backend test test.nl
root@dev:~# v-delete-web-domain-backend test sub.test.nl
```

And I have no error...  

Only after now if I want to delete the web domain

```
root@dev:~# v-delete-web-domain test test.nl
Error: php-fpm pool doesn't exist
root@dev:~# v-delete-web-domain test sub.test.nl
Error: php-fpm pool doesn't exist
```

Nevermind v-change-domain name ...

**Comment by adion-gorani** [comment]
This occurs on Nginx only installation without apache:

v-add-user test paSSwoRd your@email.net
v-add-web-domain test test.nl
v-add-web-domain test sub.test.nl
v-change-web-domain-name test test.nl newdom.test.nl
v-delete-user test


● php8.0-fpm.service - The PHP 8.0 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.0-fpm.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-07-29 15:15:03 UTC; 6s ago
       Docs: man:php-fpm8.0(8)
    Process: 7989 ExecStart=/usr/sbin/php-fpm8.0 --nodaemonize --fpm-config /etc/php/8.0/fpm/php-fpm.conf (code=exited, status=78)
    Process: 8003 ExecStopPost=/usr/lib/php/php-fpm-socket-helper remove /run/php/php-fpm.sock /etc/php/8.0/fpm/pool.d/www.conf 80 (code=exited, status=0/SUCCESS)
   Main PID: 7989 (code=exited, status=78)

Jul 29 15:15:03 test.mee.com systemd[1]: Starting The PHP 8.0 FastCGI Process Manager...
Jul 29 15:15:03 test.mee.com php-fpm8.0[7989]: [29-Jul-2022 15:15:03] **ERROR: [pool test.nl] cannot get uid for user 'test'**
Jul 29 15:15:03 test.mee.com php-fpm8.0[7989]: [29-Jul-2022 15:15:03] ERROR: FPM initialization failed
Jul 29 15:15:03 test.mee.com systemd[1]: php8.0-fpm.service: Main process exited, code=exited, status=78/CONFIG
Jul 29 15:15:03 test.mee.com systemd[1]: php8.0-fpm.service: Failed with result 'exit-code'.
Jul 29 15:15:03 test.mee.com systemd[1]: Failed to start The PHP 8.0 FastCGI Process Manager.

**Comment by jaapmarcus** [comment]
I noticed v-change-web-domain-name doesn't delete test.nl.conf in pool.d

**Comment by adion-gorani** [comment]
i was able to reproduce the bug and submitted a change

v-add-user test paSSwoRd your@email.net
v-add-web-domain test test.nl
v-add-web-domain-backend test test.nl PHP-7_4
v-add-web-domain-backend test test.nl PHP-8_0
v-delete-web-domain-backend test test.nl
Error: php-fpm pool doesn't exist

**Comment by jaapmarcus** [comment]
You should use v-change-web-domain-backend-tpl instead it does the same trick but deletes the old one first

Added a check that is can't be ran of it was created before.

**Comment by jaapmarcus** [comment]
Changes have been merged
