### ISSUE TITLE
[Feature] Update DokuWiki to new stable (from oldstable)

### ISSUE THREAD

**Issue by kpapad904** [hestiacp/hestiacp#2811]
### Describe the feature or change in detail

FYI DokuWiki released new stable version 2022-07-31 "Igor" (currently HestiaCP installs the oldstable release 2020-07-29 “Hogfather”)

For details please see https://www.dokuwiki.org/changes

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
👍🏼
