### ISSUE TITLE
[Bug] - Notification mail account dont include Password when creating

### ISSUE THREAD

**Issue by saxico** [hestiacp/hestiacp#2815]
### Describe the bug

When you create a new email account and enter a notification email, the password does not appear in the notification email.

However, if you edit an existing email account, and fill in the field in the notification email, the password is sent in the notification email.

### Tell us how to replicate the bug

1. Create a new email account
2. Complete the "Email login credentials to"
3. See the received email

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.6.6

### Operating system

Debian 10 buster

**Comment by jaapmarcus** [comment]
Linked PR should solve the issue
