### ISSUE TITLE
ForceSSL not working in Nginx + PHP-FPM Environment

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#282]
### Brief issue description:
ForceSSL is not working in Nginx + PHP-FPM Environment. It creates an Apache configuration file (forcessl.apache2.test.org.conf) instead of an Nginx one. Also, the forcessl include line is not included in any Nginx/PHP-FPM templates.

### Steps to Reproduce:
1. Edit Web Domain
2. Enable SSL
3. Enforce HTTPS connections for this site

### Expected behavior:
Visitor should be redirected from http to https

### Operating system distribution and release:
Ubuntu 18.04.1 LTS

### HestiaCP Version:
0.9.8-28)

### Which branch are you using?
master

### What software is installed?
Nginx, PHP-FPM, Dovecot/Exim, MariaDB

**Comment by Lupul** [comment]
Fixed in #288 yesterday on develop branch, can you test and confirm?

**Comment by ghost** [comment]
Issue should be resolved, closing for now -- please reopen if issue reoccurs.
