### ISSUE TITLE
[Bug] Email account change password not working after update 1.6.6

### ISSUE THREAD

**Issue by estratos** [hestiacp/hestiacp#2820]
### Describe the bug

New mail password change does not work not even recreating the account or create new ones
When creating the email account the mail folder appears empty
Folder permissions are OK

### Tell us how to replicate the bug

1. Open the mail domain in UI in backend Panel
2. select account and generate new password, SAVE not errors will be shown
3. open webmail.domain.com  user and pass, the response always is  POST https://webmail.domain.com/?_task=login 401 in console

### Which components are affected by this bug?

Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.6.6

### Operating system

Ubuntu 20.04

### Log capture

```shell
POST https://webmail.domain.com/?_task=login 401
```

**Comment by jaapmarcus** [comment]
```
sed -i "s/\$config\['auto_create_user'] = false;/\$config\['auto_create_user'] = true;/g" /etc/roundcube/config.inc.php    
```

Will fix the issue

**Comment by estratos** [comment]
Thank you!, works perfect on all my servers
