### ISSUE TITLE
[Bug] After Upgrade from 1.6.5 to 1.6.6 Roundcube shows HTML Messages in Plaintext

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#2824]
### Describe the bug

After Upgrade from 1.6.5 to 1.6.6 Roundcube shows HTML Messages in Plaintext

This can be changed in the inviduals options to display HTML messages
but all my users preferences have been switched.

I think the next update should set Display HTML to on globally for the next Hestia update as it was default before the 1.6.6 update 

### Tell us how to replicate the bug

Upgrade from Hestia 1.6.5 to 1.6.6
login roundcube
Open an HTML message

### Which components are affected by this bug?

Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.6.6

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
I don't know what "Roundcube did with the settings... after upgrade from 1.5.x to 1.6.0

**Comment by jaapmarcus** [comment]
#2825 Will fix the issue

**Comment by johnnyq** [comment]
Excellent Thank you @jaapmarcus
