### ISSUE TITLE
[Bug] Message delivery failed to Gmail

### ISSUE THREAD

**Issue by dpushkar24** [hestiacp/hestiacp#2828]
### Describe the bug

Hi Team,

Fist of all, I would like to thank you so much for providing us such a handy tool.

But I am facing issue while sending mail to gmail and other domain's and getting below mail reply;
I recived a reply on 29th Jul 2022

### Tell us how to replicate the bug

I tried to send a test mail through administrator@dpushkar24.tk and pushkar.deshpande@@dpushkar24.tk but getting an error and no mail is getting delivered to gmail.

I also tried to use SMTP relay sendinblue, but still no luck.

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.6

### Operating system

Ubuntu 22.04 (aarch64)

### Log capture

```shell
This message was created automatically by mail delivery software.
A message that you sent has not yet been delivered to one or more of its recipients after more than 72 hours on the queue on hcp.dpushkar24.tk.

The message identifier is:     1oGDan-0043iD-UY
The date of the message is:    Tue, 26 Jul 2022 11:28:53 +0530
The subject of the message is: Re: test

The address to which the message has not yet been delivered is:

  [deshpandepushkar9@gmail.com](mailto:deshpandepushkar9@gmail.com)

No action is required on your part. Delivery attempts will continue for some time, and this warning may be repeated at intervals if the message remains undelivered. Eventually the mail delivery software will give up, and when that happens, the message will be returned to you.
```

**Comment by ScIT-Raphael** [comment]
Check your exim mainlog, but probaly sending mails over port 25 is denied by your provider.

This isnt a bug, more a configuration/setup issue, please use our forum or discord channel for support requests.
