### ISSUE TITLE
[Bug] - SPF in DNS when SmartHost is used

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#2830]
### Describe the bug

When setting a global or even domain specific smarthost, it should ask for the details for SPF records, so that when a Webdomain is setup and the mail and dns options are checked, the SPF record is setup

I know there are probably loads of permutations, so at the very least a warning should be shown when smarthost is set and maildomain is being added that an SPF record needs to be created in the relevant DNS zone

### Tell us how to replicate the bug

Set Global SmartHost
Set up a web domain and check options for Mail and DNS
Watch emails get rejected

### Which components are affected by this bug?

Control Panel Backend, Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.6

### Operating system

Debian 10

**Comment by jaapmarcus** [comment]
There are a lot of options and depending on the smarthost used there are 100 different options. It is not practical to instruct users to how they setup. 

If you use a smarthost you should be able to set it up your self... Also not all users are using Hestia for their DNS
