### ISSUE TITLE
[Feature] ClamAV installation is outdated

### ISSUE THREAD

**Issue by dfag86** [hestiacp/hestiacp#2832]
### Describe the feature or change in detail

/var/log# nano ./clamav/freshclam.log

Thu Aug 11 10:19:40 2022 -> Received signal: wake up Thu Aug 11 10:19:40 2022 -> ClamAV update process started at Thu Aug 11 10:19:40 2022 Thu Aug 11 10:19:40 2022 -> WARNING: Your ClamAV installation is OUTDATED! Thu Aug 11 10:19:40 2022 -> WARNING: Local version: 0.103.6 Recommended version: 0.103.7

I think we need an update :)

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
Please reach out to the os repository provider, we install it from there. We can't provide each package on our own.
