### ISSUE TITLE
[Bug] plugin files manager cannot enable

### ISSUE THREAD

**Issue by ystartgo** [hestiacp/hestiacp#2833]
### Describe the bug

files manager is missing in control pannel
try to enable files manager show 
Unable to write keys.dev.pub to: /home/admin/.config/composer<br>Error: Composer install failed

### Tell us how to replicate the bug

try to enable file manager

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.7

### Operating system

Debian 10.12 (x86_64)

**Comment by jaapmarcus** [comment]
rm -rf  /home/admin/.composer

And try again

**Comment by ystartgo** [comment]
I found that /home/admin/.config/composer owner is root
I changed to admin and it worked
