### ISSUE TITLE
[Bug] EXIM4 - 454 TLS currently unavailable

### ISSUE THREAD

**Issue by iAndriiK** [hestiacp/hestiacp#2837]
### Describe the bug

We noticed that the exim4 mail server config file does not support TLS domain certificates, but tries to pull the main certificates from hestia by default.
This is critical for GMAIL mail, which is quite strict about TLS checking. As a result, letters sent from foo@gmail.com do not reach the addressee.

Instead we see an error:
454 TLS currently unavailable

We analyzed the /var/log/exim4/mainlog file, determined that hestiacp does not try to get TLS of a specific domain at all, but immediately checks the root certificate and get an error:
2022-08-13 14:01:11 TLS error on connection from mail-oi1-f173.google.com [209.85.167.173] (cert/key setup: cert=/usr/local/hestia/ssl/certificate.crt key =/usr/local/hestia/ssl/certificate.key): Error while reading file.

From the file /etc/exim4/exim4.conf.template we understand that the check exists:
tls_certificate=\
        ${if and {\
                     { eq {${domain:foo@$tls_in_sni}} {$tls_in_sni}}\
                     { exists{/usr/local/hestia/ssl/mail/$tls_in_sni.crt} }\
                 }\
                 {/usr/local/hestia/ssl/mail/$tls_in_sni.crt}\
                 {/usr/local/hestia/ssl/certificate.crt}\
         }

tls_privatekey=\
        ${if and {\
                     { eq {${domain:foo@$tls_in_sni}} {$tls_in_sni}}\
                     { exists{/usr/local/hestia/ssl/mail/$tls_in_sni.key} }\
                 }\
                 {/usr/local/hestia/ssl/mail/$tls_in_sni.key}\
                 {/usr/local/hestia/ssl/certificate.key}\
         }

But the $tls_in_sni variable is not initialized. Apparently, this is the cause of the error and the incorrect receipt of the domain certificate.

### Tell us how to replicate the bug

1. Create next symlinks. This not necessarily, but preferred.
1.1. ln -s /home/{user}/conf/web/{domain}/ssl/{domain}.crt
1.2. ln -s /home/{user}/conf/web/{domain}/ssl/{domain}.key
This is required for https://example.com:8083 to work in HSTS mode with a valid certificate.
2. Send message from mail foo@gmail.com to foo@{domain}.

In any case, hestiacp does not access files in the /usr/local/hestia/ssl/mail/ directory.

### Which components are affected by this bug?

Let's Encrypt SSL, Mail (Exim, Dovecot), Mail Security (Antivirus, Antispam)

### Hestia Control Panel Version

1.6.7

### Operating system

Ubuntu 20.04 (x86_64)

**Comment by jaapmarcus** [comment]
Can you try if the issue still exists if you use v-add-letsencrypt-host or use :
https://github.com/hestiacp/hestiacp/blob/main/bin/v-update-host-certificate

If possible please provide more error logs and I assume you symlinked  
/home/{user}/conf/web/{domain}/ssl/{domain}.crt to /usr/local/hestia/ssl/mail/ ?

It might be the permissions by default exim does not have read permissions to the /home/user/conf/web/ssl/ folder

**Comment by iAndriiK** [comment]
![image](https://user-images.githubusercontent.com/11510994/184495653-a78aeb32-dce0-4a50-81a5-ccbbcf513bf0.png)
![image](https://user-images.githubusercontent.com/11510994/184496108-f9ed6620-ae37-4d61-b3a0-2acacfc30d98.png)
![image](https://user-images.githubusercontent.com/11510994/184495830-b8e71978-099b-45a3-9386-35381bdbe0f7.png)

If you bring the file to the following type, then everything works perfectly.
```
tls_certificate = \
        ${if and {\
                     { eq {${domain:foo@$tls_in_sni}} {$tls_in_sni}}\
                     # { exists{/usr/local/hestia/ssl/mail/$tls_in_sni.crt} }\
                     { exists{/home/{user}/conf/mail/{domain}/ssl/{domain}.crt} }\
                 }\
                 # {/usr/local/hestia/ssl/mail/$tls_in_sni.crt}\
                 # {/usr/local/hestia/ssl/certificate.crt}\
                 {/home/{user}/conf/mail/{domain}/ssl/{domain}.crt}\
                 {/home/{user}/conf/web/{domain}/ssl/{domain}.crt}\
         }

tls_privatekey = \
        ${if and {\
                     { eq {${domain:foo@$tls_in_sni}} {$tls_in_sni}}\
                     # { exists{/usr/local/hestia/ssl/mail/$tls_in_sni.key} }\
                     { exists{/home/{user}/conf/mail/{domain}/ssl/{domain}.key} }\
                 }\
                 # {/usr/local/hestia/ssl/mail/$tls_in_sni.key}\
                 # {/usr/local/hestia/ssl/certificate.key}\
                 {/home/{user}/conf/mail/{domain}/ssl/{domain}.key}\
                 {/home/{user}/conf/web/{domain}/ssl/{domain}.key}\
         }
```

But this approach does not work in the case of mailboxes for several domains.

**Comment by jaapmarcus** [comment]
We copy for this reason: 

https://github.com/hestiacp/hestiacp/blob/258684b6c95e474efbbe61738b1d0992ace3c5b0/func/domain.sh#L696-L706

The certifies in the correct /home/{user}/conf/mail/{domain}/ssl/{domain}.key. for this reason

When it is missing 

https://github.com/hestiacp/hestiacp/blob/d50f95cf208049dfb6ac67a8020802121745bd60/bin/v-update-host-certificate#L64-L75

Will do the same trick no changes should be needed

**Comment by jaapmarcus** [comment]
So the correct option would be run:

`v-update-host-certificate admin domain.com `

And your issues are solved.

**Comment by jaapmarcus** [comment]
Also I am not able to replicate if both ssl for mail.domain.com and hostname.com are enabled:


2022-08-13 14:21:38 1oMs1C-00EHhu-I6 <= xxxxxx@gmail.com H=mail-yw1-f180.google.com [xxxxxx] P=esmtps X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_128_GCM:128 CV=no SNI=mail.viraal.org K S=4159 DKIM=gmail.com id=CALxctMASfs7O30ZQH90Zv-2+kRb+xxxx-UaA@mail.gmail.com
2022-08-13 14:21:38 1oMs1C-00EHhu-I6 => info <info@xxxxx> R=localuser T=dovecot_virtual_delivery
2022-08-13 14:21:38 1oMs1C-00EHhu-I6 Completed
