### ISSUE TITLE
[Feature] Prevent creating cname records for @ selector

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#2838]
### Describe the feature or change in detail

According to "A CNAME cannot be placed at the root domain level, because the root domain is the DNS Start of Authority (SOA) which must point to an IP address." we should not allow to create a cname record for the "top level record"/@-selector.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
See linked PR for fix
