### ISSUE TITLE
[Bug] Using the command v-change-domain-owner does not seem to properly work with e-mail domain names.

### ISSUE THREAD

**Issue by TowyTowy** [hestiacp/hestiacp#2840]
### Describe the bug

After using the command v-change-domain-owner, with a user that only has mail domains and no web domains attached to it, I get the following erros:
![image](https://user-images.githubusercontent.com/85077986/184511022-1da01014-1dbe-45fc-84de-42813845baaa.png)
![image](https://user-images.githubusercontent.com/85077986/184511029-a0eaf145-b7b9-4b6f-aef8-f68ddf349f2d.png)

This is the mail.conf for that user 
![image](https://user-images.githubusercontent.com/85077986/184511038-1207a763-8ccd-402d-8c74-7fc8349ad36d.png)

Sending mails then doesn't seem to work properly as seen in the log files of exim4
![image](https://user-images.githubusercontent.com/85077986/184511053-39207604-27ae-44f5-8303-eb3444db6b06.png)

### Tell us how to replicate the bug

1. Use the command v-change-domain-owner to transfer mail domains from a user that only has mail domains.
2. That's it

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.6.7

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
See attached PR
