### ISSUE TITLE
[Bug] Can't close shortcuts help on Full HD screen

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#2844]
### Describe the bug

![image](https://user-images.githubusercontent.com/13354331/184862641-383231e8-004c-46e7-9b2d-bca3b01742ae.png)
- scrolling scrolls the page, popup stays in position
- clicking away or pressing escape does not close it

So I have to reload the page or click the shortcut help button again, and I can't even see all shortcuts...

### Tell us how to replicate the bug

Open Shortcut help

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

installed latest a few weeks ago, you are really missing a display of that somewhere in the panel

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
What browser are you using?

I think we should consider removing it from the panel and move it to the documentation.

**Comment by xeruf** [comment]
No, please leave it there, shortcuts often get buried in the docs!

Firefox latest on Arch

**Comment by jaapmarcus** [comment]
I don't have any issues on Firefox. Can you provide the contents of javascript error console?

**Comment by xeruf** [comment]
There are no errors, it is just that the popup does not adapt well to smaller screens. If I zoom out to 80% I can actually see the whole window.

**Comment by jaapmarcus** [comment]
It should render like: (Firefox OSX)  Last version:
<img width="981" alt="Screenshot 2022-08-20 at 13 48 17" src="https://user-images.githubusercontent.com/9754650/185744597-3beffefc-48a8-4e6d-9616-63adb310d94d.png">

You might be able with css editor  in Firefox width of the .shortcuts ul to 300 for example and see how it works. But I don't have an smaller screen for testing over here..

**Comment by xeruf** [comment]
you can just resize your browser window lol

but simply removing the hardcoded width from `.shortcuts ul` fixes it:
![image](https://user-images.githubusercontent.com/13354331/185746038-38d3410f-157d-4e54-b044-b08b765af7ad.png)
![image](https://user-images.githubusercontent.com/13354331/185746059-c3268d98-efc5-45b9-9117-e02894e62fd6.png)

**Comment by jaapmarcus** [comment]
<img width="787" alt="Screenshot 2022-11-07 at 07 55 24" src="https://user-images.githubusercontent.com/9754650/200244343-d6d590da-e2c5-4da3-95bd-755077298b8c.png">
