### ISSUE TITLE
[Feature] - ADD server total disk space info

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#2846]
### Describe the feature or change in detail

If possible, kindly [Feature] - ADD server total/used/remaining disk space info please.

Eg ref : https://ibb.co/FstsDS1

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by ScIT-Raphael** [comment]
it is not planed to add a diskusage there due to space limitations. Please consider to "just" visit https://your.domainhere.tld:8083/list/server/?disk. Also server monitoring is not a part of hestia, I would suggest to use something like icinga2 or similar.
