### ISSUE TITLE
[Bug] backup failed: Can't create temp folder on sftp

### ISSUE THREAD

**Issue by MenschLink** [hestiacp/hestiacp#2847]
### Describe the bug

I get this email, and no new backup was made on the remote drive

### Tell us how to replicate the bug

add a remote sftp backup location
wait for email telling you that the backup couldn't be made

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.7

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
cant create tmp directory means that you probaly dont have write access with the used sftp creds, login manualy and try to create a file or folder.

**Comment by jaapmarcus** [comment]
Also make sure to setup the correct path of it is required

https://github.com/hestiacp/hestiacp/blob/a2eb03a9e75d09806b8c6ab6851c121482720397/func/backup.sh#L116

**Comment by MenschLink** [comment]
> cant create tmp directory means that you probaly dont have write access with the used sftp creds, login manualy and try to create a file or folder.

it was perfectly able to make backups via sftp a week ago. I have also created files and folders manually with the credentials via filezilla

> Also make sure to setup the correct path of it is required
> 
> https://github.com/hestiacp/hestiacp/blob/a2eb03a9e75d09806b8c6ab6851c121482720397/func/backup.sh#L116

I'm not even sure what you're trying to tell me. I should check if this line exists in my backup.sh script on my server - which should be the case because I get the updates automatically?

**Comment by ScIT-Raphael** [comment]
He means the correct backup path in server settings. We had no changes to the backup engine since a few releases, so I don't think this is related due to a code change - also there are no other reports. So mostly its  a local issue, but I can't really guide you where to debug.

**Comment by jaapmarcus** [comment]
There have been no changes made since 1.6.0 and even those changes should not affect the SFTP backup system:

So it fails in the code there:

https://github.com/hestiacp/hestiacp/blob/a2eb03a9e75d09806b8c6ab6851c121482720397/func/backup.sh#L109-L125

Assuming  the settings are correct. 

How ever I am using sftp backup from my own servers and had never had an issue so far

**Comment by MenschLink** [comment]
you know, the temp directory "vst.bK76A9SUkt" is there in the destination sftp folder. Is it possible that when there are many backups to be made, there is a race condition because of the async nature of network file operations that causes the script to abort because it can't create an already existing folder?

**Comment by ScIT-Raphael** [comment]
temporary files are usualy generic, the filename cant exist twice. But you can remove that folder and try it again.

**Comment by MenschLink** [comment]
just removed it and I will get back to you after the next backup cycle

**Comment by ScIT-Raphael** [comment]
you can trigger a backup with v-backup-user if you want to enforce it.

**Comment by MenschLink** [comment]
I am on my way out of the office now xD

**Comment by MenschLink** [comment]
ok backups were made after I deleted the temp folder but I was notified for one backup that it couldn't login to the sftp to make backups. So yes, there might generally be a problem with making remote backups when there is a certain number of accounts to backup

**Comment by jaapmarcus** [comment]
Backups are made after each other unless you make backups from more servers to that server...

**Comment by MenschLink** [comment]
> 

just from this server...
