### ISSUE TITLE
[Bug] Setting Timezone to UTC under Basic Settings goes back to AKST

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#2851]
### Describe the bug

When you go to Configure | Configure | Basic Options

If you set the TimeZone to UTC, after saving it goes to AKST

### Tell us how to replicate the bug

1. Login as Admin
2. Click Gear Icon
3. Click Configure
4. Expand Basic Options
5. Change TimeZone to UTC
6. Click Save
7. Expand Basic Options again
8. TimeZone will be AKST

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.7

### Operating system

Debian 10

**Comment by jaapmarcus** [comment]
Reloading with out submitting works fine 

Will patch the issue
