### ISSUE TITLE
[Feature] Allow unlimited backups

### ISSUE THREAD

**Issue by leowinterde** [hestiacp/hestiacp#2858]
### Describe the feature or change in detail

Allow unlimited backups on the edit package page.

![Screenshot 2022-08-20 215809](https://user-images.githubusercontent.com/1300141/185764169-8e8e1cda-b0ce-4946-942b-69ca328f11c4.png)

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
Unlimited backups doesnt make any sense - if you want to have "a lot", set it to 3650 and you would get around 10 years backup.

Why should it be unlimited in your opinion? Its also risky that you'll overload your backup storage.

**Comment by leowinterde** [comment]
It allows me to use a write only key for the backblaze b2 backup option, i will rotate and delete old backups with the backblaze [lifecycle rules](https://www.backblaze.com/b2/docs/lifecycle_rules.html) feature.

This way I can ensure the integrity of my backups if the server is compromised.

**Comment by jaapmarcus** [comment]
Set the value +1 or higher then the lifetime of your blackbaze and delete everything B2 deletes a file it is reflected in 
/usr/local/hestia/data/users/user/backup.con hestiacp will never delete an older backup 

I don't see reason why we have to spend time to change it for 1 user...
