### ISSUE TITLE
[Feature] Improve graphs on "Task Monitor" page

### ISSUE THREAD

**Issue by AlecRust** [hestiacp/hestiacp#2859]
### Describe the feature or change in detail

The graphs on the "Task Monitor" page are basic static images that get reloaded with the page every 10 seconds or so:

![image](https://user-images.githubusercontent.com/247634/185794566-fb50ba85-703e-496f-8ced-5f4642b7923a.png)

It would be great if we could get real graphs, even better if the data was somewhat realtime. WordOps for example has interactive graphs ([demo](https://demo.wordops.eu/)).

I'm not sure how accessible this data is, if it can be streamed to the page etc. but I thought I'd put in this feature request as I think it would improve the Hestia experience.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by dfag86** [comment]
it's not needed, that's why it's uptime kuma, or zabbix or other software.

**Comment by jaapmarcus** [comment]
We store the data in a .rrd and with https://oss.oetiker.ch/rrdtool/doc/rrdxport.en.html#I__json you should be able to export it. So it should be relative easy if we can include a "graph" js library it should be easy to solve.

**Comment by jaapmarcus** [comment]
> it's not needed, that's why it's uptime kuma, or zabbix or other software.

For info it is not a bad idea rrd graphs are not the most user friendly

**Comment by dfag86** [comment]
it is important that it is a lightweight solution.  The panel should be light and not put a strain on the processor.  You know 😊😎

**Comment by jaapmarcus** [comment]
```
rrdtool xport --json -s $(date -d "1 day ago" +%s) -e $(date +%s) --step 600    DEF:la=$RRD/la/la.rrd:LA:AVERAGE DEF:pr=$RRD/la/la.rrd:PR:AVERAGE XPORT:la:load
```

Should do the trick

**Comment by jaapmarcus** [comment]
https://github.com/jaapmarcus/hestiacp/tree/feature/2859-improve-task-monitor

v-export-rrd  should have the required info only updating the task manger page left

**Comment by AlecRust** [comment]
Nice one. What would you suggest calls this script to load the data on the page?

I had a very brief look at this page in my Multipass Ubuntu VM, and noticed there was no data populating the current image charts. I assume this is something to do with my development setup not being a live production server 🤷‍♂️ 

In terms of chart library I would typically reach for [Chart.js](https://www.chartjs.org/), any other preference?

**Comment by jaapmarcus** [comment]
That might be the issue it is based on the same images ...

**Comment by jaapmarcus** [comment]
Chart.js is fine for me I think I used in the past

**Comment by AlecRust** [comment]
> noticed there was no data populating the current image charts

This is no longer an issue thankfully.

> only updating the task manger page left

Excuse my ignorance, but I'm not quite sure where to go from here (should have some time to look at this soon).

I see you added a new `bin/v-export-rrd` script in that branch that returns JSON. Do we need some PHP to call that script for use on the page? Is there some existing pattern for this in the project?

Currently the page reloads every 10 seconds or so. Would be great if we could [update the chart data](https://www.chartjs.org/docs/latest/developers/updates.html#adding-or-removing-data) via JS to avoid this.

**Comment by jaapmarcus** [comment]
We can use Ajax / javascript to call a php script an does the job...

**Comment by jaapmarcus** [comment]
Feature has been added...

**Comment by jaapmarcus** [comment]
PR has been reverted as we didn't feel it was ready enough..
