### ISSUE TITLE
[Feature Request]: Implement plugin/theme system & API

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#286]
[Feature-Request] Any plan to use hooks-plugins modals ? (Like custom themes, custom modules).
- Should not be overwritten by Hestia updates, but the plugin owner should have to update accordingly (Same like wordpress)

**Comment by ghost** [comment]
Hi @vvcares,
Thanks for your feedback! The implementation of a proper plugin system, basic API documentation, and development guidelines is currently on the roadmap for a future release.

**Comment by ghost** [comment]
Hi @vvcares, just wanted to let you know that support for custom CSS themes will be available starting with the v1.1.0 feature release.

**Comment by vvcares** [comment]
Woow. Thankn you for this nice initiative. Hopes can see more custom options..

**Comment by ScIT-Raphael** [comment]
Theme functionality has been added to master release.
