### ISSUE TITLE
[Bug]  Control Panel Login Error code 500

### ISSUE THREAD

**Issue by Surgical71** [hestiacp/hestiacp#2860]
### Describe the bug

Unable to login due to error code 500. Log entry:
"PHP message: PHP Warning:  Undefined array key 1 in /usr/local/hestia/web/inc/prevent_csrf.php on line 59"

I used the Hestia ubuntu scripts to install and everything worked fine until the latest update. 
Side question: For future reference, if I want to reinstall Hestia but keep my database the same how would I go about doing that?

### Tell us how to replicate the bug

Unable to log in

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.7

### Operating system

Ubuntu 20.04

### Log capture

```shell
"PHP message: PHP Warning:  Undefined array key 1 in /usr/local/hestia/web/inc/prevent_csrf.php on line 59"
```

**Comment by jlguerrerosanz** [comment]
`Side question: For future reference, if I want to reinstall Hestia but keep my database the same how would I go about doing that?`
HestiaCP doesn't keep the users / domains data in a database. It reads the files and folders of the OS and shows you the information.

The database can be backuped or dumped into a file.

The backup system should do the hard work for you.

**Comment by jaapmarcus** [comment]
"PHP message: PHP Warning: Undefined array key 1 in /usr/local/hestia/web/inc/prevent_csrf.php on line 59"

https://github.com/hestiacp/hestiacp/blob/58fce01faf166c6b115e9d454b59a84536725915/web/inc/prevent_csrf.php#L58-L60

How looks $_SERVER['HOST'] when you add var_dump($_SERVER['HOST']); die(); to that file?

**Comment by Surgical71** [comment]
> $hostname = explode(':', $_SERVER['HTTP_HOST']);

Do you want me to change it to  $hostname = explode($_SERVER['HOST']); die(); ?

What will this do?

**Comment by Surgical71** [comment]
> `Side question: For future reference, if I want to reinstall Hestia but keep my database the same how would I go about doing that?` HestiaCP doesn't keep the users / domains data in a database. It reads the files and folders of the OS and shows you the information.
> 
> The database can be backuped or dumped into a file.
> 
> The backup system should do the hard work for you.

I see okay. So what is the best way to just do a reinstall then keeping all data intact?

**Comment by jlguerrerosanz** [comment]
Since reinstalls are not supported:
- Backup first and take files with you.
- Reinstall OS
- Install Hestiacp
- Restore backup

**Comment by jaapmarcus** [comment]
> > $hostname = explode(':', $_SERVER['HTTP_HOST']);
> 
> Do you want me to change it to $hostname = explode($_SERVER['HOST']); die(); ?
> 
> What will this do?

Nothing but I found allready the bug 
if you visit the website with a custom template that forwards port 443 or 80 to 8083 port is set to "empty" Will com with a patch soon

**Comment by Surgical71** [comment]
> > > $hostname = explode(':', $_SERVER['HTTP_HOST']);
> > 
> > 
> > Do you want me to change it to $hostname = explode($_SERVER['HOST']); die(); ?
> > What will this do?
> 
> Nothing but I found already the bug if you visit the website with a custom template that forwards port 443 or 80 to 8083 port is set to "empty" Will com with a patch soon

I see great thanx. SO I am correct in changing it to exactly as below?
Do you want me to change it to $hostname = explode($_SERVER['HOST']); die(); ?

**Comment by jaapmarcus** [comment]
No:
Apply the following Changes:
<img width="1735" alt="Screenshot 2022-08-22 at 13 05 43" src="https://user-images.githubusercontent.com/9754650/185906746-8b9bcf6b-a58d-4374-a86d-cb04d21104a5.png">

**Comment by jaapmarcus** [comment]
So it will looks like:

```
list($hostname, $port) = explode(':', $_SERVER["HTTP_HOST"].":");
                if(empty($port)){
                    $port = 443;
                }
```

**Comment by Surgical71** [comment]
> So it will looks like:
> 
> ```
> list($hostname, $port) = explode(':', $_SERVER["HTTP_HOST"].":");
>                 if(empty($port)){
>                     $port = 443;
>                 }
> ```

Did not resolve the issue. I did reboot the server

![image](https://user-images.githubusercontent.com/80483431/185909149-36e12c58-3dce-4006-bea9-39d5056f6b4b.png)

**Comment by jaapmarcus** [comment]
What says the error log in /var/log/hestia/nginx-error.log

**Comment by Surgical71** [comment]
> /var/log/hestia/nginx-error.log

![image](https://user-images.githubusercontent.com/80483431/185909869-3821a45b-6133-4dfc-8c8c-fbaa00e32a3d.png)

**Comment by Surgical71** [comment]
![image](https://user-images.githubusercontent.com/80483431/185911662-e874094a-a051-446e-b485-1addf2b8333f.png)

**Comment by jaapmarcus** [comment]
It is also used in:
https://github.com/hestiacp/hestiacp/blob/0220e083efadaf37f5258bd32948fbab5118ba19/web/add/db/index.php#L89

How do you access the panel?

**Comment by Surgical71** [comment]
> It is also used in:
> 
> https://github.com/hestiacp/hestiacp/blob/0220e083efadaf37f5258bd32948fbab5118ba19/web/add/db/index.php#L89
> 
> How do you access the panel?

Domain connects to Cloudflare then to NGINX Proxy Manager then to the port 2083. I get the login screen and once i type in my password it gives me error 500

**Comment by jaapmarcus** [comment]
I wonder if due to this HTTP_HOST is missing or not...

Try this?
```
<?php

    $check_csrf = true;

    if ($_SERVER['SCRIPT_FILENAME'] == '/usr/local/hestia/web/inc/mail-wrapper.php' || $_SERVER['SCRIPT_FILENAME'] == '/usr/local/hestia//web/inc/mail-wrapper.php') {
        $check_csrf=false;
    } // execute only from CLI
    if ($_SERVER['SCRIPT_FILENAME'] == '/usr/local/hestia/web/reset/mail/index.php' || $_SERVER['SCRIPT_FILENAME'] == '/usr/local/hestia/web//reset/mail/index.php') {
        $check_csrf=false;
    } // Localhost only
    if ($_SERVER['SCRIPT_FILENAME'] == '/usr/local/hestia/web/api/index.php' || $_SERVER['SCRIPT_FILENAME'] == '/usr/local/hestia/web//api/index.php') {
        $check_csrf=false;
    } // Own check
    if (substr($_SERVER['SCRIPT_FILENAME'], 0, 22)=='/usr/local/hestia/bin/') {
        $check_csrf=false;
    }

    function checkStrictness($level)
    {
        if ($level >= $_SESSION['POLICY_CSRF_STRICTNESS']) {
            return true;
        } else {
            http_response_code(400);
            echo "<h1>Potential use CSRF detected</h1>\n".
            "<p>Please disable any plugins/add-ons inside your browser or contact your system administrator. If you are the system administrator you can run v-change-sys-config-value 'POLICY_CSRF_STRICTNESS' '0' as root to disable this check.<p>".
            "<p>If you followed a bookmark or an static link <a href='/'>please click here</a>";
            die();
        }
    }

    function prevent_post_csrf()
    {
        if (!empty($_SERVER['REQUEST_METHOD'])) {
            if ($_SERVER['REQUEST_METHOD']==='POST') {
                if(!empty($_SERVER["HTTP_HOST"])){
                    list($hostname, $port) = explode(':', $_SERVER["HTTP_HOST"].":");
                    if(empty($port)){
                        $port = 443;
                    }
                }else{
                    $hostname = gethostname();
                    $port = 443;
                }
                if (isset($_SERVER['HTTP_ORIGIN'])) {
                    $origin_host = parse_url($_SERVER['HTTP_ORIGIN'], PHP_URL_HOST);
                    if (strcmp($origin_host, gethostname()) === 0 && in_array($port, array('443',$_SERVER['SERVER_PORT']))) {
                        return checkStrictness(2);
                    } else {
                        if (strcmp($origin_host, $hostname) === 0 && in_array($port, array('443',$_SERVER['SERVER_PORT']))) {
                            return checkStrictness(1);
                        } else {
                            return checkStrictness(0);
                        }
                    }
                }
            }
        }
    }

    function prevent_get_csrf()
    {
        if (!empty($_SERVER['REQUEST_METHOD'])) {
            if ($_SERVER['REQUEST_METHOD']==='GET') {
                if(!empty($_SERVER["HTTP_HOST"])){
                    list($hostname, $port) = explode(':', $_SERVER["HTTP_HOST"].":");
                    if(empty($port)){
                        $port = 443;
                    }
                }else{
                    $hostname = gethostname();
                    $port = 443;
                }
                
                //list of possible entries route and these should never be blocked
                if (in_array($_SERVER['DOCUMENT_URI'], array('/list/user/index.php', '/login/index.php','/list/web/index.php','/list/dns/index.php','/list/mail/index.php','/list/db/index.php','/list/cron/index.php','/list/backup/index.php','/reset/index.php'))) {
                    return true;
                }
                if (isset($_SERVER['HTTP_REFERER'])) {
                    $referrer_host = parse_url($_SERVER['HTTP_REFERER'], PHP_URL_HOST);
                    if (strcmp($referrer_host, gethostname()) === 0 && in_array($port, array('443',$_SERVER['SERVER_PORT']))) {
                        return checkStrictness(2);
                    } else {
                        if (strcmp($referrer_host, $hostname) === 0 && in_array($port, array('443',$_SERVER['SERVER_PORT']))) {
                            return checkStrictness(1);
                        } else {
                            return checkStrictness(0);
                        }
                    }
                } else {
                    return checkStrictness(0);
                }
            }
        }
    }

    if ($check_csrf == true) {
        prevent_post_csrf();
        prevent_get_csrf();
    }

```

**Comment by Surgical71** [comment]
Some progress:

2022/08/22 15:22:37 [error] 1336#0: *21 FastCGI sent in stderr: "PHP message: PHP Warning:  fopen(/tmp/tmp.JbcOrJ3YyI): Failed to open stream: Permission denied in /usr/local/hestia/web/login/index.php on line 147PHP message: PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /usr/local/hestia/web/login/index.php:148
#0 /usr/local/hestia/web/login/index.php(148): fwrite()
#1 /usr/local/hestia/web/login/index.php(306): authenticate_user()
#2 {main}
thrown in /usr/local/hestia/web/login/index.php on line 148" while reading response header from upstream, client: X.X.X.X, server: _, request: "POST /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "domain.org", referrer: "https://domain.org/login/"

**Comment by jaapmarcus** [comment]
Wrong write permissions of the tmp folder

**Comment by Surgical71** [comment]
what does the perms need to be? I used 777 and 755 with no luck

**Comment by jaapmarcus** [comment]
Default permissions should be enough or even 777.

Are you running hestia with Docker by accident

**Comment by Surgical71** [comment]
> 

No But I think my main issue is for some reason I messed up my entire server's perms. So will go Nuclear and reinstall os and everything else. Thank you for your help thus far. WIll update once I confirmed issue was resolved after reinstall of os. Any advice to backup my hestia or do I need to backup each wordpress website with a plugin?

**Comment by jaapmarcus** [comment]
v-backup-user user or v-backup-users

**Comment by Surgical71** [comment]
Okay, Issue resolved. I did a fresh install while also including your code above and it works. Thanx Jaap

**Comment by jaapmarcus** [comment]
We will wait with closing be after we have patched the main branch...
