### ISSUE TITLE
[Feature] SoGo Webmail / Calendar Integration

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#2867]
### Describe the feature or change in detail

SoGo provides a full groupware solution when compared to webmail clients Rainloop or Roundcube.

The biggest problem is more and more calendar invites are being sent via email now and the ability to easily accept or add them is just not there for Rainloop and Roundcube.

SoGo has an integrated calendar solutions which can also be shared amongst users.

I think this will be very important to implement for the opensource community. There is a vendor lock in with Microsoft 365 and Google Workspaces which already has calendar features.

https://www.sogo.nu/

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Production builds are behind a payment and I don't think we want to include nightly builds

**Comment by johnnyq** [comment]
Its a shame as it seems like a great solution but I agree it may not be a good idea to implement if their production builds are behind a paywall.
