### ISSUE TITLE
[Bug] Missing logrotate config file for Roundcube logs

### ISSUE THREAD

**Issue by estratos** [hestiacp/hestiacp#2868]
### Describe the bug

Logs in /var/log/roundcube/*.log   growing big in size

No config File  /etc/logrotate.d/roundcube

### Tell us how to replicate the bug

Search for logrotate config file for roundcube but there is none in /etc/logrotate.d/

### Which components are affected by this bug?

Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.6.6

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
See attached PR
