### ISSUE TITLE
[Bug] ubuntu 22.04 LTS not supported 

### ISSUE THREAD

**Issue by radwanhallak** [hestiacp/hestiacp#2881]
### Describe the bug

after I upgrade my ubuntu server from 20.04 to 22.04 LTS, i have tried to install Hestia cp but the installer gives me this message 

![1](https://user-images.githubusercontent.com/7591337/187110562-50c4ac3f-73f6-4c82-9869-cccf2c2ca02a.jpg)

I used -f because I already have an admin user 

### Tell us how to replicate the bug

1. open ssh
2. bash hst-install.sh -f

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.6.7

### Operating system

ubuntu 22.04

**Comment by ScIT-Raphael** [comment]
You're using an old installer, also there should be non need to reinstall hestia after an upgrade. Have a look at the upgrade section in our docs and check the forum using the search function to get more informations about pending parts after os upgrade.
