### ISSUE TITLE
[Bug] Getting error with inbound mails

### ISSUE THREAD

**Issue by dpushkar24** [hestiacp/hestiacp#2900]
### Describe the bug

Hi Team,

I am able to successfully send (outbound) mails by using sendinblue SMTP relay. But I am facing some issue in inbound mail for getting mails. 
I tried to check my MX records in cloudflare bit everything looks fine. 

Of course in my case, for security purpose my post 25 is blocked. I think I am close to the solution but need your valuable suggestion.

I thank you and your team for the efforts you are taking for providing this tool and support for it.

Thanks and Regards,
Pushkar Deshpande.

### Tell us how to replicate the bug

Following is the error which I am facing;

(From Gmail)
The response was:
DNS Error: DNS type 'mx' lookup of [dpushkar24.tk](http://dpushkar24.tk/) responded with code NOERROR DNS type 'aaaa' lookup of [mail.dpushkr24.tk](http://mail.dpushkr24.tk/). responded with code NXDOMAIN DNS type 'a' lookup of [mail.dpushkr24.tk](http://mail.dpushkr24.tk/). responded with code NXDOMAIN

(From Delta)
The original message was received at Thu, 1 Sep 2022 08:05:50 -0400 from m0163029.ppops.net [127.0.0.1]

   ----- The following addresses had permanent fatal errors ----- <[administrator@dpushkar24.tk](mailto:administrator@dpushkar24.tk)>

   ----- Transcript of session follows -----
550 5.1.2 <[administrator@dpushkar24.tk](mailto:administrator@dpushkar24.tk)>... Host unknown (Name server: mail.dpushkr24.tk.: host not found)

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.7

### Operating system

Ubuntu 22.04 (aarch64)

**Comment by jaapmarcus** [comment]
Disable Cloudflare proxy for mail.domain.com. It is not a Hestia problem it self

**Comment by jaapmarcus** [comment]
Also
jaapmarcus@Jaaps-MacBook-Pro ~ % ping mail.dpushkr24.tk 
ping: cannot resolve mail.dpushkr24.tk: Unknown host
jaapmarcus@Jaaps-MacBook-Pro ~ % ping dpushkr24.tk 
ping: cannot resolve dpushkr24.tk: Unknown host

**Comment by dpushkar24** [comment]
Hi,

Thanks for quick reply.
I have never used proxy for it in Cloudflare and using purely 'only DNS'.

Any more suggestion if possible?

Regards,
Pushkar Deshpande

**Comment by dpushkar24** [comment]
C:\Users\2067419>ping mail.dpushkar24.tk

Pinging mail.dpushkar24.tk [152.67.5.63] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 152.67.5.63:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

C:\Users\2067419>telnet mail.dpushkar24.tk:2525
'telnet' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\2067419>ping dpushkar24.tk

Pinging dpushkar24.tk [104.21.3.35] with 32 bytes of data:
Reply from 104.21.3.35: bytes=32 time=36ms TTL=51
Reply from 104.21.3.35: bytes=32 time=32ms TTL=51
Reply from 104.21.3.35: bytes=32 time=32ms TTL=51
Reply from 104.21.3.35: bytes=32 time=33ms TTL=51

Ping statistics for 104.21.3.35:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 32ms, Maximum = 36ms, Average = 33ms

**Comment by ScIT-Raphael** [comment]
We do not provide any support requests over github, please use forum or discord and be aware of https://forum.hestiacp.com/t/please-read-this-before-you-start/383
