### ISSUE TITLE
[Bug] exim ratelimit file per domain doesn't update when deleting mail account

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2903]
### Describe the bug

I deleted an email account. I can still see the old account in:
#cat /etc/exim4/domains/domain.tld/limits
account1@domain.tld:200
account2@domain.tld:200
deletedaccount@domain.tld:450
account4@domain.tld:450

### Tell us how to replicate the bug

Create an email account
Delete that account
Check the limit file

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

Latest

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
See attached PR
