### ISSUE TITLE
During the installation I received this message

### ISSUE THREAD

**Issue by AsafS1** [hestiacp/hestiacp#2908]
### Describe the bug

  Unable to launch a new process.
ERROR: File Manager installation failed!
**### Please report this to our development team**: https://github.com/hestiacp/hestiacp/issues
![install error ](https://user-images.githubusercontent.com/42066315/188506716-03023a90-e176-461c-87a9-1b0bc96e6aad.jpg)

### Tell us how to replicate the bug

1) Reinstall Operating System => Ubuntu 18.04.6 LTS
2) following  apt-get update  &  apt-get dist-upgrade
3)  wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
4) sudo bash hst-install.sh --apache yes --phpfpm yes --multiphp no --vsftpd yes --proftpd no --named yes --mysql yes --postgresql no --exim yes --dovecot yes --sieve no --clamav yes --spamassassin yes --iptables yes --fail2ban yes --quota yes --api yes --interactive yes --with-debs no  --port '8083' --hostname '99.999.99.99.xxxx.com' --email 'some-mail@gmail.com' --password 'xx9999999Hostinger#' --lang 'en' --force

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.6.7

### Operating system

Ubuntu 18.04.6 LTS

### Log capture

```shell
In Process.php line 355:

  Unable to launch a new process.


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

ERROR: File Manager installation failed!
Please report this to our development team:
https://github.com/hestiacp/hestiacp/issues
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
[ * ] Configuring PHPMailer...
[ * ] Configuring System IP...
Installing required kernel modules for quota support...
```

**Comment by jaapmarcus** [comment]
This is an error with composer. I don't think that we can do any thing about it.  It looks like an issue with the server it self. 

Run: 

`v-add-sys-filemanager` 

And it will install the filemanger again. 

You also might want to consider upgrading to a newer version of Ubuntu as 18.04 will go EOL in about 8 months.

**Comment by AsafS1** [comment]
Hi Jaap Marcu.
Thanks a lot for the quick reply.
Regarding version 18.04, you are right, but in my hosting (hostinger) this
is what I saw that can be installed.
But I'll check it out.....
Regarding a solution, Ubuntu 18.04 + Hestiacp can be installed in one
package.
And that's what I did. Indeed the problem was solved.
The reason I sent this issue is The line
* :*
*Please report this to our development team*
and again
Thank you

Asaf

‫בתאריך יום ב׳, 5 בספט׳ 2022 ב-23:17 מאת ‪Jaap Marcus‬‏ <‪
***@***.***‬‏>:‬

**Comment by jaapmarcus** [comment]
18.04 is still supported but goes EOL in about 8 months (End of April 2023)

I have done a lot of server installs and even on google not a lot of "reports" happen. It might be an server performance issue

Depending on your hardware you might not install ClamAV and anti spam..

**Comment by AsafS1** [comment]
Thanks again .
As I wrote, I reinstalled again, this time as an installation package
Ubuntu + Hestia, and the problem did not repeat itself.
Asaf

‫בתאריך יום ב׳, 5 בספט׳ 2022 ב-23:40 מאת ‪Jaap Marcus‬‏ <‪
***@***.***‬‏>:‬
