### ISSUE TITLE
editing didn't saved on file manager only appears on this latest update [Bug] 

### ISSUE THREAD

**Issue by AladdinShazly** [hestiacp/hestiacp#2910]
### Describe the bug

when I go to edit files on file manager it doesn't save, only appears on this latest update

### Tell us how to replicate the bug

1. go to file manager to edit the file
2. file editing updated successfully
3. after checking the file the last edit disapear
4. must go via FTP to edit or download file and edit locally and reupload

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.7

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Filemanger is developed by https://github.com/filegator/filegator

So we don't have really any control with it.  Also on my local server. Please provide /var/log/hesita/nginx-error.log  when you try to save.

**Comment by AladdinShazly** [comment]
2022/09/04 14:38:20 [error] 1257#0: *291 open() "/usr/local/hestia/web/.git/HEAD" failed (2: No such file or directory), client: 109.74.204.123, server: _, request: "GET /.git/HEAD HTTP/1.1", host: "93.ip-164-132-49.eu:8083"
2022/09/04 14:38:21 [error] 1257#0: *293 open() "/usr/local/hestia/web/Ys8X" failed (2: No such file or directory), client: 109.74.204.123, server: _, request: "GET /Ys8X HTTP/1.1", host: "93.ip-164-132-49.eu:8083"
2022/09/04 14:38:21 [error] 1257#0: *295 open() "/usr/local/hestia/web/Portal/Portal.mwsl" failed (2: No such file or directory), client: 109.74.204.123, server: _, request: "GET /Portal/Portal.mwsl HTTP/1.1", host: "93.ip-164-132-49.eu:8083"
2022/09/06 06:28:05 [error] 1257#0: *432 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key 1 in /usr/local/hestia/web/inc/prevent_csrf.php on line 59" while reading response header from upstream, client: 71.6.167.142, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "164.132.49.93"
2022/09/06 06:28:09 [crit] 1257#0: *444 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: 71.6.167.142, server: 0.0.0.0:8083
2022/09/06 07:25:50 [error] 1257#0: *612 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_nginx_cache_duration" in /usr/local/hestia/web/edit/web/index.php on line 255" while reading response header from upstream, client: 197.32.63.58, server: _, request: "POST /edit/web/?domain=star-egy.com&token=66906aa404079cf3bcc176e934f95e25 HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "panel2.star-egy.com:8083", referrer: "https://panel2.star-egy.com:8083/edit/web/?domain=star-egy.com&token=66906aa404079cf3bcc176e934f95e25"
2022/09/06 08:30:15 [error] 1257#0: *648 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_nginx_cache_duration" in /usr/local/hestia/web/edit/web/index.php on line 255" while reading response header from upstream, client: 197.32.63.58, server: _, request: "POST /edit/web/?domain=star-egy.com HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "panel2.star-egy.com:8083", referrer: "https://panel2.star-egy.com:8083/edit/web/?domain=star-egy.com"

**Comment by jaapmarcus** [comment]
Both errors have nothing to do with the filemanger.

**Comment by AladdinShazly** [comment]
> Both errors have nothing to do with the filemanger.

thank you for your time, I appreciate that.
how can i role back to v1.66

**Comment by jaapmarcus** [comment]
Will not help as it is an issue with the filemanger.  That is downloaded separately.

**Comment by jaapmarcus** [comment]
Also we didn't touch the file manager in the last release:

https://github.com/hestiacp/hestiacp/blob/main/CHANGELOG.md#167---service-release
