### ISSUE TITLE
[Bug] v-change-web-domain-name doesn't clean up old domain completely

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#2914]
### Describe the bug

In the following lines of code, `prepare_backend` is not called, hence `$backend_proxy` is empty and the conf file for older domain still exist at the php-fpm pool folder. 

```
# Delete backend
if [ -n "$BACKEND" ]; then
    delete_web_backend
fi
```

### Tell us how to replicate the bug

After executing this command, run `v-delete-user` which will delete all the files related to the "new" domain, leaving the old config behind. At this point, restart of php-fpm fails. 

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
fixed

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/2915
