### ISSUE TITLE
[Bug] Empty MariaDB edit fields

### ISSUE THREAD

**Issue by dfag86** [hestiacp/hestiacp#2916]
### Describe the bug

When I go to the mariadb / edit / server / mariadb / settings in the / list / server / settings and edit the basic values, they do not save. Still fields are empty.
Image: https://freeimage.host/i/PJg5Gt
### Tell us how to replicate the bug

I clicked: /edit/server/mariadb/
I'm editing core values,
I save and everything disappears.

### Which components are affected by this bug?

Control Panel Web Interface, Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.6.8

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Known issue:
https://github.com/hestiacp/hestiacp/issues/2672
