### ISSUE TITLE
[Bug] iOS mail untrusted certificates error

### ISSUE THREAD

**Issue by darkworks** [hestiacp/hestiacp#2918]
### Describe the bug

the iphone ios mail app give error that mail.example.com certificates are untrusted. i googled the issue and people resolved it by using fullchain.pem on the domain. so i request that pls check the issue and if possible use letsencrupt fullchain.pem 

thanks

### Tell us how to replicate the bug

1) create mail account in hestia panel
2) add this mail account ios mail settings
3) it will give error that mail.example.com certificates are untrusted

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.6.7

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Enable SSL for the mail domain and it should work as expected
