### ISSUE TITLE
SSL problem when trying to get the updated install script

### ISSUE THREAD

**Issue by hanzicode** [hestiacp/hestiacp#292]
### Brief issue description:
When I login as root to server and issue this wget command:
wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install.sh

I get this error message...

--2019-05-08 07:45:20--  https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
ERROR: The certificate of 'raw.githubusercontent.com' is not trusted.
ERROR: The certificate of 'raw.githubusercontent.com' hasn't got a known issuer.

Because of this, I cannot install Hestia

**Comment by hanzicode** [comment]
Yes, it is working now. Debian 9 is the OS.

**Comment by ghost** [comment]
@hanzicode glad to hear it's up and running! I'll go ahead and close this issue report, if you have any other questions or run into trouble feel free to let us know. Have a great day!

**Comment by hanzicode** [comment]
OK, I am testing Hestia develop branch on a non-productive server and that same problem happen again.

Having more experience with problem with GitHub, I have simply download the zip file and plan to unzip the hst-install.sh file. Then I find a file called hst-migration.sh - what does it do? Migration of users from one server to another or migration from Vesta to Hestia? Just curious as I am also preparing a tutorial of switching from Vesta to Hestia.
