### ISSUE TITLE
[Bug] German installation of Wordpress dont work.

### ISSUE THREAD

**Issue by funsurfer2008** [hestiacp/hestiacp#2926]
### Describe the bug

install wordpress with new databaes dont work at all.
the bug here https://github.com/hestiacp/hestiacp/pull/2818 is not fixed for german installs.

the config file is empty.

brgds

### Tell us how to replicate the bug

1. install Wordpress
2. choose German language
3. start
4. config file is empty so no wordpress installation is there

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.6.x

### Operating system

Debian 10.5

**Comment by jaapmarcus** [comment]
Please check what version you are using.  I have no issue with the current version of Hestia. 

<img width="1272" alt="Screenshot 2022-09-18 at 12 55 44" src="https://user-images.githubusercontent.com/9754650/190898594-ebc454fa-ea20-4fee-842c-468b9aadc000.png">

**Comment by jaapmarcus** [comment]
Issue has been solved in the main branch but not yet in the release branch.

That why it is not working you on the release branch

**Comment by funsurfer2008** [comment]
Thanks!

**Comment by jaapmarcus** [comment]
Will be released when we release 1.6.9 planned this week

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/tree/staging/1.6.9
