### ISSUE TITLE
[Bug] Control Panel not starting after update

### ISSUE THREAD

**Issue by Surgical71** [hestiacp/hestiacp#2927]
### Describe the bug

After the recent update the control panel does not start up

### Tell us how to replicate the bug

Update Hestia

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 20.04

### Log capture

```shell
No logs in error.log

is there any way of checking Hestia's status to troubleshoot and gather more information?
```

**Comment by ScIT-Raphael** [comment]
basic steps, systemctl status hestia probaly. Please use forum or discord for support requests, there are no known issues.
