### ISSUE TITLE
[Bug] Missing a valid address in From:

### ISSUE THREAD

**Issue by PotatoRui** [hestiacp/hestiacp#2929]
### Describe the bug

When I Add a new user, with a checked checkbox “Send welcome email”. 
It returns an error on my "/var/log/exim4/mainlog"

` admin <admin@domain.com> R=localuser T=local_delivery`
`SMTP error from remote mail server after pipelined end of data: 550-5.7.1 [2001:000xxxxxxxxx] Messages missing a valid address in From:\n550 5.7.1 header, or having no From: header, are not accepted. l8-20020a170902f68800b00170f6f728d4si30765320plg.543 - gsmtp`

I can telnet smtp.gmail.com 25
I can send emails with new created email account
I can receive emails

Screenshot Below
![image](https://user-images.githubusercontent.com/49616497/190919821-ed779c35-6b48-4e00-bd64-88bcd3df9e2f.png)

### Tell us how to replicate the bug

1. Login as Administrator
2. Click on add new user
3. Check the "send welcome email"
4.  Message sent successfully but returns an error that there is a missing "FROM" on the email
Image Below
![image](https://user-images.githubusercontent.com/49616497/190919954-36b6dd94-820f-446c-b1c1-a5148e304d01.png)

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface, Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 22.04.1 LTS x86_64

### Log capture

```shell
2022-09-18 16:56:27 1oZxal-0007Gb-BO <= <> R=1oZxaj-0007Fg-Ad U=Debian-exim P=local S=3196
2022-09-18 16:56:27 1oZxaj-0007Fg-Ad Completed
2022-09-18 16:56:27 1oZxal-0007Gb-BO => admin <admin@domain.com> R=localuser T=local_delivery
2022-09-18 16:56:27 1oZxal-0007Gb-BO Completed
2022-09-18 17:04:15 1oZxiJ-000AaZ-Iq <= admin@domain.com U=admin P=local S=1309 id=vRcMGC4omDgnQoc1InldGQSxsRUflvK1AueFuX96hs@localhost.localdomain
2022-09-18 17:04:17 1oZxiJ-000AaZ-Iq H=gmail-smtp-in.l.google.com [2404:6800:4003:c00::1b] TLS error on connection (recv): The TLS connection was non-properly terminated.
2022-09-18 17:04:17 1oZxiJ-000AaZ-Iq H=gmail-smtp-in.l.google.com [2404:6800:4003:c00::1b] TLS error on connection (recv): The specified session has been invalidated for some reason.
2022-09-18 17:04:17 1oZxiJ-000AaZ-Iq ** gmailuser@gmail.com R=dnslookup T=remote_smtp H=gmail-smtp-in.l.google.com [2404:6800:4003:c00::1b] X=TLS1.3:ECDHE_X25519__ECDSA_SECP256R1_SHA256__AES_256_GCM:256 CV=yes: SMTP error from remote mail server after pipelined end of data: 550-5.7.1 [2000:xxxx:xxx::xx] Messages missing a valid address in From:\n550 5.7.1 header, or having no From: header, are not accepted. l8-20020a170902f68800b00170f6f728d4si30765320plg.543 - gsmtp
2022-09-18 17:04:17 1oZxiL-000AbU-MM <= <> R=1oZxiJ-000AaZ-Iq U=Debian-exim P=local S=3199
2022-09-18 17:04:17 1oZxiJ-000AaZ-Iq Completed
2022-09-18 17:04:17 1oZxiL-000AbU-MM => admin <admin@domain.com> R=localuser T=local_delivery
2022-09-18 17:04:17 1oZxiL-000AbU-MM Completed
Messages missing a valid address in From:\n550 5.7.1 header, or having no From: header, are not accepted.  SMTP error from remote mail server after pipelined end of data: 550-5.7.1 [2000:xxxx:xxxx:xxx:xx] Messages missing a valid address in From:\n550 5.7.1 header, or having no From: header, are not accepted. l8-20020a170902f68800b00170f6f728d4si30765320plg.543 - gsmtp^C
```

**Comment by jaapmarcus** [comment]
Following code is used to generate the hostname:

https://github.com/hestiacp/hestiacp/blob/0220e083efadaf37f5258bd32948fbab5118ba19/web/inc/helpers.php#L137-L152

**Comment by jaapmarcus** [comment]
Also please provide full mail headers. It makes debugging a lot easier

**Comment by PotatoRui** [comment]
@jaapmarcus 

**RETURNED MAIL HEADERS**

Return-path: <>

Envelope-to: admin@domain.com
Delivery-date: Sun, 18 Sep 2022 17:04:17 +0000
Received: from Debian-exim by domain.com with local (Exim 4.95)
    id 1oZxiL-000AbU-MM
    for admin@otakunity.com;
    Sun, 18 Sep 2022 17:04:17 +0000
X-Failed-Recipients: gmailuser@gmail.com
Auto-Submitted: auto-replied
From: Mail Delivery System <Mailer-Daemon@domain.com>
To: admin@otakunity.com
References: <vRcMGC4omDgnQoc1InldGQSxsRUflvK1AueFuX96hs@localhost.localdomain>
Content-Type: multipart/report; report-type=delivery-status; boundary=1663520657-eximdsn-558328014
MIME-Version: 1.0
Subject: Mail delivery failed: returning message to sender
Message-Id: <E1oZxiL-000AbU-MM@domain.com>
Date: Sun, 18 Sep 2022 17:04:17 +0000

**Comment by PotatoRui** [comment]
@jaapmarcus 

**SENT EMAIL WITH "SEND WELCOME MESSAGE OPT"**

Return-path: <admin@domain.com>
Received: from admin by domain.com with local (Exim 4.95)
    (envelope-from <admin@domain.com>)
    id 1oaBwS-000dUd-Eh
    for gmailuser@gmail.com;
    Mon, 19 Sep 2022 08:15:48 +0000
To: gmailuser@gmail.com
Subject: Welcome to Hestia Control Panel
Date: Mon, 19 Sep 2022 08:15:48 +0000
From:
Message-ID: <c0AT3joC0KY8nOuyiH8XT4iKcwbqnBTRpkDfBhY6XZw@localhost.localdomain>
X-Mailer: PHPMailer 6.6.3 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
    boundary="b1_c0AT3joC0KY8nOuyiH8XT4iKcwbqnBTRpkDfBhY6XZw"
Content-Transfer-Encoding: 8bit

**Comment by tlcd96** [comment]
I've reviewed the code from 1.6.7 to 1.6.8, the only change was the new function `get_hostname()` and new version of `PHPMailer` if i'm not mistaken. 
the new function `get_hostname()` exists to replace legacy code, unfortunately i cannot make a test account since i'm not at home. nor can i connect to [IP]:8083, since the place i'm in blocks that port. 
maybe there is some error on `PHPMailer` or different syntax in `PHPMailer`? the from name and from address should be ok, since part of the legacy code is on the function `get_hostname()` .

**Comment by jaapmarcus** [comment]
Yes it looks like there are some issues with it if the hostname is not set propperly

**Comment by PotatoRui** [comment]
@jaapmarcus @tlcd96  the hostname was set properly and it should return an error or hint that it was being called ?

**Comment by PotatoRui** [comment]
are there any options to set the default mail for the hestiacp? like support@domain.com?

**Comment by tlcd96** [comment]
checking

**Comment by tlcd96** [comment]
@PotatoRui you have on: [ip]:8083/edit/server/ the hostname option, under tab basic options.
![image](https://user-images.githubusercontent.com/7103685/191822670-0ffa9e8e-dabb-4efc-8471-8e026dd6f008.png)
the create user option in the latest release, it's working @jaapmarcus, just checked on my vm01 (oldest)

**Comment by tlcd96** [comment]
localtime now: 18:22

**Comment by tlcd96** [comment]
i'll show now the option described above, 1 sec.

**Comment by tlcd96** [comment]
![image](https://user-images.githubusercontent.com/7103685/191823192-39ed34df-8bb0-481c-9447-5ad4006e01db.png)
@PotatoRui check if the hostname is there as shown in the picture above plz.

**Comment by PotatoRui** [comment]
@tlcd96 I tried editing the hostname and it works but it uses my subdomain 
panel.domain.com <- I would like to use my non subdomain which is the domain.com? is there any remedies for it?

**Comment by tlcd96** [comment]
@PotatoRui dunno, maybe when @jaapmarcus reply's he can explain why hestiacp must be in a subdomain or if you can use the domain name only (domain.tld) as the domain for hestiacp.

**Comment by PotatoRui** [comment]
i tried accessing the panel via the main domain and changed the hostname to domain.tld . still cannot get the hostname @tlcd96

**Comment by istiak101** [comment]
This will not be a valid FQDN. You can definitely patch the part of code @jaapmarcus given to send mail from your desired address but keep in mind this might lead to some mail providers rejecting the mail depending on your configuration. And after every update you will lose the patch.

https://kb.iu.edu/d/aiuv

**Comment by PotatoRui** [comment]
@istiak101 thank you, i think im going to use my fqdn which is mail.domain.tld

**Comment by jaapmarcus** [comment]
We need to add some checks so it doesn't happen

**Comment by ErminMerdanovic** [comment]
Having the same issue here. I am currently using an external mail server for the internal emails, the internal emails are being  also sent without a sender header. I used the [configure-server-smtp.sh] script for the setup.

And for some reason cron jobs messages are sent with the email [root@hcp.domain.net] instead of the externally set email [noreply@domain.net]. (My external mail server therefore refuses to send these emails).

<img src="https://user-images.githubusercontent.com/31346820/192732068-5732e366-5621-4685-b910-2646c67daf4e.png" width="400" height="700" />

**Comment by jaapmarcus** [comment]
In hestia.conf there is a value called: SERVER_SMTP_ADDR='' set it as the sender of your email adress and it should work properly. 

https://github.com/hestiacp/hestiacp/blob/44e3131312ed21f3e6a3132fb8e93f11ff07e0a1/web/inc/main.php#L407

**Comment by kfrankiewicz** [comment]
Hi guys. I don't think it has been solved. I'll show you the example I have. This is the fundamental problem in `get_hostname()` function.

![Bez nazwy](https://github.com/hestiacp/hestiacp/assets/24274081/5e5d218c-ddb9-450c-a002-ec5527436483)

Let's analyse this function. Let's take AWS as the example.
1. Firstly it takes the real local hostname. Let's say it's `$ret = "host1.mydomain.com"`.
2. Later it does gethostbyname, so it resolves the host to the IP: `$ret2 = "18.170.134.10"`.
3. At the end it does gethostbyaddr, so `$ret3 = "ec2-18-170-134-10.eu-west-2.compute.amazonaws.com"`.
4. The function returns `$ret3 = "ec2-18-170-134-10.eu-west-2.compute.amazonaws.com"` as the host. Obviously I don't control the DNS entries for this domain, so I can't set SPF nor DKIM records. So the emails from `noreply@ec2-18-170-134-10.eu-west-2.compute.amazonaws.com` are rejected by major email services, e.g. Gmail.

As the effect, get_hostname() USUALLY returns the wrong host. I think that the get_hostname() function should return `$ret`, which is `host1.mydomain.com` in the situation above. Do you agree? If so, I can do PR. Just I don't really understand the logic behind further `gethostbyname()` and `gethostbyaddr()`. Should they be just removed?

(The example above is the real example I've just had, tested and debugged with exactly the same values)

**Comment by istiak101** [comment]
You should have authority over that IP/domain space. Otherwise this would be plain spoofing.

**Comment by kfrankiewicz** [comment]
No, it won't land in the spam if it uses the domain from my hostname, which is `host1.mydomain.com`. I control that domain and I can set any DNS records I want - including SPF, DKIM and DMARC.

`You should have authority over that IP/domain space.`

Should I contact AWS to let me control their DNS to modify the SPF record for `ec2-18-170-134-10.eu-west-2.compute.amazonaws.com`? They won't let me :)

**Comment by istiak101** [comment]
That's not SPF, that's SOA.

If you can't set the SOA record for reverse DNS your mail will go to spam/rejected. That's how emails work.

**Comment by istiak101** [comment]
That's not SPF, that's PTR.

If you can't set the PTR record for reverse DNS your mail will go to spam/rejected. That's how emails work.

**Comment by jaapmarcus** [comment]
> No, it won't land in the spam if it uses the domain from my hostname, which is `host1.mydomain.com`. I control that domain and I can set any DNS records I want - including SPF, DKIM and DMARC.
> 
> `You should have authority over that IP/domain space.`
> 
> Should I contact AWS to let me control their DNS to modify the SPF record for `ec2-18-170-134-10.eu-west-2.compute.amazonaws.com`? They won't let me :)

You need to set the PTR records for 18.170.134.10 to hostname.domain.com

How ever Amazon is a pain with that best solution is to just config amazon ses via v-add-sys-smtp ...

**Comment by xbiggyl** [comment]
<img width="1096" alt="Screen Shot 2024-01-04 at 22 59 13" src="https://github.com/hestiacp/hestiacp/assets/13888527/74339f0f-875f-4ded-a9e5-754a8926239e">


Go to the DNS settings of your domain on Hestia and copy the DKIM, SPF, and DMARC records to where you set your DNS for that domain (cloudflare for example).

If it still doesn't work, check the logs:
 /var/log/exim4/mainlog

**Comment by kfrankiewicz** [comment]
Hi guys. Thanks for the messages. The current solution is not the greatest, but I've managed it. I've missed that AWS has an option "Update Reverse DNS" for Elastic IPs.

But it's also possible to add the PTR record 10.134.170.18.in-addr.arpa directly at HestiaCP and the machine uses this PTR record for reverse DNS. It thinks that it's a remote public PTR record, but it's just the local record.

But still, I think that it's an issue that HestiaCP uses only the public host from the reverse DNS. It's difficult to set the "From" domain for emails sent from HestiaCP.

**Comment by istiak101** [comment]
You need to be authority for that IP space so that you can set PTR. That IP space is owned by AWS and your PTR must be set from the AWS interface. The other mail server is going to query the nameserver for the IP address with authority not a random nameserver for PTR.
