### ISSUE TITLE
[Bug] v-update-letsencrypt-ssl error when no mail features enabled

### ISSUE THREAD

**Issue by stdnk** [hestiacp/hestiacp#2930]
### Describe the bug

Cron `sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl` emails me 
> grep: /usr/local/hestia/data/users/username/mail.conf: No such file or directory

I guess it happens because v-restore-user does not create mail.conf file while current installation has no mail features enabled.
Installation script I used:
`bash hst-install.sh --apache no --phpfpm yes --multiphp yes --vsftpd no --proftpd no --named no --mysql yes --postgresql yes --exim no --dovecot no --sieve no --clamav no --spamassassin no --iptables yes --fail2ban yes --quota no --api no --interactive no --email $ADMIN_EMAIL --password $ADMIN_PWD --with-debs no  --port 8083 --hostname $HOST_NAME --lang en`

### Tell us how to replicate the bug

1. Install Hestia with no mail features enabled.
2. Restore backup from previous installation.
3. Wait v-update-letsencrypt-ssl cron run.
4. You receive email with error I mentioned in description.

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.6.8

### Operating system

Debian 11.5

**Comment by jaapmarcus** [comment]
Please check if the PR works

**Comment by stdnk** [comment]
Made changes to my `func/main.sh` and run `v-update-letsencrypt-ssl`. The error is gone. Thanks!

**Comment by stdnk** [comment]
Hey guys! Just updated to v1.6.11 and have same issue again. There is no any #2930 mentions in recent change logs (v1.6.9-11).

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/e0d0d7168ae48a02f0874ee88b71b4f1f3e4f2c4/func/main.sh#L478-L487

Is looks like it never got merged in a staging branch / release branch

**Comment by stdnk** [comment]
Should I do smth to pull that fix from main branch into one of upcoming release?

**Comment by jaapmarcus** [comment]
I have added it to the 1.6.13 release including a bug fix for php8.2-imagenick missing

**Comment by jaapmarcus** [comment]
I knew I forgot something when I did prepare 1.6.12 ...
