### ISSUE TITLE
[Feature] Integrate internxt Drive for backups storage

### ISSUE THREAD

**Issue by darkworks** [hestiacp/hestiacp#2933]
### Describe the feature or change in detail

Am wondering if we can integrate Internxt Drive in Hestia to store our backups as this platform is very reliable and growing faster, i also own their 1 TB plan. They have even SDK to integrate with services : https://github.com/internxt/sdk

thanks 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We are planning to implement Rclone support for backup solutions with this method we support most commonly u

https://github.com/hestiacp/hestiacp/pull/2928

Other options will not mostlikely not been implemented. 

<img width="1893" alt="Screenshot 2022-09-20 at 14 50 13" src="https://user-images.githubusercontent.com/9754650/191262237-8a8cf71d-53b9-4445-9abd-b9635217e147.png">

**Comment by darkworks** [comment]
ok this is good news rclone will be big jump

**Comment by jaapmarcus** [comment]
https://www.reddit.com/r/rclone/comments/vte6d0/how_can_i_mount_internxt_drive/

Currently not supported but they seems to be working on it.
