### ISSUE TITLE
[Feature] LDAP Support?

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#2935]
### Describe the feature or change in detail

Considering the integration with invoicing and support software, LDAP could be really useful - for example for unified customer logins in Zammad and Hestia.
Are there any plans in that direction? I think Hestia could serve as an LDAP Server here and become the base for managing customers, but I don't know enough about LDAP to give any sensible advice here.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
We are not planning to adding support for LDAP to HestiaCP

Managing customer data should be done ideally in the billing system as multiple HestiaCP servers can exist or 1 client can have  1 or multiple "accounts" on HestiaCP for example multiple websites. 

Depending what need to connect to the LDAP server a custom integration is required:

- Hestia User account (Uses Linux /etc/passwd)
- SSH Access (Uses Linux /etc/passwd)
- Email (Goes trough Dovecot)
- Mysql access (Mysql)

Most likely it becomes so specific it doesn't make sense to allow it become part of "HestiaCP".

**Comment by xeruf** [comment]
That is interesting - I don't see an advantage of having multiple accounts per customer, since you can simply manage multiple sites per login.
The plethora of integrations is why I was wondering about Hestia as LDAP Provider - you create a customer in Hestia, and it is immediately available in all Service Portals with unified data/login - and staff as well, with correct permissions.

Are there any alternatives? I really think unified login is vital for modular open-source software to succeed and compete with big players.

**Comment by jaapmarcus** [comment]
It doesn't make sense to make Hestia as LDAP provider.  How are you going to handle multiple servers? 

What if you have multiple "Hestia" servers and a client want to login into Zammed. He needs to know what server has his authentication data on. Or you need to check all the servers. 

For example I have 1000 clients dived over 10 servers a client wants to login into his ticketing system. How do I needs to login:

Option 1: Select server that is currently using
Enter Password / Username

Option 2: 
Enter Password / Username
And the server needs to check where the client is hosted on. 

The only method to support it is create a central server with all the authentication data and allow Hestia connect to it to verify the login data. And receive back the account linked to this account. 

How ever you still have issue how you want to sort out other services like email, ssh and so on... 

If I check our main "competitors" as Directadmin, Cpanel and other open source panels. None of them support it. 

Currently the are other issues that are more important for us like ipv6 support, incremental backups and DNSSEC support that we also need.

**Comment by xeruf** [comment]
It's not just about direct competitors, it's about the grand scheme of things.
Hetzner is only tangientally related, but they have management, billing and support in one platform.
I want to achieve similar things with open-source, that is why I also work for example with the people https://stackspin.net
If we want progress, we need to stop building proprietary complex ecosystems, and for that we need worthy alternatives.

As for multiple servers - maybe they can each sync to a central Active Directory, updating only the accounts they created?
Then, Hestia is still in control and you don't need to worry about the other services.

LDAP for individual E-Mail-Accounts is a totally different topic, though, and seems to already be possible:
https://forum.hestiacp.com/t/exim-sender-verify-fail-when-using-ldap-dovecot-auth/1807

I do agree that these other issues are important too, though :)

**Comment by jaapmarcus** [comment]
Hetzner is an system integrator and have almost full control over their software... Hestia does not offer services as web hosting, domain registration or run cloud servers. We are a tool to help users to manage their websites. And a lot of users don't even sell "Service" to their clients. 

Hetzner has one advantage they have full control on the support software, Cloud panel and robot. So a tight integration is way easier.  The LDAP system is based on the "Billing" system and everything is tight into that and not based on their web hosting panel. 

So if you want such system base everything on a Billing system that can do it. 

I don't think there is a lot of demand from our users for such system as it depends on so many factors. 

Start with a central billing system that has already LDAP support and intgrating HestiaCP is a lot easier.

As this is a client specific it does not make sense to implement in the "core" of HestiaCP so everything that needs to be done is extra. If we need to count any work you will run into xxx+ hours + xxxx euro maintenance fee / month + x months lead time.  

An idea would be support openID / Smal so a user can connect with an LDAP or other server makes more sense...

**Comment by xeruf** [comment]
So the consensus here is to wait for https://fossbilling.org to be production-ready, which will then receive first-grade integration anyways?

**Comment by ScIT-Raphael** [comment]
The consensus is that we do not plan to implement LDAP support, if you would like to have it, you need to find another way.

**Comment by istiak101** [comment]
> So the consensus here is to wait for https://fossbilling.org to be production-ready, which will then receive first-grade integration anyways?

Setup Keycloak and connect it LDAP. I think you can then develop yourself a custom login module to work with Oauth2/SAML as there are already lots of libraries for those available. Or integrate LDAP directly with HestiaCP in your own fork.

**Comment by jaapmarcus** [comment]
FOSSBilling has already support for Hestia so ordering should work fine. It doesn't have support for login directly from it into  Hestia with out a password...
