### ISSUE TITLE
[Bug] Send Welcome Message [Missing a valid address in From: ]

### ISSUE THREAD

**Issue by PotatoRui** [hestiacp/hestiacp#2936]
### Describe the bug

When I Add a new user, with a checked checkbox “Send welcome email”. 
It returns an error on my "/var/log/exim4/mainlog"

` admin <admin@domain.com> R=localuser T=local_delivery`
`SMTP error from remote mail server after pipelined end of data: 550-5.7.1 [2001:000xxxxxxxxx] Messages missing a valid address in From:\n550 5.7.1 header, or having no From: header, are not accepted. l8-20020a170902f68800b00170f6f728d4si30765320plg.543 - gsmtp`

I can telnet smtp.gmail.com 25
I can send emails with new created email account
I can receive emails

Screenshot Below
![image](https://user-images.githubusercontent.com/49616497/190919821-ed779c35-6b48-4e00-bd64-88bcd3df9e2f.png)

```SENT EMAIL WITH "SEND WELCOME MESSAGE OPT"

Return-path: [admin@domain.com](mailto:admin@domain.com)
Received: from admin by domain.com with local (Exim 4.95)
(envelope-from [admin@domain.com](mailto:admin@domain.com))
id 1oaBwS-000dUd-Eh
for [gmailuser@gmail.com](mailto:gmailuser@gmail.com);
Mon, 19 Sep 2022 08:15:48 +0000
To: [gmailuser@gmail.com](mailto:gmailuser@gmail.com)
Subject: Welcome to Hestia Control Panel
Date: Mon, 19 Sep 2022 08:15:48 +0000
From:
Message-ID: [c0AT3joC0KY8nOuyiH8XT4iKcwbqnBTRpkDfBhY6XZw@localhost.localdomain](mailto:c0AT3joC0KY8nOuyiH8XT4iKcwbqnBTRpkDfBhY6XZw@localhost.localdomain)
X-Mailer: PHPMailer 6.6.3 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="b1_c0AT3joC0KY8nOuyiH8XT4iKcwbqnBTRpkDfBhY6XZw"
Content-Transfer-Encoding: 8bit
```

### Tell us how to replicate the bug

1. Login as Administrator
2. Click on add new user
3. Check the "send welcome email"
4.  Message sent successfully but returns an error that there is a missing "FROM" on the email
Image Below
![image](https://user-images.githubusercontent.com/49616497/190919954-36b6dd94-820f-446c-b1c1-a5148e304d01.png)

### Which components are affected by this bug?

Mail (Exim, Dovecot), Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 22.04.1 LTS x86_64

### Log capture

```shell
Return-path: admin@domain.com
Received: from admin by domain.com with local (Exim 4.95)
(envelope-from admin@domain.com)
id 1oaBwS-000dUd-Eh
for gmailuser@gmail.com;
Mon, 19 Sep 2022 08:15:48 +0000
To: gmailuser@gmail.com
Subject: Welcome to Hestia Control Panel
Date: Mon, 19 Sep 2022 08:15:48 +0000
From:
Message-ID: c0AT3joC0KY8nOuyiH8XT4iKcwbqnBTRpkDfBhY6XZw@localhost.localdomain
X-Mailer: PHPMailer 6.6.3 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="b1_c0AT3joC0KY8nOuyiH8XT4iKcwbqnBTRpkDfBhY6XZw"
Content-Transfer-Encoding: 8bit
```

**Comment by ScIT-Raphael** [comment]
Please do not create multiple reports for the same issue: https://github.com/hestiacp/hestiacp/issues/2929
