### ISSUE TITLE
[Feature] Add TOR exit nodes list to an ipset

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#2937]
### Describe the feature or change in detail

fetch this list: curl -s https://check.torproject.org/exit-addresses | awk '/ExitAddress/ {print $2}' | sort -n

And make it available from the panel so that the admin can decide to allow or deny those IP address es explicitly.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
This scripts keeps the old list and combines both to have a larger list:
```
#!/bin/bash
fichero="/opt/nm-bin/tor.list"
tmp="/tmp/tmptor"
urltor="https://check.torproject.org/exit-addresses"

#get count
#if [ -f $fichero ]; then
#       ipiniciales=$(wc -l $fichero | cut -d' ' -f1)
#       echo "IPs iniciales: $ipiniciales"
#fi

#añado nuevas IPs al fichero
curl -s $urltor | awk '/ExitAddress/ {print $2}' > $tmp

#fusiono listas
if [ -f $fichero ]; then
        cat $fichero >> $tmp
fi

#ordeno y quito duplicados
cat $tmp | sort -n | uniq > $fichero

if [ -f $fichero ]; then
        #ipfinales=$(wc -l $fichero | cut -d' ' -f1)
        #echo "IPs totales: $ipfinales"
        cat $fichero
        exit 0
        else
        echo "Error: No se ha creado $fichero"
        exit 1
        fi

```
It also outputs all the IPS so that it can be used with v-add-firewall-ipset tor path/to/script/script.sh

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp-ipset

Feel free to submit a PR to add more
