### ISSUE TITLE
[Bug] v-add-database-host does not check if really can write and the GUI show all commands OK

### ISSUE THREAD

**Issue by rodrigogarcia2021** [hestiacp/hestiacp#2939]
### Describe the bug

When you add a remote mysql server with v-add-database-host is added but never check is the remote server can write.
In addition, when you add databases and select the remote server and save, all is OK, but no database is created, so hestia does not check if really writed the db.

### Tell us how to replicate the bug

1. Install Hestia
2. Install mysql in a remote server LAN or WAN
3. Use script to add remote mysql server
4. Does not allow remote login
5. Try to create database as user in HestiaCP
6. Show ok and the DB created
7. Check in remote show databases; and DB does not exist
8. Allow remote root
9. To point 5 and now say OK too, but the DB is created in remote server.

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu server 22.04

### Log capture

```shell
No log
```

**Comment by jaapmarcus** [comment]
There are multiple issues:

Case 1:
User adds remote database + user without grant permissions or incorrect permissions

Case 2:
User alters permissions of the "root" database user (Or user in general)

Case 1: We should ideally check if the user has the correct grant permissions and can execute the task(s)

Case 2: We should monitor the return code and show errors when failed. 

See #3049

**Comment by jaapmarcus** [comment]
Issues should be fixed and merged
