### ISSUE TITLE
[Bug] Opencart Config not defined from Quick Install

### ISSUE THREAD

**Issue by PotatoRui** [hestiacp/hestiacp#2946]
### Describe the bug

I tried installing OpenCart from quick install. 
![image](https://user-images.githubusercontent.com/49616497/193302399-402961b8-39dc-428b-8d22-a633e5fbcdb7.png)

and it was installed but when Im accessing the website it returns me to an infinite loop of /install/admin.php
also the config file for database is blank
![image](https://user-images.githubusercontent.com/49616497/193302604-35a9cc39-8153-4325-90f9-5a9b802cb28d.png)

### Tell us how to replicate the bug

1. open the domain you want to be installed with opencart
2. tap quick install

### Which components are affected by this bug?

Control Panel Installation or Upgrade, Control Panel Web Interface

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 22.04.1 LTS x86_64

**Comment by jaapmarcus** [comment]
We will upgrade to a newer version that solves the issue in 1.6.9

https://github.com/hestiacp/hestiacp/tree/staging/1.6.9
