### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by acuario300** [hestiacp/hestiacp#2953]
### Describe the bug

When i delete opened port from firewall page it continues opening the port after. Seem it´s not closing it automatically.
You can see en console how it steel opened.

### Tell us how to replicate the bug

i Delete ports opened in firewall page 

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
Please provide with more information: Test it on the same server doesn't help.


```
root@cp:/home/eris# telnet my.server.nu 8083
Trying 168.xx.x.x.x..
Connected to dev.eris.nu.
Escape character is '^]'.
^X^ZConnection closed by foreign host.
```

Delete 8083 firewall rule:

```
root@cp:/home/eris# telnet my.server.nu 8083
Trying 168.xx.x.x.x.....
^X^Z
^X^Z
```

And adding it again:

```
root@cp:/home/eris# telnet my.server.nu 8083
Trying 168.xx.x.x.x.....
Escape character is '^]'.
```

Seems to work fine.
