### ISSUE TITLE
Will HestiaCP work with MySQL alongside MariaDB?

### ISSUE THREAD

**Issue by hanzicode** [hestiacp/hestiacp#296]
### Brief issue description:
I made a switch from Vesta to Hestia, not kowing Hestia uses MariaDB. Two forums at https://1459919.org gives the 500 Internal Server Error after the switching over

### Steps to Reproduce:
1. Example1: https://1459919.org/chinese - 500 Internal Server Error
2. Example2: https://1459919.org/english - 500 Internal Server Error

### Expected behavior:
When MySQL was used instead of MariaDB, the two forums loaded fine before the swtiching

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
The latest 0.9.8-28

### Which branch are you using?
Master

### What software is installed?
The default Apache, Nginx, PHP-FPM, Dovecot/Exim, MariaDB, etc

I used this to install:

bash hst-install.sh -f -y no -e myemail@gmail.com -p p4sswrd -s svr1.hostname.com

**Comment by ghost** [comment]
Hi @hanzicode, thanks for your issue report and I apologize that you're having issues. I'll escalate this internally and follow up when I have more information.

Is this a production server or a test environment? Let me know when you have a chance and have a great day.

**Comment by hanzicode** [comment]
The problem was solved by staff at the server data center. It is not the database issue but URL headers issue. This is what they say about the simple fix:

> The URLs http://1459919.org/english and http://1459919.org/chinese work fine once I enabled modules headers with Apache.
> 
> Please let me know if that is not the solution you were looking for.
> 
> root@svr1:/etc/apache2# a2enmod headers
> Enabling module headers.
> To activate the new configuration, you need to run:
> systemctl restart apache2
> root@svr1:/etc/apache2# systemctl restart apache2

**Comment by hanzicode** [comment]
It is a production server but the problem has been fixed :-)

**Comment by hanzicode** [comment]
BTW, just to use this incidence to let you know: you guys are doing a great job!

When I have time, I will write a tutorial showing people how to migrate from Vesta to Hestia, which has the needed features in default installation such as...

* Additional button beside SSL and LetsEnscrypt to make quick HTTP to HTTPS redirect
* Two factor authentication for HestiaCP login
* Hostname URL for HestiaCP login rather than IP
* Working right after fresh install for admin login password reset email

and much more yet to find out :-)

Love it!

**Comment by ghost** [comment]
Thank you so much for the kind words @hanzicode! We're working hard on the next release, which will feature (this is not a complete list):

- Improvements to the SSL layer and handling for web domains 
- DNS CAA support (Let's Encrypt by default plus custom records)
- SSL certificate support for all mail services at the domain level (with Let's Encrypt support)
- A refreshed user experience that streamlines the interface, improving the overall navigation and discovery of common items while remaining familiar to Vesta users
- An updated file system layout for storing configuration files per-domain, to facilitate easier management through the console and when managing backups.
- Many, many bug fixes.
- Security fixes and improved out-of-the-box hardening.

Keep the feedback coming! If you'd like to contribute to our documentation that would be fantastic and any effort is greatly appreciated. 

I'll close this issue for now, but if you have any other issues please do not hesitate to open a new report. Have a fantastic day!
