### ISSUE TITLE
[Feature] Re-scan backup folder

### ISSUE THREAD

**Issue by ww7** [hestiacp/hestiacp#2965]
### Describe the feature or change in detail

Backup restoration experience can be seriously improved with re-scan of backup folder.

Sometimes backup files copied manually or moved between servers.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Technically not possible if you import a backup from an other server it usually means you need to create the user anyway. Why not do it at the same time via command line.

I would prefer to create a new function so we can bulk import new users at once

**Comment by ww7** [comment]
Rotation respects all files by pattern `^$user\.` and deletes backups even if they are not in the Hestia list.
In the same time, Hestia can't show manually uploaded backups. 

For SSH lovers it's perfectly fine to restore with CLI, but for technically not skilled users ability for manually uploaded backup to find proper restore options (select certain DB or only one domain etc) is definitely missing.

**Comment by ww7** [comment]
@jaapmarcus You rushed to close this request. This feature is not false and not wrong.
Okay, I will develop this feature himself.

**Comment by jaapmarcus** [comment]
1. If Backups are stored on a remote location (With Rclone we most of them) and made on the same server as you try to import them on the same server you backup them there is not need to rescan them as they allready exists
2. For a new server what is the issue with running the command v-restore-user user user.backup.tar 

vs 
- Create new user 
- Upload backup to server
- Rescan server and then backup. 

Also we assume that users now how to run ssh commands you it is to difficult for you you are not suppost to run Hestia on your server... 

Al basic knowledge..

**Comment by ww7** [comment]
@jaapmarcus I am not mean user restore, but for cases when some backup file stored somewhere outside. With GUI much easier to restore certain DB or domain.

It especially related because Hestia rotating backups and not possible to have backups that retained (protected from deletion by rotation)

My requests based on real-world usage and years of Hestia experience. Currently, I'm using scripts with Rclone that rotating backups with customized logic (7 last days, 4 monthly, 4 quarterly, 2 half year, 1 yearly). 
Such backups not visible in GUI. And sometimes difficult to explain Hestia users how to restore with SSH. 
And no official way to list them to Hestia GUI (via calling some `v-` command)

Furthermore, protected backups from deletion are very missed. Because rotation. Sometimes website hacked 1 week ago and all backups infected, or need to preserve some website/db version.
