### ISSUE TITLE
[Bug] Time zone change bug

### ISSUE THREAD

**Issue by joramatveev** [hestiacp/hestiacp#2971]
### Describe the bug

When trying to set the time zone Europe/Kyiv - we get an error

![2](https://user-images.githubusercontent.com/88455937/195739993-8af59591-2c39-4c9f-b0c3-0bde69cbc88b.png)

This happens due to the fact that everywhere in the timezones lists, Kyiv is written as Kiev, and not Kyiv (which is the correct translation)

If I change in the html "Europe/Kyiv" to "Europe/Kiev" and press save, there will be no error

![image](https://user-images.githubusercontent.com/88455937/195740869-5847d8c4-188a-406b-8c7a-2bf57eb89086.png)

Due to the fact that "Europe/Kiev" is not in the list of time zones - displays the first time zone from the list

![image](https://user-images.githubusercontent.com/88455937/195740944-092ff12a-d9da-4f73-bd98-e1a88934f67c.png)

### Tell us how to replicate the bug

Go to the admin panel under the main admin
Go to the "Servers" tab
Then clicked "Setup".
In the "Basic Settings" section, I found this error

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

  v1.6.10	

### Operating system

Debian 11.5 (x86_64)	

### Log capture

```shell
2022-10-13 20:33:23 v-list-web-domain  'admin' 'hesta.webdevil.buzz' 'plain' [Error 3]
2022-10-13 20:33:23 v-list-web-domain  'admin' 'hesta.webdevil.buzz' 'plain' [Error 3]
2022-10-13 20:33:23 v-add-web-domain  'admin' 'hesta.webdevil.buzz' [Error 2]
2022-10-13 20:59:52 v-change-sys-timezone  'Europe/Kyiv' [Error 3]
2022-10-14 04:02:16 v-change-sys-timezone  'Europe/Kyiv' [Error 3]
2022-10-14 04:02:22 v-change-sys-timezone  'Europe/Kyiv' [Error 3]
2022-10-14 04:06:59 v-list-web-domains  [Error 1]
2022-10-13 17:13:51 v-change-sys-timezone  'Europe/Kyiv' [Error 3]
```

**Comment by jaapmarcus** [comment]
There is a difference between Debian (Europe/Kiev) and php (Europe/Kyiv) timezones...

**Comment by jaapmarcus** [comment]
https://www.reddit.com/r/ukraine/comments/x8c897/europekiev_timezone_has_officially_been_renamed/

So it it is PHP who Is "right"

**Comment by turbopixel** [comment]
*Europe/Kyiv* is officiall supported. But it is not listed on my server either.

php doc: https://www.php.net/manual/en/timezones.europe.php 
Open issue: https://bugs.php.net/bug.php?id=80254

**Comment by jaapmarcus** [comment]
PHP is just fast with updating.... 

We should probally create a list on the existing locales on the server...

**Comment by jaapmarcus** [comment]
cd /usr/share/zoneinfo/posix && find * -type f -or -type l | sort

Should do the the trick...

**Comment by jaapmarcus** [comment]
See #3031

**Comment by turbopixel** [comment]
> cd /usr/share/zoneinfo/posix && find * -type f -or -type l | sort
> 
> Should do the the trick...

Works at:
* Ubuntu 18.04.6 LTS
* Debian 5.10.84-1
