### ISSUE TITLE
[Feature] Login As in search page

### ISSUE THREAD

**Issue by softcodex-team** [hestiacp/hestiacp#2973]
### Describe the feature or change in detail

Hi, why not adding a useful link near the username in the search page to login as that user?

![image](https://user-images.githubusercontent.com/91430127/195818053-0e292b92-853c-42e5-b312-48b813565c79.png)

not sure how to check if the current user is an admins

https://github.com/hestiacp/hestiacp/blob/508d3f163d93293fc8afb39c3ae512c5bdf30f63/web/templates/pages/list_search.html#L146

can be added this

```
&nbsp;
<a href="/login/?loginas=<?=$value['USER']?>&token=<?=$_SESSION['token']?>" title="<?=_('login as');?> <?=$value['USER']?>"><i class="fas fa-sign-in-alt status-icon green status-icon dim icon-large"></i></a>


```
### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
This makes a lot of sense to me.
