### ISSUE TITLE
[Bug] User link on search page

### ISSUE THREAD

**Issue by softcodex-team** [hestiacp/hestiacp#2974]
### Describe the bug

Not sure if clicking onthe user name in the search page open the expected page

![image](https://user-images.githubusercontent.com/91430127/195819096-4c5bc001-4ba9-4914-9075-480f589ffa95.png)

redirect to /list/user/
but the href is /search/?q=%27adm%27&u=admin

### Tell us how to replicate the bug

1. list user
2. search for a term
3. click on the username cell

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.10

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
It is due the escaping of the query will patch it

**Comment by softcodex-team** [comment]
is it right is still not working on 1.6.11?

**Comment by jaapmarcus** [comment]
It was committed in the 1.7.0 branch. I might forgot to merge it into the staging / 1.6.x branch
