### ISSUE TITLE
Does not accept FQDN with 2 periods "." and 2 letter main domain [Bug] 

### ISSUE THREAD

**Issue by zafzal3** [hestiacp/hestiacp#2994]
### Describe the bug

Install script does not accept help.me as a FQDN and if used "help.me." install fails. No way to reverse install prompted to user. 

### Tell us how to replicate the bug

Try install with a FQDN such as abcd.ee

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.6.10

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
Please use hostname.domain.tld as suggested. The validation searches for atleast two points in the url, thats why abcd.ef. will be looked as valid - but honestly I do not see any need to rework that part, the example is more than clear.

**Comment by zafzal3** [comment]
I am sorry your answer is not clear, "abcd.ef." gets accepted as a valid FQDN but results in failed installation and there is no way to re-run the script to fix it either. It to me is an oversight and can be fixed, just that have the know-how on how to do it.

**Comment by jaapmarcus** [comment]
We should add a check if it is a valid domain name as well.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3048
