### ISSUE TITLE
[Bug] Unsuspending a database won't restore remote user access

### ISSUE THREAD

**Issue by raenk** [hestiacp/hestiacp#3011]
### Describe the bug

Unsuspending a database won't restore remote user access. Old password must be set again or set a new one.

Haven't test for local access.

### Tell us how to replicate the bug

1. Select a user
2. Click on DB tab
3. Suspend a DB
4. Unsuspend the DB
5. Try to connect to DB remotely

### Which components are affected by this bug?

Control Panel Web Interface, Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 22.04 x64

**Comment by jaapmarcus** [comment]
```
    query="GRANT ALL ON \`$database\`.* FROM \`$DBUSER\`@\`%\`"
    mysql_query "$query" > /dev/null
    query="GRANT ALL ON \`$database\`.* TO \`$DBUSER\`@localhost"
    mysql_query "$query" > /dev/null
```

Should be probably to

**Comment by jaapmarcus** [comment]
See PR

**Comment by jaapmarcus** [comment]
Issue has been sorted.
