### ISSUE TITLE
[Anomaly] phpMyAdmin not install with fresh install of HestiaCP 1.6.11

### ISSUE THREAD

**Issue by azvampyre** [hestiacp/hestiacp#3012]
### Describe the bug

v.1.6.11 fresh install does not install phpmyadmin
I don't know if this is a bug or if phpmyadmin was removed from 1.6.11
It's easily fixed by installing it through terminal.

### Tell us how to replicate the bug

1. Install HestiaCP v.1.6.11 using default method.
2. Create a Website and DB
3. Click phpMyAdmin
4. Access Denied: You do not have permission to access this page.
5. apt install phpmyadmin
6. Login successful

### Which components are affected by this bug?

Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.6.11

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
https://docs.hestiacp.com/admin_docs/database.html#why-i-can-t-use-http-ip-phpmyadmin

**Comment by azvampyre** [comment]
I'm not using http ip. Please pay attention.

**Comment by ScIT-Raphael** [comment]
phpmyadmin works out of the box, we do not install it over the repository (https://github.com/hestiacp/hestiacp/blob/main/install/hst-install-debian.sh#L1520-L1577), also you dont have exactly stated hiw you access it - so its hard to pay attention on it :).

Please checkout the related weblogs (var/log/[ngingx/apache2]
