### ISSUE TITLE
[Discrepancy] ClamAV installed by default

### ISSUE THREAD

**Issue by azvampyre** [hestiacp/hestiacp#3013]
### Describe the feature or change in detail

ClamAV is installed by default on new installation with no option to remove it.
This is okay, but it uses a lot of resources.
apt remove clamav && apt remove clamav-daemon leaves the angry red clamav-daemon shadow behind in Services that could cause someones OCD to trigger.

If anyone wants to disable it:

1. Edit `/etc/exim4/exim4.conf and delete "CLAM = yes"`
2. Edit `/usr/local/hestia/conf/hestia.conf` and change `ANTIVIRUS_SYSTEM='clamav-daemon' to ANTIVIRUS_SYSTEM=''`

optional: apt remove clamav && apt remove clamav-daemon

**Comment by ScIT-Raphael** [comment]
https://docs.hestiacp.com/getting_started.html#all-available-options-of-install-script
