### ISSUE TITLE
[Bug] Backblaze can't upload large files?

### ISSUE THREAD

**Issue by Fcatme** [hestiacp/hestiacp#3041]
### Describe the bug

Backing up data to backblaze seems to report an error when uploading large files. Currently, all my data is compressed to about 50G and it reports an error when backing up to backblaze. Here is the error message

### Tell us how to replicate the bug

Configure Backblaze normally, then perform a 50G+ data backup to reproduce the problem.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.11

### Operating system

Debian11

### Log capture

```shell
-- SUMMARY --
2022-11-12 00:26:18 Local: /backup/userme.2022-11-12_00-18-34.tar
2022-11-12 00:26:19 Upload to B2: userme/userme.2022-11-12_00-18-34.tar
/usr/local/hestia/func/backup.sh: line 438: 28655 Segmentation fault b2 upload-file $BUCKET $user.$backup_new_date.tar $user/$user.$backup_ new_date.tar > /dev/null 2>&1
2022-11-12 00:29:46 Size: 51913 MB
2022-11-12 00:29:46 Runtime: 13 minutes
```

**Comment by jaapmarcus** [comment]
We use https://github.com/Backblaze/B2_Command_Line_Tool to upload the file 

Maybe try uploading 
```
b2 upload-file bucket user.date.tar user/user.date.tar
```
And see if it fails or not if so you should create an issue at https://github.com/Backblaze/B2_Command_Line_Tool  instead

**Comment by ScIT-Raphael** [comment]
Thanks for the report, currently we "just" use the b2 cli tool (https://github.com/Backblaze/B2_Command_Line_Tool) and upload the file, so we can't do anything here if it fails - you would probaly need to reach out at the b2 issue tracker. Also I'm not sure if it also could be a local issue due to the "Segmentation fault" thrown out.
