### ISSUE TITLE
[Bug] BREAKING domain name appended to mx entry

### ISSUE THREAD

**Issue by MenschLink** [hestiacp/hestiacp#3043]
### Describe the bug

when I define an mx record for a domain, the domain name itself is appended to mx entry. The result is then mail.exchanger.tld.domain.tld; I want only exchanger.tld

### Tell us how to replicate the bug

define an mx value for a domain

send

nslookup or dig your mx

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.6.8

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
<img width="628" alt="Screenshot 2022-11-12 at 15 15 30" src="https://user-images.githubusercontent.com/9754650/201478244-a925aaf5-147a-4fad-af5b-69f91f4c1d80.png">

Use @ for the root domain and enter it as:

**Comment by MenschLink** [comment]
> <img alt="Screenshot 2022-11-12 at 15 15 30" width="628" src="https://user-images.githubusercontent.com/9754650/201478244-a925aaf5-147a-4fad-af5b-69f91f4c1d80.png">
> 
> Use @ for the root domain and enter it as:

I just retested it, it seems this was already addressed and I panicked because many customers were complaining that no mail was arriving.

**Comment by xeruf** [comment]
Unfortunately this issue reappeared with recently created domains. Not sure why.

Your response also does not make sense to me though, what is google smtp doing in there?

**Comment by jaapmarcus** [comment]
We haven't released any changes regrading DNS...
