### ISSUE TITLE
[Bug] Change DB username

### ISSUE THREAD

**Issue by demlasjr** [hestiacp/hestiacp#3051]
### Describe the bug

I'm not able to edit database username. When I'm doing it, I'm getting confirmation that everything gone well and when I refresh the page, the name is the same as before. 

### Tell us how to replicate the bug

1. Go to DB page
2. Create a database with it's username and password username
3. Edit DB username
4. Save

### Which components are affected by this bug?

Control Panel Web Interface, Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.6.11

### Operating system

Debian 11.5

**Comment by jaapmarcus** [comment]
Mysql or Postgresql?

For Mysql we run som tests so it should work fine:
 ✓ MYSQL: Rebuild Database 
 ✓ MYSQL: Change database user password 
 ✓ MYSQL: Change database user 
 ✓ MYSQL: Suspend database 
 ✓ MYSQL: Unsuspend database 

I know there are some issue with Postgresql

**Comment by demlasjr** [comment]
Hi @jaapmarcus,

It's happening in MariaDB (mysql). Never had this problem. I updated 2 days ago to the last version and now it's happening. Can somebody test if it works well?

**Comment by jaapmarcus** [comment]
I can confirm the issue but only on the release branch... 

Will check what is going wrong

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/e0d0d7168ae48a02f0874ee88b71b4f1f3e4f2c4/web/edit/db/index.php#L52-L53

Looks just wrong


It has been "fixed" in the main branch
https://github.com/hestiacp/hestiacp/blob/5965a75a54cb0a670b26d3329ca82628875033ae/web/edit/db/index.php#L53-L61

**Comment by jaapmarcus** [comment]
Issues have been patched in:
https://github.com/hestiacp/hestiacp/tree/staging/1.6.12

I don't know the release date yet..

**Comment by demlasjr** [comment]
Yes, I was also checking those files since you confirmed it too, but you were faster fixing it. Thank you Jaap.
I'll close this since has been fixed.
