### ISSUE TITLE
Hestia Installation issue

### ISSUE THREAD

**Issue by chiragnahata** [hestiacp/hestiacp#3054]
### Describe the bug

I have upgraded to 22.10 ubuntu arm64 and cannot install hestia. My previous hestia was not working so in tried reinstalling and this is the error i got is unsupported
Please help
My whole system is down
asap

### Tell us how to replicate the bug

Install Hestia

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

Latest

### Operating system

Ubuntu 22.10

**Comment by ScIT-Raphael** [comment]
22.10 not supported.
