### ISSUE TITLE
Purge nginx cache error

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#3062]
### Describe the bug

When you either use button or the CLI command to purge nginx cache it deletes the folder with the domain name in var/cache/nginx this causes the website to fail until the domain config  is rebuilt. 

# Purge nginx FastCGI cache 
 if [ -d "/var/cache/nginx/micro/$domain" ]; then 
     rm -rf /var/cache/nginx/micro/$domain/*
 fi 
  
 # Purge nginx proxy cache 
 if [ -d "/var/cache/nginx/$domain" ]; then 
     rm -rf /var/cache/nginx/$domain/*
 fi

Easy solution is just an ad /* on the command I shown above so it deletes the contents of the folder not the folder.

### Tell us how to replicate the bug

Purge your cache in gui

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.11

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3060
