### ISSUE TITLE
[Bug] hyphen in subdomain

### ISSUE THREAD

**Issue by frelle** [hestiacp/hestiacp#3084]
### Describe the bug

Hello
First, thank you for your repo, it helps a lot
I have noticed an issue when I add a new domain via the panel, if there is a hyphen in a subdomain, it doesn't work ( I mean I can save, but the page can't be reached : DNS_PROBE_FINISHED_NXDOMAIN

for ex : 
subdomain.domain.com -> work
sub-domain.domain.com -> not working 

Thank you for the help

### Tell us how to replicate the bug

1. Add web domain

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.6.8

### Operating system

Ubuntu 22.04 (x86_64)

**Comment by ScIT-Raphael** [comment]
DNS_PROBE_FINISHED_NXDOMAIN means you dont have a dns record set or it has not yet propangated. Infact this is more a support issue than a bug, please stick to discord or forum - we would like to use github for bug reports only.
