### ISSUE TITLE
[Bug] Wrong number of databases and total allowed databases in server config

### ISSUE THREAD

**Issue by schneiderbruno** [hestiacp/hestiacp#3085]
### Describe the bug

Hi,

In server config, url "...8083/edit/server/"
Section databases number is 23.

In header section is 138 (correct).

### Tell us how to replicate the bug

1. Look header databases numbers.
2. Go to server config
3. Section databases, see number of databases and compare.

![image](https://user-images.githubusercontent.com/8595383/204604318-eb4fff69-2c03-44e1-aca7-45b3a1cb1c2b.png)

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.11

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Number of databases / server can't be set in the user package but it set in /usr/local/hestia/conf/mysql.conf

the other https://github.com/hestiacp/hestiacp/issues/1926
