### ISSUE TITLE
Create a how to scan your server for viruses with cron part :)

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#3100]
according to https://github.com/hestiacp/hestiacp/issues/1466

**Comment by bohemier** [comment]
PS: The /etc/systemd/system/clamav-daemon.service.d/extend.conf file is specifically for extending or overriding configuration options for the ClamAV daemon service (clamd). It allows to modify the default configuration of the ClamAV daemon by adding or modifying configuration parameters.

Clamscan command is a separate command-line utility that is used to perform on-demand scanning of files or directories. It runs independently of the ClamAV daemon and does not directly read the configuration options from the clamd service.

Something like this might work to limit system resources when running clamscan: `cpulimit -l 30 nice -n 19 bash -c "ulimit -v 262144 && clamscan  /home -r --include=php -o -i -l /log/clamav/daily.log"`
