### ISSUE TITLE
[Bug] Task Monitor does not remove the SQL host graph after v-delete-database-host

### ISSUE THREAD

**Issue by charlfields** [hestiacp/hestiacp#3102]
### Describe the bug

After removing a remote database with v-delete-database-host the admin task monitor keeps a graph of the removed database host. It would be better if this graph is also removed with v-delete-database-host

### Tell us how to replicate the bug

1. add a remote database with v-add-database-host
2. create a dabase on the remote host and look at the admin task monitor to see that remote database usage
3. delete that remote database with v-delete-database-host
4. go to the task monitor, and you will see the graph for the removed database host still there.
<img width="881" alt="Screen Shot 2022-12-03 at 1 26 59 PM" src="https://user-images.githubusercontent.com/64612184/205456358-1e163b6b-1b56-462c-8578-cda2f68bbd46.png">

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.11

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Can confirm the issue we need to delete 
web/rrd/mysql_host.rrd

**Comment by jaapmarcus** [comment]
See PR
