### ISSUE TITLE
[Bug] Error: tz file 453 doesn’t exist

### ISSUE THREAD

**Issue by Jeimerson** [hestiacp/hestiacp#3127]
![image_2022-12-08_215200629](https://user-images.githubusercontent.com/37664046/206575099-12e00b75-cf62-494b-9a8e-116d682eca79.png)
### Describe the bug

Error: tz file 449 doesn't exist

### Tell us how to replicate the bug

Happens after installing php 8.2

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.6.13

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
It has nothing to do with 8.2 release but an other bug...

**Comment by semsem86** [comment]
I noticed an error that never noticed before during installation start, error servername command not found in line 171 and 172 maybe this is one reason of the bug

**Comment by jaapmarcus** [comment]
See linked commit
