### ISSUE TITLE
[Bug] 1.6.13 update breaks firewall

### ISSUE THREAD

**Issue by cr0c0dylus** [hestiacp/hestiacp#3128]
### Describe the bug

I received a notification on all hestia servers "zabbix agent is unreachable for 5 minutes". I discovered that hestia dropped all firewall rules and put new ones to /etc/iptables.rules including various garbage like fail2ban and docker artifacts. The previous version of this file wasn't backuped to /root/hst_backups/. This has never happened before.

### Tell us how to replicate the bug

Autoupdate breaks firewall.

### Which components are affected by this bug?

Firewall (Iptables, Fail2ban)

### Hestia Control Panel Version

1.6.13

### Operating system

Ubuntu 20.04

### Log capture

```shell
==============================================================================
Hestia Control Panel Software Update Log
==============================================================================

OPERATING SYSTEM:      Ubuntu (20.04)
CURRENT VERSION:       1.6.11
NEW VERSION:           1.6.13
RELEASE BRANCH:        release
BUILD TYPE:            Production release

INSTALLER OPTIONS:
=============================================================================
Send email notification on upgrade complete:      true
Send installed log output to admin email:         true

=============================================================================
[ * ] Backing up existing templates and configuration files...
=============================================================================
[ ! ] Performing system health check before proceeding with installation...
[ * ] Health check complete. Starting upgrade from 1.6.11 to 1.6.13...
=============================================================================

[ - ] Now applying patches and updates for version v1.6.12...
[ * ] Update loading firewall rules service...

[ - ] Now applying patches and updates for version v1.6.13...
[ * ] File Manager is up to date (7.8.7)...
[ * ] Roundcube is up to date (1.6.0)...
[ * ] PHPmailer is up to date (6.6.5)...
[ * ] phpMyAdmin is up to date (5.2.0)...
=============================================================================
Installation tasks complete, performing clean-up...
=============================================================================
[ * ] Restarting services...

=============================================================================
UPGRADE COMPLETE.
Please report any issues on GitHub:
https://github.com/hestiacp/hestiacp/issues
=============================================================================
```

**Comment by jaapmarcus** [comment]
@myrevery  any ideas? 

https://github.com/hestiacp/hestiacp/pull/3110 is the PR that solves an issue with ipset failed to download for reboot

And therefor we had to run v-update-firewall and there for we had to regenerate the iptables again. How ever if the port for Zabbix has been opened in the Hestia firewall settings this should be no issues

**Comment by ScIT-Raphael** [comment]
I think the rules where not added properly to hestia's firewall, just added using iptables which maybe gets dropped due to v-update-firewall.

**Comment by cr0c0dylus** [comment]
Unfortunately hesita's firewall does not allow to control DOCKER-USER chain and other custom chains, to add flags etc. BTW Hestia has never changed the /etc/iptables.rules during nightly updates before. Maybe hestia should use its own chain and never delete other rules?

**Comment by jaapmarcus** [comment]
We try to limit updates to ip tables as least as possible and only if the user "Triggers" v-update-firewall manually. 

How ever due to a bug in Hestia ipset feature If a severs fails to download an ipset and then restarts It will not restore the working that why we had to update iptables rules. 

We should be able to backup iptables.rules to the backup list and that is not an huge issue

**Comment by jaapmarcus** [comment]
> Unfortunately hesita's firewall does not allow to control DOCKER-USER chain and other custom chains, to add flags etc. BTW Hestia has never changed the /etc/iptables.rules during nightly updates before. Maybe hestia should use its own chain and never delete other rules?

You should be able to add chain manually in /usr/local/hestia/data/firewall/chains

**Comment by cr0c0dylus** [comment]
Maybe fail2ban rules also should be filtered before writing to /etc/iptables.rules ? I have hundreds of blocked ips and they all in the iptables.rules now.

**Comment by jonnydo** [comment]
![Screenshot (34)](https://user-images.githubusercontent.com/40856635/206646939-71f585d3-2559-48b6-93a4-fcb541d84008.png)
Wordpress unavailable...

**Comment by jaapmarcus** [comment]
Know issue see open PR 

https://github.com/hestiacp/hestiacp/pull/3129

**Comment by myrevery** [comment]
@cr0c0dylus Sorry you ran into this issue.

But honestly this is not Hestia's bug, because you are customizing iptables in an unsupported way.

It's not your fault though, the currently supported way of customizing iptables are not documented.

Useful help for you:

See: https://github.com/hestiacp/hestiacp/blob/1.6.13/bin/v-update-firewall#L148

```
touch /usr/local/hestia/data/firewall/custom.sh
chmod +x /usr/local/hestia/data/firewall/custom.sh

# Edit and test your custom.sh, then run:

v-update-firewall
```

custom.sh example:
```
#!/bin/bash

IPTABLES="$(command -v iptables)"

$IPTABLES -N YOURCHAIN
$IPTABLES -F YOURCHAIN
$IPTABLES -I YOURCHAIN -s 0.0.0.0/0 -j RETURN
$IPTABLES -I INPUT -p TCP -m multiport --dports 1:65535 -j YOURCHAIN
```
And about "fail2ban garbage" it really needs to be improved, I will fix it later.

@jaapmarcus "/usr/local/hestia/data/firewall/chains.conf" is used by fail2ban, not recommended to touch it.

**Comment by myrevery** [comment]
Resolved by PR https://github.com/hestiacp/hestiacp/pull/3135

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/tree/staging/1.6.14
