### ISSUE TITLE
Error: Let's Encrypt validation status 400

### ISSUE THREAD

**Issue by hanzicode** [hestiacp/hestiacp#313]
### Brief issue description:
When I tried to install LetsEnscrypt SSL from within the HestiaCP (develop branch), then this error occured:
Error: Let's Encrypt validation status 400

### Steps to Reproduce:
1. Install HestiaCP master: "bash hst-install.sh --multiphp yes"
2. Recompile the HestiaCP develop right after confirming the fresh master is working fine
3. Login to to make sure the FQDM hostname domain is set up OK and can be viewed from browser - page content contains the big checkmark with "Success! Your new web server is ready to use."

### Expected behavior:
The LetsEnscrypt cert should be issued.

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
Version 0.10.0 (amd64) release 190430

### Which branch are you using?
develop - I even trid "bash hst_autocompile.sh --hestia develop no" and "apt-get install --reinstall hestia"

### What software is installed?
Apache, Nginx, PHP-FPM, Dovecot/Exim, MariaDB, etc.

### Related issues or forum threads:

I checekd /usr/local/vesta/bin/v-add-letsencrypt-domain and found the well_known path does not contain a typo "rdomain"

**Comment by hanzicode** [comment]
Good news: after running the following command:
`bash hst_autocompile.sh --hestia develop yes`

The problem is fixed!

**Comment by hanzicode** [comment]
Well, another issue shows up: I cannot get the secured HestiaCP login myhostnamedomain.com:8083 to work even though https://myhostnamedomain.com is secured without any problem - normally this works right out of the fresh install for the master branch as soon as I enable the LetsEnscrypt SSL for the hostname domain. 

And when I run this command 
`v-update-host-certificate admin $HOSTNAME`
 from the terminal, I got this error:

> This domain does not have certificate

That domain certainly has certificate.

When I run this from the terminal:
`v-add-letsencrypt-domain 'admin' $HOSTNAME '' 'yes'`
I got this error:

> Error: SSL=yes is already exists

**Comment by hanzicode** [comment]
OK, when I view the SSL section of the HestiaCP configure area from within the panel, I see that Hestia uses the self-signed SSL rather than the LetsEnscrypt SSL. But the self-signed SSL will gives a warning. It is OK if I am the only one using it, but not OK for other users. 

I found this https://www.mysterydata.com/how-to-configure-lets-encrypt-ssl-on-vestacp-mail-server-and-vesta-admin-centos-and-ubuntu and I know I have to make sure the paths are correct for HestiaCP develop's new structure. 

Hope that the new release will not use a self-signed SSL for panel login but use the same certificate as that of the hostname domain. As soon as a SSL certificate for the hostname FQDN is generated, then configure the panel login to use it. By the token, as soon as the MAIL part of hostname domain is secured by the LetsEncrypt certificate, then use it for the server.

**Comment by ghost** [comment]
Hey @hanzicode, thanks for your feedback and sorry you ran into trouble on this. Going forward now that you are on *develop* branch builds, you can run `v-update-sys-hestia-git` to install a newer build directly from our GitHub repository, as we haven't yet implemented different release channels in our package repositories for testing.

I'll review *v-update-host-certificate* tonight, in addition to the UI functionality around that area. Stay tuned, I'll provide an update once I have more info for you. Thanks again and have a great day.

**Comment by hanzicode** [comment]
Great!

The command `v-update-sys-hestia-git` did not ruin anything :-)

However, I do notice the big difference for the general look between IP-based view and domain-based view. Check the attached two screenshots.

![ip-based-vestiacp-login-web-view](https://user-images.githubusercontent.com/48425980/57751635-41f38e80-769b-11e9-996c-6ee39a5409c0.jpg)

![domain-based-vestiacp-login-web-view](https://user-images.githubusercontent.com/48425980/57751636-428c2500-769b-11e9-81a2-7029ca9a837a.jpg)

I am sure the two are loading CSS files from different places or the domain based view cannot find the intended CSS files at all.

**Comment by ghost** [comment]
This is due to the CSS being cached by your browser -- Ctrl/Cmd-Shift+R should refresh it properly for you.

**Comment by hanzicode** [comment]
Great, that worked! Thank you so much !!!

**Comment by hanzicode** [comment]
Well, more problems show up now. I made a lot of screenshots to show the process here: https://angelright.com/222/how-to-install-hestiacp-development-builds-others

**Comment by hanzicode** [comment]
The 500 error occured after going through the installtion process documented here: https://angelright.com/172/tutorials-install-hestia-vesta-fork-linode-debian-multi-php and Hesita customizations documented here: https://angelright.com/184/how-to-customize-hestia-fork-of-vesta-debian-9

**Comment by hanzicode** [comment]
Has the new release come out? I still have the 500 error for this URL https://mail628.com and this https://pan1.mail628.com

I tried `v-update-sys-hestia-git` and even tried to re-issue LetsEnscrypt for mail628.com domain. The same problem remains.

**Comment by ScIT-Raphael** [comment]
Can you check the log files for the domains? They are mostly located under /home/user/web/domain.tld/logs. Can't find on my side any issues with let's encrypt, also in combination with multiphp (using on stable release, not develop branch).

The new release will come out soon, but I strongly suggest to NOT run the v-update-sys-hestia-git command on productive systems - also the git develop branch isnt stable at all!

**Comment by hanzicode** [comment]
Check the error log and found this:

> 2019/05/19 09:11:05 [error] 3817#3817: *231 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:11:05 [crit] 3817#3817: *231 openat() "/home/admin/web/pan1.mail628.com/public_html/css/bootstrap.min.css" failed (13: Permission denied), client: 24.7$
> 2019/05/19 09:11:05 [crit] 3817#3817: *231 openat() "/home/admin/web/pan1.mail628.com/public_html/css/all.min.css" failed (13: Permission denied), client: 24.70.204.$
> 2019/05/19 09:11:05 [crit] 3817#3817: *231 openat() "/home/admin/web/pan1.mail628.com/public_html/css/animate.css" failed (13: Permission denied), client: 24.70.204.$
> 2019/05/19 09:11:05 [crit] 3817#3817: *231 openat() "/home/admin/web/pan1.mail628.com/public_html/css/style.css" failed (13: Permission denied), client: 24.70.204.12$
> 2019/05/19 09:11:05 [crit] 3817#3817: *231 openat() "/home/admin/web/pan1.mail628.com/public_html/js/bootstrap.min.js" failed (13: Permission denied), client: 24.70.$
> 2019/05/19 09:11:05 [error] 3817#3817: *231 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:11:05 [error] 3817#3817: *231 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:11:05 [error] 3817#3817: *231 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:11:05 [error] 3817#3817: *231 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:11:05 [error] 3817#3817: *231 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:11:06 [error] 3817#3817: *231 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$

And this for another domain:

> 2019/05/19 09:14:48 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:48 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/bootstrap.min.css" failed (13: Permission denied), client: 24.70.204.1$
> 2019/05/19 09:14:48 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/all.min.css" failed (13: Permission denied), client: 24.70.204.123, se$
> 2019/05/19 09:14:48 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/animate.css" failed (13: Permission denied), client: 24.70.204.123, se$
> 2019/05/19 09:14:48 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/style.css" failed (13: Permission denied), client: 24.70.204.123, serv$
> 2019/05/19 09:14:48 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/js/bootstrap.min.js" failed (13: Permission denied), client: 24.70.204.123$
> 2019/05/19 09:14:48 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:48 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:48 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:48 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:48 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:50 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/bootstrap.min.css" failed (13: Permission denied), client: 24.70.204.1$
> 2019/05/19 09:14:50 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:50 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/all.min.css" failed (13: Permission denied), client: 24.70.204.123, se$
> 2019/05/19 09:14:50 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/animate.css" failed (13: Permission denied), client: 24.70.204.123, se$
> 2019/05/19 09:14:50 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/css/style.css" failed (13: Permission denied), client: 24.70.204.123, serv$
> 2019/05/19 09:14:50 [crit] 3817#3817: *240 open() "/home/admin/web/mail628.com/public_html/js/bootstrap.min.js" failed (13: Permission denied), client: 24.70.204.123$
> 2019/05/19 09:14:50 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:50 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:50 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:50 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
> 2019/05/19 09:14:50 [error] 3817#3817: *240 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$
>

**Comment by ScIT-Raphael** [comment]
Hmm, that's weird, never seend this error message. Basicly, I would suggest you to reinstall the server using the normal script without upgrading to git version. Then add the domains like you've already yet - if you still facing suhc a issue, then write a mail to info@hestiacp.com with your login credentials. So we would checkout your server, but please change to stable version first.

**Comment by ghost** [comment]
If mail628.com's web domain does not include any content, you could also try deleting and re-adding it instead of wiping out the entire server although I do believe there may be an underlying configuration file issue here. Upgrading via Git should be used for development and testing purposes, and any production-level servers (while not yet officially supported for use by Hestia given it's active development state) should remain on the package repository upgrade path.

**Comment by Lupul** [comment]
I can reproduce the last problem with the error log
```SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking t$```

A fix will be available soon.

**Comment by ScIT-Raphael** [comment]
Will close the issue due to the fix in reverenced commit above, thanks @lupul!

**Comment by killer30001000** [comment]
I have the same issue, but on stable version, where can I apply the fix above?

**Comment by ScIT-Raphael** [comment]
What exactly is your issue, SSL_do_handshake() or the let's encrypt 400?

**Comment by killer30001000** [comment]
In my domain error log I got this line
`[error] 22098#22098: *7624 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 85.215.2.229, server: domain.tld, request: "GET / HTTP/1.1", upstream: "https://ip-adress:8080/", host: "domain.tld"`
But I get the let's encrypt 400 error as well on ssl cert renewal and on adding certs to a new domain

**Comment by ScIT-Raphael** [comment]
The SSL_do_handshake error is different and not related. Mostly, the 400 let's encrypt error arrives on missing dns records OR invalid e-mail address in the hestia user account.

Please check if all domains, that should get let's encrypt, have proper A records and NO AAAA (ipv6) records.

**Comment by killer30001000** [comment]
The dns record are all correct and the e-mail address in the hestia user account is correct as well (we receive the error message on failed renewal)

I removed the the AAAA record from one domain, now I get error 429 (too many requests) but the other two domains don't have any AAAA record and their A record is correct.

**Comment by ScIT-Raphael** [comment]
Hmm, sounds weird. 429 -> https://community.letsencrypt.org/t/tell-me-return-code-429/30171

If you want, you can share your server credentials (ssh and hestia admin) with us on info@hestiacp.com, I will take a look asap.

**Comment by hanzicode** [comment]
Maybe what I saw yesterday on a production server could help you pin down the issue (maybe you have already found out the problem).

I added a subdomain on that server but since the default "Site under Construction" page looked ugly (appeared not to have any styling, even the yellow construction hat was not shown), so I did deeper. Turned out the three folders css, js, and webfonts in public_html are all empty. Although they all have the admin:admin ownership settings, I could not upload files into them or remove these three dolder via SFTP as admin login. I had to login SSH as root to remove these folders using the -r forced option and then was able to upload the folders and files.

The LetsEnscrypt issuing and usage worked OK for this sudomain without any problem. Note that I am using the master stable branch for this production server.

Hope this helps.

**Comment by killer30001000** [comment]
@ScIT-Raphael unfortunately we cannot give you access to our server because of sensitive data. I will try to search for a solution by myself on the weekend and will update you, if I find something.

@hanzicode the permission problem was already fixed by this issue #225

**Comment by hanzicode** [comment]
@cr1s3c Thank you for pointing me to #225 

I have made the changes to bin/v-add-web-domain and I know that I only run it when I need it. But as for the changed install/upgrade/0.9.8-28.sh script, do I run it from the command line as root or I can commit the change from within HestiaCP?

Sorry, as this is a production server, I do not want to take the risk of not doing things properly.

**Comment by killer30001000** [comment]
@hanzicode we fixed it on a production server as well, we applied all the changes but never ran the 0.9.8-28.sh Script again.
The v-add-web-domain script already adds the correct permissions to the domain directory of new users, so that the user can edit the files via ftp.
You can simply run the green part of the v-add-web-domain manually for all the existing users, but you need to replace $HOMEDIR and $user with the correct paths.

**Comment by ghost** [comment]
@hanzicode, please save the below as a Bash shell script and run it on your server, this should fix the permissions issues in the 0.9.8-28 release. We should have a new release prepared and posted to our package repositories by the end of next week; if you are using Hestia on a production server I would recommend waiting to upgrade until the release is made official just to stay on the safe side.

```
#!/bin/bash
source $HESTIA/func/main.sh

for user in `ls $HESTIA/data/users/`; do
    chmod 751 $HOMEDIR/$user/web/*/public*_html/css
    chmod 751 $HOMEDIR/$user/web/*/public*_html/js
    chmod 751 $HOMEDIR/$user/web/*/public*_html/webfonts
    chmod 751 $HOMEDIR/$user/web/*/document_errors/css
    chmod 751 $HOMEDIR/$user/web/*/document_errors/js
    chmod 751 $HOMEDIR/$user/web/*/document_errors/webfonts
done
```

You can safely ignore any errors that appear for domains that do not have the default content set in place.

**Comment by hanzicode** [comment]
@kristankenney That worked, thank you!

However today I was testing the master stable version on a Hostwinds server and got the 400 error again. The error log shows this for the hostname domain after I tried to run `v-add-letsencrypt-domain 'admin' $HOSTNAME '' 'yes'`:

> [Thu May 23 22:50:18.482760 2019] [core:crit] [pid 27806] (13)Permission denied: [client 24.70.204.123:53962] AH00529: /home/admin/web/pan2.mail628.com/public_html/c$
> [Thu May 23 22:50:18.528525 2019] [core:crit] [pid 27805] (13)Permission denied: [client 24.70.204.123:53964] AH00529: /home/admin/web/pan2.mail628.com/public_html/c$
> [Thu May 23 22:50:18.528977 2019] [core:crit] [pid 27800] (13)Permission denied: [client 24.70.204.123:53966] AH00529: /home/admin/web/pan2.mail628.com/public_html/c$
> [Thu May 23 22:50:18.529280 2019] [core:crit] [pid 27801] (13)Permission denied: [client 24.70.204.123:53968] AH00529: /home/admin/web/pan2.mail628.com/public_html/c$
> [Thu May 23 22:50:18.529563 2019] [core:crit] [pid 27802] (13)Permission denied: [client 24.70.204.123:53970] AH00529: /home/admin/web/pan2.mail628.com/public_html/j$

Note that pan2.mail628.com has resolved to the new server's IP.

It looks like the issue what Lupul mentioned above but I do not how to implement his fix as I cannot find where this file install/deb/apache2/unassigned.conf is located - I am uisng Debian 9 on the server.

**Comment by ghost** [comment]
@hanzicode The file location paths have changed considerably with much of the duplicates having been consolidated, which is why @Lupul's fix won't work on master at this time -- if you can hang tight until next week we'll have a new set of packages available as the develop branch is nearing completion, which should take care of a lot of issues from 0.9.8-28.

**Comment by hanzicode** [comment]
OK, I will wait then :-)

BTW, I have made a video on how to install the master stable version. Here is the YouTube link: https://www.youtube.com/watch?v=n--zbgq30-E

**Comment by hanzicode** [comment]
@kristankenney New update available?

**Comment by ghost** [comment]
Still working out the last few bugs, we've had a couple of showstoppers but aiming for the end of this week if all goes well.

**Comment by hanzicode** [comment]
The 400 error came back after recent upgrade to 1.00.0 (amd64)190618

**Comment by ScIT-Raphael** [comment]
On creating new certs or renew?

**Comment by ScIT-Raphael** [comment]
I just checked on a fresh installed system, generation of let's encrypt domains works properly without any error message. Can you share more informations?

**Comment by hanzicode** [comment]
On creating new certs.

This happens on the production server for which I had sent login credentials for another problem with mail.

**Comment by ScIT-Raphael** [comment]
I tested yesterday morning all systems on master branch (default installation with hst-install.sh script). SSL generation worked on all of them, so I think it have to be a validation issue, probaly invalid email address or closed ports. If it is still persistent on default installation way, please create a bew issue with all possible details.

**Comment by torsten-online** [comment]
I had the same issue by using HestiaCP with *.dev *.blog TLDs, which are enforcing SSL by Google.

So, I finally build up a just a quick hack solution with a python script, so that HestiaCP can support SSL&DNS01 Challenges over Cloudflare.

If anyone is interesting - here is my solution for that as gist on github:

https://gist.github.com/torsten-online/926b5baab451b805458e76f9a772a6ca

Please note: ITs working - if there is any issue - your feedback is welcome!
