### ISSUE TITLE
[Bug] WordPress installer missing

### ISSUE THREAD

**Issue by t3rr0rz0n3** [hestiacp/hestiacp#3131]
### Describe the bug

In the "Quick Install App" section, the Wordpress option does not work, the following error appears "WordPress installer missing".

### Tell us how to replicate the bug

1. Add domain
2. Click the button "Quick Install App".
3. Click on "Setup"

![imatge](https://user-images.githubusercontent.com/7691406/206693533-0fc91675-4fbf-4ebb-83ec-c5b826c7fbaa.png)

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.6.13

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3129

**Comment by jaapmarcus** [comment]
When the packages for php8.2-imagick has been build we release the patch
