### ISSUE TITLE
[Bug] Apache2 + Nginx services does not started after restore from UPS to regular grid power

### ISSUE THREAD

**Issue by Scan4u** [hestiacp/hestiacp#3134]
### Describe the bug

Hi! 
I live in Ukraine and now we have a lot of problems with electricity because of russian missile attacks and their active actions to occupy my country. Here is a stats from UptimeRobot where U can understand the deep of our blackouts issue:

![зображення](https://user-images.githubusercontent.com/16424225/206760309-a249d14d-a24d-4419-bf2e-c63146af9352.png)

I connected the server running Hestia to an uninterruptible power supply - APC UPS. With each new blackout, the UPS shuts down the server and automatically turns it back on after the power supply is restored.
However, there is one problem - the server that is directly connected to the network boots up faster than it receives a white IP address from the ISP provider - sometimes the external ip can be received in between 3 .... 15 minutes after the full Hestia server boot.
Due to this delay with ip, the Hestia server do not start the Apache2 and Nginx services:

![зображення](https://user-images.githubusercontent.com/16424225/206761431-b99d6066-c0a7-4e19-b992-dffaeca77d9b.png)

![зображення](https://user-images.githubusercontent.com/16424225/206761362-598cd5a9-1673-44fd-8373-fd70995ce270.png)

Here is the systemctl status for mentioned services:

![зображення](https://user-images.githubusercontent.com/16424225/206761531-8d8c4593-2828-424a-a3f1-bbd88498d9c3.png)
![зображення](https://user-images.githubusercontent.com/16424225/206761556-ad9427e6-9499-4cc4-bde5-779b7c1e1a9d.png)

In case of unsuccessful start of the mentioned services, access to all websites is lost. After manually restarting the Apache2 and Nginx services from Hestia panel, everything start to works again.

Is there a chance to get the solution for this issue - add some kind of ip Watchdog? 

### Tell us how to replicate the bug

-

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.13

### Operating system

Ubuntu 20.04 (x86_64)

### Log capture

```shell
-
```

**Comment by jaapmarcus** [comment]
Not an Hestia issue..

https://docs.hestiacp.com/admin_docs/settings.html#unable-to-bind-adress#504

**Comment by jlguerrerosanz** [comment]
Use a cron to run this:
/usr/local/hestia/bin/v-list-sys-services | grep stopped |  cut -d" " -f1 | xargs -I {}

Tested and working in my system for months

**Comment by Scan4u** [comment]
Thank U for your nice tip! Will try it asap!

Yesterday I started to use a different small script in Cron - and it also seems to working nice:

sudo
ps ax | grep apache2 | grep -v grep -q || /etc/init.d/apache2 restart > /dev/null
reply=`curl -s -L --head -w "%{http_code}\n" https://www.hestia.tld | tail -n1`
if [ $reply -ne "200" ]
then
echo "`date +%d-%m-%Y`  `date +%H:%M:%S%t` Server is offline!" >> /var/log/watchdog.log
/etc/init.d/apache2 restart
/etc/init.d/nginx restart
fi
exit 0

It would be nice to have the default watchdog in the Hestia panel - that was the main reason of my topic.

**Comment by jaapmarcus** [comment]
Run:
sysctl -w net.ipv4.ip_nonlocal_bind=1

Onece and nginx / apache2 will always start even if the ip is not available

**Comment by Scan4u** [comment]
> Use a cron to run this: /usr/local/hestia/bin/v-list-sys-services | grep stopped | cut -d" " -f1 | xargs -I {}
> 
> Tested and working in my system for months

Just had another 6 hours blackout, - and the perfect moment to test your script. 
Unfortunately, the script above won't start the Apache2 + Nginx services in my case.
Here is how it is look in the Cron of my Hestia panel:
![зображення](https://user-images.githubusercontent.com/16424225/206874225-a2069b49-25bc-4f0c-8a87-4eda76f2a03c.png)

Please explain, what i'm doing wrong?

**Comment by ScIT-Raphael** [comment]
sudo missing or place it as root. probaly the idea of @jaapmarcus is better.

**Comment by Scan4u** [comment]
> Run: sysctl -w net.ipv4.ip_nonlocal_bind=1
> 
> Onece and nginx / apache2 will always start even if the ip is not available

Successfully run this command once before blackout. 
After the blackout restart of the Ubuntu - got the Apache2 + Nginx stopped :( SO, also not work in my case..

**Comment by Scan4u** [comment]
> sudo missing or place it as root. probaly the idea of @jaapmarcus is better.

Will try with sudo ASAP and let U know the result.
*** A few moments later ***
Even with sudo - no result..
![зображення](https://user-images.githubusercontent.com/16424225/206874648-62c05d1f-a8e1-41f5-820b-c5366e964d4b.png)
![зображення](https://user-images.githubusercontent.com/16424225/206874652-b286805e-550a-40e2-b434-df553c903241.png)
Will back to my script :)

**Comment by jaapmarcus** [comment]
crontab -e as root 

systemctl restart can't be use by admin user

**Comment by Scan4u** [comment]
> crontab -e as root
> 
> systemctl restart can't be use by admin user

I'm totally messed up :) Please explain, what do I need to type after crontab -e in the window below:
![зображення](https://user-images.githubusercontent.com/16424225/206875007-26a32815-3b71-4e71-a74f-ed8b816dfd02.png)

**Comment by Pleskan** [comment]
`/usr/local/hestia/bin/v-list-sys-services | grep stopped | cut -d" " -f1 | xargs -I {}`
you should paste it there in your root's cron tasks. Spot the difference, no sudo at the beginning.

**Comment by Scan4u** [comment]
Just like that? Is it correct? 
Or do I need to add the schedule expression at the beginning of mentioned command?
![зображення](https://user-images.githubusercontent.com/16424225/206875566-043000f8-d17e-4aab-897e-d39bfcefb142.png)

**Comment by jaapmarcus** [comment]
Yes 
Probally every minute...

**Comment by Pleskan** [comment]
@Scan4u , yep, you have to add scheduling before the command and... you can ping me on Telegram (@Twissel87) where we can communicate natively... and figure out what is is the difference between blackout and outgages :-)
