### ISSUE TITLE
[Bug] tz file 423 doesn't exist

### ISSUE THREAD

**Issue by justanthonylee** [hestiacp/hestiacp#3137]
### Describe the bug

When making some changes in config on a brand new install that just was done today receiving the message Error: tz file 423 doesn't exist.

So far it looks like local settings changes that are making the error happen for example setting a theme for all users or turning off local backups.

### Tell us how to replicate the bug

Install current version: v1.6.13
Go to Settings: Configure -> Basic Options
Select option: Set as selected theme for all users

<img width="666" alt="Screenshot 2022-12-10 at 11 33 38 AM" src="https://user-images.githubusercontent.com/5204371/206872394-15919a83-0019-4b75-9a76-a9a1aa4d1690.png">

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Web Interface

### Hestia Control Panel Version

1.6.13

### Operating system

Ubuntu 22.04 (x86_64)

**Comment by wojsmol** [comment]
This is most likely a duplicate of https://github.com/hestiacp/hestiacp/issues/3127.

**Comment by ScIT-Raphael** [comment]
indeed it is...

**Comment by justanthonylee** [comment]
Sorry, I was not able to find the other report when searching. 👍
