### ISSUE TITLE
[Bug] official hestiacp demo not working 

### ISSUE THREAD

**Issue by radwanhallak** [hestiacp/hestiacp#3138]
### Describe the bug

i try to follow the demo hestiacp, located on the official website, to see the last performance of cp before depending on.
but it is not working [https://demo.hestiacp.com:8083/](https://demo.hestiacp.com:8083/)
thank you..

### Tell us how to replicate the bug

1- go to https://www.hestiacp.com/
2- choose (demo from the menu)

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.6.13

### Operating system

ubuntu 22.04

### Log capture

```shell
https://demo.hestiacp.com:8083/
```

**Comment by jaapmarcus** [comment]
Updated the server + requested a new SSL

**Comment by radwanhallak** [comment]
The demo still not working, why?

**Comment by jaapmarcus** [comment]
Have no idea it works here...

**Comment by jaapmarcus** [comment]
<img width="1057" alt="Screenshot 2022-12-22 at 07 52 48" src="https://user-images.githubusercontent.com/9754650/209075219-58b665f1-f554-4054-8748-6e2eeedc4916.png">

**Comment by radwanhallak** [comment]
it works using a VPN, but why? is I am blocked? 
![image](https://user-images.githubusercontent.com/7591337/209251506-133d4af6-a802-46da-b7f0-79cc9ee95aa3.png)

**Comment by ScIT-Raphael** [comment]
No idea, this is out of the hestiacp range.
