### ISSUE TITLE
[Feature] Add domain/URL redirection to HestiaCP

### ISSUE THREAD

**Issue by mnnobi** [hestiacp/hestiacp#3139]
### Describe the feature or change in detail

Please add the URL redirection feature to HestiaCP as it is necessary in most cases.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
<img width="498" alt="Screenshot 2022-12-11 at 16 09 33" src="https://user-images.githubusercontent.com/9754650/206911608-a922146b-ab64-43a2-875d-e53ab6581472.png">

Please explain what is missing?

Add domain and then edit the domain and you should be able to select / redirect the domain

**Comment by mnnobi** [comment]
I meant when a visitor visits a specific path of a website, it redirects to a new URL. Like this- 
![image](https://user-images.githubusercontent.com/120206757/206913372-9227cf4c-5f0f-42e2-9d1f-6a4e63c29ef1.png)

**Comment by ScIT-Raphael** [comment]
This is not realy in focus of hestia, you can solve this on your own using .htaccess, php or nginx redirects.

**Comment by ScIT-Raphael** [comment]
This is not realy in focus of hestia, you can solve this on your own using .htaccess, php or nginx redirects.
