### ISSUE TITLE
[Bug] v-update-sys-hestia bug 

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#3140]
### Describe the bug

There is a logical flaw in the `v-update-sys-hestia` command, whatever you pass to the arg1, it will automatically make it `hestia-php`. 

<img width="846" alt="CleanShot 2022-12-10 at 22 41 57@2x" src="https://user-images.githubusercontent.com/1262327/206916245-cb40322c-e67d-4c3f-9375-edff8134662a.png">

### Tell us how to replicate the bug

I have put an exit after the for loop the echoed `package` variable and I get this. 

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.6.10

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
apt update && apt upgrade 

And is should be fixed. 

See https://github.com/hestiacp/hestiacp/blob/1.6.14/CHANGELOG.md#important
