### ISSUE TITLE
Please add webdav support to remote backup

### ISSUE THREAD

**Issue by viratsoft** [hestiacp/hestiacp#3165]
### Describe the feature or change in detail

hi, 
  please add webdav support to remote backup.

thank you,

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
1.7.0 brings support for RCLONE that comes with Webdav support 

So this is all ready implemented

**Comment by jaapmarcus** [comment]
https://rclone.org/overview/
