### ISSUE TITLE
[Bug/Improvement] Adjust error message for v-add-remote-dns-host when api access is missing

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#3169]
### Describe the bug

Currently v-add-remote-dns-host just returns the following error, if the ip of the webserver isnt in the dns servers whitelist:

```
/usr/local/hestia/func/remote.sh: line 50: return: Error:: numeric argument required
Error: api connection to x.x.x.x failed
```

We should probaly improve it and throw out a fitting error.

### Tell us how to replicate the bug

Use v-add-remote-dns-host while not having the ip on whitelist.

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.0~alpha

### Operating system

Ubuntu 22.04 LTS

**Comment by jaapmarcus** [comment]
Fixed
