### ISSUE TITLE
[Bug] Backups not conclued

### ISSUE THREAD

**Issue by schneiderbruno** [hestiacp/hestiacp#3170]
### Describe the bug

Hello everybody

I always used the hestia backup and it worked very well, sending the generated backup via external FTP.

But yesterday the backup was not generated. Today I've tried 3x to manually generate the backup, it says it was sent to the queue but it doesn't generate the backup.

I updated hestiacp to the latest version, but it didn't fix the problem.

It seems to me that there is a bug in the backup routine.

### Tell us how to replicate the bug

1. Click "backup".
2. Click "Create backup"

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.6.14

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
Please check your system logs, it looks like something is stuck. There is no nug in the backup routine.

**Comment by jaapmarcus** [comment]
Try running v-backup-user user via ssh

**Comment by schneiderbruno** [comment]
> Please check your system logs, it looks like something is stuck. There is no nug in the backup routine.

Please, how do i do it?

**Comment by schneiderbruno** [comment]
Error: not enough disk space available (10778 mb) to perform the backup  of admin. ( 6213 mb * 2 = 124                                  26 mb).

Thanks @jaapmarcus and @ScIT-Raphael 
Your work is exemplary!
