### ISSUE TITLE
[Feature] Ability to deinstall Apps from CP

### ISSUE THREAD

**Issue by fisa4** [hestiacp/hestiacp#3174]
### Describe the feature or change in detail

It would be nice to have the ability to uninstall installed apps from the control panel. Completely including deleting the corresponding database and so on. 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We don't store the database used in any location except any config files. So that would require to write each plugin a specific thing. 

I don't know if it is the investment worth...

**Comment by fisa4** [comment]
OK, I didn't know that. Thanks for this information.
