### ISSUE TITLE
[Bug] Can't edit php.ini from HestiaCP Web GUI

### ISSUE THREAD

**Issue by gcasasi** [hestiacp/hestiacp#3175]
### Describe the bug

Today I tried to uninstall php 7.4 but I received an error that says that I need to do manually with the command below:

`apt-get purge php7.4-common php7.4-mbstring php7.4-bcmath php7.4-cli php7.4-curl php7.4-fpm php7.4-gd php7.4-intl php7.4-mysql php7.4-soap php7.4-xml php7.4-zip php7.4-mbstring php7.4-json php7.4-bz2 php7.4-pspell php7.4-imagick php7.4-pgsql php7.4-imap php7.4-ldap`

After that, I restart the server and check that only have php8.2 installed. 
The problem is that I can't edit configuration from HestiaCP Web GUI, I get a new error:

**_Error: php-fpm failed to start with new configuration._**

![image](https://user-images.githubusercontent.com/74934262/209889651-508ddb05-b61d-460f-823d-5b094e2315d3.png)

I can restart the service with no problems, so I tried to edit manually from SSH, below you can see the file permissions.

`#:/etc/php/8.2/fpm# ll
total 176
drwxr-xr-x 4 root root  4096 Dec 29 01:05 ./
drwxr-xr-x 5 root root  4096 Dec 19 22:46 ../
drwxr-xr-x 2 root root  4096 Dec 19 22:46 conf.d/
-rw-r--r-- 1 root root  5460 Dec 19 22:47 php-fpm.conf
-rw-r--r-- 1 root root 73118 Dec 29 01:05 php.ini 
drwxr-xr-x 2 root root  4096 Dec 29 00:49 pool.d/`

After this, if I restart the service I see the changes applied

### Tell us how to replicate the bug

1. Click on Configuration
2. Edit php
3. Try to change value (max_execution_time)
4. Save

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.14

### Operating system

Ubuntu 20.04 (x86_64)

### Log capture

```shell
==> /var/log/hestia/error.log <==
2022-12-29 01:04:18 v-restart-service  'php-fpm' [Error 20]
2022-12-29 01:04:18 v-change-sys-service-config  '/tmp/tmp.PjlThg62zC' 'php' 'yes' [Error 20]
```

**Comment by jaapmarcus** [comment]
systemctl restart php8.2-fpm

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/2297

Duplicate

**Comment by gcasasi** [comment]
Hi @jaapmarcus , thanks for your quick response, but I think that this isn't the solution, the service restarts correctly from the GUI and from SSH, the problem is when I try to editing the configuration, I only use one version of php-fpm, 

![image](https://user-images.githubusercontent.com/74934262/209915082-77898010-f34a-47f1-b0fd-b2963c47de54.png)

If I try to edit 2 or 3 times configuration from GUI, it's possible that configuration is cleared, file "/etc/php/8.2/fpm/php.ini" goes to 0 bytes and I need to create again.

**Comment by jaapmarcus** [comment]
I wonder if it partially caused by the fact the uninstall of php7.4 didn't work. 

https://github.com/hestiacp/hestiacp/blob/559aece5dc0012c765bf8f334fd649a39056593d/bin/v-change-sys-service-config#L53

We really should rewrite the part how it is handled...

**Comment by gcasasi** [comment]
**Solved!!**, Thanks for your help, finally I deleted old php folder (7.4) under (/etc/php). Now works fine

`

root:/etc/php# find /etc/php* -name php.ini
/etc/php/8.2/fpm/php.ini
/etc/php/8.2/cli/php.ini 
/etc/php/7.4/phpdbg/php.ini
/etc/php/7.4/fpm/php.ini
/etc/php/7.4/cli/php.ini
root:/etc/php# ll


root:/etc/php# ll
drwxr-xr-x   5 root root  4096 Dec 29 00:50 ./
drwxr-xr-x 123 root root 12288 Dec 29 00:14 ../
drwxr-xr-x   6 root root  4096 Dec 29 12:17 7.4/
drwxr-xr-x   5 root root  4096 Dec 19 22:46 8.2/

root:/etc/php# rm 7.4/ -rf
`
