### ISSUE TITLE
[Bug] v-backup-user

### ISSUE THREAD

**Issue by satsis** [hestiacp/hestiacp#3176]
### Describe the bug

/usr/local/hestia/bin/v-backup-user admin
and not send email

### Tell us how to replicate the bug

not send email

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.5.12

### Operating system

Ubuntu 20

### Log capture

```shell
sftp> exit
Disconnected.
2022-12-29 13:35:17 Size: 3 MB
2022-12-29 13:35:17 Runtime: 1 minute
sed: -e expression #1, char 3: unknown command: `
'
sed: -e expression #1, char 3: unknown command: `
'
```

**Comment by jaapmarcus** [comment]
I assume somewhere arround here:
https://github.com/hestiacp/hestiacp/blob/b0356cb2fa8e7de833342d0a7165e223a8a9399e/bin/v-backup-user#L750-L774

But if notify is not set in your example by default no email is send.

**Comment by satsis** [comment]
> 

Notification enabled.
But it doesn't send mail.
Test email from the console reach.

I made telegram notification - its work
OUTPUT=$(cat $BACKUP/$user.log)
telegram-send "$OUTPUT"

but on email not (

**Comment by ScIT-Raphael** [comment]
Please upgrade first to latest version.

**Comment by satsis** [comment]
> Please upgrade first to latest version.

I received the file /usr/local/hestia/bin/v-backup-user today from github

**Comment by ScIT-Raphael** [comment]
We cant provide support for it, either you update to the latest version or we have to close the issue. It may be another bug already fixed a lot of time ago.

**Comment by jaapmarcus** [comment]
Upgrade the panel to 1.6.14. There have been a lot other changes made ...

**Comment by jaapmarcus** [comment]
Also manually triggering v-backup-user admin will also not result in sending a email

https://github.com/hestiacp/hestiacp/blob/b0356cb2fa8e7de833342d0a7165e223a8a9399e/bin/v-backup-user#L780-L785

**Comment by satsis** [comment]
> Upgrade the panel to 1.6.14. There have been a lot other changes made ...

I received the file /usr/local/hestia/bin/v-backup-user today from github

> nt provide support for it, either you update to the latest version or we have to close the issue. It may be another bug already fixed a lot of time ago.

The panel does not offer me updates. The settings are set to auto-update.

> Also manually triggering v-backup-user admin will also not result in sending a email

VestaCP sends mail without problems. Why is there no email?

**Comment by jaapmarcus** [comment]
> > Upgrade the panel to 1.6.14. There have been a lot other changes made ...
> 
> I received the file /usr/local/hestia/bin/v-backup-user today from github
> 
> > nt provide support for it, either you update to the latest version or we have to close the issue. It may be another bug already fixed a lot of time ago.
> 
> The panel does not offer me updates. The settings are set to auto-update.
> 

Run apt update && apt upgrade 

> > Also manually triggering v-backup-user admin will also not result in sending a email
> 
> VestaCP sends mail without problems. Why is there no email?

Run v-backup-user admin yes

And it should send an email

**Comment by satsis** [comment]
Update 1.6.14 (amd64)

/usr/local/hestia/bin/v-backup-user admin yes

```
sed: -e expression #1, char 3: unknown command: `
'
sed: -e expression #1, char 3: unknown command: `
'
```

email not send 

echo "Это тестовое письмо" | mail -s "Проверка отправки почты" max@mail.ru - this work

**Comment by jaapmarcus** [comment]
Mails are send with 

email=$(get_user_value '$CONTACT')
	cat $BACKUP/$user.log | $SENDMAIL -s "$subj" "$email" "$notify"

where $SENDMAIL is defined as
https://github.com/hestiacp/hestiacp/blob/559aece5dc0012c765bf8f334fd649a39056593d/func/main.sh#L25

First try to discover why the sed errors are coming from I am not able to replicate the issue on my test server...

**Comment by satsis** [comment]
> First try to discover why the sed errors are coming from I am not able to replicate the issue on my test server...

I updated the panel, as insisted on in this thread. The problem didn't go away.
email also did not start to send. The developers apparently had the task of closing the problem, not solving it.

**Comment by jaapmarcus** [comment]
I still want to resolve the issue but I need to know what fails before writing a patch.  

If you are not willing to debug things why not remove Hestia and go back to Vesta or Cpanel... 

I own multiple servers running Hestia and have never seen this issue before and due to the error message it is extremely hard to debug with out root access to the server.  Or at least more information ...

**Comment by satsis** [comment]
> I still want to resolve the issue but I need to know what fails before writing a patch.

I want to solve the problem.
Tell me what do I need to do?
I updated Hestia to the latest version

I run this /usr/local/hestia/bin/v-backup-user admin yes from root and still getting error
And I still don't get emails.

`cat /backup/admin.log |/usr/local/hestia/web/inc/mail-wrapper.php -s admin → backup has been completed max@mail.ru yes`

**Comment by jaapmarcus** [comment]
For email not able to receive you probally need to setup:
https://github.com/hestiacp/hestiacp/blob/main/install/upgrade/manual/configure-server-smtp.sh

For the sed errors add some ```echo "test"``` to the code that I posted before with the sed so we are able to find what lines are causing the issue.
