### ISSUE TITLE
When backups are unlimited, when creating a backup Error: user backup is disabled [Bug] 

### ISSUE THREAD

**Issue by skorpions2000** [hestiacp/hestiacp#3179]
### Describe the bug

When backups are unlimited, when creating a backup Error: user backup is disabled
![изображение](https://user-images.githubusercontent.com/11683786/210224442-a5535f9c-c329-4537-9699-aefdfa06bd86.png)
![изображение](https://user-images.githubusercontent.com/11683786/210224753-14c416e2-2991-4cf7-ba9b-fd950363b68b.png)

### Tell us how to replicate the bug

1. Set unlimited backups in the package settings. 
![изображение](https://user-images.githubusercontent.com/11683786/210224641-d57cf24e-788f-4cd6-a14c-f6cd51721ba2.png)
![изображение](https://user-images.githubusercontent.com/11683786/210224734-ac322c5d-52da-4eed-9782-9a5db83fb63f.png)
2. Create a new backup for the user

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
We should enforce a limit so it is at least one. Allowing for Unlimited backups don't make sense

**Comment by ScIT-Raphael** [comment]
fixed with https://github.com/hestiacp/hestiacp/pull/3181
