### ISSUE TITLE
[Feature] Automatically generate username

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3184]
### Describe the feature or change in detail

I would like to have a common username scheme, which is just the lowercased first name by default.
This would be much easier if it could be automatically done - maybe one can enter a regex transformation on the name.

This would entail:
- moving the "Name" (which in German is translated as "Kontakt", a curious diversion) field above the "Username", so people fill it out first
- auto-populating the username field according to the pattern - but it should stay editable

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Questions are then:

- What regex need to be applied I think a lot of users have different ideas for it.  And make it changeable it probally not worth  the effort. Also usernames are limited `(a-zA-Z)[(a-zA-Z0-9){30}](a-zA-Z)`

For the x users that only create one or 2 accounts who cares...

If you create more users. I suggest automating it via a billing system....

If there are more users who want it maybe we can consider it but for 1 user I don't see the need for it...
