### ISSUE TITLE
[Bug] Obsolete Web Files?

### ISSUE THREAD

**Issue by codejp3** [hestiacp/hestiacp#3186]
### Describe the bug

I'm just playing around with the web interface right now to get some familiarity for [a possible pull-request](https://github.com/hestiacp/hestiacp/issues/1616#issuecomment-1371623703) in the near future, and I'm noticing inconsistency between the current web files in the repo for the latest version, and the web files on my system (also the latest version - 1.6.14)

Example:
Repo file for [hestiacp](https://github.com/codejp3/hestiacp)/[web](https://github.com/codejp3/hestiacp/tree/experimental/web)/[add](https://github.com/codejp3/hestiacp/tree/experimental/web/add)/[package](https://github.com/codejp3/hestiacp/tree/experimental/web/add/package)/index.php

Starts with:
```
<?php
use function Hestiacp\quoteshellarg\quoteshellarg;

ob_start();
$TAB = "PACKAGE";
```

But my local system `/usr/local/hestia/web/add/package/index.php` file Starts with:
```
<?php

ob_start();
$TAB = 'PACKAGE';
```

Every "web" file I've checked is different on my local system than what's in the repo:
web/add/package/index.php
web/copy/package/index.php
web/delete/package/index.php
web/edit/package/index.php

^^^ all fail with 500 server error if I try to use those in my current install. eg:
`Call to undefined function Hestiacp\quoteshellarg\quoteshellarg() in /usr/local/hestia/web/edit/package/index.php:29`

Besides the quoteshellarg change, the **templates are also different**. My local system has template files that still use table / tr / td tags for displaying fields, but the repo has newer files using (cleaner) div tags for displaying fields.

- `v-update-sys-hestia-all` does not update any of those web files.
- `apt-get update && apt-get dist-upgrade` does not update any of those web files.
- Replacing the current system `/usr/local/hestia/web/` directory with the one from the repo produces 500 server errors (undefined functions).

Something's not right with updating the system admin web interface files.

This install is several years old, updating regularly along the way...but apparently not all files are being updated.

### Tell us how to replicate the bug

Compare any older local `/usr/local/hestia/web/` file with one in the repo that's been updated recently and they won't match.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.14

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Main branch is the new 1.7.0 and hasn't been released yet. 

You are currently on the release branch that is the official last version

**Comment by codejp3** [comment]
Confusion comes in because the [readme.md file still shows the main branch as 1.6.14](https://github.com/hestiacp/hestiacp/blob/main/README.md) and there's a [separate beta/1.7.0 branch](https://github.com/hestiacp/hestiacp/tree/beta/1.7.0) which is a few commits ahead of main.

There's quite a bit different between the main branch and my local system - particularly the composer file that includes the new `quoteshellarg` function and the accompanying `v-add-sys-dependencies` command to include them, related to the issue I raised here.

I'd like to test out 1.7 beta to confirm this, and to plan future commits for the next release.

https://beta.hestiacp.com seems to defunct. What's a good source to put in my etc/apt/sources.list.d/hestia.list file ?

`deb [arch=amd64 signed-by=/usr/share/keyrings/hestia-beta-keyring.gpg] https://beta.hestiacp.com/ bullseye main`

`W: Failed to fetch https://beta.hestiacp.com/dists/bullseye/InRelease  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification.`

**Comment by ScIT-Raphael** [comment]
have a look here: https://github.com/hestiacp/hestiacp/blob/main/CONTRIBUTING.md

**Comment by jaapmarcus** [comment]
With the 1.6.0 release I have deleted the beta.hestiacp.com as it was not nessesarry any more.  We have replaced it with beta-apt.hestiacp.com as it will allow us to use beta-rpm.hestiacp.com for the rpm builds.. 

> Confusion comes in because the [readme.md file still shows the main branch as 1.6.14](https://github.com/hestiacp/hestiacp/blob/main/README.md) and there's a [separate beta/1.7.0 branch](https://github.com/hestiacp/hestiacp/tree/beta/1.7.0) which is a few commits ahead of main.

It states and the link refers of the change log to the release branch changelog:
```
Latest stable release: Version 1.6.14 | https://github.com/hestiacp/hestiacp/blob/release/CHANGELOG.md
```

We always set the current version of the branch in: https://github.com/hestiacp/hestiacp/blob/559aece5dc0012c765bf8f334fd649a39056593d/src/deb/hestia/control#L4 
And the hst-install-{os}.sh files in the /install/ folder 

With the 1.7.0 release a version is also include in package.json

Current branch structure is more ore less

- "main" / Development branch
- "beta/xxxx" contains the last beta branch forked from main branch  it is currently quite behind the main branch. The only reason why it has 2 commits ahead is due to the naming of our package we build:  https://github.com/hestiacp/hestiacp/compare/main...beta/1.7.0
- "Release" branch currently in sync with apt.hestiacp.com 
- "Release/xxx" older release branches commonly the last active release to the release branch before changing  Minor version

Then the are some staging branches when we get closer to a release.  And a few "feature/bug fix branches" 

Any changes you make should be against the 1.70 / main branch. If needed we will cherry pick the commits from main and merge it into the release branch. (Via staging/1.6.x branch first)

**Comment by codejp3** [comment]
Thank you both @jaapmarcus & @ScIT-Raphael  for the details.

Decided to setup a new container just for Hestia Beta testing instead of upgrading my current web dev server.

I've run into several issues trying to get BETA installed right from the start. 

First issue is that I cannot get the installer script to acknowledge the pre-compiled deb. The welcome/confirmation screen kept specifying that 1.6.14 was going to be installed even with including the deb directory -D install argument.

Second issue is several dirs/files are not included in main/beta, so getting a bunch of install "not found" errors:
```rm: cannot remove '/var/log/hestia': Is a directory
cp: cannot stat '/usr/local/hestia/install/deb/packages': No such file or directory
sed: can't read /usr/local/hestia/data/packages/*.pkg: No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/unassigned/index.html': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/skel/document_errors/*': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/firewall': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/api': No such file or directory
...
Error: package system doesn't exist
Error: can't create admin user
```

Seems installing the release branch and then upgrading afterwards is going to be the smoothest approach right now.  I'll mess it with it more tomorrow, but I'm done for the day.

**Comment by jaapmarcus** [comment]
I suggest follow the steps found here:

https://development.hestiacp.com/docs/contributing/development.html#creating-a-virtual-machine-for-development

If you don't use multipass  follow the steps
https://development.hestiacp.com/docs/contributing/development.html#installing-hestia-from-a-branch

git clone https://github.com/hestiacp/hestiacp.git can be also any fork  and branch can be selected with git checkout

**Comment by codejp3** [comment]
> If you don't use multipass follow the steps https://development.hestiacp.com/docs/contributing/development.html#installing-hestia-from-a-branch

^^^That did it. 

Next step is setting up an efficient development process.

Since the changes I make rarely affect dependencies, I live dangerously and edit the raw files on the server directly.

https://development.hestiacp.com/docs/contributing/development.html#making-changes-to-hestia will help follow better practices.
