### ISSUE TITLE
[Feature] Nginx template for Mautic Marketing 

### ISSUE THREAD

**Issue by weasam** [hestiacp/hestiacp#3188]
### Describe the feature or change in detail

The default Nginx configuration could not install mautic, it would return to error 404 in the process of installation.  
the problem is lack of url_rewrite in the configuration. fortunately the prestashop nginx configuration works for that. 
but not sure what issue will cause in this prestashop nginx configuration, hope it won't

New Features:
Quick install App has mautic
Or add nginx configuration for mautic

mautic nginx configuration
https://gist.github.com/virgilwashere/013a88e3dde2408808772e50988548c0

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
https://pastebin.com/Zzx06epy
https://pastebin.com/CyugZVrs

And https://forum.hestiacp.com/t/500-error-on-mautic-install/1336/7?u=eris

Please check if they work

**Comment by weasam** [comment]
Let me try this to create a new template for mautic
@jaapmarcus It works. thanks. If I know how to put to the template into hestiaCP github installation. But I'm not sure how to do it. 
next I will install another open source analytics call Matomo

**Comment by ScIT-Raphael** [comment]
@jaapmarcus we could merge it to the repo, can you create a PR?
