### ISSUE TITLE
[Bug]  Users with Administrator role (aside from admin user) cannot see Server gear icon in top right

### ISSUE THREAD

**Issue by nirbhasa** [hestiacp/hestiacp#3189]
### Describe the bug

If you create another user and give them Administrator access, they cannot see the Server gear icon

This happens even though 'Do not allow other administrators to access Server Settings' is set to 'no'

If it helps, the installation is about 2 years old, the original version was about 1.3.0 i think

### Tell us how to replicate the bug

1. Create another user and give them Administrator role
2. Make sure _Configure > Security > System Protection > Do not allow other administrators to access Server Settings_ is set to no
3. Log in as that user

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.8

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
please upgrade first to the latest version.

**Comment by nirbhasa** [comment]
Thanks for replying. Its odd - I ran v-update-sys-hestia-all and nothing happened. (Also autoupdates were already on, so it should have updated to latest package anyway)

**Comment by jaapmarcus** [comment]
Run:
 ```
apt update && apt upgrade 
```

**Comment by nirbhasa** [comment]
Thanks for this! Hestia is now at 1.6.14, but the issue is still there (at least when I access the other Administrator account from my admin account). I will ask the user to log in directly.

**Comment by jaapmarcus** [comment]
You need to login as the user it self it doesn't work if you login as admin and then use "login" as feature

**Comment by nirbhasa** [comment]
Thanks - I contacted user, hopefully should hear back soon....
