### ISSUE TITLE
[Bug] Custom caching template can put nginx off

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#3190]
### Describe the bug

I already saw this behavior happening but never tried to replicate. Today I did and I can replicate:
I clone the nginx caching template, change anything in the new files and apply it in any domain: the nginx will not restart and all domains will be offline.

### Tell us how to replicate the bug

1. Clone the caching.tpl and caching.stpl files with names caching-custom.tpl and caching-custom.stpl
2. Change anything. I just added "|contact-us|" in the URI exception
3. Login with admin user, change to any user and change the nginx template from default to **caching-custom** and apply. Nginx will fail to restart.
4. In the same page, change to **caching** and apply. It will work and nginx will return. **Important:** needs to be "caching". if you change to default and try the next step (5) it will fail again.
![Screenshot 2023-01-08 at 12 12 54](https://user-images.githubusercontent.com/8779476/211204252-def1a3cf-cd21-4208-9061-d92b72bc6dec.png)

5. In the same page, change back to **caching-custom** and bam, it will work either.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.14

### Operating system

ubuntu 20.04.5

### Log capture

When you apply the new config in step 4, this message will be showed if you try to execute nginx -t after the step 4.

```shell
nginx: [emerg] "proxy_cache" zone "xxxxxxxx.com" is unknown in /etc/nginx/nginx.conf:162
```

The 162 line is the last nginx.conf line:
```bash
    # Wildcard include
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/conf.d/domains/*.conf;
}
```

And I saw this in the hestiacp error.log:
```shell
2023-01-08 06:13:18 v-restart-proxy  '' [Error 20]
2023-01-08 06:13:18 v-add-web-domain-ssl-force  'xxxxxxxx' 'xxxxxxxx.com' [Error 20]
```

**Comment by jaapmarcus** [comment]
You also need to copy caching.sh

**Comment by franciscopaniskaseker** [comment]
- Domains are using self-signed ssl
- Instead of go from default to caching-custom, if I first set caching and then caching-custom, the problem will not happen

**Comment by franciscopaniskaseker** [comment]
> You also need to copy caching.sh

Understood. this explain why sometimes happen and sometimes not. In some servers the .sh file was copied.

**Comment by franciscopaniskaseker** [comment]
Tested. with caching-custom.sh it works. Thank you.
