### ISSUE TITLE
When a new user is created using the API and non-standard characters are present. An error occurs. [Bug] 

### ISSUE THREAD

**Issue by skorpions2000** [hestiacp/hestiacp#3195]
### Describe the bug

v-add-user  admin2 P4$$w@rD bgates@aol.com pakage_name Rubén Poben
Answer from API: invalid name format: Rubén

### Tell us how to replicate the bug

1. v-add-user  admin2 P4$$w@rD bgates@aol.com pakage_name Rubén Poben
2. Answer from API: invalid name format: Rubén

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.6.8

### Operating system

Debian 10

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/31d5f892e848e867338ec1d84e565f3683a8dbf3/func/main.sh#L1075-L1080

So according the function it is the correct behaviour.

**Comment by jaapmarcus** [comment]
Changed and merged
