### ISSUE TITLE
[Feature] [Function] [bug] File Manager and PHPMyAdmin on HestiaCP

### ISSUE THREAD

**Issue by anjasamar** [hestiacp/hestiacp#3196]
### Describe the feature or change in detail

The file manager lacks features such as unzip, and chmod file or fold operations, and permission operations. actually the most important thing is that the file manager used to edit, change file data, or the work of automatic script applications such as web script installers for example BoxBilling, cannot be installed because it is blocked by permission access, after that phpmyadmin cannot be accessed with localhost uri with localhost example port :1001, and it's a bit of a headache how do I access phpmyadmin?

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Add a domain as and it to your /etc/hosts/ file so you can access http://domain.com/phpmyadmin

Unzip support is present  and chmod needs to be added upstream. We can't do it currently.

**Comment by anjasamar** [comment]
Yes sure thanks a lots, Curently I still developing for private to small
business hosting shared at my home, ya use WSL cause I'm just have 1 PC as
server 😅

Pada tanggal Rab, 11 Jan 2023 03.43, Jaap Marcus ***@***.***>
menulis:

**Comment by anjasamar** [comment]
Ya I'm just shared what for do at the future update, and just share few
idea about advance File Manager System and differenced by user level and
administrator (root) level, like CHMOD, and Special Permission option funct
like what I said on GitHub before, and thanks again for your update about
my Issue 🙏

Pada tanggal Rab, 11 Jan 2023 03.43, Jaap Marcus ***@***.***>
menulis:

**Comment by jaapmarcus** [comment]
> Yes sure thanks a lots, Curently I still developing for private to small business hosting shared at my home, ya use WSL cause I'm just have 1 PC as server 😅 Pada tanggal Rab, 11 Jan 2023 03.43, Jaap Marcus ***@***.***> menulis:
> […](#)

You should not start a hosting company from home on the same Windows computer. Start with a 5 dollar / month VPS... If that is to expensive you should go into hosting

**Comment by jaapmarcus** [comment]
> Ya I'm just shared what for do at the future update, and just share few idea about advance File Manager System and differenced by user level and administrator (root) level, like CHMOD, and Special Permission option funct like what I said on GitHub before, and thanks again for your update about my Issue 🙏 Pada tanggal Rab, 11 Jan 2023 03.43, Jaap Marcus ***@***.***> menulis:
> […](#)

The current behaviour is fine if you want to add chmod support to the Filemanger you should create a PR against Filegator. 

PHPmyadmin behavoir we have changed in the past to bring it in sync with Hestia + Nginx setup and there  instruction to how get it accessible by ip:
https://docs.hestiacp.com/admin_docs/database.html

This is not going to change...
