### ISSUE TITLE
[Bug] After updating a web domain of another user, the UI jumps to the own web domains

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3199]
### Describe the bug

After updating a web domain of another user, the UI jumps to the own web domains

### Tell us how to replicate the bug

1. Search for a domain of another user
2. Select it
3. Make some changes (e.g. enable Let's Encrypt SSL)
4. After loading for a while, it neither stays at the domain nor at the user, it jumps to your own web domains, which is rather irritating.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

latest

### Operating system

Debian 11

**Comment by ScIT-Raphael** [comment]
This seems to be a very specific, local issue. I was not able to notice the same thing ever on my systems aswell as I didnt heared of it (on 35k+ active installs). As we can't reproduce the issue, its impossible for us to fix. If you could be more specific and help out debug the reason, we maybe could change something - otherwise it's probaly not fixable.

**Comment by jaapmarcus** [comment]
Can confirm the bug . Issue is caused by the fact we don't change the session to the new user. 

So far I can see there are 3 options:
- Make sure we change the user sessions to the new user and disable the option to go back as admin 
- Or delete it 
- Or leave it as is...

**Comment by xeruf** [comment]
I have a much simpler idea:
When editing a domain of another user, simply stay at that screen after confirmation.

**Comment by jaapmarcus** [comment]
That will not work it is currently a post request

**Comment by xeruf** [comment]
> Make sure we change the user sessions to the new user

I think that would be best - oftentimes I search domains to find another user account, currently I then have to go back to the user overview to actually switch the session

> disable the option to go back as admin

why?
