### ISSUE TITLE
[Bug] Renewed LE Certificate only served after hours of delay

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3202]
### Describe the bug

I created a new certificate for a new domain, and it was only served after either waiting many hours, or restarting (not reloading) nginx.

Looks like https://github.com/hestiacp/hestiacp/issues/2114

### Tell us how to replicate the bug

See above

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.8

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
I wonder why your server is not reloading.

Also suggest running apt-update && apt-upgrade as your server is behind on the current 1.6.14

**Comment by xeruf** [comment]
oh, I thought I had read something about hestia updating automatically
let's see

**Comment by istiak101** [comment]
The browser won't fetch the new certificate until you close and re-open. Could be a cached certificate.

**Comment by xeruf** [comment]
Not even with a Ctrl-F5? Will test that, thank you.

**Comment by jaapmarcus** [comment]
> oh, I thought I had read something about hestia updating automatically
> let's see

It does but a bug prevented it

**Comment by xeruf** [comment]
Certificate generation works out of the box in the newest version, thank you :)
But the delay is still there, browser restart does nothing.

**Comment by xeruf** [comment]
For what?

This seems to be simply a missing restart or certificate reload for nginx.

**Comment by jaapmarcus** [comment]
It should be done in:
https://github.com/hestiacp/hestiacp/blob/6058a95f88234f82a4f6505f6b37936b78f8fd3f/bin/v-add-letsencrypt-domain#L529

https://github.com/hestiacp/hestiacp/blob/6058a95f88234f82a4f6505f6b37936b78f8fd3f/bin/v-update-web-domain-ssl#L86-L91

**Comment by jaapmarcus** [comment]
Please try to enable debug mode:

And see if you are able to trigger an error
https://github.com/hestiacp/hestiacp/blob/694bee1ec3ffeaf68a700227e826c1d0a07e7eda/bin/v-restart-service#L59

**Comment by jaapmarcus** [comment]
Also make sure to remove the 

```
if [ "$DEBUG_MODE" = "true" ]; then 
    
    log="/var/log/hestia/debug.log"
fi
```

And replace it with:
log="/var/log/hestia/debug.log"

**Comment by xeruf** [comment]
`service` is not a command on my system, there is no way that line can work ^^

**Comment by jaapmarcus** [comment]
root@dev:~# service
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]

**Comment by jaapmarcus** [comment]
apt list sysvinit-utils
?

**Comment by xeruf** [comment]
ups, forgot `sudo`, it is there - but enabling the debug log and issuing a certificate did not yield anything because we get that 403 error again :/

**Comment by jaapmarcus** [comment]
Please check:
https://github.com/hestiacp/hestiacp/issues/3241#issuecomment-1416817662

**Comment by xeruf** [comment]
Aha :)

    2023/02/03 07:53:10 [emerg] 892#892: open() "/var/log/apache2/domains/DOMAIN.log" failed (24: Too many open files)

Followed https://development.hestiacp.com/docs/server-administration/configuration#error-24-too-many-open-files, let's see...

**Comment by ScIT-Raphael** [comment]
Probaly issue solved then, going to close the issue report. Please feel free to reopen if the issue occures again.

**Comment by vikasprogrammer** [comment]
sidenote: I think default hestia installation should have this settings/config.

**Comment by ScIT-Raphael** [comment]
> sidenote: I think default hestia installation should have this settings/config.

This depends on each system and belongs to the sysadmin what he want to set.

**Comment by jaapmarcus** [comment]
It would be nice if it gives an error instead a warning

**Comment by jaapmarcus** [comment]
Even with worker_rlimit_nofile    10; what is way to low.

```
root@dev:/var/log/nginx# systemctl restart nginx 
root@dev:/var/log/nginx# echo $?
0
root@dev:/var/log/nginx# cat error.log
2023/02/06 10:15:44 [emerg] 1323157#1323157: epoll_create() failed (24: Too many open files)
2023/02/06 10:15:44 [alert] 1323154#1323154: cache manager process 1323157 exited with fatal code 2 and cannot be respawned
2023/02/06 10:15:44 [emerg] 1323155#1323155: epoll_create() failed (24: Too many open files)
```

**Comment by xeruf** [comment]
This was by default in my nginx conf:
```sh
worker_rlimit_nofile    65535;
```

And this is my override:
```
[Service]
TimeoutStart=5m
Restart=always
RestartSec=60
StartLimitBurst=10
StartLimitInterval=1h
LimitNOFILE=65536
```

**Comment by xeruf** [comment]
ah finally, was fixed after a reboot :)

**Comment by xeruf** [comment]
Nope, it was not, still having nginx restart errors and constantly seeing "Too many open files" in the logs

**Comment by xeruf** [comment]
Troubleshooted in https://forum.hestiacp.com/t/too-many-open-files-despite-config-adjustments/8858, thank you :)
