### ISSUE TITLE
[Bug] Quick Install App Issues

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3203]
### Describe the bug

- If there is an error, all form fields are cleared
- If the domain folder is missing under HOME/web, there is an error - I would expect the folder to be created automatically.

## Wordpress
- When setting up Wordpress on a domain of another user, wp-config.php is copied from the sample, without the values configured at the dialogue being filled in, leading to a failing database connection (see https://github.com/hestiacp/hestiacp/issues/2711)
- When setting up Wordpress on my own domain, it did not create a config at all, prompting me to enter fresh credentials

### Tell us how to replicate the bug

Select a Web Domain and use "Install App"

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.6.8

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Could be related with:
https://github.com/hestiacp/hestiacp/issues/3199

**Comment by jaapmarcus** [comment]
If the domain folder is missing under HOME/web, there is an error - I would expect the folder to be created automatically.

>- If there is an error, all form fields are cleared
Yes a know issue

>If the domain folder is missing under HOME/web, there is an error - I would expect the folder to be created automatically.
- Users should not be able to delete this folder...

**Comment by xeruf** [comment]
> Users should not be able to delete this folder...

I used the file manager to move the folder to set it up afresh, I don't think there would be anything wrong adding a `mkdir -p` there.

**Comment by xeruf** [comment]
Now, with 1.6.14, whenever I try to install WP, I get this error:

    Error: file /tmp/hst.TRzVTN was not copied

Resulting in a working but unconfigured installation as mentioned above (no wp-config)

**Comment by jaapmarcus** [comment]
I am not able to replicate the issue (Running 1.7~alpha) at the moment

Other issues where you access via "Search" => Web domain under a different user will be resolved by an PR already. 

Also what folder did you move? 
/home/user/web/domain/public_html or a different one? 

/home/user/web/domain/public_html shouldn't be able to move unless with ssh and the root user.

**Comment by xeruf** [comment]
That time I renamed /home/user/web/domain from within the file manager to /home/user/web/domain.bak, causing the error.

Now I removed `public_html`, which was immediately recreated empty, and ran the wordpress setup again.
Still having the issue.

**Comment by jaapmarcus** [comment]
Deleting public_html is not possible as  

```
admin@dev:~/web/xxxxxx $ rm -fr public_html/
rm: cannot remove 'public_html/': Permission denied
```

I don't why we never implemented it on the domain name.

User can rename a domain in /home/user/web/domain.com 
And force a restart via creating a new site updating some values and causing a server crash

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3211

Should prevent it.

**Comment by xeruf** [comment]
That's good to tackle, still the original issue is unresolved, wordpress quick installs fail.

**Comment by jaapmarcus** [comment]
I did try on my server for Wordpress to a folder and in German and it worked like a charm. (1.7.0~beta1) 

They issue could lay in:
https://github.com/hestiacp/hestiacp/blob/b0356cb2fa8e7de833342d0a7165e223a8a9399e/web/src/app/WebApp/Installers/WordPress/WordPressSetup.php#L115-L119

Also check the logs in /var/log/hestia/nginx-error.log it provides a lot of info regarding this... 

So I don't see any issues with it. Except from some format changes I don't see any issue
