### ISSUE TITLE
[Bug] Error output while running  v-change-web-domain-name

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#3212]
### Describe the bug

root@webxx:~# v-change-web-domain-name user new.domain.tld domain.tld
/usr/local/hestia/bin/v-change-web-domain-name: line 115: prepare_web_backendv: command not found

### Tell us how to replicate the bug

Run v-change-web-domain-name

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.0~alpha

### Operating system

Ubuntu 22.04 LTS

**Comment by jaapmarcus** [comment]
prepare_web_backendv 

looks like the bug

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/commit/097ca25f0a18c239ad39288658698ff5ced958ea

See commit main branch is fine
