### ISSUE TITLE
[Bug] Hestia allows umlauts for user names, which produces some issues.

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#3213]
### Describe the bug

root@webxx:/backup# v-backup-user xxx
/usr/local/hestia/bin/v-backup-user: line 178: Error: Invalid key value format [U_SYS_USERS=$'xxxx,XXX-XXX,B\303\244ren-XXX,ith'] * 2: syntax error in expression (error token is ": Invalid key value format [U_SYS_USERS=$'xxxx,XXX-XXX,B\303\244ren-XXX,ith''] * 2")

### Tell us how to replicate the bug

Add a user with umlauts (for example ä ü ö).

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.0~alpha

### Operating system

Ubuntu 22.04 LTS

**Comment by jaapmarcus** [comment]
root@dev:# v-add-user "tetäesfawea" afwe me@xxxx
root@dev:# v-add-user "äesfawea" afwe me@xxxx

Both work :|

https://github.com/hestiacp/hestiacp/blob/main/func/main.sh#L1566-L1570

**Comment by jaapmarcus** [comment]
It is using:

https://github.com/hestiacp/hestiacp/blob/bce434fb4fb3955a9486d85b206d5f88fb22e282/func/main.sh#L680-L691
