### ISSUE TITLE
[Feature/Issue] Autofit header logo

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3215]
I replaced `/usr/local/hestia/web/images/logo-header.svg`, but my replacement is bigger.
Would be nice if it would automatically be fit to size rather than cut off.

**Comment by jaapmarcus** [comment]
I don't think it is easy it is all based on css. I and probally not feasible... 

At some point we need to write a theming module but currently it is not on the planning.

**Comment by jaapmarcus** [comment]
It should be easier to be done with the future 1.7.0 release (Currently alpha) and maybe a few lines of css. 

It is impossible for us to detect the size of the image...
