### ISSUE TITLE
[Bug] Apache2 not working after an upgrade.

### ISSUE THREAD

**Issue by DanielDEVp** [hestiacp/hestiacp#3219]
### Describe the bug

![image](https://user-images.githubusercontent.com/92984764/213885212-6c125886-e28a-4eda-9302-f61352adebd9.png)

### Tell us how to replicate the bug

Apache2 not working after upgrading apache2.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

Latest

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
not related to hestia, do not overwrite any configs:

https://forum.hestiacp.com/t/failure-in-several-hestiacp-servers-apache-does-not-start/8588
