### ISSUE TITLE
[Bug] Can't create email alias > 30 characters

### ISSUE THREAD

**Issue by mdlaat** [hestiacp/hestiacp#3222]
### Describe the bug

When adding an email alias with more than 30 characters to an email user, a popup with an error message appears:
Error: invalid malias format :: {wrongemailalias}

I tried to follow the code, it seems that the function
is_user_format_valid()
in func/main.hs
is being called to check the malias
and produces the error

Created bug as requested on https://forum.hestiacp.com/t/email-alias-maximum-length-30-characters/8607/1

### Tell us how to replicate the bug

1. Login to hestiacp webinterface
2. Select 'mail' on top icons
3. Select maildomain
4. Select existing mailaccount
5. Add new emailalias > 30 characters in the 'Aliases' box
6. Click save

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.14

### Operating system

Ubuntu 22.04.1 LTS (Jammy Jellyfish)

### Log capture

```shell
2023-01-25 12:25:49 v-add-mail-account-alias  '<hestiauser>' '<emaildomain>' '<emailuser>' '<newemailalias>' [Error 2]
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3210/commits/69a8ba917a17db0ca4a1c1b80dfe614e831618b8

See changes

**Comment by jaapmarcus** [comment]
Merged
