### ISSUE TITLE
[Feature] backup exclusion templates

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#3227]
### Describe the feature or change in detail

To be able to have a backup preset and a menu to choose from or a starting point so backups can be easily optimized for common CMS such as WordPress.

The template system could be similar to the Nginx one or maybe like the hosting plans...

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Why would you want to exclude by default any folders? 

I don't see the reasons for it...

**Comment by jlguerrerosanz** [comment]
Cache folders for instance

**Comment by jlguerrerosanz** [comment]
Zipfiles bigger than x MB
Some WP backup plugins leave zipfiles behind.

Maybe I only need the wp-content folder without plugins and themes since the rest of the assets can be downloaded.

**Comment by jaapmarcus** [comment]
So it is very specific. I don't see any reason for it. I would prefer to spend the time on issues with a way higher priority

**Comment by jlguerrerosanz** [comment]
If hestiaCP stores the config in a file, I can create my own script that copies that template upon user creation

**Comment by ScIT-Raphael** [comment]
there is already a config called backup exclusion in user data file which you can blow up with a script so much you like to do:
https://github.com/hestiacp/hestiacp/blob/c65edbad7fb9b4da567534b88fa3213f51bf19a1/bin/v-backup-user#L40

Beside that, I go along with @jaapmarcus - there feature request is way to specific, there would not be a big user group which will use it - beside we have other pending points to do.

**Comment by jlguerrerosanz** [comment]
If I come up with a solution would you accept a PR?

Something like a v-command without interface
v-add-web-domain-backup-exclude username domain template.conf

**Comment by jaapmarcus** [comment]
We have already support for it for:

See:
https://github.com/hestiacp/hestiacp/blob/main/bin/v-update-user-backup-exclusions

Settings are set on user level and not on domain level. 

But it should be enough....

**Comment by jlguerrerosanz** [comment]
Great, thank you very much.

So I have been having a look here and as long as I place a file here:
/usr/local/hestia/data/users/USERNAME/backup-excludes.conf

There is this open PR with the * issue. https://github.com/hestiacp/hestiacp/pull/3225  When its published then I will be able to add
`*:public_html/*cache*:public_html/*backup:public_html/*bkp*:public_html/*.tar.gz:public_html/*.zip`

Since there is no documentation available, i am not sure if this will work. Specially with the files.

The thing is that the users may install WP backup plugins on their own and leave the garbage behind and I will be feeding the backup system with more backups inside in a funny recursive-fractal structure.

**Comment by jaapmarcus** [comment]
> Great, thank you very much.
> 
> So I have been having a look here and as long as I place a file here: /usr/local/hestia/data/users/USERNAME/backup-excludes.conf
> 
> There is this open PR with the * issue. #3225 When its published then I will be able to add `*:public_html/*cache*:public_html/*backup:public_html/*bkp*:public_html/*.tar.gz:public_html/*.zip`
> 
> Since there is no documentation available, i am not sure if this will work. Specially with the files.
> 
> The thing is that the users may install WP backup plugins on their own and leave the garbage behind and I will be feeding the backup system with more backups inside in a funny recursive-fractal structure.

I don't think this will work...
