### ISSUE TITLE
[Bug] Endless 301 Redirects for WordPress Template with СDN Provider

### ISSUE THREAD

**Issue by webastik** [hestiacp/hestiacp#3229]
### Describe the bug

Installed the latest version of WordPress. Everything is fine.

https://af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net

I wanted to speed up the delivery of content to the user using the provider's SDN.
I got the url for the domain, connected it to WordPress using the CDN Enabler plugin Version 2.0.6, and W3 Total Cache Version 2.2.12, the result is ERR_TOO_MANY_REDIRECTS in the browser.

### Tell us how to replicate the bug

Standard installation

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.14

### Operating system

Debian 11

### Log capture

```shell
no errors in logs
```

**Comment by jaapmarcus** [comment]
Make sure to get a valid ssl certificate before enamelling the plugin / cdn.

Nothing we can do about

**Comment by jaapmarcus** [comment]
```
8-ad94-a194149da5bf.selcdn.net)|2a03:90c0:41:2801::24|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net/ [following]
--2023-01-29 00:48:20--  http://af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net/
Connecting to af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net (af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net)|2a03:90c0:41:2801::24|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net/ [following]
--2023-01-29 00:48:20--  https://af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net/
Connecting to af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net (af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net)|2a03:90c0:41:2801::24|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://af0243f3-0efd-4488-ad94-a194149da5bf.selcdn.net/ [following]
```

It has nothing to do with Hestia
