### ISSUE TITLE
[Feature] Re-send user login credentials

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3240]
### Describe the feature or change in detail

Sometimes customers have lost their account data on hestia and ask for a new password to be sent to their contact.
Would be nice if I could do this from within hestia rather than sending the mail separately.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
There is an option to allow users to reset their password them self:

<img width="753" alt="Screenshot 2023-02-01 at 09 55 12" src="https://user-images.githubusercontent.com/9754650/215996427-7565a2ab-bf89-4ac5-87ef-672aea1ca6a3.png">

Enable this option in the server settings

**Comment by xeruf** [comment]
oh thank you, that was already enabled, ugh these customers ^^
