### ISSUE TITLE
[Bug] SSL not working (custom cert/key), works after nginx restart

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#3241]
### Describe the bug

Have you seen this issue when creating a new site using custom ssl certificate and site says "self-signed" certificate until nginx is restarted. When we restart nginx the SSL is applied and everything works. 

### Tell us how to replicate the bug

We are unable to replicate. 

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.14

### Operating system

Ubuntu 20.04.5 LTS

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/3202

Please try to provide more details...

**Comment by vikasprogrammer** [comment]
Found this line

```
systemd[1]: nginx.service: Can't open PID file /run/nginx.pid (yet?) after start: Operation not permitted
```

**Comment by jaapmarcus** [comment]
WTF v-restart-web / v-update-web-domain-ssl and v-restart-serivices are suppose to run under root

**Comment by vikasprogrammer** [comment]
Did you make any changes b/w 1.6.10 to 1.6.14? It used to work at 1.6.10. 

We install custom SSL certificate for every new site. 

PReviously a simple `nginx reload` will work but it doesn't work any more. We need to restart `nginx`. 

I found these two issues, may be related? 

https://github.com/hestiacp/hestiacp/issues/1236
https://github.com/hestiacp/hestiacp/pull/3060

**Comment by ScIT-Raphael** [comment]
you can compare the code on your own: https://github.com/hestiacp/hestiacp/compare/1.6.10...1.6.14

And also have a look on the history of the related file.

It looks more like an issue with your system.

**Comment by vikasprogrammer** [comment]
You may be right, but I am having really hard time to find the root cause. 

If you have any clue on this, let me know:

1. we create a new web domain, apply the custom ssl cert (wildcard) to it. 
2. web domain shows self-signed cert. 
4. we reload nginx, nothing happens, same result
5. we restart nginx, ssl applied properly. 

If you have seen this behaviour before, let me know please.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/44314eb8ad07eac8a477ea4e26ec6b4976232781/bin/v-change-web-domain-sslcert

Has no recent changes. 

https://github.com/hestiacp/hestiacp/issues/1236 is not related it was caused by the fact that we restart all php versions instead of reloading. And also kills the active php session... 

https://github.com/hestiacp/hestiacp/pull/3060 Is related to v-pruge-nginx for fast cgi / proxy cache.

**Comment by jaapmarcus** [comment]
> Did you make any changes b/w 1.6.10 to 1.6.14? It used to work at 1.6.10.
> 
> We install custom SSL certificate for every new site.
> 
> PReviously a simple `nginx reload` will work but it doesn't work any more. We need to restart `nginx`.
> 
> I found these two issues, may be related?
> 
> #1236 #3060

How do you set it up. Via CLI I think?

**Comment by vikasprogrammer** [comment]
Yes, using cli for everything.

**Comment by jaapmarcus** [comment]
> Yes, using cli for everything.

Can you send me the script?

**Comment by vikasprogrammer** [comment]
One clue which might be useful is this

Found this in `/var/log/nginx/error.log` 

```
2023/02/04 17:45:27 [emerg] 3916357#3916357: open() "/var/log/apache2/domains/thedomain.com.bytes" failed (24: Too many open files)
```

**Comment by jaapmarcus** [comment]
https://development.hestiacp.com/docs/server-administration/configuration.html#error-24-too-many-open-files


That will explain what is wrong...

**Comment by vikasprogrammer** [comment]
Haha, thats exactly what I did. Exact same steps, I will wait if this error arise again, will report my findings very soon.
