### ISSUE TITLE
[Feature] ActiveSync or comparable functionality

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#3251]
### Describe the feature or change in detail

Development of ActiveSync interface so you can have all your Email, Contacts and Calendar via a single connection.

If that's a reach too far, then just Calendaring and Contacts built into HestiaCP

But ActiveSync would be great

Jamie

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jlguerrerosanz** [comment]
Nextcluloud has that functionality. Go to the app installer and hit the nextcluloud button. Just bear in mind that the hestia username should have no dots in it. Otherwise nextcluloud will throw an install error.

**Comment by jaapmarcus** [comment]
Active sync is almost impossible:

https://z-push.org could be used for it but is not maintained any more...

**Comment by ScIT-Raphael** [comment]
without any software like zpush, it is impossible at all - going to close the feature request. Nextcloud could be used, or any other open source groupware service, which then needs a separated server.
