### ISSUE TITLE
[Bug] Broken Translations

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3254]
### Describe the bug

I have the interface in english, and keep seeing popups missing strings, such as "DELETE_DOMAIN_CONFIRMATION"

And when I send a welcome email to a german account, the email contains:
GREETINGS_GORDON
ACCOUNT_READY 

This makes a very unprofessional impression, at least it should fall back to english?

### Tell us how to replicate the bug

Create a new account with German as language and send a welcome email

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

 v1.6.14

### Operating system

Debian 11.6 (x86_64)

**Comment by jaapmarcus** [comment]
Translations should be taken from:
https://translate.hestiacp.com/projects/hestiacp/de/default/?filters%5Bterm%5D=GREETINGS_GORDON&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by jaapmarcus** [comment]
Does /usr/local/hestia/web/locale/ exits?

**Comment by xeruf** [comment]
It does, and its contents seem fine

**Comment by jaapmarcus** [comment]
I don't have any issues with it.

![Screenshot 2023-02-10 at 07 55 52](https://user-images.githubusercontent.com/9754650/218023654-a7a33308-3429-421d-a7a3-f86a545157a3.png)

And as never have seen any issues like this I have no idea what could be wrong...

**Comment by ScIT-Raphael** [comment]
As it is not reproducible and we havent got any additional information, I'll going to close the bug report.

**Comment by xeruf** [comment]
I did a find-replace like this to apply custom branding (https://github.com/hestiacp/hestiacp/issues/2493)

    grep -rl 'Hestia Control Panel' /usr/local/hestia/web | xargs sed -i 's/Hestia Control Panel/Iridion/g'

Maybe that could have caused the issue?

**Comment by jaapmarcus** [comment]
Yes most likely as it also does the translations files:

/usr/local/hestia/web/locale/hr/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/it/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/uk/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/sv/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/el/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/da/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ka/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/th/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/pl/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/pt/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/sk/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ckb/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/fr/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ar/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/zh-cn/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/zh-tw/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/fi/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/tr/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ur/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/pt-br/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/fa/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/bs/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ja/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/sr/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ro/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/nl/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/hu/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ru/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/en/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/bn/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/ko/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/no/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/es/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/hestiacp.pot
/usr/local/hestia/web/locale/cs/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/id/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/vi/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/de/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/az/LC_MESSAGES/hestiacp.mo
/usr/local/hestia/web/locale/bg/LC_MESSAGES/hestiacp.mo


Most likely it corrupted it

**Comment by jaapmarcus** [comment]
v-update-sys-hestia-git hestiacp release 

Will fix them

**Comment by xeruf** [comment]
I see, these files are some kind of binary format, I thought they would be textfiles which could easily be modified ^^
Just for reference, I chose `None` when it asked me to replace some files, seems to have worked fine.

I think the guide at https://github.com/hestiacp/hestiacp/blob/main/web/locale/NOTES.md is outdated, how would I update the translations in a fork without messing in the binary files?

**Comment by jaapmarcus** [comment]
It should still work how ever we moved all .po files to translate.hestiacp.com

You should be able to download the .po make all the changes in plain text with Greg concert it to .no and upload the result 

Ideally we should update all the source files and replace it with a variable

**Comment by jaapmarcus** [comment]
<img width="1430" alt="Screenshot 2023-02-21 at 12 46 10" src="https://user-images.githubusercontent.com/9754650/220336656-8edcfe85-fd7b-4a58-9b16-ebe52abcc756.png">

**Comment by xeruf** [comment]
But it looks like I have to download each individually - don't you automatically fetch updated translations?

**Comment by jaapmarcus** [comment]
> 

I have written a plugin that is able to download the .mo files in the final format so I am able to download the files as needed.  Maybe it is usable for logged in users or only for admin level. 

For the same reason why we don't merge the .po files any more. It caused a lot of changes by only updating a single template. 

Google if there is a method for converting .mo to .po. But don't expect me to invest my time into it for free...

**Comment by ScIT-Raphael** [comment]
If you want to give it a new name, it would be the best idea to fork the project, build up own translation and an apt repository. You can then still merge changes from hestia's main branch if needed - but we can't help you doing it.

**Comment by xeruf** [comment]
I don't want to create a separate project - just brand it for our company. 
Is that not something you do on your instances for customers?

**Comment by ScIT-Raphael** [comment]
No, we use hestia as it is - there is no reason to "hide" the product. If you want to have it branded, you currently need to either fork the version or create your own webinterface which communicate over api. For bith we can't help.

**Comment by xeruf** [comment]
It is not about hiding it, I am all for attributing the open-source projects in use, but about a professional appearance - and when you have a brand with name and logo, the control panel should reflect that, also to ease customers.
Thanks for the insight anyways :)

See also https://github.com/hestiacp/hestiacp/issues/2493#issuecomment-1119513819
