### ISSUE TITLE
[Feature] Info about generating template files ...

### ISSUE THREAD

**Issue by tgd1973** [hestiacp/hestiacp#3267]
### Describe the feature or change in detail

I would like to ask for info that may also be useful to others for a change regarding the possibility of implementing the proxy / balancing of web files:
I would like to understand which is the responsible file in the hestiacp that starting from the tpl, stpl templates of /hestia/data/templates/web/nginx create the .conf files (in the photo below) of each domain at the time of creation?

I'm interested because I would like to automatically add two more files to each domain (as in the photo) with which I tried to insert the "upstream" function at the top of the nginx config files of the domain (as also shown in the nginx documentation:

http://nginx.org/en/docs/http/load_balancing.html

I manually copied/modified/recreated another two tpl, stpl template files entitled "Nginx-Balancing" to be selected in the advanced meu when creating the domain, and manually created the two additional files in a domain, for experimentation but I would like to insert by default in all domains, so as not to have other unexpected errors (nginx stopped due to the lack of upstream parameters in the configuration in the domains). I'm experimenting with the proxy server function or load balancing as needed.

Thanks to all who can help.

![load](https://user-images.githubusercontent.com/15127860/218771244-88918418-3b8f-449e-9c4d-fccc9a42df2d.png)

**Comment by jaapmarcus** [comment]
Basic information for for working with templates can be found 

https://docs.hestiacp.com/admin_docs/web.html

or 

https://development.hestiacp.com/docs/server-administration/web-templates.html

In /usr/local/hestia/data/template/web/nginx/ you should be able to create a new template called "loadbalence.tpl" and "loadbalence.stpl" with the required templates.  End when done enable it in the web domain selection under advanced templates

```
upstream myapp1 {
        server srv1.example.com;
        server srv2.example.com;
        server srv3.example.com;
    }

server {
    listen      %ip%:%proxy_port%;
    server_name %domain_idn% %alias_idn%;

    include %home%/%user%/conf/web/%domain%/nginx.forcessl.conf*;

    location / {
        proxy_pass      http://myapp1:%web_port%;
        location ~* ^.+\.(%proxy_extensions%)$ {
            root           %docroot%;
            access_log     /var/log/%web_system%/domains/%domain%.log combined;
            access_log     /var/log/%web_system%/domains/%domain%.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }

    location /error/ {
        alias   %home%/%user%/web/%domain%/document_errors/;
    }

    location @fallback {
        proxy_pass      http://%ip%:%web_port%;
    }

    location ~ /\.(?!well-known\/|file) {
       deny all;
       return 404;
    }

    include %home%/%user%/conf/web/%domain%/nginx.conf_*;
}
```

Should probally work otherwise you need include:

upstream myapp1 {
        server srv1.example.com;
        server srv2.example.com;
        server srv3.example.com;
    } 

In nginx.conf

You method will not work.

**Comment by tgd1973** [comment]
> Basic information for for working with templates can be found
> 
> https://docs.hestiacp.com/admin_docs/web.html
> 
> or
> 
> https://development.hestiacp.com/docs/server-administration/web-templates.html
> 
.......


Maybe it was better to read more carefully what I wrote before ...
I personally know how to manually write and edit template files tpl, stpl ...

I was asking the mechanist who from the VestaCP/HestiaCP software on the basis of this template writes the conf files for each domain ...

to the already known files that are created automatically, I would always like to automatically create two more conf files ... underlined in the image.
Please reopen my ticket otherwise I would have to open another ...  ( your answer is not what I asked for )

Thank you !

**Comment by tgd1973** [comment]
I have in /usr/local/hestia/data/templates/web/nginx modified tpl, stpl template file that automatically creates conf files in domains ....


```
#=========================================================================#

include %home%/%user%/conf/web/%domain%/load_balancing_ssl.conf;

server {
    listen      %ip%:%proxy_ssl_port% ssl http2;
    server_name %domain_idn% %alias_idn%;
    ssl_certificate      %ssl_pem%;
    ssl_certificate_key  %ssl_key%;
    ssl_stapling on;
    ssl_stapling_verify on;
    error_log  /var/log/%web_system%/domains/%domain%.error.log error;

    include %home%/%user%/conf/web/%domain%/nginx.hsts.conf*;

    location / {
        proxy_pass      https://my_backend_https;
        location ~* ^.+\.()$ {
            root           %sdocroot%;
            access_log     /var/log/%web_system%/domains/%domain%.log combined;
            access_log     /var/log/%web_system%/domains/%domain%.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }

    location /error/ {
        alias   %home%/%user%/web/%domain%/document_errors/;
    }

    location @fallback {
        proxy_pass      https://%ip%:%web_ssl_port%;
    }

    location ~ /\.(?!well-known\/|file) {
       deny all; 
       return 404;
    }

    proxy_hide_header Upgrade;

    include %home%/%user%/conf/web/%domain%/nginx.ssl.conf_*;
}
```

then I created the load-balancing.conf files by hand with these lines ...


```
# upstream section on server
upstream my_backend_https {
#least_conn;
ip_hash;
server 192.168.0.243:8443; 
server 192.168.0.114:443;
server 192.168.0.115:443;
}
```


MY QUESTION WAS TO KNOW THE MECHANISM WITH WHICH nginx.ssl.conf files are created by Hestiacp because I would like to add also this last file "load_balancing.conf" so that it is created/copied with the same mechanism automatically in all domains where I choose the template I modified

Thank you and I hope this time I was understood ...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/d128e3c770f9f87917a7e20d88a0ed9b59dbc915/func/domain.sh#L231

How ever it doesn't support custom files at the moment and generating the loadbalancer config is almost impossible.

If you want to do it for more web domain with the same settings probally

https://github.com/hestiacp/hestiacp/blob/main/install/deb/templates/web/nginx/caching.sh

That run cp /root/loadbalnacer.conf /home/$user/conf/web/$domain/

**Comment by jaapmarcus** [comment]
Also for optimal performance you should use http instead of https... 

```
# upstream section on server
upstream my_backend_http {
#least_conn;
ip_hash;
server 192.168.0.243:8080; 
server 192.168.0.114:8080;
server 192.168.0.115:8080;
}

```

**Comment by tgd1973** [comment]
I'm not interested in someone answering me whether the load balancing or the proxy works or not ...

I'm interested in the mechanism by which the conf files are created/copied from the templates that I find in /usr/local/hestia/data/templates/web/nginx
from the Hestiacp domain creation mechanism ... because I would like to add my own files to be generated automatically to the 5 files it generates who saw them in the photo of the first post  ...

**Comment by jaapmarcus** [comment]
apache2.conf / apache2.ssl.conf via  add_web_config
nginx.conf / nginx.ssl.conf via add_web_config
v-add-letsencrypt-domain for lets encrypt 

All the other files with multiple other commands. I suggest looking In the source code.  

It is way to much to explain everything use the search function on Github
