### ISSUE TITLE
[Bug] Cron Notification grep

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3278]
### Describe the bug

I have cron notifications on, to make sure I do not miss any issues, but the last few days I kept getting this useless message:

Cron <admin@main> sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl

grep: /usr/local/hestia/data/users/admin/system.log: Übereinstimmungen in Binärdatei
grep: /usr/local/hestia/data/users/admin/system.log: Übereinstimmungen in Binärdatei
grep: /usr/local/hestia/data/users/admin/system.log: Übereinstimmungen in Binärdatei
grep: /usr/local/hestia/data/users/admin/system.log: Übereinstimmungen in Binärdatei
grep: /usr/local/hestia/data/users/admin/system.log: Übereinstimmungen in Binärdatei

The content is always these lines, in varying numbers. Maybe you just missed a `-q` or `--text` flag to grep?

### Tell us how to replicate the bug

Enable cron notifications

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

  v1.6.14

### Operating system

Debian 11.6 (x86_64)

**Comment by jaapmarcus** [comment]
Buggy function in:
https://github.com/hestiacp/hestiacp/blob/fb85fcd04e6c3ddaa6929e54245139a024d03ee8/func/main.sh#L106

**Comment by jaapmarcus** [comment]
rm /usr/local/hestia/data/users/admin/system.log

Will solve the error. We have patched it for next release when it becomes a lot faster...
