### ISSUE TITLE
[Bug] Slow SSH connection

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3279]
### Describe the bug

In the recent weeks, it often takes me multiple minutes to establish a SSH connection to the VM running Hestia.
I have no idea what the cause is there, does anybody else incur such an issue?

running ssh with -vvv shows me that it is stuck at `debug3: client_repledge: enter` the whole time:
```
...
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: set_sock_tos: set socket 3 IP_TOS 0x48
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug3: client_repledge: enter
debug1: pledge: fork
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
# Connected
```

### Tell us how to replicate the bug

ssh via a user account

### Which components are affected by this bug?

Firewall (Iptables, Fail2ban)

### Hestia Control Panel Version

v1.6.14

### Operating system

Debian 11.6 (x86_64)

**Comment by jaapmarcus** [comment]
This is not a bug with in HestiaCP.  Use forum for support...

**Comment by xeruf** [comment]
Seems to have fixed itself again for now, thank you

**Comment by xeruf** [comment]
Issue was setting tmux as login shell
