### ISSUE TITLE
[Bug] Bind9 restart during upgrade to 1.7.0/main fails, named-checkconf not found

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#3287]
### Describe the bug

Upgrade from stable to main branch using v-update-sys-hestia-git provides the following output:

```
[ * ] Restarting services...
      - exim4
      - dovecot
      - apache2
      - nginx
      - bind9
Error: bind9 restart failed'
      - php8.0-fpm
      - vsftpd
      - fail2ban
      - sshd
      - hestia
```

Also triggers an email containing the following information: /usr/local/hestia/bin/v-restart-dns: line 31: /usr/sbin/named-checkconf: No such file or directory

Can confirm that the file doesnt exist.

### Tell us how to replicate the bug

As written in bug description.

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.7.0~alpha

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3275
