### ISSUE TITLE
[Bug]  awstats not updated by logrotate

### ISSUE THREAD

**Issue by mdlaat** [hestiacp/hestiacp#3289]
### Describe the bug

When awstats is being triggered by logrotate, awstats fails with error in syslog:
logrotate[490943]: Error while processing /etc/awstats/awstats.{domain}.conf
logrotate[491025]: Error: Failed to open directory /home/{user}/web/{domain}/stats : Permission denied

Also see https://forum.hestiacp.com/t/awstats-logrotate/8737/2

### Tell us how to replicate the bug

1. wait for logrotate to rotate the apache logs

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.14

### Operating system

Ubuntu 22.04.1 LTS (Jammy Jellyfish)

### Log capture

```shell
logrotate[490943]: Error while processing /etc/awstats/awstats.{domain}.conf
logrotate[491025]: Error: Failed to open directory /home/{user}/web/{domain}/stats : Permission denied
```

**Comment by mdlaat** [comment]
The error is caused by an erroneous call of awstats in the file /etc/logrotate.d/httpd-prerotate/awstats. Below is the solution. I lack the knowledge to put this solution in a PR.

Here is a diff to a version that is working:
```
2c2
< UPDATE_SCRIPT=/usr/share/awstats/tools/update.sh
---
> UPDATE_SCRIPT="/usr/local/hestia/bin/v-update-sys-queue"
5c5
<   su -s /bin/sh -l -c $UPDATE_SCRIPT www-data
---
>   sudo /usr/local/hestia/bin/v-update-sys-queue webstats

```

**Comment by jaapmarcus** [comment]
I am wondering why we need it v-update-sys-queue webstats is allready a daily conjob by default...

**Comment by mdlaat** [comment]
Indeed v-update-sys-queue webstats runs by cron on a daily basis, by default each day @ 3:30 AM. 
However, when awstats updates its pages, it only has a look at the current, running logfile from the webserver.

Logrotate kicks in (by default at midnight) and archives the current webserver's logfile and starts a new logfile.
So the information from every webrequest after the latest awstats update (@ 3:30 am) is lost from an awstats point of view, because it is not in the current logfile anymore.

If you want full webstats, you need to process the latest information in the logfile, right before the log is rotated. That's why there is an /etc/logrotate.d/httpd-prerotate/awstats.

EDIT: Also explained in the FAQ of awstats: http://www.awstats.org/docs/awstats_faq.html#ROTATE

**Comment by jaapmarcus** [comment]
Issue has been fixed with https://github.com/hestiacp/hestiacp/commit/75283659494471083bf5c155ae5a5e36ab0756d5
