### ISSUE TITLE
[Bug] Unable to update Blackblaze settings

### ISSUE THREAD

**Issue by ludekcerny** [hestiacp/hestiacp#3295]
### Describe the bug

Backblaze settings update is not working. I try to update the settings, the bucket name stays the same, but I change the Key ID and Application Key. But the change is not written, the original data remains in the config file and on FE.
![image](https://user-images.githubusercontent.com/43381140/220390983-18f85a34-42e3-4157-aed4-e666d3b2f553.png)

### Tell us how to replicate the bug

1. Go to SERVER > Configure > Backup > Remote backup | Protocol: Backblaze
2. Add configuration for a bucket and Save
3. Go to SERVER > Configure > Backup > Remote backup | Protocol: Backblaze and change Key ID and Application Key
4. Save and check Key ID - it stays the same as before update

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.6.13

### Operating system

Ubuntu 22.04.1 LTS

**Comment by jaapmarcus** [comment]
Can confirm the issue:

Changing any settings except "Host" and "Type" will not trigger the update key settings

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3335
