### ISSUE TITLE
Feature Request: Scan for hacked site and auto quarantine

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#330]
This could be a basic cron scan for malicious web content in each of the sites public_html folder. If something is detected then email the user and quarantine the site by moving public_html to public_html_quarantine folder and copying an under maint index.html to the public_html directory. Also put a robots.txt in the pblic_html directory to disallow robots. This is so SEO won't be hindered as much. Just a thought..

**Comment by JOduMonT** [comment]
@johnnyq do you have an example of which kind of script you would use ?

personnaly for wordpress I use : https://wpvulndb.com to do something similar

**Comment by ScIT-Raphael** [comment]
For malware search i would use maldet, we will check a implementation (https://www.rfxn.com/projects/linux-malware-detect/).

**Comment by ScIT-Raphael** [comment]
we discussed this internaly and do not want to directly integrate a malwarescanner.
