### ISSUE TITLE
[Bug]  Error with MariaDB 11.0 during install or use

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#3318]
### Describe the bug

mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead

### Tell us how to replicate the bug

Install Hestia with MariaDB 11.0 currently in RC

### Which components are affected by this bug?

Control Panel Installation or Upgrade, Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.7.0

### Operating system

N/A

### Log capture

```shell
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
```

**Comment by helio-cg** [comment]
Several failed attempts to install the panel on the Deian 11 server. MariaDB would not start.

I suggest adding command below if for some reason MariaDB doesn't start. The error blocks the continuation of the installation.

**solution**: chown -R mysql: /var/lib/mysql
