### ISSUE TITLE
[Bug] Case sensitive Web redirect

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3323]
### Describe the bug

The redirect url is always lowercased.
We now encountered a certain Nextcloud URL which requires the case to match for it to work, so we seem to currently be unable to configure a redirect for it.

### Tell us how to replicate the bug

1. Add a Web Domain
2. Add a redirect with mixed case
3. It is lowercased upon save.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.6.14

### Operating system

Debian 11.6 (x86_64)

**Comment by xeruf** [comment]
Thank you for the prompt fix! Any plans for a new release soon? ;)

**Comment by ScIT-Raphael** [comment]
Next release is 1.7.0, help out testing and it will come soon: https://discord.com/channels/737721354937303161/737954451687735306/1080954852777140234

**Comment by xeruf** [comment]
Hez, unfortunatelz this is still not quite fixed: The case is preserved and the link correctly displayed in the interface, but in the response header (as seen in curl), it appends a `/` to the location, which breaks the URL :/
