### ISSUE TITLE
[Bug] Back button on Firewall page navigates to wrong place

### ISSUE THREAD

**Issue by AlecRust** [hestiacp/hestiacp#3334]
### Describe the bug

If you navigate to the Firewall page (via server overview page):

![Screenshot 2023-03-06 at 18 32 55](https://user-images.githubusercontent.com/247634/223199838-20120670-de56-4a3b-843b-ff581ee80348.png)

And then click the in-page "Back" button, it navigates to "Configure Server" page instead of the server overview page.

This looks to be because there is also a link to "Firewall" on the "Configure Server" page:

![Screenshot 2023-03-06 at 18 33 56](https://user-images.githubusercontent.com/247634/223200027-e8d691ce-60b6-4684-96c8-0e7f1e3656ac.png)

So I guess the "Back" button on the Firewall page needs to know where the user came from, and act accordingly.

**Note:** Pretty sure this is not the only case of this issue

### Tell us how to replicate the bug

1. Click on the server settings cog
2. Note that you are on the "overview/list services" page
3. Click on the "Firewall" menu item
4. Click the "Back" menu item
5. Note that you are now on the "Configure Server" page, not the expected "overview/list services" page

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.6.14

### Operating system

Ubuntu 20.04

**Comment by ghost** [comment]
Issue resolved with v1.8 release as the button only exists in one location now.
