### ISSUE TITLE
DNS/Mail by default even when those services are not installed

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#335]
## issue

As, sometimes; I install Hestia without DNS and/or Mail services it is an annoyance than
DNS zone and Email service are blindly selected by default.

![image](https://user-images.githubusercontent.com/5204724/59256083-7d01c700-8c33-11e9-8f75-b18a3f1685fb.png)

### propostion

It might worth it, but I agree this is low priority, to detect if the service is installed and/or better running when then person add a website than not proposing those option by default.

PS: I look into the code, but saddly my php is limited and didn't find where to make this happen.

**Comment by ScIT-Raphael** [comment]
This request is already resolved: https://github.com/hestiacp/hestiacp/issues/180
