### ISSUE TITLE
[Bug] nginx-error.log get spammed with Undefined variable

### ISSUE THREAD

**Issue by gOOvER** [hestiacp/hestiacp#3359]
### Describe the bug

the nginx-error.log is spammed with:

`2023/03/18 06:50:03 [error] 337360#0: *27810 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 30; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 31; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 32; PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083"
`
and there is 1 Line with a deprecated warning:

`2023/03/18 06:47:49 [error] 337360#0: *27755 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_redirect_custom in /usr/local/hestia/web/templates/pages/edit_web.php on line 150; PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 406; PHP message: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/hestia/web/templates/pages/edit_web.php on line 406" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /edit/web/?domain=xxxx.at&token=64d1xxxxxxxxxxxx875a184ad HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083", referrer: "https://xx.xx.xx:8083/list/web/"`

### Tell us how to replicate the bug

check nginx-error.log

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.0beta6

### Operating system

Ubuntu 22.04

### Log capture

```shell
2023/03/18 06:47:49 [error] 337360#0: *27755 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_redirect_custom in /usr/local/hestia/web/templates/pages/edit_web.php on line 150; PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 406; PHP message: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/hestia/web/templates/pages/edit_web.php on line 406" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /edit/web/?domain=xxxxxx.at&token=64d1xxxxxxxxxxxxxxxxxa184ad HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083", referrer: "https://xx.xx.xx/list/web/"
2023/03/18 06:48:03 [error] 337360#0: *27796 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 30; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 31; PHP message: PHP Warning:  Undefined variable $user_plain in /usr/local/hestia/web/templates/includes/js.php on line 32; PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx.xx:8083"
```

**Comment by jaapmarcus** [comment]
Yes a know issue:

**Comment by cr0c0dylus** [comment]
The error continues to occur in 1.7.2:

2023/04/08 17:31:44 [error] 4027181#0: *451 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $ERROR in /usr/local/hestia/web/templates/pages/login/login_1.php on line 11" while reading response header from upstream, client: 46.211.1.1, server: _, request: "POST /login/ HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "domain.com:8083", referrer: "https://domain.com:8083/login/"

2023/04/09 10:45:34 [error] 1008#0: *54 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: 46.211.1.1, server: _, request: "GET /login/ HTTP/1.1", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "domain.com:8083", referrer: "https://domain.com:8083/list/user/"

**Comment by jaapmarcus** [comment]
I noticed... Nothing really major

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3441

Should solve most error
