### ISSUE TITLE
New repo for PHP Templates

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#336]
Even it was'nt perfect I like the idea of proposing template a la [VestaCP](https://github.com/serghey-rodin/vesta/tree/master/install/debian/9/templates/web/nginx/php-fpm)

What could/would be better is to make those templates outside of the main project like another repo
Mainly because to make the template repo more agile and to reduce the number of PR for the main project, but also:

1. template for nginx are not necessary true for apache
2. template for debian are not necessary true for ubuntu

_this is how to manage it at linuxserver
at the beginning it was include in the main project than it became a [sidekick](https://github.com/linuxserver/reverse-proxy-confs) project_

### Why Hestia need this ?

mainly to be more user friendly

I means [nextCloud](https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html?highlight=nginx) and a lot of others PHP project will not works out of the box with the default php configuration

### propostion

making 2 news repos
- one for nginx
- one for apache

than I could manage the repo and let's you continue your works on the main one

What do you think ?

**Comment by ScIT-Raphael** [comment]
Please check out the develop branch, we already consolidated the templates and configs to one folder instead for every os and version. Also a rewrite for multiphp templates is planed for the feature.
