### ISSUE TITLE
[Bug] Unknown Error while opening File Manager (1.7.0)

### ISSUE THREAD

**Issue by MajorTomDE** [hestiacp/hestiacp#3367]
### Describe the bug

Hey,

I'm getting the attached error while opening the File Manager after upgrade to 1.7.0

I see no files and so but my hosted Wordpress and Nextcloud works fine.

![unknown_error](https://user-images.githubusercontent.com/76742790/226967774-3450efd3-3f46-458b-a04a-cc3365ba580f.jpg)

### Tell us how to replicate the bug

Opening File Manager

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.0

### Operating system

Ubuntu 22.04.2

**Comment by jaapmarcus** [comment]
Please check /var/log/hestia/nginx-error.log

Also please check:

https://www.hestiacp.com/docs/server-administration/file-manager.html#file-manager-gives-unknown-error-message

**Comment by MajorTomDE** [comment]
So easy when knowing how to solve it ;-)
Thanks for your help.

**Comment by arielesp** [comment]
HI
1.7.0

[error] 24189#0: *70 FastCGI sent in stderr: "PHP message: PHP Notice:  No data received from server in /usr/local/hestia/web/fm/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3559; PHP message: PHP Notice:  Connection closed by server in /usr/local/hestia/web/fm/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3967; PHP message: PHP Fatal error:  Uncaught League\Flysystem\Sftp\InvalidRootException: Root is invalid or does not exist: / in /usr/local/hestia/web/fm/vendor/league/flysystem-sftp/src/SftpAdapter.php:279

**Comment by arielesp** [comment]
when logged in as admin
other user its ok
