### ISSUE TITLE
including Redis & Imagick ?

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#337]
## I just want to know if, someones else consider redis and imagick be pratical to being included by default in hestia ?

while for debian 9, and probably ubuntu 18+ we simply have to execute: 
`apt install -y git php-imagick php-smbclient php-redis redis-server`

for debian 8 and ubuntu 16 it seams to request a external source
ref: [install-redis-debian-ubuntu](https://www.hugeserver.com/kb/install-redis-debian-ubuntu/)

**Comment by ScIT-Raphael** [comment]
We should leave it as small as possible, for smbclient, redis and git is no reason to install it by default.

**Comment by JOduMonT** [comment]
or could be as optional like postgresql ;)

**Comment by ScIT-Raphael** [comment]
basicly, as you already wrote properly, it's just a one line install command. I personaly don't see any reason to implement a multiple line installation function to the installer script :). Also hestia is mostly for sysadmins, they should know how to install a missing php package on their own.

**Comment by JOduMonT** [comment]
## I dig a little bit more in why it could be interesting to integrate redis

yes like php-fpm it could be use without password and via TCP socket
but also like php-fpm, it would be better to be use via a socket and protected with a password

here the few line from my **/etc/redis/redis.conf**
```
bind 127.0.0.1 # which is by default
port 0 # which close the TCP socket
unixsocket /var/run/redis/redis.sock # which open the unix socket
unixsocketperm 770 # which open RWX to redis group
requirepass Th!siSN0MyP45sW0rd # which should be encrypted with sha256sum
```

### than
```
usermod -aG redis admin
systemctl restart php7.3-fpm redis
```

#### note in the config file they have this notice
```
# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
```

anyway this is almost a note for myself and other who would like a secure redis on their hestia.
