### ISSUE TITLE
[Bug] v170-cloudflare.inc - seem corrupted contents

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#3370]
### Describe the bug

v1.7.0-
After autoupdate, NGINX failed. /etc/nginx/conf.d/cloudflare.inc - seem corrupted contents. (See attached) https://ibb.co/qpq3RmB
nginx: [emerg] host not found in set_real_ip_from " nginx: configuration file /etc/nginx/nginx.conf test failed

### Tell us how to replicate the bug

v1.7.0
Restart nginx.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1,7,0

### Operating system

Ubuntu 20.04

### Log capture

```shell
Mar 23 09:17:06 dummy.com nginx[2871807]: nginx: [emerg] host not found in set_real_ip_from "<!DOCTYPE" in /etc/nginx/conf.d/cloudflare.inc:4
Mar 23 09:17:06 dummy.com systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE

---------------------------------
contents of /etc/nginx/conf.d/cloudflare.inc
#Cloudflare

# - IPv4
set_real_ip_from <!DOCTYPE;
set_real_ip_from html>;
set_real_ip_from <html;
set_real_ip_from lang="en-US">;
set_real_ip_from <head>;
set_real_ip_from <title>Just;
set_real_ip_from a;
set_real_ip_from moment...</title>;
set_real_ip_from <meta;
set_real_ip_from http-equiv="Content-Type";
set_real_ip_from content="text/html;;
set_real_ip_from charset=UTF-8">;
set_real_ip_from <meta;
set_real_ip_from http-equiv="X-UA-Compatible";
set_real_ip_from content="IE=Edge">;
set_real_ip_from <meta;
set_real_ip_from name="robots";
set_real_ip_from content="noindex,nofollow">;
set_real_ip_from <meta;
set_real_ip_from name="viewport";
set_real_ip_from content="width=device-width,initial-scale=1">;
set_real_ip_from <link;
set_real_ip_from href="/cdn-cgi/styles/challenges.css";
set_real_ip_from rel="stylesheet">;
set_real_ip_from <meta;
set_real_ip_from http-equiv="refresh";
set_real_ip_from content="35">;
set_real_ip_from </head>;
set_real_ip_from <body;
set_real_ip_from class="no-js">;
set_real_ip_from <div;
set_real_ip_from class="main-wrapper";
set_real_ip_from role="main">;
set_real_ip_from <div;
set_real_ip_from class="main-content">;
set_real_ip_from <noscript>;
set_real_ip_from <div;
set_real_ip_from id="challenge-error-title">;
set_real_ip_from <div;
```

**Comment by jaapmarcus** [comment]
Can you run this code:

```
CLOUDFLARE_FILE_PATH='/etc/nginx/conf.d/cloudflare.inc'
	echo "#Cloudflare" > $CLOUDFLARE_FILE_PATH
	echo "" >> $CLOUDFLARE_FILE_PATH

	echo "# - IPv4" >> $CLOUDFLARE_FILE_PATH
	for i in $(curl -s -L https://www.cloudflare.com/ips-v4); do
		echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH
	done
	echo "" >> $CLOUDFLARE_FILE_PATH
	echo "# - IPv6" >> $CLOUDFLARE_FILE_PATH
	for i in $(curl -s -L https://www.cloudflare.com/ips-v6); do
		echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH
	done

	echo "" >> $CLOUDFLARE_FILE_PATH
	echo "real_ip_header CF-Connecting-IP;" >> $CLOUDFLARE_FILE_PATH
```

**Comment by vvcares** [comment]
I ran this script. It successfully created new 'cloudflare.inc' file, but the contents are still same.
The issue is with the curl  CLOUDFLARE url..

**Comment by vvcares** [comment]
@jaapmarcus 
Need your help to fine tune this with your skills plz..

------------------------
```
CLOUDFLARE_FILE_PATH='/etc/nginx/conf.d/cloudflare.inc'
	echo "#Cloudflare" > $CLOUDFLARE_FILE_PATH
	echo "" >> $CLOUDFLARE_FILE_PATH

	echo "# - IPv4" >> $CLOUDFLARE_FILE_PATH
	for i in $(curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv4_cidrs'); do
		echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH
	done

		echo "# - IPv6" >> $CLOUDFLARE_FILE_PATH
	for i in $(curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv6_cidrs'); do
		echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH
	done
```

**Comment by jaapmarcus** [comment]
It is supposed to download:
https://www.cloudflare.com/ips-v4
and 
https://www.cloudflare.com/ips-v6

```
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
172.64.0.0/13
131.0.72.0/22
```
and 
```
2400:cb00::/32
2606:4700::/32
2803:f800::/32
2405:b500::/32
2405:8100::/32
2a06:98c0::/29
2c0f:f248::/32
```

**Comment by vvcares** [comment]
Yes I understood. 
My above script doing it but need attn to format the output file

**Comment by jaapmarcus** [comment]
```
upgrade_cloudflare_ip() {
	echo "[ * ] Update Cloudflare IP..."
	# https://github.com/ergin/nginx-cloudflare-real-ip/
	CLOUDFLARE_FILE_PATH='/etc/nginx/conf.d/cloudflare.inc'
	echo "#Cloudflare" > $CLOUDFLARE_FILE_PATH
	echo "" >> $CLOUDFLARE_FILE_PATH

	echo "# - IPv4" >> $CLOUDFLARE_FILE_PATH
	for i in $( curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv4_cidrs[]'); do
		echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH
	done
	echo "" >> $CLOUDFLARE_FILE_PATH
	echo "# - IPv6" >> $CLOUDFLARE_FILE_PATH
	for i in $( curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv6_cidrs[]'); do
		echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH
	done

	echo "" >> $CLOUDFLARE_FILE_PATH
	echo "real_ip_header CF-Connecting-IP;" >> $CLOUDFLARE_FILE_PATH
}
```

Will do the same

**Comment by vvcares** [comment]
This script is not creating cloudflare.inc.

**Comment by jaapmarcus** [comment]
Run with out
upgrade_cloudflare_ip() { and }

**Comment by vvcares** [comment]
YES, SUCCESS. It works.. Thank you. So to request PULL REQUEST.?

**Comment by jaapmarcus** [comment]
Yes will make a PR in a few minutes

**Comment by vvcares** [comment]
Hi, even single liner for both IPV4 & IPV6 can be as below. But the output contents need your expertise to tuneup..

`for i in $(curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result'); do`

**Comment by hmv47** [comment]
@jaapmarcus Upgrade script errors out on a legacy Apache-only install because `CLOUDFLARE_FILE_PATH='/etc/nginx/conf.d/cloudflare.inc'` does not exist. Consider either adding functionality to add IPs to Apache config, or to skip this step on Apach only installs.

**Comment by ScIT-Raphael** [comment]
> @jaapmarcus Upgrade script errors out on a legacy Apache-only install because `CLOUDFLARE_FILE_PATH='/etc/nginx/conf.d/cloudflare.inc'` does not exist. Consider either adding functionality to add IPs to Apache config, or to skip this step on Apach only installs.

apache2 only has been dropped a long time ago and isnt supported anymore. please consider to switch to nginx+apache2 stack.

**Comment by hmv47** [comment]
I have some special needs to use Apache only, so I'm sticking with it. Point is, upgrades should not break existing functionality, even for legacy, unsupported installs. If you don't want to support it any more (fine by me, of course), simply add a check that would halt the upgrade script before it does anything and displays an informational  message suggesting to upgrade to Apache+Nginx setup. Upgrades should either work completely, or not work at all, not error-out half-way through.

**Comment by ScIT-Raphael** [comment]
As written, support has been dropped - it means we do not support it anymore and also do not implement such checks or do any tests.

I'm not aware of any case, where an apache2 only setup is needed. Nginx is only used as proxy, .htaccess and every function works. Please consider to migrate to nginx+apache2, I'm nearly sure this will work for you aswell.

**Comment by vvcares** [comment]
[> for i in $(curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result'); do](https://github.com/hestiacp/hestiacp/issues/3370#issuecomment-1481071817)

@jaapmarcus

**Comment by jaapmarcus** [comment]
I know 

> > for i in $(curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result'); do
> 
> @jaapmarcus

Doesn't work

returns:
{
  "ipv4_cidrs": [
    "173.245.48.0/20",
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "162.158.0.0/15",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "172.64.0.0/13",
    "131.0.72.0/22"
  ],
  "ipv6_cidrs": [
    "2400:cb00::/32",
    "2606:4700::/32",
    "2803:f800::/32",
    "2405:b500::/32",
    "2405:8100::/32",
    "2a06:98c0::/29",
    "2c0f:f248::/32"
  ],
  "etag": "38f79d050aa027e3be3865e495dcc9bc"
}

**Comment by vvcares** [comment]
YES boss. Im not familiar to format on this output. :-) 
I hope you know how to trim this :-)

**Comment by jaapmarcus** [comment]
That is why I need to run:
curl -s -L "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv4_cidrs[]'

It will return:
```
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
172.64.0.0/13
131.0.72.0/22
```

And do the same trick for ipv6 :)

**Comment by vvcares** [comment]
Haha. So still need multi-liner script, which you already done in PR.
its OK, leave it then. Thank you very much.

**Comment by jaapmarcus** [comment]
Patched

**Comment by vvcares** [comment]
Is this change committed inside v1.7.2 ?
How often this sync will run?

**Comment by jaapmarcus** [comment]
on update only
