### ISSUE TITLE
[Bug] DNS Sec not supported for Ubuntu 20.04 or Deb 10 (or older)

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#3372]
### Describe the bug

How ever check box is visible  cause issues when enableing it

### Tell us how to replicate the bug

Enable DNSSEC on Deb 10 or Ubuntu 20.04

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.0

### Operating system

20.04 or 10

**Comment by Scan4u** [comment]
yes, on Ubuntu 20.04 just got this Error: bind9 restart failed after enabling of the DNSSEC checkbox in the domain DNS zone editor
![зображення](https://user-images.githubusercontent.com/16424225/227580149-4c153b4d-f071-4f9a-95dc-cc05cd5870dd.png)
![зображення](https://user-images.githubusercontent.com/16424225/227581138-b393bc53-12aa-4b64-a25c-fc0cf05a54f1.png)


Solve this issue only after manual removing of this string "dnssec-policy default; inline-signing yes;" for the affected domain in /etc/bind/named.conf

**Comment by jaapmarcus** [comment]
Yes we need to disable the option... for older operating systems
