### ISSUE TITLE
[Bug] Error: SSL is not enabled when rebuilding web domain

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#3375]
### Describe the bug

root@web103:~# v-rebuild-web-domains raphael
Error: SSL is not enabled

Issue was caused by a URL with out SSL enabled

### Tell us how to replicate the bug

root@web103:~# v-rebuild-web-domains raphael
Error: SSL is not enabled

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.0

### Operating system

N/A

**Comment by aessaputra** [comment]
Is there a solution for this?...
i can't add cloudflare ssl

**Comment by ScIT-Raphael** [comment]
https://github.com/hestiacp/hestiacp/pull/3374
