### ISSUE TITLE
[Bug] Button size

### ISSUE THREAD

**Issue by turbopixel** [hestiacp/hestiacp#3380]
### Describe the bug

The buttons on the admin userlist page are to big (in every layout)
![grafik](https://user-images.githubusercontent.com/15839724/227450201-e05d4731-d94e-4257-a7ab-19522cfaa645.png)

**My Firefox Version**
![grafik](https://user-images.githubusercontent.com/15839724/227450682-fe469846-fdc9-4de0-9d3c-5e48c712f574.png)

In **Chromium** for Linux is everything fine:
![grafik](https://user-images.githubusercontent.com/15839724/227450752-776f344d-4881-4cfc-812e-a287953e1d45.png)

---

After I remove the style `width: auto` the button looks beautiful:
![grafik](https://user-images.githubusercontent.com/15839724/227451275-b11007d9-2049-4f88-a49b-2d1a93adf6f4.png)

### Tell us how to replicate the bug

* Update to Version v1.7.0
* Use Firefox & Linux Mint
* Login as admin

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.0

### Operating system

Linux 4.19.0-19-amd64 #1 SMP Debian 4.19.232-1 (2022-03-07) x86_64

**Comment by turbopixel** [comment]
**Page: /list/server/**
![grafik](https://user-images.githubusercontent.com/15839724/227452265-eeafa93e-661c-40b5-b7d4-babfbb5311be.png)

**/list/cron/**
![grafik](https://user-images.githubusercontent.com/15839724/227452464-dc922df2-9ff6-4750-ae68-cfa2ced3db2e.png)

Looks fine: **/list/mail/**
![grafik](https://user-images.githubusercontent.com/15839724/227452539-0a4e6430-7393-4590-9118-0a046c239c04.png)

**Comment by turbopixel** [comment]
I don't know what `ruby` means, but the buttons looks beautiful with that css:

```
  @media (min-width: 1024px)
.toolbar-buttons .button {
  width: auto;
  display: block ruby;
}
```

![grafik](https://user-images.githubusercontent.com/15839724/227453757-a5d7bde5-c221-4f03-82e4-46d812cc9c19.png)

Sources:

* https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position
* https://caniuse.com/?search=display%20ruby

**Comment by jaapmarcus** [comment]
@AlecRust Any idea?
