### ISSUE TITLE
[Bug] Error 550 when sending email to mail server (set to Roundcube)

### ISSUE THREAD

**Issue by r1sk01** [hestiacp/hestiacp#3381]
### Describe the bug

I cannot receive emails, anyone who tries to send emails receives error 550, but I can send emails to others

### Tell us how to replicate the bug

Simply send an email to zeus@zeusteam.dev and you'll see error 550

### Which components are affected by this bug?

Mail (Exim, Dovecot), Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.7.0

### Operating system

Ubuntu 22.04

**Comment by ScIT-Raphael** [comment]
Please check your exim mainlog.

**Comment by jaapmarcus** [comment]
2023-03-24 10:02:24 1pfdJV-004eVE-9X == zeus@zeusteam.dev R=dnslookup T=remote_smtp defer (113): No route to host H=mail.zeusteam.dev [50.20.205.93]: mail.zeusteam.dev [50.20.205.93]

It looks some kind of configuration issue with your DNS / firewall

**Comment by jaapmarcus** [comment]
As it is not a bug but a support question 

https://forum.hestiacp.com
