### ISSUE TITLE
[Bug] Nginx trying to listen 8443 port

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#3382]
### Describe the bug

Today just one domain (from 4) had nginx config file listening 8080 and 8443 ports (apache2 is expected to listen those ports).

I am not sure how this happened, as is impossible to change this config through template or web dashboard (unless you remove the web port variable and manually put the port there}.

### Tell us how to replicate the bug

Not sure how this happened.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.0

### Operating system

Ubuntu 20.04

### Log capture

```shell
I just saw nginx trying to listen 8443 and 8080 port for one specific domain. This domain does not has any special config compared with others.

All domains of this server just use a special template for ssl config version to add this config, that always worked for us:

# BEGIN WebP Converter
    set $ext_avif ".avif";
    if ($http_accept !~* "image/avif") {
        set $ext_avif "";
    }

    set $ext_webp ".webp";
    if ($http_accept !~* "image/webp") {
        set $ext_webp "";
    }

    location ~ /wp-content/(?<path>.+)\.(?<ext>jpe?g|png|gif)$ {
        add_header Vary Accept;
        add_header Cache-Control "private" always;
        expires 365d;
        try_files
            /wp-content/uploads-webpc/$path.$ext$ext_avif
            /wp-content/uploads-webpc/$path.$ext$ext_webp
            $uri =404;
    }
    # END WebP Converter

So I do not think this code is the problem.
```

**Comment by franciscopaniskaseker** [comment]
Probably the question is in which situation nginx can start to listen 8443 and 8080 port? The nginx template use a variable to set the port, so was not a template config problem. The wrong port come from outsite of the template.

I am trying to reproduce this, but up to now without success.

**Comment by jaapmarcus** [comment]
When web_ssl_port and proxy_ssl_port is used instead web_ssl_port and web_port..


So far I know it should never happen and it fetches the settings from hestia.conf.

Probally impossible to repoduce on our servers with out missing information..
