### ISSUE TITLE
[Bug] Hestiacp 500 error after add SSL self-signed cert

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#3383]
### Describe the bug

I was testing one issue ( https://github.com/hestiacp/hestiacp/issues/3382 ), so I tried to edit one domain (without change anything) and save (to force recreate the virtualhost) and suddenly I got 500 error.

Then I discovered that if I try to save the domain config with ssl, I will always get 500 error.

### Tell us how to replicate the bug

1. with hestiacp 1.7.0 installed
2. add a domain
3. try to set self sgined cert

I can reproduce this in another hestiacp server that has nothing with the one that I was using to test for this issue. Seems to be a problem for 1.7.0 version.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.7.0

### Operating system

Ubuntu 20.04

### Log capture

```shell
2023-03-24 11:53:11 v-generate-ssl-cert  'xxx.com' '' 'US' 'California' 'San Francisco' 'MyCompany LLC' 'IT' '' 'json'
2023-03-24 11:53:22 v-delete-fastcgi-cache  'xxx' 'xxx.com'

Seems that the error happen when v-delete-fastcgi-cache is executed.
```

**Comment by ScIT-Raphael** [comment]
Already fixed, please check before you open a new issue report: https://github.com/hestiacp/hestiacp/pull/3374

**Comment by franciscopaniskaseker** [comment]
I checked in git search and I did not find any issue related. and when I manually checked I saw an issue related with cloudflare ssl, but now I know that is a problem for any kind of ssl.

thank you

**Comment by arielesp** [comment]
[error] 7402#0: *89 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_aliases in /usr/local/hestia/web/templates/pages/generate_ssl.php on line 23; PHP message: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/hestia/web/templates/pages/generate_ssl.php on line 23; PHP message: PHP Warning:  Undefined variable $back in /usr/local/hestia/web/templates/pages/generate_ssl.php on line 61"

**Comment by arielesp** [comment]
the error is not related to cloudflare 

Stack trace:
#0 /usr/local/hestia/web/edit/web/index.php(854): Hestiacp\quoteshellarg\quoteshellarg()
#0 /usr/local/hestia/web/edit/web/index.php(854): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream,

**Comment by jaapmarcus** [comment]
Yes we know 

v_ssl_home is not used in the html but still used In the script
