### ISSUE TITLE
[Bug] dns cluster - the master and the slaves do not synchronise

### ISSUE THREAD

**Issue by Scan4u** [hestiacp/hestiacp#3388]
### Describe the bug

Hi! Want to report new dns cluster sync bug. Got it after upgrade do 1.70.0
After executing of the v-sync-dns-cluster command on dns master, all ns records on my three dns cluster slaves removed, and the sync procedure is stopped after, and not working anymore.
To solve this issue I need to remove all three slaves from master using v-delete-remote-dns-host and reconnect them after using command v-add-remote-dns-host
But even than there is another problem - the SOA serial records on slaves are not changed anymore and hold on record "20230324**01**". In same time for example the master is already have a SOA serial "20230324**09**"
![зображення](https://user-images.githubusercontent.com/16424225/227653487-ed13e747-0406-4d9e-967f-086aa93596cb.png)
Please advise how to solve the issue with SOA serial sync and fix v-sync-dns-cluster issue?

### Tell us how to replicate the bug

-

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.70.0

### Operating system

Ubuntu 20.04.6 LTS

### Log capture

```shell
-
```

**Comment by jaapmarcus** [comment]
What method do you use to sync?
- Running behind a NAT?
- In case of hestia-zone  rdnc notify what is the out put

**Comment by Scan4u** [comment]
I have a white ip's on server and both three slaves, directly connected to the internet. No NAT.
All was worked fine before the 1.70 update, so it is not a problem of network config, I think.
Please advise how can I check the output in hestia-zone rdnc?

**Comment by jaapmarcus** [comment]
rndc notify {domain}
And check. then 
/var/log/syslog
And see:
```
Mar 25 12:02:03 cp named[3207948]: received control channel command 'notify'
Mar 25 12:02:15 cp named[3207948]: received control channel command 'notify {domain}'
Mar 25 12:02:15 cp named[3207948]: zone {domain}/IN: sending notifies (serial 2023032301)
```

**Comment by Scan4u** [comment]
result of the command rndc notify xxxxxxi.pp.ua on the master:
![зображення](https://user-images.githubusercontent.com/16424225/227715858-cbd2f1ef-d733-4925-bff8-32c6922b92bf.png)
and on the ns4 slave for same domain:
![зображення](https://user-images.githubusercontent.com/16424225/227715874-348028b1-d909-46c3-bbaf-56b45fa25788.png)
SOA serial on all slaves still stay 20230325**01**

**Comment by franciscopaniskaseker** [comment]
This change removed some customizations that we do (as we are using our internal proxy to read real ips).

I checked that now there is a file dedicated to this config: /etc/nginx/conf.d/cloudflare.inc

My question is: what do you think is the best way to customize this file? I mean, I do not want to use cloudflare config, but my own config.

Basically, as workaround, I can customize the file and set the file as immutable, but I want to know if there is a official way to disable the cloudflare script that update this file.

thank you for the excellent job!

**Comment by jaapmarcus** [comment]
This has nothing to do the issue... 

For support questions: 
https://forum.hestiacp.com

**Comment by franciscopaniskaseker** [comment]
removed. i wrote in wrong issue.
