### ISSUE TITLE
[Bug] does not accept domain after using subdomain as hostname

### ISSUE THREAD

**Issue by vitalisc** [hestiacp/hestiacp#3392]
### Describe the bug

mydomain.com on my server refused to load, despite having added it to the server.

To provide some context, my hostname is server.mydomain.com, and my nameservers are ns1.mydomain.com and ns2.mydomain.com. 
While https://server.mydomain.com  the subdomain i used as hostnameloads without issues but my main domain mydomain.com does not.

### Tell us how to replicate the bug

ok install new cpanel with your subdomain as hostname, create a user and add other domains then after somedays try and add the main domain to the cpanel
the main domain will not load 
when you check on mxtoolbox you will get loop detected https://prnt.sc/Scxxooqd8-dV

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.0

### Operating system

ubunto 22

### Log capture

```shell
where do i get the log?
```

**Comment by jaapmarcus** [comment]
Please use the forum. This is a support question and not a bug..

https://forum.hestiacp.com

Please provide domain aswell I can't debug any thing with out knowing the domain

**Comment by vitalisc** [comment]
i posted in forum https://forum.hestiacp.com/t/i-have-issues-using-my-domain-on-my-cpanel/9156/1
with domain details

**Comment by jaapmarcus** [comment]
Then there is no reason to create a bug report here...

**Comment by vitalisc** [comment]
> Then there is no reason to create a bug report here...

i did because the subdomain is working but main domain is not 
thats why i decided to report it as bug 
other domains i have are working without issues
