### ISSUE TITLE
[Bug] Quick Install [500] after update to 1.7.0-1.7.1

### ISSUE THREAD

**Issue by lapriente** [hestiacp/hestiacp#3398]
### Describe the bug

When I try to install WordPress, I get an internal server error [500]

### Tell us how to replicate the bug

1. Click on the Web tab.
2. Click on the domain.
3. Click on the Quick install button
4. Select WordPress
5. Got 500

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.0

### Operating system

Ubuntu 22.04

### Log capture

```shell
PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in /usr/local/hestia/web/src/app/System/HestiaApp.php:237
```

**Comment by jaapmarcus** [comment]
What happens when you run:
`/usr/local/hestia/bin/v-list-sys-php json`

**Comment by jaapmarcus** [comment]
See:
https://github.com/hestiacp/hestiacp/pull/3396/commits/496a57519af01597dce379e33797a33e904e9b72

**Comment by lapriente** [comment]
> What happens when you run: `/usr/local/hestia/bin/v-list-sys-php json`

```
[
        "7.4"
]

```
