### ISSUE TITLE
[Bug] Domain redirection disables itself

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3407]
### Describe the bug

After upgrading to 1.7 and checking on the domain redirection yesterday, it was gone again for one particular domain this morning. Also removed was the auto-redirect to HTTPS checkbox (though that hardly matters when the domain redirects anyways - maybe these should actually be merged to one setting, as both together make little sense).

It seems to happen for all domains with domain redirection and LE SSL setup, which is quite troubling.
Still trying to figure out when exactly it happens.

### Tell us how to replicate the bug

1. Configure Domain redirection + LE SSL for a domain
2. ? (maybe VM restart?)
3. View it again and see Domain redirection missing

We also still have `nginx restart failed` issues upon trying to confirm any change, but this seems unrelated as a manual restart fixes things

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.0

### Operating system

Debian 11.6 (x86_64)

**Comment by jaapmarcus** [comment]
Enable DEBUG_MODE to see why it is not restarting. 

We disable redirect for SSL creation as it takes  priority over .well-known ... 

And should enabled after completion

If it exits during on of those steps it disables it ...

**Comment by jaapmarcus** [comment]
And as there where other issues with restarting on your server in the past I think that should be step number one to debug the issue.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/3202#issuecomment-1486506783

As it is still the issue this is the cause of Ngixn not reloading I don't know any simple way restore to the original value after basic restart from nginx failure...
