### ISSUE TITLE
[Bug] Log full of errors

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3408]
### Describe the bug

I don't even know what to make of this.
We have issues with enabling SSL and nginx restarts and I am struggling to interpret the logs cause they have many error codes without descriptions of the error.

### Tell us how to replicate the bug

![image](https://user-images.githubusercontent.com/13354331/228173031-ee495456-3f6c-422c-b8e9-9d80edfd4ee9.png)

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.7.0

### Operating system

Debian 11.6 (x86_64)

**Comment by ScIT-Raphael** [comment]
There is currently no known issue, can you please upgarde to 1.7.1 first and check again?

**Comment by xeruf** [comment]
sorry my bad, I am already on 1.7.1 :)

**Comment by jaapmarcus** [comment]
All php errors are caused by the fact we usually don't check if it was set. It was fine in 7.4 but new requirements in php8.1 and 2 it is not possible. 

Should be fine. All the other this.  Probally need to check sperately but just merging every error log goes way beyond my willing to check it out
