### ISSUE TITLE
[Feature] Use of Secondary or Remote DB

### ISSUE THREAD

**Issue by dtuando** [hestiacp/hestiacp#3409]
### Describe the feature or change in detail

I see that there is a feature to add a Remote DB But not much documentation on how to use the remote database with hestiaCP at all. I can see that the database connection was added to my list. But I Can not figure out how to use it from there.  It would be nice if we could just select which database to use from the list.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
https://main.hestiacp.pages.dev/docs/server-administration/databases.html#remote-databases

When 1.8.0 goes live we will update the website
