### ISSUE TITLE
[Bug] New IP list -> Data Source contains empty list after submitting invalid form

### ISSUE THREAD

**Issue by tamas36** [hestiacp/hestiacp#3410]
### Describe the bug

When you don't fill everything out on the "New IP list" form, an error message is thrown.
On this page "Data Source" has missing all the options that was selectable before.

Before submitting the form:

![before](https://user-images.githubusercontent.com/5025998/228300101-91c29c36-6431-412f-a623-7cb8c6add99d.png)

After submitting the (invalid) form:

![after](https://user-images.githubusercontent.com/5025998/228300094-b7bde9b8-396d-4d8a-ab13-44bb062266e4.png)

### Tell us how to replicate the bug

1. Go to /add/firewall/ipset/
3. **Do not fill** "IP List Name" or "Data Source", so the form becomes invalid
4. Before submitting the form, observe that "Data Source" has many of selectable options
5. Submit the form (click on "Save")
6. Notice that "Data Source" now has only one selectable option, that is "Clear"

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.1

### Operating system

Debian 11.5

**Comment by tamas36** [comment]
It looks like the cause of the issue is that there are two `window.onload` event listener on the rendered source code when the form is invalid and the error message is displayed.

Here is the first one:
[add_firewall_ipset.php#L94](https://github.com/hestiacp/hestiacp/blob/main/web/templates/pages/add_firewall_ipset.php#L94)

And here is the second one:
[footer.php#L81](https://github.com/hestiacp/hestiacp/blob/main/web/templates/footer.php#L81)

Doing a quick test, it looks like the issue could be resolved by using `window.addEventListener('load')` instead, but I'm not sure if we should change it on both places or just in `add_firewall_ipset.php`.

What do you think?

**Comment by AlecRust** [comment]
Nice find. We should probably be using `window.addEventListener('load')` in both places.

I've included this change in #3403 which already modifies some of the code in question. Can confirm this fixes the issue.
