### ISSUE TITLE
[Bug] Webmail shows 500 error after changing system PHP version (8*)

### ISSUE THREAD

**Issue by saaiful** [hestiacp/hestiacp#3414]
### Describe the bug

Webmail should load normally and show the inbox of the selected email account. Webmail shows a 500 Internal Server Error page.

The error log shows that webmail is trying to use system php version. There is no option in Hestia Control Panel to set the PHP version for webmail separately.

### Tell us how to replicate the bug

1. Log in to Hestia Control Panel as admin
2. Go to Server > Configure > Web Server
3. Change the system PHP version from 7.4 to 8.0
4. Save the changes
5. Go to Mail > Webmail and try to access any email account

### Which components are affected by this bug?

Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

1.6.8

### Operating system

Ubuntu 18.04.4 LTS

**Comment by jaapmarcus** [comment]
Please make sure to update to the last version 

1.7.1 is out already. Run apt update && apt upgrade 

Roundcube should work fine with php8.0 or newer... 

Please try to restart nginx / apache2 and php8.0
