### ISSUE TITLE
[Bug] Custom Webmail templates not accepted 

### ISSUE THREAD

**Issue by ww7** [hestiacp/hestiacp#3419]
### Describe the bug

Custom Webmail templates not accepted by undefined reason. 

Hestia generates mail's Apache/Nginx configs based on disabled/default_disabled tpl’s instead of mailclient/default_mailclient tpl’s. 

I placed content of mailclient/default_mailclient tpl’s to disabled/default_disabled tpl’s and it works.

### Tell us how to replicate the bug

1. Configured Webmail PHP client (Afterlogic Aurora), hosted it as normal Webdomain (under admin user)
2. Created Apache mail templates mailclient.tpl and mailclient.stpl (https://github.com/hestiacp/hestiacp/tree/main/install/deb/templates/mail/apache2)
3. Created Nginx default_mailclient.tpl and default_mailclien.stpl (https://github.com/hestiacp/hestiacp/tree/main/install/deb/templates/mail/nginx)
4. Modified /usr/local/hestia/conf/hestia.conf line: to WEBMAIL_SYSTEM=‘roundcube,mailclient’
5. Activated Mailclient as Webmail at HestiaCP Mail settings

### Which components are affected by this bug?

Webmail 

### Hestia Control Panel Version

1.7.1

### Operating system

Ubuntu 20.4

### Log capture

```shell
Not found log files. No errors. How to troubleshot this?
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3420

Please check if it works

**Comment by ww7** [comment]
Works, fixed.
