### ISSUE TITLE
[Bug] Flarum Nginx template

### ISSUE THREAD

**Issue by Mel0ne** [hestiacp/hestiacp#3426]
### Describe the bug

Error in Nginx template for Flarum. The `root` parameter in the `server` block should be `%docroot%/public`.
The default Flarum directory is `public`. 

### Tell us how to replicate the bug

Not required

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.1

### Operating system

Debian 11

### Log capture

```shell
Not required
```

**Comment by jaapmarcus** [comment]
For https://github.com/hestiacp/hestiacp/tree/main/web/src/app/WebApp/Installers/Flarum

It needs to be installed in / of the domain...
