### ISSUE TITLE
[Feature] Add support for non-standard crontab syntax such as @reboot 

### ISSUE THREAD

**Issue by harryqt** [hestiacp/hestiacp#3428]
### Describe the feature or change in detail

Right now, HCP only accepts syntax  `* * * * *`.
It would be useful if it supports non-standard syntax such as `@reboot` or `@weekly`.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
`@weekly` is already supported by day of the week. 0 0 0

<img width="991" alt="Screenshot 2023-04-02 at 10 26 56" src="https://user-images.githubusercontent.com/9754650/229341418-476ac24e-4e25-4650-8304-a9ee8ae33031.png">

`@reboot` I assume are root user in that case create a cronjob at root user.  Use the root user for it...
