### ISSUE TITLE
Feature Request : Responsive web interface #web

### ISSUE THREAD

**Issue by myB0B** [hestiacp/hestiacp#343]
hi,
I love using Vesta CP and now testing Hestia CP
but WTF is this web design ?
Please... please !!
Make the web interface responsive and remove this hugly old school design !

**Comment by ghost** [comment]
Hi @myB0B,

We have a user interface refresh which will ship with the next release of Hestia, and we're aiming to get this release out as soon as we can barring any last minute show stopper bugs.
