### ISSUE TITLE
[Bug]  SSL routines:tls_process_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by sody1981** [hestiacp/hestiacp#3433]
### Describe the bug

using simple code:
$a = getimagesize("https://domain.com/image.jpeg")
yeilds the following error:

Got error 'PHP message: PHP Warning:  getimagesize(): SSL operation failed with code 1. OpenSSL Error messages: 
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /home/XXX/domain.com/public_html/tst111.php on line 5; PHP message: PHP Warning:  getimagesize(): Failed to enable crypto in /home/XXX/domain.com/public_html/tst00.php on line 5; PHP message: PHP Warning:  getimagesize(https://domain.com/image.jpeg)

the solution was to imports certs file:
wget http://curl.haxx.se/ca/cacert.pem -O /usr/local/ssl/cert.pem
apachectl restart

Thanks

### Tell us how to replicate the bug

1. create simple php file include one line:  $a = getimagesize("https://domain.com/image.jpeg")
2. navigate to it
3. yields the error in log file

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.1

### Operating system

debian 11

### Log capture

```shell
Got error 'PHP message: PHP Warning:  getimagesize(): SSL operation failed with code 1. OpenSSL Error messages: 
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /home/XXX/domain.com/public_html/tst111.php on line 5; PHP message: PHP Warning:  getimagesize(): Failed to enable crypto in /home/XXX/domain.com/public_html/tst00.php on line 5; PHP message: PHP Warning:  getimagesize(https://domain.com/image.jpeg)
```

**Comment by jaapmarcus** [comment]
I can only generate the error if I am using in self singed certificate. 

And even then the error doesn't solve the issue also:
print_r(openssl_get_cert_locations())

returns:
Array ( [default_cert_file] => /usr/lib/ssl/cert.pem [default_cert_file_env] => SSL_CERT_FILE [default_cert_dir] => /usr/lib/ssl/certs [default_cert_dir_env] => SSL_CERT_DIR [default_private_dir] => /usr/lib/ssl/private [default_default_cert_area] => /usr/lib/ssl [ini_cafile] => [ini_capath] => )

as path instead of /usr/local/ssl/ 


Also Apache2:
eris@cp:~$ php -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /usr/lib/ssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /usr/lib/ssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /usr/lib/ssl/private
    [default_default_cert_area] => /usr/lib/ssl
    [ini_cafile] => 
    [ini_capath] => 
)

**Comment by sody1981** [comment]
Hi,
are You using debian?
I have certs issued by lentsencrypt and not self signed

**Comment by jaapmarcus** [comment]
> Hi,
> are You using debian?
> I have certs issued by lentsencrypt and not self signed

Both Debian and Ubuntu ... 

What shows: 
php -r "print_r(openssl_get_cert_locations());"

**Comment by sody1981** [comment]
php -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /usr/local/ssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /usr/local/ssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /usr/local/ssl/private
    [default_default_cert_area] => /usr/local/ssl
    [ini_cafile] =>
    [ini_capath] =>
)

**Comment by sody1981** [comment]
and its php 8.2:
php -v
PHP 8.2.4 (cli) (built: Mar 16 2023 14:37:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies

**Comment by jaapmarcus** [comment]
```
root@dev:~# php8.2 -r "print_r(openssl_get_cert_locations());"
Array
(
    [default_cert_file] => /usr/lib/ssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => /usr/lib/ssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => /usr/lib/ssl/private
    [default_default_cert_area] => /usr/lib/ssl
    [ini_cafile] => 
    [ini_capath] => 
)
root@dev:~# php8.2 -v 
PHP 8.2.4 (cli) (built: Mar 16 2023 14:37:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies
root@dev:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
root@dev:~# 
```
Also PHP8.2 and also still 

I wonder if you have made special changes that caused the bug. So far I can see there is no need to Implement the changes

**Comment by sody1981** [comment]
hi made no changes at all... just installed hestia after I removed all old php package (the vps came with 7.4) and apache.

strange
