### ISSUE TITLE
[Bug] Allow v-backup-user to run even when automated backups are off

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3435]
### Describe the bug

```sh
sudo /usr/local/hestia/bin/v-backup-user owner
Error: BACKUP_SYSTEM is not enabled
```

I have local backups disabled in the server, but would expect the CLI to work regardless.
If needed through a flag like `--force`.

### Tell us how to replicate the bug

1. Disable local backups
2. `sudo /usr/local/hestia/bin/v-backup-user owner`

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.1

### Operating system

Debian 11.6 (x86_64)

**Comment by jaapmarcus** [comment]
If no there is no location is set there is no reason to "enable" backups

If you want to disable automatic backups delete the cronjob instead

https://github.com/hestiacp/hestiacp/blob/8404771aebcf8e5e32c13f26d6589ebd07225af3/bin/v-backup-user#L143
BACKUP_SYSTEM='rclone,local'

**Comment by xeruf** [comment]
I don't want to generally enable backups though, I'd be fine if I just get an archive of this one user into the current dir.
