### ISSUE TITLE
[Bug] Do not modify web redirect url

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3438]
### Describe the bug

The redirect url is always suffixed with a /
This breaks some redirects 

follow-up to https://github.com/hestiacp/hestiacp/issues/3323

### Tell us how to replicate the bug

1. Add a Web Domain
2. Add a redirect without slash at the end
3. It is displayed correctly
4. Check with 'curl -v`
5. The result ends in `/`

### Which components are affected by this bug?

Control Panel Backend, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.1

### Operating system

Debian 11.6 (x86_64)

**Comment by xeruf** [comment]
And there is a second issue now which was not there before:
If the redirect contains a port, it is removed on save, which just broke one of our most important redirects...

It even removes a port from the middle of the URL!

**Comment by jaapmarcus** [comment]
/ Got added by 
return $code \$scheme://$redirect\$request_uri;

Port was removed during the check  added it again
