### ISSUE TITLE
[Bug] HestiaCP v1.7.1 Error: Let's Encrypt new auth status 400

### ISSUE THREAD

**Issue by dhiraj1site** [hestiacp/hestiacp#3443]
### Describe the bug

After upgrading to v1.7.1 , lets encrypt certificate cannot be issued, the error is Error: Let's Encrypt new auth status 400 

Note - It works fine on v1.6.8

### Tell us how to replicate the bug

1. Upgrade hestia cp to v1.7.1
2. Add new web domain
3. Enable SSL For Domain -> Select Use Lets Encrypt to obtain SSL certificate
4. The error should appear ->  Error: Let's Encrypt new auth status 400

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.7.1

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
Please follow https://hestiacp.com/docs/server-administration/ssl-certificates.html#let-s-encrypt-validation-status-400 for additional debug informations. Usualy, this is not hestia related.

**Comment by dhiraj1site** [comment]
Fixed the issue, in case someone else is facing the same problem. 

1. Check if openssl is configured properly . Does `openssl version` show any errors?
2. If the problem is with openssl, navigate to `/usr/local/ssl` check if lib64 directory is present
3. Finally run `ldconfig /usr/local/ssl/lib64` 
4. Now the command `openssl version` should show the ssl version and you should be able to issue lets encrypt certificate properly
