### ISSUE TITLE
[Bug] Ajax forms not working in bitrix cms

### ISSUE THREAD

**Issue by akunich** [hestiacp/hestiacp#3453]
### Describe the bug

In this cms, there are often directories with a dot at the beginning of the name.
Everything worked fine with vestacp. This request did not work in hestiacp.

/bitrix/templates/elektro_flat/components/bitrix/catalog/template_name/bitrix/catalog.element/.default/popup.php

He got to the 
location ~ /\.(?!well-known\/|file) 

I had to return the old design to the template

    location ~ /\.ht    {return 404;}
    location ~ /\.svn/  {return 404;}
    location ~ /\.git/  {return 404;}
    location ~ /\.hg/   {return 404;}
    location ~ /\.bzr/  {return 404;}

I understand that this is not really a panel problem.
It was logical to forbid web access to hidden files.
I just think it will not be superfluous for you to know about the existence of cms with such a peculiarity.
Although, in fact, this is a bitrix cms bug.

### Tell us how to replicate the bug

1. Create a directory in the site folder with a dot at the beginning of the name
2. create any php file in this directory and access its url
3. Get http response 404

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.2

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
I don't think we need to update the existing template. For default security it not a bad idea to disable hidden by default. If certain software requires it you can use a a custom template
