### ISSUE TITLE
[Bug] backup number is always 1 on the admin/users page 

### ISSUE THREAD

**Issue by cr0c0dylus** [hestiacp/hestiacp#3454]
### Describe the bug

The admin/users page always shows "1" backup for any user. It doesn't matter what number is in the package.

![2023-04-09_11-03](https://user-images.githubusercontent.com/29104606/230761575-5279fecf-e06a-4c6d-a7ad-bc9f9f187ed4.png)

### Tell us how to replicate the bug

1. Login as admin
2. Open users page
3. Look at the backup column

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.2

### Operating system

Ubuntu 20.04.6 LTS

**Comment by jaapmarcus** [comment]
It shows the current usage what happens if you run v-backup-user admin

**Comment by cr0c0dylus** [comment]
I just ran `v-backup-user admin` and it increased. It's ok, thanks!

But I have another account with 0 backups in the package. The users page shows "1" in the backup column. But there is no backup menu if I log in as the user:

![2023-04-09_11-27](https://user-images.githubusercontent.com/29104606/230762644-ed4bb184-0fc0-4fbb-b3ba-665413f9a002.png)

![2023-04-09_11-30](https://user-images.githubusercontent.com/29104606/230762652-334ddd8e-231b-4a8b-8af2-f8f465d6cf0b.png)

**Comment by jaapmarcus** [comment]
If 0 backups are in the package by default we had the menu.. 

Probally in user.conf it still listed as 1 back up present

**Comment by cr0c0dylus** [comment]
Maybe it should be shown if there is at least one backup exists?

web/templates/includes/panel.php:
@@ -349,7 +349,7 @@

-                   <?php if ($panel[$user]["BACKUPS"] != "0") { ?>
+                   <?php if ($panel[$user]["BACKUPS"] != "0" || $panel[$user]["U_BACKUPS"] != "0") { ?>

**Comment by jaapmarcus** [comment]
User won't be able to create a backup anyways. It will only happens if an admin set the user package to 0 when there is already a backup in the user account. As v-backup-user will never run so it will never get updated...

**Comment by cr0c0dylus** [comment]
But if there is no menu available, neither the administrator nor the user can delete or download existing backups. This can be crucial in some cases.

**Comment by jaapmarcus** [comment]
> But if there is no menu available, neither the administrator nor the user can delete or download existing backups. This can be crucial in some cases.

But users won't be able to create new backups and if user was imported from a different user what is also possibles the back up won't be available any way.... 

If the admin changes the number of backups for a package or should check if it falls with on the limit and other wise shown an error than this case should never happen. So it looks like it is an bug on that side... 

You can still check if it exists and if needed increase the value to 1 in that package if needed...

**Comment by cr0c0dylus** [comment]
I created a post-install hook with the patch above. I think that the user should have access to his data even if the number of backups set to 0 by admin. I don't see the point of storing backup files on disk if they can't be used. Thank you for the clarification and great idea!

**Comment by jaapmarcus** [comment]
There should be never a backup be created for that user ...

**Comment by jaapmarcus** [comment]
Can confirm there is no check and after making your suggested changes:

<img width="416" alt="Screenshot 2023-04-09 at 13 43 51" src="https://user-images.githubusercontent.com/9754650/230770597-78237191-8d2c-453c-934d-d00a41cdeaae.png">

So the user is only able to "Download" the backup and not even restore it...
