### ISSUE TITLE
[Bug] Caching Issue

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#3455]
### Describe the bug

We have got several users using WordPress page builders (elementor or Divi) complaining that they are seeing cached pages. However we are offering Apache + Nginx stack which according to some doc I read doesn't do any caching. 

Is there a possibility of caching at the server level? 

### Tell us how to replicate the bug

Unknown at this point.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.10

### Operating system

Ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
Apache2+Nginx usualy only cache static files according to the cached file extension list while edit the web domain. Usualy this should not cache whole sites, also I do not have any issues on my side with the same setup. As this is more a support case than a bug report, please stick over to our forum. Also update to latest version, 1.6.10 is outdated.

**Comment by jaapmarcus** [comment]
Proxy cache is supported via the "Caching" template. But it is less advanced then fastcgi cache in configuration
