### ISSUE TITLE
[Feature] maybe hestia is not 100% ready to be used with PHP8

### ISSUE THREAD

**Issue by oantonioo** [hestiacp/hestiacp#3466]
### Describe the feature or change in detail

A good start for the jump would perhaps be to declare all the variables.

A lot of resources could be saved if variables were declared.
/var/log/hestia/nginx-error.log

Undefined variable $error
Undefined variable $ERROR
Undefined variable $v_record_id
Undefined array key "v_rule"
Undefined array key "v_ns3"
Undefined array key "v_quota"
Undefined array key "v_debug_mode"
Undefined array key "name"
Undefined array key "v_pgsql

and a few dozen more beads

although in reality the LOG that worries me the most is nginx-access.log, although I suppose this will be mandatory.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Feel free to patch them via PR :) there are other issues about it. Nothing major...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/3359

**Comment by enreda-net** [comment]
I understand him, I know he has more important things.

Before adding new features, the ideal would be to have the existing ones well.

A modular panel would be a perfect plan.
And you could order each module from 1 different person, I offer to program if you need it.

The user would have to install a 'HestiaCP Lite' and once in the panel, choose which modules he wants to install.

I offer to program for the community, the only problem is that I can only help with the PHP code, in bash it would not be very good.
