### ISSUE TITLE
Unable to send reset password[Bug] 

### ISSUE THREAD

**Issue by kikipatton** [hestiacp/hestiacp#3484]
### Describe the bug

When I reset password from login page, it returns "invalid host domain"

### Tell us how to replicate the bug

Tried using the subdomain via web
Tried using the public ip via web
Reconfigured SMTP Relay Sendinblue 

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.7.3

### Operating system

Debain 11

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3494

Should be fixed
