### ISSUE TITLE
[Bug] force redirect without $request_uri

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#3501]
### Describe the bug

The file generated when do a redirect to www.domain is without the $request_uri
if ($host != "www.domain.com") {
   return 301 $scheme://www.domain.com;
}

The file generated when do a redirect to domain (naked) its ok.
if ($host != "domain.com") {
   return 301 $scheme://domain.com$request_uri;
}

### Tell us how to replicate the bug

set force redirect in panel to www
when accessing the domain naked using any uri like domain.com/robots.txt is redirected to / 
the correct is redirect with uri complement

the issue occurs only in www

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.3

### Operating system

Debian 11

**Comment by arielesp** [comment]
sometimes this problem occurs to in naked domain ...

**Comment by jaapmarcus** [comment]
See last PR
