### ISSUE TITLE
[Bug] Getting error on console when using v-change-domain-owner

### ISSUE THREAD

**Issue by ANTONIOPSD** [hestiacp/hestiacp#3506]
### Describe the bug

Just like the title says, I get the next errors when using v-change-domain-owner to transfer a domain to a different user:

![imagen](https://user-images.githubusercontent.com/1978099/235117687-df3196b1-8655-4306-94b0-e8654325923f.png)

 ̶I̶'̶m̶ ̶h̶o̶s̶t̶i̶n̶g̶ ̶a̶ ̶p̶r̶e̶s̶t̶a̶s̶h̶o̶p̶ ̶w̶e̶b̶s̶i̶t̶e̶ ̶o̶n̶ ̶t̶h̶a̶t̶ ̶d̶o̶m̶a̶i̶n̶ ̶a̶n̶d̶ ̶t̶h̶e̶ ̶b̶a̶c̶k̶o̶f̶f̶i̶c̶e̶ ̶w̶o̶r̶k̶s̶ ̶b̶u̶t̶ ̶t̶h̶e̶ ̶f̶r̶o̶n̶t̶ ̶o̶f̶f̶i̶c̶e̶ ̶s̶h̶o̶w̶s̶ ̶a̶ ̶b̶l̶a̶n̶k̶ ̶p̶a̶g̶e̶,̶ ̶s̶o̶ ̶s̶o̶m̶e̶t̶h̶i̶n̶g̶ ̶m̶u̶s̶t̶ ̶b̶e̶ ̶w̶r̶o̶n̶g̶ ̶w̶i̶t̶h̶ ̶p̶e̶r̶m̶i̶s̶s̶i̶o̶n̶s̶.̶   (forget about the blank page, fixed, cache related)

Any ideas?

### Tell us how to replicate the bug

use v-change-domain-owner domain user

get errors

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.3 

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
I am not able replicate the issue  please provide more information....

**Comment by jaapmarcus** [comment]
With out any information we are not able to debug
