### ISSUE TITLE
[Bug] After auto-update, Nginx took over port 8083

### ISSUE THREAD

**Issue by aaronxn** [hestiacp/hestiacp#3507]
### Describe the bug

After auto-update, Nginx took over port 8083. 

See my post on the forum: https://forum.hestiacp.com/t/auto-update-broke-hestia/9471/5

Quick solution was:

1. Stop Nginx (freeing port 8083): `systemctl stop nginx`
2. Start Hestia (takes port 8083): `systemctl start hestia`
3. Start Nginx _last_ (so it doesn't take port 8083): `systemctl start nginx`

It’s a crude workaround, but it works.

### Tell us how to replicate the bug

The 'bug' was after the last auto-update. 

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.7.3

### Operating system

Ubuntu 20.04.6 LTS

### Log capture

```shell
root@ /etc/nginx# systemctl status hestia.service
● hestia.service - LSB: starts the hestia control panel
Loaded: loaded (/etc/init.d/hestia; generated)
Active: failed (Result: exit-code) since Fri 2023-04-28 17:00:58 UTC; 2min 23s ago
Docs: man:systemd-sysv-generator(8)
Process: 2454097 ExecStart=/etc/init.d/hestia start (code=exited, status=1/FAILURE)
CGroup: /system.slice/hestia.service

Apr 28 17:00:56 hestia[2454097]:  * Starting hestia-nginx hestia-nginx
Apr 28 17:00:56 hestia[2454100]: nginx: [emerg] bind() to 0.0.0.0:8083 failed (98: Address already in use)
Apr 28 17:00:56 hestia[2454100]: nginx: [emerg] bind() to 0.0.0.0:8083 failed (98: Address already in use)
Apr 28 17:00:57 hestia[2454100]: nginx: [emerg] bind() to 0.0.0.0:8083 failed (98: Address already in use)
Apr 28 17:00:57 hestia[2454100]: nginx: [emerg] bind() to 0.0.0.0:8083 failed (98: Address already in use)
Apr 28 17:00:58 hestia[2454100]: nginx: [emerg] bind() to 0.0.0.0:8083 failed (98: Address already in use)
Apr 28 17:00:58 hestia[2454100]: nginx: [emerg] still could not bind()
Apr 28 17:00:58 systemd[1]: hestia.service: Control process exited, code=exited, status=1/FAILURE
Apr 28 17:00:58 systemd[1]: hestia.service: Failed with result 'exit-code'.
Apr 28 17:00:58 systemd[1]: Failed to start LSB: starts the hestia control panel.
```

**Comment by ScIT-Raphael** [comment]
Please check your configs, nginx should not use port 8083, this is reseved for the hestia nginx process. Also I can't reproduce it over here.

**Comment by gOOvER** [comment]
cant confirm; works as it should

**Comment by jaapmarcus** [comment]
It is probably not reproducible on our side as it should not be the default config 
...
