### ISSUE TITLE
[Bug] Redirect Code is not respected when you edit a domain redirect

### ISSUE THREAD

**Issue by SamuelGaona** [hestiacp/hestiacp#3514]
### Describe the bug

When you modify a domain, activate domain redirection, and select the option to redirect to a custom domain, the redirect code value is not respected and is always set to 301, even if you select 302.

### Tell us how to replicate the bug

1. Edit a domain.
2. Activade domain redirection
3. Select custom domain redirection.
4. Select 302 as the redirection code.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Web Interface

### Hestia Control Panel Version

1.7.3

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3503

**Comment by jaapmarcus** [comment]
It looks like it is an issue in the Web interface only 

```
cat nginx.ssl.conf_redirect 
   return 302 https://hestiacp.com$request_uri;
```

Will look into in
