### ISSUE TITLE
[Bug] Report accurate quota use for empty entries

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3518]
### Describe the bug

A new mail-address or new web domain shows a use of 1MB by default, even if no content has been added.
This is confusing and makes it harder to find out whether there is actual content already in there.

We are migrating customers over, and just now I had the case that I had to recreate the account of a customer, with everything at 1MB I thought there was no data in the account and deleted it, only to find out later that there was data which I could have easily migrated if known beforehand.

My suggestion is to either trim the default content from the calculation or show KB values below something like 10MB, with preference for the former.

### Tell us how to replicate the bug

1. Create new web domain
2. See quota use is 1MB
3. Add a few small files
4. Quota use is still 1MB

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.3

### Operating system

Debian 11.6 (x86_64)

**Comment by jaapmarcus** [comment]
We calculate the disk usage with: 

nice -n 19 du -shm /home/user/web/folder/

So any value always becomes in megabytes and Linux decides to round it up... 

As our quotas have also calculated in megabytes it doesn't make sense to change that behaviour...
