### ISSUE TITLE
[Bug] The phpMyAdmin configuration storage is not completely configured...

### ISSUE THREAD

**Issue by anykeyist** [hestiacp/hestiacp#3520]
### Describe the bug

I got an error when logging into PhpMyAdmin:
```
The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated.
```
Executed the file _usr/local/hestia/install/upgrade/manual/migrate_phpmyadmin.sh_ to fix the issue and and got the following error : 
```
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'I1QhyQbLHWttpU7Z'' at line 1
```
The reason for the error: the use of IDENTIFIED BY password with GRANT statement has been deprecated since MySQL version 5.7.6. It means you need to use IDENTIFIED by password with CREATE USER or ALTER USER and apply GRANT PRIVILEGES

Possible solution (at lease it helped for me): comment the line _158_ in the file _usr/local/hestia/install/upgrade/manual/migrate_phpmyadmin.sh_:
```
# GRANT USAGE ON $PMADB.* TO `$PMAUSER'@'localhost' IDENTIFIED BY '$PASS';
```

### Tell us how to replicate the bug

Execute the file `usr/local/hestia/install/upgrade/manual/migrate_phpmyadmin.sh` 

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

v1.7.3

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Made some minor changes to the script issues should be solved :) Via PR
