### ISSUE TITLE
Dovecot TLSv [Bug] 

### ISSUE THREAD

**Issue by Kill3rR4zer** [hestiacp/hestiacp#3529]
### Describe the bug

Good day,

The Dovecot config shows that Dovecot uses at least TLSv1.2, but TLSv1.0 and TLSv1.1 are also used and these cannot be deactivated. Several from the Discord server have also confirmed this, it is not an individual problem.

### Tell us how to replicate the bug

Go to Services on Dovecot
2:Scroll down to /etc/dovecot/conf.d/10-ssl.conf

and then you can see the minimum TLSv1.2 although TLS1.1 and TLS1.0 are also activated

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

v1.7.3

### Operating system

Debian 11

**Comment by Kill3rR4zer** [comment]
Sorry if my English isn't that good, I'll describe the problem again in one sentence so that you can understand it better. in the Dovecot config it says the minimum TLSv1.2 should be used but for some reason it also uses TLSv1.0 and 1.1

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3528

Does solve the issue

**Comment by jaapmarcus** [comment]
@Kill3rR4zer 

Please try:
https://github.com/hestiacp/hestiacp/pull/3555

**Comment by jaapmarcus** [comment]
Support has been added by @myrevery  :heart:
