### ISSUE TITLE
help function missing in the last push + gabizz script generator

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#353]
-h or --help seams not working anymore since the last push
https://github.com/hestiacp/hestiacp/pull/352

@gabizz script missing -a no for no apache
https://gabizz.github.io/hestiacp-scriptline-generator/

### ref: 

> 
> \# Defining help function
> help() {
>     echo "Usage: $0 [OPTIONS]
>   -a, --apache            Install Apache        [yes|no]  default: yes
>   -n, --nginx             Install Nginx         [yes|no]  default: yes
>   -w, --phpfpm            Install PHP-FPM       [yes|no]  default: no
>   -o, --multiphp          Install Multi-PHP     [yes|no]  default: no
>   -v, --vsftpd            Install Vsftpd        [yes|no]  default: yes
>   -j, --proftpd           Install ProFTPD       [yes|no]  default: no
>   -k, --named             Install Bind          [yes|no]  default: yes
>   -m, --mysql             Install MariaDB       [yes|no]  default: yes
>   -g, --postgresql        Install PostgreSQL    [yes|no]  default: no
>   -x, --exim              Install Exim          [yes|no]  default: yes
>   -z, --dovecot           Install Dovecot       [yes|no]  default: yes
>   -c, --clamav            Install ClamAV        [yes|no]  default: yes
>   -t, --spamassassin      Install SpamAssassin  [yes|no]  default: yes
>   -i, --iptables          Install Iptables      [yes|no]  default: yes
>   -b, --fail2ban          Install Fail2ban      [yes|no]  default: yes
>   -q, --quota             Filesystem Quota      [yes|no]  default: no
>   -d, --api               Activate API          [yes|no]  default: yes
>   -r, --port              Change Backend Port             default: 8083
>   -l, --lang              Default language                default: en
>   -y, --interactive       Interactive install   [yes|no]  default: yes
>   -s, --hostname          Set hostname
>   -e, --email             Set admin email
>   -p, --password          Set admin password
>   -D, --with-debs         Path to Hestia debs
>   -f, --force             Force installation
>   -h, --help              Print this help
>

**Comment by JOduMonT** [comment]
in fact I had to use directly hst-install-debian.sh unless the installation won't reconize them

**Comment by gabizz** [comment]
i will revise and update the options tonight as per latest specs. sorry for the missing "a", promise to fix it asap :)

**Comment by JOduMonT** [comment]
@gabizz don't be sorry because you contribute to a project and you help the project and users ;)

**Comment by gabizz** [comment]
I have updated the web-ui install command generator a few hours ago

**Comment by Lupul** [comment]
Fixed in develop https://github.com/hestiacp/hestiacp/commit/40d57fa3928f801a60ef123b7031d611318ee2fe
