### ISSUE TITLE
hestia not running on debian9 issue with GLIBC

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#354]
On a fresh install from a template which I use since few month and was working yesterday with hestia.

Unit hestia.service has begun starting up.
Jun 18 19:55:12  hestia[23169]: Starting hestia-nginx: hestia-nginx/usr/local/hestia/nginx/sbin/hestia-nginx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (
Jun 18 19:55:12  hestia[23169]: /usr/local/hestia/nginx/sbin/hestia-nginx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/hestia/nginx
Jun 18 19:55:12  systemd[1]: hestia.service: Control process exited, code=exited status=1
Jun 18 19:55:12  systemd[1]: Failed to start LSB: starts the hestia control panel.
Subject: Unit hestia.service has failed
Defined-By: systemd
Support: https://www.debian.org/support

Unit hestia.service has failed.

The result is failed.
Jun 18 19:55:12  systemd[1]: hestia.service: Unit entered failed state.
Jun 18 19:55:12  systemd[1]: hestia.service: Failed with result 'exit-code'.

**Comment by ScIT-Raphael** [comment]
Hi @jodumont, I just edited your post to make it a bit more readable. I would like if you could work with the default issue template we've setup, this will help us to gain all important informations directly.

We've pushed today a new, big release - it looks like you found the first bug - we will get it checked.

**Comment by ScIT-Raphael** [comment]
We just pushed new deb packages for debian only, can you please run the following commands:
`apt update && apt --reinstall install hestia-nginx`

Please let us know if the package works on your system.

**Comment by ScIT-Raphael** [comment]
Ok, we've pushed new packages for php and nginx to our repository. Please use the following commands:

apt update
apt --reinstall install hestia-php hestia-nginx
systemctl start hestia

after that, hestia backend should be back properly. I would really appreciate your feedback!

**Comment by JOduMonT** [comment]
on my old installation (with the one I open the issue) and on a new installation it works!

but the install still finish with an error:

```
Installing Hestia Control Panel and required dependencies...
NOTE: This process may take 10 to 15 minutes to complete, please wait.../
(*) Updating SFTP subsystem configuration...
Upgrade phpMyAdmin to v4.9.0.1...
**sed: -e expression #1, char 0: no previous regular expression**
Job for hestia.service failed because the control process exited with error code.
See "systemctl status hestia.service" and "journalctl -xe" for details.
Error: hestia start failed
```

```
Jun 18 21:05:49  hestia[20623]: Starting hestia-nginx: hestia-nginx.
Jun 18 21:05:49  hestia[20623]: Starting hestia-php: hestia-php/usr/local/hestia/php/sbin/hestia-php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required
Jun 18 21:05:49  hestia[20623]: /usr/local/hestia/php/sbin/hestia-php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/hestia/php/sbin/
Jun 18 21:05:49  systemd[1]: hestia.service: Control process exited, code=exited status=1
Jun 18 21:05:49  systemd[1]: Failed to start LSB: starts the hestia control panel.
-- Subject: Unit hestia.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit hestia.service has failed.
--
-- The result is failed.
Jun 18 21:05:49  systemd[1]: hestia.service: Unit entered failed state.
Jun 18 21:05:49  systemd[1]: hestia.service: Failed with result 'exit-code'.
```

than as you recommend I execute

```
apt update
apt --reinstall install hestia-php hestia-nginx
systemctl start hestia
```

the services hestia is UP and RUNNING

**Comment by ScIT-Raphael** [comment]
The problem is the time - your log is from 21:05, we pushed new and fixed packages around 15 minutes ago :). Thanks for your bug report, nice that it works now!

**Comment by JOduMonT** [comment]
Debian on LXC don't like logout :P
`hst-install-debian.sh: line 1796: logout: not login shell: use `exit'`

**Comment by ScIT-Raphael** [comment]
Hmm, lxc with proxmox? Didnt noticed any issue here with logout.

**Comment by JOduMonT** [comment]
@ScIT-Raphael yes with proxmox, but anyway I would not open an issue for this :)
thanks for your help and your explanation

**Comment by Lupul** [comment]
> on my old installation (with the one I open the issue) and on a new installation it works!
> 
> but the install still finish with an error:
> 


Please post you complete install command

**Comment by JOduMonT** [comment]
@Lupul Raphael pretty well respond and contain the situation but if you insist

```
(reverse-i-search)`hst': bash hst-install-debian.sh -a no -w yes -o yes -k no -v no -c no -t no -s blah.blah.blah -e blah@blah.blah -p blahblah
```

**Comment by JOduMonT** [comment]
> Hmm, lxc with proxmox? Didnt noticed any issue here with logout.

my LXC image is probably more minimal than your:
`/sbin/nologin: also missing`
