### ISSUE TITLE
bug in Hestiacp backup restoration [Bug] 

### ISSUE THREAD

**Issue by iresha82** [hestiacp/hestiacp#3542]
### Describe the bug

Dear Hestiacp Support Team,

I am writing to report a bug with Hestiacp that I encountered after the last update. The issue is related to the inability to restore backups. I have tried to restore my backup on several VPS, including OVH France VPS, OVH USA VPS, and Hetzner VPS, and encountered the same issue each time. I am using Debian 11.

**When attempting to restore a backup, the following error message is displayed:**

root@login1:~# v-restore-user blog blog.2022-11-05_05-11-56.tar
-- USER --
2023-05-04 21:37:54 blog

-- WEB --
2023-05-04 21:37:56 mydomain.net
2023-05-04 21:38:07 mydomain1.com
sed: -e expression #1, char 39: unterminated `s' command
sed: -e expression #1, char 39: unterminated `s' command

**When trying to restore a backup, sometimes the following bug appears and the backup cannot be restored.:**

root@login2:~# v-restore-user blog blog.2023-03-02_02-08-04.tar
-- USER --
2023-05-04 21:26:26 blog

-- WEB --
2023-05-04 21:26:27 mydomain.net
2023-05-04 21:26:31 mydomain1.com

-- DNS --
2023-05-04 21:26:34 mydomain.net
2023-05-04 21:26:34 mydomain1.com

-- MAIL --
2023-05-04 21:26:35 mydomain.net
Error: WEBMAIL_ALIAS is not defined in hestia.conf.
Error: roundcube type is invalid
2023-05-04 21:26:37 mydomain1.com
Error: WEBMAIL_ALIAS is not defined in hestia.conf.
Error: roundcube type is invalid

-- DB --
2023-05-04 21:26:38 blog_blog
grep: /usr/local/hestia/conf/mysql.conf: No such file or directory
Error: mysql config parsing failed

### Which components are affected by this bug?

Control Panel Backend, Database (MariaDB, MySQL, PostgreSQL), Webmail (Roundcube, Rainloop)

### Hestia Control Panel Version

v1.7.4

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Please send an email with a link containing the backup so I can test it ...

For the second import it look like no roundcube / mysql has been installed

**Comment by iresha82** [comment]
> Please send an email with a link containing the backup so I can test it ...
> 
> For the second import it look like no roundcube / mysql has been installed

I will e-mail it

V 1.7.4 phpmyadmin seems to have a problem of not being installed.

MARIADB is installed but when going to cp.domain.com/phpmyadmin it appears as Not Found.

I use this command

wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

sudo bash hst-install.sh --apache yes --phpfpm yes --multiphp yes --vsftpd yes --proftpd no --named yes --mysql yes --mysql-classic no --postgresql no --exim yes --dovecot yes --sieve no --clamav no --spamassassin yes --iptables yes --fail2ban yes --quota no --api yes --interactive yes --with-debs no  --port '8083' --hostname 'cp.domain.com' --email 'name@gmail.com' --password '7455628@@@@A' --lang 'en'   

Does it need to be reported separately?

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/3543

**Comment by jaapmarcus** [comment]
Issue should be solved
