### ISSUE TITLE
MySQL not Installing on custom Installation [Bug] 

### ISSUE THREAD

**Issue by adion-gorani** [hestiacp/hestiacp#3543]
### Describe the bug

Tried to do fresh installation with custom install command from:
https://hestiacp.com/install.html

mysql ( mariadb ) not installed.

### Tell us how to replicate the bug

wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

 sudo bash hst-install.sh --port '8083' --lang 'en' --hostname 'xxxxxxxxxx' --email 'xxxxxxxxxxx' --password 'xxxxxxxxx' --apache no --phpfpm yes --multiphp no --vsftpd yes --proftpd no --named yes --mysql yes --mysql-classic no --postgresql no --exim yes --dovecot yes --sieve no --clamav yes --spamassassin yes --iptables yes --fail2ban yes --quota no --api yes --interactive yes --force no

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.7.4

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
ARM or Intel/AMD?

**Comment by adion-gorani** [comment]
AMD

**Comment by iresha82** [comment]
I have this problem

**Comment by jaapmarcus** [comment]
Testing a patch at the moment...

**Comment by jaapmarcus** [comment]
Fixed
