### ISSUE TITLE
[Bug] Error message "deleted" before shown due to register_shutdown_function

### ISSUE THREAD

**Issue by dfag86** [hestiacp/hestiacp#3547]
### Describe the bug

In the latest version of HestiaCP when I enter the domain and then backups. Then I want to backup manually, then no click confirmation window appears. In the background, however, the backup is done correctly and everything works, but there is no indication that this process has been queued.

### Tell us how to replicate the bug

1 enter user
2. Go to the backup tab
3. Performs backup manually by pressing a button.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

 1.7.5

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Issue was caused by :

register_shutdown_function("unset_alerts");

That "removes" the error messages when php ends. How ever if a redirect was used it did the same
