### ISSUE TITLE
[Bug] No predefined IP list available after update to 1.7.6

### ISSUE THREAD

**Issue by mozoilo** [hestiacp/hestiacp#3552]
### Describe the bug

I try to add new IP list but under "Data Sources" no predefined options are shown.

### Tell us how to replicate the bug

Login HCP updated to 1.7.6
Go to Configuration --> Firewall --> Manage IP List --> Add IP List
Show option in "Data Sources"
Options shown are just: Clear, Blacklist and IPVERSE

I've tried : 
#/usr/local/hestia/bin/v-update-firewall-ipset yes

No errors

### Which components are affected by this bug?

Firewall (Iptables, Fail2ban)

### Hestia Control Panel Version

1.7.6

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Can confirm the issue: 

<img width="819" alt="Screenshot 2023-05-08 at 10 03 49" src="https://user-images.githubusercontent.com/9754650/236770111-e2c5a42f-2847-4619-a436-a2dd90bae0c5.png">

**Comment by jaapmarcus** [comment]
Issue has been fixed
