### ISSUE TITLE
Well Done Everyone!!

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#356]
I know its not officially announced as a new release just yet but This really is a master piece!! from the beautiful UI all the way down to the nuts and bolts!! This a huge day for celebration! Great work everyone! Cheers!!

**Comment by ScIT-Raphael** [comment]
Hi Johnny, thanks for the warm words! We will prepare a changelog page for our website and work at the bugfixes on the new release. There was a lot of hard work, mostly done trough our two devs @kristankenney and @Lupul!

**Comment by JOduMonT** [comment]
I'm agree with @johnnyq , now I really feel Hestia have his own personnality and quality and it is not just a copy/fork of Vestia.

It is probably by habit but I feel I little bit lost with the new UI;
such as
- I have to think to login as and to logout my user
- looking for the save button which is only at the top right now

## but definitly love all the reorganization
