### ISSUE TITLE
[Bug] Per email domain SMTP Relay not working

### ISSUE THREAD

**Issue by campodoro74** [hestiacp/hestiacp#3564]
### Describe the bug

Emails sent from authenticated (external) users for the email domain are not using SMTP Relay configured for the email domain.

Smart host relay DOES work when using Global SMTP Relay

### Tell us how to replicate the bug

1. Enable smart host relay for email domain
2. Send email using configured email domain (P=esmtpa A=dovecot_login)
3. Email is not sent through configured SMTP Relay
5. Email sent using webmail **does** use the SMTP Relay

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.7.6

### Operating system

Debian 10

### Log capture

```shell
No log
```

**Comment by jaapmarcus** [comment]
How is the email send ? 

Please provide more logs... 

It should work fine if you have used Webmail /Smtp it was tested by me yesterday... 

If you use php make sure to use phpmailer or an smtp plugin
