### ISSUE TITLE
Mail DNS records being added when enable mail for this domain is unchecked

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#357]
### Brief issue description:
Mail DNS records being added when enable mail for this domain is unchecked

### Steps to Reproduce:
1. Click create web domain and uncheck enable mail for this domain

### Expected behavior:
The following DNS records should not be added if mail is unselected

_dmarc
SPF
MX
imap
pop
smtp
mail

### Operating system distribution and release:
Ubuntu 18.04.2

### HestiaCP Version:
1.0 Newly released =]

### Which branch are you using?
master

### What software is installed?
default

### Additional notes:
If mail is enabled at later date then the records should be added or readded

**Comment by johnnyq** [comment]
I added a web domain unchecked enable mail, deleted all records related to mail in the DNS. Then I added the domain manually under add mail domain, it did add some records webmail DKIM but it did not add mail MX SPF imap smtp or pop. I belive the way it should work is to check to see if the records exist and if not add them.

**Comment by ScIT-Raphael** [comment]
We will optimize this part for sure, thanks for your report!

**Comment by ghost** [comment]
The records that you're seeing are part of the default DNS templates and aren't dynamically added during domain creation. I'll add another template before we ship the hotfix for v1.00.0 which has no mail records in the interim and we'll revisit this for the next major release.

**Comment by johnnyq** [comment]
Awesome!! that Works! Thanks =]
