### ISSUE TITLE
[Bug] Time zone list on Debian 11

### ISSUE THREAD

**Issue by anykeyist** [hestiacp/hestiacp#3573]
### Describe the bug

In Debian 11 the list of available zones is incomplete, for example there is only Europe instead of Europe/Kyev.
This happens because the list of time zones in _/usr/share/zoneinfo_ is organized using symlinks (Ubuntu 22.04 using directories, so all is fine there), so the find does not follow the corresponding directories.

This seems to be easy fix, just make a change to the file _/usr/local/hestia/bin/v-get-sys-timezones_ ::

Before:`zones=$(cd /usr/share/zoneinfo/posix && find * -type f -or -type l | sort)`
After:`zones=$(cd /usr/share/zoneinfo/posix && find -L * -type f -or -type l | sort)`

### Tell us how to replicate the bug

1. In the control panel follow the next:  Configure Server -> Basic Options -> Time zone

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

v1.7.6

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Please submit a PR

**Comment by jaapmarcus** [comment]
Thanks
