### ISSUE TITLE
[Bug] MultiPHP config - unable to set different options for each version of php-fpm

### ISSUE THREAD

**Issue by anykeyist** [hestiacp/hestiacp#3575]
### Describe the bug

Settings entered in the web panel for any particular version of php-fpm will always be applied to all other versions of php-fpm. Cause: the _v-list-sys-php-config_ script incorrectly processes the number of existing php.ini files in /etc/php/*.

`v-list-sys-php-config plain`:
```
max_execution_time  60
max_input_time  60
memory_limit  1024M
error_reporting  E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors  Off
post_max_size  100M
upload_max_filesize  100M
max_execution_time  60
max_input_time  60
memory_limit  256M
error_reporting  E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors  Off
post_max_size  100M
upload_max_filesize  100M
config_path /etc/php/8.2/fpm/php.ini
/etc/php/7.4/fpm/php.ini
```
`v-list-sys-php-config json`:
```
{
    "CONFIG": {
        "memory_limit": "256M",
        "max_execution_time": "60",
        "max_input_time": "60",
        "upload_max_filesize": "100M",
        "post_max_size": "100M",
        "display_errors": "Off",
        "error_reporting": "E_ALL & ~E_DEPRECATED & ~E_STRICT",
        "config_path": "/etc/php/8.2/fpm/php.ini /etc/php/7.4/fpm/php.ini"
        }
}
```

Few things i noticed related to the file _v-list-sys-php-config_ (hope it will help) :
1. Line 67: `config_count=$(echo "$config_path" | wc -l)` - it is always 1. Better to use `wc -w`. but it should also be taken into account that for each version of php-fpm there are 2 php.ini files (_/etc/php/*/fpm/php.ini_ and _/etc/php/*/cli/php.ini_)
2. Line 69: `multiphp_versions=$(ls -d /etc/php/*/fpm/pool.d 2> /dev/null | wc -l)` - the same thing. Output is one line,  so it will be better to use `wc -w`

### Tell us how to replicate the bug

Just go to the server settings and try setting different values ​​for `memory_limit` for a particular version of php-fpm. This value will be applied to all installed versions of php-fpm.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

v1.7.6

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
We need to rewrite that part... 

So it can edit each version seperate...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/2297

Duplicate
