### ISSUE TITLE
Error 500[Bug] 

### ISSUE THREAD

**Issue by asielgu** [hestiacp/hestiacp#3578]
### Describe the bug

Error 500 on some wordpress and laravel sites. It is a .htaccess error. If I rename .htaccess it works. Please fix it. 

For example if im gonig to install some laravel app. It have error 500 because .htaccess.

### Tell us how to replicate the bug

when the site is setup on hectia
1. upload application
2. proceed to installation writing url/install
3. and I get error 500

or in wordpress with some sites when you are gonig to cutomize the site.

really i dont kwon what is happening 

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.6

### Operating system

ubuntu 20.04

**Comment by ScIT-Raphael** [comment]
this is not a reproducable bug, please check your related weblogs what exactly is causing the issue. As this is more a support case, please use https://forum.hestiacp.com.
