### ISSUE TITLE
[Bug] Hide usernames in /etc/passwd

### ISSUE THREAD

**Issue by eric-frost** [hestiacp/hestiacp#3580]
### Describe the bug

/etc/passwd is visible for all users and shows a list of all other users on the system.  I know this is how most Linux systems work, but most other services would consider it a vulnerability if a list of all their usernames were leaked.

#### Some other notes:

On a shared server with CPanel installed, `cat /etc/passwd` doesn't show other users on the server.  Perhaps they're using some kind of chroot jail?

A user can also see other users via `ls /home` but that can be fixed via `chmod 701 /home`.

If I do `chmod 640 /etc/passwd` and then login via SSH, then the user can no longer see other usernames in /etc/passwd, but every line of the terminal prompt begins with `I have no name!@server:~`

The command, `v-add-sys-sftp-jail username yes` doesn't seem to have any effect?

### Tell us how to replicate the bug

1. Create a new user 
2. Login as that user via SSH.
3. `cat /etc/passwd`

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.7.6

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
We don't have an jail for ssh users yet.

If you enable sftp jail and disable ssh login sftp jail works correctly.  So there is no bug...

This is an know issue

**Comment by eric-frost** [comment]
> If you enable sftp jail and disable ssh login sftp jail works correctly.

Even if I do this, a user can still see all other users by uploading this php code:

```php
<?php echo shell_exec('cat /etc/passwd');
```

**Comment by jaapmarcus** [comment]
> > If you enable sftp jail and disable ssh login sftp jail works correctly.
> 
> Even if I do this, a user can still see all other users by uploading this php code:
> 
> ```
> <?php echo shell_exec('cat /etc/passwd');
> ```

That will also not be solved with an ssh jail...
