### ISSUE TITLE
[Bug] Cluster Dns mode Slave receive only Master when upgrade key letsencrypt.

### ISSUE THREAD

**Issue by ccsipnow** [hestiacp/hestiacp#3588]
### Describe the bug

When Hestia starts updating letsencrypt it sends to DNS-SLAVE the wrong way.
I could verify that in 'v-delete-remote-dns-record' there is no line:
```
if [ "$DNS_CLUSTER_SYSTEM" != "hestia-zone" ]; then
```
It is generating the named.conf file wrongly.

### Tell us how to replicate the bug

In 

>> Alter:
```
#----------------------------------------------------------#
#                       Action                             #
#----------------------------------------------------------#

# Starting cluster loop
IFS=$'\n'
for cluster in $(cat $HESTIA/conf/dns-cluster.conf); do
```
>> for:
```
#----------------------------------------------------------#
#                       Action                             #
#----------------------------------------------------------#

# Starting cluster loop
if [ "$DNS_CLUSTER_SYSTEM" != "hestia-zone" ]; then
IFS=$'\n'
for cluster in $(cat $HESTIA/conf/dns-cluster.conf); do
```
Obs: close the if at the end.

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.6

### Operating system

Debian 11

### Log capture

```shell
# HOSTING - MASTER
2023-05-09 03:10:04 v-delete-web-domain-ssl-force  'fd_diremp' 'directorempresarial.com.br'
2023-05-09 03:10:05 v-restart-service  'bind9' ''
2023-05-09 03:10:05 v-delete-dns-record  'fd_diremp' 'directorempresarial.com.br' '32'
2023-05-09 03:10:06 v-restart-service  'bind9' ''
2023-05-09 03:10:06 v-add-dns-record  'fd_diremp' 'directorempresarial.com.br' '@' 'CAA' '0 issue "letsencrypt.org"'
2023-05-09 03:10:10 v-restart-service  'nginx' ''
2023-05-09 03:10:25 v-restart-service  'bind9' ''
2023-05-09 03:10:25 v-delete-dns-record  'fd_diremp' 'directorempresarial.com.br' '34'


# DNS - SLAVE
named.conf:

zone “ipnow.com.br" in {type slave; masters { 187.121.160.5; }; file "/home/dns-cluster/conf/dns/ipnow.com.br.db";};
zone “nicnet.com.br" in {type slave; masters { 187.121.160.5; }; file "/home/dns-cluster/conf/dns/nicnet.com.br.db";};
zone "directorempresarial.com.br" {type master; file "/home/dns-cluster/conf/dns/directorempresarial.com.br.db”;};
```

**Comment by jaapmarcus** [comment]
What  kind of setup do you currently use?

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/7ddbe1d0ac37f2629dda774efbcbcef666b191ec/bin/v-add-dns-record#L143-L151

Use the same code.. 

as v-delete-dns-record 


https://github.com/hestiacp/hestiacp/blob/7ddbe1d0ac37f2629dda774efbcbcef666b191ec/bin/v-delete-remote-dns-record#L45-L68

vs
https://github.com/hestiacp/hestiacp/blob/7ddbe1d0ac37f2629dda774efbcbcef666b191ec/bin/v-add-remote-dns-record#L59-L86

I assume this is the issue?

**Comment by ccsipnow** [comment]
With the implementation of DNSSEC I migrated my dns-cluster to slave type, adjusting the hestia.conf to:
DNS_CLUSTER_SYSTEM='hestia-zone'
DNS_CLUSTER='yes'
When there is automatic renewal of letsencrypt, dns_cluster receives the wrong instruction and launches the host as type Master.

Debugging, I made the mentioned adjustment and it solved the issue.

**Comment by jaapmarcus** [comment]
I noticed patched the issue in the pr attached

**Comment by jaapmarcus** [comment]
> With the implementation of DNSSEC I migrated my dns-cluster to slave type, adjusting the hestia.conf to: DNS_CLUSTER_SYSTEM='hestia-zone' DNS_CLUSTER='yes' When there is automatic renewal of letsencrypt, dns_cluster receives the wrong instruction and launches the host as type Master.
> 
> Debugging, I made the mentioned adjustment and it solved the issue.

Thanks for the report :) 

Will release a new version later today
