### ISSUE TITLE
Apache restart failed on Hestia update - webmail confs

### ISSUE THREAD

**Issue by vasike** [hestiacp/hestiacp#360]
### Brief issue description:
Hestia update generates empty apache webmail conf files, even the Hestia was installed without mail.
So the Apache fails to restart

### Steps to Reproduce:
1. Previous release install without mail - webserver only (apache with nginx)
2. Upgrade to new release

### Expected behavior:
Type here (e.g. A list of hosted web domains should appear).

### Operating system distribution and release:
Debian 9.9 (x86_64)

### HestiaCP Version:
0.9.8-29 to 1.00.0 (amd64) 190618

### Which branch are you using?
Releases only - auto upgrade

### What software is installed?
Apache + Nginx, Exim, MariaDB, vsftpd, cron, iptables, fail2ban

.....

**Comment by vasike** [comment]
solution - manually deletion of the webmail confs :(

**Comment by ScIT-Raphael** [comment]
Could you please share your logs when you try to restart apache2?

**Comment by vasike** [comment]
so after the auto upgrade last night (my time) i got this email

```
Usage: apache2 {start|stop|graceful-stop|restart|reload|force-reload}
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
```

and when i checked my apache was stopped 
and logs said that something wrong in the conf and webmail.domain.conf  was missing

i checked and i got for all domains those "webmail.domain.conf" empty files.
and in Hestia logs it says "enabled webmail support for domain" which is something i didn't ask for.

and as i said in my previous comment, i just delete those files and restart apache.

**Comment by Lupul** [comment]
Also /usr/local/hestia/conf/hestia.conf content would be usefull

**Comment by vasike** [comment]
```
WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='vsftpd'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
API='yes'
DB_SYSTEM='mysql'
BACKEND_PORT='8083'
MAIL_SYSTEM='exim4'
WEBMAIL_ALIAS='webmail'
RELEASE_BRANCH='develop'
VERSION='0.10.0'
```
