### ISSUE TITLE
[Bug] Laravel Vite doesnt work

### ISSUE THREAD

**Issue by icreaciones** [hestiacp/hestiacp#3601]
### Describe the bug

If use Laravel Vite for development proyect and configure Laravel Vite with domain, doesnt work.

**vite.config.js**
server: {
      https: true,
      port: 5173,
      host: 'laravelvite.innovacreaciones.com',
  },

**npm run dev**
error when starting dev server:
Error: listen EADDRNOTAVAIL: address not available myipaddress:5173
    at Http2SecureServer.setupListenHandle [as _listen2] (node:net:1468:21)
    at listenInCluster (node:net:1533:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1682:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)

Laravel Vite by default try to run a server...

### Tell us how to replicate the bug

1. Install Laravel application
2. Configure Laravel Vite with server domain and alias for domain.
3. Run in console: npm run dev

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.7

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
Error: listen EADDRNOTAVAIL: address not available myipaddress:5173

Port probably already in use...

I don't think it is related to Hestia it self...
