### ISSUE TITLE
[Bug] Apache2 and nginx not starting after system reboot

### ISSUE THREAD

**Issue by phenix-it** [hestiacp/hestiacp#3607]
### Describe the bug

Apache2 and nginx don't start after rebooting my system.

I'm using Debian 11, everything was working fine until I rebooted the system, after rebooting Apache2 and nginx stopped working

### Tell us how to replicate the bug

Apache2 and nginx don't start after rebooting my system.

I'm using Debian 11, everything was working fine until I rebooted the system, after rebooting Apache2 and nginx stopped working

![Screen Shot 2023-05-21 at 21 10 28](https://github.com/hestiacp/hestiacp/assets/103218321/bd97abb2-96e4-4bdc-a8d7-4e6ee98e4727)

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

v1.7.7

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Please check the log files / run

systemctl status nginx 
systemctl status apache2
