### ISSUE TITLE
Nginx not working after upgrade

### ISSUE THREAD

**Issue by killer30001000** [hestiacp/hestiacp#361]
### Brief issue description:
After upgrading to the develop release, nginx wouldn't start.
Error:
nginx: [emerg] invalid port in resolver "ipv6-adress" in /etc/nginx/nginx.conf:117

### Steps to Reproduce:
Automatic upgrade and ipv6 in /etc/resolv.conf file

### Expected behavior:
Nginx starting properly 

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
0.10.0

### Which branch are you using?
develop

### What software is installed?
Type here (e.g. Apache, Nginx, PHP-FPM, Dovecot/Exim, MariaDB, etc.)

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #0 or https://forum.hestiacp.com/...)

### Additional notes:
Fixed it by adding square brackes around the ipv6 in the nginx.conf:117

**Comment by ScIT-Raphael** [comment]
Thanks for the bug report, we already know the source of the issue and working on a fix.

**Comment by ghost** [comment]
We've temporarily restricted the nginx resolver to IPv4 until IPv6 support is properly implemented in Hestia. A new build will be released within the next 24 hours or so to resolve the initial issues with this release so long as we don't hit any last minute issues that prevent us from doing so.

**Comment by ScIT-Raphael** [comment]
Additional validation implemented with the following commit: https://github.com/hestiacp/hestiacp/commit/e6c69da4818e1c951f555f9437bac3b6439b88d1
