### ISSUE TITLE
rewrite BASH backend in GO

### ISSUE THREAD

**Issue by s3rj1k** [hestiacp/hestiacp#362]

**Comment by ScIT-Raphael** [comment]
Rewrite of backend is already on the roadmap - no delivery date yet.

**Comment by s3rj1k** [comment]
@ScIT-Raphael  I am curious in what language? If golang, I am willing to help out.

**Comment by ScIT-Raphael** [comment]
atm, we discussed to use a php framework as backend base - BUT we are open for other solutions. How would you handle it with golang? I just have no real knowledge about this language, bur I'm willing to learn :).

We just work to fix the issues we had in the current, unlucky (but tested!) release, sorry for the delay.

**Comment by s3rj1k** [comment]
writing some kind of RPC API with JSON would be one solution
writing simple REST API would be second

then fronted would need to send requests over some transport (HTTP for example) and read JSON responses

**Comment by s3rj1k** [comment]
RPC is more scalable, no need for tedious initial design 
REST needs some initial designing work

would go for RPC over HTTP

**Comment by ScIT-Raphael** [comment]
atm the backend works fully over the v-bash-scripts, also the existing api. So all requests sre handled over this scripts, that's the design of hestia (took over from vesta). Right now, the commands will be started over exec, the json answer will be decoded and showed in frontend.

**Comment by s3rj1k** [comment]
similar can be done in golang if needed
