### ISSUE TITLE
[Bug] Bandwidth Usage values are not correct

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#3624]
### Describe the bug

I believe that values showed in Bandwidth Usage values are not correct...
before some versions, I remember that was ok.

### Tell us how to replicate the bug

accessing /list/rrd/

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.7

### Operating system

debian 11

**Comment by jaapmarcus** [comment]
Images are still created and found on
/list/rrd/image.php?/rrd/net/daily-eth0.png

where eth0 is your ethernet port name

**Comment by arielesp** [comment]
![image](https://github.com/hestiacp/hestiacp/assets/10634047/bc6b9bd8-e295-4ae3-9506-cab8db3e6f1d)

**Comment by arielesp** [comment]
35.000.000 Kbytes is not correct ....

**Comment by jaapmarcus** [comment]
![image-test](https://github.com/hestiacp/hestiacp/assets/9754650/4cdec577-b293-406c-8a33-fe38b39f3757)

<img width="1093" alt="Screenshot 2023-05-25 at 22 53 24" src="https://github.com/hestiacp/hestiacp/assets/9754650/2fc69aab-1b70-407f-a569-87b4e874739b">

Looks fine to me...

**Comment by jaapmarcus** [comment]
We get the data from:

```
		rrdtool xport --json -s $start -e $end --step $step \
			DEF:inoctets=$RRD/net/$host.rrd:RX:AVERAGE \
			DEF:outoctets=$RRD/net/$host.rrd:TX:AVERAGE \
			XPORT:inoctets:"Input (rx)" \
			XPORT:outoctets:"Output (tx)"
```

**Comment by arielesp** [comment]
So, the values are confusing ... comparing image
30.000.000 ==== 300 M ???
![image](https://github.com/hestiacp/hestiacp/assets/10634047/d0909f86-30b5-4be8-a69f-3c0ebcdd868c)
