### ISSUE TITLE
[Feature] Allow changing password complexity policy

### ISSUE THREAD

**Issue by etfz** [hestiacp/hestiacp#3625]
### Describe the feature or change in detail

Hi,

I would like the ability to change the password complexity policy, including required length and required character classes. For example, I would like not to enforce inclusion of different character classes, but require longer passwords.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
I don't think the changes are worth to invest even 1 to 2 hours of our time on to it.

The current required settings are : minlength of 8
1 number 1 lowercase letter and 1 captital letter... 

The generate passwords currently also include any special char and length of 16. 

Feel to submit a PR for it. I don't mind including it but see no added value to develop it my self

**Comment by jaapmarcus** [comment]
Feel free to submit a PR.

Random Password generator can be found here:
https://github.com/hestiacp/hestiacp/blob/d65342e90e4580737097c55ae4c748ac63bfda3f/web/js/src/helpers.js#L1-L19
