### ISSUE TITLE
[Feature] Password generator for new users

### ISSUE THREAD

**Issue by etfz** [hestiacp/hestiacp#3626]
### Describe the feature or change in detail

When creating a new user, either an option to automatically generate a password that will only appear in the welcome mail (if checked) or, perhaps more simply, a button that generates a password for the password field according to the complexity policy.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by AlecRust** [comment]
Such a button already exists?

![image](https://github.com/hestiacp/hestiacp/assets/247634/3fbf3bd2-79ae-43e8-85e4-fa32683dca7b)

**Comment by etfz** [comment]
So it does. My bad. Completely missed that. (kinda wished it didn't generate special characters)
