### ISSUE TITLE
Notification panel shows "undefined" on clean installation

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#363]
### Brief issue description:
After performing a clean installation of v1.00.0 the notification panel displayed "undefined" when there are no notifications present.

### Steps to Reproduce:
1. Install latest release
2. Log into server
3. Click the notification bell

### Expected behavior:
The panel should display a string stating that there are no notifications.

### Operating system distribution and release:
Ubuntu 18.04 LTS

### HestiaCP Version:
1.00.0-190618

### Which branch are you using?
master

### What software is installed?
Nginx, PHP-FPM, MariaDB, vsftpd

### Screenshot
![Annotation 2019-06-19 102528](https://user-images.githubusercontent.com/40798553/59769696-0bea9100-927d-11e9-9981-1325f175126d.png)

**Comment by Lupul** [comment]
Fixed in commit https://github.com/hestiacp/hestiacp/commit/65c94ebe89acd92e70b4f628d128164ed86d1113
