### ISSUE TITLE
[Feature]: keep local backups even when FTP is full

### ISSUE THREAD

**Issue by Aviortheking** [hestiacp/hestiacp#3630]
### Describe the feature or change in detail

when FTP is full both the local and the FTP backups are not saved

It would be better to still try to keep the local backup

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
It is the user responsibility to monitor the available free space on the backup server 

I don't know if I want to run my local drive full with backups and depending on the user accounts it may result in disk space free when all the backups are stored for a longer period.
