### ISSUE TITLE
[Bug] I don't receive any kind of notification emails from hestia cp (Fresh installation)

### ISSUE THREAD

**Issue by stefanofattori** [hestiacp/hestiacp#3636]
### Describe the bug

Hello, I installed last versions of Hestia CP.
I configured a domain with mail domain, everything works fine.

**I don't receive any emails from hestia cp** like welcome mail, cron jobs event, backup event etc...

what could be the problem?
Which log can I read?

Thanks
Stefano

### Tell us how to replicate the bug

Add user checking send welcome mail, new backup, any notification emails from installation of hestiacp

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.7.7

### Operating system

Debian 11.7 (x86_64)

**Comment by ScIT-Raphael** [comment]
Please consider to use our discord channel or forum for support requests, as we want to use github for bug tracking only.
