### ISSUE TITLE
[Bug] Remote FTP backup doesn't work 

### ISSUE THREAD

**Issue by stefanofattori** [hestiacp/hestiacp#3637]
### Describe the bug

I configured remote FTP backup, the backup is created correctly on hestiacp but I can't see any file in my ftp storage.

### Tell us how to replicate the bug

New complete ftp backup
job is done correctly
no file on ftp storage
However Ideepl
 can download backup from backend even if i disabled local backup

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.7.7

### Operating system

Debian 11.7 (x86_64)

**Comment by ScIT-Raphael** [comment]
Same here, please use forum or discord, it may be a specific issue with your target server, ftp backup works well.

**Comment by stefanofattori** [comment]
ok thanks
