### ISSUE TITLE
[Bug] Error 500 page when saving server settings

### ISSUE THREAD

**Issue by stefanofattori** [hestiacp/hestiacp#3638]
### Describe the bug

Everytime I change and save server setting it show an error 500 page.
However the changes are saved correctly

### Tell us how to replicate the bug

https://hostname.domain.it:8083/edit/server/
make changes
save them
error 500
return back via browser

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.7.7

### Operating system

Debian 11.7 (x86_64)

**Comment by ScIT-Raphael** [comment]
please provide related nginx error log from /var/log/hestia/.

Maybe related to https://github.com/hestiacp/hestiacp/issues/3635.

**Comment by stefanofattori** [comment]
`2023/05/09 11:44:00 [error] 756#0: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: 151.55.86.158,>
2023/05/09 11:44:19 [error] 3365#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $ERROR in /usr/local/hestia/web/templates/pages/login/login_1.php on line 11" while reading response header from upstream, client: 151.55.86.1>
2023/05/09 11:44:40 [error] 3365#0: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_role" in /usr/local/hestia/web/edit/user/index.php on line 346" while reading response header from upstream, client: 151.55.86.158, server>
2023/05/09 11:45:11 [error] 3365#0: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "name" in /usr/local/hestia/web/add/user/index.php on line 160" while reading response header from upstream, client: 151.55.86.158, server: _>
2023/05/09 11:48:02 [error] 3365#0: *22 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.8>
2023/05/09 11:48:49 [error] 3365#0: *23 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: 151.55.86.15>
2023/05/09 11:48:52 [error] 3365#0: *23 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $ERROR in /usr/local/hestia/web/templates/pages/login/login_1.php on line 11" while reading response header from upstream, client: 151.55.86.>
2023/05/09 11:49:05 [error] 3365#0: *23 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_role" in /usr/local/hestia/web/edit/user/index.php on line 346" while reading response header from upstream, client: 151.55.86.158, serve>
2023/05/09 11:49:40 [error] 3365#0: *23 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.8>
2023/05/09 11:51:40 [error] 3365#0: *51 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.8>
2023/05/09 11:54:35 [error] 3365#0: *55 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.8>
2023/05/09 11:56:18 [error] 3365#0: *76 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.8>
2023/05/09 12:00:58 [error] 3365#0: *94 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: 198.235.24.3>
2023/05/09 13:17:33 [error] 3365#0: *96 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $error in /usr/local/hestia/web/templates/pages/login/login.php on line 11" while reading response header from upstream, client: 151.55.86.15>
2023/05/09 13:17:36 [error] 3365#0: *96 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $ERROR in /usr/local/hestia/web/templates/pages/login/login_1.php on line 11" while reading response header from upstream, client: 151.55.86.>
2023/05/09 13:22:25 [error] 3365#0: *109 open() "/usr/local/hestia/web/cgi-bin/authLogin.cgi" failed (2: No such file or directory), client: 185.180.143.188, server: _, request: "GET /cgi-bin/authLogin.cgi HTTP/1.1", host: "80.211.120.70:8083"
2023/05/09 13:44:13 [error] 3365#0: *134 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.>
2023/05/09 13:46:17 [error] 3365#0: *149 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.>
2023/05/09 13:47:46 [error] 3365#0: *159 FastCGI sent in stderr: "PHP message: PHP Notice:  Error: mysql username can be up to 32 characters long in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 46" while reading response header from upstr>
2023/05/09 13:48:45 [error] 3365#0: *163 FastCGI sent in stderr: "PHP message: PHP Warning:  Array to string conversion in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 30" while reading response header from upstream, client: 151.55.86.158>
2023/05/09 13:48:48 [error] 3365#0: *163 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.>
2023/05/09 14:08:15 [error] 3365#0: *184 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.>
2023/05/09 14:11:23 [error] 3365#0: *195 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.>
2023/05/09 14:19:54 [error] 3365#0: *216 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_rule" in /usr/local/hestia/web/edit/firewall/index.php on line 123" while reading response header from upstream, client: 151.55.86.158, >
2023/05/09 14:20:02 [error] 3365#0: *216 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_rule" in /usr/local/hestia/web/edit/firewall/index.php on line 123" while reading response header from upstream, client: 151.55.86.158, >
2023/05/09 14:20:20 [error] 3365#0: *216 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_rule" in /usr/local/hestia/web/edit/firewall/index.php on line 123" while reading response header from upstream, client: 151.55.86.158, >
2023/05/09 14:21:39 [error] 3365#0: *226 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url" in >
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.86.158, server: _, request: "POST /edit/server/ HTTP/1.1", upstr>
2023/05/09 14:21:59 [error] 3365#0: *235 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url" in >
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.86.158, server: _, request: "POST /edit/server/ HTTP/1.1", upstr>
2023/05/09 14:22:47 [error] 3365#0: *227 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url" in >
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.86.158, server: _, request: "POST /edit/server/ HTTP/1.1", upstr>
2023/05/09 14:25:42 [error] 3365#0: *263 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url" in >
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.86.158, server: _, request: "POST /edit/server/ HTTP/1.1", upstr>
2023/05/09 15:14:09 [error] 3365#0: *276 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url" in >
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.86.158, server: _, request: "POST /edit/server/ HTTP/1.1", upstr>
2023/05/09 15:20:18 [error] 3365#0: *286 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url" in >
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.86.158, server: _, request: "POST /edit/server/ HTTP/1.1", upstr>
2023/05/09 15:21:18 [error] 3365#0: *292 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url" in >
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.86.158, server: _, request: "POST /edit/server/ HTTP/1.1", upstr>
2023/05/09 15:23:12 [error] 3365#0: *307 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.>
2023/05/09 15:23:49 [error] 3365#0: *307 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_record_id in /usr/local/hestia/web/templates/pages/edit_web.php on line 411" while reading response header from upstream, client: 151.55.>`

**Comment by ScIT-Raphael** [comment]
Please only provide the relevant part when you click save.

**Comment by stefanofattori** [comment]
Sorry.

`2023/05/29 15:08:49 [error] 1169358#0: *1022 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_debug_mode" in /usr/local/hestia/web/edit/server/index.php on line 410; PHP message: PHP Warning:  Undefined array key "v_pgsql_url">
Stack trace:
#0 /usr/local/hestia/web/edit/server/index.php(1465): Hestiacp\quoteshellarg\quoteshellarg()
#1 {main}
  thrown in /usr/local/hestia/web/inc/vendor/hestiacp/phpquoteshellarg/src/Hestiacp/quoteshellarg/quoteshellarg.php on line 14" while reading response header from upstream, client: 151.55.195.184, server: _, request: "POST /edit/server/ HTTP/1.1", upst>`

**Comment by kaysersoze** [comment]
As a heads up, this looks like an issue where various $_POST array keys are being referenced, but they are not set. I've fixed this for my friend's install by doing several `isset(<affected key>) &&` in the conditionals where things were failing.

These are found in the file `/usr/local/hestia/web/edit/server/index.php` as referenced in the error message above.

Here is the list of the affected $_POST array keys and the lines on which they are found:
- v_php_versions (line 291)
- v_debug_mode (line 410)
- v_pgsql_url (line 669)
- v_policy_system_protected_admin (line 1460)
- v_policy_system_hide_admin (line 1533)
- v_policy_system_hide_services (line 1552)

I don't have time right at the moment to provide a patch, but it's simple enough to do on your local instance with a bit of PHP know-how. If I get a chance, I'll submit a pull request with some proper changes this week.

**Comment by jaapmarcus** [comment]
I know issues should been fixed in the main branch:
https://github.com/hestiacp/hestiacp

Will publish a beta release soon...

**Comment by mehargags** [comment]
Today I had same issue with a 2.5 yrs old Hestia Server. It was giving me internal 500 error whenever I was trying to 'edit a site' for any user. I then upgraded hestia ( it was marked on hold all this time).

Now I Can't seem to load the users page though v-list-users work fine
![image](https://github.com/hestiacp/hestiacp/assets/2650395/ddfd78d6-1bcc-45fb-9d49-950c17e25aee)

I see in hestao nginx error log this error

 tail -f /var/log/hestia/nginx-error.log
2023/06/26 16:19:45 [error] 718#0: *24 "/usr/local/hestia/web/list/users/index.php" is not found (2: No such file or directory), client: xxxx, server: _, request: "GET /list/users/ HTTP/1.1", host: "xxx"

why is it looking in /usr/local/hestia/web/list/users/ ('s' in the end for users) while the actual path is without 's'
/usr/local/hestia/web/list/user/

I guess some bug here.

**Comment by jaapmarcus** [comment]
Because it should be /users/

https://xxxxxx:8083/list/user/

It look like something has changed in /usr/local/hestia/web/

**Comment by mehargags** [comment]
so what do you suggest I should do?

**Comment by jaapmarcus** [comment]
Issue should be solved with 1.8.0 release
