### ISSUE TITLE
Webmail configuration routine error in install script

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#364]
### Brief issue description:
During a clean installation of 1.00.0 on a server without mail services, the console displays an error as Roundcube is not present.

![Clean Install](https://user-images.githubusercontent.com/40798553/59769805-3e948980-927d-11e9-8ffe-b8fdfa4e8f53.PNG)

**Comment by Lupul** [comment]
Fixed in commit: https://github.com/hestiacp/hestiacp/commit/af696f164884b4e3983531777d90a8c9ce291259
