### ISSUE TITLE
[Feature] Manage HestiaCP Releases over Gitlab Pipeline with renovate merges

### ISSUE THREAD

**Issue by torsten-online** [hestiacp/hestiacp#3640]
### Describe the feature or change in detail

Hi HestiaCP Community,

I want to manage my hestiacp server releases over a central gitlab instance.

Following Idea: 

> The Auto-Update Function of hestiacp should be changed to a root crontab script, 
> which is checking a file on non-root-disk, so when a gitlab merge is done - the renovate pipeline will create this file,
> so the auto-update function of hestiacp can run.

I want to ask the community if someone have a central gitlab instance already running, to manage releases?

I'am a little bit unhappy about the auto-update, because there are some problems at the past, which broke my server instances,
so the final testing of a new release will be a breacking feature,  I think.

If there is no existing, I can take care over this feature for hestiacp.

Kind regards
Torsten

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
We currently already run an test server where we test any changes of Hestia:

https://drone.hestiacp.com
https://github.com/hestiacp/hestiacp/blob/main/test/test.bats

How ever it has some major issues:
1. It doesn't restore Hestia to the last release but stacks it on top the current update
2. Failure rate for some tasks are way to high even 90% of the time it works fine. 
3. It is slow...
4. It lacks testing the interface side ...

**Comment by jaapmarcus** [comment]
Feel free to improve the CI / CD setup preferable with Drone ...  How ever will close the issue for now
