### ISSUE TITLE
[Bug] v-sync-dns-cluster don't sync the dns zone serial

### ISSUE THREAD

**Issue by setiseta** [hestiacp/hestiacp#3643]
### Describe the bug

on the slave dns server are new serials generated for the synced zones.

to fix the issue i called v-change-remote-dns-domain-soa on all zones / domains.
i think this should be done in the v-sync-dns-cluster run

### Tell us how to replicate the bug

execute v-sync-dns-cluster all zones on the slaves gets a new serial.

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.6

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
Can confirm the issue the soa is always set to:
YYYYMMDD01

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3660

Please check if this works
