### ISSUE TITLE
[Feature] backup suspended user / domain

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#3646]
### Describe the feature or change in detail

When a user / domain / database is suspended, backup does not run ... it is important, because, somentimes, we need move all users to another server and suspended users arent in backup. So I need unsuspend, do a backup, suspend again....

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Has been added for 1.8.0 release. Suspended web domains where already included

**Comment by jaapmarcus** [comment]
#3696

Feel free to make a donation to: https://hestiacp.com/donate.html
