### ISSUE TITLE
[Bug] HestiaCP MySQL Configuration Values Not Saving

### ISSUE THREAD

**Issue by iresha82** [hestiacp/hestiacp#3647]
### Describe the bug

There's a bug in HestiaCP related to MySQL on Debian 11. When Hestia auto-updates or when I manually update using "sudo apt-get update && sudo apt upgrade -y," the values of a field in MySQL's Configure Settings become empty. Even if I save the values multiple times, they don't get saved.

I attempted to change the values through Advanced Options, but the complete code is missing.

I've been experiencing this bug for several months. Please refer to the attached screenshots for further details.

![1](https://github.com/hestiacp/hestiacp/assets/132621350/35c455ce-19ea-466d-a1f6-f17b8a154603)
![2](https://github.com/hestiacp/hestiacp/assets/132621350/db6e9cd0-5a61-4bbd-af0e-bfc48a1600cd)

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

v1.7.7

### Operating system

Debian 11.7

**Comment by jaapmarcus** [comment]
duplicate...
