### ISSUE TITLE
[Feature] Support Debian GNU/Linux Bookworm

### ISSUE THREAD

**Issue by dabao1955** [hestiacp/hestiacp#3648]
### Describe the feature or change in detail

rt
When I run installation scripts，it noticed:
```
root@localhost /h/user# bash hst-install.sh
****************************************************
Your operating system (OS) is not supported by
Hestia Control Panel. Officially supported releases:
****************************************************
  Debian 10, 11
  Ubuntu 20.04, 22.04 LTS

root@localhost /h/user [1]# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@localhost /h/user#
```
Although bookworm is not released，but I still want you to support it.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Will be added after release ...

**Comment by jaapmarcus** [comment]
See: https://github.com/hestiacp/hestiacp/pull/3661

Please note I do not provide support it is really early basic alpha version for install instructions
https://hestiacp.com/docs/contributing/development.html#installing-hestia-from-a-branch

And untill we have have announced a beta version I would not try it in any production state
