### ISSUE TITLE
[Bug] Apache with Nginx Reverse Proxy !Alias auto generate wrong alias on domain creation!

### ISSUE THREAD

**Issue by xerudro** [hestiacp/hestiacp#3649]
### Describe the bug

When you create a domain on debian 11 server with Apache and Nginx as reverse proxy, when you go to domain details to generate and install SSL on the aliases field it auto add an auto generated alias that is not the correct version, using default templates, it adds an alias like this : test-servicii-it-net.servicii-it.net wich is an incorrect alias.

### Tell us how to replicate the bug

1. Click on Domains 
2. Click on Add Web Domain
3. Fill the required fields
4. Edit web domain
5. Select Enable SSS for this domain
6. Select Use Let's Encrypt to obtain SSL certificate
7.Select  Enable automatic HTTPS redirection
8.Enable HTTP Strict Transport Security 

If you did not notice the alias added to the field, it wont generate the SSL because of the wrong alias name added on that field.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2), Let's Encrypt SSL

### Hestia Control Panel Version

1.7.7

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
![Screenshot 2023-06-02 at 13 45 28](https://github.com/hestiacp/hestiacp/assets/9754650/8a1cedef-b8cb-4980-91cf-6151ab6ef330)

Keep it empty and it should work fine
