### ISSUE TITLE
[Feature] Custom buttons

### ISSUE THREAD

**Issue by hmdne** [hestiacp/hestiacp#3658]
### Describe the feature or change in detail

The feature would look like this:

As an admin:
- I have an option to create a custom button.
  - When creating/editing said custom button, I am able to give names for a number of text form fields (collectively: `$FF`)
  - Then, I am able to give a name of a Unix command prefix (`$UP`)

As user:
- I am given a menu, that would contain a list of custom buttons, described above
- When clicking a button, if there is more than 0 text form fields:
  - A form gets displayed
  - Otherwise skip to next point
- A command `$UP "$FF"` gets executed
- Result of that command is shown in a new page

(As a context, a customer asked me to develop a feature for HestiaCP and asks me for a price for that feature; this is just a crude project I came up with, so if you have a better idea to approach that goal, feel free to comment; I specifically want for such a feature to be upstreamed; my e-mail address is: hmdne@airmail.cc)

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Feature will be added in the future via Plugins:

https://github.com/hestiacp/hestiacp/pull/3645

**Comment by hmdne** [comment]
Writing plugins will need additional abilities compared to what I described.

My proposal could be implemented as a plugin though, in which case, I will still commission such a plugin.

**Comment by jaapmarcus** [comment]
Adding a custom menu  still require a developer to write some code to make it interactive so or get it working...

You can also just sed in the changes that you need to make via https://github.com/jaapmarcus/hestia-hooks

A specific feature in the Current state is not needed...
