### ISSUE TITLE
UI: Restart server does not display warning

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#366]
### Brief issue description:
When navigating to the Server page and clicking Restart, there is no confirmation/warning dialog displayed prior to issuing the restart command to the backend.

### Expected behavior:
Dialog should be displayed confirming whether or not you want to restart the server.

### Operating system distribution and release:
Ubuntu 18.04 LTS

### HestiaCP Version:
1.00.0-190618

### Which branch are you using?
master

**Comment by mehargags** [comment]
I saw the same... was about to open and issue but saw this already. Yes pls fix this with an alert confirmation taking in input of "yes"/ "No" from the user to avoid accidental reboot

**Comment by Lupul** [comment]
Even service actions 'stop', 'restart' are not asking configmation

**Comment by mehargags** [comment]
> Even service actions 'stop', 'restart' are not asking confirmation

That is fine... restart/stop is ok for services but Server restart should have an explicit alert notifying to the user.

**Comment by Lupul** [comment]
Fixed in the commit  https://github.com/hestiacp/hestiacp/commit/3d5ee58347231fe7451abc75c311b954e226490a
