### ISSUE TITLE
Random number generator error during installation

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#368]
### Brief issue description:
When performing a clean install of Hestia v1.00.0, an error is reported in the console during execution of random number generator routine. 

```Can't load /root/.rnd into RNG
139891345265088:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd```

**Comment by Lupul** [comment]
Fixed in https://github.com/hestiacp/hestiacp/commit/a738a7df35a6da5bc923ad7c00d3c20d30c8a164
