### ISSUE TITLE
[Bug] Nginx 1.25.1+ Listen ... http2" directive is deprecated

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#3684]
### Describe the bug

Update Nginx to 1.25.1 and restart server

[warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead

### Tell us how to replicate the bug

Update Nginx to 1.25.1 and restart server

[warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead

Changes required is to replace:
```
    listen      5.9.186.106:443 ssl http2;
```

With
```
    listen      ip:443 ssl;
    http2 on;
```

We should probally convert all the templates and sed them to the 1.25.0 pre format if nginx 1.25.0 or earlier is detected

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.x.x

### Operating system

N/A 

### Log capture

```shell
Update Nginx to 1.25.1 and restart server

[warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead
```

**Comment by jaapmarcus** [comment]
It looks like only "Webdomains" are affected 

https://github.com/hestiacp/hestiacp/blob/main/src/deb/nginx/nginx.conf

**Comment by myrevery** [comment]
This "issue" is not urgent yet.

NGINX usually removes obsolete directives after 5 major mainline version.

Suggested action: Send reminder to existing users, urging them to upgrade NGINX ASAP.

Reference: [NGINX's code](https://github.com/nginx/nginx/blob/release-1.25.1/src/http/modules/ngx_http_ssl_module.c#L477)

Also, what's the ETA of Hestia 1.8.0?

There are a few more features want to add, but I've been too busy lately...

**Comment by jaapmarcus** [comment]
> Also, what's the ETA of Hestia 1.8.0?
> 
> There are a few more features want to add, but I've been too busy lately...

No set time yet. How ever if Bookworm goes fine probably soon... How ever we probably want to wait for Mysql 8 support unless it take ages... 

I don't mind my self to have 1.9 following quick...

I agree that is has no priority yet how ever

**Comment by chriscapisce** [comment]
I got the same warning both for domains and webmail.

```
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/XX.XX.XXX.XX.conf:16

nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/domains/clientdomain.nl.ssl.conf:8

nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/domains/webmail.clientdomain.nl.ssl.conf:2
```

**Comment by jaapmarcus** [comment]
All Nginx configs with ssl enabled are effected ...

**Comment by myrevery** [comment]
A hotfix for this issue is on the way...

ETA is tomorrow (PDT).

**Comment by jaapmarcus** [comment]
> A hotfix for this issue is on the way...
> 
> ETA is tomorrow (PDT).

https://github.com/hestiacp/hestiacp/pull/3697

Should work fine

**Comment by TheRickDeckard** [comment]
Hi, with HestiaCP v1.7.8, nginx only, after generating Let's Encrypt for a just added user and domain (ssl for main domain, mail and webmail), nginx crash and cannot be restarted.

Deleting latest user show an error, the solution was manually removing related nginx conf files from /etc/nginx/conf.d/domains/ and after removing this user in HestiaCP.
Now the previous users are working but i can't add a new one.

Really need a fix asap. thanks.

**Comment by jaapmarcus** [comment]
This error doesn't prevent the system from working

**Comment by TheRickDeckard** [comment]
> This error doesn't prevent the system from working

Thanks for your reply but with nginx only on server, 
Nginx service crash and cannot be restart, the only fix find was removed latest just added user.

**Comment by jaapmarcus** [comment]
The warning generated should not matter. I don't know what the error message was...
