### ISSUE TITLE
[Bug] Add email alias

### ISSUE THREAD

**Issue by mdlaat** [hestiacp/hestiacp#3687]
### Describe the bug

If "a.b" is an existing emailalias for an user, one can not add a new alias "a" to that user.

### Tell us how to replicate the bug

1. Create a new mailuser "z"
2. Add an alias called "a.b" to that user
3. Save
4. Add an alias called "a" to that user
5. Save
6. Error: mail alias a is already exists

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.7

### Operating system

Ubuntu 22.04.1 LTS (Jammy Jellyfish)

**Comment by jaapmarcus** [comment]
<img width="606" alt="Screenshot 2023-06-14 at 21 33 43" src="https://github.com/hestiacp/hestiacp/assets/9754650/d39df3d8-aceb-4326-8bad-55eda3619bd0">

Can confirm the issue

Will fail...
