### ISSUE TITLE
v-update-host-certificate tries to symlink the the certificate in the old location

### ISSUE THREAD

**Issue by gabizz** [hestiacp/hestiacp#371]
### Brief issue description:
This morning, after the update, my Apache server on all my machines did not start. 
Examining the logs it looked like a ssl certificate issue, so I tried to run v-update-host-certificate admin $HOSTNAME and then I realized that the script was trying to symlink /usr/local/hestia/ssl/certificate.(crt|key) to /home/admin/conf/web/ssl.mydomain.(crt|key) and now the crt, key and pem files are in a subfolder called ssl.
So, after removing the key and crt files from hestia/ssl and running 
ln -s /home/admin/config/web/ssl/ssl.mydomain.key /usr/local/hestia/ssl/certificate.key
ln -s /home/admin/config/web/ssl/ssl.mydomain.crt/usr/local/hestia/ssl/certificate.crt
everything started normally (both hestia service  and apache2 service)

### Steps to Reproduce:
1. log via ssh to your machine and sudo su
2. try to restart apache2 and hestia

> systemctl restart apache2.service 
> systemctl restart hestia.service

2. examine apache2 error log 
> cat /var/log/apache2/error.log
look for errors mentioning the fact that your ssl key is empty

### Expected behavior:
apache2 and hestia services don't start/restart
you must, for now, manually symlink the certificates as explained above, and avoid using the bash script **v-update-host-certificate**

### Operating system distribution and release:
 Ubuntu 18.04 LTS

### HestiaCP Version:
1.0 migrated from 0.98

### Which branch are you using?
master

### What software is installed?
relevant for this case is Apache 

### Related issues or forum threads:
found none yet 

### Additional notes:
I suppose v-update-host-certificate and all ssl related bash scripts should be revised in order to comply with the new user config folder structure that puts ssh key,crt,pem in a subdirectory called ssl

**Comment by ScIT-Raphael** [comment]
Thank you for your issue report! We're facing a lot of problems with the last upgrade (for what we test it?! :)), we will check your issue asap and will work on a fix.

**Comment by ghost** [comment]
I'm unable to reproduce this issue, v-update-host-certificate copies the SSL certificates from the specified domain's SSL directory in line 55 & 56:

```
cp /home/$user/conf/web/$hostname/ssl/$hostname.pem $HESTIA/ssl/certificate.crt
cp /home/$user/conf/web/$hostname/ssl/$hostname.key $HESTIA/ssl/certificate.key
```

Can you please post your apache error log or the parts relevant to the issue? Thanks!

**Comment by gabizz** [comment]
Sorry, it happend in the morning, while I was driving when I was called by a customer that his site is not working, so I pulled right and started to debug  and all happend so fast 
The error was actually in ***syslog***

> nginx: [emerg] cannot load certificate "/usr/local/hestia/ssl/certificate.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/usr/local/hestia/ssl/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

then I did ls -lah /usr/local/hestia/ssl and saw that the symlinks were wrong. So I removed them and I tried to v-update-host-certificate but the truth is I actually wrote the NAME of the host not the global variable $HOSTNAME, and it didn't work. Then I symlinked manually and it started
The issues has been there on both (2) machines I have with Hestia

I have tried to reproduce the issue now, too, and you are right, now it works. 
I'll keep you informed if it appears again.

Thank you for your time
G.

**Comment by ScIT-Raphael** [comment]
Hi @gabbiz, thanks for your update! Due to the fact, that you we're not able to reproduce the issue again, I will close it. Please feel free to reopen it if you have additional informations or create a new one if you're facing different problems.
