### ISSUE TITLE
[Bug] restore user/domain, didnt restoring Custom document root

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#3712]
### Describe the bug

When restore user/domain, didnt restoring "Custom document root"

### Tell us how to replicate the bug

set domain to another custom document root ( another domain in same user per example )
backup user
delete user
restore user

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.7

### Operating system

ubuntu 22.04

**Comment by jaapmarcus** [comment]
It is probably because the web domain target doesn't exists ...

**Comment by arielesp** [comment]
I would like suggesting make a process to create the custom document root after finish restore all domains

thanks
