### ISSUE TITLE
Custom nginx templates missing after upgrade

### ISSUE THREAD

**Issue by FalzoMAD** [hestiacp/hestiacp#372]
### Brief issue description:
after the upgrade it seems that individually created nginx templates are missing in /usr/local/hestia/data/templates/web/nginx

this leads to empty nginx vhost files, breaking the affected domains

### Expected behavior:
the individual created templates should be left untouched

### Operating system distribution and release:
debian 9

### HestiaCP Version:
1.0

### What software is installed?
nginx + php-fpm (exim, dovecot)

**Comment by dvlpmt** [comment]
Is it possible to get template backups before update? I had more than 20 custom templates.

**Comment by ghost** [comment]
> Is it possible to get template backups before update? I had more than 20 custom templates.

Template files should be backed up under /root/hst_upgrade_<timestamp>/templates/.

**Comment by FalzoMAD** [comment]
> Template files should be backed up under /root/hst_upgrade_/templates/.

can confirm, this is the case.

**Comment by mehargags** [comment]
Can confirm as well... found the backup inside
`/root/hst_upgrade/190620190100/templates/templates/web/nginx`

Now I'm wondering more... if the backup was done, why was it not restored after the upgrade ? Was it a bug or was it completely left out in the upgrade procedure ?

I lost more than 20 sites on 4 different servers and created a panic situation, especially as I was on vacation to a distant highland with very bad internet connection.

**Comment by ScIT-Raphael** [comment]
definitely a bug, we also work with custom templates here and the function was tested multiple times. @kristankenney and @Lupul worked until early morning this night and already solved most parts for the bugfix release (https://github.com/hestiacp/hestiacp/projects/13#card-22993684). I work now on the analyse, why the template didnt get loaded back and created such a mess.

**Comment by ScIT-Raphael** [comment]
Found and eliminated the bug with the following commit: https://github.com/hestiacp/hestiacp/commit/90732edf651864631e58d77fd001b482833d9874

**Comment by Lupul** [comment]
@mehargags Were you using nginx+php-fpm or nginx+multiphp ?

**Comment by mehargags** [comment]
@Lupul I am using nginx+multiple php-FPM versions
have all versions of PHP installed that are in the install script... 5.6 to 7.3

**Comment by FalzoMAD** [comment]
~@Lupul @ScIT-Raphael as proposed by @mehargags we should narrow down the template lookup even more, to make sure we only catch templates that are default. assuming someone would clone one and just add a single word in front, this would be removed by the current grep as well...~

~maybe change it to:~ 

~> ls | grep -E '^PHP-[0-9][0-9]\.(s)?tpl?'~

~which should define the beginning and ending of the catch-phrase as well.~

nevermind, just noticed that the latest commit does not remove any templates at all.

**Comment by Lupul** [comment]
Updating web templates (data/templates/web/) was rewritten yesterday in this commit https://github.com/hestiacp/hestiacp/commit/085e2df950c26d20d030d5f9ca3dc72ec62fc601 
- no files are removed from that folder now (custom tpl are safe and are still backed-up on upgrade)
- when multiphp is enabled only PHP templates are overwritten
- nginx templates are not copied by default anymore

https://github.com/hestiacp/hestiacp/blob/085e2df950c26d20d030d5f9ca3dc72ec62fc601/bin/v-update-web-templates#L54-L82
