### ISSUE TITLE
[Bug] Public root dir is not being restored with backups

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#3727]
### Describe the bug

The customized root public dir is not being restored with hestiacp backups.

### Tell us how to replicate the bug

1. create account
2. add domain
3. customize the public dir
4. export the backup
5. delete the account
6. import the backup

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.7

### Operating system

ubuntu 22.04

### Log capture

```shell
Not sure if is related, but I always see two sed command error during the restore procedure:

-- WEB --
2023-06-28 12:59:50 xxx.yy
sed: -e expression #1, char 63: unterminated `s' command
sed: -e expression #1, char 63: unterminated `s' command
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/3712

Duplicate
