### ISSUE TITLE
WordPress Template robots.txt

### ISSUE THREAD

**Issue by MattFSGROUP** [hestiacp/hestiacp#3729]
### Describe the feature or change in detail

Hi,

Could I suggest a minor edit for the default WordPress nginx template please?

Can we amend the following section:

```
location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
```

To:

```
   location = /robots.txt {
        try_files $uri $uri/ /index.php?$args;
        log_not_found off;
        access_log off;
    }
```
Without this change, WordPress sites that use a PHP-generated ‘robots.txt’ instead of a 'real' robots.txt file give a 404 error.

Cheers

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
Does this apply to sitemap.xml too?

**Comment by jaapmarcus** [comment]
> Does this apply to sitemap.xml too?

Should be not affected by any existing rules so it should do in on default

**Comment by MattFSGROUP** [comment]
> Does this apply to sitemap.xml too?

This change doesn't affect sitemap.xml, I think that works out the box. Will double-check that though when I get chance.

**Comment by jaapmarcus** [comment]
It works fine:
<img width="1105" alt="Screenshot 2023-07-04 at 10 23 50" src="https://github.com/hestiacp/hestiacp/assets/9754650/b92e780b-8388-46b9-aa85-ff4b91c3ab95">
