### ISSUE TITLE
Custom hestia port is reset to 8083 after upgrade

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#374]
After yesterday's upgrade my Hestia port was reset to default 8083 but since I don't have 8083 allow rule in firewall, I could not access hestia backend.

Had to SSH in, use v-stop-firewall to enter into Hestia.

We need to preserve custom port if used 

Pardon the brevity , I'm typing it from my mobile

**Comment by ScIT-Raphael** [comment]
I can confirm the issue due to a missing recovery function in the upgrade routine to the new release:
https://github.com/hestiacp/hestiacp/blob/f651a7cc81fef548a015ab079590067ffde401f3/install/upgrade/0.9.8-28.sh#L59

**Comment by ghost** [comment]
Patch for this has been added to the upgrade script and we're aiming to push out a new build in the next 24 hours barring any last minute showstoppers. Sorry for any inconvenience that this may have caused.

**Comment by mehargags** [comment]
Can you pls document the commands to "try unreleased version" manually so that evaluators can check pre-released builds.  Raphael mentioned them sometime back but I forgot... I guess if documented on GIT homepage, it will help many people to contribute to evaluation
