### ISSUE TITLE
[Bug] Can't change selected language

### ISSUE THREAD

**Issue by MaxiZamorano** [hestiacp/hestiacp#3745]
### Describe the bug

When changing the language from the options it does not update, by default, it is always in English.

This also happened in beta 2.

### Tell us how to replicate the bug

1. Server settings
2. Configure
3. Basic Options
4. Default Language
5. Set as default language for all users

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.8.0 beta3

### Operating system

Ubuntu 22.04 LTS

**Comment by jaapmarcus** [comment]
Any non en locales don't work even when changing the settings manually

**Comment by jaapmarcus** [comment]
Bug was caused by a issue with the export from Crowdin
