### ISSUE TITLE
[Bug] Don't open firewall port if services are not installed

### ISSUE THREAD

**Issue by LtSich** [hestiacp/hestiacp#3747]
### Describe the feature or change in detail

atm when you make a custom install without some services (like dns or dovecot) that doesn't change the port that are open by default on the firewall.

At least the rule should disabled.

There are no security risk, as if there are no services the port will just stay close.
It's only to keep the minimal port open on the firewall.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We should do the same for FTP and SMTP...
