### ISSUE TITLE
[Bug] public_html permissions / ownership

### ISSUE THREAD

**Issue by hudokkow** [hestiacp/hestiacp#3748]
### Describe the bug

Morning everyone.

I have the domain error logs full off:

```
2023/07/04 18:06:49 [crit] 31735#31735: *885 open() "/home/xyz_user/web/example.com/public_html/" failed (13: Permission denied), ...
2023/07/04 18:06:49 [crit] 31735#31735: *885 open() "/home/xyz_user/web/example.com/public_html/" failed (13: Permission denied), ...
2023/07/04 18:06:54 [crit] 31735#31735: *885 open() "/home/xyz_user/web/example.com/public_html/" failed (13: Permission denied), ...
2023/07/04 18:06:54 [crit] 31735#31735: *885 open() "/home/xyz_user/web/example.com/public_html/" failed (13: Permission denied), ...
```

I noticed the permissions are set to 751 and ownership of `public_html` is set to `xyz_user:xyz_user`. Looking at https://github.com/hestiacp/hestiacp/blob/main/bin/v-add-web-domain#L122-L130, that is to be expected.

The problem is that it causes the errors above if, for instance, I set `WP_DEBUG_LOG` to true and it tries to write to wp-content/debug.log

After a quick search, I found https://forum.hestiacp.com/t/13-permission-denied-error-in-website-error-logfile/1130 and https://github.com/hestiacp/hestiacp/pull/866 but apparently none of the solutions presented where implemented.

Questions:

What would be the best course of action? Should I open a PR with the code changes? And if so, change permissions to 755 or ownership to www-data?

Thanks!

### Tell us how to replicate the bug

Any error log should have this.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.8

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
public_html main folder should be set to www-data user:

chown --no-dereference $user:www-data $HOMEDIR/$user/web/$domain/public_*html

as you can see in:
https://github.com/hestiacp/hestiacp/blob/bd0910154c92dac32a3127f4aefcbe0f1dfeabb4/bin/v-add-web-domain#L130

PHP should run by default under the user so all the permissions should be 644 / 755 for the user it should be fine

**Comment by hudokkow** [comment]
Actually I missed the  `chown --no-dereference $user:www-data $HOMEDIR/$user/web/$domain/public_*html` in the https://github.com/hestiacp/hestiacp/blob/main/bin/v-add-web-domain#L122-L130 code.

It doesn't seem to be working. I think `public_*html` isn't matching `public_html`. That's odd. `find . -name "public_*html"` matches it without problems.

**EDIT**
We commented at the same time! Sorry...

**Comment by jaapmarcus** [comment]
```
root@dev:/var/log/nginx/domains# v-add-web-domain jaap xxx.nu 
root@dev:/var/log/nginx/domains# cd /home/jaap/web/xxx.nu/
root@dev:/home/jaap/web/xxx.nu# ls
cgi-bin  document_errors  logs	private  public_html  stats
root@dev:/home/jaap/web/xxx.nu# ls -lah
total 32K
dr-xr-x--x 8 jaap jaap     4.0K Jul  5 12:13 .
drwxr-x--x 3 root jaap     4.0K Jul  5 12:13 ..
drwxr-x--x 2 jaap jaap     4.0K Jul  5 12:13 cgi-bin
drwxr-x--x 2 jaap jaap     4.0K Jul  5 12:13 document_errors
dr-xr-x--x 2 jaap jaap     4.0K Jul  5 12:13 logs
drwxr-x--x 2 jaap jaap     4.0K Jul  5 12:13 private
drwxr-x--x 2 jaap www-data 4.0K Jul  5 12:13 public_html
dr-xr-x--x 2 jaap jaap     4.0K Jul  5 12:13 stats
```

It seems to be working correctly

**Comment by hudokkow** [comment]
Weird. Just tried it and it works.

```
root@null01:/home# v-add-web-domain hudo xyz.xyz
root@null01:/home# cd hudo/web/xyz.xyz/
root@null01:/home/hudo/web/xyz.xyz# ls -lah
total 32K
dr-xr-x--x 8 hudo hudo     4.0K Jul  5 13:19 .
drwxr-xr-x 7 root hudo     4.0K Jul  5 13:19 ..
drwxr-x--x 2 hudo hudo     4.0K Jul  5 13:19 cgi-bin
drwxr-x--x 2 hudo hudo     4.0K Jul  5 13:19 document_errors
dr-xr-x--x 2 hudo hudo     4.0K Jul  5 13:19 logs
drwxr-x--x 2 hudo hudo     4.0K Jul  5 13:19 private
drwxr-x--x 2 hudo www-data 4.0K Jul  5 13:19 public_html
dr-xr-x--x 2 hudo hudo     4.0K Jul  5 13:19 stats
root@null01:/home/hudo/web/xyz.xyz#
```

A previous domain created in this machine didn't had the correct permissions. A glitch in the matrix, I guess.

Sorry for the noise. Closing the ticket.
