### ISSUE TITLE
It would be a cool idea to add a podman container component to Hestiacp so that it can run other programs on the container.

### ISSUE THREAD

**Issue by hestiacn** [hestiacp/hestiacp#3754]
### Describe the feature or change in detail

It would be a cool idea to add a podman container component to Hestiacp so that it can run other programs on the container. Please refer to this document for details. https://www.bilibili.com/read/cv20917247

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by ghost** [comment]
We will not be adding support for this as we believe in keeping the core of HestiaCP lightweight.
