### ISSUE TITLE
Ubuntu 16.04 - missing GLIBC 2.27/2.25

### ISSUE THREAD

**Issue by dvlpmt** [hestiacp/hestiacp#376]
After Hestia update, my server with more than 50 websites is down, seems like nginx configuration is messed up and on all websites I get only "Success!" pages.

Trying to start hestia service I get:

/usr/local/hestia/nginx/sbin/hestia-nginx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/hestia/nginx/sbin/hestia-nginx)

 /usr/local/hestia/nginx/sbin/hestia-nginx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/hestia/nginx/sbin/hestia-nginx)

Also my custom templates has been deleted. 

Thanks

**Comment by ghost** [comment]
Hi @dvlpmt, sorry to hear that you're having trouble with this release. We're currently working on resolving the reported issues and are aiming to have a new set of packages available within the next ~24 hours so long as we don't hit any showstoppers.

For the custom template files, they should be backed up under /root/hst_upgrade_<timestamp>/templates/ during the upgrade.

**Comment by dvlpmt** [comment]
Hi there, I've fixed this issue with GLIBC by upgrading to Ubuntu 18.04 LTS.

And found templates, thanks !

**Comment by ScIT-Raphael** [comment]
@dvlpmt I'm glad you found a fast solution for your issue! As @KristanKenney wrote, we will push new packages within ~24hrs, also new one for Ubuntu 16.04. Sorry for any inconvenience that this may have caused.

**Comment by ScIT-Raphael** [comment]
GLIBC error is fixed, new php and nginx packages are published to the repository.
