### ISSUE TITLE
[Bug] ipset add list error

### ISSUE THREAD

**Issue by hudokkow** [hestiacp/hestiacp#3762]
### Describe the bug

![ipset_add_error](https://github.com/hestiacp/hestiacp/assets/516183/f3cc4910-6941-47a5-99b4-65155c23d7d9)

DEBUG_MODE on shows `2023-07-11 11:14:55 v-add-firewall-ipset  'ip4-firehol-anonymous' 'https://iplists.firehol.org/files/firehol_anonymous.netset' 'v4' 'yes' [Error 1]` in hestia's error.log

### Tell us how to replicate the bug

Add an ipset list, https://iplists.firehol.org/files/firehol_anonymous.netset for instance.

cli `v-add-firewall-ipset ip4-firehol-anonymous "https://iplists.firehol.org/files/firehol_anonymous.netset"` works as expected.

### Which components are affected by this bug?

Firewall (Iptables, Fail2ban)

### Hestia Control Panel Version

1.8.0RC

### Operating system

Ubuntu 22.04

**Comment by hudokkow** [comment]
Please disregard. Apparently it is size related and it times out.

**Comment by jaapmarcus** [comment]
We should probably extend the time out then... 

It is 35 mb ...
