### ISSUE TITLE
[Bug] Starting hestia-nginx: hestia-nginxjq: error

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#3764]
### Describe the bug

after update 1.8.0, hestia not starting

hestia.service - LSB: starts the hestia control panel
   Loaded: loaded (/etc/init.d/hestia; generated)
   Active: active (exited) since Tue 2023-07-11 11:55:27 -03; 5s ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0
   Memory: 0B
   CGroup: /system.slice/hestia.service

Jul 11 11:55:27 deb20081704.servidor101.xyz systemd[1]: Starting LSB: starts the hestia control panel...
Jul 11 11:55:27 deb20081704.servidor101.xyz hestia[64288]: Starting hestia-nginx: hestia-nginxjq: error (at <stdin>:1): Cannot iterate over null (null)
Jul 11 11:55:27 deb20081704.servidor101.xyz systemd[1]: Started LSB: starts the hestia control panel.

### Tell us how to replicate the bug

update from 1.7.8 to 1.8.0

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.8.0

### Operating system

debian 10

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/cannot-start-hestia-nginx-after-upgrade-to-1-8-0/10027/12

**Comment by jaapmarcus** [comment]
Pinning for now please provide the debug in explained in the topic

**Comment by jaapmarcus** [comment]
Update has been released to solve the issue
