### ISSUE TITLE
[Bug]  HESTIA 1.8.0 upgrade does not respect custom backend port

### ISSUE THREAD

**Issue by EmsTatay** [hestiacp/hestiacp#3766]
### Describe the bug

After (automatic) upgrade to 1.8.0 the backend is NO LONGER accessible via custom port...
FIRST alert:  DNS cluster members FAIL because they use EXISTING custom port
SECOND:  BACKEND (HestiaCP admin panel) FAILS to load on custom port)

### Tell us how to replicate the bug

REPLICATE: automatic upgrade to 1.8.0 with existing custom port

checked hestai.conf - custom port is still set as before
opened default port 8083 in firewall 
backend DOES load on 8083
forum support (erris) suggested to to RE-Configure the custom port via CLI...
SOLVED the problem...

HOWEVER, any upgrades with custom port will be affected since nginx.conf will NOT inherit the custom port on upgrade.
In my case this broke the entire DSN cluster (obviously depending on custom port setting)

### Which components are affected by this bug?

Control Panel Backend, Control Panel Installation or Upgrade, Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.0

### Operating system

ubuntu 22.04

### Log capture

```shell
no log captures
```

**Comment by jaapmarcus** [comment]
Hmm have no issue on my test server when I run apt reinstall hestia-nginx

**Comment by EmsTatay** [comment]
Hello again...
My Ubuntu 22.04 auto-upgraded this morning...
shortly after I received several dozend eMails about DNS-SYNC-Failure from the other cluster peers...
attempt to login on backbend failed -- not loading
ssh (on another custom port)
added default port 8083 to the firewall AND connected to backend:8083 - WORKING

followed your suggestion to RE-issue the port configuration (nginx.conf NOW has the custom port again...)
problem fixed...

HOWEVER, NOT sure to use automated upgrades...
I will do a manual upgrade tomorrow and let you know if I see this repeating...

Thnaks for looking at this.

**Comment by jaapmarcus** [comment]
Can you check /var/log/hestia/error.log if you see v-change-sys-port failing?

**Comment by jaapmarcus** [comment]
Also share 

cat /usr/local/hestia/nginx/conf/nginx.conf | grep -m2 'listen'

**Comment by myrevery** [comment]
Key: [v-change-sys-port](https://github.com/hestiacp/hestiacp/blob/1.8.0/bin/v-change-sys-port#L59)

**Comment by myrevery** [comment]
#3593 causes "$ORIGINAL_PORT" get value 48083

**Comment by jaapmarcus** [comment]
Building hestia-nginx again where we remove the changes...

**Comment by jaapmarcus** [comment]
1.8.1 has been released solving then issue
