### ISSUE TITLE
[Bug]  Update v1.8.1 reset all the domains backend template to default

### ISSUE THREAD

**Issue by lianglee** [hestiacp/hestiacp#3771]
### Describe the bug

Update v1.8.1 reset all the domains backend template to default. My default template was not 'default' but different PHP fpm version.   Also got in email

```
The upgrade script has generated additional notifications, which must be heeded urgently:

About TLS 1.3 0-RTT anti-replay for NGINX

If you use custom templates, please update them (*.stpl) to apply this protection.

Follow the usage or other default templates:
/etc/nginx/conf.d/0rtt-anti-replay.conf
```

### Tell us how to replicate the bug

I have no idea the auto update v1.8.1  did the issue

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

v1.8.1

### Operating system

20.04.06

**Comment by jaapmarcus** [comment]
v-list-web-domain user domain.com json

It might be a bug in the admin only

**Comment by jaapmarcus** [comment]
SSL_FORCE:       yes
TEMPLATE:       default
BACKEND:        more_PHP7_4
PROXY:          caching

**Comment by lianglee** [comment]
I had to reset back to php8.1 fpm

**Comment by jaapmarcus** [comment]
I have updated my server and had no issues with it how ever you are not the first person reporting the issue 


The email if you use custom templates please read:
https://github.com/hestiacp/hestiacp/pull/3692

**Comment by xtrime-ru** [comment]
I also have similar issue. Last update broke https on all my domains. I use custom templates. All domains offered certificate for default site.

To fix the issue i had to change my templates (which was working correctly for many years):
FROM:
```
    listen      %web_ssl_port% ssl http2;
    listen      [::]:%web_ssl_port% ssl http2;
```
TO:
```
    listen      %ip%:%web_ssl_port% ssl;
    listen      [::]:%web_ssl_port% ssl;
    http2 on;
```

then run
```
v-rebuild-user admin
nginx -s reload
```

**Comment by cmstew** [comment]
> I also have similar issue. Last update broke https on all my domains. I use custom templates. All domains offered certificate for default

That is unrelated to this issue. Please open another issue if you believe it to be valid.

**Comment by jult** [comment]
> To fix the issue i had to change my templates (which was working correctly for many years): FROM:
> 
> ```
>     listen      %web_ssl_port% ssl http2;
>     listen      [::]:%web_ssl_port% ssl http2;
> ```
> 
> TO:
> 
> ```
>     listen      %ip%:%web_ssl_port% ssl;
>     listen      [::]:%web_ssl_port% ssl;
>     http2 on;
> ```

How is this not easily solved by a few sed lines in the update scripting?

Find and remove all

ssl 
http2

from lines with listen in nginx conf, and add 

http2 on;

if not exist, after listen*.; before next "}"

**Comment by jaapmarcus** [comment]
Quite easy how ever how many issue do we get when we change things. And then complain...
