### ISSUE TITLE
Unable to install MySQL 8.0 on Ubuntu 22.04 [Bug] 

### ISSUE THREAD

**Issue by 9ov7** [hestiacp/hestiacp#3772]
### Describe the bug

It is not possible to install HestiaCP with mysql8.
![image](https://github.com/hestiacp/hestiacp/assets/26053644/94a7c4b0-fa32-430b-8ea4-1f737a9975af)
![image](https://github.com/hestiacp/hestiacp/assets/26053644/d631f958-f2e6-47d4-ba31-7ab3c11a4719)

### Tell us how to replicate the bug

Try to install hestiaCP with mysql8 argument.

```shell
sudo bash hst-install.sh --port '8083' --lang 'en' --hostname 'hst.server.com' --apache yes --phpfpm yes --multiphp yes --vsftpd yes --proftpd no --named yes --mariadb no --mysql8 yes --postgresql no --exim yes --dovecot yes --sieve no --clamav yes --spamassassin yes --iptables yes --fail2ban yes --quota no --api yes --interactive yes --force no
``` 

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.8.1

### Operating system

Ubuntu 22.04

### Log capture

```shell
Hmm..nothing
```

**Comment by 9ov7** [comment]
1) Made an installation string.
![image](https://github.com/hestiacp/hestiacp/assets/26053644/f0a315ba-4772-4418-96ad-46ba0ade2ce2)
Trying to install with mysql8 , but it's impossible...
![image](https://github.com/hestiacp/hestiacp/assets/26053644/87ef3d03-616b-4c67-8260-d2a12123634c)

2) maybe if we use only --mysql8 options - we can?
`bash hst-install.sh --mysql8 yes`
![image](https://github.com/hestiacp/hestiacp/assets/26053644/d35d57dc-3379-4411-b56d-6d648e23b22e)

**Comment by 9ov7** [comment]
![image](https://github.com/hestiacp/hestiacp/assets/26053644/b273b3ce-f832-4a1a-bc02-c1296317b9ca)
After installing without mysql server, there is no way to add a database, or have I made a mistake somewhere?
https://hestiacp.com/docs/reference/cli.html#v-add-database-host
![image](https://github.com/hestiacp/hestiacp/assets/26053644/80233074-5911-4cf0-9c3f-5f30023f78a0)

============== For fix this : 

![image](https://github.com/hestiacp/hestiacp/assets/26053644/d4e3c2f2-3af4-4758-aa5d-eb70e6d5aa54)
`echo "DB_SYSTEM='mysql'" >> /usr/local/hestia/conf/hestia.conf`

**Comment by jaapmarcus** [comment]
Change: mysqlclassic to mysql8 on line 249 in a few minutes I will I will submit a PR for it
