### ISSUE TITLE
[Bug] Internal Server Error 500 when viewing system log from Web Interface

### ISSUE THREAD

**Issue by Kill3rR4zer** [hestiacp/hestiacp#3773]
### Describe the bug

Good day,

whenever I go into hestia aud logs an internal server error comes up

in the error messages I get this error:

#1 {main}
  thrown in /usr/local/hestia/web/list/log/index.php on line 32" while reading response header from upstream, client: 79.195.144.180, server: _, request: "GET /list/log/?user =system&token=9874a8a1b9c87758bb6e52a24a8b41fb HTTP/2.0", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "dash.zelx.io:8083", referrer: "https://dash. zelx.io:8083/list/server/"
2023/07/12 21:59:31 [error] 3351#0: *29 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: array_reverse(): Argument #1 ($array) must be of type array, null given in /usr/local/hestia/web/list/log/index.php:32
Stack trace:
#0 /usr/local/hestia/web/list/log/index.php(32): array_reverse()

I am sending you 2 screenshots.

Best regards
Nico
![Screenshot_2023-07-12-22-00-01-994_com android chrome-edit](https://github.com/hestiacp/hestiacp/assets/126006147/617f30aa-a8d4-4cc5-b732-bac3dfebc04d)
![Screenshot_2023-07-12-21-59-42-637_com android chrome-edit](https://github.com/hestiacp/hestiacp/assets/126006147/4c398000-67d4-405f-b187-518877b41a32)

### Tell us how to replicate the bug

1: Log into hestiacp
2:Go to Server Settings
3:Press Logs

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.8.1

### Operating system

Debian 11

**Comment by ghost** [comment]
From the command line:
```
cd /usr/local/hestia/data/users/admin/
mv system.log system.log.bak
touch system.log
```

Try accessing the page from the Web Interface again and kindly let us know if the issue has been resolved.
