### ISSUE TITLE
[Bug]  Max open files 

### ISSUE THREAD

**Issue by neovim17** [hestiacp/hestiacp#3774]
### Describe the bug

hi ! I have a server 4 CPu and 4gb RAM, os = ubuntu22.04. HestiaCP works good. If i add 337 domain my nginx down and do not restart. But if i have 336 domain hestia works good.

### Tell us how to replicate the bug

Add a 337 domain and restart nginx.service

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.7.6

### Operating system

Ubuntu 22.04

### Log capture

```shell
errors in logs :
Starting nginx - high performance web server...
nginx: [emerg] socket() 127.0.0.1:80 failed (24: Too many open files)
nginx.service: Control process exited, code=exited, status=1/FAILURE
nginx.service: Failed with result 'exit-code'.
Failed to start nginx - high performance web server.
```

**Comment by LtSich** [comment]
This is exactly why I use custom template to log everything in 1 place in vhost_combined format...
Each vhost is 3 another log file... (byte+access+error)

For the moment you have to increase your limits for the user www-data and the nginx/apache services...

Do you know how to do that ?

**Comment by jaapmarcus** [comment]
https://hestiacp.com/docs/server-administration/troubleshooting.html#error-24-too-many-open-files

**Comment by neovim17** [comment]
> This is exactly why I use custom template to log everything in 1 place in vhost_combined format... Each vhost is 3 another log file... (byte+access+error)
> 
> For the moment you have to increase your limits for the user www-data and the nginx/apache services...
> 
> Do you know how to do that ?

Hi, now I will try to increase the limits, but preceding this is do not work. Can i ask you show you custom template to log everything?

**Comment by neovim17** [comment]
> https://hestiacp.com/docs/server-administration/troubleshooting.html#error-24-too-many-open-files

thanks, i create a /etc/systemd/system/nginx.service.d/override.conf and write in file
[Service]
LimitNOFILE=65536
after
systemctl daemon-reload
and all works and nginx restart successful

**Comment by LtSich** [comment]
You should first try to follow instruction given by @jaapmarcus . (it's what you have done apparently).


But if you want to use a single log file you have multiple things to change.
 - In /etc/apache2/apache2.conf
You have a line like this : 
`LogFormat "%v %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined`
You have to change %h to %a

Add this line : `ErrorLogFormat "[%{u}t] [%-m:%l] [pid %P:tid %T] %7F: %E: [client %a] %M% ,\ referer\ %{Referer}i %v"`
This will add the vhost in the error log.

 - In /etc/nginx/nginx.conf add this log line to add a new log format, again, this allow you to get the vhost for each request : 
`log_format host '$host $remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent"';`

- Then the template, for apache you have 2 solution, with ou without php-fpm.
Depend on your configuration you have to create a new template (https://hestiacp.com/docs/server-administration/web-templates.html)

For apache you can copy the default template you use and make this change : (the line with # are the existing one that you have to comment)
```
#    CustomLog /var/log/%web_system%/domains/%domain%.bytes bytes
#    CustomLog /var/log/%web_system%/domains/%domain%.log combined
#    ErrorLog /var/log/%web_system%/domains/%domain%.error.log
     CustomLog /var/log/apache2/access.log vhost_combined 

```

For nginx (but access log is deactivate by default I think) : 
```
#            access_log     /var/log/%web_system%/domains/%domain%.log combined;
#            access_log     /var/log/%web_system%/domains/%domain%.bytes bytes;
            access_log  /var/log/nginx/access.log host;
```

Note : if you use awstats this will break your stats... 

With this configuration you should remove 3 logs file for apache and 2 for nginx (but nginx there is access_log off; in the config).
And every vhost will log in only 1 file for the access, and 1 for the error.

You can then use grep to filter the output when you monitor your logs.
Another note, you probably won't be able to read the log from user, but you will need to switch to root for that.

**Comment by neovim17** [comment]
> ```
>             access_log  /var/log/nginx/access.log host;
> ```

Thanks, this is works!
