### ISSUE TITLE
Have AutoUpdate 'OFF' as switch for install script

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#378]
This is a **request** to consider having AutoUpdate 'OFF' as a switch Argument to the install script... Will save some systems that can have impact of updates, for example we had custom Nginx templates washed off after the update on 19-Jun-2019

**Comment by ghost** [comment]
Hi @mehargags, 

Auto update will be disabled on all clean installations once our hotfix for v1.00.0 ships, and we'll look at adding in a switch to enable it in the installation script after that.

**Comment by Lupul** [comment]
Related commit: https://github.com/hestiacp/hestiacp/commit/eaf960402b7ea96c32dd8956455c237a60f8ac51
