### ISSUE TITLE
[Bug] Error in dns-cluster.pipe after DNS ip change

### ISSUE THREAD

**Issue by campodoro74** [hestiacp/hestiacp#3802]
### Describe the bug

When using the DNS cluster and I update a record on the main DNS server, the dns-cluster.pipe file at /usr/local/hestia/data/queue gets the wrong command; the last word 'domain' is not valid and thus the cluster is not updated. 

/usr/local/hestia/bin/v-add-remote-dns-domain user thisisafakedomain.nl **domain**

Running is manually, the following error appears:
Error: domain type is invalid

Running the command without **domain** gives the error 
Error: secondarydns.domain.nl connection failed

### Tell us how to replicate the bug

1. Change DNS record
2. Wait more than 5 minutes and find the record not updating on the secondary DNS servers
3. Check contents of /usr/local/hestia/data/queue/dns-cluster.pipe
4. See error in command

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Web Interface

### Hestia Control Panel Version

1.8.1

### Operating system

Debian 11

### Log capture

```shell
No log.
```

**Comment by jaapmarcus** [comment]
Plese see: 
https://github.com/hestiacp/hestiacp/pull/3803

**Comment by campodoro74** [comment]
Hi, this was indeed fixed for a while but it's back again!

root@dns01:/usr/local/hestia/data/queue# cat dns-cluster.pipe

/usr/local/hestia/bin/v-add-remote-dns-domain tralala tralala.co.uk domain
/usr/local/hestia/bin/v-add-remote-dns-domain tralala tralala.uk domain
/usr/local/hestia/bin/v-add-remote-dns-domain tralala tralala.com domain

root@dn01:/usr/local/hestia/data/queue# /usr/local/hestia/bin/v-add-remote-dns-domain tralala tralala.co.uk
Error: dns02.domain.it connection failed
