### ISSUE TITLE
[Bug]Websites  Error Logs populated with HTML & CSS entries... 

### ISSUE THREAD

**Issue by xerudro** [hestiacp/hestiacp#3804]
### Describe the bug

I am using Ubuntu 22.04, with Nginx 1.25.1 and HestiaCP 1.8.1.

Today i searched on my error logs of my domains, because one of them had a problem and did not loaded properly... and i found that the error log is almost a copy of access.log and not populated with the real errors that the pages encounters. And i checked all the error logs for all the domains and they are all the same... 

### Tell us how to replicate the bug

Open the file manager
Navigate to domain folder 
Acessing the logs folder
Open the error.log 

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.1

### Operating system

Ubuntu 20.04 LTS

### Log capture

```shell
<!doctype html>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8">
<title>WEB - speed.superhosting.vip - VIP SuperHosting</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="alternate icon" href="/images/favicon.png" type="image/png">
<link rel="icon" href="/images/logo.svg" type="image/svg+xml">
<link rel="stylesheet" href="/css/themes/default.min.css?v=1.8.1">
<link rel="stylesheet" href="/css/themes/dark.min.css?v=1.8.1"><script defer src="/js/dist/main.min.js?v=1.8.1" type="b4f1c52ada7c439bc527115d-text/javascript"></script>
<script defer src="/js/dist/alpinejs.min.js?v=1.8.1" type="b4f1c52ada7c439bc527115d-text/javascript"></script>
<script type="b4f1c52ada7c439bc527115d-text/javascript">
	document.documentElement.classList.replace('no-js', 'js');
	document.addEventListener('alpine:init', () => {
		Alpine.store('globals', {
			USER_PREFIX: 'x_',
			UNLIMITED: 'Unlimited',
			NOTIFICATIONS_EMPTY: 'No notifications',
			NOTIFICATIONS_DELETE_ALL: 'Delete all notifications',
			CONFIRM_LEAVE_PAGE: 'Are you sure you want to leave the page?',
			ERROR_MESSAGE: '',
			BLACKLIST: 'BLACKLIST',
			IPVERSE: 'IPVERSE'
		});
	})
</script>
</head>
<body class="body-web lang-en">
<header class="app-header">
<div class="top-bar">
<div class="container top-bar-inner">

<div class="top-bar-left">

<a href="/" class="top-bar-logo" title="VIP SuperHosting">
<img src="/images/logo-header.svg" alt="VIP SuperHosting" width="54" height="29">
</a>

<div class="top-bar-usage">
<div class="top-bar-usage-inner">
<span class="top-bar-usage-item">
```

**Comment by jaapmarcus** [comment]
You can't use the file manager to access logs due to lack of permissions:

Use:
https://xxxx:8083/list/web-log/?domain=xxxxxxx&type=error&token=

Also access log should populate with the access logs... Check the error log ...

**Comment by xerudro** [comment]
I did chcked the error log, what i posted there on the code format is taken from error log, opened from file manager.

Potential CSRF use detected
Please disable any plugins/add-ons inside your browser or contact your system administrator. If you are the system administrator you can run v-change-sys-config-value 'POLICY_CSRF_STRICTNESS' '0' as root to disable this check.

here is what i got when i tried to ue that link and change the domain and port ...

**Comment by jaapmarcus** [comment]
Click on the binoculars -> Error log and it should work...
