### ISSUE TITLE
[Bug]  Search function doesn't work

### ISSUE THREAD

**Issue by dfag86** [hestiacp/hestiacp#3807]
### Describe the bug

The search engine in the HestiaCP panel does not work :) after the last update.

### Tell us how to replicate the bug

When logged in as an administrator, you cannot search for domains. I have the latest version v1.8.2, previously it worked, 1.8.0 for sure but 1.8.1 probably also. Now it doesn't work.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.2

### Operating system

Debian 11

**Comment by ghost** [comment]
Thanks for the report. I believe this is valid but need to confirm the behavior you are seeing:

- Searching for domains hosted under other user accounts when logged in as `admin` returns no results.
- If you search for the hostname or any object hosted under `admin`, are results displayed?

**Comment by ghost** [comment]
Fix will be released with v1.8.3.
