### ISSUE TITLE
No website is working in receiving email via imap/pop3

### ISSUE THREAD

**Issue by hanzicode** [hestiacp/hestiacp#381]
### Brief issue description:
The error message is something like this:
> Sending of password for user contact@mydomain.com did not succeed. Mail server mail.mydomain.com responded: Internal error occurred. Refer to server log for more information

### Steps to Reproduce:
1. Thounderbird email client
2. Click on "Get Messages"
3. The error message above and no email downloaded

### Expected behavior:
Email should download using Thunderbird or Outlook email client

### Operating system distribution and release:
Debian 9

### HestiaCP Version:
1.00.0 (amd64) 190618

### Which branch are you using?
Master

### What software is installed?
Apache, Nginx, PHP-FPM, Dovecot/Exim, MySQL

### Related issues or forum threads:
Content of /etc/dovecot/conf.d/10-ssl.conf

> ssl = yes
> ssl_cert = </usr/local/hestia/ssl/certificate.crt
> ssl_key = </usr/local/hestia/ssl/certificate.key

### Additional notes:
See some IPs, including my computer's IP, have been added in the Baned IP list

**Comment by ScIT-Raphael** [comment]
Could you post the content of a "ls -l /usr/local/hestia/ssl/"?

**Comment by hanzicode** [comment]
OK

> -rw-r--r-- 1 root mail 3925 May 13 12:45 certificate.crt
> -rw-r--r-- 1 root mail 3243 May 13 12:45 certificate.key
> drwxr-xr-x 2 root root 4096 Jun 20 17:24 mail
> lrwxrwxrwx 1 root root   41 May 11 21:30 mail.gain4you.net.key -> /home/admin/conf/web/ssl.gain4you.net.key
> lrwxrwxrwx 1 root root   41 May 11 21:30 mail.gain4you.net.pem -> /home/admin/conf/web/ssl.gain4you.net.pem

**Comment by hanzicode** [comment]
The hostname domain is svr1.selfwebhosting.com

**Comment by ScIT-Raphael** [comment]
Hmm, there seems to be a issue with the mail integration. Can you share your system information that I can have a look? You can send the credentials to info@hestiacp.com.

**Comment by hanzicode** [comment]
Login credentials sent

**Comment by ScIT-Raphael** [comment]
I'm currently not able to login, please check your mails, already sent a request. Also I was not able to reproduce the issue, I will close the ticket for now but will reopen it, as soon as we've new informations.

**Comment by hanzicode** [comment]
I have replied to that email - did you receive it?

Basically you need to use the `su` command to go around for root login.

Oh, there might be another setting that prevents anyone but me from login. Let me find out.

**Comment by ScIT-Raphael** [comment]
I saw your mail, thanks - but I'm out of office today. Do you use a lets encrypt cert for hestia backend? if yes, can you run a v-update-host-certificate user domain and look, if the mail service will work again.

**Comment by hanzicode** [comment]
OK, I can try that.

BTW, I just made a change and you should be able to login using pwd now.

**Comment by hanzicode** [comment]
I tried running `v-update-host-certificate user hostdomain` and that did not resolve the problem.

**Comment by ScIT-Raphael** [comment]
I was able to resolv your issue, basicly you got the following error in your dovecot log:
`Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""`

This was caused because of the following lines in /etc/dovecot/conf.d/10-mail.conf:
```
# https://forum.vestacp.com/viewtopic.php?f=40&t=13539#p56445
namespace inbox {
inbox = yes
}
```
I've removed the lines, to be honest, I don't know where they came from - can't find them in our repository for the 10-mail.conf so I dont think this is a global issue.

Can you check on your side, if all is working properly? I created a temporary test domain, all worked well, so I cleared it up also.

**Comment by hanzicode** [comment]
Thank you so much!

I read about that solution but I was not sure whether I should follow that as I did not where HestiaCP is different from VestaCP.

Thanks again!
