### ISSUE TITLE
[Bug] Create emailalias starting or ending with - gives error

### ISSUE THREAD

**Issue by mdlaat** [hestiacp/hestiacp#3818]
### Describe the bug

Try to add an emailalias (to an existing email account) that either starts or ends with a - results in an error popup: Error: invalid malias format ::

Didn't test it with other special characters.

### Tell us how to replicate the bug

1. click on mail
2. click on maildomain
3. click on mailaccount
4. add "-a" (or "a-") in the aliases box
5. Read the error

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.2

### Operating system

Ubuntu 22.04.1 LTS (Jammy Jellyfish)

### Log capture

/var/log/hestia/error.log:
v-add-mail-account-alias  '... '...' '...' '-a' [Error 2]

**Comment by jaapmarcus** [comment]
Hyphen -, provided that it is not the first or last character.


So -a and a- are not valid for the local part

**Comment by jaapmarcus** [comment]
It seems to be invalid for domains only..

**Comment by mdlaat** [comment]
I was just checking RFC 5321 and indeed it seems that localpart may start or end with an hyphen, while (sub)domains may not.

**Comment by jaapmarcus** [comment]
See attached PR
