### ISSUE TITLE
Hestia Partially Upgraded

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#382]
UBUNTU 18.04/
Realized the Hestia been upgraded automatically but partially.
HESTIA - still 0.9.8(Rel28) - upgraded on 2019-03-17
But HESTIA-PHP & HESTIA-NGINX - upgraded on 2019-06-19

I restarted 'Service Hestia Restart' > than realized the port changed back to default 8083. 
But still HESTIA PANEL in old version only.

**Comment by ScIT-Raphael** [comment]
The issue with hestia-nginx port reset has already been resolved on the repository this moring. You could run a apt update && apt --reinstall install hestia-nginx - it will reset the port to your right one.

Can you do a apt update, followed by a apt upgrade to check if the hestia update is in the list? I would suggest to not install it yet - we're in testing phase for the hotfix package.

**Comment by vvcares** [comment]
Wow. Super fast response team.
resolved by 'apt update && apt --reinstall install hestia-nginx'
apt-get install hestia - is listed as well.

Thank you team.

**Comment by ScIT-Raphael** [comment]
Thanks for the warm words, we try to do our best here. Just had some issues during the new release :).

So I will close your ticket for now, please feel free to reopen it or create a new one at any time!
