### ISSUE TITLE
duplicate nosniff/SAMEORIGIN headers

### ISSUE THREAD

**Issue by FalzoMAD** [hestiacp/hestiacp#383]
### Brief issue description:
after the upgrade and changes to /etc/nginx/nginx.conf the nosniff and SAMEORIGIN headers get send out twice now making f.i. nextcloud complain about

### Expected behavior:
headers should only get sent once

### Operating system distribution and release:
debian stretch

### HestiaCP Version:
1.0

### What software is installed?
nginx+apache+single php

### Additional notes:
commenting out lines 119/120 in /etc/nginx/nginx.conf resolve the issue with nextcloud. the headers in question still get sent out correctly.

overall I suggest to not overengineer the default settings, especially in global config files!

**Comment by ghost** [comment]
Fixed in a88d57e.
