### ISSUE TITLE
[Feature] DirectAdmin backup import

### ISSUE THREAD

**Issue by Aartsie** [hestiacp/hestiacp#3834]
### Describe the feature or change in detail

I think it would be nice and helpful  to have an import function for DirectAdmin backups.
This will make it much easyer to migrate from DirectAdmin to Hestiacp.

Currently i'm working on a directadmin backup import script for Hestiacp based on the v-import-cpanel and [sk_da_importer](https://github.com/Skamasle/sk_da_importer). 
Hopefully this is helpfull for others, maybe we can add it to the project as v-import-directadmin in the bin folder when its working fine.

Are there requirements or criteria before we can add this to hestiacp?

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
> Currently i'm working on a directadmin backup import script for Hestiacp based on the v-import-cpanel and [sk_da_importer](https://github.com/Skamasle/sk_da_importer).
Hopefully this is helpfull for others, maybe we can add it to the project as v-import-directadmin in the bin folder when its working fine.

If you can get it working 👍🏻  I am happy to merge it feel free to submit a PR... 

Main issue in the past I encountered was issue with the mysql database user(s) as mysql creates: 
user as database user
user_xxxxx as database user 
user_xxxxy for the same database user with maybe different permissions... 

It might be impossible to for it to one

I have spoken wit the original author about it in the past:

> [22:38]ohya: It mean than cpanel not change to much
> [22:38]ohya: Im also working in directadmin script
> [22:39]ohya: but directadmin backups are diferent from one version to other and
> [22:39]ohya: have some diferent configurations

**Comment by Aartsie** [comment]
Hi @jaapmarcus, thank you for your response.
Here by a small update: I got the script working to the point where i want to create and import te database.

But when i want to add multiple users to the database I can't find them in Hestiacp but i see `3/~ (0) databases` in the header so there are multiple users? I'm new with Hestiacp so maybe i'm looking in the wrong direction? 

My conf.db looks like this now:
```
DB='omug_xxxx' DBUSER='omug' MD5='*5EDFDE94FE4D08A01***********999' HOST='localhost' TYPE='mysql' CHARSET='UTF8' U_DISK='0' SUSPENDED='no' TIME='' DATE=''
DB='omug_xxxy' DBUSER='omug_temp' MD5='*3D3B92F242033365***********40A' HOST='localhost' TYPE='mysql' CHARSET='UTF8' U_DISK='0' SUSPENDED='no' TIME='' DATE=''
DB='omug_xxxz' DBUSER='omug_wpom' MD5='*5EDFDE94FE4D08A***********99' HOST='localhost' TYPE='mysql' CHARSET='UTF8' U_DISK='0' SUSPENDED='no' TIME='' DATE=''
```

**Comment by jaapmarcus** [comment]
Hestia has currently no Support for it. Ideally we need to add support for it but a lot of other "issues" on my to do list :)

**Comment by Aartsie** [comment]
Aah check! Is it an idea to add them in mysql directly or will that result in troubles for the future?
Otherwise maybe its possible to only add 1 user with the highest permissions?

**Comment by Aartsie** [comment]
Here a small progress update:

- [x] Import domains
- [x] Import databases
- [x] Import imap 
- [x] Writing docs

The feature is almost finisht, currently there is a bug that the database password is incorrect.
Need some time to fix this but keep this issue informed about the progress.

**Comment by MrCyjaneK** [comment]
hey @Aartsie do you have it lying somewhere in a repo - I'd like to take look/help with it as a huge DA import is going to happen on my end.

**Comment by jaapmarcus** [comment]
https://github.com/Aartsie/hestiacp/tree/da_import

**Comment by Aartsie** [comment]
Hi @MrCyjaneK yes you can use it already.
I have just pushed my latest version. I still have to clean up some code but it does the job.
The script can create a user and restore Datases, 1 databases user and password, mails and domains.

You just have to add the `v-import-directadmin` file to `/usr/local/hestia/bin`

Now you can run the import like:
example: 
```shell
v-import-directadmin backup.tar.gz
```

**Comment by Caroga** [comment]
This is what I've always wanted!

**Comment by jaapmarcus** [comment]
> Hi @MrCyjaneK yes you can use it already. I have just pushed my latest version. I still have to clean up some code but it does the job. The script can create a user and restore Datases, 1 databases user and password, mails and domains.
> 
> You just have to add the v-import-directadmin file to /usr/local/hestia/bin
> 
> Now you can run the import like: example: v-import-directadmin backup.tar.gz

Can't wait for the PR :)

**Comment by Aartsie** [comment]
I've tested the script and added the docs, see PR https://github.com/hestiacp/hestiacp/pull/4177.

The first website are over to HestiaCP and are up and running :rocket: :ship:

**Comment by Skamasle** [comment]
Unfortunately some changes in DirectAdmin have broken the script, the database passwords from the latest versions are not restored.. I think problem start from DA 1.56 but not have that versión to check.

I am working on version 2 of the script to see if I can fix some bugs and improve some things.

Just like version 2 of the cpanel script, it may possibly allow changing the user to restore if it already exists in the panel and restore only the mail or the databases etc -> https://github.com/Skamasle/sk-import-cpanel-backup-to-vestacp/blob/master/v-import-cpanel-v2

Although the main thing here is to fix the problem of restoring the databases

**Comment by Aartsie** [comment]
Hi @Skamasle what is the error you have? Because i have imported all my directadmin users to Hestiacp with this script. 
My Directadmin version was 1.643

The script only import the first database user because Hestiacp doesn't support multiple database users at the moment.

**Comment by Skamasle** [comment]
Hi

I see the problem maybe is with accounts imported from cpanel to DA

This accounts first user is USER and not USER_NAME

Not a big issue, in any case I try rewrite some code in my version to make
similar to cpanel importer and cwp importer

**Comment by Aartsie** [comment]
Aah i have no experience with cpanel -> directadmin imports but if I can help you, let me know.

**Comment by Skamasle** [comment]
The backup is same, but cpanel by fault have "full privileged database user" so if cpanel account is cpanel1 cpanel have mysql user called cpanel1

And this is imported to DA, so in da you get this DB users in a backup

cpanel1
cpanel1_db1
cpanel1_db2 

So if we just take first user get error.

**Comment by Skamasle** [comment]
@Aartsie what do you think about modify script to ask user witch database want restore ?

I think most of users use in website first database user, but in DA the order may change, first created one maybe last user listed in backup.

In other way, cpanel have same issue and we not have any problems restoring databases.

**Comment by Aartsie** [comment]
Sounds good for me. Or we can add all the users in the file but the problem with this is that you can't manage them by the web control panel. So its not really an option in my opinion but don't know how @jaapmarcus thinks about this.

**Comment by Skamasle** [comment]
Hi, I rebuild some for now, next week if have time I will add more options

The idea is make script like v-import-cpanel with posibility of user to restore only emails, only domains or only databases and posibility of change user if user alredy exists in hestiacp ( this option is added alredy in v-import-cpanel-v2 )

Need more tests and alot of code, but I want make all out put similar in 3 scripts v-import-cpanel, v-import-directadmin and v-import-cwp
