### ISSUE TITLE
[Bug] new CAA records corrupt in latest version of HestiaCP version 1.8.2

### ISSUE THREAD

**Issue by amraerakit** [hestiacp/hestiacp#3837]
### Describe the bug

When add a new CAA record there is extra numbers and \ added inside the "" when doing a lookup.  
For example  0 issue "\266\128\156letsencrypt.org\266\28\157" when it should be 0 issue "letsencrypt.org" note in the HestiaCP console the entry looks correct.

### Tell us how to replicate the bug

Add a new CAA record say and entry like    0 issue "letsencrypt.org"     and do a DNS lookup to see the corruption which will look like   0 issue "\266\128\156letsencrypt.org\266\28\157"

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.8.2

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Can you share /home/user/conf/dns/domain.com.db?

Please remove ip's / domain name

**Comment by amraerakit** [comment]
Had to remove all the CAA on that site to get the site going.

Ran a test on the HestiaCP domain. Yikes. brought the NS down for the whole server.  Deleting the entry got things working. 

Managed to grab this from the /home/user/conf/dns/domain.com.db

@	3600	IN	CAA		0 issue â€œdigicert.comâ€

**Comment by jaapmarcus** [comment]
I am not able replicate this issue on my test server it looks 

record=$(idn2 --quiet -d "$3")
record=$(echo "$record" | tr '[:upper:]' '[:lower:]')

It looks like an issue with the locale encoding:

Did you copy it from some documentation?

What happens if use:

Where $user and $domain:
```
v-add-dns-record "$user" "$domain" '@' 'CAA' '0 issue "letsencrypt.org"'
```

**Comment by amraerakit** [comment]
Ok yes you are correct.  

Completed two test entries.  First one from the keyboard and second for copy and paste from the website - https://wpengine.com/support/ssl-certificates-caa-records/ 

Both look render perfect in HestaCP console but in /home/user/conf/dns/domain.com.db the second one has garage.
@	3600	IN	CAA		0 issuewild "letsencrypt.org"
@	3600	IN	CAA		0 issuewild â€œdigicert.comâ€

**Comment by jaapmarcus** [comment]
<img width="757" alt="Screenshot 2023-07-24 at 07 55 21" src="https://github.com/hestiacp/hestiacp/assets/9754650/215e1bad-e7f1-4db5-9888-d05aa96a9283">

They use html encoded ```"``` replace them with non encode will solve the issue.

Just enter:

```0 issuewild "digicert.com"```

And not copy it over from html. Probably due to the font we use they look the same..

**Comment by jaapmarcus** [comment]
I don't know if we can detect it what " are used..

**Comment by amraerakit** [comment]
I have a suggestion to have the HestaCP console rendered the content out of the  /home/user/conf/dns/domain.com.db  file as it is.  What do you think or an I off track ?  Or maybe a warning on the console page ?  Thank you for your help.
