### ISSUE TITLE
[Bug] PHP 8.1 Laravel template 

### ISSUE THREAD

**Issue by xerudro** [hestiacp/hestiacp#3845]
### Describe the bug

Laravel project on PHP 8.1 - Err 500, but on PHP 8.2 able to install it.

### Tell us how to replicate the bug

I tried to install my  laravel booking system today on my Debian 11 server, with the latest panel version : Hestia Control Panel
 v1.8.3
Operating System
Debian 11.7 (x86_64), and because it was an updated version of laravel app, i was thinking that the developer updated the supported php version from 8.1 to 8.2 and i changed the php version to 8.2, all was good until i tried to backup the database of the app, and i got an error. I read the developer changelog, and i noticed that the php version was the same. I deleted the database of the app, i deleted all the files inside the public_html folder, switched tohe php to 8.1 copied the zip archive to the folder, unzipped it, and tried to install it, but i got err 500 page ... now i am thinking that something is wrong either on php version change, or on the laravel 8.1 template or settings ... 

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.3

### Operating system

Debian 11.7

### Log capture

```shell
2023/07/25 16:35:20 [error] 257072#257072: 362 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table ‘pcdoctor_depanero.settings’ doesn’t exist in /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414
Stack trace:
#0 /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare()
#1 /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(786): Illuminate\Database\Connection->Illuminate\Database{closure}()
#2 /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->runQueryCallback()
#3 /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\Database\Connection->run()
#4 /home/pcdoctor/web/…PHP message: PHP Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table ‘pcdoctor_depanero.settings’ doesn’t exist in /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414
Stack trace:
#0 /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare()
#1 /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(786): Illuminate\Database\Connection->Illuminate\Database{closure}()
#2 /home/pcdoctor/web/.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->runQueryCallback()
#3 /home/pcdoctor/web/*.net/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate
```

**Comment by jaapmarcus** [comment]
Table ‘pcdoctor_depanero.settings’ doesn’t exist

I don't think this is an Hestia issue

**Comment by jaapmarcus** [comment]
We also use the same template independt of the of Laravel/php version. 

So you should contact your software developer/supplier ..

Also no major changes where made we only added support: 

```
	# TLS 1.3 0-RTT anti-replay
	if ($anti_replay = 307) { return 307 https://$host$request_uri; }
	if ($anti_replay = 425) { return 425; }
```
