### ISSUE TITLE
[Bug] Cert SSL wildcard show correctly info but in production site show older ssl

### ISSUE THREAD

**Issue by schneiderbruno** [hestiacp/hestiacp#3856]
### Describe the bug

HI guys,

I buy a wildcard cert and set in my website inside hestiacp.
Hestiacp show correctly info about this new ssl wildard, but when i visit the site i display the old certificate..

### Tell us how to replicate the bug

1. Go to web and edit domain
2. Add wildcard ssl and click and save
3. Page reload and correctly info is show
4. Go to website and check curre
![hesticap cf](https://github.com/hestiacp/hestiacp/assets/8595383/9a444896-7458-408f-bd79-1423bed27820)
nt ssl.. see the older

when i visit the site i display the old certificate
![image](https://github.com/hestiacp/hestiacp/assets/8595383/7fe3a347-fb8c-4ad7-bf12-5af4a757d1e8)

### Which components are affected by this bug?

Control Panel Backend, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.3

### Operating system

Debian 12

**Comment by jaapmarcus** [comment]
Restart Nginx server?

**Comment by schneiderbruno** [comment]
> Restart Nginx server?

Yeah...server, apache, nginx...

**Comment by jaapmarcus** [comment]
Lets keep it in one location:
https://forum.hestiacp.com/t/panel-display-new-certificate-but-not-actually-used-cert-ssl-wildcard-show-correctly-info-but-in-production-site-show-older-ssl/10318
