### ISSUE TITLE
Feature Request: Get Whois Info under DNS Tab

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#386]
Maybe add a Get WHOIS button along side the domain under DNS tab. Have it filter and format out crucial information about the domain being queried. Fex (Domain Expiration, Registrar, Registrant, etc)  I also noticed under the DNS tab in the domain listing there is an expiration date listed in the table view at end. It looks like it inherits the current date the domain was added to the hestia control panel + 1 year. It would be awesome if it grabbed the real expiration for each domain maybe daily with a cron job. On top of that if domain is expiring within 30 days add notification to state domain domain.ext will be expiring in 30 days. Just blowing out some rough ideas..

**Comment by ScIT-Raphael** [comment]
We've discussed this request internaly and came to the point, that it would be to much in the current state of hestia. We will decide to have this as a potential function in a plugin system, but this will need addtional time to discuss, develop and release.
