### ISSUE TITLE
[Bug] File Manager "Unknown Error" on filename with special characters

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3872]
### Describe the bug

When you try to enter a directory that contains a file with German umlauts, it does not work and pops up an Unknown Error. Example filename:
```
$ ls
'presse-vdpm-brosch'$'\374''re_steuern-sparen_6mb.pdf'
```

### Tell us how to replicate the bug

1. Create a Web Domain
2. Upload a file with umlauts into public_html
3. Try to open the corresponding folder in the inbuilt web file manager

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

 v1.8.3 

### Operating system

Debian 11.6 (x86_64)

**Comment by jaapmarcus** [comment]
https://github.com/filegator/filegator

We don't develop the filemanager you should create a bug report with Filegator

**Comment by jaapmarcus** [comment]
It might be even a bug with an underlaying composer dependency

**Comment by jaapmarcus** [comment]
It looks like an issue with the encoding used with the file name while uploading
<img width="1083" alt="Screenshot 2023-07-29 at 04 42 41" src="https://github.com/hestiacp/hestiacp/assets/9754650/1c5ce6b2-030b-413b-b613-f21dfc684736">

I don't know what encoding was used and how it was uploaded but with OSX and and SFTP client or with the Filemanger I don't have any issues 
 
If I copy the file name exactly from the issue I also encounter the error how ever it is pulled 1 on 1 from a 3rd party repo.
