### ISSUE TITLE
[Feature] Updating MariaDB to v11.0.2

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#3885]
### Describe the feature or change in detail

I've tried updating MariaDB from 10.11 to 11.0.2 and did all testing on WordPress and Laravel 
Everything looks working fine. version 11.0.2 is a stable release.

[mariadb_v="10.11" to 
mariadb_v="11.0.2"](https://github.com/hestiacp/hestiacp/blob/main/install/hst-install-ubuntu.sh#L38C1-L39C1)
``

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
https://mariadb.com/kb/en/release-notes/

And

https://mariadb.com/kb/en/mariadb-server-release-dates/

Non LTS versions have only year of support for each OS we follow only the LTS releases that have 5 year of support.

MariaBD 11.0 is already supported just update the version number and it should work.
