### ISSUE TITLE
[Bug] Unable to install Docuwiki via Quick Install

### ISSUE THREAD

**Issue by Save656** [hestiacp/hestiacp#3889]
### Describe the bug

Dokuwiki Quick install don't work.

It shows this error after install

`Error: source directory /home/public_html/tmp-dokuwiki/dokuwiki-2023-04-04/. doesn’t exist`

Install not completed. 

### Tell us how to replicate the bug

1.Quick install
2. Choose Dokuwiki 
3. Install 
4. Error shows. 

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.8.4

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Forgot to close issue
