### ISSUE TITLE
GUI issue: field ns1, ns2 can not be blank

### ISSUE THREAD

**Issue by Pleskan** [hestiacp/hestiacp#389]
### In a few words, please describe the issue that you're experiencing:
I get subject error message after default user's package options has been edited.

### What steps did you take when the issue occured? 
1. Log into the Hestia Control Panel 
2. Click on the **Packages** button, then click on  edit icon
3. Change number of backups for example and click **Save** 
4. _Field "ns1, ns2" can not be blank._ appears.

### Expected behavior:
There should not be any errors after editing.

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.00.0-190618
1.00.0-190621

### Which branch are you using?
master
develop

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)
- PostgreSQL

### In order to better assist, please post any relevant log information below:
Not Applicable

### Related issues or forum threads:
None

### Additional notes:
None

**Comment by ghost** [comment]
Fixed in v1.0.1.
