### ISSUE TITLE
wildcard ssl problem using cloudflare dns _acme-challenge is out of sync

### ISSUE THREAD

**Issue by gunsar** [hestiacp/hestiacp#3895]
### Describe the bug

I have set and filled
Edit Web Domains :
Domain : domain.ltd
Aliases : *.domain.ltd
☑Enable SSL for this domain
☑Use Let's Encrypt to obtain SSL certificate
☑Enable automatic HTTPS redirection
☑Enable HTTP Strict Transport Security (HSTS)

Cloudflare DNS Records
A / * / xxx.xxx.xxx
A / domain.ltd / xxx.xxx.xxx

when pressing the SAVE button in vestacp
description code _acme-challenge.domain.ltd error
I see in the hestiaCP DNS, the acme-challenge code always changes when I press the save button
I have entered into Cloudflare the code _acme-challenge.domain.ltd like the code listed on the hestiaCP DNS
But it's always out of sync and always changes when you press the save button

**sorry my English uses google translate
please help

### Tell us how to replicate the bug

i don't know

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

v1.8.4

### Operating system

Ubuntu 20.04

### Log capture

```shell
code _acme-challenge.domain.ltd error
```

**Comment by jaapmarcus** [comment]
It is currently not possible to sync chalanges with Cloudflare . So it is not supported. Wildcard SSL is only supported if you use DNS with "Hestia" panel

**Comment by gunsar** [comment]
thank's @jaapmarcus
