### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ad8272** [hestiacp/hestiacp#3899]
### Describe the bug

![image](https://github.com/hestiacp/hestiacp/assets/141497558/4d8f49ca-0fd8-4851-b2f1-3bd15748129c)
Show this error 
Image not open

### Tell us how to replicate the bug

https://shoppylite.com/wp-content/uploads/2023/08/download-test-file.jpg

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.8.4

### Operating system

22.04

**Comment by jaapmarcus** [comment]
Check your logs as other images are not affected I am not sure how we can help here....

**Comment by jaapmarcus** [comment]
For support use our support forum...
