### ISSUE TITLE
Feature Request: Re-evaluate public_shtml presence

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#391]
### In a few words, please describe the issue that you're experiencing:
Should public_shtml still exist? When im navigating the shell using cd to chnage directories and tab to auto complete i always having to find my self typing out pu then tab to get to public_html, if public_shtml didnt exist then it would just be p tab then it would auto complete. It saves alot of time when traversing through directories.

### What steps did you take when the issue occured? 
1. Login via ssh
2. cd /home/user/web/domain.ext/
3. type cd pu [press tab]

### Expected behavior:
Auto fill in public_html

### Operating system distribution and release:
Ubuntu 18.04.2 LXC/Proxmox

### Which version of Hestia Control Panel is currently installed?

1.00.0-190618

### Which branch are you using?
master

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

### In order to better assist, please post any relevant log information below:
N/A

### Related issues or forum threads:
N/A

### Additional notes:
N/A

**Comment by ioannidesalex** [comment]
Totally agree. Never used public_shml and most probably none does.

**Comment by johnnyq** [comment]
Maybe even a re-Evaluation of private directory as well. Im not sure what it would be used for

**Comment by ioannidesalex** [comment]
Private directory is used for SSLs (older) or any custom ones someone might need.

**Comment by FalzoMAD** [comment]
private is needed, don't touch.

public_shtml is annoying as described. 

+1 for stopping to deploy it on domain creation, might need a check how to handle restore of old backups though?

**Comment by ghost** [comment]
We've removed the option to configure public_html/public_shtml from the Web UI with commit 3cf97e0fd8c580bcf54adb8cd04dfc9bcb704271, previous/upgraded installations will need to be handled more delicately to prevent data loss and issues with restoration of previous backup files which we'll review further in the future.
