### ISSUE TITLE
[Bug] phpMyAdmin button no longer opens in a new tab

### ISSUE THREAD

**Issue by hazrpg** [hestiacp/hestiacp#3915]
### Describe the bug

The phpMyAdmin button with the right-arrow (I think its part of sso or simple login feature so that you don't have to put it the username and password each time for a database), no longer opens up in a new tab. It use to for a long time, and now it defaults to opening in a new window which can be a bit jarring when you're still wanting to check something else in the panel while having phpMyAdmin open in another screen.

### Tell us how to replicate the bug

1. Click on Database.
2. Click on the phpMyAdmin button (it has an arrow point to the right)
3. Does not open in a new window, opens in the current window.

### Which components are affected by this bug?

Control Panel Backend, Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.8.4

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Fixed probably for 1.8.6 release
