### ISSUE TITLE
[Bug] Error: SSL=yes already exists when trying to edil mail domain from GUI

### ISSUE THREAD

**Issue by sahsanu** [hestiacp/hestiacp#3919]
### Describe the bug

I'm using Debian 12 on AMD64 and HestiaCP 1.8.5

I added my own ssl cert for mail domain using:

`v-add-mail-domain-ssl myuser example.com /path/to/example.com_cert_files/`

So far, so good, all works as expected.

Now, if I try to edit mail domain from GUI (enable/disable Reject Spam, modify mail rate limits, etc.) the changes are performed but I get this error:

`Error: SSL=yes already exists`

If I try to modify the certs from the GUI I get the same error and certificates are not changed, other options yes but not the cert.

Checking the issue, seems `v-change-mail-domain-sslcert` script is the "culprit", it uses `is_object_value_empty` when it should check whether the object SSL is enabled, not empty so it should use `is_object_value_exist` instead.

I've modified it in `v-change-mail-domain-sslcert` script and tried again and this time I don't get the SSL already exists error but receive this one:

`Error: /example.com.crt not found`

So, seems it is not using the right ssl dir and checking the script again, yes, `ssl_dir` variable is not defined, once fixed both issues, the changes are performed suceesfully from command line and from GUI and no more errors.

I'm going to open a pull request with those minimal changes so you can review it.

Thank you.

Cheers,
sahsanu

### Tell us how to replicate the bug

**1.-** Add mail domain
**2.-** Add SSL and custom certificate for mail domain using `v-add-mail-domain-ssl myuser example.com /path/to/example.com_cert_files/`
**3.-** Edit mail domain from GUI (reject spam, rate limits, etc.)
**4.-** Save

### Which components are affected by this bug?

Control Panel Command Line Interface, Control Panel Web Interface

### Hestia Control Panel Version

1.8.5

### Operating system

Debian 12 AMD64

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3920
