### ISSUE TITLE
Feature Request: Don't add www alias when creating a sub web domain

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#392]
### In a few words, please describe the issue that you're experiencing:

I create a lot of sub domains and when I do, I find myself deleting out the alias as it adds www.subdomain.domain.ext. Maybe when you add a web domain domain.ext then adds the www alias, but if web domain is a sub domain then do not add www to the alias.

### What steps did you take when the issue occured? 
1. Click Web tab 
2. Click Add Web Domain
3. Fill out a domain ex test.example.com
4. Click advanced options (web Alias is auto set to www.test.example.com

### Expected behavior:
On sub Domains www should not be automatically added to alias

### Operating system distribution and release:
Ubuntu 18.04.2 (LXC Proxmox)

### Which version of Hestia Control Panel is currently installed?
1.00.0-190618

### Which branch are you using?
master

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

### In order to better assist, please post any relevant log information below:
N/A

### Related issues or forum threads:
N/A

### Additional notes:
N/A

**Comment by ioannidesalex** [comment]
Agree on this as well!

**Comment by ScIT-Raphael** [comment]
Has been realized in the follwing branch: https://github.com/hestiacp/hestiacp/tree/feature/web/NoWwwOnSub

**Comment by ghost** [comment]
This change has been made available in v1.0.1.
