### ISSUE TITLE
[Bug] Firewall dropped me out from server after install because of custom ssh port

### ISSUE THREAD

**Issue by sahsanu** [hestiacp/hestiacp#3921]
### Describe the bug

Three weeks ago I installed HestiaCP for the first time and after the install, the firewall's rules dropped my ssh connection because installation didn't detect my custom ssh port.

The reason is because I modified the ssh port in a file inside `/etc/ssh/sshd_config.d/` dir instead of main conf file `/etc/ssh/sshd_config` and checking the issue, seems two scripts; `v-add-firewall-chain` and `v-update-firewall`, are trying to get the custom ssh port using `grep` on `/etc/ssh/sshd_config` and that is the reason it didn't get my custom port.

You already have a script (`v-list-sys-sshd-port`) to check the ssh port using `sshd -T` command so I think it should be great to use it instead the `grep` approach.

I'm going to open a pull request with the changes just in case you want to use it.

Thank you.

Cheers,
sahsanu

### Tell us how to replicate the bug

**1.-** Customize ssh port but not in main conf file `/etc/ssh/sshd_config` but inside a conf file in `/etc/ssh/sshd_config.d/` dir
**2.-** Install HestiaCP
**3.-** Observe how the firewall droppes your ssh connection because it added the firewall's rule for port 22 instead of customized ssh port

### Which components are affected by this bug?

Control Panel Command Line Interface, Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.8.5

### Operating system

Debian 12 AMD64

**Comment by ghost** [comment]
Closing as this has been corrected in https://github.com/hestiacp/hestiacp/pull/3922, thanks for your contribution in resolving this issue.
