### ISSUE TITLE
Add Web Domain - Missing WebTemplate and Backend Template Options

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#393]
### In a few words, please describe the issue that you're experiencing:
Under add web domain its missing WebTemplate and Backend Template under advanced options. This is present under edit Web Domain.

### What steps did you take when the issue occured? 
1. Click Web tab
2. Click Add Web Domain

### Expected behavior:
WebTemplate and Backend Template should show under advanced options

### Operating system distribution and release:
Ubuntu 18.04.2 (LXC Proxmox)

### Which version of Hestia Control Panel is currently installed?
1.00.0-190618

### Which branch are you using?
master

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

### In order to better assist, please post any relevant log information below:
N/A

### Related issues or forum threads:
N/A

### Additional notes:
N/A

**Comment by ScIT-Raphael** [comment]
Can you rewrite your post and use the issue template we provide when you open a new one? It will provide us important informations, please do not a ctrl+a & del.

**Comment by johnnyq** [comment]
absolutely, will do with each post

**Comment by ghost** [comment]
This may be in part due to the way the domain creation process works as I believe this is also the case under Vesta so it will need more investigation, I've marked this tentatively for v1.1.0.
