### ISSUE TITLE
[Bug]  Spamassassin cannot be stopped, started or restarted through Hestia panel

### ISSUE THREAD

**Issue by demlasjr** [hestiacp/hestiacp#3931]
### Describe the bug

When I click on restart, I'm getting a popup with the error: "Error: ERROR: Restart of spamassassin failed."
When clicking on stop it does nothing. However, I can start and stop the service through /etc/init.d/spamd stop/start/restart command.
I guess it's a bug due to Debian 12 upgrade, probably the name of service changed from spamassassin to spamd

Command "v-restart-service spamd" seems to work.

### Tell us how to replicate the bug

1. Click on Server Settings
2. Click on Spammassassin stop button

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.5

### Operating system

Debian 12

### Log capture

```shell
17 Aug 2023	02:40:42	System	Service restarted (Name: spamd).
17 Aug 2023	02:36:42	System	Service failed to stop (Name: spamassassin).
17 Aug 2023	02:36:38	System	Service failed to stop (Name: spamassassin).
```

**Comment by demlasjr** [comment]
Nevermind, I found the solution and it looks like it already has been fixed in pull #3661 

Commit [bcceece](https://github.com/hestiacp/hestiacp/pull/3661/commits/bcceece0d2ad086d789ec89c40bcc17911a0dae1)

To manually fix it in Debian, go to /usr/local/hestia/conf/hestia.conf and find

`ANTISPAM_SYSTEM='spamassassin'`

Replace with 
`ANTISPAM_SYSTEM='spamd'`

Thanks.

**Comment by jaapmarcus** [comment]
Did you do a manual upgrade from 11 to 12 ?

**Comment by demlasjr** [comment]
Hi @jaapmarcus, yes I did. I'm trying to manually check every single change from that pull and manually update it, just in case I miss something. So far, I have problem only with snappymail.

**Comment by jaapmarcus** [comment]
Make sure to also update Exim conf to the last version

**Comment by demlasjr** [comment]
> Make sure to also update Exim conf to the last version

Yep, already did it. I also had to create a srs.conf with a random key (some lowercase and uppercase characters) inside /etc/exim4/ folder because I got errors in exim4 and undelivered emails.
