### ISSUE TITLE
[Bug] PHP Cli and cron versions out of sync

### ISSUE THREAD

**Issue by blazerunner44** [hestiacp/hestiacp#3934]
### Describe the bug

When running a cron job, the PHP version is not synced up with the selected PHP CLI version for the user. On my install, the PHP version used for cron jobs on any user is php 8.2. For many of my users, the selected PHP CLI version is 7.4. 

When logging in as a user via SSH, I have confirmed that the PHP CLI version is correct (running `php -v` outputs version 7.4). But the user's cron jobs all run as php 8.2.

An easy work around is to explicitly specify the PHP version on the cron command, but I'd expect the cron to default to the CLI version I've selected for my user. 

### Tell us how to replicate the bug

1. Modify a user to select PHP 7.4 as the CLI version
2. Create a cron job on the HestiaCP web interface to output the PHP version to a file. I've been using `php -v > /tmp/php.log`
3. Wait for the job to execute
4. Check the output file to see that the PHP version used to run the cron job is PHP 8.2

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.5

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
Use /usr/bin/php7.4  instead. It doesn't doesn't work with cronjobs as it doesn't log into any shell.. 

Nothing really we can do about
