### ISSUE TITLE
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/usr/local/hestia/ssl/certificate.crt"

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#394]
Whenever I'm doing nginx -t to check my configs I'm given this warning message
`nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/usr/local/hestia/ssl/certificate.crt"
`

I think it because because of Line 115-116 added to /etc/nginx/nginx.conf that setup SSL Stapling ON globaly.

```
    ssl_stapling        on;
    ssl_stapling_verify on;
```
I guess OCSP Stapling directives should be configured on a **per domain basis**, rather than globally server wide or else the self-signed or other certificates can fail to verify.

Pls check and amend this appropriately

**Comment by mehargags** [comment]
For the Nginx directives newly added to Global nginx.conf

it would rather be great if these additional directives be placed **Commented** in the default web templates... this way you can still "prompt" the sysadmins which ones to enable in individual config... and still leave it out unchecked for average Jon Doe

**Comment by ghost** [comment]
Will investigate prior to shipping v1.0.1.

**Comment by ghost** [comment]
Fixed in 1.0.1.
