### ISSUE TITLE
[Bug] Forum registration (verification) does not work

### ISSUE THREAD

**Issue by ponasromas** [hestiacp/hestiacp#3945]
### Describe the bug

Upon registration email arrives to verify. When pressed on link it drops to page with error "Oops! That page doesn’t exist or is private.".

### Tell us how to replicate the bug

1. Register account in https://forum.hestiacp.com/
2. Press email activation link in email received
3. "Oops! That page doesn’t exist or is private."

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1

### Operating system

Always Debian

**Comment by jaapmarcus** [comment]
Please send an email to info@hestiacp.com  with your username / activation url. I am not aware of any issues
