### ISSUE TITLE
[Bug] DNS cluster records get wiped out from slaves

### ISSUE THREAD

**Issue by ponasromas** [hestiacp/hestiacp#3947]
### Describe the bug

Manually editing serial in /home/dns/conf/dns/domain.tld.db wipes all DNS records (all .db files are deleted) in slave servers after v-sync-dns-cluster.

### Tell us how to replicate the bug

1. Add few DNS zones in master server. Wait for sync to slave.
2. Edit any DNS zone file via CLI in /home/dns/conf/dns (I have edited serial number to force rndc resync).
3. Execute v-sync-dns-cluster on master and watch how all records are wiped out from slave(s)

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.8.5

### Operating system

Debian 12

### Log capture

Aug 22 13:04:01 64dcf534fa19f63adf06104a named[33786]: client @0x7f0e1c5e9510 IP address#47956 (domain.tld): query (cache) 'domain.tld/DNSKEY/IN' denied

**Comment by jaapmarcus** [comment]
v-sync-dns-server deletes first all the domains and the adds them again 

If you just want to update run v-dns-domain-soa and it should update only the soa on both the master and the slaves...

**Comment by ponasromas** [comment]
> v-sync-dns-server deletes first all the domains and the adds them again
> 
> If you just want to update run v-dns-domain-soa and it should update only the soa on both the master and the slaves...

There is no such command as v-dns-domain-soa and this not resolves issue with records wipe out.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/main/bin/v-change-dns-domain-soa

v-change-dns-domain-soa

was on mobile...

Clearing Slave DNS is by design:

https://github.com/hestiacp/hestiacp/blob/32c6580f7b5e88667defd90df49d9353d5cb0fbc/bin/v-sync-dns-cluster#L57-L59

**Comment by ponasromas** [comment]
Nice design. So, I have ton of domains in master, how to resync them into slaves?

**Comment by jaapmarcus** [comment]
v-update-sys-queue dns-cluster  syncs up any changes made via the panel to slaves...

After you have made the changes via the panel or v-xxx comands ...

**Comment by ponasromas** [comment]
And if I have made changes in .db file all is lost? This is not good.

**Comment by jaapmarcus** [comment]
> And if I have made changes in .db file all is lost? This is not good.

That was how it always was... Never change them directly ..
