### ISSUE TITLE
table on statistics tab is missing the last icon for backups

### ISSUE THREAD

**Issue by FalzoMAD** [hestiacp/hestiacp#395]
see screenshot, the table lacks the backup icon and as it seems also the tooltip for the last columns is off...

![image](https://user-images.githubusercontent.com/25381635/59978801-b72e7980-95e0-11e9-9205-e9ecf160669a.png)

**Comment by johnnyq** [comment]
I noticed that too, thanks for reporting

**Comment by ghost** [comment]
Fixed in v1.0.1.
