### ISSUE TITLE
Add DNS Zone - Missing Template Option

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#396]
In a few words, please describe the issue that you're experiencing:
Under add DNS Zone its missing template under advanced options. This is present under edit DNS Zone.

What steps did you take when the issue occured?
1. Click DNS tab
2. Click Add DNS Zone
3. Click Advanced

Expected behavior:
Template option should be shown under advanced

Operating system distribution and release:
Ubuntu 18.04.2 (LXC Proxmox)

Which version of Hestia Control Panel is currently installed?
1.00.0-190618

Which branch are you using?
master

Which of the following web server configurations are you using?
default

Which of the following server roles are installed on your server?
default

In order to better assist, please post any relevant log information below:
N/A

Related issues or forum threads:
N/A

Additional notes:
N/A

**Comment by ghost** [comment]
As mentioned under #398, the current backend does not allow the template for a DNS zone to be assigned or changed prior to its creation. We'll revisit this for a future release to see how the process can be improved.
