### ISSUE TITLE
Add Mail Domain - Missing "Enable SSL for this domain"

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#397]
In a few words, please describe the issue that you're experiencing:
Under add Mail Domain it is missing "Enable SSL for this domain". This is present under edit Mail Domain.

What steps did you take when the issue occured?

1. Click Mail tab
2. Click Add Mail Domain

Expected behavior:
Enable SSL for this domain should be listed

Operating system distribution and release:
Ubuntu 18.04.2 (LXC Proxmox)

Which version of Hestia Control Panel is currently installed?
1.00.0-190618

Which branch are you using?
master

Which of the following web server configurations are you using?
default

Which of the following server roles are installed on your server?
default

In order to better assist, please post any relevant log information below:
N/A

Related issues or forum threads:
N/A

Additional notes:
N/A

**Comment by ScIT-Raphael** [comment]
Same reason as in https://github.com/hestiacp/hestiacp/issues/399
