### ISSUE TITLE
[Bug] EMali with additional FTP account details does not contain suffix

### ISSUE THREAD

**Issue by campodoro74** [hestiacp/hestiacp#3975]
### Describe the bug

When creating an additional FTP account for a domain, the specified suffix is not shown in the email with credentials.

Example:

FTP account has been created and ready to use.

Hostname: sub.domain.name
**Username: domainuser_**
Password: on9Q[-C|lofAmC(l

Best regards,

--
Hestia Control Panel

### Tell us how to replicate the bug

1. Create additional FTP user
2. Add suffix, like domainuser_ftpname
3. Send credential email
4. the ftpname part of the full username is missing in the email, it IS present in the control panel and it _does_ work

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.7

### Operating system

Deban 11

**Comment by gudge25** [comment]
same  here

**Comment by jaapmarcus** [comment]
See attached PR
