### ISSUE TITLE
Add Web Domain - Missing DNS Zone Template when Create DNS Zone is checked

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#398]
In a few words, please describe the issue that you're experiencing:
Under add Web Domain there is an option to create DNS Zone, but no option to select the DNS Zone template under Advanced.

What steps did you take when the issue occured?

1. Click Web tab
2. Click Add Web Domain
3. Click Advanced

Expected behavior:
DNS Template option should be shown under advanced if Create DNS Zone is selected

Operating system distribution and release:
Ubuntu 18.04.2 (LXC Proxmox)

Which version of Hestia Control Panel is currently installed?
1.00.0-190618

Which branch are you using?
master

Which of the following web server configurations are you using?
default

Which of the following server roles are installed on your server?
default

In order to better assist, please post any relevant log information below:
N/A

Related issues or forum threads:
N/A

Additional notes:
N/A

**Comment by ghost** [comment]
Unfortunately at this time, the current backend does not allow for DNS zone template to be assigned to a domain/zone prior to it's creation and must be done after the fact; this is true even if you were to add a new DNS domain under the DNS tab directly. We'll take a look further into this to see how the process can be improved in future releases.
