### ISSUE TITLE
[Bug] Login Session Issue

### ISSUE THREAD

**Issue by ponasromas** [hestiacp/hestiacp#3982]
### Describe the bug

Session parameter "SameSite" left unset, which leads to problems when logging in to hestiacp if PHPSESSID set on domain.tld and hestiacp is on sub,domain.tld .

### Tell us how to replicate the bug

1. https://domain.tld - login system which sets up cookie PHPSESSID:

```
[
    'expire' => time() + (60 * 60 * 24),
    'lifetime' => 0,
    'path' => '/',
    'domain' => domain.tld,
    'secure' => 1,
    'httponly' => 1,
    'samesite' => 'Strict'
]
```

2. Server with HestiaCP:

```
[
    ...
    'path' => '/',
    'domain' => sub.domain.tld,
    'secure' => 1,
    'httponly' => 1,
    'samesite' => ''
]
```

SameSite attr is not set to 'Strict' in HestiaCP, which interferes with PHPSESSID set on domain.tld and login bounces back. When deleting domain.tld PHPSESSID (Storage->Cookies in your browser) problem is resolved.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.7

### Operating system

Debian 12

**Comment by jaapmarcus** [comment]
We renamed the session cookie name already to something else for the next release 

Attached PR will set it to strict ...
