### ISSUE TITLE
[Bug] Traffic Stat

### ISSUE THREAD

**Issue by gunyakov** [hestiacp/hestiacp#3986]
### Describe the bug

Suddenly hestia start miscalculate traffic statistic
![Снимка от 2023-09-06 15-38-54](https://github.com/hestiacp/hestiacp/assets/11561182/d0bf9ac3-c12a-4326-a412-2303e68d9d5b)
But have so high traffic during one day only is completely impossible for micro vps server

### Tell us how to replicate the bug

1. Install Hestia CP
2. Wait until bug happens.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.7

### Operating system

ubuntu 20

**Comment by jaapmarcus** [comment]
If you reboot the server it RRD logs extreme amount. Due to the period is wrong. 

Don't know how to fix it and probably not important enough to fix it imo...
