### ISSUE TITLE
[Bug] FTP Details on emails doesn't send full FTP Username 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#3989]
### Describe the bug

![image](https://github.com/hestiacp/hestiacp/assets/39749258/280da529-8f4c-4b36-b537-beb91078a1f0)

### Tell us how to replicate the bug

Send FTP Details via email.

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.8.7

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Bug has been patched but not yet released
