### ISSUE TITLE
Add Web Domain - Missing Lets Encrypt support when Enable Mail is checked

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#399]
In a few words, please describe the issue that you're experiencing:
Under add Web Domain there is an option to "Enable mail for this domain", but no option to add Lets Encrypt to mail under "Enable SSL for this domain"

What steps did you take when the issue occured?

1. Click Web tab
2. Click Add Web Domain
3. Click Advanced
4. Click Enable SSL for this domain

Expected behavior:
there should be an option to Enable Lets Encrypt for mail or maybe just make it automatic when use lets encrypt is selected when Enable mail for this domain is checked

Operating system distribution and release:
Ubuntu 18.04.2 (LXC Proxmox)

Which version of Hestia Control Panel is currently installed?
1.00.0-190618

Which branch are you using?
master

Which of the following web server configurations are you using?
default

Which of the following server roles are installed on your server?
default

In order to better assist, please post any relevant log information below:
N/A

Related issues or forum threads:
N/A

Additional notes:
N/A

**Comment by ScIT-Raphael** [comment]
This is by design, because we need to have some configuration files already created to fullfill let's encrypt certificates requirements. You can compare this with the creation of a web domain, there you also can't create a let's encrypt cert directly.
