### ISSUE TITLE
Possible Re-Evaluation: mail.domain.ext instead of the additonal webmail.domain.ext record

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#400]
### In a few words, please describe the issue that you're experiencing:
I was looking at some of the DNS Records created for mail and looked at webmail im wondering if we could just use mail.domain.ext instead of having webmail as an addition. I believe thats the more modern approach and the less is more thinking mentaility. I also looked at the other "A" records being added by default smtp, pop, imap, ftp. Im wondering if these could be elimiated as well by default. I know I personally delete the extra records, it just keeps a cleaner look when navigating. This is me just brain storming and would require discussion amongst the community. 

### What steps did you take when the issue occured? 
N/A

### Operating system distribution and release:
Ubuntu 18.04.2

### Which version of Hestia Control Panel is currently installed?
1.00.0-190618

### Which branch are you using?
master

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

### In order to better assist, please post any relevant log information below:
N/A

### Related issues or forum threads:
N/A

### Additional notes:
N/A

**Comment by FalzoMAD** [comment]
that's not really thought to the end. not everyone uses mail on the same server at all, so mail.domain might not always point to the same box. for webmail just use webmail.domain if needed.

and don't forget that quite some people don't even use the internal dns at all...

**Comment by ghost** [comment]
After discussing this internally, we will be leaving the webmail subdomain as well as the /webmail/ alias which is also accessible in the event that DNS isn't hosted by Hestia or you don't have a record for webmail in your DNS zone pointed to the server. The value is configurable under Server > Configure so if you wish to change it to something else there you can and it will update the records and vortial hosts accordingly.
