### ISSUE TITLE
[Bug] suspending user is not suspending domain

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#4000]
### Describe the bug

suspend user in panel or cli, is not suspending domain ... is marked as suspended, but is acessible. Run suspend domain only work fine.
database is suspending correctly.

### Tell us how to replicate the bug

suspend user in panel or cli, is not suspending domain ... is marked as suspended, but is acessible. Run suspend domain only work fine.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.7

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
Fix has been merged
