### ISSUE TITLE
[Bug] Bandwidth disappears when updating Hestia

### ISSUE THREAD

**Issue by systracer** [hestiacp/hestiacp#4001]
### Describe the bug

On tab STATS there are statistics by month, for examble:

Sep 2023, Bandwidth 5.64 tb / 0.00 mb
Aug 2023, Bandwidth 3.95 tb / 0.00 mb
Jul 2023, Bandwidth 4.21 tb / 0.00 mb

When I simply update Hestia from v1.7.7 to 1.8.7, then Bandwidth becomes zero for all months (almost a year).

### Tell us how to replicate the bug

1. apt update & apt upgrade

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.7.7

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
0.MB is probably the number assigned in the package can you check if it is set to unlimited?

**Comment by systracer** [comment]
Thanks for the answer. In PACKAGE there are two packages - default and system, in each Bandwidth is set as unlimited.

**Comment by systracer** [comment]
Where are Bandwidth statistics stored? Maybe I can copy these files and return them after the update?

**Comment by systracer** [comment]
I realized what the problem is - in the new version, the general Bandwidth statistics are not visible from the administrator account, it is visible only for each user separately, but for this you need to log in under each user, and this is very inconvenient. Is it possible to see general Bandwidth statistics under the admin, as was the case in version 1.7.7?

**Comment by jaapmarcus** [comment]
It shows: 

Data usage / Package size of the current user...
<img width="1266" alt="Screenshot 2023-09-16 at 08 45 31" src="https://github.com/hestiacp/hestiacp/assets/9754650/59dd0251-28a8-4779-b73c-a9331966bbeb">
y default

In the user view you should be able to see the user usage 
<img width="1195" alt="Screenshot 2023-09-16 at 08 43 17" src="https://github.com/hestiacp/hestiacp/assets/9754650/06f420e5-264d-416c-9c97-bc6bde09501a">

**Comment by systracer** [comment]
Thanks for the answer! The topic does not concern the Users tab, only the Stats tab, where you can see the traffic history for each month.
Indeed, in the new version of Stats, statistics for each user are visible separately, and this has become very inconvenient, because under the administrator, general statistics for all users together are no longer visible. Previously, in version 1.7.7, this was visible:
![изображение](https://github.com/hestiacp/hestiacp/assets/12216488/e997e340-5cfd-4b17-96bf-909324f0218d)
Where "View All Statistic" selected by default and shows all statistics, and in "Show Per User" you can select a specific user and see monthly statistics only for him.
In the new version, this choice has disappeared completely ("View All Statistics" and "Show Per User") and I'm trying to understand whether this is a bug or done on purpose? But what's the point of making it worse than it was?

**Comment by jaapmarcus** [comment]
Fixed it was a bug due to changes in the behavoir in a few versions ago..

**Comment by systracer** [comment]
Thank you very much for your work!
