### ISSUE TITLE
Alert Notifications Interface

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#402]
New Hestia version v0.10.0. got alerts icon on top-right, but there is no time stamps specified, when the alert triggered.

also send email to the root admin - so the admin could start to moniter if there is any major issues occurred while upgrades..

**Comment by ghost** [comment]
Hi @vvcares, thanks for submitting this -- we'll take a look at it for the next release.

**Comment by vvcares** [comment]
Today - v1.0.1, the alert popup window is not showing for ADMIN user.

**Comment by ScIT-Raphael** [comment]
Fixed in master branch, will be shipped with v1.0.2.

**Comment by vvcares** [comment]
Auto Update triggered on 22-07-2019. The versions info shows wrongly.
- alert popup shows v0.10.0
- server configuration-release shows - v1.0.4

suggestion : Kindly display the Hestia version on top-right-bar. So the admins will know if there is changes. This will help us to check if anything goes wrong & we may check the release notes about changes on-time..

ref image : https://ibb.co/Z81Kbtm
