### ISSUE TITLE
[Feature] Adding woff2 and webmanifest in default Proxy Extensions

### ISSUE THREAD

**Issue by hardcpp** [hestiacp/hestiacp#4024]
### Describe the feature or change in detail

Adding the .woff2 and .webmanifest into nginx default Proxy Extensions

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/c2279250399c839ed7be93db7a6aa14b077922fb/bin/v-add-web-domain#L200

woff2 is already include ...

Will add .webmanifest
