### ISSUE TITLE
[Bug] Restore failure if a subsystem (e.g database) doesn't exist new server

### ISSUE THREAD

**Issue by istiak101** [hestiacp/hestiacp#4031]
### Describe the bug

v-restore-user user user.2023-09-25_20-55-09.tar

```
-- DB --
2023-09-25 22:12:59 db_name
/backup/tmp.VGaI4NQJhn/db/db_name/db_name.mysql.sql.zst: 1374 bytes 
Error: Connection to localhost failed
```

If previous HestiaCP server contains a subsystem( e.g Database) but new server was installed without this subsystem (database) restoration gets aborted while restoring database.

Expected result: Do not abort the restore if any subsystems doesn't exist. Restore either through a --force flag or notify the user that subsystem doesn't exist.

### Tell us how to replicate the bug

1. Generate a backup on previous server with a subsystem (e.g database)
2. New server doesn't contain database system
3. Try to restore a user

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.8.8

### Operating system

Debian 11

**Comment by sahsanu** [comment]
Do you know that `v-restore-user` command has more arguments to specify what do you want to restore?
`v-restore-user USER BACKUP [WEB] [DNS] [MAIL] [DB] [CRON] [UDIR] [NOTIFY]`

So if you don't want to restore dns use this:
`v-restore-user user user.2023-09-25_20-55-09.tar yes no`

**Comment by jaapmarcus** [comment]
I think the main issue is mainly the DB. 

I know it doesn't give an F if Apache2 is not installed (or not)..

**Comment by istiak101** [comment]
I wasn't aware of those extra arguments. My mistake then. Thanks.
