### ISSUE TITLE
[Bug] nginx showing stopped even though it's not

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#4032]
### Describe the bug

All my Hestia instances are showing nginx as stopped even though the service is running, and all sites are working fine

### Tell us how to replicate the bug

1. Click on Server Settings
2. Look at nginx status

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.8

### Operating system

Debian 10

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4022

Fixed but not yet released
