### ISSUE TITLE
Add nextjs | sveltkit | nuxtjs, nodejs & bun builder and runner for quick deployment

### ISSUE THREAD

**Issue by justinelut** [hestiacp/hestiacp#4054]
### Describe the feature or change in detail

In the modern world the meta frameworks are being used widely by developers around the world. I would like to request a feature support like vercels one, where you just upload your nextjs or sveltkit or nuxt files and hestia builds, and runs them which would be a game changer and inturn simplify how we deploy our custom applications to our own vps or dedicatated servers.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
What is wrong with building it before you upload?

**Comment by justinelut** [comment]
If its like vercel or application install plugin you have on hestia, it will be more easier to run the meta frameworks, or just native support for nodejs applications
