### ISSUE TITLE
[Bug] SSL Cert Distribution

### ISSUE THREAD

**Issue by ouam3r** [hestiacp/hestiacp#4058]
### Describe the bug

Hello,

Can someone help me out fix an issue with SSL cert distribution for mapped domains in WP MultiSite? 
At first, I used to add custom domains as aliases in order fully map the domain to a subdomain, when I used Cloudflare SSL origin cert it started acting kind of weird. At some point when I add domains in alias as an addon domain it shows error code 400.

I really need your help on this.

### Tell us how to replicate the bug

I followed the regular steps as per the instructions

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.8.8

### Operating system

Ubuntu 22.04

**Comment by jaapmarcus** [comment]
Cloud orgin certifacates don't work with other domains then the "main" domain

Create new domain and use the custom docroot and it should work fine
