### ISSUE TITLE
[Bug] '--port' installation option gets ignored when installing.

### ISSUE THREAD

**Issue by bermudi** [hestiacp/hestiacp#4061]
### Describe the bug

Used https://hestiacp.com/install.html to generate the installation command with --port '8080' as parameter and after finishing the following text was generated:

Ready to get started? Log in using the following credentials:

        Admin URL:  https://example.com:8080
        Backup URL: https://example.com:8080
        Username:   admin
        Password:   The password you chose during installation.

But after trying that port and failing I did a quick check of open ports and found 8083 open, the default port.

### Tell us how to replicate the bug

1. install Hestia CP with --port 8080
2. Finish installation, reboot
3. Check the installation log for CP url, it says port 8080
4. Try to connect to server at port 8080. Fails
5. Try to connect to default port 8083, it succeeds 

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.8.8

### Operating system

Debian GNU/Linux 12 (bookworm)

**Comment by jaapmarcus** [comment]
Port 8080 might be in use by Apache2 ... In that case the port change will fail

**Comment by bermudi** [comment]
server didn't even had curl installed, so no, there was no apache or anything else using any ports

**Comment by jaapmarcus** [comment]
Hestia installs Apache2 by default...

v-change-sys-port 8080 will now fail..

**Comment by bermudi** [comment]
I'm sorry I'm confused, this isn't a bug then? I expected the ui to be installed on port 8080 because that was what I entered in the installation command.

**Comment by jaapmarcus** [comment]
Yes but Apache2 is probably installed first so it will fail...
