### ISSUE TITLE
[Bug] Install.html for Main Page 10/24/2023 doesnt work correctly.

### ISSUE THREAD

**Issue by VanillaChan6571** [hestiacp/hestiacp#4096]
### Describe the bug

10/23/2023 I was testing this install command, it worked correctly and got it running No Issue.

10/24/2023, This just recently got updated and there is no reason to update the install command generator. What the f- did you do? It doesn't even work. All I get in return it `hst-install.sh: illegal option -- -`

Good job. Release an update and never tested. 

### Tell us how to replicate the bug

1. Go https://hestiacp.com/install.html and follow the guide.
2. Doesn't work as you get an `hst-install.sh: illegal option -- -`

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

N/A

### Operating system

Ubuntu 22.04.03 LTS

### Log capture

```shell
root@vpsdemo:~# bash hst-install.sh --email=demo@demo.net --password=TestDemo12345! --multiphp=yes --sieve=yes --quota=yes
hst-install.sh: illegal option -- -
Usage: hst-install.sh [OPTIONS]
  -a, --apache            Install Apache        [yes|no]  default: yes
  -w, --phpfpm            Install PHP-FPM       [yes|no]  default: yes
  -o, --multiphp          Install Multi-PHP     [yes|no]  default: no
  -v, --vsftpd            Install Vsftpd        [yes|no]  default: yes
  -j, --proftpd           Install ProFTPD       [yes|no]  default: no
  -k, --named             Install Bind          [yes|no]  default: yes
  -m, --mysql             Install MariaDB       [yes|no]  default: yes
  -M, --mysql8            Install MySQL         [yes|no]  default: no
  -g, --postgresql        Install PostgreSQL    [yes|no]  default: no
  -x, --exim              Install Exim          [yes|no]  default: yes
  -z, --dovecot           Install Dovecot       [yes|no]  default: yes
  -Z, --sieve             Install Sieve         [yes|no]  default: no
  -c, --clamav            Install ClamAV        [yes|no]  default: yes
  -t, --spamassassin      Install SpamAssassin  [yes|no]  default: yes
  -i, --iptables          Install Iptables      [yes|no]  default: yes
  -b, --fail2ban          Install Fail2ban      [yes|no]  default: yes
  -q, --quota             Filesystem Quota      [yes|no]  default: no
  -d, --api               Activate API          [yes|no]  default: yes
  -r, --port              Change Backend Port             default: 8083
  -l, --lang              Default language                default: en
  -y, --interactive       Interactive install   [yes|no]  default: yes
  -s, --hostname          Set hostname
  -e, --email             Set admin email
  -p, --password          Set admin password
  -D, --with-debs         Path to Hestia debs
  -f, --force             Force installation
  -h, --help              Print this help

  Example: bash hst-install.sh -e demo@hestiacp.com -p p4ssw0rd --multiphp yes
```

**Comment by tudorr89** [comment]
What are you talking about? You just need to run apt-update && apt upgrade to upgrade, NOT the install bash script as that can potentially override and break your installation.

**Comment by jaapmarcus** [comment]
@VanillaChan6571 is right you can't use

--force=yes  as it also support -f option with a value 

Will create a PR to fix it and update the release branch

**Comment by jaapmarcus** [comment]
hestiacp.com will update in about 2 min

**Comment by VanillaChan6571** [comment]
> What are you talking about? You just need to run apt-update && apt upgrade to upgrade, NOT the install bash script as that can potentially override and break your installation.

What the hell are you smoking? This has nothing to do with "apt-update && apt upgrade" This is also tested on a fresh machine. It seems the repo fixed the fresh install.
