### ISSUE TITLE
[Bug] email limits file resets to default

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#4102]
### Describe the bug

Every once in a while my client complaints because she can't send emails because of the account limit.

The thing is that when I check /home/client/conf/mail/domain.es/limits
All limits have been changed to the default value that is 200.
So my client that is a lawyer specialized in court procedures and needs to send sometimes 1000 in an hour hits the limit.
This client only needs the limit on one of the accounts.

When do this limits get reset? Why? Is it the default behavior?

### Tell us how to replicate the bug

All files in the folder have been regenerated October 25 at 7:20 so I  guess it is triggered upon rebuild

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

Latest

### Operating system

Debian 11

**Comment by jaapmarcus** [comment]
Edit mail account

<img width="670" alt="Screenshot 2023-10-26 at 10 56 26" src="https://github.com/hestiacp/hestiacp/assets/9754650/1b371954-3e5d-4951-8e52-4408703c5200">

And it should be saved permentaly


It should update on rebuild, Chaning thing in email account and so on..

**Comment by jlguerrerosanz** [comment]
So I have to change it via panel and not by directly editing the file

**Comment by jaapmarcus** [comment]
Yes .. Or Command line ...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/main/bin/v-change-mail-account-rate-limit

or

https://github.com/hestiacp/hestiacp/blob/main/bin/v-change-mail-domain-rate-limit
