### ISSUE TITLE
[Bug] Incorrect DNS for DKIM if using subdomain

### ISSUE THREAD

**Issue by ram108** [hestiacp/hestiacp#4113]
### Describe the bug

If a subdomain is used for mail `subdomain.domain.com`, the DKIM DNS record for that domain is not created correctly.

Created: `mail._domainkey`
Should be: `mail._domainkey.subdomain`

Source: https://forum.hestiacp.com/t/incorrect-dns-for-dkim-if-using-subdomains/11664

### Tell us how to replicate the bug

--

### Which components are affected by this bug?

Control Panel Backend, Mail Security (Antivirus, Antispam)

### Hestia Control Panel Version

1.8.10

### Operating system

Ubuntu 22.04

**Comment by ram108** [comment]
Google's recommendations for DKIM for subdomains: https://support.google.com/a/answer/177063?hl=en

**Comment by jaapmarcus** [comment]
It depends if you add it to the main domain zone or sub.domain.com zone ...

**Comment by ram108** [comment]
I didn't add anything manually, just used the Hestia interface. 

Maybe I'm not understanding these Hestia screenshots correctly, but visually I see the wrong entry.

**Comment by jaapmarcus** [comment]
You need to copy over to the DNS  provider if you use Cloudflare or any other provider ... 

So it is for information only

**Comment by ram108** [comment]
So these records are just for information only? Hestia can't be used as an ns server? 

Apologies if I don't understand this, I just wanted to use my own server with the Hestia panel as an ns server and thought Hestia creates the correct DNS records automatically.

**Comment by jaapmarcus** [comment]
You can use DNS zones but they are under the DNS tab.

Not mail tab...

**Comment by jaapmarcus** [comment]
<img width="1146" alt="Screenshot 2023-10-28 at 16 28 23" src="https://github.com/hestiacp/hestiacp/assets/9754650/35555895-ca39-4280-9b5f-a3ca1e36a837">

**Comment by jaapmarcus** [comment]
It really depends on how the user has implement it on their server / DNS as it is really for information only  I don't to display 2 methods and they still need to guess what one to use ..
