### ISSUE TITLE
[Feature] Restore hosting packages

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#4117]
### Describe the feature or change in detail

We have about 20 or so packages, and restoring a user does not recreate the corresponding hosting package, any way to move those over to a new server easily?

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
/usr/local/hestia/data/packages/ contains all the packages.  You should be able to create them when you setup a new server.

If I have more servers create a git repo store there all the packages  / custom templates in and clone theme and add some automation to it. 

Make sure that they exist before restoring the user and it should work fine.
