### ISSUE TITLE
[Bug] stats for user hestiamail Internal Server Error

### ISSUE THREAD

**Issue by maisondasilva** [hestiacp/hestiacp#4122]
### Describe the bug

![image](https://github.com/hestiacp/hestiacp/assets/11423362/3bd64b33-ccff-4a37-a1de-7304ce4901cb)

![image](https://github.com/hestiacp/hestiacp/assets/11423362/a748a56c-bbf8-432f-be77-217aca36f6a6)

### Tell us how to replicate the bug

1 open stats
2 select user hestiamail 

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.10

### Operating system

Ubuntu 22.04 (aarch64)

**Comment by jaapmarcus** [comment]
hestiamail should not have any stats it is a bug in the listing ...

**Comment by jaapmarcus** [comment]
Bug has been patched but never closed
