### ISSUE TITLE
nginx config as been rewrite my config with the default

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#413]
Hi;

2 days ago I modified nginx.conf and nginx.ssl.conf for a subdomain would use nextcloud.

It is the only one with modification but i seams all **nginx**.conf and nginx.ssl.conf on the servers has been **regenerated** this morning at 07:42 CET (Zurich time)

**Comment by ScIT-Raphael** [comment]
Due to a auto upgrade, the config files have been regenerated. It is not save at all to modify the config files directly, we strongly suggest to create a own template (for example called nextcloud) in /usr/local/hestia/data/templates/web/[nginx/apache2]. You can just copy the default template if you want. I will talk with the team that we create a "do not edit file"-remark directly in the config files as a warning.

**Comment by JOduMonT** [comment]
in the meanwhile I understand it is better to works with template
but if I make my own template I still won't benefit of the upgrade
it would be nice to add differents templates at the project or has a side project so we could put our effort all together

**Comment by ScIT-Raphael** [comment]
Mostly the changes on the templates arent big (for example magento2 needs just a edit at openbasedir restriction on apache2 + nginx configuration). Also for nginx + phpfpm there are already a bunch of preset templates you could use.

**Comment by jodumont** [comment]
Oh! Yes I see a bunch of preset templates phpfpm ([here](https://github.com/hestiacp/hestiacp/tree/master/install/deb/templates/web/nginx/php-fpm))

but for a reason or another I just have the nginx preset ([those](https://github.com/hestiacp/hestiacp/tree/master/install/deb/templates/web/nginx))

#### do you understand why I don't have those phpfpm preset ?

I might worth to mention I expressly did'nt install apache with `-a no`

**Comment by mohsenMJ** [comment]
regarding to this link :

https://github.com/hestiacp/hestiacp/issues/413#issuecomment-505748163

I totally need something like that and really appreciate it if you add it to amazing Hestiacp , I have to change everything back to my settings when they are overwritten ,

please let us know when this will happen !

Thank you for this awesome control panel

**Comment by ScIT-Raphael** [comment]
@mohsenMJ check https://docs.hestiacp.com/admin_docs/web.html#how-do-web-templates-work

**Comment by mohsenMJ** [comment]
Thanks for the quick response , 


how can I change /usr/local/hestia/data/templates/web/nginx/default.stpl for a specific domain !?

I have other domains that works fine but for a specific domain I need to redirect to "localhost \" ->  localhost:3000

```
location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
} 
```

**Comment by ScIT-Raphael** [comment]
Edit web domain and choose the template. You can do a custom template which redirect to the port 3000. Please go over to our discord or forum, we dont want to use github for support requests.

**Comment by mohsenMJ** [comment]
Thanks a lot , It is working.

My problem is solved.
