### ISSUE TITLE
Feature Request: Genericify Roundcube

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#414]
### In a few words, please describe the issue that you're experiencing:
It would awesome to have the roundcube logo replaced with a generic header maybe a white envelop fontawesome icon and just read Mail or Webmail or even the fqdn example webmail.domain.ext. Also remove the footer at the bottom Roundcube Webmail by default.

### What steps did you take when the issue occured? 
1. login to roundcube

### Operating system distribution and release:
Ubuntu 18.04.2 LXC Proxmox

### Which version of Hestia Control Panel is currently installed?
1.01

### Which branch are you using?
master

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

### In order to better assist, please post any relevant log information below:
N/A

### Related issues or forum threads:
N/A

**Comment by ScIT-Raphael** [comment]
Basicly, we use the default roundcube package, shipped by the os repository. Until now, we do not have any plans to modify that package but we will maybe provide a paid customizing service if needed.
