### ISSUE TITLE
[Bug] upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#4143]
### Describe the bug

I found some wordpress setups that works good with php 7.4, but get the error "upstream sent too big header while reading response header from upstream" with 8.0, 8.1 and 8.2.

Even if I try to increase the buffers to:
```
        # FastCGI settings
        fastcgi_buffers                 512 1m;
        fastcgi_buffer_size             1m;
        fastcgi_busy_buffers_size       1m;
        fastcgi_temp_file_write_size    1m;
```

### Tell us how to replicate the bug

I can not reproduce with any kind of wordpress setup. I am still trying to understand.

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.10

### Operating system

Ubuntu 20.04

### Log capture

```shell
502 bad gateway 
"upstream sent too big header while reading response header from upstream"
```

**Comment by franciscopaniskaseker** [comment]
Tried also to increase:
```
        proxy_buffers                   512 1m;
        proxy_buffer_size               1m;
        proxy_busy_buffers_size         1m;
        proxy_temp_file_write_size      1m;
```

then I started to see 520 error.

**Comment by franciscopaniskaseker** [comment]
with extra proxy/fastcgi sizes, will work with  php 7.4, but not with any 8.x version.

**Comment by jaapmarcus** [comment]
It is caused by Nginx config:

https://serverfault.com/questions/1119374/nginx-42-upstream-sent-too-big-header-while-reading-response-header-from-upstr

Increasing should be enough but it is hard to know what is right in your situation it is mainly caused where Apache2 is putting out a lot of data..

As there is no fix from our site I don't see a reason to keep it open...

**Comment by franciscopaniskaseker** [comment]
I increased everything from 1m to 5m. Does not make any sense. still 520 http error.  I can not reproduce in other panels, just in this hestiacp setup.

**Comment by jaapmarcus** [comment]
Check the timeouts 

Most panels don't Nginx proxy in front of Apache2..
