### ISSUE TITLE
[Feature] Multiple Contact Details

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#4148]
### Describe the feature or change in detail

We use the details in our Hestia instance to contact customers, sometimes also via a script to collect all customer mails and send a bulk mail. For some cases (e.g. outage) it would be good to have internal and external contact address separated, or separate contact adresses for reseller and user.
The old LiveConfig had such a feature, and InvoiceNinja also allows to add multiple contacts per customer, so that would be ideal.
Alternatively the ability to specify a secondary mail address (one could call it the "recovery address" as service like github do) would already be of great use. This could then be an address outside the server, or of the person supporting the user.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
This feature does not belong in Hestia but in Fossbilling or InvoiceNinja or any other billing system... 

I don't see any reason to add it...
