### ISSUE TITLE
VestaCP Migration to HestiaCP MariaDB user passwords not working

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#415]
### In a few words, please describe the issue that you're experiencing:
Everything went well except the mysql 5.7.26 database passwords did not port over from Vesta Ubuntu 16.04.5 default install to HestiaCP MariaDB 10.4. This was no problem as I reset each database password. Could be a problem for larger installations

### What steps did you take when the issue occured? 
1. Backup data on an existing vestacp
2. import into new hestiacp

### Expected behavior:
Database User Passwords should still work
### Operating system distribution and release:
Ubuntu 16.04.5 to Ubuntu 18.04.2

### Which version of Hestia Control Panel is currently installed?
Vesta to HestiaCP 1.0.1

### Which branch are you using?
master

### Which of the following web server configurations are you using?
default on both

### Which of the following server roles are installed on your server?
default on both

### In order to better assist, please post any relevant log information below:
N/A

### Related issues or forum threads:
N/A

### Additional notes:
Has anyone else experianced this problem or may know what the culprit is, I didnt do much investigation yet, but I belive it to be incompatable password backend between mysl 5.7.26 and MariaDB 10.4

**Comment by ScIT-Raphael** [comment]
This is a known VestaCP issue, due to not saved mysql user passwords: https://forum.vestacp.com/viewtopic.php?t=13239

We can't do here anything, because the passwords are not shipped inside of the configuration file. So you would need to "repair" first the vesta installation, then take backups and do the migration.
