### ISSUE TITLE
[Bug] Database file conf not updated after delete database for API

### ISSUE THREAD

**Issue by schneiderbruno** [hestiacp/hestiacp#4159]
### Describe the bug

Hello

I'm having problems with backups. When checking what happened in the backup.log, the error is that the dump of the XXX database was not possible because this database does not exist.
When checking the hestiacp panel, the database was not found, nor in mysql.
The database was deleted via the api, using the "v-delete-database" command.

The error is, it seems to me, in not updating the "db.conf" file (or file that saves which databases are to be backed up), it was not updated with this exclusion through the api.
So when trying to perform a database backup, it will try to backup a database that has already been deleted.

### Tell us how to replicate the bug

1. Create database
2. Delete database use api "v-delete-database"
3. Try execute backup

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.8.10

### Operating system

Debian 12.2

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/bug-in-backups-sql/11873

**Comment by jaapmarcus** [comment]
See forum topic
