### ISSUE TITLE
[Feature Request] set nameservers on installer

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#416]
# Feature Request
### Additional notes:
Add the possibility to set the nameservers and their ip's on the installer, avoiding the ns1.example.com on the packages

**Comment by johnnyq** [comment]
+1 =]

**Comment by ghost** [comment]
Thanks for submitting this @skullwritter, we'll discuss this internally and follow up soon. :)

**Comment by ScIT-Raphael** [comment]
We discussed this internaly and we agreed to implement it to our installer scripts. We should push a commit within the next 24 to 48 hrs, again thanks @skullwritter for the good idea!

**Comment by tlcd96** [comment]
you're welcome

**Comment by ScIT-Raphael** [comment]
Added to master branch: https://github.com/hestiacp/hestiacp/commit/08acf2e31c5d0342eadf05ac147d6d53fc62c597
