### ISSUE TITLE
the "listen ... http2" directive is deprecated, use the "http2" directive

### ISSUE THREAD

**Issue by umair-murtaza-dev** [hestiacp/hestiacp#4160]
### Describe the bug

i am using nginx 1.25.3 and getting this error 

update the nginx and restart the server it will not worked for me

please help

thanks in advance

### Tell us how to replicate the bug

the "http2_push_preload" directive is obsolete, ignored

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Web Interface

### Hestia Control Panel Version

1.25.3

### Operating system

MacOs

**Comment by jaapmarcus** [comment]
Update  Hestia to the last version 

1.8 should have support for it with out any issues

**Comment by jaapmarcus** [comment]
For https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_push_preload

remove it...
