### ISSUE TITLE
[Bug]  File manager got a error "Unknown error"

### ISSUE THREAD

**Issue by nebuchad908** [hestiacp/hestiacp#4164]
### Describe the bug

On a fresh HestiaCP installation we got a error "Unknown error" when filemanager is opened.

![image](https://github.com/hestiacp/hestiacp/assets/15632675/430f54ab-c9e0-40bc-af62-a3eab5264f1d)

### Tell us how to replicate the bug

1) Install latest Hestia CP 
2) Create user
3) Login as newly created user
4) Go to Filemanager 

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.10

### Operating system

Ubuntu 22.04.3 LTS

### Log capture

```shell
When FM is open, auth.log contains an error:

Nov 17 13:59:15 sshd[154924]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Nov 17 13:59:15 sshd[154924]: Received disconnect from 127.0.0.1 port 41830:11:  [preauth]
Nov 17 13:59:15 sshd[154924]: Disconnected from authenticating user admin 127.0.0.1 port 41830 [preauth]

fix:

add 

PubkeyAcceptedAlgorithms=+ssh-rsa

to /etc/ssh/sshd_config

and restart sshd
```

**Comment by jaapmarcus** [comment]
Update /etc/ssh/sshd_config 

Error is clear ...

**Comment by nebuchad908** [comment]
> Update /etc/ssh/sshd_config
> 
> Error is clear ...

It is not a clear error: 
Nov 17 13:59:15 sshd[154924]: **userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]**

Do you seriously think that changing the configuration file after installation - is normal?

**Comment by jaapmarcus** [comment]
> > Update /etc/ssh/sshd_config
> > Error is clear ...
> 
> It is not a clear error: Nov 17 13:59:15 sshd[154924]: **userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]**
> 
> Do you seriously think that changing the configuration file after installation - is normal?

We don't modify PubkeyAcceptedAlgorithms during the installation and any provider can use their own config it is to find all execrations in each case.

If a user encounters the issue he can use the search function and fix it them self...
