### ISSUE TITLE
[Feature] Add templante for WordPress with disable XMLRPC

### ISSUE THREAD

**Issue by maisondasilva** [hestiacp/hestiacp#4165]
### Describe the feature or change in detail

Add other templates with one of the code below!

Example wordpress-xmlrpc

https://wetopi.com/disable-wordpress-xmlrpc/#manually-disable-xmlrpcphp-in-nginx

location = /xmlrpc.php {
    deny all;
    access_log off;
    log_not_found off;
    return 403;
}

Thanks
Maison

**Comment by maisondasilva** [comment]
@jaapmarcus Is it possible to include this in the next version? I believe that many use WordPress and this removes one of the most attacked functions. It would be to clone the current one from WordPress and add this additional code!

Thanks Maison

**Comment by dfag86** [comment]
For apache
/etc/apache2/apache2.conf

add

`
<Files xmlrpc.php>
order deny,allow
deny from all
</Files>
`

**Comment by maisondasilva** [comment]
For Apache I usually use a .htaccess with the content

`<Files xmlrpc.php>
order deny,allow
deny from all
</Files>`

For Ngnix more simpler

location = /xmlrpc.php {
    deny all;
}


The advantage of the first code is that it will not generate logs of these accesses!

**Comment by dfag86** [comment]
you can globally upload the code for all domains on the server.

**Comment by maisondasilva** [comment]
> you can globally upload the code for all domains on the server.

Yes, that's a good suggestion too! As for Ngnix, there is no easy way like Apache, that's what I meant!

**Comment by arielesp** [comment]
Hello.
I suggest you create a custom template. Works well for me.

**Comment by Skamasle** [comment]
As @arielesp say the custom templates exists for this custom needs.

**Comment by Aartsie** [comment]
I share your concerns but I don't think this has to be a default config in Hestia.

When you install a quick app like wordpress you suppose to have a normal/default installation of Wordpress.
So it can be confusing when xmlrpc.php isn't working on a clean install.

I think it will be better to add is as a option.

**Comment by maisondasilva** [comment]
Yes, in my case I have already created a model, but I am referring it to other people who do not have as much knowledge and need to change files, which they can select via the web interface.
And this is one of the most attacked files

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4168/commits/6c7689b598f0d6aca1fc50a09f31be7743b71ff0

Merged...

**Comment by maisondasilva** [comment]
Thanks @jaapmarcus
