### ISSUE TITLE
[Feature] PHP 8.3 Support

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#4173]
### Describe the feature or change in detail

Sorry to jump on this already, when are we releasing PHP 8.3 support?

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
When PHP8.3 packages are released ....

**Comment by jaapmarcus** [comment]
Ohh that was yesterday ...

Will make a PR + release a version later today

**Comment by jaapmarcus** [comment]
https://packages.sury.org/php/pool/main/p/php8.3/

It looks like  not finished yet ...

**Comment by vikasprogrammer** [comment]
Thank you, I will await this PR :-)

**Comment by jaapmarcus** [comment]
root@test:/etc/php/8.2/cli# apt list php8.3
Listing... Done
php8.3/bookworm 8.3.0-1+0~20231125.13+debian12~1.gbp341c3d all


:heart:
