### ISSUE TITLE
Reverse proxy HestiaCP

### ISSUE THREAD

**Issue by vnthienvan** [hestiacp/hestiacp#4174]
### Describe the feature or change in detail

Hello, I have a suggestion to send to the Hestia CP development team.
Add Reverse proxy feature, for other LAN IP ports to connect to external domains.
Sincerely thank !

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by Skamasle** [comment]
Hi

 You can do it by create new nginx tempate and use it as reverse proxy

**Comment by jaapmarcus** [comment]
There is already a Issue for the same thing..

**Comment by vnthienvan** [comment]
Thank you so much HestiaCP team!

Vào Th 7, 25 thg 11, 2023 vào lúc 17:27 Jaap Marcus <
***@***.***> đã viết:

**Comment by vnthienvan** [comment]
> tempate nginx
Do you have any manuals? Please help me
