### ISSUE TITLE
php not working after fresh install

### ISSUE THREAD

**Issue by funsurfer2008** [hestiacp/hestiacp#4179]
### Describe the bug

After installing hestiacp an a fresh debian 11.8 and adding a User and a domain webserver delivers default index.html, but if i copy any php file over or create a info.php and wnat to open it, i get file not found. in log it says [proxy_fcgi:error] AH01071 : Got error 'Pimary script unknown'

### Tell us how to replicate the bug

After installing hestiacp an a fresh debian 11.8 and adding a User and a domain webserver delivers default index.html, but if i copy any php file over or create a info.php and wnat to open it, i get file not found. in log it says [proxy_fcgi:error] AH01071 : Got error 'Pimary script unknown'

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.10

### Operating system

Debian 11.8

**Comment by jaapmarcus** [comment]
Did you use the correct folder? 

Also for support please use our forum...
https://forum.hestiacp.com

**Comment by funsurfer2008** [comment]
WTF! You can not close it. I have 3 hestiaCP Servers and a new one is not working.

it is the right folder, and i wrote the log Lines. I have installed it 3 times, and it is allways the same. So Open the bug again and try it yourself. Install debian, install hestia, add a user, add a Domain, Check in Browser for Index.html, out a Info.php in it and try to Open.

**Comment by funsurfer2008** [comment]
Now i have installed one without apache, and it is the same error here. on fresh install.

please reopen this BUG and test ist.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/4181

With extra info we are able to reproduce it ...
