### ISSUE TITLE
php not working if a user is only numbers

### ISSUE THREAD

**Issue by funsurfer2008** [hestiacp/hestiacp#4181]
### Describe the bug

After installing hestiacp an a fresh debian 11.8 and adding a User and a domain webserver delivers default index.html, but if i copy any php file over or create a info.php and wnat to open it, i get file not found. in log it says [proxy_fcgi:error] AH01071 : Got error 'Pimary script unknown'

### Tell us how to replicate the bug

1. setup debian 11.8
2. install hestia with script
3. add user 090006
4. add webdomain and check if index.html ist working
5. insert any php file (info.php for example)
6. get file not found
7. delete user
8. add user K090006
9. add webdomain and check if index.html ist working
10. insert any php file (info.php for example)
11. php is working

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.10

### Operating system

Debian 11.8

**Comment by jaapmarcus** [comment]
It seems not even able to create the required folder in:
/home/user/web/domain.com/

root@dev v-add-user 1234 test "me@xxxxx.nu"
root@dev v-add-web-domain 1234 test.xxxx.nu
Error: directory /home/1234/web/test.xxxx.nu/public_html was not created
Error: directory /home/1234/web/test.xxxx.nu/document_errors was not created
Error: directory /home/1234/web/test.xxxx.nu/cgi-bin was not created
Error: directory /home/1234/web/test.xxxx.nu/private was not created
Error: directory /home/1234/web/test.xxxx.nu/stats was not created
Error: directory /home/1234/web/test.xxxx.nu/logs was not created
ln: target '/home/1234/web/test.xxxx.nu/logs/': No such file or directory
chmod: cannot access '/home/1234/web/test.xxxx.nu/*': Permission denied
chmod: cannot access '/home/1234/web/test.xxxx.nu/stats': Permission denied
chmod: cannot access '/home/1234/web/test.xxxx.nu/logs': Permission denied
chmod: cannot access '/home/1234/web/test.xxxx.nu/public_*html/*': Permission denied
chmod: cannot access '/home/1234/web/test.xxxx.nu': Permission denied
chown: cannot access '/home/1234/web/test.xxxx.nu/public_*html': No such file or directory
root@dev v-add-user A1234
Usage: v-add-user USER PASSWORD EMAIL [PACKAGE] [NAME] 
root@dev: v-add-user A1234 test "me@xxxxx.nu"
root@dev: v-add-web-domain A1234 web.xxxx.nu
root@dev: cd /home/1234/
root@dev:/home/1234# ls

**Comment by Aartsie** [comment]
In linux its (mostly) not allowed to create a username with only or beginning with digits.
Because it can break commands like `chmod`.

This limitation have nothing to do with Hestiacp specific.

**Comment by jaapmarcus** [comment]
We need to add a check to prevent it ...

**Comment by Aartsie** [comment]
> We need to add a check to prevent it ...

I will pick this up and give it a try.

**Comment by jaapmarcus** [comment]
This is the check:

https://github.com/hestiacp/hestiacp/blob/9d95464119fd8756e5bccd442e93220d6f92cdd4/func/main.sh#L707-L728

**Comment by Aartsie** [comment]
Thank you!, I found it but I need to figure out what it does exactly.
I'm not that experienced with bash yet :-)

**Comment by Aartsie** [comment]
Here is the PR: #4195 

I think this will fix the issue.

**Comment by AysadKozanoglu** [comment]
solution idea: i think to prevent against only digits for customer name, it would be better if hestiacp implement global Prefix to use globaly in hestia.  and if a new user is added, prefix will be added automaticly.


```
<prefix>-<username>
<prefix>-<username>-<database>
```

**Comment by jaapmarcus** [comment]
> solution idea: i think to prevent against only digits for customer name, it would be better if hestiacp implement global Prefix to use globaly in hestia. and if a new user is added, prefix will be added automaticly.
> 
> ```
> <prefix>-<username>
> <prefix>-<username>-<database>
> ```

No need for it and would require a full rewrite PR @Aartsie  made is fine however some other functions use the same check where digit  can be used with out issues (For example local part email)

**Comment by jaapmarcus** [comment]
Fixed by preventing users to create a user consisting out of a number.
