### ISSUE TITLE
[Bug] Unable to access web iterface after updating to 1.8.10

### ISSUE THREAD

**Issue by H4kt** [hestiacp/hestiacp#4185]
### Describe the bug

After updating to `1.8.10` I am no longer able to access web interface.
![image](https://github.com/hestiacp/hestiacp/assets/50774419/c998f4ad-0e71-46d6-955f-d64d8916b793)

### Tell us how to replicate the bug

1. Update HestiaCP to version 1.8.10
2. Try accessing the web interface

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.10

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
- Hestia service still running 
- Check error logs

It looks like you run behind a proxy. Any other error messages? 
http://www.squid-cache.org

Try to access Hestia directly by disabling Squid cache and see if ti works. 

Also from what version did you upgrade?

**Comment by H4kt** [comment]
> Try to access Hestia directly by disabling Squid cache and see if ti works.

The thing is that I did not install squid-cache myself

> Also from what version did you upgrade?

I cannot really remember

**Comment by jaapmarcus** [comment]
> > Try to access Hestia directly by disabling Squid cache and see if ti works.
> 
> The thing is that I did not install squid-cache myself

We don't install it either 

Unless you are using a NAT VPS contact your provider ... Or your internat provider.  

We have made some to hestia-nginx services but it was a while ago when we implemented the RTT feature.  It might cause it but then the main websites should also have issues... 


> 
> > Also from what version did you upgrade?
> 
> I cannot really remember
There is an email send when a update happens or change shell output

Are any log files created on your server?

**Comment by H4kt** [comment]
> > > Try to access Hestia directly by disabling Squid cache and see if ti works.
> > 
> > 
> > The thing is that I did not install squid-cache myself
> 
> We don't install it either
> 
> Unless you are using a NAT VPS contact your provider ... Or your internat provider.
> 
> We have made some to hestia-nginx services but it was a while ago when we implemented the RTT feature. It might cause it but then the main websites should also have issues...
> 
> > > Also from what version did you upgrade?
> > 
> > 
> > I cannot really remember
> > There is an email send when a update happens or change shell output
> 
> Are any log files created on your server?

Ok, I tested it on another server from the same VPS provider and the issue is there too.
Looks like I'm going to have a great chat with their support.
Sorry for bothering with this nonsense.
