### ISSUE TITLE
Feature Request: Fail2Ban with AbuseIPdb

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#420]
In a similar mindset of this [Feature Request](https://github.com/hestiacp/hestiacp/issues/330);
It might worth to integrate [AbuseIPdb to Fail2Ban](https://www.abuseipdb.com/fail2ban.html).

**Comment by ScIT-Raphael** [comment]
Thanks @jodumont for the feature request, we've discussed this internaly and have declined to implement a reporting to abuseipdb as default. It should be the user's decission to implement a automatically report and it is in some way not the part for hestia to provide this out of the box.
