### ISSUE TITLE
UI Improve : Put Username before First/Last Name

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#421]
I was just thinking the new way of showing User's First/Last name is a bit confusing as many of us are used to see the "username" first and try to relate  it that way. It is just a visual thing but I think it will bother some people, especially considering the fact that Hestia is mostly adopted by those moving out from VestaCP.

I have made a mockup showing the Username in a different Accented color (used on top bar) to make it stand out and noticeable.

![image](https://user-images.githubusercontent.com/2650395/60294188-7024e900-993e-11e9-8546-57b4f4f3b101.png)

**Comment by ioannidesalex** [comment]
I agree with username being first, before the Name & Surname.

**Comment by ghost** [comment]
Hey @mehargags, we'll make this change in styling for v1.0.2.

**Comment by ScIT-Raphael** [comment]
Changed with the following commit: https://github.com/hestiacp/hestiacp/commit/7db52b0a6b429ec8301b76d8df4b1ffcc1538ea3
