### ISSUE TITLE
[Feature] Adding frankenphp as a webserver.

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#4210]
### Describe the feature or change in detail

What is [FrankenPHP : The Modern PHP App Server, written in Go](https://frankenphp.dev/)

It includes native support for Symphony, Laravel, WordPress, and more:

Production-grade PHP server, powered by Caddy
Easy deploy - package your PHP apps as a standalone, self-executable binary
Run only one service - no more separate PHP-FPM and Nginx processes
Extensible - compatible with [PHP 8.2](https://laravel-news.com/php-8-2-0)+, most PHP extensions, and all Caddy modules
Worker mode - boot your application once and keep it in memory
Real-time events sent to the browser as a JavaScript event
Zstandard and Gzip compression
Structured logging
Monitor Caddy with built-in [Prometheus metrics](https://caddyserver.com/docs/metrics)
Native support for HTTPS, HTTP/2 and HTTP/3
Automatic HTTPS certificates and renewals
Graceful release - deploy your apps with zero downtime
Support for [Early Hints](https://blog.cloudflare.com/early-hints/)

https://blog.laravel.com/octane-frankenphp

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
No planned...
