### ISSUE TITLE
[Bug] Error: ssl certificate key pair is not valid

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#4214]
### Describe the bug

Trying generate SSL cert to domain, manual or letsencrypt receiving error
Error: ssl certificate key pair is not valid

server running apache + nginx ... old install ... updated to 1.8.11

I tried run in terminal, and I received the same error

### Tell us how to replicate the bug

create a domain
edit domain
add ssl cert manual or letsencrypt

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface, Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2), Let's Encrypt SSL

### Hestia Control Panel Version

1.8.11

### Operating system

debian 11

### Log capture

```shell
2023/12/25 18:24:42 [error] 2240162#0: *27 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "v_nginx_cache_duration" in /usr/local/hestia/web/edit/web/index.php on line 352" while reading response header from upstream
```

**Comment by jaapmarcus** [comment]
This error output it not relevant ... 

Please try to run this code:

https://github.com/hestiacp/hestiacp/blob/2b0b9d61934530ef8d2d79b0380680af35a36ee6/func/domain.sh#L456-L462

**Comment by jaapmarcus** [comment]
So what was the issue?

**Comment by arielesp** [comment]
I just rebooted the machine and just worked again .. very strange ...
