### ISSUE TITLE
Keep path in domain settings when using a parent directory 

### ISSUE THREAD

**Issue by stilldg** [hestiacp/hestiacp#4216]
### Describe the bug

Whenever a domain’s document root is set to a parent directory (../), it respects this change, however in the domain settings page it doesn’t show this when you return, the form appears blank.

I believe this should be shown here, as for certain use cases such as mirror domains you may wish to have a shared document root for multiple domains.

### Tell us how to replicate the bug

1. Add a domain
2. Set a document root that is a parent directory (example: ../private/)
3. Save and check the document root input box

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.10

### Operating system

Debian 12

**Comment by jaapmarcus** [comment]
../private is not valid for custom docroot ...

**Comment by stilldg** [comment]
../private was an example, I am asking about anything above public_html the folder, as it will work if it is inputted as the document root, it just won't show as such on the UI

**Comment by jaapmarcus** [comment]
Anything above "Public" Html should not be available

If you want to share 2 domain the same "website"
<img width="751" alt="Screenshot 2023-12-30 at 11 50 57" src="https://github.com/hestiacp/hestiacp/assets/9754650/6ab16015-5b37-4b56-b57f-42757f5c8309">

And select a different domain in the select box.. That belongs to this users...

We don't support to upload 1 "folder"  and share it over all users. For security reasons...
