### ISSUE TITLE
[Bug]    http://ip/phpmyadmin ? Page Not Found  Oops! We couldn't find the page that you're looking for.

### ISSUE THREAD

**Issue by nattapong2022** [hestiacp/hestiacp#4218]
### Describe the bug

 http://ip/phpmyadmin ? Page Not Found  Oops! We couldn't find the page that you're looking for.  Please check the address and try again. Error Code: 404

### Tell us how to replicate the bug

 http://ip/phpmyadmin ? Page Not Found  Oops! We couldn't find the page that you're looking for.  Please check the address and try again. Error Code: 404

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.8.11 

### Operating system

Ubuntu 22.04 (x86_64) 

### Log capture

```shell
http://ip/phpmyadmin ? Page Not Found  Oops! We couldn't find the page that you're looking for.  Please check the address and try again. Error Code: 404
```

**Comment by nattapong2022** [comment]
![Uploading Screenshot 2023-12-31 114347.png…]()

**Comment by adion-gorani** [comment]
Why I can’t use http://ip/phpmyadmin/
For security reasons, we have decided to disable this option. Please use https://host.domain.tld/phpmyadmin/ instead.

Reference:
https://hestiacp.com/docs/server-administration/databases.html

**Comment by nattapong2022** [comment]
phpMyAdmin - Error

Existing configuration file (/etc/phpmyadmin/config.inc.php) is not
readable.

ในวันที่ อา. 31 ธ.ค. 2023 เวลา 18:23 Jaap Marcus ***@***.***>
เขียนว่า:
