### ISSUE TITLE
[Bug] Dovecot failed to restart after daily cron

### ISSUE THREAD

**Issue by jorgegaspar** [hestiacp/hestiacp#4220]
### Describe the bug

Everyday I get an e-mail saying that dovecot failed to restart, only happens on my 2 ARM servers with Ubuntu. On the servers that are x64 I have no issues.

My kernel version: 
`Linux _hostname_ 5.15.0-1045-oracle #51-Ubuntu SMP Fri Sep 22 10:56:53 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

```
root@arm:~# v-list-sys-info
HOSTNAME     OS      VER    ARCH     HESTIA  RELEASE  UPTIME  LA
--------     --      ---    ----     ------  -------  ------  --
arm.tega.gg  Ubuntu  22.04  aarch64  1.8.11  release  123259  0.00

```

### Tell us how to replicate the bug

Default installation with exim and dovecot on a arm64 server

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 22.04 aarch64

### Log capture

```shell
Error: ERROR: Restart of dovecot failed.
Jan 02 06:02:01 z.tega.gg systemd[1]: Reload failed for Dovecot IMAP/POP3 email server.
Jan 02 06:02:01 z.tega.gg systemd[1]: dovecot.service: Control process exited, code=exited, status=226/NAMESPACE
Jan 02 06:02:01 z.tega.gg systemd[1024325]: dovecot.service: Failed at step NAMESPACE spawning /usr/bin/doveadm: No such file or directory
Jan 02 06:02:01 z.tega.gg systemd[1024325]: dovecot.service: Failed to set up mount namespacing: /run/systemd/unit-root/tmp: No such file or directory
Jan 02 06:02:01 z.tega.gg systemd[1024325]: Failed to mount /tmp/systemd-private-f70379936ad642078ba164d1c69bd3ea-dovecot.service-c7Yn81/tmp to /run/systemd/unit-root/tmp: No such file or directory
Jan 02 06:02:01 z.tega.gg systemd[1024325]: Failed to create destination mount point node '/run/systemd/unit-root/tmp': No such file or directory
Jan 02 06:02:01 z.tega.gg systemd[1]: Reloading Dovecot IMAP/POP3 email server...
```

**Comment by jaapmarcus** [comment]
https://support.plesk.com/hc/en-us/articles/12377478163607-Unable-to-start-Dovecot-Failed-at-step-NAMESPACE-spawning-usr-sbin-dovecot-Permission-denied

**Comment by jorgegaspar** [comment]
> https://support.plesk.com/hc/en-us/articles/12377478163607-Unable-to-start-Dovecot-Failed-at-step-NAMESPACE-spawning-usr-sbin-dovecot-Permission-denied

I did that in the past, but every time hestiacp updates it reverts that to true, I think that need to be changed on the install script to work as a permanent fix.

**Comment by jaapmarcus** [comment]
We do never touch /lib/systemd/system/dovecot.service during the upgrade script. 

Only reason why it could happen when you run apt update && apt upgrade  and everytime Ubuntu sees changed config files press yes instead of the default no...
