### ISSUE TITLE
 [Bug] Import Cpanel fails: Restore main domain: xxxx PHP version PHP-_ is not installed on HestiaCP. Please install it before trying to set it for a domain.

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#4230]
### Describe the bug

Unable to restore cpanel backups due to the above error

### Tell us how to replicate the bug

Create backup and import it

 v-import-cpanel backup-1.10.2024_12-58-58_client.tar.gz 

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.8.10

### Operating system

N/A

### Log capture

```shell
root@web01:/backup# v-import-cpanel backup-1.10.2024_12-58-58_sxtvztrk.tar.gz 
Checking provided file...
OK - Gziped File
Extracting backup...
Backup extracted without errors...
Get prefix...
Access tmp directory /backup/tmp.uhu5nz7IoW/backup-1.10.2024_12-58-58_sxtvztrk
Get User: client
Start with Databases
 Create and restore client_database 
Rebuild databases files for client
Converting addons domains, subdomains and some other fun
Start restoring domains
client.nl
Restore main domain: client.nl
PHP version PHP-_ is not installed on HestiaCP.
```

**Comment by jaapmarcus** [comment]
Also the owner of public_html is user:user instead of user:www-data

**Comment by Skamasle** [comment]
This comes from https://github.com/hestiacp/hestiacp/commit/4a42c06f8565b48dc494a8e664966108c4bce0af

I recomend just show a warning to user than " cant set same PHP version to DOMAIN.TLD, set default, may cause errors 500"

**Comment by Skamasle** [comment]
Try this https://github.com/hestiacp/hestiacp/pull/4241

**Comment by jaapmarcus** [comment]
Thanks have merged it with a few smal changes
