### ISSUE TITLE
[Bug] Email Forwarding not working.

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#4232]
### Describe the bug

when we enter the Gmail -  Email address for forwarding 
<img width="345" alt="image" src="https://github.com/hestiacp/hestiacp/assets/39749258/19cee70a-0e82-471a-bcf8-88509f9361b5">

and we get the mails on the webmail 
<img width="522" alt="image" src="https://github.com/hestiacp/hestiacp/assets/39749258/d97df95f-bfc9-4def-8e3e-15b3c0cd6547">

but it doesn't forward to Gmail.

<img width="523" alt="Pasted Graphic" src="https://github.com/hestiacp/hestiacp/assets/39749258/da67fe49-fe12-4bfb-a41b-bf0c551d2434">

### Tell us how to replicate the bug

1st. go to Edit Mail Account
2nd Enter Gmail Adress in "Forward to"
3rd  Send the test mail to webmail email.

### Which components are affected by this bug?

Control Panel Backend, Mail (Exim, Dovecot), Webmail (Roundcube, SnappyMail)

### Hestia Control Panel Version

v1.8.11

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Check /var/log/exim4/mainlog

**Comment by alber-khan** [comment]
2024-01-11 00:05:03 1rLpR7-003AAn-9d == test@gmail.com <test@test.com> R=dnslookup T=remote_forwarded_smtp defer (-1): Failed to expand return path "${srs_encode {${readfile{/etc/exim4/srs.conf}}} {$return_path} {$original_domain}}": "${srs_encode" is not a known operator (or a } is missing in a variable reference)

**Comment by alber-khan** [comment]
https://forum.hestiacp.com/t/email-forwarding-problems/10070

looks like someone already mentioned it here.

**Comment by alber-khan** [comment]
<img width="179" alt="image" src="https://github.com/hestiacp/hestiacp/assets/39749258/68ad620c-4370-4acf-9d5d-36c83e011377">


changing the config file fixed the issue.
