### ISSUE TITLE
PHPfpm templates missing

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#424]
I know my issue is similar if not identical of [this one](https://github.com/hestiacp/hestiacp/issues/215) and to follow with [this issue](https://github.com/hestiacp/hestiacp/issues/413)
I realize after @ScIT-Raphael comment; I simply don't have any phpfpm templates which I could find ([here](https://github.com/hestiacp/hestiacp/tree/master/install/deb/templates/web/nginx/php-fpm)); for a reason or another I just have [those nginx preset](https://github.com/hestiacp/hestiacp/tree/master/install/deb/templates/web/nginx)

My installation is a Debian 9 running in a unprivileged LXContainer
I install Hestia without apache but with multi-php `-a no -m yes`

**Comment by ScIT-Raphael** [comment]
We will need to put some work in the multiphp setup without apache2, in some way, this is a known issue :). We would like to have a switch in the backend, that just changes the php-fpm socket for each version so you could work with the existing phpfpm templates. Atm you've to create here your own templates, just copy the files php-xx.sh/tpl/stpl and add whatever you need.

**Comment by JOduMonT** [comment]
@ScIT-Raphael I copy files I need from php-xx.sh/tpl.stpl to ... ?
#### what is the destination ?

**Comment by ScIT-Raphael** [comment]
@jodumont based on your configuration, if apache2+nginx+multiphp /usr/local/hestia/data/templates/web/apache2, if nginx+multiphp in the same folder location but nginx instead apache2.

**Comment by JOduMonT** [comment]
@ScIT-Raphael I'm sorry I couldn't find the PHP-FPM template
I thought they would be in `/usr/local/hestia/data/templates/web/php-fpm` OR `/usr/local/hestia/data/templates/web/nginx/php-fpm`

but nothing there
> /usr/local/hestia/data/templates/web/nginx# ls -lah
> total 86K
> drwxr-xr-x  2 root root   20 Jul  3 04:17 .
> drwxr-xr-x 10 root root   10 Jul  3 02:43 ..
> -rwxr-xr-x  1 root root 1.8K Jul  3 02:43 PHP-56.sh
> -rw-r--r--  1 root root 1.6K Jul  3 02:43 PHP-56.stpl
> -rw-r--r--  1 root root 1.5K Jul  3 02:43 PHP-56.tpl
> -rwxr-xr-x  1 root root 1.8K Jul  3 02:43 PHP-70.sh
> -rw-r--r--  1 root root 1.6K Jul  3 02:43 PHP-70.stpl
> -rw-r--r--  1 root root 1.5K Jul  3 02:43 PHP-70.tpl
> -rwxr-xr-x  1 root root 1.8K Jul  3 02:43 PHP-71.sh
> -rw-r--r--  1 root root 1.6K Jul  3 02:43 PHP-71.stpl
> -rw-r--r--  1 root root 1.5K Jul  3 02:43 PHP-71.tpl
> -rwxr-xr-x  1 root root 1.8K Jul  3 02:43 PHP-72.sh
> -rw-r--r--  1 root root 1.6K Jul  3 02:43 PHP-72.stpl
> -rw-r--r--  1 root root 1.5K Jul  3 02:43 PHP-72.tpl
> -rwxr-xr-x  1 root root 1.8K Jul  3 02:43 PHP-73.sh
> -rw-r--r--  1 root root 1.6K Jul  3 02:43 PHP-73.stpl
> -rw-r--r--  1 root root 1.5K Jul  3 02:43 PHP-73.tpl
> lrwxrwxrwx  1 root root   52 Jul  3 02:43 default.sh -> /usr/local/hestia/data/templates/web/nginx/PHP-73.sh
> lrwxrwxrwx  1 root root   54 Jul  3 02:43 default.stpl -> /usr/local/hestia/data/templates/web/nginx/PHP-73.stpl
> lrwxrwxrwx  1 root root   53 Jul  3 02:43 default.tpl -> /usr/local/hestia/data/templates/web/nginx/PHP-73.tpl
>
