### ISSUE TITLE
[Bug] PHPMyAdmin Single Sing On not working on a brand new Ubuntu 20.04

### ISSUE THREAD

**Issue by n3b0r** [hestiacp/hestiacp#4248]
### Describe the bug

Hi everybody,

First let us say that Hestia is awesome, thanks for this outstanding product!

## Issue

We've recently started to test Hestia (v1.8.11) as a replacement for some Plesk panels and we came across the PHPMyAdmin SSO feature, which is awesome and a pretty important feature, but after following the installation guide and the troubleshooting guide + searching on GitHub and this community, we are not able to get this feature to work as expected.

## Environment

We are doing the tests in a brand new Ubuntu 20.04 running on top of LXC within Proxmox. The Hestia container has a public IP, and it's accessible from the Internet.

The command we used to install Hestia is as follows:

```
# Get HestiaCP installer

wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

# Install HestiaCP

bash hst-install.sh --password password --lang es --hostname server.hostname.com --email admin@email.com --multiphp yes --vsftpd no --proftpd yes --named no --quota yes --interactive no --force
```

After the installation is completed, we turn on SSO in Settings > Databases > PHPMyAdmin SSO and the IP address `0.0.0.0` (full permissions for testing purposes) is added as allowed IP into Settings > Security > System > Allowed IPs for API (we also tried using the CLI command `v-add-sys-pma-sso`)

### SSO config

![image1](https://github.com/hestiacp/hestiacp/assets/7352160/9457696d-1788-478a-8143-599d2ca94c89)

### API config

![image2](https://github.com/hestiacp/hestiacp/assets/7352160/c3c9fefb-2c38-43cc-b71a-6d4f988cc4e6)

### Testing

After those configs are set, we create a new user, impersonate him and create a new DB. Once it's done, we click on the PHPMyAdmin SSO icon (arrow icon) and we get this error:

![image3](https://github.com/hestiacp/hestiacp/assets/7352160/aec94967-f236-4f71-8ebe-e389cdab485e)

![image4](https://github.com/hestiacp/hestiacp/assets/7352160/088988e9-37c0-475a-b7af-ddbbe1835901)

This error is due to the wrong file group. After a fresh install it's set up to `hestiamail` but it should be `www-data`:

![image5](https://github.com/hestiacp/hestiacp/assets/7352160/e514706d-9403-4db4-92b0-9e19f69ab39a)

After changing the file group to `www-data`, the error is gone, but the PHPMyAdmin SSO still doesn't work, always showing the PHPMyAdmin login:

![image6](https://github.com/hestiacp/hestiacp/assets/7352160/e3280f05-78c2-477e-8672-c01e46bcaeb8)

Neither `/var/log/apache2/domains/server.hostname.com.error.log` nor `/var/log/hestia/*` shows anything interesting. 

```
==> /var/log/hestia/auth.log <==
2024-01-18 15:16:58 Jl6G2KlHg9DOKvR9RgHR X.X.X.X (redacted) v-add-database-temp-user successfully launched

==> /var/log/hestia/system.log <==
2024-01-18 15:16:58 v-add-database-temp-user  'demo' 'demo_db' 'mysql' 'localhost'

==> /var/log/hestia/nginx-access.log <==
X.X.X.X (redacted) - - [18/Jan/2024:15:16:58 +0000] POST /api/ HTTP/2.0 "200" 110 "-" "-" "-"
```

#### Manual temp SSO user creation

We have also tested the CLI command `v-add-database-temp-user` for creating SSO users manually and it works, but it throws an error:

![image7](https://github.com/hestiacp/hestiacp/assets/7352160/d5bd1c0e-37f3-4dca-88e3-8ccbd1405ae2)

Using these creds, we can log in to the database manually, but the SSO button still doesn't work. 

Can someone bring some light on what's going on here and how we can address this issue? 

If we forget any piece of docs to address the issue, please let us know and we'll add it to this thread.

Thank you in advance!

### Tell us how to replicate the bug

Follow above steps ^^

### Which components are affected by this bug?

Control Panel Backend, Control Panel Installation or Upgrade, Control Panel Web Interface, Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 20.04

**Comment by jaapmarcus** [comment]
Add X.X.X.X   to the ip white list and it should work

**Comment by jaapmarcus** [comment]
But the user is success fully created I wonder why:

https://github.com/hestiacp/hestiacp/blob/3dfaaf60c23894cb5580626cd632e4730644070e/bin/v-add-database-temp-user#L71

is causing the error it doesn't nothing more create an at  job...

`/usr/local/hestia/bin/v-add-database-temp-user: line 71: echo: write error: Broken pipe`

I use it on a daily basis last few days both on Debian and Ubuntu and never had issues with it ...

**Comment by jaapmarcus** [comment]
Check /var/log/nginx/domain/domain.error.log (Subdomain for PHPmyadmin)

replace domain with your domain

**Comment by n3b0r** [comment]
Thanks for your fast replay @jaapmarcus. 

We have also tested adding the server IP address X.X.X.X to the white list; in fact, we did a ton of tests on that. 

If the IP is not added to the white list, we get a `Unable to connect over API, please check API connection` error. Once we add either 0.0.0.0 or X.X.X.X server IP, that error is gone and nothing appears on `/var/log/apache2/domains/server.hostname.com.error.log` (being server.hostname.com the full FQDN of the server which is accessible from the Internet)

Here is an screenrecording:

https://github.com/hestiacp/hestiacp/assets/7352160/91925dcc-1f06-4aed-8560-e4d7af2f9146

We came here after testing all the solutions available here and on the forums.

**Comment by n3b0r** [comment]
BTW, no logs on Nginx for domains are available. Those only lives under Apache folder: 

<img width="309" alt="image" src="https://github.com/hestiacp/hestiacp/assets/7352160/8b456a4c-ea44-46c7-99f9-95c9de76fc50">

**Comment by Skamasle** [comment]
Please show us detailed config

Check if have some selinux enabled

Check if you have at installed, the broken pipe error is strange, in my case by default hestia not install at tool in debian, so may be lxc container problem

If you have phpmyadmin under subdomain in another hestia you need check logs in /home/user/domain/logs

If you have custom setup enable log in configuration.

**Comment by n3b0r** [comment]
Sure, @Skamasle, which config files do you need? I'm happy to share them.

Just to recap, no customizations or extra steps were done; just install the panel with the above command. In the first post, I've shared everything.

PMA is in the default admin domain, the same way it's installed by default.

Regarding SELinux, it's not installed.

**Comment by jaapmarcus** [comment]
Ather the line:

 ```
 $post_request = [
                        "hash" => $this->key,
                        "returncode" => "no",
                        "cmd" => "v-add-database-temp-user",
                        "arg1" => $user,
                        "arg2" => $database,
                        "arg3" => "mysql",
                        "arg4" => $host,
                ];
                $request = $this->request($post_request);
```

```
var_dump($request); 
die();
```
in /usr/share/phpmyadmin/hestia-sso.php

And then open phpmyadmin via SSO via the panel.

It should disable the return data from the api

**Comment by n3b0r** [comment]
Here you go @jaapmarcus 

![Captura de Pantalla 2024-01-19 a las 10 59 17](https://github.com/hestiacp/hestiacp/assets/7352160/9fe9ddf7-5ba5-48bf-803f-841d278b2336)


```==> /var/log/hestia/auth.log <==
2024-01-19 09:56:33 Jl6G2KlHg9DOKvR9RgHR X.X.X.X (redacted) v-add-database-temp-user successfully launched

==> /var/log/hestia/system.log <==
2024-01-19 09:56:33 v-add-database-temp-user  'demo' 'demo_db' 'mysql' 'localhost'

==> /var/log/hestia/nginx-access.log <==
X.X.X.X (redacted) - - [19/Jan/2024:09:56:33 +0000] POST /api/ HTTP/2.0 "200" 110 "-" "-" "-"```

**Comment by jaapmarcus** [comment]
So it creates the data correct so that part works

So the error is somewhere:
https://github.com/hestiacp/hestiacp/blob/3dfaaf60c23894cb5580626cd632e4730644070e/install/deb/phpmyadmin/hestia-sso.php#L183-L198

**Comment by jaapmarcus** [comment]
Or in then session creation

**Comment by n3b0r** [comment]
Do you want another dump somewhere else?

**Comment by n3b0r** [comment]
@jaapmarcus any suggestions to further investigate this?

**Comment by n3b0r** [comment]
Well, after investing a bunch of hours, I've found the issue and can confirm this is a bug in the code. 

Within the file `/etc/phpmyadmin/config.inc.php` there is a `foreach` that should include the PHPMyAdmin config needed to set up the Singon cookie config, this is the code:

```
foreach (glob("/etc/phpmyadmin/conf.d/*.php") as $filename) {
        include $filename;
        /*Don't remove / alter code here below this will add SSO support for all servers*/
        //Add Hestia SSO code here
     include ('/etc/phpmyadmin/hestia-sso.inc.php');
        $i++;
}
```

I've found that the loop condition doesn't match ever since `glob("/etc/phpmyadmin/conf.d/*.php")` return an empty array but it should return at least one element, since in the folder `/etc/phpmyadmin/conf.d/` a file called `01-localhost.php` exists. 

If I bypass the loop adding two manual includes:

```
include "/etc/phpmyadmin/conf.d/01-localhost.php";
include '/etc/phpmyadmin/hestia-sso.inc.php';
```

I'm able to log in using PHPMyAdmin SSO, so something is happening with the glob piece. 

My first thought was a permissions issue, but since the manual includes did the trick, I moved on, and something else is happening there. 

I hope this helps to address the issue.

Thanks!

**Comment by n3b0r** [comment]
I've detected the source of the issue, it's here: https://github.com/hestiacp/hestiacp/blob/5ed62186254d242e4f3fa86d0c613fce72e3f03f/install/hst-install-ubuntu.sh#L1868

This should be `chown -R root:www-data /etc/phpmyadmin/` since hestiamail user belongs to www-data group.
