### ISSUE TITLE
Feature Request: Minimum Password Length

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#425]
### In a few words, please describe the issue that you're experiencing:
Give the administrator the option to set/configure a minimum number of characters for all passwords involved in Hestia (users, email addresses, dbs, additional ftps, statistics etc) which can be changed/set through Hestia's configuration file.

### Operating system distribution and release:
All

### Which of the following web server configurations are you using?
All

### Additional notes:
This will assist with overall system security (brute force etc) and it can be defined globally as loose or hard the Administrator wants it to be.

**Comment by ScIT-Raphael** [comment]
Until now, we can't find enough time to develop and fullfill all feature request. I'll close this request for now,   if someone would like to do it on their own, just push a pull request - we will be happy for every contribution.
