### ISSUE TITLE
[Feature] Documetation error?

### ISSUE THREAD

**Issue by solbu** [hestiacp/hestiacp#4257]
### Describe the feature or change in detail

Just discovered this nice program yesterday, and I am in the process of reading the online documentation, when I found instructions that I consider incorrect.[1] :-)
In the _Server Administration_ section about backups and how to configure rclone it says that the easiest way to install rclone is to run a curl command which is this one:
```
sudo -v
curl https://rclone.org/install.sh | sudo bash
```

Surely the easiest way to _install_ rclone is to use `«sudo apt install rclone»` and not that script?
Using apt also ensures that rclone always works with the distro used to install it.

[1] https://hestiacp.com/docs/server-administration/backup-restore.html#how-to-setup-rclone

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
> ### Describe the feature or change in detail
> Just discovered this nice program yesterday, and I am in the process of reading the online documentation, when I found instructions that I consider incorrect.[1] :-) In the _Server Administration_ section about backups and how to configure rclone it says that the easiest way to install rclone is to run a curl command which is this one:
> 
> ```
> sudo -v
> curl https://rclone.org/install.sh | sudo bash
> ```
> 
> Surely the easiest way to _install_ rclone is to use `«sudo apt install rclone»` and not that script? Using apt also ensures that rclone always works with the distro used to install it.
> 
> [1] https://hestiacp.com/docs/server-administration/backup-restore.html#how-to-setup-rclone
> 
> ### Would you like to sponsor this feature to have it implemented?
> No

Installed from apt source is easier how ever it is usually a few versions behind. And last time I checked it didn't had support for certain  endpoints..  

For example:  Rclone Deb 11 apt: v1.53.3-1+b6
Via  Above method: v1.65.1

We should probally include rclone selfupdate on regular basis...

**Comment by solbu** [comment]
> We should probally include rclone selfupdate on regular basis...

Or have a dedicated deb repo which can be installed into the sources.list.d folder for packages you feel should always be the latest version. (Just thinking out loud)

Debian users often chose Debian because it is a _Stable_ distro where packages doesn't change to much – for better and for worse. :-)

But thank you for the reply.

**Comment by jaapmarcus** [comment]
> > We should probally include rclone selfupdate on regular basis...
> 
> Or have a dedicated deb repo which can be installed into the sources.list.d folder for packages you feel should always be the latest version. (Just thinking out loud)
> 
> Debian users often chose Debian because it is a _Stable_ distro where packages doesn't change to much – for better and for worse. :-)
> 
> But thank you for the reply.

Rclone doesn't provide a repo by them self...   And providing one by us  is currently not planned as it would require a lot of extra work for us ... 


We do it for PHPmyAdmin / Roundcube / Snappymail aswell and it provides a lot of advantages that it is more up to date other wise some users would be still using Larry as default theme for Roundcube...

We still us the official source for downloading the executable and not a shady 3rd party website...
