### ISSUE TITLE
[Bug] Error: Unable to connect to the Hestia APT repository

### ISSUE THREAD

**Issue by hasanivgen** [hestiacp/hestiacp#4258]
### Describe the bug

Welcome to the Hestia Control Panel installer!

Please wait, the installer is now checking for missing dependencies...

[ * ] Installing dependencies...
Error: Unable to connect to the Hestia APT repository

Hi HESTIACP,
I am getting the ABOVE error. can you help me. Thank you from now.

### Tell us how to replicate the bug

Welcome to the Hestia Control Panel installer!

Please wait, the installer is now checking for missing dependencies...

[ * ] Installing dependencies...
Error: Unable to connect to the Hestia APT repository

Hi HESTIACP,
I am getting the ABOVE error. can you help me. Thank you from now.

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.8.11

### Operating system

debian12

**Comment by jaapmarcus** [comment]
If you send today an email ip has been whitelisted...

If not send an email to info@hestiacp.com
