### ISSUE TITLE
[Feature] vsftpd use_localtime No

### ISSUE THREAD

**Issue by maisondasilva** [hestiacp/hestiacp#4261]
http://vsftpd.beasts.org/vsftpd_conf.html#:~:text=Default%3A%20NO-,use_localtime,-If%20enabled%2C%20vsftpd

use_localtime
If enabled, vsftpd will display directory listings with the time in your local time zone. The default is to display GMT. The times returned by the MDTM FTP command are also affected by this option.
Default: NO

Reference: https://forum.hestiacp.com/t/files-through-ftp-with-a-different-date-and-time-and-file-manager-change-for-24-hours/11951/8?u=maisondasilva

**Comment by johnnyq** [comment]
This explains why our time is off on our Nextcloud server when mounting an FTP share on HestiaCP. Nice find, seems like an easy fix, Are you able to submit a PR with those changes. The PR should include change on existing installs and new installs

**Comment by jaapmarcus** [comment]
I don't see it in our config ...

https://github.com/hestiacp/hestiacp/blob/main/install/deb/vsftpd/vsftpd.conf

**Comment by maisondasilva** [comment]
@jaapmarcus 

Here

https://github.com/hestiacp/hestiacp/blob/dcc7f5b5dcf63b88c9e881d853a90160ac9fd14d/install/deb/vsftpd/vsftpd.conf#L31

**Comment by johnnyq** [comment]
I think almost all ftp clients including Nextcloud FTP mount expect GMT 0 from an FTP Server then the FTP Client converts it to its local timezone.
So it may be a good idea just to remove line 31 on update and new installs which will enable the default which is no.

**Comment by maisondasilva** [comment]
In fact, just change the line to "NO" it doesn't need to be removed!

**Comment by maisondasilva** [comment]
@johnnyq Now it should "NO" be the default, let me know when you receive the new version if it solves it for you!
Thanks @jaapmarcus

**Comment by jaapmarcus** [comment]
Issue can be closed
