### ISSUE TITLE
[Feature] file manager doesn’t appear as 24hours!

### ISSUE THREAD

**Issue by maisondasilva** [hestiacp/hestiacp#4262]
@jaapmarcus I saw that you mentioned that
And I set upgrade_config_set_value ‘UPGRADE_UPDATE_FILEMANAGER_CONFIG’ ‘yes’ instead upgrade_config_set_value ‘UPGRADE_UPDATE_FILEMANAGER_CONFIG’ ‘true’

So it would not update …

in upgrade 1.8.11.sh config

Reference
https://forum.hestiacp.com/t/php-8-3-in-interface-web-and-file-manager/12072/5?u=maisondasilva

In the next version with the update it should be 24 hours?

**Comment by jaapmarcus** [comment]
<img width="1157" alt="Screenshot 2024-01-25 at 12 56 27" src="https://github.com/hestiacp/hestiacp/assets/9754650/3f5cb140-490c-4214-b341-f4b920826293">

It has been allready fixed

**Comment by maisondasilva** [comment]
In my case I had to manually add it to the file in the last version, as there was no line to correct this!

**Comment by jaapmarcus** [comment]
I is not on the release branch yet will b after we release a nw version
