### ISSUE TITLE
[Feature] NGINX to able support NODEJS SOKET.IO/WEBSOCKET Services

### ISSUE THREAD

**Issue by gunyakov** [hestiacp/hestiacp#4267]
### Describe the feature or change in detail

It will be very useful if you change the domain options page to allow the user to use nginx as a reverse proxy for the Nodejs sockets application. Just need to add a checkbox like "Run as reverse proxy", another checkbox "Support SOCKET APP", a text field where the user can enter the port of the local Nodejs application and some new NGING templates to support this configuration. For example, I have few NODEJS services, such as TG bots, custom Nodejs chat and so on, what these future need, but manually change Nginx template just to set the correct port is very unclear way for most users. My templates for nginx and nodejs also have only one difference - the hardcoded port of the local service.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by Pleskan** [comment]
> ### Describe the feature or change in detail
> 
> It will be very useful if you change the domain options page to allow the user to use nginx as a reverse proxy for the Nodejs sockets application. Just need to add a checkbox like "Run as reverse proxy", another checkbox "Support SOCKET APP", a text field where the user can enter the port of the local Nodejs application and some new NGING templates to support this configuration. For example, I have few NODEJS services, such as TG bots, custom Nodejs chat and so on, what these future need, but manually change Nginx template just to set the correct port is very unclear way for most users. My templates for nginx and nodejs also have only one difference - the hardcoded port of the local service.
> ### Would you like to sponsor this feature to have it implemented?
> 
> No

IMHO, you could just create a custom template for your web application, and you are good to go.
Refer to  [this](https://hestiacp.com/docs/server-administration/web-templates.html)  section of the official documentation. 
The way above is more modular and therefore better than direct integration into the codebase.
Templates is pretty good implementation for such functionality, because you have to know what you are doing with you server.

**Comment by jaapmarcus** [comment]
There are already similar issues for it requesting the same ...
