### ISSUE TITLE
Feature Request: Enforce www / no-www for web domains

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#427]
A user should be able to enforce www or no-www redirects which will greatly assist in SEO. The current structure of no-force costs an SEO penalty to the websites.

This cane be done through a radio button where user can select whether the user wants to force www or no-www or don't do any redirects (current structure).

**Comment by jaapmarcus** [comment]
Commands to be used

Redirect to no-www:
-------------------
return      301 $scheme://%domain_idn%$request_uri;


Redirect to www:
----------------
return      301 $scheme://www.%domain_idn%$request_uri;

**Comment by jaapmarcus** [comment]
Also extend the system to allow redirect to different domains...

**Comment by jlguerrerosanz** [comment]
That way we could buy a domain and 301 redirect it to another.

**Comment by jaapmarcus** [comment]
Feature has been merged  and will be released in 1.4
