### ISSUE TITLE
[Bug] Apply to selected

### ISSUE THREAD

**Issue by bojandenic** [hestiacp/hestiacp#4272]
### Describe the bug

It's not possible to delete all emails accounts when I select all emails and then in dropdown menu, select Delete.

### Tell us how to replicate the bug

1. Mail
2. Select all email account users
3. In dropdown menu, select "delete"

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 22.04 (x86_64)

**Comment by jaapmarcus** [comment]
Patched
