### ISSUE TITLE
[Feature] Add small nginx exception in Laravel Template for Livewire package

### ISSUE THREAD

**Issue by theChaosCoder** [hestiacp/hestiacp#4286]
### Describe the feature or change in detail

Hi, I just had this problem here: https://benjamincrozat.com/livewire-js-404-not-found
Livewire is a very popular package for Laravel. It exposes a laravel route /livewire/livewire.js

**The current nginx laravel template does not work with this package an returns always 404 for /livewire/livewire.js**

My proposal is to either add this line by default for Laravel or create a new template: Laravel+livewire.

I can make a PR for this, but since I'm not an "nginx expert" I wanted to ask if someone knows a better solution for this?

What do you think of this change?

Since v3 livewire has it's own subdomain https://livewire.laravel.com/ so it's not some random package.

```
location / {
                try_files $uri $uri/ /index.php?$args;

                location ~* ^.+\.(ogg|ogv|svg|svgz|swf|eot|otf|woff|woff2|mov|mp3|mp4|webm|flv|ttf|rss|atom|jpg|jpeg|gif|png|webp|ico|bmp|mid|midi|wav|rtf|css|js|jar)$ {
                        expires 30d;
                        fastcgi_hide_header "Set-Cookie";
                }

                ### THE FIX ###
                location = /livewire/livewire.js {
                    expires off;
                    try_files $uri $uri/ /index.php?$query_string;
                }

                location ~ [^/]\.php(/|$) {
                        try_files $uri =404;

                        include /etc/nginx/fastcgi_params;

                        fastcgi_index index.php;
                        fastcgi_param HTTP_EARLY_DATA $rfc_early_data if_not_empty;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

                        fastcgi_pass unix:/run/php/php8.1-fpm-lara.thechaoscoder.com.sock;

                        include /home/chaoscoder/conf/web/lara.thechaoscoder.com/nginx.fastcgi_cache.conf*;
                }
        }


```

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by Skamasle** [comment]
Solution is valid for me.

**Comment by theChaosCoder** [comment]
@jaapmarcus Thx for adding this. Ich will close it here then.

**Comment by jaapmarcus** [comment]
Did close it instead of merging it should be fixed right now ...

**Comment by farzadaqajani** [comment]
> Did close it instead of merging it should be fixed right now ...

it's merged. But it doesn't exist in the fresh install. I don't know about its status in the upgrade.
