### ISSUE TITLE
Packages.sury.org apt expired 

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#4294]
This only affects Debian systems! Ubuntu systems are not affected!

Currently the expiry is 16 februari 2024 

To fix the issue:

```
curl -sSlo /usr/share/keyrings/sury-keyring.gpg https://packages.sury.org/php/apt.gpg
curl -sSlo /usr/share/keyrings/apache2-keyring.gpg https://packages.sury.org/apache2/apt.gpg
```

To verify it works:

```
cd /usr/share/keyrings/
gpg --list-options show-sig-expire sury-keyring.gpg
```

It will show as:
```
pub   rsa3072 2019-03-18 [SC] [expires: 2026-02-04]
      15058500A0235D97F5D10063B188E2B695BD4743
uid           DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
sub   rsa3072 2019-03-18 [E] [expires: 2026-02-04]
```

**Comment by tlcd96** [comment]
This happened to an system that ran do-release-upgrade command. So Ubuntu server 16.04 up can trigger that error

**Comment by jaapmarcus** [comment]
> This happened to an system that ran do-release-upgrade command. So Ubuntu server 16.04 up can trigger that error

16.04 is no supported any more by Sury...

Not an issue with 16.04 of the packages it self ...
