### ISSUE TITLE
[Bug] SnappyMail install fails

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#4297]
### Describe the bug

```sh
> sudo /usr/local/hestia/bin/v-add-sys-snappymail
PHP Warning:  file_put_contents(/var/lib/snappymail/data/_data_/_default_/cache/CACHEDIR.TAG): Failed to open stream: No such file or directory in /var/lib/snappymail/snappymail/v/2.34.2/app/libraries/MailSo/Cache/Drivers/File.php on line 31
```

### Tell us how to replicate the bug

sudo /usr/local/hestia/bin/v-add-sys-snappymail

### Which components are affected by this bug?

Webmail (Roundcube, SnappyMail)

### Hestia Control Panel Version

 v1.8.11 

### Operating system

 Debian 11.9 (x86_64)

**Comment by xeruf** [comment]
Executing it a second time fixes it, apparently then the directory is already created somehow

**Comment by xeruf** [comment]
But trying to use it in the web throws this error: `[202] is_readable() failed`

**Comment by RaySinner** [comment]
This will solve your problem
`chown -R hestiamail:www-data /etc/snappymail/data`
