### ISSUE TITLE
[Bug] Hestial APT repository broken; as well the site

### ISSUE THREAD

**Issue by SKJoy** [hestiacp/hestiacp#4298]
### Describe the bug

```
Welcome to the Hestia Control Panel installer!

Please wait, the installer is now checking for missing dependencies...

[ * ] Installing dependencies...
Error: Unable to connect to the Hestia APT repository
```

### Tell us how to replicate the bug

- Just try to install HestiaCP
- Try to access the website

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 22 LTS

**Comment by jaapmarcus** [comment]
Please send a email to info@hestiacp.com your ip is blocked by Cloudflare and I will add your ip to the white list ...
