### ISSUE TITLE
Feature Request: File Manager

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#430]
A secure File Manager could be added.

**Comment by jmclaren7** [comment]
What's stopping the file manager from Vesta being brought over?

**Comment by ScIT-Raphael** [comment]
Multiple reasons, first of all it was a paid part of vesta, it wouldnt be fair to disable the license validation check and just take over the code, even when it is open source. Also vesta doesnt sell the filemanager license anymore, probaly there is something behind it.

The filegator filemanager has been implmenented into the master branch yesterday and will be released in v1.1.3.

**Comment by pcreadycl** [comment]
> 
> 
> Multiple reasons, first of all it was a paid part of vesta, it wouldnt be fair to disable the license validation check and just take over the code, even when it is open source. Also vesta doesnt sell the filemanager license anymore, probaly there is something behind it.
> 
> The filegator filemanager has been implmenented into the master branch yesterday and will be released in v1.1.3.

Hi, when you release 1.1.3 its ready, and how upgrade my actual 1.1.2 (master), thanks!

**Comment by ScIT-Raphael** [comment]
Master branch is for testing only, a upgrade to 1.1.3 is officially not supported - you could still try to run a v-update-sys-hestia-git, but issues may occure. The upgrade from 1.1.1 will be done over the apt repository.

The release will follow as soon as all is ready and deeply tested, currently there is no eta set.
