### ISSUE TITLE
Limit CPU and RAM for Each User Using cgroup

### ISSUE THREAD

**Issue by codebyoul** [hestiacp/hestiacp#4302]
### Describe the feature or change in detail

The proposed enhancement involves adding fields to the package modules, allowing administrators to customize CPU, RAM, and SWAP limits for each package in the package module. When a user is created within a specific package, the user's cgroup is updated during both user creation and package updates.

This feature has already been implemented and tested on the latest version of Ubuntu. However, it requires further advanced testing. Importantly, the core of HestiaCP remains unchanged; the modifications are confined to the package and user modules.

If you agree with these changes, I am prepared to submit a pull request to the repository.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Please go ahead and submit a PR

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4305
