### ISSUE TITLE
v1.8.11 API giving error . always returning [Error 3] while creating account

### ISSUE THREAD

**Issue by pks891618** [hestiacp/hestiacp#4311]
### Describe the bug

Trying to create new user account using API with access keys but its not working

NOTE:  Already added IP , already allowed admin to use access keys , and using the Access keys of admin

### Tell us how to replicate the bug

1. generate new access keys for admin
2. add IP of server that access those keys
3. write simple code to access ,

Its returning [Error3] . In auth.log its showing  v-add-user successfully launched but user is not added. Please check attached screenshot

In error.log its showing Error3. Please check last attached screenshot
![image](https://github.com/hestiacp/hestiacp/assets/46920172/dc7c2058-b5cc-4e7b-b244-dff84d39159a)

![image](https://github.com/hestiacp/hestiacp/assets/46920172/24583427-ecd4-483c-9dd3-515df8987697)

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.8.11

### Operating system

Ubuntu 22

**Comment by jaapmarcus** [comment]
What response do you get when you run:

v-add-user demo11  your password 'demo11@gmail.com' default demo11 demo11

? 

OK=0
E_ARGS=1
E_INVALID=2
E_NOTEXIST=3
E_EXISTS=4

So 3 = Something doesn't exists ...

**Comment by pks891618** [comment]
ah i found it was due to wrong package name 

Thanks for your help
