### ISSUE TITLE
Feature Request: Mail Relay

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#432]
Mail relay integration could be provided for famous services such as Amazon SES, Mailchimp etc.

**Comment by ScIT-Raphael** [comment]
Mail relay is already available in the exim configuration: https://github.com/hestiacp/hestiacp/blob/d301d61815c72955ea089da9aaf2bb54d378e1cf/install/deb/exim/exim4.conf.template#L241-L247

Add a configuration function for the backend would be nice.
