### ISSUE TITLE
[Bug] Error in Apache2 with SSL

### ISSUE THREAD

**Issue by ysilvela** [hestiacp/hestiacp#4321]
### Describe the bug

There are times when SSL files are deleted or disappear. The reason would have to be investigated. But the worrying thing is that it affects all the users of the server when the Apache2 service goes down due to a single domain.

### Tell us how to replicate the bug

Start apache2 service when the SSL certificates files (/etc/nginx/conf.d/domains/webmail.weaiwa.com.ssl.conf) not exists

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.11

### Operating system

Debian 11

### Log capture

```shell
Mar 06 13:51:53 csnur54.bastify.com systemd[1]: Starting nginx - high performance web server...
Mar 06 13:51:53 csnur54.bastify.com nginx[1814885]: nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/167.235.21.2>
Mar 06 13:51:53 csnur54.bastify.com nginx[1814885]: nginx: [emerg] open() "/etc/nginx/conf.d/domains/webmail.weaiwa.com.ssl.conf" failed (2: No such file or directory) in /etc/nginx>
Mar 06 13:51:53 csnur54.bastify.com systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Mar 06 13:51:53 csnur54.bastify.com systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 06 13:51:53 csnur54.bastify.com systemd[1]: Failed to start nginx - high performance web server.
```

**Comment by jaapmarcus** [comment]
Please provide how "config" files just disapear unless it is done via the user via command line directly? 

In this case /etc/nginx/conf.d/domains/webmail.weaiwa.com.ssl.conf doesn't exists before somebody deleted the files?

Certificates and config should not be "deleted" by Hestia and we have check in place that "prevents" Nginx / Apache2 from restarting if there is a config test error. 

We run every time nginx -t before we restart Nginx web server and any "issues" with restarting should return an error. 

So it should not happen... 

For support: https://forum.hestiacp.com
