### ISSUE TITLE
[Bug] HestiaCP forum not sending email verifications

### ISSUE THREAD

**Issue by adamgreenough** [hestiacp/hestiacp#4323]
### Describe the bug

Forum does not seem to send email verifications to be able to make a new account

### Tell us how to replicate the bug

Try and create a forum account and validate

### Which components are affected by this bug?

Docs Forums

### Hestia Control Panel Version

N/A

### Operating system

N/A

**Comment by addyzone** [comment]
Sorry for sharing here, no idea how else to get in contact!

**Comment by jaapmarcus** [comment]
This is a test email from

https://forum.hestiacp.com/

We hope you received this email deliverability test OK!

Here is a [handy checklist for verifying email delivery configuration](https://meta.discourse.org/t/email-delivery-configuration-checklist/209839).

Good luck,

Your friends at [Discourse](https://www.discourse.org/)

Please try again there was an issue on our side
