### ISSUE TITLE
[Bug] database remote failed

### ISSUE THREAD

**Issue by Benzitczo** [hestiacp/hestiacp#4332]
### Describe the bug

problem IP failed why no cant create database.

### Tell us how to replicate the bug

1. add database host mysql done
2. now is okay worked success
3. create database host ip and "error connection ip failed"

check imagen:
![image](https://github.com/hestiacp/hestiacp/assets/36309164/e2f22ae6-b6c7-422a-9b91-e455852016fc)
![image](https://github.com/hestiacp/hestiacp/assets/36309164/652e1114-6e4c-4ad9-ba50-48500b7dabef)

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

v1.8.11

### Operating system

Ubuntu 22.04 (x86_64)

### Log capture

```shell
problem failed error connection.
```

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/remote-db-for-mariadb-mysql/13487/9

**Comment by Benzitczo** [comment]
> https://forum.hestiacp.com/t/remote-db-for-mariadb-mysql/13487/9

I know, already have is okay worked IP 5003 port, connect worked fix "access denied". but no cant problem create database IP failed for hestiacp?.

![image](https://github.com/hestiacp/hestiacp/assets/36309164/5c1a59be-420b-4202-85e3-fb487da93126)

and check up image create database server.

look:
![image](https://github.com/hestiacp/hestiacp/assets/36309164/f1601577-01ba-46ac-893c-fa6e10a7d225)

**Comment by jaapmarcus** [comment]
It is trying to run the following command:

https://github.com/hestiacp/hestiacp/blob/4990504901e6073f474e1d521c62edd64137688a/func/db.sh#L71

And it is failing you might need to try to run the command and see where it goes wrong. 

Not a lot I can do without system access ..

**Comment by Benzitczo** [comment]
> It is trying to run the following command:
> 
> https://github.com/hestiacp/hestiacp/blob/4990504901e6073f474e1d521c62edd64137688a/func/db.sh#L71
> 
> And it is failing you might need to try to run the command and see where it goes wrong.
> 
> Not a lot I can do without system access ..

Ohh, ok and how is explain run command?

there is example mysql root and pass > use "--defaults-file=$mycnf -e 'SELECT VERSION()' > $mysql_out 2>&1" done right?

Or possible vps hestiacp > run commands > mysql --defaults-file=$mycnf -e 'SELECT VERSION()' > $mysql_out 2>&1 right?

but sorry i am no experts.

**Comment by Benzitczo** [comment]
Said experts help: solution success:
![image](https://github.com/hestiacp/hestiacp/assets/36309164/317fdb61-bb7c-4790-a3e5-ec76cd5f8bdf)

yep there is default mysql 3306 change 5003 worked.

**there is /usr/local/hestia/conf**
