### ISSUE TITLE
[Bug] Exim4 cannot receive email due to bad permissions of /var/log/dovecot.log file

### ISSUE THREAD

**Issue by n3b0r** [hestiacp/hestiacp#4333]
### Describe the bug

Exim4 cannot receive emails due to wrong permissions set up on /var/log/dovecot.log in a brand new Hestia 1.8.11 install.

![Captura de Pantalla 2024-03-20 a las 19 34 56](https://github.com/hestiacp/hestiacp/assets/7352160/e2d43f0e-6138-48a8-975a-6c6c1fba9830)

To fix that, I've manually set it up the following way:

```bash
chown mail:mail /var/log/dovecot.log
chmod 660 /var/log/dovecot.log
```

The default permissions are: 

```
-rw-------   1 root        root             31K Mar 20 04:44 dovecot.log
```

That error is reported to the senders as well as you can see above. 

### Tell us how to replicate the bug

1. Install Hestia on Ubuntu 20.04 with this oneliner: `bash hst-install.sh --port 8888 --hostname $host --email redacted@mail.com --password password --apache no --multiphp yes --named no --interactive no --force`
2. Create a domain with Mail Support and SSL, no other options enabled(antivirus, DKMIN, Antispam, etc)
3. Send an email and check sender and recipient inboxes

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 20.04

**Comment by sahsanu** [comment]
The right owner should be **dovecot** and group **mail** and that is what the installer does:

        
```
        # Permission changes
        chown -R dovecot:mail /var/log/dovecot.log
        chmod 660 /var/log/dovecot.log
```

Maybe the installer should be modified to include the creation of log file:

        
```
        # Permission changes
        touch /var/log/dovecot.log
        chown -R dovecot:mail /var/log/dovecot.log
        chmod 660 /var/log/dovecot.log
```

**Comment by n3b0r** [comment]
The installer creates that file by default but is owned by root using 600 as permissions. 

I'm going to give it a try on a testing server, and I'll go back to double-check if that ownership fixes the issue as well.

**Comment by n3b0r** [comment]
Confirmed, it works using dovecot:mail as owner and group.

For now, I've added that change to my install script.
