### ISSUE TITLE
[Feature]: Add ID in Response of v-add-dns-domain

### ISSUE THREAD

**Issue by kalungia** [hestiacp/hestiacp#4337]
### Describe the feature or change in detail

Hello,

If am deleting a dns record i will run a command `v-delete-dns-record` this command needs `Options: USER DOMAIN ID [RESTART]` but when creating a dns record one has to run a command `v-add-dns-domain` which doesn't return the ID that is needed to delete that record, am asking that the command `v-add-dns-domain` to return the record ID once it is ran so that we can use it to delete that record.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
The system assumes no output as success full and any text as a failure so it is hard to implant it if you need an id v-list-dns-domain can give it

**Comment by kalungia** [comment]
v-list-dns-domain is okay if you are not using api, if one is using api it is hard to tract as you add more records v-list-dns-domain is not an option

**Comment by jaapmarcus** [comment]
All the api calls execute the bash script directly so it will break it again just do the extra api call as we can't change it at the moment...
