### ISSUE TITLE
Hestiacp phpmyadmin not working. (Debian 12) [Bug] 

### ISSUE THREAD

**Issue by anuradhawe** [hestiacp/hestiacp#4360]
### Describe the bug

I installed Hestiacp on Debian 12, and when I go to https://cp,mydomain.com/phpmyadmin to access phpmyadmin, I get the error shown in the screenshot below.

![2](https://github.com/hestiacp/hestiacp/assets/166508212/216b3b35-8346-4276-a381-476ec41248ce)

I am using Hestia v1.8.11

Debian 12 has this problem.

I got this error on several VPS

Installed using the following command.

```
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

bash hst-install.sh --hostname cp.myadmin.com --email info@domain.com --password Hesta1234 --multiphp yes --clamav no
``

### Tell us how to replicate the bug

I solved the problem by Comamnd below

```
chown -R root:www-data /etc/phpmyadmin/
chown -R hestiamail:www-data /usr/share/phpmyadmin/tmp/
```
But when will this bug be fixed?

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

 v1.8.11

### Operating system

Debian 12

### Log capture

_No response_

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/4359

1 time is more then enough

**Comment by anuradhawe** [comment]
> #4359
> 
> 1 time is more then enough

Sorry, I saw it as two bugs, so I am posting two

I was able to fix the error with the following commands in Debian 12

```
chown -R root:www-data /etc/phpmyadmin/
chown -R hestiamail:www-data /usr/share/phpmyadmin/tmp/
```

But Debian 11 did not fix the error with those commands
So I thought it was two bugs, sorry
