### ISSUE TITLE
[Bug] Spam Filter Won't Disable

### ISSUE THREAD

**Issue by 3WebNZ** [hestiacp/hestiacp#4373]
### Describe the bug

Standard HestiaCP installation with all normal options.
I turned off spam filter and reject spam on email domain 2 months ago due to Outlook email servers being on Spamcop blacklist.
It worked right up until a few days ago and although the tickboxs are still off it's running anyway!

### Tell us how to replicate the bug

Unticked "Spam Filter" and "Reject Spam" for domain.
It was off for approx 2 months, then started rejecting spam again due to Spamcop blacklisting a few days ago.
Checked both were still unchecked and they are!
Re-checked and saved, then unchecked and saved to make sure, but it is still spam checking and rejecting mail.

### Which components are affected by this bug?

Mail Security (Antivirus, Antispam)

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 20.04

### Log capture

```shell
Remote server returned '550 5.7.514 Decision Engine classified the mail item was rejected because of IP Block (from outbound normal IP pools) -> 550 Rejected because 40.107.108.117 is in a black list at bl.spamcop.net;Blocked - see https://www.spamcop.net/bl.shtml?40.107.108.117'
```

**Comment by tlcd96** [comment]
See issue 
https://github.com/hestiacp/hestiacp/issues/4366

**Comment by tlcd96** [comment]
Also I'll check my server for that. Give me a couple hours and then see the issue referred

**Comment by tlcd96** [comment]
as I've said before, in the other issue, you'll have to disable the dnsbl.conf in order to receive emails.
to save you the time, here's a reference to the comment on what you should do to make that error go away:
https://github.com/hestiacp/hestiacp/issues/4366#issuecomment-2091467361

**Comment by tlcd96** [comment]
One thing, this is not recommended, at least keep the zen.spamhaus.org blocklist. the other one blocks the zen blocklist

**Comment by 3WebNZ** [comment]
Thank you that's a great fix. I had found similar info on the hestia forum and removed both lines from that file and it is def solved the issue. I just wanted to point out that unchecking those boxes doesn't appear to be turning the spam detection/rejection off in case its a bug in the code. Your a legend. :)

**Comment by 3WebNZ** [comment]
I'll leave this open in case you can replicate the check box not working, but feel free to close as your fix solves the actual real world problem. Again thanks heaps. :)

**Comment by 3WebNZ** [comment]
I have added zen.spamhaus.org back as per your advice.

**Comment by 3WebNZ** [comment]
As dnsbl.conf is in the /etc/exim4 folder does that mean checking these blacklists is actually a function of Exim4 and not SpamAssassin? Should this feature have been disabled when I unchecked the "Reject spam" as opposed to "Spam filter"?
I was unsure whether "Reject spam" rejected all spam instead of sending it to the Spam folder with "*** SPAM ***" subject or whether it was for something else so I have left it off for all mail domains.
Also should I recheck the "Spam filter" and "Reject spam" now as I have removed Spamcop from the dnsbl.conf and this would provide basic spam filtering again?
Also I did "systemctl restart exim4" after making the changes. Some people may not perform that step and I guess it won't work if they don't?

**Comment by jaapmarcus** [comment]
Reject "Spam" option currently only "reject" spam if the score is higher the 10 with Spamhaus. 

I don't know if there is an issue method to rewrite it in such way we are able to alter exim code to do the same with exim blocklists...

And it would change the current behaviour of of Exim...

**Comment by 3WebNZ** [comment]
So it is EXIM4 that's checking the SpamCop and SpamHaus blocklists?
If so should I close this issue as it's nothing to do with the Spam Filter or Reject Spam checkboxes?

**Comment by jaapmarcus** [comment]
Yes ...

**Comment by 3WebNZ** [comment]
Excellent :D
