### ISSUE TITLE
[Bug] PHP custom templates and problems

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#4384]
### Describe the bug

We have some custom templates like this:
```bash
-rw-r--r-- 1 root root 1422 May  3 04:06 PHP-7_4_custom.tpl
-rw-r--r-- 1 root root 1422 May  3 04:06 PHP-7_4.tpl
-rw-r--r-- 1 root root 1422 May  3 04:08 PHP-8_0_custom.tpl
-rw-r--r-- 1 root root 1260 May  2 15:18 PHP-8_0.tpl
-rw-r--r-- 1 root root 1422 May  3 04:07 PHP-8_1_custom.tpl
-rw-r--r-- 1 root root 1422 May  3 04:07 PHP-8_1.tpl
-rw-r--r-- 1 root root 1422 May  3 04:07 PHP-8_2_custom.tpl
-rw-r--r-- 1 root root 1422 May  3 04:07 PHP-8_2.tpl
-rw-r--r-- 1 root root 1422 May  3 04:07 PHP-8_3_custom.tpl
```
And always worked as expected in my personal server. Now when I apply PHP-8_1_custom.tpl, for example, the panel say success, but internally it does not move or recreate the config file in the new php version. If was 7.4, it will continue in 7.4, but the panel will say it is using PHP-8_1_custom.

I did not find official template doc about php template customization, just nginx/apache https://hestiacp.com/docs/server-administration/web-templates.html#why-don-t-i-have-the-option-to-use-fastcgi-cache

In the past someone here in the github recommended just copy and rename the tpl files. Now it is not working anymore.

What is the currently official or better way to have custom php tpl files?

### Tell us how to replicate the bug

1. copy one php tpl conf file and add _custom in the name, before .tpl suffix
2. apply the new php custom template using the web interface
3. the web site php conf will not move to new php version (if you are changing php from different versions; same version will work)

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.8.11

### Operating system

ubuntu 22.04

**Comment by jaapmarcus** [comment]
It should be:

YOURNAME-PHP-8_1.tpl

See:
https://hestiacp.com/docs/server-administration/web-templates.html#how-can-i-change-settings-for-a-specific-domain

It hasn't been changed since ages ...
