### ISSUE TITLE
[Feature] Integrate Git: Incremental backups, diff files to detect hacks, staging

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#4386]
### Describe the feature or change in detail

Integrating Git into HestiaCP could very easily solve many issues such as:
- How do I recover from a hacking. When did it happen? What exactly did the hacker do?
- How do I restore a backup without consuming much space
- Enhance collaboration between colleagues
- How can I restore a staging version, etc.

On a daily/hourly/minute basis we would have a cron script to take a snapshot of the uncompressed databases and the files.

`if [ ! -d "$public_html_dir" ]; then
    abort "El directorio public_html no existe: $public_html_dir."
fi
mkdir -p "$backup_dir"
if [ ! -d "$public_html_dir/.git" ]; then
    msg "Inicializando repositorio Git en $public_html_dir..."
    git init "$public_html_dir"
    cd "$public_html_dir" || exit
    echo "wp_file_integrity.txt" >> .gitignore
    git add .
    git commit -m "Initial commit for integrity check"
else
    cd "$public_html_dir" || exit
fi
git add .
git commit -m "Updated integrity check snapshot" --allow-empty
backup_file="$backup_dir/backup_$(date +'%Y%m%d_%H%M%S').tar.gz"
modified_files=$(git diff --name-only HEAD~1 HEAD)
if [ -n "$modified_files" ]; then
    tar -czf "$backup_file" $modified_files
    msg "Copia de seguridad incremental creada correctamente."
else
    msg "No hay cambios desde la última copia de seguridad. No se creó una nueva copia."
fi
msg "Copia de seguridad completada."
`

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jlguerrerosanz** [comment]
Gitlab CE could be used just the way phpmyadmin is.

So users can have a graphic interface to manage their websites.

**Comment by jaapmarcus** [comment]
You want to host a full Gitlab instance on each server :|

**Comment by jlguerrerosanz** [comment]
that is my suggestion. Is it too much? can you think about a better alternative?

The thing is that gitlab has the full web interface that can restore any version with some clicks

**Comment by mokiding** [comment]
Yes but git is not made for this purpose. Also full gitlab instance is going to kill my server.

**Comment by jlguerrerosanz** [comment]
okay okay, without gitlab. Is there a different web interface for git that you would reccomend?

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3960

Should be enough to do so ....
