### ISSUE TITLE
Feature Request: DNSSEC Support

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#439]
DNSSEC validation support.

**Comment by ScIT-Raphael** [comment]
Until now, we can't find enough time to develop and fullfill all feature request. I'll close this request for now,   if someone would like to do it on their own, just push a pull request - we will be happy for every contribution.

**Comment by gytisrepecka** [comment]
Is this issue about DNSSEC validation (DNS server acts as resolver and validates DNSSEC-enabled responses) or DNSSEC support as authoritative server (zone records added in Hestia are stored in zone file that is automatically signed)?

If it is about adding DNS support for authoritative DNS, I plan implementing such feature to Hestia - just need to work a bit on front end :)

**Comment by ScIT-Raphael** [comment]
Hi @gytisrepecka

DNSSEC support as authoritative server is the right way to go. The problem on our side is that we do not have enough time to fullfill all wishes and request. If you would like to develop a implementation for hestia, we would be really happy if you could share it with us.

If you want you can just send us a short mail to info@hestiacp.com, so I can invite you to our slack group.

**Comment by gytisrepecka** [comment]
@ScIT-Raphael, thanks, sent an e-mail!
