### ISSUE TITLE
[Feature] Is it possible to use variables in the installation script to allow the default English characters to be displayed in the terminal according to the variable to display the character encoding displayed on the current terminal? 

### ISSUE THREAD

**Issue by hestiacn** [hestiacp/hestiacp#4392]
### Describe the feature or change in detail

Is it possible to use variables in the installation script to allow the default English characters to be displayed in the terminal according to the variable to display the character encoding displayed on the current terminal? For example: sudo localectl set-locale LANG=ko_KR.UTF-8, this will allow non-professional users to have a better experience during hestia installation! For example, the user cannot understand any English or other languages!

### Would you like to sponsor this feature to have it implemented?

No

**Comment by hestiacn** [comment]
[] 시스템 설정 구성...
[] Hestia 제어판 구성...
[] TLS 성능 향상을 위한 OpenSSL 구성...
[] 기본 자체 서명 SSL 인증서 생성...
[] Hestia 제어판에 SSL 인증서 추가...
[] SFTP jail 설정...
[] 기본 관리자 계정 생성...
[] NGINX 구성...
[] Nginx용 Cloudflare IP 범위 업데이트...
[] Apache 네트워크 서버 구성...
[] PHP 8.2 설치...
[] PHP-FPM 8.2 구성...
[] PHP 구성...
[] Vsftpd 서버 구성...
[] MariaDB 데이터베이스 서버 구성...
[] phpMyAdmin 버전 v5.2.1 설치...
[] Bind9 DNS 서버 구성...
[] Exim 메일 서버 구성...
[] Dovecot POP/IMAP 메일 서버 구성...
[] ClamAV 안티바이러스 소프트웨어 설치...
[] 스팸 스캐너 구성...
[] fail2ban 액세스 시스템 구성...
[] Roundcube 설치...
[] 시스템 설정 구성...
[] Hestia 제어판 구성...
[] TLS 성능 향상을 위한 OpenSSL 구성...
[] 기본 자체 서명 SSL 인증서 생성...
[] Hestia 제어판에 SSL 인증서 추가...
[] SFTP jail 설정...
[] 기본 관리자 계정 생성...
[] NGINX 구성...
[] Nginx용 Cloudflare IP 범위 업데이트...
[] Apache 네트워크 서버 구성...
[] PHP 8.2 설치...
[] PHP-FPM 8.2 구성...
[] PHP 구성...
[] Vsftpd 서버 구성...
[] MariaDB 데이터베이스 서버 구성...
[] phpMyAdmin 버전 v5.2.1 설치...
[] Bind9 DNS 서버 구성...
[] Exim 메일 서버 구성...
[] Dovecot POP/IMAP 메일 서버 구성...
[] ClamAV 안티바이러스 소프트웨어 설치...
[] 스팸 스캐너 구성...
[] fail2ban 액세스 시스템 구성...
[] Roundcube 설치...
축하해!
서버에 Hestia 제어판을 성공적으로 설치했습니다.
시작하기 전에 도메인 이름 확인에 호스트 레코드를 추가하십시오: debian
시작할 준비 되셨나요?다음 자격 증명을 사용하여 로그인합니다.
도메인 이름으로 액세스하려면 다음과 같이 하십시오.https://debian.xxxx.me:8083/
IP를 통한 액세스:https://111.173.10.6:8083/
사용자 이름: admin
비밀번호: 당신이 설치할 때 선택한 비밀번호.
Hestia 제어판을 선택하여 전체 스택 네트워크 서버에 힘을 실어주셔서 감사합니다.
우리는 당신이 우리와 마찬가지로 그것을 즐겨 사용하기를 바랍니다!
질문이 있거나 오류나 문제가 있으면 언제든지 문의하십시오.
문서:https://docs.hestiacp.com/
포럼:https://forum.hestiacp.com/
GitHub: https://www.github.com/hestiacp/hestiacp
참고 자동 업데이트는 기본적으로 활성화되어 있습니다.비활성화하려면
로그인하고 서버 > 업데이트로 이동하여 서버를 닫으십시오.
PayPal 기부금을 통한 Hestia 제어판 프로젝트 지원:
https://www.hestiacp.com/donate

즐거운 하루 되세요.
Hestia 제어판 개발팀
세계 각지에서 온 오픈 소스 커뮤니티에서 사랑을 가득 품은 개발자가 개발한 제품입니다.
[!] 중요: 시스템이 설치 프로세스를 완료하기 위해 재부팅됩니다.
아무 키나 눌러 계속
위는 설치 내용을 바탕으로 제가 번역한 예입니다!

**Comment by jaapmarcus** [comment]
No we can't unless we are going translate everything seperatly and it not worth the time investment...
