### ISSUE TITLE
[INFO] - Please add HTMY version on footer 

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#4393]
### Describe the feature or change in detail

[INFO] - Please add HTMY version on footer. So we easily can identify which version we using now & consider the updates in future.. tq

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by AlecRust** [comment]
@vvcares what do you mean? What is HTMY?

Please note the next version of Hestia includes an improved footer with the current version number.

**Comment by Jamiul-Bari** [comment]
@AlecRust, any probable release date for the next version? And which branch has the next version?

**Comment by AlecRust** [comment]
I don't manage releases, `main` has the latest changes. I have no release date for you I'm afraid.

**Comment by vvcares** [comment]
> @vvcares what do you mean? What is HTMY?
> 
> Please note the next version of Hestia includes an improved footer with the current version number.

typo err instead of HESTIA

**Comment by AlecRust** [comment]
If you want the Hestia version displayed in the footer, this is already done and will be in the next release 🙂
