### ISSUE TITLE
[Feature] Ability to add a Global Admin or Global Team

### ISSUE THREAD

**Issue by mryanbc** [hestiacp/hestiacp#4398]
### Describe the feature or change in detail

I believe atm only one account has the ability of seeing all the users, admins and so on. I think the super admin should have the ability to add team members of sort who can also see all the users, admins and so. 

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We currently have 3 roles:

1. User 
2. Administrator 
3. DNS User

There are no plans to add an "Super" admin role  any administrator is able to see alll "administrator" accounts

**Comment by jlguerrerosanz** [comment]
Maybe a reseller role

I kind of lack this feature.
