### ISSUE TITLE
[Bug] If outgoing mail servers checks for spam and uses BAYES then hestia marks all incoming email as spam even if spamassassin is disabled

### ISSUE THREAD

**Issue by jim-perkins** [hestiacp/hestiacp#4401]
### Describe the bug

Subject of all incoming email is marked as *** SPAM *** .  This occurs even if if spamassassin is disabled.  My outgoing mail server checks for spam and adds spamassassin headers as below

```
X-Spam-Status: No, score=-96.4 required=2.0 tests=BAYES_50,DCC_CHECK,
    DIGEST_MULTIPLE,DKIM_SIGNED,DKIM_VALID,FSL_BULK_SIG,HTML_MESSAGE,
    PYZOR_CHECK,T_SCC_BODY_TEXT_LINE,UNPARSEABLE_RELAY,USER_IN_WELCOMELIST,
    USER_IN_WHITELIST autolearn=no autolearn_force=no version=3.4.4
```

The Hestia cp file /etc/exim4/system.filter has the following conditions:
```
if $h_X-Spam-Status: contains "Yes"
then
    headers add "Old-Subject: $h_subject"
    headers remove "Subject"
    headers add "Subject: *** SPAM *** $h_old-subject"
    headers remove "Old-Subject"
endif
```
apparently that regex is case insensitive because "Yes" is being tripped on "BAYES_50" and marking the subject as spam.  As I said above this is even if spamassassin is disabled on hestia cp.  changing the "Yes" to "Yes " (added whitespace) solves this issue.

Here is a simple diff that fixes my problem
```
root@redacted_hostname:/etc/exim4# diff system.filter system.filter.orig 
1c1
< if $h_X-Spam-Status: contains "Yes "
---
> if $h_X-Spam-Status: contains "Yes"
```

I can create a pull request with this if requested although it does not fix the issue where no subject should be rewritten as SPAM if spamassassin is disabled

### Tell us how to replicate the bug

Send an email from a mail server using spamassassin and a BAYES filter

### Which components are affected by this bug?

Mail Security (Antivirus, Antispam)

### Hestia Control Panel Version

1.8.11

### Operating system

Debian 12

**Comment by jim-perkins** [comment]
so the change above quit falsely marking spam but it wasnt properly rewriting the subject on real spam.  This regex worked in my testing

`if $h_X-Spam-Status: matches ^Yes\$`

the no quotations are important https://www.exim.org/exim-html-3.30/doc/html/filter_20.html
i guess you could double escape the $ if the quotes are wanted

**Comment by cyber-bye** [comment]
Sorry but I'm asking here.

 I'm try to using "Email login credentials to" problem with hcp.domain.tld(FQDN) while sending emails I mean not showing records to add or not able add mail domain (as subdomain)


Kindly reply if anyone knows the solution

**Comment by jim-perkins** [comment]
It doesn't look like your question is in any way related to this bug report. I can not help you here.

You should ask your question here.  
https://forum.hestiacp.com/

Have a good day
