### ISSUE TITLE
Feature Request: Password protected web folders

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#441]
Password protected web folders using basic http authentication.

**Comment by ghost** [comment]
This functionality is already present in the backend using **v-add-web-domain-httpauth** and **v-delete-web-domain-httpauth**, however this should be available from the Control Panel UI as well.

**Comment by Lupul** [comment]
`v-add-web-domain-httpauth` does not work with apache2
-htaccess files in not included in web templates
-htpasswd cannot be accesed by apache. File perms: root:$user (0640)

**Comment by starrhi** [comment]
Probably, good time to review this very old request to include in future 2.0 versions. 
Having Control Panel UI for password protecting folders will be a great addtion.
Hestia lacks very few things and this is one of the most important for end users.
