### ISSUE TITLE
Is HestiaCP Project now dead/Abandoned?

### ISSUE THREAD

**Issue by agarwalbikram** [hestiacp/hestiacp#4412]
Hello,
I enjoy using HestiaCP for its user-friendly interface. However, I have noticed a lack of updates in HestiaCP for the past 7-8 months. Some common issues, such as PhpMyAdmin permissions, have remained unfixed for months. I am curious if this project has been abandoned with no further development.?

**Comment by Jamiul-Bari** [comment]
https://forum.hestiacp.com/t/when-is-the-next-release/13404

It seems like it is still ongoing. The master branch had the latest commit last week. It looks like they are busy with other projects.

**Comment by jaapmarcus** [comment]
I have been extremely busy with other "work" things ...
