### ISSUE TITLE
[Bug] v-import-cpanel unable to import databases

### ISSUE THREAD

**Issue by shunkica** [hestiacp/hestiacp#4428]
### Describe the bug

Trying to import cpanel move created on cpanel v120.0.10

The databases fail to import with error:

```
Start with Databases
ERROR at line 1: Unknown command '\-'.
ERROR 1049 (42000): Unknown database 'foo'
```

The cpanel server is running MariaDB 10.6.18-1

### Tell us how to replicate the bug

1. Create backup on cpanel using `/scripts/pkgacct user`
2. Import backup on hestia using `v-import-cpanel cpmove-user.tar.gz`

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.8.11

### Operating system

Debian 12

**Comment by wojsmol** [comment]
Related MariaDB ticket https://jira.mariadb.org/browse/MDEV-34183 `/*!999999\- enable the sandbox mode */` is causing issue during import.
