### ISSUE TITLE
Security Enhancement: /home, /backup, /var/lib/mysql etc

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#443]
Non proviledged users should not be able to view all the username under /home or all the backups (and thus the usernames) in /backup folder. Same applies for databases in /var/lib/mysql and other areas as well.

**Comment by ScIT-Raphael** [comment]
Needs jail ssh, already susposed here: https://github.com/hestiacp/hestiacp/issues/442
