### ISSUE TITLE
Failed to start clamav-deamon on Ubuntu 24.04

### ISSUE THREAD

**Issue by ronald-at** [hestiacp/hestiacp#4436]
### Describe the bug

I've compiled the branch noble-support and installied in on a test system with Ubuntu 24.04. The clamav-deamon is not start. 
![grafik](https://github.com/hestiacp/hestiacp/assets/68246972/e5852e13-dd8d-4c89-a011-2ed3eda3c7c6)

### Tell us how to replicate the bug

1. Compile branch noble-support
2. Install on Ubuntu 24.04
3. Open "Server settings" in Hestia web interface

### Which components are affected by this bug?

Mail Security (Antivirus, Antispam)

### Hestia Control Panel Version

v1.9.0~alpha

### Operating system

Ubuntu 24.04

### Log capture

```shell
2024-07-07T16:09:09.135909+02:00 ... systemd[1]: clamav-daemon.socket - Socket for Clam AntiVirus userspace daemon was skipped becauseof an unmet condition check (ConditionPathExistsGlob=/var/lib/clamav/main.{c[vl]d,inc}).
2024-07-07T16:09:09.136138+02:00 ... systemd[1]: clamav-daemon.service - Clam AntiVirus userspace daemon was skipped because of an unmet condition check (ConditionPathExistsGlob=/var/lib/clamav/main.{c[vl]d,inc}).
```

**Comment by jaapmarcus** [comment]
I just tested on a newly installed Hestia 24.04 and I am not able to replicate the issue

root@test:~# v-list-sys-services 
NAME           STATE    CPU  MEM   UPTIME
----           -----    ---  ---   ------
apache2        running  0    446   92
php8.3-fpm     running  0    8     92
nginx          running  0    9     92
bind9          running  0    66    92
exim4          running  0    17    92
dovecot        running  0    0     92
clamav-daemon  running  0.4  1374  92
spamassassin   running  0    379   92
mariadb        running  0    680   92
vsftpd         running  0.4  1375  92
cron           running  0    0     92
ssh            running  1    6     91
iptables       running  0    0     0
fail2ban       running  0.4  158   92
root@test:~# 

Try if you can manually download the files maybe that went wrong during setup?

Complementary to Omid's answer, you can manually download the .cvd files from the mirror below and place them in /var/lib/clamav.

https://database.clamav.net/main.cvd
https://database.clamav.net/daily.cvd

**Comment by ronald-at** [comment]
I've tried to build Hestia noble-support again, but after building hestia I wasn't able to start to start it:
```[ * ] Configuring File Manager...
/usr/local/hestia/bin/v-add-sys-filemanager: line 66: /usr/local/hestia/php/bin/php: No such file or directory
[ * ] Configuring PHP dependencies...
/usr/local/hestia/bin/v-add-sys-dependencies: line 69: /usr/local/hestia/php/bin/php: No such file or directory
[ * ] Installing Rclone...
[ * ] Configuring System IP...
[ * ] Installing remaining software updates...E: The repository 'https://apt.hestiacp.com noble Release' does not have a Release file.

Job for hestia.service failed because the control process exited with error code.
See "systemctl status hestia.service" and "journalctl -xeu hestia.service" for details.
Error: hestia start failed
```

Systemctl shows the following error:
``` sudo systemctl status hestia.service
× hestia.service - LSB: starts the hestia control panel
     Loaded: loaded (/etc/init.d/hestia; generated)
     Active: failed (Result: exit-code) since Fri 2024-07-12 23:57:31 CEST; 4min 13s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 59718 ExecStart=/etc/init.d/hestia start (code=exited, status=2)
      Tasks: 2 (limit: 9444)
     Memory: 2.0M (peak: 3.3M)
        CPU: 27ms
     CGroup: /system.slice/hestia.service
             ├─59723 "nginx: master process /usr/local/hestia/nginx/sbin/hestia-nginx"
             └─59724 "nginx: worker process"

Jul 12 23:57:31 ... hestia[59718]:  * Starting hestia-nginx hestia-nginx
Jul 12 23:57:31 ... hestia[59722]: nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/usr/local/hestia/ssl/certificate.crt"
Jul 12 23:57:31 ... hestia[59718]:    ...done.
Jul 12 23:57:31 ... hestia[59718]:  * Starting hestia-php hestia-php
Jul 12 23:57:31 ... hestia[59725]: start-stop-daemon: unable to stat /usr/local/hestia/php/sbin/hestia-php (No such file or directory)
Jul 12 23:57:31 ... systemd[1]: hestia.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Jul 12 23:57:31 ... systemd[1]: hestia.service: Failed with result 'exit-code'.
Jul 12 23:57:31 ... systemd[1]: hestia.service: Unit process 59723 (hestia-nginx) remains running after unit stopped.
Jul 12 23:57:31 ... systemd[1]: hestia.service: Unit process 59724 (hestia-nginx) remains running after unit stopped.
Jul 12 23:57:31 ... systemd[1]: Failed to start hestia.service - LSB: starts the hestia control panel.
```

**Comment by jaapmarcus** [comment]
Did you only build the hestia package or everything?

It looks like  php failed to build...

**Comment by ronald-at** [comment]
I've run all the build steps shown in https://hestiacp.com/docs/contributing/building.html in chapter "Installing Hestia from a branch". I've chosen branch noble-support and run hst-install-ubuntu.sh at the end. I think this should build php too.

**Comment by jaapmarcus** [comment]
> I've run all the build steps shown in https://hestiacp.com/docs/contributing/building.html in chapter "Installing Hestia from a branch". I've chosen branch noble-support and run hst-install-ubuntu.sh at the end. I think this should build php too.

I know but if there is not enough memory it might cause a failure. As Hestia-php  isn't installed it might cause the issue.

**Comment by ronald-at** [comment]
Now everything is compiling correctly. Sorry, I forgot to compile as root. Now clamav-daemon  is running correctly.
