### ISSUE TITLE
Feature Request: Whitelist/Blacklist Email Addresses or Domains through the UI

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#444]
There should be the ability for users to select their per mailbox (or per account) settings with regards to whitelist and blacklist email addresses or domains. This capability should be provided through the UI.

**Comment by ScIT-Raphael** [comment]
Until now, we can't find enough time to develop and fullfill all feature request. I'll close this request for now,   if someone would like to do it on their own, just push a pull request - we will be happy for every contribution.
