### ISSUE TITLE
[Bug] chroot ssh or chroot sftp: chroot ssh coming in v1.9

### ISSUE THREAD

**Issue by gthb1** [hestiacp/hestiacp#4446]
### Describe the bug

Hi,
chroot ssh seems not to work, only chroot sftp.
Is the current state of hestiacp more like
(1) chroot ssh: https://linuxconfig.org/jail-ssh-user-to-home-directory-on-linux
OR
(2) chroot sftp: https://access.redhat.com/solutions/2399571
?
Could (1) be done eventually if not so already?
Please let me know if I missed something.
Thx

### Tell us how to replicate the bug

Create user and enable ssh for that user.
Login via ssh, and all the server is available, not just the user's directories.

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 22.04.4 LTS

**Comment by jaapmarcus** [comment]
we don't offer chroot ssh yet ..

Will be added in 1.9

**Comment by gthb1** [comment]
Hi @jaapmarcus,
Is there any movement or ETA on this?
Thx!

**Comment by gthb1** [comment]
Has this been added/resolved please?

**Comment by jaapmarcus** [comment]
Chrooted SSH has been added via bubble wrap..

**Comment by gthb1** [comment]
How can its safety be tested?
