### ISSUE TITLE
Security Enhancement: More filters for Fail2Ban

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#447]
More filters could be added for Fail2Ban, for example Nginx/Apache numerous 404 requests etc.

**Comment by JOduMonT** [comment]
related:  [fal2ban recidive](https://github.com/hestiacp/hestiacp/issues/482)

**Comment by ScIT-Raphael** [comment]
Until now, we can't find enough time to develop and fullfill all feature request. I'll close this request for now,   if someone would like to do it on their own, just push a pull request - we will be happy for every contribution.
