### ISSUE TITLE
[Feature] Monero donations

### ISSUE THREAD

**Issue by divinity76** [hestiacp/hestiacp#4476]
### Describe the feature or change in detail

[Monero](https://en.wikipedia.org/wiki/Monero) is one of the leading privacy-focused cryptocurrencies (competing with Zcash and Beam), 
and some people may want to donate Monero.

Can we add a Monero donate address? 

Fwiw I find [MyMonero](https://mymonero.com/) to be the best overall monero wallet, hitting the sweet spot between security and simplicity. (I find it much easier to use than [the official Monero wallet](https://www.getmonero.org/downloads/) which IMO is a pain to use)

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
> Fwiw I find [MyMonero](https://mymonero.com/) to be the best overall monero wallet, hitting the sweet spot between security and simplicity. (I find it much easier to use than [the official Monero wallet](https://www.getmonero.org/downloads/) which IMO is a pain to use)

Official wallet is a pain  to use..  

This wallet should be working fine:
`45p5eKWfp3kYcY3cBtKq2TWpp5HGYFAbre2Xd76sRhWGXfahAj5MkxzV2oPF2VqU617pwS5JZh1h4gy6jTm73vE7PnQ48Rs`

**Comment by divinity76** [comment]
> This wallet should be working fine

Nice. Can we add it to [the list](https://github.com/hestiacp/hestiacp?tab=readme-ov-file#donate)?

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/docs/update-docs/docs/donate.md

It has been added to a PR to add it to the list ...

**Comment by divinity76** [comment]
👍 closing
