### ISSUE TITLE
[Bug] NAT IP Association can't be edited 

### ISSUE THREAD

**Issue by Debayan-Sarkar** [hestiacp/hestiacp#4478]
### Describe the bug

![Screenshot 2024-07-26 205021](https://github.com/user-attachments/assets/ad4a6f03-8be6-41cd-a3e7-57adc5da2fd1)
i can't edit the NAT IP Association whenever try to edit showing as the below images shown this is happening when i am installing hestiacp in virtualbox ubuntu but not happening when installing on vps please help me i can't install ssl because of ip mismatch and also i can't add new ip address saying assigned user can't be blank while the shared is checked 
![image](https://github.com/user-attachments/assets/1b2d7d83-2d38-41f7-97c9-0037286a3f7c)
 when i am installing the hestiacp in virtualbox it is configuring the NAT IP Association  but when in vps it is not

### Tell us how to replicate the bug

1. Install ubuntu in virtualbox
2. Install Hestiacp by provided documentation in official website
 

### Which components are affected by this bug?

Let's Encrypt SSL

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 22.04 LTS

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/4380

Use command line and it should work fine is a know  issue

**Comment by Debayan-Sarkar** [comment]
Yes it was solved before the response
