### ISSUE TITLE
[Bug] Database name

### ISSUE THREAD

**Issue by thiagopollachini** [hestiacp/hestiacp#4484]
### Describe the bug

When we create a database, it uses the username + database name.
In mariaDB we can't use dots in the database name:
i e: domain.com_databasename.

### Tell us how to replicate the bug

add-database

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

stable

### Operating system

Debian 12

**Comment by Skamasle** [comment]
Hi

You are right and the ideal would be to not use periods in databases, but this was already discussed some time ago and the problem is that correcting this can affect the restoration of backups of user accounts that already have periods in their names

But it is not a bug as such, since mariadb specifies that special characters can be used in names as long as the quotation marks are used properly.

Therefore, in principle, databases and users can be created with the period in the name.

Example:

`> show create database hola.com_hola;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.com_hola' at line 1
`

With quotes:

> > show create database `hola.com_hola`;
+---------------+------------------------------------------------------------------------------------------------------+
| Database      | Create Database                                                                                      |
+---------------+------------------------------------------------------------------------------------------------------+
| hola.com_hola | CREATE DATABASE `hola.com_hola` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ |
+---------------+------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

But this comes from vestacp, if this was fixeds in easy way, people may have problems with backups, and other thinks in old accounts.

**Comment by thiagopollachini** [comment]
When i tried to install nextcloud it gives an error about this dot.

**Comment by thiagopollachini** [comment]
> Hi
> 
> You are right and the ideal would be to not use periods in databases, but this was already discussed some time ago and the problem is that correcting this can affect the restoration of backups of user accounts that already have periods in their names
> 
> But it is not a bug as such, since mariadb specifies that special characters can be used in names as long as the quotation marks are used properly.
> 
> Therefore, in principle, databases and users can be created with the period in the name.
> 
> Example:
> 
> `> show create database hola.com_hola; ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.com_hola' at line 1 `
> 
> With quotes:
> 
> > > show create database `hola.com_hola`;
> > > +---------------+------------------------------------------------------------------------------------------------------+
> > > | Database      | Create Database                                                                                      |
> > > +---------------+------------------------------------------------------------------------------------------------------+
> > > | hola.com_hola | CREATE DATABASE `hola.com_hola` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ |
> > > +---------------+------------------------------------------------------------------------------------------------------+
> > > 1 row in set (0.000 sec)
> 
> But this comes from vestacp, if this was fixeds in easy way, people may have problems with backups, and other thinks in old accounts.

Ok, but when applying this patch do the source code, in a new installation, it will work good. In a production system, can be done a script to rename every backup and update the database, right?

**Comment by Skamasle** [comment]
> When i tried to install nextcloud it gives an error about this dot.

I know, most systems not care about it.



> > Hi
> > You are right and the ideal would be to not use periods in databases, but this was already discussed some time ago and the problem is that correcting this can affect the restoration of backups of user accounts that already have periods in their names
> > But it is not a bug as such, since mariadb specifies that special characters can be used in names as long as the quotation marks are used properly.
> > Therefore, in principle, databases and users can be created with the period in the name.
> > Example:
> > `> show create database hola.com_hola; ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.com_hola' at line 1 `
> > With quotes:
> > > > show create database `hola.com_hola`;
> > > > +---------------+------------------------------------------------------------------------------------------------------+
> > > > | Database      | Create Database                                                                                      |
> > > > +---------------+------------------------------------------------------------------------------------------------------+
> > > > | hola.com_hola | CREATE DATABASE `hola.com_hola` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ |
> > > > +---------------+------------------------------------------------------------------------------------------------------+
> > > > 1 row in set (0.000 sec)
> > 
> > 
> > But this comes from vestacp, if this was fixeds in easy way, people may have problems with backups, and other thinks in old accounts.
> 
> Ok, but when applying this patch do the source code, in a new installation, it will work good. In a production system, can be done a script to rename every backup and update the database, right?

Need ask to devs, but In my mind it will break some user accounts.

Of course you can patch this in your hestia and prevent your user add accounts with dots by editing main.sh ( is_user_format_valid function )

**Comment by Skamasle** [comment]
Maybe a solution here is to just remove the possibility of creating users with dots in their usernames.

Additionally, edit the v-restore-backup script to include the option to restore a user with a different username. I suppose if someone uses a name with dots, they just won't have databases.

**Comment by thiagopollachini** [comment]
The prefix of each user is their domain. So, domain.com is already set when creating a database.
A workaround is preg_replace . to _ .

**Comment by Skamasle** [comment]
> The prefix of each user is their domain. So, domain.com is already set when creating a database. A workaround is preg_replace . to _ .

No, prefix is user account, and this user is manually added by each user when create hestiacp user, by defalut isnt domain, because when you create user, you not add domain by default.

**Comment by jaapmarcus** [comment]
We could just block the usage for . user name in here:
https://github.com/hestiacp/hestiacp/blob/f5603eb649d3825df0f4cfa61945f6f3c371c784/func/main.sh#L761-L766

**Comment by Skamasle** [comment]
> We could just block the usage for . user name in here:
> 
> https://github.com/hestiacp/hestiacp/blob/f5603eb649d3825df0f4cfa61945f6f3c371c784/func/main.sh#L761-L766

Remember than we add that for fix some other issue with user names and this code not afect when restore a user backup

Working fine for me:

```
`root@hestia:/usr/local/hestia/func# v-restore-user hola.com hola.com.2024-07-29_20-08-38.tar
-- USER --
2024-07-29 20:09:11 hola.com

-- WEB --
2024-07-29 20:09:12 hola.com

-- DNS --

-- MAIL --

-- DB --
2024-07-29 20:09:14 hola.com_hola
/backup/tmp.d9veMszRyk/db/hola.com_hola/hola.com_hola.mysql.sql.zst: 1354 bytes 

-- CRON --
2024-07-29 20:09:14 0 cron jobs

-- USER FILES --
2024-07-29 20:09:14 .config
2024-07-29 20:09:14 .composer
2024-07-29 20:09:14 .npm
2024-07-29 20:09:14 .local
2024-07-29 20:09:14 .ssh
2024-07-29 20:09:14 .vscode-server
2024-07-29 20:09:14 .bash_logout
2024-07-29 20:09:14 .bashrc
2024-07-29 20:09:15 .wp-cli
2024-07-29 20:09:15 .cache
2024-07-29 20:09:15 .profile


root@hestia:/usr/local/hestia/func# v-add-user hola.net hola hola@hola.com
Error: invalid user format :: hola.net

`
```

**Comment by jaapmarcus** [comment]
See: https://github.com/hestiacp/hestiacp/pull/4486
