### ISSUE TITLE
[Bug] Falla en el File Manager

### ISSUE THREAD

**Issue by Miguel-OrtizM** [hestiacp/hestiacp#4490]
### Describe the bug

Podemos ingresar a OS Hestia, pero cuando se ingresa a File Manager, carga el siguiente error Unknown error
![Captura de pantalla 2024-08-02 102928](https://github.com/user-attachments/assets/5dc038fb-1efe-45b0-8525-bbc25dc4b68b)

### Tell us how to replicate the bug

1 ingresamos al panel de HestiaCP 2. clic en file manager

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.8.11

### Operating system

Ubuntu 22.04 (x86_64)

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/nginx-error.log for more information

And https://forum.hestiacp.com for support
