### ISSUE TITLE
sftpc() is defined twice in hestia

### ISSUE THREAD

**Issue by jim-perkins** [hestiacp/hestiacp#4492]
### Describe the bug

The bash function sftpc()  is defined twice in hestia .  I wouldnt necessarily call this a bug.  It could lead to confusion. I didnt verify that the functions are exactly the same but they probably shouldnt have the same name in any case.  Maybe the one inside $HESTIA/bin/v-add-backup-host could be removed and accessed thru $HESTIA/func/backup.sh

### Tell us how to replicate the bug

cd $HESTIA
grep -r "sftpc()" *

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.8.11

### Operating system

Debian 12

**Comment by jaapmarcus** [comment]
The are not exactly the same.

Same as with ftpc() function:

```
# FTP Functions
# Defining ftp command function
ftpc() {
	/usr/bin/ftp -np $HOST $PORT << EOF
    quote USER $USERNAME
    quote PASS $PASSWORD
    binary
    $1
    $2
    $3
    quit
EOF
}
```

vs 

```
ftpc() {
	ftp -p -n $host $port << EOF
    quote USER $user
    quote PASS $password
    binary
    $1
    $2
    $3
    quit
EOF
```

The changes are about the same for sftpc() function

**Comment by jim-perkins** [comment]
thanks.  I hadnt even noticed ftpc
