### ISSUE TITLE
Feature Request: Perform apache/nginx config tests

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#450]
It will be very useful to test configuration for apache (apache2ctl configtest) and nginx (nginx -t) in cases like add website, delete website, rebuild website and inform the user if there is an issue.

**Comment by JOduMonT** [comment]
Also; if I remember well, VestaCP UI had a warning if the webservice configuration was wrong this feature seams being lost through the fork

**Comment by ScIT-Raphael** [comment]
As requested in our fourm (https://forum.hestiacp.com/t/why-restart-instead-a-reload/763) we could think about to only do a reload on template change, according to https://stackoverflow.com/questions/13525465/when-to-restart-and-not-reload-nginx, a restart seems only be needed on ip address change (listen).

**Comment by jaapmarcus** [comment]
This should also apply to other services like Bind
