### ISSUE TITLE
[Bug] Cron job command adds as blank when manually added / updated via UI on admin/initial user, and does not run at all!

### ISSUE THREAD

**Issue by vdbhb59** [hestiacp/hestiacp#4511]
### Describe the bug

There are 2 issues here, both inter-connected:-
The manually added cron entry via UI (admin user) shows saved, but the entry does not actually get added to the cron.conf file. The UI also shows the entry command line as blank (rest all show as generated/added).
The same thing happens when after manually correcting lines in the files, I need to update it at the file again.
The file does not run at all.

FYI: The script when run manually from terminal works as set.

### Tell us how to replicate the bug

**Expected**
* Click on cron tab (admin user)
* Fill out the details as necessary
* Ensure to keep the file in `/usr/local/hestia/bin/` folder
* Ensure the cron job file has proper permissions set
* Click save
* Click back to check the added cron job entry in the UI itself
* Look at the CRON tab in the UI to get the total cron jobs number reflect (example 11 > 12)
* Navigate to file `/usr/local/hestia/data/users/admin/cron.conf`
* Open to check the command has been added to the new line

**Actual**
* All steps followed, but the cron job "command" does not get populated with the cron command in the UI
* The total number of cron jobs does change. Example 11 > 12
* Navigating to the `cron.conf` file does not show the command line either. It shows as:
`JOB='12' MIN='50' HOUR='10' DAY='*' MONTH='*' WDAY='*' CMD='' SUSPENDED='no' TIME='14:49:16' DATE='2024-08-13'` instead of `JOB='12' MIN='50' HOUR='10' DAY='*' MONTH='*' WDAY='*' CMD='sudo /usr/local/hestia/bin/FILENAMEHERE' SUSPENDED='no' TIME='14:49:16' DATE='2024-08-13'`
* The cron job command should populate in the UI
* The cron command line should get populated in the cron jobs file too.
* The cron should run automatically too as set (this is the second issue).

**Few snapshots**

![image](https://github.com/user-attachments/assets/b86f699b-67e7-48d0-ac78-3443e702bbf3)

![image](https://github.com/user-attachments/assets/567d8be3-b86b-493e-b7d4-08a073d05349)

![image](https://github.com/user-attachments/assets/dacd20c4-20d0-45e8-9d27-b72bd794b1f2)

![image](https://github.com/user-attachments/assets/e54d5e9d-fbca-404f-b6c0-2419579147bf)

![image](https://github.com/user-attachments/assets/ddb9f13b-dff0-4743-a638-25138d61c237)

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.8.11

### Operating system

Debian 12 Bookworm Minimal

**Comment by jaapmarcus** [comment]
What exact command did you ran?

**Comment by vdbhb59** [comment]
So I have my hosts file which run daily/nightly at the given TZ. 10*50***.
It is executable bash file, so basically I just run ./filename (example ./hosts if I have to do it from the folder manually).
Would it work, if I add `sudo /usr/local/hestia/bin/./hosts` instead of just `sudo /usr/local/hestia/bin/hosts`?
Update: Nope, does not work. :(

**Comment by jaapmarcus** [comment]
Hestia doesn't have a hosts executable by default if you want to run a command as root just run it as root user

**Comment by vdbhb59** [comment]
In my shared hosting plan, I could run it on a cron under cPanel. This is a bash file, which runs to generate hosts file, and this is no a hosts file itself. Any cron should run just like a cron.
Since you mentioned run as a root, how do I do it via HestiaCP?

**Comment by vdbhb59** [comment]
I got it to work, but as you suggested via root user. Thanks for your help.
`20,37 * * * * /PATH/FILE.sh`
It ran automatically.
