### ISSUE TITLE
[Feature] Exclude mounted folders from user backup (or follow symlinks)

### ISSUE THREAD

**Issue by bartlebi** [hestiacp/hestiacp#4512]
### Describe the feature or change in detail

It would be great if we could exclude not only user directories from backups, but also “system” ones. For example, I store mail messages on a separate server and mount them using NFS, but I have no way to exclude the mounted folder, since there is a hard link to it in the /home/%user%/~mail - >/mnt/mail directory, the script follows the path and archives it in that including data from the mounted partition.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by Skamasle** [comment]
Hi bartlebi

Actually you can exclude mail domains, so you can just put your domain in exclution list.


![cap1](https://github.com/user-attachments/assets/7d866ea9-3757-488a-b502-5c74e5232ada)

**Comment by jaapmarcus** [comment]
Allready supported
