### ISSUE TITLE
[Feature] Allow domain only start with "www"

### ISSUE THREAD

**Issue by asika32764** [hestiacp/hestiacp#4513]
### Describe the feature or change in detail

This is same as https://github.com/hestiacp/hestiacp/issues/2632

Currently, we can add a domain, for example: `example.org`, HestiaCP will add www version: `www.example.org` as subdomain.

But we are unable to use only `www` domain as main domain, the Let's encrypt will failure and report

```
Error: web domain example.org doesn't exist
```

I think this is important, many clients did not noticed that www and non-www should be same domain, they may use them on different usages.

Describe of argue to them about how www works is unhelpful, no one wants to be educated about the basic internet theory, they just wants us to solve their problem.

I know this use case may be very rare, but sometimes we need at least a configure to allow us to enable Let's Encrypt for 
 www only domain. If HestiaCP can allow managers to configure it, it will be very helpful.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by asika32764** [comment]
My current solution:

Edit `/usr/local/hestia/func/main.sh`

at about line `1393 `, found `format_domain()`

Modify

```
        if [[ "$domain" =~ ^www\..* ]]; then
                domain=$(echo "$domain" | sed -e "s/^www.//")
        fi
```

To

```
        if false; then
                domain=$(echo "$domain" | sed -e "s/^www.//")
        fi
```

Then we can enable lets-encrypt by 

```
v-add-letsencrypt-domain {account} {domain}.com
```

----

But after HestiaCP updated, this file will be override, so this is not the perfect solution.

**Comment by jaapmarcus** [comment]
Add domain.org as domain 
Aliases are added by the default so www can be used without any issue.. 
Request LE 
and redirect non www to www.

You don't want to mix usage of www and non www of the same domain

We have allready discussed in the past and we will not change this behavour

**Comment by asika32764** [comment]
> Aliases are added by the default so www can be used without any issue..
Request LE
and redirect non www to www.

Looks like you misunderstand my case, sometimes, enterprise or company may set:
- www => IP: A  to HestiaCP
- non-www => IP: B to another service we can't control

If we set non-www domain as main domain and www as alias, the LE won't work, it can't verify non-www domain. And currently there is impossible to do any workaround to solve this issue except we hack HestiaCP source code.

The HestiaCP manager not always the domain administrators, and we can't always convince domain administrators not to use www and non-www for different purposes

**Comment by ww7** [comment]
Please reopen this issue @jaapmarcus 

Mentioned `redirect non www to www` is not solution for some cases:
1. just www. as single
2. setup www. as first location to avoid redirect and allow PHP to see it as HTTP_HOST / ISTESTSERVER etc

**Comment by jaapmarcus** [comment]
The few use cases don't warn the time to fix the issue and solve 99  other cases where the default behaviour is fine.

**Comment by ww7** [comment]
Note: in my current case I need to have www. to be first at Nginx `server { server_name` so I tricked with custom template and switched to use alias first `server_name %alias_idn% %domain_idn%;`
