### ISSUE TITLE
[Bug] Error during installation Hestia 1.9.0~alpha on Ubuntu 24.04

### ISSUE THREAD

**Issue by robsonek** [hestiacp/hestiacp#4523]
### Describe the bug

New installation on fresh Ubuntu on Proxmox. 

### Tell us how to replicate the bug

wget https://beta-apt.hestiacp.com/hst-install-ubuntu.sh 
bash hst-install-ubuntu.sh 

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.9.0~alpha

### Operating system

Ubuntu 24.04

### Log capture

```shell
NOTE: This process may take 10 to 15 minutes to complete, please wait...
E: Sub-process /usr/bin/dpkg returned an error code (1)


========================================================================

[ * ] Configuring system settings...


------

invoke-rc.d: policy-rc.d denied execution of start.
dpkg: error processing package hestia-nginx (--configure):
 installed hestia-nginx package post-installation script subprocess returned error exit status 1
Setting up dovecot-core (1:2.3.21+dfsg1-2ubuntu5) ...

------
```

**Comment by robsonek** [comment]
```shell
sudo apt-get remove --purge hestia-nginx
sudo apt-get install hestia-nginx
```

```shell
Setting up hestia-nginx (1.27.0) ...
dpkg: error processing package hestia-nginx (--configure):
 installed hestia-nginx package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-nginx
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by robsonek** [comment]
This is probably a problem with

```shell
syshealth_adapt_hestia_nginx_listen_ports  # Adapt port listing
``` 

on hestia-nginx.postinst

**Comment by jaapmarcus** [comment]
The issue is caused by:
invoke-rc.d: policy-rc.d denied execution of start.

This should fix the issue:
echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d

But I wonder why it is causing it....

**Comment by jaapmarcus** [comment]
> This is probably a problem with
> 
> ```shell
> syshealth_adapt_hestia_nginx_listen_ports  # Adapt port listing
> ```
> 
> on hestia-nginx.postinst

It is not new so it should be fine..

**Comment by robsonek** [comment]
```shell
Unpacking hestia-nginx (1.27.0) ...
Setting up hestia-nginx (1.27.0) ...
dpkg: error processing package hestia-nginx (--configure):
 installed hestia-nginx package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-nginx
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@hst:/usr/sbin# cat policy-rc.d
#!/bin/sh
exit 0
``` 

Still the same error.

**Comment by Skamasle** [comment]
```
+ cmp --silent /usr/local/hestia/nginx/conf/nginx.conf /tmp/nginx.conf
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 9318
```
If you coment this, and remove hestia-nginx and install it again postint not fail, in any case, you got error, but all works fine

-> https://github.com/hestiacp/hestiacp/blob/ae823946e920f99deead0bcd64d040838a4cf029/func/syshealth.sh#L631


```
cmp $NGINX_BCONF $NGINX_BCONF_TEMP
differ: byte 5274, line 119


diff $NGINX_BCONF $NGINX_BCONF_TEMP
119c119
< #		listen              [::]:8083 ssl;

> 		listen              [::]:8083 ssl;
```



So, this fail because installer enable IPV6 here:

```
        NGINX_BCONF="/usr/local/hestia/nginx/conf/nginx.conf"
        NGINX_BCONF_TEMP="/tmp/nginx.conf"
        cp "$NGINX_BCONF" "$NGINX_BCONF_TEMP"
        if [ -z "$ipv4_scope_global" ]; then
                sed -i 's/^\([ \t]*listen[ \t]*[0-9]\{1,5\}.*\)/#\1/' "$NGINX_BCONF"
        else
                sed -i 's/#\([ \t]*listen[ \t]*[0-9]\{1,5\}.*\)/\1/' "$NGINX_BCONF"
        fi
        if [ -z "$ipv6_scope_global" ]; then
                sed -i 's/^\([ \t]*listen[ \t]*\[\:\:\]\:[0-9]\{1,5\}.*\)/#\1/' "$NGINX_BCONF"
        else
                sed -i 's/#\([ \t]*listen[ \t]*\[\:\:\]\:[0-9]\{1,5\}.*\)/\1/' "$NGINX_BCONF"
        fi

```

**Comment by Skamasle** [comment]
OK I check the code and "the problem" is just because the default  nginx.conf in hestia-nginx.deb have IPV6 Enabled

So
`                listen              [::]:8083 ssl;`

If server have IPv6 OFF the `syshealth_adapt_hestia_nginx_listen_ports()` just return 1 and post install exit with code 1

So, this just give a warning in a log, but not affect hestia-nginx package at all, so package is installed in the server, log show error but all works fine.

This issue not have easy solution, I try force` syshealth_adapt_hestia_nginx_listen_ports()` to exit with code 0 but if dpkg detect one element in syshealth.sh than returns 1 it just report it as error.

I cant found easy solution for this:

```
dpkg: error processing package hestia-nginx (--configure):
 installed hestia-nginx package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-nginx
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

You can confirm this issue, just delete 

`cmp --silent "$NGINX_BCONF" "$NGINX_BCONF_TEMP"
`
of change it for

`cmp --silent "$NGINX_BCONF" "$NGINX_BCONF_TEMP" || true

And you can install hestia-nginx just without erros.

If you have ipv6 you not get error but if you not have IPV6, you just get error in a log, but this not have any efect in hestia-nginx package.

And I cant find any solution because **cmp --silent "$NGINX_BCONF" "$NGINX_BCONF_TEMP** always return 1 if you not have IPv6 and dpkg with this 1 show you this: **script subprocess returned error exit status 1**
`

**Comment by Skamasle** [comment]
Forget to say, this problem affects in same way debian 12 and other ubuntu versions.

```
The following NEW packages will be installed:
  hestia-nginx
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3491 kB of archives.
After this operation, 0 B of additional disk space will be used.
Selecting previously unselected package hestia-nginx.
(Reading database ... 46672 files and directories currently installed.)
Preparing to unpack .../hestia-nginx_1.27.0_amd64.deb ...
Unpacking hestia-nginx (1.27.0) ...
Setting up hestia-nginx (1.27.0) ...
dpkg: error processing package hestia-nginx (--configure):
 installed hestia-nginx package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 hestia-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@hestia:/# cat /etc/debian_version 
12.6
```

**Comment by jaapmarcus** [comment]
Issue was caused by the cpm check. Removed it should be working fine
