### ISSUE TITLE
[Feature] Update Laravel template to version 11

### ISSUE THREAD

**Issue by Eboubaker** [hestiacp/hestiacp#4525]
### Describe the feature or change in detail

please Update Laravel template to version 11

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Are there any changes to Laravel 11 for Nginx?

I am using it without any issues at the moment

**Comment by Eboubaker** [comment]
![image](https://github.com/user-attachments/assets/e664ec88-26f1-4cdd-91a4-eba16e96fc77)

The Quick install app has Laravel 10.x while laravel 11.x is released very long ago

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4526

**Comment by jaapmarcus** [comment]
Fixed

**Comment by Eboubaker** [comment]
> Fixed

Thank you!
