### ISSUE TITLE
Server fails if not running on static IP

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#453]
On occasion, a Hestia server will fail to start apache or nginx on boot due to an IP address change if the server for some reason is using DHCP. The server should detect the use of DHCP on boot and update the configuration's IP address as necessary/required.

**Comment by JOduMonT** [comment]
but having a server using a DHCP isn't very sketchy; I means, I might be too old school but a server should always have a static IP even if it's reserved through the DHCP server.

**Comment by ghost** [comment]
You're correct on that @JDmnT, however there are cases where the server may for whatever reason be using DHCP to obtain an IP address and would be great to prevent unexpected issues after reboot.

**Comment by ScIT-Raphael** [comment]
Infact DHCP is unusual for servers, I'll close this issue for now.
