### ISSUE TITLE
[Feature] Lib and bash folders

### ISSUE THREAD

**Issue by sheheryarumair-bs** [hestiacp/hestiacp#4553]
### Describe the feature or change in detail

I was going through your codebase. I was wondering when you chroot and create a folder for domain, where are you copying the necessary files like /bin /lib /lib64 to the concerned folder.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by divinity76** [comment]
I don't actually know but seems it's handled automagically by jailkit/jk_init: https://github.com/hestiacp/hestiacp/blob/0599d144faa4d91d20f11057eb374ba6246fff98/bin/v-add-user-ssh-jail#L69
