### ISSUE TITLE
Feature Request: Make AWstat an option during install and its hide elements

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#457]
### In a few words, please describe the issue that you're experiencing:
Allow awstats to be an option during install, but leave it default to install.

Hide the awstats elements on the web interface if not installed

-Web listing Statistics column
-Add/Edit Web Domain Web Statistics

**Comment by ScIT-Raphael** [comment]
Until now, we can't find enough time to develop and fullfill all feature request. I'll close this request for now,   if someone would like to do it on their own, just push a pull request - we will be happy for every contribution.
