### ISSUE TITLE
[Feature] I can't log in as a hestiacp administrator. 

### ISSUE THREAD

**Issue by park3465** [hestiacp/hestiacp#4576]
### Describe the feature or change in detail

I can't log in as a hestiacp administrator. 

The first time I logged in as an administrator and set up a user, I checked "Do not allow user to log in to Control Panel".
 I think this part is the problem.
Please tell me how to fix it.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/can-not-login-admin-access-after-enable-do-not-allow-user-to-log-in-to-control-panel/5375
