### ISSUE TITLE
[Feature] Allow Cpanel import from URL

### ISSUE THREAD

**Issue by kalungia** [hestiacp/hestiacp#4589]
### Describe the feature or change in detail

At the moment `v-import-cpanel`  allows to import from local file, it will be better if it can allow import from a url

https://github.com/Skamasle/sk-import-cpanel-backup-to-vestacp/issues/21

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
As it uses https://github.com/Skamasle/sk-import-cpanel-backup-to-vestacp/issues/21  99 % of it I don't see a reason to change it. It still requires to be downloaded first

**Comment by kalungia** [comment]
For those that use Whmcs it makes a difference

**Comment by jaapmarcus** [comment]
If https://github.com/Skamasle/sk-import-cpanel-backup-to-vestacp/issues/21 has been added it can be back ported how every you can just export to remote server via cpanel / whcms  via scp 

Have migrated 2 server last week
