### ISSUE TITLE
PHP-FPM Templates interfere with http://domain.ext/phppgadmin/

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#459]
### In a few words, please describe the issue that you're experiencing:
I created another Hestia Server and used owncloud template, I noticed the /phppgadmin/ is missing all its css and js, if I change the php-fpm template back to default it works.

![Screenshot from 2019-06-29 17-53-04](https://user-images.githubusercontent.com/1812594/60389830-fd7b5100-9a96-11e9-8413-ef0c23bc5924.png)

### What steps did you take when the issue occured? 
1. Switch php-fpm Template to owncloud
2. Goto domain.ext/phppgadmin/ 

### Expected behavior:
The template should not interfere with phppgadmin 

### Operating system distribution and release:
Ubuntu 18.04.2 LXC/Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.1

### Which branch are you using?
release

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- MySQL (MariaDB)
- PostgreSQL

### In order to better assist, please post any relevant log information below:
N/A

### Related issues or forum threads:
N/A

### Additional notes:
This may be affecting others if installed phpmyadmin roundcube etc

**Comment by ghost** [comment]
Are you able to reproduce this with any of the other PHP-FPM templates as well, or is this restricted to ownCloud's template?

**Comment by johnnyq** [comment]
I just tested all nginx templates, below is a list of the problem templates

- drupal6
- drupal7
- drupal8
- no-php
- owncloud

Also these seems to also affect /phpmyadmin as well.

**Comment by ioannidesalex** [comment]
It's normal for no-php to have issues with phpMyAdmin et al.

Regarding the others - I guess we need to review and update them (not only those but all of them).

**Comment by ghost** [comment]
Thanks @johnnyq, we'll review the templates prior to shipping 1.1.0. :)

**Comment by ghost** [comment]
@johnnyq,

Can you please confirm if this issue is resolved by testing a build from **bugfix-pgadmin**?

**Comment by johnnyq** [comment]
@kristankenney I am super sorry i am late at testing this, but its still doing the same thing. I will try to keep up with testing

**Comment by johnnyq** [comment]
I did some more testing it works if I switch to owncloud on the rootdomain for example test.com/phppgadmin. But if I switch to owncloud template on a subdomain for example pizza.test.com/phppgadmin its the same error as in the OP. Also it appears phpmyadmin does not work either for either root domain or any subdomains that have the owncloud template set
