### ISSUE TITLE
Updates Page not reflecting installed versions of PHP or Nginx

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#460]
### In a few words, please describe the issue that you're experiencing:
I noticed nginx 1.17.1 is installed and php 7.3.6 but the vesion in updates says nginx 1.16.0 and php 7.3.4

![vers](https://user-images.githubusercontent.com/1812594/60389926-21d82d00-9a99-11e9-9100-206fbcaa74d5.png)

### What steps did you take when the issue occured? 
1. Click Server
2. Click Updates

### Expected behavior:
Versions should show version that are installed

### Operating system distribution and release:
Ubunu 18.04.2 LXC / Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.1

### Which branch are you using?
release

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ghost** [comment]
This is partially due to an error in the packaging system I'll get this sorted out and shipped for v1.0.2.

Also note, these packages are only Hestia's internal use -- the front-end nginx process is separate and can be a different version.
