### ISSUE TITLE
[Bug] The site appears as blocked, but in the panel it is actually unblocked.

### ISSUE THREAD

**Issue by ctiger** [hestiacp/hestiacp#4608]
### Describe the bug

The site is shown as blocked, but in the panel it is actually unblocked.
![WEB-server1-msonline-ru-Hestia-Control-Panel](https://github.com/user-attachments/assets/dc4a69b9-8a37-4165-acbe-a38ae658c515)
![Access-Denied](https://github.com/user-attachments/assets/170eba3e-8640-454f-99eb-4c9255d8a8f8)

### Tell us how to replicate the bug

Repeated blocking and unblocking does not help.

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.8.12

### Operating system

Ubuntu 22.04

**Comment by ctiger** [comment]
I tried to unlock it via ssh - it gives the following:

```
root@server1:/usr/local/hestia/bin# v-unsuspend-domain vusinsk vusinsk.ru
Error: domain vusinsk.ru doesn't exist
```
But this can't be, here is the site - it is displayed in the panel.

**Comment by ctiger** [comment]
Any ideas?

**Comment by jaapmarcus** [comment]
v-rebuild-user?

**Comment by ctiger** [comment]
> v-rebuild-user?

I tried it, it doesn't help

**Comment by jaapmarcus** [comment]
cat /usr/local/hestia/data/users/[user]/web.conf

**Comment by ctiger** [comment]
> cat /usr/local/hestia/data/users/[user]/web.conf

```DOMAIN='vusinsk.ru' IP='62.173.141.135' IP6='' ALIAS='www.vusinsk.ru' CUSTOM_DOCROOT='' CUSTOM_PHPROOT='' REDIRECT='' AUTH_HASH='' AUTH_USER='' REDIRECT_CODE='' FASTCGI_CACHE='no' FASTCGI_DURATION='0s' TPL='default' SSL='yes' SSL_HOME='same' SSL_HSTS='' SSL_FORCE='' LETSENCRYPT='yes' FTP_USER='' FTP_MD5='' FTP_PATH='' BACKEND='PHP-7_4' PROXY='default' PROXY_EXT='jpeg,jpg,png,gif,bmp,ico,svg,tif,tiff,css,js,htm,html,ttf,otf,webp,woff,txt,csv,rtf,doc,docx,xls,xlsx,ppt,pptx,odf,odp,ods,odt,pdf,psd,ai,eot,eps,ps,zip,tar,tgz,gz,rar,bz2,7z,aac,m4a,mp3,mp4,ogg,wav,wma,3gp,avi,flv,m4v,mkv,mov,mpeg,mpg,wmv,exe,iso,dmg,swf' STATS='' STATS_USER='' STATS_CRYPT='' U_DISK='1749' U_BANDWIDTH='0' SUSPENDED='no' TIME='16:55:22' DATE='2024-10-07'```

**Comment by jaapmarcus** [comment]
Try reloading nginx  / apache2?

**Comment by ctiger** [comment]
> Try reloading nginx / apache2?

Wow! Great, it works, thanks. Now I'll know what to do!
