### ISSUE TITLE
[Bug] [Alpha] Cron jobs no longer showing in the UI & none of the cron jobs run

### ISSUE THREAD

**Issue by vdbhb59** [hestiacp/hestiacp#4609]
### Describe the bug

Just as the subject line states.
Cron jobs no longer show in the UI, and none of them run as they are supposed to run.
Edit: I think the restart one runs, and maybe others too, but not getting either recorded, or showing up. Reason I am stating this is, my system automatically goes offline daily, but never comes up. See #4611 for more details.

### Tell us how to replicate the bug

1. Install Alpha version 1.9.0 as mentioned in the [Testing Documentation](https://hestiacp.com/docs/contributing/testing.html)
2. Login and check the Cron Tab under main UI
3. Also, check the panel cron jobs (server/hestiaweb/) for "/var/spool/cron/crontabs/hestiaweb", where the cron jobs are listed (see the cron jobs listed below from this file)
4. Check daily, and none of the cron jobs automatically running at all, ever.

```
MAILTO=""
CONTENT_TYPE="text/plain; charset=utf-8"
*/2 * * * * sudo /usr/local/hestia/bin/v-update-sys-queue restart
10 00 * * * sudo /usr/local/hestia/bin/v-update-sys-queue daily
15 02 * * * sudo /usr/local/hestia/bin/v-update-sys-queue disk
10 00 * * * sudo /usr/local/hestia/bin/v-update-sys-queue traffic
30 03 * * * sudo /usr/local/hestia/bin/v-update-sys-queue webstats
*/5 * * * * sudo /usr/local/hestia/bin/v-update-sys-queue backup
10 05 * * * sudo /usr/local/hestia/bin/v-backup-users
20 00 * * * sudo /usr/local/hestia/bin/v-update-user-stats
*/5 * * * * sudo /usr/local/hestia/bin/v-update-sys-rrd
35 2 * * * sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl
55 3 * * * sudo /usr/local/hestia/bin/v-update-sys-hestia-all
```

![image](https://github.com/user-attachments/assets/6dd627d5-5a50-46c4-8254-5111da624fbf)

![image](https://github.com/user-attachments/assets/6a988267-641f-4270-a2c3-9a75cd2265cc)

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.9.0~alpha

### Operating system

Debian 12 Bookworm Minimal

### Log capture

Unfortunately, there are no logs available. :(
When checked /var/log/cron.log, I can see the following messages repeated every once in a while:

```shell

DATE+TIMEZONE HOST cron[498]: Error: bad username; while reading /etc/cron.d/hestiaweb
```

```shell

DATE+TIMEZONE HOST cron[498]: (*system*hestiaweb) ERROR (Syntax error, this crontab file will be ignored)
```

**Comment by jaapmarcus** [comment]
The don't belong under the admin user any more  that is intended

They have moved to:
https://yyy.xxxxx:8083/edit/server/hestiaweb/
