### ISSUE TITLE
DNS Record Deletion Confirmation wording Incorrect

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#461]
### In a few words, please describe the issue that you're experiencing:
When you delete a DNS Records under a domain the deletion confirmation asks if you want to delete domain #? It should read Are you sure you want to delete "record name"

![del-dns-record](https://user-images.githubusercontent.com/1812594/60390074-2520e800-9a9c-11e9-9071-3b50fc0319d2.png)

### What steps did you take when the issue occured? 
1. Click DNS
2. Click on a domain
3. select a DNS Record and attempt to delete the DNS records

### Expected behavior:
It should read Are you sure you want to delete "record name"?

### Operating system distribution and release:
Ubuntu 18.04.2 LXC / Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.1

### Which branch are you using?
Release

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

**Comment by ghost** [comment]
Thanks for pointing this out @johnnyq, will have fixed in v1.0.2.

**Comment by johnnyq** [comment]
Thanks for fixing things so fast! Im running master on another hestia installation and noticed the wording is correct now, but it still says the ID Number rather than the record name, in which it should be showing record name.
