### ISSUE TITLE
[Bug] Clarify how new users are created. 

### ISSUE THREAD

**Issue by jenslj** [hestiacp/hestiacp#4613]
### Describe the bug

In docs/docs/introduction/best-practices.md there should be added information that Hestia checks the local system user repository for usernames. So if I have my name as the local user, I can’t have that name again in Hestia. 
Since this page clearly states that one should create a user account separate from admin, this information should be added. 

### Tell us how to replicate the bug

Even, when using the CLI to list users, the local users aren’t visible sending the signal that Hestia’s user management system differs from the local OS. 

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.12

### Operating system

Ubuntu 22.04

**Comment by jenslj** [comment]
One could also discuss why Hestia would check this and not differentiate the user systems, but I assume you made the discernment for a good reason.

**Comment by jaapmarcus** [comment]
It is to prevent users create a user named "mail" or www-data  and *** their system ...

**Comment by jaapmarcus** [comment]
Feel free to suggest any changes to the docs. But hestia uses Linux system for user management ...
