### ISSUE TITLE
[Bug] SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by V4M0N0S** [hestiacp/hestiacp#4617]
### Describe the bug

hey, just for your information, on demo.hestiacp.com the SSL is expired since 11.10.2024.

### Tell us how to replicate the bug

1. Go to https://demo.hestiacp.com:8083
2. See the error message.

### Which components are affected by this bug?

Control Panel Backend, Let's Encrypt SSL

### Hestia Control Panel Version

1.8.12

### Operating system

Ubuntu 20.04 (x86_64)

**Comment by jaapmarcus** [comment]
Fixed
