### ISSUE TITLE
Dovecot misconfiguration on Debian 9

### ISSUE THREAD

**Issue by liamdemafelix** [hestiacp/hestiacp#462]
### In a few words, please describe the issue that you're experiencing:

Dovecot fails to authenticate due to duplicate namespaces. `/etc/dovecot/conf.d/15-mailboxes.conf` should be removed, since the namespace is already declared in `/etc/dovecot/dovecot.conf`.

### What steps did you take when the issue occured? 

1. Attempt to login to mail server via RoundCube and external app
2. RoundCube responds with "Connection to storage server failed", external app just fails

### Expected behavior:

Authentication should succeed.

### Operating system distribution and release:

Debian 9 64-bit

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

1.0.3

### Which branch are you using?

release

### Which of the following web server configurations are you using?

Apache + Nginx (default)

### Which of the following server roles are installed on your server?

- Web Server (Apache + Nginx)
- DNS
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)
- PostgreSQL

### In order to better assist, please post any relevant log information below:

`/var/log/dovecot.log`:

```
Jun 30 09:22:11 imap(<email snipped>): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
```

### Additional notes:

This is already fixed on my setup after some troubleshooting, just wanted to give you a heads-up.

**Comment by ScIT-Raphael** [comment]
Thanks for the issue report, this should have been fixed with the following line in installer: https://github.com/hestiacp/hestiacp/blob/a4558e10ac48ae76d5b9b56656a13242b8340384/install/hst-install-debian.sh#L1492

I will check why it is not working properly and will update you asap.

**Comment by ScIT-Raphael** [comment]
Ok, the sed command didnt worked properly, I pushed a emergency hotfix to the debian installer with the following commit: https://github.com/hestiacp/hestiacp/commit/21a7ed43736c353548444957595976a7f63b5372

As you already wrote, this will fix the dovecot namespace issue, we had the same line already for ubuntu - don't know why we done another way for debian :).

Thanks for your contribution and help!

**Comment by fianbiasa** [comment]
i have problem **Connection to storage server failed.**
Ubuntu 16.04
HestiaCP VERSION='1.0.6'

help me please @ScIT-Raphael

**Comment by ScIT-Raphael** [comment]
Please reopen a new issue report and send us as mich information as possible, including the logs - you'll find all points on the issue template.

**Comment by fianbiasa** [comment]
@ScIT-Raphael : oke done sir...
https://github.com/hestiacp/hestiacp/issues/620
