### ISSUE TITLE
[Feature] Problem with admin@sub.domain.com, info@sub.domain.com email addresses.

### ISSUE THREAD

**Issue by endrepavel** [hestiacp/hestiacp#4629]
### Describe the feature or change in detail

Hi,

I use a lot of subdomains and the generated email address is [admin|info]@sub.domain.com. But this is not correct for mailing. The valid address would be admin@domain.com.

Can you add a "Use main or parent domain" under "Add|Edit Web Domain" to use for emails?

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
A subdomain for mailing is in my point of view valid. Doesnt matter if it is domain.com or sub.domain.com. Beside that, I do not see any big advantage of that chechbox, its a really specific use case.

**Comment by endrepavel** [comment]
We have order.domain.com, depo.domain.com, audit.domain.com, partner.domain.com, premium.domain.com, tasks.domain.com, b2b.domain.com, connect.domain.com, comment.domain.com, but they all have the @domain.com email address.

**Comment by jaapmarcus** [comment]
You don't need to enable mail for that subdomains ... You can just create them only as web..

**Comment by endrepavel** [comment]
Yes, but the admin@ (php-fpm template) and info@ (letsencrypt script) email addresses are still wrong.
php-fpm template:
`php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@sub.domain.com`

When we send a "password reset" email from our php application, we get this message:
```
10:42:38 1tCyHG-00AqNv-1v <= admin@sub.doamin.com U=xx P=local S=1054
10:42:39 1tCyHG-00AqNv-1v ** gxxx.lxxx@gmail.com R=dnslookup T=remote_smtp H=gmail-smtp-in.l.google.com [74.125.133.27] X=TLS1.3:ECDHE_X25519__ECDSA_SECP256R1_SHA256__AES_256_GCM:256 CV=yes: SMTP error from remote mail server after pipelined end of data: 550-5.7.26 Your email has been blocked because the sender is unauthenticated.\n550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM.\n550-5.7.26\n550-5.7.26  Authentication results:\n550-5.7.26  DKIM = did not pass\n550-5.7.26  SPF [sub.domain.com] with ip: [1.2.3.4] = did not pass\n550-5.7.26\n550-5.7.26  For instructions on setting up authentication, go to\n550 5.7.26  https://support.google.com/mail/answer/81126#authentication 5b1f17b1804b1-432dac33c1csi56691665e9.189 - gsmtp
```
I created custom templates, so it's fine. And we're moving from sendmail to phpmailer.
