### ISSUE TITLE
v-update-sys-queue disk - PostgreSQL Disk stats not updating 

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#463]
### In a few words, please describe the issue that you're experiencing:
I noticed today posgreSQL Diskstats have stayed 0MB, I temmpted to rerun v-update-sys-queue to force the update, but still 0MB

### What steps did you take when the issue occured? 
1. Create PostgreSQL DB greater than 1MB
2. Run v-update-sys-queue via the command line as root or sudo

### Expected behavior:
Disk Column should be larger than 0MB

### Operating system distribution and release:
Ubuntu 18.04.2 LXC/Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.1

Release

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- MySQL (MariaDB)
- PostgreSQL

**Comment by johnnyq** [comment]
it looks like this file does the actual calculating of disk of the DB v-update-database-disk there are references to pgsql in there, ill skim through the code to see if anything stands out

**Comment by ScIT-Raphael** [comment]
Sound good, any help is appreciated!

**Comment by Lupul** [comment]
@johnnyq any luck finding what's wrong with this?
The code for reading pgsql database size is here : 
https://github.com/hestiacp/hestiacp/blob/455cacec1c712a12481e4c3d9052340c397a2891/func/db.sh#L421-L435

**Comment by johnnyq** [comment]
Sure thing @Lupul Thanks for pulling the source. I forgot about this issue. i'll go through it sometime in the afternoon and see what I can find

**Comment by johnnyq** [comment]
Hi @Lupul it looks like its working now! i'm not even sure what update fixed this but its working now! I'm pretty sure this can be closed

**Comment by ScIT-Raphael** [comment]
Hi @johnnyq, thanks, going to close the issue.
