### ISSUE TITLE
[Bug] PhpMyAdmin config file and tmp directory ownership are incorrect

### ISSUE THREAD

**Issue by shiwildy** [hestiacp/hestiacp#4633]
### Describe the bug

config files ownership in /etc/phpmyadmin/config.inc.php is incorrect so it cannot be read by webserver

Error:
![image](https://github.com/user-attachments/assets/d10027d5-e2a4-4eaf-9c3e-bc4f1cae6bd3)

Directory ownership for phpmyadmin tmp is incorrect

Error:
![image](https://github.com/user-attachments/assets/df8e4095-363e-437c-a51d-c9c9235e5da0)

Solution:
```bash
chown -R root:www-data /usr/share/phpmyadmin/tmp/
chown -R root:www-data /etc/phpmyadmin/config.inc.php
```

### Tell us how to replicate the bug

-

### Which components are affected by this bug?

Control Panel Web Interface, Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.8.12

### Operating system

Debian 12

### Log capture

```shell
root@test:/etc/phpmyadmin# ls -lh
total 8.0K
drwxr-x--- 2 root hestiamail 4.0K Nov 21 14:39 conf.d
-rw-r----- 1 root hestiamail  980 Nov 21 14:39 config.inc.php
root@test:/etc/phpmyadmin#
```

**Comment by jaapmarcus** [comment]
👍🏻  Will merge when test are done
