### ISSUE TITLE
[Suggestion] Add my curated IPSet & Spamassasin list

### ISSUE THREAD

**Issue by vdbhb59** [hestiacp/hestiacp#4636]
### Describe the feature or change in detail

Currently I keep updating my own eMails & IP blocks (sources are from my different email spams, received daily on various email providers). I regularly update them, and as I mention, I would like to have those added to your list.

I use HCP myself, so it would be beneficial to add it. Kindly let me know how to go about it?

The list can be found at:

[IP](https://git.flossboxin.org.in/vdbhb59/hosts/raw/branch/main/ip_spamlist.txt)
[eMail](https://git.flossboxin.org.in/vdbhb59/hosts/raw/branch/main/email%20spamlists)

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
There are email address that on the blacklist that supposed to be save for example: noreply@email.apple.com and so on. 

I am not really fine with the idea to include a random source that handles blocking email

**Comment by vdbhb59** [comment]
I mentioned both email and IP. The block happens worldwide that way as well. It is not just a random source there too. How else does the world blocks happen? They get the sources like this only. I even submit these emails to various spam checking orgs, example SPAMBEE.
