### ISSUE TITLE
Uploads to sites are not being calculated into Bandwidth stats

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#464]
### In a few words, please describe the issue that you're experiencing:
I use Nextcloud on one of my instances of hestiaCP and noticed uploading was not being calculated into bandwidth, just the download. 

### What steps did you take when the issue occured? 
1. Create Web Domain
2. install some sort of script to upload files like nextcloud
3. Upload some file using the uploader script for that web domain
4. Run /usr/local/hestia/bin/v-update-sys-queue traffic
5. Check the stats again under web listing

### Expected behavior:
Upload bandwidth should be taken in consideraton as well.

### Operating system distribution and release:
ubuntu 18.04.2 LXC/Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.1

### Which branch are you using?
Please enter your response here (e.g master, develop, etc.)

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- MySQL (MariaDB)
- PostgreSQL

**Comment by ghost** [comment]
@johnnyq, is this still happening for you on 1.2.0?

**Comment by johnnyq** [comment]
@kristankenney I will test and on a new install and report back

**Comment by johnnyq** [comment]
@kristankenney On a new install on Ubuntu 20.04 HestiaCP 1.2, created a domain installed nextcloud on it. Uploaded a 400MB file and ra /usr/local/hestia/bin/v-update-sys-queue traffic. It did not change the bandwidth number. It appears its still only calculating downloads and not uploads

**Comment by johnnyq** [comment]
im wondering if bandwidth should be split into 2 separate categories upload bandwidth and download bandwidth and maybe a total column. just throwing some ideas out there

**Comment by jaapmarcus** [comment]
I don't think Apache/Nginx file uploads are registered/logged on default

**Comment by johnnyq** [comment]
ahh that
 makes sense I never noticed that in the logs

**Comment by ghost** [comment]
Thanks for following up @johnnyq, I'll take a look.

**Comment by jaapmarcus** [comment]
As for normal usage the upload from user to server is really low this shouldn't be issue. Except for "Nextcloud" instances.  

Will close the issue as there is probably no need for implementing it.
