### ISSUE TITLE
[Bug] Error 500 in file manager

### ISSUE THREAD

**Issue by MaxiZamorano** [hestiacp/hestiacp#4643]
### Describe the bug

When upgrading or installing on a new server with HestiaCP v1.9.0~beta the file manager breaks showing a 500 error.
Log `/var/log/hestia/nginx-error.log`

```
2024/11/26 19:11:20 [error] 938#0: *44 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: Session has not been set. in /usr/local/hestia/web/fm/vendor/symfony/http-foundation/Request.php:763
Stack trace:
#0 /usr/local/hestia/web/fm/backend/Services/Session/Adapters/SessionStorage.php(62): Symfony\Component\HttpFoundation\Request->getSession()
#1 /usr/local/hestia/web/fm/backend/Services/Session/Adapters/SessionStorage.php(29): Filegator\Services\Session\Adapters\SessionStorage->getSession()
#2 /usr/local/hestia/web/fm/backend/App.php(33): Filegator\Services\Session\Adapters\SessionStorage->init()
#3 /usr/local/hestia/web/fm/dist/index.php(50): Filegator\App->__construct()
#4 {main}
  thrown in /usr/local/hestia/web/fm/vendor/symfony/http-foundation/Request.php on line 763" while reading response header from upstream, client: [IP], server: _, request: "GET /fm/ HTTP/2.0", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "[IP_SERVER]:8083", referrer: "https://[IP_SERVER]:8083/list/server/"
```

Also, for new installations the file manager is enabled by default only if the administrator user is `admin`, if it is not `admin` you have to enable the file manager from plugins but it shows an error and is not enabled (attached screenshot).

### Tell us how to replicate the bug

1. Click on file manager and it will show error 500
2. To check the error if the administrator is not admin go to Server setting > Configure > Plugins > File manager: yes and Save.

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

v1.9.0~beta

### Operating system

Ubuntu 22.04 and Debian 12.8

### Log capture

```shell
https://i.imgur.com/9rPZ8nl.png
```

**Comment by jaapmarcus** [comment]
Issue was caused by a dependency have reverted it...
