### ISSUE TITLE
[Bug] File manager language

### ISSUE THREAD

**Issue by jekasumy** [hestiacp/hestiacp#4644]
### Describe the bug

Problem with changing language in file manager

### Tell us how to replicate the bug

Everything worked out. It works as it should.

There is a problem with the file manager language. As I understand it, the language should be set depending on which one the user has installed.

The panel has Ukrainian, but the file manager is in English.

I tried changing the parameter in configuration.php:

if (!empty($_SESSION["language"])) {
$lang = $_SESSION["language"];
} elseif (!empty($_SESSION["LANGUAGE"])) {
$lang = $_SESSION["LANGUAGE"];
} else {
$lang = "ru";
}

It didn't help. What should I do?
I added a Ukrainian translation to filegator in github.
At the moment, the problem is that when I force the language to ru, nothing happens. The language remains English.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

v1.9.0~beta

### Operating system

Debian 12

**Comment by jaapmarcus** [comment]
For the translations in Filegator easiest method is:
https://github.com/filegator/filegator/tree/master/frontend/translations

And make the changes there when it added we can fix it here

**Comment by jekasumy** [comment]
> For the translations in Filegator easiest method is: https://github.com/filegator/filegator/tree/master/frontend/translations
> 
> And make the changes there when it added we can fix it here

I am a system administrator, not a developer) Unfortunately, I don't have much experience working with git in terms of `development.`
I added the language here https://github.com/filegator/filegator/pull/502
--
But why then, when forcibly installing the Russian language, does the file manager still remain in English?

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4646 for fix that will work

**Comment by jaapmarcus** [comment]
$_SESSION['lang'] is always to uk or the language you set in Hestia

**Comment by jekasumy** [comment]
> #4646 for fix that will work

I fixed everything)
https://github.com/filegator/filegator/pull/502/commits/7df2ddbed407a65145a877abe4f0f8e1203797ca

**Comment by alcalbg** [comment]
Ukrainian language is now added in filegator v7.11.1
https://github.com/filegator/filegator/releases/tag/v7.11.1
