### ISSUE TITLE
[Bug] Jail is not created when creating a new user

### ISSUE THREAD

**Issue by jekasumy** [hestiacp/hestiacp#4645]
### Describe the bug

Hello

When creating a new user with a certain package, jails are not created by default for the user

Everything is configured in the package. Jail is enabled
Creation (v-add-user-ssh-jail) only works when switching to a user on another package. Then I install the desired one back.

This happens on all packages.

### Tell us how to replicate the bug

1. Create a package with all jail restrictions (jail restrictions checkbox)
2. Create a new user and apply this package to it
As a result, you will see that it was not applied. It only works when switching to another and back.

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

v1.9.0~beta

### Operating system

Debian 12

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/4646 for the fix that will work..

**Comment by jaapmarcus** [comment]
Can confirm the issue

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4669
