### ISSUE TITLE
[Bug] Install multi php

### ISSUE THREAD

**Issue by jekasumy** [hestiacp/hestiacp#4650]
### Describe the bug

Hello. The PHP installer stopped working.

Error in the logs:

This applies to all versions of PHP. Only PHP 8.3 was installed.

### Tell us how to replicate the bug

v-add-web-php 5.6

### Which components are affected by this bug?

Control Panel Installation or Upgrade

### Hestia Control Panel Version

v1.9.0~beta1

### Operating system

Debian 12

### Log capture

```shell
v-add-web-php 5.6
sed: -e expression #1, char 17: unknown command: `/'
Installing PHP-5.6, please wait...
-
ERROR: Installation failed, please run the following command manually for debugging:
apt-get install
cp: cannot create regular file '/etc/php/5.6/fpm/pool.d/': No such file or directory
sed: can't read /etc/php/5.6/fpm/pool.d/dummy.conf: No such file or directory
cp: cannot create regular file '/etc/php/5.6/fpm/': No such file or directory
sed: can't read /etc/php/5.6/fpm/php-fpm.conf: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
sed: can't read /etc/php/5.6/cli/php.ini: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
sed: can't read /etc/php/5.6/fpm/php.ini: No such file or directory
```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4651

**Comment by jekasumy** [comment]
> #4651
Do you confirm the problem? This is a clean install of the latest beta version. There were no problems with PHP in the alpha version. How can I fix it?

**Comment by jaapmarcus** [comment]
It was caused by the check to remove php8.4-imagick module 

It has been removed as it is not needed any more

**Comment by jekasumy** [comment]
> Это было вызвано проверкой на удаление модуля php8.4-imagick
> 
> Он был удален, так как больше не нужен.

This does not install any version of PHP. Neither 5.6 nor 7.3 or 7.4. It is impossible to install at all.

**Comment by aktolu** [comment]
Same problem for me

I install new machine 2 times, v1.9.0~beta1 doesn't install php versions except 8.3 and 8.4. On control panel, looks like installed but it's not. I search all files on my server, doesn't have files like php5*, php7*, php8.0*, php8.1*, php8.2*

server: ubuntu 24.04 LTS
