### ISSUE TITLE
[Feature] Hostname in 'FROM NAME' in Email Alerts sent by Hestia

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#4657]
### Describe the feature or change in detail

So in general when an email alert is sent by Hestia, the 'From Name' on it is "**Hestia Control Panel**" <xxx@hostname>
Can we instead replace the 'Name' with hostname, that will let admins with quite many servers identify faster which server the mail is coming from. 

For example, I have about 150+ server with Hestia and get daily alerts from 3 or 4 servers, I have to look closely the 'from email' to identify which server it came from. If the 'FROM NAME' included the Hostname, it would be much more efficient to spot which server was the alert coming from.

Thanks

### Would you like to sponsor this feature to have it implemented?

No

**Comment by hestiacn** [comment]
That's a good suggestion!

**Comment by jaapmarcus** [comment]
It looks like it is allready changed in 1.9

https://github.com/hestiacp/hestiacp/blob/05493b5cc4fc888c0ee31344613de675fc9016f7/web/inc/mail-wrapper.php#L28-L35
