### ISSUE TITLE
[Bug] grep: /usr/local/hestia/data/users//cron.conf: No such file or directory

### ISSUE THREAD

**Issue by mdlaat** [hestiacp/hestiacp#4665]
### Describe the bug

Since applying [this patch](https://github.com/hestiacp/hestiacp/pull/4622) I occasionally (not daily) get an error in the mail from cron:
`From: root@{hostname} (Cron Daemon)
Subject: Cron <admin@{hostname}> sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl

grep: /usr/local/hestia/data/users//cron.conf: No such file or directory
grep: /usr/local/hestia/data/users//cron.conf: No such file or directory
`

### Tell us how to replicate the bug

replaced v-update-letsencrypt-ssl with the one from the patch

### Which components are affected by this bug?

Control Panel Command Line Interface, Let's Encrypt SSL

### Hestia Control Panel Version

1.8.12

### Operating system

22.04.5 LTS (Jammy Jellyfish)

**Comment by jaapmarcus** [comment]
It is caused by:
```
# Adding LE autorenew cronjob
if [ -z "$(grep v-update-letsen "$HESTIA/data/users/$ROOT_USER/cron.conf")" ]; then
	min=$(generate_password '012345' '2')
	hour=$(generate_password '1234567' '1')
	echo "$min $hour * * * sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl" > /etc/cron.d/hestiaweb
fi
```
