### ISSUE TITLE
Bugfix: /etc/nginx/conf.d/hestia.conf not deleted after upgrade

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#467]
### In a few words, please describe the issue that you're experiencing:
File /etc/nginx/conf.d/hestia.conf is not deleted after upgrade, even though it's empty

### What steps did you take when the issue occured? 
Upgraded from 0.98x to 1.0.1

### Expected behavior:
Should have been deleted

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.0.1

### Which branch are you using?
release

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
https://github.com/hestiacp/hestiacp/commit/08e47db5826a8a4105140322021f3e18bfe61050
