### ISSUE TITLE
[Feature] Change control panel language automatically according to visitor's browser language/env variables

### ISSUE THREAD

**Issue by ozgurkazancci** [hestiacp/hestiacp#4679]
First of all, many thanks to all HestiaCP dev team for such a great work&effort! Much respect!

Automatically setting the language of HestiaCP administration page according to visitor's browser language/env variables would be a good feature, imho.

Regards.

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/auto-language-of-hestiacp-administration-page/17037

So currently the "default" setting is:

User setting ( When logged in) 
Server setting (Logged out of user not set)
And then fall back to English... 

I don't see what advantage is to also auto detect it. I often use Dutch browsers but prefer to have server running English...

And for only the login page I don't see the use case for it....
