### ISSUE TITLE
Feature Request: Add checkbox Deny WebCrawlers under Add Web Domain

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#468]
### In a few words, please describe the issue that you're experiencing:
This would create a robots.txt file and deny all robots. This would be useful for private applications that should not be indexed or scanned.

**Comment by johnnyq** [comment]
robots.txt Content

User-agent: *
Disallow: /

**Comment by ScIT-Raphael** [comment]
I think a user can implement a file on its own - so I think a checkbox for a robots.txt file would be a bit to much. I will anyway check if a implementation is possible due to the www rewrite we want to do, I'll close this issue for now.
