### ISSUE TITLE
[Bug] Invalid self-signed SSL Certificate

### ISSUE THREAD

**Issue by mawaki** [hestiacp/hestiacp#4688]
### Describe the bug

When generating self-signed SSL certificate, the domain leads to `Invalid SSL certificate`. But everything works well when using Let's Encrypt. 

We tried on different instances and we had the same issue.

### Tell us how to replicate the bug

1. Navigate to user
2. Edit a domain
3. Enable SSL for this domain then click on `Generate Self-Signed SSL Certificate`
4. Fill the form and copy the generated SSL to the certificate input forms
5. Save and visit the domain

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.9-Beta1

### Operating system

Ubuntu 24

**Comment by jaapmarcus** [comment]
self gererated ssl certificates are not valid and still need to be manually approved by the user

**Comment by jaapmarcus** [comment]
<img width="534" alt="Screenshot 2024-12-23 at 00 40 25" src="https://github.com/user-attachments/assets/db6eb8ee-7300-458d-8e2b-1fc1bb5a78bd" />

If this is the error (Depends on browser) it is expected as self generated are not valid ssl certificates...

**Comment by mawaki** [comment]
Thanks. It was not related to that, but we will use Let's Encrypt instead. Thanks for all the hard work.
