### ISSUE TITLE
[Bug] www.maxmind.com/en/high-risk-ip-sample-list 403 error

### ISSUE THREAD

**Issue by jekasumy** [hestiacp/hestiacp#4691]
### Describe the bug

Hello.

There is an error when starting: /usr/local/hestia/bin/v-update-firewall-ipset yes

Warning: curl returned HTTP response code 403 for URL https://www.maxmind.com/en/high-risk-ip-sample-list

Blacklist added - script:/usr/local/hestia/install/common/firewall/ipset/blacklist.sh

Please pay attention to this, developers.

### Tell us how to replicate the bug

bash /usr/local/hestia/bin/v-update-firewall-ipset yes

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

v1.9.0~beta1

### Operating system

Debian 12

### Log capture

```shell
curl returned HTTP response code 403 for URL https://www.maxmind.com/en/high-risk-ip-sample-list
```

**Comment by jaapmarcus** [comment]
https://www.maxmind.com/en/high-risk-ip-sample-list seems to return an 403 error..

**Comment by ghost** [comment]
MaxMind blocks curl requests with a 403 Forbidden response when no user-agent is specified. For example:

curl -I https://www.maxmind.com/en/high-risk-ip-sample-list

This results in the following error:

![image](https://github.com/user-attachments/assets/60f6166e-028a-477d-908f-dc68ee13fd81)

However, by including a valid user-agent string, you can bypass this restriction and get the expected response:

curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" https://www.maxmind.com/en/high-risk-ip-sample-list

This successfully returns the response:

![image](https://github.com/user-attachments/assets/e27e1729-400e-4d12-b9bf-90270d225548)

**Comment by jekasumy** [comment]
> MaxMind blocks curl requests with a 403 Forbidden response when no user-agent is specified. For example:
> 
> curl -I https://www.maxmind.com/en/high-risk-ip-sample-list
> 
> This results in the following error:
> 
> ![image](https://private-user-images.githubusercontent.com/4235657/398020254-60f6166e-028a-477d-908f-dc68ee13fd81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTEzNzksIm5iZiI6MTczNDkxMTA3OSwicGF0aCI6Ii80MjM1NjU3LzM5ODAyMDI1NC02MGY2MTY2ZS0wMjhhLTQ3N2QtOTA4Zi1kYzY4ZWUxM2ZkODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMjM0NDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc0Y2U5NTU1MGQzY2EzZDgyZmRlNWMyZTcyN2VjNDU0M2JlMWUzOTUwOWEwMjc3NDQzYjFhNDM4MjBiNmIwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.L2hxoG_V9_1YxYrPvYtVA_uZ04uXvlfHnYH9X8aQxUI)
> 
> However, by including a valid user-agent string, you can bypass this restriction and get the expected response:
> 
> curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" https://www.maxmind.com/en/high-risk-ip-sample-list
> 
> This successfully returns the response:
> 
> ![image](https://private-user-images.githubusercontent.com/4235657/398020238-e27e1729-400e-4d12-b9bf-90270d225548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTEzNzksIm5iZiI6MTczNDkxMTA3OSwicGF0aCI6Ii80MjM1NjU3LzM5ODAyMDIzOC1lMjdlMTcyOS00MDBlLTRkMTItYjliZi05MDI3MGQyMjU1NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMjM0NDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGIyODUxNzZmNTMyNjJhMDcyMGVhNzNiMzYwYzFlMjZiZDZiMjc3NmM5NmIwYTkxMjNkNGZjY2U0MDNjODE5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IuWwRh9DFIc-MaZABg0xMWpJiwYnrg8i3_biHzgkvN4)

Will this be fixed in the panel?

**Comment by jaapmarcus** [comment]
I tried that on a test server of mine. I assume they also block it if you use certain ASN numbers... 

Home internet:
```
jaapmarcus@Jaaps-MacBook-Air ~ % curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" https://www.maxmind.com/en/high-risk-ip-sample-list
HTTP/2 200 
date: Sun, 22 Dec 2024 23:48:04 GMT
content-type: text/html; charset=utf-8
cache-control: max-age=14400
```

Server IP:
root@dev:~# curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" https://www.maxmind.com/en/high-risk-ip-sample-list
HTTP/2 403

**Comment by ghost** [comment]
True this blocked me on 4 servers too.
Daamn

**Comment by jekasumy** [comment]
Perhaps it's worth excluding this blacklist and forgetting about the problem)

**Comment by jekasumy** [comment]
Better to add abusedb instead of this non-working one.

**Comment by jaapmarcus** [comment]
Would require to include an api key ... 

https://docs.abuseipdb.com/#test-ip-addresses

**Comment by jekasumy** [comment]
No
https://github.com/borestad/blocklist-abuseipdb

Optimal  60d

**Comment by jaapmarcus** [comment]
Merged

**Comment by ghost** [comment]
Well,

This block occurs because Cloudflare's protection mechanism checks certain IPs and ASNs and get method, and may block access based on these checks.

**Possible Solutions**

![image](https://github.com/user-attachments/assets/f7808fc6-20e9-40b1-acab-e4ff64fbacf9)

A way to bypass this is use curl impersonate https://github.com/lwthiker/curl-impersonate

![image](https://github.com/user-attachments/assets/e1b952d2-aa23-4b17-a6f7-fa6ffb3f319d)

![image](https://github.com/user-attachments/assets/7197cdbb-8c7b-46cf-bc20-7ba64442a43f)

or choose a web proxy with a good reputation that works well with Cloudflare-protected websites.

Or create a script to copy and host IPList in Github and curl from there
