### ISSUE TITLE
[Bug] Wordpress installer fails when generated table prefix starts with a number

### ISSUE THREAD

**Issue by rjd22** [hestiacp/hestiacp#4696]
### Describe the bug

Tables are not allowed to start with a number. So when the random generator accidentally generated a prefix that starts with a number the installation fails. To avoid this we should actually just prefix the prefix with `wp` ;).

Related line:
https://github.com/hestiacp/hestiacp/blob/dbba10c701799010eb22e0745a78b125311e4394/web/src/app/WebApp/Installers/WordPress/WordPressSetup.php#L85

### Tell us how to replicate the bug

1. Run WordPress installer and be the lucky person to generate a prefix with an number.

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.12

### Operating system

Debian 12

**Comment by divinity76** [comment]
do you know exactly where it fails when table prefix is a number?

>To avoid this we should actually just prefix the prefix with wp

sounds good to me

**Comment by divinity76** [comment]
btw
```php
				$result->raw[$line_num] =
					'$table_prefix = \'' .
					addcslashes(Util::generate_string(5, false) . "_", "\\'") .
					"';\r\n";
```
should be
```php

				$result->raw[$line_num] =
					'$table_prefix = ' .
                                        var_export(Util::generate_string(5, false) . "_", true) .
                                        ";\r\n";
```

and
```php
if ('$table_prefix =' === substr($line, 0, 15)) {
```
should be
```php
if (str_starts_with($line, '$table_prefix =')) {
```

**Comment by rjd22** [comment]
> do you know exactly where it fails when table prefix is a number?
> 
> > To avoid this we should actually just prefix the prefix with wp
> 
> sounds good to me

It fails in step 2 when creating the tables.
