### ISSUE TITLE
Security Request: Tighten permissions of /usr/local/hestia/bin

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#470]
All v- scripts have permissions of 775. Is it possible to tighten them without breaking anything?

**Comment by JOduMonT** [comment]
My first observation this would be possible if all user create via HestiaCP are in a special group like hestiacap than

```
chown root:hestia -R /usr/local/hestia/bin
chmod 750 -R /usr/local/hestia/bin
```
would be possible

I'll build a dev hestia container and test this ;)

**Comment by ghost** [comment]
FYI, all users should be contained within the **hestia-users** group beginning with the v1.00.0-190618 build.

**Comment by ghost** [comment]
Heads up, the permissions for $HESTIA/bin will be locked down further starting with the v1.1.0 release.
