### ISSUE TITLE
Security Fix: document_errors permissions

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#471]
I believe that the permissions of document_errors files should be set at 644. No need for 755 for html files.

**Comment by JOduMonT** [comment]
actually since mounting /home, /tmp and /dev/shm with nodev,noexec will secure the webserver against malicious code (malware) which might be uploaded through svg, gif or others executables files.

**Comment by jaapmarcus** [comment]
I just checked the current settings are 

751 

With 644 I get a Document not found warning of Apache2

**Comment by JOduMonT** [comment]
751 = execution for everyone
644 = read for everyone
which is not the same

execute (x) Execute permission on files means the right to execute them if they are programs. (Files that are not programs should not be given the execute permission.) **For directories, execute permission allows you to enter the directory** (i.e., cd into it), and to access any of its files.

**Comment by jaapmarcus** [comment]
HTML files are currently 644 so the issue can be closed then....
