### ISSUE TITLE
Bugfix: Webalizer still installed

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#475]
### In a few words, please describe the issue that you're experiencing:
Webalizer package is still installed, its files are still present in the system.

**Comment by ScIT-Raphael** [comment]
https://github.com/hestiacp/hestiacp/commit/34504a78ea91687f94e7fb86109408250df9f708

**Comment by JOduMonT** [comment]
I think you forgot to remove `/usr/local/hestia/data/templates/web/webalizer` files which are useless now ;)
