### ISSUE TITLE
Bug: UI phpMyAdmin and Webmail icons don't respect the custom set URLs

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#477]
### In a few words, please describe the issue that you're experiencing:
When you change the aliases of phpMyAdmin using script v-change-sys-pma and the one of webmail using script v-change-sys-webmail, these are not changed (or not stored) after an upgrade.

This results the icons in the panel to link to the default aliases.

**Comment by ghost** [comment]
The icons to access webmail should be working on a per-domain basis, however we still need to rework the alias detection for PMA in the UI. 

@ioannidesalex can you please verify with the latest master build on your end if this is still the case?
