### ISSUE TITLE
Issue and Question about Mail service and SSL

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#479]
Hi;

I have few question related to the mail services and one potential issue.

### Questions

1. HestiaCP seams assuming email will be use through mail.domain.tld
While this is mostly true, what is I want to use m.domain.tld or mx.domain.ltd ?

2. HestiaCP, like VestaCP, seams assuming the hostname will be the domain name for the mail server ?

### Potential Issue

I generated a Self-SSL for domain.ltd the mail service tell me to use mail.domain.tld, but I didn't include this subdomain during the generation of the SSL

#### Do HestiaCP manage this or this implicit configuration is explicit ?

I register a subdomain mail.domain.tld which use Let's Encrypt, and my domain.tld still/and will use a self-generated SSL when I look into `/home/USER/conf/mail/DOMAIN.TLD/ssl/` it seams HestiaCP make a copy of my Self-SSL for the mail services but I would like the SSL generated with Let's Encrypt. While with VestaCP I was simply make soft link to I would like your tough about it and how you would manage this situation.

**Comment by ScIT-Raphael** [comment]
Atm, the domain is hardcoded to mail.domain.tld and webmail (set in hestia.conf) for roundcube: https://github.com/hestiacp/hestiacp/blob/a93d021a802cc886c0e7001d27998fa4bdacb277/bin/v-add-letsencrypt-domain#L101

Just edit the mail domain and tick the "let's encrypt" ssl function, it will generate and install the certs properly.

**Comment by JOduMonT** [comment]
hum; from what I understood 
- I remove the web app which was using mail.domain.tld
- than went in my domain.tld under MAIL and request a Let's Encrypt SSL
but it return an error:  → Error: SSL=yes is already exists 
![image](https://user-images.githubusercontent.com/5204724/60558166-6fdb8200-9d72-11e9-8a22-26959c926b58.png)

even if I try to generate a Self-SSL for mail.domain.tld it result the same error

Yes I have a Self Generated SSL but for the main domain (domain.tld)
which don't include mail.domain.tld and I remove the domain mail.domain.tld which yesterday, successfully receive a SSL from Let's Encrypt.

also the dir `/home/admin/conf/mail/domain.tld/ssl/` is empty

note: I didn't edit any config file yet.

**Comment by JOduMonT** [comment]
all good;
It was the beginning so I in MAIL remove the domain and recreate it
now everything is working with a Let's Encrypt SSL

thank for your support and explanation :)
