### ISSUE TITLE
Feature Request: Add Let'sEncrypt hostname certificate autorenew

### ISSUE THREAD

**Issue by Wibol** [hestiacp/hestiacp#480]
Could v-add-letsencrypt-host cli command to add "UPDATE_HOSTNAME_SSL='yes'" to "/usr/local/hestia/conf/hestia.conf" file for certificate autorenew?

**Comment by ScIT-Raphael** [comment]
Already done with the following commit: https://github.com/hestiacp/hestiacp/commit/9308c83a50e3a390286483e0b055fbc46e79ccd4

We will fix missing variables over upgrade.
