### ISSUE TITLE
Add and integrate "recidive" Fail2Ban jail in default instalation

### ISSUE THREAD

**Issue by Wibol** [hestiacp/hestiacp#482]
I'm using in VestaCP the "recidive" Fail2Ban jail for long time ban over recurrent IPs, and it works fine:
```
[recidive]
enabled  = true
maxretry = 3
findtime = 86400
bantime  = 864000
```
But the only way to view banned IPs list is:

`sudo iptables -L`

It would be great to see the list in HestiaCp backend.

**Comment by ScIT-Raphael** [comment]
Added recidive jail with the following commit: https://github.com/hestiacp/hestiacp/commit/e2fe842c19451b03507a6ce2ee0df409d701a515

**Comment by ScIT-Raphael** [comment]
Banned ips are already visible in backend: /list/firewall/banlist/

**Comment by Wibol** [comment]
Thanks.

In VestaCP I had to assign this jail to a free ban category (like DB, DNS or WEB) to view those IPs in backend, because I don't know how to create a new one:
```
[recidive]
enabled  = true
action   = vesta[name=DB]
maxretry = 3
findtime = 86400
bantime  = 864000
```

**Comment by ScIT-Raphael** [comment]
We've already adjusted the code again with later commits: https://github.com/hestiacp/hestiacp/blob/a38c103ecc6daba5fbcd60ceb14ea791f5d6ee78/install/deb/fail2ban/jail.local#L48

**Comment by ioannidesalex** [comment]
You may try this:

[recidive]
enabled  = true
filter   = recidive
action   = hestia[name=HESTIA]
logpath  = /var/log/fail2ban.log
maxretry = 5
findtime = 86400
bantime  = 864000
