### ISSUE TITLE
Bugfix: /usr/local/hestia/data/firewall/chains.conf

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#483]
This file contains hardcoded ports and they are not changed accordingly to firewall rules changes. All in all, what's really the purpose of this file? Very confusing and I am not really sure if firewall rules are propegated correctly.

**Comment by ScIT-Raphael** [comment]
The chain file fill be generated from v-add-firewall-chain, the ports are already dynamically for ssh and backend port.

**Comment by ioannidesalex** [comment]
This file still includes ports that I have chosen to close (delete the respective firewall rules). Shouldn't these be removed from this file as well?

**Comment by ScIT-Raphael** [comment]
No, if you delete the rule, it should not get reloaded again.
