### ISSUE TITLE
Templates PHP-FPM for NGINX

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#488]
while in PHP-72.stpl is: `fastcgi_pass unix:/run/php/php7.2-fpm-%domain%.sock;`
in PHP-73.stpl it's: `fastcgi_pass    %backend_lsnr%;` and cause an error

I believe the right parameter would be `fastcgi_pass unix:/run/php/php7.3-fpm-%domain%.sock;`

**Comment by Lupul** [comment]
The php7.3 template looks good, and it wasn't modified recently
https://github.com/hestiacp/hestiacp/blob/release/install/deb/multiphp/nginx/PHP-73.stpl

**Comment by JOduMonT** [comment]
yep the one of your link is good
I'm sorry; I really don't know from where my template comes from :p

**Comment by JOduMonT** [comment]
Oh! I found why I end with a` fastcgi_pass %backend_lsnr%;`

Because after this [discussion](https://github.com/hestiacp/hestiacp/issues/424) with @ScIT-Raphael 
I copy [php-fpm template](https://github.com/hestiacp/hestiacp/tree/master/install/deb/templates/web/nginx/php-fpm) inside `nginx template` directory then the default template from php-fpm overwrite the default template in nginx template dir which php7.3 point to.

### Obviously I didn't paid attention and
I probably said yes to overwrite the file **but perhaps t might be wise to simply remove default.tpl and default.stpl from php-fpm template directory**

So my question is do hestia think plan to remove default from php-fpm or maintain it properly ?

**Comment by Lupul** [comment]
Currently the plan is to merge php-fpm with multiphp so that you will be able change both PHP version and app template (wordpress, magento, laravel etc) independently,  without the need to manually copy files from php-fpm.

There is no ETA yet, but this feature is at the top of my list.

**Comment by JOduMonT** [comment]
How I may help you on this ?
because I start my own [repo](https://github.com/JDmnT/nginx-templates) without any prevention and obviously my own preference.

**Comment by ScIT-Raphael** [comment]
Atm there is not much to do right now, as @Lupul already wrote we will rework the multiphp implementation. Target should be that you can select the php version in backend and use the default preset templates from php-fpm (instead the php version template). I will close this issue for now, the pull request is already on the way: https://github.com/hestiacp/hestiacp/pull/546
