### ISSUE TITLE
Show server hostname within Control Panel interface for reference

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#490]
Hi Everyone,
As the number of servers grow for admins, I guess it would help and give a more visual appeal if we can show Server's hostname and its Public IP or IPs on the login window itself.  

I had drafted the original idea of showing server hostname on the top bar once you are logged in, so I guess showing server infor on the login window would help as well.

Attached is a mockup for it... Devs please consider this feature

![image](https://user-images.githubusercontent.com/2650395/60684572-15e6d380-9ebc-11e9-86b8-edaf1f3756a2.png)

**Comment by ghost** [comment]
Hi @mehargags, we'll discuss how to best implement the necessary information across the user interface for the next major release.

I agree that we do need some form of indication as to which server you're logged into when handling multiple connections; as I'm sure you've already noticed the server name was removed from the top panel during the user interface redesign due to space constraints and issues with long hostnames.

**Comment by mehargags** [comment]
Hi @kristankenney 
Thanks for the lightning reply :)

Yes I have noticed the hostname is removed from the UI now... my next feature request is coming up with a mockup for how we can adjust it inside.

Practically using... any admin with 10+ servers would benefit from this. I'm sure we all keep bookmarks of our HestiaCP login URLs and it is easy to hit a wrong bookmark and open another server. This would be a good visual demarcation for admins... :)

**Comment by ioannidesalex** [comment]
I strongly disagree with providing ANY private information prior to login (I already debated even for version), having security in mind as top priority. After login feel free to display whatever you want :)

**Comment by mehargags** [comment]
hostname or IP is not an issue of security here @ioannidesalex 
You only see it when you are on the login page, so the IP or the hostname is  **_already_** being displayed wide and clear in your address bar ;)  which means there is nothing "leaked" here by default.

**Comment by ioannidesalex** [comment]
Malicious bots don't use browsers my dear friend @mehargags they use other algorithms to harvest data, especially in case a security hole is discovered. Some admins might masquerade their IP by using a proxy or whatever. No need to reveal anything to unauthorized users.

Just my two cents.

**Comment by johnnyq** [comment]
Maybe make it as an option in the configure server section but by default leave it off

**Comment by ialexpw** [comment]
> 
> 
> Maybe make it as an option in the configure server section but by default leave it off

Similar to this, but maybe have an option within the panel as to what should be displayed. That way it _could_ be the hostname, but can be a custom identifier.

**Comment by ghost** [comment]
We've added the name of the host name that is used during login (HTTP_HOST) to the title to enable easier visual indication of which server you are accessing when flipping through browser tabs with commit 5a0080bb3fdfe5b85b8f4a3fa15c4abc2170f8cc, which will be available with v1.1.0.
