### ISSUE TITLE
Show Server's hostname inside WebUI Top Bar

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#491]
This was there in the previous version but removed in the last June update. I understand the space constraints so I mocked up the below screenshot where we can easily fit under the top bar.

I purposefully took the screenshot on Firewall rules page which is long enough to have as scroll bar and reduces the Menu pane's height. This design should fit fine even when its height is reduced.

Thanks

![image](https://user-images.githubusercontent.com/2650395/60685557-5563ee80-9ec1-11e9-82d0-d1fe5cf11b6b.png)

**Comment by ghost** [comment]
Thanks for the mockup -- I'll close this one for now but have left #490 open and will look at where this information best fits into the design.

**Comment by mehargags** [comment]
Well @kristankenney this one was particularly **more important** than #490 so if you can work this out on priority :)

**Comment by ghost** [comment]
We will determine where this information could be placed within the user interface effectively, however this is not a top priority at this time.

The reason why this is not high priority at this time, is that the host name/IP of the server is located in the browser's standard address bar which can also be used for reference when flipping between multiple servers. While we agree that the hostname should be displayed at least once in the UI for reference, we do not feel that it is necessary to display the same information multiple times which adds clutter (the exact thing that we have been aiming to eliminate from the original UI inherited from Vesta).
