### ISSUE TITLE
Feature Request: Add "ssh" to Server list

### ISSUE THREAD

**Issue by Wibol** [hestiacp/hestiacp#492]
So we can edit /etc/ssh/sshd_config, restart and stop the service from the backend.

**Comment by mehargags** [comment]
+1 for ability to edit sshd_config from within HestiaCP interface. It can be a life saver incase you mess up your SSH config and lose shell access accidentally. It would save much time and hassel if one can login to Hestia WebUI and be able to edit / restore the config and gain shell access again.

However, I'm sure this also means more risk incase your HestiaCP password is compromised or someone with less Linux knowledge tries to play around with SSH config. I guess we should have a vote for this.

**Comment by JOduMonT** [comment]
@mehargags actually if you mess sshd config than you restart the service and it fail you will still have your current session active; so unless you close you session you will still able to correct the file.

of course a backup of the file would be your life saver and/or you could use a tool like etckeeper and implement git in it for a better reliability.

**Comment by ghost** [comment]
SSH has been added to the Services list and allows editing of sshd_config starting in v1.1.0. This does provide an additional point of recovery should you lose shell access, but like editing any service configuration care should be taken along with necessary security practices.
