### ISSUE TITLE
SFTP backup problem

### ISSUE THREAD

**Issue by daffyyyy** [hestiacp/hestiacp#493]
Hi,
When i tried add sftp backup panel throw me "Error Code 1",
https://forum.vestacp.com/viewtopic.php?t=17923 <- this help, but next problem is backup created with sftp can't be downloaded from panel (blank page when click download)
Its possible to make download backup works?

**Comment by ghost** [comment]
Hi @daffyyyy, we're currently aware of the issues with SFTP backup not working as expected and plan on having this fixed up for the v1.1.0 feature release.

**Comment by ScIT-Raphael** [comment]
Should have been fixed with the following commit: https://github.com/hestiacp/hestiacp/commit/09335c8942adb3fedbeddda95ae54051a3ddc44d

@daffyyyy can you check if this change also works on your system? Please let us know if you have any other issues.
