### ISSUE TITLE
PHPx-FPM restart from WebUI > Server tab

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#495]
Can we have all PHPx.x-fpm restart/stop service ability on the Server Tab for WebUI ?
I guess at times you want to restart the FPM, you can do it from hestia without the need to login to shell. For multi-php we should have all FPMs listed.

Thanks

**Comment by Lupul** [comment]
This issue should was fixed in ver 1.1.0
- commit: https://github.com/hestiacp/hestiacp/commit/694806a36f2a482ca443da1e0f2c489c0c60b4b5#diff-0d34f6f888a68f8ac9c5412512b7e3ca

**Comment by mehargags** [comment]
Many thanks
