### ISSUE TITLE
Ability to change root directory for public_html

### ISSUE THREAD

**Issue by hrvylein** [hestiacp/hestiacp#499]
Symfony apps have a public subdirecotry which is the starting point when running these apps.
f.e.

> public_html/
> ├─ assets/
> ├─ bin/
> │  └─ console
> ├─ config/
> ├─ public/
> │  └─ index.php
> ├─ src/
> │  └─ ...
> ├─ templates/
> ├─ tests/
> ├─ translations/
> ├─ var/
> │  ├─ cache/
> │  ├─ log/
> │  └─ ...
> └─ vendor/

To run these apps, you would have to open https://sub.domain.tld/public/.
### Expected behavior:
Possibility to change the web root to another folder inside "public_html" leaving open_basedir on public_html, so that symfony apps can access the cache/vendor/assets/config/etc folders.

### Operating system distribution and release:
Debian 9

### Which version of Hestia Control Panel is currently installed?
latest stable

**Comment by Lupul** [comment]
Hello @hrvylein thanks for your feedback. If I understand correctly Laravel templates might be what you are looking for (if you are using php-fpm):
https://github.com/hestiacp/hestiacp/blob/master/install/deb/templates/web/nginx/php-fpm/laravel.tpl

**Comment by ScIT-Raphael** [comment]
Otherwise you can copy a existing template (for example default.s/tpl) in /usr/local/hestia/data/templates/web/apache2, rename it to symfony.s/tpl and adjust the needed parts inside the template file.

Atm, we do not plan to integrate a customization of the root path in the backend.
