### ISSUE TITLE
Visual Bug: HSTS is Working but checkmark is not sticking

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#510]
### In a few words, please describe the issue that you're experiencing:
I enabled HSTS on one of my existing domains, but noticed when I re-edit the web domain the hsts box is not checked, but I can confirm HSTS is working.

### What steps did you take when the issue occured? 
1. Click Web
2. Pick a domain to edit
3. check enable HSTS

### Expected behavior:
HSTS should remained checked if enabled

### Operating system distribution and release:
Ubuntu 18.04.2 LXC / Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.2
### Which branch are you using?
Release

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ghost** [comment]
Hey @johnnyq, just wanted to let you know that this has been resolved and will be pushed in the next hotfix which we're currently working on.

**Comment by johnnyq** [comment]
Super!! =]
