### ISSUE TITLE
Bug: Error in log files when running v-add-letsencrypt-host

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#515]
When running v-add-letsencrypt-host , the following errors shows up in hestia error log file:

2019-07-09 14:23:11 v-delete-web-domain-ssl  'admin' 'domain.tld' [Error 3]

**Comment by Wibol** [comment]
Does this mean that the script attempts to delete an existing domain to recreate it or only the cert? If the domain contains a website, it could be a disaster.

**Comment by ScIT-Raphael** [comment]
no, it delete the ssl cert if it is a invalid or self signed one.

**Comment by ghost** [comment]
I can confirm this issue is still present in the latest master build for 1.1.0.
