### ISSUE TITLE
https://mail.DOMAIN.EXT not redirecting to https://webmail.DOMAIN.EXT

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#516]
### In a few words, please describe the issue that you're experiencing:
I noticed http://mail.domain.ext is redirecting to https://webmail.domain.ext but not when using https://mail.domain.ext

### What steps did you take when the issue occured? 
1. Goto https://mail.domain.ext in your browser

### Expected behavior:
It should redirect to https://webmail.domain.ext

### Operating system distribution and release:
Ubuntu 18.04.2 LXC/Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.3

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Not sure just noticed

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ghost** [comment]
Thanks for letting us know about this @johnnyq, we'll reproduce it here internally and work on a fix.

**Comment by ghost** [comment]
Roundcube should now be displayed correctly when navigating to the mail domain via HTTPS with the latest master build (with commit bdbfcf47a5d783774308340acc5da70eb21e4a8c), will review further to see what's happening with the direction to the webmail alias prior to shipping out 1.1.0.

**Comment by ghost** [comment]
Hi @johnnyq, is this issue still valid on your end?

**Comment by johnnyq** [comment]
this seems to be solved @kristankenney You can close this
