### ISSUE TITLE
PHP-FPM failed to start directly after update to 1.0.3

### ISSUE THREAD

**Issue by cmstew** [hestiacp/hestiacp#517]
### In a few words, please describe the issue that you're experiencing:
Today I woke up to find that all of my websites were offline. php7.3-fpm failed to start up on it's own and didn't recover until I forced it to restart using the command line.

### What steps did you take when the issue occured? 
1. Hestia updated overnight and now there's something wrong

### Expected behavior:
To keep running as usual

### Operating system distribution and release:
Debian 9.7

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

1.0.3

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Hestia updated from 1.0.1 to 1.0.3 overnight and messed something up.

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Web (no DNS)
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

Here is some of the output of /var/log/syslog:

Jul  9 06:40:01 mail CRON[28686]: (admin) CMD (sudo /usr/local/hestia/bin/v-update-sys-queue backup)
Jul  9 06:40:01 mail CRON[28687]: (admin) CMD (sudo /usr/local/hestia/bin/v-update-sys-rrd)
Jul  9 06:43:01 mail CRON[28984]: (admin) CMD (sudo /usr/local/hestia/bin/v-update-sys-hestia-all)
Jul  9 06:43:09 mail systemd[1]: Reloading nginx - high performance web server.
Jul  9 06:43:09 mail systemd[1]: Reloaded nginx - high performance web server.
Jul  9 06:43:09 mail systemd[1]: Stopping The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:09 mail systemd[1]: Stopped The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:09 mail systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:09 mail systemd[1]: Started The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:10 mail systemd[1]: Reloading nginx - high performance web server.
Jul  9 06:43:10 mail systemd[1]: Reloaded nginx - high performance web server.
Jul  9 06:43:10 mail systemd[1]: Stopping The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:10 mail systemd[1]: Stopped The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:10 mail systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:10 mail systemd[1]: Started The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:10 mail systemd[1]: Stopping The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:10 mail systemd[1]: Stopped The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:10 mail systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:10 mail systemd[1]: Started The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:11 mail systemd[1]: Stopping The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:11 mail systemd[1]: Stopped The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:11 mail systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:11 mail systemd[1]: Started The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:11 mail systemd[1]: Stopping The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:11 mail systemd[1]: Stopped The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:11 mail systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:11 mail systemd[1]: Started The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:11 mail systemd[1]: Stopping The PHP 7.3 FastCGI Process Manager...
Jul  9 06:43:11 mail systemd[1]: Stopped The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:11 mail systemd[1]: php7.3-fpm.service: Start request repeated too quickly.
Jul  9 06:43:11 mail systemd[1]: Failed to start The PHP 7.3 FastCGI Process Manager.
Jul  9 06:43:11 mail systemd[1]: php7.3-fpm.service: Unit entered failed state.
Jul  9 06:43:11 mail systemd[1]: php7.3-fpm.service: Failed with result 'start-limit-hit'.
Jul  9 06:43:11 mail systemd[1]: php7.3-fpm.service: Start request repeated too quickly.

I also received this later on in the same file which I believe could be related:

Jul  9 08:32:07 mail cron[14755]: Error: bad command; while reading /etc/cron.d/hestia-sftp
Jul  9 08:32:07 mail cron[14755]: (*system*hestia-sftp) ERROR (Syntax error, this crontab file will be ignored)

### Related issues or forum threads:
Possibly related:
https://github.com/hestiacp/hestiacp/issues/370

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ScIT-Raphael** [comment]
Thanks for your issue report, we noticed some issues with to fast restarting servuces that will hit the restart limit. We're sorry about your outtake, we work as hard as possible to fix any feature issues with a hot-hotfix release under 1.0.4.

**Comment by cmstew** [comment]
No problem. I was still able to get it to start eventually. Thanks for all your hard work! :)

**Comment by ScIT-Raphael** [comment]
We still search new users for testing, we noticed that we can't get all the bugs with our existing group size. If you would have interrest to help us out, please contact us on info@hestiacp.com -thanks!

**Comment by cmstew** [comment]
Sounds good. I'll reach out.

**Comment by ScIT-Raphael** [comment]
We just pushed the hotfix of the hotfix release: https://github.com/hestiacp/hestiacp/releases/tag/1.0.4

Please let us know if you will find any issue, as already wrote, I'll contact you tomorrow again over our ticketing system.

**Comment by cmstew** [comment]
You guys are amazing!

**Comment by ScIT-Raphael** [comment]
We try to give our best and understand that we still have a lot to learn :).
