### ISSUE TITLE
UI Update: Web Statistics select to a checkbox

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#520]
### In a few words, please describe the issue that you're experiencing:
Since we are only using one web statistic awstats. The Select Box should be turned into a simple checkbox

### Expected behavior:
Web Statistics should display as a checkbox

### Operating system distribution and release:
Ubuntu 18.04.2 LXC/Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

**Comment by ghost** [comment]
Hey @johnnyq, thanks for submitting this -- we'll look at making this change for v1.1.0.

**Comment by ScIT-Raphael** [comment]
maybe we will implement additional stats in feature, maybe something that it is a bit newer than awstats.
