### ISSUE TITLE
Feature Request: Delete DNS zone and mail domain when deleting web domain if they exist

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#521]
### In a few words, please describe the issue that you're experiencing:
When a Web Domain is deleted, if dns and mail exist then it should display check boxes for each to delete those as well.

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

**Comment by ghost** [comment]
This is a great suggestion to compliment the changes which were made to ensure that other domain data wasn't accidentally deleted when removing a web domain. We'll look at tackling this for 1.1.0.

**Comment by ScIT-Raphael** [comment]
Infact we moved this feature request around since nearly two years, we decided to close it: We currently do not have enough time to implement such a function, also it isnt on our highest priority. Please feel free to provide a PR for it, we would love to implement it.
