### ISSUE TITLE
Feature Request: On DB Click, Auto login to phpmyadmin

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#522]
### In a few words, please describe the issue that you're experiencing:
In the database list view it would be awesome to click on the database and have it log you in directly to phpmyadmin or mypgadmin

**Comment by ghost** [comment]
Hey @johnnyq, thanks for submitting this -- we'll take a look at adding this for v1.1.0. :)

**Comment by johnnyq** [comment]
That is great @kristankenney , this would be a big time saver for sure!!

**Comment by johnnyq** [comment]
Also the ability to show the current password for a db would be really helpful too

**Comment by xXKynarethXx** [comment]
Helpfull but pretty insecure. Being able to show someones password means not saving it securly. So I wont recommend that :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ScIT-Raphael** [comment]
Show a passwort isnt a good idea, also we do not have enough time fullfill all feature requests - going to close this one.

**Comment by EmmanuelAmankwah** [comment]
I'm trying to host a website i have set the dns name server with cloudflare and have done  everything i know but when i try open the website it tells me,  
Connection timed out Error code 522 
If you're the owner of this website:
Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522) please help me solve it

**Comment by jaapmarcus** [comment]
This has nothing to do with this feature request:
https://forum.hestiacp.com
