### ISSUE TITLE
Feature Request: On Email Click, Auto Log into Webmail

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#523]
### In a few words, please describe the issue that you're experiencing:
In the Email Account list under email domains it would be extremely helpful to be able to login via webmail by just clicking on the email.

**Comment by ScIT-Raphael** [comment]
We just discussed this internaly: We can't do a autologin for mail, you will need to have the unencrypted credentials. Also it would not be a good idea for privacy, if a admin can login directly to the mail. We will close this issue for now, please feel free to open a new one or post here if you have any questions.

**Comment by ozgurerdogan** [comment]
Actually directadmin and cpanel has this feature, and it is really soooo helpful and time gaining for admins.

**Comment by jaapmarcus** [comment]
For email it is personally a no go. For PHPmyadmin with the requirements it is possible without plain text password and secure it should be no issue

**Comment by jlguerrerosanz** [comment]
Please fix the PHPmyadmin at least. This is a pain in the ass. I have to go to the file manager, look for the wp-config.php file, copy the credentials and then get into the database.

**Comment by thytetgc** [comment]
Will we really not have this option to access emails simply?

**Comment by ScIT-Raphael** [comment]
> Will we really not have this option to access emails simply?

no, due to the reasons posted above. Also it isnt planed to change.
