### ISSUE TITLE
Feature Request: Option to disable MySQL Strict Mode in web UI

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#525]
### In a few words, please describe the issue that you're experiencing:
I just realized the new MariaDB is enforcing mysql strict Mode by default now. It would be nice to have an option to disable it under Server | Configure | Databases | MySQL Support / Configure - Add an option there to Disable MySQL Strict Mode.

**Comment by ScIT-Raphael** [comment]
We do not have enough resources, going to close this feature request.
