### ISSUE TITLE
Visual UI Bug: When record is suspended icon should change from a pause to play

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#526]
### In a few words, please describe the issue that you're experiencing:
When record is suspended icon should change from a pause to play icon

### What steps did you take when the issue occured? 
1. Click Web
2. Select a domain and click the Pause button

### Expected behavior:
The Pause should turn into a play button for reactivation

### Operating system distribution and release:
Ubuntu 18.04.2 LXC / Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
Release

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
Fixed from @neto737, thanks for your contribution!
