### ISSUE TITLE
Feature Request: Set Default Layout in Roundcube to Widescreen (3-column view) and more..

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#527]
### In a few words, please describe the issue that you're experiencing:
Below are a couple of options I believe should be modified from their default to make using webmail similar to using a desktop mail client or phone mail client

**Preferences | User Interface**

I noticed the default view is List (No Mail Preview) which is very inefficient, can we set the default to Widescreen (3-column view) which seems to be the modern layout and works extremely well.

**Preferences | Special Folders** 

the Option "Show real names for special folders" should be checked as this will prevent confusion of the junk spam folder. By default it shows Junk in roundcube but shows Spam in an email client like thunderbird or outlook.

**Preferences | Composing Messages**

Compose HTML messages by default is set to never it should be set to "always, except when replying to plain text" This is how a lot of default mail clients do it and most people are used to this to create profesional emails and signatures.

**Preferences | Displaying Messages**

Show email address with display name should be checked it is unchecked by default, this way you can verify the real email address right away.

**Comment by ghost** [comment]
Hey @johnnyq, thanks for sending this in -- we're planning to work on mail stack and improvements to the webmail experience over the course of the next few releases, as we know that this is a pain point for many users and the default Roundcube configuration and theme leaves a lot to be desired.

**Comment by johnnyq** [comment]
Very true @kristankenney This is exciting news!! The new roundcube 1.4 which should be coming out any day now with the new updated Elastic theme! It looks extremely modern and promising! You probably already seen the new UI but if you haven't yet check out roundcube's news section on their site.

**Comment by ghost** [comment]
As I'm sure you're probably aware, we're currently we're using the default Roundcube package which ships from the OS' apt repositories, however this in itself has presented a few challenges so we'll most likely be bundling our own package in the future once RC v1.4 stable is available. 

We'll also be looking at integrating some third party plugins to extend the functionality of Roundcube; for example when contact & calendar sync backends are made available as a feature of the server we'll also expose this to the webmail client to provide a modern experience that users have come to expect.

While I can't provide a specific timeline right now, we are also looking at a redesign of the skin used with Roundcube on a Hestia server to better align to the styling of the Control Panel UI, with focus on a clean and functional look.

**Comment by ghost** [comment]
Closing as this issue will be resolved once we move away from using the default Roundcube packages provided by each OS distribution in favor of using the upstream source directly (which also means an upgrade to 1.4 with the Elastic theme).
