### ISSUE TITLE
Bug: .well-known folder should be deleted from public_html

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#530]
### In a few words, please describe the issue that you're experiencing:
After LetsEncrypt addition/renewal, folder .well-known should be delete from public_html

### What steps did you take when the issue occured? 
Let's encryption addition or renewal

### Expected behavior:
Please enter your response here (e.g. A list of hosted web domains should appear).
Deletion of folder

### Operating system distribution and release:
Ubuntu 18.04.2

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ioannidesalex** [comment]
Also exists in /var/lib/roundcube/

**Comment by ScIT-Raphael** [comment]
Fixed with the following commit: https://github.com/hestiacp/hestiacp/commit/6b62aff160be512599ce5b06321975137aec8d7f
