### ISSUE TITLE
Enhancement: v-add-mail-domain-ssl

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#533]
### In a few words, please describe the issue that you're experiencing:
Script  v-add-mail-domain-ssl is flawless when is triggered from UI. When run through CLI, it needs the below:

Usage: v-add-mail-domain-ssl USER DOMAIN SSL_DIR [RESTART]

It should be better if SSL_DIR was parsed automatically via CLI.

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
If you want to add a lets encrypt for mail, just add it over v-add-letsencrypt-domain user domain '' yes: https://github.com/hestiacp/hestiacp/blob/f437a32e0e86815ec19e263d4b8cf1eddcad9cb8/bin/v-add-letsencrypt-domain#L3

Please add domain.tld and not mail.domain.tld as name, v-add-mail-ssl gets triggered from the script above with the right settings.
