### ISSUE TITLE
I try to add postgresql after installation

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#535]
Hi;

Ok! I know Hestia teams works on this kind of request/issue but
I found this [how to install PostgreSQL after install on VestaCP](https://forum.vestacp.com/viewtopic.php?t=3799)
which I translate like this (https://github.com/JDmnT/Debian/blob/master/hestia-postgres.sh)

everything seams working fine
I means PostgreSQL is running
![image](https://user-images.githubusercontent.com/5204724/61103022-a87a0a80-a49a-11e9-8ed5-470489684ddb.png)

but even I executed

> [/usr/local/hestia/bin/v-add-database-host pgsql localhost postgres ](https://github.com/JDmnT/Debian/blob/master/hestia-postgres.sh#L23)

and restart hestia, postgres don't appear as a choice

![image](https://user-images.githubusercontent.com/5204724/61103116-fa229500-a49a-11e9-87f3-e853d788f80f.png)

**Comment by ScIT-Raphael** [comment]
Dont have much knowledge with PostgreSQL, but you don't need to touch hestia.conf here: https://github.com/JDmnT/Debian/blob/master/hestia-postgres.sh#L20-L21

Because this will be set during v-add-database-host, can you check the hestia.conf file if the database system is set properly?

**Comment by JOduMonT** [comment]
thank for your over looking and your reflection
you got me on this one :)

my sed need to be better because
I had
`DB_SYSTEM='pgsql,mysql'`
instead of
`DB_SYSTEM='mysql,pgsql'`

I just inverse it and restart hestia service and boom ! :)

thanks again

**Comment by ScIT-Raphael** [comment]
No problem, glad it worked for you - also thanks for the other commits. We still search testing users for the project, would you like to help us out? Just write a short mail to info@hestiacp.com so we can get in contact.
