### ISSUE TITLE
Beefing up nginx

### ISSUE THREAD

**Issue by LeBaux** [hestiacp/hestiacp#537]
Previously I was using https://github.com/angristan/nginx-autoinstall along with Vesta happily. I wonder if you maybe want to add support for various nginx modules? One of the absolute best modules is https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker.

This adds a lot of complexity, but it would also make Hestia stand out. Modules like FancyIndex and Brotli pretty much just work out of the box, while Google PageSpeed breaks stuff in wrong hands (mine for example).

**Comment by ScIT-Raphael** [comment]
We dont want to "overload" hestia with a lot of additional mods and use the default repository for nginx. If a admin would like to use a custom compiled nginx version, he can implement it on his own. Also the project you posted should work with hestia out of the box.
