### ISSUE TITLE
Interactive prompt for credentials used in self-signed certificate

### ISSUE THREAD

**Issue by LeBaux** [hestiacp/hestiacp#538]
As Vesta, Hestia [still uses dummy cert data during install](https://github.com/hestiacp/hestiacp/search?q=Francisco&unscoped_q=Francisco). Looks unprofessional if anyone views the certificate and even not legitimate if your company is based in Europe.

**Comment by ScIT-Raphael** [comment]
A self signed cert always looks unprofessional :). With 1.1.0 we will implementate a automated let's encrypt generation process during the installation, if the validation fails, a self signed cert will be created. So there is no need to give valid data inside a self signed cert.
