### ISSUE TITLE
Long DNS TXT value breaks bind config

### ISSUE THREAD

**Issue by ivanh** [hestiacp/hestiacp#539]
Issue: Any DNS entries after this DKIM record in the db doesn't work. 

Tried adding a DKIM record that's longer than 255 characters. And also tried splitting them too.
Eg:

"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsz89WL0IGtHCweCkO6jr1UcEyUmBbTEmljmixG0VLc4sC9HwKQBvqHjVE7FdmTmpNYGHNsNe4Zefcl1S27kqLBB ImNR7PDgNR57K48nVbwRLgePVBSefU5aU633ALLJJ0w1tiPdxSZg5YC4Sr+JP1Zvg7dKWbMQ5zAy10dJ5EGWUqcq/oa3moCSirk2fF7D2nKUQBK35S/qCuOzn8AT+uB1Kptv4ZvgfZZwJEl2h1/I/vLYfN RmRWQStuQ9zcpJAIq9K+GTFlgU5vPZmKqa6oc0Lz2vLiLkReYWOx3WnDcG79/6VZ+Ei64CF6wQe76VuYxlb7unawuAwglmGKLRSRwIDAQAB;" 

"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsz89WL0IGtHCweCkO6jr1UcEyUmBbTEmljmixG0VLc4sC9HwKQBvqHjVE7FdmTmpNYGHNsNe4Zefcl1S27kqLBB ImNR7PDgNR57K48nVbwRLgePVBSefU5aU633ALL" "JJ0w1tiPdxSZg5YC4Sr+JP1Zvg7dKWbMQ5zAy10dJ5EGWUqcq/oa3moCSirk2fF7D2nKUQBK35S/qCuOzn8AT+uB1Kptv4ZvgfZZwJEl2h1/I/vLYfN RmRWQStuQ9zcpJAIq9K+GTFlgU5vPZ" "mKqa6oc0Lz2vLiLkReYWOx3WnDcG79/6VZ+Ei64CF6wQe76VuYxlb7unawuAwglmGKLRSRwIDAQAB;"

Noticed the conf removed the the " in the conf to look like this:
"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsz89WL0IGtHCweCkO6jr1UcEyUmBbTEmljmixG0VLc4sC9HwKQBvqHjVE7FdmTmpNYGHNsNe4Zefcl1S27kqLBB ImNR7PDgNR57K48nVbwRLgePVBSefU5aU633ALL 
 JJ0w1tiPdxSZg5YC4Sr+JP1Zvg7dKWbMQ5zAy10dJ5EGWUqcq/oa3moCSirk2fF7D2nKUQBK35S/qCuOzn8AT+uB1Kptv4ZvgfZZwJEl2h1/I/vLYfN RmRWQStuQ9zcpJAIq9K+GTFlgU5vPZ 
 mKqa6oc0Lz2vLiLkReYWOx3WnDcG79/6VZ+Ei64CF6wQe76VuYxlb7unawuAwglmGKLRSRwIDAQAB;"

Manually edited the domain.com.db to have the " back in but didn't fix the issue.

### What steps did you take when the issue occured? 
1. Added the above to dns TXT entry for default._domainkey

### Expected behavior:
Public DKIM can be retrieved to pass an email with valid DKIM.

### Operating system distribution and release:
Ubuntu 18.04.

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`
VERSION=1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Exim only)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

**Comment by ScIT-Raphael** [comment]
Please rework your issue report and also provide "Expected behavior" and your issue itself.

**Comment by Lupul** [comment]
Could not reproduce on 1.0.4 . Created a new TXT record with the WebUI and added your dkim key including the dbl quotes exactly as you see below:
```
"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsz89WL0IGtHCweCkO6jr1UcEyUmBbTEmljmixG0VLc4sC9HwKQBvqHjVE7FdmTmpNYGHNsNe4Zefcl1S27kqLBBImNR7PDgNR57K48nVbwRLgePVBSefU5aU633ALL" "JJ0w1tiPdxSZg5YC4Sr+JP1Zvg7dKWbMQ5zAy10dJ5EGWUqcq/oa3moCSirk2fF7D2nKUQBK35S/qCuOzn8AT+uB1Kptv4ZvgfZZwJEl2h1/I/vLYfNRmRWQStuQ9zcpJAIq9K+GTFlgU5vPZmKqa6oc0Lz2vLiLkReYWOx3WnDcG79/6VZ+Ei64CF6wQe76VuYxlb7unawuAwglmGKLRSRwIDAQAB;"
```

dig TXT @127.0.0.1 mydkim.domain.tld
```
; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> TXT @127.0.0.1 mydkim.domain.tld
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40847
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 7aa3281a5c42e53f4b0686fc5d2b1f3c64262de9ce0fc0e0 (good)
;; QUESTION SECTION:
;mydkim.domain.tld. IN TXT

;; ANSWER SECTION:
mydkim.domain.tld. 14400	IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsz89WL0IGtHCweCkO6jr1UcEyUmBbTEmljmixG0VLc4sC9HwKQBvqHjVE7FdmTmpNYGHNsNe4Zefcl1S27kqLBBImNR7PDgNR57K48nVbwRLgePVBSefU5aU633ALL" "JJ0w1tiPdxSZg5YC4Sr+JP1Zvg7dKWbMQ5zAy10dJ5EGWUqcq/oa3moCSirk2fF7D2nKUQBK35S/qCuOzn8AT+uB1Kptv4ZvgfZZwJEl2h1/I/vLYfNRmRWQStuQ9zcpJAIq9K+GTFlgU5vPZmKqa6oc0Lz2vLiLkReYWOx3WnDcG79/6VZ+Ei64CF6wQe76VuYxlb7unawuAwglmGKLRSRwIDAQAB;"

;; AUTHORITY SECTION:
domain.tld. 14400 IN NS	ns2.domain.tld.
domain.tld. 14400 IN NS	ns1.domain.tld.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Jul 14 12:25:32 UTC 2019
;; MSG SIZE  rcvd: 558
```
