### ISSUE TITLE
Feature Request: Imagick PHP Module

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#542]
### In a few words, please describe the issue that you're experiencing:
I noticed Imagick was installed but not the php module for imagick. This would be a great addition to Hestia since so many PHP apps rely on imagick

**Comment by ScIT-Raphael** [comment]
Hi, thanks for your request, has been added with the following commit and will be shipped with 1.1.0: https://github.com/hestiacp/hestiacp/commit/d49804362560bef5f4b3144bbbf3e701e449997f

**Comment by johnnyq** [comment]
Super!! Thanks!!
