### ISSUE TITLE
Feature Request: Increase PHP ini resource vars to a more sane limit

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#543]
### In a few words, please describe the issue that you're experiencing:
Increase PHP ini vars to a more sane limit to allow larger uploads via webscripts and certain PHP scripts to consume more memory if need be. One example of this is nextcloud which now requires 512M memory limit

memory_limit 128M to 512M
post_max 8M to 2G
upload_max_filesize 2M to 2G

**Comment by ScIT-Raphael** [comment]
That's a decission of the server admin itself, we do not want to set any values here expect the default one.

**Comment by johnnyq** [comment]
That makes sense, I was thinking the same 10 mins after I posted this.
