### ISSUE TITLE
Feature Request: Adding DNS A record for domains without zone

### ISSUE THREAD

**Issue by Wibol** [hestiacp/hestiacp#545]
### In a few words, please describe the issue that you're experiencing:
When creating a new domain without checking "Create DNS zone", no record is created.

### What steps did you take when the issue occured? 
HestiaCP/Web/Add Web Domain

### Expected behavior:
I think that an A record should be added to the parent DNS zone to make it accessible.

### Operating system distribution and release:
Debian 9

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

**Comment by ScIT-Raphael** [comment]
Do I understand you correctly: Add a A Record for a subdomain to the parent domain, if the parent domain exists?

**Comment by Wibol** [comment]
That's right. Creating "test.domain.tld", then add "test A IP" record to "domain.tld" zone if "Create DNS zone" is unchecked.

**Comment by johnnyq** [comment]
Sounds logical and an excellent idea!

**Comment by johnnyq** [comment]
It could go like this when you enter a web domain for example dev.example.com it will check to see if example.com is a zone the user controls and if so the Checkbox option "Create DNS Zone" would dynamically change to "Create A Record for Example.com" We would also need other checks as well, like if the A record already exists.

**Comment by johnnyq** [comment]
This can probably be closed this feature should not be implemented. The reason why
lets say user A has example.com and user B wants to create test.example.com. This will create an "A" Record on user A's domain.

**Comment by ScIT-Raphael** [comment]
It would be clear, that a record only would be added, if the user itself has the dns zone. So i would leave the request open, we currently do not have enough ressources to fullfill it now, but maybe in future.

**Comment by jaapmarcus** [comment]
We should not allow users to create an website for example test.example.com when user B owns example.com

**Comment by ScIT-Raphael** [comment]
Infact we moved this feature request around since nearly two years, we decided to close it: We currently do not have enough time to implement such a function, also it isnt on our highest priority. Please feel free to provide a PR for it, we would love to implement it.
