### ISSUE TITLE
Bug: Additional IPs issue

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#547]
### In a few words, please describe the issue that you're experiencing:
I am having a problem of adding a second (or third) IP to HestiaCP. I have faced with problem with Hetzner Cloud.

More specifically the IP is added everywhere like it should (nginx etc), except to the networking interface. Most probably the problem is because even though netplan package is not installed, directory /etc/netplan exists.

### What steps did you take when the issue occured? 
Add manually the IP to /etc/network/interfaces.d/60-mynewip

### Expected behavior:
IP(s) should be added to /etc/network/interfaces or /etc/network/interfaces.d/*

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Both.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
solved: https://github.com/hestiacp/hestiacp/commit/f99291748e54614666ba68e250bf41f9d0525041
