### ISSUE TITLE
Bug: /etc/cron.d/hestia-sftp

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#549]
### In a few words, please describe the issue that you're experiencing:
Produces error.

 Jul 16 18:35:37 user cron[17996]: Error: bad command; while reading /etc/cron.d/hestia-sftp
 ERROR (Syntax error, this crontab file will be ignored)

### What steps did you take when the issue occured? 
Monitor logs

### Expected behavior:
No errors, run the script properly.

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your response here (e.g the feature stopped working after upgrading to the latest release)
Both

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
Just tried to reproduce this bug, but can't find any related record in syslog. I will close the issue, please feel free to reopen it if there are any new informations.

**Comment by ioannidesalex** [comment]
It seems like the issue occurs when Hestia is upgraded to a new version. Please check your syslog the day you performed the upgrade to v1.0.5.

Aug  7 04:34:52 s2 systemd[1]: Reloaded LSB: service and resource monitoring daemon.
Aug  7 04:34:53 s2 systemd[1]: Stopping Regular background program processing daemon...
Aug  7 04:34:53 s2 systemd[1]: Stopped Regular background program processing daemon.
Aug  7 04:34:53 s2 systemd[1]: Started Regular background program processing daemon.
Aug  7 04:34:53 s2 cron[29325]: (CRON) INFO (pidfile fd = 3)
Aug  7 04:34:53 s2 cron[29325]: Error: bad command; while reading /etc/cron.d/hestia-sftp
Aug  7 04:34:53 s2 cron[29325]: (*system*hestia-sftp) ERROR (Syntax error, this crontab file will be ignored)
Aug  7 04:34:53 s2 cron[29325]: (CRON) INFO (Skipping @reboot jobs -- not system startup)

**Comment by ram108** [comment]
Ubuntu 18.04
I have the same error in syslog on fresh installation performed today. The error repeats constantly.
```
cron[30544]: Error: bad command; while reading /etc/cron.d/hestia-sftp
```

See bug explanation here: https://askubuntu.com/questions/335615/does-ubuntu-support-reboot-in-crontab

**Comment by ScIT-Raphael** [comment]
Hi @ram108 
Thanks for the hint! I just adjusted the cron file to include the correct user with the following commit: https://github.com/hestiacp/hestiacp/commit/10885f8346bc04506ed4d811f110e10754676c96

Still need to finish the complete testing, but it looks already solved. I'll close this issue, please feel free to reopen it or create a new one!
