### ISSUE TITLE
Feature Request: phpMyAdmin with https

### ISSUE THREAD

**Issue by ifaist0s** [hestiacp/hestiacp#551]
Clicking on the **_Database Editor_** button (HESTIA UI > User > DB > **_Database Editor_**) opens the page of phpMyAdmin **without** https.

My suggestion is to always open the phpMyAdmin page **with** https, provided that there is a certificate for the hostname (admin > Server > Configure > SSL).

I suppose it could work together with **_[v-update-host-certificate](https://forum.hestiacp.com/t/usage-of-v-update-host-certificate/65)_** like this:
When **_v-update-host-certificate_** is used to issue the server hostname certificate, a new routine could make the following adjustments: 
1 Create the file _/usr/share/phpmyadmin/.htaccess_ and add:
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</IfModule>
```
2 Edit _/etc/phpmyadmin/apache.conf_ and add the following lines
```
	AllowOverride All
	order allow,deny
	allow from all

```
These will force the phpMyAdmin page to **always** load on https.

Maybe there are other, more easy ways to accomplish the same thing. But the goal should be to always load phpMyAdmin **with** https.

**Comment by ScIT-Raphael** [comment]
I've updated v-add-letsencrypt-host with the following commit: https://github.com/hestiacp/hestiacp/commit/c6d2da3e988cef57ba8a6f9d5c98be6651ab5b3e

You can just enable ssl forward (and hsts if needed) for the hostname web domain in admin user:
![image](https://user-images.githubusercontent.com/13765400/61515333-a831c000-aa02-11e9-86ea-e5e54288e337.png)
