### ISSUE TITLE
Feature Request: Consolidate Pre and Lastname to one field.

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#553]
### In a few words, please describe the issue that you're experiencing:
When I try to add a user, Lastname is required. However, when I edit a user I am able to remove Lastname

### Expected behavior:
Lastname should not be required.

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Both

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ghost** [comment]
In my opinion, the first name and last name fields should be merged to one single "Name" field. 
Doing so would also allow for proper entry of organization or business names.

**Comment by ghost** [comment]
This has been completed and will ship with the next release.
