### ISSUE TITLE
Release version details different.

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#556]
Auto Update triggered on 22-07-2019. The versions info shows wrongly.

alert popup shows v0.10.0
Hestia configuration-release shows - v1.0.4
suggestion : Kindly display the Hestia version on top-right-bar. So the admins will know if there is changes. This will help us to check if anything goes wrong & we may check the release notes about changes on-time..

ref image : https://ibb.co/Z81Kbtm

**Comment by Lupul** [comment]
The notification timestamp is not visible in your screenshot, my guess is that the notification is from a previous upgrade.

**Comment by ScIT-Raphael** [comment]
@lupul is right, the version has been set properly on my test system. Also I reviewed the relevant code part and can't find any wrong or hardcoded version set.
