### ISSUE TITLE
Bug: Obsolete logs not deleted

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#557]
### In a few words, please describe the issue that you're experiencing:
When mail SSL alias is changed (v-change-sys-webmail), the related (old) nginx log files are not deleted from /var/log/nginx domains/

### What steps did you take when the issue occured? 
v-change-sys-webmail

### Expected behavior:
The obsolete log files should be deleted.

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Both

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
Just discussed this internaly in slack chat: We will not remove the logs on alias name change, it's better to have them "for the records"/as archive.
