### ISSUE TITLE
Mail say SSL already exist when I try to replace the actual SSL with Let's Encrypt

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#560]
like [here](https://github.com/hestiacp/hestiacp/issues/479#issuecomment-507910575)
but this time it is in production, so can't reinstall ;)

I accidentally, apparently, attribute a selfsign SSL to my mail service, so now when I try to replace this one with a Let's Encrypt SSL it is not working

![image](https://user-images.githubusercontent.com/5204724/62185507-f775da00-b38c-11e9-938f-fbea02f59455.png)

I tried to uncheck SSL + remove the SSL in `./conf/mail/domain.tld/ssl/*` than asking for SSL with Let's Encrypt but it's not working

How I can fix this without messing my others mail domain which already use a Let's Encrypt ?

**Comment by ScIT-Raphael** [comment]
As far as I know, this bug has been already fixed in master branch. Please check the following file $HESTIA/data/users/USER/mail.conf and set ssl=no for the domain. Then try to regenerate a let's encrypt certificate.
