### ISSUE TITLE
Replace phpmyadmin with adminer

### ISSUE THREAD

**Issue by LeBaux** [hestiacp/hestiacp#561]
Since it is not already mentioned, consider replacing phpmyadmin with adminer. Or add it as an installation option. Here is a PR in Vesta. https://github.com/serghey-rodin/vesta/pull/1847

The topic of PMA vs. admirer is a neverending story of "people are used to it" in most web pannels and I hope you will not bring up this argument.

**Comment by Lupul** [comment]
Hello LeBaux, we are familiar with the 'adminer' app, i'm using it myself regularly. But we don't have any plans to replace pma with it in the near future. Currently we are focusing on improving the existing software stack

**Comment by LeBaux** [comment]
Would you mind explaining why? What is the upside? Thanks.

**Comment by ScIT-Raphael** [comment]
Because we need to focus ourself to existing software stack and testing. There is just not enough develop time to fullfill the request.
