### ISSUE TITLE
improving the software stack ?

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#562]
Hi;

I just found a script who was deploying wordpress from the VestaCP interface
[similar to this](https://forum.vestacp.com/viewtopic.php?t=15698)

I think that would be a huge plus for Hestia which might even become an alternative of Yunohost and cie.

ps the title was inspired by [@Lupul](https://github.com/hestiacp/hestiacp/issues/561#issuecomment-516822025) but I'm not sure we talk about the same software stack :p

I already have few straight forward script;
 like to deploy Searx on Hestia with Nginx, ...

it's a matter of knowing if someone else see an advantage of this and what to work on it together.

**Comment by ghost** [comment]
Hi @JOduMonT,

This is a great suggestion and would be a workable replacement for Softaculous. However, adding such functionality would require additional maintenance efforts by the team to ensure that upstream changes do not break installation routines, and at this time we are focused primarily on improving the core code base. We'll evaluate this for a future release.
