### ISSUE TITLE
Bug: v-add-sys-sftp-jail

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#563]
### In a few words, please describe the issue that you're experiencing:
In case the system has additional ftp accounts, the following error occurs when you run v-add-sys-sftp-jail
chown: cannot access '/home/user_ftp': No such file or directory

### What steps did you take when the issue occured? 
Run the script

### Expected behavior:
Additional ftps should be excluded.

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Upgrade

**Note:** If you have upgraded from an older release on an existing server, please let us know 0.9.8

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
https://github.com/hestiacp/hestiacp/commit/e96330408c9143b0d1880481d464a766c671e37e
