### ISSUE TITLE
external backup service isn't working

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#569]
1. Log into the Hestia Control Panel using Chrome (https://(SERVERIP):8083/edit/server/)
2. When I Submit "Remote backup" Details

![image](https://user-images.githubusercontent.com/39749258/63134553-920a2600-bfe7-11e9-88a2-8899ddb7381b.png)

Tried this on clean installation on ubuntu 18.04 (digitalocean) 

![image](https://user-images.githubusercontent.com/39749258/63134646-080e8d00-bfe8-11e9-8e21-739a15f36657.png)

**Comment by ScIT-Raphael** [comment]
There is something wrong with your version, actual stable release is 1.0.5. Looks like you downloaded the installer from master and not release, please use this installer as described in our docs:
`wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh`

**Comment by Lupul** [comment]
"host connection failed" would indicate a host resolution issue, check if dns is working ok on the hestia host.
https://github.com/hestiacp/hestiacp/blob/3bfd817a6455e8c64a67ebd732facc0e0c1e00cc/bin/v-add-backup-host#L102-L103

**Comment by alber-khan** [comment]
Hello I've installed the clean installer this time from release and version is 1.0.5 and i can confirm i'm still getting this error! :( 

![image](https://user-images.githubusercontent.com/39749258/63654482-5cf49500-c798-11e9-95c1-525e54fc8f5d.png)

**Comment by alber-khan** [comment]
@ScIT-Raphael 

Protocol is FTP

![image](https://user-images.githubusercontent.com/39749258/63654544-4995f980-c799-11e9-8829-0a5d611f4ecd.png)

**Comment by alber-khan** [comment]
and when i'm using SFTP i'm getting this error "Error code: 1"

![image](https://user-images.githubusercontent.com/39749258/63654565-a5f91900-c799-11e9-9d68-aa48c1be2177.png)

**Comment by ScIT-Raphael** [comment]
Did you've checked if the credentials are valid? For example using Filezilla or command line ftp client. Hestia does some basic checks in v-add-backup-host, as @lupul already referenced in his post. I can confirm that backups to ftp and sftp server works properly, sftp has a validation issue but this is already fixed in master branch.

**Comment by alber-khan** [comment]
Yes boss I can confirm that FTP details are correct. if you want we can do the zoom session and I can show you the error.

**Comment by Lupul** [comment]
run the `host` command manually on the server and check the results
```
host "remotehostname"
echo $?
```

ps: I think there might be a bug when using ipaddr instead of dns name, if this is your case add a /etc/hosts entry as a temporary workaround

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/63670989-028d2000-c7fc-11e9-8d2b-a18cba613ba0.png)

@Lupul 

here's the response i'm getting

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/63671108-4e3fc980-c7fc-11e9-8d36-db5aa564d32e.png)

**Comment by Lupul** [comment]
Does it work with the ip added in /etc/hosts files?

```bash
echo "192.168.xx.xx backupserver.example.com" | sudo tee -a /etc/hosts
```

**Comment by alber-khan** [comment]
Protocol - FTP
Host - IP Address of my server (not domain name)
Username - username of the FTP account
Password - Password of the FTP account
Directory - /

**Comment by alber-khan** [comment]
So I'm not using the domain name for the FTP (ftp.mydomain.com) I'm directly putting it on my server IP and trying it boss but it's seems not working anymore.

**Comment by Lupul** [comment]
https://askubuntu.com/questions/183176/what-is-the-use-of-etc-hosts

**Comment by Lupul** [comment]
Fixed in master
