### ISSUE TITLE
apache2 template missing on clean installtion 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#570]
I've run the clean installation on ubuntu 18.04

sudo bash hst-install.sh -a no -n yes -w yes -o yes -v no -j yes -k yes -m yes -g no -x yes -z yes -c no -t no -i no -b no -q yes -d yes -f no -y yes -r 8083 -s something -e something@something.com -p something -l en

when I tried to add the Package apache2 templates were missing

![image](https://user-images.githubusercontent.com/39749258/63134838-e5c93f00-bfe8-11e9-9623-459c27b978a6.png)

**Comment by ScIT-Raphael** [comment]
Hi @4183r 
You've installed hestia without apache2, so yes, apache templates are missing. Can you still save the package?

Please use next time our issue template, the requested informations makes it easier for us to help.
