### ISSUE TITLE
Sendmail PHP settings in nginx templates

### ISSUE THREAD

**Issue by ram108** [hestiacp/hestiacp#573]
Sendmail parameters must be specified in nginx templates to have correct `from` entry with domain name and not with the default server host name. This is also important for `DKIM` and `SPF` lines in letter headers generated by mail server.

```
location ~ [^/]\.php(/|$) {
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PHP_ADMIN_VALUE "sendmail_path = /usr/sbin/sendmail -t -i -f admin@%domain%";
    ...
}
```

**Comment by ghost** [comment]
Fixed in https://github.com/hestiacp/hestiacp/commit/515286024c12a98e6ea582cb651cde964c357865.
