### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by bet0x** [hestiacp/hestiacp#574]
Hello, i have a small security question:

Do i have to add all users under the hestia-users group?

Isn't that a security issue?

ie: Users under the same group can access files from other users?

**Comment by Lupul** [comment]
Hello bet0x, yes all non-admin users created by hestia should be added in that group. 

This group is used to restrict access to users homedir using ACL, this way even if a user does a chmod 777 on its own files, it won't be readable to other hestia users.
