### ISSUE TITLE
Jquery 3.3.1 is outdated for PCI Compliance < 3.4.0

### ISSUE THREAD

**Issue by NZSAL** [hestiacp/hestiacp#575]
### In a few words, please describe the issue that you're experiencing:
Please enter your response here (e.g. When I click on the Web tab, a blank page is displayed).
New PCI compliance testing fails
### What steps did you take when the issue occured? 
1. Ex.: Log into the Hestia Control Panel using Firefox
2. Ex.: Click on the Web tab
3. ...
Run PCI Compliance scan
4.3 FAIL 8083 TCP  www JQuery < 3.4.0 Object Prototype Pollution Vulnerability

Impact
The version of JQuery library hosted on the remote web server is prior to 3.4.0. It is, therefore, affected by an object pollution vulnerability. See also : 

> https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

Resolution
Upgrade to JQuery version 3.4.0 or later.

### Expected behavior:
Please enter your response here (e.g. A list of hosted web domains should appear).
Fail - Synopsis The remote web server is affected by an object pollution vulnerability.
### Operating system distribution and release:
Please enter your response here (e.g. Ubuntu 18.04.2 LTS)
18.0.4 LTS
### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

Please enter your response here (e.g. 1.0.1)
1.0.5
### Which branch are you using?
Please enter your response here (e.g release, master, etc.)
master
### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your response here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.
1.0.4
### Which of the following web server configurations are you using?
Apache + Nginx (default)
- Nginx + PHP-FPM
- Multi-PHP
- PHP-FPM + Multi-PHP
- Other (please specify)

### Which of the following server roles are installed on your server?
DNS
Mail (Dovecot + Exim)
Mail (Exim only)
MySQL (MariaDB)
- PostgreSQL

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.
 locate jquery-3.3.1.min.js
/usr/local/hestia/web/inc/jquery/jquery-3.3.1.min.js

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.
Scan is required and must pass for merchant account (PCI Compliance used is Security Metrics)

**Comment by ScIT-Raphael** [comment]
Hi @NZSAL 
Thanks for your detailed issue report, we've updated the jquery package with the following commit: https://github.com/hestiacp/hestiacp/commit/37dbf8957b8aa5f29bb5dd630ae4f402a470a895

**Comment by NZSAL** [comment]
No problem @ScIT-Raphael, the issue is also present in 1.0.5 Release for others that must have PCI compliance.

**Comment by ScIT-Raphael** [comment]
It will be released with the next version of hestia, probaly 1.1.0 within the next few weeks.

**Comment by NZSAL** [comment]
Hi @ScIT-Raphael just did another scan on the master install and it found that there is still a reference to the old 3.3.1 version, 1 file was missed in the version update to 3.4.1.  line 12 in \web\templates\header.html
