### ISSUE TITLE
Hestia UI & Modules

### ISSUE THREAD

**Issue by bet0x** [hestiacp/hestiacp#576]
### In a few words, please describe the issue that you're experiencing:
There is a few changes that i will be happy to see, propose and work with on HestiaCP. There is more to add.

Users can change their plan.
Users can change their hosting template.
No FTP module.
No SSL module.

### What steps did you take when the issue occured? 
Using HestiaCP

### Expected behavior:
Options to restrict what the user can or cannot do. Separated FTP module, Separated SSL module.

### Operating system distribution and release:
Ubuntu 18.04.3 LTS

### Which version of Hestia Control Panel is currently installed?
root@hestiacp:~# grep VERSION $HESTIA/conf/hestia.conf
VERSION='1.1.0'
root@hestiacp:~#

Please enter your response here (e.g. 1.0.1)

### Which branch are you using?
release

Clean install

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Nginx + PHP-FPM
- Multi-PHP
- PHP-FPM + Multi-PHP
- DNS
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)
- PostgreSQL

### In order to better assist, please post any relevant log information below:
Not relevant

### Additional notes:
Can we push changes or suggest them to the UI, i have people that can do that work. Make it more friendly to new users.

**Comment by ScIT-Raphael** [comment]
> Users can change their plan.

I don't think it's a good idea that a user can change his own plan. So basicly you sell 1GB diskspace, customer can set himself to 10GB package.

> Users can change their hosting template.

Changing the hosting template can cause a downtime, if there is a issue in the template. Also if you create a new template just for testing, a normal user could select it which would cause in a downtime of apache2/nginx service.

> No FTP module.

You can disable vsftp using the custom installation command: https://github.com/hestiacp/hestiacp#custom-installation

> No SSL module.

I do not understand what you mean with "nossl" module - basicly SSL is a must have in the current web world.

If you would like to suggest or send changes, you can also use our pull request function. We will check your request / prs as soon as possible.

I'll close your issue for now, please feel free to reopen it or create a new one.

**Comment by Lupul** [comment]
1: Users can change their plan.
This should be handled outside of HestiaCP, in the billing platform (Whmcs,Blesta,Hostbill)

What do you mean by:
- Users can change their **hosting template.**
- No FTP module?.
- No SSL module?.

**Comment by bet0x** [comment]
If i buy Plan 001 why i can change it to Plan 002 ?

FTP has a SECTION, not a standalone module.
SSL has a SECTION, not a standalone module.

**Comment by bet0x** [comment]
If ROOT chooses hosting template as Apache config, why  allow the user to change it to anything else?

**Comment by ScIT-Raphael** [comment]
Are you logged in over admin? If yes, try to login with user name and password.

**Comment by bet0x** [comment]
Does the option to impersonate other uses gets the admin permissions?  I can still change my hosting template, enable or disable nginx too and several other options, as normal user. I will start to work on standalone templates for FTP and SSL.

**Comment by ScIT-Raphael** [comment]
I think here is a language barrier issue between us. If you login as admin, then click on login as a user, you can adjust all you want.

If you login directly with a user and password, you have only limited access.

**Comment by bet0x** [comment]
If i login as the user, i can still modify some system settings. There is none, i do suck at explaining things and i been using cPanel for the past 15 years, what i want to do is make it more user friendly and practical.

FTP Options are hidden, too complicated, make it table style like domains with proper menu entries, SSL settings too. Etcétera

I will fork and work, then show you what i mean. Access logs and HestiaCP Actions (Logs too) must be unified under a single section to make it less messier.
