### ISSUE TITLE
Can't login to Panel when SSL is off (NO LANGUAGE DEFINED)

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#577]
### In a few words, please describe the issue that you're experiencing:
Please enter your response here (e.g. When I click on the Web tab, a blank page is displayed).

### What steps did you take when the issue occured? 

when i turned off the SSL from Port 8083 from file located at 
/usr/local/hestia/nginx/conf/nginx.conf Line 90;

![image](https://user-images.githubusercontent.com/39749258/63654346-d8554700-c796-11e9-874b-bff54b45bed5.png)

and try to login to the panel it causes NO LANGUAGE DEFINED error

![image](https://user-images.githubusercontent.com/39749258/63654369-076bb880-c797-11e9-9ec8-abc4a95faa83.png)

### Expected behavior:
Please enter your response here (e.g. A list of hosted web domains should appear).

### Operating system distribution and release:
Ubuntu 18.04.3 (LTS) x64

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
VERSION='1.0.5'

### Which branch are you using?
Please enter your response here (e.g release, master, etc.)
release

### When did this issue occur? After a clean installation, or after an upgrade?

clean installation

### Which of the following web server configurations are you using?

sudo bash hst-install.sh -a yes -n yes -w no -o yes -v no -j yes -k yes -m yes -g no -x yes -z yes -c no -t no -i no -b no -q yes -d yes -f no -y yes -r 8083 -s www.b2btech.in -e something@gmail.com -p something -l en

**Comment by ScIT-Raphael** [comment]
Why you want to disable ssl on backend? I don't see any reason for it, also it's not supported from hestia itself.

**Comment by alber-khan** [comment]
okay boss

**Comment by ScIT-Raphael** [comment]
I just asked you for a reason to disable ssl; if you would do it, you would send all authentication data in plain text without any encryption, that's a no go. No need to get naughty here...

**Comment by Lupul** [comment]
set `php_admin_flag[session.cookie_secure]` to false in /usr/local/hestia/php/etc/php-fpm.conf

**Comment by ScIT-Raphael** [comment]
For the notes: Change would not be persistent and overwritten with a update of hestia-nginx package.
