### ISSUE TITLE
Let's Encrypt validation status 400

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#578]
### In a few words, please describe the issue that you're experiencing:
when I try to create an SSL via Lets Encrypt for the subdomain.

### What steps did you take when the issue occured? 

Edit Web Domain
--

![image](https://user-images.githubusercontent.com/39749258/63782377-f0e56e80-c908-11e9-9714-93c23c05bc20.png)

### Expected behavior:
Please enter your response here (e.g. A list of hosted web domains should appear).

### Operating system distribution and release:
Ubuntu 18.04.3 (LTS) x64

### Which version of Hestia Control Panel is currently installed?
1.0.5

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
sudo bash hst-install.sh -a yes -n yes -w no -o yes -v no -j yes -k yes -m yes -g no -x yes -z yes -c no -t no -i no -b no -q yes -d yes -f no -y yes -r 8083 -s www.b2btech.in -e alber@b2btech.in -p something -l en

**Comment by alber-khan** [comment]
Also when i change the web-template or proxy template  services doesn't restart

**Comment by Lupul** [comment]
Make sure your subdomain (dev.addaresult.com ) is correctly configured before requesting a LE SSL cert (and you have configured a valid email address on the admin account)

```bash
~$ curl dev.addaresult.com
curl: (6) Could not resolve host: dev.addaresult.com

~$ host dev.addaresult.com
Host dev.addaresult.com not found: 3(NXDOMAIN)
```
