### ISSUE TITLE
Feature Request: Restore Individual Email accounts from backup

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#579]
Its possible to restore mail domains with all email boxes under it, but it would be awesome if we could restore individual email accounts as well.

### Operating system distribution and release:
Ubuntu 18.04.3 LXC / Proxmox

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
1.0.5

Please enter your response here (e.g. 1.0.1)

### Which branch are you using?
Please enter your response here (e.g release, master, etc.)
release

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
Sounds like a good idea, but will consume to much time to develop. Currently there is no easy way to resolve this, also if you restore a whole backup of a email account, you would need to overwrite it. Probaly a "message export from backup"-function would be more usable.
