### ISSUE TITLE
Ownership of each user's home directory

### ISSUE THREAD

**Issue by drego85** [hestiacp/hestiacp#580]
### In a few words, please describe the issue that you're experiencing:

Each user's home directory is owned by the root user, it should not be.
For security reasons and to facilitate the creation of temporary files from different applications (eg. nano).

### What steps did you take when the issue occured? 

1. Logging in bash terminal via SSH with normal user credential
2. $ nano test.txt
3. \> Unable to create directory /home/$USER/.local/share/nano/: No such file or directory
4. $ mkdir /home/$USER/.local/
5. \> mkdir: cannot create directory ‘.local’: Permission denied

### Expected behavior:

The user must be able to create temporary files in his home directory. Or any type of file!

### Operating system distribution and release:

Ubuntu 18.04.3 LTS

### Which version of Hestia Control Panel is currently installed?

1.0.5

### Which branch are you using?

release

### When did this issue occur? After a clean installation, or after an upgrade?

After a clean installation, just installed a new VM.

### Which of the following web server configurations are you using?

bash hst-install.sh --apache yes --nginx yes --phpfpm no --multiphp no --vsftpd no --proftpd no --named no --mysql yes --postgresql no --exim no --dovecot no --clamav no --spamassassin no --iptables yes --fail2ban yes --quota no --api no --port 8083 --lang en --interactive yes

### Which of the following server roles are installed on your server?

nothing

### In order to better assist, please post any relevant log information below:

nothing

### Related issues or forum threads:

nothing

### Additional notes:

As a root user I changed the ownership of the user's home directory, everything seems to be going correctly.

\# chown $USER:$USER $USER/ -R
\> chown: changing ownership of '$USER/conf': Operation not permitted

**Comment by drego85** [comment]
Ok, I did some debugging.

On 29th Aprile this [commit](https://github.com/hestiacp/hestiacp/commit/3348625a3b1aabaa1603d56e820883d315dbeb70#diff-06cef53e2dd63e97401d0c88f5762bc1) whas made, but I can't find any comment to explain this choice.

Does anyone remember why it was made?

@FalzoMAD do you remember?

Thanks

**Comment by ScIT-Raphael** [comment]
Thanks for the issue report, the change was made due to sftp jail implementation - it needs root ownership to work properly. Maybe @Lupul can give some more informations also about the acl settings we've used.

**Comment by ScIT-Raphael** [comment]
btw, it's correct that you can't chown the conf directory, just for the notes.

**Comment by drego85** [comment]
Sorry for delay, but I wanted to do some tests. I don't know in detail how a sftp works.

I installed a clean system, composed as follows:

- Ubuntu 18.04
- bash hst-install.sh --apache yes --nginx yes --phpfpm no --multiphp no --vsftpd no --proftpd no --named no --mysql yes --postgresql no --exim no --dovecot no --clamav no --spamassassin no --iptables yes --fail2ban yes --quota no --api no --port 8083 --lang en --interactive yes

I then created a new user and gave him SSH access via bash. And I tried from the terminal what I could do!

```
$ sftp usertest@hestia.example.com
> hestia.example.com password:
sftp> pwd
Remote working directory: /home/usertest
sftp> ls -all /root
remote readdir("/root/"): Permission denied
sftp> ls -all /
drwxr-xr-x   24 root     root         4096 Sep  5 05:10 .
drwxr-xr-x   24 root     root         4096 Sep  5 05:10 ..
drwxr-xr-x    2 root     root         4096 Sep  5 05:10 backup
drwxr-xr-x    2 root     root         4096 Sep  4 15:33 bin
drwxr-xr-x    3 root     root         4096 Sep  4 15:34 boot
drwxr-xr-x   18 root     root         3760 Sep  4 15:56 dev
[...]
sftp> cd /home/admin
sftp> pwd
Remote working directory: /home/admin
sftp> ls
remote readdir("/home/admin"): Permission denied
```

Ok, so Jail is working properly. Now I try to change the owner of the home directory and recconnect to sfpt!

```
$ ssh root@hestia.example.com
# cd /home
# ls -all
total 16
drwxr-xr-x   4 root root 4096 Sep  4 16:05 ./
drwxr-xr-x  24 root root 4096 Sep  5 05:10 ../
drwxr-xr-x+  5 root root 4096 Sep  4 15:46 admin/
drwxr-xr-x+  5 root root 4096 Sep  4 16:05 usertest/
# chown usertest:usertest usertest/ -R
chown: changing ownership of 'scr1ptv13w3r/conf': Operation not permitted
# ls -all
total 16
drwxr-xr-x   4 root root 4096 Sep  4 16:05 ./
drwxr-xr-x  24 root root 4096 Sep  5 05:10 ../
drwxr-xr-x+  5 root root 4096 Sep  4 15:46 admin/
drwxr-xr-x+  5 usertest usertest 4096 Sep  4 16:05 usertest/
```

Okay, I'll reconnect via sfpt! 

And I have the same result I had before! Do not list the contest of the root directory, admin, etc!

Just to make sure, I restart the system! Nothing changes!

Now I edit the file: /usr/local/hestia/bin/v-add-user-sftp-jail and comment the following line:

```
# Set home folder permission to root
# chown root:root /home/$user
```

Well, now I create a new user through the admin panel!

```
$ sftp usertest2@hestia.example.com
> hestia.example.com password:
sftp> pwd
Remote working directory: /home/usertest2
sftp> ls -all /home/admin
remote readdir("/home/admin/"): Permission denied
sftp> ls -all /home
drwxr-xr-x    5 root     root         4096 Sep  5 16:55 .
drwxr-xr-x   24 root     root         4096 Sep  5 16:48 ..
drwxr-xr-x    5 root     root         4096 Sep  4 15:46 admin
drwxr-xr-x    7 usertest2  usertest2      4096 Sep  5 16:57 usertest2
drwxr-xr-x    7 usertest usertest     4096 Sep  5 16:33 usertest
sftp> ls -all /root
remote readdir("/root/"): Permission denied
```

Honestly the SFTP jail seems to work properly even without giving the home directory ownership to the root user.

Am I wrong?

**Comment by FalzoMAD** [comment]
heyho @drego85 :-)

the thing you might be missing here is that we want to chroot additional sftp users on a deeper directory level against each other. 
imagine a use case where you handle mutliple web-domains in one account and have to give access to different developers on those. so you would want to restrict them to see only the content of public_html of one domain and not the others.

so it's not only about protecting the whole system... I haven't played around with it for a while but the root:root thing has a reason and you can read it in mostly all of the available manual regarding chrooting sftp.

I agree on the issue itself, that it's not good if a user can't create temp files in his home directory, so maybe changing the ownership based on the user having bash or not might make sense to resolve that?

If I remember correctly I also suggested to restrict additional user of a _web-domain_ to the according dir with the domainname and have the /home/<user>/web directory carry the root ownership for the jail instead of the home-dir.

**Comment by ScIT-Raphael** [comment]
Thanks for the detailed and correct answer @FalzoMAD!

I'll have a look how we can implement the permission switch, basicly I think about a "easy" chown if you set a user from nologin to bash - this would break sftp jail, but gives back write permission for temporary files.

**Comment by Lupul** [comment]
Sftp jail is working when the user doesn't have shell login permissions and should only show the folders relative to the user home dir:
```bash
root@hst-ub1804-ngx-fpm:~# sftp user@127.0.0.1
Connected to 127.0.0.1.
sftp> ls -l
drwxr-xr-x    5 root     root         4096 Aug 11 19:49 conf
drwxr-x--x    2 root     root         4096 Aug 11 19:49 mail
drwx------    2 1003     1003         4096 Aug 27 09:49 tmp
drwxr-x--x    3 1003     1003         4096 Aug 25 11:49 web
sftp> pwd
Remote working directory: /
```

If sftp root directory is not owned by root then sftp jail fails:
```bash
root@hst-ub1804-ngx-fpm:~# chown user:user /home/user
root@hst-ub1804-ngx-fpm:~# sftp user@127.0.0.1
user@127.0.0.1's password: 
packet_write_wait: Connection to 127.0.0.1 port 22: Broken pipe
Connection closed
root@hst-ub1804-ngx-fpm:~# 
```

journalctl:

```bash
Sep 06 00:04:19 hst-ub1804-ngx-fpm.hst systemd[1]: Started User Manager for UID 1003.
Sep 06 00:04:20 hst-ub1804-ngx-fpm.hst sshd[3482]: fatal: bad ownership or modes for chroot directory "/home/user"
Sep 06 00:04:20 hst-ub1804-ngx-fpm.hst sshd[3390]: pam_unix(sshd:session): session closed for user user
```

**Comment by Lupul** [comment]
As a solution we should add a couple of user writable folders to the user home dir (v-add-user):
- .config
- .local
- .composer

**Comment by ScIT-Raphael** [comment]
Thanks @Lupul for the idea, I've implemented it with the commit above. We will ship that change with release 1.1.0, so the basic writeable/temporary folders should be accessible now.

**Comment by drego85** [comment]
Thanks you all, for the clarifications and for the resolution!
