### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by vitich** [hestiacp/hestiacp#581]
Hi!
If I log in to the control panel as user not admin, I get a 500 error. If I log in as admin first and click on the "log in as user" icon
then everything is ok.
after installation, I changed the sys port (v-change-sys-port 10) and added letsencrypt (v-addletsencrypt-host)
I did not find anything useful in the logs - maybe I looked in the wrong place?
Thank you!

![Screenshot from 2019-09-05 11-29-12](https://user-images.githubusercontent.com/12166319/64326121-0c6c0b80-cfd2-11e9-8747-534dac8b1a56.png)

**Comment by ScIT-Raphael** [comment]
https://forum.hestiacp.com/t/error-500-when-log-in-as-user-not-admin/165
