### ISSUE TITLE
exim4 whitelist does not work

### ISSUE THREAD

**Issue by vitich** [hestiacp/hestiacp#582]
It seems exim4 whitelist does not work. Does it?
Here is the log:
2019-09-05 16:07:44 H=(bad.remote.addr.net) [195.195.25.95] X=TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256 CV=no F=<nginx@bad.remote.addr.net> rejected RCPT <my@email.com>: Sender verify failed
Then I added the email address and IP of the sender server to the whitelist /etc/exim4/white-blocks.conf
Unfortunately, this didn't help.
I know that this e-mail address is incorrect, the mail domain is incorrect, but I really need to receive mail from it. 
The admin on the other side is unavailable and it is impossible to reconfigure sending mail.
Yesterday, before migrating to hestiacp, the whitelist worked fine.
What am I doing wrong?
Thanks a lot!

**Comment by ScIT-Raphael** [comment]
https://forum.hestiacp.com/t/exim4-whitelist-does-not-work/166

**Comment by jult** [comment]
Why is this, whitelisting a domain or IP-address or sender, not an option IN the hestia panel itself, or am I missing something?

**Comment by jaapmarcus** [comment]
Because nobody wants to implement it or fund the development for it. 

I don't need it might self and have other things that has an higher priority to do then this. 

If you want to fund it feel free to send an email to info@hestiacp.com.
