### ISSUE TITLE
Feature Request: New Responsive Minimalistic Theme

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#583]
Hey,I am loving hestiacp and it is great.
But,I want some features.
Web Interface isn't good:
I love the Web interface of HestiaCP as it is better than vestacp,But i would love to have it lightweight,mobile compatible,good looking.
I don't want it bloat.
I think that instead of tweaking Default theme of VestaCP,you great people must create good looking,non-bloated,minimal theme from scratch.

**Comment by ScIT-Raphael** [comment]
A full rewrite of the webinterface is already on the to do list - but this needs a lot of time, which we do not have currently. If you want to work on a own implementation of a backend, please fork our project and create a pull request if you want to merge it. Until now, I'll close your issue request, please feel free to reopen it at any time.
