### ISSUE TITLE
Bug: IpTables / Fail2ban - Delete Blocked IP doesnt restart iptables

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#585]
### In a few words, please describe the issue that you're experiencing:
Fail 3 logins via ssh your IP will be blacklisted login to the web interface and delete the IP from the list, then ssh back in. It will not let you in, this is because iptables needs to be restarted when IP is removed from black list. 

### What steps did you take when the issue occured? 
1. ssh to box 3 times with invalid password
2. Click Server
3. Click Firewall
4. Delete your IP
5. Try to login

### Expected behavior:
When IP is deleted from the block list it should restart iptables

### Operating system distribution and release:
Ubuntu 18.04.3 LTS LXC/Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.5

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your response here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ScIT-Raphael** [comment]
Hmm, I think the easiest ways to solve this issue would be to run a v-update-firewall after v-delete-firewall-ban. Could you check if that works? First remove the ban trought backend or cli, then run a v-update-firewall on cli.

**Comment by johnnyq** [comment]
It Works Great!!

**Comment by johnnyq** [comment]
I have noticed after I delete the offending IP and then run v-update-firewall, it allows me in, but if I fail a bunch more logins it doesn't re-add my IP to the firewall block list.

**Comment by ioannidesalex** [comment]
In my case I never needed so far to restart iptables in order to unban any users. In fact iptables is not a service, thus with v-update-firewall you just flush its rules and re-add the default ones.

**Comment by Lupul** [comment]
I could not reproduce the issue on ubuntu18.04 (vm and lxc container)

Can you check if the ip is still blocked by iptables:
`iptables -n -L | grep 1.2.3.4`

**Comment by johnnyq** [comment]
After Deleting the banned IP in the web interface this is the output of

```
root@web01:~# iptables -n -L | grep XXX.XXX.XXX.XXX
REJECT     all  --  XXX.XXX.XXX.XXX         0.0.0.0/0            reject-with icmp-port-unreachable
```
I eradicated my IP with XXX

after running v-update-firewall and re-ran the command

```
root@web01:~# iptables -n -L | grep XXX.XXX.XXX.XXX
REJECT     all  --  XXX.XXX.XXX.XXX         0.0.0.0/0            reject-with icmp-port-unreachable
```

it still says im blocked, although it allows me to ssh in again. (keep in mind this is after i run v-update-firewall

I attempted to ssh in with many failed attempts and now it no longer blocks the IP, it seems like v-update-firewall may have disabled the firewall all together. Something does not seem right. Ill investigate further.

it must be my installation then, i'm going to attempt a fresh install on a secondary server and try to replicate.

**Comment by ioannidesalex** [comment]
Make your tests without running v-update-firewall after ban.

**Comment by johnnyq** [comment]
I spun up a new instance on proxmox with ubuntu 18.04 LXC Template default hestiacp install.
I attempt to login via ssh with false credentials after 3 tries i can no longer ssh in
I then load up the web interface of hestia and goto server | Firewall | Manage Banned IPs
I find my IP and click on the trash icon and delete the IP
I attempt to log back in to through ssh but it wont let me as my IP still appears to be banned
So i ran the command 

```
root@web01:~# iptables -n -L | grep XXX.XXX.XXX.XXX
REJECT     all  --  XXX.XXX.XXX.XXX         0.0.0.0/0            reject-with icmp-port-unreachable
```
Iptables is still blocking my IP, it looks like the web interface isnt syncing with iptables when an IP is removed and vice versa .

**Comment by Lupul** [comment]
The code responsible for deleting the IP from iptables is here:
https://github.com/hestiacp/hestiacp/blob/cd3b34e3b7d4c8961d6d0f58d7acb403e89d1c27/bin/v-delete-firewall-ban#L47-L51
Which would fail if multiple lines(similar ips) returned by 'grep $ip' but looking at your output does not seem to be the case here (although it is definitely a bug). Ex:
```
root@web01:~# iptables -n -L | grep 192.168.1.2
REJECT     all  --  192.168.1.2         0.0.0.0/0    reject-with icmp-port-unreachable
REJECT     all  --  192.168.1.21        0.0.0.0/0    reject-with icmp-port-unreachable
REJECT     all  --  192.168.1.222       0.0.0.0/0    reject-with icmp-port-unreachable
..etc..
```
Second thing that you could look into is if the iptables chains match (Hestia web; $HESTIA/data/firewall/banlist.conf ; iptables -L ). Check if your ip was added in the correct chain ex: fail2ban-SSH

**Comment by Lupul** [comment]
any update @johnnyq ?

**Comment by johnnyq** [comment]
Your right on @Lupul it looks like my IP is listed twice. Once under Chain f2b-sshd and another under Chain fail2ban-SSH. When I delete My IP under banned IPs on the web interface it deletes it under Chain fail2ban-SSH but still exists under Chain f2b-sshd. I'm not sure why there are 2 chains for ssh. Also I attempted this on a recently spun up hesita instance and upgrade to mastrer latest branch and I still get the same result.

**Comment by Lupul** [comment]
Good, we are getting somewhere, finally I could reproduce it on my test system.

This fixed for me:
1. Stop f2b ssh jail (as root): 
`fail2ban-client stop sshd`
2. Remove/Comment out ssh jail in /etc/fail2ban/jail.d/defaults-debian.conf

**Comment by johnnyq** [comment]
That did it @Lupul !
