### ISSUE TITLE
Ubuntu 18.04:  Let's Encrypt nonce request status

### ISSUE THREAD

**Issue by ram108** [hestiacp/hestiacp#592]
Getting Subj error on trying to issue Let's Encrypt sertificate on last update of Ubuntu 18.04.

Here is a topic on Vesta github:
https://github.com/serghey-rodin/vesta/issues/1886

The solution that works:

Edit 2 files:
`v-add-letsencrypt-user`
`v-add-letsencrypt-domain`

1. Replace all `HTTP/1.1` to `HTTP/2`
2. Replace all `grep Nonce` with `grep -i nonce`

**Comment by ScIT-Raphael** [comment]
Please update your hestia package, we've published a hotfix this morning.
