### ISSUE TITLE
Bug: Moving site to another user causes awstats to break

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#596]
### In a few words, please describe the issue that you're experiencing:
When you move a site to a new user using v-change-domain-owner it currently break awstats. It looks like the symlink in /etc/awstats/ does not get updated to the new path.

### What steps did you take when the issue occured? 
1. Create a site the awstats 
2. Move the site to another user using v-change-domain-owner

### Expected behavior:
When you move a site awstats should update its symlink to the new path

### Operating system distribution and release:
ubuntu 18.04.3

### Which version of Hestia Control Panel is currently installed?
1.0.6

Please enter your response here (e.g. 1.0.1)

### Which branch are you using?
release
### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your response here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ghost** [comment]
What happens if you perform a rebuild on the user or web domain after moving it?

**Comment by johnnyq** [comment]
I forgot to mention that i did rebuild the site, it did not fix, I ended up removing the stale symlink in /etc/awstats and repointed to the new location and ran sudo /usr/local/hestia/bin/v-update-sys-queue webstats to update and it worked
