### ISSUE TITLE
bug : Error: Unable to connect to the Hestia APT repository

### ISSUE THREAD

**Issue by mckaygerhard** [hestiacp/hestiacp#598]
### In a few words, please describe the issue that you're experiencing:

hestia panel seems depends too much of the gpg and security behaviour.. due that fails if a minimal change happened.. too much delicate

### What steps did you take when the issue occured? 
1. fresh install of tDebian in expert mode.. nothing automatic
2. run `bash hst-install.sh --multiphp yes --phpfpm yes -e **********@gmail.com -p *********** -s main.xxxxxx.net`
3. fails with `Error: Unable to connect to the Hestia APT repository`

### Expected behavior:
normal install

### Operating system distribution and release:
Debian 9 fresh install

### Which version of Hestia Control Panel is currently installed?
```
grep VERSION $HESTIA/conf/hestia.conf
grep: /conf/hestia.conf: No such file or directory
```

### Which branch are you using?
```
grep VERSION $HESTIA/conf/hestia.conf
grep: /conf/hestia.conf: No such file or directory
```

### When did this issue occur? After a clean installation, or after an upgrade?
clean install

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- PHP-FPM + Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ghost** [comment]
Hi @mckaygerhard, sorry to hear that you're having trouble with the install. I'll run a clean install against Debian 9 shortly to reproduce, Ubuntu 18.04 is tested and working correctly at this time. Are you able to successfully ping and resolve apt.hestiacp.com from the server?

We will be improving fail-safe mechanisms within the installer in an upcoming release, however I can't specify a time frame right now on that as we do have a lot of work ahead of us.

**Comment by mckaygerhard** [comment]
i not have the host command.. please manual said "fresh install" very pointed! so fresh install men!
and ping works:

```
ping apt.xxxx.com 
PING apt.xxxx.com (104.28.20.51) 56(84) bytes of data.
64 bytes from 104.28.20.51: icmp_seq=1 ttl=59 time=8.21 ms
64 bytes from 104.28.20.51: icmp_seq=2 ttl=59 time=8.22 ms
^C64 bytes from 104.28.20.51: icmp_seq=3 ttl=59 time=8.47 ms
^C
--- apt.xxxx.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 8.213/8.305/8.475/0.159 ms
```

**Comment by ghost** [comment]
I'm not able to reproduce this on a fresh installation of Debian 9.9.0, and both `apt.hestiacp.com` & `raw.githubusercontent.com` resolve correctly with no SSL errors. Please run the install again against a fresh install and let us know if the problem still occurs.

**Comment by ScIT-Raphael** [comment]
Same here, not able to reproduce - repository is up and running.

**Comment by mckaygerhard** [comment]
problem comes due issue #599  if i use --no-check-certificate (due invalid documentation) then second scripts fill have unexpected behavoiur.. 

also as i said in first issue apt-transport-https are not validate untill second scripts (nonsense a second scritp witha first made) are assumed.. of course that are a good mechanish due a second script are used dependeing of the linux distribution.. but fails

change label to valid and bug due issue #599  has a response of @tudorr89 with the solution .. of course

**Comment by ScIT-Raphael** [comment]
Issue due to missing ca-certificate package, duplicate of https://github.com/hestiacp/hestiacp/issues/599
