### ISSUE TITLE
Bug: stupid checking of certificate fails if used wget due "ERROR: The certificate of ‘raw.githubusercontent.com’ is not trusted."

### ISSUE THREAD

**Issue by mckaygerhard** [hestiacp/hestiacp#599]
### In a few words, please describe the issue that you're experiencing:

```
wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
--2019-10-02 19:33:49--  https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.196.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.196.133|:443... connected.
ERROR: The certificate of ‘raw.githubusercontent.com’ is not trusted.
ERROR: The certificate of ‘raw.githubusercontent.com’ hasn't got a known issuer.
```

IF i used the nocheck scertificate then this happened if i run the script:

```
root@main:~# bash hst-install.sh --multiphp yes --phpfpm yes -e **********@gmail.com -p ************ -s main.xxx.net
Error: hst-install-debian.sh download failed.
```

### Expected behavior:
normal install

### Operating system distribution and release:
Debian 9 fresh install

### Which version of Hestia Control Panel is currently installed?
```
grep VERSION $HESTIA/conf/hestia.conf
grep: /conf/hestia.conf: No such file or directory
```

### Which branch are you using?
```
grep VERSION $HESTIA/conf/hestia.conf
grep: /conf/hestia.conf: No such file or directory
```

### When did this issue occur? After a clean installation, or after an upgrade?
clean install

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- PHP-FPM + Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by mckaygerhard** [comment]
you @ScIT-Raphael  dont have professional made servers.. those servers have only minimal packages installed.. it's ovbiosu you made "all in one" install .. servers dont have "recommended" package installed.. so this stupid script fails due that

**the hestia installer are just a script that assumed a debian desktop installation not a minimal net** 

**hestia documentation said clear: "just fresh install" but does not specified what king of..** 

**dont tell me guys hestia panel will xpected a desktop made install? put nonsense!**

**_due that: ca-certificates, lsb-release and many others are not installed in professional made install fresh debian in kvm machines!_**

**Comment by tudorr89** [comment]
Have you tried 

`$ sudo apt-get install ca-certificates`

?

**Comment by ScIT-Raphael** [comment]
I don't want to write much, because it doesn't look like you're here for a solution - so just a few words: Hestia Installer works perfectly using minimal iso images on ubuntu and debian. Also it works properly on most preshiped kvm machines we've tested, for example on Hetzner Cloud or OVH. There is no need to install any desktop environment.

Please respect the common manners, otherwise we will exclude you from the github project.

**Comment by mckaygerhard** [comment]
> Have you tried
> 
> `$ sudo apt-get install ca-certificates`
> 
> ?

that's was the solution @tudorr89 .. but scritps assumed that.. 

documentations said "fresh install" but does not specify what kind of install!

**KVM virtual servers does not have any of those packages already installed:**

* ca-certificates
* lsb-release
* curl
* apt-transport-https (installed later by second script and that are not documented)

**Comment by ScIT-Raphael** [comment]
Thanks for respecting the common manners.

I'll speak with the team, if we expand the software requirements for ca-certificated and lsb-release. The other two (curl and apt-transport-https) will be already validated from the installer.

**Comment by mckaygerhard** [comment]
remove the invalid label then, mark resolved but present and due was a true! was a lie in documentation and was a valid issue

**Comment by Newbytee** [comment]
![image](https://user-images.githubusercontent.com/4428753/66133497-109e3f80-e5f7-11e9-9144-cc48cf9998e0.png)
Can confirm this occurs after a clean install of Debian 9 in "expert mode".

**Comment by ScIT-Raphael** [comment]
I adjusted the installation note and also added a lsb_release check for the install script: https://github.com/hestiacp/hestiacp/commit/1df9423caa3cd67d90c97352c5ca88549aec8841
