### ISSUE TITLE
speed up phpfpm 7.3

### ISSUE THREAD

**Issue by sander816** [hestiacp/hestiacp#600]
what can i do to speedup phpfpm 7.3?
I am running wordpress on a 1Gb vps, but loading a site(just one site hosted) takes around 3 seconds

**Comment by ioannidesalex** [comment]
@sander816 There are several things that can be done to improve the speed of a website, one of them (not the only one) being PHP 7.3.

HestiaCP does several optimizations out of the box. However, there is no one size fits all, thus further optimizations might be needed by the system administrator.

This is not related to Hestia.
