### ISSUE TITLE
Allow Users to setup Reverse Proxy

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#604]

**Comment by ioannidesalex** [comment]
With regards to Nodejs, I am succesfully running a Nodejs with Angular project using Nginx as reverse proxy. A custom nginx template is required, based on your usecase.

**Comment by ghost** [comment]
Can you please tell me how to do that?

**Comment by ScIT-Raphael** [comment]
Crosspost: https://forum.hestiacp.com/t/enable-users-to-run-go-webapps/178/3

Answered in forum, I'll close the hestia issue here.
