### ISSUE TITLE
Devuan support as Debian does (Devuan are Debian fork just no systemd)

### ISSUE THREAD

**Issue by mckaygerhard** [hestiacp/hestiacp#606]
### In a few words, please describe the issue that you're experiencing:

Please added support to Devuan.. due are same as Debian (jessie and Ascii are jessie and strech respectivelly, just no systemd support)

### What steps did you take when the issue occured? 

no Devuan support and are just same

### Expected behavior:

Install as does in Debian 8 or 9

### Operating system distribution and release:

Devuan ASCII or JESSIE

### Which version of Hestia Control Panel is currently installed?

unnable to grab due no install possible

### Which branch are you using?

unnable to grab due no install possible

### When did this issue occur? After a clean installation, or after an upgrade?

at install step

### Which of the following web server configurations are you using?

- Apache + Nginx (default)
- Nginx + PHP-FPM
- Multi-PHP
- PHP-FPM + Multi-PHP

### Which of the following server roles are installed on your server?

- DNS
- MySQL (MariaDB)
- PostgreSQL

**Comment by ScIT-Raphael** [comment]
Did you try to install it on Devuan? Basicly you could just grab the debian installer and give it a try.

**Comment by ghost** [comment]
Hi @mckaygerhard,

At this time we will continue supporting mainline Debian and Ubuntu LTS releases only as these are fully validated and tested configurations. 

You can attempt to modify the installation script to allow the install to proceed on an unsupported operating system, but please be aware that you may encounter issues which we will not be able to assist with. Support for older releases which did not rely on systemd (such as Ubuntu 14.04) was dropped several months ago and many internal scripts now call on systemd/systemctl.

**Comment by mckaygerhard** [comment]
that stupíd, droping other call means only support those and limit to those operating systems! puff

**Comment by ghost** [comment]
@mckaygerhard, I'm sorry but we simply can't support every variation/fork that's out there, doing so would increase the time that's required to validate such configurations and also add unnecessary backwards compatibility when we are working to streamline the code base and make it more efficient and reliable.

Again, you're more than welcome to download and modify the installer to force the installation on Devuan but we can't support this should issues arise.

**Comment by mckaygerhard** [comment]
if i can provide a patch for? what about that? we can work with devuan collaborators and make multi installable also for other linux?

i understand that but we need more distro agnostic no systemd dependences!

**Comment by ghost** [comment]
You're more than welcome to submit a pull request for review if you'd like to, but again providing support for every flavor of Linux out there isn't our goal which is to provide an easy-to-use but powerful and reliable web hosting control panel product that works well, and part of that is how it interacts with the underlying operating system itself.

Our team has tested native Debian and Ubuntu installations _extensively_ and this is why we have chosen to only support them at this time. Based on demand, we may consider supporting CentOS or RHEL in the future but that's still up for debate.
