### ISSUE TITLE
Feature Request: Add support for cloudflare's API for DNS management

### ISSUE THREAD

**Issue by animeai** [hestiacp/hestiacp#607]
As a lot of people will use Cloudflare these days not only for their proxying service but fast resolution of new DNS entries it would be very useful to allow VestaCP to connect to the Cloudflare API to both view and edit DNS entries - more information on this feature is available https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record

This would also allow for the verification of LetsEncrypt certificate requests via DNS entry when using Cloudflare rather than relying on http verification. This is useful if you wish to issue LetsEncrypt certificates for non-web-accessible (sub)domains - I.E. on a local network. It would also give the option to block entire subdomains to IP ranges without worrying your certificate will expire. 

You would likely still need the local named service so the server knows where to send the traffic when a (sub)domain is accessed but this would also open up the opportunity to use a software edge router such as traefik that would allow you to map subdomains to services running on ports so instead of mydomain.tld:8083 you could simply access panel.mydomain.tld (no more remembering all those port numbers!).

Combine all the concepts and you have mydomin.tld:(anyport) blocked and only accessible from the subdomin, each (sub)domain has a fully valid ssl certificate, and have each critical subdomain locked to only local IP addresses and your static VPN IP for vastly increased security without a huge amount of complexity. 

Part of this could easily be implemented without use of the Cloudflare API, but would prevent a Cloudflare user from taking advantage of all of the features. Right now Cloudflare users have to manually replicate the named entries into the Cloudflare website!

**Comment by ioannidesalex** [comment]
I would really love to see such a feature. However, it needs a lot of dev hours to be implemented.

**Comment by ghost** [comment]
If anyone is able to help us add this functionality, please submit a pull request for our team to review. Given the rising popularity of Cloudflare's DNS services, I think it only makes sense to have this available as an option but as @ioannidesalex said it would require some time to implement and validate.

**Comment by vvcares** [comment]
> If anyone is able to help us add this functionality, please submit a pull request for our team to review. Given the rising popularity of Cloudflare's DNS services, I think it only makes sense to have this available as an option but as @ioannidesalex said it would require some time to implement and validate.

hi. im using this script for my client's Synology NAS Drive.

[https://github.com/vvcares/others/blob/master/vv_cloudflare_ddns.sh]

- synology connected to internal network with local ip (192.168.xxx).
- The domain DNS is under cloudflare.
- The subdomain is used to access my NAS with custom port (Note: cloudflare free accounts SSL supports few ports only, not all ports)
- The NAS will trigger this script and the script and updates the current public IP of my home ISP IP. If there is a change, the script will update the public IP on CF DNS.

The same we could implement for Hestia domains too.

**Comment by animeai** [comment]
This could be quite simply done with docker:

https://joshuaavalon.github.io/docker-cloudflare/guide/#usage
https://hub.docker.com/r/joshava/cloudflare-ddns/

It may also be possible to just extract the scripts from https://github.com/joshuaavalon/docker-cloudflare and use these natively, but this is less desirable.

**Comment by jaapmarcus** [comment]
HestiaWebInterface has support for Cloudflare... 

Maybe we could use parts from it 
https://github.com/cdgco/HestiaWebInterface/blob/master/edit/cfrecord.php

**Comment by ioannidesalex** [comment]
That would be great!

**Comment by ScIT-Raphael** [comment]
We currently close this issue - with the existing system we do not want to implement breadcrumbs. This may be integrated, if we find enough time to do a whole rewrite of the interface.
