### ISSUE TITLE
Feature Request: White List IP/FQDN

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#613]
The ability to white list an IP or FQDN on the web interface would be awesome. This would come in handy in many situations. Lets say there are 10 Email users at a location, one person is off-site and decides to change their password, now their outlook at the location is trying to auth now and fails the IP of the whole site gets blacklisted and no one can log in.

**Comment by ioannidesalex** [comment]
Very good idea and shouldn't be very hard to implement. Just add/modify ignoreip = xxx.xxx.xxx.xxx after [DEFAULT] in /etc/fail2ban/jail.local

**Comment by ghost** [comment]
Closing this issue as this is already possible from the Control Panel web UI by navigating to **Server**, click **fail2ban** to edit the configuration, and add the necessary _ignoreip_ option as mentioned by @ioannidesalex and save your changes.
