### ISSUE TITLE
Feature Request: NGINX upstream ip option

### ISSUE THREAD

**Issue by gitpush** [hestiacp/hestiacp#614]
NGINX is known for being an awesome reverse proxy solution, but templates for nginx must be changed manually, it would be great to have an option in panel to change some parameter such as the ip for the upstream option.
http://nginx.org/en/docs/http/ngx_http_upstream_module.html

Example: **%otherip%**

`upstream dockertemplate {
  server %otherip%:8087;
}

server {
  listen      %ip%:443 ssl http2;
  server_name %domain_idn% %alias_idn%;
...
...
...
`
This would be fantastic for docker or lxc.

**Comment by ScIT-Raphael** [comment]
Currently, we do not have enough resources to fullfill your request. If you would like to provide a own pr, please feel free, we will apply it after a review.

**Comment by estratos** [comment]
Need help on this guys?

**Comment by ScIT-Raphael** [comment]
@estratos We're always open for pull requests and additional help :)
