### ISSUE TITLE
Debian 10 missing package libapache2-mod-ruid2 causes files permissions issues

### ISSUE THREAD

**Issue by laraaj** [hestiacp/hestiacp#615]
In debian 10 default templates for Apache don't work because they are built with settings 
for Apache mod-ruid2 to mange the user PHP files is expected to run as, without mod-ruid2 
the scripts are run as default Apache user www-data, which end up preventing the web server from
writing to the user's owned folders and files.

I contacted Debian about the missing package and here is their response : 
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1706275.html

The best work around i found for this is to switch the Apache Hestia template to fastCGI 
"phpfcgid". 
You may also need to update your files and permissions to make sure the folders has execution 
right.  you can use something like this shell script : 

#!/bin/bash

find /home/*/web/*/public_html -type f -exec chmod u=rw,go=r {} \;
find /home/*/web/*/public_html -type d -exec chmod u=rwx,go=rx {} \;

**Comment by ScIT-Raphael** [comment]
The answer from debian sounds like the will not implement it again, because of missing work since 2013. Basicly I think we've to remove ruid support also in hestia and rework the restore routine. I'll have a look here and come back with more informations soon.

**Comment by laraaj** [comment]
mod ruid is essential because it's what the default Apache template relies on to execute PHP scripts 
as the owner of the PHP files. so if mod ruid2 is missing even in a new installation it will be an issue.
i think best solution for this is to set fastcgi as the default apache template for debian 10. 
take a look here to understand what I'm talking about : 
https://github.com/hestiacp/hestiacp/blob/master/install/deb/templates/web/apache2/default.tpl

The configuration specify some configuration for Apache mod itk if installed. but it's not installed by
default. plus i read it may have security and performance issues.
