### ISSUE TITLE
Error code: 3 after trying to save web settings for a domain.

### ISSUE THREAD

**Issue by laraaj** [hestiacp/hestiacp#616]
After restoring backups from VestaCP, some of the domains were showing the following error 
when i try to save the web settings for some domains from Hestia WebUI or even commands : 
Error code: 3

when investigated the issue turns out it has something to do with SSL disabled while let's encrypt is
is set to 'yes' in the user web configuration file : 
/usr/local/hestia/data/users/admin/web.conf

for example : 
DOMAIN='example.com' IP='11.11.11.11' IP6='' ALIAS='www.example.com' TPL='default' SSL='no' SSL_HOME='same' LETSENCRYPT='yes'

when i manually edit the file and change SSL='no' to SSL='yes' if fixes the problem 
also if you do the opposite and changed  LETSENCRYPT='yes' to LETSENCRYPT='no' fixes the problem.

The version of Operating system I'm using is : Debian 10
The version o HestiaCP I'm using is : 1.1.0 
Release is : release 
Web server is  : Nginx, Apache

**Comment by Lupul** [comment]
This inconsistency between SSL and LETSENCRYPT was present also in the web.conf file from vestacp backup?

**Comment by laraaj** [comment]
I just checked, no the inconsistency is only present in HestiaCP configuration files after the backup restore. the websites that got the inconstancy didn't have any  LETSENCRYPT variable set. so it seems after restore by default HestiaCP adds LETSENCRYPT and set it to yes without any check for the value 
of the variable SSL.

**Comment by ScIT-Raphael** [comment]
Fun fact: The restore is still based on the vesta restore routine, we did not had made a lot of changes here.

I noticed that you wrote, that you're on deb10 and master release branch. Can you write a bit more about how you upgraded your system to master release?

I'll try to reproduce the issue, as far as I understood your report, this happened only on restored web domains, that had a non let's encrypt ssl cert?

**Comment by laraaj** [comment]
I didn't upgrade to Debian 10 I migrated from one server to another one, 

My old server had Debian 8 with VestaCP, I was going to migrate to a new server so i chose to use the most recent operating system possible to avoid having to upgrade or migrate for few years and keep getting all the security patches ... 

I had the choice between Debian 10 or CentOS 8, VestaCP didn't support any of those so i kept 
looking and came across HestiaCP which seemed to have partial support in the master branch 
so I just tried it and had to hack the installer a little bit to get it to install after it installed it seemed to
work for as much as i needed. I already submitted my hacks of the installer as patches to HestiaCP
and they have been included in the master branch. 

then i restored the backups from my old server and had to do some tweaks here and there to 
get everything to work as it used to be. that's why i mentioned those problems i had to deal with 
and how i fixed them in case they were gonna help the project or someone else who is dealing with
the same issues. The issues i dealt with are submitted to the project here : 
https://github.com/hestiacp/hestiacp/issues/615
https://github.com/hestiacp/hestiacp/issues/617
https://github.com/hestiacp/hestiacp/issues/616

The worst issue with Debian 10 is the missing package libapache2-mod-ruid2 which causes the 
default VestaCP Apache templates not to work properly by preventing PHP from writing to files 
and folders owned by the user. 

I wish i had enough time to investigate these issues more and try to submit some fixes for it. too bad 
this is a production server and i need to be done with this as soon as possible because my old 
server is gonna expire soon. I really like your project, you are doing great work guys i will try to 
help as much as i can in the future.

Yes you are right in the issue only occurs for domains that didn't have SSL activated.

**Comment by ScIT-Raphael** [comment]
Ah I see, do you use the server already in active productive mode?

If you want to use release 1.1.0 aka master branch, I would suggest to use this way here: https://github.com/hestiacp/hestiacp/issues/568#issuecomment-521086717

So you won't have to tweak the current release installer and the most parts (expect the bugs you've reported) will work out of the box. But the usual warning: Infact that 1.1.0 aka master is not released yet, we do not suggest to use it on productive servers.

I'll checkout the restore issue you had for ssl, for ruid2 we will have to remove the support and also create some catchup routine if you want to restore ruid2 templates.

Thanks for your issue reports, let me know if you find anything else during the use of hestia. We're glad to help out and also have additional feedback to improve our project!

**Comment by laraaj** [comment]
Thanks for your advise I'm a professional server administrator, and developer. I manage servers for 
living. so it's always fun to have to fix issues as long as it's not related to data getting hacked. I also have
backups setup and everything. for now everything seems to be working just fine. and if there is gonna 
be any issues i will be able to handle it.

The SSL issue is not related to mod ruid2 missing in any way. those are two separate issues. 
the lack of mod ruid will cause permission issues even with new installation. because PHP is executed
as Apache default user www-data not the owner of the PHP files. while www-data doesn't have 
permission to access the user's data. 
the SSL issue only occurs when restoring backups from VestaCP backups for domains that didn't
have SSL activated in VestaCP. 

I already found work around these issues and shared here in case others had to deal with it or if it's 
gonna help the project in anyway. 

Thanks again for all the great work you are doing.

**Comment by Lupul** [comment]
@laraaj i'm preparing a fix for this. 

Can you add the unset line to  /usr/local/hestia/bin/v-restore-user at line 292 and check if the restore works correctly after?
```diff
289   # Restoring web domain 
290   for domain in $domains; do 
291      echo -e "$(date "+%F %T") $domain" |tee -a $tmpdir/restore.log 

+ unset -v DOMAIN IP IP6 ALIAS TPL SSL SSL_HOME LETSENCRYPT FTP_USER FTP_MD5 BACKEND PROXY PROXY_EXT STATS STATS_USER STATS_CRYPT U_DISK
```
