### ISSUE TITLE
After restoring VestaCP backups websites Show database connection errors

### ISSUE THREAD

**Issue by laraaj** [hestiacp/hestiacp#617]
After restoring backups from VestaCP to HestiaCP the websites fails to connect to the database 
using the database username and password in the configuration files although the database 
is successfully restored. 

This problem is related to Database passwords restore process malfunctioning either not using 
the same passwords as in the backup or using different passwords. I didn't have a chance to 
check the code. 

A work around is to manually update the passwords for each database from HestiaCP webUI 
or commands to match same passwords in the website's configuration file. 

The version of Operating system I'm using is : Debian 10
The version o HestiaCP I'm using is : 1.1.0
Release is : release
Web server is : Nginx, Apache
Database version is : mariadb  Ver 15.1 Distrib 10.4.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Database version in the old server is : mysql  Ver 14.14 Distrib 5.5.62, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by vvcares** [comment]
mostly your DB passwords are corrupted & we faced this issue few months back. You may need to setback the passwords again on all your databases. Just try one DB and make sure it works..

**Comment by Lupul** [comment]
Check if the backup archive contains valid database hashes. I've looked into this some month back and found that mysql password/hashes were missing from backup.

**Comment by Lupul** [comment]
Duplicate: https://github.com/hestiacp/hestiacp/issues/415 https://github.com/hestiacp/hestiacp/issues/548
