### ISSUE TITLE
Website won't load correctly

### ISSUE THREAD

**Issue by Tristan370** [hestiacp/hestiacp#619]
### **Created a new user account at my HestiaCP**
- Installed WordPress on my domain (Working Page with working login)
- I transferred my current working website to my new HestiaCP account i created. 

### Problem

- Website does not load anymore. Only able to see the Hestia Welcome message. 
[**Image**](https://centralex.s3.ap-east-1.amazonaws.com/images/5418ba4d-a0c3-4bfb-b720-2e0ed5d3ab85.jpg)
> Your new web server is ready to use.

I should be able to see my normal main website instead this welcome page. How can i resolve this problem?

### System
- AWS EC2
- Ubuntu 18.04LTS
- Basic HestiaCP installation

Thanks in advanced

**Comment by alber-khan** [comment]
Delete index.html from public_html

**Comment by Lupul** [comment]
Problem was solved after adding missing web alias 
https://forum.hestiacp.com/t/website-wont-load-after-migration-from-vestacp/254/10
