### ISSUE TITLE
Roundcube Connection to storage server failed

### ISSUE THREAD

**Issue by fianbiasa** [hestiacp/hestiacp#620]
### In a few words, please describe the issue that you're experiencing:
i got an error Connection to storage server failed, while login to RoundCube (fresh Install HestiaCP)

### What steps did you take when the issue occured? 
1. Attempt to login to mail server via RoundCube and external app
2. RoundCube responds with "Connection to storage server failed", external app just fails

### Expected behavior:
Please enter your response here (e.g. A list of hosted web domains should appear).

### Operating system distribution and release:
Ubuntu 16.04 LTS

### Which version of Hestia Control Panel is currently installed?
VERSION='1.0.6'

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
After a clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)
- PostgreSQL

### In order to better assist, please post any relevant log information below:
Oct 25 07:27:04 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 07:27:04 ssl-params: Info: Generating SSL parameters
Oct 25 14:34:42 ssl-params: Info: SSL parameters regeneration completed
Oct 25 15:08:11 pop3-login: Info: Disconnected (no auth attempts in 1 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, TLS, session=<jaOmpreVvO0zW9RP>
Oct 25 15:10:23 pop3-login: Info: Disconnected (no auth attempts in 1 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, TLS, session=<Ou2KrreV9oczW9RP>
Oct 25 16:50:37 imap-login: Info: Disconnected (no auth attempts in 3 secs): user=<>, rip=92.118.160.17, lip=172.104.189.15, TLS handshaking: Disconnected, session=<2wkAFbmV2OhcdqAR>
Oct 25 17:00:30 imap-login: Info: Disconnected: Too many invalid commands (no auth attempts in 0 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, session=<5eJhOLmVduMzW9RP>
Oct 25 17:50:42 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:50:54 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:10 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:33 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:56 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 18:11:10 pop3-login: Info: Disconnected: Too many bad commands (no auth attempts in 0 secs): user=<>, rip=51.91.212.81, lip=172.104.189.15, session=</+kZNbqV+sUzW9RR>
Oct 25 21:30:09 imap-login: Info: Disconnected (no auth attempts in 10 secs): user=<>, rip=159.203.201.0, lip=172.104.189.15, session=<d9+2/LyV1K6fy8kA>
Oct 25 22:20:38 auth: Info: passwd-file(nologin@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:20:50 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:16 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:27 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:47 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 23:12:43 master: Warning: Killed with signal 15 (by pid=8827 uid=0 code=kill)
Oct 25 23:13:41 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:17:39 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4220, secured, session=<yBYrfb6VUrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:17:39 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:17:39 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:19:31 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4323, secured, session=<2CHWg76VZrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:19:31 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:19:31 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:22:37 master: Warning: Killed with signal 15 (by pid=4709 uid=0 code=kill)
Oct 25 23:23:24 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:23:34 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4733, secured, session=<d0RSkr6VgrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:23:34 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:23:34 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:24:43 master: Warning: Killed with signal 15 (by pid=4777 uid=0 code=kill)
Oct 25 23:24:44 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:24:54 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4810, secured, session=<+xkWl76VhrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:24:54 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:24:54 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:25:07 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=5091, secured, session=<wFLZl76VlLMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:25:07 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:25:07 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:25:41 master: Warning: Killed with signal 15 (by pid=5158 uid=0 code=kill)
Oct 25 23:25:41 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:25:42 master: Warning: Killed with signal 15 (by pid=5217 uid=0 code=kill)
Oct 25 23:25:42 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:25:51 master: Warning: Killed with signal 15 (by pid=5272 uid=0 code=kill)
Oct 25 23:25:52 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:25:58 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=5289, secured, session=<lwTrmr6VmrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:25:58 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:25:58 imap: Error: Invalid user settings. Refer to server log for more information.
root@server:~# sed -i "s#namespace inbox {#namespace inbox {\n  inbox = yes#" /etc/dovecot/conf.d/15-mailboxes.conf
root@server:~# sudo service dovecot restart
root@server:~# cat /var/log/dovecot.log
Oct 25 07:27:04 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 07:27:04 ssl-params: Info: Generating SSL parameters
Oct 25 14:34:42 ssl-params: Info: SSL parameters regeneration completed
Oct 25 15:08:11 pop3-login: Info: Disconnected (no auth attempts in 1 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, TLS, session=<jaOmpreVvO0zW9RP>
Oct 25 15:10:23 pop3-login: Info: Disconnected (no auth attempts in 1 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, TLS, session=<Ou2KrreV9oczW9RP>
Oct 25 16:50:37 imap-login: Info: Disconnected (no auth attempts in 3 secs): user=<>, rip=92.118.160.17, lip=172.104.189.15, TLS handshaking: Disconnected, session=<2wkAFbmV2OhcdqAR>
Oct 25 17:00:30 imap-login: Info: Disconnected: Too many invalid commands (no auth attempts in 0 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, session=<5eJhOLmVduMzW9RP>
Oct 25 17:50:42 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:50:54 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:10 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:33 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:56 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 18:11:10 pop3-login: Info: Disconnected: Too many bad commands (no auth attempts in 0 secs): user=<>, rip=51.91.212.81, lip=172.104.189.15, session=</+kZNbqV+sUzW9RR>
Oct 25 21:30:09 imap-login: Info: Disconnected (no auth attempts in 10 secs): user=<>, rip=159.203.201.0, lip=172.104.189.15, session=<d9+2/LyV1K6fy8kA>
Oct 25 22:20:38 auth: Info: passwd-file(nologin@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:20:50 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:16 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:27 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:47 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 23:12:43 master: Warning: Killed with signal 15 (by pid=8827 uid=0 code=kill)
Oct 25 23:13:41 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:17:39 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4220, secured, session=<yBYrfb6VUrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:17:39 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:17:39 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:19:31 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4323, secured, session=<2CHWg76VZrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:19:31 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:19:31 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:22:37 master: Warning: Killed with signal 15 (by pid=4709 uid=0 code=kill)
Oct 25 23:23:24 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:23:34 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4733, secured, session=<d0RSkr6VgrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:23:34 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:23:34 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:24:43 master: Warning: Killed with signal 15 (by pid=4777 uid=0 code=kill)
Oct 25 23:24:44 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:24:54 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4810, secured, session=<+xkWl76VhrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:24:54 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:24:54 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:25:07 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=5091, secured, session=<wFLZl76VlLMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:25:07 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:25:07 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:25:41 master: Warning: Killed with signal 15 (by pid=5158 uid=0 code=kill)
Oct 25 23:25:41 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:25:42 master: Warning: Killed with signal 15 (by pid=5217 uid=0 code=kill)
Oct 25 23:25:42 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:25:51 master: Warning: Killed with signal 15 (by pid=5272 uid=0 code=kill)
Oct 25 23:25:52 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:25:58 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=5289, secured, session=<lwTrmr6VmrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:25:58 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:25:58 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:29:59 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=5358, secured, session=<kz89qb6VtLMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:29:59 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:29:59 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:30:14 master: Warning: Killed with signal 15 (by pid=5773 uid=0 code=kill)
Oct 25 23:30:14 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:30:28 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=5788, secured, session=<e9X0qr6VyLMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:30:28 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:30:28 imap: Error: Invalid user settings. Refer to server log for more information.
root@server:~# cat /var/log/dovecot.log
Oct 25 07:27:04 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 07:27:04 ssl-params: Info: Generating SSL parameters
Oct 25 14:34:42 ssl-params: Info: SSL parameters regeneration completed
Oct 25 15:08:11 pop3-login: Info: Disconnected (no auth attempts in 1 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, TLS, session=<jaOmpreVvO0zW9RP>
Oct 25 15:10:23 pop3-login: Info: Disconnected (no auth attempts in 1 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, TLS, session=<Ou2KrreV9oczW9RP>
Oct 25 16:50:37 imap-login: Info: Disconnected (no auth attempts in 3 secs): user=<>, rip=92.118.160.17, lip=172.104.189.15, TLS handshaking: Disconnected, session=<2wkAFbmV2OhcdqAR>
Oct 25 17:00:30 imap-login: Info: Disconnected: Too many invalid commands (no auth attempts in 0 secs): user=<>, rip=51.91.212.79, lip=172.104.189.15, session=<5eJhOLmVduMzW9RP>
Oct 25 17:50:42 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:50:54 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:10 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:33 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 17:51:56 auth: Error: passwd-file(info,67.211.213.194): stat(/etc/exim4/domains//passwd) failed: No such file or directory
Oct 25 18:11:10 pop3-login: Info: Disconnected: Too many bad commands (no auth attempts in 0 secs): user=<>, rip=51.91.212.81, lip=172.104.189.15, session=</+kZNbqV+sUzW9RR>
Oct 25 21:30:09 imap-login: Info: Disconnected (no auth attempts in 10 secs): user=<>, rip=159.203.201.0, lip=172.104.189.15, session=<d9+2/LyV1K6fy8kA>
Oct 25 22:20:38 auth: Info: passwd-file(nologin@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:20:50 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:16 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:27 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 22:21:47 auth: Info: passwd-file(support@lentra.co.id,219.150.116.52): unknown user
Oct 25 23:12:43 master: Warning: Killed with signal 15 (by pid=8827 uid=0 code=kill)
Oct 25 23:13:41 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:17:39 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4220, secured, session=<yBYrfb6VUrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:17:39 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:17:39 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:19:31 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4323, secured, session=<2CHWg76VZrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:19:31 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:19:31 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:22:37 master: Warning: Killed with signal 15 (by pid=4709 uid=0 code=kill)
Oct 25 23:23:24 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:23:34 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4733, secured, session=<d0RSkr6VgrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:23:34 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:23:34 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:24:43 master: Warning: Killed with signal 15 (by pid=4777 uid=0 code=kill)
Oct 25 23:24:44 master: Info: Dovecot v2.2.22 (fe789d2) starting up for imap, pop3 (core dumps disabled)
Oct 25 23:24:54 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=4810, secured, session=<+xkWl76VhrMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:24:54 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:24:54 imap: Error: Invalid user settings. Refer to server log for more information.
Oct 25 23:25:07 imap-login: Info: Login: user=<admin@virel.media>, method=PLAIN, rip=::1, lip=::1, mpid=5091, secured, session=<wFLZl76VlLMAAAAAAAAAAAAAAAAAAAAB>
Oct 25 23:25:07 imap(admin@virel.media): Error: User initialization failed: namespace configuration error: Duplicate namespace prefix: ""
Oct 25 23:25:07 imap: Error: Invalid user settings. Refer to server log for more information.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by Lupul** [comment]
Hello @fianbiasa 

- What command have you used to install HestiaCP.

Do you have a reason to use ubuntu 16.04 instead of the latest LTS 18.04?

**Comment by fianbiasa** [comment]
@Lupul hai... i use default command from hestiacp.com :
- wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
and
- bash hst-install.sh

I used to use runcloud, and for the ubuntu 16.04 LTS version it still supports PHP 5.6

whereas Ubuntu 18.04 has a minimum of PHP 7.

my reason is, sometimes there are still php applications version 5.6 that I use.

This is the first day I use HestiaCP, so I don't understand.

previously used VestaCP

**Comment by Lupul** [comment]
HestiaCP comes with multiphp support (--mutiphp installer flag) for php5.6, 7.0, 7.1, 7.2 and 7.3, so you could use 18.04 without issues.

I wil try to reproduce your issue on 16.04 and will get back to you

**Comment by Lupul** [comment]
Remove /etc/dovecot/15-mailboxes.conf and restart dovecot: `service dovecot restart`

duplicate https://github.com/hestiacp/hestiacp/issues/222
