### ISSUE TITLE
Bug: v-restore-user doesn't add user to hestia-users group

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#622]
### In a few words, please describe the issue that you're experiencing:
When you create a new user via v-restore-user script (not previously created user), this user is not added in hestia-users group

### What steps did you take when the issue occured? 
Restore user via cli (v-restore-user script)

### Expected behavior:
Newly created user should be added to hestia-users group

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
both

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by Lupul** [comment]
Already fixed in master : https://github.com/hestiacp/hestiacp/commit/54c3c73a9ac0016eed14697c43ef19f80fd89218#diff-a404511f6d4c6c365eabd654b3ff9848R27-R39
Part of https://github.com/hestiacp/hestiacp/pull/567 PR
