### ISSUE TITLE
Database daily backup missing Stored_Procedures & Routines

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#625]
Database daily backup missing Stored_Procedures & Routines..

We running a Laravel apps which need some SP & Routines from mysql database. We created and all works well.
While our failover check, the HestiaCP daily bakcup > db backups not included the SP & Routines. We could see the normal tables but not Mysql SP&Routines.

Expectation from Hestia team..
1. As a hosting provider to end clients, Is there any major security issues on let use the mysql SP & Routines by PHP scripts? If not, shall we include this option into the daily db bkps?
2. We tested to delete all the table smanually & found the Routines are not dropped & we have to drop them manually. So if Hestia going to add routines to be bakp, have to makesure, while we restore the dbs, the existing routines must be dropped as well. Or it will cause restoration fails - may be..

**Comment by ScIT-Raphael** [comment]
Fixed from @gdarko, thanks for the awesome commit!
