### ISSUE TITLE
multiple IPs vs letsencrypt for mail-domains

### ISSUE THREAD

**Issue by FalzoMAD** [hestiacp/hestiacp#626]
### In a few words, please describe the issue that you're experiencing:
on servers with multiple IPs nginx automatically uses one fixed IP for all mail-domains, regardless which one is set for the according web-domains. 
letsencrypt will eventually fail if the IPs differ at least while using an external DNS server and not setting different IPs for mail/webmail (which might not be wanted anyway)
from the looks of it for mail domains the first IP in order is used always

### What steps did you take when the issue occured? 
- add a domain to web domains including mail functionality and using an IP higher up
- try to create an ssl LE cert for the mail-domain

### Expected behavior:
nginx.conf for ssl LE certification for mail-domains using the same IP as set for the regular web-domain

### Operating system distribution and release:
debian 9

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
regular (clean) install
### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
**no** DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by Lupul** [comment]
Try adding the following line to $HESTIA/bin/v-add-sys-webmail at line 39
```
local_ip=$(get_object_value 'web' 'DOMAIN' "$domain" '$IP')
```
and then run `v-rebuild-mail-domain user domain.tld`

**Comment by Lupul** [comment]
Fixed in: https://github.com/hestiacp/hestiacp/commit/d998502346ec5f703ca185936caeee2793d275dc
Please let me know if it works for you , I have tested it only on `master` branch not on `release`

**Comment by vvcares** [comment]
seems this issue request same as : https://github.com/hestiacp/hestiacp/issues/263

**Comment by Lupul** [comment]
@vvcares can you check if the latest master solved your issue? exim and webmail are now using the same ip as the web domain

**Comment by vvcares** [comment]
hi, im bit confused.
I may rephrase my another post's question again..
- As we have different IPs for web domains (2.2.2.2), but our server has only one EXIM4 instance and the ip is the main server's IP (1.1.1.1) only, due to the PTR records.
- The proxy IP cant resolve as PTR records. So we must use the server's ip only for EXIM4 (1.1.1.1).

Is this statement valid in your point of view?

**Comment by FalzoMAD** [comment]
@Lupul while the issue might be kind of similar, I think @vvcares problem is the dns zone entry, which for the mx/mail obviously gets set to the IP of the web domain, but if I understood it correctly that's unwanted in his case.

I am not using the internal DNS at all, so my issue is not related to _that_ after all ;-)

@vvcares I am not familiar with Hestias handling of DNS to be honest, but probably you can create your own nameserver templates to use and make the mail/mx entry static? again, if you have different IPs there LetsEncrypt eventually will not work, because it needs a webserver reachable on your server for the verification process, which might not work, if you need web traffic to go through a proxy instead.

**Comment by FalzoMAD** [comment]
@Lupul I can confirm this works now. somehow it gave a LE 400 error first which got me confused, however it changed the IPs correctly in the webmail configs for apache and nginx. I restarted both just in case... maybe we need to check again, if it really restarts both services after the rebuild.

**Comment by FalzoMAD** [comment]
@Lupul sorry, but I need to reopen this - just came across an unexpected follow-up problem:

I setup a domain as web-domain with another tld being an alias for it. then added this secondary domain as a mail domain, which made apache refuse to restart - simply because it could not get and set $local_ip for that domain. 

there obviously is none if the domain is just an alias and no web domain itself, so we need some kind of fallback as this will happen for all domains that don't have a primary web-domain entry...

PS: seems to affect the nginx conf file for that secondary as well, though nginx just did not reload and keeps on running, butt effectly hinders any further changes via the web panel...

**Comment by Lupul** [comment]
Your setup should have worked correctly, mail domains without a corresponding web domain will fallback to dedicated user IP if present  or default system IP.
But there looks to be a bug that I didn't catch in previous testing, will get back shortly with a fix.
