### ISSUE TITLE
Feature Request: New Roundcube Webmail 1.4 Stable Released

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#632]
Any chance on including the new Roundcube Webmail 1.4 release. Currently Roundcube is based off the version the distribution packages, but it would be really handy to include 1.4 as its an amazing improvement and is mobile responsive. This could be implemented similar to how PhpMyAdmin is implemented in HestiaCP.

**Comment by ghost** [comment]
We're planning on moving to our own Roundcube package in a future release, but can't commit to a timeline right now.

**Comment by ghost** [comment]
Closing this one for now as we plan to move from the repository-provided Roundcube package to using the upstream source directly in an upcoming release (this will happen after 1.1.0, but can't comment on when exactly at this time).
