### ISSUE TITLE
Apache remoteip config is missing from Ubuntu installer

### ISSUE THREAD

**Issue by Lupul** [hestiacp/hestiacp#633]
Debian installer is configuring apache2 remoteip module, but the ubuntu installer does not
https://github.com/hestiacp/hestiacp/blob/master/install/hst-install-debian.sh#L1703-L1721

Affected versions release 1.0.6 and master.

**Comment by ghost** [comment]
Fixed in a65bc29e86197c9aa5a5773f6f2bafb8293819c8.
