### ISSUE TITLE
Wrong dns domain IP after changing web domain IP

### ISSUE THREAD

**Issue by Lupul** [hestiacp/hestiacp#634]
Changing web domain IP is also updating the DNS domains records with the new IP but it is using the local server IP even when a public / nat ip is configured.

Affected versions: master and all previous releases

**Comment by ghost** [comment]
I can confirm this behavior occurs after adding a secondary IP address to the server with NAT IP assignment, does not appear to happen out of the box with a single IP.

**Comment by ScIT-Raphael** [comment]
@Lupul Any status update about this issue?
