### ISSUE TITLE
Feature Request: Add PHP 7.4 support, set as default on new installations

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#637]
### In a few words, please describe the issue that you're experiencing:
PHP 7.4 will be release on 28 November 2019. It should:

- Be set as default on new installations
- Add support for MultiPHP
- Option to upgrade current Hestia Installations running older versions to 7.4.

**Comment by ScIT-Raphael** [comment]
Thansk for the request: PHP 7.4 has been added to MultiPHP system (https://github.com/hestiacp/hestiacp/commit/6635019eb058dfe5366d680d5021252d01fe1f6d) and the Hestia Backend Service (https://github.com/hestiacp/hestiacp/commit/c7daefae171e0d91efb599243288d9dfec878590).

As discussed in internal develop chat, we will wait a bit to set it as default value during new installations.

A option for upgrade current hestia installations is a good idea, we will get that checked.

**Comment by ghost** [comment]
Closing as PHP 7.4 support has been added to Multi-PHP and backend, and will be set as default in a future release as per @ScIT-Raphael.

**Comment by vikasprogrammer** [comment]
I am running 1.0.6 and I don't see this in my dropdown:

<img width="420" alt="Screenshot 2020-01-30 at 1 09 56 PM" src="https://user-images.githubusercontent.com/1262327/73429524-e1f46380-4361-11ea-93c4-eea98e5930a3.png">

**Comment by ScIT-Raphael** [comment]
Please check the changelog, php74 has added in v1.1.0 which will be released within a few day.
