### ISSUE TITLE
Wrong URL on Web UI notifications

### ISSUE THREAD

**Issue by ifaist0s** [hestiacp/hestiacp#638]
### In a few words, please describe the issue that you're experiencing:
After Hestia is updated to a new version, a notification appears at the top right of the WEB UI, stating the update that has been done and to report possible issues at the URL ```https://github.com/hestiacp/hestiacp/Issues``` But this URL is not correct. The last part "Issues" starts with a capital "I" instead of a small one.
![image](https://user-images.githubusercontent.com/998239/69910609-e14d5880-1416-11ea-924d-d76548295c95.png)

### What steps did you take when the issue occured? 
1. Just wait when Hestia updates itself
2. Check the notifications
3. Click on the report bugs link

### Expected behavior:
The link should point to the correct URL https://github.com/hestiacp/hestiacp/issues

### Operating system distribution and release:
Ubuntu 18.04.3 LTS

### Which version of Hestia Control Panel is currently installed?
VERSION='1.0.6'

### Which branch are you using?
develop

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation of version 1.0 and then automatic updates to version 1.0.6

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Nginx + PHP-FPM
- Multi-PHP
- PHP-FPM + Multi-PHP
- DNS
- MySQL
- Exim
- Dovecot
- FTP
- Fail2ban

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)
- PostgreSQL

### Additional info
I did a search in the repository and I think we need corrections at: 
1.  [hestiacp/install/hst-install-debian.sh](https://github.com/hestiacp/hestiacp/blob/0f33f69736e55f2db19ada543f5bc6bebf77bca8/install/hst-install-debian.sh#L1839)
2. [install/hst-install-ubuntu.sh](https://github.com/hestiacp/hestiacp/blob/74141033208aad3143cf138684d1a90019a7d761/install/hst-install-ubuntu.sh#L1734)

I'm not sure though if these are the only lines that need to be corrected.

**Comment by ScIT-Raphael** [comment]
Thanks for your issue report! The part during upgrade was already solved with the following commit: https://github.com/hestiacp/hestiacp/commit/fa2b5856b963a93a80fa4a7d0b64c517fa6a1b17

I also fixed the issue in the installer files with the following commit: https://github.com/hestiacp/hestiacp/commit/552e61eba9979c9af2b59272fd1d9a4f77c40416

I'll close the issue due to the fixes, please reopen or add a new one if you would find anything else!
