### ISSUE TITLE
Suggestion: Integrate "automysqlbackup" for simpler mysql backups and "Tuning-Primer.sh" for easy mysql config tuning

### ISSUE THREAD

**Issue by animeai** [hestiacp/hestiacp#642]
Integrate https://sourceforge.net/projects/automysqlbackup/ for a more robust mysql only backup. Often users will only want or need to restore a database rather than a full site backup. Having the option for separated mysql backups running on a different frequency to the main site backups would be advantageous.

Currently HestiaCP gives no help or tips for tuning mysql performance. https://github.com/BMDan/tuning-primer.sh is a simple bash script that would help the server admin perform this task. It would be useful to implement in conjunction with the current simple web based my.cnf editor in the configuration section of the control panel. This should help most server admins fine tune their mysql setup.

**Comment by ScIT-Raphael** [comment]
Thanks for your suggestions: We anyway want to improve the backup process :). MySQL only backups can be done with phpmyadmin, if multiple backups should be done, this would be a simple few line bash script (mysqldump).

About the mysql performance: We ship already optimized configuration, but this depends on whatever a sysadmin wants to have or run - so there is no easy way to fullfill the optimal solution for everyone.
