### ISSUE TITLE
Feature Request: Mail Account Details

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#645]
Some mail account details on the mail account listing page would provide to be very useful.

- Last Login timestamp (this could be by webmail/imap or pop3)

Some other ones
- Last Email Timestamp (either sent or received)
- Mail count
- Delete Spam and Trash

When last login timestamp is clicked it could show the last 5 logins for example 

Timestamp - IP - Type (imap,pop3) - Mail Client used for example (iphone applemail or windows 10 - outlook 2019 or webmail)

**Comment by ghost** [comment]
Hey @johnnyq,

Adding the last login timestamp for a mailbox user is a good idea for security review purposes, so we'll discuss that one internally to see what can be done for a future release. 

From an administrative perspective, I believe that the disk usage consumed by the mailbox should be enough of a general overview. We do not want to expose too much information at the Control Panel level, as the contents and activity of a users mailbox should be considered private and we do not offer true account impersonation as what you'd find with Microsoft Exchange (and is also outside of the scope of Hestia's mail server, which as you know is a simple POP3/IMAP/SMTP implementation and will remain as such for the time being -- for more advanced functionality, a solution like Exchange or Gmail is recommended).  

As for control over deleting Trash and Spam contents of a mailbox, we can look at adding greater control at the server or domain level to perform automatic clean up after a set amount of days (30-60 days for example).

**Comment by johnnyq** [comment]
sounds good, @kristankenney I agree the disk space is enough, and the idea of having cron clean trash and spam at the domain level is perfect.

**Comment by ScIT-Raphael** [comment]
Viewable quota has been added to roundcube on master branch, I also vote for show the last login timestamp, sounds like a good feature, will have a look how we can solve this.

**Comment by jlguerrerosanz** [comment]
Add a comment field

**Comment by ScIT-Raphael** [comment]
Infact we moved this feature request around since nearly two years, we decided to close it: We currently do not have enough time to implement such a function, also it isnt on our highest priority. Please feel free to provide a PR for it, we would love to implement it.
