### ISSUE TITLE
Linode auto deploy hestia

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#647]
Hi everyone;

Apparently already 5 instances use my "script" to deploy Hestia on Linode which is I tested with Debian9 and Ubuntu18

I'll be glab if anyone could try it and see if it's trully publicly avaible and working
it should be available via the **Community Stackscripts**
under **jdumont/hestia**

**Comment by ghost** [comment]
@JOduMonT,

Thanks for your submission. To clarify, are you referring to https://github.com/JOduMonT/Debian/blob/master/hestia-install.sh?

**Comment by JOduMonT** [comment]
@kristankenney it is based on it but no this is not
it is in the stackscripts community https://cloud.linode.com/stackscripts
![image](https://user-images.githubusercontent.com/5204724/70688295-00d06500-1ce4-11ea-81d0-17c7c4868ff7.png)

**Comment by ghost** [comment]
The script appears to only be available to those who have an active Linode account, not publicly.

**Comment by JOduMonT** [comment]
Ok; 
my questions were more

1. if it's something HestiaCP is interesting to promote as a way to quick install it

2. to validate if someones with an account will have access to it / could find it which is yes because this screenshot was took from another account then mine and 5peoples actively using it
![image](https://user-images.githubusercontent.com/5204724/70768323-33876580-1d97-11ea-8afb-aba130a28001.png)
