### ISSUE TITLE
v-backup-user admin is overwriting the old backup 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#648]
### In a few words, please describe the issue that you're experiencing:
when i run this command via SSH
sudo /usr/local/hestia/bin/v-backup-user admin 
![image](https://user-images.githubusercontent.com/39749258/70709482-fa051a80-1d02-11ea-871b-51eff444fa0f.png)

it overwrites old backup and only showing one backup in panel
![image](https://user-images.githubusercontent.com/39749258/70709503-038e8280-1d03-11ea-955f-34513e134150.png)

### What steps did you take when the issue occured? 
i'm trying to run a cronjob to take a backup every 6 hours but when I run this command to test if it's working or not i notice every time it delete the old backup or overwrites them (i'm not sure) 

### Expected behavior:
whenever I create a backup manually via Panel it doesn't delete the old backup, so I'm expecting when I run this command v-backup-user admin via ssh or cronjob it should not delete old backup

### Operating system distribution and release:
Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your response here (e.g the feature stopped working after upgrading to the latest release)

when I run this command v-backup-user admin via ssh or cronjob

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.
there are no logs in /backup

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ghost** [comment]
The number of backups to keep is defined by the package assigned to the user. The default package is currently configured to keep one backup (as the cronjob is initially set to run on a 24-hour basis, so one backup per day).
