### ISSUE TITLE
Bug: mail() doesn't work with default php-fpm template

### ISSUE THREAD

**Issue by henri-hulski** [hestiacp/hestiacp#649]
I'm using Debian 10 and Hestia dev.

PHP mail() didn't work with the default  php-fpm template.
After removing the backslashes in
https://github.com/hestiacp/hestiacp/blob/master/install/deb/templates/web/php-fpm/default.tpl#L21
everything works fine.

So the correct line looks like:
```
php_admin_value[sendmail_path] = "/usr/sbin/sendmail -t -i -f admin@%domain%"
```
Before I had a really wired value for the `sendmail_path` PHP variable.
Something like `/usr/\/usr/sbin/sendmail -t -i -f admin@mydomain.com\`.
Now it's just `/usr/sbin/sendmail -t -i -f admin@mydomain.com`.

**Comment by henri-hulski** [comment]
The PHP docs even don't use quotation. So just
```
php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@%domain%
```
See Example # 1 in https://www.php.net/manual/en/install.fpm.configuration.php.

**Comment by ghost** [comment]
Hi @henri-hulski, thanks for your issue report. We'll get this one fixed up shortly. :)
