### ISSUE TITLE
v-unsuspend-user and v-suspend-user getting error

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#650]
### In a few words, please describe the issue that you're experiencing:
Please enter your response here (e.g. When I click on the Web tab, a blank page is displayed).

### What steps did you take when the issue occured? 
while running v-unsuspend-user & v-suspend-user command via SSH 

![image](https://user-images.githubusercontent.com/39749258/70867228-2d60d700-1f99-11ea-9ddc-c2c147790812.png)

### Expected behavior:
I'm trying to integrate the command via API (which is working fine) but I'm gettings these errors so I ran the command line via ssh and i got the same error. 

### Operating system distribution and release:
Ubuntu 18.04.2

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
/usr/local/hestia/log/system.log

![image](https://user-images.githubusercontent.com/39749258/70867324-47e78000-1f9a-11ea-86ed-05a54ffd73a1.png)

2019-12-16 00:22:33 v-update-user-counters  'alber'
2019-12-16 00:22:33 v-rebuild-web-domain  'alber' 'alberkhan.com' 'no'
2019-12-16 00:22:33 v-suspend-web-domain  'alber' 'alberkhan.com' 'no'
2019-12-16 00:22:34 v-suspend-web-domains  'alber'
2019-12-16 00:22:34 v-suspend-dns-domain  'alber' 'alberkhan.com' 'no'
2019-12-16 00:22:34 v-suspend-dns-domains  'alber'
2019-12-16 00:22:35 v-delete-sys-webmail  'alber' 'alberkhan.com' 'yes'
2019-12-16 00:22:35 v-suspend-mail-domain  'alber' 'alberkhan.com'
2019-12-16 00:22:35 v-suspend-mail-domains  'alber'
2019-12-16 00:22:35 v-suspend-databases  'alber'
2019-12-16 00:22:35 v-suspend-cron-jobs  'alber'
2019-12-16 00:22:36 v-suspend-user  'alber'

---------------------

2019-12-16 00:23:36 v-unsuspend-web-domain  'alber' 'alberkhan.com' 'no'
2019-12-16 00:23:36 v-unsuspend-web-domains  'alber'
2019-12-16 00:23:36 v-unsuspend-dns-domain  'alber' 'alberkhan.com' 'no'
2019-12-16 00:23:36 v-unsuspend-dns-domains  'alber'
2019-12-16 00:23:37 v-unsuspend-mail-domain  'alber' 'alberkhan.com'
2019-12-16 00:23:37 v-unsuspend-mail-domains  'alber'
2019-12-16 00:23:37 v-unsuspend-databases  'alber'
2019-12-16 00:23:37 v-unsuspend-cron-jobs  'alber'
2019-12-16 00:23:38 v-unsuspend-user  'alber'

![image](https://user-images.githubusercontent.com/39749258/70867333-5f266d80-1f9a-11ea-84d1-4ed7d4ad73dd.png)

**Comment by alber-khan** [comment]
/usr/local/hestia/log/error.log

2019-12-16 00:21:00 v-delete-dns-record  'alber' 'alberkhan.com' '22' [Error 5]
2019-12-16 00:21:59 v-rebuild-web-domain  'alber' 'alberkhan.com' 'no' [Error 5]
2019-12-16 00:22:00 v-add-sys-webmail  'alber' 'alberkhan.com' 'yes' [Error 5]
2019-12-16 00:22:34 v-delete-dns-record  'alber' 'alberkhan.com' '22' [Error 5]
2019-12-16 00:23:36 v-rebuild-web-domain  'alber' 'alberkhan.com' 'no' [Error 5]
2019-12-16 00:23:37 v-add-sys-webmail  'alber' 'alberkhan.com' 'yes' [Error 5]

**Comment by ScIT-Raphael** [comment]
The error say that the domain alberkhan.com from user alber is already suspended, which let v-suspend-user run in a exception. Please try to unsuspend this dns first on cli (v-unsuspend-dns-domain alber alberkhan.com) or from backend inside the user. Then try to run again v-suspend-user if needed.

**Comment by alber-khan** [comment]
[![Watch the video](https://user-images.githubusercontent.com/39749258/70867995-cac00900-1fa1-11ea-8159-381ef3eebcfd.png)](https://youtu.be/zWf6MLJl4Wg)

**Comment by alber-khan** [comment]
Please check the video, still having the same issue.

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/70868103-0b6c5200-1fa3-11ea-8f6e-374a019717ec.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/70912746-a2381d80-203a-11ea-83e6-7b288bd9783d.png)

same issue with another user.

**Comment by beli42** [comment]
as
>  v-unsuspend-user alber

calls
>  v-unsupend-dns-domains alber

which iterates for all domains over
>  v-unsuspend-dns-domain domainname alber

i recommend to check the status of the users dns-domains:
get all dns-domains of the user foo
>  v-list-dns-domains alber

and afterwards for all listed domains:
>  v-list-dns-domain domainname alber

and check its suspend status.

Does it correlate with the gui output?

**Comment by alber-khan** [comment]
@beli42 still no luck

![image](https://user-images.githubusercontent.com/39749258/70930672-be988200-205b-11ea-967a-3d7db3a9864a.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/70930786-015a5a00-205c-11ea-9844-1e860eb25256.png)

Same error!

**Comment by beli42** [comment]
Sorry first for the wrong syntax, but you recognized it. Nice!

Let's check the real state of the user alber. What is the result of:
>  sudo egrep "^alber\:\!" /etc/shadow > /dev/null; echo $?

**Comment by Lupul** [comment]
Hello @4183r, thanks for your detailed report, I could reproduce this issue also on our test env (master branch).

Will investigate and get back when we have more info

**Comment by Lupul** [comment]
Fixed in master with the linked commit
@4183r let me know if it fixes for you or if you need help to apply the patch

**Comment by alber-khan** [comment]
@beli42 

![image](https://user-images.githubusercontent.com/39749258/70974407-b0834980-20cd-11ea-817d-46553fbeaa0a.png)

**Comment by ScIT-Raphael** [comment]
@4183r thanks for the answer, please check the post of @Lupul, the issue was fixed on master branch and will be published in a new release.
@beli42 thanks for your effort, please check discord when you've got some time :)

**Comment by alber-khan** [comment]
applying the patch boss be right back

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/70975434-f04b3080-20cf-11ea-93f0-6e08872ac8f5.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/70975520-1a045780-20d0-11ea-81a7-9852a794e844.png)

v-unsuspend-user is working fine i guess, i'm only getting the error while running and v-suspend-user

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/70975681-6780c480-20d0-11ea-997f-0cdbd2dc27fe.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/70976116-5b493700-20d1-11ea-85ed-146c15b945be.png)

 i commented that function and everything is working fine,

![image](https://user-images.githubusercontent.com/39749258/70976410-e9252200-20d1-11ea-9a7e-792f56a33112.png)

going to check if everything is working via API now.

**Comment by alber-khan** [comment]
Everything is working now. thank you so much! :)

**Comment by alber-khan** [comment]
@Lupul boss please check-in master /bin/v-suspend-user line 34

**Comment by Lupul** [comment]
`check_hestia_demo_mode` does not exist in 1.0.6, so that error was expected
