### ISSUE TITLE
Security: Add robots.txt to webmail 

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#654]
I noticed webmail and mail are coming up on google search index when our sites are searched, I dug further and noticed the mail URLs do not have a robots.txt to deny search engines from indexing them like phpmyadmin and Hestia Web Interface 8083 do.

**Comment by ScIT-Raphael** [comment]
Thanks for the request @johnnyq, has been implemented. phpmyadmin and hestia backend are already "protected" by robots.txt.
