### ISSUE TITLE
Changing webmail alias on configure server page wont affect on mail section link

### ISSUE THREAD

**Issue by hurtsky** [hestiacp/hestiacp#659]
### In a few words, please describe the issue that you're experiencing:
Changing webmail alias on configure server page wont affect on mail section link

### What steps did you take when the issue occured? 
1. Change mail alias on https://test.com:2096/edit/server/ to mail.test.com
2. Open https://test.com:2096/list/mail/ 
3. Click Open Webmail button and it will still redirect to webmail.test.com

This button bug also exist at page =
https://test.com:2096/list/mail/?domain=test.com&token=1234 

### Expected behavior:
all button to open the webmail should changed after been change on configure server page

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
1.0.6 

### Which branch are you using?
release

**Comment by ScIT-Raphael** [comment]
Hi @hurtsky 
Thanks for your issue report, this is a duplicate of https://github.com/hestiacp/hestiacp/issues/477 but has a better description. So I'll going to close 477 and let your issue report open - we will try to find a solution for this as soon as possible.

**Comment by ghost** [comment]
Hi @hurtsky,

This issue has been resolved with b60b904c2d35856d3d3c8196e25dc3c8b78822ee where the link now points to **mail.domain.tld**, which is always assumed to be reachable for correct operation of mail services (and redirects to the webmail client when accessed from a browser).

**Comment by hurtsky** [comment]
sorry, i just notice this changes, but isn't it still will be hardcoded? because we have function to change mail alias at https://test.com:2096/edit/server/ 
and why not just use ```$v_webmail_alias``` ?

@kristankenney  @ScIT-Raphael

**Comment by ScIT-Raphael** [comment]
The only value that is hardcoded is mail, if you want to use only mail, you can set an empty value for webmail alias.

I do not suggest this change after you've got running mail ssl domains - you'll probaly need to force renew the let's encrypt certs so they are working properly with your configuration.

**Comment by hurtsky** [comment]
thanks for the clarification , but what if the user change not using mail as their webmail alias? like post.domain.tld .

**Comment by ScIT-Raphael** [comment]
Mail is the most common domain name, it is hardcoded and can't be changed right now. Ypu're free to set webmail to post if you like to do so.
