### ISSUE TITLE
Feature Request: Statistics

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#660]
### In a few words, please describe the issue that you're experiencing:
Before the UI changes, you were able to view in the Global Statistics Tab Total Disk Usage seperately of Files (Web), Emails and Databases. Now you cannot get this data separately.

### Expected behavior:
The aforementioned functionality should be restored.

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Both

**Comment by ghost** [comment]
Implemented as of v1.4.
