### ISSUE TITLE
Enable automatic HTTP-to-HTTPS redirection randomly becomes disabled

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#661]
### In a few words, please describe the issue that you're experiencing:
I noticed this for awhile now sometimes some of my sites would not redirect to https. I noticed in the web interface that Enable automatic HTTP-to-HTTPS redirection was unchecked, even though it was checked before. This seems to randomly happen with some of my sites, and i'm not sure what may be causing it.

### Expected behavior:
Sites should hold their configuration value of  Enable automatic HTTP-to-HTTPS redirection unless changed manually.

### Operating system distribution and release:
Ubuntu 18.04.3

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
been happening for awhile on all my hestia instances

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by johnnyq** [comment]
I noticed this in my logs under the hestia web interface

02  Jan  2020 05:45:22 enabled ssl support for site.com
02  Jan  2020 05:45:21 disabled ssl support for site.com

looking at this date and time stamps, I noticed 
sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl runs at 5:45AM daily

but whats weird it only seemed to affect one of my sites at that time, ill continue to dig for more info and report back

**Comment by johnnyq** [comment]
I think I see what is going on, when a site attempts to get a lets encrypt cert around 5:45AM. it disabled ssl then re-enables it but forgets to re-enable "Enable automatic HTTP-to-HTTPS redirection" upon doing so.

**Comment by ScIT-Raphael** [comment]
Thanis for the issue report, the issue was already reported also in our internal dev chat, so unlucky but confirmed :).

I'll check the issue around tomorrow or this weekend and keep you up to date. Probaly the issue has his source here: https://github.com/hestiacp/hestiacp/blob/090d1501f947b8f9badc31b5dfb0aa2b057652ae/bin/v-add-letsencrypt-domain#L396-L397

**Comment by johnnyq** [comment]
That is Super!! Thanks @ScIT-Raphael
