### ISSUE TITLE
[security enhancement] Mysql - LOAD DATA LOCAL

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#663]
This is security enhancement request on hestiacp.
Hi team, thank you for the wonderful script for us. Just for your info, if you could consider this for hestiacp as default config setting. OR is there any dis-advantages for normal web hosting servers ?

disable *LOAD DATA LOCAL*  commands in MySQL by adding the following to the 
```
##[mysqld] section of /etc/mysql/my.cnf and restarting MySQL 
local-infile=0
```

Ref: https://dev.mysql.com/doc/mysql-security-excerpt/5.7/en/load-data-local.html

**Comment by ioannidesalex** [comment]
For what is worth @vvcares , I use local-infile=0 in my.cnf without any issues.

**Comment by ScIT-Raphael** [comment]
@vvcares can you please describe more about the setting? What would be the advantage of it? Infact that we use mariadb10.3/10.4, do we also need it?

**Comment by vvcares** [comment]
Hi Raphael,

Yes, MariaDB10.4.1 also listening this command.

I found this info via my CSF server checks. then i googled about this term & found many sources saying as it is vulnerable & is enabled on [mysqld] clients by default.

Ref:
https://mariadb.com/kb/en/load-data-infile/
https://www.percona.com/blog/2019/02/06/percona-responds-to-mysql-local-infile-security-issues/

Additional Note:
If LOCAL capability is disabled, on either the server or client side, a client that attempts to issue a LOAD DATA LOCAL statement receives the following error message:

`ERROR 1148: The used command is not allowed with this MySQL version`

**Comment by vvcares** [comment]
Hi, as i checked my '/etc/mysql/my.cnf', i dont see this fix.
My server is old hestia server with latest inplace upgrades to 1.1.0

**Comment by ScIT-Raphael** [comment]
Just checked on one of my upgraded systems, local-infile=0 is set there. did you modified symbolic-links? because this was took for detection: https://github.com/hestiacp/hestiacp/commit/0f5963e55f5c9a24152461167847613cd2471fef#diff-722e66b68190677c4ee2159764911cf7

**Comment by vvcares** [comment]
my '/etc/mysql/my.cnf' is an actual file, not sym link.

**Comment by ScIT-Raphael** [comment]
i think you didnt understood what I wrote, there is a sed and replace that checks for symbolic-links line and add the local-infile after this line. If you have modified or removed symbolic-links, the patch would not work.

**Comment by vvcares** [comment]
Hi, if you meant..
the SED command will earch for text string 'symbolic-links', if it found, then it will add the INFILE string ?

But my 'my.cnf' no any entries as symbolic-links. [https://file.io/HrXfAd](https://file.io/HrXfAd)

**Comment by ScIT-Raphael** [comment]
Yup, that's the problem. Probaly you removed the line in your config, patch is there and working, you need to modify your config on your own.

**Comment by vvcares** [comment]
kindly provide me the default hestia's 'my.cnf' file. So i could replace it. I will check if i made any manual modifications there. can?

**Comment by ScIT-Raphael** [comment]
https://github.com/hestiacp/hestiacp/tree/release/install/deb/mysql - depends on how much ram you have.

**Comment by vvcares** [comment]
Ok. noted. thank you.
But my suggestion, why you searching for custom text string instead of global static variables like '[mysqld]'  ?

If this global variable, there wont be fail.
