### ISSUE TITLE
After Reboot services not starting 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#665]
### In a few words, please describe the issue that you're experiencing:

After reboot services not starting 

![image](https://user-images.githubusercontent.com/39749258/71781838-34f42880-2ff9-11ea-821e-0d5f90732b5f.png)

### Expected behavior:
Services should start automatically after reboot 

### Operating system distribution and release:
Ubuntu 18.04.2

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
Backend will not help in this case: You need to check your system logs and also try to start them manually from cli/ssh to see if any error would occur. If you find anything in the system logs that sounds like a hestia issue, please post them here.

**Comment by alber-khan** [comment]
/var/log/mysql/error.log

2020-01-05 20:18:22 0 [Note] /usr/sbin/mysqld (initiated by: unknown): Normal shutdown
2020-01-05 20:18:23 0 [Note] Event Scheduler: Purging the queue. 0 events
2020-01-05 20:18:23 0 [Note] InnoDB: FTS optimize thread exiting.
2020-01-05 20:18:24 0 [Note] InnoDB: Starting shutdown...
2020-01-05 20:18:24 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2020-01-05 20:18:24 0 [Note] InnoDB: Instance 0, restricted to 2003 pages due to innodb_buf_pool_dump_pct=25
2020-01-05 20:18:24 0 [Note] InnoDB: Buffer pool(s) dump completed at 200105 20:18:24
2020-01-05 20:18:26 0 [Note] InnoDB: Shutdown completed; log sequence number 5552014231; transaction id 11191033
2020-01-05 20:18:26 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-01-05 20:18:26 0 [Note] /usr/sbin/mysqld: Shutdown complete

2020-01-05 20:23:29 0 [Note] InnoDB: Using Linux native AIO
2020-01-05 20:23:29 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-01-05 20:23:29 0 [Note] InnoDB: Uses event mutexes
2020-01-05 20:23:29 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-01-05 20:23:29 0 [Note] InnoDB: Number of pools: 1
2020-01-05 20:23:29 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-01-05 20:23:29 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2020-01-05 20:23:29 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-01-05 20:23:29 0 [Note] InnoDB: Completed initialization of buffer pool
2020-01-05 20:23:29 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-01-05 20:23:29 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-01-05 20:23:29 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-01-05 20:23:29 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-01-05 20:23:29 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-01-05 20:23:29 0 [Note] InnoDB: 10.4.11 started; log sequence number 5552014231; transaction id 11191035
2020-01-05 20:23:29 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-01-05 20:23:29 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-01-05 20:23:29 0 [Note] Server socket created on IP: '::'.
2020-01-05 20:23:29 0 [Note] Reading of all Master_info entries succeeded
2020-01-05 20:23:29 0 [Note] Added new Master_info '' to hash table
2020-01-05 20:23:29 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.4.11-MariaDB-1:10.4.11+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2020-01-05 20:23:32 0 [Note] InnoDB: Buffer pool(s) load completed at 200105 20:23:32

**Comment by ScIT-Raphael** [comment]
It does not help when you just provide a log of mysql. As I wrote: Post a error log if it is related tp hestia, your is clearly not. Did you checked you services manualy?

**Comment by ioannidesalex** [comment]
Also, I don’t see any errors in the MariaDB log. Just notes.

**Comment by alber-khan** [comment]
> Backend will not help in this case: You need to check your system logs and also try to start them manually from cli/ssh to see if any error would occur. If you find anything in the system logs that sounds like a hestia issue, please post them here.

I tried restarting server 3-4 times and I can confirm the services aren't starting automatically each time so I have to manually start the service via SSH and I was able to start them via the panel. 

/usr/local/hestia/log/error.log

2020-01-04 02:00:06 v-update-sys-rrd-mysql  'daily' [Error 15]
2020-01-05 20:20:03 v-update-sys-rrd-mysql  'daily' [Error 15]

I'm not sure where to look for boot logs.

**Comment by alber-khan** [comment]
i was looking for a MySQL file on /etc/init.d/
and  /etc/init.d/mysql is missing

when i try to start MySQL via 
sudo /etc/init.d/mysql start

it showed me an error 
sudo: /etc/init.d/mysql: command not found

**Comment by ScIT-Raphael** [comment]
did you checked also your syslog? About start or restart mariadb: https://mariadb.com/kb/en/systemd/#interacting-with-the-mariadb-server-process

**Comment by alber-khan** [comment]
/var/log/syslog

Jan  5 20:23:28 la-s1 mysqld[2681]: 2020-01-05 20:23:28 0 [Note] /usr/sbin/mysqld (mysqld 10.4.11-MariaDB-1:10.4.11+maria~bionic) starting as process 2681 ...
Jan  5 20:23:29 la-s1 systemd[1]: Started MariaDB 10.4.11 database server.
Jan  5 20:23:29 la-s1 /etc/mysql/debian-start[2721]: Upgrading MySQL tables if necessary.
Jan  5 20:23:29 la-s1 /etc/mysql/debian-start[2726]: Looking for 'mysql' as: /usr/bin/mysql
Jan  5 20:23:29 la-s1 /etc/mysql/debian-start[2726]: Looking for 'mysqlcheck' as: /usr/bin/mysqlcheck
Jan  5 20:23:29 la-s1 /etc/mysql/debian-start[2726]: This installation of MariaDB is already upgraded to 10.4.11-MariaDB, use --force if you still need to run mysql_upgrade
Jan  5 20:23:29 la-s1 /etc/mysql/debian-start[2754]: Checking for insecure root accounts.
Jan  5 20:23:29 la-s1 /etc/mysql/debian-start[2758]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables

**Comment by johnnyq** [comment]
@4183r check the amount of disk space available post the results of `df -h` also check the amount of memory available it seems like NGINX is eating up quite a bit post the result of `free -m `

**Comment by alber-khan** [comment]
@johnnyq  i don't think that's the issue, server config is 320gb nvme and 32 GB Ram.

![image](https://user-images.githubusercontent.com/39749258/71858290-aecb0580-3110-11ea-8364-690738bf687a.png)

**Comment by johnnyq** [comment]
@4183r I was going on a hunch there. In the initial post you mentioned your using ubuntu 18.04.2 i believe the latest is 18.04.3, have you run apt update and apt dist-upgrade to retrieve the latest updates. I have always updated all packages before running the hestia install scripts and then rerun the updates after install

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/71896213-23398f00-3179-11ea-9c7a-87c9dd42bbfe.png)

sorry it's 18.04.3!

**Comment by Lupul** [comment]
After a reboot, what is the services status?
```
sudo su -
systemctl status mysql
systemctl status dovecot
systemctl status bind9
v-list-sys-services
```

**Comment by alber-khan** [comment]
root@la-s1:~ # sudo su 
```
root@la-s1:~ # systemctl status mysql
● mariadb.service - MariaDB 10.4.11 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: active (running) since Wed 2020-01-08 02:49:38 IST; 34s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 1212 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)
  Process: 1210 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 691 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 (code=exited, status=0/SUCCESS)
  Process: 684 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 641 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 871 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 45 (limit: 4915)
   CGroup: /system.slice/mariadb.service
           ├─ 871 /usr/sbin/mysqld
           ├─1215 /bin/bash /etc/mysql/debian-start
           ├─1416 xargs -i /usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf --skip-column-names --silent --batch --force -e {}
           └─3027 /usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf --skip-column-names --silent --batch --force -e select count(*) into @discard from `pandalove_wp`.`loveicl_string_translations`

Jan 08 02:49:30 la-s1 systemd[1]: Starting MariaDB 10.4.11 database server...
Jan 08 02:49:36 la-s1 mysqld[871]: 2020-01-08  2:49:36 0 [Note] /usr/sbin/mysqld (mysqld 10.4.11-MariaDB-1:10.4.11+maria~bionic) starting as process 871 ...
Jan 08 02:49:38 la-s1 systemd[1]: Started MariaDB 10.4.11 database server.
Jan 08 02:49:39 la-s1 /etc/mysql/debian-start[1216]: Upgrading MySQL tables if necessary.
Jan 08 02:49:39 la-s1 /etc/mysql/debian-start[1228]: Looking for 'mysql' as: /usr/bin/mysql
Jan 08 02:49:39 la-s1 /etc/mysql/debian-start[1228]: Looking for 'mysqlcheck' as: /usr/bin/mysqlcheck
Jan 08 02:49:39 la-s1 /etc/mysql/debian-start[1228]: This installation of MariaDB is already upgraded to 10.4.11-MariaDB, use --force if you still need to run mysql_upgrade
Jan 08 02:49:39 la-s1 /etc/mysql/debian-start[1376]: Checking for insecure root accounts.
Jan 08 02:49:39 la-s1 /etc/mysql/debian-start[1403]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables
```

```
root@la-s1:~# systemctl status dovecot
● dovecot.service - Dovecot IMAP/POP3 email server
   Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-01-08 02:49:31 IST; 43s ago
     Docs: man:dovecot(1)
           http://wiki2.dovecot.org/
 Main PID: 693 (dovecot)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/dovecot.service
           ├─ 693 /usr/sbin/dovecot -F
           ├─ 879 dovecot/anvil
           ├─ 880 dovecot/log
           ├─ 894 dovecot/config
           └─1881 dovecot/auth

Jan 08 02:49:31 la-s1 systemd[1]: Started Dovecot IMAP/POP3 email server.
```
```
root@la-s1:~# systemctl status bind9
● bind9.service - BIND Domain Name Server
   Loaded: loaded (/lib/systemd/system/bind9.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-01-08 02:49:30 IST; 45s ago
     Docs: man:named(8)
 Main PID: 637 (named)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/bind9.service
           └─637 /usr/sbin/named -f -u bind

Jan 08 02:49:32 la-s1 named[637]: checkhints: b.root-servers.net/A (192.228.79.201) extra record in hints
Jan 08 02:49:32 la-s1 named[637]: checkhints: b.root-servers.net/AAAA (2001:500:200::b) missing from hints
Jan 08 02:49:32 la-s1 named[637]: checkhints: b.root-servers.net/AAAA (2001:500:84::b) extra record in hints
Jan 08 02:49:32 la-s1 named[637]: checkhints: l.root-servers.net/AAAA (2001:500:9f::42) missing from hints
Jan 08 02:49:32 la-s1 named[637]: checkhints: l.root-servers.net/AAAA (2001:500:3::42) extra record in hints
Jan 08 02:49:32 la-s1 named[637]: network unreachable resolving 'ns7.CLOUDFLARE.COM/A/IN': 2400:cb00:2049:1::a29f:121#53
Jan 08 02:49:32 la-s1 named[637]: network unreachable resolving 'ns7.CLOUDFLARE.COM/A/IN': 2400:cb00:2049:1::a29f:506#53
Jan 08 02:49:32 la-s1 named[637]: network unreachable resolving 'ns7.CLOUDFLARE.COM/AAAA/IN': 2400:cb00:2049:1::a29f:837#53
Jan 08 02:49:32 la-s1 named[637]: network unreachable resolving 'ns7.CLOUDFLARE.COM/AAAA/IN': 2400:cb00:2049:1::a29f:30b#53
Jan 08 02:49:33 la-s1 named[637]: network unreachable resolving 'ns2/AAAA/IN': 2606:4700:50::adf5:3aa7#53
```
```
root@la-s1:~# v-list-sys-services
NAME     STATE    CPU    MEM   UPTIME
----     -----    ---    ---   ------
apache2  running  213.4  396   0
nginx    running  30.3   1664  0
bind9    running  1.1    103   0
exim4    running  0      4     0
dovecot  running  0.2    0     0
mysql    running  58.4   2711  0
proftpd  running  0      1     0
cron     running  0      0     0
```

**Comment by Lupul** [comment]
All services are up and running, don't see anything wrong here

**Comment by ScIT-Raphael** [comment]
Infact that it looks like all is working properly, I'll close this issue.

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/72401993-a78ca300-3773-11ea-8e2a-7df5b09a10f3.png)


This Happens again

**Comment by alber-khan** [comment]
root@la-s1:~ # sudo su -
root@la-s1:~ # systemctl status mysql
● mariadb.service - MariaDB 10.4.11 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: failed (Result: exit-code) since Wed 2020-01-15 08:42:26 IST; 5min ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 789 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
  Process: 645 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 (code=exited, status=0/SUCCESS)
  Process: 642 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 636 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 789 (code=exited, status=1/FAILURE)
   Status: "MariaDB server is down"

Jan 15 08:42:26 la-s1 mysqld[789]: 2020-01-15  8:42:26 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
Jan 15 08:42:26 la-s1 mysqld[789]: 2020-01-15  8:42:26 0 [ERROR] Plugin 'InnoDB' init function returned error.
Jan 15 08:42:26 la-s1 mysqld[789]: 2020-01-15  8:42:26 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Jan 15 08:42:26 la-s1 mysqld[789]: 2020-01-15  8:42:26 0 [Note] Plugin 'FEEDBACK' is disabled.
Jan 15 08:42:26 la-s1 mysqld[789]: 2020-01-15  8:42:26 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
Jan 15 08:42:26 la-s1 mysqld[789]: 2020-01-15  8:42:26 0 [ERROR] Failed to initialize plugins.
Jan 15 08:42:26 la-s1 mysqld[789]: 2020-01-15  8:42:26 0 [ERROR] Aborting
Jan 15 08:42:26 la-s1 systemd[1]: mariadb.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 08:42:26 la-s1 systemd[1]: mariadb.service: Failed with result 'exit-code'.
Jan 15 08:42:26 la-s1 systemd[1]: Failed to start MariaDB 10.4.11 database server.
root@la-s1:~# systemctl status dovecot
● dovecot.service - Dovecot IMAP/POP3 email server
   Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources)
     Docs: man:dovecot(1)
           http://wiki2.dovecot.org/

Jan 15 08:42:20 la-s1 systemd[1]: dovecot.service: Failed to run 'start' task: Read-only file system
Jan 15 08:42:20 la-s1 systemd[1]: dovecot.service: Failed with result 'resources'.
Jan 15 08:42:20 la-s1 systemd[1]: Failed to start Dovecot IMAP/POP3 email server.
root@la-s1:~# systemctl status bind9
● bind9.service - BIND Domain Name Server
   Loaded: loaded (/lib/systemd/system/bind9.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-01-15 08:42:20 IST; 6min ago
     Docs: man:named(8)
  Process: 637 ExecStart=/usr/sbin/named -f $OPTIONS (code=exited, status=1/FAILURE)
 Main PID: 637 (code=exited, status=1/FAILURE)

Jan 15 08:42:19 la-s1 named[637]: sizing zone task pool based on 26 zones
Jan 15 08:42:19 la-s1 named[637]: none:103: 'max-cache-size 90%' - setting to 28950MB (out of 32167MB)
Jan 15 08:42:19 la-s1 named[637]: obtaining root key for view _default from '/etc/bind/bind.keys'
Jan 15 08:42:19 la-s1 named[637]: working directory '/var/cache/bind' is not writable
Jan 15 08:42:19 la-s1 named[637]: ../../../../lib/isc/unix/file.c:340: unexpected error:
Jan 15 08:42:19 la-s1 named[637]: unable to convert errno to isc_result: 30: Read-only file system
Jan 15 08:42:19 la-s1 named[637]: loading configuration: permission denied
Jan 15 08:42:19 la-s1 named[637]: exiting (due to fatal error)
Jan 15 08:42:20 la-s1 systemd[1]: bind9.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 08:42:20 la-s1 systemd[1]: bind9.service: Failed with result 'exit-code'.
root@la-s1:~# v-list-sys-services
NAME     STATE    CPU  MEM   UPTIME
----     -----    ---  ---   ------
apache2  running  0.5  130   5
nginx    running  3.6  1664  6
bind9    stopped  0    0     0
exim4    running  0    4     0
dovecot  stopped  0    0     0
mysql    stopped  0    0     0
proftpd  running  0    1     5
cron     running  0    0     6
root@la-s1:~#

**Comment by ScIT-Raphael** [comment]
It sounds like your file system is read only, check your syslog if you can find out why and try again to reboot your machine.

**Comment by alber-khan** [comment]
Please find the system log before

https://pastebin.com/tX9mShGx

**Comment by ScIT-Raphael** [comment]
I'm sorry, but we can't do a full system check without any relation to hestia for free: As I wrote, your system seems to run in read only mode, which has no relation to hestia itself. For this, there would be multiple reasons which google can lead you to it.

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/72659296-be393100-39e3-11ea-9385-40b860b502c9.png)


Same stuff happened in another new server which i setup few days ago

**Comment by alber-khan** [comment]
The only option I find is to restart the services after reboot. this usually happens after I reboot it via SSH.

service apache2 restart
sudo service nginx restart
service hestia restart
service mysql restart
service bind9 restart
service dovecot restart
service exim4 restart
service php5.6-fpm restart
service php7.0-fpm restart
service php7.1-fpm restart
service php7.2-fpm restart
service php7.3-fpm restart

otherwise, most of the time MySQL, all PHP-fpm, bind9 and dovecot are always down.

**Comment by ScIT-Raphael** [comment]
I'm not able to reproduce your issue in any scenario I tested, services are always up when reboot the server over ssh - so this needs to be a "local" issue which we can't help out.

**Comment by alber-khan** [comment]
this is happening with me on both of my new servers, I've restored all the website from vestacp.

**Comment by Lupul** [comment]
what type of virtualisation are you using (and on which hosting provider)

**Comment by alber-khan** [comment]
Hypervisor vendor:   KVM
Virtualization type: full

![image](https://user-images.githubusercontent.com/39749258/72982021-22a12980-3e04-11ea-92c3-059ab5754eb0.png)

**Comment by alber-khan** [comment]
Provider is hivelocity.

**Comment by alber-khan** [comment]
@Lupul Any idea boss?

![image](https://user-images.githubusercontent.com/39749258/73201644-7b9ff300-415f-11ea-83ea-b9bc0be9989a.png)

![image](https://user-images.githubusercontent.com/39749258/73201700-9b371b80-415f-11ea-8764-2a1d0ac8fad3.png)

![image](https://user-images.githubusercontent.com/39749258/73201712-a427ed00-415f-11ea-84fc-36c6720bee62.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/73202720-ab4ffa80-4161-11ea-919a-653555047689.png)


the same thing happens to another server :(

**Comment by Lupul** [comment]
The error message you posted shows that mysql and bind9 can't start because the filesystem is readonly. You need to figure out why this keeps happening.

And to be clear, this is not a Hestia bug, as it is not involved in the system boot process at all.

**Comment by alber-khan** [comment]
Okay boss! but I've tried to same stuff in different company (digitalocean) and this happens over there too! :/

**Comment by ScIT-Raphael** [comment]
Please inform about your installation steps, using proxmox and hetzner cloud on my side without any issues.

**Comment by alber-khan** [comment]
sudo -s
sudo  apt-get update && apt-get dist-upgrade  && sudo apt-get upgrade
sudo apt-get install htop curl wget

wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

apt-get update && apt-get install ca-certificates


bash hst-install.sh --apache yes --nginx yes --phpfpm no  --multiphp yes --vsftpd no  --proftpd yes --named yes --mysql yes --postgresql no --exim yes --dovecot yes --clamav no --spamassassin no --iptables no --fail2ban no --quota yes --api yes --lang en --hostname la-s1.b2btech.in --email alber@b2btech.in --password somepassword --force

**Comment by ScIT-Raphael** [comment]
Can't see any abnormal and also not able to reproduce the issue. As @Lupul already wrote, this needs to be a local problem and is not related to hestia. Can't help you out here, you will need to find out what puts your file system to read only mode.

**Comment by alber-khan** [comment]
Okay boss! thank you

**Comment by Lupul** [comment]
@4183r have you done other filesystem related configuration on these vms? like changing mysql datadir or mounting other partitions in /etc/fstab?

**Comment by alber-khan** [comment]
Nope! just bought the server and followed these steps, after that, I started migrating from vestacp to hestiacp then I just reboot the system and services never start automatically. 

> sudo -s
> sudo apt-get update && apt-get dist-upgrade && sudo apt-get upgrade
> sudo apt-get install htop curl wget
> 
> wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
> 
> apt-get update && apt-get install ca-certificates
> 
> bash hst-install.sh --apache yes --nginx yes --phpfpm no --multiphp yes --vsftpd no --proftpd yes --named yes --mysql yes --postgresql no --exim yes --dovecot yes --clamav no --spamassassin no --iptables no --fail2ban no --quota yes --api yes --lang en --hostname la-s1.b2btech.in --email [alber@b2btech.in](mailto:alber@b2btech.in) --password somepassword --force

**Comment by moucho** [comment]
They were some issues with VestaCP also when installing with quotas. For example https://forum.vestacp.com/viewtopic.php?t=16388
Maybe try installing without quotas?

**Comment by alber-khan** [comment]
Umm in vestacp i've been using Ubuntu not CentOS

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/73326010-a3ce4580-4276-11ea-9f9f-a224f64ba3a7.png)

and my file system is ext4
