### ISSUE TITLE
Feature Request: Sort By First Column A -> Z by default

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#668]
#In a few words, please describe the issue that you're experiencing:
By default columns are sorted by Date in HestiaCP Web interface it would be excellent if they were sorted by the first column for example click on web tab the domains should be sorted A -> Z by default. It makes things much quicker to find and its a more natural approach to sort first column

The Following tabs should be sorted A - > Z first column by default

- Users
- Web Domains
- DNS Zones
- DNS Records
- Mail Domains
- Mail Accounts
- Databases

### Which version of Hestia Control Panel is currently installed?
1.0.6

**Comment by ScIT-Raphael** [comment]
Dublicate, has already been answered: https://github.com/hestiacp/hestiacp/issues/458
