### ISSUE TITLE
Ubuntu 18.04 LTS on raspberry pi 3 failed to install

### ISSUE THREAD

**Issue by KamuiX** [hestiacp/hestiacp#669]
### The content below is simply a template. Please delete any unnecessary sections from your issue reports.

Tried today to install hestiacp on a freshly installed Ubuntu 18.04.

Steps was change user & root password and start the installation. Below you can find the error log.

Updating currently installed packages, please wait...|
Now installing Hestia Control Panel and all required dependencies.
NOTE: This process may take 10 to 15 minutes to complete, please wait... /
() Configuring system settings...
() Configuring Hestia Control Panel...
cp: cannot stat '/usr/local/hestia/install/deb/sudo/admin': No such file or directory
chmod: cannot access '/etc/sudoers.d/admin': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/hestia': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/packages': No such file or directory
sed: can't read /usr/local/hestia/data/packages/.pkg: No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/unassigned/index.html': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/skel/document_errors/': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/firewall': No such file or directory
() Generating default self-signed SSL certificate...
hst-install-ubuntu.sh: line 1069: /usr/local/hestia/bin/v-generate-ssl-cert: No such file or directory
() Adding SSL certificate to Hestia Control Panel...
sed: -e expression #1, char 3: unexpected ,' sed: -e expression #1, char 1: unknown command: ,'
cp: cannot stat '/usr/local/hestia/install/deb/ssl/dhparam.pem': No such file or directory
(*) Configuring NGINX...
cp: cannot stat '/usr/local/hestia/install/deb/nginx/nginx.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/status.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/phpmyadmin.inc': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/phppgadmin.inc': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/nginx': No such file or directory
sed: can't read /etc/nginx/nginx.conf: No such file or directory
sed: can't read /usr/local/hestia/nginx/conf/nginx.conf: No such file or directory
Failed to start nginx.service: Unit nginx.service not found.
Error: nginx start failed

rssh error also showed up in the beginning but I manually installed it before copy paste here the log so include that one.

**Comment by ScIT-Raphael** [comment]
According to our system requirements, we do not support raspian or any other arm based os: https://github.com/hestiacp/hestiacp#supported-operating-systems

Also support for raspberry pi/arm isnt planed, I suggest to use a VPS provider like hetzner.com (or any other you may like).

Update: Nevermind that Ubuntu 18.04 LTS also runs on arm now, but still - we do not support arm systems.

**Comment by KamuiX** [comment]
Sorry got your response after I though my Issue disappeared.
