### ISSUE TITLE
Ubuntu 18.04 LTS Raspberry PI 3 installation error

### ISSUE THREAD

**Issue by KamuiX** [hestiacp/hestiacp#671]
In a few words, please describe the issue that you're experiencing:
After clean OS installation I'm getting the bellow error

`Updating currently installed packages, please wait.../
Now installing Hestia Control Panel and all required dependencies.
NOTE: This process may take 10 to 15 minutes to complete, please wait...                                                         /
(*) Configuring system settings...
(*) Configuring Hestia Control Panel...
cp: cannot stat '/usr/local/hestia/install/deb/sudo/admin': No such file or directory
chmod: cannot access '/etc/sudoers.d/admin': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/hestia': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/packages': No such file or directory
sed: can't read /usr/local/hestia/data/packages/*.pkg: No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/unassigned/index.html': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/skel/document_errors/*': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/firewall': No such file or directory
(*) Generating default self-signed SSL certificate...
hst-install-ubuntu.sh: line 1069: /usr/local/hestia/bin/v-generate-ssl-cert: No such file or directory
(*) Adding SSL certificate to Hestia Control Panel...
sed: -e expression #1, char 3: unexpected `,'
sed: -e expression #1, char 1: unknown command: `,'
cp: cannot stat '/usr/local/hestia/install/deb/ssl/dhparam.pem': No such file or directory
(*) Configuring NGINX...
cp: cannot stat '/usr/local/hestia/install/deb/nginx/nginx.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/status.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/phpmyadmin.inc': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/phppgadmin.inc': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/nginx': No such file or directory
sed: can't read /etc/nginx/nginx.conf: No such file or directory
sed: can't read /usr/local/hestia/nginx/conf/nginx.conf: No such file or directory
Failed to start nginx.service: Unit nginx.service not found.
Error: nginx start failed`

What steps did you take when the issue occured? 
1. Install Ubuntu server 18.04 on SD card and boot
2. change default user and root pass
3. Start installation

Operating system distribution and release:
Ubuntu 18.04 LTS

Which version of Hestia Control Panel is currently installed?
Hopefully 1.0.6

Which branch are you using?
release

When did this issue occur? After a clean installation, or after an upgrade?
After aclean installation of my Ubuntu 18.04 LTS on Raspi 3

Which of the following web server configurations are you using?
- Apache + Nginx (default)

Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)

In order to better assist, please post any relevant log information below:
Files are empty

**Comment by ScIT-Raphael** [comment]
I already answered your issue report, please stop duplicate them: https://github.com/hestiacp/hestiacp/issues/669
