### ISSUE TITLE
No DNS or Mail Records during new Installation 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#680]
### In a few words, please describe the issue that you're experiencing:

During new Installation on ubuntu 18.04.3 when i login to hestiacp i found there was no DNS or Mail Records 

### What steps did you take when the issue occured? 

 i deleted the default hostname (domain name) from web
and created them manually

![image](https://user-images.githubusercontent.com/39749258/72474875-c17bc380-380f-11ea-85ac-61757ee184cc.png)

### Expected behavior:

it should be there by default and you should remove the option for Create DNS zone and Enable mail for this domain when someone add a new domain like we have in vestacp should be added there by default 

### Operating system distribution and release:
Ubuntu 18.04.3

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by alber-khan** [comment]
can we also add ioncube loader by default?

**Comment by ScIT-Raphael** [comment]
Most users runs hestia for webhosting only, also has dns and mail services external - cloudflare and o365 for example. This was the reason why they are set to optional, just a tick to what you want to have, and it will create it for you.

There is no direct installation of ioncube planed, you can do it when you follow their docs, will take you a few minutes when you really need it.
