### ISSUE TITLE
Bug: Line breaks not set correctly in Email Credentials message

### ISSUE THREAD

**Issue by crarchile** [hestiacp/hestiacp#682]
Dear Guys,

When I create a new email account in HestiaCP and I use the option to send the email credentials by email, I get this message:

Username: hosting@superservidor.cl
Password: o3L7nTgZNe4GQVLsR
IMAP Hostname: mail.superservidor.cl
IMAP Port: 993
IMAP Security: SSL / TLS
IMAP Authentication Method: Normal Password SMTP Hostname: mail.superservidor.cl SMTP Port: 465 SMTP Security: SSL / TLS SMTP Authentication Method: Normal Password Webmail Alias: http://webmail.superservidor.cl

Is it possible to fix the lacking break lines to get the same message but with this format?
**(Please note the break lines)**

Username: hosting@superservidor.cl
Password: o3L7nTgZNe4GQVLpV
IMAP Hostname: mail.superservidor.cl
IMAP Port: 993
IMAP Security: SSL / TLS
IMAP Authentication Method: Normal Password 
SMTP Hostname: mail.superservidor.cl 
SMTP Port: 465 SMTP Security: 
SSL / TLS SMTP Authentication Method: Normal Password 
Webmail Alias: http://webmail.superservidor.cl

Regards,

Carlos Alvarez
Hosting SuperServidor.cl

**Comment by jaapmarcus** [comment]
Hmm just checked on the latest (1.12) version and the issue seems to be fixed.

Email send to a gmail address and round cube address 

Username: xxxxl@xxxx.nl
Password: ****************
IMAP Hostname: mail.xxxx.nl
IMAP Port: 143
IMAP Security: STARTTLS
IMAP Authentication Method: Normal Password
SMTP Hostname: mail.xxxx.nl
SMTP Port: 587
SMTP Security: STARTTLS
SMTP Authentication Method: Normal Password
Webmail Alias: http://webmail.xxxx.nl
` 

Otherwise the error is here:

https://github.com/hestiacp/hestiacp/blob/master/web/js/pages/add_mail_acc.js
`generate_mail_credentials = function() {
    var div = $('.mail-infoblock').clone();
    div.find('#mail_configuration').remove();
    var pass=div.find('#v_password').text();
    if (pass=="") div.find('#v_password').html(' ');
    var output = div.text();
    output=output.replace(/(?:\r\n|\r|\n|\t)/g, "|");
    output=output.replace(/  /g, "");
    output=output.replace(/\|\|/g, "|");
    output=output.replace(/\|\|/g, "|");
    output=output.replace(/\|\|/g, "|");
    output=output.replace(/^\|+/g, "");
    output=output.replace(/\|$/, "");
    output=output.replace(/ $/, "");
    output=output.replace(/:\|/g, ": ");
    output=output.replace(/\|/g, "\n");
    //console.log(output);
    $('#v_credentials').val(output);
}`

How ever I can't find any where the behaviour has been changed since it's introduction in 2017

**Comment by ScIT-Raphael** [comment]
Just confirming: The issue is still here (Hestia 1.1.1, Ubuntu 18.04)

**Comment by jaapmarcus** [comment]
isn't it an issue with the line break. 

output=output.replace(/\|/g, "\n");  
replace it with
output=output.replace(/\|/g, "\r\n"); 

```
<?php

//very short version
$v_credentials = $_POST['v_credentials'];
$mailtext = $v_credentials;
send_email($to, $subject, $mailtext, $from);
?>
```

**Comment by ScIT-Raphael** [comment]
Hi @jaapmarcus 

Just wrote it, to also confirm this issue, hadnt enough time to check it.

I had a look of the change you proposed, unclucky but it doesnt work as expected - the line still doesnt have the proper line breaks - I'll have a deeper look here.

Thanks for your contribution, also about the ssh auth key pull - still try to find enough time for my part of the review :).

**Comment by rmj-s** [comment]
Hi @ScIT-Raphael,
Is this still an issue? I can't reproduce it on  v1.1.1.

**Comment by jaapmarcus** [comment]
This should be still a issue have tested it also in the passed and no issue over here but @ScIT-Raphael  had some issues and the same as the TS.

Check yesterday also some other translation and the had similar issues with other templates.

**Comment by jaapmarcus** [comment]
We are not able to replicate the issue in 1.3.2 / "alpha" branch. If the issue happens please create an bug report for it
