### ISSUE TITLE
Mailwizz database password was wrong after run v-restore-user

### ISSUE THREAD

**Issue by crarchile** [hestiacp/hestiacp#683]
### In a few words, please describe the issue that you're experiencing:

Today I restored a backup made with vestacp 0.9.8.26 (Ubuntu 18.04) into hestiacp 1.0.6 (Debian 9.11), from user 'admin' to user 'admin', from web 'abc.site.tld' to web 'abc.site.tld', and after testing the restored site on browser I get the error "CDbException CDbConnection failed to open the DB connection" when I tried to open my Mailwizz site.

### What steps did you take when the issue occured? 

My solution to this issue was to change the password of the restored DB to the old password used by my app and the problem was solved !

### Expected behavior:

I expected that the password of restored db was equal to original db password

### Operating system distribution and release:

Debian 9.11

### Which version of Hestia Control Panel is currently installed?

1.0.6

### Which branch are you using?

Release

### When did this issue occur? After a clean installation, or after an upgrade?

After a clean install

### Which of the following web server configurations are you using?

- Apache + Nginx
- Nginx + PHP-FPM
- PHP-FPM + Multi-PHP
- I am  not sure

### Which of the following server roles are installed on your server?

- DNS Bind
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)
- PostgreSQL
- ClamAv
- SpamAssassin

### In order to better assist, please post any relevant log information below:

I run command:

root@hosting:/backup# v-restore-user  admin admin.2020-01-14_15-25-56.tar

The restore was successfull !

### Related issues or forum threads:

https://github.com/hestiacp/hestiacp/issues/548

**Comment by ScIT-Raphael** [comment]
The issue has already been fixed in #548, the solution will be released with 1.1.0.
