### ISSUE TITLE
PHP-FPM pool configuration doesn't update on rebuilt

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#684]
### In a few words, please describe the issue that you're experiencing:

i uploaded a new PHP-73.sh template in
/usr/local/hestia/data/templates/web/apache2
 
and via the web panel, I tried to rebuild the template 

![image](https://user-images.githubusercontent.com/39749258/72631666-9d88c100-397a-11ea-8442-6d52c1b07b1c.png)

but when I checked

/etc/php/7.3/fpm/pool.d/ 

the configuration did not update, so i tried to change the PHP version to PHP 7.2 and then update it back to PHP 7.3 and it didn't work

![image](https://user-images.githubusercontent.com/39749258/72631806-eccef180-397a-11ea-9f42-720f26c36252.png)

### What steps did you take when the issue occured? 

 i deleted the domain's pool file from

/etc/php/7.3/fpm/pool.d

and change the PHP version to PHP 7.2 and then update it back to PHP 7.3 and got the new configuration 

### Expected behavior:

Should get the latest configuration from
/usr/local/hestia/data/templates/web/apache2

and overwrite the pool config file each time or at least it should overwrite the pool config when i rebuilt it via web panel

### Operating system distribution and release:
Ubuntu 18.04.3

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by alber-khan** [comment]
Also in another domain, I tried to update "Web Template APACHE2" from default to PHP-7.3, and I got 500 internal error 

[Sat Jan 18 09:57:30.035333 2020] [proxy:error] [pid 8055] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm-domain.com.sock (*) failed
[Sat Jan 18 09:57:30.035457 2020] [proxy_fcgi:error] [pid 8055] [client 103.211.19.29:52720] AH01079: failed to make connection to backend: httpd-UDS


when I switch it back to default the domain started working again.

**Comment by alber-khan** [comment]
i tried switching the domain to PHP-7.3 and click on "Rebuild All" and pool file didn't created.

**Comment by Lupul** [comment]
There might be a error in the PHP-73.sh script you have replaced, on a clean install changing php versions works as expected. 
https://github.com/hestiacp/hestiacp/blob/1.0.6/install/deb/multiphp/apache2/PHP-72.sh#L63-L71

Make sure you have set the execute flag on that .sh script, and try to run it manually to see  if any errors show up

**Comment by alber-khan** [comment]
@Lupul i've only updated 

pm.max_children = 80
pm.max_requests = 8000

php_admin_value[upload_max_filesize] = 512M
php_admin_value[max_execution_time] = 300
php_admin_value[post_max_size] = 512M
php_admin_value[memory_limit] = 4096M

**Comment by alber-khan** [comment]
btw i've restored those websites via vestacp and i'm getting this error when i open the website

![image](https://user-images.githubusercontent.com/39749258/72659121-d9ef0800-39e0-11ea-85ea-89f0161bec65.png)

and in error log

[Sat Jan 18 10:54:19.404931 2020] [proxy:error] [pid 9547] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm-domain.com.sock (*) failed
[Sat Jan 18 10:54:19.405012 2020] [proxy_fcgi:error] [pid 9547] [client 54.36.150.66:34284] AH01079: failed to make connection to backend: httpd-UDS

**Comment by alber-khan** [comment]
php-fpm pool did not exist in /run/php

**Comment by alber-khan** [comment]
I also noticed after I reboot the system all the website started to give 500 Internal Server Error

so I checked /run/php and the folder was empty 

![image](https://user-images.githubusercontent.com/39749258/72659356-57684780-39e4-11ea-8fc0-042d088a6ef8.png)

**Comment by alber-khan** [comment]
after reboot i click on "Rebuilt All" and now i'm getting

![image](https://user-images.githubusercontent.com/39749258/72659367-7ebf1480-39e4-11ea-8f22-c82f07c8f97c.png)

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/72659374-9e563d00-39e4-11ea-8b73-d01bcbecc2bb.png)

**Comment by ioannidesalex** [comment]
I don’t think its related but max children 80 with a memory limit of 4gb means that you need 320gb of ram just for php.

**Comment by alber-khan** [comment]
Ahh okay, i uploaded the original file boss, but still the same results.

**Comment by ScIT-Raphael** [comment]
As @Lupul already wrote: Do you have the right execution permission on your .sh files?

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/72663663-1a6b7780-3a1b-11ea-8cea-b8cc1d8ec9ed.png)


Here boss

**Comment by fishnux** [comment]
Could be a problem of line endings. Can you run "dos2unix PHP-73.sh" on the terminal?

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/73201437-02080500-415f-11ea-93f6-07ecdea0bed4.png)


it's showing this

**Comment by ScIT-Raphael** [comment]
Infact we can't reproduce this issue, I'll close it. It looks like a local problem on the related server and not a hestia one. If you still need help you could switch to hestia forum, maybe the community can help,
