### ISSUE TITLE
can't send mails via webmail

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#685]
### In a few words, please describe the issue that you're experiencing:

when i was trying to send an email 

![image](https://user-images.githubusercontent.com/39749258/72664227-4a1d7e00-3a21-11ea-9ed3-663cab233873.png)

SMTP Error (550): Failed to set sender "alber@gmail.com" (Access denied - Invalid HELO name (See RFC2821 4.1.3)).
 

### What steps did you take when the issue occured? 

/etc/exim4/exim4.conf.template
--

![image](https://user-images.githubusercontent.com/39749258/72664283-fe1f0900-3a21-11ea-8060-2d0f578d9da1.png)

Commented these 2 lines and it works

### Expected behavior:

should just send an email without error

### Operating system distribution and release:
Ubuntu 18.04.3

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
For the next time, please do a google research: https://forum.vestacp.com/viewtopic.php?t=5408
