### ISSUE TITLE
V-backup user admin fails with Hestia 1.1.0

### ISSUE THREAD

**Issue by crarchile** [hestiacp/hestiacp#686]
### In a few words, please describe the issue that you're experiencing:
v-backup-user admin command does not work and fails when is executed

### What steps did you take when the issue occured? 
1. v-backup-user admin

### Expected behavior:
backup of admin user should be finished correctly

### Operating system distribution and release:
Debian 9.8 Stretch

### Which version of Hestia Control Panel is currently installed?
1.1.0

### Which branch are you using?

HestiaCP's  Installer's version (I don't know which)

### When did this issue occur? After a clean installation, or after an upgrade?

After a clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx 
- Nginx + PHP-FPM
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)
- PostgreSQL
- ProFTP
- IPTables
- Fail2Ban
- Clamav
- Spamassassin

**Comment by ScIT-Raphael** [comment]
Crosspost, I've already answered this in our forum: https://forum.hestiacp.com/t/v-backup-user-admin-fails-with-hestia-1-1-0/382/2
