### ISSUE TITLE
other themes?

### ISSUE THREAD

**Issue by Wqrld** [hestiacp/hestiacp#687]
Are there any other themes for hestia? Im looking for a better maintained vesta fork but i just think hestia (from the demo) looks really old. Or is there a simple way to edit the css files persisting across updates?

**Comment by ScIT-Raphael** [comment]
Hestia is based on vesta, the backend got some small reworks. For your question -  a multi theme support is already implemented in hestia master branch and will be released with v1.1.0: https://github.com/hestiacp/hestiacp/search?utf8=%E2%9C%93&q=theme&type=Code

**Comment by Wqrld** [comment]
Is 1.1.0 expected to come anytime soon or should i just use the current public build if im looking to make some small edits?

**Comment by ScIT-Raphael** [comment]
You can take the current version, if you like, just send us a pull request and we will implement your changes after a code review.
