### ISSUE TITLE
Error from ClamAV during the installation

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#689]
### Which operating system
- Ubuntu 18.04 LTS @Hetzner

### Which branch are you using?
- installation from : https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

### When did this issue occur?
During an installation I've got this error:

> (*) Installing ClamAV anti-virus definitions...\WARNING: Ignoring deprecated option DetectBrokenExecutables at /etc/clamav/clamd.conf:33

ref: https://github.com/hestiacp/hestiacp/blob/master/install/deb/clamav/clamd.conf#L33

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM + Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)
- PostgreSQL

### Related issues or forum threads:
I've quickly search for clamd before posting this issue

**Comment by ScIT-Raphael** [comment]
This has already been fixed in master, as you can see, line 33 doesnt point to that option
