### ISSUE TITLE
Feature Request: Add Nextcloud to webapp installer

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#690]
Please add Nextcloud to the webapp installer
if nginx is installed use owncloud.tpl
add the following line to config.php to enable mem caching this disables the warning on configuring caching in the nextcloud web interface.

`'memcache.local' => '\\OC\\Memcache\\APCu',`

**Comment by JOduMonT** [comment]
### [be aware of this](https://nextcloud.com/blog/urgent-security-issue-in-nginx-php-fpm/)
Since there are only two changes in the nginx configuration we highlight them here:

```
    location / {
                rewrite ^ /index.php$request_uri;
            }
```
Should become

```
    location / {
                rewrite ^ /index.php;
            }

```
### Note the removal of $request_uri

**Comment by johnnyq** [comment]
@JOduMonT good idea!

**Comment by vestacp-user** [comment]
I just installed nextcloud using the webinstaller and manually created the database and everything worked (so far) without manually changing any nginx configuration. 

Is the above nginx config still relevant?

Any start any work on an installer for nextcloud?

**Comment by jaapmarcus** [comment]
Feel free to contribute with a pull request for any software packages. 

The resources of the team are limited and we don't have enough time to full-fill all request. We should focus on the core of Hestia. 

To add any app to the system should be possible. See https://forum.hestiacp.com/t/matomo- 1-click-install/2066 for some "basic" instructions. When we have time we add / create an more extensive "guide"
