### ISSUE TITLE
Feature Request: Rainloop Webmail

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#692]
I just installed rainloop webmail and the webmail is excellent, simple, clean fast are there any chances of switching to rainloop instead of roundcube.

**Comment by ghost** [comment]
Closing this issue for now as we'll be upgrading Roundcube to the latest version soon. We may look at the ability to provide a choice for webmail client down the road if there's enough requests for it.

**Comment by tlcd96** [comment]
+1, maybe i'll do something for this if i can find time.
*if i can find time*: i've lots of work now

**Comment by jaapmarcus** [comment]
To be release with 1.4
https://github.com/hestiacp/hestiacp/pull/1548
