### ISSUE TITLE
Merge some minor open PRs from Vesta

### ISSUE THREAD

**Issue by kpapad904** [hestiacp/hestiacp#693]
While HestiaCP 1.1.0 beta is in testing, please consider merging a few minor PRs that were submitted to Vesta in the last few months.

Here are a couple of them that are applicable to HestiaCP:
https://github.com/serghey-rodin/vesta/pull/1947
https://github.com/serghey-rodin/vesta/pull/1969

Thank you for a great product!

**Comment by kpapad904** [comment]
Also:
https://github.com/serghey-rodin/vesta/pull/1930
(note: func/domain.sh L415 in Vesta is L468 in HestiaCP master)

**Comment by ScIT-Raphael** [comment]
Hi @kpapad904 
Thank you for pointing us to this pull requests, we took them over to hestia with the last few commits. Please let me know if you find any other usefull part that could improve hestia!

**Comment by dpeca** [comment]
https://github.com/serghey-rodin/vesta/pull/1930 PR is not good at all.
I closed it.
I will see to make fix for this today.

**Comment by dpeca** [comment]
Here is the correct fix - https://github.com/serghey-rodin/vesta/commit/f74301b19f3f06edb80553574fbb29df489c2ee3
