### ISSUE TITLE
Unable to send email because EXIM won't let me whitelist my IP

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#694]
I'm unable to send email because my ISP is mainly blacklisted and EXIM4 don't like this

![image](https://user-images.githubusercontent.com/5204724/73610627-fcea0080-460b-11ea-8c78-4899a5435789.png)

Well I found someone with the [same issue](https://forum.vestacp.com/viewtopic.php?t=4624)

When I whitelist my subnet in /etc/exim/white-blocks.conf
````
125.25.160.0/22 # TOT public company limited
43.228.157.0/24 # PureVPN sg2-ovpn-tcp.pointtoserver.com
````

than restart exim and spamassassin service I still unable to send

### I wonder if
1. I could whitelist a subnet like this
2. which service I should restart if it's not exim and spamassassin

**Comment by ScIT-Raphael** [comment]
I don't think this has something to do with black- or whitelists. The line you posted comes from exim configuration, you can find it here: https://github.com/hestiacp/hestiacp/blob/0af92af0168f4d02ed81dcf4e37f7c3f6d7926f7/install/deb/exim/exim4.conf.template#L111

Basicly you could uncomment this for testing, but on my side, there was no need: Havent tested thunderbird, but email works well with MS Outlook, Android and iPhone clients.

**Comment by JOduMonT** [comment]
@ScIT-Raphael 
don't get me wrong it is not just a message I have
my email is not send unless I use my VPN which is not blacklisted

#### unable to send from my ISP
here the IP provided by my ISP (https://bgp.he.net/ip/125.25.160.57#_rbl)
which change few many times per day this is why I use the subnet

#### able to send when I use [this VPN](https://bgp.he.net/ip/43.228.157.138#_rbl)

**Comment by Lupul** [comment]
Are you using a ip address as the smtp server or as part of your email addr?
ps: i'm using only thunderbird

**Comment by JOduMonT** [comment]
@Lupul 
> Are you using a ip address as the smtp server or as part of your email addr?

you means this setting in Thunberbird ?
![image](https://user-images.githubusercontent.com/5204724/73620891-6eef3380-4666-11ea-84e2-eae9b3f9d170.png)

PS: Thunderbird found the setting itself

if not, I'm sorry I don't understand your question

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/73731773-194a8200-475f-11ea-964e-52310f596418.png)

simply go and # comment these lines and it will fix the issue.

**Comment by JOduMonT** [comment]
@4183r @ScIT-Raphael already point that out
by disabling make exim4 a little less secure

my question is why I don't have the message when use a non blacklisted external IP since the message concern my local IP ?

**Comment by ScIT-Raphael** [comment]
I can't answer you that, because it looks like it is more a local issue than one with hestia. I just checked also if thunderbird works properly and it did. I used a domain where I enabled mail ssl over let's encrypt, took mail.domain.tld as name for imap and smtp server, port 465 for smtp, port 993 for imap - no problems with receiving and sending.

I'm sorry, but I'm not able to reproduce this issue and it also looks not like something that is hestia related, due to this, I've to close the issue. Please let us know if you find any solution for this or have additional informations. Thanks for your understanding!

**Comment by JOduMonT** [comment]
@ScIT-Raphael I also look around the net and I've found this error where people mention Vesta instead of Hestia. At the end the solution is always to deactivate the acl_check_mail
https://github.com/hestiacp/hestiacp/blob/0af92af0168f4d02ed81dcf4e37f7c3f6d7926f7/install/deb/exim/exim4.conf.template#L107-L120
