### ISSUE TITLE
Features Request: Backup by domain/subdomain instead of by user

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#696]
I think it would be nice to do backup by domain/subdomain so it would be easier to restore a specific website. Would it be also possible to do backup by email user ?

**Comment by ScIT-Raphael** [comment]
Currently, there are no plans to expand backup functionality, but to improve the backup process on his own (performance, etc).

**Comment by ioannidesalex** [comment]
Anyway it is strongly recommended to use separate users for each website for security purposes.

**Comment by JOduMonT** [comment]
> Anyway it is strongly recommended to use separate users for each website for security purposes.

I glad you mentioned that because it is actually what I'm doing ;)

**Comment by ioannidesalex** [comment]
Since you are doing this there is no need for backups per domain/subdomain :)

**Comment by JOduMonT** [comment]
> Since you are doing this there is no need for backups per domain/subdomain :)

yes but not everybody are smart ass like us :p

**Comment by Lupul** [comment]
v-restore-user already can restore individuals items (web/dns/mail/db) from a backup archive.
`options: USER BACKUP [WEB] [DNS] [MAIL] [DB]`
