### ISSUE TITLE
Restore backup from vestacp? 

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#698]
Hello, 

I want to move from vestacp. Is it possible to restore from vestacp's backup file?

**Comment by ScIT-Raphael** [comment]
Yes, vesta backups can be restored.

**Comment by drsdre** [comment]
Is their specific command to restore a VestaCP backup?

Using:
`v-restore-user <user> <backup>`

it gives:
`Error: invalid backup format`

I'm guessing this has something to do with the directory hestiacp missing. Instead there is a vestacp present with user configuration.
