### ISSUE TITLE
Asks for email even if specified in advanced install switch

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#70]
### Operating System (OS/VERSION):

Type here, e.g. Debian 9

### HestiaCP Version:

Type here, e.g. 1.01234

### Installed Software (what you got with the installer):

Type here, e.g. Apache, Nginx, PHP-FPM, MySQL

### Steps to Reproduce:

Even if you give install switch `--email my@email.com` it still asks for email when install starts

**Comment by ScIT-Raphael** [comment]
The switch works properly, main issue was a wrong definied multiphp switch (missing "yes/no").
