### ISSUE TITLE
Serious Bug: Restore individual Web Domain from backup also restores all sub Web Domains of the restored parent Web Domain

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#702]
### In a few words, please describe the issue that you're experiencing:
Found a pretty serious bug when you restore a web domain via the restore and you have sub domains of that domain. It restores all of them for example lets say you have 3 sites pizza.test.com cheese.test.com as well as test.com. If you restore test.com web domain from backup it also restores the other sub domains of that parent web domain.

### What steps did you take when the issue occured? 
1. Login to Web Interface click backups tab 
2. Click the backup file name f. ex admin.2020-02-12_05-10-04.tar
3. select restore on a root web domain that has several web sub domains
4. Once Done check your email it will state it restored the web domain plus all the web sub domains as well.

### Expected behavior:
It should only restore the web domain you select

### Operating system distribution and release:
Ubuntu 18.04.4

### Which version of Hestia Control Panel is currently installed?
1.06 and 1.1 Master

### Which branch are you using?
both release and master

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)
- PostgreSQL

### Additional notes:
This may affect restoring other individual backup that accompanys a sub Doamin like DNS and Mail Domains. This is a warning for anyone that uses restore and have sub domains of a parent domain as they may lose their work.

**Comment by Lupul** [comment]
This sounds bad, will try to reproduce on the latest master soon

**Comment by johnnyq** [comment]
@Lupul Looks like it affects the latest master as well. I run both and can reproduce it on both instances, im going to try just restoring a sub web domain and see what happens

**Comment by johnnyq** [comment]
Did some more testing, restoring an individual sub web domain works just fine.

**Comment by Lupul** [comment]
yes, I can confirm this on my side too, I suspect there is a greedy grep in the restore script.

**Comment by Lupul** [comment]
Pushed a fix, can you confirm it fixes the issue for you

**master**: bin/v-restore-user line 287
**release**: bin/v-restore-user line 286
```diff
--        domains=$(echo "$backup_domains" |egrep -f $tmpdir/selected.txt)
++        domains=$(echo "$backup_domains" |egrep -x -f $tmpdir/selected.txt)
```

**Comment by johnnyq** [comment]
NICE!! @Lupul

**Comment by johnnyq** [comment]
I can confirm @Lupul it has fixed the issue

**Comment by Lupul** [comment]
I'm surprised this issue didn't come up in the past on HestiaCP or on VestaCP forums, that code was almost 4 year old

**Comment by johnnyq** [comment]
@Lupul Yeah that is super weird how it slipped by. I didn't notice it until I had to restore a clients web domain that also has several sub web domains.

**Comment by ScIT-Raphael** [comment]
Thanks for reporting @johnnyq and thanks for the fast fix @Lupul, going to close the issue now.
