### ISSUE TITLE
Feature Request: Docker container and reverse proxy support for domain/subdomain => container

### ISSUE THREAD

**Issue by animeai** [hestiacp/hestiacp#706]
Docker is the simplest way to install a multitude of software and I believe adding docker support to HestiaCP would help raise it above the competition. I don't believe there would be a requirement for HestiaCP to manage its own docker packages which would simplify things.

Requirements: 
- Set up and install docker images from the HestiaCP Panel through either
  - Connection to dockerhub and allow users to select image
  - Docker compose
  - Docker command
- Add a section to the HestiaCP control panel to monitor user's docker images. This could be done with a reverse proxy to a service such as portainer. Portainer could also be used to deploy new images.
- Add a /home/user/docker directory for persistent data. Ensure this directory is included in backups
- Allow nginx/apache to be used as remote proxies to access containers on ports via domain/subdomain. Ensure letsencrypt is enabled for these domains/subdomains. Additionally allow mapping to a directory (domain.com/container) if the user doesn't want to use or can't use a whole domain or subdomain.
- Add package permissions to enable/disable docker and limit the number of containers allowed per user
- Automatically set software firewall rules to allow access to the selected ports containers run on if they are not mapped to a subdomain/domain.
- Set up DNS A-records when creating the container if it is mapped to a new domain/subdomain.

All of this with the exception of limiting the number of containers can be done manually via SSH but this is highly inconvenient, especially if you have a large number of users. 

Future enhancements to this could allow for select docker packages to have installation and persistent data directories set up by HestiaCP for specific and relevant software.

**Comment by johnnyq** [comment]
This would be a great as an optional component of the Hestia install, maybe down the line or if someone wants to do a pull request. Currently they are working on releasing 1.1 and in the next version after 1.1 they are focusing on mail.

**Comment by FalzoMAD** [comment]
I tend to say that we should focus on the control panel part and _not_ add additional stuff like that. using docker is fine, but should not be an issue for any sysadmin to install it in parallel - even with whatever GUI is needed.

for the proxy thing I see your point, though the work required to handle inputs for different ports and such will most likely be out of proportion for quite a while. feel free to start developing of course and put in pull requests, however I think we don't have the ressources to dive into that right now.

proxying by the way can easily be achieved by adding custom configs in the conf-dir per web-domain...

(and don't forget, Hestia does not aim for being any competition, it's there to ease our management needs for the most general webhosting related task... bringing docker into that is understandable but I'd consider it pandoras box ;-))

**Comment by ScIT-Raphael** [comment]
>feel free to start developing of course and put in pull requests, however I think we don't have the ressources to dive into that right now.

@FalzoMAD is complete right here, I'll going to close this request. We are always open for pull requests if you want to start the development on this part!
