### ISSUE TITLE
Bug: PostgreSQL repo upgrade: keeps old version 10 and also installs version 12 but the DBs default to Version 10

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#707]
### In a few words, please describe the issue that you're experiencing:
I have been running 1.1 master on a vm for awhile and continually update it to test and report bugs. I noticed that when it added the newest postgresql apt repo and installed it - it also kept the old  version installed too, and default to the old version when you create a DB or use a DB

### What steps did you take when the issue occured? 
1. install 1.06
2. update to 1.1 master v-update-sys-hestia-git master
3. apt get update
4. reboot

### Expected behavior:
To remove the old PostgreSQL but still keep DBs if any and default to using the new PostgreSQL

### Operating system distribution and release:
Ubuntu 18.04.4 LTS
### Which version of Hestia Control Panel is currently installed?
1.1 Master

### Which branch are you using?
Master
### When did this issue occur? After a clean installation, or after an upgrade?
After Upgrade

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)
- PostgreSQL

### In order to better assist, please post any relevant log information below:

Here is ps -axu output showing both version install
Nextcloud also states its using version 10 postgresql instead of 12 
```
postgres   363  0.0  0.3 351312 27692 ?        Ss   18:11   0:00 /usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/12/main -c config_file=/etc/postgresql/12/m
postgres   364  0.0  0.3 350420 27240 ?        S    18:11   0:00 /usr/lib/postgresql/10/bin/postgres -D /var/lib/postgresql/10/main -c config_file=/etc/postgresql/10/m


```

**Comment by johnnyq** [comment]
Also I noticed 3 Postgresql Services I can stop and start

```
root@web01:/etc/apt/sources.list.d# service postgresql
postgresql          postgresql@10-main  postgresql@12-main
```
it looks like postgresql references both postgresql@10 and postgresql@12

I did the following

`service postgresql stop` -- Stops both services from running
`service postgresql@12` -- Starts PostgreSQL 12 

Hestia cannot connect to it to create DBs

**Comment by johnnyq** [comment]
I just tested a clean install of Hestia 1.1 with PostgreSQL and it just installed PostgreSQL 12, which is what we want, but I upgraded from 1.06 Hestia to 1.1 and now I have two instances of PostgreSQL running 10 and 12 with my databases being stuck at 10 and not using 12. I can not seem to figure out how to migrate my DBs over to PostgreSQL 12 and just keep 12 installed and remove 10. Any help would be much appreciated, i'm really at a loss here.

**Comment by ioannidesalex** [comment]
Will be fixed at the next release.

**Comment by johnnyq** [comment]
Excellent!! Thanks @ioannidesalex

**Comment by ghost** [comment]
@johnnyq, can you check with a recent build to see if this is still happening for you?

**Comment by johnnyq** [comment]
Hi @kristankenney I have this issue on one of production boxes that runs only Nextcloud instances. I'm afraid to do so right now due to the many users currently using it.

**Comment by johnnyq** [comment]
@kristankenney I did an upgrade on this box, I first did the Hestia 1.2 update but still showed two instances of postgresql running 10 and 12 verified it was using the the postgresql 10 under nextcloud info. I then did a full upgrade to 20.04 and did an apt install --reinstall hestia, but still no luck

**Comment by ghost** [comment]
Thanks for following up on this one @johnnyq, we'll take a look into it. :)

**Comment by jaapmarcus** [comment]
You should just follow the instructions on the Postgresql  website. 

https://www.postgresql.org/docs/12/pgupgrade.html

But this code is the probally the cause of the issue
https://github.com/hestiacp/hestiacp/blob/320442352d3c902eeec60749be5768aa2bee7d2a/install/upgrade/versions/1.1.0.sh#L141-L155

Please follow the instructions and it should be fine. In the future we shouldn't just upgrade the any version from PostgreSQL without a manual upgrade script. 

For the few rare cases it is probably not worth spend the time to create an upgrade script...
