### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by susinths** [hestiacp/hestiacp#708]
Hi,
thanks for your fork, it's been long pending really! 
VestaCP has support for CentOS and not only Debian based systems. From the main site, only Debian and Ubuntu is listed as supported OSes. 

Will we see CentOS support at some point?

Thanks

**Comment by hestiacp** [comment]
Currently we do not support CentOS due to lack of RedHat/CentOS devs - we focused ourself to bring a stable solution with the ressources we have. If there are any devs that would like to implement centos support, we're of course willing to integrate it in hestia.

**Comment by susinths** [comment]
I see.
I will see if i can fork the project and get it running on CentOS 8 when time allows.

**Comment by ScIT-Raphael** [comment]
That would be awesome, just share your state with us and let us know, if you need any additional informations.

**Comment by SjamonDaal** [comment]
This is the only reason we are still running on VestaCP.
@susinths please let me know if you need any help with something. I'll try to help when time allows.
