### ISSUE TITLE
Feature Request: Update Roundcube Page title and footer based off the domain being accessed

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#709]
### In a few words, please describe the issue that you're experiencing:
Currently the default title bar for webmail is 

> Roundcube Webmail:: Welcome to Roundcube Webmail

and the footer is 

> Roundcube Webmail

My suggestion would be to replace the title with the domain being used to access webmail for example lets say we have 2 domains thedoctor.com and example.com. When you goto mail.example.com it should show 

> example.com - Mail

 in the title bar. and for the footer just show example.com. This way when someone bookmarks the page it holds the true title. Also it would be nice to remove the roundcube image and just replace it with an envelope and and just say Mail. These are some suggestions of some clients that we host.

**Comment by ScIT-Raphael** [comment]
Thanks for the feature request, currently we do not have enough time to fullfill every request which this is also one of it. If you like, you can adjust the roundcube webmail on your own and provide us a pull request, we would love to implement it :).

**Comment by vvcares** [comment]
short simple answer :  >> /etc/roundcube/config.inc.php
edit  this attribute: 
[original..]
$rcmail_config['product_name'] = 'Roundcube Webmail';

[change to..]
$rcmail_config['product_name'] = $_SERVER['HTTP_HOST'];
-------------------------------------------
Meantime we have a blog post with more details as [roundcube webmail custom config file]($rcmail_config['product_name'] = $_SERVER['HTTP_HOST'];)

Here the idea we provide is not to go and change anything on the original config file, but we adding our custom webmail config file together with the original. So,in future if there is any updates, we simply just include this custom file again - That's it..!

**Comment by vvcares** [comment]
short simple answer :  /etc/roundcube/config.inc.php
edit  this attribute: 
original..
$rcmail_config['product_name'] = 'Roundcube Webmail';
change to..
$rcmail_config['product_name'] = $_SERVER['HTTP_HOST'];
-------------------------------------------
Meantime we have a blog post with more details as [roundcube webmail custom config file]($rcmail_config['product_name'] = $_SERVER['HTTP_HOST'];)

Here the idea we provide is not to go and change anything on the original config file, but we adding our [custom webmail config file](https://vvcares.com/blog/2020/02/how-to-change-roundcube-webmail-title-login-details) together with the original. So,in future if there is any updates, we simply just include this custom file again - That's it..!

**Comment by Lupul** [comment]
@vvcares solution works, if you want to drop "mail, webmail" subdomain use the following line:
```php
$rcmail_config['product_name'] = htmlspecialchars( preg_replace('/^(web)?mail\./i', '', $_SERVER['HTTP_HOST']) , ENT_QUOTES);
```

**Comment by vvcares** [comment]
> @vvcares solution works, if you want to drop "mail, webmail" subdomain use the following line:
> 
> ```
> $rcmail_config['product_name'] = htmlspecialchars( preg_replace('/^(web)?mail\./i', '', $_SERVER['HTTP_HOST']) , ENT_QUOTES);
> ```

Hi Lupul, your string is just to remove IF there is text on the url contains webmail or something.
If my url is 'xxx.root.com', then better to use the below string..

preg_match("/[^\.\/]+\.[^\.\/]+$/", $_SERVER['HTTP_HOST'], $matches);
$rcmail_config['product_name'] = $matches[0];

This will remove any subdomain variables & display only the root domain name.
Correct me if im wrong.
