### ISSUE TITLE
Installer shows a line from apt-get install

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#71]
### Operating System (OS/VERSION):

Debian 9, Ubuntu 18.04

### Installed Software (what you got with the installer):

Apache, Nginx, PHP-FPM, MySQL

### Steps to Reproduce:

bash hst-install.sh

### Other Notes:

Came up after change to write in log file, it shows now the following line:
Extracting templates from packages: 100%

**Comment by ioannidesalex** [comment]
Maybe try -q or -qq flags. However, output to log file will also be minimized.

**Comment by ScIT-Raphael** [comment]
Added -qq flag to prevent the unwanted output.
