### ISSUE TITLE
Manual php update from fpm

### ISSUE THREAD

**Issue by xpiREC** [hestiacp/hestiacp#710]
I want to manually make changes from php7.3-fpm to php7.4-fpm, but when I add a new domain, the old version (7.3) fpm is restarted, how can I change it?

### Operating system distribution and release:
Ubuntu 18.04.3 LTS

### Which version of Hestia Control Panel is currently installed?
VERSION='1.0.6'

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM
- PHP-FPM

### Which of the following server roles are installed on your server?
- MySQL (MariaDB)
- Nginx + PHP-FPM
- PHP-FPM

**Comment by ScIT-Raphael** [comment]
Can you please write the steps you did? Probaly you would like to wait for release 1.1.0, we currently have rebuilded the whole multiphp backend there and made it much easier to handle different php versions.

**Comment by xpiREC** [comment]
I care about performance so I don't want to use multiphp.
 Steps I did:
 - Hestiacp installation with nginx, fpm and mysql options.
- I manually installed php7.4
- I turned off php7.3-fpm and php7.4-fpm
- I went to /etc/php/7.3/pool.d/ and copied the content to
/etc/php/php7.4/poll.d/
- then I turned on php7.4-fpm
- I switched to adding a new domain, when I do it receives php7.3-fpm
information is restarting but the files are created in the new location
/etc/php/php7.4/pool.w/

sob., 29 lut 2020, 12:02 użytkownik Raphael Schneeberger <
notifications@github.com> napisał:

**Comment by Lupul** [comment]
How much slower did you find multiphp to perform compared to regular php-fpm ?
