### ISSUE TITLE
Can't detect Digitalocean Public IP

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#713]
### In a few words, please describe the issue that you're experiencing:

Can't detect Public IP on Digitalocean 

![image](https://user-images.githubusercontent.com/39749258/75696767-1ac18880-5cd2-11ea-80b0-daf4c68fcc32.png) 

### What steps did you take when the issue occured? 

i've done the fresh installation of 1.0.6 and then updated it to beta 1.1.0

bash hst-install.sh --apache yes --nginx yes --phpfpm no  --multiphp yes --vsftpd no  --proftpd yes --named yes --mysql yes --postgresql no --exim yes --dovecot yes --clamav no --spamassassin no --iptables no --fail2ban no --quota yes --api yes --lang en --hostname s1.b2btech.in --email alber@b2btech.in --password ***** --force

rm hestia_1.1.0_amd64.deb
wget -N https://apt.hestiacp.com/beta/hestia_1.1.0_amd64.deb
apt install setpriv # on debian use 'util-linux'
dpkg -i hestia_1.1.0_amd64.deb

i'm restoring from the backup of old hestiacp server to a new server.
I've moved the IP Address to public IP and it works fine. 
 
### Expected behavior:

should detect the public IP and use that Server IP while restoring the backup.

### Operating system distribution and release:
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-76-generic x86_64)

### Which version of Hestia Control Panel is currently installed?
1.1.0 

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by tudorr89** [comment]
You can just edit the hosting package and change the internal IP to the public one. After that all newly added domains within the package will have the public IP selected

**Comment by ScIT-Raphael** [comment]
As @tudorr89 wrote, he's completly right :). Going to close this issue now.
