### ISSUE TITLE
Apache2 RemoteIP is not set for additional IPs

### ISSUE THREAD

**Issue by FalzoMAD** [hestiacp/hestiacp#715]
Hestia 1.0.6 /w nginx+apache2

IP forwarding from nginx to apache does not work properly on systems with multiple IP addresses, esp. not for the secondary IP(s).
Reason seems to be that in /etc/apache2/mods-enabled/remoteip.conf only the main IP gets added via RemoteIPInternalProxy directive, so apache is not aware, that it has to look for the x-forward header ;-)

haven't drilled down in to the scripts yet nor checked with v1.1, sorry if that's already handled a duplicate.

**Comment by Lupul** [comment]
This should be fixed in current master (v1.1.0), previous version (1.0.6) didn't create the apache2 remoteip.conf file and never got updated with newly added sys-ip's

**Comment by ghost** [comment]
This is corrected in v1.1.0; if you experience a regression please reopen the issue report.
