### ISSUE TITLE
Bugfix: When server SSL is renewed, vsftpd uses old certificate

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#717]
### The content below is simply a template. 

**To better assist in troubleshooting and aid with our debugging processes, we ask that you please delete any unnecessary sections below when filling out your issue report.**

**Important: Please DO NOT include any personal or sensitive information in your issue reports, including usernames, passwords, or email addresses.**

### In a few words, please describe the issue that you're experiencing:
It seems that ftp service is not restarted when SSL server is renewed (for example LetsEncrypt SSL) - location /usr/local/hestia/ssl/certificate.crt

### What steps did you take when the issue occured? 
Attempted to logia via vsftpd

### Expected behavior:
Updated certificate should be used

### Operating system distribution and release:
18.04

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- Mail (Exim only)
- MySQL (MariaDB)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by johnnyq** [comment]
Hi @ioannidesalex This looks to be fixed in the upcoming 1.1 release see here a25b114d9c7536ee95c6e48374b4f74198ca4057
