### ISSUE TITLE
UI Bug - Disk Size and Bandwidth columns shows 0MB when data is under 1 MB

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#720]
### In a few words, please describe the issue that you're experiencing:
Disk Size column under WEB, Mail and DB, is showing 0MB even when there is data there under 1MB for example if there is 500KB of data then display 500KB or even 0.5MB
This also affects the Bandwidth column under Web

### Operating system distribution and release:
18.04.4LTS

### Which version of Hestia Control Panel is currently installed?
1.06

### Which branch are you using?
release

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)
- PostgreSQL

**Comment by johnnyq** [comment]
This may also apply to backups and statistics

**Comment by rmj-s** [comment]
Disk size is formatted using [humanize_usage_size()](https://github.com/hestiacp/hestiacp/blob/84569da7cb2ef3474aac464950e27be0f6926806/web/inc/main.php#L223) & [humanize_usage_measure](https://github.com/hestiacp/hestiacp/blob/84569da7cb2ef3474aac464950e27be0f6926806/web/inc/main.php#L242). I directly run these functions by supplying usage 0.0002 and it returned 0.0002mb which I think is correct, I might be wrong as I didn't directly tested it in control panel.
```
echo humanize_usage_size('0.0002').humanize_usage_measure('0.0002');
//0.0002mb
```

**Comment by rmj-s** [comment]
Disk size is formatted using [humanize_usage_size()](https://github.com/hestiacp/hestiacp/blob/84569da7cb2ef3474aac464950e27be0f6926806/web/inc/main.php#L223) & [humanize_usage_measure](https://github.com/hestiacp/hestiacp/blob/84569da7cb2ef3474aac464950e27be0f6926806/web/inc/main.php#L242). I directly run these functions by supplying usage 0.0002 and it returned 0.0002mb which I think is correct, I might be wrong as I didn't directly tested it in control panel.
```
echo humanize_usage_size('0.0002').humanize_usage_measure('0.0002');
//0.0002mb
```

**Comment by jaapmarcus** [comment]
The issue is not the humanize_usage_size / humanize_usage_measure function. But the fact we save the stats (Data consumption, storage usage, ect...) as integers and as megabytes. This will mean that every thing needs to be rewritten and it is not feasible / useful
