### ISSUE TITLE
UI Feature Request: Add Acknowledge All button on top of the notifications list

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#721]
### In a few words, please describe the issue that you're experiencing:
Add an Acknowledge all button at the top of the notification drop down. This would be a great feature especially if you haven't logged into the server in awhile and you had a bunch of backup complete that need acknowledged.

### Which version of Hestia Control Panel is currently installed?
1.06

### Which branch are you using?
release

**Comment by ioannidesalex** [comment]
Not the case anymore. Thus can be closed.
