### ISSUE TITLE
Feature Request: Cron tester

### ISSUE THREAD

**Issue by netanonima** [hestiacp/hestiacp#724]
Is that possible to add a section where we can execute a cron the same way it's going to be launch the next time? Like this we could see a console message returned directly. 
A field where we can choose the user launching the script can also be nice. 

Thanks for your huge work!

**Comment by ScIT-Raphael** [comment]
Thank you for your feature request, I just split it in two points:
> Is that possible to add a section where we can execute a cron the same way it's going to be launch the next time?

I think the needed effor to implement the function would be quiet high, personaly I just test the line over cli/ssh to be sure all is working properly, then it is only a copy&paste.
>A field where we can choose the user launching the script can also be nice.
If you add a cronjob, there is only one user that can be runned - the hestia user where you create the cronjob in.

**Comment by netanonima** [comment]
Thanks. 
If you're doing a copy paste on a console, you can't be 100% sure that it's going to work when the server will do it alone. 
For being honest that's a feature available on webmin (when you're editing a cronjob) and I think it's very usefull.

**Comment by ScIT-Raphael** [comment]
It's good for webmin that they have this feature, but this is not a argument for us to implement it :).

How should the check work? Basicly this would need a v-script that triggers/validates the line, but this would be similar to run it in ssh/cli.

**Comment by netanonima** [comment]
I know that it's not a reason ^^

I don't know how it works, I'm just a hum....user.

**Comment by ioannidesalex** [comment]
In my opinion this is out of scope of Hestia. I believe Hestia is and should remain a Hosting Panel for system administrators to manage their hosting needs fast and with ease. It's not a full featured server management tool and should not be considered a terminal replacement. I can see a reason for maybe adding a "Run now" button, but not for testing a cron.

**Comment by ScIT-Raphael** [comment]
As @ioannidesalex wrote, I also think this is out of the scope of hestia -> closed.
