### ISSUE TITLE
apt.hestiacp.com missing public key. Is the HestiaCP APT repository working?

### ISSUE THREAD

**Issue by rkkoszewski** [hestiacp/hestiacp#725]
Hi, I just noticed that apt seems to be failing to verify the public key of apt.hestiacp.com. The output can be seen below.

```
root@server:~# apt-get update
Hit:1 http://nginx.org/packages/mainline/debian stretch InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease                                           
Get:3 http://security.debian.org stretch/updates InRelease [94.3 kB]                           
Hit:4 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/debian stretch InRelease                      
Get:5 http://ftp.debian.org/debian stretch-updates InRelease [91.0 kB]                                     
Hit:6 http://ftp.debian.org/debian stretch Release                                               
Get:7 https://packages.sury.org/php stretch InRelease [6,760 B]
Get:9 http://security.debian.org stretch/updates/main amd64 Packages [520 kB]
Get:10 http://security.debian.org stretch/updates/main Translation-en [230 kB]
Get:12 https://packages.sury.org/php stretch/main amd64 Packages [136 kB]                  
Err:8 https://apt.hestiacp.com stretch InRelease             
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5
Fetched 1,078 kB in 1s (783 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.hestiacp.com stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5
W: Failed to fetch https://apt.hestiacp.com/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A189E93654F0B0E5
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Not sure if this is just a temporary outage or some other issues on my side.

**Comment by ScIT-Raphael** [comment]
According to our readme (https://github.com/hestiacp/hestiacp), please update the gpg key:

`wget -qO - https://gpg.hestiacp.com/deb_signing.key | sudo apt-key add -`

**Comment by ScIT-Raphael** [comment]
I just leave the issue open for now, so other users can see it directly, will be closed in a few days.

**Comment by rkkoszewski** [comment]
@ScIT-Raphael I was actually looking for it on hestiacp.com, I didn't think that it could be in the Readme file (Or any other of the many file names that are used now a days in GitHub repos for breaking changes). Maybe having an "Announcements" section on the hestiacp.com website, or even just mention on the page that any announcements or breaking changes can be seen in the Readme file in the main repository could be a good place to have that information.

This would also avoid having a new issue to be opened on GitHub every time something like this happens.

**Comment by ScIT-Raphael** [comment]
Basicly it's here (readme isnt one of alot, it is this file which will show as project homepage) and also in our forum with a sticky note, the website is currently in redesign :)

**Comment by vvcares** [comment]
try this via SSH/CLi
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A189E93654F0B0E5`

I seen the output as:
`gpg: key A189E93654F0B0E5: "Hestia Control Panel <info@hestiacp.com>"`

what is your routput..?

**Comment by ScIT-Raphael** [comment]
There is nothing different, this is our repository key, we've sent the new one to debian, gnupg and ubuntu keyserver.

**Comment by vvcares** [comment]
hi Raphael,
Abount linux systems, Hestia team guys knows much better than us..

Here, i dont meant there is something wrong on the key itself, but there is something have to workaround on our servers, which may be out of HESTIA's scope.

Kindly have a look on this [snippet..](https://i.ibb.co/Svf9RfR/Capture.jpg)

**Comment by ScIT-Raphael** [comment]
As I wrote: the official way is using wget as suggested above and in our docs, we just sent it to some gpg servers to have it also there.

**Comment by vvcares** [comment]
Ok, Thank you guys. Cheers..!
