### ISSUE TITLE
PHP-FPM not contains phppgadmin into open_basedir

### ISSUE THREAD

**Issue by gatsukito** [hestiacp/hestiacp#726]
### In a few words, please describe the issue that you're experiencing:
phppgadmin does not working with php-fpm, you can see a typical config error.
### What steps did you take when the issue occured? 
1. Install hestiacp with postgresql
2. Open url https://{domain}/phppgadmin

### Expected behavior:
The web domain should have been showed correctly.

### Does this issue always occur, or is it intermittent?
Always

### Operating system distribution and release:
Debian 9.12

### Which version of Hestia Control Panel is currently installed?
1.1.0

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
After a clean installation

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP
- PHP-FPM + Multi-PHP
- Postgresql

### Answer
If you edit tpl file from php-fpm (/usr/local/hestia/data/templates/web/php-fpm) and you concat into open_basedir "/etc/phppgadmin:/usr/share/phppgadmin", phppgadmin loads correctly

**Comment by ScIT-Raphael** [comment]
Has been resolved in https://github.com/hestiacp/hestiacp/commit/9024409b73f9333c888bde178a15e6961367c26e and will be added with the next release.
