### ISSUE TITLE
phppgadmin 5.1 does not support postgresql 12

### ISSUE THREAD

**Issue by gatsukito** [hestiacp/hestiacp#728]
### In a few words, please describe the issue that you're experiencing:
After stablish connection with phppgadmin, I have seen that my postgresql 12 does not works with phppgadmin.

![image](https://user-images.githubusercontent.com/49730910/76698506-e96a9480-66a3-11ea-8309-141e99c14f60.png)

Official documentation says that postgresql supported is from 8.4 to 11.x, but with hestia release 1.1.0, postgresql repository returns version 12, [phpgadmin sourceforge](http://phppgadmin.sourceforge.net/doku.php)

It seems that with phppgadmin 7, from github repo, supports version 12, ref: [xzilla blog](https://xzilla.net/blog/2019/Sep/Introducing-phpPgAdmin-7-dot-12-dot-0.html)

### What steps did you take when the issue occured? 
1. Enter to phppgadmin url
2. Change pg_hba.conf for login because normal login does not work
```
# "local" is for Unix domain socket connections only
#local   all         all                               ident
local   all         all                               md5 
```
3. Login with valid user and password. Phppgadmin show error message about postgresql version

### Expected behavior:
If phppgadmin 5.1 does not work with postgresql 12 from official repo setted by hestia in apt sources, it will be mandatory change software for manage postgresql. It seems that new version of phppgadmin hosted in github it works, repo: [phppgadmin github](https://github.com/phppgadmin/phppgadmin/)

### Does this issue always occur, or is it intermittent?
Every time

### Operating system distribution and release:
Debian 9.12

### Which version of Hestia Control Panel is currently installed?
1.1.0

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
After a clean installation

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- PHP-FPM + Multi-PHP
- Postgresql

### Local solution
I have installed in my laptop pgadmin and I have connected to postgresql server hosted with hestia, it works.

**Comment by gatsukito** [comment]
Can you review this issue?

**Comment by ScIT-Raphael** [comment]
We will going to implement a autoupdater like we have it for phpmyadmin, so we will grab the current version from their github project site: https://github.com/phppgadmin/phppgadmin

**Comment by ioannidesalex** [comment]
I also get the same error message with postgresql13 and phpgadmin 7.12.1

**Comment by Draco-Zero** [comment]
In version 1.5.8, the problem with phppgadmin is also relevant.

**Comment by Digioso** [comment]
And it still is with version 1.6.5 of HestiaCPI with Postgres 15.

**Comment by jaapmarcus** [comment]
Yes it is even worse the current version of Pgadmin doesn't support 15 at all...

But probally you want to upgrade to 1.6.14...

**Comment by Digioso** [comment]
Oh, sorry, I'm using 1.6.14. I just checked. No idea where I got 1.6.5 from...
But well... It's pretty easy to change Postgres Configuration to allow remote connection and use PGAdmin 4 to connect. But still...
HestiaCP should use versions that are compatible to each other....

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/pull/3288



> Oh, sorry, I'm using 1.6.14. I just checked. No idea where I got 1.6.5 from...
> But well... It's pretty easy to change Postgres Configuration to allow remote connection and use PGAdmin 4 to connect. But still...
> HestiaCP should use versions that are compatible to each other....

Issue is caused mainly because the development of phppgadmin is dead. So even we wanted it we couldn't upgrade to a newer version as it doesn't exist.  We have decided the best way forward forking the phppgadmin project and applying the patches our self...

**Comment by Digioso** [comment]
Thanks a lot!
That means the patches will be applied in the next HestiaCP version?

**Comment by jaapmarcus** [comment]
When we release 1.7.0 at least
