### ISSUE TITLE
How to point external CNAME domain to Hestia hosted domain?

### ISSUE THREAD

**Issue by Medow** [hestiacp/hestiacp#729]
Hello all:
I have an external domain name that using clouflare DNS. I point that domain using CNAME to one of my domain that hosted in my server using Hestia panel.
The problem that the external domain that pointed using CNAME as always showed the main default website just like when we access our server using main IP address.
I need to make the CNAMEed domain show the domain which i pointed it to it.
Thanks.

**Comment by rmj-s** [comment]
Add the external domain as Aliase for hosted domain in HestiaCP->Web->Edit->Aliases
