### ISSUE TITLE
MariaDB status not showing

### ISSUE THREAD

**Issue by gatsukito** [hestiacp/hestiacp#732]
### In a few words, please describe the issue that you're experiencing:
I don't see MariaDB status

### What steps did you take when the issue occured? 
1. Log into the Hestia Control Panel
2. Click on server button
3. Click on task monitor button
4. Click on View Advanced Details
5. Click on DB button. I have MariaDB and PostgreSQL and I only see postgresql status

### Expected behavior:
The web should show me MariaDB and PostgreSQL status.

### Does this issue always occur, or is it intermittent?
Every time

### Operating system distribution and release:
Debian 9.12

### Which version of Hestia Control Panel is currently installed?
1.1.0

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP
- PHP-FPM + Multi-PHP
- MariaDB + PostgreSQL

### In order to better assist, please post any relevant log information below:
![image](https://user-images.githubusercontent.com/49730910/77015961-a3008880-6976-11ea-875b-5fab270c93dd.png)

![image](https://user-images.githubusercontent.com/49730910/77015997-b57ac200-6976-11ea-9e92-6d8438c4f3d7.png)

**Comment by ioannidesalex** [comment]
I have only MariaDB (not PostgreSQL) and shows properly. Maybe it's something about listing both of them.

**Comment by ghost** [comment]
Thanks for your report @gatsukito, we'll take a look into this and follow up when we have more information.

**Comment by gatsukito** [comment]
I see than this issue is fixed in version 1.1.1. Close issue
