### ISSUE TITLE
BUG: v-change-database-owner DB USER - Creates SQL Files under /

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#733]
### In a few words, please describe the issue that you're experiencing:
When moving databases over using v-change-database-owner DB USER as the root user I noticed that it was creating .sql files in the the root directory "/"

### What steps did you take when the issue occured? 
1. Move Database over to a new user using v-change-database-owner DB USER

### Expected behavior:
It should not create files at /

**Can you reproduce the issue:** always
**OS:** ubuntu 18.04.4 - LXC
**Hestia ver:** 1.1.0
**Branch:** release

### When did this issue occur? After a clean installation, or after an upgrade?
after upgrade although i have never moved databases this was before 1.1 so im not sure if this is a new issue or not

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

I upgraded from 1.0.6

### In order to better assist, please post any relevant log information below:
some files that it created under /
```
-rw-r--r--   1 root   root          38 Mar 19 17:33 admin_inv.mysql.admin_inv
-rw-r--r--   1 root   root        9217 Mar 19 17:33 admin_inv.mysql.sql
-rw-r--r--   1 root   root         524 Mar 19 17:33 admin_inventory.mysql.admin_default
-rw-r--r--   1 root   root        8105 Mar 19 17:33 admin_inventory.mysql.sql
-rw-r--r--   1 root   root          41 Mar 19 17:33 admin_johnny.mysql.admin_johnny
-rw-r--r--   1 root   root       94543 Mar 19 17:33 admin_johnny.mysql.sql
```

**Comment by Lupul** [comment]
Confirmed
