### ISSUE TITLE
BUG: v-change-domain-owner - Configuration not moved between users correctly

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#734]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
When I move sites from admin user to a normal user using v-change-domain-owner DOMAIN USER The site is accessible, but does not redirect to HTTPS, when I checked the WEB Config I see  Enable automatic HTTP-to-HTTPS redirection is checked but is not being honored. Im able to fix the problem by unchecking Enable automatic HTTP-to-HTTPS redirection click save then checking Enable automatic HTTP-to-HTTPS redirection then save.

### What steps did you take when the issue occured? 
1. Move a site to a different user that has all options under Enable SSL for this domain checked using v-change-domain-owner DOMAIN USER
2. Goto the site options

### Expected behavior:
When Sites are moved over it should carry the options Enable automatic HTTP-to-HTTPS redirection and the interface should show it properly

### Does this issue always occur, or is it intermittent?
always
### Operating system distribution and release:
Ubuntu 18.04.4 LXC

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

1.1.0

### Which branch are you using?
release
### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your answer here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by johnnyq** [comment]
This option  Enable HTTP Strict Transport Security (HSTS) is checked but not enabled as well, until I uncheck it click save then check it again

**Comment by ghost** [comment]
Thanks for the report @johnnyq, I'll patch these this weekend.

**Comment by johnnyq** [comment]
Super!! Thanks @kristankenney

**Comment by ghost** [comment]
For the mail component when LE doesn't carry over -- do the services still pick up the SSL certificate when accessing them via a client like Outlook or Thunderbird etc?

**Comment by johnnyq** [comment]
that's a good question @kristankenney, I didn't test that, but will do so and report back today

**Comment by ghost** [comment]
Can you set up a test install and run `v-update-sys-hestia-git bugfix-sslconf` to confirm whether this is fixed for web domain SSL/HSTS?

**Comment by johnnyq** [comment]
It worked! it transferred the domain and kept the SSL for the WEB Domain but not the Mail Domain

**Comment by johnnyq** [comment]
@kristankenney as you were mentioning earlier the services still pickup the SSL, so the certificate is working just not being shown enabled on the UI under the mail tab

**Comment by ghost** [comment]
Thanks for confirming the fix for Web domains works as expected, I'll get the situation with mail's state not showing correctly sorted out here soon. :)

**Comment by ghost** [comment]
@johnnyq, can you run `v-update-sys-hestia-git master yes` on a test server and let me know the results? Thanks!

**Comment by johnnyq** [comment]
Looks good to me @kristankenney You can close this. Another one bites the dust!
