### ISSUE TITLE
BUG - v-change-domain-owner DOMAIN USER - Does not carry over LetsEncrypt for Mail Domain

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#735]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

When migrating domains to a different user from admin that has a mail domain that has letsencrypt enabled on the mail domain does not carry over to the migrated user.

### What steps did you take when the issue occured? 
1. Move site over that has mail domain with LE Enabled using v-change-domain-owner DOMAIN USER
2. Access the new user click on mail tab

### Expected behavior:
Mail Domain letsencrypt should carry over as well when moved

### Does this issue always occur, or is it intermittent?
always

### Operating system distribution and release:
Ubuntu 18.04.4 LXC

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

1.1.0

### Which branch are you using?
Please enter your answer here (e.g release, master, etc.)

Release

### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your answer here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ghost** [comment]
Closing this and tracking under #734 as it relates to the same component.
