### ISSUE TITLE
Can't add a value to php basedir

### ISSUE THREAD

**Issue by tudorr89** [hestiacp/hestiacp#736]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
Hello guys! Sorry for the stupid question, but for some reason, I can't seem to be able to add an open basedir value to an apache template. I've tried so far editing the /home/user/conf/web/example.com/apache2.ssl.conf and apache2.conf but with no luck. 
Also, in terms of editing the apache2 template, which file should be edited from /usr/local/hestia/data/templates/web/apache2/ ? 

I'm using default values on the domains (apache default template / php-fpm default template).

PS. In the older release(1.0.6), i could see the open basedir value stored in /home/user/conf/web/example.com/apache2.ssl.conf 

### Expected behavior:
To be able to add a basedir value to the apache template

### Does this issue always occur, or is it intermittent?
Yes

### Operating system distribution and release:
Ubuntu 18.04.3 LTS

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

1.1.0

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your answer here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:

AH01071: Got error 'PHP message: PHP Warning:  require(): open_basedir restriction in effect.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by johnnyq** [comment]
I had a similar issue Edit the Web Domain and modify the proxy template from default to hosting. Please let us know if that works.

**Comment by tudorr89** [comment]
Thanks Johnny! I've spent more than 4 hours with this issue.. For anyone else's reference:
1. Edit the Web Domain and modify the proxy template from default to hosting as @johnnyq suggested.
2. Edit `/usr/local/hestia/data/templates/web/php-fpm/default.tpl` and add your path
3. Run `v-rebuild-web-domain user domain.com`

**Comment by johnnyq** [comment]
Hi @tudorr89 Excellent i'm glad it worked lets leave this open for now, to get some feedback on this to possibly make any template name changes. I think default should be renamed to openbasedir restricted and hosting should be the new default template as wordpress and alot of other php scripts rely on it.

**Comment by ScIT-Raphael** [comment]
Hi Guys, sorry for the delayed catchup - but I've to write you here because the way you solved the issue can cause problems. Do never edit a default template, they will probaly overwritten during a hestia upgrade, also do not edit any files in /home/user/conf, they are autogenerated and will also been rewritten on a upgrade.

To solve your issue, you're probaly already on the right track, I would suggest to stay on the default template, do not use hosting - then COPY the default.tpl and default.stpl to a new name, adjust and select them from the hestia backend.

Let me know if this worked for you!
