### ISSUE TITLE
Feature Request: Enable SSL for this domain Logic

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#737]
When Enable SSL for this domain is active
Enable automatic HTTP-to-HTTPS redirection and Enable HTTP Strict Transport Security (HSTS) should be on by default and the options should not even be displayed, as this should be standard with enabling SSL.

**Comment by johnnyq** [comment]
This will also enforce excellent best security practice by default in which HestiaCP is leaning towards

**Comment by neto737** [comment]
It's not right. In some cases there's a necessity of accessing some pages without passing through the HTTPS. Like pages that loads things over HTTP

**Comment by ScIT-Raphael** [comment]
Sorry, closed by missclick.

Enable hsts by default isnt a good idea, maybe we can discuss auto ssl for the domain: but basicly there are already 2 checkboxes you can decide and activate on your own. I dont see a need to auto enable it.

**Comment by johnnyq** [comment]
@neto737 You can always create another domain or subdomain under web tab that doesn't have SSL enabled for http requests. @ScIT-Raphael I have been using HSTS for all my sites since it was introduced are there any downfalls for using it for normal wordpress websites. I'm wondering if I should disable it for some of my sites, does it affect performance or increase server load?

**Comment by ghost** [comment]
If you enable HSTS for a domain and then disable SSL at a later date, you run the risk of being presented with an error page that won't let you proceed due to how the caching and verification works.

However I am in favor of flipping **Enable automatic HTTP-to-HTTPS** to be on by default if Enable SSL is checked.

**Comment by neto737** [comment]
> If you enable HSTS for a domain and then disable SSL at a later date, you run the risk of being presented with an error page that won't let you proceed due to how the caching and verification works.
> 
> However I am in favor of flipping **Enable automatic HTTP-to-HTTPS** to be on by default if Enable SSL is checked.

I'm in favor too, but if we can disable this option later.

**Comment by ghost** [comment]
Yes, the option can be easily disabled afterwards.

**Comment by ioannidesalex** [comment]
I am also in favor of auto selecting the tickbox, not enforcing it in any way.

**Comment by johnnyq** [comment]
I agree with @kristankenney as well

**Comment by ghost** [comment]
There's a test build available in **feature-autossl** for the web domain portion if you'd like to test and report back @johnnyq.

**Comment by ScIT-Raphael** [comment]
feature-autossl is merged after successfully testing: https://github.com/hestiacp/hestiacp/pull/780
