### ISSUE TITLE
Feature Request: Remove Proxy Extensions option from Edit Web under nginx

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#738]
Thoughts on removing this option as i'm not sure its necessary for many users. I'm sure advanced users would just modify the template to change these settings. This should cleanup the UI and keep it simple and alleviate any confusion.

![Screenshot from 2020-03-20 12-58-06](https://user-images.githubusercontent.com/1812594/77187336-ae54d080-6aaa-11ea-8bfa-6fcfd9e3b69b.png)

**Comment by neto737** [comment]
I think it can have a checkbox to show or not the extensions there.

**Comment by ScIT-Raphael** [comment]
I dont see any reason to remove it, as @neto737 suggested make it hidden as default would ve an option. Also we anyway need to grey out the checkbox for nginx, you currently should not disable it :).

**Comment by johnnyq** [comment]
@ScIT-Raphael My bad, i meant just the proxy Extensions textarea but leave the Proxy Support NGINX and leave proxy template alone

**Comment by ghost** [comment]
From an accessibility standpoint, it's better to leave the extensions text label where it is.
