### ISSUE TITLE
Feature Request: Merge webmail and mail to just mail

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#739]
This will keep it super simple, as most mail providers use just mail.domain.EXT for all mail protocols including webmail. This goes along with Hestia's approach of keeping it simple

**Comment by ScIT-Raphael** [comment]
I think webmail is the most common way a user search his webmail, I don't see any reason to merge it together.

**Comment by johnnyq** [comment]
Hi @ScIT-Raphael I understand, I just saw something on the forum you can change the webmail alias on the config panel in Hestia, I must of passed that up, which works great!

**Comment by ioannidesalex** [comment]
Even though I also use mail and not webmail, I understand that there might be other users wanting to do it differently.
