### ISSUE TITLE
Feature Request: Migrate WEB Domain via UI

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#740]
this would be an excellent feature, as we can select sites and move them to a new user via the WEBUI instead of from command line v-change-domain-owner DOMAIN USER this should be only limited to the admin user. This could also work with DBs as well.

**Comment by ScIT-Raphael** [comment]
Infact we moved this feature request around since nearly two years, we decided to close it: We currently do not have enough time to implement such a function, also it isnt on our highest priority. Please feel free to provide a PR for it, we would love to implement it.
