### ISSUE TITLE
Feature Request: New Install Option: Automatically add ns records and primary domain

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#741]
this would be a neat feature to automatically add the primary domain to DNS and Web and add the ns1.domain.ext and ns2.domain.ext A Records automatically. This could just be optional, so not required. This could save some additional work that needs to be done during the initial installation.

**Comment by ioannidesalex** [comment]
You mean asking the user to input his/her nameservers during installation?

**Comment by johnnyq** [comment]
@ioannidesalex I think it would automatically assume that ns1 and ns2 records are the IP of box your installing HestiaCP on to, if BIND (DNS) is being installed as well. On another note it should add the host that was given during the install as an A Record as well.

So for example when you install Hestia it asks for a FQDN during install so if you enter lets say web01.example.com

it would create the domain example.com under web and dns and add **A** Records for ns1 and ns2 and an **A** Record for web01.

**Comment by ScIT-Raphael** [comment]
A strongly no from my side, because this is not the way how dns servers should builded up. It's not the idea of dns, to point it multiple times to the same ip.

Usualy you build up the dns server as standalone machines in different subnetworks and also probaly in different networks to provide ha.

I would suggest to get in contact with sample dns cluster builds and ways how to create them. Usualy even wikipedia is a good source for this :).

**Comment by johnnyq** [comment]
@ScIT-Raphael I fully agree with you but currently HestiaCP doesn't support multi separate servers. I would love to have mutliple dns servers setup on different subnets. Maybe a feature request for this in a future Hestia

**Comment by ScIT-Raphael** [comment]
Hestia does support it, the same way as already vesta did: http://vestacp.com/docs/#how-to-setup-dns-cluser

And even it would not have a implemented cluster function, you could even use the bind built in zone transfers to build up a cluster.

**Comment by ioannidesalex** [comment]
Well, in fact it supports creating a DNS Cluster.

**Comment by johnnyq** [comment]
That is SUPER! News! I saw that option one time looking through the config and never went back to revisit. I will read the documentation and try it out Thanks @ScIT-Raphael  @ioannidesalex
