### ISSUE TITLE
Feature Request: Upcoming Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#742]
Ubuntu will be releasing their new 20.04 LTS release come April 23, 2020, does anyone know if the current HestiaCP install works under the nightly release of 20.04, and if there are any incompatibilities?

**Comment by ScIT-Raphael** [comment]
Currently, we havent tested the installation, but Ubuntu 20.04 is on our to do list, as any LTS system.

**Comment by johnnyq** [comment]
Ill give it a test run and report back

**Comment by johnnyq** [comment]
Im attempting to test but how do I install hestia using the ubuntu-20.04 dev branch?

**Comment by johnnyq** [comment]
ignore that i found it on the github page

**Comment by johnnyq** [comment]
I downloaded the ubuntu installer via https://github.com/hestiacp/hestiacp/raw/core-ubuntu-20.04/install/hst-install.sh

Ran it

but I get the following errors upon install

```
Updating currently installed packages, please wait... E: The repository 'http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu focal Release' does not have a Release file.
E: The repository 'http://nginx.org/packages/mainline/ubuntu focal Release' does not have a Release file.
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu focal Release' does not have a Release file.
E: The repository 'https://apt.hestiacp.com focal Release' does not have a Release file.
and install fails
```

it looks like apt hestia and ondrej don't have ubuntu 20.04 focal in their repo yet

**Comment by ScIT-Raphael** [comment]
Currently, we need to wait for the used repositorys (mariadb, nginx, sury) to fully support Ubuntu 20.04. As soon as we have it, we gonna test and rework the installation process to support the released version. Currently this will be around 2-3 weeks after the official release.

**Comment by ScIT-Raphael** [comment]
The Ubuntu Server 20.04 LTS support has been added in to the master branch, please check it out and test as much as you can :-).

Fast way to install it on a fresh and clean Ubuntu 20.04 Sever:
```
wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install-ubuntu.sh
bash hst-install-ubuntu.sh
```

**Comment by DemOnJR** [comment]
> 
> 
> The Ubuntu Server 20.04 LTS support has been added in to the master branch, please check it out and test as much as you can :-).
> 
> Fast way to install it on a fresh and clean Ubuntu 20.04 Sever:
> 
> ```
> wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install-ubuntu.sh
> bash hst-install-ubuntu.sh
> ```


Installation Aborted
====================================================================
Install script does not match Hestia release version
Please use the installer from the release branch

To test the beta version you need to build the hestia deb packages and re-run the installer
  ./hst_autocompile.sh --hestia no
  ./hst-install.sh .. --with-debs /tmp/hestiacp-src/debs
Error: Installation aborted

**Comment by xtrime-ru** [comment]
> The Ubuntu Server 20.04 LTS support has been added in to the master branch, please check it out and test as much as you can :-).
> 
> Fast way to install it on a fresh and clean Ubuntu 20.04 Sever:
> 
> ```
> wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install-ubuntu.sh
> bash hst-install-ubuntu.sh
> ```

Thanks for tip!

To install on clean 20.04 i  also have to change url here from release to master: https://github.com/hestiacp/hestiacp/blob/master/install/hst-install-ubuntu.sh#L828

I got few minor issues.

1. hostname, email and password options don`t work in installer. I have to print them in cli wizard again.
1. I received emails from `Cron <admin@static> sudo /usr/local/hestia/bin/v-update-sys-queue daily` with following content: `Usage: v-update-sys-queue QUEUE`. 
After i run `v-update-sys-hestia-git master` issue was fixed.
1. I got only one latest backup. And there is no settings to increase amount of backups.

All other thing seems to work.

**Comment by Lupul** [comment]
@xtrime-ru when you test the master branch you also have to build Hestia packages as instructed in that Notice otherwise you end up installing the wrong debs

```
bash hst_autocompile.sh --hestia no
bash hst-install-ubuntu.sh --with-debs /tmp/hestiacp-src/debs ...
```

Changing that url just disabled a failsafe that would prevent that :)

**Comment by xtrime-ru** [comment]
Why so complicated? :) How i can install debs over existsing hestiacp?

**Comment by Lupul** [comment]
why are you installing the development version then?

**Comment by xtrime-ru** [comment]
> why are you installing the development version then?

I have ubuntu 20.04, and release branch won`t install.

**Comment by Lupul** [comment]
ok, i hope it works for you but as you probably know the dev branch is to be installed only for testing and might give some hard time in the future if you chose to run it in production now.

**Comment by xtrime-ru** [comment]
:( 
Can i switch to release branch, when it have 20.04 support, like this `v-update-sys-hestia-git release`? Will it help? 

Do i need to disable auto update?

**Comment by ScIT-Raphael** [comment]
No, as @Lupul wrote this is only for testing and not for productive systems at all - this should be clear if you install a beta/dev version. Also we do not provide any upgrades to future stable/release versions nor support it if you get in troubles - it is and will be ever testing only.

Going to close this issue here, the requested support has been added to the master branch and is working properly.
