### ISSUE TITLE
Bug: Restore user when there is an additional ftp account

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#743]
### In a few words, please describe the issue that you're experiencing:
When restoring a user from one server to another (Hestia to Hestia), I received the below errors. Please note that the user had "Additional FTP Accounts"

"Error: absolute path  is invalid"
Please mind the extra space between "path and "is". That's because of the variable $ftp_path .

In addition, I also had the below errors:

2020-03-21 16:38:27 .profile
2020-03-21 16:38:27 .git-credential-cache
chown: cannot access '/home/xxx/.git-credential-cache': No such file or directory
2020-03-21 16:38:27 .bash_history
chown: cannot access '/home/xxx/.bash_history': No such file or directory
2020-03-21 16:38:28 .console
chown: cannot access '/home/xxx/.console': No such file or directory
2020-03-21 16:38:28 .gitconfig
chown: cannot access '/home/xxx/.gitconfig': No such file or directory
2020-03-21 16:38:28 .gnupg
chown: cannot access '/home/xxx/.gnupg': No such file or directory
2020-03-21 16:38:28 .mysql_history
chown: cannot access '/home/xxx/.mysql_history': No such file or directory
2020-03-21 16:38:28 .bashrc

### What steps did you take when the issue occured? 
Run v-restore-user script from CLI.

### Expected behavior:
The user should have been restored successfuly.

### Does this issue always occur, or is it intermittent?
When there are additional ftp accounts

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`
1.1.0

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
New installation

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

**Comment by ghost** [comment]
Unable to reproduce with backups containing domains with multiple FTP accounts in v1.2.0, closing issue.
