### ISSUE TITLE
Bug: Setting web domains to 0 still shows the WEB area

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#744]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
When a package with 0 web domains is used, when the user logs in he still has the option to "Add a web domain".

### What steps did you take when the issue occured? 
1. Ex.: Log into the Hestia Control Panel using Firefox
2. Ex.: Click on the Web tab
3. Ex.: Click on Add Web Domain
4. Ex.: Attempted to add a domain and received an error.

### Expected behavior:
User should have another "home" screen when web is disabled.

### Does this issue always occur, or is it intermittent?
Always

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`
1.1.0

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your answer here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by johnnyq** [comment]
Nice catch

**Comment by rmj-s** [comment]
@kristankenney @ScIT-Raphael 
I was working on this and just wanted to ask if we can introduce the following function in `login.php` and use that in future commits instead of `if ($user == 'admin'){}` to enable slow migration towards multi admin user functionality?
```
// login.php
// Get user's information
exec (HESTIA_CMD . "v-list-user ".$v_user." json", $output, $return_var);
$data = json_decode(implode('', $output), true);
unset($output);
// Set user information in session
$_SESSION['user_data'] = $data;
// Assign role manually until it's added in v-list-user
$_SESSION['user_data']['role'] = 'admin';
```

```
// Existing
if ($user == 'admin') {}
```
```
// main.php
$admin_role = 'admin'; // allows admin role renaming in future

// Sample Usage (if directly using session)
if ($_SESSION['user_data']['role'] == $admin_role){}
//or (if creating $user_data in main.php)
if ($user_data['role'] == $admin_role){}
```
