### ISSUE TITLE
Bug: Translation Strings Missing 

### ISSUE THREAD

**Issue by elerion64** [hestiacp/hestiacp#746]
Hi

I was just checking the quality of my translation to Croatian, and found several variables missing from the latest en.php file i used as a template:

Enabled multi PHP versions (under config web server)
user accounts (very bottom of users tab)
SQL databases (very bottom of databases tab)
mail domains (very bottom of mail tab)
DNS zones (very bottom of DNS tab)
web domains (very bottom of web tab)
Forgot Password (title of the page, after you click on forgot password)
Database Editor (button under databases tab)
Add Record (button under DNS tab)
Quick install app (button and the entire page behind it)
Hestia Control Panel (suffix to title of the welcome page)
Hestia Control Panel (alt text on logo image on the welcome page)
Hestia Control Panel: (under server tab before version)
Refresh (button under logs tab)
Time (column name under logs table)
Value (column name under logs table)
Time (column name under banned IP adresses manager)
Description (column name under updates)
Service (column name under services)
Description (column name under services)

‘RESTART_CONFIRMATION’ takes untranslated variable %s. (server, etc.)

There might be more. I didn’t follow through all the functions.

Also please make a single variable for “Update Users Default Language”, because it’s impossible to translate with correct case when three variables in capitalized nominative are combined.

Best regards,
Neven

**Comment by ghost** [comment]
Hi @elerion64,

Thanks for your issue report and providing the Croatian translation, we'll have this sorted out soon. :)

**Comment by jaapmarcus** [comment]
Please comments everything has been fixed

> Quick install app (button and the entire page behind it)
Fixed with the exception of all the installers current not defined in template but there generated with the install files

> Hestia Control Panel: (under server tab before version)

> ‘RESTART_CONFIRMATION’ takes untranslated variable %s. (server, etc.)
Service names are currently not translated 

> Also please make a single variable for “Update Users Default Language”, because it’s impossible to translate with correct case when three variables in capitalized nominative are combined.

**Comment by tlcd96** [comment]
Please check if it's missing the same strings for Portuguese, that i might be able to translate to it (i'm Portuguese but if i have spare time i translate the strings)

**Comment by jaapmarcus** [comment]
There are missing strings see https://github.com/hestiacp/hestiacp/blob/master/web/inc/i18n/en.php for the last version

and for the current Portuguese version https://github.com/hestiacp/hestiacp/blob/master/web/inc/i18n/pt.php

**Comment by tlcd96** [comment]
@jaapmarcus i'm already looking into it, some things are going to change like User in Portuguese it's:
"Utilizador" not "Usuário", "Usuário" it's used in Portuguese - Brazil not Portuguese - Native,

other things like "IPset", I'm doing my best to try to provide a valid translation, but with that i had to break the word "IPSet" to "IP Set"

I request to the Hestia maintainers to keep this issue opened as i use it to guide myself in what i have to do, like this (translation for Portuguese)

**Comment by jaapmarcus** [comment]
Ipset is the name of the sevice that has been added it adds the functionality for adding alot of IP Adresses in one time. 

Nice source for a white list http://ipverse.net

**Comment by jaapmarcus** [comment]
We have decided to switch over to Gettext to manage the strings. So al strings should be available with the changes it is also now easier to change any old string and replace / update the current strings. 

If not please create a new issue report. So we can add / improve it.

Please check https://forum.hestiacp.com/t/how-to-contribute-with-translations/1664/ how work with it.
