### ISSUE TITLE
Web domains (and some mail domains) somehow breaking in the server

### ISSUE THREAD

**Issue by victor-vanherpt** [hestiacp/hestiacp#750]
### In a few words, please describe the issue that you're experiencing:
Hestia did 'something' and now my sites are broken (I had no interaction with the server since the error)

It already happened when hestia auto upgraded to 1.1.0, but now again, right after you released in 1.1.1 (but I don't seem to have updated to it). I thought there should be some misconfiguration from my side, but it's repeating and I don't have to _change anything_ for it to be fixed. 

Entering in each domain for each user and saving the stettings (without configuration changes) seems to solve the problem. I'm afraid of having to do this every time there is an update. Some of them were working though (couldn't see any specific trait in them)

The main server domain mail domain is also doing this, and wasn't fixed after rebuilding mail-domains in the admin account (I had to give up /webmail since 1.1.0, for some unknown reason)

### What steps did you take when the issue occured? 
None on my side, just visit a site and it was down with error 500

### Expected behavior:
Everything should be working usually :)

### Operating system distribution and release:
Debian 9.12
### Which version of Hestia Control Panel is currently installed?
1.1.0
### Which branch are you using?
release
### When did this issue occur? After a clean installation, or after an upgrade?
After an upgrade
### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:
The error appearing in the web domain logs is:
`[Thu Mar 26 11:29:34.178872 2020] [proxy:warn] [pid 11897] [client XXX:33846] AH01144: No protocol handler was valid for the URL /index.php. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.`

### Additional notes:

BTW: is there a command to trigger a domain rebuild for all the domains?, in the console it seems I have to provide every user/domain in v-rebuild-web-domains or v-rebuild-web-domain).

**Comment by ScIT-Raphael** [comment]
You wrote, that it happened again without upgrading your system - can you please verify this? Check the installed deb packages to verify the installed hestia version, have a look in hestia.conf or the server tab in backend. You can also check your auto upgrade cronjob time.

The upgrade does a v-rebuild for every use, this may cause the issue - but this would only be logical if your server was upgraded today.

**Comment by victor-vanherpt** [comment]
According to debian, I have 1.1.0, in the admin panel as well and so is it in hestia.conf
`hestia:
  Installed: 1.1.0
  Candidate: 1.1.0
  Version table:
 *** 1.1.0 500
        500 https://apt.hestiacp.com stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.6 500
        500 https://apt.hestiacp.com stretch/main amd64 Packages
     1.0.5 500
        500 https://apt.hestiacp.com stretch/main amd64 Packages
     1.0.4 500
        500 https://apt.hestiacp.com stretch/main amd64 Packages
     1.0.3 500
        500 https://apt.hestiacp.com stretch/main amd64 Packages
     1.0.2 500
        500 https://apt.hestiacp.com stretch/main amd64 Packages
     1.0.1 500
        500 https://apt.hestiacp.com stretch/main amd64 Packages`
don't have a monitoring setup (I am setting up one now), so I don't know exactly when this happened today (it was a client that told me).

Maybe it's a let's encrypt problem that is not allowing the v-rebuild to fully run?
The latest reocurring errors I can see in /var/log/hestia/error.log are (they happen every night, I am going to check the domain configuration for those domains).
`2020-03-25 04:01:16 v-add-letsencrypt-domain  'admin' 'mail.maindomain.com' [Error 15]
2020-03-25 04:01:27 v-add-letsencrypt-domain  'someuserone' 'someuserone.someusersdomain.com' 'www.someuserone.someusersdomain.com' [Error 5]
2020-03-25 04:01:38 v-list-dns-records  'someusertwo' 'someusertwo.someotherdomain.net' [Error 3]
2020-03-25 04:01:38 v-add-letsencrypt-domain  'someusertwo' 'someusertwo.someotherdomain.net' 'www.someusertwo.someotherdomain.net' [Error 3]
2020-03-26 04:01:14 v-add-letsencrypt-domain  'admin' 'mail.maindomain.com' [Error 15]
2020-03-26 04:04:52 v-add-letsencrypt-domain  'someuserone' 'someuserone.someusersdomain.com' 'www.someuserone.someusersdomain.com' [Error 5]
2020-03-26 04:05:02 v-list-dns-records  'someusertwo' '' [Error 3]
2020-03-26 04:05:02 v-add-letsencrypt-domain  'someusertwo' 'someusertwo.someotherdomain.net' 'www.someusertwo.someotherdomain.net' [Error 3]`

**Comment by ScIT-Raphael** [comment]
This could be related to let's encrypt, that's possible: It triggers v-add-web-domain-ssl
https://github.com/hestiacp/hestiacp/blob/cdb1e409e47a7f660ebf696034e52baa713834d6/bin/v-add-letsencrypt-domain#L399
which itself triggers add_web_config
https://github.com/hestiacp/hestiacp/blob/cdb1e409e47a7f660ebf696034e52baa713834d6/bin/v-add-web-domain-ssl#L105
which itself does rebuild the ssl domain configuration
https://github.com/hestiacp/hestiacp/blob/cdb1e409e47a7f660ebf696034e52baa713834d6/func/domain.sh#L188-L289

So basicly yes, the domain will be newly created. Do you use custom templates? Probaly you want also to switch to fpm if you don't already have it (https://docs.hestiacp.com/release_notes/1.1.0.html#new-multiphp-system):

> Multiphp will not be enabled automaticaly since internal mod_php module will be disabled and might cause isues with some apps when switching to php-fpm backend.
> 
> To enable multiphp run the migration script: $HESTIA/install/upgrade/manual/migrate_apache.sh

But be warned: This may break websites, so probaly create a snapshot of your server before run it and verify after that, that all websites are working properly. This will enable you also the modular MultiPHP system.
