### ISSUE TITLE
Error: Let's Encrypt validation status 400

### ISSUE THREAD

**Issue by suricloud** [hestiacp/hestiacp#752]
### Operating system distribution and release:
Ubuntu 18.04 LTS

### Which version of Hestia Control Panel is currently installed?
1.1.1

Hi do get this error for Letsencrypt ssl:
Error: Let's Encrypt validation status 400

All my dns setting is ok on cloudflare,but still.
How to to fix this?

**Comment by ScIT-Raphael** [comment]
Mostly, this is due to a connection issue (maybe firewall), invalid dns or existing ipv6 records. There is nothing much we can do to help you, please verify that all records are correct and the server is reachable from outside - also a valid e-mail address is needed, but mostly this will produce a "account registration failed" error.

Let's Encrypt creation is working properly, just generated a cert for a new domain a few minutes ago.

**Comment by suricloud** [comment]
Hi,

I removed the ipv6.
Tried to install again ssl for the hostname, now i get this:

Error: Let's Encrypt new auth status 429

What to do.

**Comment by tudorr89** [comment]
You should first google your error. 429 means too many requests. Retry your request later as this issue is not hestiacp related, but rather dns issue

**Comment by suricloud** [comment]
Ok will try again later on the day.

**Comment by ScIT-Raphael** [comment]
> You should first google your error. 429 means too many requests. Retry your request later as this issue is not hestiacp related, but rather dns issue

Thanks! <3

**Comment by suricloud** [comment]
HI, I tried but still not working.Now getting status 400 again.How can i sent you my vps logins so you can check what is causing this?

**Comment by ScIT-Raphael** [comment]
Did you verified that you have setup all properly as I written above? Let's Encrypt is working properly, there doesnt exist known issue, also I just created a new cert for a domain today.

Probaly IPv6, missing/wrong dns or a connection issue.

**Comment by suricloud** [comment]
What i see,all is set ok :(
How can i pm /email  you the logins?

**Comment by tudorr89** [comment]
> HI, I tried but still not working.Now getting status 400 again.How can i sent you my vps logins so you can check what is causing this?

You might want to try a website like https://dnschecker.org/ipv6-compatibility-checker.php and make sure you're domain is fully compatible. Otherwise, you might want to double check your DNS settings.

**Comment by suricloud** [comment]
IPv6 Compatibility Info
--
No


AAAA Web Server Records
--
No AAAA Record Found.
No AAAA Record Found.

**Comment by suricloud** [comment]
/etc/hosts records:

i.p.a.dre.ss    hostname.domain.com       hostname
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
#::1    ip6-localhost   ip6-loopback
#fe00::0        ip6-localnet
#ff00::0        ip6-mcastprefix
#ff02::1        ip6-allnodes
#ff02::2        ip6-allrouters
#ff02::3        ip6-allhosts
#127.0.1.1    hostname     hostname

**Comment by ScIT-Raphael** [comment]
Infact that Let's Encrypt is working properly on all testing and productive systems, it has to be something user specific like I already wrote above. In that case we can't provide free support (a analyze of your own system including debug and verification what's the missing part).

I also just verified again, if the let's encrypt validation is working and can't find any issue:
```
root@xxxxx:~# v-add-letsencrypt-domain user letsencrypt.hestiacp.com
root@xxxxx:~#
```
The process went trough and the cert was generated properly:
root@web02:~# v-list-web-domain-ssl user letsencrypt.hestiacp.com
```
-----BEGIN CERTIFICATE-----
xxx
-----END CERTIFICATE-----

-----BEGIN RSA PRIVATE KEY-----
xxx
-----END RSA PRIVATE KEY-----

-----BEGIN CERTIFICATE-----
xxx
-----END CERTIFICATE-----


SUBJECT:        letsencrypt.hestiacp.com
ALIASES:        letsencrypt.hestiacp.com
VALID FROM:     Mar 30 13:30:43 2020 GMT
VALID TIL:      Jun 28 13:30:43 2020 GMT
SIGNATURE:      sha256WithRSAEncryption
PUB_KEY:        4096 bit
ISSUER:         C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
SSL_FORCE:      no
```
Of course you can test the domain, it will show you a propper and valid let's encrypt certificate. I'm sorry, but this is all we can currently do for you.

**Comment by ScIT-Raphael** [comment]
What I can tell you for further testing is that you can add LE_STAGING='yes' to you hestia.conf file, this will enable the staging environment of let's encrypt. This means you don't get valid certificates but can do a deep test of the validation routine without hitting the certification generation limit - and the resulting massive time loss. Of course: Do not forget to remove it after testing, otherwise you would generate invalid certificates :)

**Comment by suricloud** [comment]
ok :(

**Comment by tudorr89** [comment]
> ## IPv6 Compatibility Info
> No
> 
> ## AAAA Web Server Records
> No AAAA Record Found.
> No AAAA Record Found.

Right, so the DNS settings are incorrect. You have no valid IPV6 IPs pointing to your domain, hence it is not working. You should set them first and then test what @ScIT-Raphael advised regarding to setting 

> LE_STAGING='yes'

**Comment by ScIT-Raphael** [comment]
@tudorr89 Hestia doesnt support IPv6 yet, it is important that you have no active aaaa dns records, otherwise validation will also fail.

**Comment by tudorr89** [comment]
> @tudorr89 Hestia doesnt support IPv6 yet, it is important that you have no active aaaa dns records, otherwise validation will also fail.

My bad, I don't know why I thought this was IPv6 related. @suricloud please disregard my comments regarding IPv6.  Can you please post a screenshot from https://check-your-website.server-daten.de/ ?

**Comment by suricloud** [comment]
> > @tudorr89 Hestia doesnt support IPv6 yet, it is important that you have no active aaaa dns records, otherwise validation will also fail.
> 
> My bad, I don't know why I thought this was IPv6 related. @suricloud please disregard my comments regarding IPv6. Can you please post a screenshot from https://check-your-website.server-daten.de/ ?

Hi, check here:

https://check-your-website.server-daten.de/?q=vpc.suricloud.com

**Comment by ScIT-Raphael** [comment]
I see a lot of connection timeouts there, also I can't reach the host you've wrote there - so a validation timeout is more than logical in that case...

**Comment by tudorr89** [comment]
Just by accessing http://vpc.suricloud.com/, I get a connection timeout. The domain is not available publicly. Quick question, do you have an internal and external IP assigned?. For example, if you go to your user->web->edit your domain, how many entries do you have under IP Address? Make sure that the public IP is selected.

**Comment by suricloud** [comment]
Yes the vps has an internal ip.But on hestiacp i only see the public ip and that is selected .

**Comment by suricloud** [comment]
On server -network tab i see this : 10.0.0.8 → 150.136.19.90

**Comment by tudorr89** [comment]
> On server -network tab i see this : 10.0.0.8 → 150.136.19.90

OK, and when you go to http://vpc.suricloud.com, can you access it? I personally can't. I even tried to do a curl request from another remote server and I still could not access it. Maybe also check your firewall and troubleshoot why it is not publicly accessible.

**Comment by suricloud** [comment]
No cant reacht that too here. only with vpc.suricloud.com:8083
I will check again on the firewall settings of the vps provider.

**Comment by tudorr89** [comment]
Right, so your web ports are closed(80,443,8080). Make sure they're open and then retry generating a certificate.
