### ISSUE TITLE
How to add another admin user?

### ISSUE THREAD

**Issue by sHAsHiLx** [hestiacp/hestiacp#753]
When panel is installed - it creates admin user with login "admin" and I can login with root or admin login. But how about add another admin user? There is no option to set some user as admin - it will only creates regular users without permission to options having admin/root user. I've found solution in Vesta forums and adopted it to HestiaCP but when update releases and installed - it will erase all my changes.

**Comment by ScIT-Raphael** [comment]
Currently, there is now way to add a second admin user. There are plans for reseller and multiple admin users, also a user with free choseable name - but this will need a deep restructuration of the whole codebase.

**Comment by ScIT-Raphael** [comment]
Could you please share the post you've found on vesta forum?

**Comment by sHAsHiLx** [comment]
This one https://forum.vestacp.com/viewtopic.php?t=10752

**Comment by xeruf** [comment]
This seems to be fixed now?
And a duplicate of https://github.com/hestiacp/hestiacp/issues/636

**Comment by jaapmarcus** [comment]
This feature has been added and yes.
