### ISSUE TITLE
phpMyadmin blowfish_secret and TempDir Error 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#754]
### In a few words, please describe the issue that you're experiencing:

phpMyadmin blowfish_secret and TempDir Error 

![image](https://user-images.githubusercontent.com/39749258/77843523-a50ae880-71bb-11ea-8797-5b6715509e21.png)

### What steps did you take when the issue occured? 
After upgrading Hestia Control Panel to v1.1.1

### Expected behavior:
it's already showing it's been fixed in v1.1.1 but i don't think it been patch via upgrade script, it's showing on all 3 servers.

### Does this issue always occur, or is it intermittent?
in all 3 servers after automatic update showing this.

### Operating system distribution and release:
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)

### Which version of Hestia Control Panel is currently installed?
v1.1.1

![image](https://user-images.githubusercontent.com/39749258/77843588-485bfd80-71bc-11ea-9510-bb6eec62a9c3.png)

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
upgrading to the latest release

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.
1.1.0

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

**Comment by alber-khan** [comment]
/usr/share/phpmyadmin/libraries/vendor_config.php

![image](https://user-images.githubusercontent.com/39749258/77843816-45faa300-71be-11ea-94a1-c43daa12901f.png)


regarding TMP Folder i've checked this directory and looks like the user group is different? 
/var/lib/phpmyadmin/tmp

![image](https://user-images.githubusercontent.com/39749258/77843825-632f7180-71be-11ea-9243-4d80ff2e20b5.png)

**Comment by ScIT-Raphael** [comment]
Thanks for the report, we are already aware of the problem, which will be caused due to a open basedir issue. We're working on a solution already.

**Comment by ScIT-Raphael** [comment]
To provide some additional informations:
`[Thu Apr 23 19:56:25.742055 2020] [proxy_fcgi:error] [pid 28241] [client xx.xx.xx.xx:58374] AH01071: Got error 'PHP message: phpmyadmin: Failed to load /var/lib/phpmyadmin/blowfish_secret.inc.php Check group www-data has read access and open_basedir restrictions.PHP message: phpmyadmin: Failed to load /var/lib/phpmyadmin/config.inc.php Check group www-data has read access and open_basedir restrictions.PHP message: phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.'`

`
root@xxxxx:~# ls -l /var/lib/phpmyadmin/blowfish_secret.inc.php
-rw-r----- 1 root www-data 68 Mar 17  2019 /var/lib/phpmyadmin/blowfish_secret.inc.php
`

**Comment by ioannidesalex** [comment]
The only thing I have to do on version 1.1.1 is run the below:

sed -i "s|define('CONFIG_DIR', ROOT_PATH);|define('CONFIG_DIR', '/etc/phpmyadmin/');|" /usr/share/phpmyadmin/libraries/vendor_config.php

sed -i "s|define('TEMP_DIR', ROOT_PATH . 'tmp/');|define('TEMP_DIR', '/var/lib/phpmyadmin/tmp/');|" /usr/share/phpmyadmin/libraries/vendor_config.php

**Comment by ghost** [comment]
This issue is fixed in the commit above and will be made available with v1.2.0; should you run into further troubles please comment here and we will re-open this issue

**Comment by luisfigueroa34** [comment]
Hello I reopen this thread because I present this problem.

`$cfg['TempDir'] (/var/lib/phpmyadmin/tmp/) es inaccesible`

panel version v1.3.1

Server mounted on Ubuntu 18.04

How could I solve it?

**Comment by vadym-masiuk** [comment]
By the way, just noticed, same problem exist in 1.3.2, and even 1.3.3.
I can add that I'm running it on Ubuntu 20.04 Server headless with 10.5.8-MariaDB (type: mysql)
Permissions seem to be ok
/var/lib/phpmyadmin/blowfish_secret.inc.php (Owner - root; Group: www-data; access: -rw-r--r--, which is equal to 0644)

Trick I found [here](https://forum.hestiacp.com/t/cfg-tempdir-var-lib-phpmyadmin-tmp/2265) did the job
