### ISSUE TITLE
Statics Usage April is visible

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#755]
### Please fill in the relevant sections below and remove those which do not apply.

Logged in today 31st of March 2020 and when viewing the statics and saw this
http://mol-clan.nl/dump/april.png

It would be also nice that the reporting of data traffic would reset 

Date on the server 
Tue Mar 31 00:23:50 CEST 2020

===

### In a few words, please describe the issue that you're experiencing:
Logged in today 31st of March 2020 and when viewing the statics and saw this
http://mol-clan.nl/dump/april.png

### What steps did you take when the issue occured? 
Login on Hestia Panel
Go to Statics page

### Expected behavior:
See only March

### Does this issue always occur, or is it intermittent?
Yes,

### Operating system distribution and release:
18.04.3 LTS (Ubuntu)

### Which version of Hestia Control Panel is currently installed?
1.1.1 Updated from 1.1.0  Clean install 3 weeks ago on 1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Don't know. First time user

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

Date on the server 
root@cp:/home/eris# date
Tue Mar 31 00:23:20 CEST 2020
root@cp:/home/eris# date
Tue Mar 31 00:23:50 CEST 2020

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ScIT-Raphael** [comment]
Hi, just checking our issues, unlucky but the image isnt online anymore. Could you probaly upload it to github? I'm gonna reopen the issue then.

**Comment by jaapmarcus** [comment]
https://imgur.com/NhQNrDD

it  isn't a big issue ofcourse...

**Comment by ioannidesalex** [comment]
VestaCP inherited bug.

**Comment by gOOvER** [comment]
Here the same @ScIT-Raphael should start reading and investigating, insteed of closing ;)

**Comment by ioannidesalex** [comment]
Come on, let's stop this witch-hunt and be more productive and constructive :)
