### ISSUE TITLE
Bug: Password change via Roundcube breaks login

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#756]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
When email account password changed via Roundcube, user can no longer login.

### What steps did you take when the issue occured? 
Change password via Roundcube

### Expected behavior:
You should be able to login.

### Does this issue always occur, or is it intermittent?
Always

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by Skamasle** [comment]
This isnt a roundcube bug 

I debug this for vestacp but make some pull here https://github.com/hestiacp/hestiacp/pull/761

In vesta this not cause efects because was defined $quota, quota was reseting but login sill work, here some body add ${quota}M and this break passwd
