### ISSUE TITLE
Bug: Backup log file not removed when running v-backup-user script

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#759]
### In a few words, please describe the issue that you're experiencing:
Backup log file .log in /backup directory is not removed when running v-backup-user script. It is properly removed when run through v-backup-users script

### What steps did you take when the issue occured? 
Run v-backup-user from CLI.

### Expected behavior:
Log file should have been removed after backup creation.

### Does this issue always occur, or is it intermittent?
Always

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
After upgrade from 1.1.0. Don't know if it occured in 1.1.0 as well but definitely not at 1.0.6.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

**Comment by ScIT-Raphael** [comment]
Log file should not be removed, it gives you feedback if the backup went properly or not. I would suggest to leave it like it is.

**Comment by ioannidesalex** [comment]
In my opinion it should be removed, since you have the output on your screen and written in /var/log/hestia/backup.log 

When you use the bulk backup script v-backup-users then the log file is not created in /backup
