### ISSUE TITLE
Feature request: Upgrade RoundCube

### ISSUE THREAD

**Issue by changeme** [hestiacp/hestiacp#760]
Hello.
It' would be nice if Roundcube could be upgraded to lastest stable (https://github.com/roundcube/roundcubemail/releases/tag/1.4.3).

'Elastic' theme is compatible with mobile, and lot of bugfixes since last version (and new bugs too )

**Comment by ghost** [comment]
Hi @changeme,

Thanks for your feature request. We're already working on this and will be upgrading Roundcube along with some additional customizations in an upcoming release.

**Comment by changeme** [comment]
Thank you! You rocks!

**Comment by liamgibbins** [comment]
Would also be awesome to have roundcube filters as standard..
just saying.. :)

**Comment by ioannidesalex** [comment]
Hi @liamgibbins excellent feature indeed. However as @kristankenney mentioned there is work in progress aiming to enhance the whole mail experience. Stay tuned :)

**Comment by plutocrat** [comment]
You might be better off not using deb packages and making a script installer that installs the standard roundcube way. That would be a bit of a hassle to migrate old installs across, but would definintely be better for new installs. And it would be standard across all OS versions. I've always felt that the .deb packages did their config in a weird way.

**Comment by jaapmarcus** [comment]
Same as we have done for the phpmyadmin.

If we change we should also update phppgadmin the same

**Comment by layanto** [comment]
Just migrated from vestaCP to hestiaCP. Noticed that roundcube is already at 1.4.3. Not sure how to update to latest 1.4.8 though.

**Comment by layanto** [comment]
And how do I change the roundcube skin to elastic? Noticed that /etc/roundcube/defaults.inc.php has elastic skin configured but when I use webmail, it is using Larry skin. If I manually change the skin in roundcube setting it is only applicable to that email account. How do I change it for all email accounts?

Found it: /var/lib/roundcube/config/config.inc.php

**Comment by ghost** [comment]
Closing issue report, now tracking under feature: #1281
