### ISSUE TITLE
Probable bug / Improve : Clamav never updated or started

### ISSUE THREAD

**Issue by changeme** [hestiacp/hestiacp#762]
===
### In a few words, please describe the issue that you're experiencing:
>Clamav installed, but not start.
>Seems to be related to my new hosting provider and low bandwith transfer (2.4Mbps).
> I'm doing a big migration from old servers and customers to new server while I tried to update clamav

### What steps did you take when the issue occured? 
1. : Log into the Hestia Control Panel
2. : Click on the Server tab
3. : Click on restart 'clamav-daemon'
4. : Service seems restarted, but still gray

### Expected behavior:
> Service clamav-daemon should start and stay activated

### Does this issue always occur, or is it intermittent?
> Always, since install (5 days ago) on a fresh install

### Operating system distribution and release:

> cat /etc/lsb-release 
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

### Which version of Hestia Control Panel is currently installed?
>VERSION='1.1.1'

### Which branch are you using?
> stable

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:

***/var/log/clamav/freshclam.log***

> Wed Apr  1 13:25:33 2020 -> ClamAV update process started at Wed Apr  1 13:25:33 2020
> Wed Apr  1 13:25:33 2020 -> daily database available for download (remote version: 25769)
> Wed Apr  1 13:26:03 2020 -> WARNING: Download failed (28) Wed Apr  1 13:26:03 2020 -> WARNING:  Message: Timeout was reached
> Wed Apr  1 13:26:03 2020 -> WARNING: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
> Wed Apr  1 13:26:03 2020 -> Trying again in 5 secs...

### Related issues or forum threads:
> Unknow

### Additional notes:

Seems to be fixed when I set 'ReceiveTimeout 1800' on /etc/clamav/freshclam.conf, restart service , and wait until clamav update.
It took near 20 minutes on my server 
I know, maybe not related to Hestia, but could help to new users set a longer ReceiveTimeout

**Comment by ScIT-Raphael** [comment]
Can't confirm this issue, seems to be a connection issue, our systems are updating themself properly:

```
Mon Apr  6 17:41:07 2020 -> --------------------------------------
Mon Apr  6 18:41:07 2020 -> Received signal: wake up
Mon Apr  6 18:41:07 2020 -> ClamAV update process started at Mon Apr  6 18:41:07 2020
Mon Apr  6 18:41:07 2020 -> daily.cld database is up to date (version: 25774, sigs: 2248800, f-level: 63, builder: raynman)
Mon Apr  6 18:41:07 2020 -> main.cld database is up to date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Mon Apr  6 18:41:07 2020 -> bytecode.cld database is up to date (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
Mon Apr  6 18:41:07 2020 -> --------------------------------------
Mon Apr  6 19:41:07 2020 -> Received signal: wake up
Mon Apr  6 19:41:07 2020 -> ClamAV update process started at Mon Apr  6 19:41:07 2020
Mon Apr  6 19:41:07 2020 -> daily.cld database is up to date (version: 25774, sigs: 2248800, f-level: 63, builder: raynman)
Mon Apr  6 19:41:07 2020 -> main.cld database is up to date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Mon Apr  6 19:41:07 2020 -> bytecode.cld database is up to date (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
Mon Apr  6 19:41:07 2020 -> --------------------------------------

```
