### ISSUE TITLE
Disabling php 7.4 in multi PHP returns 500 error.

### ISSUE THREAD

**Issue by Mel0ne** [hestiacp/hestiacp#763]
### In a few words, please describe the issue that you're experiencing:
Disabling php 7.4 in "Enabled multi PHP versions"  returns 500 error, and Hestia dying until you restart the server :(

### What steps did you take when the issue occured? 
1. Ex.: Log into the Hestia Control Panel
2. Ex.: Click on the Server
3. Ex.: Click on Configure
4. Ex.: "Enabled multi PHP versions" section
5. Ex.: Uncheck php-7.4
6. Ex.: Click on Save button

### Expected behavior:
Php 7.4 can be disabled, and Hestia should work after that.

### Does this issue always occur, or is it intermittent?
Always

### Operating system distribution and release:
Debian 9.12

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM
- PHP-FPM + Multi-PHP

### In order to better assist, please post any relevant log information below:
Could not find any sane logs

**Comment by ScIT-Raphael** [comment]
We were not able to reproduce this issue, probaly your server went into a timeout. Hestia itselfs use a own stack of php and nginx, so it does not have any direct connection to the php7.4 installation.
