### ISSUE TITLE
Select or change mysql version

### ISSUE THREAD

**Issue by x86fantini** [hestiacp/hestiacp#764]
Hello
thank you for continuos development of HestiaCP.

i apreciate the MultiPHP but in my opinion also the mysql version should be chose during install.

out of the box, on ubuntu 18lts, i see mariadb 10.4. it's too updated for magento2, prestashop1.7 and some wp from last year. 

my desired option would be during install to choose from 10.2, 10.3 or 10.4

thank you

p.s. can i change/downgrade version now?

**Comment by ioannidesalex** [comment]
You can just amend line 576 of Ubuntu installer (hst-install-ubuntu.sh) and put the version you want to install instead.

**Comment by x86fantini** [comment]
wow, thank you for the so quick reply.
much apreciated.

would it be possibile to add this as a feature? :+1:

**Comment by ioannidesalex** [comment]
I have made a PR for adding a variable towards the top of the script. So far Hestia doesn't have a version selection as a parameter, only through few easy amendments in the installer script (variables on top).

**Comment by x86fantini** [comment]
excuse me, where do i find the "hst-install-ubuntu.sh" ?

here https://www.hestiacp.com/ i just see "hst-install.sh"

**Comment by ioannidesalex** [comment]
https://github.com/hestiacp/hestiacp/blob/release/install/hst-install-ubuntu.sh

**Comment by x86fantini** [comment]
thank you very much! excelent

**Comment by x86fantini** [comment]
btw, i confirm it works perfectly

root@hestiaTest:~# mysql -V
mysql  Ver 15.1 Distrib 10.2.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
