### ISSUE TITLE
Feature Request: specific php version in .bashrc per account

### ISSUE THREAD

**Issue by x86fantini** [hestiacp/hestiacp#766]
Hi Hestia team, i see that you use ondrej multi php . It's great, but i have faced an issue on all my server. You can select any fpm version and use it with you favourite webserver (apache/php) but the CLI version is always the highest installed.

let's say i really wanna take advanteges of multiphp: 
-i create a new website mydomain.tld
-i select php 7.1 for mydomain.tld
-i install magento 2.1 (last year release)
> magento via browser it wil work (nginx reverse -> apache -> fpm 7.1
> but if i run "php bin/magento xxx" i will use the php 7.3 CLI

yes, i can manually use full path, but my suggestion is:

-i create a new website mydomain.tld
-i select php 7.1 for mydomain.tld
(this extra step) -as soon as i create ssh user USER1, hestia create a  ".bash_aliases"  with `alias php='/usr/bin/php7.1'`
-i install magento 2.1 (last year release)
> magento via browser it wil work (nginx reverse -> apache -> fpm 7.1
> magento via CLI will use "php" as "/usr/bin/php7.1"

i know that if the same ssh/system user own more then 1 domain this can be challenging , but it's a first draft of my idea...maybe we can do something more complex via some bash magic...

**Comment by ioannidesalex** [comment]
Thanks for your suggestion. This is challenging though. What happens if you have two domains using two different PHP versions under the same user? Or in case you have custom backend templates?

**Comment by x86fantini** [comment]
so, this works best (and ouf the box) when you have a ratio of 1 ssh user -> 1 website.

another trick that you can use, it could be aliases aliases.

eg you create alias 

`alias php56='/usr/bin/php5.6'`

`alias php70='/usr/bin/php7.0'`

`alias php71='/usr/bin/php7.1'`

and so no.

what i'm trying to suggest here is also to have a nice and smooth way to work via CLI with multi php, becouse 99,99% of the time, if a CMS need a custom php version for fpm, it also need the same versione via CLI and it's pretty easy to miss the right php command for a developer.

thank you for listening :+1:

**Comment by ioannidesalex** [comment]
Hello again,

The team will discuss this internally and get back to you.

Thank you.

**Comment by x86fantini** [comment]
we thank you, it's great to have such an active team.

**Comment by ScIT-Raphael** [comment]
Hi @x86fantini 

I'll going to work on a implementation to set a specific cli version for each ssh enabled user. Currently I do not have any planed release date, it will be programmed as soon as we find enough time to fullfill your feature request :).

**Comment by x86fantini** [comment]
hi and thank you for this implementation.
if i can help to develop this feature, just let me know.

thx
S

**Comment by ScIT-Raphael** [comment]
If you would like to help with the implementation, you could start the work and send us then a pull request with the changed code - that would be awesome!

**Comment by x86fantini** [comment]
shure. can you just point me into the right direction on where i find the .sh scripts used to create ssh users? i'll start from there.
thx

**Comment by ScIT-Raphael** [comment]
Hestia runs over the cli stack which you will find in the $HESTIA/bin folder. So I think this could be done adding 3 or 4 new scripts like v-[add/change/delete/list]-user-phpcli, you could have a look, how the other scripts are built up.

If we have the v-scripts, then we would need to expand this feature to hestia backend, probaly under user.

**Comment by Lupul** [comment]
Hello @x86fantini, on Hestia with multiphp you already have access to php versions like in your example, so extra aliases are not that usefull:

```bash
:~# which php5.6
/usr/bin/php5.6

:~# which php7.0
/usr/bin/php7.0

:~# which php7.1
/usr/bin/php7.1

:~# which php7.3
/usr/bin/php7.3

:~# which php7.4
/usr/bin/php7.4
```
And you can run magento cli with:
`php7.1 bin/magento xxx`

Or setting a custom alias for php
`alias php='env php7.1'`

**Comment by x86fantini** [comment]
Hi, you are thinking with a "sysadmin" / "tech-guy" head. if you plan to use Hestia as intended to be (reseller, multiple clients, ssh acces, etc..) any developer or client will have hardtime to deal evereytime with /phpXX. also, some CMS just don't like to use different php's rether then good old "php" command.

if a client owns site1.com with php71 and site2.com with php72 he needs to remember each time he logs into ssh to change binary.

yes, technically it can be done: but why not an alias out of the box? :)

**Comment by Lupul** [comment]
How am I thinking with a tech-guy head?, you have proposed the `phpXX` alias solution [here](https://github.com/hestiacp/hestiacp/issues/766#issuecomment-611343616), I just pointed out that it would be redundant since you already have access to those shortcuts by default

**Comment by x86fantini** [comment]
my idea was to use a simple "php" command (eg: php myfile.php) instead of manual creating alias in .bash_aliases so this should be done when creating a user from hestia gui.
thx

**Comment by jaapmarcus** [comment]
Creating aliases is the only way... By the user or by Hestia..

Made a bash script that does it. Only issue is currently the user interface...  Probably fix it by list /etc/php/ folder and make it able to process it in PHP
