### ISSUE TITLE
Bug: Roundcube password change locking users out

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#769]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:

The Roundcube change password feature is causing accounts to be locked out. This was identified in the forum by user pluto but I noticed there was no issue reported on github.

### What steps did you take when the issue occurred? 
1. Access Roundcube Webmail
2. change password
3. reLog back in with your new password as well as your old one

### Expected behavior:
Should update the password

### Does this issue always occur, or is it intermittent?
always

### Operating system distribution and release:
Ubuntu 18.04.3

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
happens on clean install and upgrade

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

[https://forum.hestiacp.com/t/roundcube-password-change-not-working/617](https://forum.hestiacp.com/t/roundcube-password-change-not-working/617)

### Additional notes:
Thank Pluto from the forums, also does anyone know of a quick fix for this in the meantime, thanks

**Comment by ScIT-Raphael** [comment]
It is already fixed on master: https://github.com/hestiacp/hestiacp/commit/bc086804ed64db597164a621123321107a9f41d4

**Comment by ghost** [comment]
@johnnyq,

Run the following command to patch the issue on your server until we're able to release the next build containing the fix:

`wget -O $HESTIA/bin/v-change-mail-account-password https://raw.githubusercontent.com/hestiacp/hestiacp/master/bin/v-change-mail-account-password && chmod +x $HESTIA/bin/v-change-mail-account-password`

**Comment by johnnyq** [comment]
Super!!! Thanks @ScIT-Raphael and @kristankenney It worked like a charm!!
