### ISSUE TITLE
Mail account options won't be applied on the panel

### ISSUE THREAD

**Issue by peterlobster** [hestiacp/hestiacp#770]
I cannot apply
- Use domain name
- Use STARTTLS
- Use SSL / TLS
- No encryption
options for any usernames for a domain ex. test@domain.com
"→ Changes have been saved." message appears but options won't be applied. IMAP/SMTP information on the panel reverts back and the option to "USE DOMAIN NAME".

SSL certificate is properly issued for mail.domain.com and webmail.domain.com from the panel.

### What steps did you take when the issue occured? 
1. Log into the Hestia Control Panel using Firefox
2. Click on "Mail" tab
3. Click on domain ex. "domain.com"
4. Click on username ex. "test@domain.com"
5. Click on "USE DOMAIN NAME" to change to other options
6. Click on "Save"

### Expected behavior:
Options to be applied.

### Does this issue always occur, or is it intermittent?
This issue always occurs.

### Operating system distribution and release:
Debian 10.3 (x86_64)

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
After a clean installation.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:
Only this appears at `/var/log/hestia/system.log` after clicking "Save" with any options.
`2020-04-17 20:30:33 v-change-mail-account-quota  'admin' 'domain.com' 'test' '0'`

### Related issues or forum threads:
Couldn't find anything.

### Additional notes:
None.

**Comment by ghost** [comment]
Hello @peterlobster ,

The dialog you are referring to is for account set-up/informational purposes only and as such has no saved state and does not have any effect on account settings. You use this information to configure your mail client in different ways, depending on what you desire from the list of options given.
