### ISSUE TITLE
Update Apache to latest version and add support to TLSv1.3

### ISSUE THREAD

**Issue by neto737** [hestiacp/hestiacp#771]
Hi,

As HestiaCP are already using the latest version in almost all services, I think use latest version of Apache would be a great idea.

Also, TLSv1.3 is the latest TLS version, it's more secure and faster than TLSv1.2, so I think we should implement support to it too.

I would create a pull request by myself with these improvements, but I don't have the tecnichal skills to do that, so...

I hope you guys agree with it. Your work is completely amazing.

**Comment by ScIT-Raphael** [comment]
Hi @neto737 

There is already a same request in our forum: https://forum.hestiacp.com/t/password-in-backup/634

We currently review the implementation process of sury repository for apache2.

**Comment by ScIT-Raphael** [comment]
Hi

There is a test branch now which needs some feedback if all works properly: https://github.com/hestiacp/hestiacp/tree/core-sury-apache2

https://github.com/hestiacp/hestiacp/blob/master/README.md#installing--testing-development-builds

**Comment by ScIT-Raphael** [comment]
Still waiting for someone, who could test the branch :).

**Comment by jaapmarcus** [comment]
During install / update to core-sury-apache2 branch I had a error

``(*) Disable Apache2 Server Status Module...
/usr/local/hestia/install/upgrade/versions/latest.sh: line 24: syntax error near unexpected token 'then'
/usr/local/hestia/install/upgrade/versions/latest.sh: line 24:         elseif [ "$type" = "debian" ]; then'``

Apache2 - FPM-PHP Nginx setup on Ubuntu 18.04

**Comment by ioannidesalex** [comment]
It seems there has been a small bug in the branch, can you please try again with the updated code?

**Comment by jaapmarcus** [comment]
Install went fine without any errors.

**Comment by ioannidesalex** [comment]
Good to know, thanks.

**Comment by neto737** [comment]
@ScIT-Raphael sorry for not testing it before, I got some free time now. Anyway, I've installed HestiaCP in an Ubuntu Server 18.04 (it comes with Apache2 2.4.29, after updating to core-sury-apache2 branch it's now using Apache2 2.4.43, so it seems to be working fine.

**Comment by jaapmarcus** [comment]
Yesterday downloaded to day and it is working fine

Also with Nginx disabled
TLS 1.3	enabled
TLS 1.2	enabled
TLS 1.1 (deprecated)	disabled
TLS 1.0 (deprecated)	disabled

**Comment by ScIT-Raphael** [comment]
@ioannidesalex Thanks for the fast fix, coding first php then bash isnt a good idea :).

@neto737 and @jaapmarcus thanks for the testing, I'm gonna merge this branch now to master and close the issue - the feature will be published on the next hestia release.

**Comment by ScIT-Raphael** [comment]
Merged: https://github.com/hestiacp/hestiacp/commit/329865682caab6ce63059d7265baaf639615496a
