### ISSUE TITLE
Dedicated IP not working

### ISSUE THREAD

**Issue by SnAFKe** [hestiacp/hestiacp#772]
===

### In a few words, please describe the issue that you're experiencing:
For some reason when navigate with IP always i see default index.

I have multiples IPs, default IP is on shared, one IP for a user (website) and other unused.

I test with all IPs not matter what always show default message "Success!".

I see in nginx directory files with IPs, all appoint to proxy address.

For my view i not see any wrong but seems is ignoring server_name.

### What steps did you take when the issue occured? 
Navigate with dedicated IP

### Expected behavior:
When browser with IP go to website of associated IP

### Operating system distribution and release:
Debian 10

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

**Comment by ScIT-Raphael** [comment]
> When browser with IP go to website of associated IP

So if you visit the ip, you want that the website of that customer will be displayed?

**Comment by SnAFKe** [comment]
Yes, i'm not sure what different is between in vestacp and hestiacp in nginx management, in vestacp i have same configuration and not have this issue and is exactly same.

**Comment by ScIT-Raphael** [comment]
Currently, it's not planed to show any website on direct ip access - you always need to use a domain name. Also (personaly) I do not see any reason to show a website on a public ip.

**Comment by ioannidesalex** [comment]
In fact we removed the “feature” of showing a website on public IP since webservers are “agnostic” as to what domain to serve and they serve the first one they find in the relevant configuration file.
