### ISSUE TITLE
Google's 2FA generates a broken image for the QR code under certain conditions

### ISSUE THREAD

**Issue by realjumy** [hestiacp/hestiacp#776]
### In a few words, please describe the issue that you're experiencing:
When activating Google's 2FA authentication, if the password is not entered in the text-box above, it shows a broken image instead of the QR code to be scanned.

### What steps did you take when the issue occurred? 
1. Go to _User_ > _Edit user_
2. Tick the checkbox by _Enable two-factor authentication_
3. Press _Save_ without introducing any password
4. It will show as the settings have been applied but the QR code image is broken

### Expected behaviour:
The QR code should appear correctly or alternately the 2FA authentication should not be allowed if the password is empty.

The system understand that if no new password is provided it means that the password is unchanged. Therefore, it should be also understandable to think that no password should be provided to activate the 2FA, as it should be generated from the stored password.

### Does this issue always occur, or is it intermittent?
It always happens.

### Operating system distribution and release:
Ubuntu 18.04

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
Release

### When did this issue occur? After a clean installation, or after an upgrade?
After a clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

**Comment by ScIT-Raphael** [comment]
I can't reproduce this issue; qr code generarion works properly here. Infact we use google as external service to generate the image (and it also happened once), it's possible that they had a issue on their servers which prevented to generate the qr code image properly. Can you check again, if it works now?

**Comment by realjumy** [comment]
Still happening here if the password textbox is left empty. It’s probably something with my installation then.

**Comment by MichaelSch** [comment]
I am experiencing the same issue. I installed HestiaCP for the first time (current release, clean Debian 10) and if the password field is not set when enabling 2FA the image is not shown. If I enter a password I also get an image.

However it only happend the first time. Now when I disable 2FA and enable it again the QR code is shown.

**Comment by jaapmarcus** [comment]
Hmm strange 

<img width="499" alt="Screenshot 2021-02-03 at 10 02 30" src="https://user-images.githubusercontent.com/9754650/106723248-32527100-6607-11eb-9212-94eb65a65249.png">
<img width="615" alt="Screenshot 2021-02-03 at 10 01 45" src="https://user-images.githubusercontent.com/9754650/106723252-33839e00-6607-11eb-9510-602b5ea387a8.png">

**Comment by jaapmarcus** [comment]
It seems it might be an external api with some issues:

https://github.com/RobThree/TwoFactorAuth/blob/c3110d9760a05d4dbe364d51823ab3d69dc65c5b/lib/Providers/Qr/QRServerProvider.php#L59-L71

**Comment by jaapmarcus** [comment]
I have tested it again and so far no real issues maybe. Only way to solve the issue for use it to write our own function and host it our self.
