### ISSUE TITLE
Bug: Mail account quota is ignored

### ISSUE THREAD

**Issue by john-ch** [hestiacp/hestiacp#777]
### In a few words, please describe the issue that you're experiencing:
Over quota email accounts are still accepting emails.

### What steps did you take when the issue occurred? 
Set quota in the email accounts. 
(Roundcube displays correctly that the account quota limit)

### Expected behavior:
The email shouldn't be accepted

### Does this issue always occur, or is it intermittent?
Always

### Operating system distribution and release:
Ubuntu 18.04.4 LTS

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
I noticed this issue on the latest upgrade but I haven't tested it in the previous clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx + PHP-FPM

**Comment by ScIT-Raphael** [comment]
Thanks for the issue report, this behavipur is correct - hestia doesnt set any hard quota limits or stop any service when the user is over his limit. I'll let this issue open to discuss with the team, if we should change the way it works.

**Comment by FalzoMAD** [comment]
The quota setting on mailboxes is an inherited feature from Vesta and I _think_ it works as a hard limit, if you enable system quotas during installion properly. Only then the disk-space can be limited properly.

Exim also has a quota setting which should work as a virtual limitation - however, I haven't used quotas for quite some time, so we need to check and test the current status...

I think a hard limit should be available in some way.

**Comment by FalzoMAD** [comment]
I digged a bit into it, and confirm it's a bug because of changes that have been comitted a while back and modify the way quotas are now written into the exim config.
exim should indeed honor the quota settings, regardless of system quotas being used or not, so we need to fix this...

**Comment by ScIT-Raphael** [comment]
Just to documentate it, following lines needs a rewrite to get the quota working properly:
https://github.com/hestiacp/hestiacp/blob/master/install/deb/exim/exim4.conf.template#L360
https://github.com/hestiacp/hestiacp/blob/master/install/deb/exim/exim4.conf.template#L377
