### ISSUE TITLE
IDN and Letsencrypt, nslookup fails

### ISSUE THREAD

**Issue by zanami** [hestiacp/hestiacp#779]
### In a few words, please describe the issue that you're experiencing:

I'm trying to enable ssl with LE for an IDN (cyrillic) domain. I got "DNS record for ... doesn't exist" from [here](https://github.com/hestiacp/hestiacp/blob/master/bin/v-add-letsencrypt-domain#L138).

I have modified v-add-letsencrypt-domain like this (copy/pasted from [here](https://github.com/hestiacp/hestiacp/blob/master/bin/v-add-letsencrypt-domain#L178))

```
# Check if dns records exist for requested domain/aliases
if [ "$proto" = "http-01" ]; then
    for identifier in $(echo $domain,$aliases |tr ',' '\n' |sort -u); do
        if [[ "$identifier" = *[![:ascii:]]* ]]; then
            identifier=$(idn -t --quiet -a $identifier)
        fi
        if ! nslookup "${identifier}" > /dev/null 2>&1 ; then
            check_result $E_NOTEXIST "DNS record for $identifier doesn't exist"
        fi
    done
fi
```
I guess it solves the nslookup problem. Can't tell if it fixes the entire LE process as I'm getting Error: Let's Encrypt new auth status 429 now.

I also tried to add this exact domain in punycode (weird thing it can be added at all), then v-add-letsencrypt-domain fails with "Error: web domain domain_in_cyrillic_here doesn't exist".

### Which version of Hestia Control Panel is currently installed?

1.1.1
### Which of the following web server configurations are you using?
- Nginx + PHP-FPM
- Multi-PHP
- PHP-FPM + Multi-PHP

NO DNS or mail is installed, just web and db

**Comment by ScIT-Raphael** [comment]
You are on the right way! 429 shows that you hit a let's encrypt cert limit, which prevents you to request more certificates. Wait a while, then try it again and let me know, if it works.

Otherwise you could also set LE_STAGING='yes' in your hestia.conf file, then you would use the testing servers without any limits (and of course not valid certs), just set it to no or remove tje line after you've finished testing.

As soon as you confirm, that all works properly, I'll add your modification to the script.

**Comment by zanami** [comment]
Still 429 without LE_STAGING='yes'

Error: Let's Encrypt new auth status 400
with LE_STAGING='yes'

UPDATE

I had to remove /usr/local/hestia/users/user/ssl/le.conf and user.key after switching LE_STAGING on.

Now it seems to work fine, except I can't actually acquire a real cert because LE complains "Error creating new order :: too many certificates already issued for exact set of domains"

**Comment by ScIT-Raphael** [comment]
> I had to remove /usr/local/hestia/users/user/ssl/le.conf and user.key after switching LE_STAGING on.

That was my mistake: I completly forgot to give you this information, sorry for that!

Thanks for the testing and code change, I've implemented it with the commit above. Please let me know if you find (or fix :)) anything else!
