### ISSUE TITLE
Feature Request: Nodejs Support out of the Box

### ISSUE THREAD

**Issue by gOOvER** [hestiacp/hestiacp#781]
I'm reall ynew to HestiaCP and i like, what i see. Now i miss NodeJS Support out ouf the Box.

I found:

https://github.com/logico/vestacp-nodejs

I woult love to see NodeJS Support as a Part of HestiaCP.

**Comment by ScIT-Raphael** [comment]
There is already a post in our forum about NodeJS, basicly you can implement it, it should be still compatible with hestia: https://forum.hestiacp.com/t/node-js-support/653

**Comment by gOOvER** [comment]
> There is already a post in our forum about NodeJS, basicly you can implement it, it should be still compatible with hestia: https://forum.hestiacp.com/t/node-js-support/653

Thats a Guide in Forum. This Ticket is a Feature Request ;) Not the same as the Forum Post.

So why you close a request without  saying something like:

"No, we will not integrate it" or "We will think about"

Funny how Feature Requests handled here

**Comment by ScIT-Raphael** [comment]
I just missread your issue report :).

We do not have enough resources to fullfill all requests. Infact there is already a solution how you could implement it, we will not provide a full implementation yet - so: "No, we will not integrate it" (at least from our side).

If you or anyone else would like to see it implemented, we're open for any pull request - we will review, test and merge them.

**Comment by gOOvER** [comment]
Its not an issue ;)

**Comment by am2222** [comment]
Hi @ScIT-Raphael , I was wondering if we look at the nodejs support as a kind of webapp installer script (https://github.com/hestiacp/hestiacp/tree/main/web/src/app/WebApp/Installers).
using this method we can define templates and set port (according to this https://help.clouding.io/hc/es/articles/360016993480-C%C3%B3mo-usar-Node-js-en-HestiaCP). we can also provide a form to set env variables (e.g. db config) as well, do you think this is a good approach?

**Comment by jaapmarcus** [comment]
Yes it possible. 

How ever I am not a fan of creating an "App" that depends on software that is not available  99% of the systems...

**Comment by am2222** [comment]
@jaapmarcus sorry I did not get it. Do you mean nodejs apps are not available on 99% of the systems?

**Comment by am2222** [comment]
@jaapmarcus sorry I did not get it. Do you mean nodejs apps are not available on 99% of the systems?
