### ISSUE TITLE
Feature Request: Nginx Rate Limiting

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#784]
# In a few words, please describe the issue that you're experiencing:
Extremely helpful security feature to deal with DoS and DDoS attacks.

### Additional notes:
https://www.nginx.com/blog/rate-limiting-nginx/

**Comment by ioannidesalex** [comment]
Thanks for your feedback @jaapmarcus 

Rate limiting is not about limiting traffic to a site, it is about limiting max connections from the same IP in a given tineframe. For example, I can’t see a legitimate cause of a single IP making more than 10 connections per second to a website. Rate limiting is about preventing access per IP not on the server as a total.

Having said that, I believe it is totally unrelated to caching. Rate limiting isn’t about performance, it’s about preventing DoS attacks through many simultaneous http requests.

**Comment by Skamasle** [comment]
But, hestia not need implement this, this can be implemented in a template level.

If somebody want ratelimit in a webserver, this somebody may know how implement it.

If you add a option in a panel, a normal user will not know what this option do, or then use.

Any sysadmin can create a template called "Limited conection" or something like that

Of course hestia just can add a template with default ratelimit option and not touch frontend to change ratelimit options.

My opinion is than is easyest create a guide for users, on "how create a template" and then they create templates, and ask always for templates " template fro that CMS" template for this orther CMS

Is better provide information on how create templates, and users will create his own templates, and share with community and if some body need it, just download and use, not add templates in a panel

If not, you will get with a time, hundreds of pull request to add templates for any website, and maybe nobody will use it, prevent this and provide plataform to users can share they templates, and you will save time and prevent lost time decide what template add and what no.

**Comment by Skamasle** [comment]
So, may you can add a a third party templates in github and people will pull templates there and not add it directly for panel, and so you will not have to take responsibility if it works or not

**Comment by ioannidesalex** [comment]
Rate limiting needs to be either implemented in current templates or in nginx.conf . It's very troublesome to have templates duplicated for all CMS just for rate limiting. We can set some "relaxed" values in nginx.conf that the user can easily change, just to have the structure ready. Even commented out.

Regarding default vs what's a decision by a user: same might apply to almost all features, like for example forcing SSL when SSL is enabled, having mysql listening to localhost by default etc. It's always a balance between security, reliability, ease of use, performance etc.

I can argue the same for pretty much anything else ("this somebody may know how to implement it"). Sysadmins know how to do everything hestia does, however here we are :)

**Comment by sandsjh** [comment]
https://github.com/myvesta/vesta/blob/master/src/deb/for-download/tools/rate-limit-tpl/install_rate_limit_tpl.sh
