### ISSUE TITLE
RU Translate interface issue

### ISSUE THREAD

**Issue by roam34** [hestiacp/hestiacp#785]
### In a few words, please describe the issue that you're experiencing:
When I change to RU translation in panel it seems like top menu overlayed user info, that looks ridicoulus.

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
master

### When did this issue occur? After a clean installation, or after an upgrade?
clean install

**Comment by Lupul** [comment]
![image](https://user-images.githubusercontent.com/3596864/80493677-5f823c80-896e-11ea-8e10-61dc569bd5db.png)
