### ISSUE TITLE
Feature: DNSSec for domains

### ISSUE THREAD

**Issue by loxK** [hestiacp/hestiacp#786]
Add an option to secure domains with DNSSec

**Comment by jaapmarcus** [comment]
See #439 
How ever closed due to limited time constraints..

I don't know what the current status is and if @gytisrepecka has it working at his server.

Was already checking how this needed to be implemented in the current system.

**Comment by gytisrepecka** [comment]
Didn't have time to set things up for Hestia yet... I do have a functioning DNS setup with DNSSEC on my CentOS-based infrastructure, so what I need is:
1. check and modify Bind configuration;
2. rewrite scripts for Ubuntu (minor changes) to generate ZSK and KSK keys for domain zone;
2. modify template to include ZSK and KSK in the end of zone file;
2. add interface in Hestia: enable/disable DNSSEC for domain, display KSK for submission to DNSSEC-enabled domain registrar.

**Comment by jaapmarcus** [comment]
Could you share some of the script even without the changes needed for Ubuntu/Debain?

It would save me hopefully some time?

**Comment by ScIT-Raphael** [comment]
@gytisrepecka If you could share your notes and docs with @jaapmarcus, this would help us much! He is also online in our internal teams chat, you can write him directly.

**Comment by jaapmarcus** [comment]
Currently working on DNSSec support incombination with Hestia :)

Please see the attached PR for any information changes required

**Comment by jaapmarcus** [comment]
And support has ben added and is planned for the 1.7.0 release. We will come soon with a 1.7.0 beta build

**Comment by jaapmarcus** [comment]
Beta release have been publish if you would like to test it would be awesome

https://forum.hestiacp.com/t/hestia-1-7-0-beta-dnssec-testing/7999/2
