### ISSUE TITLE
Feature: allow users to select template

### ISSUE THREAD

**Issue by loxK** [hestiacp/hestiacp#787]
In packages we should be able to multiple select templates. When this occurs, users have the choice between those.

A few examples:
* I want to allow my users to create DNS domains using templates for parking domains for Google and Office365, but also using the default template
* I want my users to be able to select the PHP version per www site

**Comment by ScIT-Raphael** [comment]
Hi @loxK 

Thanks for your feature request! In the current stack, a user could break the whole nginx server if he would set a faulty template. We currently discuss this internaly in combination with #450 to enable this feature also for normal users.

**Comment by Skamasle** [comment]
Why user will breake something ?

Only admin can add templates, so if all templates work well, user can sellect they and nothing bad will happen when user will change template

**Comment by ScIT-Raphael** [comment]
It always can happen, that you have a faulty template - even when you create them on your own (also happened to me :-) ).

We'll add a config validation and also rework the way how the config gets loaded (reload instead restart).

**Comment by Skamasle** [comment]
But, is admin responsability do good templates, of course all templates you have in productions will be tested, users cand add new templates

If you want add a test to verification, you will need add some functions to revert template if this inst working because if you just test is good or not, and not revert a faulty template when server restart any orther day all will fail

**Comment by jaapmarcus** [comment]
> * I want to allow my users to create DNS domains using templates for parking domains for Google and Office365, but also using the default template

Has been merged. 


> I want my users to be able to select the PHP version per www site 

Is written hard coded. Will change it soon

**Comment by jaapmarcus** [comment]
And also fixed :)

**Comment by nevstas** [comment]
User can't change "Backend Template" for his website.

![2022-10-10_16 27 40_e9yc9lkx5m](https://user-images.githubusercontent.com/22144214/194877867-e4097106-3c46-4b47-8a36-47b372e62d5d.png)


But admin can change "Backend Template" for the website.

![2022-10-10_16 27 56_9grd07wv1n](https://user-images.githubusercontent.com/22144214/194877885-ca4ac243-465a-4875-b551-bf5a274b5b58.png)


How can user change "Backend Template"? 
Can user use "PHP-5_6" and "PHP-8_1"?
@jaapmarcus

**Comment by jaapmarcus** [comment]
There is a setting in the server settings -> policies
