### ISSUE TITLE
hackers trying to look for sensitive files on /var/www/html

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#789]
as of our "/var/log/apache2/error.log"
seems hackers trying to look for any sensitive files inside & ofcourse they getting '404' errors.

Instead i letting them to try and keep knocking my server, i wish to redirect them if there is no such files. [Eg: redirect to google.com].
So the hacker again have to re'type in our server ip again to try another. Just to give him some simple difficulties.

So, I tried to put a htaccess file but it not working.
/var/www/html/.htaccess: RewriteEngine not allowed here

**Comment by Lupul** [comment]
`/var/www/html/` path is not accesibile in Hestia by default

**Comment by vvcares** [comment]
hi, yes noted. But if we used type the server's IP, it will leads to default /var/www/html/

**Comment by vvcares** [comment]
for testing, you may try your actual server ip of hestiacp.com - just your source server ip on browser. It will resolve to your /var/www/html/index file.

I saw that, but not wish to provide here. :-) haha 

Ref: https://github.com/hestiacp/hestiacp/commit/e42670c878d1f3e952f1944e22cfe52bd68e951a

**Comment by vvcares** [comment]
I edited my 
'/etc/apache2/conf.d/ServerIP.conf'

Add the attribute..

<Directory />
    Options FollowSymLinks
    AllowOverride All
</Directory>

So this will allow me to config htaccess.

Hi team, kindly consider this as security enhancement. 

1. Any public directory must have htaccess file for better security.
2. Any unknown domain names should not resolve to default page, instead it should show 'no such domain here'. (Eg: i create cloudflare DNS as test.domain.com pointing to my server ip, it should not give any default page)

**Comment by Lupul** [comment]
You are right, my prev answer was incorrect.
`/var/www/html` is used as dead-end (catchall) for **unknown** domains and **direct IP** access.

This is by design and there are absolutely no security risks here.

I'm glad you found a way to make it work the way you want, still we don't plan the change the current behavior.
