### ISSUE TITLE
Bug: phpMyAdmin custom URL functionality does not work correctly

### ISSUE THREAD

**Issue by marcofbb** [hestiacp/hestiacp#790]
Error when change PHPmyadmin URL via https://myip:8083/list/server/, change URL for "phpMyS2828382"

![image](https://user-images.githubusercontent.com/8323867/80666754-98f0a000-8a73-11ea-93e3-9c82a4522794.png)

Save changes, and go to "DB > Phpmyadmin"

![image](https://user-images.githubusercontent.com/8323867/80666785-b02f8d80-8a73-11ea-9064-a47ac4be9cc3.png)

Open link: https://myip:8083/list/db/phpMyS2828382 and show there error: 

![image](https://user-images.githubusercontent.com/8323867/80666806-c0e00380-8a73-11ea-9734-f88974af1313.png)

I probe enter in:
https://myip:8083/list/db/phpMyS2828382
http://myip:8083/list/db/phpMyS2828382
https://myip:8083/phpMyS2828382
http://myip:8083/phpMyS2828382
http://myip/phpMyS2828382
https://myip/phpMyS2828382
http://myip:8083/phpMyS2828382
https://myip/list/db/phpMyS2828382
http://myip/list/db/phpMyS2828382

myip is the IP of my server

All generate error

### Operating system distribution and release:
Ubuntu 16.04 (x86_64) 

### Which of the following web server configurations are you using?
Install Default hestiacp v1.1.1

**Comment by vvcares** [comment]
haha. The url must be typed as full full url. not only 'phpMyS2828382'
 http://server/phpMyS2828382

**Comment by marcofbb** [comment]
> haha. The url must be typed as full full url. not only 'phpMyS2828382'
> http://server/phpMyS2828382

There I understood, in the field I have to put the complete URL


Edit: Still not working

**Comment by marcofbb** [comment]
![image](https://user-images.githubusercontent.com/8323867/80747249-81f49100-8af9-11ea-9885-b8c93273c4b5.png)

**Comment by jaapmarcus** [comment]
phpMyAdmin Url only change the button in the admin interface. Altering this value will call
./v-change-sys-config-value

You will need to run

./v-change-sys-pma

to change the nginx config

See
https://github.com/hestiacp/hestiacp/blob/master/bin/v-change-sys-pma

and

https://github.com/hestiacp/hestiacp/blob/master/bin/v-change-sys-config-value

**Comment by marcofbb** [comment]
I see, thanks.

It would be nice if it is 100% automated

Close topic

**Comment by jaapmarcus** [comment]
Please keep it open spoke with the "team" and the confirmed it is a bug and they needed to take a look at it. 

@ScIT-Raphael

**Comment by Lupul** [comment]
You are correct @jaapmarcus, this functionality needs to be fixed, the way it is now it's confusing for users.

**Comment by ghost** [comment]
In v1.2.0 final, this behavior has been modified to work the same as the Webmail Alias -- only enter the name of the alias that you wish to use for phpMyAdmin/phpPgAdmin access, such as "MyPMA" or "MyPGA" (for example) instead of the full URL.
