### ISSUE TITLE
Feature Request: Restrict panel login via hostname only

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#791]
Adding the below single line into '/usr/local/hestia/web/inc/main.php' ?

`$referer= strtok($_SERVER['HTTP_HOST'], ':');if ($referer != exec('hostname')) {header("Location: //$referer "); exit;}`

The above code will check,

If the requesting domain is matching the hostname, which assigned on HCP?
If is not matching, redirect to referrer domain itself & not letting to use HCP.

**Comment by Lupul** [comment]
Hi @vvcares, there is no security advantage in doing this, it could even create problems with setups that relay on central web application firewalls (WAF) to protect multiple Hestia deployments.

**Comment by ghost** [comment]
Hi vvcares,

Thanks for submitting this request. After discussing internally we've decided not to proceed with adding this to the default configuration, however there's no reason that you couldn't continue to make this modification to your own servers if you wish to do so.

**Comment by vvcares** [comment]
So,
- my HCP login url is = http: //ServerHostname:port
- So any of my internal domains will serve the same HCP login panel, as long the port is matched.

Means, any domain inside my HCP server, cant use that same port for other purpose, because it will be redirected to this HCP login page.

**Comment by Lupul** [comment]
tcp ports are binded to ip and not to domains
