### ISSUE TITLE
v-restore-user error when restoring users with extra files in home dir

### ISSUE THREAD

**Issue by ifaist0s** [hestiacp/hestiacp#795]
### In a few words, please describe the issue that you're experiencing:
While running v-restore-user, for users who have extra files in user dir (like in my example the directory .nano and the file .bash_history) the following errors are thrown:
```
-- USER FILES --
2020-05-03 17:11:39 .bashrc
2020-05-03 17:11:39 .nano
chown: cannot access '/home/[USER]/.nano': No such file or directory
2020-05-03 17:11:39 .profile
2020-05-03 17:11:39 .bash_history
chown: cannot access '/home/[USER]/.bash_history': No such file or directory
2020-05-03 17:11:39 .bash_logout
```
### What steps did you take when the issue occurred? 
1. Place backup file in `/backup` folder
2. Change owner to admin:admin
3. Run `v-restore user [USER] [BACKUP]`

### Expected behavior:
The backup should complete without any errors.

### Does this issue always occur, or is it intermittent?
It occurs 100% of the times I tried, **when the user being restored has extra files in their home directory**.

### Operating system distribution and release:
Ubuntu 18.04.4 LTS (where the backup file was created at)
Ubuntu 18.04.4 LTS (where the backup is being restored to)

### Which version of Hestia Control Panel is currently installed?
1.1.1 (where the backup is being restored to)
1.0.6 (where the backup file was created at)

### Which branch are you using?
Release

### When did this issue occur? After a clean installation, or after an upgrade?
Clean installation of Hestia 1.1.1

The backup file was created on a server with Hestia 1.0.6, which might have been updated from an earlier Hestia version

### Which of the following web server configurations are you using?
- Apache + Nginx (default) + Multi-PHP (–nginx yes --apache yes --phpfpm no --multiphp yes)

### Additional notes:
Running `v-restore-user` through `bash -x` I got:
```
2020-05-03 17:21:54 .nano
+ tar xf /backup/[BACKUP].tar -C /backup/tmp.alRshVf79f --no-wildcards ./user_dir/.nano.tar.gz
+ '[' 0 -ne 0 ']'
+ chown [USER] /backup/tmp.alRshVf79f/user_dir
+ chown [USER] /home/[USER]
+ chown [USER] /home/[USER]/.nano
chown: cannot access '/home/[USER]/.nano': No such file or directory
+ /usr/local/hestia/bin/v-extract-fs-archive [USER] /backup/tmp.alRshVf79f/user_dir/.nano.tar.gz /home/[USER]
```
It seems that the `chown` is happening **before** the extraction of the actual file/dir and thus the error.

I rearranged the order of execution in file `v-restore-user`, so the extraction happens before the `chown` (flipped lines [781](https://github.com/hestiacp/hestiacp/blob/b96db11b1ee3175f9c1bad9d6fe7ba272e85558c/bin/v-restore-user#L781)-782). I ran a test with the backup file that was throwing the errors and it seems OK now.

I'll prepare the relevant PR shortly.

**Comment by ScIT-Raphael** [comment]
Awesome work @ifaist0s!!!

If you catch a new bug, please feel free to directly send us a pull request - you don't need to create a such awesome and detailed issue report, if you gonna solve it directly on your own <3.

Again, thanks for your contribution!

**Comment by ScIT-Raphael** [comment]
Just merged your pull request, I'll close the issue now. Thank you very much!

**Comment by Lupul** [comment]
Changing the user permission before extracting the archive was supposed to make sure that v-extract-fs-archive has enough perm to overwrite the file since it will run with dropped priv as $user and not as root. This case was reported on the internal chat a couple of months back.

Another solution for handling the missing files:
```[ -e "$HOMEDIR/$user/$user_dir" ] && chown "$user" "$HOMEDIR/$user/$user_dir"```
