### ISSUE TITLE
Bug: Miscellaneous API task execution issues

### ISSUE THREAD

**Issue by lfsite** [hestiacp/hestiacp#797]
### In a few words, please describe the issue that you're experiencing:
I tried adding a new web domain to Hestia with the API using PHP cURL. It created the domain in Hestia, but at the same time it came up with the HTTP 500 error page. The issue was that it restarted PHP-FPM. I set arg4 (restart) to "no", it did not restarted apache, but it still restarted PHP-FPM.

### What steps did you take when the issue occured? 
1. I created this script on the same server that Hestia is installed on: https://gist.github.com/lfsite/8200c133c8c98ce371afe24c72def05a
2. I executed the script through my browser.

### Expected behavior:
It creates the domain and redirects to e.g. success.php

### Does this issue always occur, or is it intermittent?
If this script is on the same server, it will occur.

### Operating system distribution and release:
Ubuntu 18.04.4 LTS

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
This issue occurs after a clean install (i.e. no upgrade)

### Which of the following web server configurations are you using?
Apache + Nginx + Multi-PHP

### In order to better assist, please post any relevant log information below:
`[proxy_fcgi:error] AH01067: Failed to read FastCGI header
[proxy_fcgi:error] (104)Connection reset by peer: AH01075: Error dispatching request to :`

### Related issues or forum threads:
None

### Additional notes:
I temporarily fixed the problem by adding `$restart` at the end of line 110 in /bin/v-add-web-domain like this:
`$BIN/v-add-web-domain-backend "$user" "$domain" $BACKEND_TEMPLATE $restart`
This will forward the restart parameter to the v-add-web-domain-backend script. So it doesn't restart PHP-FPM anymore.

**Comment by jaapmarcus** [comment]
I don't know why instead restarting fpm / nginx / apache only reload? Probably there is some code rewrite.

**Comment by alber-khan** [comment]
Same issue on Ubuntu 16.04

**Comment by alber-khan** [comment]
Hello the same issue happens when you try to suspend the user via API, it gives "Failed to read FastCGI header" and it doesn't suspend the user. it requires hitting the API 2-3 times and then finally it suspend the user. I've noticed this usually happens when the size of the website is big.

I'm using this API File to make calls.
http://c.vestacp.com/0.9.8/rhel/whmcs-module.php

**Comment by alber-khan** [comment]
I run the script via cronjob and it automatically checks if the person has made the payment or not  
php7.3 -q -d memory_limit=1024M /home/admin/web/domain.tld/public_html/crons/cron.php

and when I try to suspend the user via a web browser (panel). The first API request usually takes around 30s and then shoots the error and when I try to run it again it works fine but it takes around 10s-15s to get response.

**Comment by alber-khan** [comment]
[Thu Jun 25 03:27:12.984911 2020] [proxy_fcgi:error] [pid 5649] [client 47.9.22.122:41908] AH01067: Failed to read FastCGI header, 

the same issue comes when you try to delete the user via API

**Comment by alber-khan** [comment]
any update on this issue?

**Comment by Lupul** [comment]
yes, was fixed in this PR https://github.com/hestiacp/hestiacp/pull/1094, will be shipped in the next release
