### ISSUE TITLE
Problem if other service is listening on 443

### ISSUE THREAD

**Issue by hrvylein** [hestiacp/hestiacp#798]
One year ago I came up with the question if somehow sslh could be integrated in the setup chain or some settings for config generation to reflect the usage of sslh. This was declined and label wontfix was added.

To fulfill my needs I duplicated some of the nginx templates and changed them to listen on 127.0.0.1 instead of %ip%. This was working to the point where I thought it was a good idea to add ssl to mail over the webinterface. After that nginx couldn't be restarted as it couldn't bind to PUBLICIP:443 for mail.domain.tld and webmail.domain.tld. When I found out which files caused the problem I edited them to instead listen on 127.0.0.1 and everything went from broken to working again.

As I really need sslh in my setup every update of hestia may possible break anything as nginx tries to listen on the public ip again and some of your templates are update too for good as they reflect changes in paths/software/security and so on. I have to manually adapt the changes in my cloned templates.

Is there any possibility to have a setting somewhere to set the serverip to 127.0.0.1 instead of public ip when generating configs?

**Comment by changeme** [comment]
Maybe this post on support forum can help you

https://forum.hestiacp.com/t/reverse-proxy-and-port-redirection/859
