### ISSUE TITLE
Bug: Quota Install fails during install

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#808]
### In a few words, please describe the issue that you're experiencing:
Install with Quota failed on Ubuntu 20.04 

### What steps did you take when the issue occured? 
Install Hestia with the following string:

sudo bash hst-install-ubuntu.sh --apache yes --nginx yes --phpfpm no --multiphp yes --vsftpd no --proftpd yes --named yes --mysql yes --postgresql yes --exim yes --dovecot yes --clamav yes --spamassassin yes --iptables yes --fail2ban yes --quota yes --api yes --force yes --interactive no --port 8083 --hostname xxx.nl --email my@email.com --password test --lang en

### Expected behavior:
Install Quota should successful and give no error
### Does this issue always occur, or is it intermittent?
Install

### Operating system distribution and release:
Ubuntu 20.04

### Which version of Hestia Control Panel is currently installed?
1.1.2 Master branch

### Which branch are you using?
Master

### When did this issue occur? After a clean installation, or after an upgrade?
Clean install

### Which of the following web server configurations are you using?

sudo bash hst-install-ubuntu.sh --apache yes --nginx yes --phpfpm no --multiphp yes --vsftpd no --proftpd yes --named yes --mysql yes --postgresql yes --exim yes --dovecot yes --clamav yes --spamassassin yes --iptables yes --fail2ban yes --quota yes --api yes --force yes --interactive no --port 8083 --hostname xxx.nl --email my@email.com --password test --lang en

### In order to better assist, please post any relevant log information below:
(*) Configuring system settings...
(*) Configuring Hestia Control Panel...
(*) Generating default self-signed SSL certificate...
(*) Adding SSL certificate to Hestia Control Panel...
(*) Configuring NGINX...
(*) Configuring Apache Web Server...
(*) Install PHP version 5.6...
(*) Install PHP version 7.0...
(*) Install PHP version 7.1...
(*) Install PHP version 7.2...
(*) Install PHP version 7.3...
(*) Install PHP version 7.4...
(*) Configuring PHP...
(*) Configuring ProFTPD server...
(*) Configuring MariaDB database server...
(*) Installing phpMyAdmin version v5.0.2...
(*) Configuring PostgreSQL database server...
ALTER ROLE
(*) Configuring Bind DNS server...
(*) Configuring Exim mail server...
(*) Configuring Dovecot POP/IMAP mail server...
(*) Installing ClamAV anti-virus definitions...-
(*) Configuring SpamAssassin...
(*) Configuring Roundcube webmail client...
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
(*) Configuring fail2ban access monitor...
cat: /etc/rc.local: No such file or directory
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
quotaon: using //aquota.group on /dev/vda1 [/]: No such process
quotaon: Quota format not supported in kernel.
quotaon: using //aquota.user on /dev/vda1 [/]: No such process
quotaon: Quota format not supported in kernel.
Error: quota can't be enabled in /

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
PostgreSQL / apache2 and rc.local error messages have already been checked/fixed

**Comment by Skamasle** [comment]
You run this in virtual machine ?

You need be sure than virtual machine support quota, so, for example if you use vz or lxc you need enable quotes for container

**Comment by ScIT-Raphael** [comment]
Hi @Skamasle 

This occured during ubuntu 20.04 support testing, the ticket is here for keep it in mind and do further testing on it. Thanks for the input about quota support, I'll check it also on one of my machines as soon as I can.

**Comment by Skamasle** [comment]
Ok, may be will be good, than you add virtualization type you use in the tests, in this way orther people can test this in orther virutal enviroments, kvm, virtualbox, vz, lxc, xen and any orther information

**Comment by jaapmarcus** [comment]
@Skamasle yes  I am using Multipass as virtualisation I know not the best software. So it could be the reason...

**Comment by Skamasle** [comment]
Ok, just check if Munltipass support quotas

A lot of containers not support quota by default, or try install panel and not use --quota yes or use --quota no if supported

**Comment by ScIT-Raphael** [comment]
@jaapmarcus is part of the dev team, this ticket is for debugging the issue :).

Thanks for the input about adjusting the issue template @Skamasle, I'll discuss this with the team, but I think we'll implement it - there are some virtualization based issues in the wild, so it would be good to know what they use.

**Comment by ifaist0s** [comment]
About the quota issue, it might be that you don't have the [kernel modules installed](https://forum.hestiacp.com/t/strange-message-during-installation-quotas-involved/204/2) (bare metal and KVM).

**Comment by ScIT-Raphael** [comment]
Hi @ifaist0s 

Yes you're right, we noticed this around 2 days ago and currently working to expand the v-add-sys-quota script with additional validation routines.

**Comment by ghost** [comment]
Fixed in v1.2.0.
