### ISSUE TITLE
Backup counter

### ISSUE THREAD

**Issue by Skyfox701** [hestiacp/hestiacp#822]
Hello,
I'm looking a bit on hestia playng a bit on a test envoroment.

For test I created a backup and today I deleted it using the delect command from the console

the  counter in the top banner is still showing 1 but no backup are available.

![immagine](https://user-images.githubusercontent.com/65709011/82545161-893a1800-9b56-11ea-9b58-6c5b13130ab3.png)

also the summary is showing 1 
![immagine](https://user-images.githubusercontent.com/65709011/82545435-f6e64400-9b56-11ea-91d5-f76908b46144.png)

![immagine](https://user-images.githubusercontent.com/65709011/82545705-580e1780-9b57-11ea-8b99-b985ac1c65b9.png)

Hestia Control Panel:                                                                                                                                        v1.1.1 
Operating System:                     
Ubuntu 18.04 (x86_64)

**Comment by jaapmarcus** [comment]
May I ask what version / branch you are currently using

Server --> Configure --> Version and Release

**Comment by Skyfox701** [comment]
sorry just updated the ticket

**Comment by jaapmarcus** [comment]
Just check it when executing the command

./bin/v-delete-user-backup [user] [name] the stats won't change.

When executed from interface the stat get changed.

**Comment by jaapmarcus** [comment]
When [user].log is present in the /backup folder it is also counted with it. 

The v-backup-user(s) does it based on counting the rows in `$HESTIA/data/users/[user]/backup.conf `

This [commit](https://github.com/hestiacp/hestiacp/commit/bdced66b8260c4efd44391bceddd1bf6ef07ebb2) will do the same will be fixed in next release. 

Thanks for reporting :)

**Comment by Skyfox701** [comment]
You are welcome.
Thanks for the fix ;)
