### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by ww7** [hestiacp/hestiacp#823]
I can recommend a temporary solution before native HeastiCP file manager developed to use elFinder with FTP connector. 

I lock FTP to localhost and add elFinder apache/nginx conf file with basic http auth. 

This scheme preserves ownership and works fine.
Drag'n'drop between users works, upload any size files, works with archives, edits with syntax highlight etc

I can write steps and provide files if anyone needed.

[![Screenshot-2020-05-21-at-23-50-24.png](https://i.postimg.cc/cJNQLmB3/Screenshot-2020-05-21-at-23-50-24.png)](https://postimg.cc/Mndcs14Z)
[![Screenshot-2020-05-21-at-23-59-31.png](https://i.postimg.cc/sx92KYZk/Screenshot-2020-05-21-at-23-59-31.png)](https://postimg.cc/BPbsn1pp)

**Comment by jaapmarcus** [comment]
We are currently working on a file manager that suits the security standaard we want to follow.

See https://github.com/hestiacp/hestiacp/pull/820 how to use and install it...

**Comment by ww7** [comment]
Cool! Thanks.

**Comment by jaapmarcus** [comment]
Please note this is a  non stable version so be carefull and don't use it on a live server that is important. Release probably in 1.1.3

**Comment by jaapmarcus** [comment]
No issue / Bug / Feature request won't be necessary. We are working on it
