### ISSUE TITLE
phpmyadmin BUG

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#825]
I do clean install hestiacp in ubuntu 18 using this command:

`bash hst-install.sh -a yes -n yes -w no -o no -v no -j no -k no -m yes -g no -x no -z no -c no -t no -i yes -b yes -q no -d no -r 8083 -l en -y yes -force`

But I cant connect/open phpmyadmin
Why?

**Comment by ScIT-Raphael** [comment]
It would help if you not delete the issue report template, there is a reason behind. Please fill it out step by step so we got all informations to help you out.

**Comment by erikdemarco** [comment]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
I do clean install hestiacp in ubuntu 18 using this command:
But I cant connect/open phpmyadmin

### What steps did you take when the issue occured? 
Just do the default installation steps.

### Expected behavior:
phpmyadmin will show login page

### Does this issue always occur, or is it intermittent?
yes. even when using default steps here: https://www.vultr.com/docs/how-to-install-hestia-control-panel-on-ubuntu-18-04

### Operating system distribution and release:
Ubuntu 18.04 vultr

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
when do the clean install

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)


### In order to better assist, please post any relevant log information below:


### Related issues or forum threads:
https://forum.hestiacp.com/t/can-not-open-phpmyadmin-in-hestia-cp-1-1-0/547

### Additional notes:

**Comment by ScIT-Raphael** [comment]
Maybe you also want to share, what exactly you try to access for a domain to reach phpmyadmin? You should anonymize it of course.

**Comment by erikdemarco** [comment]
I create test user, test db, then try to use button 'phpMyAdmin' in the admin panel.
In browser I see message: Firefox cannot establish a connection to the server xx.xx.xx.xx (my server ip).
phpMyAdmin do not working.

For comparison i try to install clean vestacp, and repeat the exact same steps. I can access it in vestacp. So its probably a bug in hestiacp

**Comment by ScIT-Raphael** [comment]
You still didnt shared the domain you try to reach, please copy & paste the content of your adressbar and anonymize your ip or domain name.

Hestia has a lot of changes in security, so it may also be by design - but as soon as we got the right information from you we can start to help :).

**Comment by erikdemarco** [comment]
Hi, sorry my english is not good.

The url is like this:
139.180.xxx.xx/phpmyadmin/

Just click "phpmyadmin" button in the admin panel. There is only 1 phpmyadmin button in the admin panel.

**Comment by ScIT-Raphael** [comment]
There is the issue, if you would have followed the vultr guide properly, you would have seen to use the hostname for login - not the ip address. If you do it, phpmyadmin will also work properly.

**Comment by erikdemarco** [comment]
@ScIT-Raphael Hi I dont know about that. Is this only apply to vultr?
I have been using a lot of control panel. I never need to use a domain name just to install control panel. I think we should make a note in the website. So they know from beginning what is the official steps to install.

At first I thought There is many bugs in hestiacp. But its not, we just need many additional steps to make it work.

For example:

To restore backup we need to (there is no document for this in hestiacp website):
1. put backup file in /backup folder
2. cd to that dir
3. run v-restore-user

To use phpmyadmin I need to run v-add-letsencrypt-host  first
https://forum.hestiacp.com/t/can-not-open-phpmyadmin-in-hestia-cp-1-1-0/547

User dont like additional steps like this. Please make hestiacp as intuitive as vestacp. Because I really like hestiacp.

**Comment by ScIT-Raphael** [comment]
Honestly, you seem to missunderstood a lot :).

You don't need a domain to run the hosting panel, but usualy you give it a hostname during installation - which is your hostname, just add a dns record that points to your server and all is done.

Also this is not needed at all to get to phpmyadmin, it just will not served on the ip - it needs a domain name, doesnt matter if this is the hostname or a additional domain you host on top of hestia.

Then about the restore, there is already a pending issue - also it is the same behaviour as on vesta, nothing is "special" here, it was always "you need to place the backup in /backup" - but yes, our doc needs still a lot of work.

To answer your last question: No, this doesnt apply to vultr at all, but vultr gave you a 1:1 tutorial how to do it, and if you would have followed it (adding a hostname and install a valid certificate, then login over domain name), you wouldnt had have any issues at all. Just my 5 cents :).

**Comment by Lupul** [comment]
-You don't have to run `v-add-letsencrypt-host` to access phpmyadmin, you just can't use the server IP for that. 
-Backup restore works the same on Vesta. ( from /backup folder)

**Comment by erikdemarco** [comment]
@ScIT-Raphael @Lupul Guys please give a suggestion.

I set my server behind cloudflare. And I lock my hestiacp panel only can be accessed by loocalhost.
So to access my panel I need to ssh tunnel to my server first after that I can access my panel.

I can't use domain because it must come thru cloudflare (which is blocked because it can only be accessed by localhost)

So the only way I can access panel is from server ip directly. But if I access by ip I cant open phpmyadmin. Because of this "security" feature

Locking my panel to localhost-only is my best protection against any hack. I have been using vestacp for 3years. And all my servers which used vestacp is safe because of this strategy alone.

Do you guys have any suggestion how to solve my problem?

**Comment by jaapmarcus** [comment]
Cloudflare allow uses certain ports for example 2083

See https://docs.hestiacp.com/cli_commands/panel_configuration_commands.html#v-change-sys-port to change the port to 2083

I just checked it last week it should work. 

See https://blog.cloudflare.com/cloudflare-now-supporting-more-ports/

**Comment by erikdemarco** [comment]
> Cloudflare allow uses certain ports for example 2083
> 
> See https://docs.hestiacp.com/cli_commands/panel_configuration_commands.html#v-change-sys-port to change the port to 2083
> 
> I just checked it last week it should work.
> 
> See https://blog.cloudflare.com/cloudflare-now-supporting-more-ports/

Im sorry maybe you misunderstand me.
I use port 2083 as well. But If I access from cloudflare (orange cloud) the accessed ip is not localhost but cloudflare's ip. So my server will deny the connection. The only way is to make it (grey cloud) but that will show my real server ip to attacker

**Comment by erikdemarco** [comment]
I have found a solution. To manually add my server ip record to my computer /etc/hosts

But there is another problem. To access phpmyadmin I need to run 'v-add-letsencrypt-host' first
Can letsencrypt work if i lock my host panel so only localhost can access it?

**Comment by ScIT-Raphael** [comment]
Yes, because the validation isnt done over the backend port - it will be done for the webdomain under the admin user, so it is over port 80/443 and also work over cloudflare.

**Comment by joeygeo** [comment]
@erikdemarco were you able to resolve this? I am also using ssh tunnel to access the hestia panel. 
I tried using a subdomain in my local hosts file with IP 127.0.0.1 and panel works fine... but phpmyadmin still does not load.
any thoughts?

**Comment by Supernova3339** [comment]
For me I just did a restart and it fixed stuff. See if it works for you.
