### ISSUE TITLE
Cant login after restore from vestacp backup file

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#827]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
When I do clean install of hestiacp and do restore from vestacp backup file, I cant login to the restored user (admin panel and ssh)

### What steps did you take when the issue occured? 
1. Place backup file in /backup folder
2. Change owner to admin:admin
3. Run v-restore user [USER] [BACKUP]

### Expected behavior:
I should be able to login succesfully

### Does this issue always occur, or is it intermittent?
Yes

### Operating system distribution and release:
Ubuntu 18

### Which version of Hestia Control Panel is currently installed?
1.1.0

Please enter your answer here (e.g. 1.1.0)

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
after clean install

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

### Related issues or forum threads:
https://github.com/hestiacp/hestiacp/issues/793

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by Lupul** [comment]
Any errors during restore?
Is the user present in /etc/shadow and does the hash match what you have in the archive.
Can create a Vesta backup without sensitive information and share it with us (contact email, or private message on forum.hestiacp.com)

**Comment by Lupul** [comment]
I could reproduce the problem, so no need to send anything anymore.

**Comment by Lupul** [comment]
Found the problem, are you ok checking the fix?

**Comment by Lupul** [comment]
After applying the patch from prev commit, running `v-rebuild-user 'myuser' no` will be enough to restore the user passwords

**Comment by erikdemarco** [comment]
@Lupul Hi. Is the patch already applied in the current release? I still cant get it to work. I use 'v-change-user-password' after the restore and it works.

Will it causes error in the future if i just do 'v-change-user-password''?

**Comment by Lupul** [comment]
It's safe to just use`v-change-user-password`

Fix was merged to master (here: https://github.com/hestiacp/hestiacp/commit/57d95375273142a431f0b915d47c12eb74bfe685) and will be released in the next Hestia version.
If you have other backups that you need to restore, you can apply manually the patch
