### ISSUE TITLE
Feature: Allow Web Domain SSL to be used for Hestia Panel and Mail

### ISSUE THREAD

**Issue by eddynetweb** [hestiacp/hestiacp#828]
In the original VestaCP, a feature was added to allow a domain SSL certificate to be imported easily for the Vesta panel and also mail server certificates. This can be seen in the demo version of VestaCP: https://demo.vestacp.com:8083/edit/server/

![Screenshot from 2020-05-23 14-15-12](https://user-images.githubusercontent.com/7884281/82738788-00f77680-9d00-11ea-99a3-485ae484fa2c.png)

![Screenshot from 2020-05-23 14-15-31](https://user-images.githubusercontent.com/7884281/82738792-08b71b00-9d00-11ea-83c4-10c45fe3f450.png)

Might be useful to add this to Hestia panel as well. I imagine that it's a feature that can be grabbed from downstream VestaCP.

**Comment by ScIT-Raphael** [comment]
Just checkout v-add-letsencrypt-host and give it a run, be sure you have a valid dns record pointing to your server for your hostname :).

**Comment by eddynetweb** [comment]
Perfect - didn't know this was a feature. 

Thank you.
