### ISSUE TITLE
Stats seem to be broken

### ISSUE THREAD

**Issue by zanami** [hestiacp/hestiacp#833]
===

### In a few words, please describe the issue that you're experiencing:
Statistics - View All Statistics doesn't work as it supposed to.

![stats-total](https://user-images.githubusercontent.com/4746069/83093067-172b7b00-a0e2-11ea-9397-48869f11f46e.png)

It used to work before and it does work for a specific user (Show Per User)

![stats-admin](https://user-images.githubusercontent.com/4746069/83093084-1c88c580-a0e2-11ea-8af7-8d8f57d242fd.png)

Seems like it displays somewhat inaccurate stats for the last added (newest) user
Here's that user, not sure why IPs=0, everything else looks fine

![stats-user22](https://user-images.githubusercontent.com/4746069/83093779-75a52900-a0e3-11ea-93eb-25095ad0b98f.png)

### What steps did you take when the issue occured? 
1. Log into the Hestia Control Panel
2. Click on the Statistics

### Expected behavior:
Statistics totals should be displayed

### Does this issue always occur, or is it intermittent?
So far it's pretty consistent. Doesn't help: log out/in, reboot, re-run cron jobs (it updates user22 stats and totals, they are still equal, IPs is still 0)

### Operating system distribution and release:
Debian GNU/Linux 9 (stretch)

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Not sure, just noticed

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM
- PHP-FPM + Multi-PHP

**Comment by Lupul** [comment]
Confirmed.

for a quick fixed you can comment out the for block highlighted here (`/usr/local/hestia/bin/v-list-users-stats`):
https://github.com/hestiacp/hestiacp/blob/85158e483f11cde9e5f0a3abe4ca56144b4c0102/bin/v-list-users-stats#L125-L127

and add the following line after:
```
$BIN/v-update-user-stats
```

**Comment by Lupul** [comment]
Will keep the issue open as the underling bug in v-update-user-stats need to be investigated too.
https://github.com/hestiacp/hestiacp/blob/58d051970b6c58dc26ebb05fd10f6ed80f97cd23/bin/v-update-user-stats#L161
