### ISSUE TITLE
File manager installer

### ISSUE THREAD

**Issue by DemOnJR** [hestiacp/hestiacp#837]
When i try to install filemanager with this command **sh install-fm.sh** i get an error:

```
cp: cannot stat '/filemanager/filegator/*': No such file or directory
install-fm.sh: 57: install-fm.sh: /admin/.composer/composer: not found
```

**Comment by ScIT-Raphael** [comment]
The issue form isnt a decoration, please use it :).

**Comment by Lupul** [comment]
The full output log will also be required. First glance at the error msg the env vars are missing, was the installer run as root?
