### ISSUE TITLE
Please dont use mpm prefork anymore for Apache.

### ISSUE THREAD

**Issue by erikdemarco** [hestiacp/hestiacp#839]
Why mpm prefork is still used in vestacp until this day?

Even in apache official docs they do not recommend it anymore since apache 2.1 is released 13 years ago.

https://cwiki.apache.org/confluence/display/HTTPD/PHP

Please remove support for mpm prefork in hestiacp. As its really reallly old school.

And dont use fcgid as well as there is known bug. it will show 500 error every 500request see:
=> https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html

```
"Special PHP considerations

By default, PHP FastCGI processes exit after handling 500 requests, and they may exit after this module has already connected to the application and sent the next request. When that occurs, an error will be logged and 500 Internal Server Error will be returned to the client. "
```

**Comment by ScIT-Raphael** [comment]
Hi @erikdemarco 

We are already working on the switch to mpm_event instead mpm_prefork - this will start with a manual migration script and adjustment of the installer. The priority is set to be done after the next release.
