### ISSUE TITLE
Default Package Request Addition - GMP php extention

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#849]
Looks like Nextcloud 19.0 is relying on the gmp php extension now, this would make a nice addition to Hestia

the command I used to install it was
apt install php7.4-gmp

### Operating system distribution and release:
Ubuntu 18.04.4 LXC

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Please enter your answer here (e.g the feature stopped working after upgrading to the latest release)

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

**Comment by ScIT-Raphael** [comment]
Hi @johnnyq 

We do not want to overload hestia, it should arrive in a small and fast default configuration that works for the most websites and cms - which it does already. If you need additional packages, you can install them as you already written over apt install for the required version.

**Comment by Lupul** [comment]
@johnnyq  Can I get an update on this: https://github.com/hestiacp/hestiacp/issues/463
