### ISSUE TITLE
Bug: Installer - apt caused output to truncate occasionally

### ISSUE THREAD

**Issue by rmj-s** [hestiacp/hestiacp#851]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
**There is a typo in the installer for Ubuntu.**
```
Extracting templates from packages: 100%lease wait...\
```
### What steps did you take when the issue occured? 
**NA**
### Expected behavior:
**It should be:**
```
Extracting templates from packages: 100% Please wait...\
```
### Does this issue always occur, or is it intermittent?
**Always**

### Operating system distribution and release:
**Ubuntu 18.04**

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

` v1.1.1`

### Which branch are you using?
**Master**

### When did this issue occur? After a clean installation, or after an upgrade?
**During Installation**

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
```bash
bash hst-install.sh --apache yes --nginx yes --phpfpm yes --multiphp no --mysql yes --postgresql no --vsftpd yes --proftpd no --named yes --exim yes --dovecot yes --clamav no --spamassassin no --iptables yes --fail2ban yes --quota no --api yes --lang en --port 8083 --interactive yes --force
```

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.
**NA**
### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)
**NA**
### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.
**NA**

**Comment by ScIT-Raphael** [comment]
This isnt a typo from the installer, it comes from apt-get upgrade (https://github.com/hestiacp/hestiacp/blob/fe5bf53aff1f7ddb5e897d53a3f05202a650a130/install/hst-install-ubuntu.sh#L611), the output doesnt get fully redirected some times - depends on the upgraded packages.

I'll just leave the issue open for some time, maybe we can see why this happens.

**Comment by rmj-s** [comment]
You are right, I also searched the whole installer file before opening the issue but couldn't find it.

**Comment by ghost** [comment]
We'll continue to work on cleaning up the installer output, however due do this being caused by apt's behavior it may not be possible to fix this 100%. Closing this issue for now, thanks for your report.
