### ISSUE TITLE
Bug: Let's Encrypt SSL certificate renewal fails after modifying web domain aliases

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#856]
### In a few words, please describe the issue that you're experiencing:
Removing an alias in Web sections will result in failure of SSL certificate when result

### What steps did you take when the issue occured? 
- Create a domain add a alias
- Create a ssl certificate via LE
- Delete Alias
- And wait until renewal

### Expected behavior:
Alias removed from certificate

### Operating system distribution and release:
No OS related

### Which version of Hestia Control Panel is currently installed?
1.1.1 and up (Master / release)

### Which branch are you using?
Master and release

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Nginx + PHP-FPM
- Multi-PHP
- PHP-FPM + Multi-PHP
- Other (please specify)

### In order to better assist, please post any relevant log information below:
In line 56 till 61 the old certificate is used to determent the used aliases

https://github.com/hestiacp/hestiacp/blob/a16901ba082dc0a9634c7f6ca5032708f6b2f878/bin/v-update-letsencrypt-ssl#L56-L61

In case of a web domain we can match it against the web.conf record. How ever other solutions are required for the host/mail domains

**Comment by johnnyq** [comment]
I noticed the same thing where I deleted an alias on an LE enabled Site

**Comment by ghost** [comment]
Fixed, closing issue.
