### ISSUE TITLE
DNS Configuration

### ISSUE THREAD

**Issue by sebasira** [hestiacp/hestiacp#858]
I've got a question about DNS configuration. I'm using DigitalOcean and have installed Hestia. I would normally set up the DNS records for *domain.com* in DigitalOcean, but as my knowledge grow I think I should configure them in the Hestia panel.

Once I ask about LE certificate with wildcard which could not be validated because I was using external DNS. If I setup the DNS in the Hestia panel...

1- Will wildcard certificate validation succeed?
2- The **Use Lets Encrypt to obtain SSL certificate** option will request a Wildcard Certificate?

And finally if I use the DNS configuration in Hestia, could I leave the *ns1.digitailocean.com* on my domain delegation or should I change it to something like *ns1.domain.com* (the ones configured in the Hestia panel)

**Comment by Lupul** [comment]
Github isues are for bug reports, for general discussion about using Hestia we prefer to keep the discussion on our forum https://forum.hestiacp.com/
