### ISSUE TITLE
Security: Limit Apache behind reverse proxy to listen on loopback only

### ISSUE THREAD

**Issue by changeme** [hestiacp/hestiacp#859]
### Please fill in the relevant sections below and remove those which do not apply.

===

### In a few words, please describe the issue that you're experiencing:
Apache should listen on loopback and not on public IP

### What steps did you take when the issue occured? 
1. On server do `lsof -ni TCP:8443` or `lsof -ni TCP:8080`
2. run `nmap -p 8080,8443 $server_ip_or_fqdn`

### Expected behavior:
Ports should be closed to external IP

### Does this issue always occur, or is it intermittent?
Always

### Operating system distribution and release:
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

### Which version of Hestia Control Panel is currently installed?

```echo `grep VERSION $HESTIA/conf/hestia.conf`
VERSION='1.1.2'
```
But it happens too on 1.1.1

### Which branch are you using?

`master`

### When did this issue occur? After a clean installation, or after an upgrade?

Clean install with 1.1.1 version, then upgraded to 1.1.2 version.
Ports are open on both version

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### In order to better assist, please post any relevant log information below:

### Related issues or forum threads:

### Additional notes:

All files on `/etc/apache2/conf.d` with public IP address, should change to 127.0.0.1 and all files on `/etc/nginx/conf.d/domains` should change accordingly

**Comment by Lupul** [comment]
Although apache is listening on public ip, ports 8080 and 8443 are not accessible outside the server.

**Comment by Lupul** [comment]
I'm closing this issue now: can't reproduce and not a security problem
