### ISSUE TITLE
Feature Request: Custom port for v-add-database-host

### ISSUE THREAD

**Issue by jibon57** [hestiacp/hestiacp#860]
Thank you for this excellent software. I am coming from `vestacp`. This new control panel has really excellent extra features. In my control panel I am using external database but when I was trying to add using `v-add-database-host`, I didn’t find any option to add custom port. I needed to edit file manually. Will be helpful if you add this feature.

### Operating system distribution and release:
Ubuntu 18.04.4 LTS

Ref: https://forum.hestiacp.com/t/custom-port-for-v-add-database-host/1043/3

**Comment by ghost** [comment]
Merged into `staging/features` for inclusion with the next release.
