### ISSUE TITLE
Read only fields in dark theme looks the same as editable fields

### ISSUE THREAD

**Issue by theChaosCoder** [hestiacp/hestiacp#861]
The difference should be much clearer.

![image](https://user-images.githubusercontent.com/3579830/84576557-e4f26c80-adb5-11ea-90e3-7829d8f5a791.png)
VS 
![image](https://user-images.githubusercontent.com/3579830/84576566-f9cf0000-adb5-11ea-9d66-fbc7c85d419e.png)

**Comment by ScIT-Raphael** [comment]
Hi @theChaosCoder 

Thanks for pointing us to it, we'll rework that part a bit so it is more clear if the field is disabled. If you would like to push a idea on your own, please feel free to open a PR (http://github.com/hestiacp/hestiacp/pull).

**Comment by ScIT-Raphael** [comment]
Awesome, thanks @theChaosCoder! Going to close this issue now, please let us know if you find anything else.
