### ISSUE TITLE
Hestia not loading correctly

### ISSUE THREAD

**Issue by axisiscool** [hestiacp/hestiacp#863]
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

### What steps did you take when the issue occured? 
1. Installed Hestia
2. Started the Hestia Service
3. Logged In with my account details.
4. Issue Occurs

### Expected behavior:
The website showing up correctly

### Does this issue always occur, or is it intermittent?
Always Occur

### Operating system distribution and release:
Ubuntu 18.04 LTS

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
This issue occurred during a clean installation.

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx

### In order to better assist, please post any relevant log information below:
/var/log/hestia/error.log - 2020-06-16 22:38:22 v-list-user  'admin' [Error 3]
/var/log/hestia/auth.log - 2020-06-16 23:02:05 admin REDACTED successfully logged in

### Related issues or forum threads:
None

### Additional notes:
Just a simple install of Hestia produced this issue.

**Comment by axisiscool** [comment]
[Image with the issue](https://i.ibb.co/F35k50F/Screen-Shot-2020-06-16-at-5-04-42-PM.png)

**Comment by jaapmarcus** [comment]
Screenshot you supplied is from Vesta Cp? Not from Hestia.

Did you do a clean install?

**Comment by axisiscool** [comment]
Oh my I just realized that... funny thing is I did do a clean install.

**Comment by axisiscool** [comment]
This is the login screen though https://i.ibb.co/CnC3vJw/Screen-Shot-2020-06-16-at-5-52-44-PM.png

**Comment by axisiscool** [comment]
Oh sorry, just my cookies being weird :) Thanks for the help

**Comment by jaapmarcus** [comment]
Np, Was allready afraid of it. try to clean caches / cookies and probably it works...

**Comment by axisiscool** [comment]
Also on more thing, any reason why the save button doesnt work? I went on safari for a diff session.
