### ISSUE TITLE
[BUG] after changing the email password

### ISSUE THREAD

**Issue by MarioC-IRL** [hestiacp/hestiacp#864]
I wanted to report a bug that I could see when one of my users forget his password, he wants to change it from the panel so far no error but once done it seems that the email doesn't exist anymore and it's impossible to connect by rouncube or external mail service.

**Hestia Control Panel**
v1.1.1

**Operating System**
Ubuntu 18.04

**Comment by ioannidesalex** [comment]
Hi @Cnockaert-Mario ,

Issue is already known and will be resolved at the next release. In case you would like to apply a fix before the new version is release, please replicate the below:

https://github.com/hestiacp/hestiacp/commit/b4e9cb780fd933621fd9422ffbb33488c7285ab4#diff-1a6f37ebf95e3100f3fe56e9fdb2dab4

You can then rebuild your mail domain.

Thanks!
