### ISSUE TITLE
Error adding in DNS record with 'google-site-verification=xxxx' 

### ISSUE THREAD

**Issue by BorisDNK** [hestiacp/hestiacp#865]
When I adding DNS record with 'google-site-verification=xxxx'  I get error message "Error: invalid record format :: google-site-verification=xxxxx "

Steps:
1. Log into the Hestia Control Panel using Firefox
2. Click on the DNS tab
3. Click on Add DNS Record
4. Fill Record with google-site-verification=xxxxx
5. Fill Type with 'TXT'
6. Click Save

### Expected behavior:
DNS record added without error message

### Does this issue always occur, or is it intermittent?
allways

### Operating system distribution and release:
Ubuntu 18.04.4 LTS

### Which version of Hestia Control Panel is currently installed?
1.1.1

### Which branch are you using?
master

### When did this issue occur? After a clean installation, or after an upgrade?
clean

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

**Comment by ScIT-Raphael** [comment]
I'm not able to reproduce your issue, do you maybe add it with 'google-site-verification=xxx' instead google-site-verification=xxx?

![image](https://user-images.githubusercontent.com/13765400/85003364-664f5380-b156-11ea-9408-2d253105c762.png)

**Comment by BorisDNK** [comment]
Sorry guys. Your system much more smarter then me))
I put google-site-verification=xxxxx into 'record' field ))
Have a nice day
