### ISSUE TITLE
Feature Request: Use alternate document root (Park/Add-on Domains)

### ISSUE THREAD

**Issue by jibon57** [hestiacp/hestiacp#867]
Hello,

As we were discussing here: https://forum.hestiacp.com/t/ability-to-point-new-domain-on-existing/1079/

I think this is possible with cPanel. What I want is the ability to park/point another domain over existing one. For example: now if we want to create a domain it will create a separate directory example.com. So, if I would like to share the same code with other domain then I’ll require to create an alias of example.com but in my new domain example2.com has separate SSL certificate. I know this can be done by doing customized configuration file but will be helpful if can do automatically. So, what I want is to share other domain’s public_html with new one under same username.

Workaround: https://forum.hestiacp.com/t/ability-to-point-new-domain-on-existing/1079/3

**Comment by ghost** [comment]
Hi @jibon57,

Thanks for your feature request. 

We may consider this as a potential option for the web interface; one design I'd like to propose is a checkbox option in **Edit Web Domain** labelled something such as "**Use document root from another domain:**" with a drop-down list of available public_html directories from domains that are located under the same user account. Would this work for your use case?

Sample:
![image](https://user-images.githubusercontent.com/40798553/86543675-3f837200-bef7-11ea-9cbc-558912436eb4.png)

**Comment by jibon57** [comment]
Thanks for reply @kristankenney . Yes, that will be perfect! Just one question, will that create new directory under `web` folder with `public_html`?  Because it will be unnecessary here.

**Comment by ghost** [comment]
Hi again @jibon57,

We've implemented the backend for this with the command `v-change-web-domain-docroot`.

### Inputs:

`$user` = User name where domain you wish to change resides
`$domain` = Source domain which you want to change to a different document root
`$target_domain` = Target domain
`$target_directory`  = (Optional) Specify a directory inside of the target domain's **public_html** folder.

### Examples:

- `v-change-web-domain-docroot admin test.tld otherdomain.tld` = Sets test.tld to use **/home/admin/web/otherdomain.tld/public_html/** as its document root.
- `v-change-web-domain-docroot admin test.tld otherdomain.tld somefolder` = Sets test.tld to use **/home/admin/web/otherdomain.tld/public_html/somefolder/** as its document root.
- `v-change-web-domain-docroot admin test.tld test.tld somefolder` = Sets test.tld to use **/home/admin/web/test.tld/public_html/somefolder/** as its document root.
- `v-change-web-domain-docroot admin test.tld default` = Restores the default document root value for test.tld **(/home/admin/web/test.tld/public_html/**.

To answer your question as to whether the document root directory will be created, the command expects the value passed to `$target_directory` to exist under **/home/$user/web/$target_domain/public_html/** and will throw an error if it does not exist.

We're still working on implementing the Web UI for this functionality and I'll follow up when that has been completed along with a time frame for delivery to production.

**Comment by jibon57** [comment]
Thank you! Excellent job.

**Comment by ghost** [comment]
Hi @jibon57,

We'll be shipping this feature with next major update (v1.3).

**Comment by Barmunksu** [comment]
@kristankenney 
hello, i try to change docroot like [deployer.php](https://deployer.org/) structure
[https://hsto.org/files/ad3/5ac/e37/ad35ace374a644e6b5cf8e9f149d095b.png](https://hsto.org/files/ad3/5ac/e37/ad35ace374a644e6b5cf8e9f149d095b.png)

if i add
`/home/user/web/site.com/public_html/current`
hestiacp transform to
`/home/user/web/site.com/public_html/releases/2`

because 'current' folder is symlink dynamic release folder...

**Comment by tudorr89** [comment]
> @kristankenney
> hello, i try to change docroot like [deployer.php](https://deployer.org/) structure
> https://hsto.org/files/ad3/5ac/e37/ad35ace374a644e6b5cf8e9f149d095b.png
> 
> if i add
> `/home/user/web/site.com/public_html/current`
> hestiacp transform to
> `/home/user/web/site.com/public_html/releases/2`
> 
> because 'current' folder is symlink dynamic release folder...

You should just add a custom .tpl to adapt for deployer, changing docroot for symlinks doesn't work.
