### ISSUE TITLE
Dovecot/ssl-params 100% CPU only with HestiaCP installed

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#871]
### In a few words, please describe the issue that you're experiencing:
Installed HestiaCP on a Google Cloud VM. Clean install. Immediately dovecot uses 100% CPU. Deleted VM and created a new one but installed VestaCP. Dovecot works as expected.

### What steps did you take when the issue occured? 
Recreated VM and reinstalled several times.

### Expected behavior:
1% CPU usage???

### Does this issue always occur, or is it intermittent?
Everytime

### Operating system distribution and release:
Ubuntu 18.04 LTS

Please enter your answer here (e.g. 1.1.0)
1.1.1

### Which branch are you using?
VIA git command as per install instructions on hestiacp.com

### When did this issue occur? After a clean installation, or after an upgrade?
clean install

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP
-Spamassassin

I've tried disabling Spamassassin, installed without Spamassasin on one install... Same results.

**Comment by Lupul** [comment]
ssl-params is just an one time process, should finish in 5-10minutes after the first run

**Comment by ghost** [comment]
I let it run for 45 minutes and still at 100%... I just reinstalled without Exim, Dovecot or Spamassassin. Not usable with them installed.

**Comment by ScIT-Raphael** [comment]
If you dont need them, then is no need to have them installed :). Usualy, ssl params generation should be done as @Lupul wrote within a few minutes - but this depends on your system and its performance, so it also can take longer.

**Comment by ghost** [comment]
I actually would have preferred to have them there. I just spun up a second instance and installed mail in a box. As I said in my OP, installing VestaCP on a clean install, same specs, no issues. It seems to me, to be related to something with the install of Hestia but as Vesta isn't updated anymore I can't see using it.

**Comment by Pleskan** [comment]
@roxyschram You also can use pregenerated DHparam file in your case.
Just FYI :-)

**Comment by ScIT-Raphael** [comment]
@roxyschram The cpu usage is by design, this isnt a bug. To generate a dh param certificate, it takes some time and ressources but will increase the e-mail security over all.

**Comment by ghost** [comment]
I understand how all this works. But it only runs like this after Hestia install on a clean system. I installed Vesta to try and narrow down the cause and it run at 100% for 2 minutes. I used an identical instance for mail in a box and never saw over 80% and only for about 3-4 minutes. I don't see why Hestia is running for 45 minutes before I deleted the instance and reinstalled without them and created the second instance.

**Comment by ioannidesalex** [comment]
As far as I know Vesta doesn't generate a dh param certificate. As previously mentioned, it all depends to the CPU power.

**Comment by ScIT-Raphael** [comment]
Vesta doesnt generate a dh param certifciate, that's the reason you don't have that usage on a vesta based system.

**Comment by ghost** [comment]
I'll try it on a 4 core instance instead of 2 core next time...

**Comment by ScIT-Raphael** [comment]
CPU power isnt all, you also need to have entropy on your system - so it will be able to generate the key faster. You'll find some more informations here: https://www.linode.com/community/questions/18453/generating-a-diffie-hellman-4096-bit-key

**Comment by ghost** [comment]
24 is crazy. I copied over 2 backups from Vesta and restored them. About 2GB of restored data. I've never dug into Vesta so i wasn't aware it didn't generate the certificate. This had me thinking it was something specific to Hestia causing a conflict or hanging process. I'm going to try it on a bare metal tomorrow... if 64 cores takes an hour, I'll stick with mail in a box as a dedicated mail server not that I want to.

**Comment by ghost** [comment]
Just installed Hestia on a vultr instance and it went right through in 5 minutes. Maybe it’s to do with Google VMs. Not that it matters as I just learned google blocks port 25 which means I can migrate to them.
