### ISSUE TITLE
ubuntu 20 - master and 1.2.0-rc - can't install

### ISSUE THREAD

**Issue by working-name** [hestiacp/hestiacp#876]
### In a few words, please describe the issue that you're experiencing:
Trying to follow notice instructions for the beta `./hst_autocompile.sh --hestia no` but I get `Error: Branch invalid, could not detect version`. I cloned both master branch and 1.2.0-rc, both give the same message.

### What steps did you take when the issue occured? 
1. `git clone -b master $HGIT; cd hestiacp/src; ./hst_autocompile.sh --hestia no`
2. `git clone -b 1.2.0-rc $HGIT 1.2.0-rc; cd 1.2.0-rc/src; ./hst_autocompile.sh --hestia no`

### Expected behavior:
try to compile necessary packages

### Does this issue always occur, or is it intermittent?
always for me

### Operating system distribution and release:
Ubuntu 20.04 LTS

### Which version of Hestia Control Panel is currently installed?
none, clean 20.04 install

### Which branch are you using?
master and 1.2.0-rc

### Which of the following web server configurations are you using?
didn't get this far

### Related issues or forum threads:
#742

### Additional notes:
just trying to test hestia out

**Comment by Lupul** [comment]
try
./hst_autocompile.sh --hestia master no

**Comment by ScIT-Raphael** [comment]
As @Lupul already posted the right answer, I'm going to close the issue here. Olease oet us know, if you still got any other issue.

**Comment by working-name** [comment]
I read the header of the file and it suggests `./hst_autocompile.sh --hestia ~localsrc no`. The result is the same as using `--hestia master no`, the deb is created in /tmp.

Once you issue the install command the prompt to continue install shows 1.1.1 as opposed to 1.2.0. It then fails if you try to continue.

```
Updating currently installed packages, please wait...-
Now installing Hestia Control Panel and all required dependencies.
NOTE: This process may take 10 to 15 minutes to complete, please wait...
\
(*) Configuring system settings...
sed: can't read /etc/rssh.conf: No such file or directory
sed: can't read /etc/rssh.conf: No such file or directory
sed: can't read /etc/rssh.conf: No such file or directory
chmod: cannot access '/usr/bin/rssh': No such file or directory
(*) Configuring Hestia Control Panel...
cp: cannot stat '/usr/local/hestia/install/deb/sudo/admin': No such file or directory
chmod: cannot access '/etc/sudoers.d/admin': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/hestia': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/packages': No such file or directory
sed: can't read /usr/local/hestia/data/packages/*.pkg: No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/unassigned/index.html': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/templates/web/skel/document_errors/*': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/firewall': No such file or directory
(*) Generating default self-signed SSL certificate...
hst-install-ubuntu.sh: line 1080: /usr/local/hestia/bin/v-generate-ssl-cert: No such file or directory
(*) Adding SSL certificate to Hestia Control Panel...
sed: -e expression #1, char 3: unexpected `,'
sed: -e expression #1, char 1: unknown command: `,'
cp: cannot stat '/usr/local/hestia/install/deb/ssl/dhparam.pem': No such file or directory
(*) Configuring NGINX...
cp: cannot stat '/usr/local/hestia/install/deb/nginx/nginx.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/status.conf': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/phpmyadmin.inc': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/nginx/phppgadmin.inc': No such file or directory
cp: cannot stat '/usr/local/hestia/install/deb/logrotate/nginx': No such file or directory
sed: can't read /etc/nginx/nginx.conf: No such file or directory
sed: can't read /usr/local/hestia/nginx/conf/nginx.conf: No such file or directory
Failed to start nginx.service: Unit nginx.service not found.
Error: nginx start failed
```

**Comment by jaapmarcus** [comment]
You wil need to use 
https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install-ubuntu.sh

And then run
bash hst-install-ubuntu.sh --with-debs /tmp

Or follow https://forum.hestiacp.com/t/some-problems-with-1-2-0-rc-installation/1101/9?u=eris

**Comment by working-name** [comment]
I am already using both the master and 1.2.0-rc installation scripts. They both fail the same way.

Update: using eris' instructions on the forum just brings me back to the same prompt as before:
```
Would you like to continue with the installation? [Y/N]: y
Installation backup directory: /root/hst_install_backups/270620201320
Installation log file: /root/hst_install_backups/hst_install-270620201320.log

Adding required repositories to proceed with installation:

(*) NGINX
(*) PHP
(*) MariaDB
(*) Hestia Control Panel

Updating currently installed packages, please wait...\

Installation Aborted
====================================================================
Install script does not match Hestia release version
Please use the installer from the release branch

To test the beta version you need to build the hestia deb packages and re-run the installer
  ./hst_autocompile.sh --hestia no
  ./hst-install.sh .. --with-debs /tmp/hestiacp-src/debs
Error: Installation aborted
```
But at least the prompt to continue shows 1.2.0 as the version.

**Comment by working-name** [comment]
Just ran a diff on the two installation scripts from my git clone of the master branch (up to date, just pulled it minutes ago) and the [raw master branch URL](https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install-ubuntu.sh) and they're different. That is some weird crap.

**Comment by jaapmarcus** [comment]
Try to use bash hst-install-ubuntu.sh --with-debs /tmp/hestia-src if I can remember in thee folder should exists the pakages...

**Comment by working-name** [comment]
Yes the .deb exists in `/tmp/hestia-src/debs`, I also downloaded the deb as instructed by eris and pointed the installer to each location; no go. I must be doing something wrong because it doesn't make sense for the two files to be different. It's the same branch! 

Alright, reinstalling ubuntu and trying again.

**Comment by ScIT-Raphael** [comment]
Just reopened the issue, please hold us up to date, usualy it is not needed to git clone the whole project, it should work when you follow the steps @jaapmarcus wrote.

**Comment by working-name** [comment]
Okay, finally got it to install. [asciinema recording](https://asciinema.org/a/sva02R85IO0m3JqEFiGjCK6ZV)

What I was doing wrong is not feeding it a full path to the deb folder as the installer expects.

**Comment by ScIT-Raphael** [comment]
Awesome, thanks for your feedback!!
