### ISSUE TITLE
Refactor: Apache2 and nginx configuration file includes

### ISSUE THREAD

**Issue by beird** [hestiacp/hestiacp#878]
apache is picking any file from conf.d/ which can be pain when adding config backups and probably generating issues running the server

Modify from /etc/apache2/apache2.conf
`Include conf.d/`
to
`Include conf.d/*.conf`

**Comment by jaapmarcus** [comment]
See https://forum.hestiacp.com/t/server-security/1112/15

As this should change anything this has been tested and should work with out any issues.

Also the domain config is included with 

`IncludeOptional conf.d/domains/*.conf`

**Comment by jaapmarcus** [comment]
We should also consider this for Nginx however phpmyadmin/phppgadmin are using  inc instead of .conf...
