### ISSUE TITLE
File Manager not working

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#880]
### In a few words, please describe the issue that you're experiencing:
After Upgrading the Server from v1.1.1 to 1.2.0 i tried to use file manager

![image](https://user-images.githubusercontent.com/39749258/86034688-ba144380-ba58-11ea-8402-79ffae9f474f.png)

### What steps did you take when the issue occured? 
https://hostname:8083/fm/

### Expected behavior:
File Manager Should work after upgrading.

### Operating system:
Ubuntu 20.04 (x86_64)
Ubuntu 18.04 (x86_64)

### Hestia Control Panel version:
1.2.0

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ScIT-Raphael** [comment]
Hi

Can you please trigger bash $HESTIACP/install/deb/filemanager/install-fm.sh and check again? Sometimes the filemanager installation process fails, we currently try to gain more informations. Please let me know if you got any output, when it didnt worked.

**Comment by Lupul** [comment]
Can you confirm hestia-nginx was upgraded and restarted?
```
cat /usr/local/hestia/nginx/conf/nginx.conf | grep "fm"
systemctl restart hestia
```

**Comment by johnnyq** [comment]
I'm having the same issue on a new install of 1.2.0

Ubuntu 20.04 Proxmox LXC

It looks like the files that its looking for are in the wrong path for example the js folder is actually in dist/js

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/86035907-acf85400-ba5a-11ea-9c1b-ec8cd0472086.png)

i even reboot the server after upgrading it and it's not working

The command I used to upgrade. 
apt-get update && apt-get install --reinstall hestia

**Comment by ScIT-Raphael** [comment]
can you send a ls -ll $HESTIA/web/fm?

**Comment by Lupul** [comment]
Check nginx version: ( should be 1.17.10)
`apt show hestia-nginx`

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/86036736-f5644180-ba5b-11ea-9f9f-382f88385dd9.png)

**Comment by ScIT-Raphael** [comment]
Hmm, looks good, please check nginx  version @Lupul wrote.

**Comment by gytisrepecka** [comment]
In my case File Manager wasn't installed - mentioned folder doesn't exist. Even though upgrade attempted to install File Manager ( #882). Recent upgrade is messed up :(

**Comment by ScIT-Raphael** [comment]
We currently remove the 1.2.0 update from the repository to do further testing.

**Comment by ScIT-Raphael** [comment]
Ok, according to your screenshot, you don't have any fm part in your nginx configuration. Can you please check if you got the latest nginx verison installed? `apt show hestia-nginx`

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/86047816-1e410280-ba6d-11ea-9e78-7ca1f419ee95.png)

**Comment by imyller** [comment]
Having the same issue.

Looks like all compiled/distributable resources for Filegator filemanager are located in `/usr/local/hestia/web/fm/dist/` and that directory should be publicly served as `/fm/` and not the project root directory `/usr/local/hestia/web/fm`.

However, at least with the `hestia-nginx` package version `1.17.10` there are no special location config for `/fm/` URL specified in `/usr/local/hestia/nginx/conf/nginx.conf`.

**Comment by ScIT-Raphael** [comment]
Hi @imyller 

Can you share your os? We currently revoked the 1.2.0 update and are working on a fixed version

**Comment by imyller** [comment]
Also, due to security risks I would **not** recommend putting Filegator project files under publicly served folder at `/usr/local/hestia/web/fm` (`/usr/local/hestia/web` is root path for nginx port 8083). Instead placing or symlinking `/dist` to web root would be ok, but currently all file manager project resources can be downloaded.

**Comment by imyller** [comment]
@ScIT-Raphael 
I'm running HestiaCP with Ubuntu 20.04 LTS

**Comment by ScIT-Raphael** [comment]
@imyller was it a fresh or a upgraded installation?

**Comment by imyller** [comment]
@ScIT-Raphael 
Upgraded installation.

I've rerun hestia deb install scripts (`--reinstall`) and they succeed without error. Also `install-fm.sh` succeed with exitcode 0. However they seem to deliver this non-functional combination of filegator build and nginx-config where `/fm/` path is a "direct" link to filegator project root and its included `index.php` intended for development purposes (as stated in file comments).

**Comment by ScIT-Raphael** [comment]
Thanks for the detailed report @imyller, I'll need @Lupul to have a look here, he implemented the filemanager.

**Comment by imyller** [comment]
Whatever the solution, it should end up being the filegator's `/dist` being served as `/fm/` in Hestia :8083 and preferably other project files of filegator located outside webroot for security.

**Comment by ScIT-Raphael** [comment]
@imyller thanks for the feedback, I already noticed it when you wrote it above - we'll for sure check and validate it.

**Comment by Lupul** [comment]
Hestia nginx is serving the filemanager dist folder https://github.com/hestiacp/hestiacp/commit/4bcf26c34be227bd51d22e5e991f18d2508cbf3c

**Comment by imyller** [comment]
Looks like configuration file installation issue then. After `--reinstall` of both `hestia` and `hestia-nginx` packages (snippet from `/usr/local/hestia/nginx/conf/nginx.conf`):

```        location /rrd/ {
            expires off;
            internal;
        }

        location /backup/ {
            root /;
            internal;
        }

        location ~ \.php$ {
            include         /usr/local/hestia/nginx/conf/fastcgi_params;
            fastcgi_param   SCRIPT_FILENAME /usr/local/hestia/web/$fastcgi_script_name;
            fastcgi_param   QUERY_STRING    $query_string;
            fastcgi_pass    unix:/var/run/hestia-php.sock;
            fastcgi_intercept_errors on;
            break;
        }
    }
}
```

**Comment by ScIT-Raphael** [comment]
@imyller We currently try to find out why the nginx.conf file didnt got replaced properly - even when the file is part of the hestia-nginx package. Could you replace the conf file with that one here https://github.com/hestiacp/hestiacp/blob/master/src/deb/nginx/nginx.conf, restart the hestia service then check if the filemanager works properly?

**Comment by imyller** [comment]
@ScIT-Raphael 
Yes, that fixes filemanager in `/fm/`.

Just a suggestion: maybe you've listed that `nginx.conf` in `DEBIAN/conffiles` and as such it wont be replaced with deb upgrades?

**Comment by ScIT-Raphael** [comment]
@imyller thanks for testing and the hint, unlucky but we don't use conffiles for hestia-nginx - you'll find the used files here https://github.com/hestiacp/hestiacp/tree/master/src/deb/nginx and the deb generation script here https://github.com/hestiacp/hestiacp/blob/master/src/hst_autocompile.sh.

It just doesnt make much sense, the nginx.conf file got always properly replaced on my personal test systems :).

**Comment by ScIT-Raphael** [comment]
Wrong click on smartphone, sorry. We probaly found the issue, doing further investigation.

**Comment by imyller** [comment]
At least it is not registered as conffile by dpkg in my systems after `1.2.0` upgrade. Verified that with:

```
dpkg-query -W -f='${Conffiles}\n' | grep -i hestia
```

and 

```
debsums -ce | grep -i hestia
```

**Comment by ScIT-Raphael** [comment]
As already wrote, we've found the issue: During testing we added already a nginx build for focal to our repository, due to unknown issue that one didnt got replaced / we didnt got any notice that it exists. We've replaced now the focal package with the proper nginx.conf file.

@imyller could you do one last test and remove the fm part from the nginx configuration (or just adjust the file with a remark to check if it got overwritten) and reinstall the hestia-nginx package? -> apt update && apt --reinstall install hestia-nginx

**Comment by ScIT-Raphael** [comment]
I just manualy checked the hestia-nginx package for focal and can confirm, that the part for the fm configuration is properly in place now - so the issue is solved.

To be sure that you got the current version, you can just reinstall the package: `apt-get update && apt-get install --reinstall hestia-nginx`

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/86938238-d5b8d180-c15d-11ea-8119-be12fc1ad5f6.png)

After Updating to 1.2.0 from RC 1 on ubuntu 20 it's showing missing files

**Comment by alber-khan** [comment]
GET https://hostname:8083/fm/css/chunk-vendors.css?1589704837 net::ERR_ABORTED 404 (Not Found)
(index):10 GET https://hostname:8083/fm/css/app.css?1589704837 net::ERR_ABORTED 404 (Not Found)
(index):16 GET https://hostname:8083/fm/js/app.js?1589704837 net::ERR_ABORTED 404 (Not Found)
(index):17 GET https://hostname:8083/fm/js/chunk-vendors.js?1589704837 net::ERR_ABORTED 404 (Not Found)

**Comment by tudorr89** [comment]
Not sure if it helps, but sometimes, clearing the browser cache solves the issue. Also a server reboot might also help. At least that worked for me.

**Comment by ScIT-Raphael** [comment]
as @tudorr89 wrote, probaly caching issue, try in incognito mode please.

**Comment by tudorr89** [comment]
> GET https://hostname:8083/fm/css/chunk-vendors.css?1589704837 net::ERR_ABORTED 404 (Not Found)
> (index):10 GET https://hostname:8083/fm/css/app.css?1589704837 net::ERR_ABORTED 404 (Not Found)
> (index):16 GET https://hostname:8083/fm/js/app.js?1589704837 net::ERR_ABORTED 404 (Not Found)
> (index):17 GET https://hostname:8083/fm/js/chunk-vendors.js?1589704837 net::ERR_ABORTED 404 (Not Found)

also, you could retry v-add-sys-filemanager in cmd. that also could help 😄

**Comment by jaapmarcus** [comment]
Please follow https://docs.hestiacp.com/admin_docs/server_management.html#how-can-i-enable-disable-the-filemanager

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/86945229-73b09a00-c166-11ea-90bd-34c9eb0c705a.png)

already tired v-delete-sys-filemanager
 and v-add-sys-filemanager in cmd

and I can confirm those folder doesn't exist in /usr/local/hestia/web/fm

**Comment by jaapmarcus** [comment]
What is you hestia-nginx / Hestia-php version?

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/86948377-aceb0900-c16a-11ea-9aca-19242a7cef01.png)

**Comment by jaapmarcus** [comment]
Please try 
`apt update && apt install --reinstall hestia-nginx`

I think for some reason the nginx.conf is not changed...  Dit it work before the update to 1.2.0

**Comment by alber-khan** [comment]
already did that aswell

**Comment by ScIT-Raphael** [comment]
the only thing i can propose: move the fm folder to fm_old then run again v-add-sys-filemanager and check if it works

**Comment by jaapmarcus** [comment]
And maybe check the content of /usr/local/hestia/nginx/conf/nginx.conf 

It should have some where

`        location /fm/ {
            alias /usr/local/hestia/web/fm/dist/;
            index index.php;
        }`

**Comment by sonsofuttam** [comment]
One of site is on Hestia cp site is related [pikashow app](https://pikashows.world/) but I'm unable to reach the file manger to edit files it says 404 error page not found.

![Screenshot 2023-11-24 234736](https://github.com/hestiacp/hestiacp/assets/142832586/779decfc-b07b-4363-8ba4-dfb17056341a)

**Comment by jaapmarcus** [comment]
v-add-sys-filemanager 

Or check logs ...
