### ISSUE TITLE
mpm_event migration script is giving error. 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#886]
### In a few words, please describe the issue that you're experiencing:
getting an error while running a migration script

### What steps did you take when the issue occured? 

```
root@ca-s1:~# $HESTIA/install/upgrade/manual/migrate_mpm_event.sh
Module mpm_prefork disabled.
Enabling module mpm_event.
cp: cannot stat '/apache2/hestia-event.conf': No such file or directory
mpm_event module was successfully activated.
root@ca-s1:~#
```
![image](https://user-images.githubusercontent.com/39749258/86038644-db782e00-ba5e-11ea-8848-92db102ec4ce.png)

### Operating system:
Ubuntu 18.04

### Hestia Control Panel version:
1.2.0

**Comment by jaapmarcus** [comment]
`cp /usr/local/hestia/install/deb/apache2/hestia-event.conf /etc/apache2/conf.d/ `

will sort your issue

**Comment by alber-khan** [comment]
this is what I'm getting on webmail now.
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.
```

![image](https://user-images.githubusercontent.com/39749258/86039359-f13a2300-ba5f-11ea-88b6-d7d4b32d6233.png)

**Comment by ScIT-Raphael** [comment]
please check the error logs for any further informations

**Comment by alber-khan** [comment]
AH01079: failed to make connection to backend: 127.0.0.1

**Comment by alber-khan** [comment]
[Mon Jun 29 23:35:42.238230 2020] [proxy:error] [pid 20889:tid 139874829051648] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed

**Comment by jaapmarcus** [comment]
Are you running php-fpm?

**Comment by alber-khan** [comment]
- Apache + Nginx (default)
- Multi-PHP

**Comment by jaapmarcus** [comment]
Check if www.conf exists in /etc/php/7.3/fpm/pool.d

If not 

Copy https://github.com/hestiacp/hestiacp/blob/master/install/deb/php-fpm/www.conf

I the folder above :)

**Comment by alber-khan** [comment]
Yes indeed it's empty/by a different name

![image](https://user-images.githubusercontent.com/39749258/86041061-b685ba00-ba62-11ea-8976-b80a9dd914ed.png)

After I put the file there.

i run these commands
service apache2 restart
service php7.3-fpm restart
service php7.4-fpm restart

and #881 webmail issue was fixed

**Comment by neto737** [comment]
> Check if [www.conf](http://www.conf) exists in /etc/php/7.3/fpm/pool.d
> 
> If not
> 
> Copy https://github.com/hestiacp/hestiacp/blob/master/install/deb/php-fpm/www.conf
> 
> I the folder above :)

It fixed the problem. Thanks @jaapmarcus
