### ISSUE TITLE
hst-install-ubuntu.sh: line 833: curl: command not found

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#890]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When I do a new install of the latest 1.2 Hestia I get the following error this happened to me as well before the hestia 1.2 was pulled.

```
hst-install-ubuntu.sh: line 833: curl: command not found

Installation Aborted
```
The error is resolved if I do an apt install curl then rerun the script `bash hst-install-ubuntu.sh`

### What steps did you take when the issue occured? 
1. install latest 1.2 hestia

### Expected behavior:
should just install

### Operating system:
Ubuntu 20.04 LXC (Proxmox)

### Hestia Control Panel version:
1.2 

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ScIT-Raphael** [comment]
Curl will usualy be checked using the hst-install.sh script, if you install it directly over hst-install-OS.sh please be sure curl is also installed on your system (apt install curl).
