### ISSUE TITLE
v-add-sys-sftp-jail - No such file or directory 

### ISSUE THREAD

**Issue by vr0** [hestiacp/hestiacp#891]
### In a few words, please describe the issue that you're experiencing:
```
[root@dash]-[~]: cat /etc/cron.d/hestia-sftp
@reboot root /usr/local/hestia/bin/v-add-sys-sftp-jail
...
find: ‘/home/webuser_somename’: No such file or directory
chown: cannot access '/home/webuser_somename': No such file or directory

[root@dash]-[~]: cat /etc/ssh/sshd_config
...
# Hestia SFTP Chroot
Match User sftp_dummy99,admin,webuser,webuser_somename
ChrootDirectory %h
    X11Forwarding no
    AllowTCPForwarding no
    ForceCommand internal-sftp
..
[root@dash]-[~]: cat /etc/passwd
...
admin:x:1000:1000:admin@domain.tld:/home/admin:/usr/sbin/nologin
webuser:x:1001:1001:webuser@domain.tld:/home/webuser:/usr/sbin/nologin
webuser_somename:x:1001:1001::/home/webuser/web/somename.domain.tld:/usr/sbin/nologin
```

### What steps did you take when the issue occured? 
none

### Expected behavior:
No error.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.0 from apt.hestiacp.com (Before revert to 1.1.1)

### Additional notes:

Testing 

> Removing webuser_somename from sshd_config

Result 

> v-add-sys-sftp-jail auto readd webuser_somename to sshd_config

**Comment by ScIT-Raphael** [comment]
Is there any reason why you want to remove sftp-jail for this user?

**Comment by vr0** [comment]
No, just testing if  the "error" goes away.

**Comment by jaapmarcus** [comment]
Should be fixed
