### ISSUE TITLE
Feature request: Restricted shell with ability to run rsync and/or git (GNU Rush)

### ISSUE THREAD

**Issue by kpapad904** [hestiacp/hestiacp#894]
The ability to use rsync and/or git on the webserver can be very helpful to web professionals. HestiaCP offers rssh, which however is unmaintained and has been removed from the repos of Debian 10 and Ubuntu 20.04.

GNU Rush seems the best (only?) alternative to rssh and is still actively developed (although Debian/Ubuntu offer a rather outdated version): https://packages.debian.org/buster/rush

The project's homepage is: http://puszcza.gnu.org.ua/software/rush/

**Comment by jaapmarcus** [comment]
Available all-ready for all versions we support for Ubuntu and Debian

https://packages.debian.org/stretch/rush
https://packages.ubuntu.com/xenial/rush

Don't see any reason to no replace RSSH

**Comment by ScIT-Raphael** [comment]
Yes, would be a good thing to implement after the 1.2.0 release, we'll take it on the list.

**Comment by jlguerrerosanz** [comment]
Please add WP CLI to the list of commands

**Comment by darkworks** [comment]
Any update on this ? we are at 1.4 now

**Comment by ScIT-Raphael** [comment]
Currently not, no. We're limited with the available dev time ressources. If you have some time and knowledge to help expanding it, we're clearly open for it.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/4052

**Comment by jaapmarcus** [comment]
Fixed
