### ISSUE TITLE
Security improvement: Replace PHP crypt() with password_hash() and MD5 with a stronger hashing algo (like BCRYPT)

### ISSUE THREAD

**Issue by kpapad904** [hestiacp/hestiacp#895]
A Control Panel typically stores login credentials for hundreds or thousands of people; and we known that most people re-use the same credentials across services.

Currently HestiaCP is using MD5 password hashes (for Dovecot & Exim authentication, webserver .htpasswd files) except for the WebGUI itself which uses the Linux system's /etc/shadow file (SHA512). However, MD5 hashes (even salted) are considered weak and have been largely replaced with SHA512 and BCRYPT (in recent years also ARGON).

Based on a quick review of docs, it seems BCRYPT is supported by all recent versions of Dovecot and Apache. I've also checked and Apache htpasswd files support both MD5 and BCRYPT hashes in the same file. Apparently Nginx can also use BCRYPT, and Exim can authenticate via Dovecot (but this needs more checking).

https://doc.dovecot.org/configuration_manual/authentication/password_schemes/
https://www.exim.org/exim-html-current/doc/html/spec_html/ch-the_dovecot_authenticator.html

Finally, HestiaCP scripts call bin/v-generate-password-hash which uses the old PHP crypt() and a provided salt to generate the hashed passwords. Newer PHP versions 5.5+ offer password_hash() and generate the salt by default.

**Comment by kpapad904** [comment]
On second thought, we would need to check if changing the default hashing function from MD5 to something better like BCRYPT might break the ability to migrate / restore from other panels like cPanel and DirectAdmin ...

I'm looking at some cPanel / DirectAdmin -> VestaCP / HestiaCP import scripts:
https://github.com/Skamasle/sk-import-cpanel-backup-to-vestacp
https://github.com/Skamasle/sk_da_importer

**Comment by jaapmarcus** [comment]
That, and migrating older users to the new "secure" system could be pain full..

Old VestaCP users will also break partial..

**Comment by kpapad904** [comment]
@jaapmarcus Usually the software supports several hashing formats (e.g. MD5, SHA512 and BCRYPT) concurrently in the same passwd file. I know Apache and Dovecot can both do that.

E.g. here is a snippet from a htpasswd file, the first entry uses a custom Apache MD5 ($apr1$) and the second entry BCRYPT ($2y$):
```
test3:$apr1$EOGltEjv$gaDw0b8sKFDnTAeVpJkER0
test5:$2y$05$TSS77FOB5P6pvUKo9poqm.h4EIQHuDuk3nDJme1skhAprNfw9.cAy
```
See: https://httpd.apache.org/docs/2.4/misc/password_encryptions.html

Similarly with Dovecot (note: which uses BCRYPT $2y$ as its default hashing algo since years), you can create password hashes using the doveadm tool:
```
doveadm pw -s MD5 -p test
{MD5}$1$OJH0Vnug$EMvgpSk7.9gWwrjl9DKOq1
doveadm pw -s BLF-CRYPT -p test
{BLF-CRYPT}$2y$05$RTTOLpXNu94tQzuC6r61j.yAVTMCFVuUJbn9bhSR.VFYFIkXGz65q
doveadm pw -p test
{CRYPT}$2y$05$/3Q5PiXIVVW7hKyyaWwnTOUF4U8323KA0iGUEJYwz0HkXRdEmheUS
```
Here is how a passwd file currently looks on a HestiaCP v1.2.0 server:
```
root@vm05:/etc/exim4# more /etc/exim4/domains/testdomain.cctld/passwd 
testuser:{MD5}$1$VRzt9roe$pqMOPo/LytraBwNVGxVpR/:mytest:mail::/home/mytest::userdb_quota_rule=*:storage=0M
testuser2:{MD5}$1$UilMNjGi$dPhJMNrYsNtd/b9f7c8rx1:mytest:mail::/home/mytest::userdb_quota_rule=*:storage=0M
```
If I would manually add testuser3 with BCRYPT, then Dovecot/Exim would still work (needs testing):
```
testuser3:{BLF-CRYPT}$2y$05$RTTOLpXNu94tQzuC6r61j.yAVTMCFVuUJbn9bhSR.VFYFIkXGz65q:mytest:mail::/home/mytest::userdb_quota_rule=*:storage=0M
```
Anyway, if HestiaCP eventually replaces MD5 with BCRYPT then the migration for newly created users would be one way (i.e. after migration you wouldn't be able to go from HestiaCP back to VestaCP).

**Comment by kpapad904** [comment]
Upon further checking, it seems that even backwards compatibility can be achieved if HestaCP stores both the MD5 and BCRYPT hashes in its own config files (although that approach would defeat the purpose of improving security):
```
more /usr/local/hestia/data/users/mytest/mail/testdomain.cctld.conf
ACCOUNT='testuser' ALIAS='' AUTOREPLY='no' FWD='' FWD_ONLY='' MD5='{MD5}$1$VRzt9roe$pqMOPo/LytraBwNVGxVpR/' QUOTA='unlimited' U_DISK='0' SUSPENDED='no' TIME='01:34:24' DATE='2020-07-02'
ACCOUNT='testuser2' ALIAS='' AUTOREPLY='no' FWD='' FWD_ONLY='' MD5='{MD5}$1$UilMNjGi$dPhJMNrYsNtd/b9f7c8rx1' QUOTA='unlimited' U_DISK='0' SUSPENDED='yes' TIME='01:39:36' DATE='2020-07-02'
```

**Comment by ghost** [comment]
Hi @kpapad904,

Thanks for bringing this up; we've discussed this internally and while we agree that security is paramount, this change would introduce some challenges for us - handling backup archives from other systems, previous installations of Hestia, etc. At this time, we don't really have the available time to commit to reworking such a critical component, however we will see what happens in the future.

**Comment by kpapad904** [comment]
Hi @kristankenney , sorry to hear that ...

It seems to me that even if HestiaCP would replace MD5 with BCRYPT, that change would affect only newly created users. The migration script wouldn't need to re-create any existing password hashes (MD5), since all modern software understands MD5, SHA512, BCRYPT and ARGON and can use them simultaneously. But of course it would mean that change would be one way, i.e. after migrating to HestiaCP one wouldn't be able to go back to VestaCP.

PS: By the way, BCRYPT has been the default hashing algo for both Apache and Dovecot since years.

**Comment by divinity76** [comment]
fwiw it was changed to argon2id in PR https://github.com/hestiacp/hestiacp/pull/2421 , and there is currently a PR proposed to change it to bcrypt: https://github.com/hestiacp/hestiacp/pull/2752
