### ISSUE TITLE
[Bug] Reset 2FA Page not Working 

### ISSUE THREAD

**Issue by Prince-M** [hestiacp/hestiacp#896]
hello team,

I am facing an issue with HestiaCP v 1.2.0 RC.
OS - Ubuntu 20.04
H.CP. v - 1.2.0 RC

Issue - https://domain.ltd:8083/reset2fa ...
Show Error 404 Not Found.

**Comment by jaapmarcus** [comment]
OS independed
Hestia 1.2.0(RC)

Template is available how ever not the php code for checking it
https://github.com/hestiacp/hestiacp/blob/master/web/templates/reset2fa.html

**Comment by jaapmarcus** [comment]
Fixed

**Comment by Prince-M** [comment]
Page 404 Error cleared but No response on resetting Two-Factor Authentication.

**Comment by jaapmarcus** [comment]
When you enter the "Account recovery code" you should enter the code / username and submit then 

2FA Token has been reset with success. You are now able to login again 

And the token is cleared. Just checked working fine on local test server
