### ISSUE TITLE
Has anyone tested mod_pagespeed with hestiacp nginx/php-fpm and/or apache configs?

### ISSUE THREAD

**Issue by tudorr89** [hestiacp/hestiacp#898]
Hey guys, just a quick question around google pagespeed and their apache/nginx module.(https://www.modpagespeed.com/doc/) 

Has anyone tried to install and use it in any setup(nginx+php-fpm / apache+nginx)? 
Furthermore, have you noticed any improvements in terms of page loads or performance? 

I saw in their documentation that for apache you can install a package, while for nginx you have to build it froum source. Would this break any hestia related configs?

Thanks,
Tudor

**Comment by ioannidesalex** [comment]
Hi @tudorr89,

Building nginx from source means you would need to handle nginx updates manually on you own. I haven’t tested it with Hestia but my bet is that it will not work as intended out of the box.

Regarding whether pagespeed module is worth it - from a search online you will find out that it is debatable. I personally tested it and was not impressed, mainly because of the resources it needs. I just prefer to do performance tweaks on my own.

Just my humble, personal opinion.

**Comment by tudorr89** [comment]
Thanks for your input @ioannidesalex ! I'm really frustrated to see low scores on their pagespeed test page, although I did tweak most common things (deffer js/minify/combine js+css/lazyload/compression/etc) on the websites I host. I was just wondering how much of an impact would that module have if I was to install it. So I guess I'll just test it on a vanilla hestiacp install 😃

**Comment by ioannidesalex** [comment]
Well it depends whether you value benchmark or user experience the most :) for me it’s clearly the second!

Let us know how it goes when you test it.

**Comment by benzntech** [comment]
Please try the below link which is done for vestacp. Which can be used for hestiacp
[Rebuild Nginx with Google PageSpeed and http/2 for VestaCP](https://github.com/Prihod/vestacp_nginx_pagespeed_http2)

**Comment by ScIT-Raphael** [comment]
I dont think this will work for hestia, as it was written for vesta. So you probaly need to adjust a lot - our templates already support http2 so its basicly to build the custom nginx version as discussed above.

**Comment by gOOvER** [comment]
> Please try the below link which is done for vestacp. Which can be used for hestiacp [Rebuild Nginx with Google PageSpeed and http/2 for VestaCP](https://github.com/Prihod/vestacp_nginx_pagespeed_http2)

this link is now 5!!! Years old. Nginx support http2 per default. for apache install the module. and mod_pagespeed do not really speed up the page
