### ISSUE TITLE
Bug: phpMyAdmin reverted to 4.9.5 during upgrade from Ubuntu 18.04 to 20.04 LTS

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#904]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Upgraded to HestiaCP 1.2 on Ubuntu 18.04.4 LXC Proxmox no problems, then I  did an upgrade to ubuntu 20.04 using do-release-upgrade -d chose to not touch current configs which is the default. Rebooted everything awesome but the only thing i noticed was phpmyadmin reverted back to 4.9.5 instead of 5.0.2

### What steps did you take when the issue occured? 
upgrade ubuntu 20.04

### Expected behavior:
phpMyAdmin 5.0.2 to be installed

### Operating system:
Ubuntu 18.04.4 to Ubuntu 20.04 LXC Proxmox

### Hestia Control Panel version:
1.2.0

### Additional notes:

Other than this very very minor problem this has been a pretty solid upgrade!! Great Job Everyone!!!!

**Comment by ghost** [comment]
Hey @johnnyq, thanks for letting us know about this. This is likely due to the Ubuntu 20.04 upgrade replacing phpMyAdmin as we do a custom install; what happens if you run `apt install --reinstall hestia`? It should process the upgrade steps for PMA again and bring you back up to date.

**Comment by johnnyq** [comment]
@kristankenney 

Wow that was fast!! I can't keep up with you guys!!

I ran the command `apt install --reinstall hestia` below is the output, but its still keeping 4.9.5, i'm going to attempt to reboot then report back

`root@web01:~# apt install --reinstall hestia
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 2526 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://apt.hestiacp.com focal/main amd64 hestia amd64 1.2.0 [2526 kB]
Fetched 2526 kB in 1s (1961 kB/s)
(Reading database ... 49356 files and directories currently installed.)
Preparing to unpack .../hestia_1.2.0_amd64.deb ...
Unpacking hestia (1.2.0) over (1.2.0) ...
Setting up hestia (1.2.0) ...

                _   _           _   _        ____ ____                  
               | | | | ___  ___| |_(_) __ _ / ___|  _ \                 
               | |_| |/ _ \/ __| __| |/ _` | |   | |_) |                
               |  _  |  __/\__ \ |_| | (_| | |___|  __/                 
               |_| |_|\___||___/\__|_|\__,_|\____|_|                    
                                                                        
                  Hestia Control Panel Software Update                  
                            Version: 1.2.0                       
========================================================================

[ ! ] IMPORTANT INFORMATION:                                              

Default configuration files and templates may be modified or replaced   
during the upgrade process. You may restore these files from:           

Backup directory: /root/hst_backups/080720202003/                                       

This process may take a few minutes, please wait...                     

========================================================================

[ ! ] The latest version of Hestia Control Panel is already installed.
      Verifying configuration...

/usr/sbin/iptables
/usr/sbin/iptables-save
/usr/sbin/iptables-restore
[ * ] Updating Roundcube configuration...
[ * ] Updating exim4 configuration...
[ * ] Updating Apache2 configuration...
[ * ] Updating File Manager configuration...
[ * ] Updating NGINX configuration...
[ * ] Updating public_(s)html ownership...
[ * ] Updating phpMyAdmin permissions...
[ * ] Updating default PHP templates...
[ * ] Updating templates for PHP 5.6...
[ * ] Updating templates for PHP 7.3...
[ * ] Updating templates for PHP 7.4...
[ ! ] phpMyAdmin v5.0.2 is already installed, skipping update...
[ * ] Rebuilding domains and account for user: admin...
[ * ] Rebuilding domains and account for user: russ...
[ * ] Rebuilding domains and account for user: richfarms...
[ * ] Rebuilding domains and account for user: johnny...
[ * ] Restarting services...

========================================================================

Upgrade complete! If you encounter any issues or find a bug,            
please take a moment to report it to us on GitHub at the URL below:     
https://github.com/hestiacp/hestiacp/issues                             

We hope that you enjoy using this version of Hestia Control Panel,      
have a wonderful day!                                                   

Sincerely,                                                              
The Hestia Control Panel development team                               

Web:      https://www.hestiacp.com/                                     
Forum:    https://forum.hestiacp.com/                                   
GitHub:   https://github.com/hestiacp/hestiacp/                        
E-mail:   info@hestiacp.com                                             

Made with love & pride by the open-source community around the world.   


root@web01:~#`

**Comment by johnnyq** [comment]
I restarted the server, but still got the lingering phpMyAdmin 4.9.5

**Comment by ghost** [comment]
Run `rm /usr/share/phpmyadmin/RELEASE-DATE-5.0.2` followed by `apt install --reinstall hestia`.

**Comment by johnnyq** [comment]
that did the trick!! Thanks @kristankenney I'll continue testing and report. Should we leave this open for awhile just in case someone runs into a similar issue

**Comment by ghost** [comment]
We'll leave it open for now and I'll close it once we've re-worked how PMA is handled. Thanks again @johnnyq, much appreciated.

**Comment by johnnyq** [comment]
Fantastic!! We got a great team here at HestiaCP!

**Comment by jaapmarcus** [comment]
Same issue. So we need to spend time on it :)

**Comment by jaapmarcus** [comment]
Had the same issue ran
```
apt-get remove phpmyadmin
apt-get autoremove
```

Then 

```
root@cp:/usr/share/phpmyadmin# rm RELEASE-DATE-*
root@cp:/usr/share/phpmyadmin# apt install --reinstall hestia
```

Only had to clear the cache due to right issues and it worked fine maybe we should consider this.

**Comment by jaapmarcus** [comment]
We are planning to switch to OS Abstraction layer for a future release. With this release we will probably disconnect the use of ATP for PHPMyAdmin and just use the offical website/source code instead. This will fix the issue with downgrading by APT during server upgrade/update.

See https://github.com/hestiacp/hestiacp/blob/feature/osal/bin/module/phpmyadmin/install.inc

**Comment by jaapmarcus** [comment]
We will install phpmyadmin directly from source
