### ISSUE TITLE
Need to block .user.ini files in nginx configuration

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#905]
Now that you've moved apache to mpm_worker, .user.ini files are the way to alter PHP values on a per-domain/directory basis, rather than in .htaccess

These need to be blocked in the nginx config, same as .htaccess files .git files, and the like. eg.

location ~ /.us {return 404;}

**Comment by jaapmarcus** [comment]
Fixed in current beta release will be released net release.

See https://github.com/hestiacp/hestiacp/blob/beta/CHANGELOG.md
