### ISSUE TITLE
1.2.0 File Manager fails to install: Path outside of user homedir

### ISSUE THREAD

**Issue by drsdre** [hestiacp/hestiacp#906]
During upgrade to HestiaCP 1.2.0 installation of the file manager failed. This is nicely notified in the CP:

> Composer installation failed!
> The File Manager will not work without Composer.
> 
> Please try running the installer manually from a shell session:
> v-add-sys-filemanager
> 
> If this continues, open an issue report on  GitHub."

When running the installer manually in the CLI (_v-add-sys-filemanager_) as root, it fails with the message:

> Error: Path outside of user homedir (Composer bin)

Installed composer through apt (_apt install composer_), but the result stays the same.

### Operating system:
Ubuntu 18.04 LTS)

### Hestia Control Panel version:
1.2.0

### PHP version:
PHP 7.4.7 (cli) (built: Jun 12 2020 07:44:05) ( NTS )

### Composer version:
1.6.3 2018-01-31 16:28:17

**Comment by drsdre** [comment]
Looking a bit deeper into the code, it seems that running _v-add-user-composer_ has trouble finding the /home/admin/.composer directory which is not there:

```
+ COMPOSER_DIR=/home/admin/.composer
+ COMPOSER_BIN=/home/admin/.composer/composer
+ '[' -f /home/admin/.composer/composer ']'
++ readlink -f /home/admin/.composer
++ egrep '^/home/admin/'
+ '[' -z /home/admin/.composer ']'
++ readlink -f /home/admin/.composer/composer
++ egrep '^/home/admin/'
+ '[' -z '' ']'
+ check_result 10 'Path outside of user homedir (Composer bin)'
+ '[' 10 -ne 0 ']'
+ echo 'Error: Path outside of user homedir (Composer bin)'
Error: Path outside of user homedir (Composer bin)
+ '[' '!' -z '' ']'
+ log_event 10 ' '\''admin'\'''
+ '[' -z '' ']'
++ date '+%F %T'
++ basename /usr/local/hestia/bin/v-add-user-composer
+ LOG_TIME='2020-07-09 10:53:52 v-add-user-composer'
+ '[' 10 -eq 0 ']'
+ echo '2020-07-09 10:53:52 v-add-user-composer  '\''admin'\'' [Error 10]'
```

**Comment by jaapmarcus** [comment]
There is a known bug with switching when the there was a version skipped in the the install it only did the last step

So if you upgrade from 1.0.6 directly to 1.1.1 it skipped the "1.1.0" changes. 

There is a second issue in https://github.com/hestiacp/hestiacp/blob/main/bin/v-add-user-composer

Where the folder isn't created we will working on a fix for 1.2.0 

You can solve the issue to create the .composer folder

**Comment by jaapmarcus** [comment]
The permanent fix:

https://github.com/hestiacp/hestiacp/blob/2896c6b448461e67c695f7335ae70024749b1411/bin/v-add-user-composer#L49-L50

replace readlink -f with readlink -m 

Please confirm so I can push the changes

Also smart to rerun the 1.1.0 installer:

https://github.com/hestiacp/hestiacp/blob/main/install/upgrade/versions/previous/1.1.0.sh

**Comment by drsdre** [comment]
The change from readlink -f to readlink -m has indeed resolved the issue. File manager is now installed.

This server was installed with 1.1.1 end of May, it never ran 1.0.6.

Something else: I ran the script in bash debug mode and noticed that it was executing composer using PHP 7.3. Given that I just updated all users to use CLI PHP 7.4, that is a bit suprising. The relevant parts out of the logs are:

```
user_exec /usr/bin/php7.3 /home/admin/.composer/composer --quiet --no-dev install

setpriv --groups 1000 --reuid admin --regid admin -- /usr/bin/php7.3 /home/admin/.composer/composer --quiet --no-dev install
```

**Comment by jaapmarcus** [comment]
There is an "strange" issue when installing the file manger under 7.4.x. With 7.3.x the issue doesn't exsits as we didn't want the delay of the release 1.2.0 we decided to implement the current fix as a temporary solution. 

I will alter the code for v-add-user-composer

**Comment by ScIT-Raphael** [comment]
PHP7.3 is used due to compatibility issues of the composer with 7.4 - all right here.

**Comment by drsdre** [comment]
Clear. Thanks for the quick help gentleman!
