### ISSUE TITLE
Bug: PhpMyAdmin - Failed to load config.inc.php - config-db.php - Permission issue

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#909]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Upgraded to hestia 1.2 then upgrade ubuntu 20.04 from 18.04 after upgrade reinstalled hestia, phpmyadmin works but i'm getting permission issues loading phpmyadmin config files

Here is a log sample

`[Thu Jul 09 12:37:06.566271 2020] [proxy_fcgi:error] [pid 16305:tid 140458865493760] [client 209.166.184.226:34616] AH01071: Got error 'PHP message: phpmyadmin: Failed to load /var/lib/phpmyadmin/config.inc.php Check group www-data has read access and open_basedir restrictions.PHP message: phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.'`

### What steps did you take when the issue occured? 
1. install 1.2 hestia
2. upgrade to 20.04 from 18.04
3. access /phpmyadmin 

### Expected behavior:
PhpMyAdmin should have access to these files

### Operating system:
Ubuntu 20.04 LXC (Proxmox)

### Hestia Control Panel version:
1.2.0

### Additional notes:
I'm going to test a new install to see if the same thing is happening. will report back

**Comment by ghost** [comment]
Run `ls -la /var/lib/phpmyadmin/` and `ls -la /etc/phpmyadmin/` and send us the output please.

**Comment by johnnyq** [comment]
### /var/lib/phpmyadmin/
```
johnny@web01:~/web/simpnas.com/logs$ ls -la /var/lib/phpmyadmin/
total 16
drwxr-xr-x  3 root     root     4096 Jul  8 19:27 .
drwxr-xr-x 50 root     root     4096 Jul  8 19:34 ..
-rw-r--r--  1 root     www-data   68 Jun 26  2019 blowfish_secret.inc.php
drwxrwxrwx  3 www-data www-data 4096 Jun 26  2019 tmp
```
### /etc/phpmyadmin/

```
johnny@web01:~/web/simpnas.com/logs$ ls -la /etc/phpmyadmin
total 72
drwxr-xr-x   3 root root      4096 Jul  8 19:27 .
drwxr-xr-x 108 root root     12288 Jul  8 20:08 ..
-rw-r--r--   1 root root      1107 Jun 26  2019 apache.conf
-rw-r--r--   1 root root      1089 Mar 31 15:59 apache.conf.dpkg-dist
drwxr-xr-x   2 root root      4096 Jul 10  2017 conf.d
-rw-r-----   1 root www-data   527 Jun 26  2019 config-db.php
-rw-r--r--   1 root root       168 Jun 23  2016 config.footer.inc.php
-rw-r--r--   1 root root       168 Jun 23  2016 config.header.inc.php
-rw-r--r--   1 root root      4836 Jun 26  2019 config.inc.php
-rw-r--r--   1 root root      6172 Mar 31 15:59 config.inc.php.dpkg-dist
-rw-r-----   1 root www-data     8 Jun 26  2019 htpasswd.setup
-rw-r--r--   1 root root       273 Mar 31 15:59 lighttpd.conf
-rw-r--r--   1 root root       198 Jun 23  2016 phpmyadmin.desktop
-rw-r--r--   1 root root       295 Jun 23  2016 phpmyadmin.service
johnny@web01:~/web/simpnas.com/logs$
```

**Comment by jaapmarcus** [comment]
It wouldn't supprise me that the upgrade overwrote some settings

**Comment by johnnyq** [comment]
@jaapmarcus @kristankenney It looks like it affects new installs as well. I just did a new default install on ubuntu 20.04 and get the same error see below 

### New Install
### Log
```
cat bitpitt.com.error.log 
[Thu Jul 09 18:52:09.305196 2020] [proxy_fcgi:error] [pid 7931:tid 139904482776832] [client x.x.x.x:0] AH01071: Got error 'PHP message: phpmyadmin: Failed to load /var/lib/phpmyadmin/config.inc.php Check group www-data has read access and open_basedir restrictions.PHP message: phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.'
```
### /var/lib/phpmyadmin/
```
johnny@web01:~/web/bitpitt.com/logs$ ls -la /var/lib/phpmyadmin/
total 16
drwxr-xr-x  3 root     root     4096 Jul  9 17:03 .
drwxr-xr-x 47 root     root     4096 Jul  9 17:03 ..
-rw-r--r--  1 root     www-data   68 Jul  9 17:03 blowfish_secret.inc.php
drwxrwxrwx  3 www-data www-data 4096 Jul  9 18:52 tmp
johnny@web01:~/web/bitpitt.com/logs$ 
```

#### /etc/phpmyadmin
```
johnny@web01:~/web/bitpitt.com/logs$ ls -la /etc/phpmyadmin/
total 48
drwxr-xr-x   3 root root     4096 Jul  9 17:05 .
drwxr-xr-x 103 root root     4096 Jul  9 17:39 ..
-rw-r--r--   1 root root     1108 Jul  9 17:04 apache.conf
drwxr-xr-x   2 root root     4096 Mar 31 19:59 conf.d
-rw-r-----   1 root www-data  527 Jul  9 17:03 config-db.php
-rw-r--r--   1 root root      168 Mar 31 19:59 config.footer.inc.php
-rw-r--r--   1 root root      168 Mar 31 19:59 config.header.inc.php
-rw-r--r--   1 root root     4836 Jul  9 17:05 config.inc.php
-rw-r--r--   1 root root      273 Mar 31 19:59 lighttpd.conf
-rw-r--r--   1 root root      198 Mar 31 19:59 phpmyadmin.desktop
-rw-r--r--   1 root root      295 Mar 31 19:59 phpmyadmin.service
```

**Comment by ghost** [comment]
Thanks @johnnyq, we'll investigate.

**Comment by ioannidesalex** [comment]
From what I see based on your "ls",  /var/lib/phpmyadmin/config.inc.php doesn't exist at all - it doesn't have to do with permissions.

Regarding /etc/phpmyadmin/config-db.php - the permissions appear to be correct.

Can you please try and create an empty file /var/lib/phpmyadmin/config.inc.php ? Also please let us know what version of phpMyAdmin is installed. Are you using Apache standalone? or with Nginx?

**Comment by johnnyq** [comment]
hello @ioannidesalex 

Yur right the file doesnt exist. I created the file

```
root@web01:/var/lib/phpmyadmin# touch config.inc.php
root@web01:/var/lib/phpmyadmin# ls -la
total 16
drwxr-xr-x  3 root     root     4096 Jul 24 17:05 .
drwxr-xr-x 50 root     root     4096 Jul  8 19:34 ..
-rw-r--r--  1 root     www-data   68 Jun 26  2019 blowfish_secret.inc.php
-rw-r--r--  1 root     root        0 Jul 24 17:05 config.inc.php
drwxrwxrwx  3 www-data www-data 4096 Jun 26  2019 tmp

```

The version of phpMyAdmin is 5.0.2

I'm using Apache with NGINX Default Install. Its also a Proxmox Ubuntu 20.04 LXC Template

**Comment by ioannidesalex** [comment]
What are the erors now @johnnyq ?

**Comment by johnnyq** [comment]
Hi @ioannidesalex 

there is a new error when I access the phpmyadmin

`[Sat Jul 25 10:57:12.847219 2020] [proxy_fcgi:error] [pid 33520:tid 140080188626688] [client 209.166.184.226:50666] AH01071: Got error 'PHP message: phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.'`

**Comment by johnnyq** [comment]
also it appear I get this error at the bottom when I log into phpmyadmin

![image](https://user-images.githubusercontent.com/1812594/88459846-38041880-ce66-11ea-8389-6bc33e8dd041.png)

although all phpmyadmin functions still work

**Comment by jaapmarcus** [comment]
The file got created with apt updates for Debian/Ubuntu 

The issue is that need chmod 644 for /etc/phpmyadmin/config-db.php

And it has currently 640 solutions is chmod 644 to that file but not "preferred" as then every user has access to it.

2nd would be running phpmyadmin on the host only user www-data and use our own install and not depend on  apt-get

**Comment by johnnyq** [comment]
@jaapmarcus chmod 644 worked and cleared the error, but your right this leaves it open for anyone to view the contents of the file. Is there any other solution to fixing the issue.

**Comment by jaapmarcus** [comment]
Fixed we have made multiple changes to phpmyadmin
