### ISSUE TITLE
Missing location @rewrite in drupal7,8 templates

### ISSUE THREAD

**Issue by stasionok** [hestiacp/hestiacp#916]
Please fix templates 
\install\deb\templates\web\nginx\php-fpm\drupal7.stpl
\install\deb\templates\web\nginx\php-fpm\drupal7.tpl
\install\deb\templates\web\nginx\php-fpm\drupal8.stpl
\install\deb\templates\web\nginx\php-fpm\drupal8.tpl
They are refer to @rewrite but it missing. Need add
```
location @rewrite {
        rewrite ^/(.*)$ /index.php?q=$1;
}
```

**Comment by ioannidesalex** [comment]
Hi @stasionok thanks for your feedback.

Made a few other amendments to enhance security mostly, can you please have a look at the branch below and let us know if thats ok?

They do work for me.

https://github.com/hestiacp/hestiacp/tree/fix/916_drupal-templates

**Comment by stasionok** [comment]
A lot of changes. I see my issue was fixed, but can`t check it all cause do not know how (and where, only live servers) to setup and check

**Comment by ioannidesalex** [comment]
Ok if your issue is fixed we are good. Patch will be included in next version.

I will close this issue, let us know if you have any further issues.
