### ISSUE TITLE
New backup not creating after running this v-schedule-user-backup-download

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#918]
### In a few words, please describe the issue that you're experiencing:
when trying to create a new backup it's just saying "An existing backup is already running. Please wait for that backup to finish." 
but it's not running the v-schedule-user-backup

![image](https://user-images.githubusercontent.com/39749258/87228650-419a7480-c3c0-11ea-8de5-abebce20bcb7.png)

### What steps did you take when the issue occurred? 
i tried to download the backup first but the backup was deleted from /backup so I think it triggered "v-schedule-user-backup-download"
![image](https://user-images.githubusercontent.com/39749258/87228453-02b7ef00-c3bf-11ea-8872-fd13cdf3ce70.png)

![image](https://user-images.githubusercontent.com/39749258/87228413-b8367280-c3be-11ea-87b2-c5fb55bff702.png)

and after that when i try to create a new backup it's not working!

### Expected behavior:
Should create a new backup 

### Operating system:
Ubuntu 18.04 and 20.04 

### Hestia Control Panel version:
1.2.0

**Comment by alber-khan** [comment]
https://docs.hestiacp.com/cli_commands/panel_configuration_commands.html#v-schedule-user-backup

also i can't find "v-schedule-user-backup-download" function in panel configuration commands documentation.

**Comment by jaapmarcus** [comment]
v-schedule-user-backup-download is used to Schedule the download task for a back up from an external location (SFTP, FTP) 
See https://github.com/hestiacp/hestiacp/blob/main/bin/v-schedule-user-backup-download

And trigged when click on the download button.

When you want to create a backup use the "Create backup" button and wait approx 5 to 10 min (Or even more depending on file size)

Backups are handled on a interval basis that has been set in the Admin user cronjob

**Comment by alber-khan** [comment]
**"v-schedule-user-backup-download is used to Schedule the download task for a back up from an external location (SFTP, FTP)"**
I haven't put the external FTP/SFTP details. 
![image](https://user-images.githubusercontent.com/39749258/87232243-00fc2480-c3db-11ea-9639-0f90e0fb1e03.png)

**"Backups are handled on an interval basis that has been set in the Admin user cronjob"**
I've set the cronjob to every minute 
![image](https://user-images.githubusercontent.com/39749258/87232262-1e30f300-c3db-11ea-919c-ba8821422bf9.png)

**When you want to create a backup use the "Create backup" button and wait approx 5 to 10 min (Or even more depending on file size)**
that's the issue it doesn't create the backup if "v-schedule-user-backup-download" is trigged.

**Comment by jaapmarcus** [comment]
You are right when the backup download fails the queue isn't cleared

See should fix it
https://github.com/hestiacp/hestiacp/pull/921/commits/de0d3700bf865d63ef755563149af4c4c88e206b

**Comment by jaapmarcus** [comment]
fixed

**Comment by ScIT-Raphael** [comment]
Just reviewed and merged the related code part - we will ship it with the next release (1.2.1). If you already want to fix it on your system, please patch the file according to the commit above.
