### ISSUE TITLE
File Manager unzip is slow and potential issue with permissions

### ISSUE THREAD

**Issue by beird** [hestiacp/hestiacp#925]
When decompressing zip files with FM

- it is very slow (compared with unzip file.zip on command line)
- I think as well it blocks whole Hestiacp panel when is decompressing (could not open other browser tab with the panel)
- after I decompressed joomla I needed to re-do the permissions. I found easy to use the command line unzip all was working properly after that oppose using FM unzip.

**Comment by jaapmarcus** [comment]
Also creating folders with chmod drwxr--r-- instead drwxr-xr-x causing .htaccess not accessible.

**Comment by jaapmarcus** [comment]
For creating folders:
`[Mon Jul 13 12:47:08.904962 2020] [core:crit] [pid 31949:tid 140226291853056] (13)Permission denied: [client ip:0] AH00529: /home/eris/web/domain.tld/public_html/test/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/eris/web/domain.tld/public_html/test/' is executable`

**Comment by ghost** [comment]
To note on the second point: this is likely because File Gator is handled by the backend hestia-nginx/hestia-php processes, so if the operation is blocking or the load is high enough during an unzip operation then that would explain the panel stalling out. 

Can you please run `top` and see what your CPU usage goes up to when unzipping a file in the File Manager?

**Comment by jaapmarcus** [comment]
With top

`14113 admin     20   0   99608  31804   9564 R  98.0   3.1   0:14.71 hestia-php  `

**Comment by Lupul** [comment]
blocking is probably due to php session locking

**Comment by jaapmarcus** [comment]
Permissions issue should be fixed with https://github.com/hestiacp/hestiacp/pull/1102

**Comment by jlguerrerosanz** [comment]
I tried to unzip a 3GB file. It took forever. When Hestia finally came around, the file was not unzipped.

**Comment by ScIT-Raphael** [comment]
We can't improve the unpack performance of the filegator filemanager due to the fact how the combination works (sftp and hestia backend). I would suggest to use cli for handling big files, currently this is the best way to go.
