### ISSUE TITLE
Hestia 1.2.0 upgrade File Manager not installed properly 

### ISSUE THREAD

**Issue by TikiGuat** [hestiacp/hestiacp#929]
### In a few words, please describe the issue that you're experiencing:
Upgraded Hestia to 1.2.0, error File Manager not installed. 

[ ! ] Installing File Manager...
Error: Path outside of user homedir (Composer bin)

### What steps did you take when the issue occured? 
Also tried 
 v-add-sys-filemanager
Error: Path outside of user homedir (Composer bin)

### Operating system:
Debian 9.12

### Hestia Control Panel version:
Hestia 1.2.0

**Comment by jaapmarcus** [comment]
Please read:
https://github.com/hestiacp/hestiacp/issues/906

May I ask if you accidentally skipped a version? (for example 1.06 straight to 1.1.1?)

**Comment by TikiGuat** [comment]
No I was on the most current production version before upgrading. (The only thing not standard about my system prior to upgrade is that I use Roundcube 1.4.6)

**Comment by TikiGuat** [comment]
I manually added the .composer directory 

/home/admin/.composer

v-add-sys-filemanager
File Manager is now installed and ready for use.

However when I click on the Files icon to launch, filemanager loads correctly and then gives a "Unknown Error" in red oval box. No files are shown. 

Rebooted server, same problem. Also added the .composer directory to another user. Ran v-add-user-composer "username" and it sets up fine. But same Unknown Error problem.

**Comment by jaapmarcus** [comment]
Are you able login with Sftp?

`sftp -P 22 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1`

**Comment by TikiGuat** [comment]
I can use WinSCP to get into my server fine. Is that what your asking?

If I try the command you provided at the command prompt I get the following error but that seems normal since I use keys.

root@vcp:/home/admin# sftp -P 22 -i /home/admin/.ssh/hst-filemanager-key admin@127.0.0.1
Warning: Identity file /home/admin/.ssh/hst-filemanager-key not accessible: No such file or directory.
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:qynJL4kIdGkZyrXHP(rest hidden for forum post).
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
Enter passphrase for key '/root/.ssh/id_ecdsa':
Permission denied (publickey).
Couldn't read packet: Connection reset by peer

Edit: Oh, so the system generates it own SSH key to use for the filemanager? And then does a local loopback ssh session. Is that how the file manager actually works?

**Comment by jaapmarcus** [comment]
Key file is missing. Check if folder .ssh exists probably not and create it and then try again

**Comment by TikiGuat** [comment]
Okay that fixed the issue and now the admin account file manager seems to be working! 

Noticed that my primary user account still has the "unknown error", so I added the .ssh directory to that username but it still seems to be not working. Suggestions?

**Comment by Lupul** [comment]
`sftp -P 22 -i /home/primary_user_account/.ssh/hst-filemanager-key primary_user_account@127.0.0.1`

**Comment by TikiGuat** [comment]
My Result:

sftp -P 22 -i /home/MOJO/.ssh/hst-filemanager-key MOJO@127.0.0.1
Permission denied (publickey).
Couldn't read packet: Connection reset by peer

**Comment by Lupul** [comment]
Does this file exist  `/home/MOJO/.ssh/hst-filemanager-key`? it is suposed to be created when you access the file manager from Web-UI.
You can create it manually with:
`v-add-user-sftp-key MOJO 30` and

**Comment by jaapmarcus** [comment]
Did you modify by accident the /etc/ssh/sshd_config? And limit access to certain users?

Who is the owner of the ssh key? admin:admin

**Comment by TikiGuat** [comment]
The only modification to my ssh config is 
ChallengeResponseAuthentication No
Use Pam No
Edit: Also PasswordAuthentication No

The owner of the hst-filemanager-key
for my primary user and admin are both:
admin:admin

**Comment by vestacp-user** [comment]
I have been able to reproduce this problem with a fresh install on Debian 10 Buster and Hestia 1.2.0.  

Short answer: 
add `Subsystem sftp internal-sftp` to `/etc/ssh/sshd_config`:

Long answer: 
Refer to the install script `./install/hst-install-debian.sh` for all the changes made to `/etc/ssh/sshd_config`.   For Debian, the changes can be summarized as follows:

```
# HestiaCP Changes to the default /etc/ssh/sshd_config in Debian 10 Buster 

# Forced default yes
PasswordAuthentication yes

# Changed from default 2m to 1m
LoginGraceTime 1m 

# Changed from default /usr/lib/openssh/sftp-server to internal-sftp
Subsystem sftp internal-sftp

# Changed from default yes
DebianBanner no
```

Returning all of the other parameters to their defaults and also changing to `PasswordAuthentication no` did not reproduce the error, thus it would seem to be isolated to the `Subsystem sftp internal-sftp` parameter.

**Comment by TikiGuat** [comment]
Upgraded today to Hestia 1.2.1 and my issue is now resolved My admin and primary user can both access the file manager.

Something in the update fixed it.
