### ISSUE TITLE
Some elements of the GUI remain untranslated

### ISSUE THREAD

**Issue by Wibol** [hestiacp/hestiacp#930]
Some elements of the GUI remain untranslated because their translation string does not exist or are not used in en.php or es.php languages files:

Missing strings:
'Forwarding' (in column title) > https://host.domain.tld:8083/list/mail/?domain=domain.tld
'%s backups' (in footer) > https://host.domain.tld:8083/list/backup/
'%s firewall rules' (in footer) > https://host.domain.tld:8083/list/firewall/
'%s banned IP addresses' (in footer) > https://host.domain.tld:8083/list/firewall/banlist/

Unused tags:
'Cron Job' (in left column title) > https://host.domain.tld:8083/list/cron/
'Host' (in Databases, third form text box title) > https://host.domain.tld:8083/edit/server/
'Host' (in Backups, Remote backup, second form text box title) > https://host.domain.tld:8083/edit/server/

The same translation string (‘Records’) is used in the top navigation menu and the DNS section, which makes the work complicated at least in Spanish. Different translation strings should be used for those items. The Records tab links to user accounts list in admin session and to web domains list in user session, so I think a more generic name should be used like: Management, Administration, Index or Home.

My Hetzner VPS is running HesiaCp v1.2.0 recently upgraded on Debian 9.

**Comment by ghost** [comment]
Hi @Wibol, thanks for reporting your findings. We'll add the missing strings to en.php with initial translations to other languages which can then be updated as necessary, if you find any more strings which need to be adjusted please let us know.

**Comment by jaapmarcus** [comment]
Added the following strings:

https://github.com/hestiacp/hestiacp/commit/aa30f5a590fa9045c33e67abcfe5d2570b493c1e#diff-cbc962e9856c73ab5a83d22a0134cbd0

Feel free to improve my Google translate Spanish.

**Comment by jlguerrerosanz** [comment]
I just commented my translation. If you need more help, let me know

**Comment by ScIT-Raphael** [comment]
@jlguerrerosanz uos, posted it under the wrong thread, but still the same: https://github.com/hestiacp/hestiacp/issues/1354#issuecomment-744128815

Language handling has been reworked :).
