### ISSUE TITLE
Translation bug with Bulgarian Lang

### ISSUE THREAD

**Issue by Indjov** [hestiacp/hestiacp#932]
That what i see when change my language from EN to BG is that the Icon in USERS menu move under the "USERS".
![Screenshot_1](https://user-images.githubusercontent.com/5468168/87385516-e8d90080-c5a6-11ea-9636-c607a5f9ca07.png)
![Screenshot_2](https://user-images.githubusercontent.com/5468168/87385528-f0000e80-c5a6-11ea-8cc0-ca8c87ef9cfc.png)

**Comment by ghost** [comment]
Hi @Indjov, thanks for your issue report. I'll take a look and follow up soon. :)

**Comment by ghost** [comment]
I've made some adjustments with the font size to bring the translated strings in line, does this look okay for you?

![image](https://user-images.githubusercontent.com/40798553/87388681-a51cd180-c57b-11ea-95ed-776d4a914ec2.png)

**Comment by Indjov** [comment]
@kristankenney looks perfect!

if i want to make changes to the language, what are the requirements for translation and their corresponding approval

**Comment by jaapmarcus** [comment]
Please check https://github.com/hestiacp/hestiacp/blob/main/web/inc/i18n/en.php as this file acts currently as "master".   You can clone HestiaCP and and make your changes. Push your changes to Github and create a pull request. 

Main translations are mainly "Google translate". Prefer to keep this as little as possible. When completed we will check them as much as we can do. However all the support is really needed.
