### ISSUE TITLE
Visual Bug - Notification Bell is yellow with no notifications

### ISSUE THREAD

**Issue by cmstew** [hestiacp/hestiacp#935]
### In a few words, please describe the issue that you're experiencing:
Logged into a client account via the admin account and the notification bell was lit up but there were no notifications. The issue is present on most user accounts but I noticed there were a few that it wasn't present on as well.

### What steps did you take when the issue occured? 
1. Login as Admin
2. Login as user through admin
3. Notification bell is yellow but there's no notifications

### Expected behavior:
The bell to not be yellow if there's no notifications.

### Operating system:
Ubuntu 18.04

### Hestia Control Panel version:
1.2.0

![image](https://user-images.githubusercontent.com/8193597/87478972-e4810780-c5e7-11ea-9592-20420f59d857.png)

**Comment by ghost** [comment]
Unable to reproduce issue, closing.
