### ISSUE TITLE
Discussion - Disable vsftpd by default for new installations?

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#936]
While configuring my server I ended up doing research on major FTP clients. Most of the popular ones support SFTP already as they are multi-protocol clients. Most of what the FTP server is used for in Hestia is already doable over SFTP. The rest can be handled by HTTP or HTTPS for anonymous downloads. Given that the FTP server is largely redundant due to other parts doing most of what it does already, does it still make sense to enable an FTP server by default?

**Comment by jaapmarcus** [comment]
Disagree Additional FTP accounts are still limited to FTP only due to issues with the sftp jail.

So if this was solved I agree (and I have disabled FTP for my servers) to disable it on default

**Comment by ghost** [comment]
@jaapmarcus

What do you mean by additional FTP accounts? It seemed that at least with the default vsftpd that it was limited to system user accounts which would normally just be the users created by hestia. Are you referring to users not managed by hestia?

Can you elaborate on the SFTP jail issues? It seemed to work fine in my tests.

**Comment by jaapmarcus** [comment]
See https://cp.domain.nu:8083/edit/web/?domain=domain.nu and then at the bottom you have a check box with text.

Additional FTP account(s) you assign this a folder. 

I have looked Into in the past and this was the only major issue left...

**Comment by ghost** [comment]
Oh, so the SFTP jail issue is that you can't create additional virtual accounts for it?

**Comment by ghost** [comment]
Under the current structure that is correct.

FTP as we all know is insecure and SFTP should **_always_** be used unless there is absolutely no other option. Any sane application in today's age should support SFTP.

Therefore I believe the best course of action here is to fix the issue with additional accounts not working under SFTP and disable vsftpd for all new installations.

**Comment by ghost** [comment]
Ok, I've found why it doesn't work and what it requires to fix it. The SFTP jail requires all directories in the user's home directory chain to be owned by root. This works for normal users because their home directory is already owned by root. Hestia makes this still usable by using ACLs to allow the regular user to still use it normally.

Now how can this be applied to FTP accounts? I'm not sure honestly. There's no way to disable the check that the sshd performs. The manual for the configuration file says as much. And it would still need to allow the regular user full access as well. And to any directories they in turn create. I think more research is needed into the check that sshd is performing.

**Comment by ghost** [comment]
I dug through the source code of openssh and read the C code. The actual checks for permissions check that each directory component is owned by root user (though it doesn't check the group) and that the mode has the write permissions for group and other turned off. So there's no way to give write permissions to non-root users aside from ACL.

**Comment by ghost** [comment]
To start we could make it that when the ~/web directory is created it must be mode 0755 and owned by root:root. This directory would also need to have its default ACL set to user:$USER:rwx to ensure that the main user retains full privileges to any new directories that are created. This works by ACL inheritance. This should be sufficient for the foundation work. The remaining issues is related to ownership of sub-directories since most of those will be created by the user and they can't be predicted or hooked into normally. How can the rest be made transparent? Or does this only matter when the auxiliary accounts are created, deleted, or modified?

**Comment by ghost** [comment]
I think we could get away with just changing the owner/group of each component of the chroot path and removing the write permissions. The rest would be taken care of by the default ACL via inheritance so that regular user permissions are not impacted.

**Comment by ghost** [comment]
I'll see what I can come up with.

**Comment by jaapmarcus** [comment]
Go ahead. How ever I am not fan of changing the owner of any folder in web to root:root as this will break apache2 / php-fpm.

**Comment by ghost** [comment]
Well so far it's seemingly impossible for other reasons. Anytime I change the group or other permissions the ACL mask gets reset and vice-versa. So far no luck trying to find a way to both satisfy sshd and provide write access to SFTP.

**Comment by ghost** [comment]
Ok, after reading about how ACLs actually work in depth, I've concluded there's no way to make it work with openssh's chrootdirectory feature without patching openssh. However since SFTP in openssh is modular we may be able to find another program that can do what we're wanting instead.

**Comment by ghost** [comment]
I found out one option is to use proftpd's SFTP support but the distribution packaging of this doesn't get security updates on Ubuntu at least so it's not my first choice.

**Comment by ghost** [comment]
Ok, I've found a viable option. It involves using the PAM module, pam_chroot to chroot to the home directory before the internal SFTP server is run. This resolves the problem entirely by bypassing the need for openssh's chroot support since it is way too strict here.

**Comment by ghost** [comment]
Thanks for the details @braewoods. If you are able to get this working on your end, would you mind submitting a pull request with the changes or documented steps so that our team can review it? It would be much appreciated if at all possible.

**Comment by ghost** [comment]
@kristankenney I'm looking at it but pam_chroot has some side-effects in sshd. It trips for all sshd sessions whether SFTP or otherwise as long as the user is in its configuration. It seems to be harmless mostly but it does cause some errors to be logged when a normal session is attempted by an SFTP jailed user. Furthermore there seems to be no way for PAM to know which session type is present so it can't really do anything that I can tell.

**Comment by ghost** [comment]
So if we go ahead as it is, sshd will log errors for:

error: openpty: No such file or directory

pam_systemd(sshd:session): Failed to connect to system bus: No such file or directory
pam_mail(sshd:session): user unknown

At least on my Ubuntu system. Which set of errors appears depends on whether the client requests a PTY to be allocated. If this is an acceptable tradeoff (since they are apparently harmless but they can cause users to ask about it) then I can go ahead and implement it.

Unfortunately a portable solution requires chroot which requires root which cannot be used by the SFTP process as openssh executes it with reduced privileges. There's also the option of a userspace chroot but not many programs support it. It would be similar to what a web server does when restricting filesystem access.

**Comment by jaapmarcus** [comment]
Found maybe a hint to give the alias user access to create a folder "/home/alias_user/" and mount the destination folder /home/user/web/public_html/ to it. Then give root:root permission to the "/home/alias_user/". Haven't tested it yet and don't know what issues it can cause and other issues it can give...

**Comment by ghost** [comment]
Already tried that. It causes a new issue as the only way to achieve that is to do a bind mount. And if you change the permissions of the new bind mount root then they will modify the permissions of the original directory. And even if that worked you wouldn't have write access to the home directory due to what SSHD is imposing.

So far the only solution I found that 100% works with SSHD is to create a new root owned root that has the home directory bind-mounted to a sub-directory of it. This would put all files under /data or so from SFTP's perspective. But if our goal is a mostly seamless transition from FTP then this won't work since its chroot setup has the home directory as the root.

Another option I've been exploring is patching another SFTP server that is designed to run as a SFTP submodule to be setuid root so I can setup the chroot and then drop permissions before running the actual server code. This is about the only solution that would work with a kernel space chroot because of mutual exclusion issues. The code for both have to be in the same process for it to work and that's not possible with chroot scripts.

Edit: This is the one I'm looking at modifying. https://github.com/ewxrjk/sftpserver

**Comment by ghost** [comment]
Well, now I know why openssh cares so much. It's to stop a form of privilege escalation which is only possible when the chroot root is writeable. http://lists.mindrot.org/pipermail/openssh-unix-dev/2009-May/027651.html

**Comment by ghost** [comment]
I'm going to try a bind mount jail with some quirks to smooth out the user experience. It's the best option despite a small tradeoff.

**Comment by ghost** [comment]
vsftpd will remain enabled for new installations at this time, however steps are being taken to harden it's out-of-box security state. Please feel free to continue working on fixes for the SFTP jail to enable virtual accounts in your PR; closing this issue report.
