### ISSUE TITLE
Error Downloading Logs

### ISSUE THREAD

**Issue by dvgui** [hestiacp/hestiacp#937]
### In a few words, please describe the issue that you're experiencing:
When I try to download a log, I get an error. Via FTP or Web

### What steps did you take when the issue occured? 
1. Log in as user
2. Open File Manager
3. Attempted to download a log

### Expected behavior:
File manager or FTP should allow downloading logs.
### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.0

### Additional notes:
Since the logs are a soft link to /var/log it is impossible for users to download logs for troubleshooting their applications. 
This could be fixed in two ways.
1) Adding a redirection to the open and download buttons on file managers so that the file served is the full log instead of the soft link.
2) Making hestia create a hard link instead of a soft link to the log file.

**Comment by jaapmarcus** [comment]
The cause is that those files are located outside the sftp jail. How ever you are able download the files via the control panel. See binoculars icon (Third icon)

**Comment by Lupul** [comment]
![image](https://user-images.githubusercontent.com/3596864/87590006-ca7e1c80-c6ee-11ea-9df3-fdea3cb22959.png)
