### ISSUE TITLE
Vesta backup error : sed: can't read /etc/exim4/mailhelo.conf: No such file or directory

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#938]
I ran v-restore from vesta backup in fresh install on Debian 10 and during restore see this:
**sed: can't read /etc/exim4/mailhelo.conf: No such file or directory**

ll /etc/exim4/
total 36
drwxr-xr-x 9 root root         4096 Jul 15 19:31 conf.d
-rw-r--r-- 1 root root           32 Jul 15 19:48 dnsbl.conf
drwxr-xr-x 2 root root         4096 Jul 15 21:58 domains
-rw-r----- 1 root root        13820 Jul 15 19:48 exim4.conf.template
-rw-r----- 1 root Debian-exim   204 May 13 18:01 passwd.client
-rw-r--r-- 1 root root            0 Jul 15 19:48 spam-blocks.conf
-rw-r--r-- 1 root root         1053 Jul 15 19:42 update-exim4.conf.conf
-rw-r--r-- 1 root root            0 Jul 15 19:48 white-blocks.conf

**Comment by ScIT-Raphael** [comment]
Same here as in #940, please use the issue template, so we have all needed informations.

**Comment by ScIT-Raphael** [comment]
fixed, will be reviewed and released in 1.2.1, cosmetical only. https://github.com/hestiacp/hestiacp/pull/942/files
