### ISSUE TITLE
Network - New IP list Error

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#939]
I tried make black iplist from url https://lists.blocklist.de/lists/all.txt but always getting error  **Error: Populating ipset table**

**Comment by ghost** [comment]
Whats the output of `wget https://lists.blocklist.de/lists/all.txt`?

**Comment by avcvv** [comment]
> Whats the output of `wget https://lists.blocklist.de/lists/all.txt`?

# wget https://lists.blocklist.de/lists/all.txt
--2020-07-15 23:41:06--  https://lists.blocklist.de/lists/all.txt
Resolving lists.blocklist.de (lists.blocklist.de)... 2a00:1158:2:6d00::2, 185.21.103.31
Connecting to lists.blocklist.de (lists.blocklist.de)|2a00:1158:2:6d00::2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 459806 (449K) [text/plain]
Saving to: ‘all.txt’

all.txt                                    100%[======================================================================================>] 449.03K  --.-KB/s    in 0.04s   

2020-07-15 23:41:06 (10.1 MB/s) - ‘all.txt’ saved [459806/459806]

**Comment by ghost** [comment]
Are you able to use any of the existing lists without issue? It is possible that the list you are trying to use contains more than the maximum supported number of IPs per IPset list (65336 as per the ipset documentation) which would cause IPset to fail.

**Comment by jaapmarcus** [comment]
Just checked to confirm have the same error when I try to install 

root@dev:~# v-add-firewall-ipset Test http://lists.blocklist.de/lists/all.txt
Error: Populating ipset table

wget https://lists.blocklist.de/lists/all.txt
wc -l all.txt 
29805 all.txt

root@dev: v-add-firewall-ipset Nederland http://ipverse.net/ipblocks/data/countries/nl.zone 
root@dev: 

There could be a issue in http://lists.blocklist.de/lists/all.txt

**Comment by Lupul** [comment]
`all.txt` has to be preprocessed, cannot be used as is, ~~ipset expects networks to be using CIDR notation~~.

Later added (from https://github.com/hestiacp/hestiacp/pull/819 ):
`v-add-firewall-ipset country-de 'http://ipverse.net/ipblocks/data/countries/de.zone'`
-The command will define `country-de` in Hestia, download the network lists file and load them in the Linux kernel trough ipset
-If a preprocessing script is present at $HESTIA/data/firewall/ipset/country-de.v4.sh it will be executed after the file is downloaded, with the following args: NAME and TEMPPATH eg: `country-de.v4.sh country-de /tmp/abcdef1234`

**Comment by Lupul** [comment]
After looking closer at the `all.txt` file the problem seems to be that the list also contains ipv6 addresses.
So the issue is confirmed

**Comment by ScIT-Raphael** [comment]
fixed: https://github.com/hestiacp/hestiacp/pull/1038

**Comment by avcvv** [comment]
Can't add lists with comments, can you fix this?
example: https://www.spamhaus.org/drop/drop.txt

**Comment by ScIT-Raphael** [comment]
@avcvv can you please open a new issue report? so we can fix this aswell.

**Comment by Lupul** [comment]
@avcvv please check if the related commit (https://github.com/hestiacp/hestiacp/pull/1038/commits/9fcf434830ab66e5013e6d37c75fb0c3627c6b49) fixes your issues, patching  the `v-add-firewall-ipset` should be straight forward
