### ISSUE TITLE
Roundcube 

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#940]
Can't run roundcube
i did records for domain:  groovys.online

A Record | webmail
A Record | mail
A Record | @
A Record | www

But i can't run roundcube, i see only **Success! Your new web server is ready to use.**
How to run roundcube?

**Comment by ScIT-Raphael** [comment]
Please do not replace the issue template, this text isnt decoration, it helps us to get all needed informations frol you to debug the issue. Please post your issue using the template here or create a new one - I'll reopen your issue then.
