### ISSUE TITLE
Roundcube doesn't open

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#943]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:

Can't run roundcube after adding domain in panel, i did all necessary records for domain: groovys.online

A Record | webmail
A Record | mail
A Record | @
A Record | www
MX Record | mail.groovys.online.

But i can't run roundcube, i see only Success! Your new web server is ready to use.
How to run roundcube?

### What steps did you take when the issue occured? 
1. Ex.: Click on the Web tab
2. Ex.: Click on Add Web Domain
3. Ex.: Attempted to add a domain and received an Internal Server Error.

### Expected behavior:
Please enter your answer here (e.g. the web domain should have been added successfully).

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.0

**Comment by jaapmarcus** [comment]
Did you create a mail domain?

Then mail should be availble add webmail.domain.com

**Comment by avcvv** [comment]
> Did you create a mail domain?
> 
> Then mail should be availble add webmail.domain.com

i' he added domain to hestia, then did A records and no more, such details i  see in panel:
`

Username: | admin@groovys.online
-- | --
Password: |  
IMAP Hostname: | mail.groovys.online
IMAP Port: | 143
IMAP Security: | STARTTLS
IMAP Authentication Method: | Normal Password
SMTP Hostname: | mail.groovys.online
SMTP Port: | 587
SMTP Security: | STARTTLS
SMTP Authentication Method: | Normal Password
Webmail Alias: | http://webmail.groovys.online

`

When i go to http://webmail.groovys.online i see only **Success!**

**Comment by avcvv** [comment]
<img width="1030" alt="Screenshot 2020-07-16 13 07 22" src="https://user-images.githubusercontent.com/39009179/87658852-677b9c80-c765-11ea-9b47-58d222d0d603.png">
<img width="1088" alt="Screenshot 2020-07-16 13 07 30" src="https://user-images.githubusercontent.com/39009179/87658857-69456000-c765-11ea-81be-715ceafb8d9a.png">
<img width="473" alt="Screenshot 2020-07-16 13 07 39" src="https://user-images.githubusercontent.com/39009179/87658868-6c405080-c765-11ea-89d8-7ca312f08698.png">
<img width="565" alt="Screenshot 2020-07-16 13 07 45" src="https://user-images.githubusercontent.com/39009179/87658884-71050480-c765-11ea-98aa-1982c69b8b56.png">

**Comment by jaapmarcus** [comment]
Check if /etc/nginx/conf.d/domains/webmail.groovys.online.conf

Or /etc/apache2/conf.d/domains/webmail.groovys.online.conf

Depending on setup.

**Comment by avcvv** [comment]
File exist

```
cat /etc/nginx/conf.d/domains/webmail.groovys.online.conf
server {
    listen      134.119.205.79:80;
    server_name webmail.groovys.online mail.groovys.online;
    root        /var/lib/roundcube;
    index       index.php index.html index.htm;
    access_log /var/log/nginx/domains/webmail.groovys.online.log combined;
    error_log  /var/log/nginx/domains/webmail.groovys.online.error.log error;

    include /home/mailo/conf/mail/groovys.online/nginx.forcessl.conf*;

    location ~ /\.(?!well-known\/) {
        deny all;
        return 404;
    }

    location ~ ^/(README.md|config|temp|logs|bin|SQL|INSTALL|LICENSE|CHANGELOG|UPGRADING)$ {
        deny all;
        return 404;
    }

    location / {
        try_files $uri $uri/ =404;
        location ~* ^.+\.(ogg|ogv|svg|svgz|swf|eot|otf|woff|woff2|mov|mp3|mp4|webm|flv|ttf|rss|atom|jpg|jpeg|gif|png|ico|bmp|mid|midi|wav|rtf|css|js|jar)$ {
            expires 7d;
            fastcgi_hide_header "Set-Cookie";
        }

        location ~ ^/(.*\.php)$ {
            alias /var/lib/roundcube/$1;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $request_filename;
        }
    }

    location /error/ {
        alias /var/www/document_errors/;
    }
	
    include /home/mailo/conf/mail/groovys.online/nginx.conf_*;
}
```

<img width="1046" alt="Screenshot 2020-07-16 15 08 47" src="https://user-images.githubusercontent.com/39009179/87669239-4f604900-c776-11ea-9dc6-9a4b7b9072a1.png">

Host records:

<img width="1145" alt="Screenshot 2020-07-16 15 11 39" src="https://user-images.githubusercontent.com/39009179/87669450-af56ef80-c776-11ea-9c55-cf7386b1a9ea.png">

**Comment by jaapmarcus** [comment]
Run `nginx -t` to see if there is any issue in any config file. Just checked and with my local machine I have no issue.

**Comment by avcvv** [comment]
nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by avcvv** [comment]
So, somebody help resolve this issue?

**Comment by avcvv** [comment]
Please help resolve this issue

**Comment by jaapmarcus** [comment]
Please try to enable SSL..  I can't replicate any thing?

What is your server setup dit you have Apache, Nginx enabled?

**Comment by avcvv** [comment]
Nginx + php fpm, i can provide you teamviewer maybe it will b e faster to resolve

**Comment by jaapmarcus** [comment]
Create a new server for testing but never but can't replicate the issue. Unless you have added the domain also as web domain or alias domain.  Please check those settings again.

**Comment by avcvv** [comment]
> Create a new server for testing but never but can't replicate the issue. Unless you have added the domain also as web domain or alias domain. Please check those settings again.

I've added domain in web domain and set checkbox (Enable mail for this domain)

**Comment by jaapmarcus** [comment]
Delete and try to add them again. The configuration seems to be fine...

**Comment by avcvv** [comment]
I've started reinstall OS already

**Comment by avcvv** [comment]
Same again, not opened roundcube

**Comment by jaapmarcus** [comment]
Are any other domains working with out issues? As when I visit the main domain I also see the "success" logo instead of "under" construction.

**Comment by avcvv** [comment]
> Are any other domains working with out issues? As when I visit the main domain I also see the "success" logo instead of "under" construction.

All domains same, maybe i can give you ssh and you check it?

**Comment by jaapmarcus** [comment]
Send me a email to -----. Will have a look at it.. Won't happen before 12o clock UTC...

**Comment by avcvv** [comment]
Everywhere same

**Comment by avcvv** [comment]
I restored vesta backup only with domains which belong admin, then added mail domains to mailo user

**Comment by avcvv** [comment]
You can delete and then again add domains in  user (mailo)

**Comment by jaapmarcus** [comment]
Found the issue 

When  /usr/local/hestia/bin/v-restart-web
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory


PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"

**Comment by avcvv** [comment]
What cause call this trouble?

**Comment by jaapmarcus** [comment]
Was executing the command form a folder that was removed. How ever the issue still remains

**Comment by avcvv** [comment]
Do you now how to fix this? Very weird that I did 2 installs of OS and were same troubles

**Comment by jaapmarcus** [comment]
For now manually restart nginx..  How ever need to find the issue.. Think https://github.com/hestiacp/hestiacp/issues/953 issue is some how related.

**Comment by jaapmarcus** [comment]
xxxxx.online  failed (24: Too many open files) Changed some config files. Just google the error message with nginx. 

We should really work on v-diagnostic-report command.
