### ISSUE TITLE
Normal User Cannot Change Backend Template PHP-FPM

### ISSUE THREAD

**Issue by pakdhetimin** [hestiacp/hestiacp#947]
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
When normal user edit web domain in Backend Template PHP-FPM eg. from PHP-7_2 to PHP-5_6 nothing change, always keep in PHP-7_2 status.

### What steps did you take when the issue occured? 
1. Click on the Web tab
2. Click on Edit Web Domain
3. Attempted to edit a domain Backend Template PHP-FPM but nothing change.
4. But when I login as Admin, and then login to that normal user, i can change or edit web domain Backend Template PHP-FPM for that user.

### Expected behavior:
Normal user login can edit/change web domain Backend Template PHP-FPM.

### Operating system:
Ubuntu 18.04 LTS

### Hestia Control Panel version:
v1.2.0 

### Additional notes:
This bug is so annoying because normal user cannot change/edit their Backend Template PHP-FPM by themselves, but an Admin can do. Why?

**Comment by jaapmarcus** [comment]
Known "issue" see https://github.com/hestiacp/hestiacp/issues/787

We are discussing solving the issue...

**Comment by jaapmarcus** [comment]
Duplicate issue see #787
