### ISSUE TITLE
Use https when downloading executable scripts, signatures, keys, etc.

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#949]
Similar to this issue: https://github.com/myvesta/vesta/issues/78

Examples:
https://github.com/hestiacp/hestiacp/blob/main/install/hst-install-debian.sh
Lines 617, 618, 639, 649, 660, etc...

Similar in the other install scripts.

**Comment by vestacp-user** [comment]
I did some futher tests and the following HTTPS link has an encryption problem.  
https://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/debian

Currently, the install script hst-install-debian.sh is using the non-ssl link
http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/debian 

Why isn't HestiaCP using official Debian Repos whenever possible? eg:
https://packages.debian.org/buster/mariadb-server

Same question for several of the other repos.  You can also mix use of backports or newer vesions of debian repos to get the most recent versions of the various packages.  Why is HestiaCP using various less trusted sources?

**Comment by vestacp-user** [comment]
Which components of HestiaCP need to be on the most recent versions? I can help figure out which Debian sources would be the best.  Note that anything outside of Debian 10 Stable (buster, buster-backports) will not get security updates as frequently and is a higher security risk.  Unless absolutely required, Debian 10 Stable Repos should be used (I am not considering another other Distros or Releases in this analysis)

Apache2
Debian buster: 2.4.38-3+deb10u3 https://packages.debian.org/buster/apache2
Debian buster-backports: 2.4.43-1~bpo10+1 https://packages.debian.org/buster-backports/apache2
Hestia installed: 2.4.43-1+0~20200511.11+debian10~1.gbpdc0c89 from deb.sury.org, so basically the same as buster-backports

MariaDB
Debian buster: 1:10.3.22-0+deb10u1 https://packages.debian.org/buster/mariadb-server
Higher is probably NOT required: sid 1:10.3.23-1, experimental 1:10.4.13-1~exp1
current HestiaCP DigitalOcean repo is NOT a good one.

PHP7:
Debian buster: 2:7.3+69 https://packages.debian.org/buster/php
Higher is probably NOT required: sid 2:7.4+76
HestiaCP installed: 2:7.4+76+0~20200511.26+debian10~1.gbpc9beb6 from deb.sury.org, probably not required.

nginx.org is good, but could be debian sources too.  
Debian buster: 1.14.2-2+deb10u1 https://packages.debian.org/buster/nginx
Debian bullseye and sid: 1.18.0-5 https://packages.debian.org/bullseye/nginx https://packages.debian.org/sid/nginx
Bullseye and Sid can usually be mix with stable Buster.
nginx.org: 1.19.1-1~buster https://nginx.org/packages/mainline/debian buster/nginx amd64 Packages

apt.postgresql.org is a good source also, but could be Debian source.  Depends on what version HestiaCP really needs.

Yes, ded.sury.org is a Debian maintainer, but his repos are one guy and he is overloaded.  The Debian repos are are a much better source in many perspectives.

(Ignore the crossed-out texts, the markup is doing that automatically)

**Comment by ioannidesalex** [comment]
Debian repos always have much outdated versions of software. There is no right or wrong approach though.

Personally I prefer using latest software.

**Comment by jaapmarcus** [comment]
For MariaDB packages you have a few points but and for missing SSL we need to check if they support all ready. How ever we use the official repos as close as possible and they are more up to date... 

Sury is one of the ways to support multiple PHP versions...

**Comment by vestacp-user** [comment]
The most critical issue is MariaDB.  At least follow the official instructions if not using the Distros Repos. (mirror choice is just an example, the key is the important part)

Instructions for the current stable version of MariaDB 10.5 for Debian 10:
https://downloads.mariadb.org/mariadb/repositories/#distro=Debian&distro_release=buster--buster&mirror=ukfast&version=10.5

Instructions for the old stable version of MariaDB 10.4 for Debian 10:
https://downloads.mariadb.org/mariadb/repositories/#distro=Debian&distro_release=buster--buster&mirror=ukfast&version=10.4

So something like (as per their instructions):
sudo apt-get install software-properties-common dirmngr
sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
sudo add-apt-repository 'deb [arch=amd64] http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.4/debian buster main'

**Comment by ScIT-Raphael** [comment]
@vestacp-user things are changing over time, we followed the official instructions from mariadb when we implemented it to the installer. We'll have a look and rework the parts, also digital ocean is listed as official mirror, can you describe why you think that it is not a good mirror?

**Comment by vestacp-user** [comment]
@ScIT-Raphael of course! I appreciate of everyones hard work and contributions and obviously I am discussing these issues here since the original VestaCP seems dead.  Maybe my comments seem rough, but I am just trying to get straight to the main points without too much blah blah.

I am putting some initial changes in a fork/branch of the release version so that I can test and explore.   Also permits anyone to look at concrete examples of what I mean in my above discussions. 

https://github.com/vestacp-user/hestiacp/blob/release_https/install/hst-install-debian.sh

**Comment by vestacp-user** [comment]
@ScIT-Raphael digital ocean mirror:  https/ssl not working, and an http mirror could be subject to MITM.  Yes, the key is from ubuntu and should be trusted, and the package will ultimately be checked against the key.  However, many users would not understand the error message if it occured and would look for a way to bypass it or force the install anyways.  General reccommendations are that you ensure your trust the server you think you are communicating with.  

Many other parts of the install script are already using https repos, just a few exceptions left.  You could argue that they could all just be http repos also since the packages signatures will be checked after, but obviously it's better to make sure they are all https.

**Comment by kpapad904** [comment]
I brought up this particular issue back in Feb-2020 also offering diffs, depending on whether the project would prefer to download signing keys from the URL (over https) or from a keyserver:

https://github.com/hestiacp/hestiacp/issues/695

**Comment by ghost** [comment]
There's some benefit to using the distribution packaging more but not always. The main benefit is security updates but that needs to be evaluated on a case by case basis. Like, no distribution supplies multiple versions of php. They only supply one at most. So you need a third party source to get that to work. In another example Ubuntu doesn't guarantee security updates for packages outside of the main repository. That can make it problematic for using them for a source for software at times when security matters.

**Comment by jaapmarcus** [comment]
Only Apache / PHP under Ubuntu are still http but https://ppa.launchpad.net doesn't work...
