### ISSUE TITLE
Never succeeded & The directory index cannot be read

### ISSUE THREAD

**Issue by kang28ivan** [hestiacp/hestiacp#953]
Hi, I'm just a new user HestiaCP who was previously a VestaCP user.

I have tried installing Hestia on several VPS a number of times but it never worked at all, I tried installing on Debian 9/10, Ubuntu 16.04/18.04 same result.

When I add domain/IP its always show **Success!** can't read index.html or index.php even though I've tried installing wordpress on the **Quick Installer** I access wp-login.php also not found.

There seems to be something wrong with this panel, previously I tried to restore backup from VestaCP and it worked, but when it started to start there was absolutely no success.

Does anyone here have the same experience?

Thank you.

**Comment by ScIT-Raphael** [comment]
Hi @kang28ivan 

I think it would be important, that you start to use the issue report template, it will give us a lot of needed informations like installed versions and so on.

Also you wrote "never succeded" a installation, which could be aswell "everything" :). As well as it looks that you successfully restored a vesta backup, there might be other configuration issues on your side, maybe also related with the installation issues you had?

Without additional informations it is just a wild guessing here. I do not have any issues with debian 10 or ubuntu 18.04 and 20.04 here, all is working well. Also Hestia is != Vesta, we made a lot of changes and improvements, which makes it to a different product, which is based on vesta.

**Comment by kang28ivan** [comment]
Hi @ScIT-Raphael thank you for quick reply, 

Yes, for new install I never succeded when I Add domain its always show **Success!**, but when I  access domain in browser with domain.com/index.html its show **coming soon**, when I try restore backup from vestacp it is possible that the correct config/settings are from vestacp backup including permissions, but when I upload script to hestia file manager all permission file/folders goes wrong.  Currently 1 vps uses Hestia and it is restore backup from Vestacp no problem.

I do not know why this problem, I'm also confused, I have reinstalled VPS several times using different options, for example Apache is installed without nginx and php-fpm, its same.

I am just a user who is familiar with vestacp which is very easy, when I add IP (not domains) in the WEB menu the IP can be directly accessed. or hestia does not support more than 1 ip in the panel?

**Comment by kang28ivan** [comment]
Also I have question, in the future hestia will support centos?

**Comment by ScIT-Raphael** [comment]
Hestia does support multiple ips, CentOS support is in work, but no release date yet.

I can't tell you what's wrong with your system, again to less informations. Maybe start at a point and decide what system you need, apache2+nginx or nginx only (or one of the other possibilities), then note down the steps you did 1:1 and fill out a issue report, that should be the way how we can help you here.

**Comment by kang28ivan** [comment]
Ok thank you @ScIT-Raphael I'll try it later, because it's urgent for now vps for my client, so I'm using Vestacp again.
it just makes me confused why it never works, because if basically vestacp there should be no problem we add my IP and IP access.

Thank you for your prompt reply and hope to release centos soon.
