### ISSUE TITLE
SSL on Admin Panel. 

### ISSUE THREAD

**Issue by archergod** [hestiacp/hestiacp#955]
I have been using VestaCP for sometime and really like your fork. Here are some feature I feel missing:

1. Allow SSL for Admin Panel from Let's Encrypt. I see in server setting we can change certificate, but it doesn't have auto certificate there.

2. Can you allow us to upload our logo along with yours. Not important.

**Comment by ScIT-Raphael** [comment]
Hi

For nr. 1 please check this part here: https://docs.hestiacp.com/admin_docs/ssl_certificates.html

For nr. 2, have a look here: https://github.com/hestiacp/hestiacp/blob/main/bin/v-add-sys-theme

**Comment by archergod** [comment]
Thanks, Just that when we upgrade Hesita in future these setting remain preserved right ?

**Comment by ScIT-Raphael** [comment]
Exactly, that's why v-add-sys-theme is here :).

**Comment by archergod** [comment]
I try to run the Hostname but getting `400` error 

![image](https://user-images.githubusercontent.com/4686220/87901526-eed25400-ca74-11ea-8dcc-bd5fa0645bb2.png)

What I am doing wrong. My Hostname is set with `A` Record in DNS

**Comment by jaapmarcus** [comment]
Cloudflare or other third party?

**Comment by archergod** [comment]
Nope, plain new server, also I observe I cannot access PhpMyAdmin through IP based address that panel offer for mysql/mariadb. until I add second user and domain with SSL under it's' name (now it goes to HTTPS of that new domain).

**Comment by jaapmarcus** [comment]
For Ip phpmyadmin see https://docs.hestiacp.com/admin_docs/server_management.html#why-i-can-t-use-http-my-ip-adress-phpmyadmin

For let encrypt we create the hostname  as a web domain in the admin account. But if it can't access that url (hostname.com/phpmyadmin/) you won't be able to use Let encrypt ssl as it uses the main Nignx as source for requesting the lets encrypt certificate.

**Comment by archergod** [comment]
I am okay to disable PHPMyadmin, but then why Panel itself has a button for it :). It should be Hostname/phpmyadmin in that case. 

I just reboot server and now hostname/phpmyamdin works, but still getting this

![image](https://user-images.githubusercontent.com/4686220/87904285-918dd100-ca7b-11ea-9a26-1e6ec5cbd950.png)

**Comment by ScIT-Raphael** [comment]
It only occurs when you connect also to your hestia controlpanel over ip - it's recommend to use the server hostname. About the LE400 issue you need to have a look in our forum, this has been discussed a lot of times and the different solutions should lead you to the right way: https://forum.hestiacp.com/search?q=400

**Comment by archergod** [comment]
For using base address to access panel. The installer shows IP by default to access it. Then maybe you need to change installer

![image](https://user-images.githubusercontent.com/4686220/87904749-a028b800-ca7c-11ea-9493-6b1aee6dd506.png)

from IP to base address/hostname itself? 

For LE, I think I found the problem (as it is not using public IP). But not seems I hit rate limit so cannot really verify at this moment and have to wait for rate limit fixes. But thanks I guess we are set now. 

You guys really do a great job.

**Comment by ScIT-Raphael** [comment]
Mostly you havent setup the hostname, that's why the IP is there. We'll discuss how we could resolve this.

**Comment by archergod** [comment]
I did configure the Hostname before installer. Yes, my client didn't set DNS for hostname when I run setup, so if it check DNS record then it is fine showing IP, but I do set hostname before installer.
