### ISSUE TITLE
Install 1.2.1.deb it`s fail

### ISSUE THREAD

**Issue by Indjov** [hestiacp/hestiacp#956]
OS: Debian 10
dpkg -i hestia_1.2.1_amd64.deb
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin

**Comment by FalzoMAD** [comment]
How did you become root? In deb 10 you need to properly use su - not just su, otherwise you won't have the full path set correctly.
Not hestia related though...

**Comment by Indjov** [comment]
Ahh, that su - solve my problem.
