### ISSUE TITLE
Only default Apache2 template available

### ISSUE THREAD

**Issue by Spheerys** [hestiacp/hestiacp#958]
I have followed the doc about how web templates works : https://docs.hestiacp.com/admin_docs/server_management.html#how-do-web-templates-work
I have created a new template but is not available on HestiaCP nor with v-list-web-template : 
```
~  ls -al /usr/local/hestia/data/templates/web/apache2/
total 68
drwxr-xr-x 3 root root 4096 juil. 19 14:26 .
drwxr-xr-x 9 root root 4096 juil. 17 22:06 ..
-rw-r--r-- 1 root root 1435 juil. 19 14:21 default.stpl
-rw-r--r-- 1 root root 1331 juil. 19 14:22 default.tpl
-rw-r--r-- 1 root root 1916 juil. 17 22:06 hosting.stpl
-rw-r--r-- 1 root root 1813 juil. 17 22:06 hosting.tpl
-rw-r--r-- 1 root root 1422 juil. 17 23:24 modx.stpl
-rw-r--r-- 1 root root 1317 juil. 17 23:24 modx.tpl
-rwxr-xr-x 1 root root  304 juil. 17 22:06 phpcgi.sh
-rw-r--r-- 1 root root 1321 juil. 17 22:06 phpcgi.stpl
-rw-r--r-- 1 root root 1217 juil. 17 22:06 phpcgi.tpl
-rwxr-xr-x 1 root root  409 juil. 17 22:06 phpfcgid.sh
-rw-r--r-- 1 root root 1387 juil. 17 22:06 phpfcgid.stpl
-rw-r--r-- 1 root root 1245 juil. 17 22:06 phpfcgid.tpl
drwxr-xr-x 2 root root 4096 juil. 17 22:06 php-fpm
```
And : 
```
~ v-list-web-templates
TEMPLATE
--------
default

```

I'm running last version of HestiaCP and Ubuntu 20.04LTS

What did I miss ?

**Comment by ScIT-Raphael** [comment]
Let's start with the issue template, it isnt decoration and would help us to understand your issue - so please use it.

Depending on your setup, you need to use different templates - can you share your install string?

**Comment by jaapmarcus** [comment]
Probably you are using PHP-FPM 

https://github.com/hestiacp/hestiacp/tree/main/install/deb/templates/web/apache2/php-fpm

https://github.com/hestiacp/hestiacp/tree/main/install/deb/templates/web/apache2/  is for mod-php / legacy php

**Comment by Spheerys** [comment]
Sorry for the template. I will use it next time.
@jaapmarcus it was this. Thanks !

**Comment by jaapmarcus** [comment]
But I agree we need it to make it more clear.... 
Will update the documentation

**Comment by Spheerys** [comment]
Yes it could be useful :)
Maybe can you also add how to change settings like open_basedir in php-fpm environment : 
```
Copy the /usr/local/hestia/data/templates/web/php-fpm/default.tpl to a new template and edit it and modify the line php_admin_value[open_basedir]
```

**Comment by jaapmarcus** [comment]
Depends if you are also using multiphp. But we advice when you change certain values of templates create a copy as old templates can be overwritten in the future during upgrades

**Comment by ScIT-Raphael** [comment]
Do NOT edit default files, copy them - otherwise they get resetted during upgrade. You can copy them aswell and set it under backend template when editing the web domain.

**Comment by Spheerys** [comment]
Yes of course !
