### ISSUE TITLE
v-change-sys-config-value: errors when trying to change BACKUP

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#959]
I am getting errors from the special code in the `v-change-sys-config-value` script from how it tries to handle the /backup removal. If the directory does not yet exist it produces a spurious error (ENOENT). If it does then it gives a different error (EISDIR) because rm is the wrong command to use for removing a directory when not done recursively.

Either way this should be handled better but how? That depends on what is deemed acceptable as side-effects regarding what happens to existing backups at the old location.

**Comment by ScIT-Raphael** [comment]
May you contact us on info@hestiacp.com? We would love to discuss with you in our dev chat, makes the thibgs a bit faster :).

**Comment by ghost** [comment]
Sent.

**Comment by ScIT-Raphael** [comment]
Answered :)

**Comment by jaapmarcus** [comment]
With the following pull request the issues should be sorted as changing via Web GUI has been changed 
https://github.com/hestiacp/hestiacp/pull/1658 

We need to rewrite the current behaviour any way see: 

https://github.com/hestiacp/hestiacp/issues/1655
