### ISSUE TITLE
Error during v-restore-user with VestaCP backup

### ISSUE THREAD

**Issue by Spheerys** [hestiacp/hestiacp#961]
### In a few words, please describe the issue that you're experiencing:
When restoring a VestaCP backup, I have the error : 
```
Error: invalid source path /backups/hestia/tmp.BFiORSFZNy/user_dir/.bash_logout.tar.gz
Error: Can't unpack .bash_logout user dir container
```
However the website is fully functional after restoring.
The issue is concerning the error message only : why it is occuring  ?

### What steps did you take when the issue occurred? 
1. make a successful backup on VestaCP
2. transfer it on another server with HestiaCP
3. restore the backup on the new server

I moved several websites and each time the issue occurs.

### Expected behavior:
No error during restoration.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.0

### Other informations
VestaCP version on the old server :  0.9.8 (amd64) Release:    26

**Comment by jaapmarcus** [comment]
Could you supply us a  backup with a perfable dummy data that causes an issue?

**Comment by Spheerys** [comment]
Of course : https://cloud.spheerys.fr/index.php/s/KSFEQjkeg4FLzR4
It's an nearly empty backup (just a domain and a database) but the issue occurs during my restore step

**Comment by jaapmarcus** [comment]
Oke will have a look tommorow

**Comment by jaapmarcus** [comment]
Tried to use you back up bit didn't had any issue but also the .bash_logout was missing

**Comment by Spheerys** [comment]
Same conclusion.
Not a big deal, except if you run scripts with strict mode...

**Comment by ScIT-Raphael** [comment]
After a short discussion in our dev chat we're going to close this issue, because it's "just" an unimportant error output.

**Comment by jaapmarcus** [comment]
Please check:
https://github.com/hestiacp/hestiacp/issues/1655
