### ISSUE TITLE
v-add-mail-account-fwd-only: doesn't handle non-existing forwarding list gracefully

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#963]
This is the result I get if I try to run this before running `v-add-mail-account-forward`:

root@vps1:/etc/nginx/conf.d# v-add-mail-account-fwd-only admin ${HOSTNAME} admin
Error: forward doesn't exist
/usr/local/hestia/func/main.sh: line 70: [: 3  'admin' 'vps1.example.com' 'admin': integer expression expected

**Comment by jaapmarcus** [comment]
@braewoods Could you try if it is still a issue?

root@cp:/home/eris#  v-add-mail-account-fwd-only admin $(hostname) admin
Error: $(hostname) account admin doesn't exist

Both on my main server and dev server...

**Comment by jaapmarcus** [comment]
Fixed issue
