### ISSUE TITLE
SMTP Queue Log is Growing

### ISSUE THREAD

**Issue by archergod** [hestiacp/hestiacp#968]
After initial `admin` user I create another user to put my first site, and now in attempt to see all feature of Hestia I see that my SMTP log shows 7400 messages in queue

![image](https://user-images.githubusercontent.com/4686220/87905511-5640d180-ca7e-11ea-84ae-f39fbd5f2985.png)

I use same gmail account for both User (default admin, as it pick email from system user) and then my second user.

Those 3 gmail email are one that I try to send Credential for DB and hosting account I create and rest are set to admin@hotname and <newuser>@hostname .. 

It is default setup, I didn't change any settings related to email. I just try to change theme as I mention in tickets. I can clear the queue and stuff. but my question/concern is that when we provide the gmail ID, why it is not sending those email to gmail id and linux user. And why it generate 7400 emails? It is secure not hacked, But are either system generated message loop or something. 

Second concern is why those 3 Gmail emails are not delivered in default configuration. I am searching configuration error or why they are not delivered. maybe something at my setup end. But want to point out the #1

**Comment by archergod** [comment]
It seems my server is not able to resolve hostname, and briefly my client mess the DNS setting so maybe it is because of it.

**Comment by jaapmarcus** [comment]
For questions regarding set up / Lets ecrypt and other things please use our forum. We want to keep Github Issues for bug reports so the can be easily tracked.
