### ISSUE TITLE
phpmyadmin alias change does not work with PHP-FPM backend & NGINX web server

### ISSUE THREAD

**Issue by tudorr89** [hestiacp/hestiacp#970]
### In a few words, please describe the issue that you're experiencing:
After changing the phpmyadmin alias, the new alias returns 404

### What steps did you take when the issue occured? 
1. Go to Server -> Configure -> Databases
2. Change phpMyAdmin alias and save.
3. https://example.com/newphpmyadmin alias redirects to 404

### Expected behavior:
phpmyadmin alias should be accessible

### Operating system:
Ubuntu 18.04 LTS

### Hestia Control Panel version:
Hestia 1.2.0 release

### Additional notes:
PHP-FPM backend
NGINX web server
Multi-PHP enabled with version 7.4 set to default (7.3,7.2,7.1 installed)

**Comment by jaapmarcus** [comment]
There is a know bug that should be fixed in 1.2.1 
https://github.com/hestiacp/hestiacp/commit/458d973031067324716c384c898c7a299e4da6de

It should be fixed in the next Release. 

See the link for more information about the beta release.
https://forum.hestiacp.com/t/1-2-1-beta-release/1314/3
