### ISSUE TITLE
Error log for phpmyadmin

### ISSUE THREAD

**Issue by MarioC-IRL** [hestiacp/hestiacp#971]
### Expected behavior:
I've been using the HestiaCP service for a while now and since I've never used phpmyadmin directly, I wanted to test the service and provide an acquaintance with a code error. I went into the logs and saw a number of phpmyadmin errors.

The error is therefore as follows: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.

### Operating system:
Ubuntu 18.04.4 LTS

### Hestia Control Panel version:
v1.2.0

**Comment by ScIT-Raphael** [comment]
Can you please use the issue report template? It isnt decoration and contains a lot if beeded informations if you would fill it out.

**Comment by MarioC-IRL** [comment]
> Can you please use the issue report template? It isnt decoration and contains a lot if beeded informations if you would fill it out.
I changed my station, I'm sorry I wasn't paying attention.

**Comment by jaapmarcus** [comment]
Are you using the default templates for PHP FPM?

It should be fixed in 1.2.0 see 
https://github.com/hestiacp/hestiacp/commit/1e73d50af678d83b15fb5b7d6c293930bafe9ba5#diff-3f05fefed81f2dec822d19db94459677

**Comment by MarioC-IRL** [comment]
I have version 1.2.0 but this modification is not in my files.

**Comment by kpapad904** [comment]
I noticed the same error on a HestiaCP 1.2.1-beta running on Debian10.

https://pastebin.com/Wg4YhnXf

**Comment by jaapmarcus** [comment]
Just checked on my own server. Same issue

**Comment by jaapmarcus** [comment]
Check the rights in /etc/phpmyadmin and /var/lib/phpmyadmin it should be normally 640 change it to 644

**Comment by WHUGLIT** [comment]
Can you tell me how to fix this error ? The panel is installed on Debian 10

**Comment by jaapmarcus** [comment]
chmod 644 /etc/phpmyadmin/config-db.php

**Comment by ioannidesalex** [comment]
Duplicate of issue #909
