### ISSUE TITLE
File Manager gives "Unknown Error" message (Hestia 1.2.0, Debian 10)

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#977]
File Manager gives an error message "Unknown Errror" (Hestia 1.2.0).  Fresh Debian 10 Install except for modifications to `/etc/ssh/sshd_config`

This seems to occur specifically when the line `Subsystem sftp /usr/lib/openssh/sftp-server` is removed or changed in `/etc/ssh/sshd_config` in such a way that the install script cannot update it to `Subsystem sftp internal-sftp`

Short answer: 
add `Subsystem sftp internal-sftp` to `/etc/ssh/sshd_config`:

Long answer: 
Refer to the install script `./install/hst-install-debian.sh` for all the changes made to `/etc/ssh/sshd_config`.   For Debian, the changes can be summarized as follows:

```
# HestiaCP Changes to the default /etc/ssh/sshd_config in Debian 10 Buster 

# Forced default yes
PasswordAuthentication yes

# Changed from default 2m to 1m
LoginGraceTime 1m 

# Changed from default /usr/lib/openssh/sftp-server to internal-sftp
Subsystem sftp internal-sftp

# Changed from default yes
DebianBanner no
```

Returning all of the other parameters to their defaults and also changing to `PasswordAuthentication no` did not reproduce the error, thus it would seem to be isolated to the `Subsystem sftp internal-sftp` parameter.

I am posting this issue as a reference for anyone who might get this same error.

**Comment by vestacp-user** [comment]
Issue posted only for reference, closing it.

**Comment by jaapmarcus** [comment]
But it doesn't belong here :)

Will update https://docs.hestiacp.com for further references

https://docs.hestiacp.com/admin_docs/filemanager.html

Feel free to create a PR In the future

**Comment by vestacp-user** [comment]
@jaapmarcus I am not sure I follow, there is no error with a vanilla install.  This is a bug that could occur when installed on a system with a modified sshd_config file.  Many cloud providers modify the default distros for their VMs, so I put it here for someone looking for a solution to the "Unknown Error" error popup in the "File Manager"
