### ISSUE TITLE
Feature Request: Migration tool to move from Vesta to Hestia

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#981]
### In a few words, please describe the issue that you're experiencing:
N/A

### What steps did you take when the issue occured? 
N/A

### Expected behavior:
N/A

### Operating system:
Ubuntu 16.04

### Hestia Control Panel version:
N/A

### Additional notes:
Is there a upgrade script for this matter?
as like:
hestia-upgrade.sh or vesta-to-hestia.sh, 
if no, it's possible to create it with the following conditions / steps?
- it should remove the vestacp keys, and the rest,
- install the "new" hestiacp
- upgrade scripts, users, and needed data
- if multiple php installed (my case), add it to the settings as enabled
- keep the same admin password or, if wanted:
    - generate it with a flag `--generate-password`
    - modify password with the flag `--modify-password "{password}"`
        - in the case of the flag(s), output the new password, with the username

**Comment by ScIT-Raphael** [comment]
Basicly yes, it is possible. We already have discussed it here: https://github.com/serghey-rodin/vesta/issues/2006#issuecomment-650081849

As I already have written there, it will probaly take a lot of time to do it to get a clean migration - including the whole testing stack. In the current state, we don't have enough time to do this on our own - but if someone can help us, this would be amazing!

**Comment by ScIT-Raphael** [comment]
We just clear up our issues and will close this one: The way with restoring vesta backups is working properly with hestia, migrating an existing system is currently out of our scope.
