### ISSUE TITLE
A few files are not executable at source

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#982]
The following files are missing the executable flag in the source.  I can create a pull, but I figure the project will prefer to batch this into a maintenance pull. The files and the command to fix it are below just case.

`bin/v-add-sys-filemanager`
`bin/v-change-sys-db-alias`
`bin/v-add-sys-filemanager`

These seems to be a few patches to fix this on compile and update ( see scripts below for `chmod +x *` ), but should be fixed at source.
`src/hst_autocompile.sh`
`bin/v-update-sys-hestia-git`

**Comment by jaapmarcus** [comment]
See commit  https://github.com/hestiacp/hestiacp/commit/93cca65be81aacd6123748fa91b6f1b4c0bed365

How ever when we build the packages the files are made executable by default

We are aware of it

**Comment by vestacp-user** [comment]
Thank you! :)
