### ISSUE TITLE
File Manager installation failed if only PHP-7.4 is installed

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#984]
HestiaCP v1.2.0 on Fresh Debian 10.4

> **Before installing I edited hst-install-debian.sh to remove all PHP versions except PHP-7.4, so I only have PHP7.4 installed.**

After install completes in the Alert box (see screenshot) I see this message:
```
File Manager installation failed! Unable to proceed with installation of File Manager.
Package php7.3-cli is missing from your system. Please check your PHP installation and environment settings.
```
![image](https://user-images.githubusercontent.com/2650395/88233121-bb6e1000-cc94-11ea-8205-b78ba87dec65.png)

So probably the file manager is hard coded to use PHP7.3 ? We should do a check in install script for this to use the default FPM installed if the install.sh was altered.

Thanks

**Comment by jaapmarcus** [comment]
See https://github.com/hestiacp/hestiacp/issues/906#issuecomment-656069319

You can try to disable this code:

https://github.com/hestiacp/hestiacp/blob/b27cc6625a5abb6245d3bcdbd1f1d4db4f7cb6f2/install/deb/filemanager/install-fm.sh#L55-L65

And try it your self how ever at your own risk. (Or install 7.3 tempory)

**Comment by ScIT-Raphael** [comment]
The composer installation routine is not compatible with php 7.4, that's why this validation has been implemented. There isnt anything we can currently change, as soon as the composer installation is working with php7.4, we will overwrite that specific part.
