### ISSUE TITLE
Title / Tooltip on hover for top right icons

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#985]
I think we should have some tooltip showing what icon stands for what action... or atleast a simple "title" of the icon images to show up on hover. That would be certainly helpful for new comers or people coming from VestaCP.

![image](https://user-images.githubusercontent.com/2650395/88233797-c8d7ca00-cc95-11ea-9711-ae1294786dfa.png)

Thanks

**Comment by ghost** [comment]
Fixed in https://github.com/hestiacp/hestiacp/commit/14d87725f792437792b2339e53d450f86d49ad3a, closing issue report.
