### ISSUE TITLE
Passwords stay in history after changing them using the CLI, security risk

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#987]
Passwords stay in the command history when using the CLI, this represents multiple security risks, (eg. they are plain text in memory, in the file system, can be displayed accidentally, can end up on offsite backups, etc.)

Example: 
```
v-change-user-password admin SuperSecretPassword
history
```

There are multiple options to deal with this, please advise if I just missed something obvious, if there is something in the pipeline, or if proposals are welcome on this?

**Comment by Lupul** [comment]
Currently `SuperSecretPassword` can be a path to a temp file file in `/tmp/..` folder, containing the real passwd, the script could be extended to prompt user for a password

**Comment by vestacp-user** [comment]
From a quick look at the code, I do not see any other way to use the script other than with the password as a command line argument.  @Lupul I imagine you mean that it "...*could* be a path to a temp file..."?  Thus no other option exists at the moment in the current version?   For the temp file, it has it's security risks also, see the reference below.

I would suggest the following in order of priority and effort (see list of points below).  I do completely appreciate that there is only very limited ressources avaible on this project.  I can try to contribute some of these changes if there is interest in receiving the pull requests:
1) The script should delete it's entry from the command history.  It can't guaranteed that it is itself the most recent entry, so it should scan the full command history and delete and "v-..." commands that could have the password on the command line.
2) When used interactively, the script should prompt for a password, like all other unix utilities.  Scripts should never have passwords as command arguments
3) All calls from other program and scripts should be changed to pipe passwords instead of using command arguments. 

For those not aware of the seriousness of this issue, a short summary can found in SECURITY CONSIDERATIONS section of `man sshpass`:

> SECURITY CONSIDERATIONS
First and foremost, users of sshpass should realize that ssh's insistance on only getting the password interactively is not without reason. It is close to impossible to securely  store  the  password,  and users  of  sshpass  should consider whether ssh's public key authentication provides the same end-user experience, while involving less hassle and being more secure.

>The -p option should be considered the least secure of all of sshpass's options.  All system users can see  the  password  in the command line with a simple "ps" command. Sshpass makes a minimal attempt to hide the password, but such attempts are doomed to create race conditions without actually solving the problem.  Users  of  sshpass are encouraged to use one of the other password passing techniques, which are all more secure.

>In particular, people writing programs that are meant to communicate the password programatically are encouraged to use an anonymous pipe and pass the pipe's reading end to sshpass using the -d option.

**Comment by Lupul** [comment]
A file path (located under /tmp/* ) as password containing a password is currently supported by that script

**Comment by vestacp-user** [comment]
@Lupul Ok, thank you, it's good to know.  

However, the issues still remain.  To be more concrete about a future solution:

-Password scripts would not acccept passwords as a parameter

-If script is run interactively, prompt for the password.  Interactive can be tested as follows:
`[[ $- == *i* ]] && echo 'Interactive' || echo 'Not interactive'`

-If the script is called by another script or program (non-interactive), the password would be received via a pipe.  The sending program/script must always ensure to send to the pipe without a command argument as this would defeat the purpose.  
eg `echo "$pass" | v-...` is ok in bash since echo is compiled into bash, but not ok if spawning the /usr/bin/echo executable. 

Opsec can work around some of the above issues, eg by not using certain v-commands, but it should be built and coded into all Hestia password operations by default for all users, especially novice ones.

**Comment by ScIT-Raphael** [comment]
Fixed with https://github.com/hestiacp/hestiacp/pull/1005
