### ISSUE TITLE
WebUI: Changing a DNS A record to a CNAME record breaks it

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#988]
Create a new A record on the DNS page
Go back to the same record and change it to a CNAME record and save, the new record is incorrectly saved.
Creating a CNAME record works correctly

The cause is because when creating a CNAME record, the ending period is added automatically on save.  However, when changing an A record to a CNAME, the save does not add the period.

This should be fixed to avoid user problems and confusion.  Either apply the same CNAME save logic on save of a change that is apply on save of a create, or do not permit change and require a delete and re-create.

Two workarounds:
1) Delete the A record and create a new CNAME
2) Ensure that the entry in the value box (domain name or FQDN) has an ending period before saving

**Comment by jaapmarcus** [comment]
Can confirm the issue

**Comment by jaapmarcus** [comment]
You where wrong it was  a bug in v-change-dns-record 

Fixed !

**Comment by ghost** [comment]
Fixed, closing issue.
