### ISSUE TITLE
WebUI: Back in Add DNS Record after create does not go back to the list

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#989]
"Add Record" in the DNS webUI brings a new empty form after creating a new DNS record.  Pressing the back button on the browser returns to the previous empty form.  It should return to the previous list.

As a reference, the behavior works as expected in the "Add Web Domain"

**Comment by jaapmarcus** [comment]
Also applies to "Add Mail Account" in mail section the issue is caused by the javascript:window.history.back(); instead of /list/domain?domain=test.nl

**Comment by jaapmarcus** [comment]
Noticed also that list_search has the same user but probably changing would be more difficult...

https://github.com/hestiacp/hestiacp/search?q=javascript%3Awindow.history.back%28%29%3B&unscoped_q=javascript%3Awindow.history.back%28%29%3B

**Comment by ghost** [comment]
Thanks for the issue report @vestacp-user, the appropriate fix has been merged for inclusion.
