### ISSUE TITLE
WebUI: "Add DNS Record" resets type on input error

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#992]
On a save attempt of "Add DNS Record" with a missing "Record" value, the WebUI resets the Record "Type" to "A" when it throws the error `Field "record" can not be blank.`

For example: Choose "Type" MX, specify an "IP or Value", leave "Record" blank, click "Save".  WebUI resets the Type to "A" but retains the "IP or Value"

A second very minor ethetic issue is that the error returns the field name as "record" with no first caps, but on the screen, the field is named "Record" with first caps.  

A third issue to be discussed is the @ record.  Leaving record blank intuitively means no subdomain specified, thus only reference domain.  Knowing that "@" mean "no value" requires prior technical knowledge, reading the documentation (if it is documented?) or inferring it from existing records if the user is savy enough.  This is not ideal for a UI, thus, one of the following options might be helpfull:
1) start with "@" as a default "Record" entry
or
2) maybe adding "@" by default when saving blank
or
3) Add a short note in the field title indicating that "@" represent "no value"

**Comment by jaapmarcus** [comment]
Point 1: Loosing focus is fixed (after merging pull request that not has been made...)
Point 2: Rework for language strings are on planning in future...

Point 3: Still don't know what is the best option. Probably a combination of 1 and 3?

**Comment by vestacp-user** [comment]
For the "@", putting it by default will probably be the faster and most generally helpful.  If possible and simple in the code, the "@" should be selected when the field gets focus so that when the user types a value in the "Record" field, the "@" ia is always overwritten.  I can't see any situation (create or change) where the user would want to keep the "@" as part of the Record when typing a new value.

Additionally, since both create and change have a FQDN preview, the user will quickly be able to understand how the field works.  

The help note should be as short as possible.  I see there is often an info after a "Field Title" such as "(optional)" or "(Internal)", so maybe "(@ = Blank)".  

Probably best to avoid anything technical such as Origin, Root, etc..., etc. since the user probably just wants to quickly create something like either "example.com" or "mail.example.com"

**Comment by ghost** [comment]
Fix has been merged for inclusion, closing issue.
