### ISSUE TITLE
WebUI: FQDN preview missing on "Edit DNS Record"

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#993]
When changing a DNS record using the "Edit DNS Record" WebUI screen, the FQDN (Fully Qualified Domain Name) preview associated to the "Record" field is missing. 

Example: Changing "Record" mail to mail1 should show a FQDN preview of mail1.example.com while typing.

For reference, when using the "Add DNS Record" screen, the "Record" field FQDN preview is displayed.

**Comment by ghost** [comment]
Fixed, closing issue.
