### ISSUE TITLE
WebUI: File Manager not explicitly logged out when changing users

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#994]
When using the admin "Login as" function of the WebUI to switch to other users, the File Manager is not logged out explicitly.

To reproduce: 
1) Login as admin, click "Login as" on another user, open the File Manager, click around to confirm that the File Manager has rights to the folders and files.
2) Switch users **WITHOUT** using the "Exit to Control Panel" function of the File Manager.  This can be done in many ways.
2a) Have multiple windows open, typical because might have simply done a right-click open in new window/tab.  Switch users on the browser windows that is not on the File Manager.
2b) Pressing broser back button many times.
2c) Using shortcuts/bookmarks that directly navigate to other parts of the WebUI. 
2d) Otherwise typing, modifying, copy/paster, etc. the WebUI url.
3) Open the File Manager again, it will remain on the previous location, but there should be no folders not files visible because the current user does no thave rights.

The user will think that the File Manager messed up or that all the files are deleted.  Ideally, the File Manager should be forced to log out on a change of user in the WebUI "Login as". Additionally, ensuring the the previous current path is reset.

The File Manager works correctly when switching users **IF** the File Manager is closed specifically using the "Exit to Control Panel" function.

**Comment by jaapmarcus** [comment]
```
<?php 
    unset($_SESSION['_sf2_attributes']);
    unset($_SESSION['_sf2_meta']);
?>
```

Both sessions caused the issues will removed due to logging out as extra check
