### ISSUE TITLE
When will all the v-* commands be changed to h-* commands?  :P

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#995]
When will all the v-* commands be renamed to h-* commands?  :P

**Comment by mehargags** [comment]
what is your problem with using v-* ?  it provides good inter-operability for people coming from VestaCP so they don't need to change their scripts or learn h-*

There more productive things to focus

**Comment by jaapmarcus** [comment]
There are currently no advantage with switching command from v-* to h-* as this would mean we need to change over the complete php code base as well.

That are some plans to change the CLI system requiring  in stead the arguments as list make them inter change able. 

v-add-user username password email name 

Change it over to  for example

hestia user add -u username -p pw -e email@email.com -n "Test user"
or 
h-user-add -u username -p pw -e email@email.com -n "Test user"

This would mean some advantages about the current ones for example 
v-add-database-host would normally mean 
v-add-database-host server username password "" "" "" 3306 
Will become 
hestia database-host add --host server1.hostname.com --userame root --password 1234 --port 3306

v-* are still in use for backward compability

**Comment by vestacp-user** [comment]
It was a joke (hence the ":P" in the title) that was also sarcastically saying that the original vestacp will soon be forgotten as Hestia's project activity and progress constrasts starkly with the that of it's ancestor!  

But thank you for your serious responses, they are informative.
