### ISSUE TITLE
Hestia Upgrade resets custom PHPMYAdmin db-alias

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#996]
Just did an apt-upgrade for HestiaCP from v1.1.1 to latest v1.2.0 on Debian 10.4, I noticed the upgrade '**reset**' my custom PHPMyAdmin URL back to default `/phpmyadmin`. 

Would be good if we can preserve that custom setting during upgrade

**Comment by wojsmol** [comment]
Please see first bullet point in [known issues and notes in 1.2.0](https://github.com/hestiacp/hestiacp/blob/main/CHANGELOG.md#known-issues-and-notes) changelog.

**Comment by jaapmarcus** [comment]
It fixed issues with https://github.com/hestiacp/hestiacp/issues/790

https://github.com/hestiacp/hestiacp/blob/main/bin/v-change-sys-db-alias

`v-change-sys-db-alias pma new_alias`
